### ISSUE TITLE
[🐛 Bug]: [Chrome 95] Page is stuck on loading when using Throttling settings on Chrome 95 version 

### ISSUE THREAD

**Issue by zupap** [SeleniumHQ/selenium#10002]
### What happened?

Network operations not working - page is stuck on loading when using Throttling settings on Chrome 95 version 
**Not reproducing on other chrome versions.** 

### How can we reproduce the issue?

```shell
((ChromeDriver)driver).NetworkConditions = ChromeNetConditions(networkProfile);

//function used
        public ChromeNetworkConditions ChromeNetConditions(string profile)
        {
            ChromeNetworkConditions networkConditions = new ChromeNetworkConditions();
            profile = profile.ToLower();
            switch (profile)
            {
                case "2g":
                    networkConditions.Latency = TimeSpan.FromMilliseconds(300);
                    networkConditions.DownloadThroughput = 250 * 1024;
                    networkConditions.UploadThroughput = 50 * 1024;
                    networkConditions.IsOffline = false;
                    break;

                case "3g":
                    networkConditions.Latency = TimeSpan.FromMilliseconds(100);
                    networkConditions.DownloadThroughput = 750 * 1024;
                    networkConditions.UploadThroughput = 250 * 1024;
                    networkConditions.IsOffline = false;
                    break;
                
                default:
                    throw new Exception("There is no Profile name that matching the given parameter");
             }
            return networkConditions;

        }
```

### Relevant log output

```shell
no log output
```

### Operating System

Windows 10

### Selenium version

C# 3.141.0  /  4.0.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 95.0.4638.54

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 95.0.4638.54

**Comment by n2o1988** [comment]
+1 we're seeing a similar behavior since the update to Chrome 95: infinite loading when we throttle the network (in our case we disabled it entirely).

In addition, this ultimately results in the following error for us:
```
WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=95.0.4638.69)
```

We're using the JavaScript `selenium-webdriver` bindings

**Comment by Dor-bl** [comment]
@jimevans you have any idea what can cause this? maybe we should take it with the ChromeDriver team?

**Comment by TeoTN** [comment]
I've started encountering the same issue in JS (might be worth adding `C-nodejs` label as well?)
It started after the latest Chrome update to `95.0.4638.69`. When I manually disable network in devtools and reproduce the testing scenario in the browser it works fine, but when Chrome is controlled by selenium it seems to hang after the first action after the network is disabled.

**Comment by TeoTN** [comment]
I've also managed to confirm in my case the issue doesn't occur on Chrome v94

**Comment by TeoTN** [comment]
@Dor-bl @jimevans 
The issue persists on Google Chrome @ 96.0.4664.45 (with chromedriver@96.0.4664.45) - but it was absent on v94
For context, the issue occurs on first action after network is disabled - when clicking on a button that triggers HTTP request. 

Exact error and stack trace:
```
  BROWSER: Chrome (local)

Caught when clicking on confirm WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=96.0.4664.45)
    at Object.throwDecodedError (/Users/.../node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/Users/.../node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/Users/.../node_modules/selenium-webdriver/lib/http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at thenableWebDriverProxy.execute (/Users/.../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
    at Object.findAndClick (/Users/.../src/utils/utils.js:20:5)
    at Context.<anonymous> (/Users/.../src/tests/[...].js:128:9) {
  name: 'WebDriverError',
  remoteStacktrace: '0   chromedriver                        0x00000001063b3269 __gxx_personality_v0 + 582729\n' +
    '1   chromedriver                        0x000000010633ec33 __gxx_personality_v0 + 106003\n' +
    '2   chromedriver                        0x0000000105efbcdf chromedriver + 171231\n' +
    '3   chromedriver                        0x0000000105ee86a3 chromedriver + 91811\n' +
    '4   chromedriver                        0x0000000105ee8129 chromedriver + 90409\n' +
    '5   chromedriver                        0x0000000105ee7726 chromedriver + 87846\n' +
    '6   chromedriver                        0x0000000105ee675c chromedriver + 83804\n' +
    '7   chromedriver                        0x0000000105ee6b5c chromedriver + 84828\n' +
    '8   chromedriver                        0x0000000105ef43f1 chromedriver + 140273\n' +
    '9   chromedriver                        0x0000000105ef4fa2 chromedriver + 143266\n' +
    '10  chromedriver                        0x0000000105f02b63 chromedriver + 199523\n' +
    '11  chromedriver                        0x0000000105f05c4a chromedriver + 212042\n' +
    '12  chromedriver                        0x0000000105ee6e7e chromedriver + 85630\n' +
    '13  chromedriver                        0x0000000105f0279c chromedriver + 198556\n' +
    '14  chromedriver                        0x0000000105f6187a chromedriver + 587898\n' +
    '15  chromedriver                        0x0000000105f4ec23 chromedriver + 511011\n' +
    '16  chromedriver                        0x0000000105f2475e chromedriver + 337758\n' +
    '17  chromedriver                        0x0000000105f25a95 chromedriver + 342677\n' +
    '18  chromedriver                        0x000000010636f8ab __gxx_personality_v0 + 305803\n' +
    '19  chromedriver                        0x0000000106386863 __gxx_personality_v0 + 399939\n' +
    '20  chromedriver                        0x000000010638bc7f __gxx_personality_v0 + 421471\n' +
    '21  chromedriver                        0x0000000106387bba __gxx_personality_v0 + 404890\n' +
    '22  chromedriver                        0x0000000106363e51 __gxx_personality_v0 + 258097\n' +
    '23  chromedriver                        0x00000001063a3158 __gxx_personality_v0 + 516920\n' +
    '24  chromedriver                        0x00000001063a32e1 __gxx_personality_v0 + 517313\n' +
    '25  chromedriver                        0x00000001063ba6f8 __gxx_personality_v0 + 612568\n' +
    '26  libsystem_pthread.dylib             0x00007fff203fb8fc _pthread_start + 224\n' +
    '27  libsystem_pthread.dylib             0x00007fff203f7443 thread_start + 15\n'
}
```

**Comment by TeoTN** [comment]
The issue also persists on newer versions:
```
(Session info: chrome=97.0.4692.99)
```

**Comment by Joacchim** [comment]
Hello,

We're also observing this issue in the testing code of a web-extension.
That being said, we're not configuring any kind of network throttling, but it's nigh impossible to pass our tests with the chrome-driver and our selenium python binding.
Note, though, that we're testing against third-party websites (supposed to be supported by our web-extension), which may be slow ?

Issue observed with a version 96, 97, and still present on 98 (sorry I didn't take time to provide exact versions).

As a result, our CI times-out, and if we run the test manually and enter pdb upon failure, we can see this kind of stack-trace:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
...
[Custom Test code]
...
    self._driver.get(URL)
../../.virtualenvs/bmc/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:333: in get
    self.execute(Command.GET, {'url': url})
../../.virtualenvs/bmc/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:319: in execute
    response = self.command_executor.execute(driver_command, params)
../../.virtualenvs/bmc/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py:374: in execute
    return self._request(command_info[0], url, body=data)
../../.virtualenvs/bmc/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py:397: in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
../../.virtualenvs/bmc/lib/python3.6/site-packages/urllib3/request.py:80: in request
    method, url, fields=fields, headers=headers, **urlopen_kw
../../.virtualenvs/bmc/lib/python3.6/site-packages/urllib3/request.py:171: in request_encode_body
    return self.urlopen(method, url, **extra_kw)
../../.virtualenvs/bmc/lib/python3.6/site-packages/urllib3/poolmanager.py:330: in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
../../.virtualenvs/bmc/lib/python3.6/site-packages/urllib3/connectionpool.py:672: in urlopen
    chunked=chunked,
../../.virtualenvs/bmc/lib/python3.6/site-packages/urllib3/connectionpool.py:421: in _make_request
    six.raise_from(e, None)
<string>:3: in raise_from
    ???
../../.virtualenvs/bmc/lib/python3.6/site-packages/urllib3/connectionpool.py:416: in _make_request
    httplib_response = conn.getresponse()
/usr/lib/python3.6/http/client.py:1377: in getresponse
    response.begin()
/usr/lib/python3.6/http/client.py:320: in begin
    version, status, reason = self._read_status()
/usr/lib/python3.6/http/client.py:281: in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <socket.SocketIO object at 0x7fcff22c9780>, b = <memory at 0x7fcff2340948>

    def readinto(self, b):
        """Read up to len(b) bytes into the writable buffer *b* and return
        the number of bytes read.  If the socket is non-blocking and no bytes
        are available, None is returned.
    
        If *b* is non-empty, a 0 return value indicates that the connection
        was shutdown at the other end.
        """
        self._checkClosed()
        self._checkReadable()
        if self._timeout_occurred:
            raise OSError("cannot read from timed out object")
        while True:
            try:
>               return self._sock.recv_into(b)
E               KeyboardInterrupt

/usr/lib/python3.6/socket.py:586: KeyboardInterrupt
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

```

**Comment by Dor-bl** [comment]
Hi,
After updating to the below chrome version, seems like issue is resolved. 
![image](https://user-images.githubusercontent.com/59066376/152741669-746c1cab-368d-4b6d-b95b-dd8a444c1b1c.png)
if other can confirm, that will be great.

**Comment by diemol** [comment]
Thank you for letting us know. If other people have this issue after upgrading, we can reopen.

**Comment by Joacchim** [comment]
Given what I've been observing and reported yesterday, I'm still affected by a similar problem on version 98; though it's not related to network throttling.
Should I open a new issue instead ?

**Comment by Dor-bl** [comment]
> Given what I've been observing and reported yesterday, I'm still affected by a similar problem on version 98; though it's not related to network throttling. Should I open a new issue instead ?

@Joacchim this thread is for the network throttling issue. so yes,open a new issue

**Comment by TeoTN** [comment]
Hey @Dor-bl @diemol, could you please kindly reopen the issue? It still occurs with network throttling and was **NOT** fixed:

**Chrome version:** 98.0.4758.80
**chromedriver version:** ChromeDriver 98.0.4758.80 (7f0488e8ba0d8e019187c6325a16c29d9b7f4989-refs/branch-heads/4758@{#972})

### Error thrown:
```
     WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=98.0.4758.80)
      at Object.throwDecodedError (/Users/.../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (/Users/.../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (/Users/.../node_modules/selenium-webdriver/lib/http.js:491:26)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at thenableWebDriverProxy.execute (/Users/.../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.findAndClick (src/utils/utils.js:14:5)
      at Context.<anonymous> (src/tests/[testSuiteName].js:128:7)
```

### Reproducing
The test case looks like follows:
```
await utils.disableNetwork();
// Error is thrown from next line - button makes a request on click
await utils.findAndClick(Locators.BUTTON);
```
where:
```
export function disableNetwork(driver) {
  return driver.setNetworkConditions({ offline: true, latency: 0, throughput: 0 });
}
export function makeFindAndClick(driver) {
  return async locator => {
    const elt = await find(driver, locator, 5000);
    await elt.click();
    return elt;
  };
}
```

When the erroring line is wrapped in try-catch console.log(error), the following is outputted:
```
WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=98.0.4758.80)
    at Object.throwDecodedError (/Users/.../node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/Users/.../node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/Users/.../node_modules/selenium-webdriver/lib/http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at thenableWebDriverProxy.execute (/Users/.../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
    at Object.findAndClick (/Users/.../src/utils/utils.js:14:5)
    at Context.<anonymous> (/Users/.../src/tests/[test-case].js:129:9) {
  name: 'WebDriverError',
  remoteStacktrace: '0   chromedriver                        0x00000001062033c9 chromedriver + 5018569\n' +
    '1   chromedriver                        0x000000010618e333 chromedriver + 4539187\n' +
    '2   chromedriver                        0x0000000105d6393f chromedriver + 170303\n' +
    '3   chromedriver                        0x0000000105d50693 chromedriver + 91795\n' +
    '4   chromedriver                        0x0000000105d50119 chromedriver + 90393\n' +
    '5   chromedriver                        0x0000000105d4f713 chromedriver + 87827\n' +
    '6   chromedriver                        0x0000000105d4e747 chromedriver + 83783\n' +
    '7   chromedriver                        0x0000000105d4eb4c chromedriver + 84812\n' +
    '8   chromedriver                        0x0000000105d5c641 chromedriver + 140865\n' +
    '9   chromedriver                        0x0000000105d5d202 chromedriver + 143874\n' +
    '10  chromedriver                        0x0000000105d6a933 chromedriver + 198963\n' +
    '11  chromedriver                        0x0000000105d6da2a chromedriver + 211498\n' +
    '12  chromedriver                        0x0000000105d4ee6e chromedriver + 85614\n' +
    '13  chromedriver                        0x0000000105d6a56c chromedriver + 197996\n' +
    '14  chromedriver                        0x0000000105dc8a13 chromedriver + 584211\n' +
    '15  chromedriver                        0x0000000105db56d3 chromedriver + 505555\n' +
    '16  chromedriver                        0x0000000105d8b95e chromedriver + 334174\n' +
    '17  chromedriver                        0x0000000105d8c935 chromedriver + 338229\n' +
    '18  chromedriver                        0x00000001061bf1ee chromedriver + 4739566\n' +
    '19  chromedriver                        0x00000001061d8f51 chromedriver + 4845393\n' +
    '20  chromedriver                        0x00000001061de928 chromedriver + 4868392\n' +
    '21  chromedriver                        0x00000001061d9a7a chromedriver + 4848250\n' +
    '22  chromedriver                        0x00000001061b3c31 chromedriver + 4693041\n' +
    '23  chromedriver                        0x00000001061f4978 chromedriver + 4958584\n' +
    '24  chromedriver                        0x00000001061f4b01 chromedriver + 4958977\n' +
    '25  chromedriver                        0x000000010620a795 chromedriver + 5048213\n' +
    '26  libsystem_pthread.dylib             0x00007fff204488fc _pthread_start + 224\n' +
    '27  libsystem_pthread.dylib             0x00007fff20444443 thread_start + 15\n'
```
