### ISSUE TITLE
[🐛 Bug]: Unable to locate xpath element in --headless mode

### ISSUE THREAD

**Issue by NicoCaldo** [SeleniumHQ/selenium#10000]
### What happened?

I have a code that pastes a text inside a text box such as:

```
driver.get("https://quillbot.com/")
text_box = driver.find_element(By.XPATH,"//*[@id=\"inputText\"]")
```

but in --headless mode for some reason it returns 

```
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="inputText"]"}
  (Session info: headless chrome=95.0.4638.54)
```

Everything works great in non-headless mode

### How can we reproduce the issue?

```shell
service = Service('C:\\Users\\nicoc\\PycharmProjects\\WriteAI\\chromedriver.exe')
chrome_options = Options()
chrome_options.add_argument("--headless --window-size=900,1000")
driver = webdriver.Chrome(service=service, options=chrome_options)

driver.get("https://quillbot.com/")
text_box = driver.find_element(By.XPATH,"//*[@id=\"inputText\"]")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:/Users/nicoc/PycharmProjects/WriteAI/main.py", line 173, in <module>
    text_box = driver.find_element(By.XPATH,"//*[@id=\"inputText\"]")
  File "C:\Users\nicoc\PycharmProjects\WriteAI\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\nicoc\PycharmProjects\WriteAI\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\nicoc\PycharmProjects\WriteAI\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="inputText"]"}
  (Session info: headless chrome=95.0.4638.54)
Stacktrace:
Backtrace:
	Ordinal0 [0x0094B9D3+2472403]
	Ordinal0 [0x008E6961+2058593]
	Ordinal0 [0x007F22B8+1057464]
	Ordinal0 [0x0081C68B+1230475]
	Ordinal0 [0x008465B2+1402290]
	Ordinal0 [0x008355CA+1332682]
	Ordinal0 [0x0084495F+1395039]
	Ordinal0 [0x0083545B+1332315]
	Ordinal0 [0x00811FB4+1187764]
	Ordinal0 [0x00812E09+1191433]
	GetHandleVerifier [0x00AD3396+1551078]
	GetHandleVerifier [0x00B7D53A+2247818]
	GetHandleVerifier [0x009D7FBB+521995]
	GetHandleVerifier [0x009D7079+518089]
	Ordinal0 [0x008EBD4D+2080077]
	Ordinal0 [0x008EFC18+2096152]
	Ordinal0 [0x008EFD52+2096466]
	Ordinal0 [0x008F94B1+2135217]
	BaseThreadInitThunk [0x75E9FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77BC7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77BC7A6E+238]
```

### Operating System

Windows 10

### Selenium version

Phyton 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95.0.4638.54

### What are the browser driver(s) and version(s) where you see this issue?

95.0.4638.54

### Are you using Selenium Grid?

No

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
