### ISSUE TITLE
[🐛 Bug]: Not able to define executable path attribute in webdriver.Chrome (selenium==3.141.0)

### ISSUE THREAD

**Issue by rb05751** [SeleniumHQ/selenium#10044]
### What happened?

So when trying to instantiate my browser object using seleniums webdriver module, the `executable_path` attribute that is passed through to `webdriver.Chrome` like this:

`browser = webdriver.Chrome(executable_path=r"C:\path\to\chromedriver\chromedriver.exe")`

Is not being reflected in the WebDriver class. The executable path remains as `chromedriver`, the default. I had to change the source code to my path in order to get this to run with an absolute path to my executable.

### How can we reproduce the issue?

```shell
Download the same version of selenium and Python 3.7.6. Try to pass in the absolute path to your chromedriver.exe and see if the system cannot find the file specified. If so, using your IDE, step into the Chrome portion of webdriver.Chrome, this will take you to the WebDriver class. If you place a debug point in the constructor you will be able to see that the default "chromedriver" value stays as the classes attribute.
```

### Relevant log output

```shell
I do not have a log but I do have the error message: 

Traceback (most recent call last):
  File "C:\Users\rbeas\miniconda3\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\rbeas\miniconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\rbeas\miniconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
  File "C:\Users\rbeas\OneDrive\Documents\Deep Learning Research-DESKTOP-EMK236C\PyCharm Community Edition 2020.1.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 551, in new_CreateProcess
    return getattr(_subprocess, original_name)(app_name, patch_arg_str_win(cmd_line), *args)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Benzinga\scrapie-engine\scrapers\syndicatescraper\scraper.py", line 19, in <module>
    browser = webdriver.Chrome(options=chromeOptions)
  File "C:\Users\rbeas\miniconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\rbeas\miniconda3\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

### Operating System

Windows 10

### Selenium version

3.141.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95.0.4638.69

### What are the browser driver(s) and version(s) where you see this issue?

9ChromeDriver 95.0.4638.69

### Are you using Selenium Grid?

Note using that

**Comment by diemol** [comment]
Please try the most recent version of Selenium and let us know https://pypi.org/project/selenium/4.0.0/

**Comment by diemol** [comment]
Closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.
