### ISSUE TITLE
[🐛 Bug]: input type file, upload error

### ISSUE THREAD

**Issue by nord98d** [SeleniumHQ/selenium#10047]
### What happened?

The file is not loaded via the file type input when using RemoteWebDriver. 
If you use WebDriver and the corresponding browser instead of RemoteWebDriver, then everything works.

### How can we reproduce the issue?

```shell
options = ChromeOptions()
options.binary_location = "GoogleChromePortable/App/Chrome-bin/chrome.exe"

driver = RemoteWebDriver(CHROME_DRIVER_ADDRESS, options=options)

url = ""
driver.get(url)
inp = driver.find_elements(By.TAG_NAME, "input")
print(inp[8].get_attribute("type"))
inp[8].send_keys(os.getcwd() + "\TypeFile.txt")
time.sleep(5)
driver.quit()
# inp[8] - input type file
```

### Relevant log output

```shell
file
Traceback (most recent call last):
  File "C:\Users\dimau\PycharmProjects\webscanner\test.py", line 35, in <module>
    inp[8].send_keys(os.getcwd() + "\TypeFile.txt")
  File "C:\Users\dimau\PycharmProjects\webscanner\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 536, in send_keys
    remote_files.append(self._upload(file))
  File "C:\Users\dimau\PycharmProjects\webscanner\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 768, in _upload
    raise e
  File "C:\Users\dimau\PycharmProjects\webscanner\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 759, in _upload
    return self._execute(Command.UPLOAD_FILE, {'file': content})['value']
  File "C:\Users\dimau\PycharmProjects\webscanner\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 693, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\dimau\PycharmProjects\webscanner\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dimau\PycharmProjects\webscanner\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown command: unknown command: session/7a484bba05eb391ec543922ed6438333/se/file
Stacktrace:
Backtrace:
	Ordinal0 [0x005FD403+2479107]
	Ordinal0 [0x00597D51+2063697]
	Ordinal0 [0x004A20C8+1056968]
	Ordinal0 [0x004E371E+1324830]
	Ordinal0 [0x004E351D+1324317]
	Ordinal0 [0x00484D3F+937279]
	Ordinal0 [0x00485246+938566]
	Ordinal0 [0x00485521+939297]
	GetHandleVerifier [0x0077F3F6+1531734]
	GetHandleVerifier [0x0082E9AE+2249998]
	GetHandleVerifier [0x006839AB+501003]
	GetHandleVerifier [0x00682A29+497033]
	Ordinal0 [0x0059D11D+2085149]
	Ordinal0 [0x00484ADE+936670]
	Ordinal0 [0x004846C0+935616]
	GetHandleVerifier [0x00855E4C+2410924]
	BaseThreadInitThunk [0x75B7FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77277A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77277A6E+238]


Process finished with exit code 1
```

### Operating System

Windows 10

### Selenium version

4.0 Python

### What are the browser(s) and version(s) where you see this issue?

Chrome 93

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 93

**Comment by AutomatedTester** [comment]
You are using `webdriver.Remote` to connect to the driver directly when it's intended for use with a Selenium Grid of sorts.

Please either use the `webdriver.Chrome()` directly and pass through the options and if need be a service class to manage the service for you or need to set [`self._is_remote`](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/webdriver.py#L259) to false after you have instantiate the object.

The way you are using the code for this issue is not how it was intended to be used so hopefully these workarounds help.

**Comment by AutomatedTester** [comment]
If chrome driver is allowing connections from outside a container that is them not following https://w3c.github.io/webdriver/#security which could be seen as a security vulnerability
