### ISSUE TITLE
[🐛 Bug]: Selenium tests sometimes randomly fail because of port already in use

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#10066]
### What happened?

I submitted [another PR](https://github.com/SeleniumHQ/selenium/pull/10063) to Selenium, and [the build failed](https://github.com/SeleniumHQ/selenium/runs/4270614439?check_suite_focus=true) because of a flaky test.

In fact, my own integration tests also fail time-to-time, see [issue 9972](https://github.com/SeleniumHQ/selenium/issues/9972). 

# Proposed solution
I want to retry starting netty server several times if it fails due to "port already in use" exception.

### How can we reproduce the issue?

```shell
It's hard to reproduce.
```

### Relevant log output

```shell
There was 1 failure:
1) testToggleAirplaneMode(org.openqa.selenium.mobile.NetworkConnectionTest)
java.lang.RuntimeException: java.io.UncheckedIOException: java.io.IOException: Port 41538 already in use
	at org.openqa.selenium.environment.GlobalTestEnvironment.getOrCreate(GlobalTestEnvironment.java:44)
	at org.openqa.selenium.testing.JUnit4TestBase.prepareEnvironment(JUnit4TestBase.java:54)
	... 32 trimmed
Caused by: java.io.UncheckedIOException: java.io.IOException: Port 41538 already in use
	at org.openqa.selenium.netty.server.NettyServer.start(NettyServer.java:159)
	at org.openqa.selenium.netty.server.NettyServer.start(NettyServer.java:52)
	at org.openqa.selenium.environment.webserver.NettyAppServer.start(NettyAppServer.java:104)
	at org.openqa.selenium.environment.InProcessTestEnvironment.<init>(InProcessTestEnvironment.java:29)
	at org.openqa.selenium.environment.GlobalTestEnvironment.getOrCreate(GlobalTestEnvironment.java:41)
	... 34 more
Caused by: java.io.IOException: Port 41538 already in use
	... 39 more
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
```

### Operating System

no matter

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

no matter

### What are the browser driver(s) and version(s) where you see this issue?

no matter

### Are you using Selenium Grid?

no matter

**Comment by asolntsev** [comment]
I submitted a pull request that should solve this problem: https://github.com/SeleniumHQ/selenium/pull/10067

**Comment by diemol** [comment]
#10170 addresses this
