### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.WebDriverException: Message: Host header doesn't match server localhost:60955

### ISSUE THREAD

**Issue by DEADF00D** [SeleniumHQ/selenium#10065]
### What happened?

Running the python program give a direct exception:
```
Traceback (most recent call last):
  File "/home/deadf00d/Documents/RedditBot/bot.py", line 3, in <module>
    driver = webdriver.Firefox()
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 180, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 420, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 244, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Host header doesn't match server localhost:60955
```

### How can we reproduce the issue?

```shell
from selenium import webdriver

driver = webdriver.Firefox()
driver.get("https://dev.to")
```

### Relevant log output

```shell
NaN
```

### Operating System

Linux deadf00d 5.14.14-arch1-1 #1 SMP PREEMPT Wed, 20 Oct 2021 21:35:18 +0000 x86_64 GNU/Linux

### Selenium version

Python - Selenium 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 93.0 (64 bit)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.30.0 (d372710b98a6 2021-09-16 10:29 +0300)

### Are you using Selenium Grid?

No (i guess)

**Comment by lodrantl** [comment]
Encountered the same problem on Arch. I don't think it is a Selenium problem but more of a geckodriver problem. I looks like it has something to do with localhost resolving to both IPv6 and IPv4 address while geckodriver is only bound to IPv4.

I found two possible fixes:

1. disable IPv6 completely
2. add the standard localhost config to `/etc/hosts` (no idea why it works)
```
127.0.0.1        localhost
::1              localhost
```

**Comment by DEADF00D** [comment]
It does work indeed !
Thank you very much.
