### ISSUE TITLE
[🐛 Bug]: Selenium 4.0.0: Can't instantiate chromedriver behind corporate proxy

### ISSUE THREAD

**Issue by miguelius** [SeleniumHQ/selenium#10062]
### What happened?

Instantiating chromedriver behind corporate proxy throws an exception while trying to connect to driver port path /session.

### How can we reproduce the issue?

```python
# 1. Setup a proxy and HTTP_PROXY and HTTPS_PROXY variables, and ensure corresponding chromedriver in PATH
# 2. Create virtualenv
# 3. Activate virtualenv
# 4. Install with pip selenium 4.0.0
# 5. Run python interpreter:

from selenium import webdriver

driver = webdriver.Chrome()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/xxxxx/estamos-al-horno/prueba.py", line 12, in <module>
    driver = webdriver.Chrome() # options=chrome_options)
  File "/home/xxxxx/estamos-al-horno/venv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/xxxxx/estamos-al-horno/venv/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/xxxxx/estamos-al-horno/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/xxxxx/estamos-al-horno/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/xxxxx/estamos-al-horno/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/home/xxxxx/estamos-al-horno/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 207, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: <HEAD><TITLE>Request on loopback from external IP</TITLE></HEAD>
```

### Operating System

Windows and Linux

### Selenium version

Python 3.7, 3.8, 3.9, 3.10

### What are the browser(s) and version(s) where you see this issue?

chrome 94

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.61

### Are you using Selenium Grid?

Nope

**Comment by miguelius** [comment]
Adding localhost to no_proxy environment driver solves the issue. This wasnt necessary on release 3.141.0.

**Comment by AutomatedTester** [comment]
We have moved the HTTP client in the 4.0 development cycle. There are a number of default states that were done in the past that were missed. In 4.1 we should have hit all of these fixes. 

If you're using a corporate proxy then they would be following all the different main environmental variables. The `NO_PROXY` should have localhost and is managed with Selenium 4.1 better now.
