### ISSUE TITLE
[🐛 Bug]: AttributeError: 'dict' object has no attribute 'is_displayed'

### ISSUE THREAD

**Issue by Lovelaces** [SeleniumHQ/selenium#10071]
### What happened?

Within the expected_conditions.py support package of selenium python,

`is_displayed()` 

does not appear to be a function of:

`from selenium.webdriver.remote.webdriver import WebElement`

So, when attempting to:
`WebDriverWait(webdriver, 30).until(ec.element_to_be_clickable((By.ID, "username")))`

The following is produced from shell:
> AttributeError: 'dict' object has no attribute 'is_displayed'

I've attached the python file that would reproduce the bug. Please help. Thanks!

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.common.exceptions import WebDriverException, TimeoutException, \
    ElementClickInterceptedException, ElementNotVisibleException, \
    ElementNotInteractableException, NoSuchElementException, UnexpectedAlertPresentException, StaleElementReferenceException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.wait import WebDriverWait

def browser_settings(user_agent):
    """
    Inits the chrome browser with headless setting and user agent
    :param headless_mode: Boolean
    :param user_agent: String
    :return: webdriver obj
    """

    service = Service('drivers/chromedriver')
    options = Options()
    options.add_argument(f'user-agent={user_agent}')
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option('useAutomationExtension', False)
    options.add_experimental_option('w3c', False)

    prefs = {
        "profile.default_content_setting_values.geolocation": 2,
        'profile.default_content_setting_values.notifications': 2,
        'profile.content_settings.exceptions.notifications': 2,
        'profile.default_content_settings.geolocation': 2,
        "profile.managed_default_content_settings.popups": 2,
        "profile.managed_default_content_settings.notifications": 2,
        #"profile.managed_default_content_settings.images": 2,
        #"profile.default_content_settings.images": 2,
        'profile.content_settings.exceptions.geolocation': 2,
        "profile.managed_default_content_settings.infobar": 2,
        'profile.managed_default_content_settings.geolocation': 2,
        'credentials_enable_service': False,
        'profile': {
            'password_manager_enabled': False
        }
    }

    options.add_experimental_option("prefs", prefs)
    chrome_obj = webdriver.Chrome(service=service, options=options)
    return chrome_obj

userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
    

browser = browser_settings(userAgent)
browser.get('https://account.protonmail.com/login')
WebDriverWait(browser, 30).until(ec.element_to_be_clickable((By.ID, "username")))
browser.find_element(By.ID, "username").send_keys("email_address@protonmail.com")
time.sleep(7)
browser.quit()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "Y:\For filing a report.py", line 58, in <module>
    WebDriverWait(browser, 10).until(ec.element_to_be_clickable((By.NAME, "loginfmt")))
  File "C:\Users\Lovelace\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\Lovelace\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 332, in _predicate
    target = visibility_of(target)(driver)
  File "C:\Users\Lovelace\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 143, in _predicate
    return _element_if_visible(element)
  File "C:\Users\Lovelace\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 154, in _element_if_visible
    return element if element.is_displayed() == visibility else False
AttributeError: 'dict' object has no attribute 'is_displayed'
```

### Operating System

Windows 10 Pro 32-bit

### Selenium version

Selenium 4.0.0; Python 3.10.150.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.45

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.45

### Are you using Selenium Grid?

No

**Comment by AutomatedTester** [comment]
You’re passing in options.add_experimental_option('w3c', False) which is causing this. Either remove that or downgrade chrome and selenium.

**Comment by Lovelaces** [comment]
Okay, thanks for letting me know. Do you know if this problem will persist indefinitely in order to be in compliance with W3C?...Or will there be a patch in the future that would make the `options.add_experimental_option('w3c', False)` setting applicable with the aforementioned WebDriverWait command?

**Comment by AutomatedTester** [comment]
The Selenium project is moving to only support W3C moving forward and Chrome have set W3C to be their default and will likely remove it in due course. As mentioned before, you can downgrade if there are things that you rely on. The test you have shown should work without the need for setting `W3C` to `False`

**Comment by jedie** [comment]
> You’re passing in options.add_experimental_option('w3c', False) which is causing this

I have also deactivate "w3c" in the past with the commend: "needed to get browser logs" ... ?!?

EDIT: I tested it now: It's still needed :(

I run this:
```
driver.execute_script("console.log('Foo Bar!');")
driver.get_log("browser")
```

With _W3C==False_ this is in the logs, e.g.: `INFO console-api console-api 2:32 "Foo Bar!"`
It's not in, without it :(

Any work-a-round for this?
