### ISSUE TITLE
[🐛 Bug]: importing webdriver: «File "<frozen importlib._bootstrap_external>", line 1039, in get_data», getAttribute.js FileNotFoundError

### ISSUE THREAD

**Issue by Geremia** [SeleniumHQ/selenium#10083]
### What happened?

Importing `webdriver` with `from selenium import webdriver` produces this error:
```python
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/python3.9/site-packages/selenium/webdriver/remote/getAttribute.js'
```

### How can we reproduce the issue?

```python
from selenium import webdriver
```

### Relevant log output

```shell
>>> from selenium import webdriver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/site-packages/selenium/webdriver/__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "/usr/lib64/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 25, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/usr/lib64/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 42, in <module>
    from .switch_to import SwitchTo
  File "/usr/lib64/python3.9/site-packages/selenium/webdriver/remote/switch_to.py", line 25, in <module>
    from selenium.webdriver.remote.webelement import WebElement
  File "/usr/lib64/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 37, in <module>
    getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
  File "/usr/lib64/python3.9/pkgutil.py", line 639, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/python3.9/site-packages/selenium/webdriver/remote/getAttribute.js'
```

### Operating System

slackware64-current (Linux kernel 5.15.4)

### Selenium version

Python 3.9.9 with Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 91.3.0esr

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

**Comment by AutomatedTester** [comment]
How did you install Selenium?

**Comment by Geremia** [comment]
@AutomatedTester I used [this SlackBuild](https://slackbuilds.org/slackbuilds/14.2/python/selenium/selenium.SlackBuild), patched with:

```patch
26c26
< VERSION=${VERSION:-3.141.0}
---
> VERSION=${VERSION:-4.1.0}
64c64
< cd $PRGNAM-$VERSION
---
> cd $PRGNAM-$PRGNAM-$VERSION/py
83c83
< cp -a README.rst LICENSE CHANGES $PKG/usr/doc/$PRGNAM-$VERSION
---
> cp -a README.rst CHANGES $PKG/usr/doc/$PRGNAM-$VERSION
```

**Comment by AutomatedTester** [comment]
Unfortunately, doing that will never give you a working build of Selenium. Please use bazel with `bazel build //py:selenium-wheel`. If you need a sdist version, I need to work on #9917 soon
