### ISSUE TITLE
[🐛 Bug]: Incognito mode can't open "chrome://settings/"

### ISSUE THREAD

**Issue by Bollie15** [SeleniumHQ/selenium#10104]
### What happened?

Can't open `chrome://settings/` by selenium using `--incognito` argument. However, if remove this argument, it works!
```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
chrome_options = webdriver.ChromeOptions() 
chrome_options.add_argument("--incognito")
# driver = webdriver.Chrome('./chromedriver', options=chrome_options)  # crash!
driver = webdriver.Chrome('./chromedriver')  # work!
try:
    driver.get("chrome://settings/")
    print('Open!')
    driver.execute_script('chrome.settingsPrivate.setDefaultZoom(0.5);')
    print('Done!')
    driver.get('https://www.baidu.com/')
    print('Ok')
except Exception:
    pass
finally:
    driver.close()
```

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
chrome_options = webdriver.ChromeOptions() 
chrome_options.add_argument("--incognito")
driver = webdriver.Chrome('./chromedriver', options=chrome_options)
try:
    driver.get("chrome://settings/")
    print('Open!')
    driver.execute_script('chrome.settingsPrivate.setDefaultZoom(0.5);')
    print('Done!')
    driver.get('https://www.baidu.com/')
    print('Ok')
except Exception:
    pass
finally:
    driver.close()
```

### Relevant log output

```shell
a007@007deMacBook-Pro se测试 % python3 test.py
/Users/a007/se测试/test.py:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('./chromedriver', options=chrome_options)
Open!
Traceback (most recent call last):
  File "/Users/a007/se测试/test.py", line 16, in <module>
    driver.close()
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 937, in close
    self.execute(Command.CLOSE)
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=96.0.4664.55)
Stacktrace:
0   chromedriver                        0x0000000103009408 __gxx_personality_v0 + 543364
1   chromedriver                        0x0000000102f9f138 __gxx_personality_v0 + 108468
2   chromedriver                        0x0000000102b9e6a8 chromedriver + 157352
3   chromedriver                        0x0000000102b8ea9c chromedriver + 92828
4   chromedriver                        0x0000000102b821f4 chromedriver + 41460
5   chromedriver                        0x0000000102bed628 chromedriver + 480808
6   chromedriver                        0x0000000102bc3238 chromedriver + 307768
7   chromedriver                        0x0000000102fccc7c __gxx_personality_v0 + 295672
8   chromedriver                        0x0000000102fe0bd8 __gxx_personality_v0 + 377428
9   chromedriver                        0x0000000102fe52b0 __gxx_personality_v0 + 395564
10  chromedriver                        0x0000000102fe19f8 __gxx_personality_v0 + 381044
11  chromedriver                        0x0000000102fc2754 __gxx_personality_v0 + 253392
12  chromedriver                        0x0000000102ffaa38 __gxx_personality_v0 + 483508
13  chromedriver                        0x0000000102ffabac __gxx_personality_v0 + 483880
14  chromedriver                        0x000000010300ffec __gxx_personality_v0 + 570984
15  libsystem_pthread.dylib             0x0000000187def878 _pthread_start + 320
16  libsystem_pthread.dylib             0x0000000187dea5e0 thread_start +
```

### Operating System

macOS Big Sur

### Selenium version

python selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

93.0.4577.82 (arm64)

### What are the browser driver(s) and version(s) where you see this issue?

97.0.4692.20

**Comment by AutomatedTester** [comment]
This is a chromedriver issue, Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
