### ISSUE TITLE
[🐛 Bug]: "WARNING: Failed to resolve host name" displayed with Selenium 4.1.0 on MacOS.

### ISSUE THREAD

**Issue by wakaleo** [SeleniumHQ/selenium#10111]
### What happened?

When using Selenium 4.1.0 (Chrome 96, MacOS, Serenity BDD 3.1.4) the follow warning appears during test execution:

```
Dec 02, 2021 2:32:43 PM org.openqa.selenium.net.HostIdentifier resolveHostName
WARNING: Failed to resolve host name
java.lang.InterruptedException
        at java.base/java.lang.Object.wait(Native Method)
        at java.base/java.lang.Object.wait(Object.java:472)
        at java.base/java.util.concurrent.TimeUnit.timedWait(TimeUnit.java:408)
        at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:449)
        at org.openqa.selenium.net.HostIdentifier.resolveHostName(HostIdentifier.java:52)
        at org.openqa.selenium.net.HostIdentifier.getHostName(HostIdentifier.java:112)
        at org.openqa.selenium.WebDriverException.getSystemInformation(WebDriverException.java:95)
        at org.openqa.selenium.WebDriverException.createMessage(WebDriverException.java:87)
        at org.openqa.selenium.WebDriverException.getMessage(WebDriverException.java:65)
        at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:397)
        at java.base/java.lang.Throwable.toString(Throwable.java:496)
        at java.base/java.lang.Throwable.<init>(Throwable.java:317)
        at java.base/java.lang.Exception.<init>(Exception.java:103)
        at java.base/java.lang.RuntimeException.<init>(RuntimeException.java:97)
        at java.base/java.util.concurrent.CompletionException.<init>(CompletionException.java:88)
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

This message did not appear in version 4.0.0.

### How can we reproduce the issue?

```shell
https://github.com/serenity-dojo/swaglabs-serenity-cucumber.git 

Run "mvn verify" (problem observed on MacOS).
```

### Relevant log output

```shell
Dec 02, 2021 2:32:43 PM org.openqa.selenium.net.HostIdentifier resolveHostName
WARNING: Failed to resolve host name
java.lang.InterruptedException
        at java.base/java.lang.Object.wait(Native Method)
        at java.base/java.lang.Object.wait(Object.java:472)
        at java.base/java.util.concurrent.TimeUnit.timedWait(TimeUnit.java:408)
        at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:449)
        at org.openqa.selenium.net.HostIdentifier.resolveHostName(HostIdentifier.java:52)
        at org.openqa.selenium.net.HostIdentifier.getHostName(HostIdentifier.java:112)
        at org.openqa.selenium.WebDriverException.getSystemInformation(WebDriverException.java:95)
        at org.openqa.selenium.WebDriverException.createMessage(WebDriverException.java:87)
        at org.openqa.selenium.WebDriverException.getMessage(WebDriverException.java:65)
        at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:397)
        at java.base/java.lang.Throwable.toString(Throwable.java:496)
        at java.base/java.lang.Throwable.<init>(Throwable.java:317)
        at java.base/java.lang.Exception.<init>(Exception.java:103)
        at java.base/java.lang.RuntimeException.<init>(RuntimeException.java:97)
        at java.base/java.util.concurrent.CompletionException.<init>(CompletionException.java:88)
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

-------------------

14:40:34.414 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Using chromedriver 96.0.4664.45 (resolved driver for Chrome 96)
14:40:34.455 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/john/.cache/selenium/chromedriver/mac64/96.0.4664.45/chromedriver
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 63409
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Dec 02, 2021 2:40:38 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Dec 02, 2021 2:40:38 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found exact CDP implementation for version 96
```

### Operating System

macOS

### Selenium version

Java 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.45

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
This has been fixed by #10063 and will be released in the next days.
