### ISSUE TITLE
[🐛 Bug]: Firefox DevTools - java.lang.NullPointerException: (keyExchange|initialPriority) is required

### ISSUE THREAD

**Issue by Wojciech-Kopec** [SeleniumHQ/selenium#10124]
### What happened?

Im trying to implement DevTools support for my tests, i would like to use Network.requestWillBeSent() and Network.responseReceived() 

Using Firefox v94 I'm getting NullPointerExceptions for params:
`RequestWillBeSent -> Request -> java.lang.NullPointerException: initialPriority is required`
`ResponseReceived -> Response -> SecurityDetails ->  java.lang.NullPointerException: keyExchange is required`
Also this below:
`ResponseReceived -> Unable to find matching enum value for Img in class org.openqa.selenium.devtools.v94.network.model.ResourceType`

and all these Exceptions are logged to my console in bulk which just pollutes logs to the point you cannot read anything.

All works out properly with Chrome v96 browser, no Exceptions are logged

Stacktraces attached.

P.S Why are dev tools related classes 'multiplied', what is the reason there got to be same classes in packages v85, v94, v95, v96 ?

 
[selenium4_ResourceType_Unable to find matching enum value for Img.txt](https://github.com/SeleniumHQ/selenium/files/7684609/selenium4_ResourceType_Unable.to.find.matching.enum.value.for.Img.txt)
[Selenium4_initialPriority is required.txt](https://github.com/SeleniumHQ/selenium/files/7684610/Selenium4_initialPriority.is.required.txt)
[Selenium4_keyExchange is required.txt](https://github.com/SeleniumHQ/selenium/files/7684611/Selenium4_keyExchange.is.required.txt)

### How can we reproduce the issue?

```shell
I'm getting there Exceptions using https://www.keycloak.org/ , don't know how this can be reproduced outside of this application
```

### Relevant log output

```shell
Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: Unable to create instance of class org.openqa.selenium.devtools.v94.network.model.RequestWillBeSent
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-3U0IJPO', ip: '10.40.0.90', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:202)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v94.network.model.RequestWillBeSent
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-3U0IJPO', ip: '10.40.0.90', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:296)
	at org.openqa.selenium.devtools.v94.network.Network.lambda$requestWillBeSent$40(Network.java:513)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:266)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:257)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 21 more
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v94.network.model.Request
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-3U0IJPO', ip: '10.40.0.90', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:296)
	at org.openqa.selenium.devtools.v94.network.model.RequestWillBeSent.fromJson(RequestWillBeSent.java:149)
	... 25 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 29 more
Caused by: java.lang.NullPointerException: initialPriority is required
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.openqa.selenium.devtools.v94.network.model.Request.<init>(Request.java:80)
	at org.openqa.selenium.devtools.v94.network.model.Request.fromJson(Request.java:246)
	... 33 more
	at org.openqa.selenium.devtools.v94.network.Network.lambda$responseReceived$43(Network.java:525)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:266)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)




WARNING: Unable to process: {"method":"Network.responseReceived","params":{"requestId":"93587337379934","loaderId":"93587337379934","timestamp":1639048121.082,"type":"Document","response":{"url":"https://asauthservice.dev.fingo.info/auth/admin/E2E-Testing/console/#/realms/E2E-Testing&state=c16aa57f-f43e-40c7-abd4-0b069b8ccae5&session_state=732233c9-a091-43ca-839d-a491420bab58&code=c3516c8e-ec80-46c0-9d80-20428926c1a8.732233c9-a091-43ca-839d-a491420bab58.742b6c2a-2af4-46e0-9e8b-f328c1e6c9a8","status":200,"statusText":"OK","headers":{"cache-control":"no-cache","x-xss-protection":"1; mode=block","x-frame-options":"SAMEORIGIN","referrer-policy":"no-referrer","content-security-policy":"frame-src 'self'; frame-ancestors 'self'; object-src 'none';","date":"Thu, 09 Dec 2021 11:08:41 GMT","x-robots-tag":"none","strict-transport-security":"max-age=31536000; includeSubDomains","x-content-type-options":"nosniff","content-type":"text/html;charset=utf-8","content-length":"7673","content-language":"en"},"mimeType":"text/html","requestHeaders":{"host":"asauthservice.dev.fingo.info","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","accept-language":"pl","accept-encoding":"gzip, deflate, br","connection":"keep-alive","cookie":"1e6ba2f2d871c9ac17b291cb7ad00cda=ca75b31d052dc101b7dec9f224f81006","upgrade-insecure-requests":"1","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"none","sec-fetch-user":"?1"},"remoteIPAddress":"10.10.74.111","remotePort":443,"fromDiskCache":false,"protocol":"http/1.1","securityDetails":{"protocol":"TLS 1.2","subjectName":"*.dev.fingo.info","issuer":"ESET SSL Filter CA","validFrom":1638944279,"validTo":1646720278},"securityState":"unknown"},"frameId":"19"},"sessionId":"d4cc82e3-2e6d-445c-8e67-8154e0880de9"}
org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v94.network.model.ResponseReceived
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-3U0IJPO', ip: '10.40.0.90', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:296)
	at org.openqa.selenium.devtools.v94.network.Network.lambda$responseReceived$43(Network.java:525)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:266)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:257)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 21 more
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v94.network.model.Response
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-3U0IJPO', ip: '10.40.0.90', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:296)
	at org.openqa.selenium.devtools.v94.network.model.ResponseReceived.fromJson(ResponseReceived.java:97)
	... 25 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 29 more
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v94.network.model.SecurityDetails
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-3U0IJPO', ip: '10.40.0.90', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:296)
	at org.openqa.selenium.devtools.v94.network.model.Response.fromJson(Response.java:340)
	... 33 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 37 more
Caused by: java.lang.NullPointerException: keyExchange is required
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.openqa.selenium.devtools.v94.network.model.SecurityDetails.<init>(SecurityDetails.java:39)
	at org.openqa.selenium.devtools.v94.network.model.SecurityDetails.fromJson(SecurityDetails.java:208)
	... 41 more



Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: Unable to create instance of class org.openqa.selenium.devtools.v94.network.model.ResponseReceived
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-3U0IJPO', ip: '10.40.0.90', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:202)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v94.network.model.ResponseReceived
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-3U0IJPO', ip: '10.40.0.90', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:296)
	at org.openqa.selenium.devtools.v94.network.Network.lambda$responseReceived$43(Network.java:525)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:266)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:257)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 21 more
Caused by: org.openqa.selenium.json.JsonException: Unable to find matching enum value for Img in class org.openqa.selenium.devtools.v94.network.model.ResourceType
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-3U0IJPO', ip: '10.40.0.90', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.EnumCoercer.lambda$apply$0(EnumCoercer.java:49)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:296)
	at org.openqa.selenium.devtools.v94.network.model.ResponseReceived.fromJson(ResponseReceived.java:94)
	... 25 more
```

### Operating System

Windows 10

### Selenium version

Java 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 94

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

**Comment by diemol** [comment]
v85 is there because that is the version of CDP Firefox implemements. The others are to match the current versions of Chrome people have around.

**Comment by titusfortner** [comment]
Does this work properly with Firefox when you use v85?

And all of these versioning issues will eventually go away when the BiDi spec gets implemented.

**Comment by Wojciech-Kopec** [comment]
Unfortunately no, setting DevTools packages to v85 does not change this behaviour for Firefox

**Comment by titusfortner** [comment]
Same error/stack trace? What is the code you are using?

**Comment by Wojciech-Kopec** [comment]
[Selenium4_DevTools_Exceptions_RequestWillBeSent_ResponseReceived.txt](https://github.com/SeleniumHQ/selenium/files/7944267/Selenium4_DevTools_Exceptions_RequestWillBeSent_ResponseReceived.txt)

Stacktraces are a little different, probably due to different packages being used (v94 vs v85)
My code seems to not have to do anything with this issue as my Listeners don't do anything special - Exceptions are thrown as soon as Event is called.

As for reproduction I cannot provide any more information - as in first post - these Exception are logged during usage of Keycloak application (https://www.keycloak.org/) in my company's infrastructure, and as User authenticates and leaves Keycloak site, these exceptions are no longer logged.

My code regarding DevTools:
```

public class DevToolsUtils {
    protected static DevTools devTools;
    protected static final ObjectWriter objectWriter = new ObjectMapper().registerModule(new Jdk8Module())
            .disable(SerializationFeature.FAIL_ON_EMPTY_BEANS).writer().withDefaultPrettyPrinter();
    protected static final ThreadLocal<List<RequestWillBeSent>> REQUESTS = ThreadLocal.withInitial(ArrayList::new);
    protected static final Logger logger = LogManager.getLogger(DevToolsUtils.class);

    public static void initDevTools(WebDriver driver) {
        final Optional<DevTools> devToolsOpt = ((HasDevTools) driver).maybeGetDevTools();
        if (devToolsOpt.isPresent()) {
            final DevTools devTools = devToolsOpt.get();
            devTools.createSessionIfThereIsNotOne();
            devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
            devTools.send(Log.enable());
            DevToolsUtils.devTools = devTools;
        }
        logger.error("DevTools initialization failed for this WebDriver");
    }


    /**
     * Requests are collected to List. See captureHTTPResponses for more information
     */
    public static void captureHTTPRequests() {
        //Listen to ALL the requests made by application
        devTools.addListener(Network.requestWillBeSent(),
                entry -> REQUESTS.get().add(entry));
    }

    /**
     * If Response with invalid status is received (>=400), then log this Response along with unresolved collected Requests.
     * If Response has a valid HTTP status - then clear collected Requests
     */
    public static void captureHTTPResponses() {
        //Listen to ALL the responses made by application
        devTools.addListener(Network.responseReceived(),
                entry -> {
                    if (entry.getResponse().getStatus() >= 400) {
                        final String log = String.format("Response received with invalid status\nResponse:\n%s\n\nUnresolved requests:\n%s",
                                toJson(entry), REQUESTS.get().stream().map(DevToolsUtils::toJson).collect(Collectors.joining("\n")));
                        logger.error(log);
                    } else {
                        REQUESTS.get().clear();
                    }
                });
    }

    private static String toJson(Object entry) {
        try {
            return objectWriter.writeValueAsString(entry);
        } catch (JsonProcessingException e) {
            return Throwables.getStackTraceAsString(new RuntimeException(e));
        }
    }

```

**Comment by TamsilAmani** [comment]
I looked into the issue. It persists because Firefox doesn't implement CDP fully. For example in the error,

`ResponseReceived -> Unable to find matching enum value for Img in class org.openqa.selenium.devtools.v94.network.model.ResourceType`

there is no enum for **Img** in ResourceType, (the response returned by firefox). 

This issue is likely to get solved with the implementation of BiDi protocol.

**Comment by diemol** [comment]
>It persists because Firefox doesn't implement CDP fully.

Exactly. The first bits from BiDi will come in the next version of Firefox (101), so this will be eventually supported there. For now, please use the Chromium based browsers. 

Closing this as there is nothing to do on the Selenium code.
