### ISSUE TITLE
[🐛 Bug]: Selenium::WebDriver::Error:: on Chrome headless execution

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [SeleniumHQ/selenium#10143]
### What happened?

Test execution on headless Chrome using Watir v7.1.0 gives Selenium WebDriver exception but works just fine when the same test script is run opening Chrome.

### Additional findings
At my work script when I do `element.click` I get `Selenium::WebDriver::Error::ElementClickInterceptedError: element click intercepted: Element is not clickable at point (-250, 18)` only when on headless.
```
element.present? #=> true
element.obscured? #=> false
element.located? #=> true
```
#### Selenium Log
```
2021-12-10 23:18:41 INFO Selenium -> POST session/17c5881585ba86904574800ef4f3f394/element/4ef1bca4-b638-4ee2-b988-5737329486c4/click
2021-12-10 23:18:42 INFO Selenium <- {"value":{"error":"element click intercepted","message":"element click intercepted: Element is not clickable at point (-250, 18)\n  (Session info: headless chrome=96.0.4664.45)","stacktrace":"Backtrace:\n\tOrdinal0 [0x00C26903+2517251]\n\tOrdinal0 [0x00BBF8E1+2095329]\n\tOrdinal0 [0x00AC2848+1058888]\n\tOrdinal0 [0x00AF3509+1258761]\n\tOrdinal0 [0x00AF1868+1251432]\n\tOrdinal0 [0x00AEFB53+1243987]\n\tOrdinal0 [0x00AEE4A8+1238184]\n\tOrdinal0 [0x00AE4037+1196087]\n\tOrdinal0 [0x00B064D3+1336531]\n\tOrdinal0 [0x00AE3A36+1194550]\n\tOrdinal0 [0x00B065BA+1336762]\n\tOrdinal0 [0x00B15BBF+1399743]\n\tOrdinal0 [0x00B0639B+1336219]\n\tOrdinal0 [0x00AE27A7+1189799]\n\tOrdinal0 [0x00AE3609+1193481]\n\tGetHandleVerifier [0x00DB5904+1577972]\n\tGetHandleVerifier [0x00E60B97+2279047]\n\tGetHandleVerifier [0x00CB6D09+534521]\n\tGetHandleVerifier [0x00CB5DB9+530601]\n\tOrdinal0 [0x00BC4FF9+2117625]\n\tOrdinal0 [0x00BC98A8+2136232]\n\tOrdinal0 [0x00BC99E2+2136546]\n\tOrdinal0 [0x00BD3541+2176321]\n\tBaseThreadInitThunk [0x74D962C4+36]\n\tRtlSubscribeWnfStateChangeNotification [0x77401B69+1081]\n\tRtlSubscribeWnfStateChangeNotification [0x77401B34+1028]\n"}}
Selenium::WebDriver::Error::ElementClickInterceptedError: element click intercepted: Element is not clickable at point (-250, 18)
  (Session info: headless chrome=96.0.4664.45)
from Backtrace:
```

### How can we reproduce the issue?

```shell
# your gemfile
source "https://rubygems.org"

gem 'webdrivers', '~> 5.0.0'
gem 'ffi'
gem 'watir', '~> 7.0.0'

# test.rb
require 'webdrivers'
require 'watir'

@browser = Watir::Browser.new(:chrome, headless: true)
@browser.goto "http://watir.com"
@browser.link(text: 'Nerodia', visible: true).click
@browser.close

# Running test.rb
bundle exec ruby test.rb
```

### Relevant log output

```shell
# Logfile created on 2021-12-13 19:46:25 -0800 by logger.rb/66358
2021-12-13 19:46:27 INFO Selenium -> POST session
2021-12-13 19:46:27 INFO Selenium    >>> http://127.0.0.1:9516/session | {"capabilities":{"alwaysMatch":{"browserName":"chrome","unhandledPromptBehavior":"ignore","goog:chromeOptions":{"args":["--headless","--disable-gpu","--no-sandbox"]}}}}
2021-12-13 19:46:28 INFO Selenium <- {"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"96.0.4664.45","chrome":{"chromedriverVersion":"96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947})","userDataDir":"C:\\Users\\<user>\\AppData\\Local\\Temp\\2\\scoped_dir1588_1126362906"},"goog:chromeOptions":{"debuggerAddress":"localhost:51526"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"ignore","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:virtualAuthenticators":true},"sessionId":"5b6b502e70bd7314227c4386f7c8680e"}}
2021-12-13 19:46:28 INFO Selenium -> POST session/5b6b502e70bd7314227c4386f7c8680e/url
2021-12-13 19:46:28 INFO Selenium    >>> http://127.0.0.1:9516/session/5b6b502e70bd7314227c4386f7c8680e/url | {"url":"http://watir.com"}
2021-12-13 19:46:29 INFO Selenium <- {"value":{"error":"unknown error","message":"unknown error: net::ERR_CONNECTION_RESET\n  (Session info: headless chrome=96.0.4664.45)","stacktrace":"Backtrace:\n\tOrdinal0 [0x00C26903+2517251]\n\tOrdinal0 [0x00BBF8E1+2095329]\n\tOrdinal0 [0x00AC2848+1058888]\n\tOrdinal0 [0x00ABF431+1045553]\n\tOrdinal0 [0x00AB54D9+1004761]\n\tOrdinal0 [0x00AB60E0+1007840]\n\tOrdinal0 [0x00AB572A+1005354]\n\tOrdinal0 [0x00AB4DDA+1002970]\n\tOrdinal0 [0x00AB3F8D+999309]\n\tOrdinal0 [0x00AB4246+1000006]\n\tOrdinal0 [0x00AC3E1A+1064474]\n\tOrdinal0 [0x00B1616D+1401197]\n\tOrdinal0 [0x00B064D3+1336531]\n\tOrdinal0 [0x00B15BBF+1399743]\n\tOrdinal0 [0x00B0639B+1336219]\n\tOrdinal0 [0x00AE27A7+1189799]\n\tOrdinal0 [0x00AE3609+1193481]\n\tGetHandleVerifier [0x00DB5904+1577972]\n\tGetHandleVerifier [0x00E60B97+2279047]\n\tGetHandleVerifier [0x00CB6D09+534521]\n\tGetHandleVerifier [0x00CB5DB9+530601]\n\tOrdinal0 [0x00BC4FF9+2117625]\n\tOrdinal0 [0x00BC98A8+2136232]\n\tOrdinal0 [0x00BC99E2+2136546]\n\tOrdinal0 [0x00BD3541+2176321]\n\tBaseThreadInitThunk [0x74D962C4+36]\n\tRtlSubscribeWnfStateChangeNotification [0x77401B69+1081]\n\tRtlSubscribeWnfStateChangeNotification [0x77401B34+1028]\n"}}
```

### Operating System

Windows 10

### Selenium version

selenium-webdriver (4.1.0)

### Watir version

watir (7.1.0)

### Webdrivers version

webdrivers (5.0.0)

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.45

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.45

**Comment by Ana-tech-ro** [comment]
I'm having the same issue when running tests using headless Chrome.
I use:
 **Java 11** 
Selenium 4.1
ChromeDriver 96.0.4664.45
Windows 10

Is there any workaround? :-s

Thanks in advance1

**Comment by titusfortner** [comment]
One thing to keep in mind with headless is that the dimensions of the window might be different, so things might get placed on top of each other. You can take a screenshot to see what you're working with. I haven't tried to duplicate this issue yet, I'll look later today.

**Comment by titusfortner** [comment]
I can't duplicate this.
```
irb(main):049:0> browser = Watir::Browser.new :chrome, headless: true
=> #<Watir::Browser:0x..f9ad18c4bb99c83b0 url="data:," title="">
irb(main):050:0> browser.goto 'watir.com'
=> "http://watir.com"
irb(main):051:0> element = browser.link(text: 'Nerodia')
=> #<Watir::Anchor: located: false; {:text=>"Nerodia", :tag_name=>"a"}>
irb(main):052:0> element.present?
=> true
irb(main):053:0> element.click
=> nil
irb(main):054:0> browser.title
=> "Nerodia Guides – Watir Project"
irb(main):055:0> 
```

Add this code and see what it you get:
```ruby
Watir.logger.selenium = :debug
@browser.window.size
element = @browser.link(text: 'Nerodia')
elemnt.wd.rect
element.click
```

**Comment by pgundlupetvenkatesh** [comment]
Still fails at `Watir::Browser.new(:chrome, headless: true)`
```ruby
require 'webdrivers'
require 'watir'

Watir.logger.selenium             = :debug
Selenium::WebDriver.logger.output = 'selenium.log'

@browser = Watir::Browser.new(:chrome, headless: true, options: { args: ['--start-maximized'] })

@browser.goto "http://watir.com"

# @browser.link(text: 'Nerodia', visible: true).click
@browser.window.size
element = @browser.link(text: 'Nerodia')
element.wd.rect
element.click

@browser.close
```
```bash
# Logfile created on 2021-12-15 14:41:18 -0800 by logger.rb/66358
2021-12-15 14:41:19 DEBUG Selenium Executing Process ["C:/Users/<user>/.webdrivers/chromedriver
.exe", "--port=9515"]
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2021-12-15 14:41:20 INFO Selenium -> POST session
2021-12-15 14:41:20 INFO Selenium    >>> http://127.0.0.1:9515/session | {"capabilities":{"alwaysMatch":{"browserName":"chrome","unhandledPromptBehavior":"ignore","goog:chromeOptions":{"args":["--headless","--disable-gpu","--no-sandbox"]}}}}
2021-12-15 14:41:20 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby windows)", "Content-Length"=>"168"}
2021-12-15 14:41:20 INFO Selenium <- {"value":{"capabilities":{"acceptInsecureCerts":false,
"browserName":"chrome","browserVersion":"96.0.4664.45","chrome":{"chromedriverVersion":"96.0.4664
.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947})",
"userDataDir":"C:\\Users\\<user>>\\AppData\\Local\\Temp\\2\\scoped_dir24160_1851820248"},
"goog:chromeOptions":{"debuggerAddress":"localhost:55480"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"ignore","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:virtualAuthenticators":true},"sessionId":"37f7d3836f3b8a243c15058fb024062f"}}
2021-12-15 14:41:20 INFO Selenium -> POST session/37f7d3836f3b8a243c15058fb024062f/url
2021-12-15 14:41:20 INFO Selenium    >>> http://127.0.0.1:9515/session/37f7d3836f3b8a243c15058fb024062f/url | {"url":"http://watir.com"}
2021-12-15 14:41:20 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby windows)", "Content-Length"=>"26"}
2021-12-15 14:41:21 INFO Selenium <- {"value":{"error":"unknown error","message":"unknown error: net::ERR_CONNECTION_RESET\n  (Session info: headless chrome=96.0.4664.45)","stacktrace":"Backtrace:\n\tOrdinal0 [0x00F76903+2517251]\n\tOrdinal0 [0x00F0F8E1+2095329]\n\tOrdinal0 [0x00E12848+1058888]\n\tOrdinal0 [0x00E0F431+1045553]\n\tOrdinal0 [0x00E054D9+1004761]\n\tOrdinal0 [0x00E060E0+1007840]\n\tOrdinal0 [0x00E0572A+1005354]\n\tOrdinal0 [0x00E04DDA+1002970]\n\tOrdinal0 [0x00E03F8D+999309]\n\tOrdinal0 [0x00E04246+1000006]\n\tOrdinal0 [0x00E13E1A+1064474]\n\tOrdinal0 [0x00E6616D+1401197]\n\tOrdinal0 [0x00E564D3+1336531]\n\tOrdinal0 [0x00E65BBF+1399743]\n\tOrdinal0 [0x00E5639B+1336219]\n\tOrdinal0 [0x00E327A7+1189799]\n\tOrdinal0 [0x00E33609+1193481]\n\tGetHandleVerifier [0x01105904+1577972]\n\tGetHandleVerifier [0x011B0B97+2279047]\n\tGetHandleVerifier [0x01006D09+534521]\n\tGetHandleVerifier [0x01005DB9+530601]\n\tOrdinal0 [0x00F14FF9+2117625]\n\tOrdinal0 [0x00F198A8+2136232]\n\tOrdinal0 [0x00F199E2+2136546]\n\tOrdinal0 [0x00F23541+2176321]\n\tBaseThreadInitThunk [0x74D962C4+36]\n\tRtlSubscribeWnfStateChangeNotification [0x77401B69+1081]\n\tRtlSubscribeWnfStateChangeNotification [0x77401B34+1028]\n"}}
```
log file -
[selenium.log](https://github.com/SeleniumHQ/selenium/files/7723280/selenium.log)

Didn't work with `--start-maximized` as well. `Watir::Browser.new(:chrome, headless: true, options: args: { ['--start-maximized'] })`

**Comment by titusfortner** [comment]
That time it crashed trying to navigate, which seems weird. Try again, without the arg, I want to see the return values from that code.

**Comment by pgundlupetvenkatesh** [comment]
Without browser `args`
 
### From log file
```batch
# Logfile created on 2021-12-15 17:04:33 -0800 by logger.rb/66358
2021-12-15 17:04:34 DEBUG Selenium Executing Process ["C:/Users/<user>/.webdrivers/chromedriver.exe", "--port=9515"]
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2021-12-15 17:04:35 INFO Selenium -> POST session
2021-12-15 17:04:35 INFO Selenium    >>> http://127.0.0.1:9515/session | {"capabilities":{"alwaysMatch":{"browserName":"chrome","unhandledPromptBehavior":"ignore","goog:chromeOptions":{"args":["--headless","--disable-gpu","--no-sandbox"]}}}}
2021-12-15 17:04:35 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby windows)", "Content-Length"=>"168"}
2021-12-15 17:04:36 INFO Selenium <- {"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"96.0.4664.45","chrome":{"chromedriverVersion":"96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947})","userDataDir":"C:\\Users\\<user>\\AppData\\Local\\Temp\\2\\scoped_dir19192_1301703562"},"goog:chromeOptions":{"debuggerAddress":"localhost:65426"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"ignore","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:virtualAuthenticators":true},"sessionId":"30a1b54eb2746eb061070620972224f7"}}
2021-12-15 17:04:36 INFO Selenium -> POST session/30a1b54eb2746eb061070620972224f7/url
2021-12-15 17:04:36 INFO Selenium    >>> http://127.0.0.1:9515/session/30a1b54eb2746eb061070620972224f7/url | {"url":"http://watir.com"}
2021-12-15 17:04:36 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby windows)", "Content-Length"=>"26"}
2021-12-15 17:04:36 INFO Selenium <- {"value":{"error":"unknown error","message":"unknown error: net::ERR_CONNECTION_RESET\n  (Session info: headless chrome=96.0.4664.45)","stacktrace":"Backtrace:\n\tOrdinal0 [0x00F76903+2517251]\n\tOrdinal0 [0x00F0F8E1+2095329]\n\tOrdinal0 [0x00E12848+1058888]\n\tOrdinal0 [0x00E0F431+1045553]\n\tOrdinal0 [0x00E054D9+1004761]\n\tOrdinal0 [0x00E060E0+1007840]\n\tOrdinal0 [0x00E0572A+1005354]\n\tOrdinal0 [0x00E04DDA+1002970]\n\tOrdinal0 [0x00E03F8D+999309]\n\tOrdinal0 [0x00E04246+1000006]\n\tOrdinal0 [0x00E13E1A+1064474]\n\tOrdinal0 [0x00E6616D+1401197]\n\tOrdinal0 [0x00E564D3+1336531]\n\tOrdinal0 [0x00E65BBF+1399743]\n\tOrdinal0 [0x00E5639B+1336219]\n\tOrdinal0 [0x00E327A7+1189799]\n\tOrdinal0 [0x00E33609+1193481]\n\tGetHandleVerifier [0x01105904+1577972]\n\tGetHandleVerifier [0x011B0B97+2279047]\n\tGetHandleVerifier [0x01006D09+534521]\n\tGetHandleVerifier [0x01005DB9+530601]\n\tOrdinal0 [0x00F14FF9+2117625]\n\tOrdinal0 [0x00F198A8+2136232]\n\tOrdinal0 [0x00F199E2+2136546]\n\tOrdinal0 [0x00F23541+2176321]\n\tBaseThreadInitThunk [0x74D962C4+36]\n\tRtlSubscribeWnfStateChangeNotification [0x77401B69+1081]\n\tRtlSubscribeWnfStateChangeNotification [0x77401B34+1028]\n"}}

```
### From console
```bash
Backtrace:: unknown error: net::ERR_CONNECTION_RESET (Selenium::WebDriver::Error::UnknownError)
  (Session info: headless chrome=96.0.4664.45)
        from    Ordinal0 [0x00F76903+2517251]
        from    Ordinal0 [0x00F0F8E1+2095329]
        from    Ordinal0 [0x00E12848+1058888]
        from    Ordinal0 [0x00E0F431+1045553]
        from    Ordinal0 [0x00E054D9+1004761]
        from    Ordinal0 [0x00E060E0+1007840]
        from    Ordinal0 [0x00E0572A+1005354]
        from    Ordinal0 [0x00E04DDA+1002970]
        from    Ordinal0 [0x00E03F8D+999309]
        from    Ordinal0 [0x00E04246+1000006]
        from    Ordinal0 [0x00E13E1A+1064474]
        from    Ordinal0 [0x00E6616D+1401197]
        from    Ordinal0 [0x00E564D3+1336531]
        from    Ordinal0 [0x00E65BBF+1399743]
        from    Ordinal0 [0x00E5639B+1336219]
        from    Ordinal0 [0x00E327A7+1189799]
        from    Ordinal0 [0x00E33609+1193481]
        from    GetHandleVerifier [0x01105904+1577972]
        from    GetHandleVerifier [0x011B0B97+2279047]
        from    GetHandleVerifier [0x01006D09+534521]
        from    GetHandleVerifier [0x01005DB9+530601]
        from    Ordinal0 [0x00F14FF9+2117625]
        from    Ordinal0 [0x00F198A8+2136232]
        from    Ordinal0 [0x00F199E2+2136546]
        from    Ordinal0 [0x00F23541+2176321]
        from    BaseThreadInitThunk [0x74D962C4+36]
        from    RtlSubscribeWnfStateChangeNotification [0x77401B69+1081]
        from    RtlSubscribeWnfStateChangeNotification [0x77401B34+1028]
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:109:in `request'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-7.0.0/lib/watir/http_client.rb:6:in `request'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:93:in `get'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/navigation.rb:32:in `to'
        from <path_to_ruby_dir>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-7.0.0/lib/watir/navigation.rb:16:in `goto'
        from test.rb:9:in `<main>'
```

**Comment by titusfortner** [comment]
Something on your system or in your network is keeping chromedriver from navigating. I can't reproduce your headless issue, and I can't help debug it when chromedriver crashes. It's possible chromedriver crashing and the original error have the same cause.

**Comment by pgundlupetvenkatesh** [comment]
> Something on your system or in your network is keeping chromedriver from navigating. I can't reproduce your headless issue, and I can't help debug it when chromedriver crashes. It's possible chromedriver crashing and the original error have the same cause.

Okay I have created a bug in ChromeDriver - https://bugs.chromium.org/p/chromedriver/issues/detail?id=3977 and will follow up there. Thanks for checking @titusfortner
