### ISSUE TITLE
Invalid hostname MicrosoftWebDriver

### ISSUE THREAD

**Issue by arsenik** [SeleniumHQ/selenium#1015]
Python can not connect to the Edge driver because of invalid hostname.

selenium-2.47.1
Win10 64bits

```
from selenium import webdriver
d = webdriver.Edge()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 33, in __init__
    self.edge_service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\edge\service.py", line 66, in start
    raise WebDriverException("Can not connect to the EdgeDriver")
selenium.common.exceptions.WebDriverException: Message: Can not connect to the EdgeDriver
```

**Comment by vveliev** [comment]
What's the config for selenium ?

**Comment by arsenik** [comment]
How to I get the config?

**Comment by vveliev** [comment]
How did you start selenium ? Any parameters ? Local/remote ?

**Comment by lukeis** [comment]
I'm reproducing this too right now... with Build 10240

@thejohnjansen

**Comment by arsenik** [comment]
Driver is started locally. Python is using http://localhost:50560/status which is not a valid hostname for the server. http://localhost:50560/status is working fine.

**Comment by lukeis** [comment]
I'll look at doing a point release of python tomorrow for this.

**Comment by arsenik** [comment]
@lukeis did you get a chance to prepare next python point release?

**Comment by lukeis** [comment]
@arsenik not yet... conference wifi was crap, I'll see about doing so today

**Comment by lukeis** [comment]
@arsenik 2.47.2 is in pypi now

**Comment by arsenik** [comment]
@lukeis thanks
I did an update, got selenium-2.47.3 then
```
>>> b = webdriver.Edge()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 43, in __init__
    desired_capabilities=capabilities)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 87, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 141, in start_session
    'desiredCapabilities': desired_capabilities,
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error 
```
