### ISSUE TITLE
[🐛 Bug]: Attempting to get Selenium Standalone working with WebKitGTK browsers and WebKitWebDriver

### ISSUE THREAD

**Issue by jamesmortensen** [SeleniumHQ/selenium#10178]
### What happened?

We run our tests on GitHub Actions in Selenium/Standalone-Chrome container images.  We're looking to experiment with also including WebKitGTK browsers.  I successfully created [WebKitWebDriver-Browser-Images](https://github.com/jamesmortensen/WebKitWebDriver-Browser-Images), a multi-arch container image, which uses Epiphany browser and MiniBrowser, alongside WebKitWebDriver, which also accepts remote connections. I connected WebdriverIO to it using the following capabilities:

```
capabilities: [{
        maxInstances: 1,
        browserName: 'MiniBrowser',
        browserVersion: '2.34.1',
        'webkitgtk:browserOptions': {
            args: [
                '--automation'
            ], // ln -s /usr/lib/`arch`-linux-gnu /usr/lib/linux-gnu
            binary: `/usr/lib/${ARCH}-linux-gnu/webkit2gtk-4.0/MiniBrowser`
        }
    }],
```

We're able to run tests standalone, but I believe if we want to include WebKitGTK browsers in a Selenium Grid, the containers will also need to be running Selenium as a node.

I've experimented with some modifications to the config.toml file in order to see if I can register MiniBrowser via standalone mode, as shown below:

```
# cat ../selenium/config.toml 
[network]
relax-checks = true

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "WebKitGTK"
stereotype = '{"browserName": "WebKitGTK", "browserVersion": "", "platformName": "Linux"}'
max-sessions = 1
webdriver-executable = '/usr/bin/WebKitWebDriver'
```

As you can see, I've included the WebDriver binary location.  However, I get the following exception when trying to launch the Selenium server:

```
Selenium Grid Standalone configuration: 
[network]
relax-checks = true

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "WebKitGTK"
stereotype = '{"browserName": "WebKitGTK", "browserVersion": "", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Standalone...
09:13:45.628 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
09:13:45.652 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
09:13:46.296 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:131)
	at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:203)
	at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
	at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:214)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
	... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: Unable to find matching driver for Capabilities {browserName: WebKitGTK, browserVersion: , platformName: Linux, se:vncEnabled: true}
	at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverConfigs$11(NodeOptions.java:351)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverConfigs$15(NodeOptions.java:350)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverConfigs$16(NodeOptions.java:323)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.openqa.selenium.grid.node.config.NodeOptions.addDriverConfigs(NodeOptions.java:277)
	at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:190)
	at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:76)
	... 22 more

```

The exception error message appears [here in this part of the code](https://github.com/SeleniumHQ/selenium/blob/3a2181467904af9043828cede13e5dc866c1af12/java/src/org/openqa/selenium/grid/node/config/NodeOptions.java#L351) but I'm not sure what's needed to make this work.  Am I using the wrong variation of the name?  "WebKitGTK" vs "webkitgtk2", etc, or does a separate implementation need to be created, similar to ChromeDriver, FirefoxDriver, ChromeOptions, FirefoxOptions, etc?  

Hoping to get a little insight on what I can do to make this work.  Thank you!

### How can we reproduce the issue?

To reproduce the issue, please build the container image from [this GitHub repo](https://github.com/jamesmortensen/WebKitGTK-Selenium-Standalone). This is a minimum reproducible example.  

Once built, run the container, then go to http://localhost:7900 and open a terminal. Alternatively, use docker exec to bash into the container.  

On start of the container, you'll see the exceptions. From within the container shell, you can try other alternative inputs to the config.toml (WebKitGTK, webkitgtk all lowercase, etc).

The variations of capitalization I tried all resulted in the same exception.

To start the selenium server, I'm using the shell script within the container:

```shell
$ /opt/bin/start-selenium-standalone.sh
```

### Relevant log output

```shell
Selenium Grid Standalone configuration: 
[network]
relax-checks = true

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "WebKitGTK"
stereotype = '{"browserName": "WebKitGTK", "browserVersion": "", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Standalone...
09:13:45.628 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
09:13:45.652 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
09:13:46.296 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:131)
	at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:203)
	at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
	at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:214)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
	... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: Unable to find matching driver for Capabilities {browserName: WebKitGTK, browserVersion: , platformName: Linux, se:vncEnabled: true}
	at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverConfigs$11(NodeOptions.java:351)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverConfigs$15(NodeOptions.java:350)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverConfigs$16(NodeOptions.java:323)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.openqa.selenium.grid.node.config.NodeOptions.addDriverConfigs(NodeOptions.java:277)
	at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:190)
	at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:76)
	... 22 more
```

### Operating System

macOS 12.0.1 Apple M1, but running in a Debian 11 ARM/Ubuntu 20.04 x86_64 container image.  I don't think the architecture is relevant as binaries are available for the same version of WebKitGTK and WebKitWebDriver for both x86_64 and ARM64.

By default, the Dockerfile in the repo is built for those on x86_64 architectures, from selenium/node-base:latest.

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Epiphany, MiniBrowser, WebKitGTK 2.34.1

### What are the browser driver(s) and version(s) where you see this issue?

WebKitWebDriver version 2.34.1

### Are you using Selenium Grid?

Not yet, but that's the end goal. I'm starting by just trying to run in standalone mode as that involves the least number of other components.

**Comment by beckietech** [comment]
hi @jamesmortensen, 
Please kindly forgive my presumptuous of writing this question to you. It was because I was using ios-webkit-debug proxy with my debian Stretch, it worked fine until iOS upgraded to iOS 15; so I am looking for something can be replacement and I looked your description, I think maybe you may suggest me if Selenium can be it? Please also don't mind I don't need it co-work with WebkitGTK+ since I am using console only. Thanks in advance.

**Comment by diemol** [comment]
This happens because we do not have a driver implemtation for these browsers, therefore, this is a feature request rather than a bug.

Paths that could be followed from here:
- Implement your own [`SessionFactory`](https://www.selenium.dev/documentation/grid/configuration/cli_options/#node), build the jar and add it to the classpath when starting the Grid. An example is the [`DockerSessionFactory`](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/node/docker/DockerSessionFactory.java).
- Same idea but with a [Node implementation](https://www.selenium.dev/documentation/grid/configuration/cli_options/#node), an example of that is the [`OneShotNode`](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/node/k8s/OneShotNode.java).
- Use the [Docker functionality](https://www.selenium.dev/documentation/grid/configuration/cli_options/#docker) to start those images you have built.

At the moment, it is unlikely that we will implement support for these browsers given their popularity.

I will leave this issue open for a while to receive more comments and feedback.

**Comment by jamesmortensen** [comment]
Thanks for the follow up on this issue.  I'll take a look at the resources you linked.
