### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.interactions.MoveTargetOutOfBoundsException IN FireFox version 95 and 94

### ISSUE THREAD

**Issue by Vipin20th** [SeleniumHQ/selenium#10180]
### What happened?

Browser: Firefox 
Version : 96
I have located an element which is available on bottom of the page so i used "action.moveToElement" method for navigating on that element but i am getting MoveTargetOutOfBoundsException in Firefox and Safari only but in chrome it is working fine.

Logs attached for Firefox and safari Please check below.

### How can we reproduce the issue?

```shell
Just call this method to move on the particular element

Actions action = new Actions(DriverProvider.getInstance().getDriver());
action.moveToElement(moveElement).perform();
```

### Relevant log output

```shell
org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: (341, 1119) is out of bounds of viewport width (1440) and height (730)
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'LTB0224786-MAC.local', ip: 'fe80:0:0:0:182b:f77b:d928:a013%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.11'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [9c5dc7fa-8e40-4047-b149-60dba5364a08, actions {actions=[org.openqa.selenium.interactions.Sequence@14a3d766]}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 95.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20211218203254, moz:debuggerAddress: localhost:64204, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 1183, moz:profile: /var/folders/6m/mz3rjtx11qn..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 20.4.0, proxy: Proxy(), se:cdp: ws://localhost:64204/devtoo..., se:cdpVersion: 85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 9c5dc7fa-8e40-4047-b149-60dba5364a08

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)





org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'LTB0224786-MAC.local', ip: 'fe80:0:0:0:182b:f77b:d928:a013%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.11'
Driver info: org.openqa.selenium.safari.SafariDriver
Command: [E4A6A4DA-58DB-42C3-9FE1-ACC7CAEEBE41, actions {actions=[org.openqa.selenium.interactions.Sequence@5ae79c6]}]
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 14.1, javascriptEnabled: true, platform: MAC, platformName: MAC, safari:automaticInspection: false, safari:automaticProfiling: false, safari:diagnose: false, safari:platformBuildVersion: 20E241, safari:platformVersion: 11.3.1, safari:useSimulator: false, setWindowRect: true, strictFileInteractability: false, webkit:WebRTC: {DisableICECandidateFiltering: false, DisableInsecureMediaCapture: false}}
Session ID: E4A6A4DA-58DB-42C3-9FE1-ACC7CAEEBE41
```

### Operating System

MacBook Pro BigSur 11 with M1 chip

### Selenium version

4.1.1

### What are the browser(s) and version(s) where you see this issue?

FireFox 94,95 and Safari 14.1

### What are the browser driver(s) and version(s) where you see this issue?

i am using webdrivermanager 

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
This is actually a bug in Chrome. Firefox and Safari behavior is correct. 
The spec for `moveTo` actions requires not scrolling to the element, and if the center of the element is outside of the viewport to return the out of bounds error.

In Selenium 4.2 you'll have the ability to scroll to the element before pointing to it.
A workaround in the meantime is to take a screenshot of the element, which will automatically scroll the element into view, before using the `moveTo` method.

This is the bug report for the chromedriver issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3955
