### ISSUE TITLE
[🐛 Bug]: Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.HasAuthentication

### ISSUE THREAD

**Issue by idoly** [SeleniumHQ/selenium#10204]
### What happened?

Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.HasAuthentication
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 19 more

### How can we reproduce the issue?

```shell
public static void main(String[] args) {
	System.setProperty("webdriver.chrome.driver", "D:/plugins/web-driver/chromedriver.exe");
	WebDriver driver = new ChromeDriver();
        driver.get("https://google.com");
        driver.getTitle(); // => "Google"
        WebElement searchBox = driver.findElement(By.name("q"));
        WebElement searchButton = driver.findElement(By.name("btnK"));
        searchBox.sendKeys("Selenium");
        searchButton.click();
        driver.findElement(By.name("q")).getAttribute("value"); // => "Selenium"
        driver.quit();
}
```

### Relevant log output

```shell
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/HasAuthentication
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at xyz.idoly.selenium.SeleniumApplication.main(SeleniumApplication.java:18)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.HasAuthentication
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 19 more
```

### Operating System

win10

### Selenium version

selenium-java-4.1.1

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

selenium-chrome-driver-4.1.1

**Comment by titusfortner** [comment]
There's nothing to reproduce from this code, it doesn't look like it is even getting as far as to execute the code?

Best guess is that you haven't imported the dependencies you need. Are you using maven? What are your imports on this file?

**Comment by idoly** [comment]
> 这段代码没有什么可重现的，看起来它甚至没有执行代码？
> 
> 最好的猜测是您尚未导入所需的依赖项。你在用maven吗？你对这个文件的导入是什么？



> There's nothing to reproduce from this code, it doesn't look like it is even getting as far as to execute the code?
> 
> Best guess is that you haven't imported the dependencies you need. Are you using maven? What are your imports on this file?

**Comment by idoly** [comment]
<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-chrome-driver</artifactId>
			<version>4.1.1</version>
		</dependency>

**Comment by idoly** [comment]
yes,i use maven.
now i know the reason of the mistake,because the library-selenium-java-4,1,1's dependencies are not all updated to the latest
![image](https://user-images.githubusercontent.com/75156737/147807985-8cc74316-2dc9-47bd-8869-29daaeb4e033.png)

**Comment by titusfortner** [comment]
So, selenium-java will pull all of that in for you. If you only specify it, then you only have to manage one version. See what you get here: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/4.1.1
