### ISSUE TITLE
[🐛 Bug]: Grid 4 error: Failed to create Chrome process

### ISSUE THREAD

**Issue by ccarmannt** [SeleniumHQ/selenium#10228]
### What happened?

When attempting to start a test using Selenium Grid 4 that runs in Chrome, the grid hub returns a 500 response to the new session request with a message that says "Failed to create Chrome process".

Tests using Internet Explorer work correctly.

### How can we reproduce the issue?

```shell
`
using System;
using System.Threading;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Remote;

namespace app
{
    public class Program
    {
        public static void Main(string[] args)
        {
            const string server = "host:4444";
            //var capabilities = new InternetExplorerOptions
            //{
            //    PlatformName = "WINDOWS"
            //};
            var capabilities = new ChromeOptions
            {
                PlatformName = "WINDOWS"
            };

            try
            {
                var driver = new RemoteWebDriver(new Uri("http://" + server),
                    capabilities.ToCapabilities(), TimeSpan.FromMinutes(1));
                driver.Navigate().GoToUrl("https://www.msn.com/");
                Thread.Sleep(TimeSpan.FromSeconds(30));
                driver.Quit();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"ERROR: {ex.Message}");
                Console.WriteLine(ex.StackTrace);
            }
        }
    }
}
````
```


### Relevant log output

```shell
System info: host: 'BK38HM2', ip: '10.12.73.121', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_291'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:131)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:65)
	at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)
	at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:314)
	at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

### Operating System

Windows 10

### Selenium version

C# 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96, Internet Explorer 11

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.4500, IEDriver 4.0.0

### Are you using Selenium Grid?

4.1.1

**Comment by diemol** [comment]
How are you starting the Grid? Please share the Grid logs as well.

**Comment by ccarmannt** [comment]
Start hub with `java -jar selenium-server-4.1.1.jar hub --config hub.toml`.
Start nodes with `java -Dwebdriver.ie.driver=Selenium.WebDriver.IEDriver.4.0.0\driver\IEDriverServer.exe -Dwebdriver.chrome.driver=Selenium.WebDriver.ChromeDriver.96.0.4664.4500\driver\win32\chromedriver.exe -Dwebdriver.edge.driver=Selenium.WebDriver.MSEdgeDriver.96.0.1054.26\driver\win32\msedgedriver.exe -jar \SeleniumGrid\4\selenium-server-4.1.1.jar node --config \SeleniumGrid\4\node.toml`.

(hub and nodes are separate machines)

Attached logs and toml configs.

[node.log](https://github.com/SeleniumHQ/selenium/files/7824863/node.log)
[hub.log](https://github.com/SeleniumHQ/selenium/files/7824864/hub.log)
[tomlconfigs.zip](https://github.com/SeleniumHQ/selenium/files/7824870/tomlconfigs.zip)

**Comment by diemol** [comment]
The problem is that you are setting the ChromeDriver path in the `binary` value of `goog:chromeOptions`
```
{\"binary\":\"/source/RCT/Tools/Highlander/Base/packages/Selenium.WebDriver.ChromeDriver.96.0.4664.4500/driver/win32\"}
```

`binary` should be used to set the path of the browser binary itself. To set the path of the browser driver you need to use `webdriver-executable`. See https://www.selenium.dev/documentation/grid/configuration/toml_options/#configuring-and-customising-drivers

**Comment by ccarmannt** [comment]
Confirmed that dropping the "binary" specification from the config allowed this to work.
However, the config for the IE browser was set the same way and yet was working.

**Comment by diemol** [comment]
Because they are different browser drivers with different implementations.
