### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down[🐛 Bug]: 

### ISSUE THREAD

**Issue by programming-paradox** [SeleniumHQ/selenium#10235]
### What happened?

Well i am making a simple python script using selenium to open Instagram and grab an element from the site and close the driver but the driver failed to close. And a strange error was shown I looked up on the internet and there was same error faced by other people. But they wrote that we should driver.quit() instead of driver.close() I did the same but the problem remained the same.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait



driver = webdriver.Edge("msedgedriver.exe")

# Opening instagram
driver.get("https://instagram.com")

WebDriverWait(driver, 15)

login_username = driver.find_element_by_name("username")
print(login_username)
driver.quit()
```

### Relevant log output

```shell
D:\Projects\InstAut\env\Scripts\python.exe D:/Projects/InstAut/main.py
Traceback (most recent call last):
  File "D:/Projects/InstAut/main.py", line 13, in <module>
    login_username = driver.find_element_by_name("username")
  File "D:\Projects\InstAut\env\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "D:\Projects\InstAut\env\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "D:\Projects\InstAut\env\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "D:\Projects\InstAut\env\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"name","selector":"username"}
  (Session info: MicrosoftEdge=97.0.1072.55)
  (Driver info: msedgedriver=97.0.1072.55 (ce3bf3364880558d4945082f4ac36e01fe36716e),platform=Windows NT 10.0.19042 x86_64)

Exception ignored in: <function Service.__del__ at 0x00000171B3CFBEE8>
Traceback (most recent call last):
  File "D:\Projects\InstAut\env\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
  File "D:\Projects\InstAut\env\lib\site-packages\selenium\webdriver\common\service.py", line 139, in stop
  File "D:\Projects\InstAut\env\lib\site-packages\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
```

### Operating System

windows 10

### Selenium version

selenium for python 3.0

### What are the browser(s) and version(s) where you see this issue?

Edge Version 97.0.1072.55

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver Version 97.0.1072.55

**Comment by titusfortner** [comment]
This appears to be a race condition between the driver.quit() stopping the process and the Python ending the session.
It's possible that the Selenium code is not verifying the process is closed after sending the command to do so.

Are you using Selenium 4.1?
Your code example is using methods that have been deprecated.

**Comment by programming-paradox** [comment]
No i am using selenium version 3.0

**Comment by diemol** [comment]
Then please update your Selenium version and report back.

**Comment by programming-paradox** [comment]
Thanks it has solved the error.
