### ISSUE TITLE
[🐛 Bug]: Selenium crash due to JS heap memory full issue in Edge Browser Python

### ISSUE THREAD

**Issue by ahsantfw** [SeleniumHQ/selenium#10245]
### What happened?

I have been downloading some files using selenium and after a certain number of files downloaded from the website, the Edge driver crashes with the error of FATAL Javascript OOM in GC  during deserialization. 

How do I fix this? 

### How can we reproduce the issue?

```shell
Download a large number of files that will keep on storing in a cache of JS Heap
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/aftab.ahsan/Desktop/Bot/main.py", line 229, in <module>
    lock_tbody = locktable.find_element_by_tag_name('tbody')
  File "C:\Users\aftab.ahsan\Anaconda3\envs\resume1\lib\site-packages\selenium\webdriver\remote\webelement.py", line 305, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "C:\Users\aftab.ahsan\Anaconda3\envs\resume1\lib\site-packages\selenium\webdriver\remote\webelement.py", line 659, in find_element
    {"using": by, "value": value})['value']
  File "C:\Users\aftab.ahsan\Anaconda3\envs\resume1\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\aftab.ahsan\Anaconda3\envs\resume1\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\aftab.ahsan\Anaconda3\envs\resume1\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
```

### Operating System

Windows 10

### Selenium version

Selenium = 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge

### What are the browser driver(s) and version(s) where you see this issue?

Web Driver

**Comment by diemol** [comment]
The log does not show anything related to what you mention. Does it work with other browsers? Maybe you can report this to the EdgeDriver team.

Also, there is no clear way that shows how to reproduce this.

**Comment by diemol** [comment]
Closing as we did not get any more information.
