### ISSUE TITLE
[🐛 Bug]:  ProtocolError: ('Connection aborted' with Function Get Element Count 

### ISSUE THREAD

**Issue by eravion** [SeleniumHQ/selenium#10258]
### What happened?

Hello,

Sometime, this function 
Get Element Count      xpath=//*[@id='consent_prompt_submit']

on this URL
https://espaceclient.orange-business.com/

fail with this error
ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

when trying to do the screenshot capture.

In parallel, we are testing the same website with Selenium 2.53 (on 20 scenarios) and the function Get Matching Xpath Count is running perfectly.

Thanks for your help.

### How can we reproduce the issue?

```shell
I cannot reproduce it.
I have 2 tests running 24/7 every 10 minutes.
I have the issue 10/15 time by day.
```

### Relevant log output

```shell
RobotFramework debug trace :  

20220117 12:28:28.614 - INFO - +--- START KEYWORD: SeleniumLibrary.Get Element Count [ xpath=//*[@id='consent_prompt_submit'] ]
20220117 12:28:28.615 - INFO - +---- START KEYWORD: SeleniumLibrary.Capture Page Screenshot [ ]
20220117 12:28:29.011 - INFO - </td></tr><tr><td colspan="3"><a href="selenium-screenshot-1.png"><img src="selenium-screenshot-1.png" width="800px"></a>
20220117 12:28:29.011 - INFO - +---- END KEYWORD: SeleniumLibrary.Capture Page Screenshot (396)
20220117 12:28:29.015 - FAIL - ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
20220117 12:28:29.015 - DEBUG - Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/__init__.py", line 467, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/base/robotlibcore.py", line 102, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/keywords/element.py", line 1020, in get_element_count
    return len(self.find_elements(locator))
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/base/context.py", line 90, in find_elements
    return self.element_finder.find(locator, tag, False, False, parent)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/locators/elementfinder.py", line 72, in find
    elements = strategy(criteria, tag, constraints,
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/locators/elementfinder.py", line 125, in _find_by_xpath
    return self._filter_elements(parent.find_elements_by_xpath(criteria),
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 537, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1273, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 416, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 398, in execute
    return self._request(command_info[0], url, body=data)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 420, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
20220117 12:28:29.015 - INFO - +--- END KEYWORD: SeleniumLibrary.Get Element Count (401)
```

### Operating System

Official Docker running on Debian 11 host 

### Selenium version

4.1.1

### What are the browser(s) and version(s) where you see this issue?

firefox in docker 4.1.1

### What are the browser driver(s) and version(s) where you see this issue?

driver included on docker 4.1.1

### Are you using Selenium Grid?

grid 4.1.1

**Comment by titusfortner** [comment]
Typically this is an issue with an intermittent closing of the connection based on your network access to a site:
https://stackoverflow.com/a/68787239/4072371

Do your grid logs contain any additional information?

**Comment by eravion** [comment]
> Typically this is an issue with an intermittent closing of the connection based on your network access to a site: https://stackoverflow.com/a/68787239/4072371
> 
> Do your grid logs contain any additional information?

Hello,
Thanks for your feedback.
The docker running this test have the same Internet access than the selenium 2.53 vm.
If the network between the node and the website is the issue, we should have it with selenium 2.53 too.
Which is not the case.

Maybe this is linked to the docker itself, we have dedicated vm for selenium 2.53.

I do not have additional information on hub logs, I'll check how to increase log level and enable log rotation.

Could it be an issue between the hub and the node ?

**Comment by titusfortner** [comment]
@diemol do you know of an obvious reason for this from the grid side?

**Comment by diemol** [comment]
What version of the Selenium bindings are you using? We'd need a way to reproduce this and ideally the logs, otherwise we cannot troubleshoot this. 

It is hard to say what is causing this. Seems you are using normally Grid 2.53, and there are tons of changes in Grid 4. You should be using the latest 3.x bindings or ideally version 4.

**Comment by eravion** [comment]
Hello,

I discover the same issue with the Go To function.

When we are running the test, we are opening file:///etc/hostname on the browser to identify the node.
Then we are using Go To to open the web site URL to test.
I have this connection issue once I try to use Go To function.

I'll check this section https://www.selenium.dev/documentation/grid/configuration/cli_options/#logging to increase log level.
Advice are welcome to produce the level of log you are looking for.

Sorry, I don't get your question "Selenium bindings"
We have selenium 4.1.1 hub and nodes running on stand alone docker.
1 vm running one hub, 3 vm running 1 firefox and 1 chrome node each.
And Selenium 2.53 on vm whitout docker.

**Comment by diemol** [comment]
The code you are using to run the tests, uses Selenium, right? Seems like you are using Python. How does your dependencies look like?

**Comment by eravion** [comment]
Not Python, RobotFramework on Redhat.

With this libs : 
/opt/rh/rh-python38/root/usr/bin/python3 -m pip list
Package                        Version  
------------------------------ ---------
Appium-Python-Client           1.3.0    
async-generator                1.10     
attrs                          21.2.0   
certifi                        2021.10.8
cffi                           1.15.0   
charset-normalizer             2.0.7    
cryptography                   35.0.0   
decorator                      5.1.0    
docutils                       0.17.1   
h11                            0.12.0   
idna                           3.3      
kitchen                        1.2.6    
outcome                        1.1.0    
pip                            19.3.1   
pycparser                      2.20     
pyOpenSSL                      21.0.0   
pytest-runner                  5.3.1    
requests                       2.26.0   
robotframework                 4.1.2    
robotframework-appiumlibrary   1.6.3    
robotframework-seleniumlibrary 4.0.0    
selenium                       4.0.0    
setuptools                     41.6.0   
six                            1.16.0   
sniffio                        1.2.0    
sortedcontainers               2.4.0    
trio                           0.19.0   
trio-websocket                 0.9.2    
urllib3                        1.26.7   
wsproto                        1.0.0

**Comment by diemol** [comment]
You are using RobotFramework with SeleniumLibrary, ok.

I am out of ideas. In the end, we need a way to reproduce the issue so we can troubleshoot it properly. This will probably require a Selenium Python script given that we do not maintain RobotFramework/SeleniumLibrary repository. 
Another option is for you to post an issue in the RobotFramework/SeleniumLibrary.

**Comment by eravion** [comment]
Ok, I don't know why we have robotframework-seleniumlibrary 4.0.0
 and not the last version.
I'll fix that and come back to you.

**Comment by eravion** [comment]
Upgrading robotframework-seleniumlibrary and selenium does not fix the issue.
I'll check with RobotFramework team and let you know.
Thks for your help.

**Comment by diemol** [comment]
Ok, if you find a solution after checking with them, please post it here for others who might bump into the same issue.
