### ISSUE TITLE
[🐛 Bug]: imposible getting devtools from a seleniumGrid driver instance (remoteWebDriver)

### ISSUE THREAD

**Issue by JuanManuelCarames** [SeleniumHQ/selenium#10263]
### What happened?

Hi all!
I have the following code for controller creation via a selenium grid instance:

`Controller WebDriver=new RemoteWebDriver(getGridUrl(), options);`

Then I need to get the performance metrics from devTools. but the getDevTools() method is not available for a RemoteDriver instance. Downcasting is not possible.

```
((ChromeDriver)driver).getDevTools();
((ChromiumDriver)driver).getDevTools();
```
Both throw a ClassCastException error.

the local case is not a problem because it is treated as a ChromeDriver and does not need a cast.
`driver=new ChromeDriver(options);`

Would it be possible to add the interface (HasDevTools) as part of RemoteWebDriver?
Thanks

### How can we reproduce the issue?

```shell
just creating a driver through a seleniumGridInstances, and then trying to get the devTools.
```

### Relevant log output

```shell
13:54:04 java.lang.ClassCastException: class org.openqa.selenium.remote.RemoteWebDriver cannot be cast to class org.openqa.selenium.chromium.ChromiumDriver (org.openqa.selenium.remote.RemoteWebDriver and org.openqa.selenium.chromium.ChromiumDriver are in unnamed module of loader 'app')
```

### Operating System

kubuntu 20.04

### Selenium version

selenium-java 4.1.1

### What are the browser(s) and version(s) where you see this issue?

chrome 95

### What are the browser driver(s) and version(s) where you see this issue?

selenium-java 4.1.1

### Are you using Selenium Grid?

yes, v.3.141.59

**Comment by titusfortner** [comment]
You need to use the `Augmenter` class then cast to `HasDevTools` interface.

should be like this:
```
WebDriver augmentedDriver = new Augmenter().augment(driver);
((HasDevTools) augmentedDriver).getDevTools();
```

**Comment by diemol** [comment]
Also, seems you are using Grid 3. `DevTools` only works with Grid 4.

Regarding the question, `HasDevTools` should not be added to `RemoteWebDriver` by default as not all drivers implement `DevTools`.

**Comment by JuanManuelCarames** [comment]
Thank you so much... yes, I'm using GridV3, but I upgraded to V4. 
I will try using Augmenter.

**Comment by JuanManuelCarames** [comment]
here again.
I started the selenium grid docker service with the following docker-compose File
I was getting a connection refused error.  (Connection refused: /172.80.4.3:4444), so y expose the port 4444 for the chrome node, and change the hub port to 4440.
but unfortunately, I'm getting the same error....any idea? 

I checked the cdt url from the hub sessions section.its the same as requested

```
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "4444:4444"
      
  selenium-hub:
    image: selenium/hub:4.1.1-20211217
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4440:4444"
```

the stack trace

Jan 21, 2022 10:52:35 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found exact CDP implementation for version 96
Jan 21, 2022 10:52:35 AM org.openqa.selenium.remote.http.netty.NettyWebSocket lambda$new$0
WARNING: Connection refused: /172.80.4.3:4444
java.net.ConnectException: Connection refused: /172.80.4.3:4444
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)


and the java code
```
	public void performance(String resource) throws URISyntaxException, IOException {

		WebDriver augmentedDriver = new Augmenter().augment(context.driver);  // throwing the exception here!
		DevTools chromeDevTools = ((HasDevTools) augmentedDriver).getDevTools();
		
		chromeDevTools.createSession();
```

Thanks.
