### ISSUE TITLE
[🐛 Bug]: ruby: dangling window handles after a file download in a headless chrome

### ISSUE THREAD

**Issue by jstefek** [SeleniumHQ/selenium#10289]
### What happened?

When I download a file in **headless**  Chrome it spawns a window, which then cannot be interacted with. When I e.g. try to get the url from it, it times out with Net::ReadTimeout exception.

Partial workaround: such window can be at least closed.

There is no problem without the headless mode.

### How can we reproduce the issue?

```shell
require 'selenium/webdriver'


File.write(File.join(__dir__, 'download.html'), <<OUT
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="zipfile.zip" target="_blank">Download Report</a>
</body>
</html>
OUT
)
File.write(File.join(__dir__, 'zipfile.zip'), <<OUT
<empty>
OUT
)

$stdout.sync = true

Selenium::WebDriver.logger.level = :debug
options = Selenium::WebDriver::Chrome::Options.new
options.add_argument("--headless")
options.add_preference('download', { 'prompt_for_download' => false, 'default_directory' => "#{__dir__}/downloads" })

client = Selenium::WebDriver::Remote::Http::Default.new
client.read_timeout = 5
client.open_timeout = 5

begin
  # @type [Chrome::Driver]
  driver = Selenium::WebDriver.for(:chrome, http_client: client,  options: options)
  driver.navigate.to("file://#{__dir__}/download.html")
  puts driver.window_handles.size
  driver.find_element(css: 'a').click
  sleep 1
  puts driver.window_handles.size
  driver.window_handles.each do |h|
    puts "switch to handle: #{h}"
    driver.switch_to.window(h)
    puts driver.current_url
  end
ensure
  driver.close
end
```

### Relevant log output

```shell
2022-01-26 15:42:42 DEBUG Selenium Executing Process ["/usr/local/bin/chromedriver", "--port=9515"]
2022-01-26 15:42:42 DEBUG Selenium polling for socket on ["127.0.0.1", 9515]
Starting ChromeDriver 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2022-01-26 15:42:42 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
2022-01-26 15:42:42 INFO Selenium -> POST session
2022-01-26 15:42:42 INFO Selenium    >>> http://127.0.0.1:9515/session | {"capabilities":{"alwaysMatch":{"browserName":"chrome","goog:chromeOptions":{"args":["--headless"],"prefs":{"download":{"prompt_for_download":false,"default_directory":"/home/jstefek/workspace/selenium-bug/downloads"}}}}}}
2022-01-26 15:42:42 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby linux)", "Content-Length"=>"222"}
2022-01-26 15:42:42 INFO Selenium <- {"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"97.0.4692.99","chrome":{"chromedriverVersion":"97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247})","userDataDir":"/tmp/.com.google.Chrome.Y79Npd"},"goog:chromeOptions":{"debuggerAddress":"localhost:43343"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:virtualAuthenticators":true},"sessionId":"a0c551bcaf05dad5563ed79dfc9da30b"}}
2022-01-26 15:42:42 INFO Selenium -> POST session/a0c551bcaf05dad5563ed79dfc9da30b/url
2022-01-26 15:42:42 INFO Selenium    >>> http://127.0.0.1:9515/session/a0c551bcaf05dad5563ed79dfc9da30b/url | {"url":"file:///home/jstefek/workspace/selenium-bug/download.html"}
2022-01-26 15:42:42 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby linux)", "Content-Length"=>"67"}
2022-01-26 15:42:42 INFO Selenium <- {"value":null}
2022-01-26 15:42:42 INFO Selenium -> GET session/a0c551bcaf05dad5563ed79dfc9da30b/window/handles
2022-01-26 15:42:42 INFO Selenium <- {"value":["CDwindow-DDC4BE669651BB5DE2E903C41D1DB202"]}
1
2022-01-26 15:42:42 INFO Selenium -> POST session/a0c551bcaf05dad5563ed79dfc9da30b/element
2022-01-26 15:42:42 INFO Selenium    >>> http://127.0.0.1:9515/session/a0c551bcaf05dad5563ed79dfc9da30b/element | {"using":"css selector","value":"a"}
2022-01-26 15:42:42 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby linux)", "Content-Length"=>"36"}
2022-01-26 15:42:42 INFO Selenium <- {"value":{"element-6066-11e4-a52e-4f735466cecf":"2f7d2bc6-f65a-46f2-9d99-46b3c83dc6db"}}
2022-01-26 15:42:42 INFO Selenium -> POST session/a0c551bcaf05dad5563ed79dfc9da30b/element/2f7d2bc6-f65a-46f2-9d99-46b3c83dc6db/click
2022-01-26 15:42:42 INFO Selenium <- {"value":null}
2022-01-26 15:42:43 INFO Selenium -> GET session/a0c551bcaf05dad5563ed79dfc9da30b/window/handles
2022-01-26 15:42:43 INFO Selenium <- {"value":["CDwindow-DDC4BE669651BB5DE2E903C41D1DB202","CDwindow-4424994D680D68FBD3B3B5F1EF4E1E3B"]}
2
2022-01-26 15:42:43 INFO Selenium -> GET session/a0c551bcaf05dad5563ed79dfc9da30b/window/handles
2022-01-26 15:42:43 INFO Selenium <- {"value":["CDwindow-DDC4BE669651BB5DE2E903C41D1DB202","CDwindow-4424994D680D68FBD3B3B5F1EF4E1E3B"]}
switch to handle: CDwindow-DDC4BE669651BB5DE2E903C41D1DB202
2022-01-26 15:42:43 INFO Selenium -> POST session/a0c551bcaf05dad5563ed79dfc9da30b/window
2022-01-26 15:42:43 INFO Selenium    >>> http://127.0.0.1:9515/session/a0c551bcaf05dad5563ed79dfc9da30b/window | {"handle":"CDwindow-DDC4BE669651BB5DE2E903C41D1DB202"}
2022-01-26 15:42:43 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby linux)", "Content-Length"=>"54"}
2022-01-26 15:42:43 INFO Selenium <- {"value":null}
2022-01-26 15:42:43 INFO Selenium -> GET session/a0c551bcaf05dad5563ed79dfc9da30b/url
2022-01-26 15:42:43 INFO Selenium <- {"value":"file:///home/jstefek/workspace/selenium-bug/download.html"}
file:///home/jstefek/workspace/selenium-bug/download.html
switch to handle: CDwindow-4424994D680D68FBD3B3B5F1EF4E1E3B
2022-01-26 15:42:43 INFO Selenium -> POST session/a0c551bcaf05dad5563ed79dfc9da30b/window
2022-01-26 15:42:43 INFO Selenium    >>> http://127.0.0.1:9515/session/a0c551bcaf05dad5563ed79dfc9da30b/window | {"handle":"CDwindow-4424994D680D68FBD3B3B5F1EF4E1E3B"}
2022-01-26 15:42:43 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby linux)", "Content-Length"=>"54"}
2022-01-26 15:42:43 INFO Selenium <- {"value":null}
2022-01-26 15:42:43 INFO Selenium -> GET session/a0c551bcaf05dad5563ed79dfc9da30b/url
2022-01-26 15:42:53 INFO Selenium -> DELETE session/a0c551bcaf05dad5563ed79dfc9da30b/window
/home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill': Net::ReadTimeout with #<Socket:(closed)> (Net::ReadTimeout)
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:193:in `readuntil'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:203:in `readline'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http/response.rb:42:in `read_status_line'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http/response.rb:31:in `read_new'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1575:in `block in transport_request'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1566:in `catch'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1566:in `transport_request'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1539:in `request'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:77:in `request'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:194:in `close'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:192:in `close'
	from reproducer.rb:47:in `ensure in <main>'
	from reproducer.rb:47:in `<main>'
/home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill': Net::ReadTimeout with #<Socket:(closed)> (Net::ReadTimeout)
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:193:in `readuntil'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:203:in `readline'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http/response.rb:42:in `read_status_line'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http/response.rb:31:in `read_new'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1575:in `block in transport_request'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1566:in `catch'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1566:in `transport_request'
	from /home/jstefek/.rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1539:in `request'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:77:in `request'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:141:in `url'
	from /home/jstefek/.gem/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:153:in `current_url'
	from reproducer.rb:44:in `block in <main>'
	from reproducer.rb:41:in `each'
	from reproducer.rb:41:in `<main>'
```

### Operating System

Centos 8 stream, Fedora 30

### Selenium version

selenium-webdriver 4.1.0, ruby 3.1

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 97.0.4692.99

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247})

**Comment by titusfortner** [comment]
Selenium is sending the correct command to the driver. It looks like the driver isn't able to parse that schema in headless mode.

**Comment by jstefek** [comment]
issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4011
