### ISSUE TITLE
[🐛 Bug]: [Firefox] UnknownMethodError for CDP methods: Network.getResponseBody, Network.setBlockedURLs

### ISSUE THREAD

**Issue by bimanaev** [SeleniumHQ/selenium#10297]
### What happened?

Unable to perform some CDP methods, for example: Network.getResponseBody, Network.setBlockedURLs

For example Network.getResponseBody is not implemented in Firefox devtools: https://bugzilla.mozilla.org/show_bug.cgi?id=1637062

Why do we have the same implementation for Chrome and Firefox if they have different APIs?

### How can we reproduce the issue?

```shell
RemoteWebDriver driver = new RemoteWebDriver(gridUrl, capabilities);

Field capabilitiesField = RemoteWebDriver.class.getDeclaredField("capabilities");
capabilitiesField.setAccessible(true);

String sessionId = driver.getSessionId().toString();
String devtoolsUrl = String.format("ws://%s:%s/session/%s/se/cdp", gridUrl.getHost(), gridUrl.getPort(), sessionId);

MutableCapabilities mutableCapabilities = (MutableCapabilities) capabilitiesField.get(driver);
mutableCapabilities.setCapability("se:cdp", devtoolsUrl);
mutableCapabilities.setCapability("se:cdpVersion", mutableCapabilities.getBrowserVersion());

driver = (RemoteWebDriver) new Augmenter().augment(driver);

DevTools devTools = ((HasDevTools) driver).getDevTools();
    devTools.createSession();

devTools.send(org.openqa.selenium.devtools.v85.network.Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));

devTools.send(org.openqa.selenium.devtools.v85.network.Network.setBlockedURLs(
        Arrays.asList("*png")));

driver.get("https://ya.ru");
```

### Relevant log output

```shell
{"id":6,"error":{"message":"Network.setBlockedURLs","data":"RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5\nUnknownMethodError@chrome://remote/content/cdp/Error.jsm:112:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:98:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45\n"},"sessionId":"f414ed6b-905f-4b62-b49f-e1b19564b1c7"}
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'MacBook-Pro-Macbook-2.local', ip: 'fe80:0:0:0:14c6:e870:25a7:e52d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_201'
Driver info: driver.version: unknown
org.openqa.selenium.devtools.DevToolsException: {"id":6,"error":{"message":"Network.setBlockedURLs","data":"RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5\nUnknownMethodError@chrome://remote/content/cdp/Error.jsm:112:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:98:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45\n"},"sessionId":"f414ed6b-905f-4b62-b49f-e1b19564b1c7"}
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'MacBook-Pro-Macbook-2.local', ip: 'fe80:0:0:0:14c6:e870:25a7:e52d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_201'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:159)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:70)
	at com.ringcentral.vlt.regression.tests.debug.DebugTests.firefoxDevToolsTest(DebugTests.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.WebDriverException: {"id":6,"error":{"message":"Network.setBlockedURLs","data":"RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5\nUnknownMethodError@chrome://remote/content/cdp/Error.jsm:112:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:98:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45\n"},"sessionId":"f414ed6b-905f-4b62-b49f-e1b19564b1c7"}
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'MacBook-Pro-Macbook-2.local', ip: 'fe80:0:0:0:14c6:e870:25a7:e52d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_201'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:234)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
	... 3 more
```

### Operating System

MacOs Monterey M1

### Selenium version

Java 4.1.1

### What are the browser(s) and version(s) where you see this issue?

Firefox 96.0.2

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

### Are you using Selenium Grid?

4.1.1

**Comment by pujagani** [comment]
Selenium aims in supporting [WebDriver Bidi](https://github.com/w3c/webdriver-bidi). It is a W3C protocol that will be implemented by all browsers eventually but currently, it is in progress and not completed. Meanwhile, Selenium provides APIs to use CDP for the supported browsers (Chromium-based browsers and partially Firefox). Firefox supports CDP only as much as needed for supporting Puppeteer and Playwright. Hence, the CDP implementation in Firefox is incomplete. So wherever possible, we recommend using the BiDi APIs. Refer https://www.selenium.dev/documentation/webdriver/bidirectional/ for details and examples.

**Comment by bimanaev** [comment]
@pujagani 
I didn't find these possibilities in WebDriver BiDi.

Are there any workarounds for the problem described above?

**Comment by titusfortner** [comment]
No, there's no workaround at this time. Firefox does not support this functionality, yet. When BiDi specification is implemented by the browser vendors, Selenium will be able to implement this functionality independent of the vairous chrome dev tools versions.
