### ISSUE TITLE
[🐛 Bug]: Edge is started but not working with standalone server 

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#10299]
### What happened?

The browser is started and will remain open for some seconds, a Exception is raised.

The server logs contains some errors, see logs textbox below.

### How can we reproduce the issue?

```shell
1. Start the server

java -Dwebdriver.gecko.driver=geckodriver.exe -Dwebdriver.edge.driver=msedgedriver.exe -jar selenium-server-4.1.1.jar standalone --port 1234

2. Run this code

       RemoteWebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:1234"), new EdgeOptions());

        driver.navigate().to("https://www.google.de/");

        driver.quit();
```

### Relevant log output

```shell
------------------------------
- Java Output 
------------------------------

Jan. 28, 2022 4:46:10 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFORMATION: Using OpenTelemetry for tracing
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: DevToolsActivePort file doesn't exist
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'CSTRLLE47720226', ip: '53.206.62.157', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.8'
Driver info: driver.version: unknown
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'CSTRLLE47720226', ip: '53.206.62.157', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.8'
Driver info: driver.version: unknown
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'CSTRLLE47720226', ip: '53.206.62.157', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}}]
Capabilities {}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:230)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:151)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at Issue9671.main(Issue9671.java:32)


------------------------------
- Server Output
------------------------------

16:45:55.260 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
16:45:55.267 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:46:02.306 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
16:46:02.308 WARN [NodeOptions.getSessionFactories] - Overriding max recommended number of 8 concurrent sessions. Session stability and reliability might suffer!
16:46:02.309 WARN [NodeOptions.getSessionFactories] - One browser session is recommended per available processor. Safari is always limited to 1 session per host.
16:46:02.310 WARN [NodeOptions.getSessionFactories] - Overriding this value for Internet Explorer is not recommended. Issues related to parallel testing with Internet Explored won't be accepted.
16:46:02.310 WARN [NodeOptions.getSessionFactories] - Double check if enabling 'override-max-sessions' is really needed
16:46:02.310 WARN [NodeOptions.getSessionFactories] - Max sessions set to 128
16:46:02.351 INFO [NodeOptions.discoverDrivers] - Discovered 2 driver(s)
16:46:02.395 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 128 times
16:46:02.397 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge"} 128 times
16:46:03.373 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
16:46:03.399 INFO [LocalDistributor.add] - Added node db314629-f4ef-4129-8fe8-cf2052cc88d0 at http://192.168.1.25:1234. Health check every 120s
16:46:03.400 INFO [GridModel.setAvailability] - Switching node db314629-f4ef-4129-8fe8-cf2052cc88d0 (uri: http://192.168.1.25:1234) from DOWN to UP
16:46:06.612 INFO [Standalone.execute] - Started Selenium Standalone 4.1.1 (revision e8fcc2cecf): http://192.168.1.25:1234
16:46:17.343 INFO [LocalDistributor.newSession] - Session request received by the distributor:
 [Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}]
Starting MSEdgeDriver 97.0.1072.55 (ce3bf3364880558d4945082f4ac36e01fe36716e) on port 59223
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
16:47:20.889 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "959917a2efdc9d3b23f18bedcb93556a","eventTime": 1643384840318688700,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:59223","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: DevToolsActivePort file doesn't exist\nBuild info: version: '4.1.1', revision: 'e8fcc2cecf'\nSystem info: host: 'mybox', ip: '192.168.1.25', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.8'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: DevToolsActivePort file doesn't exist\nBuild info: version: '4.1.1', revision: 'e8fcc2cecf'\nSystem info: host: 'mybox', ip: '192.168.1.25', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.8'\nDriver info: driver.version: unknown\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)\r\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:131)\r\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:65)\r\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)\r\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:314)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:513)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:440)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:648)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:612)\r\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:834)\r\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"browserName\": \"MicrosoftEdge\",\"ms:edgeOptions\": {\"args\": [  ],  \"extensions\": [    ]    }    }\n"}}

16:47:20.899 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "959917a2efdc9d3b23f18bedcb93556a","eventTime": 1643384840898789500,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "127.0.0.1:1234","http.method": "POST","http.request_content_length": "371","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.1.1 (java windows)"}}
```

### Operating System

Windows 10 x64

### Selenium version

Java 4.1.1

### What are the browser(s) and version(s) where you see this issue?

Edge x86 97.0.1072.55

### What are the browser driver(s) and version(s) where you see this issue?

msedgedriver.exe 97.0.1072.55

### Are you using Selenium Grid?

selenium-server-4.1.1.jar

**Comment by joerg1985** [comment]
Running via this code does not work either:
```
        System.setProperty("webdriver.edge.driver", "repository\\msedgedriver.exe");

        EdgeDriver driver = new EdgeDriver();
```

The only difference is the logs do not contain any details about the error:
```
Starting MSEdgeDriver 97.0.1072.55 (ce3bf3364880558d4945082f4ac36e01fe36716e) on port 65524
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: DevToolsActivePort file doesn't exist
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'mybox', ip: '192.168.1.25', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:230)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:151)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:49)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:41)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:38)
	at Issue9671.main(Issue9671.java:34)
```

**Comment by diemol** [comment]
The Grid log and the command to start the Grid do not match, the log shows that you are overwriting max sessions and that is not present in the command used to start the Grid.

Can you please share the complete command?

Also, does this happen with the same code in a different machine?

**Comment by joerg1985** [comment]
@diemol thanks for looking into this, i also had a look and could identify the issue, without getting new logs.

For documentation:
There is a relative new Edge group policy [`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\RemoteDebuggingAllowed` ](https://chromium.googlesource.com/chromium/src/+/fa2ade36bf40fc0063a8cb59cd450135eb9b301f)

This must haven been set by someone in my company, this will lead to the logged error message.
`Response code 500. Message: unknown error: DevToolsActivePort file doesn't exist`

Disabling the `RemoteDebuggingAllowed` GPO will fix the startup issue.


Update: i created a chromedriver issue [here](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4014)
