### ISSUE TITLE
[🐛 Bug]: Regression in selenium 4.1.2 with NoSuchMethodError on ImmutableMap.of

### ISSUE THREAD

**Issue by henrik242** [SeleniumHQ/selenium#10324]
### What happened?

Upon updating from Selenium 4.1.1 to 4.1.2 I got this stacktrace with 
```
java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'
	at org.openqa.selenium.chrome.AddHasCasting.getAdditionalCommands(AddHasCasting.java:38)
```

Reverting back to 4.1.1 fixes the issue.  `ImmutableMap.of()` can only take 5 arguments, here it asks for 10.  _(**EDIT**: `of` can take 10 args, but AddHasCasting.java ask for 12)_

Someone else also noticed the same thing, see https://stackoverflow.com/a/70969932/13365 (last part)

### How can we reproduce the issue?

```shell
This is a huge project, so I haven't got a snippet yet.
```

### Relevant log output

```shell
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [no.example.config.ModuleTestConfig$$EnhancerBySpringCGLIB$$9a335649]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'
	at app//org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at app//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
	... 101 more
Caused by: java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'
	at org.openqa.selenium.chrome.AddHasCasting.getAdditionalCommands(AddHasCasting.java:38)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.getExtraCommands(ChromeDriver.java:123)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.<init>(ChromeDriver.java:118)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:93)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
	at no.example.webdriver.WebDriverSelector.createChromeDriver(WebDriverSelector.kt:137)
	at no.example.webdriver.WebDriverSelector.createWebDriverFor(WebDriverSelector.kt:142)
	at no.example.webdriver.WebDriverSelector.getDriver(WebDriverSelector.kt:95)
	at no.example.config.LmsModuleTestConfig.<init>(ModuleTestConfig.java:26)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 103 more
```

### Operating System

macOS 12.1, Ubuntu 20.04

### Selenium version

Java 4.1.2

### What are the browser(s) and version(s) where you see this issue?

ChromeDriver 83.0.4103.14

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 83.0.4103.14

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
The same error was mentioned yesterday in Slack, probably you have Guava as a dependency in your project? Please double check.

Text from Slack:
>I could finally get rid of the error.
I have a Guava dependency on my project that was with the version 30.0.1-jre, which seems not to have the signature used in the method call ImmutableMap.of() used in org.openqa.selenium.chrome.AddHasCasting#getAdditionalCommands .
It seems the
I upgraded Guava to version 30.1.1-jre and the error did not happen anymore.
It may happen to more people, I believe.

Then, @asolntsev shared this link that can help you debug it https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

Please join our [Slack/IRC](https://www.selenium.dev/support/#ChatRoom) channel if you need more help.

**Comment by henrik242** [comment]
@diemol Hmm, `gradle dependencies` only shows 30.1.1-jre.  I'll need to investigate further, I guess.

```
$ gradle dependencies | grep guava | sed 's/[ |*+)(\\]//g' |sort -u
---com.google.guava:failureaccess:1.0.1
---com.google.guava:guava:16.0->30.1.1-jre
---com.google.guava:guava:28.2-jre->30.1.1-jre
---com.google.guava:guava:30.0-android->30.1.1-jre
---com.google.guava:guava:30.1.1-jre
---com.google.guava:guava:31.0.1-jre->30.1.1-jre
---com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
```

**Comment by henrik242** [comment]
@diemol  Found it! In my exception it fails with a `ImmutableMap.of` with *12* parameters:

```
java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(
  java.lang.Object, java.lang.Object, 
  java.lang.Object, java.lang.Object, 
  java.lang.Object, java.lang.Object, 
  java.lang.Object, java.lang.Object, 
  java.lang.Object, java.lang.Object, 
  java.lang.Object, java.lang.Object)'
```
Guava [only supports 10](https://guava.dev/releases/30.1.1-jre/api/docs/com/google/common/collect/ImmutableMap.html#of(K,V,K,V,K,V,K,V,K,V))

**Comment by diemol** [comment]
But Selenium 4.1.2 is using 31.0.1
https://github.com/SeleniumHQ/selenium/blob/b07eb4b59a6c06c9a45720bdff453c61497d35cc/java/maven_deps.bzl#L21
https://guava.dev/releases/31.0.1-jre/api/docs/com/google/common/collect/ImmutableMap.html#of(K,V,K,V,K,V,K,V,K,V,K,V)

**Comment by henrik242** [comment]
@diemol Wow, I must be blind. Thanks for your patience!  I was fooled by the comment above, I guess: 

>  I upgraded Guava to version 30.1.1-jre and the error did not happen anymore.

**Comment by gauravkhuraana** [comment]
This problem has started coming recently to many users and they are clueless with latest libraries

https://stackoverflow.com/a/70969932/2986279
