### ISSUE TITLE
Unable to run chrome headless - java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)Lorg/openqa/selenium/chrome/ChromeOptions;

### ISSUE THREAD

**Issue by namrathaPhenoTips** [SeleniumHQ/selenium#10340]
### What happened?

I am trying to run my tests in chrome headless mode, Using Chrome-Selenium-EclipseIDE- MacOS
<img width="809" alt="Screen Shot 2022-02-08 at 10 30 00 AM" src="https://user-images.githubusercontent.com/73238107/153038044-62e1a298-64cd-4261-a36b-fdbb960da7be.png">
<img width="539" alt="Screen Shot 2022-02-08 at 10 31 12 AM" src="https://user-images.githubusercontent.com/73238107/153038072-a1ef3c19-9c9d-4093-b783-10a900629ca4.png">

### How can we reproduce the issue?

```shell
I don't see the issue while I run my individual cucumber feature files, but when I am running the test runner or through maven when the browser is set as headless it fails.

My POM.XML

<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.0.0</version>
		</dependency>

		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>4.4.3</version>
		</dependency>

		<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber6-adapter</artifactId>
			<version>2.8.4</version>
			<scope>test</scope>
		</dependency>

<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.version}</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven.surefire.version}</version>
				<configuration>
					<includes>
						<include>*Runner.java</include>
					</includes>
				</configuration>
			</plugin>
```

### Relevant log output

```shell
org.opentest4j.MultipleFailuresError: Multiple Failures (3 failures)
	org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)Lorg/openqa/selenium/chrome/ChromeOptions;
	<no message> in java.lang.NullPointerException
	<no message> in java.lang.NullPointerException
	at org.junit.vintage.engine.execution.TestRun.getStoredResultOrSuccessful(TestRun.java:166)
	at org.junit.vintage.engine.execution.RunListenerAdapter.fireExecutionFinished(RunListenerAdapter.java:202)
	at org.junit.vintage.engine.execution.RunListenerAdapter.testFinished(RunListenerAdapter.java:160)
	at org.junit.vintage.engine.execution.RunListenerAdapter.testFinished(RunListenerAdapter.java:76)
	at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:87)
	at org.junit.runner.notification.RunNotifier$9.notifyListener(RunNotifier.java:225)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:222)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:140)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:199)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:90)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:234)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:39)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:79)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:70)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:100)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

### Operating System

macOS Catalina 10.15.7 (19H2)

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome - headless 

### What are the browser driver(s) and version(s) where you see this issue?

I am using WebdriverManager 

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
I can't reproduce this error. 

You can try updating to the latest version of Selenium.

Also because the driver wasn't started, the things you are doing in your after hook are throwing exceptions which is hiding the error/stack trace we need to see. Can you put in a conditional in the afterhook not to use the driver if it is null?

**Comment by namrathaPhenoTips** [comment]
Hi @titusfortner , I tried adding selenium dependency to 4.1.0, it didn't work. I am assuming the issue is from my hooks like you said? I have attached it here, I can think of taking a screenshot while the error hook failing, but is there anything else I should do here. And also, running the individual cucumber feature files in headless files works fine. 
<img width="843" alt="Screen Shot 2022-02-08 at 9 03 30 PM" src="https://user-images.githubusercontent.com/73238107/153107922-c7bf1137-8001-460c-9362-d7cb2afdb256.png">

**Comment by asolntsev** [comment]
@namrathaPhenoTips Why you are reporting `NoSuchMethodError`, though no such exception is visible on your screenshots? I see only several `NullPointerException`s in your screenshots.

Anyway, if you really get `NoSuchMethodError`, it can only happen because you have non-matching versions of Selenium jars in your classpath. Please run `mvn dependency:tree` and you will see the versions.

**Comment by titusfortner** [comment]
If you wrap your after hook methods with `if (driver != null)` conditionals, then it won't hide the full error/stacktrace of the failure in the before hook

**Comment by namrathaPhenoTips** [comment]
I am not getting any other error when adding the above condition, could this be related to this - https://github.com/SeleniumHQ/selenium/issues/4839

and I have mentioned "No suchMethod Error" because the console shows me that - `java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)Lorg/openqa/selenium/chrome/ChromeOptions;`. 
<img width="908" alt="Screen Shot 2022-02-13 at 10 49 11 PM" src="https://user-images.githubusercontent.com/73238107/153797083-f39a08c4-c984-49e0-a65b-ef6ed6c94dff.png">

**Comment by asolntsev** [comment]
@namrathaPhenoTips you have a dependency conflict. See 

https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

There is nothing to fix on Selenium side.

**Comment by titusfortner** [comment]
Let us know if you have any issues fixing dependencies
