### ISSUE TITLE
[🐛 Bug]: [Chrome 95+] Error occurring when using throttling settings in Chrome 95 and above

### ISSUE THREAD

**Issue by TeoTN** [SeleniumHQ/selenium#10372]
### What happened?

Creating this one since #10002 was closed prematurely and haven't been re-opened despite my reports of the issues persisting.

**Chrome version:** 
  * 95.0.4638.69
  * 96.0.4664.45
  * 97.0.4692.99
  * 98.0.4758.80

**chromedriver versions:** 
* 95.0.4638.69
* 96.0.4664.45
* 97.0.4692.99
* ChromeDriver 98.0.4758.80 (7f0488e8ba0d8e019187c6325a16c29d9b7f4989-refs/branch-heads/4758@{#972})

### Error thrown:
```
     WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=98.0.4758.80)
      at Object.throwDecodedError (/Users/.../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (/Users/.../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (/Users/.../node_modules/selenium-webdriver/lib/http.js:491:26)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at thenableWebDriverProxy.execute (/Users/.../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.findAndClick (src/utils/utils.js:14:5)
      at Context.<anonymous> (src/tests/[testSuiteName].js:128:7)
```

### How can we reproduce the issue?

The test case looks like follows:

```js
await utils.disableNetwork();
// Error is thrown from next line - button makes a request on click
await utils.findAndClick(Locators.BUTTON);
```
where:
```js
export function disableNetwork(driver) {
  return driver.setNetworkConditions({ offline: true, latency: 0, throughput: 0 });
}
export function makeFindAndClick(driver) {
  return async locator => {
    const elt = await find(driver, locator, 5000);
    await elt.click();
    return elt;
  };
}
```

### Relevant log output

When the erroring line is wrapped in try-catch console.log(error), the following is outputted:

```shell

WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=98.0.4758.80)
    at Object.throwDecodedError (/Users/.../node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/Users/.../node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/Users/.../node_modules/selenium-webdriver/lib/http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at thenableWebDriverProxy.execute (/Users/.../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
    at Object.findAndClick (/Users/.../src/utils/utils.js:14:5)
    at Context.<anonymous> (/Users/.../src/tests/[test-case].js:129:9) {
  name: 'WebDriverError',
  remoteStacktrace: '0   chromedriver                        0x00000001062033c9 chromedriver + 5018569\n' +
    '1   chromedriver                        0x000000010618e333 chromedriver + 4539187\n' +
    '2   chromedriver                        0x0000000105d6393f chromedriver + 170303\n' +
    '3   chromedriver                        0x0000000105d50693 chromedriver + 91795\n' +
    '4   chromedriver                        0x0000000105d50119 chromedriver + 90393\n' +
    '5   chromedriver                        0x0000000105d4f713 chromedriver + 87827\n' +
    '6   chromedriver                        0x0000000105d4e747 chromedriver + 83783\n' +
    '7   chromedriver                        0x0000000105d4eb4c chromedriver + 84812\n' +
    '8   chromedriver                        0x0000000105d5c641 chromedriver + 140865\n' +
    '9   chromedriver                        0x0000000105d5d202 chromedriver + 143874\n' +
    '10  chromedriver                        0x0000000105d6a933 chromedriver + 198963\n' +
    '11  chromedriver                        0x0000000105d6da2a chromedriver + 211498\n' +
    '12  chromedriver                        0x0000000105d4ee6e chromedriver + 85614\n' +
    '13  chromedriver                        0x0000000105d6a56c chromedriver + 197996\n' +
    '14  chromedriver                        0x0000000105dc8a13 chromedriver + 584211\n' +
    '15  chromedriver                        0x0000000105db56d3 chromedriver + 505555\n' +
    '16  chromedriver                        0x0000000105d8b95e chromedriver + 334174\n' +
    '17  chromedriver                        0x0000000105d8c935 chromedriver + 338229\n' +
    '18  chromedriver                        0x00000001061bf1ee chromedriver + 4739566\n' +
    '19  chromedriver                        0x00000001061d8f51 chromedriver + 4845393\n' +
    '20  chromedriver                        0x00000001061de928 chromedriver + 4868392\n' +
    '21  chromedriver                        0x00000001061d9a7a chromedriver + 4848250\n' +
    '22  chromedriver                        0x00000001061b3c31 chromedriver + 4693041\n' +
    '23  chromedriver                        0x00000001061f4978 chromedriver + 4958584\n' +
    '24  chromedriver                        0x00000001061f4b01 chromedriver + 4958977\n' +
    '25  chromedriver                        0x000000010620a795 chromedriver + 5048213\n' +
    '26  libsystem_pthread.dylib             0x00007fff204488fc _pthread_start + 224\n' +
    '27  libsystem_pthread.dylib             0x00007fff20444443 thread_start + 15\n'
```

### Operating System

macOS

### Selenium version

JavaScript, 4.0.0-alpha.7

### What are the browser(s) and version(s) where you see this issue?

Chrome 95+

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver ^95,^96,^97,^98

**Comment by titusfortner** [comment]
The previous issue shouldn't have been tagged with .NET, as this problem will be the same in all languages, and there's nothing that can be changed in the Selenium code to make this any different.

**Comment by TeoTN** [comment]
Created an issue [here](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4041)
