### ISSUE TITLE
[🐛 Bug]: ModuleNotFoundError: No module named 'selenium.webdriver.common.devtools.v98'

### ISSUE THREAD

**Issue by gromovoff** [SeleniumHQ/selenium#10390]
### What happened?

It seems that in the event of a new browser update, Selenium doesn't fall back to using the previous version of devtools like it does with other language bindings.

### How can we reproduce the issue?

```shell
1. Install Python/Selenium 4.1.0
2. Ensure that browser is on at least version 98
3. Run following snippet:
import asyncio

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.log import Log


async def printConsoleLogs():
  service = Service(executable_path="./driver/chromedriver")
  chrome_options = webdriver.ChromeOptions()
  driver = webdriver.Chrome(service=service)
  driver.get("http://www.google.com")

  async with driver.bidi_connection() as session:
      log = Log(driver, session)
      from selenium.webdriver.common.bidi.console import Console
      async with log.add_listener(Console.ALL) as messages:
          driver.execute_script("console.log('I love cheese')")
      print(messages["message"])

  driver.quit()

asyncio.run(printConsoleLogs())
4. Confirm error of ModuleNotFoundError: No module named 'selenium.webdriver.common.devtools.v98'
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/gromovoy/PycharmProjects/selenium4/network.py", line 23, in <module>
    asyncio.run(printConsoleLogs())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/gromovoy/PycharmProjects/selenium4/network.py", line 14, in printConsoleLogs
    async with driver.bidi_connection() as session:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Users/gromovoy/PycharmProjects/selenium4/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1573, in bidi_connection
    cdp.import_devtools(version)
  File "/Users/gromovoy/PycharmProjects/selenium4/venv/lib/python3.8/site-packages/selenium/webdriver/common/bidi/cdp.py", line 55, in import_devtools
    devtools = importlib.import_module("selenium.webdriver.common.devtools.v{}".format(version))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'selenium.webdriver.common.devtools.v98'

Process finished with exit code 1
```

### Operating System

macOS Catalina

### Selenium version

Python 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 98

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 98.0.4758.102

**Comment by AutomatedTester** [comment]
I've released a new version of the python bindings that solves this issue.
