### ISSUE TITLE
[🐛 Bug]: Exception when initializing the webdriver with Service

### ISSUE THREAD

**Issue by raffaelemancuso** [SeleniumHQ/selenium#10402]
### What happened?

Exception when initializing the webdriver with Service: NotImplementedError

### How can we reproduce the issue?

```python
from webdriver_manager.firefox import GeckoDriverManager
from selenium import webdriver
from selenium.webdriver.common.service import Service

service = Service(executable=GeckoDriverManager().install())
# same error
#service = Service(executable=firefox_wd_path)
browser = webdriver.Firefox(service=service)
browser.close()
```

### Relevant log output

```
$ python3 selenium_bug.py 

====== WebDriver manager ======
Current firefox version is 97.0
Get LATEST geckodriver version for 97.0 firefox
Driver [/home/raffaele/.wdm/drivers/geckodriver/linux64/v0.30.0/geckodriver] found in cache
Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 70, in start
    cmd.extend(self.command_line_args())
  File "/home/raffaele/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 58, in command_line_args
    raise NotImplementedError("This method needs to be implemented in a sub class")
NotImplementedError: This method needs to be implemented in a sub class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/raffaele/55ab61c4-83cf-4d9f-a5cd-7fcfdc14b4fb/Dropbox (DIG)/Deepening RISIS/LexisNexis_webscraper/src/selenium_bug.py", line 9, in <module>
    browser = webdriver.Firefox(service=service)
  File "/home/raffaele/.local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 173, in __init__
    self.service.start()
  File "/home/raffaele/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 93, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: The executable geckodriver needs to be available in the path. 
This method needs to be implemented in a sub class
```

### Operating System

Fedora Workstation 35

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 97.0.1

### What are the browser driver(s) and version(s) where you see this issue?

0.30

**Comment by titusfortner** [comment]
The error says
> This method needs to be implemented in a sub class

So instead of doing this
```
from selenium.webdriver.common.service import Service
```

you need to do this:
https://github.com/SeleniumHQ/seleniumhq.github.io/blob/dev/examples/python/tests/getting_started/test_install_drivers.py#L5

**Comment by raffaelemancuso** [comment]
Yeah I figured it out. Thanks :)
