### ISSUE TITLE
[🐛 Bug]: Getting ConnectionFailedException while trying to use driver.close() for firefox browser.

### ISSUE THREAD

**Issue by EswariKarthik** [SeleniumHQ/selenium#10417]
### What happened?

I have a sample code written to test normal firefox browser launch then launching web page then closing the browser using Selenium 4.1.2 with Java. It is failing with ConnectionFailedException in line driver.close()
**I am using Firefox Browser** whereas the **Exception starts with chrome**, not sure why.

### How can we reproduce the issue?

```shell
public class CaptureScreenshotExample 
{
	public static void main(String[] args) throws IOException 
	{
		Format f = new SimpleDateFormat("dd_MM_yy hh_mm");
		String strDate = f.format(new Date());
		System.out.println("Current Date = "+strDate);
		
		System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		
		//Launch the web page
		driver.get("https://demo.actitime.com/login.do");
		
		//To take screen shot
		TakesScreenshot ts = (TakesScreenshot)driver;
		File screenshot = ts.getScreenshotAs(OutputType.FILE);
		
		//Creating an external file
		File output_ss = new File("./screenshots/" + driver.getTitle() + "_" + strDate + ".jpg");
		
		//Copying the captured screen shot from source file to destination file
		FileHandler.copy(screenshot, output_ss);
		
		driver.close();		
	}

}
```

### Relevant log output

```shell
JavaScript error: **chrome://remote/content/server/WebSocketHandshake.jsm**, line 117: Error: The handshake request has incorrect Origin header http://localhost:52540
Mar 07, 2022 5:36:38 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Invalid Status code=400 text=Bad Request
java.io.IOException: Invalid Status code=400 text=Bad Request
	at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
	at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Exception in thread "main" org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:52540/devtools/browser/25f0debb-b795-4375-9ba6-83c9dcd9c461
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: '', ip: '', os.name: 'Windows 10', os.arch: '', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:104)
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:137)
	at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:118)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
	at org.openqa.selenium.firefox.FirefoxDriver.maybeGetDevTools(FirefoxDriver.java:310)
	at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:440)
	at com.practice.tests.CaptureScreenshotExample.main(CaptureScreenshotExample.java:45)
```

### Operating System

Windows 10

### Selenium version

Java 4.1.2

### What are the browser(s) and version(s) where you see this issue?

Firefox V97.0.2

### What are the browser driver(s) and version(s) where you see this issue?

gecko driver v0.30.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
This was fixed in Firefox, please update to latest
#10348
