### ISSUE TITLE
[🐛 Bug]: I use grid4 automated mobile phone to find elements and prompt "selenium. Common. Exceptions. Invalidselectorexception: Message: an element could not be located on the page using the given search parameters.", But the location information of this element on the page is also correct.

### ISSUE THREAD

**Issue by tianyao1111** [SeleniumHQ/selenium#10422]
### What happened?

`1，hub(10.22.64.60)：`
`java -jar selenium-server-4.1.1.jar hub`

`2，node（11.204.111.8）：`
appium:
`appium --session-override -a 11.204.111.8 -p 4726  -U  连接一体机手机的UDID  --log-level error --relaxed-security`

1.tom:
```
[server]
port = 5555

[node]
detect-drivers = false
grid-url = "http://10.22.64.60:4444"
hub = "http://10.22.64.60:4444"

[relay]
# Default Appium server endpoint
url = "http://11.204.111.8:4726/wd/hub"
status-endpoint = "/status"
# Stereotypes supported by the service
[[relay.configs]]
max-sessions = 1
stereotype = '{"browserName": "chrome", "platformName": "android", "appium:platformVersion": "11","nodename:applicationName":"huawei honor 10"}}'

[events]
publish = "tcp://10.22.64.60:4442"
subscribe = "tcp://10.22.64.60:4443"
```
`java -jar selenium-server-4.1.1.jar node --config  1.toml`

`3，client(10.22.64.60)`
#selenium GRID专用
```
host="http://localhost:4444/wd/hub"
def get_driver():
	'''生成deiver'''
	caps = {}
	caps["platformName"] = "Android"
	# caps["platformVersion"] = "7.1.2"
	# caps["deviceName"] = "P7CDU18C03003486        device"
	# caps["deviceName"] = udid
	# caps["udid"] = udid
	# caps["deviceName"] = "127.0.0.1:62001 device"

	# 新架构app
	#caps["appPackage"] = "com.picc.etong"
	# caps["appActivity"] = "com.picc.etong.etongmain.main.GroupLoginActivity"
	#caps["appActivity"] = "com.picc.nmmslogin.activity.GroupWelcomeActivity"

	#老版app
	caps["appPackage"] = "com.picc.nx"
	# caps["appActivity"] = "com.picc.nx.ui.activity.MainActivity"
	# caps["appActivity"] = "com.picc.nx.ui.activity.common.locker.WholePatternCheckingActivity"

	# caps["appActivity"] = "com.picc.nx.ui.activity.user.LoginActivity"

	caps["appActivity"] = "com.picc.nx.ui.activity.extras.SplashActivity"

	#Don't reset app state before this session. 
	caps["noReset"] = True
	#Have Appium automatically determine which permissions your app requires and grant them to the app on install. Defaults to false. If noReset is true, this capability doesn't work.
	# caps["autoGrantPermissions"] = True
	#为了输入框输入中文
	caps["unicodeKeyboard"] = True
	caps["resetKeyboard"] = True
	#How long (in seconds) Appium will wait for a new command from the client before assuming the client quit and ending the session
	caps["newCommandTimeout"] = 180
	#Timeout in milliseconds used to wait for adb command execution. Defaults to 20000
	caps["adbExecTimeout"] = 180000
	# caps["automationName"] = "UiAutomator1"
	#Set the output format for logcat messages since Appium 1.18.0. Supported formats are listed in here. Please read logcat#outputFormat for more details about each format. Defaults to threadtime.
	caps["logcatFormat"] = "time"
	#Set the output filter rule for logcat messages since Appium 1.18.0. Please read logcat#filteringOutput for more details about the rule. Write and View Logs with Logcat is also helpful.
	caps["logcatFilterSpecs"] = ['*:E']
	#在每次会话开始时清除logcat日志
	caps["clearDeviceLogsOnStart"] = True
	caps["chromeOptions"] = {"w3c": False}
	driver = webdriver.Remote(host, caps)
	driver.implicitly_wait(global_wait)

	return driver
```
YZB_CB_HKT_case_01.py:
```

@when_error_screenshot
    @logcatlogger
    def test_case_01(self):
        '''清单-验标-投保单'''

        self.logging.info("*********************登录页面*********************")

        LP=LoginPage(self.logging)

        #登录耘智保
        LP.login_by_sss(self.driver)
```
LoginPage.py:
```
#coding=utf-8
from appium.webdriver.common.touch_action import TouchAction
from test_page.BasePage import BasePage
from public.sss import get_point_pos
from public.common import get_element
class LoginPage(BasePage):
	'''登录页所有操作'''

	def login_by_sss(self,driver):
		'''手势锁登录'''
		self.logging.info("*画手势锁登录*")
		try:
			el1 = get_element(driver,'id','com.picc.nx:id/patternLockerView')
		except:
			self.logging.error("*非手势锁页面*")
		else:
			p1=get_point_pos(el1)
			TouchAction(driver).press(x=int(p1[1][0]),y=int(p1[1][1])).move_to(x=int(p1[3][0]),y=int(p1[3][1])).wait(100).move_to(x=int(p1[7][0]),y=int(p1[7][1])).wait(10).move_to(x=int(p1[5][0]),y=int(p1[5][1])).wait(10).release().perform()
```
common.py:
```
def get_element(driver,method,value):
    '''封装find_ellement_by_*()方法'''
    e=None
    if method=='id':
        e=driver.find_element_by_id(value)
    elif method=='xpath':
        e=driver.find_element_by_xpath(value)

    elif method=='class':
        e=driver.find_element_by_class_name(value)

    elif method=="content-desc":
        e=driver.find_element_by_accessibility_id(value)

    elif method=="text":
        e=driver.find_element_by_android_uiautomator("text(\""+value+"\")")

    return e
```

**4,error**
```
ft1.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\MyTestCase.py", line 27, in testPartExecutor
    yield
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\MyTestCase.py", line 188, in run
    testMethod()
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\common2.py", line 123, in wrapper
    func(self)
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\common2.py", line 45, in wrapper
    func(self)
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\test_case\YZB_CB_HKT_case_01.py", line 92, in test_case_01
    LP.login_by_sss(self.driver)
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\test_page\LoginPage.py", line 13, in login_by_sss
    el1 = get_element(driver,'id','com.picc.nx:id/patternLockerView')
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\common.py", line 16, in get_element
    e=driver.find_element_by_id(value)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DZB11117303RK', ip: '11.204.111.8', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '11.0.10'
Driver info: org.openqa.selenium.grid.node.CustomLocatorHandler$CustomWebDriver
Command: [d6b391f9-8699-4a47-b83c-7907eeb03700, findElement {using=id, value=com.picc.nx:id/patternLockerView}]
Capabilities {}
Session ID: d6b391f9-8699-4a47-b83c-7907eeb03700
```

### How can we reproduce the issue?

```shell
#selenium GRID专用

host="http://localhost:4444/wd/hub"
def get_driver():
	'''生成deiver'''
	caps = {}
	caps["platformName"] = "Android"
	# caps["platformVersion"] = "7.1.2"
	# caps["deviceName"] = "P7CDU18C03003486        device"
	# caps["deviceName"] = udid
	# caps["udid"] = udid
	# caps["deviceName"] = "127.0.0.1:62001 device"

	# 新架构app
	#caps["appPackage"] = "com.picc.etong"
	# caps["appActivity"] = "com.picc.etong.etongmain.main.GroupLoginActivity"
	#caps["appActivity"] = "com.picc.nmmslogin.activity.GroupWelcomeActivity"

	#老版app
	caps["appPackage"] = "com.picc.nx"
	# caps["appActivity"] = "com.picc.nx.ui.activity.MainActivity"
	# caps["appActivity"] = "com.picc.nx.ui.activity.common.locker.WholePatternCheckingActivity"

	# caps["appActivity"] = "com.picc.nx.ui.activity.user.LoginActivity"

	caps["appActivity"] = "com.picc.nx.ui.activity.extras.SplashActivity"

	#Don't reset app state before this session. 
	caps["noReset"] = True
	#Have Appium automatically determine which permissions your app requires and grant them to the app on install. Defaults to false. If noReset is true, this capability doesn't work.
	# caps["autoGrantPermissions"] = True
	#为了输入框输入中文
	caps["unicodeKeyboard"] = True
	caps["resetKeyboard"] = True
	#How long (in seconds) Appium will wait for a new command from the client before assuming the client quit and ending the session
	caps["newCommandTimeout"] = 180
	#Timeout in milliseconds used to wait for adb command execution. Defaults to 20000
	caps["adbExecTimeout"] = 180000
	# caps["automationName"] = "UiAutomator1"
	#Set the output format for logcat messages since Appium 1.18.0. Supported formats are listed in here. Please read logcat#outputFormat for more details about each format. Defaults to threadtime.
	caps["logcatFormat"] = "time"
	#Set the output filter rule for logcat messages since Appium 1.18.0. Please read logcat#filteringOutput for more details about the rule. Write and View Logs with Logcat is also helpful.
	caps["logcatFilterSpecs"] = ['*:E']
	#在每次会话开始时清除logcat日志
	caps["clearDeviceLogsOnStart"] = True
	caps["chromeOptions"] = {"w3c": False}
	driver = webdriver.Remote(host, caps)
	driver.implicitly_wait(global_wait)

	return driver
```
YZB_CB_HKT_case_01.py:
```

@when_error_screenshot
    @logcatlogger
    def test_case_01(self):
        '''清单-验标-投保单'''

        self.logging.info("*********************登录页面*********************")

        LP=LoginPage(self.logging)

        #登录耘智保
        LP.login_by_sss(self.driver)
```
LoginPage.py:
```
#coding=utf-8
from appium.webdriver.common.touch_action import TouchAction
from test_page.BasePage import BasePage
from public.sss import get_point_pos
from public.common import get_element
class LoginPage(BasePage):
	'''登录页所有操作'''

	def login_by_sss(self,driver):
		'''手势锁登录'''
		self.logging.info("*画手势锁登录*")
		try:
			el1 = get_element(driver,'id','com.picc.nx:id/patternLockerView')
		except:
			self.logging.error("*非手势锁页面*")
		else:
			p1=get_point_pos(el1)
			TouchAction(driver).press(x=int(p1[1][0]),y=int(p1[1][1])).move_to(x=int(p1[3][0]),y=int(p1[3][1])).wait(100).move_to(x=int(p1[7][0]),y=int(p1[7][1])).wait(10).move_to(x=int(p1[5][0]),y=int(p1[5][1])).wait(10).release().perform()
```
common.py:
```
def get_element(driver,method,value):
    '''封装find_ellement_by_*()方法'''
    e=None
    if method=='id':
        e=driver.find_element_by_id(value)
    elif method=='xpath':
        e=driver.find_element_by_xpath(value)

    elif method=='class':
        e=driver.find_element_by_class_name(value)

    elif method=="content-desc":
        e=driver.find_element_by_accessibility_id(value)

    elif method=="text":
        e=driver.find_element_by_android_uiautomator("text(\""+value+"\")")

    return e
```
```


### Relevant log output

```shell
ft1.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\MyTestCase.py", line 27, in testPartExecutor
    yield
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\MyTestCase.py", line 188, in run
    testMethod()
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\common2.py", line 123, in wrapper
    func(self)
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\common2.py", line 45, in wrapper
    func(self)
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\test_case\YZB_CB_HKT_case_01.py", line 92, in test_case_01
    LP.login_by_sss(self.driver)
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\test_page\LoginPage.py", line 13, in login_by_sss
    el1 = get_element(driver,'id','com.picc.nx:id/patternLockerView')
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\common.py", line 16, in get_element
    e=driver.find_element_by_id(value)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DZB11117303RK', ip: '11.204.111.8', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '11.0.10'
Driver info: org.openqa.selenium.grid.node.CustomLocatorHandler$CustomWebDriver
Command: [d6b391f9-8699-4a47-b83c-7907eeb03700, findElement {using=id, value=com.picc.nx:id/patternLockerView}]
Capabilities {}
Session ID: d6b391f9-8699-4a47-b83c-7907eeb03700
```

### Operating System

HUB:windows server 2008 R2;NODE:win7;clent:windows server 2008 R2

### Selenium version

python3.8.5 selenium3.14.1

### What are the browser(s) and version(s) where you see this issue?

IE11

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer_win32_3.141.0

### Are you using Selenium Grid?

selenium-server-4.1.1.jar

**Comment by titusfortner** [comment]
Technically we're not still supporting Selenium 3 client, and we've recently found that attempts the grid is making to convert JSON Wire Protocol commands to W3C commands are not as comprehensive as we'd hoped.

My best guess as to what is going on...
ID is not a valid w3c locator, so Grid is translating it to CSS, which is a valid w3c locator, and while html recognizes an id with any non-space character, CSS locators do not allow it. 

If you run your grid with `--log-level FINE` you should be able to see if this is the translation being made
We're looking into removing these translations so that problems like this will surface better.
We're also looking into working with Appium team better so that the right things happen with Appium allowed parameters in Selenium grid.

**Comment by tianyao1111** [comment]
> Technically we're not still supporting Selenium 3 client, and we've recently found that attempts the grid is making to convert JSON Wire Protocol commands to W3C commands are not as comprehensive as we'd hoped.
> 
> My best guess as to what is going on... ID is not a valid w3c locator, so Grid is translating it to CSS, which is a valid w3c locator, and while html recognizes an id with any non-space character, CSS locators do not allow it.
> 
> If you run your grid with `--log-level FINE` you should be able to see if this is the translation being made We're looking into removing these translations so that problems like this will surface better. We're also looking into working with Appium team better so that the right things happen with Appium allowed parameters in Selenium grid.

Thank you so much, you solved my 2 weeks of problems!
