### ISSUE TITLE
[🐛 Bug]: When I use GRID4 to control the web, it prompts 'An invalid or illegal selector was specified', but sometimes this piece does not report an error

### ISSUE THREAD

**Issue by tianyao1111** [SeleniumHQ/selenium#10435]
### What happened?

- hub
`java -jar selenium-server-4.1.1.jar hub`

- node
web1.tom:
```
[server]
port = 5556

[node]
detect-drivers = false

[[node.driver-configuration]]
display-name = "internet explorer"
max-sessions = 1
stereotype = "{\"browserName\": \"internet explorer\", \"browserVersion\": \"11\", \"platformName\": \"WINDOWS\"}"
webdriver-executable = 'C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\tools\IEDriverServer_Win32_4.0.0\IEDriverServer_Win32_4.0.0.exe'
```
`java -jar selenium-server-4.1.1.jar node --config  C:\Users\14221\Desktop\项目资料\人保E通新架构\web1.toml`

- client
get_driver.py:
```
def get_web_driver(url,data=None,kill_all_ie=True):
        global_wait=30
	chrome_capabilities = {
				"browserName": "internet explorer",		# 浏览器名称
				"version": "11",				  # 操作系统版本
				"platform": "WINDOWS",			  # 平台，这里可以是windows、linux、andriod等等
				"javascriptEnabled": True,	  # 是否启用js
				#"webdriver.chrome.driver": chrome_driver
			}
	driver=webdriver.Remote(host, desired_capabilities=chrome_capabilities)
	driver.get(url)
	driver.maximize_window()
	driver.implicitly_wait(global_wait)
	#等待页面加载
	driver.find_element_by_xpath('//a[@id="overridelink"]')

	#点击详细信息
	driver.execute_script("javascript:expandCollapse('infoBlockID', true);")

	#转到此网页
	WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.XPATH, '//a[@id="overridelink"]')))
	ele=driver.find_element_by_xpath('//a[@id="overridelink"]')
	str1='return arguments[0].click();'
	driver.execute_script(str1, ele)
	return driver
```
YZB_CB_HKT_case_01.py:
```
global product_info
self.wins = {}
self.wins['首页'] = self.driver.current_window_handle
# 登录农险核心系统
CBWebLoginPage(self.logging).login(self.driver, self.data['web_CB_user'], self.data['web_CB_pwd'])
```
CBWebLoginPage.py:
```
from test_page.BasePage import BasePage
from public.common import get_visibile_element,js_click
class CBWebLoginPage(BasePage):

	def input_userName(self,driver,val):
		self.logging.info("*录入用户名-%s*"%val)
		ele=get_visibile_element(driver,'id','username1')
		ele.clear()
		ele.send_keys(val)

	def input_pwd(self,driver,val):
		self.logging.info("*录入密码-%s*"%val)
		ele=get_visibile_element(driver,'id','password1')
		ele.clear()
		ele.send_keys(val)

	def click_login(self,driver):
		self.logging.info("*点击登录*")
		ele=get_visibile_element(driver,'id','button')
		js_click(driver,ele)

	def login(self,driver,user,pwd):
		self.input_userName(driver,user)
		self.input_pwd(driver,pwd)
		self.click_login(driver)
```
common.py:
```
def get_visibile_element(driver,method,value):
    '''查找可见元素'''
    e=None
    if method=='id':
        e=WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.ID, value)))

    elif method=='xpath':
        e=WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.XPATH, value)))
    return e
```

- error
```
ft1.1: test_case_02---{}
Traceback (most recent call last):
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common2.py", line 123, in wrapper
    func(self)
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\test_case\YZB_CB_HKT_case_01.py", line 300, in test_case_02
    CBWebLoginPage(self.logging).login(self.driver, self.data['web_CB_user'], self.data['web_CB_pwd'])
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\test_page\CBWebLoginPage.py", line 24, in login
    self.input_userName(driver,user)
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\test_page\CBWebLoginPage.py", line 8, in input_userName
    ele=get_visibile_element(driver,'id','username1')
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common.py", line 54, in get_visibile_element
    e=WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.ID, value)))
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 82, in until
    raise e
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 127, in _predicate
    raise e
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Python39\lib\site-packages\appium\webdriver\webdriver.py", line 414, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 30, in check_response
    raise wde
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: An invalid or illegal selector was specified
For documentation on this error, please visit: https://selenium.dev/exceptions/#invalid_selector_exception
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DESKTOP-H3KEKEV', ip: '11.204.111.178', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: org.openqa.selenium.grid.node.CustomLocatorHandler$CustomWebDriver
Command: [33128463-5d15-4c24-98a0-642598db2182, findElement {using=id, value=username1}]
Capabilities {}
Session ID: 33128463-5d15-4c24-98a0-642598db2182
Stacktrace:
org.openqa.selenium.InvalidSelectorException: An invalid or illegal selector was specified
For documentation on this error, please visit: https://selenium.dev/exceptions/#invalid_selector_exception
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DESKTOP-H3KEKEV', ip: '11.204.111.178', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: org.openqa.selenium.grid.node.CustomLocatorHandler$CustomWebDriver
Command: [33128463-5d15-4c24-98a0-642598db2182, findElement {using=id, value=username1}]
Capabilities {}
Session ID: 33128463-5d15-4c24-98a0-642598db2182
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.grid.node.CustomLocatorHandler$NodeWrappingExecutor.execute(CustomLocatorHandler.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:367)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
	at org.openqa.selenium.grid.node.CustomLocatorHandler.execute(CustomLocatorHandler.java:202)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\MyTestCase.py", line 27, in testPartExecutor
    yield
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\MyTestCase.py", line 188, in run
    testMethod()
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common2.py", line 129, in wrapper
    if hasattr(self.driver, 'current_context'):
  File "C:\Python39\lib\site-packages\appium\webdriver\extensions\context.py", line 46, in current_context
    return self.execute(Command.GET_CURRENT_CONTEXT)['value']
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 30, in check_response
    raise wde
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Command not found: GET /session/33128463-5d15-4c24-98a0-642598db2182/context
```

### How can we reproduce the issue?

```shell
get_driver.py:

def get_web_driver(url,data=None,kill_all_ie=True):
        global_wait=30
	chrome_capabilities = {
				"browserName": "internet explorer",		# 浏览器名称
				"version": "11",				  # 操作系统版本
				"platform": "WINDOWS",			  # 平台，这里可以是windows、linux、andriod等等
				"javascriptEnabled": True,	  # 是否启用js
				#"webdriver.chrome.driver": chrome_driver
			}
	driver=webdriver.Remote(host, desired_capabilities=chrome_capabilities)
	driver.get(url)
	driver.maximize_window()
	driver.implicitly_wait(global_wait)
	#等待页面加载
	driver.find_element_by_xpath('//a[@id="overridelink"]')

	#点击详细信息
	driver.execute_script("javascript:expandCollapse('infoBlockID', true);")

	#转到此网页
	WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.XPATH, '//a[@id="overridelink"]')))
	ele=driver.find_element_by_xpath('//a[@id="overridelink"]')
	str1='return arguments[0].click();'
	driver.execute_script(str1, ele)
	return driver
```
YZB_CB_HKT_case_01.py:
```
global product_info
self.wins = {}
self.wins['首页'] = self.driver.current_window_handle
# 登录农险核心系统
CBWebLoginPage(self.logging).login(self.driver, self.data['web_CB_user'], self.data['web_CB_pwd'])
```
CBWebLoginPage.py:
```
from test_page.BasePage import BasePage
from public.common import get_visibile_element,js_click
class CBWebLoginPage(BasePage):

	def input_userName(self,driver,val):
		self.logging.info("*录入用户名-%s*"%val)
		ele=get_visibile_element(driver,'id','username1')
		ele.clear()
		ele.send_keys(val)

	def input_pwd(self,driver,val):
		self.logging.info("*录入密码-%s*"%val)
		ele=get_visibile_element(driver,'id','password1')
		ele.clear()
		ele.send_keys(val)

	def click_login(self,driver):
		self.logging.info("*点击登录*")
		ele=get_visibile_element(driver,'id','button')
		js_click(driver,ele)

	def login(self,driver,user,pwd):
		self.input_userName(driver,user)
		self.input_pwd(driver,pwd)
		self.click_login(driver)
```
common.py:
```
def get_visibile_element(driver,method,value):
    '''查找可见元素'''
    e=None
    if method=='id':
        e=WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.ID, value)))

    elif method=='xpath':
        e=WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.XPATH, value)))
    return e
```
```


### Relevant log output

```shell
ft1.1: test_case_02---{}
Traceback (most recent call last):
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common2.py", line 123, in wrapper
    func(self)
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\test_case\YZB_CB_HKT_case_01.py", line 300, in test_case_02
    CBWebLoginPage(self.logging).login(self.driver, self.data['web_CB_user'], self.data['web_CB_pwd'])
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\test_page\CBWebLoginPage.py", line 24, in login
    self.input_userName(driver,user)
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\test_page\CBWebLoginPage.py", line 8, in input_userName
    ele=get_visibile_element(driver,'id','username1')
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common.py", line 54, in get_visibile_element
    e=WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.ID, value)))
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 82, in until
    raise e
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 127, in _predicate
    raise e
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 125, in _predicate
    return _element_if_visible(driver.find_element(*locator))
  File "C:\Python39\lib\site-packages\appium\webdriver\webdriver.py", line 414, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 30, in check_response
    raise wde
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: An invalid or illegal selector was specified
For documentation on this error, please visit: https://selenium.dev/exceptions/#invalid_selector_exception
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DESKTOP-H3KEKEV', ip: '11.204.111.178', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: org.openqa.selenium.grid.node.CustomLocatorHandler$CustomWebDriver
Command: [33128463-5d15-4c24-98a0-642598db2182, findElement {using=id, value=username1}]
Capabilities {}
Session ID: 33128463-5d15-4c24-98a0-642598db2182
Stacktrace:
org.openqa.selenium.InvalidSelectorException: An invalid or illegal selector was specified
For documentation on this error, please visit: https://selenium.dev/exceptions/#invalid_selector_exception
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'DESKTOP-H3KEKEV', ip: '11.204.111.178', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: org.openqa.selenium.grid.node.CustomLocatorHandler$CustomWebDriver
Command: [33128463-5d15-4c24-98a0-642598db2182, findElement {using=id, value=username1}]
Capabilities {}
Session ID: 33128463-5d15-4c24-98a0-642598db2182
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.grid.node.CustomLocatorHandler$NodeWrappingExecutor.execute(CustomLocatorHandler.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:367)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)
	at org.openqa.selenium.grid.node.CustomLocatorHandler.execute(CustomLocatorHandler.java:202)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\MyTestCase.py", line 27, in testPartExecutor
    yield
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\MyTestCase.py", line 188, in run
    testMethod()
  File "C:\Users\14221\Desktop\project-git\UITestAND_PICC_YZB\public\common2.py", line 129, in wrapper
    if hasattr(self.driver, 'current_context'):
  File "C:\Python39\lib\site-packages\appium\webdriver\extensions\context.py", line 46, in current_context
    return self.execute(Command.GET_CURRENT_CONTEXT)['value']
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 30, in check_response
    raise wde
  File "C:\Python39\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Command not found: GET /session/33128463-5d15-4c24-98a0-642598db2182/context
```

### Operating System

win10

### Selenium version

python selenium 4.0.0

### What are the browser(s) and version(s) where you see this issue?

IE11

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer_win32_4.0.0

### Are you using Selenium Grid?

selenium-server-4.1.1.jar

**Comment by pujagani** [comment]
Thank you for sharing the details.  Does this happen only when used with the Grid or does it also happen when run locally? 
Please provide a reproducible test script/project that can be used to reproduce the issue.

**Comment by titusfortner** [comment]
So this actually is an Appium issue because Selenium is following strict w3c requirements with the Grid. The correct fix would be for Appium to implement their own `/session/{session id}/appium/element` endpoint that accepts non-standard locators. Selenium grid would pass these along to the Appium server without issue. Selenium team and Appium team will work together to resolve this.

https://github.com/appium/appium/issues/16550#issuecomment-1067659054
