### ISSUE TITLE
[🐛 Bug]: Can't handle alerts on new ChromeDriver update

### ISSUE THREAD

**Issue by RenanSchwyz** [SeleniumHQ/selenium#10431]
### What happened?

Hello,

I'm using Selenium to check if my credentials in a website are working. When the credentials are accepted, the website returns an alert with OK button on it. Until ChromeDriver 98.0.4758.102 everything worked fine but when I upgraded to ChromeDriver 99.0.4844.51 this stop working. I can't continue using the old version of Google Chrome because my updates are automatically.

The problem is: everytime the alert appears on the page and I try to handle it, I get an error

### How can we reproduce the issue?

```shell
(...)

login_button = driver.find_elements(By.ID, "Entrada")[0]
login_button.click()
time.sleep(15)

try:
	driver.switch_to.alert.accept()
	time.sleep(5)
        print('Successful Login')
except:
	print('Error')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\Schwyz\Documents\scrap_files.py", line 102, in run
    driver.switch_to.alert.accept()
  File "C:\Users\Schwyz\Documents\lib\site-packages\selenium\webdriver\remote\switch_to.py", line 56, in alert
    alert.text
  File "C:\Users\Schwyz\Documents\lib\site-packages\selenium\webdriver\common\alert.py", line 66, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "C:\Users\Schwyz\Documents\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Schwyz\Documents\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 246, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: A sessão anterior foi encerrada.
Stacktrace:
Backtrace:
        Ordinal0 [0x00929943+2595139]
        Ordinal0 [0x008BC9F1+2148849]
        Ordinal0 [0x007B4528+1066280]
        Ordinal0 [0x007A4B9A+1002394]
        Ordinal0 [0x007A50D8+1003736]
        Ordinal0 [0x007A5068+1003624]
        Ordinal0 [0x007AAD85+1027461]
        Ordinal0 [0x007AAFC6+1028038]
        Ordinal0 [0x007A62AD+1008301]
        Ordinal0 [0x007A67C5+1009605]
        Ordinal0 [0x007A65AF+1009071]
        Ordinal0 [0x007A5BC6+1006534]
        Ordinal0 [0x007A4AD0+1002192]
        Ordinal0 [0x007A50D8+1003736]
        Ordinal0 [0x007A5068+1003624]
        Ordinal0 [0x007AB220+1028640]
        Ordinal0 [0x007A62AD+1008301]
        Ordinal0 [0x007A67C5+1009605]
        Ordinal0 [0x007A65AF+1009071]
        Ordinal0 [0x007A5BC6+1006534]
        Ordinal0 [0x007A4AD0+1002192]
        Ordinal0 [0x007A50D8+1003736]
        Ordinal0 [0x007A5068+1003624]
        Ordinal0 [0x007AB220+1028640]
        Ordinal0 [0x007A62AD+1008301]
        Ordinal0 [0x007A67C5+1009605]
        Ordinal0 [0x007A65AF+1009071]
        Ordinal0 [0x007A5BC6+1006534]
        Ordinal0 [0x007A4AD0+1002192]
        Ordinal0 [0x007A50D8+1003736]
        Ordinal0 [0x007A5068+1003624]
        Ordinal0 [0x007AB220+1028640]
        Ordinal0 [0x007A62AD+1008301]
        Ordinal0 [0x007A67C5+1009605]
        Ordinal0 [0x007A65AF+1009071]
        Ordinal0 [0x007A5BC6+1006534]
        Ordinal0 [0x007A4AD0+1002192]
        Ordinal0 [0x007A50D8+1003736]
        Ordinal0 [0x007A5068+1003624]
        Ordinal0 [0x007AAD85+1027461]
        Ordinal0 [0x007AAFC6+1028038]
        Ordinal0 [0x007A62AD+1008301]
        Ordinal0 [0x007A67C5+1009605]
        Ordinal0 [0x007A65AF+1009071]
        Ordinal0 [0x007A5BC6+1006534]
        Ordinal0 [0x007A4AD0+1002192]
        Ordinal0 [0x007A50D8+1003736]
        Ordinal0 [0x007A5068+1003624]
        Ordinal0 [0x007AAD85+1027461]
        Ordinal0 [0x007AAFC6+1028038]
        Ordinal0 [0x007A62AD+1008301]
        Ordinal0 [0x007A67C5+1009605]
        Ordinal0 [0x007A65AF+1009071]
        Ordinal0 [0x007A5BC6+1006534]
        Ordinal0 [0x007A542B+1004587]
        Ordinal0 [0x007A52C9+1004233]
        Ordinal0 [0x007B58A0+1071264]
        Ordinal0 [0x007C4747+1132359]
        Ordinal0 [0x007FB806+1357830]
        Ordinal0 [0x007D6086+1204358]
        Ordinal0 [0x007D6F96+1208214]
        GetHandleVerifier [0x00ACB232+1658114]
        GetHandleVerifier [0x00B8312C+2411516]
        GetHandleVerifier [0x009BF261+560433]
        GetHandleVerifier [0x009BE366+556598]
        Ordinal0 [0x008C286B+2173035]
        Ordinal0 [0x008C75F8+2192888]
        Ordinal0 [0x008C76E5+2193125]
        Ordinal0 [0x008D11FC+2232828]
        BaseThreadInitThunk [0x757BFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77947A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77947A6E+238]
```

### Operating System

Windows 10

### Selenium version

Python 3.9.1 - Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 99.0.4844.51 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 99.0.4844.51

**Comment by RaGreen** [comment]
Chrome and ChromeDriver 99.0.4844.51 on Windows 64-bit. Using Selenium in Java. I notice not working ElementNotVisibleException. Chromedriver logs:

`[1647100273.811][INFO]: [8659a25c28be91ea9ca8a7eec849cf61] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"xpath","selector":"//tr[contains(., '1966-03-06')]"}
  (Session info: chrome=99.0.4844.51)`

But code execution stops here. No success, no exception thrown.

Everything worked before update from 98 to 99.

**Comment by RenanSchwyz** [comment]
I solved the problem by using the following:

```
try:
	driver.switch_to.alert.accept()
except UnexpectedAlertPresentException:
	driver.switch_to.alert.accept()
```

No matter what I do using the driver the UnexpectedAlertPresentException appears, so I trigger this error and handle the same way I was doing

**Comment by titusfortner** [comment]
Yeah, this is weird. It's the exception you would get if you were making a non-alert related command, but switching to the alert calls `alert/text`, which is allowed. I can't reproduce it on my mac at least. 

Regardless, this would be an issue that Google would need to fix in their chromedriver.

**Comment by wolendranh** [comment]
HI! Is there a link to corresponding ChromeDriver issue? Is there any progress?
