### ISSUE TITLE
[🐛 Selenium4 is unable to launch chrome browser in docker container]: 

### ISSUE THREAD

**Issue by AC49184** [SeleniumHQ/selenium#10469]
### What happened?

1. Create a Selenium 4 Maven project with JUnit 
2. Create a docker file to execute test cases over docker container
3. Execute the jenkins pipeline job to run the test
4. After executing jenkins pipeline job our chrome browser is launching in docker container with the latest version of chromedriver but crashing immediately.

### How can we reproduce the issue?

```shell
My Docker File Details :
ARG MAVEN_VERSION=${MAVEN_VERSION:-3.6.1}
ENV MAVEN_VERSION=${MAVEN_VERSION}
ENV MAVEN_HOME=/usr/apache-maven-${MAVEN_VERSION}
ENV PATH=${PATH}:${MAVEN_HOME}/bin
RUN curl -sL http://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  | gunzip \
  | tar x -C /usr/ \
  && ln -s ${MAVEN_HOME} /usr/maven
ENV PATH=${PATH}:${JAVA_HOME}/bin


RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm && \
    yum localinstall google-chrome-stable_current_x86_64.rpm -y  && \
    rm -rf google-chrome-stable_current_x86_64.rpm


RUN echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf && \
    echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf


These are the chrome options that we are passing : 

ChromeOptions options = new ChromeOptions() ;
options.addArguments("--disable-gpu") ;
options.addArguments("--shm-size=2g");
```

### Relevant log output

```shell
10:04:51  -------------------------------------------------------
10:04:51   T E S T S
10:04:51  -------------------------------------------------------
10:04:52  Running selenium.webdriverTest
10:04:52  path of driver is :/usr/local/bin/chromedriver
10:04:53  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10:04:53  SLF4J: Defaulting to no-operation (NOP) logger implementation
10:04:53  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
10:04:54  Starting ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}) on port 51616
10:04:54  Only local connections are allowed.
10:04:54  Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
10:04:54  ChromeDriver was started successfully.
10:04:54  [1648010094.058][SEVERE]: CreatePlatformSocket() failed: Address family not supported by protocol (97)
10:04:57  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.99 sec <<< FAILURE!
10:04:57  swTestAcademyTitleTest(selenium.webdriverTest)  Time elapsed: 4.759 sec  <<< ERROR!
10:04:57  org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
10:04:57    (unknown error: DevToolsActivePort file doesn't exist)
10:04:57    (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
10:04:57  Build info: version: '4.0.0', revision: '3a21814679'
10:04:57  System info: host: 'dfe73a40d685', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.42.2.el7.x86_64', java.version: '1.8.0_272'
10:04:57  Driver info: org.openqa.selenium.chrome.ChromeDriver
10:04:57  Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-gpu, --shm-size=2g], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-gpu, --shm-size=2g], extensions: []}}}]
10:04:57  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
10:04:57  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
10:04:57  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
10:04:57  	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
10:04:57  	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
10:04:57  	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
10:04:57  	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
10:04:57  	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:246)
10:04:57  	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168)
10:04:57  	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
10:04:57  	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:104)
10:04:57  	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:91)
10:04:57  	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:80)
10:04:57  	at selenium.webdriverTest.swTestAcademyTitleTest(webdriverTest.java:32)
10:04:57  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:04:57  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:04:57  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:04:57  	at java.lang.reflect.Method.invoke(Method.java:498)
10:04:57  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
10:04:57  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
10:04:57  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
10:04:57  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
10:04:57  	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
10:04:57  	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
10:04:57  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
10:04:57  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
10:04:57  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
10:04:57  	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
10:04:57  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
10:04:57  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
10:04:57  	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
10:04:57  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
10:04:57  	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
10:04:57  	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
10:04:57  	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
10:04:57  	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
10:04:57  	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
10:04:57  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:04:57  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:04:57  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:04:57  	at java.lang.reflect.Method.invoke(Method.java:498)
10:04:57  	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
10:04:57  	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
10:04:57  	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
10:04:57  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
10:04:57  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
10:04:57  
10:04:57  
10:04:57  Results :
10:04:57  
10:04:57  Tests in error: 
10:04:57    swTestAcademyTitleTest(selenium.webdriverTest): Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.(..)
10:04:57  
10:04:57  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
10:04:57  
10:04:57  [INFO] ------------------------------------------------------------------------
10:04:57  [INFO] BUILD FAILURE
10:04:57  [INFO] ------------------------------------------------------------------------
```

### Operating System

Linux

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Google Chrome  99.0.4844.51-1.x86_64

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver(Latest) :  99.0.4844.51 

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
When using a docker image we recommend to use the official docker selenium images from this project. We don't support custom docker images, as the assumption is that the user is well versed in docker to build their own solution.

Please try the docker selenium images and ask more questions on the links below.
