### ISSUE TITLE
Selenium Grid 4, How to match a particular pattern capability in ruby 3.x.x

### ISSUE THREAD

**Issue by user574** [SeleniumHQ/selenium#10508]
### What happened?

I'm unable to match the custom capabilities in ruby code for selenium grid 4 nodes.

As per this documentation: https://www.selenium.dev/documentation/grid/configuration/cli_options/#matching-node-a

I've tried to do the same thing in ruby like below:

1) Started the selenium grid with this command:

```
java -jar ./selenium-server-4.1.2.jar  hub --session-request-timeout 500 --port 4444 --tracing false

```

2) Started Running nodes with the below commands:

```
node a) java -jar selenium-server-4.1.2.jar node --max-sessions 74 --log-level "fine" --port 5555  --driver-implementation "chrome" --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" stereotype='{"browserName":"chrome","custom_key1":"custom_value1"}'

node b) java -jar selenium-server-4.1.2.jar node --max-sessions 74 --log-level "fine" --port 5556  --driver-implementation "chrome" --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" stereotype='{"browserName":"chrome","custom_key2":"custom_value2"}'

```

Then From My Ruby Code, I've tried to connect to the node 'a' which uses custom_key1 and custom_value1 like below:

```


options = Selenium::WebDriver::Chrome::Options.new(args: ['start-maximized'])

caps = {"custom_key1":"custom_value1"}

options.add_option("my_options",caps)

And finally trying to initialize the browser:

driver = Selenium::WebDriver.for(:remote, :url => "http://192.168.29.141:4444", :capabilities => options)

```

So here Im able to get the driver but its getting randomly from the above nodes. If I pass custom_key1 and custom_value1 then I should get the browser from that node 'a' only. But However browser session is getting created in node 'b' too. Im getting browser from node 'b' even after I pass custom_key1 from my code.

Could someone please help me to match this particular nodes with some pattern

### How can we reproduce the issue?

```shell
options = Selenium::WebDriver::Chrome::Options.new(args: ['start-maximized'])

caps = {"custom_key1":"custom_value1"}

options.add_option("my_options",caps)

And finally trying to initialize the browser:

driver = Selenium::WebDriver.for(:remote, :url => "http://192.168.29.141:4444", :capabilities => options)

```
```


### Relevant log output

```shell
browser getting initialized whatever the args we pass
```

### Operating System

ubuntu 18.04

### Selenium version

selenium 4.1.2

### What are the browser(s) and version(s) where you see this issue?

chrome Version 99.0.4844.82 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 99.0.4844.51

### Are you using Selenium Grid?

Selenium Grid 4.1.2 (revision 9a5a329c5a)

**Comment by diemol** [comment]
`custom_key1` and `custom_key2` need to be prefixed with something.

So, `myPrefix:custom_key1`, and in the `caps = {"myPrefix:custom_key1":"custom_value1"}`

**Comment by user574** [comment]
> `custom_key1` and `custom_key2` need to be prefixed with something.
> 
> So, `myPrefix:custom_key1`, and in the `caps = {"myPrefix:custom_key1":"custom_value1"}`


Hi @diemol 

Thanks for the quick reply.

I've started the selenium node as per your suggestion , however Im getting following error. Could you please help me with this?

Running nodes with the below commands:
1)
`java -jar selenium-server-4.1.2.jar node --max-sessions 74 --log-level "fine" --port 5555  --driver-implementation "chrome" --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" stereotype='{"browserName":"chrome","cluster:pcgeo":"hetzner"}'`

2)
` java -jar selenium-server-4.1.2.jar node --max-sessions 74 --log-level "fine" --port 5555  --driver-implementation "chrome" --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" stereotype='{"browserName":"chrome","cluster:pcgeo":"aws}'`

Ruby Code:

```
opt = Selenium::WebDriver::Chrome::Options.new(args: ['start-maximized'])
caps = {"cluster:pcgeo":"hetzner"}
opt.add_option("my_options",caps) 
driver = Selenium::WebDriver.for(:remote, :url =>"http://192.168.29.141:4444" , :capabilities => opt)
```


output :

```
(rdbg) opt
#<Selenium::WebDriver::Chrome::Options:0x00007f5a330fcf50
 @encoded_extensions=[],
 @extensions=[],
 @logging_prefs={},
 @options=
  {:args=>["start-maximized"],
   :prefs=>{},
   :emulation=>{},
   :local_state=>{},
   :exclude_switches=>[],
   :perf_logging_prefs=>{},
   :window_types=>[],
   :browser_name=>"chrome",
   "my_options"=>{:"cluster:pcgeo"=>"hetzner"}},
 @profile=nil>


(rdbg) @ajax_driver = Selenium::WebDriver.for(:remote, :url => "http://192.168.29.141:4444", :capabilities => opt)    # ruby
eval error: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: myOptions
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'mahendhar-Lenovo-V15-IIL', ip: '192.168.29.141', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-105-generic', java.version: '11.0.14'
Driver info: driver.version: unknown
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'mahendhar-Lenovo-V15-IIL', ip: '192.168.29.141', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-105-generic', java.version: '11.0.14'
Driver info: driver.version: unknown
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'mahendhar-Lenovo-V15-IIL', ip: '192.168.29.141', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-105-generic', java.version: '11.0.14'
Driver info: driver.version: unknown
nil
```

**Comment by diemol** [comment]
Do not put it as a nested option, Grid will not match that. Put it at the same level of the other caps.

For more questions, please join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.

**Comment by user574** [comment]
@diemol If I give like this, then following error is coming:

opt1 = Selenium::WebDriver::Chrome::Options.new(args: ['start-maximized'])
caps = {"cluster:pcgeo":"hetzner"}
opt1.add_option(caps)
driver = Selenium::WebDriver.for(:remote, :url =>"http://192.168.29.141:4444" , :capabilities => opt)

output::

```
(rdbg) opt1    # ruby
#<Selenium::WebDriver::Chrome::Options:0x00007f5a3313ea90
 @encoded_extensions=[],
 @extensions=[],
 @logging_prefs={},
 @options=
  {:args=>["start-maximized"],
   :prefs=>{},
   :emulation=>{},
   :local_state=>{},
   :exclude_switches=>[],
   :perf_logging_prefs=>{},
   :window_types=>[],
   :browser_name=>"chrome",
   :"cluster:pcgeo"=>"hetzner",
   {:"cluster:pcgeo"=>"hetzner"}=>nil},
 @profile=nil>


(rdbg) @ajax_driver = Selenium::WebDriver.for(:remote, :url => grid_hub_url, :capabilities => opt1)    # ruby
eval error: undefined method `gsub' for {:"cluster:pcgeo"=>"hetzner"}:Hash

        str.gsub(/_([a-z])/) { Regexp.last_match(1).upcase }
           ^^^^^
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/options.rb:180:in `camel_case'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/options.rb:173:in `convert_json_key'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/options.rb:166:in `block in process_json_hash'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/options.rb:162:in `each'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/options.rb:162:in `each_with_object'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/options.rb:162:in `process_json_hash'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/options.rb:149:in `generate_as_json'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/options.rb:123:in `as_json'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:358:in `block in generate_capabilities'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:345:in `map'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:345:in `generate_capabilities'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:333:in `create_bridge'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/driver.rb:44:in `initialize'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:57:in `new'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:57:in `for'
  /home/mahi/.rvm/gems/ruby-3.1.1@20220217_sdftestupgrade/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver.rb:88:in `for'
  (rdbg)//home/mahi/bin_mahi/diskfetcher_plugins/selenium_diskfetcher_module_v2.rb:1:in `initialize_ajax_driver'
nil



```

**Comment by diemol** [comment]
I am not familiar with the Ruby bindings, I still see the capability being embedded. Maybe you can join the Slack channel and ask your question there.

**Comment by titusfortner** [comment]
I discussed with @user574 on Slack and got the Ruby correct, but it still doesn't seem to be limiting which node is being used.

This is what is getting sent:
```
{"capabilities":{"alwaysMatch":{"browserName":"chrome","cluster:pcgeo":"hetzner","goog:chromeOptions":{"args":["start-maximized"]}}}}
```

This is what is returned:

```
{
  "value": {
    "sessionId": "cdfbf2c87ee034068abb94f128e9b1bc",
    "capabilities": {
      "acceptInsecureCerts": false,
      "browserName": "chrome",
      "browserVersion": "99.0.4844.82",
      "chrome": {
        "chromedriverVersion": "99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs\u002fbranch-heads\u002f4844@{#875})",
        "userDataDir": "\u002ftmp\[u002f.com](http://u002f.com/).google.Chrome.BGNaOG"
      },
      "cluster:pcgeo": "hetzner",
      "goog:chromeOptions": {
        "debuggerAddress": "localhost:44857"
      },
      "networkConnectionEnabled": false,
      "pageLoadStrategy": "normal",
      "platformName": "linux",
      "proxy": {
      },
      "se:cdp": "ws:\u002f\u002f192.168.29.141:4444\u002fsession\u002fcdfbf2c87ee034068abb94f128e9b1bc\u002fse\u002fcdp",
      "se:cdpVersion": "99.0.4844.82",
      "setWindowRect": true,
      "strictFileInteractability": false,
      "timeouts": {
        "implicit": 0,
        "pageLoad": 300000,
        "script": 30000
      },
      "unhandledPromptBehavior": "dismiss and notify",
      "webauthn:extension:credBlob": true,
      "webauthn:extension:largeBlob": true,
      "webauthn:virtualAuthenticators": true
    }
  }
}
```

```
[19:02][mahi]$ java -jar ./selenium-server-4.1.2.jar  hub --session-request-timeout 500 --port 4444 --tracing false
19:02:21.029 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
19:02:21.033 INFO [LoggingOptions.getTracer] - Using null tracer
19:02:21.102 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://192.168.29.141:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://192.168.29.141:4443]
19:02:21.217 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://192.168.29.141:4442 and tcp://192.168.29.141:4443
19:02:21.298 INFO [UnboundZmqEventBus.<init>] - Sockets created
19:02:22.300 INFO [UnboundZmqEventBus.<init>] - Event bus ready
19:02:23.456 INFO [Hub.execute] - Started Selenium Hub 4.1.2 (revision 9a5a329c5a): http://192.168.29.141:4444/
19:02:35.383 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
19:02:36.466 INFO [LocalDistributor.add] - Added node 0c76e1d2-cdc7-443b-96f0-56033da00730 at http://192.168.29.141:5555/. Health check every 120s
19:02:36.514 INFO [GridModel.setAvailability] - Switching node 0c76e1d2-cdc7-443b-96f0-56033da00730 (uri: http://192.168.29.141:5555/) from DOWN to UP
19:02:44.658 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
19:02:45.043 INFO [LocalDistributor.add] - Added node 3e5db3c7-00af-4944-b803-a191c07dd1cf at http://192.168.29.141:5556/. Health check every 120s
19:02:45.092 INFO [GridModel.setAvailability] - Switching node 3e5db3c7-00af-4944-b803-a191c07dd1cf (uri: http://192.168.29.141:5556/) from DOWN to UP
19:03:10.431 INFO [LocalDistributor.newSession] - Session request received by the distributor: 
 [Capabilities {browserName: chrome, cluster:pcgeo: hetzner, goog:chromeOptions: {args: [start-maximized]}}]
19:03:13.987 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: 8b3675442a39fd2faaa410ccddfe8987, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.82, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.9eiRg1}, cluster:pcgeo: hetzner, goog:chromeOptions: {debuggerAddress: localhost:38781}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:cdp: ws://192.168.29.141:4444/se..., se:cdpVersion: 99.0.4844.82, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
```

**Comment by diemol** [comment]
Ok, can you share the Node configs and the test request again?

**Comment by user574** [comment]
I've created the 2 nodes like this:
A)
java -jar selenium-server-4.1.2.jar node --max-sessions 74 --log-level "fine" --port 5555  --driver-implementation "chrome" --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" stereotype='{"browserName":"chrome","cluster:pcgeo":"aws"}'
B)
java -jar selenium-server-4.1.2.jar node --max-sessions 74 --log-level "fine" --port 5556  --driver-implementation "chrome" --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" stereotype='{"browserName":"chrome","cluster:pcgeo":"hetzner"}'

**Comment by mahendharpc** [comment]
The correct command to create the nodes :
```
A)
java -jar selenium-server-4.1.2.jar node --detect-drivers false --log-level "fine" --port 5555   --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74 stereotype='{"browserName":"chrome","cluster:pcgeo":"hetzner"}'
B)
java -jar selenium-server-4.1.2.jar node --detect-drivers false --log-level "fine" --port 5556   --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74 stereotype='{"browserName":"chrome","cluster:pcgeo":"aws"}'
```

Correct code to add ruby options:

```
opt = Selenium::WebDriver::Chrome::Options.new(args: ['start-maximized'])
opt.add_option("cluster:pcgeo","aws_india")
driver = Selenium::WebDriver.for(:remote, :url => "http://192.168.29.141:4444" , :capabilities => opt)
```

**Thanks a lot for your quick response & the best solution** :) 

@diemol @titusfortner

**Comment by user574** [comment]
The correct command to create the nodes :
```
A)
java -jar selenium-server-4.1.2.jar node --detect-drivers false --log-level "fine" --port 5555   --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74 stereotype='{"browserName":"chrome","cluster:pcgeo":"hetzner"}'
B)
java -jar selenium-server-4.1.2.jar node --detect-drivers false --log-level "fine" --port 5556   --override-max-sessions true --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74 stereotype='{"browserName":"chrome","cluster:pcgeo":"aws"}'
```

Correct code to add ruby options:

```
opt = Selenium::WebDriver::Chrome::Options.new(args: ['start-maximized'])
opt.add_option("cluster:pcgeo","aws_india")
driver = Selenium::WebDriver.for(:remote, :url => "http://192.168.29.141:4444" , :capabilities => opt)
```

**Thanks a lot for your quick response & the best solution** :) 

@diemol @titusfortner
