### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by ski123786** [SeleniumHQ/selenium#10502]
### What happened?

The below **java.lang.NoClassDefFoundError for InvalidCoordinatesException** class is generated and no further execution of the code happens while using **selenium-java 4.1.3 version.jar** for creating a HTMLUnitDriver object.  Please refer to the below code snippet. Also, observed that both **selenium-api-4.1.3.jar** and 4.1.3 selenium javadoc are missing InvalidCoordinatesException class reference.

https://www.javadoc.io/doc/org.seleniumhq.selenium/selenium-api/latest/org/openqa/selenium/WebDriverException.html

https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/WebDriverException.html

**Observation**: When a downgraded selenium-java and selenium-api version 4.1.2 are used the below code snippet can be executed even when the below java.lang.NoClassDefFoundError for InvalidCoordinatesException class exception is produced. 

-------------------------------------------------------------------
Exception received while executing the below code snippet.
-------------------------------------------------------------------
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/InvalidCoordinatesException
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.resetKeyboardAndMouseState(HtmlUnitDriver.java:605)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:600)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$get$7(HtmlUnitDriver.java:560)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$runAsync$0(HtmlUnitDriver.java:292)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.interactions.InvalidCoordinatesException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 7 more

### How can we reproduce the issue?

```shell
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.ie.InternetExplorerDriver;
import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.WebClient;

public class InstallDriversTest {

@Test
public void htmlUnitDriver() {
HtmlUnitDriver driver = new HtmlUnitDriver(BrowserVersion.EDGE);
driver.get("https://htmlunit.sourceforge.io/");
}
}
```

### Relevant log output

```shell
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/InvalidCoordinatesException
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.resetKeyboardAndMouseState(HtmlUnitDriver.java:605)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:600)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$get$7(HtmlUnitDriver.java:560)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$runAsync$0(HtmlUnitDriver.java:292)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.interactions.InvalidCoordinatesException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 7 more
```

### Operating System

windows10

### Selenium version

**selenium-java-4.1.3.jar, selenium-api-4.1.3.jar, htmlunit-driver-3.60.0.jar**

### What are the browser(s) and version(s) where you see this issue?

HTMLUnitDriver

### What are the browser driver(s) and version(s) where you see this issue?

**Edge** Version = 99.0.1150.55,  **Chrome** Version= 99.0.4844.84

### Are you using Selenium Grid?

None

**Comment by diemol** [comment]
@titusfortner, what would be a good replacement for `InvalidCoordinatesException`?  

@ski123786, can you please report this to https://github.com/SeleniumHQ/htmlunit-driver, so maybe they can do a new release and remove/replace the class based on @titusfortner recommendation?

**Comment by titusfortner** [comment]
The only usage I see in that code is

> About to perform an interaction that relies on the active element, but there isn't one.")

Per spec, attempting to get an active element when there isn't one should return no such element error.
