### ISSUE TITLE
[🐛 Bug]: ChromeDriver Failed to open new tab

### ISSUE THREAD

**Issue by RameshBabuPrudhvi** [SeleniumHQ/selenium#10504]
### What happened?

ChromeDriver Failed to open new tab

### How can we reproduce the issue?

```shell
ChromeOptions options = new ChromeOptions();
options.addArguments("--incognito");
ChromiumDriver driver = new ChromeDriver(options);
driver.get("https://www.google.com");        
driver.switchTo().newWindow(WindowType.TAB);
```

### Relevant log output

```shell
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [201f8f7d8102097f65a24e565bc8db38, newWindow {type=tab}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 100.0.4896.60, chrome: {chromedriverVersion: 100.0.4896.60 (6a5d10861ce8..., userDataDir: C:\Users\ramesh\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:53997}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:53997/devtoo..., se:cdpVersion: 100.0.4896.60, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 201f8f7d8102097f65a24e565bc8db38
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.newWindow(RemoteWebDriver.java:1095)
```

### Operating System

Windows 10

### Selenium version

4.1.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 100.0.4896.60

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 100.0.4896.60

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Seems to be an issue with Chrome/ChromeDriver, when `options.addArguments("--incognito")` is removed, it works as expected.
