### ISSUE TITLE
[🐛 Bug]: InvocationTargetException while using dynamic Selenium grid 4

### ISSUE THREAD

**Issue by cloudmsdasari** [SeleniumHQ/selenium#10501]
### What happened?

Getting InvocationTargetException while using dynamic Selenium grid 4.

We have downloaded docker compose file (docker-compose-v3-dynamic-grid.yml) from https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-dynamic-grid.yml and created config.toml file using the code from https://github.com/SeleniumHQ/docker-selenium#dynamic-grid without changing anything. The config.toml file is place in NodeDocker folder.

### How can we reproduce the issue?

```shell
selenium-compose.yml:

version: "3"
services:
  node-docker:
    image: selenium/node-docker:latest
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config/config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.1.3-20220327
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

config.toml

[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:latest", "{\"browserName\": \"chrome\"}"
	"selenium/standalone-firefox:latest", "{\"browserName\": \"firefox\"}"
    ]

# URL for connecting to the docker daemon
# Most simple approach, leave it as http://127.0.0.1:2375, and mount /var/run/docker.sock.
# 127.0.0.1 is used because interally the container uses socat when /var/run/docker.sock is mounted 
# If var/run/docker.sock is not mounted: 
# Windows: make sure Docker Desktop exposes the daemon via tcp, and use http://host.docker.internal:2375.
# macOS: install socat and run the following command, socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock,
# then use http://host.docker.internal:2375.
# Linux: varies from machine to machine, please mount /var/run/docker.sock. If this does not work, please create an issue.
url = "http://host.docker.internal:2375"
# Docker image used for video recording
video-image = "selenium/video:latest"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>

Running below docker compose command:

docker-compose -f selenium-compose.yml up
```

### Relevant log output

```shell
selenium-hub    | 2022-03-31 20:24:30,036 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub    | 2022-03-31 20:24:30,039 INFO supervisord started with pid 8
selenium-hub    | 2022-03-31 20:24:31,041 INFO spawned: 'selenium-grid-hub' with pid 10
selenium-hub    | 20:24:31.411 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
selenium-hub    | 2022-03-31 20:24:31,413 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 20:24:31.416 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub    | 20:24:31.517 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.22.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.22.0.2:4443]
selenium-hub    | 20:24:31.567 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.22.0.2:4442 and tcp://172.22.0.2:4443
selenium-hub    | 20:24:31.587 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub    | 20:24:32.589 INFO [UnboundZmqEventBus.<init>] - Event bus ready
selenium-hub    | 20:24:33.198 INFO [Hub.execute] - Started Selenium Hub 4.1.3 (revision 7b1ebf28ef): http://172.22.0.2:4444
selenium-hub    | Trapped SIGTERM/SIGINT/x so shutting down supervisord...
selenium-hub    | 2022-03-31 20:31:13,705 WARN received SIGTERM indicating exit request
selenium-hub    | 2022-03-31 20:31:13,706 INFO waiting for selenium-grid-hub to die
selenium-hub    | 2022-03-31 20:31:14,707 INFO stopped: selenium-grid-hub (terminated by SIGTERM)
selenium-hub    | Shutdown complete
selenium-hub    | 2022-03-31 20:31:35,542 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub    | 2022-03-31 20:31:35,545 INFO supervisord started with pid 9
selenium-hub    | 2022-03-31 20:31:36,547 INFO spawned: 'selenium-grid-hub' with pid 11
selenium-hub    | 20:31:36.964 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
selenium-hub    | 2022-03-31 20:31:36,968 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 20:31:36.971 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub    | 20:31:37.102 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.22.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.22.0.2:4443]
selenium-hub    | 20:31:37.158 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.22.0.2:4442 and tcp://172.22.0.2:4443
selenium-hub    | 20:31:37.181 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub    | 20:31:38.183 INFO [UnboundZmqEventBus.<init>] - Event bus ready
selenium-hub    | 20:31:38.936 INFO [Hub.execute] - Started Selenium Hub 4.1.3 (revision 7b1ebf28ef): http://172.22.0.2:4444
node-docker_1   | 2022-03-31 20:33:12,162 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-docker.conf" during parsing
node-docker_1   | 2022-03-31 20:33:12,165 INFO supervisord started with pid 8
node-docker_1   | 2022-03-31 20:33:13,167 INFO spawned: 'socat' with pid 10
node-docker_1   | 2022-03-31 20:33:13,169 INFO spawned: 'selenium-grid-docker' with pid 11
node-docker_1   | 2022-03-31 20:33:13,176 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
node-docker_1   | 2022-03-31 20:33:13,177 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
node-docker_1   | 2022-03-31 20:33:13,177 INFO exited: socat (exit status 0; expected)
node-docker_1   | Starting Selenium Grid Node Docker...
node-docker_1   | 20:33:13.656 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
node-docker_1   | 20:33:13.663 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
node-docker_1   | 20:33:13.831 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
node-docker_1   | 20:33:13.889 INFO [UnboundZmqEventBus.<init>] - Sockets created
node-docker_1   | 20:33:14.892 INFO [UnboundZmqEventBus.<init>] - Event bus ready
node-docker_1   | 20:33:15.016 INFO [NodeServer.createHandlers] - Reporting self as: http://172.22.0.3:5555
node-docker_1   | 20:33:15.032 INFO [NodeOptions.getSessionFactories] - Detected 12 available processors
node-docker_1   | java.lang.reflect.InvocationTargetException
node-docker_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
node-docker_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
node-docker_1   |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
node-docker_1   |       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
node-docker_1   |       at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
node-docker_1   |       at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
node-docker_1   | Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
node-docker_1   |       at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
node-docker_1   |       at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:149)
node-docker_1   |       at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:127)
node-docker_1   |       at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:183)
node-docker_1   |       at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:231)
node-docker_1   |       at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
node-docker_1   |       at org.openqa.selenium.grid.Main.launch(Main.java:83)
node-docker_1   |       at org.openqa.selenium.grid.Main.go(Main.java:57)
node-docker_1   |       at org.openqa.selenium.grid.Main.main(Main.java:42)
node-docker_1   |       ... 6 more
node-docker_1   | Caused by: java.lang.reflect.InvocationTargetException
node-docker_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
node-docker_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
node-docker_1   |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
node-docker_1   |       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
node-docker_1   |       at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
node-docker_1   |       at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
node-docker_1   |       at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
node-docker_1   |       at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
node-docker_1   |       ... 14 more
node-docker_1   | Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://127.0.0.1:2375
node-docker_1   |       at org.openqa.selenium.grid.node.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:125)
node-docker_1   |       at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
node-docker_1   |       ... 22 more
node-docker_1   | Exception in thread "Thread-0" java.lang.NullPointerException
node-docker_1   |       at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:79)
node-docker_1   |       at java.base/java.lang.Thread.run(Thread.java:829)
node-docker_1   | 2022-03-31 20:33:15,858 INFO exited: selenium-grid-docker (exit status 1; not expected)
```

### Operating System

Windows 10

### Selenium version

Java 4.1.3

### What are the browser(s) and version(s) where you see this issue?

dynamic grid using docker

### What are the browser driver(s) and version(s) where you see this issue?

selenium/node-docker:latest, selenium/standalone-chrome:latest, selenium/standalone-firefox:latest

### Are you using Selenium Grid?

4

**Comment by diemol** [comment]
Compose file example was fixed.
