### ISSUE TITLE
Edge crash at startup

### ISSUE THREAD

**Issue by arsenik** [SeleniumHQ/selenium#1051]
Microsoft Web Driver version 10.0.10240.0
selenium-2.47.3
Win10 64bits

``` 
from selenium import webdriver
b = webdriver.Edge()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 43, in __init__
    desired_capabilities=capabilities)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 87, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 141, in start_session
    'desiredCapabilities': desired_capabilities,
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error 
```

**Comment by lukeis** [comment]
This would be a bug in Microsoft's Edge Driver itself... please log issues with Microsoft - https://connect.microsoft.com/

10240 seems to have various issues... mine can start up edge, but then crashes shortly thereafter doing any command.

I hear that the latest version on the insiders program https://insider.windows.com/  is considerably better... but I can't confirm that myself.

currently I don't see any issue in selenium's python bindings, rather the MS Web Driver is not replying with a proper error message.

**Comment by arsenik** [comment]
Bug opened at Microsoft https://connect.microsoft.com/IE/feedbackdetail/view/1807033/microsoft-web-driver-crashes-edge-at-startup
