### ISSUE TITLE
[🐛 Bug]: Selenium Grid not working with WebView2 application

### ISSUE THREAD

**Issue by pramodkeeliputti12345** [SeleniumHQ/selenium#10527]
### What happened?

Detailed steps to reproduce the behavior:
Run the below c# code

            EdgeOptions edgeOptions = new EdgeOptions();
            edgeOptions.UseChromium = true;
            edgeOptions.UseWebView = true;
            edgeOptions.BinaryLocation = @"C:\MyWebView2App.exe";
            IWebDriver webDriver = new RemoteWebDriver(new Uri("http://127.0.0.1:4444"),edgeOptions);
Below exception occurs:

OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4444/session timed out after 60 seconds.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, DriverOptions options)
   at WebViewTesting.Program.Main(String[] args) in 

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebException: The operation has timed out.

### How can we reproduce the issue?

```shell
The sample test project (WebViewTesting) and sample app (SampleApp) can be found in below git repo.
https://github.com/pramodkeeliputti12345/pramodkeeliputti12345

Start selenium grid 4 (selenium-server-4.0.0-beta-4.jar) in standalone mode.
Load project WebViewTesting in visual studio 2019.
Copy 'SampleApp' folder under c drive.
Run the WebViewTesting application.
Exception occurse @ line number 16. (IWebDriver webDriver = new RemoteWebDriver(new Uri("http://127.0.0.1:4444"),edgeOptions);)

What i am looking is to achieve the below functionality with Selenium Grid.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

This works for EdgeDriver but not working for RemoteWebDriver.
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4444/session timed out after 60 seconds.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, DriverOptions options)
   at WebViewTesting.Program.Main(String[] args) in 

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebException: The operation has timed out.
```

### Operating System

Windows 10

### Selenium version

selenium-server-4.0.0

### What are the browser(s) and version(s) where you see this issue?

Webview2

### What are the browser driver(s) and version(s) where you see this issue?

91.0.864.37

### Are you using Selenium Grid?

4.0.0

**Comment by diemol** [comment]
Did you check my reply in the issue you created? #9714

**Comment by pramodkeeliputti12345** [comment]
Yes . i had logged the defect initially with MicrosoftEdge . please find the below link for the bug which was closed stating it is grid issue.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1679#issue-976717937

**Comment by diemol** [comment]
I believe you did not read my comment completely because what they suggest in the linked issue was what I did a while ago in this commit https://github.com/SeleniumHQ/selenium/commit/2d36ea2cd98af9ae33716e2591edd4e6c9cf126c. This is already part of the most recent release, 4.1.3.

Please check the whole comment, retest and if there is an issue related to Selenium please comment and we can reopen.
