### ISSUE TITLE
[🐛 Bug]: When use diffrent proxy server, the driver can not start

### ISSUE THREAD

**Issue by BurningTeng** [SeleniumHQ/selenium#10535]
### What happened?

Code as below:
```
var task = Task.Run(() =>
{
    SignUtils su = new();
    su.StartProxyServer();
    su.SetProxyPort(8888);

    su.exit = false;
    su.Sign(listPerson[0].name, listPerson[0].email, listPerson[0].password, 8888);
    su.StopProxyServer();
});
task.Wait();

Console.WriteLine("Finish first proxy");

await Task.Delay(10*1000);

task = Task.Run(() =>
{
    SignUtils su = new();

    su.StartProxyServer();
    su.SetProxyPort(9999);
    su.exit = false;
    su.Sign(listPerson[0].name, listPerson[0].email, listPerson[0].password, 9999);
    su.StopProxyServer();
});
task.Wait();
```
Sign function as below:
```
public void Sign(string? name, string? email, string? password, int port)
  {
      using (IWebDriver wd = new EdgeDriver())
      {
          wd.Navigate().GoToUrl("http://kq.neusoft.com/");
          wd.Quit();

      }    
  }
```
I use Titanium as proxy server, when I set diffreent port, the second time will occur following error:
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)

### How can we reproduce the issue?

```shell
You can run the code as https://github.com/BurningTeng/Bill.The second task will occur the issue.
```

### Relevant log output

```shell
The second task will show following log:

由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
```

### Operating System

Win11

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

Chrome 100 and Edge 100.0.1185.36

### What are the browser driver(s) and version(s) where you see this issue?

MSEdgeDriver 99.0.1150.46 (a1c1ea02160226bf4a0831a74f06de8edf55ffcf)

### Are you using Selenium Grid?

No

**Comment by BurningTeng** [comment]
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot start the driver service on http://localhost:55285/)
 ---> OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:55285/
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor()
   at SignSystem.SignUtils.Sign(String name, String email, String password, Int32 port) in D:\vs2022\Project\SignSystem\SignUtils.cs:line 260
   at Program.<>c__DisplayClass0_0.<<Main>$>b__1() in D:\vs2022\Project\SignSystem\Program.cs:line 66
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Program.<Main>$(String[] args) in D:\vs2022\Project\SignSystem\Program.cs:line 72
   at Program.<Main>(String[] args)

**Comment by BurningTeng** [comment]
Above is full  error stack

**Comment by diemol** [comment]
Aside seeing you using .NET 6.0, which we do not support yet, it is really hard to know what is going on because the code needs to be debugged. 

Please provide a simplified version with clear instructions showing how to run the code, what is expected and what is the error happening.

**Comment by BurningTeng** [comment]
You can test the issue by https://github.com/BurningTeng/NeusoftSign/tree/tmp.
1. Buid and run the program.
2. **Then following error will occur:**
```
今年是：2022年
Listening on 'ExplicitProxyEndPoint' endpoint at Ip 0.0.0.0 and port: 9999
Set endpoint at Ip 0.0.0.0 and port: 9999 as System HTTP Proxy
Set endpoint at Ip 0.0.0.0 and port: 9999 as System HTTPS Proxy
Starting MSEdgeDriver 100.0.1185.36 (22972d25db820838a94def61dc345b1a7e9c095a) on port 54652
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
https://edge.microsoft.com/serviceexperimentation/v2/
http://localhost:54652/status

DevTools listening on ws://127.0.0.1:54699/devtools/browser/e0dfd226-7ac8-483a-a239-62c992263847
http://localhost:54652/session
https://nav.smartscreen.microsoft.com/api/browser/edge/actions
http://localhost:54652/shutdown
Listening on 'ExplicitProxyEndPoint' endpoint at Ip 0.0.0.0 and port: 8888
Set endpoint at Ip 0.0.0.0 and port: 8888 as System HTTP Proxy
Set endpoint at Ip 0.0.0.0 and port: 8888 as System HTTPS Proxy
Starting MSEdgeDriver 100.0.1185.36 (22972d25db820838a94def61dc345b1a7e9c095a) on port 54749
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:9999 (localhost:9999)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:9999 (localhost:9999)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:9999 (localhost:9999)
https://teams.events.data.microsoft.com/OneCollector/1.0/
https://teams.events.data.microsoft.com/OneCollector/1.0/
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:9999 (localhost:9999)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:9999 (localhost:9999)
Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot start the driver service on http://localhost:54749/)
 ---> OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:54749/
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor()
   at SignSystem.SignUtils.Sign() in D:\vs2022\Project\SignSystem\SignUtils.cs:line 22
   at Program.<>c__DisplayClass0_0.<<Main>$>b__1() in D:\vs2022\Project\SignSystem\Program.cs:line 38
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait() 
```
**What I expect is the second task can run normally other than exception.**

**Comment by diemol** [comment]
OK, I cloned the repository to run the code and I see the same behaviour. Next thing I did was to isolate the code and find if this is a Selenium issue or not. Therefore, I replaced the code in the `SignUtils.cs` file and used this:

```csharp
namespace SignSystem
{
    internal class SignUtils
    {
        public static void Sign()
        {
            Console.WriteLine("Doing a request...");
            Console.WriteLine(HttpClient.DefaultProxy.GetProxy(new Uri("http://localhost")));
        }
    }
}
```

The idea was to see which proxy was being setup on each case. The output I got after making that change is:
```
???:2022?
Listening on 'ExplicitProxyEndPoint' endpoint at Ip 0.0.0.0 and port: 9999
Set endpoint at Ip 0.0.0.0 and port: 9999 as System HTTP Proxy
Set endpoint at Ip 0.0.0.0 and port: 9999 as System HTTPS Proxy
Doing a request...
http://localhost:9999/
Listening on 'ExplicitProxyEndPoint' endpoint at Ip 0.0.0.0 and port: 8888
Set endpoint at Ip 0.0.0.0 and port: 8888 as System HTTP Proxy
Set endpoint at Ip 0.0.0.0 and port: 8888 as System HTTPS Proxy
Doing a request...
http://localhost:9999/
```
Which shows that for the second task, somehow, the system proxy is not being correctly set to the desired address. Even when Selenium code is not involved. So, please check the code you have to configure the proxy you are using, as this issue you are seeing is not related to Selenium at all.
