### ISSUE TITLE
[🐛 Bug]: ClassNotFoundException org.openqa.selenium.internal.Require

### ISSUE THREAD

**Issue by flimtix** [SeleniumHQ/selenium#10547]
### What happened?

I have a Java Spring Boot application that uses Maven to manage its dependencies.

Since I don't want to download the Selenium driver, I use Selenium Grid as a Docker container. I am using the dynamic grid.

I connect to Selenium using RemoteWebDriver(). On the error, it doesn't matter what option I use.

Now we come to my error. As soon as I call `new RemoteWebDriver()` I get an error that a class was not found. (See relevant log output).

> This is the first time I am working with Selenium.

### How can we reproduce the issue?

```shell
I made a repository in which my whole setup is mapped. The same error message appears there. You can also find a more detailed description of the application setup.
[Repo](https://github.com/21r8390/asdf)

Everything is related to the [docker-compose](https://github.com/21r8390/asdf/blob/master/docker-compose.yml) file. Only that needs to be executed and everything else should build automatically.
```

### Relevant log output

```shell
## Spring Boot
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.6)

2022-04-14 13:53:05.373  INFO 61 --- [           main] asdf.asdf.AsdfApplication                : Starting AsdfApplication using Java 17.0.2 on 1ea3f3fd804e with PID 61 (/target/classes started by root in /)

2022-04-14 13:53:05.376  INFO 61 --- [           main] asdf.asdf.AsdfApplication                : No active profile set, falling back to 1 default profile: "default"

2022-04-14 13:53:06.121  INFO 61 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9080 (http)

2022-04-14 13:53:06.129  INFO 61 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]

2022-04-14 13:53:06.130  INFO 61 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.60]

2022-04-14 13:53:06.212  INFO 61 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext

2022-04-14 13:53:06.212  INFO 61 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 771 ms

2022-04-14 13:53:06.469  INFO 61 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9080 (http) with context path ''

2022-04-14 13:53:06.478  INFO 61 --- [           main] asdf.asdf.AsdfApplication                : Started AsdfApplication in 1.444 seconds (JVM running for 1.755)

2022-04-14 13:53:23.149  INFO 61 --- [nio-9080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'

2022-04-14 13:53:23.149  INFO 61 --- [nio-9080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'

2022-04-14 13:53:23.150  INFO 61 --- [nio-9080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms

2022-04-14 13:53:23.302 ERROR 61 --- [nio-9080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Require] with root cause


java.lang.ClassNotFoundException: org.openqa.selenium.internal.Require

at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]

at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]

at org.openqa.selenium.json.NumberCoercer.<init>(NumberCoercer.java:49) ~[selenium-json-4.1.3.jar:na]

at org.openqa.selenium.json.JsonTypeCoercer.<init>(JsonTypeCoercer.java:71) ~[selenium-json-4.1.3.jar:na]

at org.openqa.selenium.json.JsonTypeCoercer.<init>(JsonTypeCoercer.java:53) ~[selenium-json-4.1.3.jar:na]

at org.openqa.selenium.json.Json.<init>(Json.java:37) ~[selenium-json-4.1.3.jar:na]

at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:100) ~[selenium-remote-driver-3.141.59.jar:na]

at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:94) ~[selenium-remote-driver-3.141.59.jar:na]

at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68) ~[selenium-remote-driver-3.141.59.jar:na]

at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136) ~[selenium-remote-driver-3.141.59.jar:na]

at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[selenium-remote-driver-3.141.59.jar:na]

at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) ~[selenium-remote-driver-3.141.59.jar:na]

at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) ~[selenium-remote-driver-3.141.59.jar:na]

at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144) ~[selenium-remote-driver-3.141.59.jar:na]

at asdf.asdf.AsdfApplication.getUser(AsdfApplication.java:30) ~[classes/:na]

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]

at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]

at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.18.jar:5.3.18]

at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.18.jar:5.3.18]

at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.18.jar:5.3.18]

at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.18.jar:5.3.18]

at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.18.jar:5.3.18]

at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.18.jar:5.3.18]

at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.18.jar:5.3.18]

at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.18.jar:5.3.18]

at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.18.jar:5.3.18]

at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.18.jar:5.3.18]

at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]

at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.18.jar:5.3.18]

at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.60.jar:4.0.FR]

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.60.jar:9.0.60]

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar:5.3.18]

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.18.jar:5.3.18]

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.18.jar:5.3.18]

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar:5.3.18]

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.60.jar:9.0.60]

at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

# Selenium Node:
```
2022-04-14 13:50:39,359 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-docker.conf" during parsing

2022-04-14 13:50:39,361 INFO supervisord started with pid 8

2022-04-14 13:50:40,362 INFO spawned: 'socat' with pid 10

2022-04-14 13:50:40,365 INFO spawned: 'selenium-grid-docker' with pid 11

2022-04-14 13:50:40,369 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2022-04-14 13:50:40,369 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

Starting Selenium Grid Node Docker...

13:50:41.087 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding

13:50:41.096 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

13:50:41.253 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443

13:50:41.323 INFO [UnboundZmqEventBus.<init>] - Sockets created

13:50:42.325 INFO [UnboundZmqEventBus.<init>] - Event bus ready

13:50:42.450 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.0.3:5555

13:50:42.485 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors

13:50:43.182 INFO [V141Docker.isContainerPresent] - Checking if container is present: 60d813c025ab

13:50:43.279 INFO [Docker.getImage] - Obtaining image: selenium/standalone-firefox:4.1.3-20220405

13:50:43.279 INFO [Docker.getImage] - Obtaining image: selenium/standalone-edge:4.1.3-20220405

13:50:43.279 INFO [Docker.getImage] - Obtaining image: selenium/standalone-chrome:4.1.3-20220405

13:50:43.294 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-firefox', tag='4.1.3-20220405', digest='null'}

13:50:43.294 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-chrome', tag='4.1.3-20220405', digest='null'}

13:50:43.294 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-edge', tag='4.1.3-20220405', digest='null'}

13:50:43.400 INFO [Docker.getImage] - Obtaining image: selenium/video:latest

13:50:43.400 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/video', tag='latest', digest='null'}

13:50:43.436 INFO [Docker.getImage] - Obtaining image: selenium/video:latest

13:50:43.439 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/video', tag='latest', digest='null'}

13:50:43.480 INFO [Docker.getImage] - Obtaining image: selenium/standalone-firefox:4.1.3-20220405

13:50:43.484 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-firefox', tag='4.1.3-20220405', digest='null'}

13:50:43.525 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: firefox} to docker image selenium/standalone-firefox:4.1.3-20220405 8 times

13:50:43.525 INFO [Docker.getImage] - Obtaining image: selenium/standalone-chrome:4.1.3-20220405

13:50:43.525 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-chrome', tag='4.1.3-20220405', digest='null'}

13:50:43.604 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: chrome} to docker image selenium/standalone-chrome:4.1.3-20220405 8 times

13:50:43.604 INFO [Docker.getImage] - Obtaining image: selenium/standalone-edge:4.1.3-20220405

13:50:43.605 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-edge', tag='4.1.3-20220405', digest='null'}

13:50:43.633 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: MicrosoftEdge} to docker image selenium/standalone-edge:4.1.3-20220405 8 times

13:50:43.685 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative

13:50:43.826 INFO [NodeServer$1.start] - Starting registration process for Node http://192.168.0.3:5555

13:50:43.827 INFO [NodeServer.execute] - Started Selenium node 4.1.3 (revision 7b1ebf28ef): http://192.168.0.3:5555

13:50:43.859 INFO [NodeServer$1.lambda$start$1] - Sending registration event...

13:50:44.403 INFO [NodeServer.lambda$createHandlers$2] - Node has been added

Trapped SIGTERM/SIGINT/x so shutting down supervisord...

2022-04-14 13:51:55,515 WARN received SIGTERM indicating exit request

2022-04-14 13:51:55,515 INFO waiting for socat, selenium-grid-docker to die

2022-04-14 13:51:56,517 INFO stopped: selenium-grid-docker (terminated by SIGTERM)

2022-04-14 13:51:57,519 INFO stopped: socat (terminated by SIGTERM)

Shutdown complete

2022-04-14 13:52:59,325 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-docker.conf" during parsing

2022-04-14 13:52:59,327 INFO supervisord started with pid 9

2022-04-14 13:53:00,329 INFO spawned: 'socat' with pid 11

2022-04-14 13:53:00,330 INFO spawned: 'selenium-grid-docker' with pid 12

2022-04-14 13:53:00,335 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2022-04-14 13:53:00,335 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

Starting Selenium Grid Node Docker...

13:53:00.842 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding

13:53:00.847 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

13:53:00.985 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443

13:53:01.049 INFO [UnboundZmqEventBus.<init>] - Sockets created

13:53:02.052 INFO [UnboundZmqEventBus.<init>] - Event bus ready

13:53:02.269 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.0.3:5555

13:53:02.342 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors

13:53:03.154 INFO [V141Docker.isContainerPresent] - Checking if container is present: 60d813c025ab

13:53:03.238 INFO [Docker.getImage] - Obtaining image: selenium/standalone-firefox:4.1.3-20220405

13:53:03.239 INFO [Docker.getImage] - Obtaining image: selenium/standalone-chrome:4.1.3-20220405

13:53:03.239 INFO [Docker.getImage] - Obtaining image: selenium/standalone-edge:4.1.3-20220405

13:53:03.241 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-chrome', tag='4.1.3-20220405', digest='null'}

13:53:03.241 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-edge', tag='4.1.3-20220405', digest='null'}

13:53:03.261 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-firefox', tag='4.1.3-20220405', digest='null'}

13:53:03.377 INFO [Docker.getImage] - Obtaining image: selenium/video:latest

13:53:03.377 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/video', tag='latest', digest='null'}

13:53:03.409 INFO [Docker.getImage] - Obtaining image: selenium/video:latest

13:53:03.410 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/video', tag='latest', digest='null'}

13:53:03.453 INFO [Docker.getImage] - Obtaining image: selenium/standalone-firefox:4.1.3-20220405

13:53:03.454 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-firefox', tag='4.1.3-20220405', digest='null'}

13:53:03.507 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: firefox} to docker image selenium/standalone-firefox:4.1.3-20220405 8 times

13:53:03.507 INFO [Docker.getImage] - Obtaining image: selenium/standalone-chrome:4.1.3-20220405

13:53:03.507 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-chrome', tag='4.1.3-20220405', digest='null'}

13:53:03.570 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: chrome} to docker image selenium/standalone-chrome:4.1.3-20220405 8 times

13:53:03.571 INFO [Docker.getImage] - Obtaining image: selenium/standalone-edge:4.1.3-20220405

13:53:03.573 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-edge', tag='4.1.3-20220405', digest='null'}

13:53:03.611 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: MicrosoftEdge} to docker image selenium/standalone-edge:4.1.3-20220405 8 times

13:53:03.672 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative

13:53:03.883 INFO [NodeServer$1.start] - Starting registration process for Node http://192.168.0.3:5555

13:53:03.887 INFO [NodeServer.execute] - Started Selenium node 4.1.3 (revision 7b1ebf28ef): http://192.168.0.3:5555

13:53:03.949 INFO [NodeServer$1.lambda$start$1] - Sending registration event...

13:53:04.687 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
```
## Selenium Hub
```shell
2022-04-14 13:50:38,729 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing

2022-04-14 13:50:38,731 INFO supervisord started with pid 8

2022-04-14 13:50:39,733 INFO spawned: 'selenium-grid-hub' with pid 10

13:50:40.075 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding

2022-04-14 13:50:40,078 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

13:50:40.082 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

13:50:40.211 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://192.168.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://192.168.0.2:4443]

13:50:40.307 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://192.168.0.2:4442 and tcp://192.168.0.2:4443

13:50:40.383 INFO [UnboundZmqEventBus.<init>] - Sockets created

13:50:41.400 INFO [UnboundZmqEventBus.<init>] - Event bus ready

13:50:42.297 INFO [Hub.execute] - Started Selenium Hub 4.1.3 (revision 7b1ebf28ef): http://192.168.0.2:4444

13:50:43.988 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name

13:50:44.387 INFO [GridModel.setAvailability] - Switching node 58ac6c35-2896-4077-b686-8263885d6d34 (uri: http://192.168.0.3:5555) from DOWN to UP

13:50:44.389 INFO [LocalDistributor.add] - Added node 58ac6c35-2896-4077-b686-8263885d6d34 at http://192.168.0.3:5555. Health check every 120s

Trapped SIGTERM/SIGINT/x so shutting down supervisord...

2022-04-14 13:51:58,512 WARN received SIGTERM indicating exit request

2022-04-14 13:51:58,513 INFO waiting for selenium-grid-hub to die

2022-04-14 13:51:59,514 INFO stopped: selenium-grid-hub (terminated by SIGTERM)

Shutdown complete

2022-04-14 13:52:58,667 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing

2022-04-14 13:52:58,668 INFO supervisord started with pid 8

2022-04-14 13:52:59,671 INFO spawned: 'selenium-grid-hub' with pid 10

13:53:00.010 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding

2022-04-14 13:53:00,013 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

13:53:00.016 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

13:53:00.144 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://192.168.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://192.168.0.2:4443]

13:53:00.210 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://192.168.0.2:4442 and tcp://192.168.0.2:4443

13:53:00.234 INFO [UnboundZmqEventBus.<init>] - Sockets created

13:53:01.236 INFO [UnboundZmqEventBus.<init>] - Event bus ready

13:53:02.234 INFO [Hub.execute] - Started Selenium Hub 4.1.3 (revision 7b1ebf28ef): http://192.168.0.2:4444

13:53:04.093 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative

13:53:04.669 INFO [GridModel.setAvailability] - Switching node 7b6ca41e-bce9-4d7a-9402-f51d44e47b39 (uri: http://192.168.0.3:5555) from DOWN to UP

13:53:04.670 INFO [LocalDistributor.add] - Added node 7b6ca41e-bce9-4d7a-9402-f51d44e47b39 at http://192.168.0.3:5555. Health check every 120s
```

### Operating System

Windows 10

### Selenium version

Java 4.1.3

### What are the browser(s) and version(s) where you see this issue?

Chrome: 100.0.4896.75

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver: 100.0.4896.60

### Are you using Selenium Grid?

Dynamic [grid](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.1.3-20220405) with docker 4.1.3-20220405

**Comment by flimtix** [comment]
Also as a note: I get the same error when using Selenium without Grid, Docker and other. Also version `4.1.3 in Java Spring Boot`:
```java
        WebDriverManager.firefoxdriver().setup();

        WebDriver driver = new FirefoxDriver(); // Crashes here

        driver.get("https://www.google.com/");

        System.out.println(driver.getTitle());

        driver.close();
```

**Comment by titusfortner** [comment]
This indicates you should update your WebDriverManager — https://stackoverflow.com/questions/70183609/what-causes-java-lang-noclassdeffounderror-org-openqa-selenium-internal-require

Let us know if that fixes it.

**Comment by flimtix** [comment]
I am already using the latest version of WebDriverManager. 
The same is true if I use the path hardcode. So in other words whenever I use version 4.x.

<details>

```xml
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>5.1.1</version>
		</dependency>
```

</details>

If I use the grid, shouldn't the Docker container itself fetch the latest versions?

**Comment by flimtix** [comment]
@titusfortner  I have now written exactly the same as it said in stackoverflow. With these settings everything works.

**BUT**! there is a big problem with this.
1. selenium 3.x is not compatible with 4.x
2. selenium 3.x has a security vulnerability

**Comment by titusfortner** [comment]
Yeah, you should be using Selenium 4, I didn't realize the accepted answer was Selenium 3. 
I still think this is a dependency issue. Can you follow this and see if there's something that isn't Selenium 4, or that Selenium 4 wants to see but is getting overridden?
https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

**Comment by diemol** [comment]
Closing as we did not get more information.
