### ISSUE TITLE
[🐛 Bug]: ModuleNotFoundError: No module named 'selenium.webdriver.common.devtools.v100'

### ISSUE THREAD

**Issue by jurecuhalev** [SeleniumHQ/selenium#10556]
### What happened?

This is a variation of #10390 - for v100 of Chrome devtools.

### How can we reproduce the issue?

```shell
1. Install Python/Selenium 4.1.3
2. Ensure that browser is on at least version 100
3. Run following snippet:

import asyncio

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.log import Log


async def printConsoleLogs():
  service = Service(executable_path="./driver/chromedriver")
  chrome_options = webdriver.ChromeOptions()
  driver = webdriver.Chrome(service=service)
  driver.get("http://www.google.com")

  async with driver.bidi_connection() as session:
      log = Log(driver, session)
      from selenium.webdriver.common.bidi.console import Console
      async with log.add_listener(Console.ALL) as messages:
          driver.execute_script("console.log('I love cheese')")
      print(messages["message"])

  driver.quit()

asyncio.run(printConsoleLogs())
ModuleNotFoundError: No module named 'selenium.webdriver.common.devtools.v100'
```
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/jure/selenium-test/test.py", line 23, in <module>
    asyncio.run(printConsoleLogs())
  File "/Users/jure/.pyenv/versions/3.9.10/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/jure/.pyenv/versions/3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jure/selenium-test/test.py", line 14, in printConsoleLogs
    async with driver.bidi_connection() as session:
  File "/Users/jure/.pyenv/versions/3.9.10/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/Users/jure/selenium-test/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1577, in bidi_connection
    cdp.import_devtools(version)
  File "/Users/jure/selenium-test/lib/python3.9/site-packages/selenium/webdriver/common/bidi/cdp.py", line 55, in import_devtools
    devtools = importlib.import_module("selenium.webdriver.common.devtools.v{}".format(version))
  File "/Users/jure/.pyenv/versions/3.9.10/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'selenium.webdriver.common.devtools.v100'
```

### Operating System

macOs 12.3.1

### Selenium version

Python 4.1.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 100

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 100.0.4896.60

**Comment by titusfortner** [comment]
Yeah, we need to do another patch release for Python to support v100, thanks for reporting

**Comment by saqibamjad** [comment]
I'm having the same issue for v101. Please let me know if I should be filing another bug for it. Also, is there an ETA for the fix?

**Comment by diemol** [comment]
https://pypi.org/project/selenium/4.1.4/
