### ISSUE TITLE
[🐛 Bug]: RemoteWebDriver - Unexpected error creating WebSocket DevTools session.

### ISSUE THREAD

**Issue by wongkhaimeng** [SeleniumHQ/selenium#10552]
### Issue
This issue happens when attempting to retrieve a Dev Tools session using a `RemoteWebDriver` instance connecting to Selenium hosted on a remote server. In this case, I hosted the grid as **Hub & Node** style where all are hosted in a Kubernetes Cluster.

When retrieving the Dev Tools session, the error logged seems to indicate that the Node **IP Address** and **Port Number** that is being connected to is not responding (either invalid/blocked). Based on the example log output provided, `10.32.129.130:4444` is the Selenium Node **IP Address** and **Port Number** that it is trying to connect to.

### Expected
The **IP Address** is correct, but the **Port Number** used is wrong as the Selenium Node being hosted uses a default port number of 5555, which may explain the failure to connect when retrieving the Dev Tools session.

Is it possible to change the port number used to connect and create Dev Tools session (assuming the wrong port number is the one causing the issue)?

### How can we reproduce the issue?

```shell
// Create options
var options = new OpenQA.Selenium.Chrome.ChromeOptions();
options.AddArguments("--no-sandbox", "--disable-dev-shm-usage", "--disable-gpu", "--disable-cache", "--disable-infobars", "--window-size=1366,768", "--start-maximized", "--disable-extensions", "--remote-debugging-port=9230", "--disable-blink-features=AutomationControlled", "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36");

// Create Driver
var driver = new OpenQA.Selenium.Remote.RemoteWebDriver(new Uri("http://<Selenium Hub IP>:4444/wd/hub"), options.ToCapabilities(), TimeSpan.FromMinutes(1));

// Start DevTools session (Error here)
var devToolsSession = driver.GetDevToolsSession();
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverException: Unexpected error creating WebSocket DevTools session.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10.32.129.130:4444)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at OpenQA.Selenium.DevTools.DevToolsSession.InitializeSocketConnection()
   at OpenQA.Selenium.DevTools.DevToolsSession.StartSession(Int32 requestedProtocolVersion)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession(Int32 protocolVersion)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession(Int32 protocolVersion)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession()
   ...
```

### Operating System

Google Kubernetes Engine Cluster

### Selenium version

C# 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 100

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 100.0.4896.60

### Are you using Selenium Grid?

4.1.3

**Comment by wongkhaimeng** [comment]
I noticed that when triggering LiveView VNC for an existing session using Selenium Hub & Node hosting at `http://<Hub IP Address>:4444/ui/index.html#/sessions`, the link for the VNC is `ws://<Hub IP Address>:4444/session/<session ID>/se/vnc` (Which is not using the Selenium Node IP Address).

Perhaps the current issue is due to the IP Address used, in which case it should be using the Selenium Hub IP Address instead of the Selenium Node IP Address? If so, is there a way to set the IP Address for the `se:cdp` capability? Or maybe the library could be updated to compare the IP Address used for the `RemoteWebDriver` vs the IP Address used for `se:cdp`, and update the value accordingly?

**Comment by wongkhaimeng** [comment]
Tested using locally hosted Selenium Standalone and using `RemoteWebDriver` to connect and create `IDevTools` session, same issue as above. I believe `RemoteWebDriver` instances cannot start any `IDevTools` session as the IP Address retrieved from `se:cdp` is not replaced with the appropriate IP Address (localhost, exposed IP Address of the Selenium Standalone/Selenium Hub)

**Comment by diemol** [comment]
The `se:cdp` URL is built when the Node creates the session. However, the Node does not have a way to know what the public IP of the Grid is (the one you use to send your tests to). That is why it has to be configured through the [`--grid-url`](https://www.selenium.dev/documentation/grid/configuration/cli_options/#node) flag. When you do that, the `se:cdp` URL will have the correct value for your use case.

**Comment by wongkhaimeng** [comment]
@diemol Thank you for the reply. I did not realize that the parameter is used by the `se:cdp` URL. It is working now. Thank you very much for the guidance.

**Comment by burkasaurusrex** [comment]
@diemol is there a way to set the grid URL for a standalone container instead of a grid (e.g. standalone-chrome)? Running into the same issue as above where the `se:cdp` is building an internal IP address within the standalone container. Ideally it would be great to set with an environment variable, but it seems like `GRID_URL` isn't working.

Edit: nevermind, just found it. For posterity, the docker env is `SE_NODE_GRID_URL`
