### ISSUE TITLE
[🐛 Bug]: 'NetworkManager.OnRequestPaused' event throwing exception instead of catching, causing application to crash

### ISSUE THREAD

**Issue by wongkhaimeng** [SeleniumHQ/selenium#10564]
### What happened?

Selenium WebDriver's `NetworkManager.OnRequestPaused` event is throwing exception when it should be catching it. This is causing the application to crash due to the uncaught exception.

### How can we reproduce the issue?

```shell
// Create options
var options = new OpenQA.Selenium.Chrome.ChromeOptions();
options.AddArguments("--no-sandbox", "--disable-dev-shm-usage", "--headless", "--disable-gpu", "--disable-cache", "--disable-infobars", "--window-size=1366,768", "--start-maximized", "--disable-extensions", "--remote-debugging-port=9230", "--disable-blink-features=AutomationControlled", "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36");

// Create Driver
var driver = new OpenQA.Selenium.Chrome.ChromeDriver(options);

// Start DevTools session (Sometimes there will be error after this line if the 'NetworkManager.OnRequestPaused' event throws an exception)
var devToolsSession = driver.GetDevToolsSession();
```

### Relevant log output

```shell
Unhandled exception. System.InvalidOperationException: A command response was not received: Fetch.continueRequest
 at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand(String commandName, JToken commandParameters, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
 at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand[TCommand,TCommandResponse](TCommand command, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
 at OpenQA.Selenium.DevTools.V96.Fetch.FetchAdapter.ContinueRequest(ContinueRequestCommandSettings command, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
 at OpenQA.Selenium.DevTools.V96.V96Network.ContinueRequestWithoutModification(HttpRequestData requestData)
 at OpenQA.Selenium.NetworkManager.OnRequestPaused(Object sender, RequestPausedEventArgs e)
 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
 at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
 at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
 at System.Threading.QueueUserWorkItemCallback.Execute()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
 at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Operating System

Google Kubernetes Engine Cluster

### Selenium version

C# 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 100

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 100.0.4896.60

### Are you using Selenium Grid?

no

**Comment by wongkhaimeng** [comment]
Different error here, but still same method causing issue
```
Unhandled exception. System.OperationCanceledException: The operation was canceled.
 ---> System.IO.IOException: Cannot access a closed stream.
 at System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
 at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
 at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
 at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
 --- End of stack trace from previous location ---
 at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
 at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
 at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand(String commandName, JToken commandParameters, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
 at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand[TCommand,TCommandResponse](TCommand command, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
 at OpenQA.Selenium.DevTools.V96.Fetch.FetchAdapter.ContinueRequest(ContinueRequestCommandSettings command, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
 at OpenQA.Selenium.DevTools.V96.V96Network.ContinueRequestWithoutModification(HttpRequestData requestData)
 at OpenQA.Selenium.NetworkManager.OnRequestPaused(Object sender, RequestPausedEventArgs e)
 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
 at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
 at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
 at System.Threading.QueueUserWorkItemCallback.Execute()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
 at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by wongkhaimeng** [comment]
So far, this issue happens after the application disposed the first instance of `IWebDriver`, which resulted in the session being destroyed. Then it tried to get a new DevTools session on another new instance of `IWebDriver` session, which frequently failed on the method above.

**Comment by wongkhaimeng** [comment]
Missing exception catching at `Network.OnResponsePaused` as well. This exception seems to be happening when the DevTools Session is closed before the event is triggered.


```
Unhandled exception. OpenQA.Selenium.DevTools.CommandResponseException: Fetch.getResponseBody: Fetch domain is not enabled
 at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand(String commandName, JToken commandParameters, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
 at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand[TCommand,TCommandResponse](TCommand command, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
 at OpenQA.Selenium.DevTools.V96.Fetch.FetchAdapter.GetResponseBody(GetResponseBodyCommandSettings command, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
 at OpenQA.Selenium.DevTools.V96.V96Network.AddResponseBody(HttpResponseData responseData)
 at OpenQA.Selenium.NetworkManager.OnResponsePaused(Object sender, ResponsePausedEventArgs e)
 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
 at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
 at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
 at System.Threading.QueueUserWorkItemCallback.Execute()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
 at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
 at System.Threading.Thread.StartCallback()
```

**Comment by pujagani** [comment]
> So far, this issue happens after the application disposed the first instance of `IWebDriver`, which resulted in the session being destroyed. Then it tried to get a new DevTools session on another new instance of `IWebDriver` session, which frequently failed on the method above.

Thank you for sharing the details. So in order to reproduce the issue, using the example above as one part of it, one would need to first need to close a WebDriver instance and then create another one and start a devtools session to see the error? Are you still seeing the same error with the latest C# bindings https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.4.0 ?

**Comment by bobylevm** [comment]
Hi. The same error occurred while using NetworkAuthenticationHandler.
`
var browserOptions = new ChromeOptions();
browserOptions.AddArgument("headless");
var driver = new RemoteWebDriver(new Uri("http://testselen.avp-test.ru:4444/wd/hub"), browserOptions.ToCapabilities(), new TimeSpan(0, 5, 0));
`

**Comment by bobylevm** [comment]
Hi. The same error sometimes occurs when using  NetworkAuthenticationHandler for **domain** authentication. (HTTP/NTLM at test site  https://authenticationtest.com/ works great)
Selenium standalone 4.5.3, Selenium.Support 4.5.1, C# .NET 6.0, Chrome 107.0.5304.63, Chromedriver 107.0.5304.62

System.InvalidOperationException
  HResult=0x80131509
  Message=A command response was not received: Fetch.continueRequest
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.DevTools.DevToolsSession.<SendCommand>d__35.MoveNext()
   at OpenQA.Selenium.DevTools.DevToolsSession.<SendCommand>d__34`2.MoveNext()
   at OpenQA.Selenium.DevTools.V106.Fetch.FetchAdapter.<ContinueRequest>d__16.MoveNext()
   at OpenQA.Selenium.DevTools.V106.V106Network.<ContinueResponseWithoutModification>d__16.MoveNext()
   at OpenQA.Selenium.NetworkManager.<OnResponsePaused>d__21.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()


`                var browserOptions = new ChromeOptions();
                browserOptions.AddArgument("headless");

                var driver = new RemoteWebDriver(new Uri("http://seleniumhub:4444/wd/hub"), browserOptions.ToCapabilities(), new TimeSpan(0, 5, 0));

                NetworkAuthenticationHandler handler = new NetworkAuthenticationHandler()
                {
                    UriMatcher = (d) => d.Host.Contains("your-domain.com"),
                    Credentials = new PasswordCredentials("admin@your-domain.com", "password")
                };
                INetwork networkInterceptor = driver.Manage().Network;
                networkInterceptor.AddAuthenticationHandler(handler);

                networkInterceptor.StartMonitoring().Wait();;

                driver.Navigate().GoToUrl(new Uri("https://site.your-domain.com"));
                
                networkInterceptor.StopMonitoring().Wait();;
                driver.Quit();`

**Comment by bobylevm** [comment]
I have performed a little bit investigation. To reproduce the issue you need a windows domain and default site with Windows Authentication.
        static void Main(string[] args)
        {
            var browserOptions = new ChromeOptions();
            var driver = new RemoteWebDriver(new Uri("http://testselen.your-domain.com:4444/wd/hub"),
                    browserOptions.ToCapabilities(), new TimeSpan(0, 5, 0));
            NetworkAuthenticationHandler handler = new NetworkAuthenticationHandler()
            {
                UriMatcher = (d) => d.Host.Contains("your-domain.com"),
                Credentials = new PasswordCredentials("admin@your-domain.com", "password")
            };
            INetwork networkInterceptor = driver.Manage().Network;
            networkInterceptor.AddAuthenticationHandler(handler);
            networkInterceptor.StartMonitoring().Wait();

            driver.Navigate().GoToUrl(new Uri("https://site.your-domain.com"));
            networkInterceptor.StopMonitoring().Wait();

            driver.Quit();

            Console.WriteLine($@"{DateTime.UtcNow} - driver closed");
            Thread.Sleep(10000);
        }

Unhandled exception is thrown after driver.Quit();
Here are exception from selenium logs:
15:01:02.400 WARN [ProxyNodeWebsockets$ForwardingListener.onError] - Error proxying websocket command
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by bobylevm** [comment]
And if you add a little sleep after networkInterceptor.StopMonitoring().Wait(); and before driver.Quit(); than all works as expected.

`            networkInterceptor.StopMonitoring().Wait();
            Thread.Sleep(100);
            driver.Quit();`

**Comment by pujagani** [comment]
@bobylevm Thank you for the details. I tried to reproduce using the code snippet shared in https://github.com/SeleniumHQ/selenium/issues/10564#issuecomment-1291912634. The issue is intermittent and occurred once in multiple runs. I am yet to try out https://github.com/SeleniumHQ/selenium/issues/10564#issuecomment-1294947327 to see if it can be reproduced consistently. I have added it to my work queue.

**Comment by hheexx** [comment]
I have problem that may be related.
After some time we also dispose and recreate WD driver.
After that some navigations fail with same error:

System.InvalidOperationException: A command response was not received: Page.navigate

**Comment by nvborisenko** [comment]
Please try the latest 4.12.2 version, DevTools area was significantly improved.

**Comment by nvborisenko** [comment]
Feel free to open new issue if it still occurs on the latest selenium version.
