### ISSUE TITLE
[🐛 Bug]: unable to connect the node to the hub: Could not bind to address or port is already in use

### ISSUE THREAD

**Issue by shettypriy** [SeleniumHQ/selenium#10576]
### What happened?

We are using AWS EC2 instance with OS version debian 9 and trying to start a selenium node version 4 on the EC2 instance using the below command , but it is giving the error as "Could not bind to address or port is already in use"

java -jar selenium-server-4.1.2.jar node --host $public_ip --hub  http://127.0.0.1:35577/wd/hub --publish-events tcp://127.0.0.1:5442 --subscribe-events tcp://127.0.0.1:5443 --detect-drivers false --log-level "fine" --port 5555 --override-max-sessions true --max-sessions 74 --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74  stereotype='{"browserName":"chrome","cluster:pcgeo":"geo"}'

The  hub is running on a normal linux machine with debian 11 . To connect to the hub which is installed on the linux machine, on EC2 instance we are using port forwarding and the hub is behind a haproxy load balancer. So the local port 35577 on the EC2 instance will make a connection to the frontend haproxy bind port 35555 which will forward the requests to the linux machine (debian11) where the hub is running on the port 4444

Even though there are no process running on the port 5555 on EC2 instance we still get the error as 'Could not bind to address or port is already in use'. Selecting a random port for the node is giving the same error.

### How can we reproduce the issue?

```shell
java -jar selenium-server-4.1.2.jar node --host $public_ip --hub  http://127.0.0.1:35577/wd/hub --publish-events tcp://127.0.0.1:5442 --subscribe-events tcp://127.0.0.1:5443 --detect-drivers false --log-level "fine" --port 5555 --override-max-sessions true --max-sessions 74 --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74  stereotype='{"browserName":"chrome","cluster:pcgeo":"geo"}'
```

### Relevant log output

```shell
[07:09][sdf@ip-172-31-15-152:selenium-server]$ java -jar selenium-server-4.1.2.jar node --host $public_ip --hub  http://127.0.0.1:35577/wd/hub --publish-events tcp://127.0.0.1:5442 --subscribe-events tcp://127.0.0.1:5443 --detect-drivers false 
--log-level "fine" --port 57843 --override-max-sessions true --max-sessions 74 --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74 stereotype='{"browserName":"chrome","cluster:pcgeo":"aws_paris"}'
07:10:05.343 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
07:10:05.350 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
07:10:05.509 DEBUG [AutoConfiguredOpenTelemetrySdkBuilder.build] - Global OpenTelemetrySdk set to OpenTelemetrySdk{tracerP
rovider=SdkTracerProvider{clock=SystemClock{}, idGenerator=RandomIdGenerator{}, resource=Resource{schemaUrl=https://opente
lemetry.io/schemas/1.8.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.na
me="opentelemetry", telemetry.sdk.version="1.10.1"}}, spanLimitsSupplier=SpanLimitsValue{maxNumberOfAttributes=128, maxNum
berOfEvents=128, maxNumberOfLinks=128, maxNumberOfAttributesPerEvent=128, maxNumberOfAttributesPerLink=128, maxAttributeVa
lueLength=2147483647}, sampler=ParentBased{root:AlwaysOnSampler,remoteParentSampled:AlwaysOnSampler,remoteParentNotSampled
:AlwaysOffSampler,localParentSampled:AlwaysOnSampler,localParentNotSampled:AlwaysOffSampler}, spanProcessor=SimpleSpanProc
essor{spanExporter=org.openqa.selenium.remote.tracing.opentelemetry.SeleniumSpanExporter$1@16267862}}} by autoconfiguration
07:10:05.614 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://127.0.0.1:5442 and tcp://127.0.0.1:5443
07:10:05.700 INFO [UnboundZmqEventBus.<init>] - Sockets created
07:10:06.704 INFO [UnboundZmqEventBus.<init>] - Event bus ready
07:10:07.119 INFO [NodeServer.createHandlers] - Reporting self as: http://public_ip_of_ec2:5555
07:10:07.165 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
07:10:07.166 WARN [NodeOptions.getSessionFactories] - Overriding max recommended number of 1 concurrent sessions. Session 
stability and reliability might suffer!
07:10:07.166 WARN [NodeOptions.getSessionFactories] - One browser session is recommended per available processor. Safari is always limited to 1 session per host.
07:10:07.167 WARN [NodeOptions.getSessionFactories] - Overriding this value for Internet Explorer is not recommended. Issues related to parallel testing with Internet Explored won't be accepted.
07:10:07.167 WARN [NodeOptions.getSessionFactories] - Double check if enabling 'override-max-sessions' is really needed
07:10:07.169 WARN [NodeOptions.getSessionFactories] - Max sessions set to 74 
07:10:07.273 DEBUG [NodeOptions.getDriverMaxSessions] - Overriding max recommended number of 1 concurrent sessions for Chrome, setting it to 74
07:10:07.336 INFO [NodeOptions.report] - Adding ip-private-ip for {"browserName": "chrome","cluster:pcgeo": "geo","platformName": "LINUX"} 74 times
07:10:07.474 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
07:10:07.609 DEBUG [MultithreadEventLoopGroup.<clinit>] - -Dio.netty.eventLoopThreads: 2
07:10:07.660 DEBUG [InternalThreadLocalMap.<clinit>] - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
07:10:07.663 DEBUG [InternalThreadLocalMap.<clinit>] - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
07:10:07.734 DEBUG [PlatformDependent0.explicitNoUnsafeCause0] - -Dio.netty.noUnsafe: false
07:10:07.734 DEBUG [PlatformDependent0.javaVersion0] - Java version: 11
07:10:07.736 DEBUG [PlatformDependent0.<clinit>] - sun.misc.Unsafe.theUnsafe: available
07:10:07.740 DEBUG [PlatformDependent0.<clinit>] - sun.misc.Unsafe.copyMemory: available
07:10:07.741 DEBUG [PlatformDependent0.<clinit>] - java.nio.Buffer.address: available
07:10:07.742 DEBUG [PlatformDependent0.<clinit>] - direct buffer constructor: unavailable: Reflective setAccessible(true) disabled
07:10:07.742 DEBUG [PlatformDependent0.<clinit>] - java.nio.Bits.unaligned: available, true
07:10:07.743 DEBUG [PlatformDependent0.<clinit>] - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @c4ed84
07:10:07.744 DEBUG [PlatformDependent0.<clinit>] - java.nio.DirectByteBuffer.<init>(long, int): unavailable
07:10:07.745 DEBUG [PlatformDependent.unsafeUnavailabilityCause0] - sun.misc.Unsafe: available
07:10:07.749 DEBUG [PlatformDependent.maxDirectMemory0] - maxDirectMemory: 508887040 bytes (maybe)
07:10:07.757 DEBUG [PlatformDependent.tmpdir0] - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
07:10:07.757 DEBUG [PlatformDependent.bitMode0] - -Dio.netty.bitMode: 64 (sun.arch.data.model)
07:10:07.758 DEBUG [PlatformDependent.<clinit>] - -Dio.netty.maxDirectMemory: -1 bytes
07:10:07.761 DEBUG [PlatformDependent.<clinit>] - -Dio.netty.uninitializedArrayAllocationThreshold: -1
07:10:07.762 DEBUG [CleanerJava9.<clinit>] - java.nio.ByteBuffer.cleaner(): available
07:10:07.764 DEBUG [PlatformDependent.<clinit>] - -Dio.netty.noPreferDirect: false
07:10:07.766 DEBUG [NioEventLoop.<clinit>] - -Dio.netty.noKeySetOptimization: false
07:10:07.770 DEBUG [NioEventLoop.<clinit>] - -Dio.netty.selectorAutoRebuildThreshold: 512
07:10:07.780 DEBUG [PlatformDependent$Mpsc.<clinit>] - org.jctools-core.MpscChunkedArrayQueue: available
07:10:07.835 DEBUG [DefaultChannelId.<clinit>] - -Dio.netty.processId: 38260 (auto-detected)
07:10:07.839 DEBUG [NetUtil.<clinit>] - -Djava.net.preferIPv4Stack: false
07:10:07.839 DEBUG [NetUtil.<clinit>] - -Djava.net.preferIPv6Addresses: false
07:10:07.846 DEBUG [NetUtilInitializations.determineLoopback] - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
07:10:07.847 DEBUG [NetUtil$1.run] - /proc/sys/net/core/somaxconn: 128
07:10:07.849 DEBUG [DefaultChannelId.<clinit>] - -Dio.netty.machineId: 06:66:21:ff:fe:37:18:90 (auto-detected)
07:10:07.868 DEBUG [ResourceLeakDetector.<clinit>] - -Dio.netty.leakDetection.level: simple
07:10:07.874 DEBUG [ResourceLeakDetector.<clinit>] - -Dio.netty.leakDetection.targetRecords: 4
07:10:07.922 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.numHeapArenas: 2
07:10:07.922 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.numDirectArenas: 2
07:10:07.922 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.pageSize: 8192
07:10:07.923 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.maxOrder: 11
07:10:07.923 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.chunkSize: 16777216
07:10:07.923 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.smallCacheSize: 256
07:10:07.923 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.normalCacheSize: 64
07:10:07.924 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
07:10:07.924 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.cacheTrimInterval: 8192
07:10:07.924 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
07:10:07.925 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.useCacheForAllThreads: true
07:10:07.925 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
07:10:07.943 DEBUG [ByteBufUtil.<clinit>] - -Dio.netty.allocator.type: pooled
07:10:07.944 DEBUG [ByteBufUtil.<clinit>] - -Dio.netty.threadLocalDirectBufferSize: 0
07:10:07.944 DEBUG [ByteBufUtil.<clinit>] - -Dio.netty.maxThreadLocalCharBufferSize: 16384
07:10:07.977 DEBUG [LoggingHandler.channelRegistered] - [id: 0x56c341a2] REGISTERED
07:10:07.979 DEBUG [LoggingHandler.bind] - [id: 0x56c341a2] BIND: /public_ip:57843
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.netty.server.ServerBindException: Could not bind to address or port is already in use. Host public_ip_of_ec2, Port 5555
        at org.openqa.selenium.netty.server.NettyServer.start(NettyServer.java:169)
        at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:191)
        at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:188)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:230)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
       at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
        ... 6 more
Caused by: java.net.BindException: Cannot assign requested address
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:459)
        at java.base/sun.nio.ch.Net.bind(Net.java:448)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
        at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
07:10:08.014 DEBUG [LoggingHandler.close] - [id: 0x56c341a2] CLOSE
07:10:08.016 DEBUG [LoggingHandler.channelUnregistered] - [id: 0x56c341a2] UNREGISTERED
```

### Operating System

debian 11, debian 9

### Selenium version

selenium version 4

### What are the browser(s) and version(s) where you see this issue?

chrome browser and  version 99

### What are the browser driver(s) and version(s) where you see this issue?

chromdriver 99

### Are you using Selenium Grid?

yes

**Comment by diemol** [comment]
Please use
> `--bind-host`
> Whether the server should  bind to the host address/name, or only use it to" report its reachable  url. Helpful in complex network topologies where the server cannot  report itself with the current IP/hostname but rather an external IP or  hostname (e.g. inside a Docker container)

https://www.selenium.dev/documentation/grid/configuration/cli_options/#server

**Comment by shettypriy** [comment]
I was able to fix the issue, thanks, however, now the node is not connecting to the hub and it gets stuck at Sending registration event. I am using the following command

 /usr/bin/java -jar selenium-server-4.1.2.jar node --hub  http://127.0.0.1:35577/wd/hub --publish-events tcp://127.0.0.1:5442 --subscribe-events tcp://127.0.0.1:5443 --detect-drivers false --log-level "fine" --port 5555 --override-max-sessions true --max-sessions 74 --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74  stereotype='{"browserName":"chrome","cluster:pcgeo":"geo"}'


13:35:32.103 DEBUG [LoggingHandler.channelRegistered] - [id: 0xa13720e2] REGISTERED
13:35:32.105 DEBUG [LoggingHandler.bind] - [id: 0xa13720e2] BIND: /0.0.0.0:5555
13:35:32.113 INFO [NodeServer$1.start] - Starting registration process for node id ba5cb923-b098-415c-9dc0-3790ac2928ea
13:35:32.116 DEBUG [LoggingHandler.channelActive] - [id: 0xa13720e2, L:/0:0:0:0:0:0:0:0:5555] ACTIVE
13:35:32.117 INFO [NodeServer.execute] - Started Selenium node 4.1.2 (revision 9a5a329c5a): http://private_ip_of_ec2:5555
13:35:32.166 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
13:35:42.203 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
13:35:52.233 INFO [NodeServer$1.lambda$start$1] - Sending registration event...


'

**Comment by diemol** [comment]
`--publish-events tcp://127.0.0.1:5442 --subscribe-events tcp://127.0.0.1:5443` 

those IPs and ports need to be the ones where the Hub is running

**Comment by shettypriy** [comment]
The hub is behind haproxy servers. We are using the ssh port forwarding on the AWS EC2 instances so that it connects to the hub via haproxy servers. 5442 and 5443 are the local ssh port forwarding ports on EC2 instance which will connect to the bind ports of haproxy servers and then forward to the hub ports 4442 and 4443.
