### ISSUE TITLE
[🐛 Bug]: OpenQA.Selenium.WebDriverException: 'Cannot start the driver service on http://localhost:59166/'

### ISSUE THREAD

**Issue by QA1980** [SeleniumHQ/selenium#10586]
### What happened?

My MStest test script works as a charm using Selenium 3.141.0 version. After I upgraded to the latest version 4.1.0 , I have started getting This error only in Firefox session

### How can we reproduce the issue?

```shell
- Create .NET 3.1 mstest project 
- Firefox driver latest version or previous ( any version) 
-Add selenium 4.1.0 
- Run test
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=Cannot start the driver service on http://localhost:59166/
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options)
   at bPerxDynamocData.bPerxVoucherCall.InitializeClass(TestContext TestContext) in C:\Users\Karim\source\repos\bPerxDynamocData\configuration\bPerxVoucherCall.cs:line 67
```

### Operating System

windows 10

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 90

### What are the browser driver(s) and version(s) where you see this issue?

Firefox driver v0.27.0

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Also, please be aware that Selenium 4 needs GeckoDriver 0.30.0 or higher.

**Comment by QA1980** [comment]
@diemol Removed Selenium.Firefox.WebDriver v0.27.0 and added Selenium.WebDriver.GeckoDriver v0.31.0 from my NuGet solution has solved my issue. Very appreciated for help :)

**Comment by diemol** [comment]
Great.
