### ISSUE TITLE
[🐛 Bug]: The "Unexpected error creating WebSocket DevTools session." error is thrown after attempt to get the DevTools Session

### ISSUE THREAD

**Issue by whereismyai** [SeleniumHQ/selenium#10675]
### What happened?

Hello, Currently we are working on additional logging using the DevTools protocol
Unfortunately, after Google Chrome updated to the 101.0.4951.67 version, there is no way to initialize the devTools session because of the following error:
```
Unexpected error creating WebSocket DevTools session
Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

The initialized driver has the following properties:
```
{{
  "acceptInsecureCerts": false,
  "browserName": "chrome",
  "browserVersion": "101.0.4951.67",
  "chrome": {
    "chromedriverVersion": "101.0.4951.41 (93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904})",
    "userDataDir": "C:\\Users\\Office\\AppData\\Local\\Temp\\scoped_dir14936_1859885920"
  },
  "goog:chromeOptions": {
    "debuggerAddress": "localhost:58932"
  },
  "networkConnectionEnabled": false,
  "pageLoadStrategy": "normal",
  "platformName": "windows",
  "proxy": {},
  "setWindowRect": true,
  "strictFileInteractability": false,
  "timeouts": {
    "implicit": 0,
    "pageLoad": 300000,
    "script": 30000
  },
  "unhandledPromptBehavior": "dismiss and notify",
  "webauthn:extension:credBlob": true,
  "webauthn:extension:largeBlob": true,
  "webauthn:virtualAuthenticators": true
}}

```

### How can we reproduce the issue?

```shell
var devTools = (IDevTools)driver;
var session = devTools.GetDevToolsSession();   // The error will be thrown here
_domains = session.GetVersionSpecificDomains<DevToolsVer.DevToolsSessionDomains>();
_domains.Network.Enable(new EnableCommandSettings()).GetAwaiter().GetResult();
```
```


### Relevant log output

```shell
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=Unexpected error creating WebSocket DevTools session.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession(Int32 devToolsProtocolVersion)
   at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession()
   at DashworksTestAutomationCore.Utils.Diagnostics.ApiRequest.ApiRequestRecordingService..ctor(WebDriver driver) in C:\Users\Office\Source\Repos\dashworksTesting\dashworks\SpecFlow\DashworksTestAutomationCore\Utils\Diagnostics\ApiRequest\ApiRequestRecordingService.cs:line 23
   at DashworksTestAutomation.Base.BeforeAfterActions.OnStartUp() in C:\Users\Office\Source\Repos\dashworksTesting\dashworks\SpecFlow\DashworksTestAutomationCore\Base\BeforeAfterActions.cs:line 114

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

### Operating System

Windows 10 

### Selenium version

C# 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 101.0.4951.67

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 101.0.4951.41

**Comment by titusfortner** [comment]
Update to 4.1.1 and see if that fixes it
https://www.nuget.org/packages/Selenium.WebDriver/4.1.1

**Comment by whereismyai** [comment]
> Update to 4.1.1 and see if that fixes it https://www.nuget.org/packages/Selenium.WebDriver/4.1.1

Yep. It works now. Thanks
