### ISSUE TITLE
[🐛 Bug]: Open.Selenium.InvalidStateException was occurred using IE.

### ISSUE THREAD

**Issue by neko3cs** [SeleniumHQ/selenium#10694]
### What happened?

Open.Selenium.InvalidStateException was occurred using IE.

For details and reproduction methods, I wonder if you check items after 'How can we reproduce the issue?'.

This exception is occured at InternetExplorerDriver, is not occured at EdgeDriver.

I test this 👆 change to EdgeDriver class from InternetExplorerDriver class, test has all passed.

Sorry for my poor english, thank you.

### How can we reproduce the issue?

```shell
The implementation is like this:


private readonly IWebDriver _webDriver; // selenium process run class field.

...

public ctor(string webDriverDirectoryPath)
{
    // get webdriver directory absolute path from ctor argument.
    _webDriver = new InternetExplorerDriver(webDriverDirectoryPath);
}

public void Init()
{
  // this method is navigating method for looping invoke method page.
}

// this method called by other class using foreach.
public void Invoke(TestCase testCase)
{
    ...

    _webDriver
        .FindElement(By.Id("{Input html tag id}"))
        .Clear();  // error has occurred this point.
    _webDriver
        .FindElement(By.Id("{Input html tag id}"))
        .SendKeys(testCase.Value);

    ...

    var selectElement = new SelectElement(_webDriver
        .FindElement(By.Id("{Select html tag id}"))
    );
    selectElement.SelectByIndex(testCase.SelectIndex);  // this method not work. however using for loop and SendKey(Keys.ArrowDown) is work.
}


That👆 code runnning at Xunit testing.

```cs
var testCases = new[]
{
    new TestCase(1, 1, "hoge", "001", "51000", "Yamada"),
    new TestCase(2, 1, "fuga", "002", "51001", "Tanaka"),
    new TestCase(3, 1, "piyo", "003", "51002", "Suzuki")
};

using var invoker = new SeleniumInvoker();
invoker.Init();

var result1 = invoker.Invoke(testCases[0]);
Assert.Equal("OK", result1.CheckResult);
Assert.Equal("Yamada", result1.CustomerName);
Assert.Empty(result1.ErrorMessages);

var result2 = invoker.GetResult(testCases[1]);
Assert.Equal("NG", result2.CheckResult);
Assert.Equal("Tanaka", result2.CustomerName);
Assert.Equal("Invalid Code", result2.ErrorMessages.Single());

var result3 = invoker.GetResult(testCases[2]);
Assert.Equal("NG", result3.CheckResult);
Assert.Equal("Suzuki", result3.CustomerName);
Assert.Equal("No Account", result3.ErrorMessages.Single());
```
```


### Relevant log output

```shell
Xunit failed message:

OpenQA.Selenium.InvalidElementStateException
A JavaScript error was encountered clearing the element. The driver assumes this is because the element is hidden, disabled or read-only, and it must not be to clear the element.
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Clear()
```
```


### Operating System

Windows 10, Version 21H1 , OS Build 19043.1706

### Selenium version

C#, Selenium.Support 4.1.1, Selenium.WebDriver 4.1.1

### What are the browser(s) and version(s) where you see this issue?

Internet Explorer Version 21H1 (OS Build 19043.1706)

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer.exe 4.0.0.0 (64-bit)

### Are you using Selenium Grid?

_No response_

**Comment by titusfortner** [comment]
Based on the error message:
> A JavaScript error was encountered clearing the element. The driver assumes this is because the element is hidden, disabled or read-only, and it must not be to clear the element.

Can you verify that the element is not hidden, disabled or read-only?

**Comment by neko3cs** [comment]
I think that element is not disabled and read-only.

The test is looping and there are 3 test cases.

Excepion was occurred at 2nd time of foreach loop and that was not occurred  at 1st time of loop.

Furthermore, I debugged on VS2022 and put break point, I was able to enter input element and change text.

Thank you for your reply :)

**Comment by titusfortner** [comment]
If you reload the page as part of the loop does it work? Somehow the driver sees it as being in a state that won't work, and without something consistent that we can reproduce, it will be very difficult for us to see why it happens.

**Comment by neko3cs** [comment]
Sorry for the late my reply. :(

Yes, but that page is posted page, so I can not use `webDriver.Navigate.Refresh()` method.
So I had webdriver refresh page by clicking button to send form page.

Is there anything else I need to check?

**Comment by neko3cs** [comment]
Additional:
The test has passed by refresh page with the method that clicking button to send form page.

**Comment by diemol** [comment]
Is there anything else we need to check here? Not sure what needs to be done or checked from the previous comments.

**Comment by diemol** [comment]
Closing as we did not get a reply.
