### ISSUE TITLE
[🐛 Bug]: call devtools.target.create_browser_context() failed

### ISSUE THREAD

**Issue by ant1dot** [SeleniumHQ/selenium#10708]
### What happened?

call devtools.target.create_browser_context() return error

selenium.webdriver.common.bidi.cdp.BrowserError: BrowserError<code=-32000 message=Not allowed> None

Python 3.8.9 

### How can we reproduce the issue?

```shell
from selenium import webdriver
import selenium.webdriver.common.devtools.v101 as devtools


async def create_context(driver):
    async with driver.bidi_connection() as session:
        cdp_session = session.session
        a = await cdp_session.execute(
            devtools.target.create_browser_context()
        )
        print(a)


async def main():
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_argument("--no-sandbox")
    driver = webdriver.Chrome(options=chrome_options)

    try:
        driver.get("https://my-location.org/")
        await create_context(driver)
        # or driver.execute_cdp_cmd('Target.createBrowserContext', {})
    finally:
        driver.quit()


if __name__ == '__main__':
    import trio
    trio.run(main)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/ant/work/selenium4/test_context.py", line 29, in <module>
    trio.run(main)
  File "/Users/ant/work/selenium4/venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/Users/ant/work/selenium4/test_context.py", line 21, in main
    await create_context(driver)
  File "/Users/ant/work/selenium4/test_context.py", line 8, in create_context
    a = await cdp_session.execute(
  File "/Users/ant/work/selenium4/venv/lib/python3.8/site-packages/selenium/webdriver/common/bidi/cdp.py", line 203, in execute
    raise response
selenium.webdriver.common.bidi.cdp.BrowserError: BrowserError<code=-32000 message=Not allowed> None
```

### Operating System

macOS Monterey

### Selenium version

Python Selenium 4.1.5

### What are the browser(s) and version(s) where you see this issue?

Chrome 102.0.5005.61

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 102.0.5005.61

**Comment by symonk** [comment]
@ant1dot could you try this with devtools `102` in `selenium==4.2.0` ?

**Comment by ant1dot** [comment]
> 

updated to 4.2.0 but getting the same error

**Comment by ant1dot** [comment]
issue is actual, current error 
`selenium.webdriver.common.bidi.cdp.BrowserError: BrowserError<code=-32000 message=Not allowed> None`

**Comment by ant1dot** [comment]
chromedriver fixed this bug https://bugs.chromium.org/p/chromedriver/issues/detail?id=4533

**Comment by diemol** [comment]
Thanks for letting us know, @ant1dot!
