### ISSUE TITLE
[🐛 Bug]:Python upgrading to selenium 4 raises exception:  selenium.common.exceptions.WebDriverException: Message:

### ISSUE THREAD

**Issue by davuses** [SeleniumHQ/selenium#10710]
### What happened?

Python version: `Python 3.8.10`

I upgraded my selenium package from `selenium==3.14.0` to  `selenium==4.0.0`, with selenium 4 it failed to open a chrome browser and raises `selenium.common.exceptions.WebDriverException: Message:`. But the same code can run without issues with selenium 3.14.0.

What confused me is the `WebDriverException` Message is empty, so I couldn't figure out where the problem really lies. 

I have made sure the chromedriver is in `PATH`.

The same issue occured when running with firefox and geckodriver, selenium 4.0.0

### How can we reproduce the issue?

```shell
from selenium import webdriver

browser = webdriver.Chrome()
browser.get('http://selenium.dev/')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "selenium_test.py", line 3, in <module>
    browser = webdriver.Chrome()
  File "/home/patrick/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/patrick/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/patrick/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/patrick/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/patrick/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/home/patrick/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 207, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message:
```

### Operating System

Ubuntu 20

### Selenium version

`selenium==4.0.0`

### What are the browser(s) and version(s) where you see this issue?

Chrome 102

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 102

### Are you using Selenium Grid?

no

**Comment by symonk** [comment]
Hi @davuses could you run your example with python debug logs displayed? I'd be curious to see `request` / `response` logs.  There isn't enough information to reproduce for me, if `chromedriver` is on `PATH`; try this:

```python
from selenium import webdriver
import logging

logging.basicConfig(level=logging.DEBUG)


def main() -> int:
    browser = webdriver.Chrome()
    browser.get('http://selenium.dev/')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
```

and share with me the logs for request/response

**Comment by davuses** [comment]
> and share with me the logs for request/response

@symonk Here is the debug logs:
```
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:40187/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": []}}}, "desiredCapabilities": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": []}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:10073
DEBUG:urllib3.connectionpool:http://127.0.0.1:10073 "POST http://localhost:40187/session HTTP/1.1" 503 0
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "selenium_test.py", line 14, in <module>
    raise SystemExit(main())
  File "selenium_test.py", line 8, in main
    browser = webdriver.Chrome()
  File "/home/kiu/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/kiu/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/kiu/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/kiu/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/kiu/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/home/kiu/python/venv/selenium/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 207, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 
```
After seeing the logs, I realized it could be a problem resulting from http proxy (`http://127.0.0.1:10073`). And yeah, everything works again after I remove the http proxy environment variable.

And here is the logs running with selenium 3.14.0
```
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58151/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "goog:chromeOptions": {"extensions": [], "args": []}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "goog:chromeOptions": {"extensions": [], "args": []}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:58151
DEBUG:urllib3.connectionpool:http://127.0.0.1:58151 "POST /session HTTP/1.1" 200 752
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58151/session/b9d0776e281c1d5b0019caa9951bc080/url {"url": "http://selenium.dev/"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:58151 "POST /session/b9d0776e281c1d5b0019caa9951bc080/url HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
```
It seems this version doesn't respect the proxy setting so the issue doesn't occur.

**Comment by symonk** [comment]
Any more findings/info?

**Comment by titusfortner** [comment]
Looks like this turned out to be a proxy issue? Please raise a new issue with a reproducible case if so.
