### ISSUE TITLE
[🐛 Bug]: SeleniumGrid: DriverFactory from config is expected to be a SessionFactory

### ISSUE THREAD

**Issue by HenningL** [SeleniumHQ/selenium#10740]
### What happened?

When i try to add a custom selenium driver with "--driver-factory" argument and a class derived from "`org.openqa.selenium.remote.server.DriverFactory`" i will get an error, that the class is expected to be a "org.openqa.selenium.grid.node.SessionFactory"

In method "private void addDriverFactoriesFromConfig" (line 262) the configured class gets loaded and tried to make a Sessionfactory out of it, which fails.
https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/node/config/NodeOptions.java

Besides that, the error message is misleading:`Caused by: java.lang.IllegalArgumentException: Class ..XXDriverFactory's `create(Config, Capabilities)` method must be static`

### How can we reproduce the issue?

```shell
Create a class derived from "org.openqa.selenium.remote.server.DriverFactory". Start a grid-node with the --driver-factory argument whith this class.

java -cp  "yourArtifacts" org.openqa.selenium.grid.Bootstrap node --config  X.toml --driver-factory XXDriverFactory "{\\\"browserName\\\": \\\"custom\\\"}"
```

### Relevant log output

```shell
Caused by: java.lang.IllegalArgumentException: Class XXDriverFactory's `create(Config, Capabilities)` method must be static
        at org.openqa.selenium.grid.node.config.NodeOptions.createSessionFactory(NodeOptions.java:296)
        at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverFactoriesFromConfig$3(NodeOptions.java:274)
        at java.base/java.util.HashMap.forEach(HashMap.java:1425)
        at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverFactoriesFromConfig$4(NodeOptions.java:272)
        at java.base/java.util.Optional.ifPresent(Optional.java:176)
        at org.openqa.selenium.grid.node.config.NodeOptions.addDriverFactoriesFromConfig(NodeOptions.java:264)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:209)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:79)
        ... 22 more
```

### Operating System

Windows10

### Selenium version

4.0.0-alpha-2

### What are the browser(s) and version(s) where you see this issue?

grid-node

### What are the browser driver(s) and version(s) where you see this issue?

custom-driver

### Are you using Selenium Grid?

4.1.0

**Comment by diemol** [comment]
Probably the naming is a bit misleading, naming things is hard.

The class needs to implement [`SessionFactory`](https://github.com/SeleniumHQ/selenium/blob/702b3aae7385adf331d75cdeacd79720cf6b9c84/java/src/org/openqa/selenium/grid/node/SessionFactory.java#L28-L30). Like the [`DriverServiceSessionFactory`](https://github.com/SeleniumHQ/selenium/blob/df41b5816219c91590f32e29208d4b43bf7570aa/java/src/org/openqa/selenium/grid/node/config/DriverServiceSessionFactory.java#L67). 

However, when loading the class via the configuration options, it needs to implement a `static` method which takes care of instantiating the object, like the [`HelperFactory`](https://github.com/SeleniumHQ/selenium/blob/7e541ed157662ccaa13e21b5307ab11537335ef8/java/test/org/openqa/selenium/grid/node/config/NodeOptionsTest.java#L509) we use for tests.

If you have more questions, please reach out to us through the channels shared in the links below.
