### ISSUE TITLE
[🐛 Bug]: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure

### ISSUE THREAD

**Issue by sumitchauhanJan** [SeleniumHQ/selenium#10758]
### What happened?

Recently my web test cases which were running on chrome headless mode in CI started Failing with below error.

Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:246)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
        at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:106)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:93)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
        at app.functions.webFunctions.WebDriverInitFunctions.setupChromeDriver(WebDriverInitFunctions.kt:34)
        at app.functions.webFunctions.CybersourceFunctions$getCybersourceExternalToken$2.invokeSuspend(CybersourceFunctions.kt:27)
        at app.functions.webFunctions.CybersourceFunctions$getCybersourceExternalToken$2.invoke(CybersourceFunctions.kt)
        at app.functions.webFunctions.CybersourceFunctions$getCybersourceExternalToken$2.invoke(CybersourceFunctions.kt)
        at io.kotest.assertions.RetryKt.retry-G6guFE4(Retry.kt:67)
        at app.functions.webFunctions.CybersourceFunctions.getCybersourceExternalToken(CybersourceFunctions.kt:22)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1.invoke$validateCybersource3dsPurchase(Cybs3ds1.kt:76)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1.access$invoke$validateCybersource3dsPurchase(Cybs3ds1.kt:51)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1$1$1.invokeSuspend(Cybs3ds1.kt:383)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1$1$1.invoke(Cybs3ds1.kt)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1$1$1.invoke(Cybs3ds1.kt)
        Caused by:
        org.openqa.selenium.WebDriverException: Driver server process died prematurely.
        **Build info: version: '4.2.1', revision: 'ac4d0fdd4a'
        System info: host: '014d6c15-e8c1-11ec-b9d8-ca14bbdd5338', ip: '10.0.50.95', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.117-58.216.amzn2.x86_64', java.version: '11.0.14'**
        Driver info: driver.version: ChromeDriver
            at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:226)
            at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
            at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:551)
            ... 17 more
```

I have highlighted the build info in above code.

Piece of code block  which is failing is 
```
val webConfig = WebDriverInitFunctions()
 val driver = webConfig.setupChromeDriver()
```
Implementation of Set setupChromeDriver is 
````
fun setupChromeDriver(): WebDriver {
        WebDriverManager.chromedriver().setup()
        val preferences = LoggingPreferences()
        preferences.enable(LogType.PERFORMANCE, Level.ALL)
        val option = ChromeOptions()
        option.setCapability(CapabilityType.LOGGING_PREFS, preferences)
        option.setCapability("goog:loggingPrefs", preferences)

        if (System.getenv("HEADLESS").lowercase() == "true") {
            option.addArguments("--disable-dev-shm-usage")
            option.addArguments("--disable-gpu")
            option.addArguments("--no-sandbox")
            option.addArguments("--start-maximized")
            option.addArguments("--window-size=1920,1080")
            option.addArguments("--headless")
            option.addArguments("--user-agent=HeadlessChrome/${option.browserVersion}")
        }

        driver = ChromeDriver(option)
        return driver
```
    }`




### How can we reproduce the issue?

```shell
Running below code block in CI

`fun setupChromeDriver(): WebDriver {
        WebDriverManager.chromedriver().setup()
        val preferences = LoggingPreferences()
        preferences.enable(LogType.PERFORMANCE, Level.ALL)
        val option = ChromeOptions()
        option.setCapability(CapabilityType.LOGGING_PREFS, preferences)
        option.setCapability("goog:loggingPrefs", preferences)

        if (System.getenv("HEADLESS").lowercase() == "true") {
            option.addArguments("--disable-dev-shm-usage")
            option.addArguments("--disable-gpu")
            option.addArguments("--no-sandbox")
            option.addArguments("--start-maximized")
            option.addArguments("--window-size=1920,1080")
            option.addArguments("--headless")
            option.addArguments("--user-agent=HeadlessChrome/${option.browserVersion}")
        }

        driver = ChromeDriver(option)
        return driver
    }`

CI job in Prow is as followed: 

presubmits:
 /--api-automation:
    - name: payment
      context: "Build and Run Regression Payment tests"
      agent: kubernetes
      always_run: false
      skip_report: false
      decorate: true
      clone_uri: "-------"
      cluster: {{ .Values.clusters.prowJobs }}
      labels:
        preset-github: "true"
        preset-scripts: "true"
      spec:
        serviceAccountName: xyz
        containers:
          - name: rg-automation-ci
            image: openjdk:11
            resources:
              requests:
                cpu: "2"
                memory: "2Gi"
              limits:
                cpu: "2"
                memory: "2Gi"
            envFrom:
              - secretRef:
                  name: xyz
            securityContext:
                  privileged: true
            command:
              - /bin/bash
            args:
              - -c
              - |
                echo "-----------------------------------------------------------------"
                echo "-----------------------------------------------------------------"
                apt-get update && apt-get install -y bash
                apt-get install -y curl
                apt-get install -y awscli
                aws --version
                apt-get install -y jq
                echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list
                wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
                set -x \
                    && apt-get update \
                    && apt-get install -y google-chrome-stable
                export CHROME_BIN="/usr/bin/google-chrome"

                echo "-----------------------------------------------------------------"
                echo "Fetching branch name..."
                echo "-----------------------------------------------------------------"
                branchName=`curl -s -H "Authorization: token ${GITHUB_OAUTH_TOKEN}" -H "Accept: application/json"----------} | jq -r .head.ref`
                echo "Branch Name = '$branchName'"

                echo "-----------------------------------------------------------------"
                echo "Building and running all 'Payment Regression' automation tests.(Only 1 paymaya case as of now.."
                echo "-----------------------------------------------------------------"
                ./gradlew clean test -Dkotest.tags="Payment & Cybs" -DrunId="79901" 
         

        
I have Removed unnecessary details from above job
```


### Relevant log output

```shell
app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1 > Visa Secure Card Enrolled: Successful Authentication FP_LA[tags = Regression, WebTests, TestRailIds, Payment, Cybs] FAILED
    org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:246)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
        at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:106)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:93)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
        at app.functions.webFunctions.WebDriverInitFunctions.setupChromeDriver(WebDriverInitFunctions.kt:34)
        at app.functions.webFunctions.CybersourceFunctions$getCybersourceExternalToken$2.invokeSuspend(CybersourceFunctions.kt:27)
        at app.functions.webFunctions.CybersourceFunctions$getCybersourceExternalToken$2.invoke(CybersourceFunctions.kt)
        at app.functions.webFunctions.CybersourceFunctions$getCybersourceExternalToken$2.invoke(CybersourceFunctions.kt)
        at io.kotest.assertions.RetryKt.retry-G6guFE4(Retry.kt:67)
        at app.functions.webFunctions.CybersourceFunctions.getCybersourceExternalToken(CybersourceFunctions.kt:22)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1.invoke$validateCybersource3dsPurchase(Cybs3ds1.kt:76)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1.access$invoke$validateCybersource3dsPurchase(Cybs3ds1.kt:51)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1$1$1.invokeSuspend(Cybs3ds1.kt:383)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1$1$1.invoke(Cybs3ds1.kt)
        at app.journeys.payments.cybersource.cards.async.redirections.Cybs3ds1$1$1$1.invoke(Cybs3ds1.kt)
        Caused by:
        org.openqa.selenium.WebDriverException: Driver server process died prematurely.
        Build info: version: '4.2.1', revision: 'ac4d0fdd4a'
        System info: host: '014d6c15-e8c1-11ec-b9d8-ca14bbdd5338', ip: '10.0.50.95', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.117-58.216.amzn2.x86_64', java.version: '11.0.14'
        Driver info: driver.version: ChromeDriver
            at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:226)
            at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
            at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:551)
            ... 17 more
```


### Operating System

Linux

### Selenium version

seleniumVersion = "4.1.4"

### What are the browser(s) and version(s) where you see this issue?

Chrome  102.0.5005.115 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 102.0.5005.61 

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
Really hard to say what the issue might be. If this was working before and suddenly started to fail, what has changed in your environment? Chrome update? Selenium update? 

Also, what happens when you run it locally on your machine? On a local docker container?

**Comment by sumitchauhanJan** [comment]
In my local i don't se this issue and as I am using WebDriverManager for chrome its always latest one.We have not changed selenium version as of now.

**Comment by diemol** [comment]
I see you use `WebDriverManager` both locally and in the pod, so things should be the same. However, if this works locally and not in the other environment, then you need to check what is different between the environments since all versions are the same. We cannot really troubleshoot infrastructure issues.
