### ISSUE TITLE
Test not run on HtmlUnitDriver using selenium 2.47.1 ClassNotFoundException: org.apache.http.conn.ssl.NoopHostnameVerifier 

### ISSUE THREAD

**Issue by nikolmarku** [SeleniumHQ/selenium#1076]
I have updated to selenium 2.47.1 from 2.45.0
and one of my test is not working 
it uses html unit driver
--
webDriver = new HtmlUnitDriver(){
            @Override protected WebClient modifyWebClient( WebClient webClient){
                WebClient answer=super.modifyWebClient(webClient);
                answer.addRequestHeader(headerName, headerValue);
                return answer;
            }
        };
--

Fix: I had to change the dependency not to use the latest selenium but use V45
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-htmlunit-driver</artifactId>
            <version>2.45.0</version>
            <scope>test</scope>
        </dependency>
---------

this looked interesting : https://issues.apache.org/jira/browse/HTTPCLIENT-1611

Log:

java.lang.NoClassDefFoundError: org/apache/http/conn/ssl/NoopHostnameVerifier 
at com.gargoylesoftware.htmlunit.httpclient.HtmlUnitSSLConnectionSocketFactory.buildSSLSocketFactory(HtmlUnitSSLConnectionSocketFactory.java:112) 
at com.gargoylesoftware.htmlunit.HttpWebConnection.configureHttpsScheme(HttpWebConnection.java:606) 
at com.gargoylesoftware.htmlunit.HttpWebConnection.createHttpClient(HttpWebConnection.java:541) 
at com.gargoylesoftware.htmlunit.HttpWebConnection.getHttpClientBuilder(HttpWebConnection.java:496) 
at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:163) 
at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1316) 
at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1233) 
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:341) 
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:410) 
at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:512) 
at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:501) 
at com.englishlive.tests.redirect.htmlunit.ArRedirectTest.setup(ArRedirectTest.java:26) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:606) 
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85) 
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:552) 
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215) 
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140) 
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170) 
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104) 
at org.testng.TestRunner.privateRun(TestRunner.java:767) 
at org.testng.TestRunner.run(TestRunner.java:617) 
at org.testng.SuiteRunner.runTest(SuiteRunner.java:348) 
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343) 
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305) 
at org.testng.SuiteRunner.run(SuiteRunner.java:254) 
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) 
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) 
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) 
at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) 
at org.testng.TestNG.run(TestNG.java:1057) 
at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111) 
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204) 
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175) 
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:606) 
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) 
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.ssl.NoopHostnameVerifier 
at java.net.URLClassLoader$1.run(URLClassLoader.java:366) 
at java.net.URLClassLoader$1.run(URLClassLoader.java:355) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.net.URLClassLoader.findClass(URLClassLoader.java:354) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:425) 
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:358) 
... 42 more

**Comment by lukeis** [comment]
htmlunit driver now requires httpclient 4.5, you likely have that dependency set to a lower version in your project or another dependency is using a lower version. Please check your maven dependency graph (or if not using maven, check the jars you are including) and update org.apache.httpcomponents  httpclient to 4.5
