### ISSUE TITLE
[🐛 Bug]:  Exception is thrown when using the getShadowHost function 

### ISSUE THREAD

**Issue by kfirbenhamou** [SeleniumHQ/selenium#10774]
### What happened?

I used selenium grid 4.2.2
Java + TestNG project
Selenium client version 4.2.2 
Tried to implement the shadow dom example from here 

https://titusfortner.com/2021/11/22/shadow-dom-selenium.html

WebElement class has built in throw exception in the code 

RemoteWebElement

org.openqa.selenium.UnsupportedCommandException: getElementShadowRoot throws this exception 

MyProject also contains the appium 7.3.0
but I am using RemoteWebElement class which is not related to appium

### How can we reproduce the issue?

```shell
just try to implement this solution for selenium 4


https://titusfortner.com/2021/11/22/shadow-dom-selenium.html
```

### Relevant log output

```shell
org.openqa.selenium.UnsupportedCommandException: getElementShadowRoot
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'NG-KFIR-B', ip: 'fe80:0:0:0:102c:a238:5dd7:48fc%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.7'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [1e4a75052f8190660f042b73d2b0971d, getElementShadowRoot {id=0.8449315288979184-1}]
Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 102.0.5005.61 (0e59bcc00cc4..., userDataDir: /tmp/.com.google.Chrome.JwyuJB}, cssSelectorsEnabled: true, databaseEnabled: false, enableLog: true, enableVNC: true, enableVideo: true, env: [ROOT_CA_DIGI=LS0tLS1CRUdJTi...], goog:chromeOptions: {debuggerAddress: localhost:37791}, handlesAlerts: true, hasTouchScreen: false, hostsEntries: [auth.digi.service:10.70.220.58, test-application.digi.servi..., sws-test-simulator.digi.ser..., sws-api.digi.service:10.70....], javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: Linux, platformName: ANY, proxy: Proxy(), rotatable: false, se:cdp: ws://172.20.0.4:4444/sessio..., se:cdpVersion: 102.0.5005.61, se:vnc: ws://172.20.0.4:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.20.0.4:7900, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 102.0.5005.61, videoScreenSize: 1024x768, webStorageEnabled: true, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on ANY (1e4a75052f8190660f042b73d2b0971d)] -> css selector: #shadow_host]
Session ID: 1e4a75052f8190660f042b73d2b0971d

	at org.openqa.selenium.remote.codec.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:250)
	at org.openqa.selenium.remote.codec.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:127)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:172)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:588)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
	at org.openqa.selenium.remote.RemoteWebElement.getShadowRoot(RemoteWebElement.java:251)
```

### Operating System

client mac grid on ubuntu

### Selenium version

4.2.2

### What are the browser(s) and version(s) where you see this issue?

chrome > 96

### What are the browser driver(s) and version(s) where you see this issue?

chrome 102.

### Are you using Selenium Grid?

4.2.2

**Comment by diemol** [comment]
Which one from all the examples shown in that link?

**Comment by kfirbenhamou** [comment]
@diemol 
<img width="855" alt="image" src="https://user-images.githubusercontent.com/24809974/173821989-b68bdb18-8568-4b76-bce3-baf52ee3f30a.png">

**Comment by diemol** [comment]
I cannot reproduce this. I created a project and copied the code and things work well.

Here is the link https://github.com/diemol/selenium-issues/tree/master/selenium/issue-10774

Feel free to check it and use it to run the examples.
