### ISSUE TITLE
[🐛 Bug]: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by anikomt** [SeleniumHQ/selenium#10782]
### What happened?

Following issue happens for FireFox and Google Chrome browsers/drivers for latest versions. I found same issues from past years, where it was recommended to update to latest versions of selenium/driver, however I already have latest versions.

**Test:**
```
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

public class testSel {
    public static void main(String[] args){
        System.out.println("1");
        System.setProperty("webdriver.gecko.driver", "/Users/atkeshelashvili/Downloads/geckodriver");
        WebDriver driver=new FirefoxDriver();
        System.out.println("2");
        driver.get("http://demo.guru99.com/");
        System.out.println("3");
        WebElement element=driver.findElement(By.xpath("//input[@name='emailid']"));
        element.sendKeys("abc@gmail.com");

        WebElement button=driver.findElement(By.xpath("//input[@name='btnLogin']"));
        button.click();
    }
}
```

### How can we reproduce the issue?

**Upload following versions:**
```shell
FireFox 101.0.1 (64 bit) 
Selenium Web Driver 4.2.2 selenium-java-4.2.2.zip
Geckodriver 0.31.0
System macOS Monterey (M1)

Same happens for Google Chrome 102.0.5005.61.
```

### Relevant log output

**Logs:**
```shell
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ce://gre/modules/AsyncShutdown.jsm:526:26
addBlocker@resource://gre/modules/AsyncShutdown.jsm:465:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1564:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1584:16
@resource://gre/modules/osfile.jsm:11:30
@resource://gre/modules/TelemetryStorage.jsm:18:28
getShutdownState@resource://gre/modules/TelemetrySend.jsm:1665:7
getShutdownState@resource://gre/modules/TelemetrySend.jsm:358:30
_getState@resource://gre/modules/TelemetryControllerParent.jsm:1073:33
setupTelemetry/<@resource://gre/modules/TelemetryControllerParent.jsm:913:18
safeGetState@resource://gre/modules/AsyncShutdown.jsm:257:17
Barrier/addBlocker/promise<@resource://gre/modules/AsyncShutdown.jsm:766:20
observe@resource://gre/modules/AsyncShutdown.jsm:575:16

WARNING: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
WARNING: addBlocker@resource://gre/modules/AsyncShutdown.jsm:718:15
addBlocker@resource://gre/modules/AsyncShutdown.jsm:526:26
addBlocker@resource://gre/modules/AsyncShutdown.jsm:465:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1564:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1584:16
@resource://gre/modules/osfile.jsm:11:30
@resource://gre/modules/TelemetryStorage.jsm:18:28
removeAbortedSessionPing@resource://gre/modules/TelemetryControllerParent.jsm:717:5
removeAbortedSessionPing@resource://gre/modules/TelemetryControllerParent.jsm:246:17
shutdownChromeProcess/cleanup/<@resource://gre/modules/TelemetrySession.jsm:1231:37
observe@resource://gre/modules/AsyncShutdown.jsm:575:16

JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
2022-06-17 10:13:54.733 plugin-container[84134:8972533] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-17 10:13:54.734 plugin-container[84134:8972533] nil host used in call to allowsAnyHTTPSCertificateForHost:
2022-06-17 10:13:54.735 plugin-container[84134:8972533] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-17 10:13:54.735 plugin-container[84134:8972533] nil host used in call to allowsAnyHTTPSCertificateForHost:
2022-06-17 10:13:54.735 plugin-container[84134:8972531] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-17 10:13:54.735 plugin-container[84134:8972531] nil host used in call to allowsAnyHTTPSCertificateForHost:
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
console.error: BackgroundUpdate: 
  _reasonsToNotScheduleUpdates: Failed to check for Maintenance Service Registry Key: [Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIUpdateProcessor.getServiceRegKeyExists]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource://gre/modules/BackgroundUpdate.jsm :: _reasonsToNotScheduleUpdates :: line 241"  data: no]

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
	at testSel.main(testSel.java:10)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows: 
ce://gre/modules/AsyncShutdown.jsm:526:26
addBlocker@resource://gre/modules/AsyncShutdown.jsm:465:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1564:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1584:16
@resource://gre/modules/osfile.jsm:11:30
@resource://gre/modules/TelemetryStorage.jsm:18:28
getShutdownState@resource://gre/modules/TelemetrySend.jsm:1665:7
getShutdownState@resource://gre/modules/TelemetrySend.jsm:358:30
_getState@resource://gre/modules/TelemetryControllerParent.jsm:1073:33
setupTelemetry/<@resource://gre/modules/TelemetryControllerParent.jsm:913:18
safeGetState@resource://gre/modules/AsyncShutdown.jsm:257:17
Barrier/addBlocker/promise<@resource://gre/modules/AsyncShutdown.jsm:766:20
observe@resource://gre/modules/AsyncShutdown.jsm:575:16

WARNING: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
WARNING: addBlocker@resource://gre/modules/AsyncShutdown.jsm:718:15
addBlocker@resource://gre/modules/AsyncShutdown.jsm:526:26
addBlocker@resource://gre/modules/AsyncShutdown.jsm:465:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1564:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1584:16
@resource://gre/modules/osfile.jsm:11:30
@resource://gre/modules/TelemetryStorage.jsm:18:28
removeAbortedSessionPing@resource://gre/modules/TelemetryControllerParent.jsm:717:5
removeAbortedSessionPing@resource://gre/modules/TelemetryControllerParent.jsm:246:17
shutdownChromeProcess/cleanup/<@resource://gre/modules/TelemetrySession.jsm:1231:37
observe@resource://gre/modules/AsyncShutdown.jsm:575:16

JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
2022-06-17 10:13:54.733 plugin-container[84134:8972533] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-17 10:13:54.734 plugin-container[84134:8972533] nil host used in call to allowsAnyHTTPSCertificateForHost:
2022-06-17 10:13:54.735 plugin-container[84134:8972533] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-17 10:13:54.735 plugin-container[84134:8972533] nil host used in call to allowsAnyHTTPSCertificateForHost:
2022-06-17 10:13:54.735 plugin-container[84134:8972531] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-17 10:13:54.735 plugin-container[84134:8972531] nil host used in call to allowsAnyHTTPSCertificateForHost:
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
console.error: BackgroundUpdate: 
  _reasonsToNotScheduleUpdates: Failed to check for Maintenance Service Registry Key: [Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIUpdateProcessor.getServiceRegKeyExists]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource://gre/modules/BackgroundUpdate.jsm :: _reasonsToNotScheduleUpdates :: line 241"  data: no]

Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'ip-192-168-0-198.eu-central-1.compute.internal', ip: '192.168.0.198', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.1', java.version: '11.0.12'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
	at testSel.main(testSel.java:10)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ce://gre/modules/AsyncShutdown.jsm:526:26
addBlocker@resource://gre/modules/AsyncShutdown.jsm:465:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1564:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1584:16
@resource://gre/modules/osfile.jsm:11:30
@resource://gre/modules/TelemetryStorage.jsm:18:28
getShutdownState@resource://gre/modules/TelemetrySend.jsm:1665:7
getShutdownState@resource://gre/modules/TelemetrySend.jsm:358:30
_getState@resource://gre/modules/TelemetryControllerParent.jsm:1073:33
setupTelemetry/<@resource://gre/modules/TelemetryControllerParent.jsm:913:18
safeGetState@resource://gre/modules/AsyncShutdown.jsm:257:17
Barrier/addBlocker/promise<@resource://gre/modules/AsyncShutdown.jsm:766:20
observe@resource://gre/modules/AsyncShutdown.jsm:575:16

WARNING: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
WARNING: addBlocker@resource://gre/modules/AsyncShutdown.jsm:718:15
addBlocker@resource://gre/modules/AsyncShutdown.jsm:526:26
addBlocker@resource://gre/modules/AsyncShutdown.jsm:465:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1564:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1584:16
@resource://gre/modules/osfile.jsm:11:30
@resource://gre/modules/TelemetryStorage.jsm:18:28
removeAbortedSessionPing@resource://gre/modules/TelemetryControllerParent.jsm:717:5
removeAbortedSessionPing@resource://gre/modules/TelemetryControllerParent.jsm:246:17
shutdownChromeProcess/cleanup/<@resource://gre/modules/TelemetrySession.jsm:1231:37
observe@resource://gre/modules/AsyncShutdown.jsm:575:16

JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 718: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
2022-06-17 10:13:54.733 plugin-container[84134:8972533] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-17 10:13:54.734 plugin-container[84134:8972533] nil host used in call to allowsAnyHTTPSCertificateForHost:
2022-06-17 10:13:54.735 plugin-container[84134:8972533] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-17 10:13:54.735 plugin-container[84134:8972533] nil host used in call to allowsAnyHTTPSCertificateForHost:
2022-06-17 10:13:54.735 plugin-container[84134:8972531] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-17 10:13:54.735 plugin-container[84134:8972531] nil host used in call to allowsAnyHTTPSCertificateForHost:
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
console.error: BackgroundUpdate: 
  _reasonsToNotScheduleUpdates: Failed to check for Maintenance Service Registry Key: [Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIUpdateProcessor.getServiceRegKeyExists]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource://gre/modules/BackgroundUpdate.jsm :: _reasonsToNotScheduleUpdates :: line 241"  data: no]

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	... 7 more
```
```


### Operating System

macOs

### Selenium version

4.2.2

### What are the browser(s) and version(s) where you see this issue?

FireFox 101.0.1 (64 bit)

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.31.0

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment]
I have the exact same setup and I am not able to reproduce this issue. Is it possible that you downloaded the binaries for the x86 architecture?

**Comment by anikomt** [comment]
I downloaded Selenium Server (Grid) and Java Binding from here https://www.selenium.dev/downloads/
and used `brew install geckodriver` / `brew install cask chromedriver` console commands to install browser drivers.
I also tried to download geckodriver from here [geckodriver-v0.31.0-macos-aarch64.tar.gz](https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-macos-aarch64.tar.gz)
As far as I use there is nothing of x86 architecture.

**Comment by anikomt** [comment]
Turned out I had an older version of selenium in my pom.xml and didn't upgrade it after downloading it from https://www.selenium.dev/downloads/ 🤦‍♀️
Upgrading to 4.2.1 version helped.
