### ISSUE TITLE
[🐛 Bug]: windows 10pro, python 3.9.13, selenium 4, chrome 102.0.5005.115, chromedriver 102.0.5005.61. my script doesn't work

### ISSUE THREAD

**Issue by PyyTom** [SeleniumHQ/selenium#10788]
### What happened?

Hello, my following script just stopped to working, i don't understand why, because i used it every day, many times per day.
My s.o. is windows 10pro, my idle is python 3.9.13, i've just installed selenium 4 (but neither selenium 3 works). 
I tried many combinations between Chrome's and  chromedriver's versions, but nothin happened.
p.s. maybe is important that chromedriver doesn't start because it has no sessionID assigned.
thanks

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.binary_location='C:\Program_Files\Google\Chrome\Application'
d = webdriver.Chrome(options=chrome_options)
d.get('https://www.google.nl/')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\marche\PROGRAMMA\lab.PYW", line 9, in <module>
    d = webdriver.Chrome(options=chrome_options)
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: no chrome binary at C:\Program_Files\Google\Chrome\Application
Stacktrace:
Backtrace:
	Ordinal0 [0x0042D953+2414931]
	Ordinal0 [0x003BF5E1+1963489]
	Ordinal0 [0x002AC6B8+837304]
	Ordinal0 [0x002C7A23+948771]
	Ordinal0 [0x002C5FB1+942001]
	Ordinal0 [0x002F9100+1151232]
	Ordinal0 [0x002F8D5A+1150298]
	Ordinal0 [0x002F42B6+1131190]
	Ordinal0 [0x002CE860+976992]
	Ordinal0 [0x002CF756+980822]
	GetHandleVerifier [0x0069CC62+2510274]
	GetHandleVerifier [0x0068F760+2455744]
	GetHandleVerifier [0x004BEABA+551962]
	GetHandleVerifier [0x004BD916+547446]
	Ordinal0 [0x003C5F3B+1990459]
	Ordinal0 [0x003CA898+2009240]
	Ordinal0 [0x003CA985+2009477]
	Ordinal0 [0x003D3AD1+2046673]
	BaseThreadInitThunk [0x7744FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77D67A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77D67A6E+238]
```

### Operating System

windows 10 pro

### Selenium version

selenium 4

### What are the browser(s) and version(s) where you see this issue?

chrome 102.0.5005.115

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 102.0.5005.61

**Comment by symonk** [comment]
Should the binary be pointing at a `chrome.exe` specifically? I need to take a look

**Comment by titusfortner** [comment]
Yes, this should be pointing to an actual executable, not the directory of an executable.
https://chromedriver.chromium.org/capabilities

We know the driver service has started, because it is the driver that looks for the binary and throws that error if it can't find it.

Please provide the full path and executable to the property and let us know if that fixes it.

**Comment by diemol** [comment]
Closing as we did not get more information.
