### ISSUE TITLE
Edge browser is not working while executing in Grid with ver. 2.47.1

### ISSUE THREAD

**Issue by chris1248** [SeleniumHQ/selenium#1078]
I am attempting to hook up our automation to test on Edge (Windows 10).
I have a ruby script, pulling in the 2.47.1 library.

```ruby
require 'rubygems'
require 'selenium-webdriver'

caps = Selenium::WebDriver::Remote::Capabilities.edge
driver = Selenium::WebDriver.for :remote, url: "http://10.0.9.218:4444/wd/hub", desired_capabilities: caps
driver.navigate.to "http://google.com"
element = driver.find_element(:name, 'q')
element.send_keys "Selenium Tutorials"
element.submit
driver.quit
```

On the other windows machine I launched the selenium standalone server like this.

```
rem hub is the IP address where the script is running
set hub=%1
java -jar selenium-server-standalone-2.47.1.jar -nodeConfig nodeConfig.json -Dwebdriver.edge.driver="C:\Program Files (x86)\Microsoft Web Driver\MicrosoftWebDriver.exe" -hub http://%hub%:4444/grid/register
```
Where the MicrosoftWebDriver.exe was installed from an installer I found on microsoft's website. That indicated it supported the Edge browser.

So the node starts up, and I can even browse to the page hosted by the node:
`http://10.0.9.218:4444/wd/hub`

So when I attempt to run my ruby script, it fails quite spectacularly with the following error and callstack:

```
[remote server] org.openqa.selenium.remote.server.DefaultDriverFactory(DefaultDriverFactory.java):62:in `newInstance': The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't create a new driver instance for Capabilities [{rotatable=false, nativeEvents=false, browserName=edge, takesScreenshot=false, javascriptEnabled=true, version=, platform=WINDOWS, cssSelectorsEnabled=false}] (Selenium::WebDriver::Error::UnknownError)
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'TestWin', ip: '10.0.9.218', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown (org.openqa.selenium.WebDriverException)
	from [remote server] org.openqa.selenium.remote.server.DefaultSession$BrowserCreator(DefaultSession.java):222:in `call'
	from [remote server] org.openqa.selenium.remote.server.DefaultSession$BrowserCreator(DefaultSession.java):1:in `call'
	from [remote server] java.util.concurrent.FutureTask():-1:in `run'
	from [remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
	from [remote server] java.util.concurrent.ThreadPoolExecutor():-1:in `runWorker'
	from [remote server] java.util.concurrent.ThreadPoolExecutor$Worker():-1:in `run'
	from [remote server] java.lang.Thread():-1:in `run'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:122:in `create_session'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:52:in `new'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:52:in `for'
	from <snip>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver.rb:86:in `for'
	from test_selenium_edge.rb:5:in `<main>'
```

I have no idea how to overcome this.

**Comment by titusfortner** [comment]
I only tested the Edge implementation locally, not through the Remote, and the browser_name I used doesn't work via Remote. It's fixed, but not yet released.

This should work in the meantime:
```Ruby
Selenium::WebDriver::Remote::Capabilities.edge(browser_name: 'MicrosoftEdge')
```

**Comment by vveliev** [comment]
there was a change #1002 
for now you need to replace browser name 

```
when /^edge$/i
          caps[:browser_name] = 'MicrosoftEdge'
        end

```

**Comment by lukeis** [comment]
closing this as it's just pending a new code release

**Comment by chris1248** [comment]
Tried that, and this is what I got:

```
[remote server] sun.reflect.NativeConstructorAccessorImpl():-2:in `newInstance0': not implemented (WARNING: The server did not provide any stacktrace information) (Selenium::WebDriver::Error::UnknownError)
Command duration or timeout: 16 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'Chris-Win7', ip: '10.0.9.218', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.edge.EdgeDriver
Capabilities [{acceptSslCerts=true, browserVersion=20.10240.16384.0, platformVersion=10, browserName=MicrosoftEdge, takesScreenshot=true, pageLoadStrategy=normal, takesElementScreenshot=true, platformName=windows, platform=ANY}]
Session ID: F6B56EB0-2134-49C8-9E14-CA56E6420930 (org.openqa.selenium.WebDriverException)
	from [remote server] sun.reflect.NativeConstructorAccessorImpl():-1:in `newInstance'
	from [remote server] sun.reflect.DelegatingConstructorAccessorImpl():-1:in `newInstance'
	from [remote server] java.lang.reflect.Constructor():-1:in `newInstance'
	from [remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):206:in `createThrowable'
	from [remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):158:in `throwIfResponseFailed'
	from [remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):595:in `execute'
	from [remote server] org.openqa.selenium.remote.RemoteWebElement(RemoteWebElement.java):273:in `execute'
	from [remote server] org.openqa.selenium.remote.RemoteWebElement(RemoteWebElement.java):88:in `submit'
	from [remote server] sun.reflect.NativeMethodAccessorImpl():-2:in `invoke0'
	from [remote server] sun.reflect.NativeMethodAccessorImpl():-1:in `invoke'
	from [remote server] sun.reflect.DelegatingMethodAccessorImpl():-1:in `invoke'
	from [remote server] java.lang.reflect.Method():-1:in `invoke'
	from [remote server] org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1(EventFiringWebDriver.java):332:in `invoke'
	from [remote server] com.sun.proxy.$Proxy2():-1:in `submit'
	from [remote server] org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement(EventFiringWebDriver.java):350:in `submit'
	from [remote server] sun.reflect.NativeMethodAccessorImpl():-2:in `invoke0'
	from [remote server] sun.reflect.NativeMethodAccessorImpl():-1:in `invoke'
	from [remote server] sun.reflect.DelegatingMethodAccessorImpl():-1:in `invoke'
	from [remote server] java.lang.reflect.Method():-1:in `invoke'
	from [remote server] org.openqa.selenium.remote.server.KnownElements$1(KnownElements.java):64:in `invoke'
	from [remote server] com.sun.proxy.$Proxy3():-1:in `submit'
	from [remote server] org.openqa.selenium.remote.server.handler.SubmitElement(SubmitElement.java):30:in `call'
	from [remote server] org.openqa.selenium.remote.server.handler.SubmitElement(SubmitElement.java):1:in `call'
	from [remote server] java.util.concurrent.FutureTask():-1:in `run'
	from [remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
	from [remote server] java.util.concurrent.ThreadPoolExecutor():-1:in `runWorker'
	from [remote server] java.util.concurrent.ThreadPoolExecutor$Worker():-1:in `run'
	from [remote server] java.lang.Thread():-1:in `run'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:635:in `execute'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:455:in `submitElement'
	from /Users/cjohnson/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/element.rb:198:in `submit'
	from test_selenium_edge.rb:10:in `<main>'
```

**Comment by lukeis** [comment]
@chris1248 this is now a different issue... I would imagine your browser actually started and did something.

It appears that  element.submit() failed. Which I'd imagine you've encountered an Edge Driver bug, to which, can you please log a bug with Microsoft at  https://connect.microsoft.com/

**Comment by lukeis** [comment]
@chris1248 actually it says "not implemented" ... which is the case according to microsoft's own status of their webdriver implementation:

https://dev.modern.ie/platform/status/webdriver/details/

**Comment by chris1248** [comment]
Not implemented for doing what? Could someone explain this in plain language?

**Comment by lukeis** [comment]
"element.submit()" selenium API call is not implemented in the Microsoft Edge Driver

**Comment by chris1248** [comment]
So, how do you send keys to an input element then with Selenium?
does `send_keys` work without calling .submit()?

**Comment by lukeis** [comment]
yes, you can call send_keys without submit.

Typically .submit is a shortcut to submitting a form, often forms have a button that you could .click() on instead of submit, or some forms allow one to press the enter key to submit and you could send that key at the end.

**Comment by chris1248** [comment]
let me give that a try.
