### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.InvalidArgumentException: Message: invalid argument (only in Linux)

### ISSUE THREAD

**Issue by joaomaranhao** [SeleniumHQ/selenium#10837]
### What happened?

When I run my code on Linux it returns this error
On Windows it works just as expected
I have this code:
```
cwd = os.getcwd()
html_path = os.path.join(cwd, 'assets', 'thumbnail.html')
self.scrapper.driver.get(html_path)
```

On Linux, it returns: /home/jmaranhao/Documents/video-maker/assets/thumbnail.html
That's the "invalid" string

### How can we reproduce the issue?

```shell
Just create a driver and have an HTML local file
Pass HTML to the function driver.get(html_path)
```

### Relevant log output

```shell
[WDM] - ====== WebDriver manager ======
[WDM] - Current brave-browser version is 102
[WDM] - Get LATEST chromedriver version for 102 brave-browser
[WDM] - Driver [/home/jmaranhao/.wdm/drivers/chromedriver/linux64/102.0.5005.61/chromedriver] found in cache
Traceback (most recent call last):
  File "/home/jmaranhao/Documents/video-maker/video_maker/main.py", line 11, in <module>
    thumb_creator.create_thumbnail()
  File "/home/jmaranhao/Documents/video-maker/video_maker/usecases/create_thumbnail.py", line 26, in create_thumbnail
    self.scrapper.driver.get(html_path)
  File "/home/jmaranhao/Documents/video-maker/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in get
    self.execute(Command.GET, {'url': url})
  File "/home/jmaranhao/Documents/video-maker/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/home/jmaranhao/Documents/video-maker/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: headless chrome=102.1.39.122)
```

### Operating System

Fedora 35

### Selenium version

Python 4.3.0

### What are the browser(s) and version(s) where you see this issue?

Brave 102

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 102.0.5005.61

**Comment by diemol** [comment]
Can you just create a complete code sample we can use to reproduce your issue? It will help us a lot and just take shorter to troubleshoot this.

**Comment by joaomaranhao** [comment]
Hey, I solved it by just putting "file://" in front of absolute path for the file

driver.get('file://' + html_path)

now it works on both Linux and Windows
