### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by Bilal209** [SeleniumHQ/selenium#10839]
### What happened?

I am having an issue in launching the chrome driver using selenium.

### How can we reproduce the issue?

```shell
package newproject;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class newclass {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
      System.setProperty("webdriver.chrome.driver","C:\\Users\\bilal\\Downloads\\chromedriver_win32.exe");
	    WebDriver driver = new ChromeDriver();
	    driver.get("https://www.google.com/");
	}

}



Problems
Exception in thread "main" java.lang.IllegalStateException: The driver executable must exist: C:\Users\bilal\Downloads\chromedriver_win32.exe
	at org.openqa.selenium.internal.Require$FileStateChecker.isFile(Require.java:342)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:147)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:142)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:39)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:233)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:437)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:128)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:49)
	at newproject.newclass.main(newclass.java:11)
```

### Relevant log output

```shell
Chromepage
```

### Operating System

Window10

### Selenium version

Java  4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 

### What are the browser driver(s) and version(s) where you see this issue?

Chrome  103.0.5060.66

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
The error message says that you do not have that file in that location.

Consider placing the driver in a directory on PATH or using a Driver Manager: https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/
