### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by uwemneku** [SeleniumHQ/selenium#10897]
### What happened?

Using node js. I've created some test automation using the page model architecture. They work fine on my laptop but my colleague gets this error below when they try to run it. 
<img src="https://i.ibb.co/NsmWbGr/image.png" alt="image" border="0">
Would appreciate any idea on how to go about debugging the issue
```ts
async function loginFromHomePage(page: BasePage) {
  const { password, phoneNumber } = LoginConfig.loginDetails;
  try {
    await page.get(`${page.baseUrl}/login`);
    await page.driver.executeScript("localStorage.clear()")
    await page.driver.navigate().refresh()
    await skipCookiesDialogue(page)

   // it throws an error at this point
    const loginByCellButton = await page.driver.wait(
      until.elementLocated(By.id("loginWithCellButton")),
      10000
    ); // wait for a maximum of 10 seconds for the login button to appear

      await page.driver.wait(until.elementIsEnabled(loginByCellButton), 10000); // wait for a maximum of 10 seconds for the login button to be enabled);
      await loginByCellButton.click();

    // find the phone number and password input then send keys
    const inputs = await page.findAll(
      "input.MuiInputBase-input.MuiFilledInput-input",
      80000
    );
    await Promise.all([
      inputs[0].sendKeys(phoneNumber),
      inputs[1].sendKeys(password),
    ]);

    // find the login button and click it
    const loginButton = await page.driver.findElement(By.name("button"));
    await loginButton.click();

    // if we can find the play button, we are logged in
    const playButton = await page.find("#firstTimeDialogPlayButton", 20000);
    await page.driver.wait(until.elementIsVisible(playButton), 5000);
    await playButton.click();

  } catch (error) {
    throw new Error("There was an error logging in from homepage");
  }
}
```

### How can we reproduce the issue?

```shell
export default async function skipCookiesDialogue(page: BasePage ) {
  const el = await page.find(`.cookieDialogue`, 5000); //uses a maximum of 5sec to find the element
  const dialogue = await page.driver.wait(until.elementIsVisible(el))

  const el2 = dialogue.findElement(By.css(".acceptBtn"))
  const acceptButton = await page.driver.wait(until.elementIsEnabled(el2))

  await acceptButton.click()

  await page.driver.sleep(250) //wait for half a second for modal to close
}

async function loginFromHomePage(page: BasePage) {
  const { password, phoneNumber } = LoginConfig.loginDetails;
  try {
    await page.get(`${page.baseUrl}/login`);
    await page.driver.executeScript("localStorage.clear()")
    await page.driver.navigate().refresh()
    await skipCookiesDialogue(page)

   // it throws an error at this point
    const loginByCellButton = await page.driver.wait(
      until.elementLocated(By.id("loginWithCellButton")),
      10000
    ); // wait for a maximum of 10 seconds for the login button to appear

      await page.driver.wait(until.elementIsEnabled(loginByCellButton), 10000); // wait for a maximum of 10 seconds for the login button to be enabled);
      await loginByCellButton.click();

    // find the phone number and password input then send keys
    const inputs = await page.findAll(
      "input.MuiInputBase-input.MuiFilledInput-input",
      80000
    );
    await Promise.all([
      inputs[0].sendKeys(phoneNumber),
      inputs[1].sendKeys(password),
    ]);

    // find the login button and click it
    const loginButton = await page.driver.findElement(By.name("button"));
    await loginButton.click();

    // if we can find the play button, we are logged in
    const playButton = await page.find("#firstTimeDialogPlayButton", 20000);
    await page.driver.wait(until.elementIsVisible(playButton), 5000);
    await playButton.click();

  } catch (error) {
    throw new Error("There was an error logging in from homepage");
  }
```

### Relevant log output

```shell
DevTools listening on ws://127.0.0.1:56896/devtools/browser/2c60a25e-2447-4323-b022-ab8aaea0bebe
    1) "before all" hook for "Should display Menu button"


  0 passing (20s)
  1 failing

  1) Side bar test
       "before all" hook for "Should display Menu button":
     WebDriverError: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.134)
      at Object.throwDecodedError (node_modules\selenium-webdriver\lib\error.js:522:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:589:13)
      at Executor.execute (node_modules\selenium-webdriver\lib\http.js:514:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at thenableWebDriverProxy.execute (node_modules\selenium-webdriver\lib\webdriver.js:740:17)
      at thenableWebDriverProxy.findElements (node_modules\selenium-webdriver\lib\webdriver.js:1066:17)
```

### Operating System

windows 10

### Selenium version

4.3.1

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 103.0.5060.134

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 103

**Comment by titusfortner** [comment]
Selenium is doing the right thing, so there's nothing for us to do.

I'd suggest checking what platform/versioning things are different to see why one is working and the other isn't.
