### ISSUE TITLE
[🐛 Bug]: java.lang.UnsupportedOperationException: getDomAttribute while using select in Selenium 4

### ISSUE THREAD

**Issue by manvirsinghparmar** [SeleniumHQ/selenium#10905]
### What happened?

I recently updated my project from 3.141.59 to Selenium 4.0.0. 
Most of it went pretty well, however whenever my script uses the Select class constructor, it throws an error java.lang.UnsupportedOperationException: getDomAttribute.

I read the various stacks that it might be compatibility issue or W3C protocol is not being followed.

I checked all of these and didn't found any problem with those.

Maven dependency version:
![image](https://user-images.githubusercontent.com/38955635/180921885-7fd047ea-4f0a-4cf5-8677-08a4bd51ce4c.png)

Code snip:
![image](https://user-images.githubusercontent.com/38955635/180920992-ee94c60c-b7cf-470b-b639-64f5d2ad4d4a.png)

It follows W3C
![image](https://user-images.githubusercontent.com/38955635/180920275-0a0a6df6-6674-444c-9dc7-398a26075930.png)

Actual error:
![image](https://user-images.githubusercontent.com/38955635/180920557-9989456d-68ca-4cae-9eea-dace089a5420.png)

### How can we reproduce the issue?

```shell
i have attached snip in 'what happened' section
```

### Relevant log output

```shell
[RemoteTestNG] detected TestNG version 6.14.3
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.

.
.
..
.

00:00:25.840 [EnvironmentUtil.setSystemProperty()] INFO : Set property: rfa.backup.config = accounts-dev.xml
00:00:25.842 [DeviceUtil.getDevice()] INFO : System property: device = null
00:00:25.845 [DeviceUtil.getDevice()] INFO : Device: DESKTOP
00:00:25.859 [BrowserUtil.getBrowser()] INFO : System property: portal.browser = null
00:00:25.860 [BrowserUtil.getBrowser()] INFO : System property: browser = null
00:00:25.860 [BrowserUtil.getBrowser()] INFO : Browser: CHROME
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 103.0.5060.134 (8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}) on port 51132
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Jul 26, 2022 12:00:28 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Jul 26, 2022 12:00:28 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 103, so returning the closest version found: a no-op implementation
Jul 26, 2022 12:00:28 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Unable to find CDP implementation matching 103.
Jul 26, 2022 12:00:28 AM org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
WARNING: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.0.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
..
.
.
.
.
.
.
  When User select macOS from the drop down menu on the webroot secure anywhere protection dialog                               # com.carbonite.step.definitions.WebrootSecureAnywhereProtectionDialogSteps.user_select_mac_os_from_the_drop_down_menu_on_the_webroot_secure_anywhere_protection_dialog(java.lang.String)
      java.lang.UnsupportedOperationException: getDomAttribute
	at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)
	at com.carbonite.browser.ProxyDriver.selectDropdownOption(ProxyDriver.java:1013)
	at com.carbonite.browser.ProxyDriver.selectDropdownOption(ProxyDriver.java:953)
	at com.carbonite.browser.ProxyDriver.selectDropdownOption(ProxyDriver.java:936)
	at com.carbonite.customerportal.flows.dialogs.WebrootSecureAnywhereProtectionDialog.selectOSFromDropDown(WebrootSecureAnywhereProtectionDialog.java:104)
	at com.carbonite.step.definitions.WebrootSecureAnywhereProtectionDialogSteps.user_select_mac_os_from_the_drop_down_menu_on_the_webroot_secure_anywhere_protection_dialog(WebrootSecureAnywhereProtectionDialogSteps.java:142)
	at ✽.User select macOS from the drop down menu on the webroot secure anywhere protection dialog(file:///C:/Users/manvirs/git/Redbull-Automation/Portals/VueDawnPortal/features/Download%20Page/Download.feature:112)

  And user clicks on download button on the webroot secure anywhere protection dialog                                           # com.carbonite.step.definitions.WebrootSecureAnywhereProtectionDialogSteps.user_clicks_on_download_button_on_the_webroot_secure_anywhere_protection_dialog()
  Then verify webroot client is downloaded successfully                                                                         # com.carbonite.step.definitions.WebrootSecureAnywhereProtectionDialogSteps.verify_webroot_secure_anywhere_protection_file_is_downloaded_with_filename()

    Embedding Screenshot [image/png 150796 bytes]

00:02:17.557 [Hooks.after()] INFO : Closing Webdriver !!
FAILED: runScenario("Validate that OS is detected and displayed as first option on downloading WSA App from My available Downloads", "Optional[Downloads Page]")
        Runs Cucumber Scenarios
java.lang.UnsupportedOperationException: getDomAttribute
	at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)
	at com.carbonite.browser.ProxyDriver.selectDropdownOption(ProxyDriver.java:1013)
	at com.carbonite.browser.ProxyDriver.selectDropdownOption(ProxyDriver.java:953)
	at com.carbonite.browser.ProxyDriver.selectDropdownOption(ProxyDriver.java:936)
	at com.carbonite.customerportal.flows.dialogs.WebrootSecureAnywhereProtectionDialog.selectOSFromDropDown(WebrootSecureAnywhereProtectionDialog.java:104)
	at com.carbonite.step.definitions.WebrootSecureAnywhereProtectionDialogSteps.user_select_mac_os_from_the_drop_down_menu_on_the_webroot_secure_anywhere_protection_dialog(WebrootSecureAnywhereProtectionDialogSteps.java:142)
	at ✽.User select macOS from the drop down menu on the webroot secure anywhere protection dialog(file:///C:/Users/manvirs/git/Redbull-Automation/Portals/VueDawnPortal/features/Download%20Page/Download.feature:112)


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================
```

### Operating System

Window 10

### Selenium version

Selenium 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Browser Chrome , Version :103.0.5060.134

### What are the browser driver(s) and version(s) where you see this issue?

I am using Webdriver manager api

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
It is hard to say what the issue is. Maybe you can attach a script to reproduce the issue if it is still happening after upgrading to the most recent version (4.3.0).

**Comment by owenatkinson-kainos** [comment]
Within a recent selenium upgrade, it looks like the Select class constructor now uses `getDomAttribute` (it previously used `getAttribute`). I managed to get around this issue by:

- Creating my own Java class & copy pasting all contents of the Selenium Select.class into it
- Renaming the class e.g. NewSelect
- Change the `element.getDomAttribute` to `element.getAttribute`
- Where your script references Select class constructor, replace with the NewSelect class constructor

Hopefully that works for you until Selenium patch the bug 🤞

**Comment by manvirsinghparmar** [comment]
Well, I created a small project to test if SELECT is working otherwise(outside of my company framework), the result is that the Select is working in that scenario for the same web element...

I tried to figured out dependencies conflicts in the small project, but even after trying all combination, still Select was working fine...

**Comment by diemol** [comment]
@manvirsinghparmar understood, so this points that something might be off in your internal framework? 

If you need more help figuring that part out, feel free to ask the community at https://www.selenium.dev/support/

**Comment by titusfortner** [comment]
This issue is almost always a dependency management issue.

Please make sure that your project is correctly using Selenium 4 libraries for everything. I've found this guide by @asolntsev  helpful for this: https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html
