### ISSUE TITLE
[🚀 Feature]: Degrade more gracefully if relay server is not reachable

### ISSUE THREAD

**Issue by mythsunwind** [SeleniumHQ/selenium#10908]
### Feature and motivation

Currently the node stops with a NullPointerException if the relay server is not reachable.

Example:

relay.toml
```
[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://localhost:4723"
status-endpoint = "/status"
configs = [
  "1", "{\"browserName\": \"chrome\", \"platformName\": \"android\", \"version\": \"11\"}"
]
```

Running `java -jar selenium-server-4.3.0.jar node --config relay.toml` results in the following output if localhost:4723 cannot be reached:
```
11:12:01.767 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
11:12:01.771 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
11:12:01.881 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
11:12:01.923 INFO [UnboundZmqEventBus.<init>] - Sockets created
11:12:02.929 INFO [UnboundZmqEventBus.<init>] - Event bus ready
11:12:03.054 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.121.96:5555
11:12:03.075 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:151)
	at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:127)
	at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:183)
	at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:231)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
	... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: Unable to reach the service at http://localhost:4723
	at org.openqa.selenium.grid.node.relay.RelayOptions.isServiceUp(RelayOptions.java:119)
	at org.openqa.selenium.grid.node.relay.RelayOptions.getSessionFactories(RelayOptions.java:131)
	at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:89)
	... 22 more
Exception in thread "Thread-0" java.lang.NullPointerException
	at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:79)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The output contains a clear error message why it is not working (Unable to reach the service at http://localhost:4723) but the java program completely exits leaving no possibility that the relay server is slow in starting up or is only temporary unreachable.

### Usage example

A retry mechanism would make it possible that the node does not need to be restarted every time the relay server is too slow in starting up (happens with appium) or is only temporary unreachable.

**Comment by diemol** [comment]
Thanks for the report, @mythsunwind. It does make sense. I've pushed a fix and it will be included in 4.4, which should be released in 1-2 days.
