### ISSUE TITLE
Edge Driver doesn't support maximize method  

### ISSUE THREAD

**Issue by tobecrazy** [SeleniumHQ/selenium#1092]
My code :	 
		EdgeOptions options = new EdgeOptions();
		options.setPageLoadStrategy( "eager");  
		WebDriver driver = new EdgeDriver(options );
		driver.get("https://www.baidu.com");
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		driver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS);
		driver.manage().window().maximize();

Exceptions:
org.openqa.selenium.UnsupportedCommandException: Unknown command received
Command duration or timeout: 8 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 02:56:46'
System info: host: 'Young-PC', ip: '192.168.28.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_79'
Session ID: 8F4F392C-B41E-4E62-9A50-692D20EB368E
Driver info: org.openqa.selenium.edge.EdgeDriver
Capabilities [{platformVersion=10, platform=ANY, acceptSslCerts=true, browserVersion=20.10240.16384.0, platformName=windows, browserName=MicrosoftEdge, takesElementScreenshot=true, takesScreenshot=true, pageLoadStrategy=eager}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:833)org.openqa.selenium.UnsupportedCommandException: Unknown command received
Command duration or timeout: 8 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 02:56:46'
System info: host: 'Young-PC', ip: '192.168.28.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_79'
Session ID: 8F4F392C-B41E-4E62-9A50-692D20EB368E
Driver info: org.openqa.selenium.edge.EdgeDriver
Capabilities [{platformVersion=10, platform=ANY, acceptSslCerts=true, browserVersion=20.10240.16384.0, platformName=windows, browserName=MicrosoftEdge, takesElementScreenshot=true, takesScreenshot=true, pageLoadStrategy=eager}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:833)

**Comment by jimevans** [comment]
The Selenium project does not maintain the Edge driver; Microsoft does. Any issues with functionality must be taken up with them. Looking at [their status page](https://dev.modern.ie/platform/status/webdriver/details/) for the driver, maximize was implemented in build 10532, which is not the initial release of the driver. It would require an Insider build of both Windows 10 and the driver executable.

**Comment by tobecrazy** [comment]
Ok, I see. Thanks
