### ISSUE TITLE
[🐛 Bug]: Exception Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

### ISSUE THREAD

**Issue by avishekhece** [SeleniumHQ/selenium#10939]
### What happened?

Not able to Run selenium 4.4.0. 
Browser not opening 

### How can we reproduce the issue?

```shell
Not able to Run selenium 4.4.0. 
Browser not opening 
all dependencies are updated with the latest version
```

### Relevant log output

```shell
Exception Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.4.0', revision: ''
System info: host: '', ip: '', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: MicrosoftEdge, elementScrollBehavior: 1, ensureCleanSession: true, logLevel: ERROR, ms:edgeOptions: {args: [], extensions: []}, nativeEvents: true, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: MicrosoftEdge, elementScrollBehavior: 1, ensureCleanSession: true, logLevel: ERROR, ms:edgeOptions: {args: [], extensions: []}, nativeEvents: true, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss}}]
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.4.0', revision: ''
System info: host: '', ip: '', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: MicrosoftEdge, elementScrollBehavior: 1, ensureCleanSession: true, logLevel: ERROR, ms:edgeOptions: {args: [], extensions: []}, nativeEvents: true, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: MicrosoftEdge, elementScrollBehavior: 1, ensureCleanSession: true, logLevel: ERROR, ms:edgeOptions: {args: [], extensions: []}, nativeEvents: true, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss}}]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:565)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:54)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:46)
	
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.steepgraph.ta.framework.MasterApp.start(MasterApp.java:215)
	at com.sgs.xray.Launcher.main(Launcher.java:26)
Caused by: java.lang.NoSuchMethodError: io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:123)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
	at org.asynchttpclient.netty.request.NettyRequestFactory.newNettyRequest(NettyRequestFactory.java:114)
	at org.asynchttpclient.netty.request.NettyRequestSender.newNettyRequestAndResponseFuture(NettyRequestSender.java:204)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:136)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:114)
	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:259)
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:228)
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:249)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:55)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:98)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:120)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	... 36 more
```

### Operating System

10

### Selenium version

4.4.0

### What are the browser(s) and version(s) where you see this issue?

edge

### What are the browser driver(s) and version(s) where you see this issue?

Version 104.0.1293.54

**Comment by diemol** [comment]
How can we reproduce the issue?

**Comment by apetrichkovich** [comment]
Hello.
I've an exception on the server.
What i'm doing wrong?
Please help.

**OS:** CentOS 7.9.2009 (x86-64)
**Java:** OpenJDK 64-Bit Server VM (Red_Hat-11.0.16.0.8-1.el7_9) (build 11.0.16+8-LTS, mixed mode, sharing)
**Google Chrome:** 104.0.5112.101
**Chrome Driver:** 104.0.5112.79 (3cf3e8c8a07d104b9e1260c910efb8f383285dc5-refs/branch-heads/5112@{#1307})
**Selenium dependencies:** selenium-chrome-driver, selenium-remote-driver, selenium-api, selenium-java (4.4.0)

**Code:**
```
System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver");

ChromeOptions options = new ChromeOptions()
	.addArguments("--start-maximized")
	.addArguments("--window-size=1366,1080")
	.addArguments("--enable-automation")
	.addArguments("--headless")
	.addArguments("--no-sandbox")
	.addArguments("--disable-infobars")
	.addArguments("--disable-dev-shm-usage")
	.addArguments("--disable-browser-side-navigation")
	.addArguments("--disable-gpu")
	.addArguments("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36");

WebDriver chromeDriver = new ChromeDriver(options);
	chromeDriver.manage().timeouts().implicitlyWait(Duration.ofMinutes(1));
	chromeDriver.manage().timeouts().scriptTimeout(Duration.ofMinutes(1));
	chromeDriver.manage().timeouts().pageLoadTimeout(Duration.ofMinutes(1));
```
	
**Exception:**
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:565) ~[selenium-remote-driver-4.4.0.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242) ~[selenium-remote-driver-4.4.0.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157) ~[selenium-remote-driver-4.4.0.jar!/:na]
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101) ~[selenium-chromium-driver-4.4.0.jar!/:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:81) ~[selenium-chrome-driver-4.4.0.jar!/:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:70) ~[selenium-chrome-driver-4.4.0.jar!/:na]
	at tv.televizor.crypto.service.impl.PageServiceImpl.getChromeDriver(PageServiceImpl.java:59) ~[classes!/:0.0.1-SNAPSHOT]
	at tv.televizor.crypto.service.impl.PageServiceImpl.getJson(PageServiceImpl.java:121) ~[classes!/:0.0.1-SNAPSHOT]
	at tv.televizor.crypto.service.impl.ParserServiceImpl.getOffers(ParserServiceImpl.java:54) ~[classes!/:0.0.1-SNAPSHOT]
	at tv.televizor.crypto.service.impl.ParserServiceImpl.parseData(ParserServiceImpl.java:74) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.19.jar!/:5.3.19]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.19.jar!/:5.3.19]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.19.jar!/:5.3.19]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'webad', ip: '95.216.201.155', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.59.1.el7.x86_64', java.version: '11.0.16'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:230) ~[selenium-remote-driver-4.4.0.jar!/:na]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98) ~[selenium-remote-driver-4.4.0.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547) ~[selenium-remote-driver-4.4.0.jar!/:na]
	... 22 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'webad', ip: '95.216.201.155', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.59.1.el7.x86_64', java.version: '11.0.16'
Driver info: driver.version: unknown
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~[na:na]
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:220) ~[selenium-remote-driver-4.4.0.jar!/:na]
	... 24 common frames omitted
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'webad', ip: '95.216.201.155', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.59.1.el7.x86_64', java.version: '11.0.16'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:251) ~[selenium-remote-driver-4.4.0.jar!/:na]
	at org.openqa.selenium.remote.service.DriverService.lambda$start$1(DriverService.java:205) ~[selenium-remote-driver-4.4.0.jar!/:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
	... 3 common frames omitted
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:36294/status] to be available after 20006 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89) ~[selenium-api-4.4.0.jar!/:na]
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:247) ~[selenium-remote-driver-4.4.0.jar!/:na]
	... 5 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[na:na]
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:87) ~[selenium-api-4.4.0.jar!/:na]
	... 6 common frames omitted
```

**Comment by titusfortner** [comment]
I think these are likely different issues.

@avishekhece we need to know what code you're using so we can figure out why you are having a problem that other people are not having.

@apetrichkovich it is recommended when starting sessions on a *nix machine that does not have a GUI to run Chrome in "normal" mode with xvfb rather than in headless mode. Fewer problems that way. For this error, make sure chrome is installed properly and consider specifying the location directly in the options class.
