### ISSUE TITLE
[🐛 Bug]: SetExperimental option is not available in webdriverjs (Javascript/Typescript)

### ISSUE THREAD

**Issue by sent2280** [SeleniumHQ/selenium#10959]
### What happened?

i am trying to connect with already opened chrome session using the following code:

 let options : Options = new Options();
      options.windowSize({width: 1920,height : 1080});
      options.setExperimentalOption({"debuggerAddress" : "localhost:9950"});
      this.driver  = await new Builder().forBrowser('chrome').setChromeOptions(options).build();

But i am getting error as "Property 'setExperimentalOption' does not exist on type 'Options'". 

How we can connect to existing browser, which is opened with remote-debugging(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debuggin-port=9950) ?

Note: 
   i am using mac os.
 
 Using following dependency:

 "@types/chai": "^4.3.3",
    "@types/expect": "^24.3.0",
    "@types/mocha": "^9.1.1",
    "@types/node": "^18.0.3",
    "@types/selenium-webdriver": "^4.1.1",
    "chai": "^4.3.6",
    "geckodriver": "^3.0.2",
    "mocha": "^10.0.0",
    "selenium-webdriver": "^4.3.1",
    "ts-mocha": "^10.0.0",
    "typescript": "^4.7.4"
chromedriver": "^104.0.0"

chrome browser and driver version is 104

### How can we reproduce the issue?

```shell
code:

import { Options } from 'selenium-webdriver/chrome';
import {Builder} from 'selenium-webdriver';

  let options : Options = new Options();
      options.windowSize({width: 1920,height : 1080});
      options.setExperimentalOption({"debuggerAddress" : "localhost:9950"});
      this.driver  = await new Builder().forBrowser('chrome').setChromeOptions(options).build();
      await this.driver.get('https://www.google.co.in/');
```

### Relevant log output

```shell
output:


TSError: ⨯ Unable to compile TypeScript:
spec/vbdpoc.spec.ts(34,15): error TS2339: Property 'setExperimentalOption' does not exist on type 'Options'.

    at createTSError (/Users/sesellam/Desktop/POCWorkspace/spectraui_vbdt/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/sesellam/Desktop/POCWorkspace/spectraui_vbdt/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/sesellam/Desktop/POCWorkspace/spectraui_vbdt/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/sesellam/Desktop/POCWorkspace/spectraui_vbdt/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/sesellam/Desktop/POCWorkspace/spectraui_vbdt/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (/Users/sesellam/Desktop/POCWorkspace/spectraui_vbdt/node_modules/mocha/lib/nodejs/esm-utils.js:49:16)
    at Object.exports.loadFilesAsync (/Users/sesellam/Desktop/POCWorkspace/spectraui_vbdt/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
    at singleRun (/Users/sesellam/Desktop/POCWorkspace/spectraui_vbdt/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/Users/sesellam/Desktop/POCWorkspace/spectraui_vbdt/node_modules/mocha/lib/cli/run.js:370:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

### Operating System

macOS Monterey

### Selenium version

"selenium-webdriver": "^4.3.1"

### What are the browser(s) and version(s) where you see this issue?

chrome 104

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver - 104

**Comment by TamsilAmani** [comment]
@sent2280 

I was able to reproduce the issue and found a fix. Can you re-place the line:

`options.setExperimentalOption({"debuggerAddress" : "localhost:9950"});` with

`options.addArguments("--remote-debugging-port=9950");`

This works on my machine and chrome listens on 9950. This is correct way in my opinion.

@pujagani The approach of adding the function signature `setExperimentalOption()` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/selenium-webdriver/chrome.d.ts#L48 didn't feel correct as Selenium JS has no such method.

**Comment by titusfortner** [comment]
`setExperimentalOption()` is a workaround in other languages for not being able to set each of these directly: https://chromedriver.chromium.org/capabilities#h.p_ID_102

Note that `debuggerAddress` is on that list, and as such it should be used in top-level of `goog:chromeOptions` which is why JS allows you to set it directly:
https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/chromium.js#L307

Ideally once we know about a valid property in the browser we should support it directly rather than relying on `setExperimentalOption`, but probably more work than it's worth right now.

**Comment by titusfortner** [comment]
Also, it would really help if we had our docs fleshed out with this info so it would be less confusing for users. We'll get there.

**Comment by sanjeevavreddy** [comment]
@sent2280 Did you find any solution for this??

**Comment by titusfortner** [comment]
The equivalent to `setExperimentalOption` is to use `debuggerAddress` which I linked to above.
