### ISSUE TITLE
screenshot + firefox 41 + w3c test == exception

### ISSUE THREAD

**Issue by hrj** [SeleniumHQ/selenium#1097]
Selenium version: 2.47.2
Firefox version: 41

To reproduce the bug:

``` scala
val d = new org.openqa.selenium.firefox.FirefoxDriver()
d.navigate.to("http://test.csswg.org/suites/css21_dev/nightly-unstable/xhtml1/root-box-003.xht")
d.getScreenshotAs(org.openqa.selenium.OutputType.BYTES)
```

causes:

```
org.openqa.selenium.WebDriverException: Could not convert screenshot to base64 - Error: Invalid base64 data: data:,
Command duration or timeout: 24 milliseconds
Build info: version: '2.47.2', revision: '4d972c01cab1304452627f837654326a11eb92fe', time: '2015-09-24 09:17:17'
System info: host: 'linux'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=41.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: "xxx"
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
  at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
  at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
  at org.openqa.selenium.firefox.FirefoxDriver.getScreenshotAs(FirefoxDriver.java:354)
  ... 43 elided
Caused by: org.openqa.selenium.WebDriverException: Could not convert screenshot to base64 - Error: Invalid base64 data: data:,
```

**Comment by barancev** [comment]
This issue is still actual in legacy Firefox driver, but it's not going to be fixed there.
New Firefox driver implementation (aka geckodriver) does not suffer from this issue.
