### ISSUE TITLE
[🐛 Bug]: Selenium-4 actions class giving error Exception in thread "main" org.openqa.selenium.ElementNotInteractableException

### ISSUE THREAD

**Issue by pavanwashimkar** [SeleniumHQ/selenium#10993]
### What happened?

With selenium4, we are not able to use Actions class and for most of the cases where we are using moveToElement(), we are getting below error.

Exception in thread "main" org.openqa.selenium.ElementNotInteractableException

Please note we are getting this error in both normal and grid mode.

### How can we reproduce the issue?

```shell
Please run the below code to reproduce the issue.

import io.github.bonigarcia.wdm.WebDriverManager;
import io.github.bonigarcia.wdm.config.DriverManagerType;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

import java.net.MalformedURLException;
import java.net.URL;

public class TestActionsClass {
    public static void main(String args[]) {
        WebDriverManager.getInstance(DriverManagerType.CHROME).setup();
        WebDriver webDriver = null;
        try {
            DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
            //desiredCapabilities.setCapability("myCapabilityName", "myCapabilityValue");
            ChromeOptions chromeOptions = new ChromeOptions();
            chromeOptions.addArguments("--no-sandbox");
            desiredCapabilities.merge(chromeOptions);
            webDriver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), desiredCapabilities);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        webDriver.manage().window().maximize();

        webDriver.get("https://the-internet.herokuapp.com/hovers");
        try {
            Thread.sleep(1000*10);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        //WebElement element = webDriver.findElement(By.xpath("//h5[contains(text(),'user2')]"));
        WebElement element = webDriver.findElement(By.xpath("//a[contains(@href,'users/1')]"));
        String propertyName = element.getAttribute("href");
        try {
            Thread.sleep(1000*20);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("Check111 :: " + propertyName + " :: " +element.getTagName() + " :: " + element.getAttribute("alt"));
        //driver.hoverAndClickOnElement(element);
        Actions builder = new Actions(webDriver);
        builder.moveToElement(element);
        builder.click();
        builder.build().perform();
        //builder.click(element);

      
        builder.build().perform();*/
                System.out.println("Check123 :: " + propertyName + " :: ");

        }

}
```

### Relevant log output

```shell
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 104.0.5112.79 (resolved driver for Chrome 104)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\pavan.washimkar\.cache\selenium\chromedriver\win32\104.0.5112.79\chromedriver.exe
Sep 01, 2022 4:46:56 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
Sep 01, 2022 4:47:15 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Check111 :: https://the-internet.herokuapp.com/users/1 :: a :: null
Exception in thread "main" org.openqa.selenium.ElementNotInteractableException: element not interactable: https://the-internet.herokuapp.com/users/1 has no size and location
  (Session info: chrome=104.0.5112.102)
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'PUNITP375008L', ip: '10.170.178.188', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [f6354e038d092dce2190e9b05dc35d50, actions {actions=[org.openqa.selenium.interactions.Sequence@889d9e8]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 104.0.5112.102, chrome: {chromedriverVersion: 103.0.5060.134 (8ec6fce403b..., userDataDir: C:\Users\PAVAN~1.WAS\AppDat...}, goog:chromeOptions: {debuggerAddress: localhost:56412}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://192.168.0.129:4444/ses..., se:cdpVersion: 104.0.5112.102, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: f6354e038d092dce2190e9b05dc35d50
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:615)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:567)
	at TestActionsClass.main(TestActionsClass.java:51)

Process finished with exit code 1
```

### Operating System

Windows 10

### Selenium version

Java 4.4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 104.0.5112.102 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 104.0.5112.102

### Are you using Selenium Grid?

4.4.0

**Comment by titusfortner** [comment]
You need to move to the image element before the link will become displayed and it has to be displayed for you to click it.
