### ISSUE TITLE
[🐛 Bug]: Python chromium webdriver fails to start

### ISSUE THREAD

**Issue by j54n1n** [SeleniumHQ/selenium#11001]
### What happened?

Running Chromium headless on Debian 11 with latest packages and via python bindings crashes with:
```
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

### How can we reproduce the issue?

```shell
#!/usr/bin/env python3
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("--headless")
driver = webdriver.Chrome(options=chrome_options)
driver.get("https://example.tld")
print(driver.page_source.encode("utf-8"))
driver.quit()
```

### Relevant log output

```shell
$ ./run-headless-chrome.py
Traceback (most recent call last):
  File "/home/julian/tmp/./run-headless-chrome.py", line 7, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55e2da887193 <unknown>
#1 0x55e2da678b66 <unknown>
#2 0x55e2da69e21f <unknown>
#3 0x55e2da69a279 <unknown>
#4 0x55e2da6dacc3 <unknown>
#5 0x55e2da6d4bd3 <unknown>
#6 0x55e2da6a4872 <unknown>
#7 0x55e2da6a5e1e <unknown>
#8 0x55e2da8c578d <unknown>
#9 0x55e2da8c75e0 <unknown>
#10 0x55e2da8c70e7 <unknown>
#11 0x55e2da8c7c55 <unknown>
#12 0x55e2da8b49cb <unknown>
#13 0x55e2da8c7f86 <unknown>
#14 0x55e2da8a8eae <unknown>
#15 0x55e2da8dff95 <unknown>
#16 0x55e2da8e0133 <unknown>
#17 0x55e2da8f9f90 <unknown>
#18 0x7f84c90eaea7 <unknown>
```

### Operating System

Debian 11

### Selenium version

Python 4.4.3

### What are the browser(s) and version(s) where you see this issue?

Chromium 105.0.5195.52-1~deb11u1

### What are the browser driver(s) and version(s) where you see this issue?

ChromiumDriver 105.0.5195.52-1~deb11u1

### Are you using Selenium Grid?

None

**Comment by diemol** [comment]
What happens if you open ChromiumDriver directly and send a curl request to open the session, ex:
```json
{
	"capabilities": {
		"alwaysMatch": {
			"browserName": "chrome"
		}
	}
}
```

Does it work or do you get the same error?

**Comment by j54n1n** [comment]
I have a binary in `/usr/bin/chromedriver` and this is the output in terminal:
```
$ chromedriver
Starting ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```
and the curl request:
```
$ curl -XPOST http://localhost:9515/session -d '{ "capabilities": { "alwaysMatch": { "browserName": "chrome" }}}'
{"value":{"error":"unknown error","message":"unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)","stacktrace":"#0 0x56092e794193 \u003Cunknown>\n#1 0x56092e585b66 \u003Cunknown>\n#2 0x56092e5ab21f \u003Cunknown>\n#3 0x56092e5a7279 \u003Cunknown>\n#4 0x56092e5e7cc3 \u003Cunknown>\n#5 0x56092e5e1bd3 \u003Cunknown>\n#6 0x56092e5b1872 \u003Cunknown>\n#7 0x56092e5b2e1e \u003Cunknown>\n#8 0x56092e7d278d \u003Cunknown>\n#9 0x56092e7d45e0 \u003Cunknown>\n#10 0x56092e7d40e7 \u003Cunknown>\n#11 0x56092e7d4c55 \u003Cunknown>\n#12 0x56092e7c19cb \u003Cunknown>\n#13 0x56092e7d4f86 \u003Cunknown>\n#14 0x56092e7b5eae \u003Cunknown>\n#15 0x56092e7ecf95 \u003Cunknown>\n#16 0x56092e7ed133 \u003Cunknown>\n#17 0x56092e806f90 \u003Cunknown>\n#18 0x7f56667edea7 \u003Cunknown>\n"}}
```
so basically the same response as in python

**Comment by titusfortner** [comment]
This means that chromedriver doesn't know where to find the browser. 
Specify the path of the browser in the options using the `binary` parameter.

**Comment by j54n1n** [comment]
But I do not think this is the issue, my Chromium binary is at its place in `/usr/bin/chromium` and in the error message
```
(The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
it can clearly find that location.

This is the content of `/usr/bin/chromium`:
```sh
#!/bin/sh

# Chromium launcher

# Authors:
#  Fabien Tassin <fta@sofaraway.org>
# License: GPLv2 or later

APPNAME=chromium

GDB=/usr/bin/gdb
LIBDIR=/usr/lib/$APPNAME
BUILD_DIST="11.4"

usage () {
  echo "$APPNAME [-h|--help] [-g|--debug] [--temp-profile] [options] [URL]"
  echo
  echo "        -g or --debug              Start within $GDB"
  echo "        -h or --help               This help screen"
  echo "        --temp-profile             Start with a new and temporary profile"
  echo "        --enable-remote-extensions Allow extensions from remote sites"
  echo
  echo " Other supported options are:"
  MANWIDTH=80 man chromium | sed -e '1,/OPTIONS/d; /ENVIRONMENT/,$d'
  echo " See 'man chromium' for more details"
}

nosse3="\
The hardware on this system lacks support for the sse3 instruction set.
The upstream chromium project no longer supports this configuration.
For more information, please read and possibly provide input to their
bug tracking system at http://crbug.com/1123353"

case `uname -m` in
    i386|i586|i686|x86_64)
        # Check whether this system supports SSE3
        if ! grep -q sse3 /proc/cpuinfo; then
            xmessage "$nosse3"
            exit 1
        fi
        ;;
esac

# Source additional settings
for file in /etc/chromium.d/*; do
  test $file = /etc/chromium.d/README || expr $file : .*\.dpkg > /dev/null || . $file
done

# Use the /usr/bin helper script for generated launchers
if test -z "$CHROME_WRAPPER"; then
    export CHROME_WRAPPER="/usr/bin/$APPNAME"
fi

# Set the correct file name for the desktop file
export CHROME_DESKTOP="chromium.desktop"

# Set CHROME_VERSION_EXTRA text, which is displayed in the About dialog
DIST=`cat /etc/debian_version`
export CHROME_VERSION_EXTRA="built on Debian $BUILD_DIST, running on Debian $DIST"

want_debug=0
want_temp_profile=0
while [ $# -gt 0 ]; do
  case "$1" in
    -h | --help | -help )
      usage
      exit 0 ;;
    -g | --debug )
      want_debug=1
      shift ;;
    --temp-profile )
      want_temp_profile=1
      shift ;;
    --enable-remote-extensions )
      CHROMIUM_FLAGS="$CHROMIUM_FLAGS --enable-remote-extensions"
      shift ;;
    -- ) # Stop option prcessing
      shift
      break ;;
    * )
      break ;;
  esac
done

# Whitelist installed extensions that are specified via --load-extension
if [ -z "$(echo $CHROMIUM_FLAGS | grep \\-\\-enable-remote-extensions)" ]; then
  export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --disable-background-networking"
  export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --disable-extensions-except=$(echo $CHROMIUM_FLAGS | tr ' ' \\n | grep \\-\\-load-extension | cut -d= -f2 | tr \\n ,)"
fi

if [ $want_temp_profile -eq 1 ] ; then
  TEMP_PROFILE=`mktemp -d`
  echo "Using temporary profile: $TEMP_PROFILE"
  CHROMIUM_FLAGS="$CHROMIUM_FLAGS --user-data-dir=$TEMP_PROFILE"
fi

if [ $want_debug -eq 1 ] ; then
  if [ ! -x $GDB ] ; then
    echo "Sorry, can't find usable $GDB. Please install it."
    exit 1
  fi
  tmpfile=`mktemp /tmp/chromiumargs.XXXXXX` || { echo "Cannot create temporary file" >&2; exit 1; }
  trap " [ -f \"$tmpfile\" ] && /bin/rm -f -- \"$tmpfile\"" 0 1 2 3 13 15
  echo "set args $CHROMIUM_FLAGS --single-process ${1+"$@"}" > $tmpfile
  echo "# Env:"
  echo "#     LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
  echo "#                PATH=$PATH"
  echo "#            GTK_PATH=$GTK_PATH"
  echo "#      CHROMIUM_FLAGS=$CHROMIUM_FLAGS"
  echo "$GDB $LIBDIR/$APPNAME -x $tmpfile"
  $GDB "$LIBDIR/$APPNAME" -x $tmpfile
  if [ $want_temp_profile -eq 1 ] ; then
    rm -rf $TEMP_PROFILE
  fi
  exit $?
else
  if [ $want_temp_profile -eq 0 ] ; then
    exec $LIBDIR/$APPNAME $CHROMIUM_FLAGS "$@"
  else
    # we can't exec here as we need to clean-up the temporary profile
    $LIBDIR/$APPNAME $CHROMIUM_FLAGS "$@"
    rm -rf $TEMP_PROFILE
  fi
fi
```

**Comment by j54n1n** [comment]
Ok after reading the chromium shell file I did try to execute the part with the **SSE3** requirement manually:
```sh
nosse3="\
The hardware on this system lacks support for the sse3 instruction set.
The upstream chromium project no longer supports this configuration.
For more information, please read and possibly provide input to their
bug tracking system at http://crbug.com/1123353"

case `uname -m` in
    i386|i586|i686|x86_64)
        # Check whether this system supports SSE3
        if ! grep -q sse3 /proc/cpuinfo; then
            echo "$nosse3"
            exit 1
        fi
        ;;
esac
```
and I got the message that **SSE3** was missing.

Then it doomed me that since the machine was a *Proxmox VM* and it may miss the additional CPUID flags.
In fact I checked the machine settings and I found it was set to CPU model type **kvm64**, but with **host** it is working now and the VM with installed chromium sees now the **SSE3** flag, and chromedriver has no more startup issues.
