### ISSUE TITLE
[🐛 Bug]: Can not validate ".pdf" type URL in chrome headless mode.

### ISSUE THREAD

**Issue by youvegotnigel** [SeleniumHQ/selenium#11017]
### What happened?

I need to verify the URL of a PDF file (ex: https://www.orimi.com/pdf-test.pdf)
When I execute this test in a normal chrome browser the test passes and works fine.
But when I execute it in chrome headless mode, the test fails, and not able to verify the PDF file URL.

My code is as below:
```
package com.pdf.test;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

public class PDFTest {

    private WebDriver driver;
    private static final String target_url = "https://www.orimi.com/pdf-test.pdf";

    public void setup_browser(Boolean status) {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.setHeadless(status); //set headless mode true or false
        driver = new ChromeDriver(options);
        driver.manage().window().maximize();
        driver.get("https://google.com");
    }

    @Test
    public void test1() throws InterruptedException {
        System.out.println("Starting test #1");
        setup_browser(false);
        driver.navigate().to(target_url);
        Thread.sleep(5000);

        System.out.println("Current URL : " + driver.getCurrentUrl());
        Assert.assertEquals(target_url, driver.getCurrentUrl());
    }

    @Test
    public void test2() throws InterruptedException {
        System.out.println("Starting test #2");
        setup_browser(true);
        driver.navigate().to(target_url);
        Thread.sleep(5000);

        System.out.println("Current URL : " + driver.getCurrentUrl());
        Assert.assertEquals(target_url, driver.getCurrentUrl());
    }

    @AfterMethod
    public void tearDown(){
        driver.quit();
    }
}
```
I am using below versions of;
Selenium: 4.4.0
TestNG: 7.6.1
Webdriver Manager: 5.3.0
OS: Windows 10

In the above code;
test1() - using a normal chrome browser
test2() - using a headless chrome browser

test1() is working fine and test2() is failing;
```
java.lang.AssertionError: 
Expected :https://www.google.com/
Actual   :https://www.orimi.com/pdf-test.pdf
<Click to see difference>

```

### How can we reproduce the issue?

```shell
https://github.com/youvegotnigel/pdf-test

You can clone the above repo and execute it using the maven command "mvn clean install"
```

### Relevant log output

```shell
PS C:\dev\my-automation-projects\pdf-test> mvn clean install
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.example:pdf-test >------------------------
[INFO] Building pdf-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pdf-test ---
[INFO] Deleting C:\dev\my-automation-projects\pdf-test\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pdf-test ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ pdf-test ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to C:\dev\my-automation-projects\pdf-test\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pdf-test ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\dev\my-automation-projects\pdf-test\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ pdf-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ pdf-test ---
[INFO] No tests to run.
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting test #1
Starting ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}) on port 51910
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Sep 08, 2022 12:27:13 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Sep 08, 2022 12:27:13 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Sep 08, 2022 12:27:13 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
Current URL : https://www.orimi.com/pdf-test.pdf
Starting test #2
Starting ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}) on port 52880
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Sep 08, 2022 12:27:24 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Sep 08, 2022 12:27:24 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Sep 08, 2022 12:27:24 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
Current URL : https://www.google.com/
PASSED: com.pdf.test.PDFTest.test1
FAILED: com.pdf.test.PDFTest.test2
java.lang.AssertionError: expected [https://www.google.com/] but found [https://www.orimi.com/pdf-test.pdf]
        at org.testng.Assert.fail(Assert.java:110)
        at org.testng.Assert.failNotEquals(Assert.java:1413)
        at org.testng.Assert.assertEqualsImpl(Assert.java:149)
        at org.testng.Assert.assertEquals(Assert.java:131)
        at org.testng.Assert.assertEquals(Assert.java:655)
        at org.testng.Assert.assertEquals(Assert.java:665)
        at com.pdf.test.PDFTest.test2(PDFTest.java:44)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.testng.TestRunner.privateRun(TestRunner.java:806)
        at org.testng.TestRunner.run(TestRunner.java:601)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
        at org.testng.SuiteRunner.run(SuiteRunner.java:330)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
        at org.testng.TestNG.runSuites(TestNG.java:1099)
        at org.testng.TestNG.run(TestNG.java:1067)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ pdf-test ---
[INFO] Building jar: C:\dev\my-automation-projects\pdf-test\target\pdf-test-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pdf-test ---
[INFO] Installing C:\dev\my-automation-projects\pdf-test\target\pdf-test-1.0-SNAPSHOT.jar to C:\Users\nigel.mulholland\.m2\repository\org\example\pdf-test\1.0-SNAPSHOT\pdf-test-1.0-SNAPSHOT.jar
[INFO] Installing C:\dev\my-automation-projects\pdf-test\pom.xml to C:\Users\nigel.mulholland\.m2\repository\org\example\pdf-test\1.0-SNAPSHOT\pdf-test-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.665 s
[INFO] Finished at: 2022-09-08T12:27:34+05:30
[INFO] ------------------------------------------------------------------------
```

### Operating System

Windows 10

### Selenium version

4.4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 105.0.5195.102

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 105.0.5195.52 

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Headless mode is not the full version of the browser and has a number of expected limitations. You can raise an issue with Google if you think it is something that needs to be supported, but most likely it is part of the tradeoff you make to have a headless browser.
