### ISSUE TITLE
[🐛 Bug]: Error when connecting to an authenticated Grid with authenticated Proxy 

### ISSUE THREAD

**Issue by erik-rnbt** [SeleniumHQ/selenium#11012]
### What happened?

I have two different cases. In the first one i have to connect to my own Selenium Grid through an authenticated proxy:

```
	public static void main(String[] args) throws Exception {
		
		ChromeOptions browserOptions = new ChromeOptions();

		browserOptions.setPlatformName("Linux");
		browserOptions.setAcceptInsecureCerts(true);
		browserOptions.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.IGNORE);

		RemoteWebDriver driver = new RemoteWebDriver(getURL(), browserOptions);
            
                [some testing]
	}

	public static HttpCommandExecutor getURL() throws Exception {
		String proxy_user = "myUser";
		String proxy_password = "myPW";
		
		ClientConfig config = ClientConfig.defaultConfig()
                .readTimeout(Duration.ofMinutes(1))
                .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("myProxyHost", myProxyPort)))
                .authenticateAs(new UsernameAndPassword(proxy_user, proxy_password))
                .baseUrl(new URL("URL to my Grid"));
		
		HttpCommandExecutor executor = new HttpCommandExecutor(config);

		return executor;
	}
```

This works fine. But in my second usecase i have to connect to an external grid host (Saucelabs) through the same proxy and with authentification credentials for the grid.
To send the authentication for the grid I use:
```
		ChromeOptions browserOptions = new ChromeOptions();

		browserOptions.setPlatformName("Windows 10");
		browserOptions.setBrowserVersion("latest");
		browserOptions.setAcceptInsecureCerts(true);
		browserOptions.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.IGNORE);

		Map<String, Object> sauceOptions = new HashMap<>();
		sauceOptions.put("name", "test");
		sauceOptions.put("username", "my Username");
		sauceOptions.put("accessKey", "my AccessKey");

		browserOptions.setCapability("sauce:options", sauceOptions);
```

If i put the baseUrl without /wd/hub i get 
```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <html><body><h1>404 Not Found</h1>
The resource could not be found.
```

And if i put the /wd/hub at the end i get
```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 401. Message: failed serving request POST /wd/hub/session: Unauthorized
```

### How can we reproduce the issue?

```shell
Try to connect to an authenticated grid through an authenticated proxy. Example is above.
```

### Relevant log output

```shell
1. Log without /wd/hub
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <html><body><h1>404 Not Found</h1>
The resource could not be found.
</body></html>

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:130)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:264)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:179)
	at test2.SaucelabsTest.main(SaucelabsTest.java:55)
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: <html><body><h1>404 Not Found</h1>
The resource could not be found.
</body></html>

	at org.openqa.selenium.json.Json.toType(Json.java:57)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:127)
	... 7 more
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: '***', ip: '***', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:126)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:141)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.Json.toType(Json.java:71)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	... 9 more

2. Log with /wd/hub
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 401. Message: failed serving request POST /wd/hub/session: Unauthorized
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: '***', ip: '***', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: latest, goog:chromeOptions: {args: [], extensions: []}, platformName: Windows 10, sauce:options: {accessKey: ***, name: test, username: ***}, unhandledPromptBehavior: ignore}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: latest, goog:chromeOptions: {args: [], extensions: []}, platformName: Windows 10, sauce:options: {accessKey: ***, name: test, username: ***}, unhandledPromptBehavior: ignore}}]
Capabilities {}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:264)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:179)
	at test2.SaucelabsTest.main(SaucelabsTest.java:55)
```

### Operating System

Windows 10

### Selenium version

4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 105

### What are the browser driver(s) and version(s) where you see this issue?

remote

### Are you using Selenium Grid?

4.4.0

**Comment by erik-rnbt** [comment]
Just tried Selenium 4.4.0. Same result.

**Comment by titusfortner** [comment]
This is a Sauce labs authentication issue, not a grid authentication issue...

Please verify that you have the right username and access key for Sauce Labs.
Feel free to contact me on Selenium Slack/irc if you still have issues - https://www.selenium.dev/support/#ChatRoom

**Comment by jdohnstad** [comment]
I am running into the same issue. While it is true that its a failure to authenticate to SauceLabs, the reason seems to be with the code. I interecepted a request to see what was happening and it seems like the credentials intended for the proxy are being sent in the request. In other words, SauceLabs is receiving both the proxy credentials as basic auth, and the expected username/access key.

```text
POST /wd/hub/session HTTP/1.1
User-Agent: selenium/4.4.0 (java windows)
Cache-Control: no-cache
Content-Length: 889
Content-Type: application/json; charset=utf-8
host: ondemand.us-west-1.saucelabs.com
authorization: Basic cHJveHlVc2VyOnByb3h5UGFzc3dvcmQ=
accept: */*
Connection: close

{
  "desiredCapabilities": {
    "browserName": "chrome",
    "platformName": "Windows 10",
    "goog:chromeOptions": {
      "args": [
      ],
      "extensions": [
      ]
    },
    "browserVersion": "latest",
    "sauce:options": {
      "accessKey": "<my sauce access key>",
      "name": "My Automated Test",
      "username": "<my sauce username>"
    }
  },
  "capabilities": {
    "firstMatch": [
      {
        "sauce:options": {
          "accessKey": "<my sauce access key>",
          "name": "My Automated Test",
          "username": "<my sauce username>"
        },
        "browserName": "chrome",
        "browserVersion": "latest",
        "goog:chromeOptions": {
          "args": [
          ],
          "extensions": [
          ]
        },
        "platformName": "Windows 10"
      }
    ]
  }
}
```

```java
    @Bean
    public WebDriver driver(ClientConfig clientConfig)  {
        var driver = RemoteWebDriver.builder()
                                                            .oneOf(options())
                                                            .setCapability("sauce:options", sauceOptions(null, null))
                                                            .config(clientConfig)
                                                            .build();
        return driver;
    }

    @Bean
    public ClientConfig clientConfig(@Value("${SAUCE_URL:https://ondemand.us-west-1.saucelabs.com/wd/hub}") URL sauceUrl,
                                     @Value("${PROXY_USERNAME}") String proxyUser,
                                     @Value("${PROXY_PASSWORD}") String proxyPassword) {
        return ClientConfig.defaultConfig()
                .baseUrl(sauceUrl)
                .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 8080)))
                .authenticateAs(new UsernameAndPassword(proxyUser, proxyPassword));
    }

    @Bean
    public Map<String, Object> sauceOptions(@Value("${SAUCE_USERNAME}") String username,
                                            @Value("${SAUCE_ACCESS_KEY}") String accessKey) {
        Map<String, Object> sauceOptions = new HashMap<>();

        sauceOptions.put("username", username);
        sauceOptions.put("accessKey", accessKey);
        sauceOptions.put("name", "My Automated Test");

        return sauceOptions;
    }

    @Bean
    public ChromeOptions options() {
        var caps = new ChromeOptions();

        caps.setCapability("platformName", "Windows 10");
        caps.setCapability("browserVersion", "latest");

        return caps;
    }
```

Saucelabs gets confused by the two sets of credentials, but I don't think the proxy credentials should be sent in the first place.

**Comment by erik-rnbt** [comment]
@jdohnstad 
If its true I also think the proxy credentials shouldn't be sent. 

Can you put these information in a new bug issue and mention this issue? This one is already closed.

**Comment by titusfortner** [comment]
If you pass proxy into the options, that means the driver is going to look for that proxy in order to load the assets in the browser. There is no proxy on Sauce Labs VM, so localhost isn't doing what you think it is. If you're using Sauce Connect, you need to add that to SC startup settings not Selenium Options.
