### ISSUE TITLE
[🐛 Bug]: IE mode in Edge is started giving Read timed out issue after stucking at localhost:xxxxx

### ISSUE THREAD

**Issue by joypipal** [SeleniumHQ/selenium#11011]
### What happened?

Using python 3.6.8 and Selenium 3.141.0

Background: We're running a python script for automated testing and in the single run, we're opening and closing the browser (IE mode EDGE) 7-10 times. Earlier we used to get this error once in a while but now since last 2-3 weeks we're starting to get the read timeout error after browser stuck at local-host page at 3rd iteration every time. After restart of machine, iteration # changes but we will always get the error at the same iteration in every run.

Summary: In a single run, couple of time browser open perfectly and couple of time it won't work and also every run browser will fail at the same iteration with same exception.

So, what could be root cause and what could be 100% fix of the issue?

Have attached the IEdriver logs for the issue (Note: Scroll down to find log)

### How can we reproduce the issue?

```shell
from selenium import webdriver
from time import sleep
import subprocess
from utilities import kill_processes_by_name

url="https://google.com/"
ie_options = webdriver.IeOptions()
ie_options.add_additional_option("ie.edgechromium", True)
ie_options.ignore_zoom_level = True
ie_options.ignore_protected_mode_settings = True
ie_options.add_additional_option("ie.edgepath",'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe')
driver_exe_path=r"C:\opt\soroco\bin\IEDriverServer.exe"
kill_processes_by_name('iexplore.exe')
kill_processes_by_name('msedge.exe')
subprocess.run('TASKKILL /F /IM IEDriverServer.exe')
for i in range(15):
	print(i)	
	logfile = 'C:\\Users\\KRPATEL\\Downloads\\Selenium\\NewSelenium\\IEDriverServer'+str(i)+'.log'
	print(logfile)
	try:
		browser = webdriver.Ie(executable_path=driver_exe_path, options=ie_options, log_level="TRACE", service_log_path=logfile)
		browser.get(url)
		sleep(5)
		browser.quit()
		
	except Exception as e:
		print(e)
		kill_processes_by_name('iexplore.exe')
		kill_processes_by_name('msedge.exe')
		subprocess.run('TASKKILL /F /IM IEDriverServer.exe')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\***\venv\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\***\venv\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\***\venv\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 97, in __init__
    keep_alive=keep_alive)
  File "C:\Users\***\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\***\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\***\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\***\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\***\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 402, in _request
    resp = http.request(method, url, body=body, headers=headers)
  File "C:\Users\***\venv\lib\site-packages\urllib3\request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "C:\Users\***\venv\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\***\venv\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\***\venv\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\***\venv\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\***\venv\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\***\venv\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Users\***\venv\lib\site-packages\urllib3\connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\***\venv\lib\site-packages\urllib3\connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=50047): Read timed out. (read timeout=60)
*****************************************************************************************************
IE driver logs
***************************************************************************************************
I 2022-09-02 17:44:16:508 C:\Projects\webdriver\cpp\webdriver-server\server.cc(87) Starting WebDriver server on port: '64419' on host: ''
T 2022-09-02 17:44:16:508 C:\Projects\webdriver\cpp\webdriver-server\server.cc(733) Entering Server::PopulateCommandRepository
T 2022-09-02 17:44:16:508 C:\Projects\webdriver\cpp\iedriver\IEServer.cpp(32) Entering IEServer::IEServer
I 2022-09-02 17:44:16:508 C:\Projects\webdriver\cpp\iedriver\IEServer.cpp(33) Driver version: 3.150.1.0 (64-bit)
T 2022-09-02 17:44:16:508 C:\Projects\webdriver\cpp\webdriver-server\server.cc(179) Entering Server::Start
T 2022-09-02 17:44:16:744 C:\Projects\webdriver\cpp\webdriver-server\server.cc(233) Entering Server::ProcessRequest
T 2022-09-02 17:44:16:744 C:\Projects\webdriver\cpp\webdriver-server\server.cc(297) Entering Server::ReadRequestBody
T 2022-09-02 17:44:16:745 C:\Projects\webdriver\cpp\webdriver-server\server.cc(242) Process request with: URI: /session HTTP verb: POST
body: {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "internet explorer", "platformName": "windows", "se:ieOptions": {"ignoreZoomSetting": true, "ignoreProtectedModeSettings": true, "ie.edgechromium": true, "ie.edgepath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"}}}, "desiredCapabilities": {"browserName": "internet explorer", "version": "", "platform": "WINDOWS", "se:ieOptions": {"ignoreZoomSetting": true, "ignoreProtectedModeSettings": true, "ie.edgechromium": true, "ie.edgepath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"}}}
T 2022-09-02 17:44:16:745 C:\Projects\webdriver\cpp\webdriver-server\server.cc(329) Entering Server::DispatchCommand
T 2022-09-02 17:44:16:745 C:\Projects\webdriver\cpp\webdriver-server\server.cc(682) Entering Server::LookupCommand
D 2022-09-02 17:44:16:745 C:\Projects\webdriver\cpp\webdriver-server\server.cc(338) Command: POST /session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "internet explorer", "platformName": "windows", "se:ieOptions": {"ignoreZoomSetting": true, "ignoreProtectedModeSettings": true, "ie.edgechromium": true, "ie.edgepath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"}}}, "desiredCapabilities": {"browserName": "internet explorer", "version": "", "platform": "WINDOWS", "se:ieOptions": {"ignoreZoomSetting": true, "ignoreProtectedModeSettings": true, "ie.edgechromium": true, "ie.edgepath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"}}}
T 2022-09-02 17:44:16:745 C:\Projects\webdriver\cpp\iedriver\IEServer.cpp(42) Entering IEServer::InitializeSession
T 2022-09-02 17:44:16:745 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(45) Entering IESession::Initialize
D 2022-09-02 17:44:16:745 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(60) Mutex acquired for session initalization
T 2022-09-02 17:44:16:745 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(743) Entering IECommandExecutor::ThreadProc
T 2022-09-02 17:44:16:753 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(74) Entering IECommandExecutor::OnCreate
T 2022-09-02 17:44:16:753 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(1470) Entering IECommandExecutor::PopulateElementFinderMethods
T 2022-09-02 17:44:16:753 C:\Projects\webdriver\cpp\iedriver\InputManager.cpp(56) Entering InputManager::InputManager
T 2022-09-02 17:44:16:753 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(1141) Entering BrowserFactory::GetExecutableLocation
T 2022-09-02 17:44:16:753 C:\Projects\webdriver\cpp\iedriver\RegistryUtilities.cpp(49) Attempting to get registry value  from HKEY_LOCAL_MACHINE\SOFTWARE\Classes\InternetExplorer.Application\CLSID
T 2022-09-02 17:44:16:753 C:\Projects\webdriver\cpp\iedriver\RegistryUtilities.cpp(133) Retrieved value {0002DF01-0000-0000-C000-000000000046}
T 2022-09-02 17:44:16:754 C:\Projects\webdriver\cpp\iedriver\RegistryUtilities.cpp(49) Attempting to get registry value  from HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0002DF01-0000-0000-C000-000000000046}\LocalServer32
T 2022-09-02 17:44:16:754 C:\Projects\webdriver\cpp\iedriver\RegistryUtilities.cpp(133) Retrieved value "C:\Program Files\Internet Explorer\IEXPLORE.EXE"
T 2022-09-02 17:44:16:754 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(1190) Entering BrowserFactory::GetIEVersion
T 2022-09-02 17:44:16:756 C:\Projects\webdriver\cpp\iedriver\CommandHandlerRepository.cpp(110) Entering CommandHandlerRepository::PopulateCommandHandlers
T 2022-09-02 17:44:16:756 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(106) Created thread for command executor returns HWND: '00000000000D0674'
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(110) Session id is retrived from command executor window: '5b021aad-3783-4f7c-8881-2ed90c8aea02'
D 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(116) Releasing session initialization mutex
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(198) Entering IESession::ExecuteCommand
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(154) Entering IECommandExecutor::OnSetCommand
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\webdriver-server\command.cc(31) Entering Command::Deserialize
D 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "internet explorer", "platformName": "windows", "se:ieOptions": {"ignoreZoomSetting": true, "ignoreProtectedModeSettings": true, "ie.edgechromium": true, "ie.edgepath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"}}}, "desiredCapabilities": {"browserName": "internet explorer", "version": "", "platform": "WINDOWS", "se:ieOptions": {"ignoreZoomSetting": true, "ignoreProtectedModeSettings": true, "ie.edgechromium": true, "ie.edgepath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"}}} }
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\webdriver-server\command.cc(31) Entering Command::Deserialize
D 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "internet explorer", "platformName": "windows", "se:ieOptions": {"ignoreZoomSetting": true, "ignoreProtectedModeSettings": true, "ie.edgechromium": true, "ie.edgepath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"}}}, "desiredCapabilities": {"browserName": "internet explorer", "version": "", "platform": "WINDOWS", "se:ieOptions": {"ignoreZoomSetting": true, "ignoreProtectedModeSettings": true, "ie.edgechromium": true, "ie.edgepath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"}}} }
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(176) Entering IECommandExecutor::OnExecCommand
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(226) Beginning wait for response length to be not zero
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(815) Entering IECommandExecutor::DispatchCommand
D 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(880) Executing command: newSession
D 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(48) Found W3C capabilities structure
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(183) Entering NewSessionCommandHandler::ValidateArguments
D 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(191) Found alwaysMatch in capabilities
D 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(199) Validating alwaysMatch capability set
T 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(672) Entering NewSessionCommandHandler::ValidateCapabilities
D 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(673) Validating capabilities object
D 2022-09-02 17:44:16:757 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(722) Found browserName capability. Validating value type is string.
D 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(751) Found platformName capability. Validating value type is string.
D 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(989) Found se:ieOptions capability. Validating value type is object.
D 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(220) Validating firstMatch capability set with index 0
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(672) Entering NewSessionCommandHandler::ValidateCapabilities
D 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(673) Validating capabilities object
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(648) Entering NewSessionCommandHandler::MergeCapabilities
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(274) Entering NewSessionCommandHandler::ProcessCapabilities
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(589) Entering NewSessionCommandHandler::MatchCapabilities
D 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(279) Processing matched capability set with index 0
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability unhandledPromptBehavior
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability pageLoadStrategy
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(167) Entering NewSessionCommandHandler::GetPageLoadStrategyValue
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability strictFileInteractability
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability timeouts
W 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(105) Invalid capability setting: timeouts is type null instead of object. Default value will be used: null

T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(345) Entering NewSessionCommandHandler::SetTimeoutSettings
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(364) Entering NewSessionCommandHandler::SetBrowserFactorySettings
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ignoreProtectedModeSettings
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ignoreZoomSetting
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability browserAttachTimeout
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability initialBrowserUrl
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.forceCreateProcessApi
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.forceShellWindowsApi
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.browserCommandLineSwitches
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.ensureCleanSession
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.edgechromium
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.edgepath
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(118) Entering BrowserFactory::Initialize
D 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(128) path before was C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

D 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(130) path after was 0000011E95D19120

T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(485) Entering NewSessionCommandHandler::SetInputSettings
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability nativeEvents
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability elementScrollBehavior
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability requireWindowFocus
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.fileUploadDialogTimeout
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability enablePersistentHover
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\InputManager.cpp(82) Entering InputManager::Initialize
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(532) Entering NewSessionCommandHandler::CreateReturnedCapabilities
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(1345) Entering IECommandExecutor::CreateNewBrowser
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(150) Entering BrowserFactory::LaunchBrowserProcess
D 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(154) Ignoring Protected Mode Settings: 1
D 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(160) Has Valid Protected Mode Settings: 0
T 2022-09-02 17:44:16:758 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(236) Entering BrowserFactory::IsIELaunchURLAvailable
T 2022-09-02 17:44:16:777 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(138) Entering BrowserFactory::ClearCache
T 2022-09-02 17:44:16:777 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(340) Entering BrowserFactory::LaunchEdgeInIEMode
D 2022-09-02 17:44:16:777 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(341) Starting Edge Chromium from the command line
T 2022-09-02 17:44:16:777 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(359) IE starting command line is: 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --ie-mode-force --internet-explorer-integration=iemode http://localhost:64419/'.
D 2022-09-02 17:44:17:087 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(212) IE launched successfully with process ID 13188
D 2022-09-02 17:44:17:087 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(218) Process with ID 13188 is executing msedge.exe
T 2022-09-02 17:44:17:087 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(425) Entering BrowserFactory::AttachToBrowser
D 2022-09-02 17:44:17:087 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(435) Using Active Accessibility to find IWebBrowser2 interface
T 2022-09-02 17:44:17:087 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(486) Entering BrowserFactory::AttachToBrowserUsingActiveAccessibility
T 2022-09-02 17:44:20:837 C:\Projects\webdriver\cpp\webdriver-server\server.cc(233) Entering Server::ProcessRequest
T 2022-09-02 17:44:20:837 C:\Projects\webdriver\cpp\webdriver-server\server.cc(242) Process request with: URI: / HTTP verb: GET
body: {}
T 2022-09-02 17:44:20:837 C:\Projects\webdriver\cpp\webdriver-server\server.cc(535) Entering Server::SendHttpOk
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\server.cc(233) Entering Server::ProcessRequest
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\server.cc(242) Process request with: URI: /favicon.ico HTTP verb: GET
body: {}
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\server.cc(329) Entering Server::DispatchCommand
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\server.cc(682) Entering Server::LookupCommand
D 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\server.cc(338) Command: GET /favicon.ico {}
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\response.cc(94) Entering Response::SetErrorResponse
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\response.cc(87) Entering Response::SetResponse
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\response.cc(60) Entering Response::Serialize
D 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\server.cc(421) Response: {
	"value" : 
	{
		"error" : "unknown command",
		"message" : "Command not found: GET /favicon.ico",
		"stacktrace" : ""
	}
}
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\server.cc(474) Entering Server::SendResponseToClient
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\response.cc(30) Entering Response::Deserialize
T 2022-09-02 17:44:21:173 C:\Projects\webdriver\cpp\webdriver-server\server.cc(598) Entering Server::SendHttpNotFound
T 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\server.cc(233) Entering Server::ProcessRequest
T 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\server.cc(242) Process request with: URI: /favicon.ico HTTP verb: GET
body: {}
T 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\server.cc(329) Entering Server::DispatchCommand
T 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\server.cc(682) Entering Server::LookupCommand
D 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\server.cc(338) Command: GET /favicon.ico {}
T 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\response.cc(94) Entering Response::SetErrorResponse
T 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\response.cc(87) Entering Response::SetResponse
T 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\response.cc(60) Entering Response::Serialize
D 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\server.cc(421) Response: {
	"value" : 
	{
		"error" : "unknown command",
		"message" : "Command not found: GET /favicon.ico",
		"stacktrace" : ""
	}
}
T 2022-09-02 17:44:21:476 C:\Projects\webdriver\cpp\webdriver-server\server.cc(474) Entering Server::SendResponseToClient
T 2022-09-02 17:44:21:477 C:\Projects\webdriver\cpp\webdriver-server\response.cc(30) Entering Response::Deserialize
T 2022-09-02 17:44:21:477 C:\Projects\webdriver\cpp\webdriver-server\server.cc(598) Entering Server::SendHttpNotFound
```

### Operating System

Windows 10 Version 20H2

### Selenium version

3.141.0

### What are the browser(s) and version(s) where you see this issue?

Edge 105.0.1343.27 (Official build) (64-bit) and IE -11

### What are the browser driver(s) and version(s) where you see this issue?

InternetExplorerDriver server (64-bit) 3.150.1.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Could it be this bug?
https://github.com/MicrosoftEdge/EdgeWebDriver/issues/38

This is my tracelog for it, is the one you provided showing the full log? 
https://gist.github.com/titusfortner/3aef8609eb6b0bfa052d1d764ce01f8f

Mine reproduces 100% of the time.

**Comment by joypipal** [comment]
@titusfortner Looks like a similar issue to yours.
Yes, I've attached the full trace log of a iteration where browser didn't work.

**Comment by titusfortner** [comment]
I'm going to close this one and we'll track it over there; hopefully we can figure out what is going on.
