### ISSUE TITLE
ReferenceError: after is not defined

### ISSUE THREAD

**Issue by N1lshui** [SeleniumHQ/selenium#11019]
### What happened?

I'm not able to run Slenium with Javascript. I try to start my tes.js an dthere is this error

### How can we reproduce the issue?

```shell
I don't know
test.js
```

### Relevant log output

```shell
$ node test.js
[INFO] Searching for WebDriver executables installed on the current system...
[INFO] ... located firefox
[INFO] Running tests against [firefox]
C:\Users\nbirken\Documents\Selenium\js\node_modules\selenium-webdriver\testing\index.js:229
  after(function () {
  ^

ReferenceError: after is not defined
    at init (C:\Users\nbirken\Documents\Selenium\js\node_modules\selenium-webdriver\testing\index.js:229:3)
    at suite (C:\Users\nbirken\Documents\Selenium\js\node_modules\selenium-webdriver\testing\index.js:374:5)
    at Object.<anonymous> (C:\Users\nbirken\Documents\Selenium\js\test.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

### Operating System

Windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Firefox

### What are the browser driver(s) and version(s) where you see this issue?

Firefox

**Comment by harsha509** [comment]
Hi @N1lshui ,


Thank you for raising the issue. 

Yes there is a missing info in document on running the test. 
To execute, please install mocha by `npm install mocha` and run test using `mocha test.js`

As this is not an issue with selenium-webdriver i will move this issue to documentation!!!

Thanks,
Sri Harsha
