### ISSUE TITLE
[🐛 Bug]: creating service with explicit path points to wrong driver

### ISSUE THREAD

**Issue by andykais** [SeleniumHQ/selenium#11050]
### What happened?

I downloaded a chrome driver here http://chromedriver.storage.googleapis.com/index.html?path=106.0.5249.21 and wanted to spin up a selenium instance pointed at it. Instead, what happened was the selenium-webdriver nodejs module attempted to point to the chrome executable I have installed on my system, which was too old for what it was expecting, and the program crashed

### How can we reproduce the issue?

```shell
import chrome from 'selenium-webdriver/chrome'

async function run() {
  const service = new chrome.ServiceBuilder('./chromedriver_linux64/chromedriver')
    .loggingTo('chrome.log')
    .build()

  const options = new chrome.Options()
  const driver = chrome.Driver.createSession(options, service)
  await driver.get('http://www.google.com/ncr');
}

run()
```

### Relevant log output

```shell
/home/andrew/Code/development/selenium-scraper/node_modules/.pnpm/selenium-webdriver@4.4.0/node_modules/selenium-webdriver/lib/error.js:522
    let err = new ctor(data.message)
              ^
SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 106
Current browser version is 104.0.5112.79 with binary path /opt/google/chrome/google-chrome
    at Object.throwDecodedError (/home/andrew/Code/development/selenium-scraper/node_modules/.pnpm/selenium-webdriver@4.4.0/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/home/andrew/Code/development/selenium-scraper/node_modules/.pnpm/selenium-webdriver@4.4.0/node_modules/selenium-webdriver/lib/http.js:589:13)
    at Executor.execute (/home/andrew/Code/development/selenium-scraper/node_modules/.pnpm/selenium-webdriver@4.4.0/node_modules/selenium-webdriver/lib/http.js:514:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: '#0 0x5631c82b7343 <unknown>\n' +
    '#1 0x5631c80c154a <unknown>\n' +
    '#2 0x5631c80ead82 <unknown>\n' +
    '#3 0x5631c80e653d <unknown>\n' +
    '#4 0x5631c80e2256 <unknown>\n' +
    '#5 0x5631c8120af6 <unknown>\n' +
    '#6 0x5631c812045f <unknown>\n' +
    '#7 0x5631c8118a73 <unknown>\n' +
    '#8 0x5631c80ed4f3 <unknown>\n' +
    '#9 0x5631c80ee731 <unknown>\n' +
    '#10 0x5631c830562e <unknown>\n' +
    '#11 0x5631c8308ac2 <unknown>\n' +
    '#12 0x5631c82ebf4e <unknown>\n' +
    '#13 0x5631c8309743 <unknown>\n' +
    '#14 0x5631c82e036f <unknown>\n' +
    '#15 0x5631c8329a28 <unknown>\n' +
    '#16 0x5631c8329ba6 <unknown>\n' +
    '#17 0x5631c8343d52 <unknown>\n' +
    '#18 0x7f42de5ed78d <unknown>\n'
}
```
you can see that instead of the relative path set on the service, it is picking the system version of chrome I have installed (`/opt/google/chrome/google-chrome`).
```


### Operating System

Arch Linux

### Selenium version

nodejs v18.8.0,     "selenium-webdriver": "^4.4.0"

### What are the browser(s) and version(s) where you see this issue?

Chrome 106.0.5249.21

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 106.0.5249.21

### Are you using Selenium Grid?

n/a

**Comment by titusfortner** [comment]
By default, the driver and browser versions need to match. If you want to use a different browser than the one the driver finds by default, you need to use the `binary` parameter in the options class to pass the location.

**Comment by andykais** [comment]
oh thats my mistake then. I had assumed the driver _was_ the whole chrome driver. It sounds like you are saying it is more of a tool to communicate with the binary

**Comment by titusfortner** [comment]
@andykais yes exactly, the driver is a shim created by the browser vendor that translates Selenium commands to browser actions.
