### ISSUE TITLE
[🐛 Bug]: scroll_to_element raises "unknown variant `wheel`, expected one of `none`, `key`, `pointer` (Firefox 102)

### ISSUE THREAD

**Issue by claudep** [SeleniumHQ/selenium#11059]
### What happened?

When running (in Python):
`ActionChains(self.selenium).scroll_to_element(element).perform()`

I'm getting the error:
```selenium.common.exceptions.InvalidArgumentException: Message: unknown variant `wheel`, expected one of `none`, `key`, `pointer` at line 1 column 226```

### How can we reproduce the issue?

```shell
Run `ActionChains(self.selenium).scroll_to_element(element).perform()`
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<project_path>/test_live.py", line 60, in test_adresse_add
    ActionChains(self.selenium).scroll_to_element(btn).perform()
  File "<venv>/lib/python3.9/site-packages/selenium/webdriver/common/action_chains.py", line 78, in perform
    self.w3c_actions.perform()
  File "/<venv>/lib/python3.9/site-packages/selenium/webdriver/common/actions/action_builder.py", line 88, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "<venv>/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "<venv>/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: unknown variant `wheel`, expected one of `none`, `key`, `pointer` at line 1 column 226
```

### Operating System

Debian 11

### Selenium version

Python 4.4.3

### What are the browser(s) and version(s) where you see this issue?

Firefox 102

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.31.0

**Comment by titusfortner** [comment]
It's not supported on Firefox until v106
https://bugzilla.mozilla.org/show_bug.cgi?id=1746601

**Comment by claudep** [comment]
Thanks for triaging this quickly!
