### ISSUE TITLE
[🐛 Bug]: chromedriver for Apple M1 has changed name

### ISSUE THREAD

**Issue by agodwin** [SeleniumHQ/selenium#11066]
### What happened?

Webdriver version 5.1 tried to download:
     Webdrivers::NetworkError:
       Net::HTTPServerException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip

Actual file path name has become:
https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac_arm64.zip

### How can we reproduce the issue?

```shell
you need an Apple M1 laptop
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro

you need the latest version of Chrome v106
```

### Relevant log output

```shell
Failure/Error: Watir::Browser.new :chrome, options: options
      
      Webdrivers::NetworkError:
        Net::HTTPServerException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/webdrivers-5.1.0/lib/webdrivers/network.rb:19:in `get'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/webdrivers-5.1.0/lib/webdrivers/system.rb:74:in `block (2 levels) in download_file'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/webdrivers-5.1.0/lib/webdrivers/system.rb:73:in `block in download_file'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/webdrivers-5.1.0/lib/webdrivers/system.rb:72:in `chdir'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/webdrivers-5.1.0/lib/webdrivers/system.rb:72:in `download_file'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/webdrivers-5.1.0/lib/webdrivers/system.rb:63:in `download'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/webdrivers-5.1.0/lib/webdrivers/common.rb:98:in `update'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/webdrivers-5.1.0/lib/webdrivers/chromedriver.rb:149:in `block in <top (required)>'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/service.rb:101:in `binary_path'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/service.rb:73:in `initialize'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/service.rb:32:in `new'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/service.rb:32:in `chrome'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/driver.rb:340:in `service_url'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/driver.rb:321:in `create_bridge'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/selenium-webdriver-4.5.0/lib/selenium/webdriver.rb:89:in `for'
      # /Users/godwina/.rvm/gems/ruby-2.7.2/gems/watir-7.1.0/lib/watir/browser.rb:46:in `initialize'


selenium-webdriver (4.5.0, 3.142.7)
watir (7.1.0, 6.19.1)
webdrivers (5.1.0, 4.7.0)
```

### Operating System

MacOS Monterey Version 12.6

### Selenium version

ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin21]

### What are the browser(s) and version(s) where you see this issue?

Chrome 106.0.5249.61

### What are the browser driver(s) and version(s) where you see this issue?

was deleted attempting to update

### Are you using Selenium Grid?

n/a

**Comment by agodwin** [comment]
work around
manually download chromedriver, unzip and copy into the ~/.webdrivers directory

**Comment by technicalpickles** [comment]
In case anyone using the [webdrivers gem](https://github.com/titusfortner/webdrivers), upgrading to 5.2.0 fixes it cc https://github.com/titusfortner/webdrivers/issues/237

**Comment by titusfortner** [comment]
Yes, this is a driver manager issue, not a Selenium one. Thanks.
