### ISSUE TITLE
[🐛 Bug]: webdriver-manager is picking nonsensical paths for chromium

### ISSUE THREAD

**Issue by cwoodruf** [SeleniumHQ/selenium#11064]
### What happened?

Looks like the webdriver-manager is picking a directory to try and run chromium from.

### How can we reproduce the issue?

```shell
Test program:
$ cat selenium-test.py 
#!/usr/bin/env python

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.google.com")

Steps to reproduce:

$ sudo pip3 install -U selenium
Collecting selenium
  Downloading selenium-4.5.0-py3-none-any.whl (995 kB)
     |████████████████████████████████| 995 kB 3.8 MB/s 
Collecting urllib3[socks]~=1.26
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 10.6 MB/s 
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.9.2-py3-none-any.whl (16 kB)
Collecting certifi>=2021.10.8
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
     |████████████████████████████████| 161 kB 10.8 MB/s 
Collecting trio~=0.17
  Downloading trio-0.22.0-py3-none-any.whl (384 kB)
     |████████████████████████████████| 384 kB 10.7 MB/s 
Collecting PySocks!=1.5.7,<2.0,>=1.5.6; extra == "socks"
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Requirement already satisfied, skipping upgrade: async-generator>=1.10 in /usr/local/lib/python3.8/dist-packages (from trio-websocket~=0.9->selenium) (1.10)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied, skipping upgrade: attrs>=19.2.0 in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium) (21.2.0)
Collecting exceptiongroup>=1.0.0rc9; python_version < "3.11"
  Downloading exceptiongroup-1.0.0rc9-py3-none-any.whl (12 kB)
Requirement already satisfied, skipping upgrade: idna in /usr/lib/python3/dist-packages (from trio~=0.17->selenium) (2.8)
Collecting sniffio
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting outcome
  Downloading outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Collecting h11<1,>=0.9.0
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 4.3 MB/s 
Installing collected packages: PySocks, urllib3, exceptiongroup, sniffio, sortedcontainers, outcome, trio, h11, wsproto, trio-websocket, certifi, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.25.8
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'urllib3'. No files were found to uninstall.
  Attempting uninstall: certifi
    Found existing installation: certifi 2019.11.28
    Not uninstalling certifi at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'certifi'. No files were found to uninstall.
  Attempting uninstall: selenium
    Found existing installation: selenium 4.0.0a1
    Not uninstalling selenium at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'selenium'. No files were found to uninstall.
Successfully installed PySocks-1.7.1 certifi-2022.9.24 exceptiongroup-1.0.0rc9 h11-0.14.0 outcome-1.2.0 selenium-4.5.0 sniffio-1.3.0 sortedcontainers-2.4.0 trio-0.22.0 trio-websocket-0.9.2 urllib3-1.26.12 wsproto-1.2.0

$ sudo pip3 install webdriver-manager
Collecting webdriver-manager
  Downloading webdriver_manager-3.8.3-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from webdriver-manager) (2.22.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.8/dist-packages (from webdriver-manager) (0.17.1)
Collecting tqdm
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 3.7 MB/s 
Installing collected packages: tqdm, webdriver-manager
Successfully installed tqdm-4.64.1 webdriver-manager-3.8.3

$ ./selenium-test.py
```

### Relevant log output

```shell
W16: Warning: Mode of file "selenium-test.py" has changed since editing started
See ":help W16" for more info.
"selenium-test.py" 9L, 280C
Press ENTER or type command to continue
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[WDM] - Downloading: 100%|█████████████████████████████████████████████████████████████████████████| 6.35M/6.35M [00:00<00:00, 10.2MB/s]
Traceback (most recent call last):
  File "./selenium-test.py", line 7, in <module>
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/local/bin/Zotero_linux-x86_64/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x561a33b162c3 <unknown>
#1 0x561a3391f83a <unknown>
#2 0x561a33945543 <unknown>
#3 0x561a33940546 <unknown>
#4 0x561a3397ede6 <unknown>
#5 0x561a3397e74f <unknown>
#6 0x561a33976d63 <unknown>
#7 0x561a3394b7e3 <unknown>
#8 0x561a3394ca21 <unknown>
#9 0x561a33b6418e <unknown>
#10 0x561a33b67622 <unknown>
#11 0x561a33b4aaae <unknown>
#12 0x561a33b682a3 <unknown>
#13 0x561a33b3eecf <unknown>
#14 0x561a33b88588 <unknown>
#15 0x561a33b88706 <unknown>
#16 0x561a33ba28b2 <unknown>
#17 0x7f13f4a58609 <unknown>


shell returned 1
```

### Operating System

Linux system76-pc 5.18.10-76051810-generic #202207071639~1659403207~20.04~cb5f582~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux

### Selenium version

4.5

### What are the browser(s) and version(s) where you see this issue?

Chromium Version 105.0.5195.102 (Official Build) snap (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

don't know its picking a directory to run chromium from

### Are you using Selenium Grid?

no

**Comment by cwoodruf** [comment]
Keep in mind this error is going to be different for different systems if it happens at all. The place the manager is looking for chromium is a local install of zotero. I suspect most people aren't going to have this specific setup. However, its easy enough to reproduce if needed by downloading zotero from zotero.org and unpacking it in the home directory where selenium is to be run.

**Comment by titusfortner** [comment]
Your logs say its finding selenium 4.0.0a1?

If you're having an issue with webdriver_manager package, please report it at their repo - https://github.com/SergeyPirogov/webdriver_manager
