### ISSUE TITLE
[🐛 Bug]: JDK 11 HTTP client is not included in selenium-server-4.5.0.jar

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#11086]
### What happened?

I tried to start the standalone server with the new JDK 11 HTTP client (#10730) using the JVM argument `-Dwebdriver.http.factory=jdk-http-client` and expected it to start.
The server startup failed with `Unknown HttpClient factory jdk-http-client` 

I had a look inside the selenium-server-4.5.0.jar and could not find the corresponding class files, the `jdk` folder is missing:
![image](https://user-images.githubusercontent.com/16140691/194056327-e7cda51f-23a7-438b-8fed-8e35de1c924d.png)

### How can we reproduce the issue?

```shell
set the JVM argument -Dwebdriver.http.factory=jdk-http-client while starting the standalone server
```

### Relevant log output

```shell
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: java.lang.IllegalArgumentException: Unknown HttpClient factory jdk-http-client
	at org.openqa.selenium.remote.http.HttpClient$Factory.create(HttpClient.java:57)
	at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:73)
	at org.openqa.selenium.grid.server.NetworkOptions.getHttpClientFactory(NetworkOptions.java:49)
	at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:140)
	at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
	at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:235)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
```

### Operating System

Windows 10 x64

### Selenium version

Java 4.5.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

No

**Comment by KroArtem** [comment]
I don't think it's a bug, the reasoning is described here https://www.selenium.dev/blog/2022/using-java11-httpclient/

The correct way to add a dependency is also there

**Comment by joerg1985** [comment]
@KroArtem thanks for the hint, i had to add this additional jar to the server startup:

`java -jar selenium-server-4.5.0.jar --ext selenium-http-jdk-client-4.5.0.jar standalone ...`
