### ISSUE TITLE
[🐛 Bug]: Full stack trace not logged from wait() function

### ISSUE THREAD

**Issue by jiri-skrivanek** [SeleniumHQ/selenium#11080]
### What happened?

No full stack trace is provided when the wait() function timeouts.

### How can we reproduce the issue?

```shell
return driver.wait(async () => {
            const foundElements: WebElement[] = await driverLike.findElements(by);
            return foundElements[0];
    },
        timeout,
        `Timed out waiting for locator ${by}`
    );
```

### Relevant log output

```shell
TimeoutError: Timed out waiting for locator By(css selector, .oj-menu-dropdown:not(.oj-subtree-hidden):not([aria-hidden=true]))
Wait timed out after 30134ms
      at D:\repo\hdqr\node_modules\selenium-webdriver\lib\webdriver.js:907:17
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating System

Windows10

### Selenium version

selenium-webdriver 4.5.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 106

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106.0.5249.61

**Comment by TamsilAmani** [comment]
I was looking into this issue and I think the stack trace printed is reasonable. The `wait()` is a callback function so it is transferred to the task queue once the timeout is reached. From there the `wait()` function is executed and the timeout condition is true, so it gives the error `Wait timed out after 30134ms`.

According to me the stack trace is pretty clear. But we can consider adding another error message if need be. 

CC: @harsha509

**Comment by jiri-skrivanek** [comment]
If I call for example this ` await driver.wait(until.elementLocated(By.css('dummy')), 100);`. The point is that I get the following stack trace with selenium-webdriver 3.6.0

TimeoutError: Waiting for element to be located By(css selector, dummy)
Wait timed out after 146ms
      at D:\repo\vb3\breeze\vbcs-client\node_modules\selenium-webdriver\lib\promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules\selenium-webdriver\lib\promise.js:1376:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at D:\repo\vb3\breeze\vbcs-client\node_modules\selenium-webdriver\lib\promise.js:2927:27
      at D:\repo\vb3\breeze\vbcs-client\node_modules\selenium-webdriver\lib\promise.js:668:7
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
  From: Task: Waiting for element to be located By(css selector, dummy)
      at scheduleWait (node_modules\selenium-webdriver\lib\promise.js:2188:20)
      at ControlFlow.wait (node_modules\selenium-webdriver\lib\promise.js:2517:12)
      at Driver.wait (node_modules\selenium-webdriver\lib\webdriver.js:934:29)
      at Context.<anonymous> (tests\functional-wd\tests\watchdog\MySpec.ts:58:22)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.safeCallback (tests\functional-wd\base\test-hooks.ts:185:17)

and just this one with 4.5.0

TimeoutError: Waiting for element to be located By(css selector, dummy)
Wait timed out after 245ms
      at D:\repo\vb4\breeze\vbcs-client\node_modules\selenium-webdriver\lib\webdriver.js:907:17
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

I need to know that it was originated at MySpec.ts:58:22.

**Comment by jiri-skrivanek** [comment]
Any news about this issue?

**Comment by diemol** [comment]
@TamsilAmani I think it makes sense to show in the stacktrace where the error is actually happening. What do you think?

**Comment by jiri-skrivanek** [comment]
Any progress?
