### ISSUE TITLE
[🐛 Bug]: Runtime.exceptionThrown fails to parse (FirefoxDriver)

### ISSUE THREAD

**Issue by cocreature** [SeleniumHQ/selenium#11122]
### What happened?

I'm trying to use the devtools support to get console.log statements. However on an uncaught exception I'm getting the following error:
```
Caused by: org.openqa.selenium.json.JsonException: Expected to read a STRING but instead have: NUMBER. Last 128 characters read: host:3000/static/js/bundle.js","stackTrace":{"callFrames":[{"functionName":"./src/views/Coins.tsx/Coins/fetchCoins<","scriptId":
```

Full error output below

As far as I can tell the issue is that the `scriptId` is an integer but selenium expects a string. It’s not clear to me if that is a bug in selenium or geckodriver so opening here.

It looks like somehow CDP and bidi is getting mixed from what I can tell. If there is a way that I can just disable CDP I'm also happy.

### How can we reproduce the issue?

```shell
I can only share snippets sadly but happy to expand on any pieces as needed

val options: FirefoxOptions = new FirefoxOptions().setHeadless(true)
val webDriver = new FirefoxDriver(options)
val devTools = webDriver.getDevTools()
devTools.createSession()
webDriver.get(url)
// wait for frontend to throw an uncaught exception
```
```


### Relevant log output

```shell
https://gist.github.com/cocreature/74252c7d20823f64c15926e1f5cb81b3
```

### Operating System

Ubuntu 22.04

### Selenium version

Java 4.5.0

### What are the browser(s) and version(s) where you see this issue?

Mozilla Firefox 105.0.3

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.31

### Are you using Selenium Grid?

No

**Comment by pujagani** [comment]
Thank you for sharing the details. I have attempted to reproduce the issue and I am unable to. I have used the example below to listen to console logs and it works as expected. 

```
 public static void main(String[] args) throws MalformedURLException, InterruptedException {
    WebDriver driver = new FirefoxDriver();
    try {
      DevTools devTools = ((HasDevTools) driver).getDevTools();
      devTools.createSession();
      devTools.send(Log.enable());
      devTools.send(org.openqa.selenium.devtools.v85.runtime.Runtime.enable());
      devTools.addListener(Log.entryAdded(), logEntry -> {
        System.out.println("log: " + logEntry.getText());
        System.out.println("level: " + logEntry.getLevel());
      });
      devTools.addListener(Runtime.consoleAPICalled(), logEntry -> {
        System.out.println("Runtime log: " + logEntry.getTimestamp());
        System.out.println("Runtime level: " + logEntry.getType());
      });

      driver.get("https://fakestore.testelka.pl/console-log-events/");
// Check the terminal output for the browser console messages.
      driver.quit();
    } finally {
      driver.quit();
    }
  }
}
```
I have used the same geckodriver version and tried on browser version 105.b and 106.0. 
I appreciate it if you are able to provide a reproducible script/ code snippet to reproduce it, it does not have to be the code you use but anything that can help reproduce this error. It will help me triage to see where the issue lies and accordingly fix it. Thank you!

**Comment by cocreature** [comment]
Thanks for taking a look, I managed to build a standalone reproducer. I've attached a tarball with a README on how to run it.
[reproducer.tar.gz](https://github.com/SeleniumHQ/selenium/files/9808497/reproducer.tar.gz)

**Comment by pujagani** [comment]
Appreciate it. I will take a look and try to reproduce it and if I am successful at reproducing will triage it further. Will keep this issue updated. Thank you!

**Comment by pujagani** [comment]
I was able to reproduce the issue. The error that you see is not a Selenium bug. If one runs the same test using ChromeDriver, the test passes. The scriptId is expected to be String https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-ScriptId https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-ExceptionDetails as per the CDP protocol. Selenium uses the same protocol and creates object mapping for the same. 

Sharing trace logs below:

Firefox trace log: 
```
{"method":"Runtime.exceptionThrown","params":{"timestamp":1666094899594,"exceptionDetails":{"exceptionId":0,"text":"Error: uncaught exception","lineNumber":21,"columnNumber":9,"url":"http://localhost:3000/static/js/bundle.js","stackTrace":{"callFrames":[{"functionName":"App","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":21,"columnNumber":9},{"functionName":"renderWithHooks","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":21146,"columnNumber":31},{"functionName":"mountIndeterminateComponent","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":24432,"columnNumber":17},{"functionName":"beginWork","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":25728,"columnNumber":20},{"functionName":"callCallback","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":10738,"columnNumber":18},{"functionName":"invokeGuardedCallbackDev","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":10782,"columnNumber":20},{"functionName":"invokeGuardedCallback","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":10839,"columnNumber":35},{"functionName":"beginWork$1","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":30713,"columnNumber":32},{"functionName":"performUnitOfWork","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":29960,"columnNumber":16},{"functionName":"workLoopSync","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":29883,"columnNumber":26},{"functionName":"renderRootSync","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":29856,"columnNumber":11},{"functionName":"recoverFromConcurrentError","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":29348,"columnNumber":38},{"functionName":"performConcurrentWorkOnRoot","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":29260,"columnNumber":26},{"functionName":"performConcurrentWorkOnRoot","scriptId":45,"url":"self-hosted","lineNumber":1406,"columnNumber":25},{"functionName":"workLoop","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":37277,"columnNumber":46},{"functionName":"flushWork","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":37255,"columnNumber":18},{"functionName":"performWorkUntilDeadline","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":37492,"columnNumber":25},{"functionName":"./node_modules/scheduler/cjs/scheduler.development.js/<","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":37529,"columnNumber":7},{"functionName":"./node_modules/scheduler/cjs/scheduler.development.js","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":37579,"columnNumber":5},{"functionName":"options.factory","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40883,"columnNumber":31},{"functionName":"__webpack_require__","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40306,"columnNumber":33},{"functionName":"fn","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40540,"columnNumber":21},{"functionName":"./node_modules/scheduler/index.js","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":37594,"columnNumber":20},{"functionName":"options.factory","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40883,"columnNumber":31},{"functionName":"__webpack_require__","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40306,"columnNumber":33},{"functionName":"fn","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40540,"columnNumber":21},{"functionName":"./node_modules/react-dom/cjs/react-dom.development.js/<","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":7027,"columnNumber":40},{"functionName":"./node_modules/react-dom/cjs/react-dom.development.js","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":32760,"columnNumber":5},{"functionName":"options.factory","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40883,"columnNumber":31},{"functionName":"__webpack_require__","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40306,"columnNumber":33},{"functionName":"fn","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40540,"columnNumber":21},{"functionName":"./node_modules/react-dom/index.js","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":32831,"columnNumber":20},{"functionName":"options.factory","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40883,"columnNumber":31},{"functionName":"__webpack_require__","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40306,"columnNumber":33},{"functionName":"fn","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40540,"columnNumber":21},{"functionName":"./node_modules/react-dom/client.js","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":32774,"columnNumber":28},{"functionName":"options.factory","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40883,"columnNumber":31},{"functionName":"__webpack_require__","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40306,"columnNumber":33},{"functionName":"fn","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40540,"columnNumber":21},{"functionName":"./src/index.js","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":71,"columnNumber":93},{"functionName":"options.factory","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40883,"columnNumber":31},{"functionName":"__webpack_require__","scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":40306,"columnNumber":33},{"functionName":null,"scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":41529,"columnNumber":56},{"functionName":null,"scriptId":44,"url":"http://localhost:3000/static/js/bundle.js","lineNumber":41531,"columnNumber":12}]},"executionContextId":2}},"sessionId":"e1283052-fdb8-488b-9b93-ca30f6234b40"}
```

Chrome trace log: 

```
 "exceptionDetails": {
      "columnNumber": 8,
      "exception": {
         "className": "Error",
         "description": "Error: uncaught exception\n    at App (http://localhost:3000/static/js/bundle.js:21:9)\n    at renderWithHooks (http://localhost:3000/static/js/bundle.js:21146:22)\n    at mountIndeterminateComponent ...",
         "objectId": "9018953901251212833.1.1",
         "preview": {
            "description": "Error: uncaught exception\n    at App (http://localhost:3000/static/js/bundle.js:21:9)\n    at renderWithHooks (http://localhost:3000/static/js/bundle.js:21146:22)\n    at mountIndeterminateComponent ...",
            "overflow": false,
            "properties": [ {
               "name": "stack",
               "type": "string",
               "value": "Error: uncaught exception\n    at App (http://local…ttp://localhost:3000/static/js/bundle.js:29883:9)"
            }, {
               "name": "message",
               "type": "string",
               "value": "uncaught exception"
            } ],
            "subtype": "error",
            "type": "object"
         },
         "subtype": "error",
         "type": "object"
      },
      "exceptionId": 1,
      "executionContextId": 1,
      "lineNumber": 20,
      "scriptId": "8",
      "stackTrace": {
         "callFrames": [ {
            "columnNumber": 8,
            "functionName": "App",
            "lineNumber": 20,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 21,
            "functionName": "renderWithHooks",
            "lineNumber": 21145,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 16,
            "functionName": "mountIndeterminateComponent",
            "lineNumber": 24431,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 19,
            "functionName": "beginWork",
            "lineNumber": 25727,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 17,
            "functionName": "callCallback",
            "lineNumber": 10737,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 19,
            "functionName": "invokeGuardedCallbackDev",
            "lineNumber": 10781,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 34,
            "functionName": "invokeGuardedCallback",
            "lineNumber": 10838,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 10,
            "functionName": "beginWork$1",
            "lineNumber": 30712,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 15,
            "functionName": "performUnitOfWork",
            "lineNumber": 29959,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 8,
            "functionName": "workLoopSync",
            "lineNumber": 29882,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 10,
            "functionName": "renderRootSync",
            "lineNumber": 29855,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 77,
            "functionName": "performConcurrentWorkOnRoot",
            "lineNumber": 29249,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 37,
            "functionName": "workLoop",
            "lineNumber": 37276,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 17,
            "functionName": "flushWork",
            "lineNumber": 37254,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         }, {
            "columnNumber": 24,
            "functionName": "performWorkUntilDeadline",
            "lineNumber": 37491,
            "scriptId": "8",
            "url": "http://localhost:3000/static/js/bundle.js"
         } ]
      },
      "text": "Uncaught",
      "url": "http://localhost:3000/static/js/bundle.js"
   },
   "timestamp": 1.666094921682581e+12
}

```

For the same test, Chrome is sending the scriptId in the expected format. 

However, irrespective of the above error, the expected console logs in both cases is the same and the result the test is seeking is unchanged.
The console log is printed as expected
```
2022-10-18T12:08:41.690Z
error
[The above error occurred in the <App> component:

    at App (http://localhost:3000/static/js/bundle.js:21:9)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.]
```

The CDP implementation is Firefox is incomplete, implementation is sufficient to support selected CDP commands and events. That could be a potential the reason for the difference discussed above.

**Comment by pujagani** [comment]
Additionally, if your test framework permits, you can also use BiDi support in Firefox. Selenium is working on providing full support as the browser implements BiDi-specific commands and events. But for console logs, BiDi support is currently available in FirefoxDriver.

Updated your test script to include all the cases and BiDi : 
```
public class AppTest
{
    @Test
    public void reproducer()
    {
        FirefoxOptions options = new FirefoxOptions();
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);

        FirefoxDriver driver = new FirefoxDriver(options);
        DevTools devTools = driver.getDevTools();
        System.out.println("Creating session");
        devTools.createSession();
        System.out.println("Adding console listener");
        devTools.getDomains().events().addConsoleListener(e -> {
            System.out.println("Hereeee!");
            System.out.println(e.getTimestamp());
            System.out.println(e.getType());
            System.out.println(e.getMessages());
        });
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));
        System.out.println("Navigating to page");
        driver.get("http://localhost:3000");
        WebElement textBox = driver.findElement(By.name("my-text"));
        driver.quit();
    }

    @Test
    public void reproducer2()
    {
        ChromeOptions options = new ChromeOptions();
        options.setLogLevel(ChromeDriverLogLevel.DEBUG);
        ChromeDriver driver = new ChromeDriver(options);
        DevTools devTools = driver.getDevTools();
        System.out.println("Creating session");
        devTools.createSession();
        System.out.println("Adding console listener");
        devTools.getDomains().events().addConsoleListener(e -> {
            System.out.println("Hereeee!");
            System.out.println(e.getTimestamp());
            System.out.println(e.getType());
            System.out.println(e.getMessages());
        });
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));
        System.out.println("Navigating to page");
        driver.get("http://localhost:3000");
        WebElement textBox = driver.findElement(By.name("my-text"));
        driver.quit();
    }

    @Test
    public void reproducer3()
    {
        FirefoxOptions options = new FirefoxOptions();
        options.setCapability("webSocketUrl", true);
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);

        FirefoxDriver driver = new FirefoxDriver(options);
        BiDi biDi = driver.getBiDi();
        biDi.addListener(Log.entryAdded(), logEntry -> {
            if (logEntry.getConsoleLogEntry().isPresent()) {
                ConsoleLogEntry entry = logEntry.getConsoleLogEntry().get();
                System.out.println(entry.getType());
                System.out.println(entry.getText());
            }
        });

        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));
        System.out.println("Navigating to page");
        driver.get("http://localhost:3000");
        WebElement textBox = driver.findElement(By.name("my-text"));
        driver.quit();
    }
}


```

**Comment by cocreature** [comment]
Thank you very much! For reference https://bugzilla.mozilla.org/show_bug.cgi?id=1795871 is the new firefox issue to track the issue on their side.
