### ISSUE TITLE
[🐛 Bug]: Modal window is not detected in tests which causing connection refused error

### ISSUE THREAD

**Issue by amitkpal83** [SeleniumHQ/selenium#11145]
### What happened?

We are running selenium test's created in C# language in chrome. Operating system is linux. Original application is in .net. Most of test's are running fine in linux but few which have modal popup involved those are failing with connection refused error. We are running chrome in headless mode. Have tried lot of things but modal popup test cases are continuously failing.

### How can we reproduce the issue?

```shell
I cannot share my application code but it is a simple application where we are having few windows popup to show the customer information. Application built in .net. Simple test cases are there but whichever test case involved modal popup method those are failing.
```

### Relevant log output

```shell
X AssignSupplementRequest [11m 11s]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at AutoFramework.Helpers.Shouldly.IsTrue(Boolean expected)
   at AutoFramework.Extensions.WebDriverExtension.WaitForElementPresentAndEnabled(IWebDriver driver, By locator, Int32 timeOut)
   at AutoFramework.Extensions.WebElementExtension.IsElementPresent(IWebDriver driver, By locator, Int32 timeOut)
   at AutoFramework.Extensions.WebElementExtension.AssertElementPresent(IWebDriver driver, By locator, Int32 timeOut)
   at Automation.POM.PageActions.CommonAction.SelectCustomerUser(IWebDriver driver, String customerName) in    at Automation.Smoke.StepsFiles. in 

  Standard Output Messages:
 Connection refused Connection refused
 Connection refused Connection refused
```

### Operating System

Linux

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 103

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 103

**Comment by diemol** [comment]
Closing as we did not get more information.
