### ISSUE TITLE
Getting Error Message 'java.lang.AbstractMethodError: org.openqa.selenium.remote.service.DriverService$Builder.createArgs()Ljava/util/List;' While Upgrading From Selenium 3.141.59 to 4.5.0 in my Appium Project.

### ISSUE THREAD

**Issue by vishnuverma2908** [SeleniumHQ/selenium#11149]
### What happened?

While Upgrading the selenium in my appium project from 3.141.59 to 4.5.0, I came across new Exception whose Exception message is as follows: 
java.lang.AbstractMethodError: org.openqa.selenium.remote.service.DriverService$Builder.createArgs()Ljava/util/List;
Hence i am unable to start my Server programmatically after Selenium library upgradation .

### How can we reproduce the issue?

```shell
The code base to reproduce the issue:

public static URL startAppiumServer() {
		try {
			log.info("Entering in GetInstance method.");
			AppiumServiceBuilder builder = new AppiumServiceBuilder();
			builder.withAppiumJS(new File(PATH_TO_appium_main.js)).withIPAddress("127.0.0.1").usingPort(8206).withLogFile(new File("AppiumLog.txt"));
			server = AppiumDriverLocalService.buildService(builder);
			if(!Objects.isNull(server)) {
			log.info("Service object is not null : "+server);
			server.clearOutPutStreams();
			log.info("Returning AppiumDriverLocalService Successfully.");
		    log.info("Url is : " + server.getUrl());
		    server.start();
		    log.info("Appium Server has been started successfully.");
			}
		}
		catch(Exception e) {
			log.error("Exception occured while Creating and Starting appium server",e);
			System.exit(1);
		}
		return server.getUrl();
	}
```

### Relevant log output

```shell
java.lang.AbstractMethodError: org.openqa.selenium.remote.service.DriverService$Builder.createArgs()Ljava/util/List;
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:444)
	at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:86)
	at common.BaseClass.startAppiumServer(BaseClass.java:94)
	at common.BaseClass.configureAppium(BaseClass.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

### Operating System

Windows 10

### Selenium version

4.5.0

### What are the browser(s) and version(s) where you see this issue?

Using Selenium API for Appium to test native mobile app.

### What are the browser driver(s) and version(s) where you see this issue?

UiAutomator2

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
To use Selenium 4 with Appium Java client, please follow the [upgrade guide](https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md) from the Appium project. If you need help or have questions, please reach out through our [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.
