### ISSUE TITLE
[🐛 Bug]: Unable to instance ChromeDriver using `dotnet-script`

### ISSUE THREAD

**Issue by enricobenedos** [SeleniumHQ/selenium#11155]
### What happened?

Hello,

I'm using `Selenium.WebDriver` and `WebDriverManager` packages in a [dotnet script](https://github.com/dotnet-script/dotnet-script).
During the `ChromeDriver` initialization (when instancing it) an exception regarding a missing package is fired. In a normal console app this issue does not happen.

Steps:
- install `dotnet-script` tool
- paste the code in a text file with `.csx` extensions
- `dotnet-script .\thatScript.csx`

### How can we reproduce the issue?

```shell
#
#r "nuget: Selenium.WebDriver, 4.4.0"
#r "nuget: WebDriverManager, 2.15.0"

using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using WebDriverManager;
using WebDriverManager.DriverConfigs.Impl;
using WebDriverManager.Helpers;

//Let's log user in
// Instance chrome driver and the connection with it
ChromeOptions options = new ChromeOptions();
options.AddArgument("--no-sandbox");
options.AddArgument("--headless");

//If chrome instance is locally available (for example personal PC)
// Download chrome driver in order to be able use it
new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);

ChromeDriverService service = ChromeDriverService.CreateDefaultService();
service.EnableVerboseLogging = false;
service.SuppressInitialDiagnosticInformation = true;
service.HideCommandPromptWindow = true;

var driver = new ChromeDriver(service, options);
System.Console.WriteLine("Driver initialized");
```

### Relevant log output

```shell
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (0x80131621)
File name: 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
 ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
```

### Operating System

Windows 11

### Selenium version

C# 4.4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome  106.0.5249.119

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106.0.5249.61

**Comment by nvborisenko** [comment]
Not reproducible, at least on the latest `dotnet-script` version.

When you resolve this, you face new issue that `Selenium Manager` is not involved in the process of driver binary detection. This is not an issue on Selenium side, please report it to `dotnet-script` (they don't consider `*.targets` files in nuget packages).

**Comment by titusfortner** [comment]
No follow-up and Selenium 4.16 should obviate the need for another driver manager.
