### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by andos561** [SeleniumHQ/selenium#11164]
### What happened?

I'm running a test on the Grid with Firefox and I always get this Exception in the console.
I pasted the grid hub log in the Relevant log output section.

org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://10.169.54.25:4444/session/251e675f-7847-44ea-ba81-873fec335bbb/se/cdp
Build info: version: '4.5.2', revision: '702c64f787c'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.16'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
	at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:107)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:34)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$0(SeleniumCdpConnection.java:56)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:54)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:47)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:50)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:31)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:186)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.build(RemoteWebDriverBuilder.java:375)

### How can we reproduce the issue?

```shell
Run a test on the Grid with Firefox and Win 10 nodes
```

### Relevant log output

```shell
08:01:54.716 DEBUG [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "cfd62c6db2e414a70bdde42094f0195a","eventTime": 1666684914711825748,"eventName": "Session created by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {acceptInsecureCerts: true, proxy: {httpProxy: 10.163.24.235:443, noProxy: [.jsdelivr.net], proxyType: MANUAL, sslProxy: 10.163.24.235:443}}, Capabilities {acceptInsecureCerts: true, proxy: {httpProxy: 10.163.24.235:443, noProxy: [.jsdelivr.net], proxyType: manual, sslProxy: 10.163.24.235:443}}]","session.capabilities": "{\"acceptInsecureCerts\": true,\"browserName\": \"firefox\",\"browserVersion\": \"106.0.1\",\"moz:accessibilityChecks\": false,\"moz:buildID\": \"20221019185550\",\"moz:geckodriverVersion\": \"0.32.0\",\"moz:headless\": false,\"moz:platformVersion\": \"10.0\",\"moz:processID\": 7088,\"moz:profile\": \"C:\\\\Users\\\\testuser\\\\AppData\\\\Local\\\\Temp\\\\rust_mozprofileJSjQgX\",\"moz:shutdownTimeout\": 60000,\"moz:useNonSpecCompliantPointerOrigin\": false,\"moz:webdriverClick\": true,\"moz:windowless\": false,\"pageLoadStrategy\": \"normal\",\"platformName\": \"WINDOWS\",\"proxy\": {\"httpProxy\": \"10.163.24.235:443\",\"proxyType\": \"MANUAL\",\"noProxy\": [  \".jsdelivr.net\"  ],  \"sslProxy\": \"10.163.24.235:443\"  },  \"se:bidi\": \"ws:\\u002f\\u002f10.169.54.25:4444\\u002fsession\\u002f251e675f-7847-44ea-ba81-873fec335bbb\\u002fse\\u002fbidi\",  \"se:cdp\": \"ws:\\u002f\\u002f10.169.54.25:4444\\u002fsession\\u002f251e675f-7847-44ea-ba81-873fec335bbb\\u002fse\\u002fcdp\",  \"setWindowRect\": true,  \"strictFileInteractability\": false,  \"timeouts\": {  \"implicit\": 0,  \"pageLoad\": 300000,  \"script\": 30000  },  \"unhandledPromptBehavior\": \"dismiss and notify\"  }\n","session.id": "251e675f-7847-44ea-ba81-873fec335bbb","session.uri": "http:\u002f\u002f10.169.54.29:5555"}}

08:01:54.717 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=cfd62c6db2e414a70bdde42094f0195a, spanId=d26c94cc620bf820, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=cfd62c6db2e414a70bdde42094f0195a, spanId=e15472f43f032e40, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=true, valid=true}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=sessionqueue.completed, kind=INTERNAL, startEpochNanos=1666684914716000000, endEpochNanos=1666684914716426302, attributes={}, totalAttributeCount=0, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
08:01:54.717 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=cfd62c6db2e414a70bdde42094f0195a, spanId=c41247787e40b782, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=cfd62c6db2e414a70bdde42094f0195a, spanId=e15472f43f032e40, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=true, valid=true}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=sessionqueue.add_to_queue, kind=INTERNAL, startEpochNanos=1666684886448000000, endEpochNanos=1666684914716880703, attributes={}, totalAttributeCount=0, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
08:01:54.717 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=cfd62c6db2e414a70bdde42094f0195a, spanId=1d328f6d4e487b5e, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=cfd62c6db2e414a70bdde42094f0195a, spanId=e15472f43f032e40, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=true, valid=true}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=distributor.poll_queue, kind=INTERNAL, startEpochNanos=1666684910515000000, endEpochNanos=1666684914716751864, attributes=AttributesMap{data={request.id=aa936248-b3bb-421e-bd81-e02beb4149f5}, capacity=128, totalAddedValues=1}, totalAttributeCount=1, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
08:01:54.718 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=cfd62c6db2e414a70bdde42094f0195a, spanId=e15472f43f032e40, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=session_queue, kind=INTERNAL, startEpochNanos=1666684886394000000, endEpochNanos=1666684914717731217, attributes=AttributesMap{data={span.kind=server, http.target=/session, random.key=c6dd9b79-3119-43fc-aab8-57b6fba15e3f, http.method=POST, http.status_code=200}, capacity=128, totalAddedValues=5}, totalAttributeCount=5, events=[ImmutableEventData{name=HTTP request execution complete, attributes={http.flavor=1, http.handler_class="org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue", http.host="10.169.54.25:4444", http.method="POST", http.request_content_length="949", http.scheme="HTTP", http.status_code=200, http.target="/session", http.user_agent="selenium/4.5.2 (java windows)"}, epochNanos=1666684914717719817, totalAttributeCount=9}], totalRecordedEvents=1, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=OK, description=Kind: OK Description:}, hasEnded=true}
08:01:54.718 DEBUG [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "cfd62c6db2e414a70bdde42094f0195a","eventTime": 1666684914717719817,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "10.169.54.25:4444","http.method": "POST","http.request_content_length": "949","http.scheme": "HTTP","http.status_code": 200,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.5.2 (java windows)"}}

08:01:54.809 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://10.169.54.29:5555 : 1
08:01:55.693 DEBUG [LoggingHandler.channelRead] - [id: 0x61ef8f02, L:/0:0:0:0:0:0:0:0:4444] READ: [id: 0x657b5878, L:/10.169.54.25:4444 - R:/10.65.248.248:61601]
08:01:55.694 DEBUG [LoggingHandler.channelReadComplete] - [id: 0x61ef8f02, L:/0:0:0:0:0:0:0:0:4444] READ COMPLETE
08:01:55.706 DEBUG [ThreadLocalRandom.newSeed] - -Dio.netty.initialSeedUniquifier: 0x98f85fa72f486043
08:01:55.710 DEBUG [NettyConnectListener.writeRequest] - Using new Channel '[id: 0xdb7be0a0, L:/10.169.54.25:60408 - R:/10.169.54.29:5555]' for 'GET' to '/session/251e675f-7847-44ea-ba81-873fec335bbb/se/cdp'
08:01:55.718 DEBUG [WebSocketHandler.handleRead] -

Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /session/251e675f-7847-44ea-ba81-873fec335bbb/se/cdp HTTP/1.1
upgrade: websocket
connection: upgrade
sec-websocket-key: RdtHrLcuAHGzlSOBjI09MQ==
sec-websocket-version: 13
origin: http://10.169.54.29:5555
host: 10.169.54.29:5555
accept: */*
user-agent: AHC/2.1

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 400 Bad Request
content-length: 15

08:01:55.718 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
java.io.IOException: Invalid Status code=400 text=Bad Request
        at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
        at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
08:01:55.719 DEBUG [ChannelManager.closeChannel] - Closing Channel [id: 0xdb7be0a0, L:/10.169.54.25:60408 - R:/10.169.54.29:5555]
08:01:55.720 DEBUG [AsyncHttpClientHandler.channelInactive] - Channel Closed: [id: 0xdb7be0a0, L:/10.169.54.25:60408 ! R:/10.169.54.29:5555] with attribute DISCARD
```

### Operating System

Windows 10

### Selenium version

Java 4.5.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 106

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.32

### Are you using Selenium Grid?

4.5.3

**Comment by diemol** [comment]
Please set the `--grid-url` parameter: https://www.selenium.dev/documentation/grid/configuration/cli_options/#node

If you are using the Docker images, please follow https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout

**Comment by andos561** [comment]
Thanks for that link. What solved it in the end was the --enable-cdp option.
