### ISSUE TITLE
[🐛 Bug]: Selenium::WebDriver::Error::JavascriptError (javascript error: b.toLowerCase is not a function)

### ISSUE THREAD

**Issue by AumCoin** [SeleniumHQ/selenium#11160]
### What happened?

I try the code below and `driver.find_element` throws the error below.  None of the information helps me to resolve the issue.  No idea what is happening here.

### How can we reproduce the issue?

```shell
require 'selenium-webdriver'
require 'webdrivers'

@driver ||= Selenium::WebDriver.for(:chrome)
@driver.get("https://www.tcgplayer.com/login")
username = @driver.find_element(:css, "input[type=email]")[0]
```

```
Traceback (most recent call last):
	33: from tcgplayer_purchase_order_scraper.rb:38:in `<main>'
	32: from tcgplayer_purchase_order_scraper.rb:14:in `login'
	31: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/element.rb:116:in `attribute'
	30: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:476:in `element_attribute'
	29: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/atoms.rb:32:in `execute_atom'
	28: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:305:in `execute_script'
	27: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
	26: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	25: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	24: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
	23: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
	22: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
	21: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	20: from /var/lib/gems/2.5.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
	19: from #19 0x7fa020b6bfa3 <unknown>
	18: from #18 0x5646d03cf8b2 <unknown>
	17: from #17 0x5646d03b5706 <unknown>
	16: from #16 0x5646d03b5588 <unknown>
	15: from #15 0x5646d036becf <unknown>
	14: from #14 0x5646d03952a3 <unknown>
	13: from #13 0x5646d0377aae <unknown>
	12: from #12 0x5646d0394622 <unknown>
	11: from #11 0x5646d039118e <unknown>
	10: from #10 0x5646d0179a21 <unknown>
	 9: from #9 0x5646d01787e3 <unknown>
	 8: from #8 0x5646d01a3d63 <unknown>
	 7: from #7 0x5646d01bba50 <unknown>
	 6: from #6 0x5646d01a3f42 <unknown>
	 5: from #5 0x5646d01bc6c3 <unknown>
	 4: from #4 0x5646d01504a0 <unknown>
	 3: from #3 0x5646d014f877 <unknown>
	 2: from #2 0x5646d014f9d7 <unknown>
	 1: from #1 0x5646d014c83a <unknown>
#0 0x5646d03432c3 <unknown>: javascript error: b.toLowerCase is not a function (Selenium::WebDriver::Error::JavascriptError)
  (Session info: chrome=106.0.5249.119)
```
```


### Relevant log output

```shell
huh?
```

### Operating System

Debian

### Selenium version

ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu] , selenium-webdriver gem 2.7.6.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 91, updated to latest and issue persists

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver, whatever version is automatically downloaded by "webdrivers" gem

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
Selenium has a shortcut for getting an attribute value of an element by doing:
```
my_element['attribute_name']
```

By adding `[0]` at the end of your element location you are requesting the element's `0` attribute value, which is an invalid type, so you get a weird JS error from the driver.
