### ISSUE TITLE
[🐛 Bug]: Perform() function from actions throwing bellow exception in docker but working fine on local system

### ISSUE THREAD

**Issue by chik145** [SeleniumHQ/selenium#11199]
### What happened?

I am trying to perform an horizontal scroll by using bellow code

 WebElement element = wait.until(presenceOfElementLocated(By.cssSelector("div[ref = \"eCenterViewport\"]")));
 actions.scrollFromOrigin(WheelInput.ScrollOrigin.fromElement(element), 500, 0).build().perform();

working fine while executing on local system, but getting bellow exception in docker system (Grid Console v.3.141.59)

### How can we reproduce the issue?

```shell
Scroll vertical/horizontal using wheelInput in docker
```

### Relevant log output

```shell
org.openqa.selenium.InvalidArgumentException: invalid argument
from invalid argument: 'type' must be one of the strings 'key', 'pointer' or 'none'
  (Session info: chrome=81.0.4044.92)
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [bb126809a1334ec8dd624f215cc6e8b5, actions {actions=[org.openqa.selenium.interactions.Sequence@3ab6678b]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 81.0.4044.92, chrome: {chromedriverVersion: 81.0.4044.69 (6813546031a4b..., userDataDir: /tmp/.com.google.Chrome.FYRJ4S}, goog:chromeOptions: {debuggerAddress: localhost:35167}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: bb126809a1334ec8dd624f215cc...}
Session ID: bb126809a1334ec8dd624f215cc6e8b5
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:609)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:567)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:536)
```

### Operating System

win 10

### Selenium version

4.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

latest

### Are you using Selenium Grid?
Grid Console v.3.141.59

**Comment by titusfortner** [comment]
I think you need at least Chrome 86, and probably Grid >= 4.2 for this functionality to work correctly.
