### ISSUE TITLE
[🐛 Bug]: NetworkAuthenticationHandler invokes unhandled exception when used with domain authentication

### ISSUE THREAD

**Issue by bobylevm** [SeleniumHQ/selenium#11216]
### What happened?

We use NetworkAuthenticationHandler to perform domain authentication on corporate site. To reproduce the issue you need a default IIS site at your network with windows domain authentication.
Unhandled exception is thrown after driver.Quit():
System.InvalidOperationException
  HResult=0x80131509
  Message=A command response was not received: Fetch.getResponseBody
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.DevTools.DevToolsSession.<SendCommand>d__35.MoveNext()
   at OpenQA.Selenium.DevTools.DevToolsSession.<SendCommand>d__34`2.MoveNext()
   at OpenQA.Selenium.DevTools.V106.Fetch.FetchAdapter.<GetResponseBody>d__19.MoveNext()
   at OpenQA.Selenium.DevTools.V106.V106Network.<AddResponseBody>d__15.MoveNext()
   at OpenQA.Selenium.NetworkManager.<OnResponsePaused>d__21.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

If you uncomment Thread.Sleep(500), than unhandled exception is not thrown.

### How can we reproduce the issue?

```shell
static void Main(string[] args)
{
    var browserOptions = new ChromeOptions();
    var driver = new RemoteWebDriver(new Uri("http://selenium.domain.com:4444/wd/hub"),
        browserOptions.ToCapabilities(), new TimeSpan(0, 5, 0));
    NetworkAuthenticationHandler handler = new NetworkAuthenticationHandler()
    {
        UriMatcher = (d) => d.Host.Contains("domain.com"),
        Credentials = new PasswordCredentials("user@domain.com", "password")
    };
    driver.Manage().Network.AddAuthenticationHandler(handler);
    driver.Manage().Network.StartMonitoring().Wait();

    driver.Navigate().GoToUrl(new Uri("https://testsite.domain.com"));
    driver.Manage().Network.StopMonitoring().Wait();
    //Thread.Sleep(500);
    driver.Quit();

    Console.WriteLine($@"{DateTime.UtcNow} - driver closed");
    Thread.Sleep(10000);
}
```

### Relevant log output

```shell
13:59:41.652 FINEST [WebSocket08FrameDecoder.decode] - Decoding WebSocket Frame opCode=1
13:59:41.652 FINEST [WebSocket08FrameDecoder.decode] - Decoding WebSocket Frame length=1758
13:59:41.653 FINEST [LoggingHandler.channelReadComplete] - [id: 0xddecbfc7, L:/127.0.0.1:56090 - R:localhost/127.0.0.1:56082] READ COMPLETE
13:59:41.653 FINEST [WebSocket08FrameEncoder.encode] - Encoding WebSocket Frame opCode=1 length=1758
13:59:41.655 FINEST [WebSocket08FrameDecoder.decode] - Decoding WebSocket Frame opCode=8
13:59:41.655 FINEST [WebSocket08FrameDecoder.decode] - Decoding WebSocket Frame length=2
13:59:41.656 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
DELETE /wd/hub/session/88d2d8d57e6821905b3808444fc1db0c HTTP/1.1
Host: selenium.domain.com.ru:4444
User-Agent: selenium/4.0.0 (.net windows)
Accept: application/json, image/png
13:59:41.656 DEBUG [RequestConverter.channelRead0] - Start of http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
DELETE /wd/hub/session/88d2d8d57e6821905b3808444fc1db0c HTTP/1.1
Host: selenium.domain.com:4444
User-Agent: selenium/4.0.0 (.net windows)
Accept: application/json, image/png
13:59:41.656 DEBUG [RequestConverter.channelRead0] - Incoming message: EmptyLastHttpContent
13:59:41.656 FINEST [WebSocket08FrameEncoder.encode] - Encoding WebSocket Frame opCode=8 length=2
13:59:41.656 DEBUG [RequestConverter.channelRead0] - Closing input pipe.
13:59:41.658 DEBUG [RequestConverter.channelInactive] - Closing input pipe, channel became inactive.
13:59:41.658 DEBUG [HttpTracing.inject] - Injecting (DELETE) /session/88d2d8d57e6821905b3808444fc1db0c into OpenTelemetrySpan{traceId=02747cc0183e2e4ebd66fe6c3035461c,spanId=43c4305d4f629534} at org.openqa.selenium.grid.router.HandleSession:121
13:59:41.659 FINEST [WebSocket08FrameEncoder.encode] - Encoding WebSocket Frame opCode=8 length=2
13:59:41.659 FINEST [LoggingHandler.write] - [id: 0xddecbfc7, L:/127.0.0.1:56090 - R:localhost/127.0.0.1:56082] WRITE: 8B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 88 82 73 02 db b6 8c fd                         |..s.....        |
+--------+-------------------------------------------------+----------------+
13:59:41.659 FINEST [LoggingHandler.flush] - [id: 0xddecbfc7, L:/127.0.0.1:56090 - R:localhost/127.0.0.1:56082] FLUSH
13:59:41.660 DEBUG [SpanWrappedHttpHandler.execute] - Wrapping request. Before OpenTelemetryContext{tracer=io.opentelemetry.sdk.trace.SdkTracer@9cdb213, context={opentelemetry-trace-span-key=SdkSpan{traceId=02747cc0183e2e4ebd66fe6c3035461c, spanId=d6c50d2ec0e509b1, parentSpanContext=ImmutableSpanContext{traceId=02747cc0183e2e4ebd66fe6c3035461c, spanId=43c4305d4f629534, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=true, valid=true}, name=reverse_proxy, kind=INTERNAL, attributes=AttributesMap{data={http.method=DELETE, http.target=/session/88d2d8d57e6821905b3808444fc1db0c}, capacity=128, totalAddedValues=2}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1667473181659000000, endEpochNanos=0}}, span id=d6c50d2ec0e509b1, trace id=02747cc0183e2e4ebd66fe6c3035461c} and after OpenTelemetryContext{tracer=io.opentelemetry.sdk.trace.SdkTracer@9cdb213, context={opentelemetry-trace-span-key=SdkSpan{traceId=02747cc0183e2e4ebd66fe6c3035461c, spanId=b928d59e04ab01bb, parentSpanContext=ImmutableSpanContext{traceId=02747cc0183e2e4ebd66fe6c3035461c, spanId=43c4305d4f629534, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=true, valid=true}, name=node.forward_command, kind=INTERNAL, attributes=AttributesMap{data={random.key=ab9743eb-8465-4596-974a-03fc1f38c338}, capacity=128, totalAddedValues=1}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1667473181659000000, endEpochNanos=0}}, span id=b928d59e04ab01bb, trace id=02747cc0183e2e4ebd66fe6c3035461c}
13:59:41.660 FINEST [LoggingHandler.channelReadComplete] - [id: 0xddecbfc7, L:/127.0.0.1:56090 - R:localhost/127.0.0.1:56082] READ COMPLETE
13:59:41.660 DEBUG [HttpTracing.inject] - Injecting (DELETE) /session/88d2d8d57e6821905b3808444fc1db0c into OpenTelemetrySpan{traceId=02747cc0183e2e4ebd66fe6c3035461c,spanId=b928d59e04ab01bb} at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler:84
13:59:41.660 FINEST [LoggingHandler.channelInactive] - [id: 0xddecbfc7, L:/127.0.0.1:56090 ! R:localhost/127.0.0.1:56082] INACTIVE
13:59:41.661 DEBUG [AsyncHttpClientHandler.channelInactive] - Channel Closed: [id: 0xddecbfc7, L:/127.0.0.1:56090 ! R:localhost/127.0.0.1:56082] with attribute NettyResponseFuture{currentRetry=0,
	isDone=1,
	isCancelled=0,
	asyncHandler=org.asynchttpclient.ws.WebSocketUpgradeHandler@298e7ac4,
	nettyRequest=org.asynchttpclient.netty.request.NettyRequest@1cd94afa,
	future=java.util.concurrent.CompletableFuture@67eb9b25[Completed normally],
	uri=ws://localhost:56082/devtools/browser/c6970e87-4768-44f5-83f7-8eba561c6311,
	keepAlive=true,
	redirectCount=0,
	timeoutsHolder=null,
	inAuth=0,
	touch=1667473181652}
13:59:41.661 FINEST [WebSocketHandler.handleChannelInactive] - Connection was closed abnormally (that is, with no close frame being received).
13:59:41.661 DEBUG [ChannelManager.closeChannel] - Closing Channel [id: 0xddecbfc7, L:/127.0.0.1:56090 ! R:localhost/127.0.0.1:56082] 
13:59:41.662 FINEST [LoggingHandler.channelUnregistered] - [id: 0xddecbfc7, L:/127.0.0.1:56090 ! R:localhost/127.0.0.1:56082] UNREGISTERED
13:59:41.662 DEBUG [NettyRequestSender.pollPooledChannel] - Using pooled Channel '[id: 0x2c262d3a, L:/127.0.0.1:56081 - R:localhost/127.0.0.1:5165]' for 'DELETE' to 'http://localhost:5165/session/88d2d8d57e6821905b3808444fc1db0c'
13:59:41.662 DEBUG [NettyRequestSender.sendRequestWithOpenChannel] - Using open Channel [id: 0x2c262d3a, L:/127.0.0.1:56081 - R:localhost/127.0.0.1:5165] for DELETE '/session/88d2d8d57e6821905b3808444fc1db0c'
13:59:41.663 FINEST [LoggingHandler.write] - [id: 0x2c262d3a, L:/127.0.0.1:56081 - R:localhost/127.0.0.1:5165] WRITE: 329B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 44 45 4c 45 54 45 20 2f 73 65 73 73 69 6f 6e 2f |DELETE /session/|
|00000010| 38 38 64 32 64 38 64 35 37 65 36 38 32 31 39 30 |88d2d8d57e682190|
|00000020| 35 62 33 38 30 38 34 34 34 66 63 31 64 62 30 63 |5b3808444fc1db0c|
|00000030| 20 48 54 54 50 2f 31 2e 31 0d 0a 41 63 63 65 70 | HTTP/1.1..Accep|
|00000040| 74 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6a |t: application/j|
|00000050| 73 6f 6e 2c 20 69 6d 61 67 65 2f 70 6e 67 0d 0a |son, image/png..|
|00000060| 55 73 65 72 2d 41 67 65 6e 74 3a 20 73 65 6c 65 |User-Agent: sele|
|00000070| 6e 69 75 6d 2f 34 2e 30 2e 30 20 28 2e 6e 65 74 |nium/4.0.0 (.net|
|00000080| 20 77 69 6e 64 6f 77 73 29 0d 0a 43 6f 6e 6e 65 | windows)..Conne|
|00000090| 63 74 69 6f 6e 3a 20 6b 65 65 70 2d 61 6c 69 76 |ction: keep-aliv|
|000000a0| 65 0d 0a 43 61 63 68 65 2d 43 6f 6e 74 72 6f 6c |e..Cache-Control|
|000000b0| 3a 20 6e 6f 2d 63 61 63 68 65 0d 0a 74 72 61 63 |: no-cache..trac|
|000000c0| 65 70 61 72 65 6e 74 3a 20 30 30 2d 30 32 37 34 |eparent: 00-0274|
|000000d0| 37 63 63 30 31 38 33 65 32 65 34 65 62 64 36 36 |7cc0183e2e4ebd66|
|000000e0| 66 65 36 63 33 30 33 35 34 36 31 63 2d 32 30 39 |fe6c3035461c-209|
|000000f0| 36 30 62 61 38 36 63 31 63 63 32 62 31 2d 30 31 |60ba86c1cc2b1-01|
|00000100| 0d 0a 68 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 |..host: localhos|
|00000110| 74 3a 35 31 36 35 0d 0a 43 6f 6e 74 65 6e 74 2d |t:5165..Content-|
|00000120| 54 79 70 65 3a 20 61 70 70 6c 69 63 61 74 69 6f |Type: applicatio|
|00000130| 6e 2f 6a 73 6f 6e 3b 20 63 68 61 72 73 65 74 3d |n/json; charset=|
|00000140| 75 74 66 2d 38 0d 0a 0d 0a                      |utf-8....       |
+--------+-------------------------------------------------+----------------+
13:59:41.663 FINEST [LoggingHandler.flush] - [id: 0x2c262d3a, L:/127.0.0.1:56081 - R:localhost/127.0.0.1:5165] FLUSH
13:59:41.752 FINEST [LoggingHandler.channelReadComplete] - [id: 0x86df5974, L:/127.0.0.1:56089 - R:localhost/127.0.0.1:56082] READ COMPLETE
13:59:41.752 FINEST [LoggingHandler.exceptionCaught] - [id: 0x86df5974, L:/127.0.0.1:56089 - R:localhost/127.0.0.1:56082] EXCEPTION: java.net.SocketException: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
13:59:41.752 DEBUG [AsyncHttpClientHandler.exceptionCaught] - Unexpected I/O exception on channel [id: 0x86df5974, L:/127.0.0.1:56089 - R:localhost/127.0.0.1:56082]
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
13:59:41.752 DEBUG [ChannelManager.closeChannel] - Closing Channel [id: 0x86df5974, L:/127.0.0.1:56089 - R:localhost/127.0.0.1:56082] 
13:59:41.752 FINEST [LoggingHandler.close] - [id: 0x86df5974, L:/127.0.0.1:56089 - R:localhost/127.0.0.1:56082] CLOSE
13:59:41.752 FINEST [LoggingHandler.userEventTriggered] - [id: 0x86df5974, L:/127.0.0.1:56089 ! R:localhost/127.0.0.1:56082] USER_EVENT: io.netty.channel.socket.ChannelInputShutdownReadComplete@37a5fc6e
13:59:41.752 FINEST [LoggingHandler.channelInactive] - [id: 0x86df5974, L:/127.0.0.1:56089 ! R:localhost/127.0.0.1:56082] INACTIVE
13:59:41.752 DEBUG [AsyncHttpClientHandler.channelInactive] - Channel Closed: [id: 0x86df5974, L:/127.0.0.1:56089 ! R:localhost/127.0.0.1:56082] with attribute DISCARD
13:59:41.752 FINEST [LoggingHandler.channelUnregistered] - [id: 0x86df5974, L:/127.0.0.1:56089 ! R:localhost/127.0.0.1:56082] UNREGISTERED
13:59:41.784 FINEST [LoggingHandler.channelRead] - [id: 0x2c262d3a, L:/127.0.0.1:56081 - R:localhost/127.0.0.1:5165] READ: 122B
```

### Operating System

Windows 10

### Selenium version

C# 4.5.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 107.0.5304.88

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62

### Are you using Selenium Grid?

standalone 4.5.3

**Comment by titusfortner** [comment]
Did this used to work and now no longer does? does it work in another context but not this one? We've gotten a few issues reported recently surrounding `driver.Manage().Network.StartMonitoring().Wait();` and I'm not sure if that's coincidence for something that has never worked properly or if something changed.

**Comment by titusfortner** [comment]
I think this is another one to merge with #11129 though. At least I expect the resolution is the same for it.

**Comment by pujagani** [comment]
I think the issue seems same as https://github.com/SeleniumHQ/selenium/issues/10564.

**Comment by nvborisenko** [comment]
Please try the latest selenium version, it was significantly improved. Feel free to open new issue in any case.
