### ISSUE TITLE
[🐛 Bug]: Not able to launch Firefox browser with 4.6.0 - Selenium Manager.

### ISSUE THREAD

**Issue by naveenanimation20** [SeleniumHQ/selenium#11231]
### What happened?

Bug Summary: Not able to launch Firefox browser with 4.6.0 - Selenium Manager.

Browser: Firefox
Browser Version: 106.0.5 (64-bit)
Selenium-Java version: 4.6.0

==========sample code======
package demo;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class DemoPage {

	public static void main(String[] args) {

		
		WebDriver driver = new FirefoxDriver();
		driver.get("https://www.google.com");
		System.out.println(driver.getTitle());
		
		driver.quit();
		
	}

}

=======================

Getting below exception:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
/Users/naveenautomation/Library/Application Support/WebDriverManager/gecko/v0.29.0/geckodriver-v0.29.0-macos/geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context

USAGE:
    geckodriver --port <PORT>

For more information try --help

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'naveenautomationlabss-MacBook-Pro.local', ip: '2401:4900:1f29:1cb0:21cb:54ee:fb86:20dc%en0'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:111)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:99)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
	at demo.DemoPage.main(DemoPage.java:11)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_261'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:239)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	... 6 more

### How can we reproduce the issue?

```shell
Bug Summary: Not able to launch Firefox browser with 4.6.0 - Selenium Manager.

Browser: Firefox
Browser Version: 106.0.5 (64-bit)
Selenium-Java version: 4.6.0
```

### Relevant log output

```shell
Getting below exception:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
/Users/naveenautomation/Library/Application Support/WebDriverManager/gecko/v0.29.0/geckodriver-v0.29.0-macos/geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context

USAGE:
    geckodriver --port <PORT>

For more information try --help

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'naveenautomationlabss-MacBook-Pro.local', ip: '2401:4900:1f29:1cb0:21cb:54ee:fb86:20dc%en0'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:111)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:99)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
	at demo.DemoPage.main(DemoPage.java:11)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_261'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:239)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	... 6 more
```

### Operating System

MAC OS

### Selenium version

Java 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 106.0

### What are the browser driver(s) and version(s) where you see this issue?

Selenium Manager

### Are you using Selenium Grid?

NO

**Comment by titusfortner** [comment]
Selenium Manager does not get used when another driver is found on the system. In this case, it appears an old version of geckodriver is in your `WebDriverManager` directory above. Selenium Manager downloads drivers to a `~/.cache` subdirectory.

Remove references to 3rd party driver managers, and delete all drivers from directories on PATH
