### ISSUE TITLE
[🐛 Bug]: selenium can't get dom elements in facebook

### ISSUE THREAD

**Issue by AhmedSheri123** [SeleniumHQ/selenium#11245]
### What happened?

**the problem the selenium can't see html elements that generated by javascript or dom in facebook page** 

selenium see the javascript or dom code only and can't see rendered html code by javascript or dom

I hope you understand what I mean, thank you

### How can we reproduce the issue?

```shell
python code:

WebDriverWait(driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.CSS_SELECTOR,"iframe[title='reCAPTCHA']"))) 

WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "div.recaptcha-checkbox-border"))).click()

selenium after load the page view this code link below:
before dom selenium view this code only and can't get elements after dom:

https://raw.githubusercontent.com/AhmedSheri123/license/main/source.html
```

### Relevant log output

```shell
c:\Users\****\Documents\****\****\project\venv\lib\site-packages\pydub\utils.py:170: RuntimeWarning: 

DevTools listening on ws://127.0.0.1:11202/devtools/browser/0120b89b-8a42-45bc-a991-ead5c3c0de22
[8136:600:1109/194410.150:ERROR:device_event_log_impl.cc(215)] [19:44:10.150] USB: usb_device_handle_win.cc:1048 Failed to read descriptor 
from node connection: A device attached to the system is not functioning. (0x1F)
[8136:600:1109/194410.154:ERROR:device_event_log_impl.cc(215)] [19:44:10.155] USB: usb_device_handle_win.cc:1048 Failed to read descriptor 
from node connection: A device attached to the system is not functioning. (0x1F)
الاشتراك في فيسبوك | فيسبوك
['CDwindow-C8C8C349895E61EFDE57EDB5188B8D1E']
Traceback (most recent call last):
  File "c:\Users\SHERI\Documents\mostql\MosaShaheen\facebook\main.py", line 120, in <module>
    WebDriverWait(driver, 20).until(EC.frame_to_be_available_and_switch_to_it((By.CSS_SELECTOR,"iframe[title='reCAPTCHA']")))
  File "c:\Users\SHERI\Documents\mostql\MosaShaheen\facebook\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until 
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00D0ACD3+2075859]
        Ordinal0 [0x00C9EE61+1633889]
        Ordinal0 [0x00B9B7BD+571325]
        Ordinal0 [0x00BCAC2F+764975]
        Ordinal0 [0x00BCAE1B+765467]
        Ordinal0 [0x00BFD0F2+970994]
        Ordinal0 [0x00BE7364+881508]
        Ordinal0 [0x00BFB56A+963946]
        Ordinal0 [0x00BE7136+880950]
        Ordinal0 [0x00BBFEFD+720637]
        Ordinal0 [0x00BC0F3F+724799]
        GetHandleVerifier [0x00FBEED2+2769538]
        GetHandleVerifier [0x00FB0D95+2711877]
        GetHandleVerifier [0x00D9A03A+521194]
        GetHandleVerifier [0x00D98DA0+516432]
        Ordinal0 [0x00CA682C+1665068]
        Ordinal0 [0x00CAB128+1683752]
        Ordinal0 [0x00CAB215+1683989]
        Ordinal0 [0x00CB6484+1729668]
        BaseThreadInitThunk [0x76A0FA29+25]
        RtlGetAppContainerNamedObjectPath [0x776E7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x776E7B8E+238]
```

### Operating System

windows10

### Selenium version

4.5.0

### What are the browser(s) and version(s) where you see this issue?

chrome v- 107.0.5304.88 

### What are the browser driver(s) and version(s) where you see this issue?

from webdriver_manager.chrome import ChromeDriverManager

**Comment by diemol** [comment]
Facebook is most likely blocking the agent used for automation. If you want to automate Facebook, I assume you work there and have authorization to do so, and in that case you can reach out to the developers or DevOps area to allow automation on the site.
