### ISSUE TITLE
[🐛 Bug]: Implicit wait is ignoring NoSuchElementException when using relative locators

### ISSUE THREAD

**Issue by alpatron** [SeleniumHQ/selenium#11261]
### What happened?

When setting WebDriver to use an implicit wait and then using a relative locator that does not immediately find the element, Selenium immediately crashes with a `NoSuchElementException` without waiting and retrying for the set implicit wait time.

The code example uses Chrome, but the same behaviour is happening in Firefox as well.

Explicit waits on the other hand work as expected:

```
from selenium.webdriver.support.wait import WebDriverWait
from selenium import webdriver
from selenium.webdriver.support.relative_locator import locate_with
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get('https://www.example.com')
WebDriverWait(driver,30).until(lambda driver: driver.find_element(
    locate_with(By.TAG_NAME,"p").near({By.TAG_NAME:"footer"}) #There is no footer tag on the website
))
driver.close()
```
The code above waits 30 seconds and then returns a `TimeoutException` exception.

I expect that `find_element` calls with relative locators and an implicit wait set to wait for the set amount of time and then raise a timeout exception if the element is not found.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.support.relative_locator import locate_with
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.implicitly_wait(30)
driver.get('https://www.example.com')
driver.find_element(
    locate_with(By.TAG_NAME,"p").near({By.TAG_NAME:"footer"}) #There is no footer tag on the website
)
driver.close()
```

### Relevant log output

```shell
DevTools listening on ws://127.0.0.1:19054/devtools/browser/7d9b9623-b238-40c0-8529-8f7c25ed70c4
Traceback (most recent call last):
  File "C:\Users\Vikto\Desktop\SeleniumTests Big Boy\debug.py", line 8, in <module>
    driver.find_element(
  File "C:\Users\Vikto\Desktop\SeleniumTests Big Boy\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 846, in find_element
    elements = self.find_elements(by=by, value=value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vikto\Desktop\SeleniumTests Big Boy\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 878, in find_elements
    return self.execute_script(find_element_js, by.to_dict())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vikto\Desktop\SeleniumTests Big Boy\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 506, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vikto\Desktop\SeleniumTests Big Boy\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Vikto\Desktop\SeleniumTests Big Boy\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: No element has been found by {"tag name":"footer"}
  (Session info: chrome=107.0.5304.107)
Stacktrace:
Backtrace:
        Ordinal0 [0x00B5ACD3+2075859]
        Ordinal0 [0x00AEEE61+1633889]
        Ordinal0 [0x009EB7BD+571325]
        Ordinal0 [0x009EE374+582516]
        Ordinal0 [0x009EE225+582181]
        Ordinal0 [0x009EEBA5+584613]
        Ordinal0 [0x00A4BF4F+966479]
        Ordinal0 [0x00A3731C+881436]
        Ordinal0 [0x00A4B56A+963946]
        Ordinal0 [0x00A37136+880950]
        Ordinal0 [0x00A0FEFD+720637]
        Ordinal0 [0x00A10F3F+724799]
        GetHandleVerifier [0x00E0EED2+2769538]
        GetHandleVerifier [0x00E00D95+2711877]
        GetHandleVerifier [0x00BEA03A+521194]
        GetHandleVerifier [0x00BE8DA0+516432]
        Ordinal0 [0x00AF682C+1665068]
        Ordinal0 [0x00AFB128+1683752]
        Ordinal0 [0x00AFB215+1683989]
        Ordinal0 [0x00B06484+1729668]
        BaseThreadInitThunk [0x75CFFA29+25]
        RtlGetAppContainerNamedObjectPath [0x776C7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x776C7B8E+238]
```

### Operating System

Windows 10 21H1

### Selenium version

Python 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62

### Are you using Selenium Grid?

No

**Comment by symonk** [comment]
Thanks for the report.  At a quick glance the `Relative` locators send a sizable blob of javascript internally within `find_elements(..., ...)` via `/w3cExecuteScript` but the normal flow is to dispatch out to `findElement`.  The javascript is quite a sizable script to do the handling there but I assume the root cause is buried in there somewhere.

**Comment by titusfortner** [comment]
Relative locators are special. Implicit waits are managed by the driver when using a `POST` to the `/element` endpoint. As mentioned, relative locators are implemented with fancy JS code that gets sent to the `/execute/sync` endpoint. The driver does not (can't?) apply implicit wait logic to JS return values. You'll have to manage these with your own explicit wait implementation.
