### ISSUE TITLE
Issue in MacOS with latest version 2.48.0

### ISSUE THREAD

**Issue by javigomez** [SeleniumHQ/selenium#1127]
Hi, I have no experience with java, so my excuses.

I have a mac, and if I do: `$ java -jar selenium-server-standalone-2.48.0.jar`

I get:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncher : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

```

While with version 2.27.1: `$ java -jar selenium-server-standalone-2.27.1.jar`

```
14:27:28.557 INFO - Launching a standalone Selenium Server
14:27:28.610 INFO - Java: Apple Inc. 20.65-b04-466.1
14:27:28.610 INFO - OS: Mac OS X 10.10.5 x86_64
14:27:28.631 INFO - v2.46.0, with Core v2.46.0. Built from revision 87c69e2
14:27:28.729 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform MAC
14:27:28.729 INFO - Driver class not found: com.opera.core.systems.OperaDriver
14:27:28.730 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
14:27:28.736 INFO - Driver class is built for higher Java version: org.openqa.selenium.htmlunit.HtmlUnitDriver
14:27:28.736 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
14:27:28.835 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
14:27:28.836 INFO - Selenium Server is up and running
```

Just in case it was the issue I have to the latest xCode:

![screen shot 2015-10-08 at 14 28 48](https://cloud.githubusercontent.com/assets/1375475/10366179/efad4ffa-6dc8-11e5-8eae-22c9365654b9.png)

but the issue persists.

Does anyone can recommend me any idea to make it work?

My firefox is the latest: `41.0.1`
but I also have tried with the previous version `40` without luck.

Thanks for your help

**Comment by lukeis** [comment]
This means your java version installed on the system is very old. Selenium now requires at least java 7 installed (if you're upgrading Java, upgrade to 8)

**Comment by javigomez** [comment]
Thanks

**Comment by bmsoko** [comment]
Hello! I had updated to Java 8, and my issue still remains... what else can I do? Thanks!
```
$ ./node_modules/.bin/webdriver-manager start
seleniumProcess.pid: 454
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncher : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Selenium Standalone has exited with code 1
```

**Comment by lukeis** [comment]
@bmsoko the version of java being used here by your node modules is not java 8... this error will only occur if the java being run is version 6 or older.

**Comment by 810** [comment]
or you have 2 java versions installed. uninstall the old one.
