### ISSUE TITLE
[🐛 Bug]: ElementNotInteractableError: element not interactable

### ISSUE THREAD

**Issue by N1lshui** [SeleniumHQ/selenium#11274]
### What happened?

Hi,
when I try to use the following command on firefox, all performs correct.
But when I try to use it on Chromium based Browsers on the same site and element, It get the following

await edgeDriver.findElement(By.css('textarea[id^="input-"]'))
                        .sendKeys('Test', Key.ENTER);

ElementNotInteractableError: element not interactable
  (Session info: MicrosoftEdge=107.0.1418.42)
    at Object.throwDecodedError (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\error.js:524:15)
    at parseHttpResponse (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\http.js:587:13)
    at Executor.execute (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\http.js:515:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\webdriver.js:741:17)
...

Can you tell me why?

### How can we reproduce the issue?

```shell
Try the command above at chrome or firefox
```

### Relevant log output

```shell
ElementNotInteractableError: element not interactable
  (Session info: MicrosoftEdge=107.0.1418.42)
    at Object.throwDecodedError (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\error.js:524:15)
    at parseHttpResponse (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\http.js:587:13)
    at Executor.execute (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\http.js:515:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\webdriver.js:741:17)
...
```

### Operating System

Windows 10

### Selenium version

4.6.0

### What are the browser(s) and version(s) where you see this issue?

chrome, edge

### What are the browser driver(s) and version(s) where you see this issue?

msedgedriver 106.0.1370.47, chromedriver.exe (Version unbekannt)

### Are you using Selenium Grid?

No

**Comment by N1lshui** [comment]
Sorry, I meant to reproduce you have to use chhrome or EDGE

**Comment by diemol** [comment]
Also, if it works in Firefox and it does not work on a Chromium based browser, might be a bug in Chrome. So, if after providing a reduced test case you still have the issue, let us know and we can point you to the ChromerDriver bug tracker.

**Comment by diemol** [comment]
Closing as we did not get more information.
