### ISSUE TITLE
[🐛 Bug]: Too many logs related to 'DEBUG o.a.n.c.ChannelManager - Adding key...' while running automation scripts

### ISSUE THREAD

**Issue by VikramMokallaTR** [SeleniumHQ/selenium#11293]
### What happened?

Below logs are displayed in thousands during Selenium automated suite execution: 

12:57:21      [AsyncHttpClient-1-16] 12:57:21.320 DEBUG o.a.n.c.ChannelManager - Adding key: http://localhost:62931/ for channel [id: 0x1f18b05f, L:/127.0.0.1:61408 - R:localhost/127.0.0.1:62931]
12:57:21      [Forwarding executeScript on session b2d9187c378ddb9752e5ed47b6a48ac5 to remote] 12:57:21.320 DEBUG o.a.n.r.NettyRequestSender - Using pooled Channel '[id: 0x1f18b05f, L:/127.0.0.1:61408 - R:localhost/127.0.0.1:62931]' for 'POST' to 'http://localhost:62931/session/b2d9187c378ddb9752e5ed47b6a48ac5/execute/sync'
12:57:21      [Forwarding executeScript on session b2d9187c378ddb9752e5ed47b6a48ac5 to remote] 12:57:21.320 DEBUG o.a.n.r.NettyRequestSender - Using open Channel [id: 0x1f18b05f, L:/127.0.0.1:61408 - R:localhost/127.0.0.1:62931] for POST '/session/b2d9187c378ddb9752e5ed47b6a48ac5/execute/sync'
12:57:21      [AsyncHttpClient-1-16] 12:57:21.322 DEBUG o.a.n.h.HttpHandler - 
12:57:21  
12:57:21      Request DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
12:57:21      POST /session/b2d9187c378ddb9752e5ed47b6a48ac5/execute/sync HTTP/1.1
12:57:21      User-Agent: selenium/4.3.0 (java windows)
12:57:21      Content-Length: 229
12:57:21      Content-Type: application/json; charset=utf-8
12:57:21      host: localhost:62931
12:57:21      accept: */*
12:57:21  
12:57:21      Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
12:57:21      HTTP/1.1 200 OK
12:57:21      Content-Type: application/json; charset=utf-8
12:57:21      cache-control: no-cache
12:57:21      content-length: 14

### How can we reproduce the issue?

```shell
Upgrade Selenium version to 4.3.0 from 3.151.49 and run the existing scripts.
Chromedriver version: 103
Mode: Headless
```

### Relevant log output

```shell
[AsyncHttpClient-1-16] 12:57:21.832 DEBUG o.a.n.c.ChannelManager - Adding key: http://localhost:62931 for channel [id: 0x1f18b05f, L:/127.0.0.1:61408 - R:localhost/127.0.0.1:62931]
12:57:22      [AsyncHttpClient-1-15] 12:57:22.149 DEBUG o.a.n.h.WebSocketHandler - Unexpected I/O exception on channel [id: 0x09e4c215, L:/127.0.0.1:61335 - R:localhost/127.0.0.1:61329]
12:57:22      java.io.IOException: An existing connection was forcibly closed by the remote host
12:57:22      	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
12:57:22      	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
12:57:22      	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
12:57:22      	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
12:57:22      	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
12:57:22      	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
12:57:22      	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
12:57:22      	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
12:57:22      	at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:821)
12:57:22      	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
12:57:22      	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
12:57:22      	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
12:57:22      	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
12:57:22      	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
12:57:22      	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
12:57:22      	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
12:57:22      	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
12:57:22      	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
12:57:22      	at java.base/java.lang.Thread.run(Thread.java:829)
12:57:22      [AsyncHttpClient-1-15] 12:57:22.149 DEBUG o.a.n.h.WebSocketHandler - Trying to recover from dead Channel: [id: 0x09e4c215, L:/127.0.0.1:61335 - R:localhost/127.0.0.1:61329]
12:57:22      [AsyncHttpClient-1-15] 12:57:22.149 DEBUG o.a.n.h.WebSocketHandler - Channel Closed: [id: 0x09e4c215, L:/127.0.0.1:61335 ! R:localhost/127.0.0.1:61329] with attribute NettyResponseFuture{currentRetry=0,
12:57:22      	isDone=1,
12:57:22      	isCancelled=0,
12:57:22      	asyncHandler=org.asynchttpclient.ws.WebSocketUpgradeHandler@12a32a91,
12:57:22      	nettyRequest=org.asynchttpclient.netty.request.NettyRequest@23494c02,
12:57:22      	future=java.util.concurrent.CompletableFuture@1256b361[Completed normally],
12:57:22      	uri=ws://localhost:61329/devtools/browser/c12620d6-df77-4a4d-8fad-23894cc53b4e,
12:57:22      	keepAlive=true,
12:57:22      	redirectCount=0,
12:57:22      	timeoutsHolder=null,
12:57:22      	inAuth=0,
12:57:22      	touch=1669102042149}
12:57:22      [AsyncHttpClient-1-15] 12:57:22.149 DEBUG o.a.n.c.ChannelManager - Closing Channel [id: 0x09e4c215, L:/127.0.0.1:61335 ! R:localhost/127.0.0.1:61329] 
12:57:22      [AsyncHttpClient-1-1] 12:57:22.289 DEBUG o.a.n.c.DefaultChannelPool - Entry count for : http://localhost:62931 : 1
12:57:23      [AsyncHttpClient-1-16] 12:57:22.813 DEBUG o.a.n.h.HttpHandler - Channel Closed: [id: 0x1f18b05f, L:/127.0.0.1:61408 ! R:localhost/127.0.0.1:62931] with attribute DISCARD
12:57:23      [Test worker] 12:57:23.325 INFO  c.h.b.TestBaseSetup - Closed driver executable
12:57:23      [AsyncHttpClient-1-1] 12:57:23.389 DEBUG o.a.n.c.DefaultChannelPool - Entry count for : http://localhost:62931 : 1
12:57:23      [AsyncHttpClient-1-1] 12:57:23.389 DEBUG o.a.n.c.DefaultChannelPool - Adding Candidate expired Channel [id: 0x1f18b05f, L:/127.0.0.1:61408 ! R:localhost/127.0.0.1:62931] isIdleTimeoutExpired=false isRemotelyClosed=true isTtlExpired=false
12:57:23      [AsyncHttpClient-1-1] 12:57:23.389 DEBUG o.a.n.c.DefaultChannelPool - Closing Idle Channel [id: 0x1f18b05f, L:/127.0.0.1:61408 ! R:localhost/127.0.0.1:62931]
12:57:23      [AsyncHttpClient-1-1] 12:57:23.389 DEBUG o.a.n.c.DefaultChannelPool - Closed 1 connections out of 1 in 0 ms
12:57:23      [Test worker] 12:57:23.575 INFO  c.h.b.TestBaseSetup - Chrome Killed
12:57:23  
12:57:23  Smoke Suite HighQ 5.7.x > Events Module > com.highq.test.events.CD153 STANDARD_OUT
12:57:23      [Test worker] 12:57:23.575 INFO  c.h.l.ScreenshotListener - Executing scenario : com.highq.test.events.CD153
12:57:23      [Test worker] 12:57:23.686 INFO  c.h.b.TestBaseSetup - Current class in execution: CD153
12:57:23      [Test worker] 12:57:23.686 INFO  c.h.b.TestBaseSetup - Launching headless google chrome with new profile..
12:57:23      [Test worker] 12:57:23.686 INFO  c.h.d.DriverController - Setting up local chrome binary from path D:\jenkins_slave\workspace\Collaborate\Automation\Smoke\5.7.x_Release_Part1\oldAutomationTests_test\automationtests\resources\chromedriver.exe
```

### Operating System

Windows 10

### Selenium version

4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 103

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 103

**Comment by pujagani** [comment]
Selenium 4 uses Netty and AsyncHttpClient under the hood. The logs you see are debug logs from those libraries. There is nothing Selenium can do in this case. I suggest please change the log level if you find the debug level logs noisy. Thank you!

**Comment by VikramMokallaTR** [comment]
Thanks Pujagani

**Comment by VikramMokallaTR** [comment]
Hi @pujagani, could you please help me with a way to reduce the above mentioned logs as we haven't succeeded on doing so after trying multiple things. 

We have tried below: 
```
System.setProperty(ChromeDriverService.CHROME_DRIVER_SILENT_OUTPUT_PROPERTY, "true");
		java.util.logging.Logger.getLogger("org.openqa.selenium").setLevel(Level.INFO);
```

Also tried a few other levels, but no luck. Appreciate your help. Thanks.

**Comment by pujagani** [comment]
The logs you see are not ChromeDriver-specific logs hence the property you are trying will not work. The logs are coming from the Selenium client library, which displays debug logs only if the logging framework used by the project/testing sets the log level to debug. There is not anything Selenium related that one can do to change that, it is purely how the project is set up. Please check in your project how the logging is configured for the project and set the required log level. Thank you!
