### ISSUE TITLE
[🐛 Bug]: RemoteWebDriver.findElement works weirdly

### ISSUE THREAD

**Issue by ImSejin** [SeleniumHQ/selenium#11335]
### What happened?

When I tried to find an element by xpath, it works.

The current call stack of method was done and then jvm went into other method call stack.
I tried to do that again at there, but it doesn't work.

There is no action for ChromeDriver. The changes are only call stack.
I don't understand why.

```java
driver.findElement(By.xpath("//script[not(@src) and contains(text(), '__LZ_ME__')]"));
```

### How can we reproduce the issue?

```shell
1. Clone https://github.com/ImSejin/lezhin-comics-downloader on branch dev.
2. Write down your login info of lezhin comics to config.ini
3. Run io.github.imsejin.dl.lezhin.Application on debug mode.
4. Compare LoginProcessor.getAccessToken() with AccessTokenProcessor.getAccessToken().
```

### Relevant log output

```shell
Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 5280
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Exception in thread "main" java.lang.RuntimeException: Cannot find access token
	at io.github.imsejin.dl.lezhin.process.impl.AccessTokenProcessor.getAccessToken(AccessTokenProcessor.java:117)
	at io.github.imsejin.dl.lezhin.process.impl.AccessTokenProcessor.process(AccessTokenProcessor.java:80)
	at io.github.imsejin.dl.lezhin.process.impl.AccessTokenProcessor.process(AccessTokenProcessor.java:75)
	at io.github.imsejin.dl.lezhin.Application.main(Application.java:73)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//script[not(@src) and contains(text(), '__LZ_ME__')]"}
  (Session info: headless chrome=107.0.5304.108)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.7'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [de5624873d2b4a72ae1bdaca9b137fda, findElement {using=xpath, value=//script[not(@src) and contains(text(), '__LZ_ME__')]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.108, chrome: {chromedriverVersion: 107.0.5304.62
```

### Operating System

Windows 10

### Selenium version

Java 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107.0.5304.108

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
This is likely an issue of your implementation as it has a number of moving parts. If you think this is a Selenium bug, then you need to provide a short reproducible case that doesn't involve debugging your code repo.

**Comment by ImSejin** [comment]
Okay, I'm going to check my code again.
If I find a prove that the cause is selenium, I reopen this issue.
