### ISSUE TITLE
ChromeDriver throws UnsupportedCommandException

### ISSUE THREAD

**Issue by konsoletyper** [SeleniumHQ/selenium#1136]
### Steps to reproduce

Run 
```java
js.executeAsyncScript(readFile("script.js"), readFile("0.js"), readFile("1.js"), readFile("2.js"));
```
where files are in the [archive](https://www.dropbox.com/s/bueqwjy3wit8gmd/selenium-error.zip?dl=0), and `readFile` is declared as following:
```java
    static String readFile(File file) throws IOException {
        try (InputStream input = new FileInputStream(file)) {
            return IOUtils.toString(input, "UTF-8");
        }
    }
```

Get the following exception:

```
org.openqa.selenium.UnsupportedCommandException: missing command parameters
Command duration or timeout: 12 milliseconds
Build info: version: '2.47.2', revision: '4d972c01cab1304452627f837654326a11eb92fe', time: '2015-09-24 09:17:17'
System info: host: 'chesire-cat', ip: '192.168.1.34', os.name: 'Linux', os.arch: 'amd64', os.version: '4.1.8-100.fc21.x86_64', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.Xddz8C}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=45.0.2454.101, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: c7dc3caed25f70200920327db83f90c9
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:522)
```

### Expected result

Script completes normally

### Additional comments

I run WebDriver on 1.5K scripts and all of them complete normally, except this one (`1.js` varies between executions, others remain the same). I can't find anything special about this particular script. I can't debug any further than `HttpCommandExecutor.execute`, since it just sends commands and receives this error, and I don't have idead how to debug `chromedriver`.

**Comment by konsoletyper** [comment]
BTW, Firefox driver completes normally on all of the scripts, including this one

**Comment by lukeis** [comment]
For chromedriver specific issues, please log them with the chromedriver project:

https://code.google.com/p/chromedriver/issues/list
