### ISSUE TITLE
[🐛 Bug]: Safari test execution is queued up in console 

### ISSUE THREAD

**Issue by remyanekkuth** [SeleniumHQ/selenium#11390]
### What happened?

When try to execute selenium test in selenium grid 4  safari node , session is queuing up in grid console and after sometime getting timeout exception.

Please help. Not able to figure out what is missing.

Configuration is as below. 

seleium server  4.3.0
safari 15.4

<img width="925" alt="queue" src="https://user-images.githubusercontent.com/16626518/206469844-0a47394c-422f-4b94-bf23-201e17ecdce6.PNG">

**nodeconfig.toml file :** 

**[node]

max-sessions = 1

detect-drivers = false

grid-url = http://selenium:xxxx/grid/register

session-timeout = 1800

register = true

registerCycle = 5000

 

[[node.driver-configuration]]

max-sessions = 1

display-name = "Safari"

webdriver-executable='/usr/bin/safaridriver/'

stereotype = "{\"browserName\": \"safari\", \"browserVersion\": \"15.4\", \"platformName\": \"MAC\", \"maxInstances\": \"1\"}"

 

[events]

subscribe="tcp://grid_id:4442"

publish="tcp://grid_id:4443"

 **

**run configuration :**.   **java  -jar "path to selenium-server-4.3.0.jar"  node --config "$pathToConfigFile" --hub " http://selenium:xxxx/grid/register" --port 4900 --host machine name**

### How can we reproduce the issue?

```shell
In mac , 
get the selenium-server-4.3.0.jar 
set up toml file as 

node]
max-sessions = 1
detect-drivers = false
grid-url = "http://selenium:xxxx/grid/register"
session-timeout = 1800
register = true
registerCycle = 5000

[[node.driver-configuration]]
max-sessions = 1
display-name = "Safari"
webdriver-executable='/usr/bin/safaridriver/'
stereotype = "{\"browserName\": \"safari\", \"browserVersion\": \"15.4\", \"platformName\": \"MAC\", \"maxInstances\": \"1\"}"

[events]
subscribe="tcp://grid_id:4442"
publish="tcp://grid_id:4443"

configuration. :

java -jar "path to jar folder " node --config "toml file path" --hub "http://seleniumxxx:4944/grid/register" --port 4900 --host "computername"

run a selenium test in safari
```

### Relevant log output

```shell
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.safari.SafariDriver

              at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:168)

              at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:156)

              at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:126)

              at net.serenitybdd.core.webdriver.RemoteDriver.of(RemoteDriver.java:18)

              at com.test.testautomation.utilities.DriverUtils.getBrowserName(DriverUtils.java:28)

              at

Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.safari.SafariDriver (Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

Build info: version: '4.4.0', revision: 'e5c75ed026a'

System info: host: 'host', ip: 'ip', [os.name](http://os.name/): 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_25'

Driver info: org.openqa.selenium.remote.RemoteWebDriver

Command: [null, newSession {capabilities=[Capabilities {}], desiredCapabilities=Capabilities {}}]

Capabilities {}). See below for more details.

              at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:150)

              at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:165)

              ... 74 more

Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

Build info: version: '4.4.0', revision: 'e5c75ed026a'

System info: host: 'host name', ip: 'xxxx', [os.name](http://os.name/): 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_25'

Driver info: org.openqa.selenium.remote.RemoteWebDriver

Command: [null, newSession {capabilities=[Capabilities {}], desiredCapabilities=Capabilities {}}]

Capabilities {}

              at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:565)

              at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)

              at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)

              at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)

              at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider.newInstance(RemoteDriverProvider.java:80)

              at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:161)

              at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:140)

              ... 75 more

Caused by: java.lang.RuntimeException: NettyHttpHandler request execution error

              at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76)

              at org.openqa.selenium.remote.http.netty.NettyHttpHandler$$Lambda$538/1759328722.execute(Unknown Source)

              at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)

              at org.openqa.selenium.remote.http.AddSeleniumUserAgent$$Lambda$727/1940906679.execute(Unknown Source)

              at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)

              at org.openqa.selenium.remote.http.Filter$$Lambda$539/1625539182.execute(Unknown Source)

              at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)

              at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)

              at org.openqa.selenium.remote.http.AddSeleniumUserAgent$$Lambda$727/1940906679.execute(Unknown Source)

              at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)

              at org.openqa.selenium.remote.http.Filter$$Lambda$539/1625539182.execute(Unknown Source)

              at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:98)

              at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)

              at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:120)

              at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)

              at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)

              at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)

              at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)

              at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)

              ... 81 more

Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to [selenium-url.domain.com/ip:4944](http://selenium-url.domain.com/ip:4944) after 180000 ms

              at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2272)

              at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)

              at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)

              ... 99 more

Caused by: java.util.concurrent.TimeoutException: Request timeout to [selenium-url.domain.com/ip:4944](http://selenium-url.domain.com/ip:4944) after 180000 ms

              at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)

              at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)

              at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)

              at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)

              at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)

              at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)

              at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)

              at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

              at java.lang.Thread.run(Thread.java:745)
```

### Operating System

MacOS BigSur

### Selenium version

4.3.0

### What are the browser(s) and version(s) where you see this issue?

safari 15.4 

### What are the browser driver(s) and version(s) where you see this issue?

safari 15.4

### Are you using Selenium Grid?

4.3.0

**Comment by pujagani** [comment]
Locally, if I tried to run a Safari test against Selenium Standalone Grid 4.7, it works as expected. 

Can you please share the logs on the Grid side as well? It will help us confirm if the Safari slot was added properly.

I am thinking, there could also be a case, that the first-time test ran fine but the slot in the Grid is occupied and hence the second test keep retrying and waiting in the queue. Did you try to run the test multiple times? 
Does it only happen with Safari? or even other browsers?

**Comment by pujagani** [comment]
Locally, one thing I observed is, on calling `driver.quit()`, I sometimes see an error message "Safari quit unexpectedly". After that, if try to run the test again, the Grid retries the session request since the first request has blocked the slot, and hence it stays in the queue. But this seems like a Safari error to not quit in a clean manner. My machine has Safari Version 16.1.

**Comment by remyanekkuth** [comment]
@pujagani thus issue is only with safari.
When I ran for the first time itself, it straight away went to the queue. 
let me get the grid log and will update here. 

In the log for the node, I saw “channel is inactive, closing the input pipe “ message though. 
will share detailed log soon

**Comment by pujagani** [comment]
It does go to the queue and gets picked up if there is a matching slot. Maybe there is a case where Safari slots are not registered with the Grid. The logs on Hub and Node side would be helpful. Thank you!
"channel is inactive, closing the input pipe " - This is a debug log from Netty client and mostly not a concern as far as I understand.

**Comment by diemol** [comment]
There is no need to declare a detailed toml configuration for Safari as Grid should pick it automatically. That most likely is an overhead.

**Comment by rohitsh1691** [comment]
facing the same issue and safardriver diagnose has no logs

04:38:27.105 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "0e7c60da1d709824a75668421bae9c79","eventTime": 1672268907101030083,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "101","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.6.0 (java mac)"}}

**Comment by rohitsh1691** [comment]
Facing the same issue with safari and hub showing 500 response code while connecting local.
Safari version 16.2
Grid version 4.7.2
Mode standalone

**Comment by pujagani** [comment]
Please share logs on Hub and Node when they are started and when the error occurs. We can only triage the issue if we have all the details and a way to reproduce it.

**Comment by rohitsh1691** [comment]
@pujagani

The remote driver is not working for the safari browser as working fine with the chrome browser. During a session with the grid, hub shows empty capabilities like {} and chrome shows all capabilities.

Selenium grid 4.7.2 is started locally in standalone mode.
Serenity-BDD version 3.5.1
Selenium Grid version - 4.7.2
Safari version - 16.2

The selenium starter sample code is also working for the safari with Selenium grid 4.7.2 and shows all capabilities of the safari.

Serenity properties file:
webdriver.driver=remote
webdriver.remote.driver=safari/chrome
webdriver.remote.os=MAC
webdriver.remote.url=http://localhost:4444/wd/hub

**Comment by diemol** [comment]
Do you have a way to reproduce this with Selenium, @rohitsh1691?

**Comment by rohitsh1691** [comment]
@diemol please try with the serenity-cucumber-starter project in local- https://github.com/serenity-bdd/serenity-cucumber-starter

**Comment by diemol** [comment]
Please share a script we can use that only has Selenium as a dependency, with that we can discard any issues in other dependencies.

**Comment by rohitsh1691** [comment]
@diemol I have downloaded the project from https://github.com/serenity-bdd/serenity-cucumber-starter and changed serenity.conf file (https://github.com/serenity-bdd/serenity-cucumber-starter/blob/master/src/test/resources/serenity.conf) with the following changes.

webdriver {
  driver=remote
  remote {
    url="http://localhost:4444"
    driver=safari
  }
}

started grid on localhost - 
java -jar selenium-server-4.7.2.jar standalone --host localhost --allow-cors true

The grid session tab will show the test execution is queued up and capabilities are empty {}. When we change the driver to chrome its works as.

webdriver {
  driver=remote
  remote {
    url="http://localhost:4444"
    driver=chrome
  }
}


If u are not able to replicate can we have a call

**Comment by krmahadevan** [comment]
@rohitsh1691 - I tried and I am not able to reproduce the problem.

1. Ensure that you have enabled automation by following instructions available [here](https://stackoverflow.com/a/63935098)
2. Started the standalone using the command `java -jar selenium-server-4.7.2.jar standalone`
3. Used a [configuration file](https://github.com/serenity-bdd/serenity-cucumber-starter/blob/master/src/test/resources/serenity.conf) that looks like below

```
serenity {
    take.screenshots = FOR_FAILURES
}

webdriver {
  driver = remote
  remote {
      url="http://localhost:4444"
      driver=safari
    }
  capabilities {
    browserName = "safari"
  }
}
```

The test case fails, but the browser opens up.

I think the problem in your case was because your capabilities in your example seems all empty

**Comment by rohitsh1691** [comment]
@krmahadevan its working after adding the capabilities of safari
capabilities {
    browserName = "safari"
  }
  
Thank you

**Comment by diemol** [comment]
Thanks for troubleshooting, @krmahadevan!
