### ISSUE TITLE
[🐛 Bug]: Reset Devtools selenium - java

### ISSUE THREAD

**Issue by Estefac10** [SeleniumHQ/selenium#11444]
### What happened?

I'm using devtools to retrieve a response and interact with a UI, on first use of devtools.addListener everything works, but when trying to add another listener elsewhere in the flow it just doesn't do anything.

For example, when one opens a new tab/window after calling devtools.addListener() once, it is impossible to get another response.

devTools -> devTools.addListener(Network.responseReceived(), responseReceived ->{}

### How can we reproduce the issue?

```shell
First call

WithDevTools.perform(
                        DevTools::createSession
                ),
                WithDevTools.perform(
                        devTools -> devTools.send(Network.enable(Optional.of(100000000), Optional.empty(), Optional.empty()))
                ),

                WithDevTools.perform(
                        devTools -> devTools.addListener(Network.responseReceived(), responseReceived -> {

                            if (responseReceived.getResponse().getStatus().equals(200) && responseReceived.getResponse().getUrl().contains(URL_SERVICE_OTP.getValor())){
                                System.out.print("First listener")

                                } 

                            }
                        }
                        )
                )

Second call 


WithDevTools.perform(
                        DevTools::createSession
                ),
                WithDevTools.perform(
                        devTools -> devTools.send(Network.enable(Optional.of(100000000), Optional.empty(), Optional.empty()))
                ),

                WithDevTools.perform(
                        devTools -> devTools.addListener(Network.responseReceived(), responseReceived -> {

                            if (responseReceived.getResponse().getStatus().equals(200) && responseReceived.getResponse().getUrl().contains(URL_SERVICE_PROSPECT.getValor())){
                                System.out.print("First listener")

                                } 

                            }
                        }
                        )
                )
```

### Relevant log output

```shell
Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 56361
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
dic. 19, 2022 3:15:55 P. M. org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
dic. 19, 2022 3:15:55 P. M. org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 108, so returning the closest version found: 104
dic. 19, 2022 3:15:55 P. M. org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 108 of 104
dic. 19, 2022 3:16:26 P. M. org.openqa.selenium.devtools.Connection$Listener lambda$onText$0
WARNING: Unable to process: {"method":"Network.responseReceived","params":{"requestId":"B25C92A11C35B57B1995D2D5D032F245","loaderId":"","timestamp":371010.547656,"type":"Preflight","response":{"url":"https://validar-identidad-lab.herokuapp.com/ms-validacion-identidad/otp/v2/sendPinNumber","status":200,"statusText":"OK","headers":{"Access-Control-Allow-Credentials":"true","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST","Access-Control-Allow-Origin":"https://ventaslab.suraenlinea.com","Access-Control-Max-Age":"1800","Connection":"keep-alive","Date":"Mon, 19 Dec 2022 20:16:26 GMT","Server":"Cowboy","Transfer-Encoding":"chunked","Vary":"Origin","Via":"1.1 vegur"},"mimeType":"","connectionReused":true,"connectionId":1606,"remoteIPAddress":"54.165.58.209","remotePort":443,"fromDiskCache":false,"fromServiceWorker":false,"fromPrefetchCache":false,"encodedDataLength":368,"timing":{"requestTime":371010.444402,"proxyStart":-1,"proxyEnd":-1,"dnsStart":-1,"dnsEnd":-1,"connectStart":-1,"connectEnd":-1,"sslStart":-1,"sslEnd":-1,"workerStart":-1,"workerReady":-1,"workerFetchStart":-1,"workerRespondWithSettled":-1,"sendStart":0.179,"sendEnd":0.392,"pushStart":0,"pushEnd":0,"receiveHeadersEnd":102.035},"responseTime":1.671480986776007e+12,"protocol":"http/1.1","alternateProtocolUsage":"unspecifiedReason","securityState":"secure","securityDetails":{"protocol":"TLS 1.2","keyExchange":"ECDHE_RSA","keyExchangeGroup":"P-256","cipher":"AES_128_GCM","certificateId":0,"subjectName":"*.herokuapp.com","sanList":["*.herokuapp.com"],"issuer":"Amazon","validFrom":1651449600,"validTo":1685577599,"signedCertificateTimestampList":[{"status":"Verified","origin":"Embedded in certificate","logDescription":"Google 'Xenon2023' log","logId":"ADF7BEFA7CFF10C88B9D3D9C1E3E186AB467295DCFB10C24CA858634EBDC828A","timestamp":1651468944110,"hashAlgorithm":"SHA-256","signatureAlgorithm":"ECDSA","signatureData":"3046022100E8CC023D4E9005CA0131AD980AADDDA1297AC4427783AB4F8648E2C44F6D7948022100F1B7B6E62C0000E2A227598F6EC09ED055E5DC489B41F3011E98DDEB0B6C1F44"},{"status":"Verified","origin":"Embedded in certificate","logDescription":"DigiCert Yeti2023 Log","logId":"35CF191BBFB16C57BF0FAD4C6D42CBBBB627202651EA3FE12AEFA803C33BD64C","timestamp":1651468944107,"hashAlgorithm":"SHA-256","signatureAlgorithm":"ECDSA","signatureData":"3045022100FE7B07BFAE32CF1E7E43A1B94A2E73870CF6E164B9888996656E333A4F9796C302204DD4FF5BBF4C80A2AC58EF2983C7F1DB4E155C505E139059A14EDE0B4677C4FF"},{"status":"Verified","origin":"Embedded in certificate","logDescription":"Let's Encrypt 'Oak2023' log","logId":"B73EFB24DF9C4DBA75F239C5BA58F46C5DFC42CF7A9F35C49E1D098125EDB499","timestamp":1651468944089,"hashAlgorithm":"SHA-256","signatureAlgorithm":"ECDSA","signatureData":"3046022100BAEF34FB84C58B2DE6DE9A6C80A189F066B6A48E300F76F32318DE7505FC7420022100C85CECB8B7DC38E0B018104251F2365277B8578716C80B2D04C3C0312571247D"}],"certificateTransparencyCompliance":"compliant","serverSignatureAlgorithm":1025,"encryptedClientHello":false}},"hasExtraInfo":true},"sessionId":"89A3387438D8AFCF6DC2D457F488235B"}
org.openqa.selenium.devtools.DevToolsException: {"id":6,"error":{"code":-32000,"message":"No resource with given identifier found"},"sessionId":"89A3387438D8AFCF6DC2D457F488235B"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'PSOFKA01049', ip: '192.168.1.22', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:159)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:74)
	at co.com.sura.suraenlinea.interactions.ObtenerRespuestaServicios.lambda$performAs$1(ObtenerRespuestaServicios.java:57)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:288)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:257)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.openqa.selenium.WebDriverException: {"id":6,"error":{"code":-32000,"message":"No resource with given identifier found"},"sessionId":"89A3387438D8AFCF6DC2D457F488235B"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'PSOFKA01049', ip: '192.168.1.22', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:234)
	... 5 more

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: {"id":6,"error":{"code":-32000,"message":"No resource with given identifier found"},"sessionId":"89A3387438D8AFCF6DC2D457F488235B"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'PSOFKA01049', ip: '192.168.1.22', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:202)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.openqa.selenium.devtools.DevToolsException: {"id":6,"error":{"code":-32000,"message":"No resource with given identifier found"},"sessionId":"89A3387438D8AFCF6DC2D457F488235B"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'PSOFKA01049', ip: '192.168.1.22', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:159)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:74)
	at co.com.sura.suraenlinea.interactions.ObtenerRespuestaServicios.lambda$performAs$1(ObtenerRespuestaServicios.java:57)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:288)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:257)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
	... 3 more
Caused by: org.openqa.selenium.WebDriverException: {"id":6,"error":{"code":-32000,"message":"No resource with given identifier found"},"sessionId":"89A3387438D8AFCF6DC2D457F488235B"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'PSOFKA01049', ip: '192.168.1.22', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:234)
	... 5 more


Sometimes console print a WebSocketException
```

### Operating System

Windows 10

### Selenium version

Java 17, , Serenity 3.3.2

### What are the browser(s) and version(s) where you see this issue?

Webdriver manager serenity (chrome)

### What are the browser driver(s) and version(s) where you see this issue?

Webdriver manager serenity  (chrome)

**Comment by diemol** [comment]
Have you tried to create a `devTools` session for the new tab by passing the window handle?

**Comment by Estefac10** [comment]
> Have you tried to create a `devTools` session for the new tab by passing the window handle?

@diemol 
Yes, use this statement in both classes and nothing happens

WithDevTools.perform(
                        devTools -> devTools.createSession(Serenity.getDriver().getWindowHandle())
                )

**Comment by pujagani** [comment]
Thank you for the details. I tried to reproduce this issue based on the description and it flow of code works as expected. 

I have used the code below: 
```

import org.openqa.selenium.By;
import org.openqa.selenium.WindowType;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.DevTools;
import org.openqa.selenium.devtools.v108.log.Log;
import org.openqa.selenium.devtools.v108.runtime.Runtime;

public class MultipleCDPListeners {
    public static void main(String args[]) throws InterruptedException {
        ChromeDriver driver = new ChromeDriver();
        DevTools devTools = driver.getDevTools();
        devTools.createSession();
        devTools.send(Log.enable());
        devTools.send(Runtime.enable());
        addConsoleLogListener(devTools, 1);

        driver.get("https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html");
        driver.findElement(By.id("consoleLog")).click();

        String originalWindowHandle = driver.getWindowHandle();

        Thread.sleep(5000);

        String windowHandle = driver.switchTo().newWindow(WindowType.TAB).getWindowHandle();

        devTools.createSession(windowHandle);
        devTools.send(Log.enable());
        devTools.send(Runtime.enable());
        addConsoleLogListener(devTools, 2);

        driver.get("https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html");
        driver.findElement(By.id("consoleLog")).click();

        Thread.sleep(5000);

        addConsoleLogListener(devTools, 3);
        driver.get("https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html");
        driver.findElement(By.id("consoleLog")).click();
    }

    public static void addConsoleLogListener(DevTools devTools, int number) {
        devTools.addListener(Log.entryAdded(),
                logEntry -> {
                    final String log = "listener: " + number + " [console.log] " + logEntry.getText();
                    System.out.println(log);
                });

        devTools.addListener(Runtime.consoleAPICalled(),
                logEntry -> {
                    final String log = "listener: " + number + " [console.log] " + logEntry.getTimestamp();
                    System.out.println(log);
                });
    }

}
```

The resulting output is: 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 30086
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
listener: 1 [console.log] Failed to load resource: the server responded with a status of 404 ()
listener: 1 [console.log] 1.671625981596598E12
listener: 2 [console.log] 1.671625986779612E12
listener: 1 [console.log] 1.671625986779612E12
listener: 2 [console.log] 1.671625991864069E12
listener: 1 [console.log] 1.671625991864069E12
listener: 3 [console.log] 1.671625991864069E12
```
I am printing the timestamp so it is easier to identify the listeners called. This indicates that all registered listeners are called at each step. I was unable to reproduce the error you are facing. I do see an exception when `driver.quit(`) is called and Selenium is trying to close the devtools connection (I will triage it further) but the flow of the code is not interrupted.
Feel free try the code snippet above and provide feedback if you face the error.
Please provide a reproducible test code/snippet pertaining to your use case also to help us triage the issue. Thank you!

**Comment by Estefac10** [comment]
Muchas gracias, era un problema en la versión del devtools, se estaba utilizando la versión 103 y al cambiarlo por una versión superior (104 - version superior implementada por serenity) funciona

**Comment by Estefac10** [comment]
Thank you very much, it was a problem in the devtools version, I was using version 103 and when I changed it to a higher version (104 - higher version implemented by serenity) it works.
