### ISSUE TITLE
[🐛 Bug]: Not able to Perform Drag and Drop using Actions Class

### ISSUE THREAD

**Issue by shashikumarcd** [SeleniumHQ/selenium#11452]
### What happened?

I'm try to use Actions class to perform drag and drop, But it's able to ClickAndHold(sourceElement), but not able to movetoElement(Dest) and release

Any help will be appriciated

### How can we reproduce the issue?

```shell
Here is the code which i have tried
Source HTML :
<span _ngcontent-mdi-c367="" id="tagNode1" draggable="true" class="ng-star-inserted"><span _ngcontent-mdi-c367="" class="grab-pointer">Tag1</span><span _ngcontent-mdi-c367="" class="tag-data-type ng-star-inserted">DT_INT16</span><!----></span>

Destination HTML :
<span _ngcontent-mdi-c366="" class="text"><span _ngcontent-mdi-c366="" aria-hidden="true" class="iconMdsp bold icon-spacing asset"></span><span _ngcontent-mdi-c366="" class="text-wrap-asset-name ng-star-inserted"> New Asset22 </span><!----><!----></span>

Selenium C# :

IWebElement source1 = _driver.FindElement(By.CssSelector("span#tagNode1"));
IWebElement sourceChild = _driver.FindElement(By.CssSelector("span.grab-pointer"));              
IWebElement dest = _driver.FindElement(By.CssSelector("span.text>span.text-wrap-asset-name"));

Option1:
Actions action = new Actions(driver);
action.ClickAndHold(source)
.MoveToElement(dest)
.Release(dest).Build().Perform();   

Option2:
Actions action = new Actions(driver);
action.ClickAndHold(source)
.MoveToElement(sourceChild)
.Release(dest).Build().Perform();    

Options3:
Actions action = new Actions(driver);            
action.DragAndDropToOffset(source, 297, 22)
.Build().Perform(); 

Option4:
Actions action = new Actions(driver);
action.DragAndDrop(source, dest);
action.Perform();

Option5: 
int x = source.Location.X;
int y = source.Location.Y;
Actions action = new Actions(driver);
action.MoveToElement(source)               
.ClickAndHold(source)                
.MoveByOffset(x, y)
.MoveToElement(dest)
.MoveByOffset(x, y)                
.Release().Build().Perform(); 

None of the above methods are worked
```

### Relevant log output

```shell
Option 1 and 2 will throwing an exception as below

  at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.PerformActions(IList`1 actionSequenceList)
   at OpenQA.Selenium.Interactions.Actions.Perform()
   at Classname.UI.Helper.DragAndDrop(IWebDriver driver, IWebElement source, IWebElement dest)
```

### Operating System

Windows10

### Selenium version

Selenium WebDriver 4.1.0 with C#

### What are the browser(s) and version(s) where you see this issue?

Chrome Version - 108.0.5359.125

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver - 108.0.5359.125

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
This is a known issue in the drivers right now. None of them seem to be able to get this to work, unfortunately.

https://github.com/SeleniumHQ/selenium/issues/10601

**Comment by nekdan** [comment]
> Это известная проблема в драйверах прямо сейчас. Никто из них, к сожалению, не может заставить это работать.
> 
> #10601

Hi I have a similar problem in selenium + python. Does this problem have a solution? I found js scripts as an alternative [rcorreia/drag_and_drop_helper.js](https://gist.github.com/rcorreia/2362544), but they do not work, apparently because they are outdated, since they have been since 2016.
