### ISSUE TITLE
[🐛 Bug]: Can't Change form data in a POST request by Fetch.requestPaused and Fetch.contiunPaused in devtools

### ISSUE THREAD

**Issue by ImJongHwan** [SeleniumHQ/selenium#11479]
### What happened?

I want to check the DOM after changing form data in a POST request that was occurred as XHR.
So I intercepted the POST request with Fetch.requestPaused and changed the form data. And I sent a POST request with Fetch.continueRequest.
However, the request could not be sent because a DevToolsException was thrown.

I tried to change the form data of the POST request several times but failed.

I tested by a BenchmarkTest00036 in OWASP Benchmark v1.2

` 

        DevTools devTools = driver.getDevTools();
        devTools.createSession();

        devTools.send(Fetch.enable(Optional.empty(), Optional.empty()));

        long start = System.currentTimeMillis();
        devTools.addListener(Fetch.requestPaused(), (r) -> {
            if (r.getResourceType().equals(ResourceType.XHR)) {
                devTools.send(Fetch.continueRequest(r.getRequestId(), Optional.empty(), Optional.empty(), 
                        Optional.of("vectorArea=&answer=&vector=SafeText%2F%2F--%3E%3C%2FSCRIPT%3E%5C%22%3E'%3Ea1s2d3f4g5%3CsCrIpT%3Ewindow.open('about%3Ablank'%2C'1398712525')%3B%3C%2FScRiPt%3Ea1s2d3f4g5&SafeText%2F%2F--%3E%3C%2FSCRIPT%3E%5C%22%3E'%3Ea1s2d3f4g5%3CsCrIpT%3Ewindow.open('about%3Ablank'%2C'1398712525')%3B%3C%2FScRiPt%3Ea1s2d3f4g5=vector"),
                        Optional.empty(), Optional.empty()));
            } else {
                devTools.send(Fetch.continueRequest(r.getRequestId(),
                        Optional.empty(), Optional.empty(),
                        Optional.empty(), Optional.empty(), Optional.empty()));
            }
        });

        driver.get("http://dastapp.fasoo.com:8080/benchmark/BenchmarkTest00036.html?vector=SafeText");
        driver.findElement(By.xpath("//*[@id=\"login-btn\"]")).click();
        System.out.println(driver.getPageSource());
        devTools.clearListeners();
        System.out.println(System.currentTimeMillis() - start + " ms");
`

### How can we reproduce the issue?

```shell
1. Finds an element that causes a POST request with the application/x-www-form-urlencoded content type.
2. Intercept the POST request with Fetch.requestPaused.
3. Change the form data.
4. Sent the POST request with Fetch.continueRequest.
5. Check this error.
```

### Relevant log output

```shell
Starting ChromeDriver 103.0.5060.134 (8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}) on port 50741
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
12월 26, 2022 9:55:54 오전 org.openqa.selenium.remote.ProtocolHandshake createSession
정보: Detected upstream dialect: W3C
12월 26, 2022 9:55:54 오전 org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
정보: Found exact CDP implementation for version 103
12월 26, 2022 9:56:01 오전 org.openqa.selenium.devtools.Connection$Listener lambda$onText$0
경고: Unable to process: {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-4.0","request":{"url":"http://dastapp.fasoo.com:8080/benchmark/BenchmarkTest00036","method":"POST","headers":{"Accept":"*/*","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8","Referer":"http://dastapp.fasoo.com:8080/benchmark/BenchmarkTest00036.html?vector=SafeText","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/103.0.5060.134 Safari/537.36","X-Requested-With":"XMLHttpRequest"},"postData":"vectorArea=&answer=&vector=SafeText&SafeText=vector","hasPostData":true,"postDataEntries":[{"bytes":"dmVjdG9yQXJlYT0mYW5zd2VyPSZ2ZWN0b3I9U2FmZVRleHQmU2FmZVRleHQ9dmVjdG9y"}],"initialPriority":"High","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"B8873EDFA460402983FF13E41A3C2776","resourceType":"XHR"},"sessionId":"F3F267527308E782FB5C0AFBC38CC19E"}
org.openqa.selenium.devtools.DevToolsException: {"id":9,"error":{"code":-32602,"message":"Invalid parameters","data":"Failed to deserialize params.postData - BINDINGS: invalid base64 string at position 47"},"sessionId":"F3F267527308E782FB5C0AFBC38CC19E"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'SP0024B', ip: '192.168.10.67', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:159)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:74)
	at com.sparrow.dast.lab.test.FetchRequestChange.lambda$innerTest$0(FetchRequestChange.java:35)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:288)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:257)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openqa.selenium.WebDriverException: {"id":9,"error":{"code":-32602,"message":"Invalid parameters","data":"Failed to deserialize params.postData - BINDINGS: invalid base64 string at position 47"},"sessionId":"F3F267527308E782FB5C0AFBC38CC19E"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'SP0024B', ip: '192.168.10.67', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:234)
	... 5 more

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: {"id":9,"error":{"code":-32602,"message":"Invalid parameters","data":"Failed to deserialize params.postData - BINDINGS: invalid base64 string at position 47"},"sessionId":"F3F267527308E782FB5C0AFBC38CC19E"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'SP0024B', ip: '192.168.10.67', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:202)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openqa.selenium.devtools.DevToolsException: {"id":9,"error":{"code":-32602,"message":"Invalid parameters","data":"Failed to deserialize params.postData - BINDINGS: invalid base64 string at position 47"},"sessionId":"F3F267527308E782FB5C0AFBC38CC19E"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'SP0024B', ip: '192.168.10.67', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:159)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:74)
	at com.sparrow.dast.lab.test.FetchRequestChange.lambda$innerTest$0(FetchRequestChange.java:35)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:288)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:257)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
	... 3 more
Caused by: org.openqa.selenium.WebDriverException: {"id":9,"error":{"code":-32602,"message":"Invalid parameters","data":"Failed to deserialize params.postData - BINDINGS: invalid base64 string at position 47"},"sessionId":"F3F267527308E782FB5C0AFBC38CC19E"}
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'SP0024B', ip: '192.168.10.67', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:234)
	... 5 more
```

### Operating System

Windows 10 Pro 21H2

### Selenium version

Java 1.8

### What are the browser(s) and version(s) where you see this issue?

Chrome 103

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 103.0.5060.134 (8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262})

### Are you using Selenium Grid?

selenium java 4.4.0

**Comment by pujagani** [comment]
Thank you for sharing the details. The error you are receiving is from the CDP protocol and not from Selenium's end. Selenium is just wrapping the error received and throwing the exception to communicate it further to the user. Seems like there is an issue with the data being sent, please double-check on your end to fix it and resolve the error. Please look into https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-continueRequest to ensure all parameters are encoded as needed by the protocol.
