### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by murilonerdx** [SeleniumHQ/selenium#11490]
### What happened?

I did the whole creation process to use Selenium but without success I already downloaded several dependencies and resources but nothing solves it, it works normally running through IntelliJ but when I generate a .jar of it it explodes this problem.

```java
 Properties props = getProp();
                    WebDriver browser = new ChromeDriver();
                    browser.navigate().to(props.getProperty("root.properties.ip") + "/login.asp");

                    browser.findElement(By.id("txtUser")).sendKeys(props.getProperty("root.properties.admin"));
                    browser.findElement(By.id("txtPass")).sendKeys(props.getProperty("root.properties.password"));

                    browser.findElement(By.id("btnLogin")).click();
                    browser.navigate().to(props.getProperty("root.properties.navigate"));
                    browser.findElement(By.id("btn-clicktocall")).click();
                    browser.navigate().to(props.getProperty("root.properties.ip") + "/popup-reboot.asp");
                    browser.findElement(By.id("btnaAccept")).click();
                    browser.close();
                    browser.quit();
                    break;
```

### How can we reproduce the issue?

```shell
<dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>ru.yandex.qatools.ashot</groupId>
      <artifactId>ashot</artifactId>
      <version>1.5.4</version>
    </dependency>
    <dependency>
      <groupId>io.qameta.allure</groupId>
      <artifactId>allure-testng</artifactId>
      <version>2.13.1</version>
    </dependency>
    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>6.11</version>
    </dependency>
    <dependency>
      <groupId>velocity</groupId>
      <artifactId>velocity</artifactId>
      <version>1.5</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>${selenium.version}</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-firefox-driver</artifactId>
      <version>${selenium.version}</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-chrome-driver</artifactId>
      <version>${selenium.version}</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-safari-driver</artifactId>
      <version>${selenium.version}</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-remote-driver</artifactId>
      <version>${selenium.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.bonigarcia</groupId>
      <artifactId>webdrivermanager</artifactId>
      <version>5.3.1</version>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>31.1-jre</version>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.10</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/commons-logging/commons-logging -->
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>1.2</version>
    </dependency>

  </dependencies>
```

### Relevant log output

```shell
java -jar server-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/WebDriver
        at org.example.RemoteAccessServerOpen.main(RemoteAccessServerOpen.java:25)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.WebDriver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more
```

### Operating System

Windows 10 64x

### Selenium version

Java 11+

### What are the browser(s) and version(s) where you see this issue?

ChromeDriver 109.0.5414.25

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 109.0.5414.25

**Comment by titusfortner** [comment]
How to execute a Selenium script within a jar is a question you'll need to ask elsewhere. Perhaps you are not including *all of the dependencies found in the Java zip download here -  https://www.selenium.dev/downloads/#bindings (including those in lib directory).
