### ISSUE TITLE
[🐛 Bug]: TruffleRuby 22.3 fails on CI on the installing dependencies step

### ISSUE THREAD

**Issue by andrykonchin** [SeleniumHQ/selenium#11506]
### What happened?

Hi, just wanted to let you know that TruffleRuby CI jobs are failing on CI on the installing dependencies step. It started to fail on Jan 2.

Example of a failed job - https://github.com/SeleniumHQ/selenium/actions/runs/3828372836/jobs/6513895974

### How can we reproduce the issue?

```shell
The first CI build with failed TruffleRuby job (Jan 2) - https://github.com/SeleniumHQ/selenium/actions/runs/3821613565
The last CI build without TruffleRuby related issue (Jan 1) - https://github.com/SeleniumHQ/selenium/actions/runs/3818804362

The TruffleRuby related job is "unit-test (truffleruby-22.3.0, ubuntu-latest)"
```

### Relevant log output

```shell
/tmp/bazel/external/rules_ruby_dist/dist/lib/mri/bundler/definition.rb:502:in `materialize': Could not find pry-0.14.1, rack-2.2.4, rspec-3.12.0, rubocop-1.40.0, rubocop-performance-1.15.1, rubocop-rspec-2.15.0, webmock-3.18.1, webrick-1.7.0, yard-0.9.28, rubyzip-2.3.2, websocket-1.2.9, coderay-1.1.3, method_source-1.0.0, rspec-core-3.12.0, rspec-expectations-3.12.0, rspec-mocks-3.12.1, json-2.6.3, parallel-1.22.1, parser-3.1.3.0, rainbow-3.1.1, regexp_parser-2.6.1, rubocop-ast-1.24.0, ruby-progressbar-1.11.0, unicode-display_width-2.3.0, addressable-2.8.1, crack-0.4.5, hashdiff-1.0.1, rspec-support-3.12.0, diff-lcs-1.5.0, ast-2.4.2, public_suffix-5.0.1 in any of the sources (Bundler::GemNotFound)
	from /tmp/bazel/external/rules_ruby_dist/dist/lib/mri/bundler/definition.rb:189:in `specs'
```

### Operating System

Ubuntu

### Selenium version

master

### What are the browser(s) and version(s) where you see this issue?

headless

### What are the browser driver(s) and version(s) where you see this issue?

headless

**Comment by titusfortner** [comment]
Yeah, it coincides with the update of the bazel ruby rules to support ruby 3.2. I already brought it up with @p0deje

**Comment by titusfortner** [comment]
Passing now - https://github.com/SeleniumHQ/selenium/actions/runs/3830444104

**Comment by andrykonchin** [comment]
Thank you!
