### ISSUE TITLE
Restarting Marionette session with Remote WebDriver

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#1150]
For some reason the Remote WebDriver implementation for Marionette isn't letting me start a new session after ending a previous one.

I can verify the wires binary is started. It seems like I might be getting the error before the binary loads, but I can't tell for sure.

This code does work when I run directly through the Ruby code.

```
-> DELETE session/01f3b40f-f5ba-4673-b45e-4ad847ef52b2
<- {"status":0,"sessionId":"01f3b40f-f5ba-4673-b45e-4ad847ef52b2","state":"success","value":null,"class":"org.openqa.selenium.remote.Response","hCode":1610282042}

-> POST session
   >>> http://127.0.0.1:4444/wd/hub/session | {"desiredCapabilities":{"browserName":"firefox","browserVersion":"any","platformName":"any","platformVersion":"any","acceptSslCerts":false,"takesScreenshot":false,"takesElementScreenshot":false,"pageLoadStrategy":"normal","marionette":true}}
     > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"241"}
<- {"status":13,"sessionId":null,"state":"unhandled error","value":{"message":"Connection refused","suppressed":[],"localizedMessage":"Connection refused","cause":null,"class":"java.net.ConnectException","hCode":544287636,"stackTrace":
```

**Comment by titusfortner** [comment]
@barancev - Can you check into this? Having to restart the java server in order to restart a browser makes Marionette mostly unusable via remote.

**Comment by titusfortner** [comment]
I'm not sure if this is the same issue or similar, but when I have an existing session, and I try to start a new one (selenium-server-standalone v2.52 & Firefox 45). Since I can do this just fine directly, it is an issue with the server.

Firefox Driver:
```
-> POST session
   >>> http://127.0.0.1:4447/wd/hub/session | {"desiredCapabilities":{"browserName":"firefox","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false}}
<- {"state":null,"sessionId":"7f7efb2f-50e5-42a3-81f2-1400806dc131","hCode":1937525575,"value":{"applicationCacheEnabled":true,"rotatable":false,"handlesAlerts":true,"databaseEnabled":true,"version":"45.0","platform":"MAC","nativeEvents":false,"acceptSslCerts":true,"webdriver.remote.sessionid":"7f7efb2f-50e5-42a3-81f2-1400806dc131","webStorageEnabled":true,"locationContextEnabled":true,"browserName":"firefox","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true},"class":"org.openqa.selenium.remote.Response","status":0}
```
Marionette Driver:
```
-> POST session
   >>> http://127.0.0.1:4444/wd/hub/session | {"desiredCapabilities":{"browserName":"firefox","browserVersion":null,"platformName":null,"platformVersion":"any","acceptSslCerts":false,"takesScreenshot":false,"takesElementScreenshot":false,"pageLoadStrategy":"normal","marionette":true}}
<- {"state":"unhandled error","sessionId":null,"hCode":232727648,"value":{"localizedMessage":"Connection refused","cause":null,"stackTrace":[{"fileName":"PlainSocketImpl.java","nativeMethod":true,"methodName":"socketConnect","className":"java.net.PlainSocketImpl","hCode":1566792002,"lineNumber":-2,"class":"java.lang.StackTraceElement"},{"fileName":"AbstractPlainSocketImpl.java","nativeMethod":false,"methodName":"doConnect","className":"java.net.AbstractPlainSocketImpl","hCode":495250506,"lineNumber":350,"class":"java.lang.StackTraceElement"},{"fileName":"AbstractPlainSocketImpl.java","nativeMethod":false,"methodName":"connectToAddress","className":"java.net.AbstractPlainSocketImpl","hCode":-2104362742,"lineNumber":206,"class":"java.lang.StackTraceElement"},{"fileName":"AbstractPlainSocketImpl.java","nativeMethod":false,"methodName":"connect","className":"java.net.AbstractPlainSocketImpl","hCode":-1864045581,"lineNumber":188,"class":"java.lang.StackTraceElement"},{"fileName":"SocksSocketImpl.java","nativeMethod":false,"methodName":"connect","className":"java.net.SocksSocketImpl","hCode":1780853535,"lineNumber":392,"class":"java.lang.StackTraceElement"},{"fileName":"Socket.java","nativeMethod":false,"methodName":"connect","className":"java.net.Socket","hCode":1700005482,"lineNumber":589,"class":"java.lang.StackTraceElement"},{"fileName":"PlainConnectionSocketFactory.java","nativeMethod":false,"methodName":"connectSocket","className":"org.apache.http.conn.socket.PlainConnectionSocketFactory","hCode":1175278798,"lineNumber":74,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultHttpClientConnectionOperator.java","nativeMethod":false,"methodName":"connect","className":"org.apache.http.impl.conn.DefaultHttpClientConnectionOperator","hCode":-502593948,"lineNumber":134,"class":"java.lang.StackTraceElement"},{"fileName":"PoolingHttpClientConnectionManager.java","nativeMethod":false,"methodName":"connect","className":"org.apache.http.impl.conn.PoolingHttpClientConnectionManager","hCode":-1370960713,"lineNumber":353,"class":"java.lang.StackTraceElement"},{"fileName":"MainClientExec.java","nativeMethod":false,"methodName":"establishRoute","className":"org.apache.http.impl.execchain.MainClientExec","hCode":848422720,"lineNumber":380,"class":"java.lang.StackTraceElement"},{"fileName":"MainClientExec.java","nativeMethod":false,"methodName":"execute","className":"org.apache.http.impl.execchain.MainClientExec","hCode":1688513621,"lineNumber":236,"class":"java.lang.StackTraceElement"},{"fileName":"ProtocolExec.java","nativeMethod":false,"methodName":"execute","className":"org.apache.http.impl.execchain.ProtocolExec","hCode":-642149983,"lineNumber":184,"class":"java.lang.StackTraceElement"},{"fileName":"RetryExec.java","nativeMethod":false,"methodName":"execute","className":"org.apache.http.impl.execchain.RetryExec","hCode":2007799545,"lineNumber":88,"class":"java.lang.StackTraceElement"},{"fileName":"RedirectExec.java","nativeMethod":false,"methodName":"execute","className":"org.apache.http.impl.execchain.RedirectExec","hCode":608278487,"lineNumber":110,"class":"java.lang.StackTraceElement"},{"fileName":"InternalHttpClient.java","nativeMethod":false,"methodName":"doExecute","className":"org.apache.http.impl.client.InternalHttpClient","hCode":2023045549,"lineNumber":184,"class":"java.lang.StackTraceElement"},{"fileName":"CloseableHttpClient.java","nativeMethod":false,"methodName":"execute","className":"org.apache.http.impl.client.CloseableHttpClient","hCode":1628029009,"lineNumber":71,"class":"java.lang.StackTraceElement"},{"fileName":"CloseableHttpClient.java","nativeMethod":false,"methodName":"execute","className":"org.apache.http.impl.client.CloseableHttpClient","hCode":1628028993,"lineNumber":55,"class":"java.lang.StackTraceElement"},{"fileName":"ApacheHttpClient.java","nativeMethod":false,"methodName":"fallBackExecute","className":"org.openqa.selenium.remote.internal.ApacheHttpClient","hCode":652052260,"lineNumber":144,"class":"java.lang.StackTraceElement"},{"fileName":"ApacheHttpClient.java","nativeMethod":false,"methodName":"execute","className":"org.openqa.selenium.remote.internal.ApacheHttpClient","hCode":-904183856,"lineNumber":90,"class":"java.lang.StackTraceElement"},{"fileName":"HttpCommandExecutor.java","nativeMethod":false,"methodName":"execute","className":"org.openqa.selenium.remote.HttpCommandExecutor","hCode":-1852790187,"lineNumber":142,"class":"java.lang.StackTraceElement"},{"fileName":"DriverCommandExecutor.java","nativeMethod":false,"methodName":"execute","className":"org.openqa.selenium.remote.service.DriverCommandExecutor","hCode":-633333582,"lineNumber":82,"class":"java.lang.StackTraceElement"},{"fileName":"RemoteWebDriver.java","nativeMethod":false,"methodName":"execute","className":"org.openqa.selenium.remote.RemoteWebDriver","hCode":1767885131,"lineNumber":644,"class":"java.lang.StackTraceElement"},{"fileName":"RemoteWebDriver.java","nativeMethod":false,"methodName":"startSession","className":"org.openqa.selenium.remote.RemoteWebDriver","hCode":-1182648225,"lineNumber":249,"class":"java.lang.StackTraceElement"},{"fileName":"RemoteWebDriver.java","nativeMethod":false,"methodName":"startSession","className":"org.openqa.selenium.remote.RemoteWebDriver","hCode":-1182648240,"lineNumber":234,"class":"java.lang.StackTraceElement"},{"fileName":"MarionetteDriver.java","nativeMethod":false,"methodName":"run","className":"org.openqa.selenium.firefox.MarionetteDriver","hCode":838782575,"lineNumber":79,"class":"java.lang.StackTraceElement"},{"fileName":"MarionetteDriver.java","nativeMethod":false,"methodName":"<init>","className":"org.openqa.selenium.firefox.MarionetteDriver","hCode":-127354736,"lineNumber":73,"class":"java.lang.StackTraceElement"},{"fileName":"MarionetteDriver.java","nativeMethod":false,"methodName":"<init>","className":"org.openqa.selenium.firefox.MarionetteDriver","hCode":-127354760,"lineNumber":49,"class":"java.lang.StackTraceElement"},{"fileName":"NativeConstructorAccessorImpl.java","nativeMethod":true,"methodName":"newInstance0","className":"sun.reflect.NativeConstructorAccessorImpl","hCode":-917798116,"lineNumber":-2,"class":"java.lang.StackTraceElement"},{"fileName":"NativeConstructorAccessorImpl.java","nativeMethod":false,"methodName":"newInstance","className":"sun.reflect.NativeConstructorAccessorImpl","hCode":-1864225098,"lineNumber":62,"class":"java.lang.StackTraceElement"},{"fileName":"DelegatingConstructorAccessorImpl.java","nativeMethod":false,"methodName":"newInstance","className":"sun.reflect.DelegatingConstructorAccessorImpl","hCode":-2122307259,"lineNumber":45,"class":"java.lang.StackTraceElement"},{"fileName":"Constructor.java","nativeMethod":false,"methodName":"newInstance","className":"java.lang.reflect.Constructor","hCode":-1319859920,"lineNumber":422,"class":"java.lang.StackTraceElement"},{"fileName":"FirefoxDriverProvider.java","nativeMethod":false,"methodName":"callConstructor","className":"org.openqa.selenium.remote.server.FirefoxDriverProvider","hCode":380089712,"lineNumber":91,"class":"java.lang.StackTraceElement"},{"fileName":"FirefoxDriverProvider.java","nativeMethod":false,"methodName":"newInstance","className":"org.openqa.selenium.remote.server.FirefoxDriverProvider","hCode":-616843600,"lineNumber":66,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultDriverFactory.java","nativeMethod":false,"methodName":"newInstance","className":"org.openqa.selenium.remote.server.DefaultDriverFactory","hCode":-1365021416,"lineNumber":60,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultSession.java","nativeMethod":false,"methodName":"call","className":"org.openqa.selenium.remote.server.DefaultSession$BrowserCreator","hCode":2056168471,"lineNumber":222,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultSession.java","nativeMethod":false,"methodName":"call","className":"org.openqa.selenium.remote.server.DefaultSession$BrowserCreator","hCode":2056168250,"lineNumber":1,"class":"java.lang.StackTraceElement"},{"fileName":"FutureTask.java","nativeMethod":false,"methodName":"run","className":"java.util.concurrent.FutureTask","hCode":-820313554,"lineNumber":266,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultSession.java","nativeMethod":false,"methodName":"run","className":"org.openqa.selenium.remote.server.DefaultSession$1","hCode":-255143467,"lineNumber":176,"class":"java.lang.StackTraceElement"},{"fileName":"ThreadPoolExecutor.java","nativeMethod":false,"methodName":"runWorker","className":"java.util.concurrent.ThreadPoolExecutor","hCode":-1285150184,"lineNumber":1142,"class":"java.lang.StackTraceElement"},{"fileName":"ThreadPoolExecutor.java","nativeMethod":false,"methodName":"run","className":"java.util.concurrent.ThreadPoolExecutor$Worker","hCode":-242190645,"lineNumber":617,"class":"java.lang.StackTraceElement"},{"fileName":"Thread.java","nativeMethod":false,"methodName":"run","className":"java.lang.Thread","hCode":-82946320,"lineNumber":745,"class":"java.lang.StackTraceElement"}],"suppressed":[],"message":"Connection refused","hCode":1213895969,"class":"java.net.ConnectException","screen":null},"class":"org.openqa.selenium.remote.Response","status":13}
```

**Comment by schmidtkp** [comment]
Not sure if this is related, but seems like it maybe...

I'm getting a "org.openqa.selenium.WebDriverException: Connection refused” (full stack trace below) attempting to use the Marionette Driver (via RemoteWebDriver) in Java.

Config Info -
OS:			Mac OSX 10.11.4
Selenium:		v2.53.0
Marionette/Wires:	v0.6.2

Note: Both hub/node processes are running on same host for this exercise (works fine for ChromeDriver, IEDriverServer and normal FirefixDriver).

I believe I've properly deployed marionette binary and set system property correctly.  I see the process running after starting the Selenium node:

1248187572 5080 4937 0 7:18AM ?? 0:00.01 /private/var/folders/99/kx9d7lpx7s5258rq49tpgs1s56bn5m/T/marionettedriver_mac --webdriver-port=35910 -b /Applications/Firefox.app/Contents/MacOS/firefox-bin

Note:
- I renamed the Marionette Driver from "wires" to "marionettedriver_mac"
- I get multiple processes running from each attempt.  I kill -9 the process after each attempt.

Here is how I instantiate the RemoteWebDriver -

capabilities = DesiredCapabilities.firefox();
	other capabilities ...
capabilities.setCapability("marionette", true);
webDriver = new RemoteWebDriver(url, capabilities);

Full stack trace -
org.openqa.selenium.WebDriverException: Connection refused
Command duration or timeout: 3.94 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.7.0_79'
Caused by: java.net.ConnectException: Connection refused
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:579)
at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:234)
at org.openqa.selenium.firefox.MarionetteDriver.run(MarionetteDriver.java:79)
at org.openqa.selenium.firefox.MarionetteDriver.<init>(MarionetteDriver.java:73)
at org.openqa.selenium.firefox.MarionetteDriver.<init>(MarionetteDriver.java:49)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:66)
at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)

**Comment by davehunt** [comment]
This may be related to https://github.com/mozilla/geckodriver/issues/58

**Comment by barancev** [comment]
Is this issue still actual?
