### ISSUE TITLE
[🐛 Bug]: Selenium 4 script times out after 3 minute

### ISSUE THREAD

**Issue by BilalKamran** [SeleniumHQ/selenium#11505]
### What happened?

We upgraded from Selenium 3 to Selenium 4. Selenium 3 allowed us to have a max script timeout of 30 min, but since upgrading to Selenium 4.x.x, Even if we explicitly set the timeout more than 3 minutes, it does not allow it, and after 3 minutes, the following exception occurs:

Error Stacktrace: 

`org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-56-generic', java.version: '13.0.13'
Driver info: com.intelliagent.executionEngine.core.IntelliAgentChromeDriver
Command: [022e1e27c8f2626a86e88259c55bbd8d, executeScript {script=return await window.waitForSomeSeconds();, args=[]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.98, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.jaSsAo}, goog:chromeOptions: {debuggerAddress: localhost:44941}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:44941/devtoo..., se:cdpVersion: 108.0.5359.98, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 022e1e27c8f2626a86e88259c55bbd8d
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:472)
	at com..executionEngine.commands.JavaScriptCommand.execute(JavaScriptCommand.java:69)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1957)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2092)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 17 more`

### How can we reproduce the issue?

```shell
ChromeDriver webDriver = new ChromeDriver();

webDriver.manage().timeouts().setScriptTimeout(190l, TimeUnit.SECONDS);

((JavascriptExecutor) webDriver).executeScript("function timeout(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }; const printFunction = async () => { await timeout(190000); return "bla bla" }; await printFunction();");

//above code run for 3 min and 10 sec
```

### Relevant log output

```shell
Error Stacktrace: 

`org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-56-generic', java.version: '13.0.13'
Driver info: com.intelliagent.executionEngine.core.IntelliAgentChromeDriver
Command: [022e1e27c8f2626a86e88259c55bbd8d, executeScript {script=return await window.waitForSomeSeconds();, args=[]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.98, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.jaSsAo}, goog:chromeOptions: {debuggerAddress: localhost:44941}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:44941/devtoo..., se:cdpVersion: 108.0.5359.98, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 022e1e27c8f2626a86e88259c55bbd8d
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:472)
	at com..executionEngine.commands.JavaScriptCommand.execute(JavaScriptCommand.java:69)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1957)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2092)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 17 more`
```

### Operating System

Linux and Windows

### Selenium version

4.1.2, 4.7.2, basically all 4.x.x

### What are the browser(s) and version(s) where you see this issue?

108.0.5359.98, basically all versions

### What are the browser driver(s) and version(s) where you see this issue?

108, basically all versions

### Are you using Selenium Grid?

no

**Comment by pujagani** [comment]
This might be happening due to the default read timeout value of 3 minutes for the Netty HTTP client that Selenium 4 uses. I am not sure what the solution for it is though for local drivers. I will look into it and revert back.

**Comment by krmahadevan** [comment]
@pujagani - Maybe we could consider adding an overloaded constructor to the `org.openqa.selenium.remote.HttpCommandExecutor` sub-classes, such that it can call into `org.openqa.selenium.remote.HttpCommandExecutor#HttpCommandExecutor(java.util.Map<java.lang.String,org.openqa.selenium.remote.CommandInfo>, org.openqa.selenium.remote.http.ClientConfig, org.openqa.selenium.remote.http.HttpClient.Factory)` and be able to set the client timeout via the `ClientConfig` ?

**Comment by pujagani** [comment]
This issue is similar to https://github.com/SeleniumHQ/selenium/issues/9314. I was able to use the same example and simply it. Please refer to the example below: 

```
 ChromeOptions options = new ChromeOptions();

        DriverService.Builder<ChromeDriverService, ChromeDriverService.Builder> serviceBuilder = new ChromeDriverService.Builder();
        ChromeDriverService chromeDriverService = serviceBuilder.build();

        RemoteWebDriver driver = (RemoteWebDriver) RemoteWebDriver
                .builder()
                .config(ClientConfig.defaultConfig()
                        .connectionTimeout(Duration.ofMinutes(10))
                        .readTimeout(Duration.ofMinutes(10)))
                .withDriverService(chromeDriverService)
                .addAlternative(options)
                .build();

        driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(190L));

        ((JavascriptExecutor) driver).executeScript("function timeout(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }; const printFunction = async () => { await timeout(190000); return \"bla bla\" }; await printFunction();");

        driver.quit();

        chromeDriverService.stop();
```

**Comment by pujagani** [comment]
@krmahadevan The RemoteWebDriver builder allows for a custom config to be used. I just had to debug the example and double check it works as expected.

**Comment by BilalKamran** [comment]
@pujagani Configuration of this timeout should be possible with Chromedriver as well, without going all the way back to setting up the RemoteWebDriver, as this was previously supported in Selenium 3, unless there is a good reason not to do this. I have noticed a default client config is being used in the constructors of ChromiumDriver, this should be easy to support.

**Comment by titusfortner** [comment]
@BilalKamran agreed, that's being tracked here: #11158
