### ISSUE TITLE
ruby: Cannot start multiple IE drivers concurrently

### ISSUE THREAD

**Issue by p0deje** [SeleniumHQ/selenium#1153]
An attempt to start multiple IE drivers concurrently maybe result in IE drivers binding to the same port. Related to #736

```ruby
require 'selenium-webdriver'

threads, drivers = [], []
2.times do
  threads << Thread.new do
    drivers << Selenium::WebDriver.for(:ie)
  end
end

threads.each do |thread|
  thread.abort_on_exception = true
  thread.join
end

drivers.each_with_index do |driver, index|
  puts "Checking ##{index + 1}: #{driver}"
  puts "  it runs on #{driver.send(:bridge).instance_variable_get(:@server).port}"

  driver.title # make any wire call
  driver.quit
end
```

```
C:\selenium\rb>bundle exec ruby test.rb
Checking #1: #<Selenium::WebDriver::Driver:0x0000000302ed08>
  it runs on 5555
Checking #2: #<Selenium::WebDriver::Driver:0x00000002fcca40>
  it runs on 5555
C:/selenium/rb/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok': session 5d736cb5-f63d-4271-8120-6c3e55eff7a7 does not exist (Selenium::WebDriver::Err
or::NoSuchDriverError)
        from C:/selenium/rb/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
        from C:/selenium/rb/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
        from C:/selenium/rb/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
        from C:/selenium/rb/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
        from C:/selenium/rb/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        from C:/selenium/rb/lib/selenium/webdriver/remote/bridge.rb:664:in `raw_execute'
        from C:/selenium/rb/lib/selenium/webdriver/remote/bridge.rb:642:in `execute'
        from C:/selenium/rb/lib/selenium/webdriver/remote/bridge.rb:197:in `getTitle'
        from C:/selenium/rb/lib/selenium/webdriver/common/driver.rb:153:in `title'
        from test.rb:19:in `block in <main>'
        from test.rb:15:in `each'
        from test.rb:15:in `each_with_index'
        from test.rb:15:in `<main>'
```

**Comment by p0deje** [comment]
Fixed in 3c24cca240123b30fa3293928d9d518d7ae0b704
