### ISSUE TITLE
[🐛 Bug]: can not launch chrome when proxy environment variables are set

### ISSUE THREAD

**Issue by XinyuWuu** [SeleniumHQ/selenium#11549]
### What happened?

if the proxy is set in bash:

```bash
export http_proxy=http://127.0.0.1:1080
export https_proxy=http://127.0.0.1:1080
```

I can not launch chrome:

```python
from selenium import webdriver
browser = webdriver.Chrome()
```

raise error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 213, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 
```

### How can we reproduce the issue?

```shell
set proxy in bash:


export http_proxy=http://127.0.0.1:1080
export https_proxy=http://127.0.0.1:1080


launch chrome:

```python
from selenium import webdriver
browser = webdriver.Chrome()
```
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/xinyu/Downloads/spotify manipulate test/envs/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 213, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message:
```

### Operating System

ubuntu 22.04

### Selenium version

python 4.7.2

### What are the browser(s) and version(s) where you see this issue?

chrome 109.0.5414.74 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 109.0.5414.74

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
Most likely your proxy is being used to local addresses as well, which is why the code fails to connect to ChromeDriver. Please check your proxy configuration.

**Comment by XinyuWuu** [comment]
> 

Thank you! It works after adding `no_proxy` to the environment varibales.

```bash
export no_proxy="127.0.0.1, localhost"
```
