### ISSUE TITLE
[🐛 Bug]: Grid 4 cannot cannot find iOS element by classchain, predicate, or classname

### ISSUE THREAD

**Issue by janonymus** [SeleniumHQ/selenium#11566]
### What happened?

I'm currently working on our test automation project,
to update our libraries to the latest ( meaning to: selenium grid4 and appium 2 ).

While running the test for iOS, I get the following error ( while trying to access our textfield for login)

```
org.openqa.selenium.InvalidArgumentException: Unable to determine element locating strategy for class name
*** Element info: {Using=class name, value=XCUIElementTypeTextField}
```

Tried to access the element also via classchain and ios predicate string, all resulted with the same error.

If I switch the method to XPath, the element is found.

If I don't connect to the grid, but send the commands right to appium, 
then all the above strategies are working again ( className, classChain, predicate).

What I mean in the connecting to grid or appium is that,
in the start of the tests,
If I configure the driver to connect to the grid:
`IOSDriver<MobileElement> driver = new IOSDriver<>(new URL("http://10.0.4.90:4444"), capabilities);`
Then I get the errors, test fails
If I configure the driver to go straight to my appium server (default port)
`IOSDriver<MobileElement> driver = new IOSDriver<>(new URL("http://127.0.0.1:4723"), capabilities);`
Same test is successful

I also wonder if it's sort of related to this [older android issue](https://github.com/appium/appium/issues/16550)

my local setup while upgrading is rather simple currently
I'm running appium 2 in terminal ( having xcuitest and android driver) with the **appium** command
```
[Appium] Welcome to Appium v2.0.0-beta.48
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/janoscsizmadia/.appium/node_modules/appium-uiautomator2-driver
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/janoscsizmadia/.appium/node_modules/appium-xcuitest-driver
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.12.1 (automationName 'UiAutomator2')
[Appium]   - xcuitest@4.16.5 (automationName 'XCUITest')
[Appium] Available plugins:
[Appium]   - images@2.0.1
[Appium]   - execute-driver@3.0.1
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
```
and grid 4 with a toml config file
`java -jar selenium-server-4.jar standalone --config config.toml`

```
[node]
detect-drivers = false

[relay]
url = "http://localhost:4723"
status-endpoint = "/status"
configs = [
    "1", '{"browserName": "chrome", "platformName": "android", "appium:platformVersion": "13"}',
    "1", '{"browserName": "safari", "platformName": "iOS", "appium:automationName":"XCUITest", "appium:platformVersion": "16.1", "appium:udid": "59683A4A-725E-4B49-8397-47BA112D6836" }'
]
```

### How can we reproduce the issue?

```shell
Not sure on how you can reproduce it, since I cannot share the iOS app,

The Appium and Selenium startups are shared in the description,
I guess any random iOS project would do, later I might try to make a minimalistic project to reproduce and share.


Perhaps an issue can be, that so far I only updated the local environments, but not the version used in the code.

Snippet from the project's pom.xml:

        <java.version>1.8</java.version>
        <appium.version>7.6.0</appium.version> <!-- 8.1.1 -->
        <cucumber.version>7.4.1</cucumber.version>
        <selenium.version>3.141.59</selenium.version>
```

### Relevant log output

```shell
org.openqa.selenium.InvalidArgumentException: Unable to determine element locating strategy for class name
*** Element info: {Using=class name, value=XCUIElementTypeTextField}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:61)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByClassName(RemoteWebDriver.java:412)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByClassName(DefaultGenericMobileDriver.java:125)
	at io.appium.java_client.AppiumDriver.findElementByClassName(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElementByClassName(IOSDriver.java:1)
	at org.openqa.selenium.By$ByClassName.findElement(By.java:389)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:57)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.findElement(IOSDriver.java:1)
```

### Operating System

macOS Monterey Version 12.6

### Selenium version

Selenium 4 standalone

### What are the browser(s) and version(s) where you see this issue?

iPhone 14.1 Simulator iOS 16.1

### What are the browser driver(s) and version(s) where you see this issue?

iOSDriver

### Are you using Selenium Grid?

4.0

**Comment by diemol** [comment]
Did you try Selenium Grid 4.7.2?

**Comment by janonymus** [comment]
Thank you very much for your response, sorry that my answer took this much time.
Tried out with grid 4.7.2 and it works.

Actually facepalm that I had older 4.x grid and didn't think of updating

Closing the issue
