### ISSUE TITLE
Chrome + profile. POST session fails with Net::ReadTimeout

### ISSUE THREAD

**Issue by markych** [SeleniumHQ/selenium#1158]
Hi all,
trying to launch and use Chrome with certain existing profile with selenium on ruby.

Code is very simple:

``` ruby
driver = Selenium::WebDriver.for :chrome, :service_log_path => "d:\\chromedriver.log", :switches => [
'--profile-directory=Profile 2', '--user-data-dir=C:\\Users\\myuser\\AppData\\Local\\Google\\Chrome\\User Data', '--log-level=10', '--enable-logging', '--v=10']
driver.navigate.to "http://google.com"
```

This 
- opens a new Chrome window for the 'Profile 2' profile indeed
- set the focus to address line
- blocks on the very first line of code above and fails with the following trace after about a minute:

```
d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/http.rb:1376:in `request'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/http.rb:852:in `start'
    from d:/Install/Ruby/ruby/lib/ruby/2.0.0/net/http.rb:1367:in `request'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:664:in `raw_execute'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:122:in `create_session'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/chrome/bridge.rb:48:in `initialize'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:60:in `new'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:60:in `for'
    from d:/Install/Ruby/ruby/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver.rb:86:in `for'
    from profile.rb:8:in `<main>'
-> POST session
   >>> http://127.0.0.1:9515/session | {"desiredCapabilities":{"browserName":"chrome","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":false,"nativeEvents":false,"rotatable":false,"chromeOptions":{"args":["--profile-directory=Profile 2","--user-data-dir=C:\\Users\\myuser\\AppData\\Local\\Google\\Chrome\\User Data","--log-level=10","--enable-logging","--v=10"],"detach":true},"chrome.switches":["--profile-directory=Profile 2","--user-data-dir=C:\\Users\\myuser\\AppData\\Local\\Google\\Chrome\\User Data","--log-level=10","--enable-logging","--v=10"],"chrome.detach":true}}
     > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"589"}
```

If I remove 
`
--profile-directory=Profile 2', '--user-data-dir=C:\\Users\\myuser\\AppData\\Local\\Google\\Chrome\\User Data'
`
from 'switches' everything runs smoothly without any exceptions 
- opening new window for temporary profile
- sets data:, in the address line without focusing into it
- passes control to the next lines of code

I tried ChromeDriver v.2.19 and 2.20 with the same outcome.
Any suggestions or guidance would be very appreciated.

Regards,
Mark

**Comment by titusfortner** [comment]
Oh interesting, I didn't know Chrome supported all of these options.

Looking over the [Chromedriver Capabilities documenation](https://sites.google.com/a/chromium.org/chromedriver/capabilities), it looks like chromedriver is expecting the argument array to be strings without the flags. Try this format (no '--' before it):
```
driver = Selenium::WebDriver.for :chrome, switches: ['user-data-dir=/tmp/temp_profile']
```

**Comment by Th33x1l3** [comment]
i got readtimeout too, but i'm using docker container. When not running in docker container, the test runs well

**Comment by titusfortner** [comment]
With latest Selenium gem and chromedriver, this code successfully starts up Chrome for me with the correct profile and data directory.

```
switches = ["--profile-directory=Profile 2", "--log-level=10", "--enable-logging", "--user-data-dir=/Users/titusfortner/tmp/"]
Selenium::WebDriver.for :chrome, switches: switches
```

This is what is getting sent to the server (found when setting `$DEBUG = true`)

```
   >>> http://127.0.0.1:9519/session | {"desiredCapabilities":{"browserName":"chrome","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":false,"nativeEvents":false,"rotatable":false,"chromeOptions":{"args":["--profile-directory=Profile 2","--log-level=10","--enable-logging","--user-data-dir=/Users/titusfortner/tmp/"]}}}
```
