### ISSUE TITLE
[🐛 Bug]: Selenium WebDriver Exception The HTTP request to the remote WebDriver server for URL Timed out after 60 seconds

### ISSUE THREAD

**Issue by nnson0310** [SeleniumHQ/selenium#11595]
### What happened?

I do many research and it seems this popular bug did exist for many years and nothing on stackoverflow or any solution can help me out to resolve this problem. And it seems this bug is also very popular to Selenium C# user. The web driver just stuck right after navigating to a new page and the browser will stop for eternity.

I also tried to reproduce with Selenium Java and it seems reproducible. Luckily, this domain using for reproduce bug is public. In Java, it throws out Timeout Exception instead of WebDriverException. I did not see anything wrong in my code. And this bugs does exist for a long time in Selenium community. I do not know the reason lying on web driver or on Selenium core at all.  

I tried to debug it by starting chrome driver separately and below is chrome driver logs:
`
Starting ChromeDriver 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

DevTools listening on ws://127.0.0.1:59978/devtools/browser/59ae3282-66b7-461d-b868-697abd1b798d
[2216:12024:0128/164354.376:ERROR:device_event_log_impl.cc(215)] [16:43:54.376] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
[2216:12232:0128/164450.257:ERROR:util.cc(134)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
[6464:11352:0128/164550.261:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
`
This bugs did happen for Chromium browser too (Ms Edge or Opera). 

### How can we reproduce the issue?

```shell
I created a maven repo and use IntelliJ to run test.

https://github.com/nnson0310/Selenium_Bugs.git
```

### Relevant log output

```shell
I will attach logs for Selenium Java. In Selenium C#, it will throw WebDriverException: The HTTP request to the remote WebDriver server for URL Timed out after 60 seconds

`
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Jan 28, 2023 4:43:49 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.13'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [9a0b159214b121081b4399873f8b768c, get {url=https://www.ericsson.com/en/events/imagine-possible/content/extended-reality-and-metaverse-track}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 109.0.5414.120, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: C:\Users\son\AppData\Local\...}, goog:chromeOptions: {debuggerAddress: localhost:59978}, networkConnectionEnabled: false, pageLoadStrategy: eager, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 9a0b159214b121081b4399873f8b768c
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:297)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:983)
	at demo.TC_01(demo.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 40 more
`
```

### Operating System

Windows 10 Pro

### Selenium version

4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome with version 109.0.5414.120 

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver with version 109.0.5414.74

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
A few things...

This code does not work because there is no instance running on port 9515. 

```java
        driver = new RemoteWebDriver(
                new URL("http://127.0.0.1:9515"),
                chromeOptions
        );
```

You should use `ChromeDriver` instead of `RemoteWebDriver` in this case.


Also, not sure what the issue is with that page with Chrome, but Firefox works fine. I changed the `BeforeMethod` to

```java
    @BeforeMethod
    public void setUp() throws InterruptedException {
        FirefoxOptions options =  new FirefoxOptions();
        options.setPageLoadStrategy(PageLoadStrategy.EAGER);
        driver = new FirefoxDriver(options);
        driver.get("https://www.ericsson.com/");
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        Thread.sleep(5000);
    }
```

and things work (aside of errors related to element finding). 

So please report this issue to the Chrome/ChromeDriver team.

**Comment by ilyasdusme** [comment]
DevTools listening on ws://127.0.0.1:50574/devtools/browser/5167ad7b-3643-4b93-bfdb-27ebaa5b190f 
109.0.5414.120 Chrome with version 
I am making such a mistake, can you help me?

**Comment by NCLnclNCL** [comment]
I increasing it to 120 seconds timeout

**Comment by NCLnclNCL** [comment]
I increasing it to 120 seconds timeout and perfect
