### ISSUE TITLE
[🐛 Bug]: Selenium 4.8 Java is not compatible with Chrome 109.0.5414.120 Version . 

### ISSUE THREAD

**Issue by Mathan31** [SeleniumHQ/selenium#11635]
### What happened?

Today morning Chrome Browser got upgraded to 110 and its impacted my existing program. Selenium Manager is not able to download the driver corresponding to the latest Chrome110 version .

### How can we reproduce the issue?

```shell
public class GoogleSearchWebElements {
	
	public static WebDriver driver;
	public static int iBrowser = 5;// 1 - Chrome,2 - FF,3 - Edge
	public static String sURL = "https://www.google.com/";

	public static void main(String[] args) {
		invokeBrowser();
		browserSettings();
		navigateURL();
		getPageInfo();
		searchText("Selenium WebDriver");
		closeBrowser();
	}
	
	public static void invokeBrowser() {
		switch (iBrowser) {
		case 1:
			System.out.println("User option is - "+iBrowser+" ,So invoking the Chrome browser!!");
			driver = new ChromeDriver();
			break;
			
		case 2:
			System.out.println("User option is - "+iBrowser+" ,So invoking the Firefox browser!!");
			driver = new FirefoxDriver();
			break;
			
		case 3:
			System.out.println("User option is - "+iBrowser+" ,So invoking the Edge browser!!");
			driver = new EdgeDriver();
			break;

		default:
			System.out.println("User option is  wrong - "+iBrowser+" ,So invoking the default chrome browser!!");
			driver = new ChromeDriver();
			break;
		}
	}
	
	public static void browserSettings() {
		driver.manage().deleteAllCookies();
		driver.manage().window().maximize();
	}
	
	public static void navigateURL() {
		driver.get(sURL);
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(20));
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));
	}
	
	public static void getPageInfo() {
		System.out.println("Title is : "+driver.getTitle());
		System.out.println("Current URL is : "+driver.getCurrentUrl());
	}
	
	public static void searchText(String text) {
		WebElement oText,oBtn;
		oText = driver.findElement(By.xpath("//input[@title='Search']"));
		oText.sendKeys(text);
		oBtn = driver.findElement(By.name("btnK"));
		oBtn.click();
	}
	
	public static void closeBrowser() {
		driver.quit();
	}

}
```

### Relevant log output

```shell
[🐛 Bug]: Selenium 4.8 Java is not compatible with Chrome 110 Version . 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 110.0.5481.77 (65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}) on port 36962
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 110
Current browser version is 109.0.5414.120 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
Host info: host: 'DESKTOP-8GQ3KA3', ip: '192.168.29.29'
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:148)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:50)
	at day03.GoogleSearchWebElements.invokeBrowser(GoogleSearchWebElements.java:46)
	at day03.GoogleSearchWebElements.main(GoogleSearchWebElements.java:19)
```

### Operating System

Windows10 Pro

### Selenium version

Java

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver110.0.5481.77

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
First, that reference to sflj in your logs appears to indicate you are using webdriver manager jar. Selenium manager code is completely skipped when webdriver manager is used.

Secondly, the issue in the logs is that the browser isn't updated, while the driver is.

Do you perhaps have multiple versions of chrome installed?

**Comment by Mathan31** [comment]
Hi, Thanks for the quick response . I have not used webdriver manager in my maven pom.xml and I dont have installed multiple  chrome in my system . It was working 2 days before and after the Chrome upgrade it was not working from yesterday .

**Comment by titusfortner** [comment]
Per the logs above:
```
Current browser version is 109.0.5414.120 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
```
So it appears the driver has been updated, but the browser has not.

**Comment by Mathan31** [comment]
Hi, I have not configured driver locally then how come it is updating it .
Currently I am handling the scenario by providing the "Chrome Driver" path .

**Comment by titusfortner** [comment]
How are you referencing the driver location, I don't see that in your code.

What is the location of the driver? Is it in a directory on PATH?

**Comment by Mathan31** [comment]
I was using the driver location as part of solution, meaning after getting that issue I was using driver path . But Selenium 4.8 was working without providing driver location, By referring to selenium manager .

**Comment by titusfortner** [comment]
We're hoping to have more logging in the next version to make it easier to see what is going on for troubleshooting. It's going to be  difficult to walk thru what went wrong and why and how to fix at this point. 

In the meantime, just download the correct driver version and set the system property to its location.
