### ISSUE TITLE
[🐛 Bug]: Unable to open the browser successfully

### ISSUE THREAD

**Issue by huajingtong** [SeleniumHQ/selenium#11633]
### What happened?

The driver and browser versions are the same. The browser cannot be opened
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/30971576/217576428-c95fba62-3d8f-414c-a8e9-e077bbaf2cb7.png">
<img width="947" alt="image" src="https://user-images.githubusercontent.com/30971576/217576584-925f2409-0199-4e9c-b0f1-5ce896d3ef0b.png">

### How can we reproduce the issue?

```shell
An error is reported at this point：
ChromeDriver driver = new ChromeDriver(options);
```

### Relevant log output

```shell
Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 35671
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.



org.openqa.selenium.WebDriverException: disconnected: unable to connect to renderer
  (failed to check if window was closed: disconnected: unable to connect to renderer)
  (Session info: chrome=108.0.5359.71)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'xiaoyatongdeMacBook-Pro.local', ip: '2409:8a00:24a9:ae80:a423:b71a:60e7:8ebc%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_191'
Driver info: driver.version: InitDriver
remote stacktrace: 0   chromedriver3                       0x000000010dee1f38 chromedriver3 + 4910904
1   chromedriver3                       0x000000010de61a03 chromedriver3 + 4385283
2   chromedriver3                       0x000000010daa6747 chromedriver3 + 472903
3   chromedriver3                       0x000000010da8b7ea chromedriver3 + 362474
4   chromedriver3                       0x000000010da7ae19 chromedriver3 + 294425
5   chromedriver3                       0x000000010da7a9f5 chromedriver3 + 293365
6   chromedriver3                       0x000000010db1a578 chromedriver3 + 947576
7   chromedriver3                       0x000000010db19cbf chromedriver3 + 945343
8   chromedriver3                       0x000000010db10ee3 chromedriver3 + 909027
9   chromedriver3                       0x000000010dadb30c chromedriver3 + 688908
10  chromedriver3                       0x000000010dadc88e chromedriver3 + 694414
11  chromedriver3                       0x000000010deaf1de chromedriver3 + 4702686
12  chromedriver3                       0x000000010deb3b19 chromedriver3 + 4721433
13  chromedriver3                       0x000000010debb28e chromedriver3 + 4752014
14  chromedriver3                       0x000000010deb491a chromedriver3 + 4725018
15  chromedriver3                       0x000000010de88b02 chromedriver3 + 4545282
16  chromedriver3                       0x000000010ded3888 chromedriver3 + 4851848
17  chromedriver3                       0x000000010ded3a05 chromedriver3 + 4852229
18  chromedriver3                       0x000000010dee9e5f chromedriver3 + 4943455
19  libsystem_pthread.dylib             0x00007fff6cbf3109 _pthread_start + 148
20  libsystem_pthread.dylib             0x00007fff6cbeeb8b thread_start + 15


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at common.InitDriver.launchChromeDriver(InitDriver.java:46)
	at common.BaseTest.setUp(BaseTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
```

### Operating System

mac 10.15.7

### Selenium version

java 1.8  selenium=3.141.59(pom)

### What are the browser(s) and version(s) where you see this issue?

108.0.5359.71

### What are the browser driver(s) and version(s) where you see this issue?

108.0.5359.71

### Are you using Selenium Grid?

no.local

**Comment by diemol** [comment]
Please note we do not support Selenium 3.x anymore.

**Comment by surajverma255** [comment]
Maybe updating the Selenium Version will help here

**Comment by diemol** [comment]
Closing this as we did not get more information.
