### ISSUE TITLE
[🐛 Bug]: Error when creating CDP connection with IE Driver

### ISSUE THREAD

**Issue by zamgill** [SeleniumHQ/selenium#11641]
### What happened?

I'm trying to intercept network logs while using IE driver.

When I call the following code:
```javascript
const connection = await driver.createCDPConnection('page');
```

I get the following error:
```
Uncaught TypeError: debuggerAddress.match is not a function
```

### How can we reproduce the issue?

```javascript
const { Builder, By, Key, until } = require('selenium-webdriver');
const { Options } = require('selenium-webdriver/ie');

(async () => {
  let ieOptions = new Options();
  ieOptions.setEdgeChromium(true);
  ieOptions.setEdgePath('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe');
  ieOptions.initialBrowserUrl('http://www.bing.com');
  ieOptions.ignoreZoomSetting(true);
  ieOptions.requireWindowFocus(true);

  let driver = await new Builder().forBrowser('ie').setIeOptions(ieOptions).build();
  try {
    const connection = await driver.createCDPConnection('page');
    let httpResponse = new HttpResponse();
    await driver.onIntercept(connection, httpResponse, async function () {
      console.log('http response: ', httpResponse);
    });
    await driver.get('https://www.google.com')
} finally {
    await driver.quit();
}
})();
```

### Relevant log output

```shell
TypeError: debuggerAddress.match is not a function
    at WebDriver.getWsUrl (C:\Users\$USER$\Projects\a\testProject\node_modules\selenium-webdriver\lib\webdriver.js:1297:25)
    at WebDriver.createCDPConnection (C:\Users\$USER$\Projects\a\testProject\node_modules\selenium-webdriver\lib\webdriver.js:1226:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\$USER$\Projects\a\testProject\index.js:18:24
```

### Operating System

Windows 11

### Selenium version

4.8.0.0

### What are the browser(s) and version(s) where you see this issue?

Internet Explorer 11

### What are the browser driver(s) and version(s) where you see this issue?

IE Driver 4.8.0.0

**Comment by titusfortner** [comment]
This is not and will not be supported in IE.

**Comment by zamgill** [comment]
@titusfortner is there workaround at all?

**Comment by titusfortner** [comment]
You can use a proxy to log network traffic.
