### ISSUE TITLE
[🐛 Bug]: Chrome failed to start: crashed.

### ISSUE THREAD

**Issue by many1337** [SeleniumHQ/selenium#11691]
### What happened?

I wanted to use 15 profile in real-time, cause I need to use cookies for the website. I read the closed issues about that error, but I tried all option and seems not working. 

### How can we reproduce the issue?

```shell
options = webdriver.ChromeOptions()
            options.binary_location = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"

            options.add_argument("--headless=new")
            options.add_argument('--no-sandbox')
            options.add_argument("--disable-dev-shm-usage");
            options.add_argument(f'--user-data-dir={self.user_dir}')
            options.add_argument(f'--profile-directory={self.username}')
            options.add_argument('--window-size=800,700')
            options.add_argument('--no-default-browser-check')
            options.add_argument('--disable-threaded-scrolling')
            options.add_argument('--disable-threaded-animation')
            options.add_argument('--disable-backgrounding-occluded-windows')
            options.add_argument('--disable-hang-monitor')
            options.add_argument('--disable-prompt-on-repost')
            options.add_argument('--disable-pnacl-crash-throttling')
            options.add_argument('--disable-gpu')
            options.add_argument('--start-maximized')
            options.add_argument('--enable-ipv6')
            options.add_argument('--disable-features=site-per-process, GlobalMediaControls, TranslateUI, IsolateOrigins')
            options.add_argument('--no-first-run')
            options.add_argument('--disable-breakpad')
            options.add_argument('--ignore-urlfetcher-cert-requests')
            options.add_argument('--disable-pepper-3d')
            options.add_argument('--disable-default-apps')
            options.add_argument('--disable-background-networking')
            options.add_argument('--disable-component-extensions-with-background-pages')
            options.add_argument('--disable-popup-blocking')
            options.add_argument('--disable-web-security')
            options.add_argument('--force-color-profile=srgb')
            options.add_argument('--disable-extensions')
            options.add_argument('--enable-low-end-device-mode')
            options.add_argument('--disable-background-timer-throttling')
            options.add_argument('--disable-renderer-backgrounding')
            options.add_argument('--enable-low-res-tiling')
            options.add_argument('--test-type')
            #options.add_argument('--window-position=3333,3333')
            options.add_argument('--disable-client-side-phishing-detection')
            options.add_argument('--enable-automation')
            options.add_argument('--metrics-recording-only')
            if self.proxy:
                options.add_argument('--proxy-server=socks5://%s' % self.proxy)
            options.add_argument("--mute-audio")
            options.add_experimental_option('excludeSwitches', ['enable-logging', 'enable-automation'])
            options.add_experimental_option('useAutomationExtension', False)
            
            HERE IS THE ERROR:
            driver = webdriver.Chrome(executable_path=r'.\src\chromedriver.exe', options=options)
```

### Relevant log output

```shell
Exception has occurred: WebDriverException
Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
Backtrace:
	(No symbol) [0x003E37D3]
	(No symbol) [0x00378B81]
	(No symbol) [0x0027B36D]
	(No symbol) [0x0029B7EF]
	(No symbol) [0x00296FC9]
	(No symbol) [0x002D1ED5]
	(No symbol) [0x002D1B2C]
	(No symbol) [0x002CB216]
	(No symbol) [0x002A0D97]
	(No symbol) [0x002A253D]
	GetHandleVerifier [0x0065ABF2+2510930]
	GetHandleVerifier [0x00688EC1+2700065]
	GetHandleVerifier [0x0068C86C+2714828]
	GetHandleVerifier [0x00493480+645344]
	(No symbol) [0x00380FD2]
	(No symbol) [0x00386C68]
	(No symbol) [0x00386D4B]
	(No symbol) [0x00390D6B]
	BaseThreadInitThunk [0x76AD7D69+25]
	RtlInitializeExceptionChain [0x7710BB9B+107]
	RtlClearBits [0x7710BB1F+191]
```

### Operating System

Windows 11 22H2 Build: 22621.1265

### Selenium version

Python 3.11.2 / Selenium 4.8.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 110.0.5481.104

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.77

**Comment by diemol** [comment]
There are many variables in the script that we need to know their value to reproduce the issue. You can also try to remove all those options and add one by one to see where the issue starts happening.

In short, without a way to reproduce the issue we won't be able to triage it.

**Comment by RazeSoldier** [comment]
@diemol In my case, I use "--headless" argument in my linux server and also encountered an exception. So I running a command `google-chrome --headless`, it say `[0221/162410.322607:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`

So I add "--no-sandbox" to arguments and work fine. I suggest you test first with command.

**Comment by mohit59** [comment]
Hi, I am also facing the same issue. 
I am not using any options or capabilities. 
PFA snapshot 

<img width="443" alt="Screenshot 2023-02-22 165522" src="https://user-images.githubusercontent.com/15117753/220607040-5cbe5d3a-0948-440d-9d41-aa65ab032e28.png">

**Comment by titusfortner** [comment]
Wow, Selenium 3.4? @mohit59 you need to be using the latest selenium 4 version.

**Comment by mohit59** [comment]
> 

I tried with the latest version 4.8.1 but it was also not working.

**Comment by diemol** [comment]
Still, waiting for a script that helps to reproduce the issue.

**Comment by mohit59** [comment]
```bash
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-debugging-port=9222, –no-sandbox, –disable-dev-shm-usage], extensions: [], useAutomationExtension: true}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-debugging-port=9222, –no-sandbox, –disable-dev-shm-usage], extensions: [], useAutomationExtension: true}}}]
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:148)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
    at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:71)
    at com.console.init.initialization.launchBrowser(initialization.java:229)
    at com.console.init.initialization.startLogin(initialization.java:789)
    at ConsoleRegressionSuite.Console_Tile_Validation_Test.ready(Console_Tile_Validation_Test.java:74)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    at org.testng.TestRunner.privateRun(TestRunner.java:782)
    at org.testng.TestRunner.run(TestRunner.java:632)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
    at org.testng.TestNG.run(TestNG.java:1064)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

**Comment by krmahadevan** [comment]
@mohit59 - That exception stacktrace does not help a lot.

So can you please help do the following?

1. Create a sample maven project that can be used to reproduce the problem you are experiencing (This will also help tell us what versions you use, what does your code look like, do you deal with the Selenium Manager or are you managing the chromedriver binary on your own etc.,)
2. What is the Chrome browser version that you are using.

On a side note, you can do something like below to check if your chromedriver is the one at fault here.

1. Open a command prompt and run chromedriver binary `./chromedriver `
2. Now open up another command prompt and trigger a curl post that looks like below.
3. You should see a browser open up. Post back the results.

```bash
curl -X POST 'localhost:9515/session' \
--header 'Content-Type: application/json; charset=utf-8' \
 --data-raw '{ "desiredCapabilities": { "browserName": "chrome", "goog:chromeOptions": { "args": [ "--remote-debugging-port=9225" ] }, "goog:loggingPrefs": { "browser": "ALL", "driver": "ALL", "server": "ALL" } }, "capabilities": { "browserName": "chrome" } }'
```

**Comment by mohit59** [comment]
> 

Hi,

I tried the above steps for 1st step it says chrome driver running but does not open the screen 
2nd step it stays port 9225 unknown

**Comment by krmahadevan** [comment]
@mohit59 then I think you have a bad/corrupted chromedriver. Have you tried getting rid of it and then letting selenium use selenium manager to download the correct binary and use it ? 

For selenium manager to kick in, you need to ensure the following:

1. There should not be any chromedriver binaries available in `%Path` (You can confirm this by typing `which chromedriver` or its equivalent on windows and ensuring that you dont see any.
2. You should not be using any of the JVM arguments to setup the chromedriver binary.

A simple test that merely opens up a webpage using `ChromeDriver` should suffice to confirm this. Give this a try and see how it goes 

If selenium manager downloaded the binary, you should find it under `$HOME/.cache/selenium`

**Comment by many1337** [comment]
I solved the problem with another option, so whatever. any way thanks ! ✌️

**Comment by Judimax** [comment]
@many1337 how did you solve the problem can you post it   I get this error

Greetings everyone I have an issue does anyone have spare code to open java selenium with your own profile I keep getting    (unknown error: DevToolsActivePort file doesn't exist)
(The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
However I see chrome load up w/ my profile
Version info
Windows 10 pro
JDK: open jdk java 17.0.4.1 2022-08-18 LTS
mvn v 3.8.7
selenium v4.8.1
