### ISSUE TITLE
[🐛 Bug]: Unable to find CDP implementation matching 110.

### ISSUE THREAD

**Issue by dlee-amplify** [SeleniumHQ/selenium#11710]
### What happened?

Chrome Browser Version: v110
Selenium Version: 4.8.1

Issue:
- Getting error "Unable to find CDP implementation matching 110" with the code in "How can we reproduce the issue" section
- As I was using Intellij to populate the Network module for Devtools version, it only shows v85, 102, 103 and 104, but not 110

### How can we reproduce the issue?

```shell
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.DevTools;
import org.openqa.selenium.devtools.v104.network.Network;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.Optional;

public class CDP {


    public static void main(String[] args){
        // WebDriverManager.chromedriver().setup();
        WebDriver driver = new ChromeDriver();
        driver.get("https://reqres.in/");
        // driver.navigate().to("https://www.google.com");
        // driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".key-sells")));
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        CDP cdp = new CDP();
        cdp.setUpDevTool(driver);
        By outputLinkLocator = By.cssSelector("[data-key=\"request-output-link\"]");
        wait.until(ExpectedConditions.visibilityOfElementLocated(outputLinkLocator));
        WebElement outputLink = driver.findElement(outputLinkLocator);
        outputLink.click();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    }

    public void setUpDevTool(WebDriver driver) {
        DevTools devTools = ((ChromeDriver) driver).getDevTools();
        devTools.createSession();
        devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
        devTools.addListener(Network.requestWillBeSent(), entry -> {
            System.out.println("request URI:" + entry.getRequest().getUrl());
        });
    }
}
```

### Relevant log output

```shell
Unable to find CDP implementation matching 110.
Feb 26, 2023 10:11:33 PM org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
WARNING: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.4.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
Exception in thread "main" org.openqa.selenium.devtools.DevToolsException: You are using a no-op implementation of the CDP. The most likely reason for this is that Selenium was unable to find an implementation of the CDP protocol that matches your browser. Please be sure to include an implementation on the classpath, possibly by adding a new (maven) dependency of `org.seleniumhq.selenium:selenium-devtools-vNN:4.4.0` where `NN` matches the major version of the browser you're using.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'amplifydev-3.local', ip: 'fe80:0:0:0:e7:5562:b9a6:e5cb%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.11'
Driver info: DevTools Connection
	at org.openqa.selenium.devtools.noop.NoOpDomains.target(NoOpDomains.java:59)
	at org.openqa.selenium.devtools.DevTools.findTarget(DevTools.java:145)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:114)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:102)
	at CDP.setUpDevTool(CDP.java:41)
	at CDP.main(CDP.java:31)

Process finished with exit code 1
```

### Operating System

macOS Ventura

### Selenium version

4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome v110

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 110.0.5481.77

### Are you using Selenium Grid?

No

**Comment by dlee-amplify** [comment]
![Screenshot 2023-02-26 at 10 17 04 PM](https://user-images.githubusercontent.com/15660806/221464868-07048b1f-4aa1-42dc-8b66-a193499804f1.png)
![Screenshot 2023-02-26 at 10 17 40 PM](https://user-images.githubusercontent.com/15660806/221464952-3b94e158-a9fd-4091-a1d5-bdbd87e6d768.png)
![Screenshot 2023-02-26 at 10 18 05 PM](https://user-images.githubusercontent.com/15660806/221464996-e753beba-f3b6-4951-9d76-d367c5c87ccb.png)

**Comment by krmahadevan** [comment]
@dlee-amplify - Your exception stack trace says that you are using '4.4.0`. Can you please bump up to `4.8.1` and try again ?

```bash
Feb 26, 2023 10:11:33 PM org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
WARNING: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.4.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
Exception in thread "main" org.openqa.selenium.devtools.DevToolsException: You are using a no-op implementation of the CDP. The most likely reason for this is that Selenium was unable to find an implementation of the CDP protocol that matches your browser. Please be sure to include an implementation on the classpath, possibly by adding a new (maven) dependency of `org.seleniumhq.selenium:selenium-devtools-vNN:4.4.0` where `NN` matches the major version of the browser you're using.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
```

**Comment by dlee-amplify** [comment]
thanks @krmahadevan !  it totally works! thanks so much!
