### ISSUE TITLE
selenium-webdriver 2.48.0 syntax error

### ISSUE THREAD

**Issue by bricas** [SeleniumHQ/selenium#1171]
Upgraded to the latest release this morning and got this error:

```
+ ./node_modules/.bin/cucumber.js -r features -f json

/var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/_base.js:104
        vm.runInContext(opt_srcText, closure, src);
           ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.Context.closure.goog.retrieveAndExecModule_ (/var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
    at Object.goog.writeScripts_ (/var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
    at Object.goog.require (/var/lib/jenkins/workspace/myproject/node_modules/selenium-webdriver/lib/goog/base.js:663:14)
```

Downgrading to 2.47.0 allows my tests to run again.

**Comment by jleyba** [comment]
If you're using node 0.12.x, you must run with the --harmony flag. See [changelog](http://seleniumhq.github.io/selenium/docs/api/javascript/Changes.html) for 2.48.0 (and 2.47.0)
