### ISSUE TITLE
[🐛 Bug]: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.

### ISSUE THREAD

**Issue by Poonam-25445** [SeleniumHQ/selenium#11741]
### What happened?

Chrome browser crashed after pulling latest node-chrome image from docker.

### How can we reproduce the issue?

```shell
Pull latest selenium/node-chrome image from docker hub and execute test cases on selenium grid.

**reference docker-compose file:**

version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    user: "${UID}:${GID}"
    ports:
     - "5900"
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1200
      - SCREEN_DPI=400
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
```

### Relevant log output

```shell
**Error Message:**
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
12:36:50    (unknown error: DevToolsActivePort file doesn't exist)
12:36:50    (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
12:36:50  Host info: host: 'b12aa9010a2b', ip: '192.168.3.19'
12:36:50  Build info: version: '4.8.1', revision: '8ebccac989'
12:36:50  System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1085-azure', java.version: '11.0.18'
12:36:50  Driver info: driver.version: unknown
12:36:50  Build info: version: '4.8.1', revision: '8ebccac989'
12:36:50  System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1085-azure', java.version: '11.0.18'
12:36:50  Driver info: driver.version: unknown
12:36:50  Build info: version: '4.8.0', revision: '267030adea'
12:36:50  System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1085-azure', java.version: '11.0.17'
12:36:50  Driver info: driver.version: unknown
12:36:50  Build info: version: '4.3.0', revision: 'a4995e2c09*'
12:36:50  System info: host: 'azure-apollo-selenium-grid-agentfa7f20', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1085-azure', java.version: '11.0.18'
12:36:50  Driver info: org.openqa.selenium.remote.RemoteWebDriver
12:36:50  Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--test-type, --disable-extensions, –headless, --no-sandbox, --disable-dev-shm-usage, --disable-backgrounding-occ...], extensions: [], prefs: {download.default_directory: /TestData/Downloads/, profile.default_content_settings.popups: 0}}, platformName: LINUX, unhandledPromptBehavior: dismiss}], desiredCapabilities=Capabilities {acceptSslCerts: true, browserName: chrome, goog:chromeOptions: {args: [--test-type, --disable-extensions, –headless, --no-sandbox, --disable-dev-shm-usage, --disable-backgrounding-occ...], extensions: [], prefs: {download.default_directory: /TestData/Downloads/, profile.default_content_settings.popups: 0}}, platformName: LINUX, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss}}]
12:36:50  Capabilities {}
12:36:50  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
12:36:50  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
12:36:50  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
12:36:50  	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
12:36:50  	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
12:36:50  	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
12:36:50  	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:264)
12:36:50  	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:179)
12:36:50  	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
12:36:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:36:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:36:50  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:36:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:36:50  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
12:36:50  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
12:36:50  	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
12:36:50  	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
12:36:50  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
12:36:50  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
12:36:50  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
12:36:50  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
12:36:50  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
12:36:50  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
12:36:50  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
12:36:50  	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Operating System

Linux

### Selenium version

4.8.1

### What are the browser(s) and version(s) where you see this issue?

chrome:110.0

### What are the browser driver(s) and version(s) where you see this issue?

selenium/node-chrome:110.0-20230210

### Are you using Selenium Grid?

4.8.1

**Comment by Anilkumar-Shrestha** [comment]
I have also faced the same issue after I added `chromeOptions.addArguments("--headless=new")` for downloading file in headless mode.
I am downloading google chrome from `https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb` and using `WebDriverManager.chromedriver().setup()` to auto download the driver.
 Chrome driver version: 111.0.5563.64
![image](https://user-images.githubusercontent.com/26526138/224017165-080dcffe-67e0-47a3-b939-0947f1cf73cd.png)

**Comment by titusfortner** [comment]
If it is working in non-headless but not working in headless, it is an issue for Google.

**Comment by Anilkumar-Shrestha** [comment]
Has someone created an issue to [ChromeDriver](https://bugs.chromium.org/p/chromedriver/issues/list) team to look upon?

**Comment by shabana-parveen** [comment]
Hello All,

Does anyone created this issue, I also face the same issue.

**Comment by sahlex** [comment]
I have the same issue when running tests unter linux as normal user. However, if run as root user it works!
