### ISSUE TITLE
[🐛 Bug]: selenium downloads the wrong chromedriver for Brave Version 1.48.171

### ISSUE THREAD

**Issue by danielhoherd** [SeleniumHQ/selenium#11746]
### What happened?

Using Brave Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64), the wrong chromedriver is downloaded.

```
$ find $HOME/.cache/selenium
$HOME/.cache/selenium
$HOME/.cache/selenium/selenium-manager.json
$HOME/.cache/selenium/chromedriver
$HOME/.cache/selenium/chromedriver/mac64
$HOME/.cache/selenium/chromedriver/mac64/111.0.5563.64
$HOME/.cache/selenium/chromedriver/mac64/111.0.5563.64/chromedriver
```

The contents of selenium-manager.json are:

```json
{
  "browsers": [
    {
      "browser_name": "chrome",
      "browser_version": "111",
      "browser_ttl": 1678287363
    }
  ],
  "drivers": [
    {
      "browser_version": "111",
      "driver_name": "chromedriver",
      "driver_version": "111.0.5563.64",
      "driver_ttl": 1678373740
    }
  ]
}
```

Everything was working fine on two machines until this morning. When I woke up, one of my machines was in this failed state, and one was in a working state. The `driver_ttl` on the working machine was set to a time in the future, and it had only the correct chromedriver installed. The failed machine had the correct chromedriver installed as well as the newer incorrect chromedriver.

### How can we reproduce the issue?

1. Install Brave Version 1.48.171

2. Do not have Chrome installed

3. Do not have any version of chromedriver or selenium-manager installed

4. Run the following commands:
```shell
rm -rf ~/.cache/selenium venv
python3 -m venv venv
venv/bin/pip install selenium==4.8.2
```

5. Run the following python script:

```py
from selenium import webdriver

options = webdriver.ChromeOptions()
options.binary_location = "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"

driver = webdriver.Chrome(options=options)
```

### Relevant log output

```shell
>>> driver = webdriver.Chrome(options=options)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/code/python-playground/selenium/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/Users/user/code/python-playground/selenium/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/Users/user/code/python-playground/selenium/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/user/code/python-playground/selenium/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/user/code/python-playground/selenium/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/Users/user/code/python-playground/selenium/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 111
Current browser version is 110.0.5481.177 with binary path /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Stacktrace:
0   chromedriver                        0x0000000102e38428 chromedriver + 4899880
1   chromedriver                        0x0000000102db5a23 chromedriver + 4364835
2   chromedriver                        0x00000001029ffbf6 chromedriver + 474102
3   chromedriver                        0x0000000102a30970 chromedriver + 674160
4   chromedriver                        0x0000000102a2b766 chromedriver + 653158
5   chromedriver                        0x0000000102a27af9 chromedriver + 637689
6   chromedriver                        0x0000000102a73019 chromedriver + 946201
7   chromedriver                        0x0000000102a723af chromedriver + 943023
8   chromedriver                        0x0000000102a69333 chromedriver + 906035
9   chromedriver                        0x0000000102a3355f chromedriver + 685407
10  chromedriver                        0x0000000102a34a7e chromedriver + 690814
11  chromedriver                        0x0000000102e0579e chromedriver + 4691870
12  chromedriver                        0x0000000102e0a961 chromedriver + 4712801
13  chromedriver                        0x0000000102e112ff chromedriver + 4739839
14  chromedriver                        0x0000000102e0b85a chromedriver + 4716634
15  chromedriver                        0x0000000102dddfce chromedriver + 4530126
16  chromedriver                        0x0000000102e2b5c8 chromedriver + 4847048
17  chromedriver                        0x0000000102e2b747 chromedriver + 4847431
18  chromedriver                        0x0000000102e4087f chromedriver + 4933759
19  libsystem_pthread.dylib             0x00007ff818b19259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff818b14c7b thread_start + 15
```
```


### Operating System

macOS 13.2.1

### Selenium version

python 3.10.10 selenium==4.8.2

### What are the browser(s) and version(s) where you see this issue?

Brave 1.48.171

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.177

### Are you using Selenium Grid?

_No response_

**Comment by titusfortner** [comment]
Selenium does not yet support provided browsers and is just going off of the default installation of the browser. This is being tracked in: #11351
