### ISSUE TITLE
[🐛 Bug]: Jenkins as a Service on Windows doesn’t type characters for example “ą, ć” into input

### ISSUE THREAD

**Issue by testermarcinf** [SeleniumHQ/selenium#11760]
### What happened?

Tests run with Jenkins (2.361.1)
Jenkins is running as a service.
Jenkins runs tests on the default executor.
I enter values "ALA ąźćńłóę" in input.
In input is only "ńłóę".
I enter value "BABA żęóśłźćń" in input.
In input is "ńłóęóśłń".

No problem when the Jenkins executor run in cmd.
```
curl -sO http://XXXXXXXX/jnlpJars/agent.jar
java -jar agent.jar -jnlpUrl http://XXXXXXX/computer/XXXXXX/jenkins-agent.jnlp -secret XXXXXXX -workDir "XXXXXXX"
```

### How can we reproduce the issue?

```shell
import dictionaries.run.params.RunParams;
import helpers.ScreenShotUtils;
import lombok.SneakyThrows;
import lombok.extern.log4j.Log4j2;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chromium.ChromiumOptions;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.edge.EdgeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.testng.Assert;
import org.testng.annotations.Test;

@Log4j2
public class PolishCharactersTest {

    @Test
    public void testChrome() {
        steps(getChromeDriver());
    }

    @Test
    public void testEdge() {
        steps(getEdgeDriver());
    }

    @Test
    public void testFirefox() {
        steps(getFirefoxDriver());
    }

    private static void getChromiumOptions(ChromiumOptions options) {
        options.addArguments("--incognito");
        options.addArguments("--remote-allow-origins=*");
    }

    private WebDriver getChromeDriver() {
        ChromeOptions options = new ChromeOptions();
        getChromiumOptions(options);
        log.info(options.toString());
        System.setProperty("webdriver.chrome.driver", "XXXXXXX\\chromedriver.exe");
        return new ChromeDriver(options);
    }

    private WebDriver getEdgeDriver() {
        EdgeOptions options = new EdgeOptions();
        getChromiumOptions(options);
        log.info(options.toString());
        System.setProperty("webdriver.edge.driver", "XXXXXXX\\msedgedriver.exe");
        return new EdgeDriver(options);
    }

    private WebDriver getFirefoxDriver() {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-private");
        log.info(options.toString());
        System.setProperty("webdriver.gecko.driver", "XXXXXXX\\geckodriver.exe");
        return new FirefoxDriver(options);
    }

    @SneakyThrows
    private void steps(WebDriver driver) {
        driver.get(
            "https://self-onboarding.eservice.pl/?_gl=1*18p4s1f*_ga*MTgxNTc3Mjk0NS4xNjc1NDI5MTI4*_ga_SJNHHWB53W*MTY3ODcyNjYzOS4yLjEuMTY3ODcyNjY0NC4wLjAuMA..&_ga=2.253928904.1705791648.1678726642-1815772945.1675429128#!/p=1");
        Thread.sleep(2000);
        WebElement input = driver.findElement(By.xpath("//input[@name='email']"));

        String insertString1 = "ALA ąźćńłóę";
        input.sendKeys(insertString1);
        log.info("input.sendKeys(\"" + insertString1 + "\")");
        ScreenShotUtils.saveScreenShot(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES));
        log.info("input.getText() = " + input.getAttribute("value"));

        String insertString2 = "BABA żęóśłźćń";
        input.sendKeys(insertString2);
        log.info("input.sendKeys(\"" + insertString2 + "\")");
        ScreenShotUtils.saveScreenShot(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES));
        log.info("input.getText() = " + input.getAttribute("value"));

        Assert.assertEquals(input.getAttribute("value"), insertString1 + insertString2);

        driver.quit();
    }

}
```

### Relevant log output

```shell
Started by user XXXXXXXXXXXXXXX
Running as SYSTEM
Building on the built-in node in workspace X:\Workspace\Regression
[Regression] $ cmd.exe /C "C:\devtools\maven\bin\mvn.cmd -Dtest=PolishCharactersTest test "-Dkey=****" && exit %%ERRORLEVEL%%"
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.example:testAuto >------------------------
[INFO] Building testAuto 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testAuto ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 19 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ testAuto ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ testAuto ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ testAuto ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M7:test (default-test) @ testAuto ---
[INFO] Using auto detected provider org.apache.maven.surefire.testng.TestNGProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running PolishCharactersTest
2023-03-13 17:46:35 [INFO ] PolishCharactersTest:66 - Capabilities {browserName: chrome, goog:chromeOptions: {args: [--incognito, --proxy-server=XXXXXXXXXXXXXXX, --proxy-bypass-list=*XXXXXX..., --remote-allow-origins=*], extensions: []}}
Starting ChromeDriver 110.0.5481.77 (65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}) on port 53498
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1678726000.489][WARNING]: virtual void DevToolsClientImpl::AddListener(DevToolsEventListener *) subscribing a listener to the already connected DevToolsClient. Connection notification will not arrive.
mar 13, 2023 5:46:40 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
mar 13, 2023 5:46:40 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 110, so returning the closest version found: 106
mar 13, 2023 5:46:40 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 110 of 106
2023-03-13 17:46:45 [INFO ] PolishCharactersTest:110 - input.sendKeys("ALA ąźćńłóę")
2023-03-13 17:46:45 [INFO ] PolishCharactersTest:112 - input.getText() = ńłóę
2023-03-13 17:46:46 [INFO ] PolishCharactersTest:116 - input.sendKeys("BABA żęóśłźćń")
2023-03-13 17:46:46 [INFO ] PolishCharactersTest:118 - input.getText() = ńłóęóśłń




2023-03-13 17:46:47 [INFO ] PolishCharactersTest:74 - Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [--incognito, --proxy-server=XXXXXXXXXXXXXX, --proxy-bypass-list=XXXXXX..., --remote-allow-origins=*], extensions: []}}
Starting Microsoft Edge WebDriver 110.0.1587.41 (dec2c0803210602702555b3ee7cdbf59c9a7eb17) on port 59585
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
[1678726013.177][WARNING]: virtual void DevToolsClientImpl::AddListener(DevToolsEventListener *) subscribing a listener to the already connected DevToolsClient. Connection notification will not arrive.
mar 13, 2023 5:46:53 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
mar 13, 2023 5:46:53 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 110, so returning the closest version found: 106
mar 13, 2023 5:46:53 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 110 of 106
2023-03-13 17:46:58 [INFO ] PolishCharactersTest:110 - input.sendKeys("ALA ąźćńłóę")
2023-03-13 17:46:59 [INFO ] PolishCharactersTest:112 - input.getText() = ńłóę
2023-03-13 17:46:59 [INFO ] PolishCharactersTest:116 - input.sendKeys("BABA żęóśłźćń")
2023-03-13 17:47:00 [INFO ] PolishCharactersTest:118 - input.getText() = ńłóęęóśłń




2023-03-13 17:47:00 [INFO ] PolishCharactersTest:96 - Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [-headless, --window-size=1920,1080, user-agent=Mozilla/5.0 (Win..., -private]}, proxy: Proxy(manual, http=10.52.1....}
1678726020540	geckodriver	INFO	Listening on 127.0.0.1:50377
1678726020651	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-headless" "--window-size=1920,1080" "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-private" "--remote-debugging-port" "55085" "--remote-allow-hosts" "localhost" "--remote-allow-origins" "http://127.0.0.1:55085/,http://localhost:55085/,http://[::1]:55085/" "-no-remote" "-profile" "C:\\Users\\QA_AUT~1\\AppData\\Local\\Temp\\rust_mozprofilevsjFRI"
*** You are running in headless mode.
console.warn: services.settings: Ignoring preference override of remote settings server
console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
1678726022188	Marionette	INFO	Marionette enabled
Dynamically enable window occlusion 0
1678726022197	Marionette	INFO	Listening on port 58227
Read port: 58227
console.error: "Warning: unrecognized command line flag -window-size\n"
WebDriver BiDi listening on ws://127.0.0.1:55085
1678726022546	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
1678726022676	RemoteAgent	INFO	Proxy settings initialised: {"proxyType":"manual","httpProxy":"XXXXXXXXXXXXXX","noProxy":["XXXXXXce.local"],"sslProxy":"XXXXXXXXXXXXXX"}
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
console.error: Region.sys.mjs: "Error fetching region" (new SyntaxError("JSON.parse: unexpected character at line 1 column 1 of the JSON data", ""))
console.error: Region.sys.mjs: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.sys.mjs", 416))
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\QA_AUT~1\\AppData\\Local\\Temp\\rust_mozprofilevsjFRI\\search.json.mozlz4", (void 0)))
console.error: (new Error("Unexpected content-type \"text/html; charset=UTF-8\"", "resource://services-settings/Utils.jsm", 407))
DevTools listening on ws://127.0.0.1:55085/devtools/browser/86792d34-23da-41a3-81b1-cce047d4165c
mar 13, 2023 5:47:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
2023-03-13 17:47:12 [INFO ] PolishCharactersTest:110 - input.sendKeys("ALA ąźćńłóę")
2023-03-13 17:47:12 [INFO ] ScreenShotUtils:56 - Screenshot in file: ./target/screenshots/2023_03_13_17_47_12cf33ffd4-73ab-4498-8a7a-e2c49eb00649.png
2023-03-13 17:47:12 [INFO ] PolishCharactersTest:112 - input.getText() = ALA ąźćńłóę
2023-03-13 17:47:12 [INFO ] PolishCharactersTest:116 - input.sendKeys("BABA żęóśłźćń")
2023-03-13 17:47:13 [INFO ] ScreenShotUtils:56 - Screenshot in file: ./target/screenshots/2023_03_13_17_47_1337dfc3da-2b52-4261-83f4-7e7b186bc60f.png
2023-03-13 17:47:13 [INFO ] PolishCharactersTest:118 - input.getText() = ALA ąźćńłóęBABA żęóśłźćń
1678726033390	Marionette	INFO	Stopped listening on port 58227
Dynamically enable window occlusion 1
WARNING: A blocker encountered an error while we were waiting.
          Blocker:  Waiting for ping task
          Phase: TelemetryController: Waiting for pending ping activity
          State: (none)
WARNING: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
WARNING: addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:727:15
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:523:26
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:458:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1548:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1568:16
@resource://gre/modules/osfile.jsm:12:30
@resource://gre/modules/TelemetryStorage.sys.mjs:10:28
_checkPendingPings@resource://gre/modules/TelemetrySend.sys.mjs:863:17
setup@resource://gre/modules/TelemetrySend.sys.mjs:803:18
setup@resource://gre/modules/TelemetrySend.sys.mjs:241:30
setupTelemetry/this._delayedInitTask<@resource://gre/modules/TelemetryControllerParent.sys.mjs:829:36
observe@resource://gre/modules/AsyncShutdown.sys.mjs:576:16

WARNING: A blocker encountered an error while we were waiting.
          Blocker:  Waiting for ping task
          Phase: TelemetryController: Waiting for pending ping activity
          State: (none)
WARNING: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
WARNING: addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:727:15
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:523:26
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:458:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1548:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1568:16
@resource://gre/modules/osfile.jsm:12:30
@resource://gre/modules/TelemetryStorage.sys.mjs:10:28
_checkPendingPings@resource://gre/modules/TelemetrySend.sys.mjs:863:17
setup@resource://gre/modules/TelemetrySend.sys.mjs:803:18
setup@resource://gre/modules/TelemetrySend.sys.mjs:241:30
setupTelemetry/this._delayedInitTask<@resource://gre/modules/TelemetryControllerParent.sys.mjs:829:36
observe@resource://gre/modules/AsyncShutdown.sys.mjs:576:16

WARNING: A blocker encountered an error while we were waiting.
          Blocker:  Waiting for ping task
          Phase: TelemetryController: Waiting for pending ping activity
          State: (none)
WARNING: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
WARNING: addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:727:15
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:523:26
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:458:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1548:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1568:16
@resource://gre/modules/osfile.jsm:12:30
@resource://gre/modules/TelemetryStorage.sys.mjs:10:28
_checkPendingPings@resource://gre/modules/TelemetrySend.sys.mjs:863:17
setup@resource://gre/modules/TelemetrySend.sys.mjs:803:18
setup@resource://gre/modules/TelemetrySend.sys.mjs:241:30
setupTelemetry/this._delayedInitTask<@resource://gre/modules/TelemetryControllerParent.sys.mjs:829:36
observe@resource://gre/modules/AsyncShutdown.sys.mjs:576:16

WARNING: A blocker encountered an error while we were waiting.
          Blocker:  TelemetryController: shutting down
          Phase: profile-before-change-telemetry
          State: Error getting state: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange" at addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:727:15
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:523:26
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:458:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1548:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1568:16
@resource://gre/modules/osfile.jsm:12:30
@resource://gre/modules/TelemetryStorage.sys.mjs:10:28
_checkPendingPings@resource://gre/modules/TelemetrySend.sys.mjs:863:17
setup@resource://gre/modules/TelemetrySend.sys.mjs:803:18
setup@resource://gre/modules/TelemetrySend.sys.mjs:241:30
setupTelemetry/this._delayedInitTask<@resource://gre/modules/TelemetryControllerParent.sys.mjs:829:36
observe@resJource://gre/modules/AsyncShutdown.sys.mjas:v57a6:S16c
r
iWAptR NeIrNGr:o Errr:or : rPheasse o"purorficlee-b:ef/or/e-gchranege/" miso dfinuislheed,s/Async Shitu is ttoo ladteo town r.egsisytesr .commpjletion condition "OS.File: flush I/O queued before profileBeforeChange"
WARNING: addBlocker@resource:/s/g,re /molduilens/eAs y7ncS2hu7tdown.sys.mjs:727:15
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:523:26
addBlocker@resource://gre/modules/AsyncShutdown.sys.mjs:458:15
setupShutdown@resource://gre/modules/osfile/osfile_async_front.jsm:1548:28
@resource://gre/modules/osfile/osfile_async_front.jsm:1568:16
@resource://gre/modules/osfile.jsm:12:30:
@resource://gre/modu lEesr/rToerl:e mPehtarsyeS t"oprraogfei.lsey-s.before-changem" ijss :f1i0n:i2s8h
e
d_,c hietc isk Pteonod ilnagtPei ntgos @rreegsister completoiuornc ec:o/n/dgirtei/omno d"uOlSe.sF/iTleel:e mfeltursyhS eIn/dO. sqyuse.umejds :b8e6f3o:r1e7 
p
rsoeftiulpe@BreefsooruerCchea:n/g/eg"r
e
/JmaovdauSlcersi/pTte leermreotrr:y Sreensdo.usrycse.:m/j/sg:r8e0/3m:o1d8u
l
esse/tAuspy@nrceSshouutrdcoew:n/./sgys.mjs,re /linme o727d:u lEers/rToerl:e mPehtarsyeS e"npdr.osfyisl.em-jbse:for2e4-1c:h3a0
n
gseetup"Te lemietsry/ thfisi._delanyediInsitThaske<@dre,so uircte:/ /gires/m odtuleos/Toele meltraytCeo nttrool lerrPaeregnt.isyss.mjts:8e29:r36
 
ocbseorvem@rpesolurcee:/t/giroen/ mcoodnudlies/tAsyincoShnu t"dOoSw.nF.islyes:. mfjlsu:s5h7 6I:/1O6
 

queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.sys.mjs, line 727: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.sys.mjs, line 727: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.sys.mjs, line 727: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
JavaScript error: resource://gre/modules/AsyncShutdown.sys.mjs, line 727: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange"
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 43.948 s <<< FAILURE! - in ztestowania.PolishCharactersTest
[ERROR] ztestowania.PolishCharactersTest.testChrome  Time elapsed: 12.063 s  <<< FAILURE!
java.lang.AssertionError: expected [ALA ąźćńłóęBABA żęóśłźćń] but found [ńłóęóśłń]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:655)
	at org.testng.Assert.assertEquals(Assert.java:665)
	at ztestowania.PolishCharactersTest.steps(PolishCharactersTest.java:120)
	at ztestowania.PolishCharactersTest.testChrome(PolishCharactersTest.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:111)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[ERROR] ztestowania.PolishCharactersTest.testEdge  Time elapsed: 12.733 s  <<< FAILURE!
java.lang.AssertionError: expected [ALA ąźćńłóęBABA żęóśłźćń] but found [ńłóęęóśłń]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:655)
	at org.testng.Assert.assertEquals(Assert.java:665)
	at ztestowania.PolishCharactersTest.steps(PolishCharactersTest.java:120)
	at ztestowania.PolishCharactersTest.testEdge(PolishCharactersTest.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:111)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PolishCharactersTest.testChrome:28->steps:120 expected [ALA ąźćńłóęBABA żęóśłźćń] but found [ńłóęóśłń]
[ERROR]   PolishCharactersTest.testEdge:33->steps:120 expected [ALA ąźćńłóęBABA żęóśłźćń] but found [ńłóęęóśłń]
[INFO] 
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.592 s
[INFO] Finished at: 2023-03-13T17:47:17+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project testAuto: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Workspace\Regression\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE
```

### Operating System

Windows Server 2019 Standard; Windows 10

### Selenium version

Java 11, Selenium 4.5.0, TestNG 7.5

### What are the browser(s) and version(s) where you see this issue?

Chrome 110, Edge 110

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.77; Edge WebDriver 110.0.1587.41

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Not really sure what is required from Selenium? If you mention that it works on the command line but not in the other mode, it shows that is an environment issue, which might be addressed in the Jenkins community support group?

**Comment by testermarcinf** [comment]
I reported a bug here because the sendKeys method treats the string "ą" as CRTL+a. I don't know what it comes from. I don't know how to fix it.

**Comment by titusfortner** [comment]
Does it work in Firefox?

**Comment by diemol** [comment]
And also you are mentioning it works in a given environment and in a different one it does not, which could hint issues with the environment. Trying out with a different browser is also a good idea.

**Comment by testermarcinf** [comment]
> Does it work in Firefox?

Yes, it work in FF.

**Comment by diemol** [comment]
Good, that is progress, so it means it is an issue in Chrome. I will leave some links below which you can use to report the issue to them.
