### ISSUE TITLE
[🐛 Bug]: Error when executing scripts in different virtual machines and the machine is not active

### ISSUE THREAD

**Issue by Luciano1689** [SeleniumHQ/selenium#11779]
### What happened?

We migrated selenium web driver version from 3.14 to 4.8.1 to use Edge IE mode. When I run my jenkins script on different virtual machines it is giving an error.The scripts in version 3.14 worked correctly. And it only gives us the error when the machine is not active.

### How can we reproduce the issue?

```shell
public WebDriver inicializarIE() throws Exception{		
		WebDriver driver=null;
		try {
			System.setProperty("webdriver.ie.driver", "src/main/java/utilerias/IEDriverServer.exe");
			InternetExplorerOptions ieOptions = new InternetExplorerOptions();
			ieOptions.attachToEdgeChrome();
			ieOptions.ignoreZoomSettings();			
			driver = new InternetExplorerDriver(ieOptions);
		}catch(Exception e) {
			parametros.getLog().getLogger().error("ERROR INICIALIZANDO EL DRIVER");
			parametros.getLog().getLogger().error("ERROR -- > " + e.getMessage());
			parametros.setError(true);
			throw e;
		}
		return driver;
	}
```

### Relevant log output

```shell
2023-03-13 09-17-18 | ERROR | Menu:180 | ERROR INICIALIZANDO EL DRIVER
2023-03-13 09-17-18 | ERROR | Menu:181 | ERROR -- > Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'VIR22P0053W106', ip: '172.20.232.10'
2023-03-13 09-17-18 | ERROR | Tareas:25 | ERROR EN LA TAREA --> MENU
2023-03-13 09-17-18 | ERROR | Tareas:26 | ERROR --> Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'VIR22P0053W106', ip: '172.20.232.10'
2023-03-13 09-17-18 | ERROR | Tareas:27 | org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'VIR22P0053W106', ip: '172.20.232.10'
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'VIR22P0053W106', ip: '172.20.232.10'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:553)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:228)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:181)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:168)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:145)
	at tareas.menu.Menu.inicializarIE(Menu.java:178)
	at tareas.menu.Menu.ingresoDatos(Menu.java:160)
	at tareas.Tareas.ingreso(Tareas.java:20)
	at tareas.empresa.inscripcionCEWs.RegistroEmpresaArmadoCsv.ingresarSiguienteFuncionalidad(RegistroEmpresaArmadoCsv.java:29)
	at tareas.Tareas.ingreso(Tareas.java:23)
	at tareas.menu.Menu.ingresarSiguienteFuncionalidad(Menu.java:85)
	at tareas.Tareas.ingreso(Tareas.java:23)
	at tareas.Ejecutar.ingresar(Ejecutar.java:62)
	at tareas.EjecutarCaso.ejecutarCaso(EjecutarCaso.java:33)
	at test.empresa.inscripcionEmpresa.OK.caso005.Test005.ejecutarCaso(Test005.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_292'
Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:124)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535)
	... 27 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 40 more
2023-03-13 09-17-18 | INFO  | Menu:212 | error en cerrar el navegador
2023-03-13 09-17-18 | ERROR | EjecutarCaso:37 | EL CASO TERMINO CON ERRROR
```

### Operating System

Windows 10

### Selenium version

Java 1.8 Selenium 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Edge Versión 108.0.1462.54

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 32 bits 4.8.1.0

**Comment by diemol** [comment]
Seems this is a known issue in IE Mode in Edge, where the user needs to be logged in order to have WebDriver sessions work well. I believe it is reported already to the Edge developers, however I will leave you some links below so you can head over there to check and report it if needed.
