### ISSUE TITLE
[🐛 Bug]: Selenium Grid Server 4.8.1 fails to create InternetExplorer session

### ISSUE THREAD

**Issue by rbourga** [SeleniumHQ/selenium#11775]
### What happened?

Given that I have:
1.  Started **Selenium Standalone 4.8.1** (revision 8ebccac989);
2.  Donwloaded latest version of WebDriver InternetExplorerDriver (IEDriverServer_Win32_4.8.1) and made sure that this is available on my %PATH%;

When I:
 Send the following IE Session request

```
  [Capabilities {acceptInsecureCerts: false, browserName: internet explorer, proxy: {proxyType: SYSTEM}, se:ieOptions: {ie.edgechromium: true, ie.fileUploadDialogTimeout: 1000, initialBrowserUrl: https://www.bing.com/}}, Capabilities {acceptInsecureCerts: false, browserName: internet explorer, proxy: {proxyType: system}, se:ieOptions: {ie.edgechromium: true, ie.fileUploadDialogTimeout: 1000, initialBrowserUrl: https://www.bing.com/}}]
```

Then it fails with:
```
11:02:17.427 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. null
11:02:17.442 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. null
11:02:17.443 WARN [SeleniumSpanExporter$1.lambda$export$1] - java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.util.TreeMap.getEntry(TreeMap.java:345)
        at java.base/java.util.TreeMap.containsKey(TreeMap.java:233)
        at java.base/java.util.Collections$UnmodifiableMap.containsKey(Collections.java:1500)
        at org.openqa.selenium.grid.node.config.SessionCapabilitiesMutator.apply(SessionCapabilitiesMutator.java:61)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:118)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:69)
        at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
        at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:384)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:818)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:779)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**The operation is successful when using version 4.8.0:**
```
13:13:18.342 INFO [Standalone.execute] - Started Selenium Standalone 4.8.0 (revision 267030adea): http://192.168.1.104:4444
13:13:31.229 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
 [Capabilities {acceptInsecureCerts: false, browserName: internet explorer, proxy: {proxyType: SYSTEM}, se:ieOptions: {ie.edgechromium: true, ie.fileUploadDialogTimeout: 1000, initialBrowserUrl: https://www.bing.com/}}, Capabilities {acceptInsecureCerts: false, browserName: internet explorer, proxy: {proxyType: system}, se:ieOptions: {ie.edgechromium: true, ie.fileUploadDialogTimeout: 1000, initialBrowserUrl: https://www.bing.com/}}]
Started InternetExplorerDriver server (32-bit)
4.8.1.0
Listening on port 34007
Only local connections are allowed
```

Also please note that I can start a local IE 4.8.1 session successfully locally, i.e., without going via the Selenium Grid 4.8.1.

### How can we reproduce the issue?

```shell
See description of issue above.
```

### Relevant log output

```shell
11:02:17.448 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "ba7267ecd8cfc92eba7930517dd9cc5c","eventTime": 1678849337427586800,"eventName": "exception","attributes": {"exception.message": "Error while creating session with the driver service. null","exception.stacktrace": "java.lang.NullPointerException\r\n\tat java.base\u002fjava.util.Objects.requireNonNull(Objects.java:208)\r\n\tat java.base\u002fjava.util.TreeMap.getEntry(TreeMap.java:345)\r\n\tat java.base\u002fjava.util.TreeMap.containsKey(TreeMap.java:233)\r\n\tat java.base\u002fjava.util.Collections$UnmodifiableMap.containsKey(Collections.java:1500)\r\n\tat org.openqa.selenium.grid.node.config.SessionCapabilitiesMutator.apply(SessionCapabilitiesMutator.java:61)\r\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:118)\r\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:69)\r\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)\r\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:384)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:818)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:779)\r\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:833)\r\n","exception.type": "java.lang.NullPointerException"}}

11:02:17.454 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "ba7267ecd8cfc92eba7930517dd9cc5c","eventTime": 1678849337451571000,"eventName": "Unable to create session with the driver","attributes": {"current.session.count": 0,"logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {acceptInsecureCerts: false, browserName: internet explorer, proxy: {proxyType: SYSTEM}, se:ieOptions: {ie.edgechromium: true, ie.fileUploadDialogTimeout: 1000, initialBrowserUrl: https:\u002f\u002fwww.bing.com\u002f}}","session.request.downstreamdialect": "[OSS, W3C]"}}
```

### Operating System

Windows 10.

### Selenium version

4.8.1

### What are the browser(s) and version(s) where you see this issue?

Edge 111.0.1661.41 (Official build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer_Win32_4.8.1

### Are you using Selenium Grid?

4.8.1

**Comment by diemol** [comment]
This has been fixed in https://github.com/SeleniumHQ/selenium/commit/ed0fe601775a35432e2492a5d9b0952eb9ce9ed2 and will be available in 4.9.0 soon.
