### ISSUE TITLE
[🐛 Bug]: [JS]: java.util.concurrent.TimeoutException on attempt to async reading of more than 15 elements.

### ISSUE THREAD

**Issue by StanislavKharchenko** [SeleniumHQ/selenium#11789]
### What happened?

The issue is that WebDriver caught an exception on attempt to resolve a more than 15 promises of "getAttribute" reading.
Workaround:
- read attributes in synchronous manner (just await each element one by one);
- array contains not more than 15 web elements
- run using session created by Driver.createSession for e.g. chromedriver binary directly (not using selenium hosted server)
- run using selenoid

Please also note, that issue reproduced very often, but not in 100% cases. I noticed that very rarely but not reproduced.

### How can we reproduce the issue?

```shell
const arrElements = await driver.findElements(By.xpath('//someXpathHere'));
const attResults = [];

for (const element of arrElements) {
    attResults.push(element.getAttribute('textContent'));
}

await Promise.all(attResults); --> exception will be here
```

### Relevant log output

```shell
ScriptTimeoutError: Unable to execute request for an existing session: java.net.ConnectException
    at Object.throwDecodedError (C:\**\node_modules\selenium-webdriver\lib\error.js:524:15)
    at parseHttpResponse (C:\**\node_modules\selenium-webdriver\lib\http.js:587:13)
    at Executor.execute (C:\**\node_modules\selenium-webdriver\lib\http.js:515:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at WebDriver.execute (C:\**\node_modules\selenium-webdriver\lib\webdriver.js:741:17)
    at async Promise.all (index 13)
    at WbcSelectMultiDropDown.getDropDownContent (C:\**\src\app\elements\dropDowns\wbcSelect\wbcSelectLookup.ts:48:23)
    at SetupHISLabelPrintingTable.step16 (C:\**\src\testCases\app\regression\setup\hisLabelPrinting\45554IS-SetupHISLabelPrintingTable.ts:493:28)
    at C:\**\node_modules\**\cmnWrapper.ts:21:28 {
  remoteStacktrace: 'java.lang.RuntimeException: Unable to execute request for an existing session: java.net.ConnectException\r\n' +
    '\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:151)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\r\n' +
    '\tat org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)\r\n' +
    '\tat org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)\r\n' +
    '\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\r\n' +
    '\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\r\n' +
    '\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n' +
    '\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n' +
    '\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n' +
    '\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n' +
    '\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\r\n' +
    '\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)\r\n' +
    '\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\r\n' +
    '\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\r\n' +
    '\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\r\n' +
    '\tat java.base/java.lang.Thread.run(Thread.java:1589)\r\n' +
    'Caused by: java.net.ConnectException\r\n' +
    '\tat java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:846)\r\n' +
    '\tat java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)\r\n' +
    '\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:292)\r\n' +
    '\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\r\n' +
    '\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)\r\n' +
    '\tat org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)\r\n' +
    '\tat org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:127)\r\n' +
    '\tat org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:472)\r\n' +
    '\tat org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\r\n' +
    '\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n' +
    '\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n' +
    '\tat org.openqa.selenium.grid.node.Node.execute(Node.java:248)\r\n' +
    '\tat org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:59)\r\n' +
    '\tat org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:72)\r\n' +
    '\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)\r\n' +
    '\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:122)\r\n' +
    '\t... 32 more\r\n' +
    'Caused by: java.net.ConnectException\r\n' +
    '\tat java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1045)\r\n' +
    '\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:224)\r\n' +
    '\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:259)\r\n' +
    '\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:235)\r\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)\r\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)\r\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\r\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)\r\n' +
    '\t... 3 more\r\n' +
    'Caused by: java.nio.channels.ClosedChannelException\r\n' +
    '\tat java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:202)\r\n' +
    '\tat java.base/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:786)\r\n' +
    '\tat java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:874)\r\n' +
    '\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:208)\r\n' +
    '\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:569)\r\n' +
    '\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:210)\r\n' +
    '\t... 9 more\r\n',
```

### Operating System

Windows 10

### Selenium version

Selenium for javascript binding: 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Edge 111.0.1661.43

### What are the browser driver(s) and version(s) where you see this issue?

Edgedriver 111.0.1661.43

### Are you using Selenium Grid?

Selenium server 4.8.1

**Comment by titusfortner** [comment]
The current WebDriver implementation is inherently synchronous, so I think the expectation is that even in JS things be called synchronously, and if you can make it work otherwise that is outside what we explicitly support. @AutomatedTester / @pujagani please chime in if you think that's not accurate.

For getAttribute specifically, it is currently implemented with a large javascript execution, so it somewhat makes sense that it will take longer than other commands. Perhaps you can get what you want by calling the supported endpoints directly using `getDomAttribute()` or `getProperty()`
