### ISSUE TITLE
[🐛 Bug]: Using IEServerDriver to drive ie mode fails

### ISSUE THREAD

**Issue by iamxiaojianzheng** [SeleniumHQ/selenium#11834]
### What happened?

When IEDriverServer is used to drive edge to start, the init url is opened, but the subsequent process cannot continue. The browser seems to be blocking.

### How can we reproduce the issue?

```shell
public class IEModeEdgeTest {

    @Test
    public void test() {
        InternetExplorerDriverService service = new InternetExplorerDriverService.Builder()
            .withLogLevel(InternetExplorerDriverLogLevel.TRACE).build();
        InternetExplorerOptions options = new InternetExplorerOptions();
        options.attachToEdgeChrome();
        options.ignoreZoomSettings();
        options.withInitialBrowserUrl("https://bing.com");
        ieDriver = new InternetWebDriver(new InternetExplorerDriver(service, options));

        driver.get("https://bing.com");
    }

}
```

### Relevant log output

```shell
I 2023-03-29 17:03:23:437 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(88) Starting WebDriver server on port: '24732' on host: ''
T 2023-03-29 17:03:23:437 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(738) Entering Server::PopulateCommandRepository
T 2023-03-29 17:03:23:437 C:\projects\seleniumhq\selenium\cpp\iedriver\IEServer.cpp(32) Entering IEServer::IEServer
I 2023-03-29 17:03:23:437 C:\projects\seleniumhq\selenium\cpp\iedriver\IEServer.cpp(33) Driver version: 4.8.1.0 (32-bit)
T 2023-03-29 17:03:23:437 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(180) Entering Server::Start
Started InternetExplorerDriver server (32-bit)
4.8.1.0
Listening on port 24732
Log level is set to TRACE
Only local connections are allowed
T 2023-03-29 17:03:23:554 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(234) Entering Server::ProcessRequest
T 2023-03-29 17:03:23:554 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(243) Process request with: URI: /status HTTP verb: GET
body: {}
T 2023-03-29 17:03:23:554 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(334) Entering Server::DispatchCommand
T 2023-03-29 17:03:23:554 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(687) Entering Server::LookupCommand
D 2023-03-29 17:03:23:554 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(343) Command: GET /status {}
T 2023-03-29 17:03:23:554 C:\projects\seleniumhq\selenium\cpp\iedriver\IEServer.cpp(51) Entering IEServer::GetStatus
T 2023-03-29 17:03:23:556 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(81) Entering Response::SetSuccessResponse
T 2023-03-29 17:03:23:556 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(87) Entering Response::SetResponse
T 2023-03-29 17:03:23:556 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(60) Entering Response::Serialize
D 2023-03-29 17:03:23:556 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(426) Response: {
        "value" :
        {
                "build" :
                {
                        "version" : "4.8.1.0 (32-bit)"
                },
                "message" : "Ready to create session",
                "os" :
                {
                        "arch" : "x64",
                        "name" : "windows",
                        "version" : "10.0.19041.1741 (WinBuild.160101.0800)"
                },
                "ready" : true
        }
}
T 2023-03-29 17:03:23:556 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(479) Entering Server::SendResponseToClient
T 2023-03-29 17:03:23:556 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(30) Entering Response::Deserialize
T 2023-03-29 17:03:23:556 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(540) Entering Server::SendHttpOk
T 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(234) Entering Server::ProcessRequest
T 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(298) Entering Server::ReadRequestBody
T 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(243) Process request with: URI: /session HTTP verb: POST
body: {
  "desiredCapabilities": {
    "se:ieOptions": {
      "ie.edgechromium": true,
      "initialBrowserUrl": "https:\u002f\u002fbing.com",
      "ignoreZoomSetting": true
    },
    "browserName": "internet explorer"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "internet explorer",
        "se:ieOptions": {
          "ie.edgechromium": true,
          "initialBrowserUrl": "https:\u002f\u002fbing.com",
          "ignoreZoomSetting": true
        }
      }
    ]
  }
}
T 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(334) Entering Server::DispatchCommand
T 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(687) Entering Server::LookupCommand
D 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(343) Command: POST /session {
  "desiredCapabilities": {
    "se:ieOptions": {
      "ie.edgechromium": true,
      "initialBrowserUrl": "https:\u002f\u002fbing.com",
      "ignoreZoomSetting": true
    },
    "browserName": "internet explorer"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "internet explorer",
        "se:ieOptions": {
          "ie.edgechromium": true,
          "initialBrowserUrl": "https:\u002f\u002fbing.com",
          "ignoreZoomSetting": true
        }
      }
    ]
  }
}
T 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\iedriver\IEServer.cpp(42) Entering IEServer::InitializeSession
T 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\iedriver\IESession.cpp(45) Entering IESession::Initialize
D 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\iedriver\IESession.cpp(60) Mutex acquired for session initalization
T 2023-03-29 17:03:23:668 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(922) Entering IECommandExecutor::ThreadProc
T 2023-03-29 17:03:23:675 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(75) Entering IECommandExecutor::OnCreate
T 2023-03-29 17:03:23:675 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1707) Entering IECommandExecutor::PopulateElementFinderMethods
T 2023-03-29 17:03:23:675 C:\projects\seleniumhq\selenium\cpp\iedriver\InputManager.cpp(56) Entering InputManager::InputManager
T 2023-03-29 17:03:23:675 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1315) Entering BrowserFactory::GetEdgeExecutableLocation
T 2023-03-29 17:03:23:676 C:\projects\seleniumhq\selenium\cpp\iedriver\RegistryUtilities.cpp(49) Attempting to get registry value  from HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe
T 2023-03-29 17:03:23:676 C:\projects\seleniumhq\selenium\cpp\iedriver\RegistryUtilities.cpp(133) Retrieved value C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
T 2023-03-29 17:03:23:676 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1255) Entering BrowserFactory::GetIEExecutableLocation
T 2023-03-29 17:03:23:676 C:\projects\seleniumhq\selenium\cpp\iedriver\RegistryUtilities.cpp(49) Attempting to get registry value {1FD49718-1D00-4B19-AF5F-070AF6D5D54C} from HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\Ext\CLSID
T 2023-03-29 17:03:23:676 C:\projects\seleniumhq\selenium\cpp\iedriver\RegistryUtilities.cpp(133) Retrieved value 0
T 2023-03-29 17:03:23:676 C:\projects\seleniumhq\selenium\cpp\iedriver\RegistryUtilities.cpp(49) Attempting to get registry value  from HKEY_LOCAL_MACHINE\SOFTWARE\Classes\InternetExplorer.Application\CLSID
T 2023-03-29 17:03:23:678 C:\projects\seleniumhq\selenium\cpp\iedriver\RegistryUtilities.cpp(133) Retrieved value {0002DF01-0000-0000-C000-000000000046}
T 2023-03-29 17:03:23:678 C:\projects\seleniumhq\selenium\cpp\iedriver\RegistryUtilities.cpp(49) Attempting to get registry value  from HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0002DF01-0000-0000-C000-000000000046}\LocalServer32
T 2023-03-29 17:03:23:678 C:\projects\seleniumhq\selenium\cpp\iedriver\RegistryUtilities.cpp(133) Retrieved value "%ProgramFiles%\Internet Explorer\iexplore.exe"
T 2023-03-29 17:03:23:678 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1344) Entering BrowserFactory::GetIEVersion
T 2023-03-29 17:03:23:681 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlerRepository.cpp(110) Entering CommandHandlerRepository::PopulateCommandHandlers
T 2023-03-29 17:03:23:681 C:\projects\seleniumhq\selenium\cpp\iedriver\IESession.cpp(106) Created thread for command executor returns HWND: '00130676'
T 2023-03-29 17:03:23:681 C:\projects\seleniumhq\selenium\cpp\iedriver\IESession.cpp(110) Session id is retrived from command executor window: 'ecd4e14b-af50-40a9-b290-2731d1b8feb4'
D 2023-03-29 17:03:23:681 C:\projects\seleniumhq\selenium\cpp\iedriver\IESession.cpp(116) Releasing session initialization mutex
T 2023-03-29 17:03:23:681 C:\projects\seleniumhq\selenium\cpp\iedriver\IESession.cpp(198) Entering IESession::ExecuteCommand
T 2023-03-29 17:03:23:681 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(156) Entering IECommandExecutor::OnSetCommand
T 2023-03-29 17:03:23:682 C:\projects\seleniumhq\selenium\cpp\webdriver-server\command.cc(31) Entering Command::Deserialize
D 2023-03-29 17:03:23:682 C:\projects\seleniumhq\selenium\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {
  "desiredCapabilities": {
    "se:ieOptions": {
      "ie.edgechromium": true,
      "initialBrowserUrl": "https:\u002f\u002fbing.com",
      "ignoreZoomSetting": true
    },
    "browserName": "internet explorer"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "internet explorer",
        "se:ieOptions": {
          "ie.edgechromium": true,
          "initialBrowserUrl": "https:\u002f\u002fbing.com",
          "ignoreZoomSetting": true
        }
      }
    ]
  }
} }
T 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\webdriver-server\command.cc(31) Entering Command::Deserialize
D 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {
  "desiredCapabilities": {
    "se:ieOptions": {
      "ie.edgechromium": true,
      "initialBrowserUrl": "https:\u002f\u002fbing.com",
      "ignoreZoomSetting": true
    },
    "browserName": "internet explorer"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "internet explorer",
        "se:ieOptions": {
          "ie.edgechromium": true,
          "initialBrowserUrl": "https:\u002f\u002fbing.com",
          "ignoreZoomSetting": true
        }
      }
    ]
  }
} }
T 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(178) Entering IECommandExecutor::OnExecCommand
T 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(994) Entering IECommandExecutor::DispatchCommand
D 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1059) Executing command: newSession
D 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(48) Found W3C capabilities structure
T 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(183) Entering NewSessionCommandHandler::ValidateArguments
D 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(199) Validating alwaysMatch capability set
T 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(672) Entering NewSessionCommandHandler::ValidateCapabilities
D 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(673) Validating capabilities object
D 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(220) Validating firstMatch capability set with index 0
T 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(672) Entering NewSessionCommandHandler::ValidateCapabilities
D 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(673) Validating capabilities object
D 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(722) Found browserName capability. Validating value type is string.
D 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(989) Found se:ieOptions capability. Validating value type is object.
T 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(648) Entering NewSessionCommandHandler::MergeCapabilities
T 2023-03-29 17:03:23:705 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(274) Entering NewSessionCommandHandler::ProcessCapabilities
T 2023-03-29 17:03:23:706 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(589) Entering NewSessionCommandHandler::MatchCapabilities
D 2023-03-29 17:03:23:706 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(279) Processing matched capability set with index 0
T 2023-03-29 17:03:23:706 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability unhandledPromptBehavior
T 2023-03-29 17:03:23:706 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability pageLoadStrategy
T 2023-03-29 17:03:23:706 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(167) Entering NewSessionCommandHandler::GetPageLoadStrategyValue
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability strictFileInteractability
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability timeouts
W 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(105) Invalid capability setting: timeouts is type null instead of object. Default value will be used: null

T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(345) Entering NewSessionCommandHandler::SetTimeoutSettings
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(364) Entering NewSessionCommandHandler::SetBrowserFactorySettings
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ignoreProtectedModeSettings
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ignoreZoomSetting
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability browserAttachTimeout
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability initialBrowserUrl
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.forceCreateProcessApi
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.forceShellWindowsApi
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.browserCommandLineSwitches
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.ensureCleanSession
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.edgechromium
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.edgepath
T 2023-03-29 17:03:23:706 C:\projects\seleniumhq\selenium\cpp\iedriver\IESession.cpp(226) Beginning wait for response length to be not zero
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(121) Entering BrowserFactory::Initialize
D 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(131) path before was

D 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(133) path after was 06FFF218

T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(485) Entering NewSessionCommandHandler::SetInputSettings
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability nativeEvents
T 2023-03-29 17:03:23:739 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability elementScrollBehavior
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability requireWindowFocus
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability ie.fileUploadDialogTimeout
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(101) Entering NewSessionCommandHandler::GetCapability for capability enablePersistentHover
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\InputManager.cpp(82) Entering InputManager::Initialize
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(532) Entering NewSessionCommandHandler::CreateReturnedCapabilities
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1581) Entering IECommandExecutor::CreateNewBrowser
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(153) Entering BrowserFactory::LaunchBrowserProcess
D 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(157) Ignoring Protected Mode Settings: 0
D 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(160) Checking validity of Protected Mode settings.
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1363) Entering BrowserFactory::ProtectedModeSettingsAreValid
D 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1366) Detected IE version: 11, Windows version supports Protected Mode: 1
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1440) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1457) Found Protected Mode setting value of 0 for zone 1
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1440) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1457) Found Protected Mode setting value of 0 for zone 2
T 2023-03-29 17:03:23:786 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1440) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2023-03-29 17:03:23:790 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1457) Found Protected Mode setting value of 0 for zone 3
T 2023-03-29 17:03:23:790 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1440) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2023-03-29 17:03:23:790 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(1457) Found Protected Mode setting value of 0 for zone 4
D 2023-03-29 17:03:23:790 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(163) Has Valid Protected Mode Settings: 1
T 2023-03-29 17:03:23:790 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(239) Entering BrowserFactory::IsIELaunchURLAvailable
T 2023-03-29 17:03:23:822 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(141) Entering BrowserFactory::ClearCache
T 2023-03-29 17:03:23:822 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(382) Entering BrowserFactory::LaunchEdgeInIEMode
D 2023-03-29 17:03:23:822 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(383) Starting Edge Chromium from the command line
T 2023-03-29 17:03:23:823 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(404) 6EFCF598C:\Users\haigui\AppData\Local\Temp\IEDriver-a805052d-d5b2-45c8-94a1-febb2d6ef49f.
T 2023-03-29 17:03:23:823 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(428) IE starting command line is: 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --ie-mode-force --internet-explorer-integration=iemode --user-data-dir=C:\Users\haigui\AppData\Local\Temp\IEDriver-a805052d-d5b2-45c8-94a1-febb2d6ef49f --no-first-run --no-service-autorun --disable-sync --disable-features=msImplicitSignin --disable-popup-blocking --enable-features=msIEModeAlwaysWaitForUnload https://bing.com'.
D 2023-03-29 17:03:24:193 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(215) IE launched successfully with process ID 6444
D 2023-03-29 17:03:24:193 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(221) Process with ID 6444 is executing msedge.exe
T 2023-03-29 17:03:24:193 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(494) Entering BrowserFactory::AttachToBrowser
D 2023-03-29 17:03:24:193 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(504) Using Active Accessibility to find IWebBrowser2 interface
T 2023-03-29 17:03:24:193 C:\projects\seleniumhq\selenium\cpp\iedriver\BrowserFactory.cpp(555) Entering BrowserFactory::AttachToBrowserUsingActiveAccessibility
T 2023-03-29 17:06:23:664 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(234) Entering Server::ProcessRequest
T 2023-03-29 17:06:23:664 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(243) Process request with: URI: /shutdown HTTP verb: GET
body: {}
T 2023-03-29 17:06:23:664 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(540) Entering Server::SendHttpOk
T 2023-03-29 17:06:23:664 C:\projects\seleniumhq\selenium\cpp\iedriver\IEServer.cpp(88) Entering IEServer::ShutDown
T 2023-03-29 17:06:23:667 C:\projects\seleniumhq\selenium\cpp\iedriver\WebDriver.cpp(54) Entering StopServer
T 2023-03-29 17:06:23:667 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(225) Entering Server::Stop

Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: InternetExplorerDriver

Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Host info: host: 'DESKTOP-1Q32E2S', ip: '192.168.56.31'
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
        at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:153)
        at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:140)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:286)
        at com.haigui.qingting.script.SpireTest.beforeExecute(Script_e1498136f142b966b9c895f6fb59bd62.groovy:53)
        ... 13 common frames omitted
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: InternetExplorerDriver
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:124)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        ... 26 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
        ... 39 common frames omitted
```

### Operating System

Windows10

### Selenium version

Java 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Edge 108.0.1462.54

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.8.1 Win32

**Comment by iamxiaojianzheng** [comment]
The same code works fine for me in Windows 11.

**Comment by iamxiaojianzheng** [comment]
blocked here

![image](https://user-images.githubusercontent.com/29248764/228484255-449a49d0-f057-4172-b118-fce955588e54.png)
