### ISSUE TITLE
[🐛 Bug]: RemoteWebDriver failed while trying to upload file

### ISSUE THREAD

**Issue by parkhomchukp** [SeleniumHQ/selenium#11849]
### What happened?

I am trying to upload the file to the web application. The file size is like 4 gigabytes (that's the point, I guess).
My script looks like this:
``` python
elem = self.driver.find_element("//input[@type='file']")
elem.send_keys(f"/tmp/filename")
elem = self.driver.find_element("//button[@data-testid='upload-btn']")
elem.click()
```

### How can we reproduce the issue?

```shell
Upload large file via RemoteWebDriver.
```

### Relevant log output

```shell
Traceback (most recent call last):
File "/app/file.py", line 115, in <module>
 scenario.run()
File "/app/file.py", line 74, in run
elem.send_keys(f"/tmp/{distributable_name}")
File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webelement.py", line 475, in send_keys
value = self._upload(local_file)
File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webelement.py", line 708, in _upload
raise e

File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webelement.py", line 699, in _upload
 return self._execute(Command.UPLOAD_FILE, {'file': content})['value']
File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
return self._parent.execute(command, params)
File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: None
 Stacktrace:
at java.io.ByteArrayOutputStream.hugeCapacity (ByteArrayOutputStream.java:123)
at java.io.ByteArrayOutputStream.grow (ByteArrayOutputStream.java:117)
at java.io.ByteArrayOutputStream.ensureCapacity (ByteArrayOutputStream.java:93)
at java.io.ByteArrayOutputStream.write (ByteArrayOutputStream.java:153)
at com.google.common.io.ByteStreams.copy (ByteStreams.java:113)
at org.openqa.selenium.remote.http.HttpMessage.getContent (HttpMessage.java:140)
at org.openqa.selenium.remote.http.HttpRequest.getContent (HttpRequest.java:25)
at org.openqa.selenium.remote.http.HttpMessage.getContentString (HttpMessage.java:152)
at org.openqa.selenium.remote.http.HttpRequest.getContentString (HttpRequest.java:25)
 at org.openqa.selenium.remote.server.commandhandler.UploadFile.execute (UploadFile.java:47)
at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:235)
at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
at java.util.concurrent.FutureTask.run (FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
at java.lang.Thread.run (Thread.java:748)
```

### Operating System

Ubuntu

### Selenium version

3.141.0

### What are the browser(s) and version(s) where you see this issue?

selenium/standalone-chrome-debug

### What are the browser driver(s) and version(s) where you see this issue?

selenium/standalone-chrome-debug

**Comment by diemol** [comment]
Can you check with the latest version of Docker Selenium?

**Comment by diemol** [comment]
We do not support Selenium 3.x anymore.

**Comment by diemol** [comment]
I'm kindly closing this issue as we haven't received additional information. If you have further details to share or if there's anything else we can assist you with, please feel free to reach out.
