### ISSUE TITLE
Selenium grid Timeout issue with selenium version 4.2.2 - org.openqa.selenium.SessionNotCreatedException:

### ISSUE THREAD

**Issue by sumitsg004** [SeleniumHQ/selenium#11860]
### What happened?

Hi All, facing an issue with selenium 4.2.2 version, but it works fine with 3.141.59 version
facing issue particularly with selenium grid, works as expected with local run.
Error message -
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'L43511WIN', ip: '192.168.1.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, browserVersion: }], desiredCapabilities=Capabilities {acceptSslCerts: true, browserName: chrome, browserVer
sion: }}]
Capabilities {}
Caused by: java.lang.RuntimeException: NettyHttpHandler request execution error
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76)*

*Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to {hub url} after 180000 ms
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
Code -
driver = new RemoteWebDriver(new URL(remoteDriverConfig.getHubUrl()), capabilities);
Selenium grid is up and running - version 4.1.3
Selenium version - 4.2.2
OS - windows
Note that the same code works good with selenium 3.141.59 version
Can someone please help or suggest what might be issue ?

### How can we reproduce the issue?

```shell
Upgrading selenium from 3.141.59 to 4.2.2
```

### Relevant log output

```shell
Error message -
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'L43511WIN', ip: '192.168.1.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, browserVersion: }], desiredCapabilities=Capabilities {acceptSslCerts: true, browserName: chrome, browserVer
sion: }}]
Capabilities {}
Caused by: java.lang.RuntimeException: NettyHttpHandler request execution error
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76)*

*Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to {hub url} after 180000 ms
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
```

### Operating System

windows 10

### Selenium version

Selenium-java 4.2.2

### What are the browser(s) and version(s) where you see this issue?

chrome 111

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver - 111.0.5563.64

### Are you using Selenium Grid?

Selenium grid - 4.1.3

**Comment by diemol** [comment]
3.141.59 had broken timeouts so they were never being triggered. Also, we need a way to reproduce the issue.

**Comment by diemol** [comment]
Please use the most recent release.

**Comment by diemol** [comment]
Closing as we did not get more information.
