### ISSUE TITLE
[🐛 Bug]: Augmenting (Remote)WebDrivers for DevTools

### ISSUE THREAD

**Issue by Auto81** [SeleniumHQ/selenium#11892]
### What happened?

Java 11, Maven, IntelliJ
Chrome+Driver v112
Grid Hub+Node 4.8.3

Trying to Augment RemoteWebDriver fails and throws. Following example from [selenium ChromeDevTools](https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/#emulate-geo-location-with-the-remote-webdriver)

### How can we reproduce the issue?

```shell
pom here - https://gist.github.com/Auto81/4c3cb09a05ea7d901bd19e414cc205af  

@Test
  public void remoteChromeDriver() {
    System.setProperty("webdriver.http.factory", "jdk-http-client");

    WebDriver driver = new RemoteWebDriver(grid4Location, new ChromeOptions());
    driver.get("http://www.bbc.co.uk");

    //Browser is open and navigated to bbc correctly
    //fails here
    driver = new Augmenter().augment(driver);

    DevTools devTools = ((HasDevTools) driver).getDevTools();
    devTools.createSession();
  }
```

### Relevant log output

```shell
/Library/Java/JavaVirtualMachines/jdk-11.0.17.jdk/Contents/Home/bin/java...
Apr 13, 2023 1:10:17 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
Apr 13, 2023 1:10:34 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find CDP implementation matching 112

java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: URI must contain a host: ws:/session/cde4a2c6312e1bdbfe23c578353d5af0/se/cdpws:/session/cde4a2c6312e1bdbfe23c578353d5af0/se/cdp

	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.openSocket(JdkHttpClient.java:204)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:82)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:34)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$0(SeleniumCdpConnection.java:56)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:54)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:47)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:50)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:31)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:188)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:164)
```

### Operating System

MacOs

### Selenium version

Java 4.8.3

### What are the browser(s) and version(s) where you see this issue?

Chrome v112

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 112

### Are you using Selenium Grid?

Grid hub (java11 -Dwebdriver.http.factory=jdk-http-client -jar selenium-server-4.8.3.jar -—ext selenium-http-jdk-client-4.8.3.jar hub)
) and node (java11 -Dwebdriver.http.factory=jdk-http-client -jar selenium-server-4.8.3.jar --ext selenium-http-jdk-client-4.8.3.jar node --grid-url xxx.xxx.xxx.xxx)

**Comment by titusfortner** [comment]
My apologies, it looks like we never got to triaging this one ☹️ 

We have made some updates to how this is called, though, so please try the latest version of Selenium and let us know if it is still an issue.

**Comment by Auto81** [comment]
Hey thanks for catching now :) Looks to still be happening when using selenium docker as below, but not when running grid natively on box.

- Now using selenium docker 4.16.1/chrome 120 in grid mode as [here](https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#macoslinux)
- Java 21

Can see the hub get the request, and the node get assigned in the logs.

```
  @Test
  public void remoteChromeDriver() throws URISyntaxException, MalformedURLException {
    WebDriver driver = new RemoteWebDriver(new URI(String.format("http://%s", GRID_IP_PORT_ADDRESS)).toURL(), new ChromeOptions());
    driver.get("http://www.bbc.co.uk");

    //fails here
    driver = new Augmenter().augment(driver);
    DevTools devTools = ((HasDevTools) driver).getDevTools();
    devTools.createSession();
  }
```

Stack trace
```
org.openqa.selenium.remote.http.ConnectionFailedException: JdkWebSocket initial request execution error
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.2.1', java.version: '21.0.1'
Driver info: driver.version: unknown

Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:585)
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:532)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:452)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:592)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by diemol** [comment]
How are you starting the Docker container?

**Comment by Auto81** [comment]
from a fresh docker install with nothing im just doing the commands in [readme](https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#macoslinux)

1. `docker network create grid` in terminal
2. `docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub:4.16.1-20231219` in terminal
3. 
```
 docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
    --shm-size="2g" \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    selenium/node-chrome:4.16.1-20231219
``` 
in terminal

*EDIT: Happens on a windows docker grid setup too

**Comment by diemol** [comment]
You need to set the Grid URL https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout

**Comment by Auto81** [comment]
From that link (thanks) I cant see an example format that the SE_NODE_GRID_URL should be during the docker run command? i've tried empty, localhost, grid, selenium-hub, http://localhost:4444

```
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub --shm-size="2g" 
-e SE_EVENT_BUS_PUBLISH_PORT=4442 
-e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 
-e SE_NODE_GRID_URL=??????? 
selenium/node-chrome:4.16.1-20231219
```

**Comment by diemol** [comment]
You need to set there the Grid public URL, so the same you are entering in your test.

**Comment by Auto81** [comment]
Working with below, thanks

```
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub --shm-size="2g" 
-e SE_EVENT_BUS_PUBLISH_PORT=4442 
-e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 
-e SE_NODE_GRID_URL=http://<hostMachine>:4444 
selenium/node-chrome:4.16.1-20231219
```
