### ISSUE TITLE
[🐛 Bug]: Selenium Server 4.8.2 does not download the drivers and throws no drivers found in PATH exception

### ISSUE THREAD

**Issue by kv-naveen** [SeleniumHQ/selenium#11902]
### What happened?

Downloaded selenium-server-4.8.2.jar  and tried to setup standalone grid.  
Getting No drivers have been configured or have been found on PATH
It downloads the drivers by default when using 4.8.1

### How can we reproduce the issue?

```shell
Download selenium-server-4.8.2.jar  and try to setup standalone grid.
```

### Relevant log output

```shell
C:\Users\*******\Downloads>java -jar selenium-server-4.8.2.jar standalone
07:52:54.014 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
07:52:54.021 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
07:52:56.849 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
07:52:56.874 INFO [NodeOptions.discoverDrivers] - Driver(s) already present on the host: 0
07:52:56.881 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:159)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:215)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:48)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:254)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
        ... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:454)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:220)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:81)
        ... 22 more
```

### Operating System

Windows 10

### Selenium version

4.8.2 

### What are the browser(s) and version(s) where you see this issue?

NA

### What are the browser driver(s) and version(s) where you see this issue?

NA

### Are you using Selenium Grid?

4.8.2

**Comment by titusfortner** [comment]
We've decided that selenium manager should not yet be the default on Grid until it is out of beta. You may opt-in to using it when starting the grid with `--selenium-manager true`

**Comment by diemol** [comment]
Here are all the flags documented https://www.selenium.dev/documentation/grid/configuration/cli_options/#node

**Comment by kv-naveen** [comment]
Thank you for the info. 
can you please point me to a link (if any) where we can track if selenium manager is out of beta.

**Comment by diemol** [comment]
Selenium Manager will be out of beta when we release Selenium 5, which does not have a clear date yet as we are building the roadmap for that version.
