### ISSUE TITLE
Running Protractor tests on Webdriver 2.47.1 gets - Error: Server terminated early with status 1

### ISSUE THREAD

**Issue by qualityshepherd** [SeleniumHQ/selenium#1191]
**Steps:**
1. Install Protractor 2.5.1 via npm
2. Update webdriver/chrome: `webriver-manager update` (installs WebdriverJS 2.47.1)
3. Run any Protractor test

**Results:**
Two of four people on my team get the error below, and cannot ever run the tests until they downgrade webdriver. It works fine for the other two machines. 

**Impact:**
* Downgrading Webdriver to 2.45.0 fixes the problem. 
* This occurs for 1/2 my team, and I found the [same issue on StackOverflow](http://stackoverflow.com/questions/33196337/gulp-protractor-selenium-webdriver-exited-status-1/33269135#33269135)

**Error:**
``` 
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
 goog.global.setTimeout(function() { throw exception; }, 0);
                                           ^
Error: Server terminated early with status 1
   at Error (native)
   at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:204:25
   at promise.ControlFlow.runInFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
   at goog.defineClass.notify (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
   at promise.Promise.notify_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
   at Array.forEach (native)
   at promise.Promise.notifyAll_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
   at goog.async.run.processWorkQueue (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
   at runMicrotasksCallback (node.js:337:7)
   at process._tickCallback (node.js:355:11)
```

**Comment by ddavison** [comment]
have you tried to bring this up with https://github.com/Angular/Protractor yet?

**Comment by qualityshepherd** [comment]
Not yet. Since the error seemed to be coming from Webdriver, and downgrading WD fixed the problem, I figured I'd start here... but I expected to be ping-ponged between y'all :) Unfortunately, this doesn't occur on my machine, thus my ability to regress is limited.

**Comment by jleyba** [comment]
The error came from WD in the sense that something asked it to run a Selenium server, and the server terminated early. There's nothing here that indicates what version of the server you tried to run, what args were used, etc.

There's nothing for us to take action on here, so I'm going to close this bug.

**Comment by qualityshepherd** [comment]
As the bug states, the installed server version is 2.47.1. Regardless, because my machine does not reproduce the issue, I'm not able to regress with the latest version of WD, etc... and thus, closing this is fair. Thanks!
