### ISSUE TITLE
[🐛 Bug]:  find_element does not work for shadow_root object in Firefox 

### ISSUE THREAD

**Issue by GorgMish** [SeleniumHQ/selenium#11919]
### What happened?

I want to find a specific element in the `shadow_root` object. But it throws the following exception. It works well with ChromeDriver.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Firefox()
driver.get("https://www.plantopedia.de/")

driver.implicitly_wait(3)

elem = driver.find_element(By.ID, "cmpwrapper")
shadow_root = elem.shadow_root
elem_in_shadow_dom = shadow_root.find_element(By.ID, "cmpbox")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Drivers\Codes\Workstation\bannerclick\test.py", line 57, in find_shadowdom_banners
    elem_in_shadow_dom = shadow_root.find_element(By.ID, "cmpbox")
  File "C:\Users\arasaii\anaconda3\envs\alienv\lib\site-packages\selenium\webdriver\remote\shadowroot.py", line 53, in find_element
    return self._execute(Command.FIND_ELEMENT_FROM_SHADOW_ROOT, {"using": by, "value": value})["value"]
  File "C:\Users\arasaii\anaconda3\envs\alienv\lib\site-packages\selenium\webdriver\remote\shadowroot.py", line 82, in _execute
    return self.session.execute(command, params)
  File "C:\Users\arasaii\anaconda3\envs\alienv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\arasaii\anaconda3\envs\alienv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: WebDriver:FindElementFromShadowRoot
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
UnknownCommandError@chrome://remote/content/shared/webdriver/Errors.jsm:502:5
despatch@chrome://remote/content/marionette/server.js:299:13
execute@chrome://remote/content/marionette/server.js:279:16
onPacket/<@chrome://remote/content/marionette/server.js:252:20
onPacket@chrome://remote/content/marionette/server.js:253:9
_onJSONObjectReady/<@chrome://remote/content/marionette/transport.js:500:20

```

### Operating System

Windows 10

### Selenium version

Python 4.8.3

### What are the browser(s) and version(s) where you see this issue?

Firefox 102.8.0

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.33.0

**Comment by titusfortner** [comment]
finding elements in shadow root isn't supported until Firefox v113 which is currently in beta.
