### ISSUE TITLE
[🐛 Bug]: NullpointerException while spinning up dynamic grid

### ISSUE THREAD

**Issue by devqaio** [SeleniumHQ/selenium#11935]
### What happened?

I have used the default config and compose yaml mentioed in readme section and tried to spinup a grid. The docker compose was executed on a Linux host. It spinned the hub correctly and was accessible. But for node, it spinned up exited saying InvocationTargetException which starts from a Nullpointerexception as per trace.

### How can we reproduce the issue?

```shell
docker-compose.yml

# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.9.0-20230421
    volumes:
      - ./assets:/opt/selenium/assets
      - ./grid-config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.9.0-20230421
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

### Relevant log output

```shell
Attaching to selenium-hub, grid_node-docker_1
�[33mselenium-hub    |�[0m 2023-04-24 00:16:29,881 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
�[33mselenium-hub    |�[0m 2023-04-24 00:16:30,187 INFO RPC interface 'supervisor' initialized
�[33mselenium-hub    |�[0m 2023-04-24 00:16:30,188 CRIT Server 'unix_http_server' running without any HTTP authentication checking
�[33mselenium-hub    |�[0m 2023-04-24 00:16:30,189 INFO supervisord started with pid 8
�[36mnode-docker_1   |�[0m 2023-04-24 00:16:30,422 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-docker.conf" during parsing
�[36mnode-docker_1   |�[0m 2023-04-24 00:16:30,734 INFO RPC interface 'supervisor' initialized
�[36mnode-docker_1   |�[0m 2023-04-24 00:16:30,735 CRIT Server 'unix_http_server' running without any HTTP authentication checking
�[36mnode-docker_1   |�[0m 2023-04-24 00:16:30,737 INFO supervisord started with pid 8
�[33mselenium-hub    |�[0m 2023-04-24 00:16:31,195 INFO spawned: 'selenium-grid-hub' with pid 10
�[33mselenium-hub    |�[0m Tracing is disabled
�[33mselenium-hub    |�[0m 2023-04-24 00:16:31,207 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
�[36mnode-docker_1   |�[0m 2023-04-24 00:16:31,744 INFO spawned: 'socat' with pid 10
�[36mnode-docker_1   |�[0m 2023-04-24 00:16:31,747 INFO spawned: 'selenium-grid-docker' with pid 11
�[36mnode-docker_1   |�[0m Starting Selenium Grid Node Docker...
�[36mnode-docker_1   |�[0m 2023-04-24 00:16:31,764 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
�[36mnode-docker_1   |�[0m 2023-04-24 00:16:31,765 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
�[36mnode-docker_1   |�[0m Tracing is disabled
�[33mselenium-hub    |�[0m 00:16:31.947 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
�[33mselenium-hub    |�[0m 00:16:31.958 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
�[33mselenium-hub    |�[0m 00:16:32.158 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.23.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.23.0.2:4443]
�[33mselenium-hub    |�[0m 00:16:32.461 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.23.0.2:4442 and tcp://172.23.0.2:4443
�[33mselenium-hub    |�[0m 00:16:32.703 INFO [UnboundZmqEventBus.<init>] - Sockets created
�[36mnode-docker_1   |�[0m 00:16:32.721 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
�[36mnode-docker_1   |�[0m 00:16:32.760 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
�[36mnode-docker_1   |�[0m 00:16:33.006 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
�[36mnode-docker_1   |�[0m 00:16:33.136 INFO [UnboundZmqEventBus.<init>] - Sockets created
�[33mselenium-hub    |�[0m 00:16:33.707 INFO [UnboundZmqEventBus.<init>] - Event bus ready
�[36mnode-docker_1   |�[0m 00:16:34.143 INFO [UnboundZmqEventBus.<init>] - Event bus ready
�[36mnode-docker_1   |�[0m 00:16:34.378 INFO [NodeServer.createHandlers] - Reporting self as: http://172.23.0.3:5555
�[36mnode-docker_1   |�[0m 00:16:34.442 INFO [NodeOptions.getSessionFactories] - Detected 2 available processors
�[33mselenium-hub    |�[0m 00:16:34.891 INFO [Hub.execute] - Started Selenium Hub 4.9.0 (revision d7057100a6): http://172.23.0.2:4444
�[36mnode-docker_1   |�[0m java.lang.reflect.InvocationTargetException
�[36mnode-docker_1   |�[0m 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
�[36mnode-docker_1   |�[0m 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
�[36mnode-docker_1   |�[0m 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
�[36mnode-docker_1   |�[0m 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
�[36mnode-docker_1   |�[0m Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:159)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:128)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:239)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.Main.launch(Main.java:83)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.Main.go(Main.java:57)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.Main.main(Main.java:42)
�[36mnode-docker_1   |�[0m 	... 6 more
�[36mnode-docker_1   |�[0m Caused by: java.lang.reflect.InvocationTargetException
�[36mnode-docker_1   |�[0m 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
�[36mnode-docker_1   |�[0m 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
�[36mnode-docker_1   |�[0m 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
�[36mnode-docker_1   |�[0m 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
�[36mnode-docker_1   |�[0m 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
�[36mnode-docker_1   |�[0m 	... 14 more
�[36mnode-docker_1   |�[0m Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://127.0.0.1:2375
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.node.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:134)
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:86)
�[36mnode-docker_1   |�[0m 	... 22 more
�[36mnode-docker_1   |�[0m Exception in thread "Thread-0" java.lang.NullPointerException
�[36mnode-docker_1   |�[0m 	at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:80)
�[36mnode-docker_1   |�[0m 	at java.base/java.lang.Thread.run(Thread.java:829)
�[36mnode-docker_1   |�[0m 2023-04-24 00:16:35,609 INFO exited: selenium-grid-docker (exit status 1; not expected)
Gracefully stopping... (press Ctrl+C again to force)
```

### Operating System

CentOS 7

### Selenium version

4.90

### What are the browser(s) and version(s) where you see this issue?

Node Docker

### What are the browser driver(s) and version(s) where you see this issue?

4.9.0-20230421

### Are you using Selenium Grid?

4.9.0

**Comment by diemol** [comment]
How does the `config.toml` look like?

**Comment by diemol** [comment]
TOML is taken from https://github.com/SeleniumHQ/docker-selenium/issues/1836#issuecomment-1519209921

**Comment by devqaio** [comment]
It is the same TOML mention in ReadMe under docker-selenium repo. Observed the same in Window 11 machine with Docker Desktop

**Comment by devqaio** [comment]
@diemol - Any interim workaround?

**Comment by diemol** [comment]
After reading the stacktrace again I see:

```
�[36mnode-docker_1   |�[0m Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://127.0.0.1:2375
```

This means that Selenium Grid could not reach the Docker daemon. Since you are using Linux, sometimes mounting the socket is not enough, so you need to tune the configuration. It varies from host to host sometimes, check the following links and ideally one of them should work:
- https://stackoverflow.com/questions/33260989/correct-way-to-start-docker-daemon-listening-to-specific-port
- https://stackoverflow.com/questions/35488251/how-to-access-docker-daemon-through-tcp-socker
- https://docs.docker.com/config/daemon/
- https://serverfault.com/questions/843296/how-do-i-expose-the-docker-api-over-tcp
