### ISSUE TITLE
Node.js v4.2.1 install selenium-webdriver got " node.lib : fatal error LNK1106: invalid file or disk full " error

### ISSUE THREAD

**Issue by notejs** [SeleniumHQ/selenium#1194]
Following is the error .
```
D:\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  bufferutil.cc
  win_delay_load_hook.c
C:\Users\linus\.node-gyp\4.2.1\Release\node.lib : fatal error LNK1106: invalid
file or disk full: cannot seek to 0x313C2 [D:\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

OS is Win 10 64bit with MS Express 2013 

I try Node.js v4.1.0,work well. I can install newest selenium-webdriver ( 2.48.0 ) .

Both node-gyp is v3.0.3.

Actually, every partition of disk has at least 30GB of free space.

**Comment by jleyba** [comment]
[bufferutil](npmjs.com/package/bufferutil) is an optional dependency (pulled in from a dependency on [ws](https://www.npmjs.com/package/ws)). selenium-webdriver should install even if the bufferutil build fails.

Looks like there are several related issues logged on the [websockets/bufferutil](https://github.com/websockets/bufferutil/issues?utf8=%E2%9C%93&q=is%3Aissue+install) project.
