### ISSUE TITLE
It seems FindDriverServiceExecutable has not been updated to use SeleniumManager in version 4.9?

### ISSUE THREAD

**Issue by jefsmo** [SeleniumHQ/selenium#11942]
It seems FindDriverServiceExecutable has not been updated to use SeleniumManager in version 4.9?
Actual:
```    
protected static string FindDriverServiceExecutable(string executableName, Uri downloadUrl)
{
    return FileUtilities.FindFile(executableName);
}
```
Expected:
```
protected static string FindDriverServiceExecutable(string executableName, Uri downloadUrl)
{
    string text = FileUtilities.FindFile(executableName);
    if (string.IsNullOrEmpty(text))
    {
        try
        {
            text = Path.GetDirectoryName(SeleniumManager.DriverPath(executableName));
        }
        catch (Exception)
        {
        }

        if (string.IsNullOrEmpty(text))
        {
            throw new DriverServiceNotFoundException(string.Format(CultureInfo.InvariantCulture, "The {0} file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at {1}.", executableName, downloadUrl));
        }
    }

    return text;
}
```

_Originally posted by @jefsmo in https://github.com/SeleniumHQ/selenium/issues/11929#issuecomment-1520561296_

**Comment by jefsmo** [comment]
Repro:
```csharp
            using ChromeDriverService service = ChromeDriverService.CreateDefaultService();
            service.EnableVerboseLogging = true;
            service.SuppressInitialDiagnosticInformation = false;

            if (!service.IsRunning)
            {
                service.Start();
            }

```

Error:
```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'chromedriver.exe' with working directory 'C:\Users\********\Source\repos\Sample\DriverServiceSample\bin\Debug\net6.0'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at OpenQA.Selenium.DriverService.Start()
   at DriverServiceSample.Program.Main() in C:\Users\********\Source\repos\Sample\DriverServiceSample\Program.cs:line 18
```

**Comment by jefsmo** [comment]
OS: Win 10 Enterprise (21H2) 64-bit
Selenium.WebDriver v4.9.0

**Comment by titusfortner** [comment]
@nvborisenko can you take a look at what we changed here?

**Comment by diemol** [comment]
I believe this is something I missed when I made changes to use browser options to invoke Selenium Manager. I will have a look.
