### ISSUE TITLE
[🐛 Bug]: can't start a new session after adding "--remote-allow-origins=*" argument for new chrome version 112

### ISSUE THREAD

**Issue by Mary1210** [SeleniumHQ/selenium#11951]
### What happened?

I added argument  "--remote-allow-origins=*"  for chrome options and add option to webdriver and I have an error "Could not start a new session"
and here the code:
ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver(options);

### How can we reproduce the issue?

```shell
1- added argument  "--remote-allow-origins=*"  for chrome options and add option to webdriver
2- try to run the code to start driver
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
```

### Operating System

windows 10

### Selenium version

4.9.0

### What are the browser(s) and version(s) where you see this issue?

Chrome version 112.0.5615.138

### What are the browser driver(s) and version(s) where you see this issue?

Chrome version 112.0.5615.138

**Comment by titusfortner** [comment]
That argument gets added automatically if you are using Selenium 4.9. Does it work if you remove that? Also, you shouldn't need `WebDriverManager` in your code any more.

**Comment by Mary1210** [comment]
No it doesn't work with me after deleting argument and remove webdriver

**Comment by diemol** [comment]
Please paste the exact code you are using so we can copy it to reproduce the issue.

**Comment by Mary1210** [comment]
https://drive.google.com/file/d/1pYf9UUCNqhk45Bu35DTdvbAZTyjyEHWo/view?usp=sharing
my code is here

**Comment by titusfortner** [comment]
I'm confused; if it doesn't work with or without that argument, why do you think your issue is related to that argument?

**Comment by diemol** [comment]
> https://drive.google.com/file/d/1pYf9UUCNqhk45Bu35DTdvbAZTyjyEHWo/view?usp=sharing my code is here

I could not find where you are using `--remote-allow-origins=*` in that code. 

Please attached the code to this issue that we can use to reproduce this.

**Comment by Mary1210** [comment]
@diemol you can check my code from here https://drive.google.com/file/d/1X2P3H-Jz7aeTe8PIQ9oplH-fyFCVr27U/view?usp=sharing
I added --remote-allow-origins=* in that code.

**Comment by diemol** [comment]
Can you share this in a https://gist.github.com/ or a GitHub repo, even attach it as a zip. It is not easy to check the code there.

**Comment by Mary1210** [comment]
https://gist.github.com/Mary1210/ccf414f6eea601c9ce18646407a7a282
you can check it from here @diemol

**Comment by diemol** [comment]
I cannot reproduce it, can you provide the complete stacktrace/error?

**Comment by Mary1210** [comment]
@diemol You can check my repo from here https://github.com/Mary1210/seleniumreponew

**Comment by diemol** [comment]
> I cannot reproduce it, can you provide the complete stacktrace/error?

What about this ⬆️ ?

**Comment by Mary1210** [comment]
@diemol maybe you can't reproduce becanues I forgot to add pom.xml file. I think you can check from the repo and it will work

**Comment by diemol** [comment]
I still need to see your complete stacktrace/error

**Comment by Mary1210** [comment]
![image](https://user-images.githubusercontent.com/45977095/235131218-ae334c9a-93ee-43da-9bbb-3d21eba684e1.png)
this is the error @diemol

**Comment by diemol** [comment]
Please, the whole text, you can copy and paste it.

**Comment by Mary1210** [comment]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Invalid port. Exiting...

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-SKQGP0J', ip: '172.28.0.1'

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)
	at Tests.intitatedriver.openBrowser(intitatedriver.java:18)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:376)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.1'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:234)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:114)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 23 more

**Comment by Mary1210** [comment]
@diemol Hello, Do you have any feedback?

**Comment by diemol** [comment]
Apologies for the delay. 

The current version requires Java 11, and does not have the `"--remote-allow-origins="` option in the code anymore. You should not be having this issue anymore. Please let us know if this is not the case and we can reopen.
