### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by RandMental** [SeleniumHQ/selenium#11965]
### What happened?

Linux debian 64 bit on RPI4 with Python 3.11.3

Trying to run program with Selenium creates this error 

Tracker Web Portal
==================
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 97, in start
    path = SeleniumManager().driver_location(browser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 75, in driver_location
    str(self.get_binary()),
        ^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 56, in get_binary
    raise SeleniumManagerException(f"{path} is missing.  Please open an issue on {tracker}")
selenium.common.exceptions.SeleniumManagerException: Message: /home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/linux/se                              lenium-manager is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues

### How can we reproduce the issue?

```shell
import os
import time
import gvars
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

from selenium import webdriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium.webdriver.firefox.options import Options as FirefoxOptions

# set the path to the Geckodriver executable
geckoDriverPath = './Browsr/geckodriver'



def firefoxDriverInit():

    # set Firefox Driver options
    firefox_options = FirefoxOptions()

    firefox_options.set_preference('browser.cache.disk.enable', False)
    firefox_options.set_preference('browser.cache.memory.enable', False)
    firefox_options.set_preference('browser.cache.offline.enable', False)
    firefox_options.set_preference('network.http.use-cache', False)

    firefox_options.add_argument('--disable-plugins')
    firefox_options.add_argument('--no-sandbox')
    firefox_options.add_argument('--window-size=1920,500')

    if gvars.headlessMode:
        firefox_options.add_argument('--headless')

    if gvars.myDebug:
        firefox_options.add_argument('--log-level=debug')
        print('-- Debug mode --')
    else:
        firefox_options.add_argument('--log-level=debug')

    # set path to Firefox binary (if necessary)
    firefox_binary = FirefoxBinary('C:/Program Files/Mozilla Firefox/firefox.exe')
    firefox_options.binary = firefox_binary

    # create a Firefox driver instance
    firefox_service = FirefoxService(executable_path=geckoDriverPath)
    driver = webdriver.Firefox(service=firefox_service, options=firefox_options)

    return driver
```

### Relevant log output

```shell
Tracker Web Portal
==================
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 97, in start
    path = SeleniumManager().driver_location(browser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 75, in driver_location
    str(self.get_binary()),
        ^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 56, in get_binary
    raise SeleniumManagerException(f"{path} is missing.  Please open an issue on {tracker}")
selenium.common.exceptions.SeleniumManagerException: Message: /home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/linux/se                              lenium-manager is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/eaglemon/eaglemonitor.py", line 393, in <module>
    main()
  File "/home/pi/eaglemon/eaglemonitor.py", line 153, in main
    checkWebPortal()
  File "/home/pi/eaglemon/WebPortal.py", line 73, in checkWebPortal
    driver = browserDrivers.firefoxDriverInit()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/eaglemon/browserDrivers.py", line 51, in firefoxDriverInit
    driver = webdriver.Firefox(service=firefox_service, options=firefox_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 194, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 100, in start
    raise err
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/home/pi/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 218, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

### Operating System

Linux UniPi4-64G 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64

### Selenium version

4.8.3

### What are the browser(s) and version(s) where you see this issue?

Mozilla Firefox 102.10.0esr

### What are the browser driver(s) and version(s) where you see this issue?

Mozilla Firefox 102.10.0esr

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Can you try 4.9.0? Also, is the browser path correct? Looks like a Windows path and in the template you mention Linux as your OS.

**Comment by RandMental** [comment]
Thanks for the quick response - I updated to the latest  V4.0.9 and corrected the Firefox binary path which solved the problem
