### ISSUE TITLE
[🐛 Bug]: -Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Host info: host:

### ISSUE THREAD

**Issue by arpithaHM** [SeleniumHQ/selenium#11984]
### What happened?

hi, 

I see the issue reported in  https://github.com/SeleniumHQ/selenium/issues/9528 this thread is re-occuring. I am getting the below issue again. We are using sauce labs for remote test execution and below is the issue we are facing very randomly but often 

```bash
-Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Host info: host: <HOST Name>, <IP>

Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
build 01-May-2023 21:06:32 Build info: version: '4.8.2', revision: '826dbfc730'
build 01-May-2023 21:06:32 System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
build 01-May-2023 21:06:32 Driver info: driver.version: RemoteWebDriver
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:124)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:165)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
```

Could someone please look into this?

### How can we reproduce the issue?

```shell
Reproducible steps are mentioned in this thread https://github.com/SeleniumHQ/selenium/issues/9528
```

### Relevant log output

```shell
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
build 01-May-2023 21:06:32 Build info: version: '4.8.2', revision: '826dbfc730'
build 01-May-2023 21:06:32 System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
build 01-May-2023 21:06:32 Driver info: driver.version: RemoteWebDriver
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:124)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:165)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
build 01-May-2023 21:06:32 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
```

### Operating System

Windows 10

### Selenium version

4.8.2 , programming language - Java

### What are the browser(s) and version(s) where you see this issue?

Chrome, Edge

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 112.0.5615.49

**Comment by diemol** [comment]
But it is not the same issue. You are getting a timeout while starting the session, the linked issue was throwing a timeout after the session was already started.

Please share a way to reproduce the issue you are having.

**Comment by titusfortner** [comment]
The resolution in the other thread was to update to the new HTTP Client. Please try https://www.selenium.dev/blog/2022/using-java11-httpclient/

**Comment by csgbn** [comment]
Do you need to use the new HTTP Client on the remote grid/hub and nodes as well?

**Comment by diemol** [comment]
Yes, both sides

**Comment by arpithaHM** [comment]
If we use SauceLabs or Browserstack for remote executions where should we add this dependency httpclient ?

**Comment by diemol** [comment]
I know Sauce Labs uses the Java 11 Http client, but not sure about BrowserStack. To be on the safe side, you should reach out to their customer support.

**Comment by arpithaHM** [comment]
> I know Sauce Labs uses the Java 11 Http client, but not sure about BrowserStack. To be on the safe side, you should reach out to their customer support.
Great, let me check. Thank you

**Comment by arpithaHM** [comment]
We are using SauceLabs and Java 11 Http client is added on our hub as well. Even then we have this issue : 

```bash
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '<Host Name>', ip: '<IP address>'
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.8.2', revision: '826dbfc730'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:124)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:165)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 22 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(
```

**Comment by diemol** [comment]
But the "Hub" is Sauce Labs. I do not follow what you mean. 

In any case, we need a way to reproduce the issue. Please share some code we can use to get the same error you are getting. Thanks!

**Comment by ksingha161** [comment]
@arpithaHM If it helps, I faced the same problem and I found out we need to add http client to both hub and node. CLI command I used to start hub and node
`java -Dwebdriver.http.factory=jdk-http-client -jar selenium-server-4.9.0.jar --ext selenium-http-jdk-client-4.9.0.jar hub`

`java -Dwebdriver.http.factory=jdk-http-client -jar selenium-server-4.9.0.jar --ext selenium-http-jdk-client-4.9.0.jar node --config nodeConfig.toml`

I also added this in code - 
`System.setProperty("webdriver.http.factory", "jdk-http-client");`

**Comment by diemol** [comment]
Closing this as different folks have provided hints how to fix but still no code to reproduce the issue has been provided.
