### ISSUE TITLE
[🐛 Bug]: Selenium Chromedriver not reachable

### ISSUE THREAD

**Issue by BugShredder** [SeleniumHQ/selenium#11985]
### What happened?

I have recently started using VS2022 and I wanted to upgrade the .NET framework to .NET 6.0. After installing all the required components as given below. I wrote a sample chrome launch code. The automation opens chrome however it closes the window with 'Chrome not reachable' error. I get similar issue with Firefox and Edge drivers as well.

 

### How can we reproduce the issue?

```shell
public void GivenIAmOnHomepage()
        {
            ChromeOptions options = new ChromeOptions();
            options.AddArgument("--no-sandbox");

            ChromeDriver driver = new ChromeDriver("\\chromedriver.exe", options, TimeSpan.FromMinutes(3));
            



            //var driverService = FirefoxDriverService.CreateDefaultService();


            //FirefoxOptions FirefoxOptions = new FirefoxOptions();

            //FirefoxOptions.AddArgument("start-maximized");
            //driverService.HideCommandPromptWindow = true;

            //driver = new FirefoxDriver(driverService, FirefoxOptions, TimeSpan.FromSeconds(220));
            //driver.ExecuteJavaScript("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})");
        }
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=chrome not reachable
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at SpecflowSelenium_net6_POC.StepDefinitions.CorporateWebsiteStepDefinitions.GivenIAmOnBCUHomepage() in C:\Users\id124627\source\repos\SpecflowSelenium_net6_POC\SpecflowSelenium_net6_POC\StepDefinitions\CorporateWebsiteStepDefinitions.cs:line 25
```

### Operating System

Windows 10

### Selenium version

c# 4.9.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 113.0.5672.64 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Selenium.WebDriver.GeckoDriver 0.33.0, Selenium.WebDriver.IEDriver 4.8.1

### Are you using Selenium Grid?

NO

**Comment by diemol** [comment]
There is no need to specify the ChromeDriver location, Selenium takes care of that for you.

Do you have Chrome installed?

**Comment by BugShredder** [comment]
> There is no need to specify the ChromeDriver location, Selenium takes care of that for you.
> 
> Do you have Chrome installed?

I am aware of this however was just trying out everything. I do have Chrome installed

**Comment by diemol** [comment]
What happens if you start ChromeDriver at the command line and then use an API client like [Insominia](https://insomnia.rest/) to post this payload

```
{
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
      }
    ]
  }
}
```

**Comment by BugShredder** [comment]
> What happens if you start ChromeDriver at the command line and then use an API client like [Insominia](https://insomnia.rest/) to post this payload
> 
> ```
> {
>   "capabilities": {
>     "firstMatch": [
>       {
>         "browserName": "chrome",
>       }
>     ]
>   }
> }
> ```

Error: Couldn't connect to server

**Comment by diemol** [comment]
Can you share the whole execution output?

**Comment by BugShredder** [comment]
> Can you share the whole execution output?

Not sure if this is what you are asking for:

* Preparing request to https://localhost:9515/
* Current time is 2023-05-03T15:45:46.308Z
* Enable automatic URL encoding
* Using default HTTP version
* Enable timeout of 30000ms
* Enable SSL validation
*   Trying 127.0.0.1:9515...
*   Trying ::1:9515...
* connect to 127.0.0.1 port 9515 failed: Connection refused
* connect to ::1 port 9515 failed: Connection refused
* Failed to connect to localhost port 9515 after 2228 ms: Connection refused
* Closing connection 6

**Comment by diemol** [comment]
No, the ChromeDriver output

**Comment by BugShredder** [comment]
> No, the ChromeDriver output

I have put all the log in Relevant log output.

**Comment by diemol** [comment]
I expect something like this that shows how you started ChromeDriver on the terminal and how the payload was received.

```
./chromedriver --verbose
Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1683191086.253][INFO]: [9fe24dd400bfdbf83a060698660dda60] COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "browserName": "chrome"
      } ]
   }
}
[1683191086.260][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1683191086.261][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1683191086.261][INFO]: Launching chrome: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --allow-pre-commit-input --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-service-autorun --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/var/folders/85/m0jdxw2j3yn9mrn_2dpnbsmm0000gn/T/.com.google.Chrome.hEgqOu data:,

DevTools listening on ws://127.0.0.1:64139/devtools/browser/4b5d77dc-3b01-44e5-b7e7-124f99cbf3f7
[1683191086.691][DEBUG]: DevTools HTTP Request: http://localhost:64139/json/version
objc[76261]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x24872afe0) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/112.0.5615.137/Libraries/libGLESv2.dylib (0x107b1bc58). One of the two will be used. Which one is undefined.
[1683191087.101][DEBUG]: DevTools HTTP Response: {
   "Browser": "Chrome/112.0.5615.137",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
   "V8-Version": "11.2.214.14",
   "WebKit-Version": "537.36 (@b160f1d9e90aa6940d17d5cb44d9e815205d2024)",
   "webSocketDebuggerUrl": "ws://localhost:64139/devtools/browser/4b5d77dc-3b01-44e5-b7e7-124f99cbf3f7"
}

[1683191087.101][DEBUG]: DevTools HTTP Request: http://localhost:64139/json/list
[1683191087.106][DEBUG]: DevTools HTTP Response: [ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:64139/devtools/page/1A2CC6F8CF0987CED92ABA86CB6FA6C3",
   "id": "1A2CC6F8CF0987CED92ABA86CB6FA6C3",
   "title": "",
   "type": "page",
   "url": "data:,",
   "webSocketDebuggerUrl": "ws://localhost:64139/devtools/page/1A2CC6F8CF0987CED92ABA86CB6FA6C3"
} ]

[1683191087.109][INFO]: resolved localhost to ["::1","127.0.0.1"]
[1683191087.110][DEBUG]: DevTools WebSocket Command: Target.getTargets (id=1) (session_id=) browser {
}
[1683191087.110][DEBUG]: DevTools WebSocket Response: Target.getTargets (id=1) (session_id=) browser {
   "targetInfos": [ {
      "attached": false,
      "browserContextId": "E22E68B788FB0C51827136D7FCBF8BAF",
      "canAccessOpener": false,
      "targetId": "1A2CC6F8CF0987CED92ABA86CB6FA6C3",
      "title": "",
      "type": "page",
      "url": "data:,"
   } ]
}
[1683191087.110][DEBUG]: DevTools WebSocket Command: Target.attachToTarget (id=2) (session_id=) browser {
   "flatten": true,
   "targetId": "1A2CC6F8CF0987CED92ABA86CB6FA6C3"
}
[1683191087.111][DEBUG]: DevTools WebSocket Event: Target.attachedToTarget (session_id=) browser {
   "sessionId": "C13706C4E59149601BAFEAC39E407923",
   "targetInfo": {
      "attached": true,
      "browserContextId": "E22E68B788FB0C51827136D7FCBF8BAF",
      "canAccessOpener": false,
      "targetId": "1A2CC6F8CF0987CED92ABA86CB6FA6C3",
      "title": "",
      "type": "page",
      "url": "data:,"
   },
   "waitingForDebugger": false
}
[1683191087.111][DEBUG]: DevTools WebSocket Response: Target.attachToTarget (id=2) (session_id=) browser {
   "sessionId": "C13706C4E59149601BAFEAC39E407923"
}
[1683191087.111][DEBUG]: DevTools WebSocket Command: Page.addScriptToEvaluateOnNewDocument (id=3) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "source": "(function () {window.cdc_adoQpoasnfa76pfcZLmcfl_Array = window.Array;window.cdc_adoQpoasnfa76pfcZLmcfl_Promise = window.Promise;window.cdc_adoQpoasnfa76pfcZLmcfl_Symbol = window.Symbol;}) ();"
}
[1683191087.111][DEBUG]: DevTools WebSocket Command: Runtime.evaluate (id=4) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "expression": "(function () {window.cdc_adoQpoasnfa76pfcZLmcfl_Array = window.Array;window.cdc_adoQpoasnfa76pfcZLmcfl_Promise = window.Promise;window.cdc_adoQpoasnfa76pfcZLmcfl_Symbol = window.Symbol;}) ();"
}
[1683191087.111][DEBUG]: DevTools WebSocket Command: Log.enable (id=5) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.112][DEBUG]: DevTools WebSocket Command: Target.setAutoAttach (id=6) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "autoAttach": true,
   "flatten": true,
   "waitForDebuggerOnStart": false
}
[1683191087.112][DEBUG]: DevTools WebSocket Command: Page.enable (id=7) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.112][DEBUG]: DevTools WebSocket Command: Page.enable (id=8) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.116][DEBUG]: DevTools WebSocket Response: Page.addScriptToEvaluateOnNewDocument (id=3) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "identifier": "1"
}
[1683191087.116][DEBUG]: DevTools WebSocket Response: Runtime.evaluate (id=4) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "result": {
      "type": "undefined"
   }
}
[1683191087.116][DEBUG]: DevTools WebSocket Response: Log.enable (id=5) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.116][DEBUG]: DevTools WebSocket Response: Target.setAutoAttach (id=6) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.116][DEBUG]: DevTools WebSocket Response: Page.enable (id=7) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.117][DEBUG]: DevTools WebSocket Event: Page.loadEventFired (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "timestamp": 77826.989105
}
[1683191087.117][DEBUG]: DevTools WebSocket Command: Runtime.evaluate (id=9) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "awaitPromise": false,
   "expression": "document.readyState",
   "returnByValue": true
}
[1683191087.117][DEBUG]: DevTools WebSocket Event: Page.frameStoppedLoading (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "frameId": "1A2CC6F8CF0987CED92ABA86CB6FA6C3"
}
[1683191087.117][DEBUG]: DevTools WebSocket Event: Page.domContentEventFired (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "timestamp": 77826.989216
}
[1683191087.117][DEBUG]: DevTools WebSocket Response: Page.enable (id=8) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.118][DEBUG]: DevTools WebSocket Response: Runtime.evaluate (id=9) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "result": {
      "type": "string",
      "value": "complete"
   }
}
[1683191087.118][DEBUG]: DevTools WebSocket Command: Runtime.enable (id=10) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.118][DEBUG]: DevTools WebSocket Event: Runtime.executionContextCreated (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "context": {
      "auxData": {
         "frameId": "1A2CC6F8CF0987CED92ABA86CB6FA6C3",
         "isDefault": true,
         "type": "default"
      },
      "id": 1,
      "name": "",
      "origin": "://",
      "uniqueId": "6262781493917192189.6494841875688816266"
   }
}
[1683191087.118][DEBUG]: DevTools WebSocket Response: Runtime.enable (id=10) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.118][DEBUG]: DevTools WebSocket Command: Page.enable (id=11) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.118][DEBUG]: DevTools WebSocket Response: Page.enable (id=11) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.118][DEBUG]: DevTools WebSocket Command: Runtime.enable (id=12) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.118][DEBUG]: DevTools WebSocket Response: Runtime.enable (id=12) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
}
[1683191087.119][DEBUG]: DevTools WebSocket Command: Runtime.evaluate (id=13) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "awaitPromise": true,
   "expression": "(function() { // Copyright 2012 The Chromium Authors\n// Use of this source code is governed by a BSD-style license that can be\n// found in the LICENSE file.\n\n/**\n * Enum for WebDriver status codes....",
   "returnByValue": true
}
[1683191087.120][DEBUG]: DevTools WebSocket Response: Runtime.evaluate (id=13) (session_id=C13706C4E59149601BAFEAC39E407923) 1A2CC6F8CF0987CED92ABA86CB6FA6C3 {
   "result": {
      "type": "object",
      "value": {
         "status": 0,
         "value": 1
      }
   }
}
[1683191087.120][INFO]: [9fe24dd400bfdbf83a060698660dda60] RESPONSE InitSession {
   "capabilities": {
      "acceptInsecureCerts": false,
      "browserName": "chrome",
      "browserVersion": "112.0.5615.137",
      "chrome": {
         "chromedriverVersion": "112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936})",
         "userDataDir": "/var/folders/85/m0jdxw2j3yn9mrn_2dpnbsmm0000gn/T/.com.google.Chrome.hEgqOu"
      },
      "goog:chromeOptions": {
         "debuggerAddress": "localhost:64139"
      },
      "networkConnectionEnabled": false,
      "pageLoadStrategy": "normal",
      "platformName": "mac os x",
      "proxy": {
      },
      "setWindowRect": true,
      "strictFileInteractability": false,
      "timeouts": {
         "implicit": 0,
         "pageLoad": 300000,
         "script": 30000
      },
      "unhandledPromptBehavior": "dismiss and notify",
      "webauthn:extension:credBlob": true,
      "webauthn:extension:largeBlob": true,
      "webauthn:extension:minPinLength": true,
      "webauthn:extension:prf": true,
      "webauthn:virtualAuthenticators": true
   },
   "sessionId": "9fe24dd400bfdbf83a060698660dda60"
}
```

**Comment by BugShredder** [comment]
[1683301738.394][INFO]: Starting ChromeDriver 113.0.5672.24 (65f30d4e8051264233c679c7cd3743679f15339d-refs/branch-heads/5672@{#243}) on port 59417
[1683301738.395][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1683301738.928][INFO]: [50ed71acf5814d34205826e5328795b4] COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "browserName": "chrome",
         "goog:chromeOptions": {
         }
      } ]
   }
}
[1683301738.942][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1683301738.946][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1683301738.969][INFO]: Launching chrome: "C:\Program Files\Google\Chrome\Application\chrome.exe" --allow-pre-commit-input --disable-background-networking --disable-backgrounding-occluded-windows --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-service-autorun --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Users\id124627\AppData\Local\Temp\scoped_dir30436_1596570925" data:,
[1683301739.183][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301749.193][DEBUG]: DevTools HTTP Request failed
[1683301749.255][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301759.269][DEBUG]: DevTools HTTP Request failed
[1683301759.331][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301760.522][DEBUG]: DevTools HTTP Request failed
[1683301760.583][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301760.818][DEBUG]: DevTools HTTP Request failed
[1683301760.878][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301770.606][DEBUG]: DevTools HTTP Request failed
[1683301770.668][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301780.661][DEBUG]: DevTools HTTP Request failed
[1683301780.722][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301781.922][DEBUG]: DevTools HTTP Request failed
[1683301781.985][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301782.236][DEBUG]: DevTools HTTP Request failed
[1683301782.296][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301792.034][DEBUG]: DevTools HTTP Request failed
[1683301792.098][DEBUG]: DevTools HTTP Request: http://localhost:59421/json/version
[1683301802.069][DEBUG]: DevTools HTTP Request failed
[1683301802.130][INFO]: Failed to connect to Chrome. Attempting to kill it.
[1683301802.461][INFO]: [50ed71acf5814d34205826e5328795b4] RESPONSE InitSession ERROR chrome not reachable
[1683301802.469][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1683301802.469][DEBUG]: Log type 'browser' lost 0 entries on destruction

**Comment by BugShredder** [comment]
This is with --no-sandbox option


[1683302107.127][INFO]: Starting ChromeDriver 113.0.5672.24 (65f30d4e8051264233c679c7cd3743679f15339d-refs/branch-heads/5672@{#243}) on port 59519
[1683302107.127][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1683302107.649][INFO]: [fb4970a1587086bd0d8b058a5a8ac1d5] COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "browserName": "chrome",
         "goog:chromeOptions": {
            "args": [ "--no-sandbox" ]
         }
      } ]
   }
}
[1683302107.653][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1683302107.653][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1683302107.656][INFO]: Launching chrome: "C:\Program Files\Google\Chrome\Application\chrome.exe" --allow-pre-commit-input --disable-background-networking --disable-backgrounding-occluded-windows --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Users\id124627\AppData\Local\Temp\scoped_dir7096_623887137" data:,
[1683302108.001][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302118.008][DEBUG]: DevTools HTTP Request failed
[1683302118.068][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302128.072][DEBUG]: DevTools HTTP Request failed
[1683302128.133][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302129.362][DEBUG]: DevTools HTTP Request failed
[1683302129.425][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302129.631][DEBUG]: DevTools HTTP Request failed
[1683302129.694][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302139.428][DEBUG]: DevTools HTTP Request failed
[1683302139.489][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302149.472][DEBUG]: DevTools HTTP Request failed
[1683302149.535][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302150.774][DEBUG]: DevTools HTTP Request failed
[1683302150.836][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302151.038][DEBUG]: DevTools HTTP Request failed
[1683302151.102][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302160.824][DEBUG]: DevTools HTTP Request failed
[1683302160.887][DEBUG]: DevTools HTTP Request: http://localhost:59522/json/version
[1683302170.874][DEBUG]: DevTools HTTP Request failed
[1683302170.935][INFO]: Failed to connect to Chrome. Attempting to kill it.
[1683302171.231][INFO]: [fb4970a1587086bd0d8b058a5a8ac1d5] RESPONSE InitSession ERROR chrome not reachable
[1683302171.231][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1683302171.231][DEBUG]: Log type 'browser' lost 0 entries on destruction

**Comment by diemol** [comment]
OK, so you got the same "Chrome not reachable" error by only using ChromeDriver. This might be an issue with how you Chrome binary is installed but it is hard to say. It is better to report this issue to the Chrome/ChromeDriver folks. I will leave some links below so you can do that. Thanks!

**Comment by BugShredder** [comment]
> Hi, @BugShredder. This issue has been determined to require fixes in [ChromeDriver](https://chromedriver.chromium.org/home).
> 
> You can see if the feature is passing in the [Web Platform Tests](https://wpt.fyi/results/webdriver/tests).
> 
> If it is something new, please [create an issue](https://bugs.chromium.org/p/chromedriver/issues/list) with the ChromeDriver team. Feel free to comment the issues that you raise back in this issue. Thank you.

This happens with all the drivers not just cromedriver. I have tried gekodriver and edgedriver as well??? Should I still raise a ticket with chromedriver

**Comment by diemol** [comment]
Might be an issue with your machine then, but there not much we can do on the Selenium side.

**Comment by BugShredder** [comment]
> Might be an issue with your machine then, but there not much we can do on the Selenium side.

This happens on another machine as well and not just mine!?

**Comment by diemol** [comment]
I understand, but you showed that it still happens without using Selenium. Have you tried asking in StackOverflow or to the Chrome team?
