### ISSUE TITLE
[🐛 Bug]: ChromeDriver is assuming that Chrome has crashed

### ISSUE THREAD

**Issue by samuelsennev** [SeleniumHQ/selenium#11998]
### What happened?

Chrome is somehow crashing when I initialize it's driver after passing the path to /User Data as an option, so I can use the browser with my account logged, not the default one.

### How can we reproduce the issue?

```shell
from selenium import webdriver
import time

options = webdriver.ChromeOptions()
options.add_argument("user-data-dir=C:/Users/Usuario/AppData/Local/Google/Chrome/User Data")

driver = webdriver.Chrome('chromedriver.exe', options=options)
driver.get("https://google.com/")

time.sleep(5)

driver.quit()
```

### Relevant log output

```shell
c:/Users/Usuario/Documents/Python/Projetos basicos/bot-ingressos.py:34: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('chromedriver.exe', options=options)
Abrindo em uma sessÒo de navegador existente.
Traceback (most recent call last):
  File "c:/Users/Usuario/Documents/Python/Projetos basicos/bot-ingressos.py", line 34, in <module>
    driver = webdriver.Chrome('chromedriver.exe', options=options)
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\chrome\webdriver.py", line 84, in __init__
    super().__init__(
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)   
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00ABDCE3+50899]
        (No symbol) [0x00A4E111]
        (No symbol) [0x00955588]
        (No symbol) [0x0097281C]
        (No symbol) [0x0096F479]
        (No symbol) [0x009A1FFE]
        (No symbol) [0x009A1CEC]
        (No symbol) [0x0099B6F6]
        (No symbol) [0x00977708]
        (No symbol) [0x0097886D]
        GetHandleVerifier [0x00D23EAE+2566302]
        GetHandleVerifier [0x00D592B1+2784417]
        GetHandleVerifier [0x00D5327C+2759788]
        GetHandleVerifier [0x00B55740+672048]
        (No symbol) [0x00A58872]
        (No symbol) [0x00A541C8]
        (No symbol) [0x00A542AB]
        (No symbol) [0x00A471B7]
        BaseThreadInitThunk [0x75F70099+25]
        RtlGetAppContainerNamedObjectPath [0x77347B6E+286]
        RtlGetAppContainerNamedObjectPath [0x77347B3E+238]
```

### Operating System

Windows 10 Pro

### Selenium version

Python 4.9.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 112.0.5615.138 64 bits

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 112.0.5615.49

### Are you using Selenium Grid?

Not using

**Comment by diemol** [comment]
Selenium is mainly passing those options to ChromeDriver, so you would need to check with the Chrome/ChromeDriver folks.
