### ISSUE TITLE
[🐛 Bug]: Unable to start Selenium Grid

### ISSUE THREAD

**Issue by MHabiib** [SeleniumHQ/selenium#12077]
### What happened?

when running "java -jar ~/Downloads/selenium-server-4.8.0.jar hub" getting 

and tried using running with different port using command -p but still got same issue

but when im trying to run it using standalone, it's working fine

### How can we reproduce the issue?
java version 11.0.17

```shell
"java -jar ~/Downloads/selenium-server-4.8.0.jar hub"
```

### Relevant log output

```shell
`13:50:57.155 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
13:50:57.162 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
13:50:57.313 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://[fe80:0:0:0:cf3:bb84:7ad2:94bd%en0]:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://[fe80:0:0:0:cf3:bb84:7ad2:94bd%en0]:4443]
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
	at org.openqa.selenium.grid.server.EventBusOptions.createBus(EventBusOptions.java:51)
	at org.openqa.selenium.grid.server.EventBusOptions.getEventBus(EventBusOptions.java:41)
	at org.openqa.selenium.grid.commands.Hub.createHandlers(Hub.java:125)
	at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:48)
	at org.openqa.selenium.grid.commands.Hub.execute(Hub.java:228)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
	... 15 more
Caused by: org.zeromq.ZMQException: Errno 48 : Address already in use
	at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3732)
	at org.zeromq.ZMQ$Socket.bind(ZMQ.java:3111)
	at org.openqa.selenium.events.zeromq.BoundZmqEventBus.<init>(BoundZmqEventBus.java:61)
	at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:51)
	at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:79)
	... 23 more`
```

### Operating System

macOS Monterey

### Selenium version

selenium-server-4.8.0, selenium-server-4.9.1

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

-

### Are you using Selenium Grid?

selenium-server-4.8.0, selenium-server-4.9.1

**Comment by diemol** [comment]
Something is using the ports you want to try, check what is using the ports and either release the or try a different one.

https://stackoverflow.com/questions/4421633/who-is-listening-on-a-given-tcp-port-on-mac-os-x

If you have more questions, I will leave some links below.

**Comment by MHabiib** [comment]
able to run after stopping httpd service using `sudo apachectl stop`
