### ISSUE TITLE
[🐛 Bug]: Invalid InterceptionId exceptions when using HasAuthentication.register() multiple times

### ISSUE THREAD

**Issue by KatalinGacs** [SeleniumHQ/selenium#12115]
### What happened?

I have a test that visits multiple websites protected with basic authentication, each having different credentials. I am using RemoteWebDriver, so I need to use addDriverAugmentation, to be able to use the register method from HasAuthentication interface. When I call the register method more than once, the logs are full of this kind of message
`DevToolsException: {"id":14,"error":{"code":-32602,"message":"Invalid InterceptionId."}`
Adding basic authentication works, the protected websites are reached but the logs are practically unreadable because of the many DevToolsExceptions

### How can we reproduce the issue?

```shell
driver = new Augmenter().augment(driver);
DevTools devTools = ((HasDevTools) driver).getDevTools();
devTools.createSession();

Augmenter augmenter = new Augmenter();
driver = augmenter
         .addDriverAugmentation("chrome",
             HasAuthentication.class,
             caps, exec) -> (whenThisMatches, useTheseCredentials) ->
                 devTools.getDomains()
                     .network()
                     .addAuthHandler(whenThisMatches, useTheseCredentials))
         .augment(driver);

Predicate<URI> mallUri = uri -> uri.getHost().contains("the-internet.herokuapp.com");
((HasAuthentication) driver).register(mallUri, UsernameAndPassword.of("admin", "admin"));

Predicate<URI> siosUri = uri -> uri.getHost().contains("authenticationtest.com");
((HasAuthentication) driver).register(siosUri, UsernameAndPassword.of("user", "pass"));

driver.get("https://the-internet.herokuapp.com/basic_auth");
Thread.sleep(10000);

driver.get("https://authenticationtest.com/HTTPAuth/");
Thread.sleep(10000);
```

### Relevant log output

```shell
May 30, 2023 1:25:32 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 113, so returning the closest version found: 112
May 30, 2023 1:25:33 PM org.openqa.selenium.devtools.Connection$Listener lambda$onText$0
WARNING: Unable to process: {"method":"Fetch.authRequired","params":{"requestId":"interception-job-1.0","request":{"url":"https://the-internet.herokuapp.com/basic_auth","method":"GET","headers":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","Cookie":"rack.session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTFiZDM3NzJmOTI5NjNjYzA1MDAz%0AMDkwNGM2MWIxMjBiN2FlYmFhOTljN2FkMWU3ZjViOGY3NDg4MTk1N2FiMDUG%0AOwBGSSIJY3NyZgY7AEZJIiUwMmMyMTY5ODlkMDMxYTE2Mjk2OGYwYTg5NjJi%0AZDY0ZAY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBfVVNFUl9BR0VOVAY7%0AAFRJIi1jZmVkZDllYTczYWNiOWU2YmYxYjExNjE0OTFjZWYyYTA2NjYyMDc0%0ABjsARkkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsAVEkiLTE0NGRmODIxYjUx%0AMWNmNWFjYWY3ZTFiOGNjZTJhNjZlNjU0MmFhZTUGOwBG%0A--7f37e41a0df3027fd936f3d61080b36aa922293d","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36","sec-ch-ua":"\"Google Chrome\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\""},"initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"BE084FA017ACCB7BAD970950632344F0","resourceType":"Document","authChallenge":{"source":"Server","origin":"https://the-internet.herokuapp.com","scheme":"basic","realm":"Restricted Area"}},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
org.openqa.selenium.devtools.DevToolsException: {"id":11,"error":{"code":-32000,"message":"Invalid state for continueInterceptedRequest"},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:173)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:81)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$1(Network.java:168)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:304)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:440)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:273)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:59)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.openqa.selenium.WebDriverException: {"id":11,"error":{"code":-32000,"message":"Invalid state for continueInterceptedRequest"},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:250)
	... 5 more

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: {"id":11,"error":{"code":-32000,"message":"Invalid state for continueInterceptedRequest"},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:218)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.openqa.selenium.devtools.DevToolsException: {"id":11,"error":{"code":-32000,"message":"Invalid state for continueInterceptedRequest"},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:173)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:81)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$1(Network.java:168)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:304)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:440)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:273)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:59)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:215)
	... 3 more
Caused by: org.openqa.selenium.WebDriverException: {"id":11,"error":{"code":-32000,"message":"Invalid state for continueInterceptedRequest"},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:250)
	... 5 more
May 30, 2023 1:25:33 PM org.openqa.selenium.devtools.Connection$Listener lambda$onText$0
WARNING: Unable to process: {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-1.0","request":{"url":"https://the-internet.herokuapp.com/basic_auth","method":"GET","headers":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36","sec-ch-ua":"\"Google Chrome\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\""},"initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"BE084FA017ACCB7BAD970950632344F0","resourceType":"Document"},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
org.openqa.selenium.devtools.DevToolsException: {"id":14,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:173)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:81)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:227)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:304)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:440)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:273)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:59)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.openqa.selenium.WebDriverException: {"id":14,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:250)
	... 5 more

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: {"id":14,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:218)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.openqa.selenium.devtools.DevToolsException: {"id":14,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:173)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:81)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:227)
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:304)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:440)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:273)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:59)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:215)
	... 3 more
Caused by: org.openqa.selenium.WebDriverException: {"id":14,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"9E1FAD9D88E67ADCE6BABC090A28BB01"}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_362'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:250)
	... 5 more
```

### Operating System

Windows 10 

### Selenium version

Java 4.9.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 113.0.5672.127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver  113.0.5672.63

### Are you using Selenium Grid?

4.9.0

**Comment by titusfortner** [comment]
Update to 4.9.1 and see if explicit support for Chrome v113 fixes it.

**Comment by KatalinGacs** [comment]
> Update to 4.9.1 and see if explicit support for Chrome v113 fixes it.

updated to 4.9.1 and I get the same result.

**Comment by titusfortner** [comment]
This is the currently recommended code to manage Basic Authentication:

https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/#register-basic-auth

Please try this and provide a new stack trace. Thanks.

**Comment by KatalinGacs** [comment]
> This is the currently recommended code to manage Basic Authentication:
> 
> https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/#register-basic-auth
> 
> Please try this and provide a new stack trace. Thanks.

I think this is exactly what I do, maybe I'm missing something. Could you point out what should I do differently in the code I provided to reproduce the issue?

**Comment by titusfortner** [comment]
Here's a working example

```java
    WebDriver driver = RemoteWebDriver.builder().oneOf(new ChromeOptions()).build();
    Predicate<URI> uriPredicate = uri -> uri.getHost().contains("the-internet.herokuapp.com");

    ((HasAuthentication) driver).register(uriPredicate,
            UsernameAndPassword.of("admin", "admin"));
    driver.get("https://the-internet.herokuapp.com/basic_auth");

    WebElement element = driver.findElement(By.tagName("p"));
    String expected = "Congratulations! You must have the proper credentials.";

    Assertions.assertEquals(expected, element.getText());
    driver.quit();
```

**Comment by KatalinGacs** [comment]
Yes, this works for me too. But I have a test that visits two different websites protected with basic authentication (let's say https://the-internet.herokuapp.com/basic_auth and https://authenticationtest.com/HTTPAuth) and I have this problem only when I use HasAuthentication.register() two times.

**Comment by titusfortner** [comment]
Ok, I can duplicate it with this:

```java
    Predicate<URI> uriPredicate = uri -> uri.getHost().contains("the-internet.herokuapp.com");

    ((HasAuthentication) driver).register(uriPredicate,
        UsernameAndPassword.of("admin", "admin"));

    Predicate<URI> uriPredicate2 = uri -> uri.getHost().contains("jigsaw.w3.org");
    ((HasAuthentication) driver).register(uriPredicate2,
            UsernameAndPassword.of("guest", "guest"));

    driver.get("https://the-internet.herokuapp.com/basic_auth");
    WebElement element = driver.findElement(By.tagName("p"));

    String expected = "Congratulations! You must have the proper credentials.";
    Assertions.assertEquals(expected, element.getText());

    driver.get("https://jigsaw.w3.org/HTTP/Basic/");
    WebElement element2 = driver.findElement(By.tagName("body"));

    String expected2 = "Your browser made it!";
    Assertions.assertEquals(expected2, element2.getText());
```

Note that my code actually worked, but a bunch of errors were added to console.

I'm not sure why this is happening, and I think we're more likely to change the implementation to use webdriver-bidi than we are to fix this for Chrome devtools, but I don't have a timeframe on that.

**Comment by joerg1985** [comment]
@KatalinGacs i think this has been fixed in bbe2ac5d1a54fb91b3e051bde71618645689362b could you retest this please?

**Comment by pujagani** [comment]
@joerg1985 Isn't that the fix for NetworkInterceptor? This is a different use case of authentication.

**Comment by joerg1985** [comment]
@pujagani legitimate question, but `addAuthHandler` and `interceptTrafficWith` both call `prepareToInterceptTraffic`.

The linked change did ensure `prepareToInterceptTraffic` does not add the handler multiple times.
If a handler is registered multiple times, the traffic is intercepted multiple times and only the first time will pass.
The following calls to the handler will lead to a 'Invalid InterceptionId.', as these InterceptionId have already been handeled.

**Comment by KatalinGacs** [comment]
@joerg1985  I can confirm, works now without the errors, thank you!

**Comment by pujagani** [comment]
Ahh makes perfect sense. Thank you for the explanation.
