### ISSUE TITLE
ChromeDriver: `switchTo().frame(WebElement)` should throw StaleElementReferenceException in case the element is stale

### ISSUE THREAD

**Issue by alb-i986** [SeleniumHQ/selenium#1213]
Consider the following code:

```
WebDriver driver = new ChromeDriver();
driver.get("http://the-internet.herokuapp.com/iframe");

WebElement iframe = driver.findElement(By.tagName("iframe"));
driver.switchTo().frame(iframe); // works

driver.navigate().refresh();

try {
    driver.switchTo().frame(iframe); // **
    Assert.fail();
} catch (WebDriverException e) {
    e.printStackTrace();
} finally {
    driver.quit();
}
```

With ChromeDriver, the command switchFrame at the line marked with "**" returns error code 13 aka UNHANDLED_ERROR, thus throws the exception below:

```
org.openqa.selenium.WebDriverException: unknown error: Runtime.evaluate threw exception: Error: element is not attached to the page document
    at Object.Cache.retrieveItem (<anonymous>:77:17)
    at unwrap (<anonymous>:181:20)
    at unwrap (<anonymous>:185:19)
    at callFunction (<anonymous>:225:29)
    at apply.ELEMENT (<anonymous>:239:23)
    at <anonymous>:240:3
    at Object.InjectedScript._evaluateOn (<anonymous>:875:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)
    at Object.InjectedScript.evaluate (<anonymous>:664:21)
  (Session info: chrome=46.0.2490.71)
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 6.2 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 42 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: '', ip: '', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\ascotto\AppData\Local\Temp\scoped_dir8212_30311}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.71, platform=WIN8, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: fcc85d2699bc9507f004e76d4b7bfc76
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.frame(RemoteWebDriver.java:885)
	at Main.test(Main.java:45)
```

As you can see, the exception message says `unknown error: Runtime.evaluate threw exception: Error: element is not attached to the page document`.
It's not too bad as it says "element is not attached to the page document", from which we can understand it's a stale element issue.
But the user should be able to catch explicitly StaleElementReferenceException and recover:

```
WebElement iframe = ...
try {
    driver.switchTo().frame(iframe);
} catch (StaleElementReferenceException e) {
    iframe = driver.findElement( .. );
    driver.switchTo().frame(iframe);
}
```

For comparison, please consider what happens with FirefoxDriver, which is we get a StaleElementReferenceException as expected:

```
org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 498 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: '', ip: '', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=41.0.2, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: e46c5e7a-5f20-4e0c-9105-75d8a4df6cc1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.frame(RemoteWebDriver.java:885)
	at Main.test(Main.java:45)
Caused by: org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: '', ip: '', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_60'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:9348)
	at <anonymous class>.Utils.getElementAt(file:///C:/Users/ascotto/AppData/Local/Temp/anonymous2819227405591454245webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:8942)
	at <anonymous class>.FirefoxDriver.prototype.switchToFrame(file:///C:/Users/ascotto/AppData/Local/Temp/anonymous2819227405591454245webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10724)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/ascotto/AppData/Local/Temp/anonymous2819227405591454245webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12643)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///C:/Users/ascotto/AppData/Local/Temp/anonymous2819227405591454245webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12648)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///C:/Users/ascotto/AppData/Local/Temp/anonymous2819227405591454245webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12590)
```

Env info:
Selenium 2.47.1, 2.48.0
ChromeDriver 2.20.353145
Chrome Version 46.0.2490.71 m

**Comment by lukeis** [comment]
for issues with chromedriver, please log a reproducible test case with them here:
https://code.google.com/p/chromedriver/issues/list

**Comment by alb-i986** [comment]
Will do. Thanks
