### ISSUE TITLE
[🐛 Bug]: Your Firefox profile cannot be loaded. It may be missing or inaccessible.

### ISSUE THREAD

**Issue by emakei** [SeleniumHQ/selenium#12167]
### What happened?

I'm just try simple test^
`from selenium import webdriver

browser = webdriver.Firefox()
browser.get('http://localhost:8000')

assert 'Django' in browser.title
`
and got this error.
Then i'm try set profile folder:
`webdriver.FirefoxProfile('/home/emakei/snap/firefox/common/.mozilla/firefox/880pwoyb.default')`
but got same error

### How can we reproduce the issue?

```shell
from selenium import webdriver

# Use your own profile path
webdriver.FirefoxProfile('/home/emakei/snap/firefox/common/.mozilla/firefox/880pwoyb.default')

browser = webdriver.Firefox()
browser.get('http://localhost:8000')

assert 'Django' in browser.title
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

### Operating System

Ubuntu 22.04

### Selenium version

geckodriver 0.33.0 (a80e5fd61076 2023-04-02 18:31 +0000)

### What are the browser(s) and version(s) where you see this issue?

Firefox 114.0 (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.33.0 (a80e5fd61076 2023-04-02 18:31 +0000)

**Comment by diemol** [comment]
What Selenium version are you using?

Can you try to add more logging and see what might be the issue? https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by emakei** [comment]
> What Selenium version are you using?
> 
> Can you try to add more logging and see what might be the issue? https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

```python
>>> selenium.__version__
'4.0.0a1'
```
```bash
emakei@ubuntu-server:~/scripts$ pytest-3 -s -p no:logging
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.10.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
rootdir: /home/emakei/scripts
collecting ... DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:47441/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true}}, "desiredCapabilities": {"browserName": "firefox", "acceptInsecureCerts": true}}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
collected 0 items / 1 error                                                                                                                                                                   

=========================================================================================== ERRORS ============================================================================================
_____________________________________________________________________________ ERROR collecting functional_test.py _____________________________________________________________________________
functional_test.py:11: in <module>
    browser = webdriver.Firefox()
/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py:170: in __init__
    RemoteWebDriver.__init__(
/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py:152: in __init__
    self.start_session(capabilities, browser_profile)
/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py:249: in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py:318: in execute
    self.error_handler.check_response(response)
/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
=================================================================================== short test summary info ===================================================================================
ERROR functional_test.py - selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================================== 1 error in 4.40s =======================================================================================
emakei@ubuntu-server:~/scripts$ 
```

**Comment by diemol** [comment]
Well, 4.0.0a1 is extremely old. I would advise to upgrade to 4.9.1 (latest at the moment), and try again.

**Comment by titusfortner** [comment]
Take a look here: https://www.selenium.dev/documentation/webdriver/browsers/firefox/#profiles

you want to be setting:
```
options.profile = profile_location
```

**Comment by emakei** [comment]
> Take a look here: https://www.selenium.dev/documentation/webdriver/browsers/firefox/#profiles
> 
> you want to be setting:
> 
> ```
> options.profile = profile_location
> ```

it think problem was because of default available version on ubuntu 22.04
but Chrome work nice with v4 Selenium

**Comment by diemol** [comment]
Have you tried the instructions provided? Or does your previous comment also mean that is working now?

**Comment by emakei** [comment]
> Have you tried the instructions provided? Or does your previous comment also mean that is working now?

Still doesn't work
```python
>>> selenium.__version__
'4.10.0'
```
with error
`DeprecationWarning: firefox_profile has been deprecated, please use an Options object`

**Comment by titusfortner** [comment]
That's only a warning, not an error. 
If you still have a problem, post the code and the lags again with Selenium 4.10

Also, please set it on options instance the way I showed above.

**Comment by emakei** [comment]
> That's only a warning, not an error. If you still have a problem, post the code and the lags again with Selenium 4.10
> 
> Also, please set it on options instance the way I showed above.
``` bash
emakei@ubuntu-server:~/scripts$ python3 -m pytest -s -p no:logging
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/emakei/scripts
collecting ... DEBUG:selenium.webdriver.common.service:Started executable: `/usr/local/bin/geckodriver` in a child process with pid: 669297
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:60851/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:debuggerAddress": true, "pageLoadStrategy": "normal"}}}
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=500 | data={"value":{"error":"unknown error","message":"Process unexpectedly closed with status 1","stacktrace":""}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '105', 'date': 'Fri, 09 Jun 2023 15:17:42 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
_____________________ ERROR collecting functional_test.py ______________________
functional_test.py:11: in <module>
    browser = webdriver.Firefox()
../.local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py:68: in __init__
    super().__init__(command_executor=executor, options=self.options)
../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:206: in __init__
    self.start_session(capabilities)
../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute
    self.error_handler.check_response(response)
../.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:245: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
=============================== warnings summary ===============================
functional_test.py:9
  /home/emakei/scripts/functional_test.py:9: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
    webdriver.FirefoxProfile('/home/emakei/snap/firefox/common/.mozilla/firefox/880pwoyb.default')

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR functional_test.py - selenium.common.exceptions.WebDriverException: Message: Process unexpectedl...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 5.10s ==========================
emakei@ubuntu-server:~/scripts$ 
```

**Comment by titusfortner** [comment]
So you are still not using the non deprecated code method.
Please create an options instance and set the profile with that.

But also, that capabilities being sent (without the profile) shouldn't result in a process unexpectedly closed error.

Maybe a permission issue? Could you delete the driver and see if selenium manages it properly?

**Comment by emakei** [comment]
> So you are still not using the non deprecated code method. Please create an options instance and set the profile with that.
> 
> But also, that capabilities being sent (without the profile) shouldn't result in a process unexpectedly closed error.
> 
> Maybe a permission issue? Could you delete the driver and see if selenium manages it properly?

``` bash
emakei@ubuntu-server:~/scripts$ !1890
python3 -m pytest -s -p no:logging
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/emakei/scripts
collecting ... DEBUG:selenium.webdriver.common.service:Started executable: `/usr/local/bin/geckodriver` in a child process with pid: 12601
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:33225/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:debuggerAddress": true, "pageLoadStrategy": "normal", "moz:firefoxOptions": {"prefs": {"profile": "/home/emakei/snap/firefox/common/.mozilla/firefox/880pwoyb.default"}}}}}
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=500 | data={"value":{"error":"unknown error","message":"Process unexpectedly closed with status 1","stacktrace":""}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '105', 'date': 'Fri, 09 Jun 2023 20:22:34 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
collected 0 items / 1 error                                                                                                                                                                   

=========================================================================================== ERRORS ============================================================================================
_____________________________________________________________________________ ERROR collecting functional_test.py _____________________________________________________________________________
functional_test.py:14: in <module>
    browser = Firefox(options = options)
../.local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py:68: in __init__
    super().__init__(command_executor=executor, options=self.options)
../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:206: in __init__
    self.start_session(capabilities)
../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute
    self.error_handler.check_response(response)
../.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:245: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
=================================================================================== short test summary info ===================================================================================
ERROR functional_test.py - selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================================== 1 error in 10.54s ======================================================================================
emakei@ubuntu-server:~/scripts$ 
```

**Comment by titusfortner** [comment]
The profile is properly added to the capabilities.

According to SO, you are likely running on a computer without a GUI, and need to add an argument for `--headless`

https://stackoverflow.com/a/47642457/4072371

**Comment by emakei** [comment]
> The profile is properly added to the capabilities.
> 
> According to SO, you are likely running on a computer without a GUI, and need to add an argument for `--headless`
> 
> https://stackoverflow.com/a/47642457/4072371

A you serious bro? Like I said above Chrome works fine and off course I have Xfce4 on my machine running while try test.

**Comment by emakei** [comment]
> The profile is properly added to the capabilities.
> 
> According to SO, you are likely running on a computer without a GUI, and need to add an argument for `--headless`
> 
> https://stackoverflow.com/a/47642457/4072371

Got hanging script after add `options.add_argument("--headless")`

**Comment by emakei** [comment]
This code works fine:
``` CSharp
using OpenQA.Selenium.Firefox;

namespace SeleniumDocs.Hello
{
    public class HelloSelenium
    {
        public static void Main()
        {
            var options = new FirefoxOptions();

	    options.AddArgument("-profile");
	    options.AddArgument("/home/emakei/snap/firefox/common/.mozilla/firefox/880pwoyb.default");
	    
            var driver = new FirefoxDriver(options);
	    
            driver.Navigate().GoToUrl("https://selenium.dev");
            
            driver.Quit();
        }
    }
}

```

**Comment by titusfortner** [comment]
Look bro, Selenium code is responsible for formatting the capabilities sent to the driver. 
What you've logged as returning an error is the default capabilities:
```
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:60851/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:debuggerAddress": true, "pageLoadStrategy": "normal"}}}
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=500 | data={"value":{"error":"unknown error","message":"Process unexpectedly closed with status 1","stacktrace":""}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '105', 'date': 'Fri, 09 Jun 2023 15:17:42 GMT'})
```
If sending the default capabilities to the driver causes an error, something not related to Selenium is wrong with your system. I can close this issue and tell you to file a ticket with Mozilla; instead, I did a search for that error and seeing if I might be of further help. 

I see you are using snap, perhaps this is your issue - https://github.com/mozilla/geckodriver/issues/2010
