### ISSUE TITLE
[🐛 Bug]: Chrome failed to start: crashed.

### ISSUE THREAD

**Issue by shermanrxie** [SeleniumHQ/selenium#12181]
### What happened?

ChromeDriver cannot run with google chrome.

WebDriverError: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

### How can we reproduce the issue?

```shell
1. run docker selenium/node-chrome:latest
2. Run following nodejs in the container

const webdriver = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');

const options = new chrome.Options();


describe('Should be able to Test Command line arguments', function () {
  it('headless', async function () {
    let driver = new webdriver.Builder()
      .forBrowser(webdriver.Browser.CHROME)
      .setChromeOptions(options.addArguments('--headless=new',
        "--start-maximized",
        "--window-size=1920,1080",
        "--enable-automation",
        "--disable-infobars", "--disable-extensions",
        "--disable-gpu", "--disable-dev-shm-usage",
        "--no-sandbox", "--disable-browser-side-navigation", "--whitelisted-ips"))
        .disableEnvironmentOverrides()
        .build();

    await driver.get('https://www.bind.com/');
    await driver.takeScreenshot().then((image) => {
      return require('fs').writeFileSync("./demo_test_check.png", image, 'base64')
    })

    await driver.quit();
  })
})




{
    "name": "javascript-examples",
    "version": "1.0.0",
    "scripts": {
        "test": "npx mocha test/**/*.spec.js test/setup.js --reporters --timeout 60000"
    },
    "author": "The Selenium project",
    "license": "Apache-2.0",
    "dependencies": {
        "@types/jasmine": "^3.10.3",
        "@types/selenium-webdriver": "^4.0.0",
        "assert": "^2.0.0",
        "chromedriver": "^114.0.1",
        "geckodriver": "^4.0.0",
        "selenium-webdriver": "^4.0.0"
    },
    "devDependencies": {
        "mocha": "^10.2.0"
    }
}
```

### Relevant log output

```shell
google-chrome -version
Google Chrome 114.0.5735.106 

{"value":{"build":{"version":"114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Linux","version":"5.15.49-linuxkit"},"ready":true}}
>>>
POST /session HTTP/1.1
accept: application/json; charset=utf-8

{"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"chrome","goog:chromeOptions":{"args":["--headless=new","--start-maximized","--window-size=1920,1080","--enable-automation","--disable-infobars","--disable-extensions","--disable-gpu","--disable-dev-shm-usage","--no-sandbox","--disable-browser-side-navigation","--whitelisted-ips"]}}}}
<<<
HTTP/1.1 500
content-length: 899
content-type: application/json; charset=utf-8
cache-control: no-cache

{"value":{"error":"unknown error","message":"unknown error: Chrome failed to start: crashed.\n  (chrome not reachable)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)","stacktrace":"#0 0x0040006d74e3 \u003Cunknown>\n#1 0x004000406c76 \u003Cunknown>\n#2 0x00400042fd78 \u003Cunknown>\n#3 0x00400042c029 \u003Cunknown>\n#4 0x00400046accc \u003Cunknown>\n#5 0x00400046a47f \u003Cunknown>\n#6 0x004000461de3 \u003Cunknown>\n#7 0x0040004372dd \u003Cunknown>\n#8 0x00400043834e \u003Cunknown>\n#9 0x0040006973e4 \u003Cunknown>\n#10 0x00400069b3d7 \u003Cunknown>\n#11 0x0040006a5b20 \u003Cunknown>\n#12 0x00400069c023 \u003Cunknown>\n#13 0x00400066a1aa \u003Cunknown>\n#14 0x0040006c06b8 \u003Cunknown>\n#15 0x0040006c0847 \u003Cunknown>\n#16 0x0040006d0243 \u003Cunknown>\n#17 0x0040026c3609 start_thread\n"}}
    1) headless
```

### Operating System

Ubuntu Docker

### Selenium version

4.1.15

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 114.0.5735.106 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.90

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
How are you running `selenium/node-chrome:latest`?

**Comment by titusfortner** [comment]
We can only troubleshoot issues with latest version of Selenium. Please update and if you still have the problem, turn on logging so we can see the details.

**Comment by shermanrxie** [comment]
> How are you running `selenium/node-chrome:latest`?
 @diemol @titusfortner   Yes,  I run selenium/node-chrome:latest  image in my local mac machine.

export DOCKER_DEFAULT_PLATFORM=linux/amd64 
docker run -it  -v /lcoalcode:/tmp2 selenium/node-chrome:latest bash
npm install 
npm run test

And I'm not sure whether ChromeDriver 114.0.5735.90 is compatiable with Google Chrome 114.0.5735.106

**Comment by diemol** [comment]
@shermanrxie please check the docs that show how to start the Grid containers: https://github.com/SeleniumHQ/docker-selenium#execution-modes (you are missing the `shm` option).

Also, you are starting just a Node.
