### ISSUE TITLE
[🐛 Bug]: Ruby selenium-webdriver find_element invocation yields Selenium::WebDriver::Error::UnknownError when using safaridriver

### ISSUE THREAD

**Issue by tpospisil** [SeleniumHQ/selenium#12227]
### What happened?

Attempting to find an element using the Ruby `selenium-webdriver` gem’s `#find_element` method is resulting in a `Selenium::WebDriver::Error::UnknownError` exception when performed on certain web pages. The issue appears to be consistently reproducible for newer versions of safari, but potentially not for earlier versions. This issue is not reproducible in any other browser’s driver, including: Chrome (chromedriver), Firefox (geckodriver), and Edge (edgedriver).

### How can we reproduce the issue?

```shell
Ruby version: ruby-3.0.4
selenium-webdriver version: 4.10.0

Repro steps:
1. Clone this repository, which contains a ruby script that will demonstrate the issue: https://github.com/tpospisil/safaridriver-se-issue
2. Perform the setup steps listed in the README 
3. Execute the test by running `ruby test-script.rb`. The test will execute a script that will run two tests — each of which is tasked with navigating to a URL and locating an element by its CSS selector.
```

### Relevant log output

```shell
# Logfile created on 2023-06-19 12:10:59 -0700 by logger.rb/v1.4.3
2023-06-19 12:10:59 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2023-06-19 12:10:59 DEBUG Selenium [:driver_service] Executing Process ["/usr/bin/safaridriver", "--port=7050"] 
2023-06-19 12:10:59 DEBUG Selenium [:process] Starting process: ["/usr/bin/safaridriver", "--port=7050"] with {[:out, :err]=>#<File:selenium.log>, :pgroup=>true} 
2023-06-19 12:10:59 DEBUG Selenium [:process]   -> pid: 7441 
2023-06-19 12:10:59 DEBUG Selenium [:driver_service] polling for socket on ["127.0.0.1", 7050] 
2023-06-19 12:10:59 DEBUG Selenium [:command] -> POST session 
2023-06-19 12:10:59 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session | {"capabilities":{"alwaysMatch":{"browserName":"safari"}}} 
2023-06-19 12:10:59 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"57"} 
2023-06-19 12:11:00 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:00 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["517"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:00 DEBUG Selenium [:command] <- {"value":{"sessionId":"0539C87D-F6C6-444B-B658-C16E228216F0","capabilities":{"safari:platformVersion":"11.3.1","safari:automaticInspection":false,"webkit:WebRTC":{"DisableICECandidateFiltering":false,"DisableInsecureMediaCapture":false},"browserVersion":"14.1","strictFileInteractability":false,"browserName":"Safari","safari:useSimulator":false,"safari:automaticProfiling":false,"safari:platformBuildVersion":"20E241","acceptInsecureCerts":false,"setWindowRect":true,"platformName":"macOS","safari:diagnose":false}}} 
2023-06-19 12:11:00 DEBUG Selenium [:command] -> POST session/0539C87D-F6C6-444B-B658-C16E228216F0/timeouts 
2023-06-19 12:11:00 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session/0539C87D-F6C6-444B-B658-C16E228216F0/timeouts | {"implicit":30000} 
2023-06-19 12:11:00 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"18"} 
2023-06-19 12:11:00 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:00 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["14"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:00 DEBUG Selenium [:command] <- {"value":null} 
2023-06-19 12:11:00 DEBUG Selenium [:command] -> POST session/0539C87D-F6C6-444B-B658-C16E228216F0/url 
2023-06-19 12:11:00 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session/0539C87D-F6C6-444B-B658-C16E228216F0/url | {"url":"https://saas-release.snapsheet.tech/efnol/kin_us?policy_number=systemTests-HO&date_of_loss=2020-01-01&name=Rizzo"} 
2023-06-19 12:11:00 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"122"} 
2023-06-19 12:11:03 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:03 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["14"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:03 DEBUG Selenium [:command] <- {"value":null} 
2023-06-19 12:11:03 DEBUG Selenium [:command] -> POST session/0539C87D-F6C6-444B-B658-C16E228216F0/element 
2023-06-19 12:11:03 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session/0539C87D-F6C6-444B-B658-C16E228216F0/element | {"using":"css selector","value":".ss-btn-secondary-dark"} 
2023-06-19 12:11:03 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"57"} 
2023-06-19 12:11:03 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:03 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["64"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:03 DEBUG Selenium [:command] <- {"value":{"error":"unknown error","message":"","stacktrace":""}} 
2023-06-19 12:11:03 DEBUG Selenium [:command] -> DELETE session/0539C87D-F6C6-444B-B658-C16E228216F0 
2023-06-19 12:11:03 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:03 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["14"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:03 DEBUG Selenium [:command] <- {"value":null} 
2023-06-19 12:11:03 DEBUG Selenium [:process] Checking if 7441 is exited: 
2023-06-19 12:11:03 DEBUG Selenium [:process] Checking if 7441 is exited: 
2023-06-19 12:11:03 DEBUG Selenium [:process] Sending TERM to process: 7441 
2023-06-19 12:11:03 DEBUG Selenium [:process] Polling 20 seconds for exit of 7441 
2023-06-19 12:11:03 DEBUG Selenium [:process] Checking if 7441 is exited: 
2023-06-19 12:11:03 DEBUG Selenium [:process] Checking if 7441 is exited: 
2023-06-19 12:11:03 DEBUG Selenium [:process]   -> exit code is 0 
2023-06-19 12:11:03 DEBUG Selenium [:process] Checking if 7441 is exited: 
2023-06-19 12:11:03 DEBUG Selenium [:process]   -> exit code is 0 
2023-06-19 12:11:03 DEBUG Selenium [:process]   -> stopped 7441 
2023-06-19 12:11:03 DEBUG Selenium [:driver_service] Executing Process ["/usr/bin/safaridriver", "--port=7050"] 
2023-06-19 12:11:03 DEBUG Selenium [:process] Starting process: ["/usr/bin/safaridriver", "--port=7050"] with {[:out, :err]=>#<File:selenium.log>, :pgroup=>true} 
2023-06-19 12:11:03 DEBUG Selenium [:process]   -> pid: 7453 
2023-06-19 12:11:03 DEBUG Selenium [:driver_service] polling for socket on ["127.0.0.1", 7050] 
2023-06-19 12:11:03 DEBUG Selenium [:command] -> POST session 
2023-06-19 12:11:03 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session | {"capabilities":{"alwaysMatch":{"browserName":"safari"}}} 
2023-06-19 12:11:03 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"57"} 
2023-06-19 12:11:04 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:04 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["517"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:04 DEBUG Selenium [:command] <- {"value":{"sessionId":"2AD2A189-17F1-4CD2-BB22-14439FF4FE00","capabilities":{"safari:platformVersion":"11.3.1","safari:automaticInspection":false,"webkit:WebRTC":{"DisableICECandidateFiltering":false,"DisableInsecureMediaCapture":false},"browserVersion":"14.1","strictFileInteractability":false,"browserName":"Safari","safari:useSimulator":false,"safari:automaticProfiling":false,"safari:platformBuildVersion":"20E241","acceptInsecureCerts":false,"setWindowRect":true,"platformName":"macOS","safari:diagnose":false}}} 
2023-06-19 12:11:04 DEBUG Selenium [:command] -> POST session/2AD2A189-17F1-4CD2-BB22-14439FF4FE00/timeouts 
2023-06-19 12:11:04 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session/2AD2A189-17F1-4CD2-BB22-14439FF4FE00/timeouts | {"implicit":30000} 
2023-06-19 12:11:04 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"18"} 
2023-06-19 12:11:04 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:04 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["14"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:04 DEBUG Selenium [:command] <- {"value":null} 
2023-06-19 12:11:04 DEBUG Selenium [:command] -> POST session/2AD2A189-17F1-4CD2-BB22-14439FF4FE00/url 
2023-06-19 12:11:04 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session/2AD2A189-17F1-4CD2-BB22-14439FF4FE00/url | {"url":"https://saas-release.snapsheet.tech/app/snapsheet_insurance/start"} 
2023-06-19 12:11:04 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"75"} 
2023-06-19 12:11:05 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:05 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["14"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:05 DEBUG Selenium [:command] <- {"value":null} 
2023-06-19 12:11:05 DEBUG Selenium [:command] -> POST session/2AD2A189-17F1-4CD2-BB22-14439FF4FE00/element 
2023-06-19 12:11:05 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session/2AD2A189-17F1-4CD2-BB22-14439FF4FE00/element | {"using":"css selector","value":".ss-btn-secondary-dark"} 
2023-06-19 12:11:05 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"57"} 
2023-06-19 12:11:05 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:05 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["93"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:05 DEBUG Selenium [:command] <- {"value":{"element-6066-11e4-a52e-4f735466cecf":"node-F9B68ACE-C218-48B9-99D9-A14D0C8697E9"}} 
2023-06-19 12:11:05 DEBUG Selenium [:command] -> DELETE session/2AD2A189-17F1-4CD2-BB22-14439FF4FE00 
2023-06-19 12:11:05 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [16611.1.21.161.6]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Mon, 19 Jun 2023 19:11:05 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["14"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-19 12:11:05 DEBUG Selenium [:command] <- {"value":null} 
2023-06-19 12:11:05 DEBUG Selenium [:process] Checking if 7453 is exited: 
2023-06-19 12:11:05 DEBUG Selenium [:process] Checking if 7453 is exited: 
2023-06-19 12:11:05 DEBUG Selenium [:process] Sending TERM to process: 7453 
2023-06-19 12:11:05 DEBUG Selenium [:process] Polling 20 seconds for exit of 7453 
2023-06-19 12:11:05 DEBUG Selenium [:process] Checking if 7453 is exited: 
2023-06-19 12:11:05 DEBUG Selenium [:process] Checking if 7453 is exited: 
2023-06-19 12:11:05 DEBUG Selenium [:process]   -> exit code is 0 
2023-06-19 12:11:05 DEBUG Selenium [:process] Checking if 7453 is exited: 
2023-06-19 12:11:05 DEBUG Selenium [:process]   -> exit code is 0 
2023-06-19 12:11:05 DEBUG Selenium [:process]   -> stopped 7453 
2023-06-19 12:11:05 DEBUG Selenium [:process] Checking if 7453 is exited: 
2023-06-19 12:11:05 DEBUG Selenium [:process]   -> exit code is 0 
2023-06-19 12:11:05 DEBUG Selenium [:process] Checking if 7441 is exited: 
2023-06-19 12:11:05 DEBUG Selenium [:process]   -> exit code is 0
```

### Operating System

macOS Big Sur

### Selenium version

Ruby 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Safari 14.1

### What are the browser driver(s) and version(s) where you see this issue?

Included with Safari 14.1

### Are you using Selenium Grid?

N/A

**Comment by titusfortner** [comment]
Thanks for giving the full reproduction including the logging. What was sent to the driver by Selenium is correct, so this going to be an issue with Safari Driver.

**Comment by tpospisil** [comment]
Thanks for the quick reply, @titusfortner. I tried logging this issue with Apple (feedback ID: FB12339555) with the exact same information and it was seemingly closed with resolution "Investigation complete - Unable to diagnose with current information" without any further explanation. I will continue to try to pester them about this issue.

**Comment by titusfortner** [comment]
Apple is frustrating. You can give an even smaller reproduction, though:

```
titusfortner@SL-1837 ~ % irb
irb(main):001:0> require 'selenium-webdriver'
=> true
irb(main):002:0> Selenium::WebDriver.logger.level = :debug
=> :debug
irb(main):003:0> driver = Selenium::WebDriver.for :safari
2023-06-20 14:19:18 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2023-06-20 14:19:18 DEBUG Selenium [:driver_service] Executing Process ["/System/Cryptexes/App/usr/bin/safaridriver", "--port=7050"] 
2023-06-20 14:19:18 DEBUG Selenium [:process] Starting process: ["/System/Cryptexes/App/usr/bin/safaridriver", "--port=7050"] with {[:out, :err]=>#<IO:<STDOUT>>, :pgroup=>true} 
2023-06-20 14:19:18 DEBUG Selenium [:process]   -> pid: 14600 
2023-06-20 14:19:18 DEBUG Selenium [:driver_service] polling for socket on ["127.0.0.1", 7050] 
2023-06-20 14:19:18 DEBUG Selenium [:command] -> POST session 
2023-06-20 14:19:18 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session | {"capabilities":{"alwaysMatch":{"browserName":"safari"}}} 
2023-06-20 14:19:18 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"57"} 
2023-06-20 14:19:18 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [18615.2.9.11.4]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Tue, 20 Jun 2023 19:19:18 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["514"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-20 14:19:18 DEBUG Selenium [:command] <- {"value":{"sessionId":"FDC23786-5011-4CEF-B467-B441A1BD889C","capabilities":{"safari:platformVersion":"13.4","safari:automaticInspection":false,"webkit:WebRTC":{"DisableICECandidateFiltering":false,"DisableInsecureMediaCapture":false},"browserVersion":"16.5","strictFileInteractability":false,"browserName":"Safari","safari:useSimulator":false,"safari:automaticProfiling":false,"safari:platformBuildVersion":"22F66","acceptInsecureCerts":false,"setWindowRect":true,"platformName":"macOS","safari:diagnose":false}}} 
=> #<Selenium::WebDriver::Safari::Driver:0x72ec58e696b539d2 browser=:safari>
irb(main):004:0> driver.get 'https://saas-release.snapsheet.tech/efnol/kin_us'
2023-06-20 14:19:28 DEBUG Selenium [:command] -> POST session/FDC23786-5011-4CEF-B467-B441A1BD889C/url 
2023-06-20 14:19:28 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session/FDC23786-5011-4CEF-B467-B441A1BD889C/url | {"url":"https://saas-release.snapsheet.tech/efnol/kin_us"} 
2023-06-20 14:19:28 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"58"} 
2023-06-20 14:19:29 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [18615.2.9.11.4]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Tue, 20 Jun 2023 19:19:29 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["14"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-20 14:19:29 DEBUG Selenium [:command] <- {"value":null} 
=> nil
irb(main):005:0> driver.find_element(css: 'body')
2023-06-20 14:19:38 DEBUG Selenium [:command] -> POST session/FDC23786-5011-4CEF-B467-B441A1BD889C/element 
2023-06-20 14:19:38 DEBUG Selenium [:command]    >>> http://127.0.0.1:7050/session/FDC23786-5011-4CEF-B467-B441A1BD889C/element | {"using":"css selector","value":"body"} 
2023-06-20 14:19:38 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.10.0 (ruby macosx)", "Content-Length"=>"39"} 
2023-06-20 14:19:38 DEBUG Selenium [:header]    <<<  {"server"=>["safaridriver [18615.2.9.11.4]"], "content-type"=>["application/json; charset=utf-8"], "date"=>["Tue, 20 Jun 2023 19:19:38 GMT"], "accept-ranges"=>["bytes"], "content-length"=>["64"], "cache-control"=>["no-cache"], "connection"=>["keep-alive"]} 
2023-06-20 14:19:38 DEBUG Selenium [:command] <- {"value":{"error":"unknown error","message":"","stacktrace":""}} 
/Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok': Selenium::WebDriver::Error::UnknownError
	from /Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
	from /Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
	from /Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
	from /Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:537:in `find_element_by'
	from /Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/search_context.rb:63:in `find_element'
	from (irb):5:in `<main>'
	from /Users/titusfortner/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /Users/titusfortner/.rbenv/versions/3.0.6/bin/irb:23:in `load'
	from /Users/titusfortner/.rbenv/versions/3.0.6/bin/irb:23:in `<main>'
```
