### ISSUE TITLE
[🐛 Bug]: 50 Consoles of chrome after python interpreter shutdown

### ISSUE THREAD

**Issue by Were-Logan-0110** [SeleniumHQ/selenium#12259]
### What happened?

i tried running selenium alot of instances of the chrome webdriver (50) on a threading env on a PyQt5 application and got alot of different errors some of are no response and invalid session id 

so i tried stopping the program and the interpreter so it result to a very weird bug of
50 consoles with a title of the "path to the chrome.exe" 
and when i try closing them they get opened again [Im sure the interpreter was closed as i closed the program used the terminate method on the app and deleted the vsc terminal]
NOTE : when i try with maybe a less number of threads like 10 it works kind of fine
["C:\Users\ahmed\AppData\Local\Google\Chrome\Application\chrome.exe"]

thats a screenshot of what happened 
![image](https://github.com/SeleniumHQ/selenium/assets/123822233/6c58ae55-1805-4275-b645-4fdcc058e1e8)

```py
class ConcurrencyManager:
    def __init__(self, initial_limit=5):
        self.limit = initial_limit
        self.semaphore = threading.BoundedSemaphore(initial_limit)

    def update_limit(self, new_limit):
        self.limit = new_limit
        self.semaphore = threading.BoundedSemaphore(new_limit)

    def acquire(self):
        return self.semaphore.acquire()

    def release(self):
        return self.semaphore.release()

class SeleniumGoogleFetcher:
    def __init__(self, urls, Window, concurrency_limit=5):
        self.drivers = []
        def getData():
            self.urls = urls
            self.concurrency_limit = ConcurrencyManager(concurrency_limit)
            self.Window = Window
            self.window = Window
            self.queue = queue.Queue()
            self.headless = Window.checkBox_37.isChecked()
            self.port = Window.spinBox_15.value()
            self.customArguments = Window.lineEdit_20.text()
            self.log = Window.checkBox_36.isChecked()
            self.useStealth = Window.checkBox_38.isChecked()
            self.chromeDriverPath = Window.lineEdit_21.placeholderText()
            self.bravePath = Window.lineEdit_22.placeholderText()
            self.browser = Window.comboBox_19.currentText()
            self.isPaused = False
            self.isTerminated = False
        inmain(getData)

    def MakeDriver(self):
        Service = ChromeService(self.chromeDriverPath, port=self.port)
        Options = ChromeOptions()
        if self.customArguments != "":
            Options.add_argument(self.customArguments)
        Options.headless = self.headless
        if self.browser != "Chrome":
            Options.binary_location = self.bravePath
        driver = Chrome(service=Service, options=Options)
        if self.useStealth:
            stealth(
                driver,
                languages=["en-US", "en"],
                vendor="Google Inc.",
                platform="Win32",
                webgl_vendor="Intel Inc.",
                renderer="Intel Iris OpenGL Engine",
                fix_hairline=True,
            )
        driver.delete_all_cookies()
        self.drivers.append(driver)
        return driver

    def pause(self):
        self.isPaused = True

    def resume(self):
        self.isPaused = False

    def setItem(self, item, list_widget, label):
        def main():
            if item != "" and item != " " and item != len(item) > 3:
                list_widget.addItem(item)
                label.setText(str(list_widget.count()))

        inmain(main)

    def addOne(self):
        def main():
            self.window.label_36.setText(str(int(self.window.label_36.text()) + 1))

        inmain(main)

    def terminate(self):
        self.isTerminated = True
        for driver in self.drivers:
            driver.quit()
    @ErrorWrapper
    def fetch(self, url):
        while self.isPaused:
            sleep(1)

        if self.isTerminated:
            return

        try:
            if self.isTerminated:
                return
            driver = self.MakeDriver()
            print(f"SENDING GET REQUEST TO {url}")
            driver.get(url)

            while "Our systems have detected unusual traffic" in driver.page_source:
                print("Solving reCaptcha")
                Recaptcha_Solver(
                    driver=driver,
                    debug=True
                ).solve_recaptcha()
            parser = GoogleParser(driver.page_source)
            driver.quit()
            main_class = parser.GetMainResultsClass()
            results = parser.ParseAllResults(main_class)
            for result in results.values():
                self.setItem(result["url"], self.window.listWidget_9, self.window.label_18)
                self.setItem(result["title"], self.window.listWidget_10, self.window.label_29)
                self.setItem(result["description"], self.window.listWidget_11, self.window.label_29)
            return
        except Exception as e:
            print(url)
            print(traceback.format_exc())
            if self.isTerminated:
                return

    @ErrorWrapper
    def fetch_all(self):
        def fetch_with_semaphore(sem, url):
            with sem:
                self.fetch(url)

        if self.isTerminated:
            return

        
        worker_threads = []
        for _ in range(self.concurrency_limit.limit):
            worker_thread = threading.Thread(target=self.worker, args=())
            worker_threads.append(worker_thread)
            worker_thread.start()

        
        for url in self.urls:
            self.queue.put(url)

        
        self.queue.join()

        
        for worker_thread in worker_threads:
            worker_thread.join()
    @ErrorWrapper
    def worker(self):
        if self.isTerminated:
            return
        while True:
            url = self.queue.get()
            try:
                self.fetch(url)
            finally:
                self.queue.task_done()
    @ErrorWrapper
    def main(self):
        self.fetch_all()
```

some of the results on the terminal

```py
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Traceback (most recent call last):
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request        
    response = conn.getresponse()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\me\Better-Dorky\GoogleRScraper.py", line 373, in fetch
    driver.get(url)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 355, in get     
    self.execute(Command.GET, {"url": url})
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute 
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 290, in 
execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 311, in 
_request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\_request_methods.py", line 118, in request
    return self.request_encode_body(
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\_request_methods.py", line 217, in request_encode_body    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request        
    response = conn.getresponse()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Traceback (most recent call last):
  File "e:\me\Better-Dorky\GoogleRScraper.py", line 375, in fetch
    while "Our systems have detected unusual traffic" in driver.page_source:
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 447, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)["value"]
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute 
    self.error_handler.check_response(response)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python310-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
```

### How can we reproduce the issue?

```shell
.
```

### Relevant log output

```shell
.
```

### Operating System

Windows 10

### Selenium version

Python10

### What are the browser(s) and version(s) where you see this issue?

Chrome 94

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 94

### Are you using Selenium Grid?

4.10.0

**Comment by titusfortner** [comment]
Actually, maybe this is your issue? https://github.com/SeleniumHQ/selenium/issues/12138#issuecomment-1574941188

**Comment by Were-Logan-0110** [comment]
> Actually, maybe this is your issue? [#12138 (comment)](https://github.com/SeleniumHQ/selenium/issues/12138#issuecomment-1574941188)

but it doesnot open the consoles on run instead after shutdown so if i made the threads to 50 after shutdown it will open 50 console + even trying to close it wouldnot as it will pop up again untill they are the count of threads

**Comment by titusfortner** [comment]
Can you reproduce this issue without running in parallel?

**Comment by Were-Logan-0110** [comment]
> Can you reproduce this issue without running in parallel?

probably will not happened as it mostly happens when there is alot of drivers are there when it exits

**Comment by Were-Logan-0110** [comment]
> Can you reproduce this issue without running in parallel?

maybe can you run the code on your machine and check if it happens to u?

**Comment by diemol** [comment]
> > Can you reproduce this issue without running in parallel?
> 
> maybe can you run the code on your machine and check if it happens to u?

Sorry, we need a reduced test case to reproduce the issue. We cannot troubleshoot a web scraper.

**Comment by diemol** [comment]
Basically we need what this comment already mentions https://github.com/SeleniumHQ/selenium/issues/12259#issuecomment-1607632131

**Comment by Were-Logan-0110** [comment]
> > > Can you reproduce this issue without running in parallel?
> > 
> > maybe can you run the code on your machine and check if it happens to u?
> 
> Sorry, we need a reduced test case to reproduce the issue. We cannot troubleshoot a web scraper. 

im not sure how can i do such a thing? but wdym a web scrapped you can remove the scraping parts it doesn't got anything to do with it yk?

**Comment by diemol** [comment]
To be more precise, we really need a reduced test case that only uses Selenium to troubleshoot this. For example, the code you are providing has external dependencies we don't know how to install and use. We simply need code that we can copy and paste, and then execute after installing Selenium.

**Comment by diemol** [comment]
Closing as we did not get any more information.
