### ISSUE TITLE
[🐛 Bug]: Unable to Identify locators on Chrome 114 version using Selenium WebDriver

### ISSUE THREAD

**Issue by sekhartirumala** [SeleniumHQ/selenium#12257]
### What happened?

We are using selenium with WebDriver manager after updating Chrome 114 version we are not able to identify locators on webpage. The same code is working fine with Chrome 112 version. 

### How can we reproduce the issue?

```shell
ChromeOptions options = new ChromeOptions();
options.addArguments("--disable-gpu");
options.addArguments("--remote-allow-origins=*");
options.addArguments("--start-maximized");
driver = new ChromeDriver(options);
driver.navigate().to("URL");
driver.findElement(By.id("j_username")).sendKeys("loginname"); 
driver.findElement(By.id("j_password")).sendKeys("xxxx");
driver.findElement(By.id("log-in-command")).click();
driver.findElement(By.linkText("Reset Session")).click();
WebElement element = driver.findElement(By.xpath("//html//body"));
String text = driver.getPageSource();
System.out.println("Page Text:"+text);
```

### Relevant log output

```shell
SeleniumTest
Jun 26, 2023 6:18:05 PM org.openqa.selenium.remote.service.DriverService$Builder getLogOutput
INFO: Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//html//body"}
  (Session info: chrome=114.0.5735.134)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_341'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [b755d51e10f57fb64339b2369f9587f4, findElement {using=xpath, value=//html//body}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 114.0.5735.134, chrome: {chromedriverVersion: 114.0.5735.90 (386bc09e8f4f..., userDataDir: C:\Users\LOCAL_~1\Temp\scop...}, goog:chromeOptions: {debuggerAddress: localhost:53395}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:53395/devtoo..., se:cdpVersion: 114.0.5735.134, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: b755d51e10f57fb64339b2369f9587f4
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:199)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:132)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:51)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at SeleniumTest.main(SeleniumTest.java:31)
```

### Operating System

Windows 10

### Selenium version

Java 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 114.0.5735.134

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 114.0.5735.90

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
Does using `By.tagName("body")` or `By.cssSelector("body")` work? Either way, Selenium code is sending the right things to the driver. If it is working in v112 and not v114 it may be a regression in chromedriver. I'll add the link for submitting an issue below.

**Comment by sekhartirumala** [comment]
Thank you for the quick response. We have created an issue with ChromeDriver team https://bugs.chromium.org/p/chromedriver/issues/detail?id=4487

**Comment by jpvasconcelos-m** [comment]
Maybe using this could help:

use:
import org.openqa.selenium.support.ui.WebDriverWait
WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30)); 

and change:
WebElement element = driver.findElement(By.xpath("//html//body"))  to:
WebElement element = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//html//body")));
