### ISSUE TITLE
[🐛 Bug]: `NetworkInterceptor` crashes `FirefoxDriver`

### ISSUE THREAD

**Issue by csvtuda** [SeleniumHQ/selenium#12282]
### What happened?

I am currently preparing for a Java & Maven testing project where certain HTTP responses will need to be intercepted during browser navigation. For interception, I set up a `NetworkInterceptor` as described in the [documentation](https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/#network-interception).

The driver instance is acquired through the Selenium Manager. I don't have any driver executables in `PATH`, nor am I using a web driver manager. Apart from `groupId` etc., the content of my `pom.xml` is simply:

```xml
<project>
    <!-- ... -->
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.10.0</version>
        </dependency>
    </dependencies>
</project>
```
When I run the SSCCE below, Firefox crashes for reasons I don't really understand (see attached log output). To reproduce the issue, simply run the main method.

The other drivers (`ChromeDriver`, `EdgeDriver` or `InternetExplorerDriver`) work just fine and result in `Example Domain` (https://example.org) being printed to the console.

Am I doing something wrong? Do I need to configure certain `FirefoxOptions` beforehand? I could not find anything on the Internet, apart from a somewhat similar `selenium-wire` [discussion](https://github.com/wkeeling/selenium-wire/issues/326#issuecomment-862628163), which obviously did not work.

The (default) firefox capabilities are as follows:

```json
{
   "acceptInsecureCerts":true,
   "browserName":"firefox",
   "browserVersion":"113.0.2",
   "moz:accessibilityChecks":false,
   "moz:buildID":"20230522134052",
   "moz:debuggerAddress":"127.0.0.1:35403",
   "moz:geckodriverVersion":"0.33.0",
   "moz:headless":false,
   "moz:platformVersion":"10.0",
   "moz:processID":18732,
   "moz:profile":"C:\\...",
   "moz:shutdownTimeout":60000,
   "moz:useNonSpecCompliantPointerOrigin":false,
   "moz:webdriverClick":true,
   "moz:windowless":false,
   "pageLoadStrategy":"normal",
   "platformName":"windows",
   "proxy":"Proxy()",
   "se:cdp":"ws://127.0.0.1:35403/devtoo...",
   "se:cdpVersion":"85.0",
   "setWindowRect":true,
   "strictFileInteractability":false,
   "timeouts":{
      "implicit":0,
      "pageLoad":300000,
      "script":30000
   },
   "unhandledPromptBehavior":"dismiss and notify"
}
```

### How can we reproduce the issue?

```java
package selenium;

import org.openqa.selenium.devtools.NetworkInterceptor;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.http.Filter;
import org.openqa.selenium.remote.http.HttpResponse;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {

    static {
        Logger logger = Logger.getLogger("");
        logger.setLevel(Level.FINE);
        Arrays.stream(logger.getHandlers()).forEach(handler -> handler.setLevel(Level.FINE));
    }

    public static void main(String[] args) {
        RemoteWebDriver driver = new FirefoxDriver();
        Filter filter = handler -> request -> {
            HttpResponse res = handler.execute(request);
            try {
                String body = new String(res.getContent().get().readAllBytes(), StandardCharsets.UTF_8);
                Pattern pattern = Pattern.compile("<title>(.+)</title>");
                Matcher matcher = pattern.matcher(body);
                if (matcher.find()) {
                    System.out.println(matcher.group(1));
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
            return res;
        };
        try (NetworkInterceptor ignored = new NetworkInterceptor(driver, filter)) {
            driver.get("https://example.org");
            driver.quit();
        }
    }

}
```

### Relevant log output

```shell
Juni 28, 2023 5:45:41 PM org.openqa.selenium.remote.service.DriverService$Builder getLogOutput
INFORMATION: Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output
Juni 28, 2023 5:45:41 PM org.openqa.selenium.manager.SeleniumManager getDriverPath
FINE: Applicable driver not found; attempting to install with Selenium Manager (Beta)
Juni 28, 2023 5:45:41 PM org.openqa.selenium.manager.SeleniumManager runCommand
FINE: Executing Process: [C:\Users\user\AppData\Local\Temp\selenium-manager11667388974750010546430013306487898\selenium-manager.exe, --browser, firefox, --output, json, --debug]
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Using shell command to find out firefox version
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Running command: "set PFILES=%PROGRAMFILES: (x86)=%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Mozilla Firefox\\\\firefox.exe' get Version /value"
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Output: "\r\r\n\r\r\nVersion=113.0.2.8542\r\r\n\r\r\n\r\r\n\r"
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: The version of firefox is 113.0.2.8542
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Detected browser: firefox 113
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Required driver: geckodriver 0.33.0
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Running command: "geckodriver --version"
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Output: ""
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: geckodriver 0.33.0 already in the cache
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: C:\Users\user\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
Juni 28, 2023 5:45:42 PM org.openqa.selenium.manager.SeleniumManager getDriverPath
FINE: Using driver at location: C:\Users\user\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Juni 28, 2023 5:45:42 PM io.netty.util.internal.logging.InternalLoggerFactory useJdkLoggerFactory
FINE: Using java.util.logging as the default logging framework
Juni 28, 2023 5:45:42 PM io.netty.util.ResourceLeakDetector <clinit>
FINE: -Dio.netty.leakDetection.level: simple
Juni 28, 2023 5:45:42 PM io.netty.util.ResourceLeakDetector <clinit>
FINE: -Dio.netty.leakDetection.targetRecords: 4
Juni 28, 2023 5:45:42 PM io.netty.util.ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory newResourceLeakDetector
FINE: Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@657c8ad9
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 explicitNoUnsafeCause0
FINE: -Dio.netty.noUnsafe: false
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 javaVersion0
FINE: Java version: 17
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: sun.misc.Unsafe.theUnsafe: available
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: sun.misc.Unsafe.copyMemory: available
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: sun.misc.Unsafe.storeFence: available
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: java.nio.Buffer.address: available
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: direct buffer constructor: unavailable: Reflective setAccessible(true) disabled
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: java.nio.Bits.unaligned: available, true
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: class io.netty.util.internal.PlatformDependent0$7 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @32a068d1
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: java.nio.DirectByteBuffer.<init>(long, int): unavailable
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent unsafeUnavailabilityCause0
FINE: sun.misc.Unsafe: available
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent estimateMaxDirectMemory
FINE: maxDirectMemory: 4221566976 bytes (maybe)
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent tmpdir0
FINE: -Dio.netty.tmpdir: C:\Users\user\AppData\Local\Temp (java.io.tmpdir)
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent bitMode0
FINE: -Dio.netty.bitMode: 64 (sun.arch.data.model)
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent isWindows0
FINE: Platform: Windows
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent <clinit>
FINE: -Dio.netty.maxDirectMemory: -1 bytes
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent <clinit>
FINE: -Dio.netty.uninitializedArrayAllocationThreshold: -1
Juni 28, 2023 5:45:42 PM io.netty.util.internal.CleanerJava9 <clinit>
FINE: java.nio.ByteBuffer.cleaner(): available
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent <clinit>
FINE: -Dio.netty.noPreferDirect: false
Juni 28, 2023 5:45:42 PM io.netty.util.internal.PlatformDependent$Mpsc <clinit>
FINE: org.jctools-core.MpscChunkedArrayQueue: available
Juni 28, 2023 5:45:42 PM io.netty.util.internal.InternalThreadLocalMap <clinit>
FINE: -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
Juni 28, 2023 5:45:42 PM io.netty.util.internal.InternalThreadLocalMap <clinit>
FINE: -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
Juni 28, 2023 5:45:42 PM jdk.internal.event.EventHelper logX509CertificateEvent
# [certificates omitted]
Juni 28, 2023 5:45:42 PM jdk.internal.event.EventHelper logX509CertificateEvent
Juni 28, 2023 5:45:42 PM io.netty.handler.ssl.JdkSslContext <clinit>
FINE: Default protocols (JDK): [TLSv1.3, TLSv1.2] 
Juni 28, 2023 5:45:42 PM io.netty.handler.ssl.JdkSslContext <clinit>
FINE: Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384]
Juni 28, 2023 5:45:42 PM io.netty.util.concurrent.GlobalEventExecutor <clinit>
FINE: -Dio.netty.globalEventExecutor.quietPeriodSeconds: 1
Juni 28, 2023 5:45:42 PM io.netty.channel.MultithreadEventLoopGroup <clinit>
FINE: -Dio.netty.eventLoopThreads: 16
Juni 28, 2023 5:45:42 PM io.netty.channel.nio.NioEventLoop <clinit>
FINE: -Dio.netty.noKeySetOptimization: false
Juni 28, 2023 5:45:42 PM io.netty.channel.nio.NioEventLoop <clinit>
FINE: -Dio.netty.selectorAutoRebuildThreshold: 512
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.numHeapArenas: 16
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.numDirectArenas: 16
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.pageSize: 8192
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.maxOrder: 9
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.chunkSize: 4194304
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.smallCacheSize: 256
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.normalCacheSize: 64
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.maxCachedBufferCapacity: 32768
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.cacheTrimInterval: 8192
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.cacheTrimIntervalMillis: 0
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.useCacheForAllThreads: false
Juni 28, 2023 5:45:42 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
Juni 28, 2023 5:45:42 PM io.netty.buffer.ByteBufUtil <clinit>
FINE: -Dio.netty.allocator.type: pooled
Juni 28, 2023 5:45:42 PM io.netty.buffer.ByteBufUtil <clinit>
FINE: -Dio.netty.threadLocalDirectBufferSize: 0
Juni 28, 2023 5:45:42 PM io.netty.buffer.ByteBufUtil <clinit>
FINE: -Dio.netty.maxThreadLocalCharBufferSize: 16384
Juni 28, 2023 5:45:42 PM org.openqa.selenium.remote.RemoteWebDriver log
FINE: Executing: newSession [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}}]}]
Juni 28, 2023 5:45:42 PM org.openqa.selenium.remote.service.DriverService start
FINE: Starting driver at C:\Users\user\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe with [--port=15593, --websocket-port=11726, --allow-origins, http://127.0.0.1:11726, http://localhost:11726, http://[::1]:11726]
Juni 28, 2023 5:45:43 PM io.netty.channel.DefaultChannelId <clinit>
FINE: -Dio.netty.processId: 22768 (auto-detected)
Juni 28, 2023 5:45:43 PM io.netty.util.NetUtil <clinit>
FINE: -Djava.net.preferIPv4Stack: false
Juni 28, 2023 5:45:43 PM io.netty.util.NetUtil <clinit>
FINE: -Djava.net.preferIPv6Addresses: false
Juni 28, 2023 5:45:43 PM io.netty.util.NetUtilInitializations determineLoopback
FINE: Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
Juni 28, 2023 5:45:43 PM io.netty.util.NetUtil$SoMaxConnAction run
FINE: Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
Juni 28, 2023 5:45:43 PM io.netty.channel.DefaultChannelId <clinit>
FINE: -Dio.netty.machineId: 04:56:e5:ff:fe:fa:61:7b (auto-detected)
Juni 28, 2023 5:45:43 PM io.netty.buffer.AbstractByteBuf <clinit>
FINE: -Dio.netty.buffer.checkAccessible: true
Juni 28, 2023 5:45:43 PM io.netty.buffer.AbstractByteBuf <clinit>
FINE: -Dio.netty.buffer.checkBounds: true
Juni 28, 2023 5:45:43 PM io.netty.util.ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory newResourceLeakDetector
FINE: Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@290f0ca
Juni 28, 2023 5:45:43 PM io.netty.util.Recycler <clinit>
FINE: -Dio.netty.recycler.maxCapacityPerThread: 4096
Juni 28, 2023 5:45:43 PM io.netty.util.Recycler <clinit>
FINE: -Dio.netty.recycler.ratio: 8
Juni 28, 2023 5:45:43 PM io.netty.util.Recycler <clinit>
FINE: -Dio.netty.recycler.chunkSize: 32
Juni 28, 2023 5:45:43 PM io.netty.util.Recycler <clinit>
FINE: -Dio.netty.recycler.blocking: false
Juni 28, 2023 5:45:43 PM io.netty.util.Recycler <clinit>
FINE: -Dio.netty.recycler.batchFastThreadLocalOnly: true
Juni 28, 2023 5:45:44 PM io.netty.handler.codec.compression.Brotli <clinit>
FINE: brotli4j not in the classpath; Brotli support will be unavailable.
Juni 28, 2023 5:45:44 PM org.openqa.selenium.remote.ProtocolHandshake createSession
FINE: Detected upstream dialect: W3C
Juni 28, 2023 5:45:45 PM org.openqa.selenium.remote.RemoteWebDriver log
FINE: Executed: newSession (Response: SessionID: e0cf6426-fcc5-41aa-9b35-9d3b92448bf2, Status: 0, Value: {acceptInsecureCerts=true, browserName=firefox, browserVersion=113.0.2, moz:accessibilityChecks=false, moz:buildID=20230522134052, moz:debuggerAddress=127.0.0.1:11726, moz:geckodriverVersion=0.33.0, moz:headless=false, moz:platformVersion=10.0, moz:processID=25412, moz:profile=C:\Users\user\AppData\Local\Temp\rust_mozprofileoitRNJ, moz:shutdownTimeout=60000, moz:useNonSpecCompliantPointerOrigin=false, moz:webdriverClick=true, moz:windowless=false, pageLoadStrategy=normal, platformName=windows, proxy=Proxy(), setWindowRect=true, strictFileInteractability=false, timeouts={implicit=0, pageLoad=300000, script=30000}, unhandledPromptBehavior=dismiss and notify})
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.CdpEndpointFinder getReportedUri
FINE: URI found: http://127.0.0.1:11726
Juni 28, 2023 5:45:45 PM io.netty.util.internal.ThreadLocalRandom newSeed
FINE: -Dio.netty.initialSeedUniquifier: 0x46407eff45d3055d
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
FINE: Found exact CDP implementation for version 85
Juni 28, 2023 5:45:45 PM org.openqa.selenium.remote.RemoteWebDriver log
FINE: Executing: getCurrentWindowHandle [e0cf6426-fcc5-41aa-9b35-9d3b92448bf2, getCurrentWindowHandle {}]
Juni 28, 2023 5:45:45 PM org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec decode
FINE: Decoding response. Response code was: 200 and content: {"value":"1a7080bd-c989-4bf6-bc0c-ec6bc9ed71be"}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.remote.RemoteWebDriver log
FINE: Executed: getCurrentWindowHandle (Response: SessionID: e0cf6426-fcc5-41aa-9b35-9d3b92448bf2, Status: 0, Value: 1a7080bd-c989-4bf6-bc0c-ec6bc9ed71be)
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection send
FINE: -> {
  "id": 1,
  "method": "Target.getTargets",
  "params": {
  }
}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: <- {"id":1,"result":{"targetInfos":[{"targetId":"1a7080bd-c989-4bf6-bc0c-ec6bc9ed71be","type":"page","title":"","url":"about:blank","attached":false,"browserContextId":null}]}}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection send
FINE: -> {
  "id": 2,
  "method": "Target.attachToTarget",
  "params": {
    "targetId": "1a7080bd-c989-4bf6-bc0c-ec6bc9ed71be",
    "flatten": true
  }
}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: <- {"method":"Target.attachedToTarget","params":{"targetInfo":{"targetId":"1a7080bd-c989-4bf6-bc0c-ec6bc9ed71be","type":"page","title":"","url":"about:blank","attached":true,"browserContextId":null},"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe","waitingForDebugger":false}}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: <- {"id":2,"result":{"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"}}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: Method Target.attachedToTarget called with 0 callbacks available
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection send
FINE: -> {
  "id": 3,
  "method": "Target.setAutoAttach",
  "params": {
    "autoAttach": true,
    "waitForDebuggerOnStart": false,
    "flatten": true
  },
  "sessionId": "3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"
}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: <- {"id":3,"result":{},"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe","message":"{\"id\":3,\"result\":{}}"}}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection send
FINE: -> {
  "id": 4,
  "method": "Log.clear",
  "params": {
  },
  "sessionId": "3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"
}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: Method Target.receivedMessageFromTarget called with 0 callbacks available
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: <- {"id":4,"error":{"message":"Log.clear","data":"RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5\nUnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45\n"},"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.DevTools lambda$createSession$0
FATAL: {"id":4,"error":{"message":"Log.clear","data":"RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5\nUnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45\n"},"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"}
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: unknown
org.openqa.selenium.WebDriverException: {"id":4,"error":{"message":"Log.clear","data":"RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5\nUnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45\n"},"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"}
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:260)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:57)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:224)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection send
FINE: -> {
  "id": 5,
  "method": "Network.setCacheDisabled",
  "params": {
    "cacheDisabled": true
  },
  "sessionId": "3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"
}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: <- {"id":5,"result":{},"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: <- {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe","message":"{\"id\":5,\"result\":{}}"}}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: Method Target.receivedMessageFromTarget called with 0 callbacks available
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection send
FINE: -> {
  "id": 6,
  "method": "Fetch.enable",
  "params": {
    "patterns": [
      {
        "requestStage": "Request",
        "urlPattern": "*"
      },
      {
        "requestStage": "Response",
        "urlPattern": "*"
      }
    ],
    "handleAuthRequests": true
  },
  "sessionId": "3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"
}
Juni 28, 2023 5:45:45 PM org.openqa.selenium.devtools.Connection handle
FINE: <- {"id":6,"error":{"message":"Fetch.enable","data":"RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5\nUnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45\n"},"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"}
Exception in thread "main" org.openqa.selenium.devtools.DevToolsException: {"id":6,"error":{"message":"Fetch.enable","data":"RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5\nUnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45\n"},"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"}
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:181)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:81)
	at org.openqa.selenium.devtools.idealized.Network.prepareToInterceptTraffic(Network.java:241)
	at org.openqa.selenium.devtools.idealized.Network.interceptTrafficWith(Network.java:148)
	at org.openqa.selenium.devtools.NetworkInterceptor.<init>(NetworkInterceptor.java:97)
	at selenium.Main.main(Main.java:42)
Caused by: org.openqa.selenium.WebDriverException: {"id":6,"error":{"message":"Fetch.enable","data":"RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5\nUnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45\n"},"sessionId":"3dbeeeb1-8215-4b27-8a61-03fb8f394cbe"}
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:260)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:57)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:224)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Process finished with exit code 1
```

### Operating System

Windows 10

### Selenium version

Java 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 113.0.2

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.33.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Wait, how does this work for IE driver, it doesn't implement those things? 😂 

If it is working for Chrome/Edge, but not for Firefox, then it is likely a geckodriver/marionette implementation issue. Mozilla is no longer working on supporting Chrome DevTools Protocol (what `NetworkInterceptor` is currently implemented with). They now support this feature with the new BiDi spec (https://wpt.fyi/results/webdriver/tests/bidi/network), but Selenium has not yet updated the class to work with the BiDi implementation.

So this is either a geckodriver bug/won't fix or a Selenium feature not yet implemented that we're tracking here - https://github.com/SeleniumHQ/selenium/issues/11768

**Comment by csvtuda** [comment]
> Wait, how does this work for IE driver, it doesn't implement those things? 😂

You're right, don't know what I was doing when "it worked" 🤔 

Thank you for the quick response, I will make sure to watch the linked issue and stick to Chromium browsers for now.
