### ISSUE TITLE
[🐛 Bug]: Why LocalFileDetector does not allows Folder?

### ISSUE THREAD

**Issue by shirokuma-ds** [SeleniumHQ/selenium#12311]
### What happened?

In my local automation run I am able to upload a whole folder containing files inside it to an input element that directory attribute true.

But when I run my automation on Selenium Grid aka Remote run, it was unable to find the Folder even though it was able to find the Files inside the Folder if I give the files path instead of the folder path.

So I debug the LocalFileDetector code and found out that the Folder is actually found by the getLocalFile function, but it was returning false because it checks toUpload.isFile(), and thus sendKeys function throws an error the Folder unable to be found.

What is the reason that it's not allowing Folder to be uploaded? Can we remove those toUpload.isFile() or can have something like LocalFolderDetector if it's Folder that we want to upload?

### How can we reproduce the issue?

```shell
Run an automation using RemoteWebDriver with LocalFileDetector set to true.
Make sure the there is an input element with attribute file and directory.
Try to upload a folder containing some files to that input element using sendKeys
```

### Relevant log output

```shell
org.openqa.selenium.InvalidArgumentException: invalid argument: File not found : /Users/ts-dennis.sandjaya/Documents/Projects/Automation Projects/some-automation-project/AutomationTestFilesFolder
  (Session info: chrome=114.0.5735.133)
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '19.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [b9679eaea7355f4652d7a2f75a4005c1, sendKeysToElement {id=8CCDE120DF691BF6BE0C1E4A9E052C63_element_45, value=[Ljava.lang.CharSequence;@28bbac99}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 114.0.5735.133, chrome: {chromedriverVersion: 114.0.5735.90 (386bc09e8f4f..., userDataDir: /tmp/.com.google.Chrome.VIDYXu}, goog:chromeOptions: {debuggerAddress: localhost:33349}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://10.48.15.203:5556/sess..., se:cdpVersion: 114.0.5735.133, se:forwardCdp: ws://172.17.0.3:4444/sessio..., se:vnc: ws://10.48.15.203:5556/sess..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on linux (b9679eaea7355f4652d7a2f75a4005c1)] -> xpath: //input[@type='file' and @directory='true']]
Session ID: b9679eaea7355f4652d7a2f75a4005c1

	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:113)
	at com.company.framework.WebElementLocator.sendKeys(WebElementLocator.kt:314)
	at com.company.qa.project.web.steps.cloud.MyDriveSteps.uploadFolder(MyDriveSteps.kt:108)
	at com.company.qa.project.web.features.cloud.UploadFilesFeature.verify upload folder functionality(UploadFilesFeature.kt:184)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

### Operating System

macOS 13.4.1 (22F82)

### Selenium version

4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 114

### Are you using Selenium Grid?

4.10.0

**Comment by titusfortner** [comment]
This is how w3c has specified it. You can send the list of files, but not the directory — https://w3c.github.io/webdriver/#:~:text=first%20matching%20condition%3A-,file%20is%20true,-Let%20files%20be

Changes to selenium behavior must be done there.

**Comment by shirokuma-ds** [comment]
Hi @titusfortner ,

Thanks for your reply. But my local automation run able to upload the directory using sendKeys, the test only failed when I am running it via RemoteWebDriver.
(Note: The element in the web page needs to have attribute directory true, otherwise it won't work)

Does not that means the sendKeys actually supports it as long as the element supports it?

**Comment by titusfortner** [comment]
I'm not sure what you mean. The specification allows uploading multiple files, using send keys method on an input element of "file" type, but does not allow uploading a directory using that method by only specifying the directory name. Any changes to this behavior needs to be requested from the w3c specification.
