### ISSUE TITLE
[🐛 Bug]: gitlab CI + docker == driver.version: unknown + stacktrace

### ISSUE THREAD

**Issue by FreifunkerEZ** [SeleniumHQ/selenium#12339]
### What happened?

Hellows!
I have this gitlab CI definition. It works.

But if I use `START_XVFB: "false"` as recommended here https://github.com/SeleniumHQ/docker-selenium#running-in-headless-mode the thing blows apart without a hint why. A nice error-message would be good.

### How can we reproduce the issue?

```shell
Use this gitlab-CI definition:

firefox_selenium_NG:
  tags:
    - docker
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/selenium/standalone-firefox
      alias: selenium.local
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.8
  variables:
#    START_XVFB: "false"
  script:
    - pip install selenium
    - python3 ./pwresetweb/tests/example/test_example.py
```
It loads a python image and adds selenium-firefox-standalone as a service. The python selenium-lib is installed and the test-script (below --v) is executed.

```
#!/usr/bin/env python3
import unittest
from selenium import webdriver


class ExampleTest(unittest.TestCase):
    def test_example_from_selenium_website(self):
        """simple test with google"""
        firefox_options = webdriver.FirefoxOptions()
        driver = webdriver.Remote(
            command_executor='http://selenium.local:4444',
            options=firefox_options
        )
        driver.get("http://www.google.com")
        driver.quit()


if __name__ == "__main__":
    unittest.main()
```
```


### Relevant log output

```shell
Output of the gitlab-CI. I replaced my company's name with "myCompany"


Running with gitlab-runner 16.1.0 (865283c5)
  on ci-runner2 vUG5mxWC, system ID: s_df3b394eae65
Resolving secrets 00:00
Preparing the "docker" executor 00:09
Using Docker executor with image gitlab.myCompany.de:443/myCompany-se/dependency_proxy/containers/python:3.8 ...
Starting service gitlab.myCompany.de/myCompany-se/dependency_proxy/containers/selenium/standalone-firefox:latest ...
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image gitlab.myCompany.de:443/myCompany-se/dependency_proxy/containers/selenium/standalone-firefox:latest ...
Using docker image sha256:0e81648fc732d9142fdb436d7a322dd06c2cd0e9766e735b42e4cbfd6d135739 for gitlab.myCompany.de:443/myCompany-se/dependency_proxy/containers/selenium/standalone-firefox:latest with digest selenium/standalone-firefox@sha256:b6d8279268b3183d0d33e667e82fec1824298902f77718764076de763673124f ...
Waiting for services to be up and running (timeout 30 seconds)...
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image gitlab.myCompany.de:443/myCompany-se/dependency_proxy/containers/python:3.8 ...
Using docker image sha256:db2bf59cb82fcb0b0f93d5ff9d52aad0b1b09d1ee9436946cd30922afdc2b98a for gitlab.myCompany.de:443/myCompany-se/dependency_proxy/containers/python:3.8 with digest gitlab.myCompany.de:443/myCompany-se/dependency_proxy/containers/python@sha256:c293ab0afb856e1f378bd676d43010154827f3e228ba859f66e5ffa6c850427e ...
Preparing environment 00:00
Running on runner-vug5mxwc-project-33362-concurrent-2 via ci-runner2...
Getting source from Git repository 00:02
Fetching changes...
Reinitialized existing Git repository in /builds/myCompany-se/pw-reset-service/.git/
Checking out c1c91d2c as detached HEAD (ref is 345-restart-ci-fix-from-scratch)...
Removing .cache/
Skipping Git submodules setup
Restoring cache 00:00
Checking cache for default-non_protected...
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted. 
Successfully extracted cache
Executing "step_script" stage of the job script 00:07
Using docker image sha256:db2bf59cb82fcb0b0f93d5ff9d52aad0b1b09d1ee9436946cd30922afdc2b98a for gitlab.myCompany.de:443/myCompany-se/dependency_proxy/containers/python:3.8 with digest gitlab.myCompany.de:443/myCompany-se/dependency_proxy/containers/python@sha256:c293ab0afb856e1f378bd676d43010154827f3e228ba859f66e5ffa6c850427e ...
$ pip install selenium
Collecting selenium
  Using cached selenium-4.10.0-py3-none-any.whl (6.7 MB)
Collecting certifi>=2021.10.8
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting trio-websocket~=0.9
  Using cached trio_websocket-0.10.3-py3-none-any.whl (17 kB)
Collecting urllib3[socks]<3,>=1.26
  Using cached urllib3-2.0.3-py3-none-any.whl (123 kB)
Collecting trio~=0.17
  Using cached trio-0.22.1-py3-none-any.whl (399 kB)
Collecting idna
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting sniffio
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting exceptiongroup>=1.0.0rc9
  Using cached exceptiongroup-1.1.2-py3-none-any.whl (14 kB)
Collecting attrs>=20.1.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting sortedcontainers
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting outcome
  Using cached outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Collecting wsproto>=0.14
  Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting h11<1,>=0.9.0
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Installing collected packages: sortedcontainers, urllib3, sniffio, pysocks, idna, h11, exceptiongroup, certifi, attrs, wsproto, outcome, trio, trio-websocket, selenium
Successfully installed attrs-23.1.0 certifi-2023.5.7 exceptiongroup-1.1.2 h11-0.14.0 idna-3.4 outcome-1.2.0 pysocks-1.7.1 selenium-4.10.0 sniffio-1.3.0 sortedcontainers-2.4.0 trio-0.22.1 trio-websocket-0.10.3 urllib3-2.0.3 wsproto-1.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
$ python3 ./pwresetweb/tests/example/test_example.py
E
======================================================================
ERROR: test_example_from_selenium_website (__main__.ExampleTest)
simple test with google
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./pwresetweb/tests/example/test_example.py", line 45, in test_example_from_selenium_website
    driver = webdriver.Remote(
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1 
Host info: host: '8f719680e43e', ip: '172.17.0.4'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-23-amd64', java.version: '11.0.19'
Driver info: driver.version: unknown
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-23-amd64', java.version: '11.0.19'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply (DriverServiceSessionFactory.java:210)
    at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply (DriverServiceSessionFactory.java:69)
    at org.openqa.selenium.grid.node.local.SessionSlot.apply (SessionSlot.java:147)
    at org.openqa.selenium.grid.node.local.LocalNode.newSession (LocalNode.java:467)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession (LocalDistributor.java:643)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession (LocalDistributor.java:560)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest (LocalDistributor.java:814)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1 (LocalDistributor.java:773)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
----------------------------------------------------------------------
Ran 1 test in 0.947s
FAILED (errors=1)
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

### Operating System

docker image selenium/standalone-firefox@sha256:b6d8279268b3183d0d33e667e82fec1824298902f77718764076de763673124f

### Selenium version

docker image python:3.8 == python@sha256:c293ab0afb856e1f378bd676d43010154827f3e228ba859f66e5ffa6c850427e running selenium-4.10.0 

### What are the browser(s) and version(s) where you see this issue?

your docker image

### What are the browser driver(s) and version(s) where you see this issue?

your docker image

### Are you using Selenium Grid?

standalone docker image

**Comment by titusfortner** [comment]
Sorry, it looks like we missed this one. @diemol or @pujagani can you triage this when you get a chance? Thanks.

**Comment by diemol** [comment]
It fails because your script is running a headed Firefox. If you want to do `START_XVFB: "false"` do disable XVFB, then you need to run Firefox headless.
