### ISSUE TITLE
[🐛 Bug]: Timeout when launching chrome session on Selenium 4.9.0+ for protractor tests

### ISSUE THREAD

**Issue by eecormier** [SeleniumHQ/selenium#12362]
### What happened?

When launching chrome after starting the selenium server in a docker container on selenium 4.9.0+ we are seeing the error "Could not start a new session. New session request timed out" which looks like it comes from this [line of code](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/sessionqueue/local/LocalNewSessionQueue.java#L213). The issue is with selenium, as we have tested with multiple recent versions of chrome and chromedriver on selenium 4.8.3 and the selenium server is working fine. It seems likely that this issue is related to https://github.com/SeleniumHQ/selenium/pull/11816.

### How can we reproduce the issue?

```shell
1. Set up the selenium docker container in this repo: `https://github.com/eecormier/selenium-bug/tree/main`
2. Run the example test in this repo: `https://github.com/eecormier/example-protractor-test/tree/main`
3. You should see the errors described above.
```

### Relevant log output

```shell
Here are the docker logs, note the status code 500 for the POST call at the bottom:
`2023-07-12 13:50:44,384 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2023-07-12 13:50:44,389 INFO RPC interface 'supervisor' initialized
2023-07-12 13:50:44,389 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-07-12 13:50:44,389 INFO supervisord started with pid 9
2023-07-12 13:50:45,392 INFO spawned: 'xvfb' with pid 11
2023-07-12 13:50:45,394 INFO spawned: 'selenium-standalone' with pid 12
2023-07-12 13:50:45,400 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds
2023-07-12 13:50:45,400 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds
13:50:45.836 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
13:50:45.843 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
13:50:46.726 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
13:50:46.734 INFO [NodeOptions.discoverDrivers] - Driver(s) already present on the host: 1
13:50:46.760 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","goog:chromeOptions": {"args": [ "--remote-allow-origins=*" ] } } 4 times (Host)
13:50:46.783 INFO [Node.<init>] - Binding additional locator mechanisms: relative
13:50:46.812 INFO [GridModel.setAvailability] - Switching Node 7a844858-9309-400d-87e1-e8bed32525b2 (uri: http://172.17.0.3:4444) from DOWN to UP
13:50:46.813 INFO [LocalDistributor.add] - Added node 7a844858-9309-400d-87e1-e8bed32525b2 at http://172.17.0.3:4444. Health check every 120s
13:50:46.953 INFO [Standalone.execute] - Started Selenium Standalone 4.9.0 (revision d7057100a6): http://172.17.0.3:4444
13:53:19.376 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "de2f6be9fa6c0db6c88de4e4fa617b98","eventTime": 1689184399372561083,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "selenium-server-castle-chrome-beta-test-suite:4444","http.method": "POST","http.request_content_length": "93","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession"}}`



Here are the logs from the test run output:
`[12:12:07] I/launcher - Running 1 instances of WebDriver
[12:12:07] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[12:17:08] E/launcher - Could not start a new session. New session request timed out 
Host info: host: '56414f86dc88', ip: '172.17.0.2'
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.18'
Driver info: driver.version: unknown
[12:17:08] E/launcher - SessionNotCreatedError: Could not start a new session. New session request timed out 
Host info: host: '56414f86dc88', ip: '172.17.0.2'
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.18'
Driver info: driver.version: unknown
    at Object.throwDecodedError (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:519:13)
    at /Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:626:16)
    at Hosted.getNewDriver (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/built/runner.js:195:43)
    at /Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at /Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/ecormier/.nvm/versions/node/v16.15.1/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[12:17:08] E/launcher - Process exited with error code 199`
```

### Operating System

Linux and mac

### Selenium version

4.9.0

### What are the browser(s) and version(s) where you see this issue?

Chrome, multiple versions

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver, multiple versions

**Comment by titusfortner** [comment]
Protractor is no longer actively developed and is not compatible with the w3c specification, which is required for Selenium4.
