### ISSUE TITLE
[🐛 Bug]: Firefox driver cannot handle http requests made by browser

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#12374]
### What happened?

I am using `driver.Manage().Network` to get an information about http requests made by browser. It works for `ChromeDriver`, but doesn't for `FirefoxDriver`.

### How can we reproduce the issue?

```shell
var driver = new FirefoxDriver();

// output http request url to console
driver.Manage().Network.NetworkRequestSent += (sender, e) =>
{
    Console.WriteLine(e.RequestUrl);
};

await driver.Manage().Network.StartMonitoring();

driver.Navigate().GoToUrl("https://www.google.com");

driver.Quit();
```

### Relevant log output

```shell
1689608831469   geckodriver     INFO    Listening on 127.0.0.1:59624
1689608835647   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-no-remote" "-profile" "C:\\Users\\nikol\\AppData\\Local\\Temp\\rust_mozprofiletLupNA"
Read port: 59630
Unhandled exception. OpenQA.Selenium.WebDriverException: Cannot find moz:debuggerAddress capability for driver
   at OpenQA.Selenium.Firefox.FirefoxDriver.GetDevToolsSession(Int32 devToolsProtocolVersion)
   at OpenQA.Selenium.Firefox.FirefoxDriver.GetDevToolsSession()
   at OpenQA.Selenium.NetworkManager.<>c__DisplayClass4_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at OpenQA.Selenium.NetworkManager.StartMonitoring()
   at Program.<Main>$(String[] args) in D:\Temp\ConsoleApp24\ConsoleApp24\Program.cs:line 11
   at Program.<Main>(String[] args)
```

### Operating System

Windows 11

### Selenium version

4.10

### What are the browser(s) and version(s) where you see this issue?

Firefox 115.0.2

### What are the browser driver(s) and version(s) where you see this issue?

Selenium Manager

**Comment by titusfortner** [comment]
For Firefox, you have to pass in: `webSocketURL: true` as an option to get the debuggerAddress
https://bugzilla.mozilla.org/show_bug.cgi?id=1669218

Selenium error should be better for this, probably, or not give access to that method if the capability hasn't been set. Not sure what it might look like in .NET code

**Comment by nvborisenko** [comment]
Update: I explicitly set enabling dev protocol for firefox.
```csharp
var ffOptions = new FirefoxOptions
{
EnableDevToolsProtocol = true
};

var driver = new FirefoxDriver(ffOptions);
```

But now getting different error:
```
1689610452447   geckodriver     INFO    Listening on 127.0.0.1:60123
1689610456623   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--remote-debugging-port" "60124" "--remote-allow-hosts" "localhost" "-no-remote" "-profile" "C:\\Users\\nikol\\AppData\\Local\\Temp\\rust_mozprofilekxlEWb"
Read port: 60129
Unhandled exception. OpenQA.Selenium.DevTools.CommandResponseException: Fetch.enable: Fetch.enable - RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5
UnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7
execute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13
receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45

   at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand(String commandName, JToken commandParameters, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
   at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand[TCommand,TCommandResponse](TCommand command, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
   at OpenQA.Selenium.DevTools.V85.Fetch.FetchAdapter.Enable(EnableCommandSettings command, CancellationToken cancellationToken, Nullable`1 millisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
   at OpenQA.Selenium.DevTools.V85.V85Network.EnableFetchForAllPatterns()
   at OpenQA.Selenium.NetworkManager.StartMonitoring()
   at Program.<Main>$(String[] args) in D:\Temp\ConsoleApp24\ConsoleApp24\Program.cs:line 16
   at Program.<Main>(String[] args)
```

**Comment by titusfortner** [comment]
I don't think Mozilla ever implemented `Fetch`. This is what I had recorded of their v85 support: https://gist.github.com/titusfortner/04ec6be591c014ad3f08e8b172d29251

They have this implemented in BiDi spec, but we're not sure when/how we are implementing that one, yet.
