### ISSUE TITLE
[🐛 Bug]: CLI sometimes not working with JDK 19+

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#12382]
### What happened?

Running the selenium-server-4.10.0.jar in standalone mode with arguments with JDK 19+ and the server will start or fail to start printing the usage instructions.

  `jdk19.0.2_7\bin\java -jar selenium-server-4.10.0.jar standalone --host 127.0.0.1`

Ignore the startup errors of the server, they are expected.

### How can we reproduce the issue?

```shell
Run command above several times.
```

### Relevant log output

```shell

C:\repository>C:\jdk19.0.2_7\bin\java -jar 1.2.0_selenium\selenium-server-4.10.0.jar standalone --host 127.0.0.1
Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
14:34:30.985 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
14:34:30.991 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:34:31.907 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
14:34:31.954 INFO [NodeOptions.discoverDrivers] - Driver(s) already present on the host: 0
14:34:31.962 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:162)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:216)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:47)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:261)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 12 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:500)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:224)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 17 more

C:\repository>C:\jdk19.0.2_7\bin\java -jar 1.2.0_selenium\selenium-server-4.10.0.jar standalone --host 127.0.0.1
Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
14:34:38.480 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
14:34:38.486 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:34:39.392 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
14:34:39.437 INFO [NodeOptions.discoverDrivers] - Driver(s) already present on the host: 0
14:34:39.447 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:162)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:216)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:47)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:261)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 12 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:500)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:224)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 17 more

C:\repository>C:\jdk19.0.2_7\bin\java -jar 1.2.0_selenium\selenium-server-4.10.0.jar standalone --host 127.0.0.1
Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
14:34:40.670 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
14:34:40.676 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:34:41.520 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
14:34:41.565 INFO [NodeOptions.discoverDrivers] - Driver(s) already present on the host: 0
14:34:41.572 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:162)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:216)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:47)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:261)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 12 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:500)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:224)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 17 more

C:\repository>C:\jdk19.0.2_7\bin\java -jar 1.2.0_selenium\selenium-server-4.10.0.jar standalone --host 127.0.0.1
Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
14:34:42.760 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
14:34:42.769 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:34:43.677 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
14:34:43.725 INFO [NodeOptions.discoverDrivers] - Driver(s) already present on the host: 0
14:34:43.735 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:162)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:216)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:47)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:261)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 12 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:500)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:224)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 17 more

C:\repository>C:\jdk19.0.2_7\bin\java -jar 1.2.0_selenium\selenium-server-4.10.0.jar standalone --host 127.0.0.1
Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
14:34:44.977 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
14:34:44.983 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:34:45.841 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
14:34:45.888 INFO [NodeOptions.discoverDrivers] - Driver(s) already present on the host: 0
14:34:45.896 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:162)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:216)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:47)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:261)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 12 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:500)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:224)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 17 more

C:\repository>C:\jdk19.0.2_7\bin\java -jar 1.2.0_selenium\selenium-server-4.10.0.jar standalone --host 127.0.0.1
Picked up JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
Was passed main parameter '--host' but no main parameter was defined in your arg class
Usage: standalone [options]
  Options:
    --config
      Config file to read from (may be specified more than once)
    --config-help
      Output detailed information about config options
      Default: false
    --service-configuration
      Configuration for the service where calls will be relayed to. It is
      recommended to provide this type of configuration through a toml config
      file to improve readability. Command line example:
      --service-configuration max-sessions=2 stereotype='{"browserName":
      "safari", "platformName": "iOS", "appium:platformVersion": "14.5"}}'
    --service-host
      Host name where the service that supports WebDriver commands is running
    --service-port
      Port where the service that supports WebDriver commands is running
    --service-status-endpoint
      Endpoint to query the WebDriver service status, an HTTP 200 response is
      expected
    --service-url
      URL for connecting to the service that supports WebDriver commands, like
      an Appium server or a cloud service.
    --version
      Displays the version and exits.
      Default: false


C:\repository>
```

### Operating System

Windows 10 x64

### Selenium version

Java 4.10.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

Standalone 4.10.0

**Comment by joerg1985** [comment]
After looking into this very short, i would say the reflective access from jcommander is not possible due to missing `opens` statements in the module-info of the server jar.

**Comment by joerg1985** [comment]
With JDK 20 you get the usage instructions much more often, might be easier to debug there.

**Comment by joerg1985** [comment]
Okay, this is the root issue, we are createing a parallel stream: 
https://github.com/SeleniumHQ/selenium/blob/12f387210fb3c3aa5fb02139a1570750a4798b2f/java/src/org/openqa/selenium/grid/TemplateGridCommand.java#L55

And add it to a LinkedHashSet which is not thread safe, this will result in chaos
https://github.com/SeleniumHQ/selenium/blob/12f387210fb3c3aa5fb02139a1570750a4798b2f/java/src/org/openqa/selenium/grid/TemplateGridCommand.java#L57

I have seen this in other areas of the code too, LinkedHashSets and LinkedHashMaps are not thread-safe.
