### ISSUE TITLE
[🐛 Bug]: UnreachableBrowserException with Selenium 4.10.0, Chrome 114, ChromeDriver 114

### ISSUE THREAD

**Issue by david-jng** [SeleniumHQ/selenium#12393]
### What happened?

While trying to clear a WebElement (input field) or read the text of an WebElement (heading), I receive the following error: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
This error does not occur if I send keys.

**Works:**
WebElement we = driver.findElement(By.xpath("my-input-field"));
we.sendKeys("This is working!");

**Works not:**
WebElement we = driver.findElement(By.xpath("my-input-field"));
we.clear() --> error in this line

WebElement we = driver.findElement(By.xpath("my-heading"));
we.getText() --> error in this line

I am using Java 11, Chrome 114 and ChromeDriver 114.

### How can we reproduce the issue?

```shell
String webdriverPath = "<path-to-chromedriver-114>";

System.setProperty("webdriver.chrome.driver", webdriverPath); 
ChromeOptions chromeOptions = new ChromeOptions();

chromeOptions.addArguments("--window-size=1920,1080");
chromeOptions.addArguments("--ignore-certificate-errors");

ChromeDriver driver = new ChromeDriver(chromeOptions);

driver.get("chrome://about");
System.out.println(driver.findElement(By.xpath("(//h2)[1]")).getText());
```

### Relevant log output

```shell
[java] org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
     [java] Build info: version: '4.10.0', revision: 'c14d967899'
     [java] System info: os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '11'
     [java] Driver info: org.openqa.selenium.chrome.ChromeDriver
     [java] Command: [f67058abf3a3ee984d3372052aedf824, getElementText {id=712DA98C7024FBA612FA53C5931F2C88_element_2}]
     [java] Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 114.0.5735.199, chrome: {chromedriverVersion: 114.0.5735.90 (386bc09e8f4f..., userDataDir: C:\Users\infodba\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:57604}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57604/devtoo..., se:cdpVersion: 114.0.5735.199, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
     [java] Element: [[ChromeDriver: chrome on windows (f67058abf3a3ee984d3372052aedf824)] -> xpath: (//h2)[1]]
     [java] Session ID: f67058abf3a3ee984d3372052aedf824
     [java]     at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
     [java]     at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:242)
     [java]     at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:192)
     [java]     at net.atos.plm.t4tc.plugin.webui.methods.OpenBrowserMethod.executeTest(Unknown Source)
     [java]     at net.atos.plm.t4tc.plugin.webui.methods.OpenBrowserMethod.executeTest(Unknown Source)
     [java]     at net.atos.plm.t4tc.plugin.webui.model.WebUiMethod.execute(Unknown Source)
     [java]     at net.atos.plm.t4tc.framework.MethodHandler.execute(Unknown Source)
     [java]     at net.atos.plm.t4tc.framework.execution.Control.runMethodOrMacro(Unknown Source)
     [java]     at net.atos.plm.t4tc.framework.execution.Control.runTest(Unknown Source)
     [java]     at net.atos.plm.t4tc.framework.execution.JUnitRunner.test(Unknown Source)
     [java]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [java]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
     [java]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [java]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
     [java]     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [java]     at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
     [java]     at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
     [java]     at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
     [java]     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
     [java]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
     [java]     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
     [java]     at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
     [java]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
     [java]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
     [java]     at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
     [java]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
     [java]     Error (Failure): org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.Build info: version: '4.10.0', revision: 'c14d967899'System info: os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '11'Driver info: org.openqa.selenium.chrome.ChromeDriverCommand: [f67058abf3a3ee984d3372052aedf824, getElementText {id=712DA98C7024FBA612FA53C5931F2C88_element_2}]Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 114.0.5735.199, chrome: {chromedriverVersion: 114.0.5735.90 (386bc09e8f4f..., userDataDir: C:\Users\infodba\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:57604}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57604/devtoo..., se:cdpVersion: 114.0.5735.199, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}Element: [[ChromeDriver: chrome on windows (f67058abf3a3ee984d3372052aedf824)] -> xpath: (//h2)[1]]Session ID: f67058abf3a3ee984d3372052aedf824
     [java]     at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
     [java]     at org.junit.runners.Suite.runChild(Suite.java:128)
     [java]     at org.junit.runners.Suite.runChild(Suite.java:27)
     [java]     at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
     [java]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
     [java]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
     [java]     at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
     [java]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
     [java]     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [java]     at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [java]     at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
     [java]     at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
     [java]     at org.junit.runners.Suite.runChild(Suite.java:128)
     [java]     at org.junit.runners.Suite.runChild(Suite.java:27)
     [java]     at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
     [java]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
     [java]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
     [java]     at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
     [java]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
     [java]     at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
     [java]     at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
     [java]     at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
     [java]     at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
     [java]     at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
     [java]     at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
     [java]     at net.atos.plm.t4tc.editor.application.presenter.dialogs.runner.RunnerThread.run(Unknown Source)
     [java] Caused by: java.io.UncheckedIOException: java.io.IOException: An existing connection was forcibly closed by the remote host
     [java]     at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
     [java]     at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
     [java]     at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
     [java]     at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
     [java]     at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
     [java]     at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
     [java]     at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:97)
     [java]     at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:188)
     [java]     at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
     [java]     at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
     [java]     at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
     [java]     ... 54 more
     [java] Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
     [java]     at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
     [java]     at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
     [java]     at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
     [java]     at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
     [java]     at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
     [java]     at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
     [java]     at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256)
     [java]     at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
     [java]     at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
     [java]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
     [java]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
     [java]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
     [java]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
     [java]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
     [java]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
     [java]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
     [java]     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
     [java]     at java.base/java.lang.Thread.run(Thread.java:834)
     [java]
```

### Operating System

Windows Server 2016

### Selenium version

Java 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
I don't understand. The code to reproduce the issue is not the same you are saying works/not work above. Can you share the code we can use to reproduce the issue?

**Comment by david-jng** [comment]
> I don't understand. The code to reproduce the issue is not the same you are saying works/not work above. Can you share the code we can use to reproduce the issue?

In my reproduceable code, you will find the following line at the end:

`System.out.println(driver.findElement(By.xpath("(//h2)[1]")).getText());`

This will reproduce the same error as the code in my initial post:

```
WebElement we = driver.findElement(By.xpath("(//h2)[1]"));
we.getText() --> error in this line
```

**Comment by david-jng** [comment]
Note: Just tested the same code with Chrome 109, ChromeDriver 109 and Selenium 4.10.0. Everything is working fine.

**Comment by diemol** [comment]
That was going to be my next question, what happens in previous Chrome version or different browsers. Therefore, it seems to be an issue in Chrome.
