### ISSUE TITLE
having 502 within docker error even though proxy has been passed

### ISSUE THREAD

**Issue by b-guerra** [SeleniumHQ/selenium#12412]
### What happened?

I  am having some serious issues trying to run selenium within a docker build.
I am currently hosting my application within Amazon ECS and building the docker using the following build command:

`docker build --progress=plain --build-arg http_proxy=MY_PROXY --build-arg https_proxy=MY_PROXY -f Dockerfile .
`

And everything executes fine until the selenium piece. It is giving me an error that comes back as a proxy error, you can see it below:

What makes me think it is not a proxy issue per se, is the fact that when trying to get the page HTML thru the requests package, it works fine.

You can see my selenium_test.py in the code snipped session.
Honestly I have no idea of what is going on. If anyone could give me any light I would REALLY appreciate, thank you very much.

I am using --proxy-server option to handle the proxy connection, my Docker has also the proxies working... I tried using ChromeService to download the driver case it was the issue... It downloads the driver but generates same error when opening it... I tried everything you can imagine, as I showed above.. nothing works...

What makes me think it is a problem with selenium per se is the fact that when I try to get something from the webpage using requests.get, it works fine, example below:

```
proxies = {
    'http': "MY_PROXY",
    'https': "MY_PROXY",
}

from bs4 import BeautifulSoup
import requests
url = "https://www.sec.gov/"

soup =  BeautifulSoup(requests.get(url, proxies=proxies, timeout=30).text, 'html.parser')
print(soup)
```

I am sorry if this post should not be here, I really feeling without any other place to go, I really appreciate any help.

Thanks.

### How can we reproduce the issue?

```shell
import logging
from selenium import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--headless=new')
chrome_options.add_argument("--ignore-certificate-errors")
chrome_options.add_argument("--disable-notifications")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument('--single-process')
chrome_options.add_argument('--no-zygote')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--remote-debugging-port=9222')
chrome_options.add_argument('--proxy-server=MY_PROXY')


driver = webdriver.Chrome(
    options=chrome_options
)

driver.get("https://www.sec.gov/")
print(driver.title)

```
```


### Relevant log output

```shell
#17 [13/13] RUN python3.9 selenium_test.py
#17 sha256:fb81a1e7dd19fac7fcde47181c89ebce42b3772d317ca54cee6c660416c6f02f
#17 2.000 Traceback (most recent call last):
#17 2.000   File "/ricky/selenium_test.py", line 33, in <module>
#17 2.001     driver = webdriver.Chrome(
#17 2.001   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
#17 2.001     super().__init__(
#17 2.001   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
#17 2.001     super().__init__(
#17 2.001   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
#17 2.001     self.start_session(capabilities)
#17 2.001   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
#17 2.001     response = self.execute(Command.NEW_SESSION, caps)["value"]
#17 2.001   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
#17 2.001     self.error_handler.check_response(response)
#17 2.001   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 209, in check_response
#17 2.002     raise exception_class(value)
#17 2.002 selenium.common.exceptions.WebDriverException: Message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
#17 2.002 <html>
#17 2.002 <!-- FileName: index.html
#17 2.002      Language: [en]
#17 2.002 -->
#17 2.002 <!--Head-->
#17 2.002 <head>
#17 2.002   <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
#17 2.002   <meta http-equiv="X-UA-Compatible" content="IE=7" />
#17 2.002   <title>McAfee Web Gateway - Notification</title>
#17 2.002   <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
#17 2.002   <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" />
#17 2.002 </head>
#17 2.002 <!--/Head-->
#17 2.002 <!--Body-->
#17 2.002 <body onload="swOnLoad();">
#17 2.002   <table class='bodyTable'>
#17 2.002     <tr>
#17 2.002       <td class='bodyData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif'>
#17 2.002 <!--Logo-->
#17 2.002 <table class='logoTable'>
#17 2.002   <tr>
#17 2.002     <td class='logoData'>
#17 2.002       <a href='http://www.mcafee.com'>
#17 2.002         <img src='/mwg-internal/de5fs23hu73ds/files/default/img/logo_mwg.png'></a>
#17 2.002     </td>
#17 2.002   </tr>
#17 2.002 </table>
#17 2.002 <!--/Logo-->
#17 2.002 <!--Contents-->
#17 2.002 <!-- FileName: cannotconnect.html
#17 2.002      Language: [en]
#17 2.002 -->
#17 2.002 <!--Title-->
#17 2.002 <table class='titleTable' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
#17 2.002   <tr>
#17 2.002     <td class='titleData'>
#17 2.002       Cannot Connect
#17 2.002     </td>
#17 2.002   </tr>
#17 2.002 </table>
#17 2.002 <!--/Title-->
#17 2.002
#17 2.002 <!--Content-->
#17 2.002 <table class="contentTable">
#17 2.002   <tr>
#17 2.002     <td class="contentData">
#17 2.002       The proxy could not connect to the destination in time.
#17 2.002     </td>
#17 2.002   </tr>
#17 2.002 </table>
#17 2.002 <!--/Content-->
#17 2.002
#17 2.002 <!--Info-->
#17 2.002 <table class="infoTable">
#17 2.002   <tr>
#17 2.002     <td class="infoData">
#17 2.002       <b>URL: </b><script type="text/javascript">break_line("http://localhost:46523/session");</script><br />
#17 2.002       <p class="proxyErrorData">Failure Description: :cannotconnect:server state 1:state 9:Application response 502 cannotconnect</p>
#17 2.002     </td>
#17 2.002   </tr>
#17 2.002 </table>
#17 2.002 <!--/Info-->
#17 2.002
#17 2.002 <!--/Contents-->
#17 2.002 <!--Policy-->
#17 2.002 <table class='policyTable'>
#17 2.002   <tr>
#17 2.002     <td class='policyHeading'>
#17 2.002       <hr>
#17 2.002       Company Acceptable Use Policy
#17 2.002     </td>
#17 2.002   </tr>
#17 2.002   <tr>
#17 2.002     <td class='policyData'>
#17 2.002       This is an optional acceptable use disclaimer that appears on every page. You may change the wording or remove this section entirely in index.html.
#17 2.002     </td>
#17 2.002   </tr>
#17 2.002 </table>
#17 2.002 <!--/Policy-->
#17 2.002 <!--Foot-->
#17 2.002 <table class='footTable'>
#17 2.002   <tr>
#17 2.002     <td class='helpDeskData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
#17 2.002       For assistance, please contact your system administrator.
#17 2.002     </td>
#17 2.002   </tr>
#17 2.002   <tr>
#17 2.002     <td class='footData'>
#17 2.002       generated <span id="time">2023-07-25 01:17:27</span> by McAfee Web Gateway
#17 2.002       <br />
#17 2.002       selenium/4.10.0 (python linux)
#17 2.002     </td>
#17 2.002   </tr>
#17 2.002 </table>
#17 2.002 <!--/Foot-->
#17 2.002       </td>
#17 2.002     </tr>
#17 2.002   </table>
#17 2.002 </body>
#17 2.002 <!--/Body-->
#17 2.002 </html>
#17 2.002
#17 ERROR: executor failed running [/bin/sh -c python3.9 selenium_test.py]: exit code: 1
```
```


### Operating System

public.ecr.aws/docker/library/ubuntu:latest

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment]
You need to set the proxy when starting the container, not only when building it.

**Comment by b-guerra** [comment]
> You need to set the proxy when starting the container, not only when building it.

I actually am... Below you'll find the first couple lines of my Dockerfile

```
FROM public.ecr.aws/docker/library/ubuntu:latest
ENV DEBIAN_FRONTEND noninteractive
ENV http_proxy "MY PROXY"
ENV https_proxy "MY PROXY"
```

The proxy, as I mentioned in the problem statement, is working fine.. I am being able to connect to any website using requests.get, I even pasted a snipped above, I really don't believe the proxy is being the issue :(

**Comment by diemol** [comment]
Yes, but when you do `docker run...` you also need to set the proxy as an env var

**Comment by b-guerra** [comment]
I am not even at the step of a docker run yet, this problem is happening inside the docker build command.

**Comment by diemol** [comment]
OK, I thought you were using our images. You can check our dockerfiles and probably pick what you need to build your script. https://github.com/SeleniumHQ/docker-selenium

Aside of that, it would be better to ask in a different forum.
