### ISSUE TITLE
[🐛 Bug]:  Unable to obtain driver using Selenium Manager

### ISSUE THREAD

**Issue by SiddharthJ09** [SeleniumHQ/selenium#12414]
### What happened?

C:\Users\<username>\AppData\Local\Temp\selenium-manager4780040182003919112691930970461\selenium-manager.exe

Script is unable to obtain driver. Though the selenium-manager.exe is available on above path. Below highlight error is shown.
I ran maven clean command, updated the project with latest jar but still didnt work.

Jul 25, 2023 6:06:04 PM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: **Unable to obtain driver using Selenium Manager: Error running command: [C:\Users\<username>\AppData\Local\Temp\selenium-manager4780040182003919112691930970461\selenium-manager.exe**, --driver, chromedriver]
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_361'
Driver info: driver.version: ChromeDriver
      [31mjava.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:148)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:39)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:233)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:450)
	at org.openqa.selenium.chrome.ChromeDriverService.createServiceWithConfig(ChromeDriverService.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:70)
	at scm.utils.BrowserUtils.launch_browser(BrowserUtils.java:48)
	at scm.stepdefinitions.StepHooks.setup(StepHooks.java:24)

### How can we reproduce the issue?

```shell
This is uncertain error which is working fine on other machine.
```

### Relevant log output

```shell
Jul 25, 2023 6:06:04 PM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: **Unable to obtain driver using Selenium Manager: Error running command: [C:\Users\<username>\AppData\Local\Temp\selenium-manager4780040182003919112691930970461\selenium-manager.exe**, --driver, chromedriver]
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_361'
Driver info: driver.version: ChromeDriver
      [31mjava.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:148)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:39)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:233)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:450)
	at org.openqa.selenium.chrome.ChromeDriverService.createServiceWithConfig(ChromeDriverService.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:70)
	at scm.utils.BrowserUtils.launch_browser(BrowserUtils.java:48)
	at scm.stepdefinitions.StepHooks.setup(StepHooks.java:24)
```

### Operating System

windows 10

### Selenium version

4.6

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 115.0.5790.102 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Version 115.0.5790.102 (Official Build) (64-bit)

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Let us know how it goes after upgrading to 4.10.0

**Comment by titusfortner** [comment]
It is not expected to work in 4.6.

What is working in 4.10 is that Selenium sees chrome v115, can't get chromedriver 115, and gets 114 instead.
Which is good because the current chromedriver 115 can't find the standard installed Chrome 115 due to a bug.

All of this gets fixed in 4.11, so I'm closing this.

**Comment by SiddharthJ09** [comment]
Thank you for the update. When are we expecting release of 4.11?
And what should be solution for existing issue?

**Comment by titusfortner** [comment]
Update to 4.10 and it will work, but will give a warning. 4.11 will be out as soon as we can finish it.
