### ISSUE TITLE
Error when running selenium webdriver with phantomjs - Permission Issue

### ISSUE THREAD

**Issue by ridwanguidanz** [SeleniumHQ/selenium#1244]
When running Selenium webdriver javascript version 2.42.1 with phantom browser version 1.9.17. We get the following error

/xxx/xxxxx/xxx/xxxx/node_modules/selenium-webdriver/lib/webdriver/promise.js:1643
throw error;
^
Error: Timed out waiting for the WebDriver server at http://xxx.xx.xxx.xxx:56763/
at Error (native)
at onResponse (/usr/local/src/xxxxxxxxx/node_modules/selenium-webdriver/http/util.js:87:66)
at /usr/local/src/xxxxxxxxx/node_modules/selenium-webdriver/http/util.js:42:21
at /usr/local/src/xxxxxxxxx/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
at ClientRequest.<anonymous> (/usr/local/src/xxxxxxxxx/node_modules/selenium-webdriver/http/index.js:136:7)
at ClientRequest.emit (events.js:107:17)
at Socket.socketErrorListener (_http_client.js:271:9)
at Socket.emit (events.js:107:17)
at net.js:459:14
at process._tickDomainCallback (node.js:381:11)
==== async task ====
WebDriver.createSession()
at Function.webdriver.WebDriver.acquireSession_ (/usr/local/src/xxxxxxxxx/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:49)
at Function.webdriver.WebDriver.createSession (/usr/local/src/xxxxxxxxx/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:111:30)
at Object.createDriver (/usr/local/src/xxxxxxxxx/node_modules/selenium-webdriver/phantomjs.js:152:36)
at createNativeDriver (/usr/local/src/xxxxxxxxx/node_modules/selenium-webdriver/builder.js:43:24)
at Builder.build (/usr/local/src/xxxxxxxxx/node_modules/selenium-webdriver/builder.js:96:18)
at Object.module.exports.loadDriver (eval at <anonymous> (/usr/local/src/xxxxxxxxx/xxx/xxx/xxx.js:1:395), <anonymous>:1:2214)
at Object.module.exports.insertDataToExcel (eval at <anonymous> (/usr/local/xxx/xxxxxxxxx/xxx/xxx/xxx.js:1:395), <anonymous>:1:6459)
at eval (eval at <anonymous> (/usr/local/xxx/xxxxxxxxx/xxx/xxx.js:1:485), <anonymous>:1:51991)
at eval (eval at k (eval at <anonymous> (/usr/local/src/xxxxxxxxx/xxx/xxx/xxxx.js:1:485)), <anonymous>:41:414)
at respond (/usr/local/src/xxxxxxxxx/node_modules/elasticsearch/src/lib/transport.js:253:9)
at checkRespForFailure (/usr/local/src/xxxxxxxxx/node_modules/elasticsearch/src/lib/transport.js:200:7)
at HttpConnector.<anonymous> (/usr/local/src/xxxxxxxxx/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
at IncomingMessage.wrapper (/usr/local/src/xxxxxxxxx/node_modules/elasticsearch/node_modules/lodash/index.js:3111:19)
at IncomingMessage.emit (events.js:129:20)
at _stream_readable.js:908:16

When we give the full permission it is working fine. Is it possible to get the same without full permission

**Comment by jleyba** [comment]
That version of selenium-webdriver is really old, please upgrade.

Feel free to reopen if this reproduces for you with 2.48.x.  Although, to be honest, I'm considering dropping phantomjs support since that project's WebDriver implementation is currently unmaintained (see notice on https://github.com/detro/ghostdriver).

**Comment by ridwanguidanz** [comment]
when I used 2.48 I got this [issue] (http://stackoverflow.com/questions/33433914/error-using-selenium-js-chrome-webdriver)

    undefined:1178
    vlog(2, () => this + ' scheduling notifications', this);
             ^
    SyntaxError: Unexpected token )

when I tried with 2.47 the issue again exist.

    /home/ubuntu/git/xxxxxx_dev/xxxxxx/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
      goog.global.setTimeout(function() { throw exception; }, 0);
                                                ^
    Error: Timed out waiting for the WebDriver server at http://xx.xxx.xxx.xxx:33989/
        at Error (native)
        at onResponse (/home/ubuntu/git/xxxxx_dev/xxxxx/node_modules/selenium-we

**Comment by maxvipon** [comment]
@ridwanguidanz it happens cause selenium [runs phantomjs with `--webdriver-logfile`](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/phantomjs.js#L143) which requires write access. And there is no option to override this behavior.

**Comment by maxvipon** [comment]
@jleyba :+1:
