### ISSUE TITLE
[🐛 Bug]: Unable to obtain browser driver

### ISSUE THREAD

**Issue by Pauan** [SeleniumHQ/selenium#12456]
### What happened?

I followed the directions to [install `selenium-webdriver` through npm](https://www.selenium.dev/documentation/webdriver/getting_started/install_library/).

Then I copy-pasted the [JavaScript code on the "Write your first Selenium script" page](https://www.selenium.dev/documentation/webdriver/getting_started/first_script/#putting-everything-together).

However, when I tried to run that code, I got an "Unable to obtain browser driver" error. The [relevant page](https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/#use-the-latest-version-of-selenium) said to file a bug report.

### How can we reproduce the issue?

```shell
Here is a Gist that contains the code:

https://gist.github.com/Pauan/d22b69c5e6fad00a1806ce1d9cafe7f0
```

### Relevant log output

```shell
[INFO] Searching for WebDriver executables installed on the current system...
/tmp/selenium/node_modules/selenium-webdriver/common/driverFinder.js:35
    throw Error(
    ^

Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. TypeError: options.getBrowserName is not a function
    at getPath (/tmp/selenium/node_modules/selenium-webdriver/common/driverFinder.js:35:11)
    at getAvailableBrowsers (/tmp/selenium/node_modules/selenium-webdriver/testing/index.js:121:6)
    at init (/tmp/selenium/node_modules/selenium-webdriver/testing/index.js:225:59)
    at suite (/tmp/selenium/node_modules/selenium-webdriver/testing/index.js:375:5)
    at Object.<anonymous> (/tmp/selenium/test.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

Node.js v18.16.0
```

### Operating System

NixOS Unstable 64-bit

### Selenium version

npm 4.11.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by titusfortner** [comment]
I'm seeing this in our documentation repo as well. https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/5719915294/job/15498812127

**Comment by diemol** [comment]
This was fixed in 4.11.1 thanks to @harsha509!
https://www.npmjs.com/package/selenium-webdriver/v/4.11.1

**Comment by Pauan** [comment]
@diemol Thanks, I can confirm that the error is fixed. But now there is a new error:

```
[INFO] Searching for WebDriver executables installed on the current system...
Selenium Manager binary found at /tmp/selenium/node_modules/selenium-webdriver/bin/linux/selenium-manager
Driver path: /home/pauan/.cache/selenium/chromedriver/linux64/115.0.5790.102/chromedriver
Browser path: /home/pauan/.cache/selenium/chrome/linux64/115.0.5790.102/chrome
The version of edge cannot be detected. Trying with latest driver version
Driver path: /home/pauan/.cache/selenium/msedgedriver/linux64/115.0.1901.188/msedgedriver
The version of firefox cannot be detected. Trying with latest driver version
Driver path: /home/pauan/.cache/selenium/geckodriver/linux64/0.33.0/geckodriver
Driver path: /home/pauan/.cache/selenium/IEDriverServer/win32/4.11.0/IEDriverServer.exe
The version of safari cannot be detected. Trying with latest driver version
/tmp/selenium/node_modules/selenium-webdriver/common/driverFinder.js:35
    throw Error(
    ^

Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /tmp/selenium/node_modules/selenium-webdriver/bin/linux/selenium-manager with --browser,safari,--output,json: safaridriver not available for download
    at getPath (/tmp/selenium/node_modules/selenium-webdriver/common/driverFinder.js:35:11)
    at getAvailableBrowsers (/tmp/selenium/node_modules/selenium-webdriver/testing/index.js:125:6)
    at init (/tmp/selenium/node_modules/selenium-webdriver/testing/index.js:225:59)
    at suite (/tmp/selenium/node_modules/selenium-webdriver/testing/index.js:375:5)
    at Object.<anonymous> (/tmp/selenium/test.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

I am not using iOS, so it shouldn't even be trying to download the Safari WebDriver.

And it should fail gracefully: if it cannot download the driver, it should just ignore the error and continue.

It's also trying to download some `.exe` files even though I'm on Linux, so that's odd.

**Comment by diemol** [comment]
Will have a look.

**Comment by gentlekenny** [comment]
Is the fix coming soon?
I'm having the same issue, with exact same steps as @Pauan, on my M2 Sillicon
I tried safari, mozzila, chrome..same issue

**Comment by titusfortner** [comment]
that's the goal. It takes a lot of work to do a release, though

**Comment by SattyaP** [comment]
Anyone find a solution? I got the error when running the results of my build electron which contains a script to run the selenium when pressing the start button

**Comment by titusfortner** [comment]
@SattyaP You have to wait for the next release.

**Comment by SattyaP** [comment]
> @SattyaP You have to wait for the next release.

Ok thanks

**Comment by corcoranp** [comment]
@SattyaP 

You can disable Safari by commenting out line 125 in the `\node_modules\selenium-webdriver\testing\index.js` file of your selenium install 

`//[getPath(new safari.Options()).driverPath, Browser.SAFARI],`

This will allow the process to continue with the exception below: 

> Error: Unable to obtain browser driver.
>         For more information on how to install drivers see

**Comment by SattyaP** [comment]
> @SattyaP
> 
> You can disable Safari by commenting out line 125 in the `\node_modules\selenium-webdriver\testing\index.js` file of your selenium install
> 
> `//[getPath(new safari.Options()).driverPath, Browser.SAFARI],`
> 
> This will allow the process to continue with the exception below:
> 
> > Error: Unable to obtain browser driver.
> > For more information on how to install drivers see

Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for E:\Documents\test-spoof\dist\win-unpacked\resources\app.asar\node_modules\selenium-webdriver\bin\windows\selenium-manager.exe with --browser,chrome,--output,json: TypeError: Cannot read properties of null (reading 'toString')
    at getPath (E:\Documents\test-spoof\dist\win-unpacked\resources\app.asar\node_modules\selenium-webdriver\common\driverFinder.js:35:11)
    at thenableWebDriverProxy.createSession (E:\Documents\test-spoof\dist\win-unpacked\resources\app.asar\node_modules\selenium-webdriver\chromium.js:692:43)
    at thenableWebDriverProxy.createSession (E:\Documents\test-spoof\dist\win-unpacked\resources\app.asar\node_modules\selenium-webdriver\chrome.js:224:13)
    at createDriver (E:\Documents\test-spoof\dist\win-unpacked\resources\app.asar\node_modules\selenium-webdriver\index.js:152:33)
    at Builder.build (E:\Documents\test-spoof\dist\win-unpacked\resources\app.asar\node_modules\selenium-webdriver\index.js:680:16)
    at test (E:\Documents\test-spoof\dist\win-unpacked\resources\app.asar\test.js:15:14)
    at IpcMainImpl.<anonymous> (E:\Documents\test-spoof\dist\win-unpacked\resources\app.asar\index.js:80:9)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88498)
    at WebContents.emit (node:events:513:28)
    
    
    look same, this error appears when after packaging the electron app which has a ui button to start the function selenium

**Comment by titusfortner** [comment]
4.12 is out. The issue should be resolved.
