### ISSUE TITLE
[🐛 Bug]: Unable to launch URL with chrome (with CFT - Chrome Browser for Automated Testing) with 4.11 version

### ISSUE THREAD

**Issue by naveenanimation20** [SeleniumHQ/selenium#12457]
### What happened?

I have upgraded to selenium version to 4.11, It's downloading the respective Chrome (CFT) Beta version in my .cache folder.
When I try to launch the browser, its launching the browser but while entering the URL, its giving exception:

Note: same issue with stable , Beta, Dev, Canary.

### How can we reproduce the issue?

```shell
using the follwoing code:
public class BrowserLaunch {

	public static void main(String[] args) {
		
		ChromeOptions co = new ChromeOptions();
		co.setBrowserVersion("beta");
		
		String browserPath = SeleniumManager.getInstance().getDriverPath(co, false).getBrowserPath();
		String driverPath = SeleniumManager.getInstance().getDriverPath(co, false).driverPath;
		System.out.println(browserPath);
		System.out.println(driverPath);

		WebDriver driver = new ChromeDriver(co);
		driver.get("https://www.google.com");
		System.out.println(driver.getTitle());
		
	}

}
```

### Relevant log output

```shell
/Users/naveenautomationlabs/.cache/selenium/chrome/mac-x64/116.0.5845.49/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
/Users/naveenautomationlabs/.cache/selenium/chromedriver/mac-x64/116.0.5845.49/chromedriver
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalArgumentException: http://:-1/json/version could not be parsed into a proper Uri, missing host
	at org.asynchttpclient.uri.Uri.create(Uri.java:73)
	at org.asynchttpclient.uri.Uri.create(Uri.java:62)
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:147)
	at org.asynchttpclient.Dsl.request(Dsl.java:73)
	at org.openqa.selenium.remote.http.netty.NettyMessages.toNettyRequest(NettyMessages.java:57)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:55)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:96)
	at org.openqa.selenium.devtools.CdpEndpointFinder.getCdpEndPoint(CdpEndpointFinder.java:58)
	at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$3(ChromiumDriver.java:144)
	at java.util.Optional.flatMap(Optional.java:241)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at demo.BrowserLaunch.main(BrowserLaunch.java:20)
```

### Operating System

MAC OS

### Selenium version

Java 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 115, 116, 117

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 115, 116, 117

**Comment by titusfortner** [comment]
I'm pretty sure this is a Google bug and needs to be reported to https://github.com/GoogleChromeLabs/chrome-for-testing/issues

@bonigarcia saw this for Dev & Canary, but we didn't see it for stable or beta. If you are seeing this for stable, please turn on logging and run with stable so we can see what is getting sent to the driver - https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by sanoj-s** [comment]
Able to start the chrome driver session and also able to launch the application ONLY when we use the WebDriverManager as below:
		WebDriverManager.chromedriver().setup();
		WebDriver driver = new ChromeDriver();
		driver.get("https://www.google.com/");

I am also expecting it should work with SeleniumManager, without using the third-party dependency WebDriverManager.

**Comment by diemol** [comment]
This is an issue with Chrome Beta, inside ChromeOptions, the value `debuggerAddress -> :-1`, when it should be something like `debuggerAddress -> localhost:64533`.

**Comment by diemol** [comment]
I reported this to the Google folks https://bugs.chromium.org/p/chromedriver/issues/detail?id=4533.

There is little we can do about the Beta version for now. Let's close this and wait for their response.

**Comment by soumyajit0905** [comment]
@diemol thank you so much.
I also saw the issue in Canary.
![image](https://github.com/SeleniumHQ/selenium/assets/32562194/efc778ee-a7fb-4ce2-9315-3d23929f9825)
cc @bonigarcia  @naveenanimation20

**Comment by naveenanimation20** [comment]
any updates on this issue? Now its working fine with current chrome browser version (116) but same issue with dev, beta and canary versions.

**Comment by diemol** [comment]
Have you checked the ChromeDriver bug report for updates?

**Comment by SanghamitraBhowmick1993** [comment]
Is there a solution or workaround available for this issue? The URI missing error persists even with Chrome Browser version 118, and upgrading the Selenium version does not appear to resolve the problem.

**Comment by titusfortner** [comment]
Google fixed the reported issue above. You can open a new issue and provide code and logs, but most likely we will just send you to chromedriver tracker.
