### ISSUE TITLE
[🐛 Bug]: Unable to update to 4.11.0 (Python)

### ISSUE THREAD

**Issue by yusancky** [SeleniumHQ/selenium#12458]
### What happened?

My code has worked fine in the last few versions including 4.10.0. But when the bot tried to upgrade the dependency to 4.11.0, the problem appeared: the error said "Unable to locate or obtain driver for chromeUnable to locate or obtain driver for chrome".

#### `build.py`
```python
# Copyright (c) yusancky. All rights reserved. 
# Licensed under the Apache License 2.0. See License in the project root for license information. 

import AllUp_utils.web

if __name__ == '__main__':
    chromedriver = AllUp_utils.web.configure_chromedriver()
```

#### `AllUp_utils/web.py`
```python
# Copyright (c) yusancky. All rights reserved. 
# Licensed under the Apache License 2.0. See License in the project root for license information. 

from requests import get
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

def configure_chromedriver():
    chrome_service = Service('/usr/local/share/chrome_driver/chromedriver')
    chrome_options = Options()
    for option in ['--headless','--disable-gpu','--window-size=1920,1200','--ignore-certificate-errors','--disable-extensions','--no-sandbox','--disable-dev-shm-usage']:
        chrome_options.add_argument(option)
    return webdriver.Chrome(service = chrome_service,options = chrome_options)

def fetch_data(url,need_selenium = False):
    if need_selenium:
        need_selenium.get(url)
        return need_selenium.page_source
    else:
        response = get(url)
        return response.text
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/runner/work/AllUp-Satwiki/AllUp-Satwiki/build.py", line 41, in <module>
    chromedriver = AllUp_utils.web.configure_chromedriver()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/AllUp-Satwiki/AllUp-Satwiki/AllUp_utils/web.py", line 14, in configure_chromedriver
    return webdriver.Chrome(service = chrome_service,options = chrome_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to locate or obtain driver for {options.capabilities['browserName']}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Ubuntu 22.04

### Selenium version

Python 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 115.0.5790.102

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 115.0.5790.102

**Comment by titusfortner** [comment]
That's this bug - https://github.com/GoogleChromeLabs/chrome-for-testing/issues/30

You do not need to specify a driver location or manage drivers yourself with Selenium 4.11. Remove the references to `chrome_service` in the above code and it will work.

**Comment by anuragkumar201002** [comment]
Message: unknown error: Chrome failed to start: exited abnormally

**Comment by titusfortner** [comment]
@anuragkumar201002 turn on logging and see what the problem is. If it looks like a bug, file a new issue here.

https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
