### ISSUE TITLE
[🐛 Bug]: Entire application crash in case of unhandled exception in `async void` method

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#12480]
### What happened?

Application is crashed.

### How can we reproduce the issue?

```shell
Open `youtube.com` with enabled network monitoring.


var net = driver.Manage().Network;

        net.NetworkRequestSent += (sender, e) =>
        {
            //Console.WriteLine(e.RequestUrl);
        };
```

### Relevant log output

```shell
Running selected tests in D:\Temp\aaa\bin\Debug\net7.0\aaa.dll
   NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Non-Explicit run
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at aaa.UnitTest1.<>c__DisplayClass0_0.<Test1>b__2(Object sender, NetworkResponseReceivedEventArgs e) in D:\Temp\aaa\UnitTest1.cs:line 31
   at OpenQA.Selenium.NetworkManager.OnResponsePaused(Object sender, ResponsePausedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
```


### Operating System

any

### Selenium version

any

### What are the browser(s) and version(s) where you see this issue?

any

### What are the browser driver(s) and version(s) where you see this issue?

any

### Are you using Selenium Grid?

_No response_

**Comment by nvborisenko** [comment]
It happens because of `async void` as event handler: https://github.com/SeleniumHQ/selenium/blob/fbfa5d26ce96ca067d62b6921915e640498e3b09/dotnet/src/webdriver/NetworkManager.cs#L215C9-L215C9

We should refactor it to `async Task` or just `void`.

**Comment by diemol** [comment]
Thank you for reporting this and pointing out the issue. Which option would be better?

**Comment by nvborisenko** [comment]
`async Task` is better, it allows us use `await` in the body. But changing method signature might be a breaking change (hopefully no, seems it's not public).

Otherwise plan B: just `void` and changing all `await`s to `Task.Run().GetAwaiter().GetResult()`.
