### ISSUE TITLE
[🐛 Bug]: Getting java.lang.IllegalArgumentException: Unknown HttpClient factory jdk-http-client error after upgrading to Selenium 4.10.0

### ISSUE THREAD

**Issue by sandeshmms** [SeleniumHQ/selenium#12498]
### What happened?

In the automation test framework, I upgraded Selenium version to 4.10.0 and ran the tests on Chrome browser 105 on Bamboo linux agents.

But the test failed in the setup method and it threw the below error:
_"java.lang.ExceptionInInitializerError Caused by: java.lang.IllegalArgumentException: Unknown HttpClient factory jdk-http-client"_

**Below are the pom dependencies:**
```
<properties>
		<selenium-version>4.10.0</selenium-version>
		<selenium-http-jdk-client>4.10.0</selenium-http-jdk-client>
		<testng-version>7.8.0</testng-version>
		<itext-version>1.3.1</itext-version>
		<gson-version>2.8.5</gson-version>
	</properties>
```
```
	<dependencies>

		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>3.0.7</version>
		</dependency>

		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>${gson-version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.rc.alm</groupId>
			<artifactId>automated-acceptance-tests-services</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>${selenium-version}</version>
		</dependency>

		<dependency>
		  <groupId>org.seleniumhq.selenium</groupId>
		  <artifactId>selenium-http-jdk-client</artifactId>
		  <version>${selenium-http-jdk-client}</version>
		</dependency>

		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testng-version}</version>
		</dependency>

		<dependency>
			<groupId>com.lowagie</groupId>
			<artifactId>itext</artifactId>
			<version>${itext-version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjrt</artifactId>
		</dependency>

		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
		</dependency>

		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>3.0.0</version>
		</dependency>

		<dependency>
			<groupId>com.flipkart.zjsonpatch</groupId>
			<artifactId>zjsonpatch</artifactId>
			<version>0.4.8</version>
		</dependency>
		
	</dependencies>


```
The above dependencies have both selenium-java and selenium-http-jdk-client. Also, I have added the below statement as well before instantiating the driver:
`System.setProperty("webdriver.http.factory", "jdk-http-client");`

Still it is throwing the above error.

Please advise.

### How can we reproduce the issue?

```shell
Proxy proxy = new Proxy();
		proxy.setSslProxy("<some proxy value>");

		ChromeOptions options = new ChromeOptions();
		options.addArguments("--headless", "--disable-gpu", "--window-size=1920,1200", "--start-maximized", "--incognito", 
				"disable-features=NetworkServiceInProcess", "--disable-dev-shm-usage", "--verbose", "--remote-allow-origins=*", "--ignore-certificate-errors");

		HashMap<String, Object> chromePref = new HashMap<>();
		chromePref.put("download.default_directory", System.getProperty("java.io.tmpdir"));
		options.setExperimentalOption("prefs", chromePref);
		// This gracefully handle insecure certificate error.
		options.setAcceptInsecureCerts(true);
		options.setProxy(proxy);
		
		LOG.info("Selenium Manager driver path: " + SeleniumManager.getInstance().getDriverPath(options));
      
`System.setProperty("webdriver.http.factory", "jdk-http-client");`

		WebDriver driver = new ChromeDriver(options);
driver.get("https://www.google.com");
```

### Relevant log output

```shell
java.lang.ExceptionInInitializerError
	at org.openqa.selenium.remote.HttpCommandExecutor.getDefaultClientFactory(HttpCommandExecutor.java:61)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:95)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.<init>(DriverCommandExecutor.java:89)
	at org.openqa.selenium.chromium.ChromiumDriverCommandExecutor.<init>(ChromiumDriverCommandExecutor.java:43)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.<init>(ChromeDriver.java:111)
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:101)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:87)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:71)
	at com.rc.alm.it.tests.utilities.setup.WebBrowserConfigurator.invokeChromeDriver(WebBrowserConfigurator.java:95)
	at com.rc.alm.it.tests.utilities.setup.WebBrowserConfigurator.invokeChromeDriverHeadless(WebBrowserConfigurator.java:126)
	at com.rc.alm.it.tests.utilities.setup.WebBrowserConfigurator.openBrowser(WebBrowserConfigurator.java:53)
	at com.rc.alm.it.basetests.BaseTest.setup(BaseTest.java:75)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Unknown HttpClient factory jdk-http-client
	at org.openqa.selenium.remote.http.HttpClient$Factory.create(HttpClient.java:57)
	at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor$DefaultClientFactoryHolder.<clinit>(HttpCommandExecutor.java:57)
	... 33 more
... Removed 15 stack frames
```

### Operating System

Linux

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome version 105.0.5195.125

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 105.0.5195.19

### Are you using Selenium Grid?

No. Bamboo agents.

**Comment by diemol** [comment]
Please follow the instructions shown at https://www.selenium.dev/blog/2022/using-java11-httpclient/
