### ISSUE TITLE
[🐛 Bug]: NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager

### ISSUE THREAD

**Issue by cursedgrape** [SeleniumHQ/selenium#12505]
### What happened?

**Note:** I keep getting a connection reset when I try installing chromedriver so apparently there's an issue with the server and this may not be a bug.

```
% brew install chromedriver
==> Downloading https://formulae.brew.sh/api/formula.jws.json
##O#- #                                                                        
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##O#- #                                                                        
Error: Download failed on Cask 'chromedriver' with message: Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.8\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/mac-x64/chromedriver-mac-x64.zip` exited with 35. Here's the output:
curl: (35) Recv failure: Connection reset by peer
```

After installing selenium 4.11.2 on macOS Monterey 12.6.8, selenium stopped working.

### How can we reproduce the issue?

I simply do:

```shell
import selenium
from selenium.webdriver import Chrome

print(selenium.__version__)
Chrome()
```

### Relevant log output

```shell
4.11.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 90, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 138, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}.\n{result}{stderr}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /usr/local/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json.
{'code': 65, 'message': 'error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.170/mac-x64/chromedriver-mac-x64.zip): error trying to connect: Connection reset by peer (os error 54)', 'driver_path': '', 'browser_path': ''}


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Library/Application Support/JetBrains/PyCharm2023.2/scratches/scratch_3.py", line 5, in <module>
    Chrome()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

macOS Monterey 12.6.8

### Selenium version

4.11.2

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 115.0.5790.114 (Official Build) (x86_64)

### What are the browser driver(s) and version(s) where you see this issue?

Unknown

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
You can turn on logging to see what is happening https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

But selenium manages driver downloads for you if you want to avoid installing the driver completely.

**Comment by titusfortner** [comment]
I wonder if the cask isn't updated for the new location of chromedriver with chrome for testing.

**Comment by cursedgrape** [comment]
You probably missed the note which was at the end of my post, I moved it to the top anyway. The issue probably has something to do with chromedriver server, which is confirmed by turning on the logging:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 90, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 138, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}.\n{result}{stderr}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /usr/local/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --debug --output json.
{'code': 65, 'message': 'error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.170/mac-x64/chromedriver-mac-x64.zip): error trying to connect: Connection reset by peer (os error 54)', 'driver_path': '', 'browser_path': ''}
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
python-BaseException
```

**Comment by cursedgrape** [comment]
The issue occurs because of this:

```
{'code': 65, 'message': 'error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.170/mac-x64/chromedriver-mac-x64.zip): error trying to connect: Connection reset by peer (os error 54)', 'driver_path': '', 'browser_path': ''}
```

which is the same error I indicated in the note. Nothing additional shows up when I change the logging level to debug, info, error, ...

**Comment by titusfortner** [comment]
Are you behind a proxy?

**Comment by cursedgrape** [comment]
no and I never encountered such issue, pip upgrades usually work fine.

**Comment by cursedgrape** [comment]
The issue is gone now, possibly due to a local network problem.

**Comment by 11897208** [comment]
i am getting same issue now.. how did you fixed the error ?

**Comment by kvk30** [comment]
I still have the issue. 
can you help me?

**Comment by YoungerThuggg** [comment]
> I still have the issue. can you help me?

Did you find a fix for this?

**Comment by titusfortner** [comment]
Update to 4.14, turn on logging to see if it explains the issue, file a new bug if it does not.
