### ISSUE TITLE
[🐛 Bug]: SessionNotCreatedError exception for chrome 112/113/114/115 with selenium

### ISSUE THREAD

**Issue by firnny11** [SeleniumHQ/selenium#12566]
### What happened?

Use selenium hub and selenium node-chrome images to create hub and nodes(the images are got from https://hub.docker.com/r/selenium/node-chrome/tags?), the session can't be started when running automation with the created hub and nodes, the issue persists for chrome 112/113/114/115([tags: [4.10.0-20230607], [4.11.0-20230801]) and  [111.0-20230404] is working fine.

### How can we reproduce the issue?

```shell
Use selenium hub and selenium node-chrome images to create hub and nodes(the images are got from https://hub.docker.com/r/selenium/node-chrome/tags?), then run automation with the hub and nodes. Issue images started from chrome 112 until chrome 115
```

### Relevant log output

```shell
SessionNotCreatedError: An error occurred while creating a new Selenium Server session: [SessionNotCreatedError] Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Handshake response does not match any supported protocol. Response payload: {"sessionId":"e53b3e47e7e317497b67e1a96612d011","status":33,"value":{"message":"session not created: Missing or invalid capabilities\n  (Driver info: chromedriver=114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}),platform=Linux 5.4.242-155.348.amzn2.x86_64 x86_64)"}} 
       Host info: host: 'firnnytest-selenium-chrome-node-654c4855b4-zz5t4', ip: '10.5.83.101'
       Build info: version: '4.10.0', revision: 'c14d967899'
       System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.242-155.348.amzn2.x86_64', java.version: '11.0.19'
       Driver info: driver.version: unknown
       Build info: version: '4.10.0', revision: 'c14d967899'
       System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.242-155.348.amzn2.x86_64', java.version: '11.0.19'
       Driver info: driver.version: unknown
       Build info: version: '4.10.0', revision: 'c14d967899'
       System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.242-155.348.amzn2.x86_64', java.version: '11.0.19'
       Driver info: driver.version: unknown
           at Object.throwDecodedError (/Users/fsun/nightwatch-cucumber-starter/node_modules/selenium-webdriver/lib/error.js:522:15)
           at parseHttpResponse (/Users/fsun/nightwatch-cucumber-starter/node_modules/selenium-webdriver/lib/http.js:589:13)
           at Executor.execute (/Users/fsun/nightwatch-cucumber-starter/node_modules/selenium-webdriver/lib/http.js:514:28)
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating System

Ubuntu

### Selenium version

4.9.0, 4.9.1 4.10.0, 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 112,/113/114/115

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver=114.0.5735.90 for chrome 114

### Are you using Selenium Grid?

4.x

**Comment by diemol** [comment]
You are sending JWP formed capabilities, this has been deprecated for a long time and removed in 4.9 (4.10?).

https://www.selenium.dev/blog/2022/legacy-protocol-support/
