### ISSUE TITLE
[🐛 Bug]: Unable to use ChromeDriverService with selenium 4.11.0 version

### ISSUE THREAD

**Issue by bachhavdipak** [SeleniumHQ/selenium#12598]
### What happened?

I am facing issue while using ChromeDriverService with selenium 4.11.0 version but same code is working with bonigarcia WebDriverManager. Obviously we need to add below code to manage drivers.
     
```
ChromeDriverManager.getInstance(DriverManagerType.CHROME).setup();
WebDriverManager.chromedriver().setup();
```

### How can we reproduce the issue?

```shell
import org.jetbrains.annotations.NotNull;
    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.chrome.ChromeDriverService;
    import org.openqa.selenium.chrome.ChromeOptions;
    import org.openqa.selenium.remote.RemoteWebDriver;
    import java.io.IOException;
    public class TestExample {
    
        @NotNull
        private static ChromeOptions getChromeOptions() {
    
            final ChromeOptions chromeOptions = new ChromeOptions();
    
            chromeOptions.setAcceptInsecureCerts(true);
    
            chromeOptions.addArguments(
                    "--ignore-certificate-errors",
                    "--disable-download-notification",
                    "--no-sandbox"
            );
            return chromeOptions;
        }
    
        public static void main(String[] args) throws IOException {
    
            ChromeDriverService service;
            service = new ChromeDriverService.Builder()
                    .usingAnyFreePort()
                    .build();
            service.start();
            WebDriver driver = new RemoteWebDriver(service.getUrl(), getChromeOptions());
            driver.get("https://selenium.dev");    
            driver.quit();
        }
    }
```

### Relevant log output

```shell
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at org.openqa.selenium.os.ExecutableFinder.find(ExecutableFinder.java:47)
	at org.openqa.selenium.os.OsProcess.<init>(OsProcess.java:63)
	at org.openqa.selenium.os.CommandLine.<init>(CommandLine.java:35)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:198)
	at digital.eComm.ui.tests.TestExample.main(TestExample.java:78)
```

### Operating System

Windows 11

### Selenium version

JAVA 11

### What are the browser(s) and version(s) where you see this issue?

chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

hromedriver 116.0.5845.96

**Comment by diemol** [comment]
If you are building the service yourself, you need to set up the driver on your own. Which is what you are doing when you invoke WebDriverManager. You can probably do the same by executing `DriverFinder.getPath`.
