### ISSUE TITLE
[🐛 Bug]: ChromeDriver is assuming that Chrome has crashed

### ISSUE THREAD

**Issue by fprin** [SeleniumHQ/selenium#12619]
### What happened?

I keep getting this error message: 
```
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'a5c6dc83835e', ip: '192.168.224.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '1.8.0_292'
Driver info: driver.version: unknown
```

### How can we reproduce the issue?

Run this python code:
```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

selenium_host = "selenium"  # Hostname of the Selenium container
selenium_port = 4444       # Port of the Selenium container

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Remote(
    command_executor=f"http://{selenium_host}:{selenium_port}/wd/hub",
    options=chrome_options
)
```

Use this Dockerfile:
```Dockerfile
FROM --platform=linux/amd64 python:3.10

# Install Chrome browser dependencies
RUN apt-get update && \
    apt-get install -y \
    curl \
    wget \
    gnupg \
    unzip \
    fonts-liberation

# Download and install Chrome browser
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

# Install specific version of chromedriver
RUN CHROMEDRIVER_VERSION=94.0.4606.61 && \
    wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip -d /usr/local/bin && \
    rm /tmp/chromedriver.zip

# Install Selenium and other required packages
RUN pip install selenium
```

and this docker-compose file:
```docker-comopse
version: '3.7'

services:

  selenium:
    image: selenium/standalone-chrome-debug:latest
    platform: linux/amd64
    # user: "${UID}:${GID}"
    environment:
      - VNC_NO_PASSWORD=1
      # - SCREEN_WIDTH=1200
      # - SCREEN_HEIGHT=675
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      - START_XVFB=true
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps= -Dselenium.LOGGER.level=ALL
    ports:
      - 4444:4444
      - 5900:5900


  python-script:
    build:
      context: .
      dockerfile: Dockerfile.python
    platform: linux/amd64
    # user: "${UID}:${GID}" 
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    depends_on:
      - selenium
    command: >
      bash -c "sleep infinity
      "
```

The required commands are:
```bash
# first terminal
docker-compose up
# second terminal
docker-compose exec -it python-script python
# execute python code above
```

#### Logs after executing python code above.

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'a5c6dc83835e', ip: '192.168.224.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '1.8.0_292'
Driver info: driver.version: unknown
remote stacktrace: #0 0x004000a2a8f3 <unknown>
#1 0x00400050fba8 <unknown>
#2 0x004000532e33 <unknown>
#3 0x00400052e9ef <unknown>
#4 0x004000568995 <unknown>
#5 0x004000562d63 <unknown>
#6 0x004000539144 <unknown>
#7 0x00400053a135 <unknown>
#8 0x004000a59c3e <unknown>
#9 0x004000a6f6b7 <unknown>
#10 0x004000a5ab95 <unknown>
#11 0x004000a70b05 <unknown>
#12 0x004000a4f2ab <unknown>
#13 0x004000a8b248 <unknown>
#14 0x004000a8b3c8 <unknown>
#15 0x004000aa633d <unknown>
#16 0x004002be3609 start_thread

Stacktrace:
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:423)
    at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0 (W3CHandshakeResponse.java:62)
    at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0 (HandshakeResponse.java:30)
    at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0 (ProtocolHandshake.java:126)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.tryAdvance (Spliterators.java:958)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
    at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession (ProtocolHandshake.java:128)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession (ProtocolHandshake.java:74)
    at org.openqa.selenium.grid.session.remote.RemoteSession$Factory.performHandshake (RemoteSession.java:147)
    at org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply (ServicedSession.java:161)
    at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12 (ActiveSessionFactory.java:180)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$11$1.accept (ReferencePipeline.java:440)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.Spliterators$ArraySpliterator.tryAdvance (Spliterators.java:958)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
    at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
    at org.openqa.selenium.remote.server.ActiveSessionFactory.apply (ActiveSessionFactory.java:183)
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2 (NewSessionPipeline.java:66)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.Collections$2.tryAdvance (Collections.java:4719)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
    at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3 (NewSessionPipeline.java:69)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.DistinctOps$1$2.accept (DistinctOps.java:175)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance (StreamSpliterators.java:303)
    at java.util.stream.Streams$ConcatSpliterator.tryAdvance (Streams.java:731)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
    at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
    at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession (NewSessionPipeline.java:72)
    at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute (BeginSession.java:65)
    at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:235)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
```

#### Logs from the selenium container.

```
novnc-selenium-1       | 21:26:18.936 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.lang:type=MemoryPool,name=Code Cache
novnc-selenium-1       | 21:26:18.936 FINER [Repository.addMBean] - name = java.lang:type=MemoryPool,name=Code Cache
novnc-selenium-1       | 21:26:18.936 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.lang:name=Code Cache,type=MemoryPool
novnc-selenium-1       | 21:26:18.936 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=MemoryPool,name=Code Cache
novnc-selenium-1       | 21:26:18.936 FINER [Repository.contains] -  name = java.lang:type=MemoryPool,name=Metaspace
novnc-selenium-1       | 21:26:18.937 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
novnc-selenium-1       | 21:26:18.937 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.lang:type=MemoryPool,name=Metaspace
novnc-selenium-1       | 21:26:18.938 FINER [Repository.addMBean] - name = java.lang:type=MemoryPool,name=Metaspace
novnc-selenium-1       | 21:26:18.938 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.lang:name=Metaspace,type=MemoryPool
novnc-selenium-1       | 21:26:18.938 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=MemoryPool,name=Metaspace
novnc-selenium-1       | 21:26:18.938 FINER [Repository.contains] -  name = java.lang:type=MemoryPool,name=Compressed Class Space
novnc-selenium-1       | 21:26:18.938 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
novnc-selenium-1       | 21:26:18.939 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.lang:type=MemoryPool,name=Compressed Class Space
novnc-selenium-1       | 21:26:18.939 FINER [Repository.addMBean] - name = java.lang:type=MemoryPool,name=Compressed Class Space
novnc-selenium-1       | 21:26:18.939 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.lang:name=Compressed Class Space,type=MemoryPool
novnc-selenium-1       | 21:26:18.939 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=MemoryPool,name=Compressed Class Space
novnc-selenium-1       | 21:26:18.939 FINER [Repository.contains] -  name = java.lang:type=MemoryPool,name=PS Eden Space
novnc-selenium-1       | 21:26:18.940 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
novnc-selenium-1       | 21:26:18.940 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.lang:type=MemoryPool,name=PS Eden Space
novnc-selenium-1       | 21:26:18.940 FINER [Repository.addMBean] - name = java.lang:type=MemoryPool,name=PS Eden Space
novnc-selenium-1       | 21:26:18.940 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.lang:name=PS Eden Space,type=MemoryPool
novnc-selenium-1       | 21:26:18.940 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=MemoryPool,name=PS Eden Space
novnc-selenium-1       | 21:26:18.940 FINER [Repository.contains] -  name = java.lang:type=MemoryPool,name=PS Survivor Space
novnc-selenium-1       | 21:26:18.950 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
novnc-selenium-1       | 21:26:18.981 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.lang:type=MemoryPool,name=PS Survivor Space
novnc-selenium-1       | 21:26:18.981 FINER [Repository.addMBean] - name = java.lang:type=MemoryPool,name=PS Survivor Space
novnc-selenium-1       | 21:26:18.982 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.lang:name=PS Survivor Space,type=MemoryPool
novnc-selenium-1       | 21:26:18.998 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=MemoryPool,name=PS Survivor Space
novnc-selenium-1       | 21:26:18.998 FINER [Repository.contains] -  name = java.lang:type=MemoryPool,name=PS Old Gen
novnc-selenium-1       | 21:26:18.998 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
novnc-selenium-1       | 21:26:18.999 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.lang:type=MemoryPool,name=PS Old Gen
novnc-selenium-1       | 21:26:18.999 FINER [Repository.addMBean] - name = java.lang:type=MemoryPool,name=PS Old Gen
novnc-selenium-1       | 21:26:18.999 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.lang:name=PS Old Gen,type=MemoryPool
novnc-selenium-1       | 21:26:18.999 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=MemoryPool,name=PS Old Gen
novnc-selenium-1       | 21:26:19.066 FINER [Repository.contains] -  name = java.lang:type=OperatingSystem
novnc-selenium-1       | 21:26:19.070 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.OperatingSystemImpl
novnc-selenium-1       | 21:26:19.071 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.lang:type=OperatingSystem
novnc-selenium-1       | 21:26:19.071 FINER [Repository.addMBean] - name = java.lang:type=OperatingSystem
novnc-selenium-1       | 21:26:19.071 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.lang:type=OperatingSystem
novnc-selenium-1       | 21:26:19.071 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=OperatingSystem
novnc-selenium-1       | 21:26:19.071 FINER [Repository.contains] -  name = java.lang:type=Runtime
novnc-selenium-1       | 21:26:19.078 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.RuntimeImpl
novnc-selenium-1       | 21:26:19.078 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.lang:type=Runtime
novnc-selenium-1       | 21:26:19.078 FINER [Repository.addMBean] - name = java.lang:type=Runtime
novnc-selenium-1       | 21:26:19.079 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.lang:type=Runtime
novnc-selenium-1       | 21:26:19.079 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=Runtime
novnc-selenium-1       | 21:26:19.081 FINER [Repository.contains] -  name = java.lang:type=Threading
novnc-selenium-1       | 21:26:19.098 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.ThreadImpl
novnc-selenium-1       | 21:26:19.098 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.lang:type=Threading
novnc-selenium-1       | 21:26:19.099 FINER [Repository.addMBean] - name = java.lang:type=Threading
novnc-selenium-1       | 21:26:19.099 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.lang:type=Threading
novnc-selenium-1       | 21:26:19.099 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=Threading
novnc-selenium-1       | 21:26:19.100 FINER [Repository.contains] -  name = java.util.logging:type=Logging
novnc-selenium-1       | 21:26:19.105 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.ManagementFactoryHelper$PlatformLoggingImpl
novnc-selenium-1       | 21:26:19.106 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.util.logging:type=Logging
novnc-selenium-1       | 21:26:19.106 FINER [Repository.addMBean] - name = java.util.logging:type=Logging
novnc-selenium-1       | 21:26:19.106 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.util.logging:type=Logging
novnc-selenium-1       | 21:26:19.106 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.util.logging:type=Logging
novnc-selenium-1       | 21:26:19.109 FINER [Repository.contains] -  name = java.nio:type=BufferPool,name=direct
novnc-selenium-1       | 21:26:19.111 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.ManagementFactoryHelper$1
novnc-selenium-1       | 21:26:19.111 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.nio:type=BufferPool,name=direct
novnc-selenium-1       | 21:26:19.111 FINER [Repository.addMBean] - name = java.nio:type=BufferPool,name=direct
novnc-selenium-1       | 21:26:19.111 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.nio:name=direct,type=BufferPool
novnc-selenium-1       | 21:26:19.111 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.nio:type=BufferPool,name=direct
novnc-selenium-1       | 21:26:19.112 FINER [Repository.contains] -  name = java.nio:type=BufferPool,name=mapped
novnc-selenium-1       | 21:26:19.112 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.ManagementFactoryHelper$1
novnc-selenium-1       | 21:26:19.112 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = java.nio:type=BufferPool,name=mapped
novnc-selenium-1       | 21:26:19.112 FINER [Repository.addMBean] - name = java.nio:type=BufferPool,name=mapped
novnc-selenium-1       | 21:26:19.112 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object java.nio:name=mapped,type=BufferPool
novnc-selenium-1       | 21:26:19.113 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.nio:type=BufferPool,name=mapped
novnc-selenium-1       | 21:26:19.114 FINER [Repository.contains] -  name = java.lang:type=GarbageCollector,name=PS Scavenge
novnc-selenium-1       | 21:26:19.114 FINER [Repository.contains] -  name = java.lang:type=GarbageCollector,name=PS MarkSweep
novnc-selenium-1       | 21:26:19.114 FINER [Repository.contains] -  name = java.lang:type=OperatingSystem
novnc-selenium-1       | 21:26:19.114 FINER [Repository.contains] -  name = java.lang:type=OperatingSystem
novnc-selenium-1       | 21:26:19.116 FINER [Repository.contains] -  name = com.sun.management:type=HotSpotDiagnostic
novnc-selenium-1       | 21:26:19.122 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for sun.management.HotSpotDiagnostic
novnc-selenium-1       | 21:26:19.122 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = com.sun.management:type=HotSpotDiagnostic
novnc-selenium-1       | 21:26:19.123 FINER [Repository.addMBean] - name = com.sun.management:type=HotSpotDiagnostic
novnc-selenium-1       | 21:26:19.123 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object com.sun.management:type=HotSpotDiagnostic
novnc-selenium-1       | 21:26:19.123 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered com.sun.management:type=HotSpotDiagnostic
novnc-selenium-1       | 21:26:19.164 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = com.sun.management:type=DiagnosticCommand
novnc-selenium-1       | 21:26:19.165 FINER [Repository.addMBean] - name = com.sun.management:type=DiagnosticCommand
novnc-selenium-1       | 21:26:19.166 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object com.sun.management:type=DiagnosticCommand
novnc-selenium-1       | 21:26:19.166 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered com.sun.management:type=DiagnosticCommand
novnc-selenium-1       | 21:26:19.199 FINER [Repository.contains] -  name = jdk.management.jfr:type=FlightRecorder
novnc-selenium-1       | 21:26:19.199 FINER [MBeanServerFactory.getMBeanInfo] - Building MBeanInfo for jdk.management.jfr.FlightRecorderMXBeanImpl
novnc-selenium-1       | 21:26:19.203 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = jdk.management.jfr:type=FlightRecorder
novnc-selenium-1       | 21:26:19.203 FINER [Repository.addMBean] - name = jdk.management.jfr:type=FlightRecorder
novnc-selenium-1       | 21:26:19.204 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object jdk.management.jfr:type=FlightRecorder
novnc-selenium-1       | 21:26:19.204 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered jdk.management.jfr:type=FlightRecorder
novnc-selenium-1       | 21:26:19.251 FINER [DefaultMBeanServerInterceptor.registerMBean] - ObjectName = org.seleniumhq.server:type=SeleniumServer
novnc-selenium-1       | 21:26:19.251 FINER [Repository.addMBean] - name = org.seleniumhq.server:type=SeleniumServer
novnc-selenium-1       | 21:26:19.251 FINER [DefaultMBeanServerInterceptor.addObject] - Send create notification of object org.seleniumhq.server:type=SeleniumServer
novnc-selenium-1       | 21:26:19.251 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered org.seleniumhq.server:type=SeleniumServer
novnc-selenium-1       | 21:26:19.486 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
novnc-selenium-1       | 21:26:19.765 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
novnc-selenium-1       | 21:26:38.182 DEBUG [WebDriverServlet.handle] - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@3e944acc
novnc-selenium-1       | 21:26:38.196 DEBUG [WebDriverServlet.lambda$handle$0] - /session: Executing POST on /session (handler: BeginSession)
novnc-selenium-1       | 21:26:38.398 INFO [ActiveSessionFactory.apply] - Capabilities are: {
novnc-selenium-1       |   "browserName": "chrome",
novnc-selenium-1       |   "goog:chromeOptions": {
novnc-selenium-1       |     "extensions": [
novnc-selenium-1       |     ],
novnc-selenium-1       |     "args": [
novnc-selenium-1       |       "--no-sandbox",
novnc-selenium-1       |       "--headless",
novnc-selenium-1       |       "--disable-dev-shm-usage",
novnc-selenium-1       |       "--disable-extensions"
novnc-selenium-1       |     ]
novnc-selenium-1       |   },
novnc-selenium-1       |   "pageLoadStrategy": "normal"
novnc-selenium-1       | }
novnc-selenium-1       | 21:26:38.405 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
novnc-selenium-1       | 21:26:38.447 DEBUG [UrlChecker.waitUntilAvailable] - Waiting for [http://localhost:29765/status]
novnc-selenium-1       | 21:26:38.454 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:29765/status
novnc-selenium-1       | 21:26:38.489 FINEST [HttpURLConnection.plainConnect0] - ProxySelector Request for http://localhost:29765/status
novnc-selenium-1       | 21:26:38.526 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:29765/status
novnc-selenium-1       | 21:26:38.527 FINEST [HttpURLConnection.plainConnect0] - ProxySelector Request for http://localhost:29765/status
novnc-selenium-1       | 21:26:38.550 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:29765/status
novnc-selenium-1       | 21:26:38.552 FINEST [HttpURLConnection.plainConnect0] - ProxySelector Request for http://localhost:29765/status
novnc-selenium-1       | 21:26:38.594 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:29765/status
novnc-selenium-1       | 21:26:38.595 FINEST [HttpURLConnection.plainConnect0] - ProxySelector Request for http://localhost:29765/status
novnc-selenium-1       | Starting ChromeDriver 94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}) on port 29765
novnc-selenium-1       | All remote connections are allowed. Use an allowlist instead!
novnc-selenium-1       | Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
novnc-selenium-1       | 21:26:38.677 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:29765/status
novnc-selenium-1       | 21:26:38.678 FINEST [HttpURLConnection.plainConnect0] - ProxySelector Request for http://localhost:29765/status
novnc-selenium-1       | ChromeDriver was started successfully.
novnc-selenium-1       | 21:26:38.839 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:29765/status
novnc-selenium-1       | 21:26:38.842 FINEST [HttpURLConnection.plainConnect0] - ProxySelector Request for http://localhost:29765/status
novnc-selenium-1       | 21:26:38.846 FINEST [HttpURLConnection.plainConnect0] - Proxy used: DIRECT
novnc-selenium-1       | 21:26:38.851 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@3a854de45 pairs: {GET /status HTTP/1.1: null}{User-Agent: Java/1.8.0_292}{Host: localhost:29765}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
novnc-selenium-1       | 21:26:38.863 FINEST [HttpClient.logFinest] - KeepAlive stream used: http://localhost:29765/status
novnc-selenium-1       | 21:26:38.867 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@7f87d4d04 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 252}{Content-Type: application/json; charset=utf-8}{cache-control: no-cache}
```
```


### Operating System

macOS M2 Venture 13.0

### Selenium version

4.11.2

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 94.0.4606.61 (inside of selenium container)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204})

### Are you using Selenium Grid?

yes - version 3.141.59

**Comment by diemol** [comment]
We don't support old versions of Selenium. Please update and report back if the issue still persists.

**Comment by fprin** [comment]
I mean @diemol how do you want me to work with at latest version of grid, if you guys haven't push a new image to the dockerhub repository in two years: https://github.com/SeleniumHQ/docker-selenium/issues/1928#issuecomment-1695693107

**Comment by diemol** [comment]
I replied to that issue as well. Please have a look at our README. Plenty of things have changed since Selenium 4 release.
