### ISSUE TITLE
[🐛 Bug]: can not launch geckodriver.exe under cygwin environment

### ISSUE THREAD

**Issue by mora-01** [SeleniumHQ/selenium#12618]
### What happened?

Under Cygwin environment using selenium-webdriver version 11.4? I got the error : 

/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/child_process.rb:57:in `spawn': No such file or directory - D:\\cygwin64_latest\\cygwin64\\usr\\local\\bin\\geckodriver.exe
 (Errno::ENOENT)

I use this workaround to resolve the issue. 
In selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service.rb file, I replace 
@executable_path = path by @executable_path = '/usr/local/bin/geckodriver.exe' in initialize method.

### How can we reproduce the issue?

```shell
require 'watir'
Watir::Browser.new :firefox
```

### Relevant log output

```shell
/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/child_process.rb:57:in `spawn': No such file or directory - D:\cygwin64_latest\cygwin64\usr\local\bin\geckodriver.exe (Errn
o::ENOENT)
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/child_process.rb:57:in `start'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service_manager.rb:104:in `start_process'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/socket_lock.rb:42:in `locked'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service_manager.rb:55:in `start'
        from <internal:kernel>:90:in `tap'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service.rb:91:in `launch'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:334:in `service_url'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/local_driver.rb:28:in `initialize_local_driver'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/firefox/driver.rb:42:in `initialize'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `new'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver.rb:88:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/watir-7.3.0/lib/watir/browser.rb:46:in `initialize'
```

### Operating System

Cygwin

### Selenium version

Ruby 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 116.0.3 (64 bits)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.33.0

**Comment by titusfortner** [comment]
@mora-01 thanks. Can you
1. Delete all drivers on your system
2. Re-run that code with `Watir.logger.selenium = :debug`?

**Comment by mora-01** [comment]
Hi, here is the output after running Watir.logger.selenium = :debug

2023-08-27 09:08:46 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2023-08-27 09:08:46 DEBUG Selenium [:selenium_manager] Selenium Manager binary found at /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/bin/windows/selenium-manager.exe
2023-08-27 09:08:46 DEBUG Selenium [:selenium_manager] Executing Process ["/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/bin/windows/selenium-manager.exe", "--browser", "firefox", "--output", "json",
 "--debug"]
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Checking geckodriver in PATH
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Running command: geckodriver --version
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Output: "geckodriver 0.33.0 (a80e5fd61076 2023-04-02 18:31 +0000)\n\nThe source code of this program is available from\ntesting/geckodriver in https://hg.mozi
lla.org/mozilla-central.\n\nThis program is subject to the terms of the Mozilla Public License 2.0.\nYou can obtain a copy of the license at https://mozilla.org/MPL/2.0/."
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Running command: where geckodriver
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Output: "D:\\cygwin64_latest\\cygwin64\\usr\\local\\bin\\geckodriver.exe"
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Found geckodriver 0.33.0 in PATH: D:\cygwin64_latest\cygwin64\usr\local\bin\geckodriver.exe
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] firefox detected at C:\Program Files\Mozilla Firefox\firefox.exe
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Using shell command to find out firefox version
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Running command: wmic datafile where name='C:\\Program Files\\Mozilla Firefox\\firefox.exe' get Version /value
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Output: "\r\r\n\r\r\nVersion=116.0.3.8627\r\r\n\r\r\n\r\r\n\r"
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Detected browser: firefox 116.0.3.8627
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Required driver: geckodriver 0.33.0
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Driver path: D:\cygwin64_latest\cygwin64\usr\local\bin\geckodriver.exe
2023-08-27 09:08:47 DEBUG Selenium [:selenium_manager] Browser path: C:\Program Files\Mozilla Firefox\firefox.exe
2023-08-27 09:08:47 DEBUG Selenium [:driver_service] Executing Process ["D:\\cygwin64_latest\\cygwin64\\usr\\local\\bin\\geckodriver.exe", "--port=4444"]
2023-08-27 09:08:47 DEBUG Selenium [:process] Starting process: ["D:\\cygwin64_latest\\cygwin64\\usr\\local\\bin\\geckodriver.exe", "--port=4444"] with {[:out, :err]=>#<IO:<STDOUT>>}
/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/child_process.rb:57:in `spawn': No such file or directory - D:\cygwin64_latest\cygwin64\usr\local\bin\geckodriver.exe (Errn
o::ENOENT)
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/child_process.rb:57:in `start'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service_manager.rb:104:in `start_process'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/socket_lock.rb:42:in `locked'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service_manager.rb:55:in `start'
        from <internal:kernel>:90:in `tap'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service.rb:92:in `launch'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:334:in `service_url'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/local_driver.rb:28:in `initialize_local_driver'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/firefox/driver.rb:42:in `initialize'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `new'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver.rb:88:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/watir-7.3.0/lib/watir/browser.rb:46:in `initialize'

**Comment by titusfortner** [comment]
Huh, that's weird that the system reports that as the location but that Ruby can't use it at that location.

Try deleting the driver at this location: D:\\cygwin64_latest\\cygwin64\\usr\\local\\bin\\geckodriver.exe
Then re-run

**Comment by mora-01** [comment]
output after deleting the driver at this location: D:\cygwin64_latest\cygwin64\usr\local\bin\geckodriver.exe and re-run :
require 'watir'
Watir.logger.selenium = :debug
Watir::Browser.new :firefox

2023-08-27 15:35:42 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2023-08-27 15:35:42 DEBUG Selenium [:selenium_manager] Selenium Manager binary found at /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/bin/windows/selenium-manager.exe
2023-08-27 15:35:42 DEBUG Selenium [:selenium_manager] Executing Process ["/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/bin/windows/selenium-manager.exe", "--browser", "firefox", "--output", "json",
 "--debug"]
2023-08-27 15:36:04 DEBUG Selenium [:selenium_manager] Checking geckodriver in PATH
2023-08-27 15:36:04 DEBUG Selenium [:selenium_manager] Running command: geckodriver --version
2023-08-27 15:36:04 DEBUG Selenium [:selenium_manager] Output: ""
2023-08-27 15:36:04 DEBUG Selenium [:selenium_manager] geckodriver not found in PATH
2023-08-27 15:36:04 DEBUG Selenium [:selenium_manager] firefox detected at C:\Program Files\Mozilla Firefox\firefox.exe
2023-08-27 15:36:04 DEBUG Selenium [:selenium_manager] Using shell command to find out firefox version
2023-08-27 15:36:04 DEBUG Selenium [:selenium_manager] Running command: wmic datafile where name='C:\\Program Files\\Mozilla Firefox\\firefox.exe' get Version /value
2023-08-27 15:36:04 DEBUG Selenium [:selenium_manager] Output: "\r\r\n\r\r\nVersion=116.0.3.8627\r\r\n\r\r\n\r\r\n\r"
2023-08-27 15:36:04 DEBUG Selenium [:selenium_manager] Detected browser: firefox 116.0.3.8627
2023-08-27 15:36:04 ERROR Selenium [:selenium_manager] error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): error trying to connect: tcp connect error: Une tentative de connexion
 a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. (os error 10060)
/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver_finder.rb:30:in `rescue in path': Unable to obtain geckodriver using Selenium Manager; Unsuccessful command executed
: ["/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/bin/windows/selenium-manager.exe", "--browser", "firefox", "--output", "json", "--debug"] (Selenium::WebDriver::Error::NoSuchDriverError)
{"code"=>65, "message"=>"error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): error trying to connect: tcp connect error: Une tentative de connexion a échoué car le parti connect
é n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. (os error 10060)", "driver_path"=>"", "browser_path"=>""}; For documentation
 on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver_finder.rb:27:in `path'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/local_driver.rb:49:in `process_options'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/local_driver.rb:27:in `initialize_local_driver'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/firefox/driver.rb:42:in `initialize'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `new'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver.rb:88:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/watir-7.3.0/lib/watir/browser.rb:46:in `initialize'
        from ./test.rb:2738:in `new'
        from ./test.rb:2738:in `<main>'
/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/selenium_manager.rb:123:in `run': Unsuccessful command executed: ["/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.1
1.0/bin/windows/selenium-manager.exe", "--browser", "firefox", "--output", "json", "--debug"] (Selenium::WebDriver::Error::WebDriverError)
{"code"=>65, "message"=>"error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): error trying to connect: tcp connect error: Une tentative de connexion a échoué car le parti connect
é n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. (os error 10060)", "driver_path"=>"", "browser_path"=>""}
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/selenium_manager.rb:42:in `driver_path'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver_finder.rb:28:in `path'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/local_driver.rb:49:in `process_options'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/local_driver.rb:27:in `initialize_local_driver'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/firefox/driver.rb:42:in `initialize'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `new'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver.rb:88:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/watir-7.3.0/lib/watir/browser.rb:46:in `initialize'

**Comment by titusfortner** [comment]
Ok, well, now that's a network/proxy issues. Something on your system/network doesn't give you access to the site we look at for determining the right driver to install. 

So 3 things.

First, @bonigarcia I'm not familiar with cygwin, any idea why it might be lying to us here or what the disconnect is?

Second, figure out what your network issue is and if the network calls need to go through a proxy, or something needs to be added to an allow-list somewhere so it can work automatically like we want.

Third, in the meantime you can make it work manually by downloading the correct driver again and referencing it with Watir like this:
```ruby
require 'watir'
Watir::Browser.new :firefox, service: {path: path_to_driver}
```

**Comment by mora-01** [comment]
sorry for the network issue, after deleting the driver at this location: D:\cygwin64_latest\cygwin64\usr\local\bin\geckodriver.exe I re-run :

require 'watir'
Watir.logger.selenium = :debug
Watir::Browser.new :firefox

Here is the output : 

2023-08-27 22:12:24 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2023-08-27 22:12:24 DEBUG Selenium [:selenium_manager] Selenium Manager binary found at /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/bin/windows/selenium-manager.exe
2023-08-27 22:12:24 DEBUG Selenium [:selenium_manager] Executing Process ["/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/bin/windows/selenium-manager.exe", "--browser", "firefox", "--output", "json", "--debug"]
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Checking geckodriver in PATH
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Running command: geckodriver --version
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Output: ""
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] geckodriver not found in PATH
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] firefox detected at C:\Program Files\Mozilla Firefox\firefox.exe
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Using shell command to find out firefox version
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Running command: wmic datafile where name='C:\\Program Files\\Mozilla Firefox\\firefox.exe' get Version /value
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Output: "\r\r\n\r\r\nVersion=116.0.3.8627\r\r\n\r\r\n\r\r\n\r"
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Detected browser: firefox 116.0.3.8627
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Required driver: geckodriver 0.33.0
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Driver URL: https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-win64.zip
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Driver path: C:\Users\mchea\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Browser path: C:\Program Files\Mozilla Firefox\firefox.exe
2023-08-27 22:12:25 DEBUG Selenium [:driver_service] Executing Process ["C:\\Users\\mchea\\.cache\\selenium\\geckodriver\\win64\\0.33.0\\geckodriver.exe", "--port=4444"]
2023-08-27 22:12:25 DEBUG Selenium [:process] Starting process: ["C:\\Users\\mchea\\.cache\\selenium\\geckodriver\\win64\\0.33.0\\geckodriver.exe", "--port=4444"] with {[:out, :err]=>#<IO:<STDOUT>>}
/home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/child_process.rb:57:in `spawn': No such file or directory - C:\Users\mchea\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe (Errno::ENOENT)
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/child_process.rb:57:in `start'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service_manager.rb:104:in `start_process'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/socket_lock.rb:42:in `locked'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service_manager.rb:55:in `start'
        from <internal:kernel>:90:in `tap'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/service.rb:92:in `launch'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:334:in `service_url'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/local_driver.rb:28:in `initialize_local_driver'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/firefox/driver.rb:42:in `initialize'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `new'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:53:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver.rb:88:in `for'
        from /home/mcheav/.gem/ruby/3.2.0/gems/watir-7.3.0/lib/watir/browser.rb:46:in `initialize'

**Comment by titusfortner** [comment]
@bonigarcia do you think this is related to #12612 ?

**Comment by bonigarcia** [comment]
It seems everything is correct in the last logs:

```
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Driver path: C:\Users\mchea.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Browser path: C:\Program Files\Mozilla Firefox\firefox.exe
```

**Comment by titusfortner** [comment]
Right, but then we get this error:
```
No such file or directory - C:\Users\mchea\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
```

**Comment by bonigarcia** [comment]
I suppose the problem happens because the filesystem in Cygwin (`C:\Users\mchea\`) is not the same as the host (`/home/mcheav`):

```
2023-08-27 22:12:25 DEBUG Selenium [:selenium_manager] Driver path: C:\Users\mchea\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
```

```
from /home/mcheav/.gem/ruby/3.2.0/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/child_process.rb:57
```

But that mapping is not the responsibility of Selenium, I'm afraid.

**Comment by titusfortner** [comment]
@p0deje if Ruby is passing this to child process, shouldn't it figure it out? 
```
C:\Users\mchea\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
```

**Comment by p0deje** [comment]
@titusfortner Probably we need to be checking for the environment and then translating the path accordingly.

**Comment by titusfortner** [comment]
@p0deje I guess I'm not sure how to take what SM is returning to us and convert it to where the system wants to see it?

**Comment by p0deje** [comment]
@titusfortner I think we can just check if it's `Platform.cygwin?` and then use `Platform.cygiwn_path` to preform the conversion?

https://github.com/SeleniumHQ/selenium/blob/8640ea8ae5731639e22272e6989648aff2c98e16/rb/lib/selenium/webdriver/common/platform.rb#L110-L115

**Comment by diemol** [comment]
Is there something to do in this issue or did we fix it already?

**Comment by p0deje** [comment]
@titusfortner I don't see this implemented anywhere in the code, do you want to do it yourself or want me to try it out?

**Comment by titusfortner** [comment]
Oh, I got distracted, running tests on a fix locally now.
