### ISSUE TITLE
Cannot launch ChromeDriver[🐛 Bug]: 

### ISSUE THREAD

**Issue by gidigal** [SeleniumHQ/selenium#12617]
### What happened?

I got an error saying that my selenium version is 114 while chrome version is 116. I installed new version for selenium (4.11) and chrome driver 116 win64. I still got errors. According to an advice I read, I searched for chromedriver and deleted it from under C:\Users\Gidi\.cache\selenium. Still got errors.

I see in the log attached below this line (log was produced using SeleniumLogger):
2023-08-26 22:16:58 FINE - chromedriver not found in PATH
I don't see an executable named chromedriver in the files I downloaded.
I will be grateful for help.

### How can we reproduce the issue?

```shell
Have Chrome 114 installed with selenium 4.9. Now, update Chrome and see the erorr about version differences. Now, update selenium to 4.11 and download chrome driver 116, and delete chromedriver.exe from .cache folder. Try to launch again. I also tried to delete my project and start a new one.
```

### Relevant log output

```shell
2023-08-26 22:16:35 FINE - Selenium Manager binary found at: C:\Users\Gidi\AppData\Local\Temp\selenium-manager148523699687006136012390874952462\selenium-manager.exe 
2023-08-26 22:16:35 FINE - Executing Process: [C:\Users\Gidi\AppData\Local\Temp\selenium-manager148523699687006136012390874952462\selenium-manager.exe, --browser, chrome, --output, json, --debug] 
2023-08-26 22:16:58 FINE - Checking chromedriver in PATH 
2023-08-26 22:16:58 FINE - Running command: chromedriver --version 
2023-08-26 22:16:58 FINE - Output: "" 
2023-08-26 22:16:58 FINE - chromedriver not found in PATH 
2023-08-26 22:16:58 FINE - chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe 
2023-08-26 22:16:58 FINE - Using shell command to find out chrome version 
2023-08-26 22:16:58 FINE - Running command: wmic datafile where name='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' get Version /value 
2023-08-26 22:16:58 FINE - Output: "\r\r\n\r\r\nVersion=116.0.5845.111\r\r\n\r\r\n\r\r\n\r" 
2023-08-26 22:16:58 FINE - Detected browser: chrome 116.0.5845.111 
2023-08-26 22:16:58 FINE - Required driver: chromedriver 116.0.5845.96 
2023-08-26 22:16:58 FINE - Reading metadata from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json 
2023-08-26 22:16:58 FINE - Driver URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win64/chromedriver-win64.zip 
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}, error Command failed with code: 65, executed: [C:\Users\Gidi\AppData\Local\Temp\selenium-manager148523699687006136012390874952462\selenium-manager.exe, --browser, chrome, --output, json, --debug]
error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win64/chromedriver-win64.zip): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:51)
	at Main.main(Main.java:13)
Caused by: org.openqa.selenium.WebDriverException: Command failed with code: 65, executed: [C:\Users\Gidi\AppData\Local\Temp\selenium-manager148523699687006136012390874952462\selenium-manager.exe, --browser, chrome, --output, json, --debug]
error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win64/chromedriver-win64.zip): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:151)
	at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:273)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)
	... 6 more

Process finished with exit code 1
```

### Operating System

Windows 10 64 bit

### Selenium version

Java Selenium 4.11

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116

**Comment by kaurmanjot90** [comment]
I am also getting the same issue with - System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4', java.version: '17.0.7'

**Comment by titusfortner** [comment]
This means there is a network issue get information from the internet:
> error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time,

Most likely the computer is behind a proxy that filters what is allowed to be accessed. Selenium supports setting proxy information for the driver by Options class, environment variable or configuration file.

**Comment by titusfortner** [comment]
@kaurmanjot90 double check that you have Rosetta installed. It won't be necessary in 4.12, but is in 4.11

**Comment by domoncassiu** [comment]
double check your chrome driver version, or trying using the chrome driver manager for driver installation
`driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))`

**Comment by titusfortner** [comment]
We do not recommend using webdriver manager (the project where `ChromeDriverManager` comes from) with the latest versions of Selenium.

**Comment by gidigal** [comment]
@titusfortner below is a screenshot of my LAN settings:
![image](https://github.com/SeleniumHQ/selenium/assets/16175918/73db9bba-5202-4c1c-b040-070be7236bb7)
I understand that it means that I don't use proxy server. I did not need to set Options class in my previous work with 4.9.
Is there a link to guide me what needs be set ? Thanks.

**Comment by kaurmanjot90** [comment]
> @kaurmanjot90 double check that you have Rosetta installed. It won't be necessary in 4.12, but is in 4.11

Thank you plenty! This helped to resolve my issue, able to execute.

**Comment by titusfortner** [comment]
@gidigal yes, we've made a bunch of changes since 4.10.

Selenium is saying it can't access https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win64/chromedriver-win64.zip

Can you access that link from your browser?
Can you access it from command line using curl or wget?

Is this a work computer? Might your IT be limiting what can be downloaded?

**Comment by gidigal** [comment]
@titusfortner I am unable to access this path. When I needed to download this chrome driver version, I did it through my cell phone, because of this issue. I tried contacting my internet provider to understand if they are able to download it. I understood they are able to access it. I tried adding https://edgedl.me.gvt1.com to the approved list of sites in my antivirus program. It did not help. I don't understand why selenium tries to download it, while I have a local version and I added its path to PATH varible.
This is my home computer.

**Comment by titusfortner** [comment]
Huh, that's weird that you can't access it.

Selenium wants to make it so that you don't have to manually update drivers any more. That means Selenium figures out what you should be using and gets it for you.

If you want to avoid that, you need to manually download it and put it in a directory on PATH. Looking at the logs, Selenium doesn't detect anything on PATH. So, sounds like you'll need to update that.

```
2023-08-26 22:16:58 FINE - Running command: chromedriver --version 
2023-08-26 22:16:58 FINE - Output: "" 
2023-08-26 22:16:58 FINE - chromedriver not found in PATH 
```

**Comment by gidigal** [comment]
@titusfortner , I look on my download of chrome-win64.zip and I see there is no chromedriver.exe in it (I think it is 116.0.5845.96 version, according to the name of the manifest file). Below are the exe files in it:
chrome.exe
chrome_proxy.exe
chrome_pwa_launcher.exe
elevation_service.exe
notification_helper.exe

So, the question is why would selenium search for chromedriver ? I did not set property "webdriver.chrome.driver". Is there something else I should delete in my temp files ?
Thanks,
Gidi

**Comment by titusfortner** [comment]
You need a driver to use selenium. If selenium can't access the location online to get the driver automatically, you have to install it manually and put it in a directory on PATH.

**Comment by sakshi4219** [comment]
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}, error Command failed with code: 65, executed: [--browser, chrome, --output, json]
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: dns error: No such host is known. (os error 11001)
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.2'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)

**Comment by sakshi4219** [comment]
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:51)
	at firstscript.main(firstscript.java:7)

**Comment by gidigal** [comment]
I found the reason for my error. [The the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/) has both downloads for chrome and chromddriver. I mistakenly downloaded chrome. Once I downloaded chromedriver the issue was resolved. @titusfortner, thank you for your help :-)

**Comment by GitAmi55** [comment]
Any solution for this error - error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: dns error: No such host is known. (os error 11001) ?

**Comment by titusfortner** [comment]
https://www.selenium.dev/documentation/selenium_manager/#connectivity-issues
