### ISSUE TITLE
[🐛 Bug]: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

### ISSUE THREAD

**Issue by GANGHSUN** [SeleniumHQ/selenium#12625]
### What happened?

I try [quotes-js-project ](https://github.com/python-scrapy-playbook/quotes-js-project) with Firefox.geckodriver, no any code modification, but always post error: TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

I switch to ChromeDriver and learn from previous issue downgrade selenium to 4.9 is works 

I suppose the firefox , geckodriver version mismatch with selenium, but don't know how to fix it. 

### How can we reproduce the issue?

```shell
https://github.com/python-scrapy-playbook/quotes-js-project
```

### Relevant log output

```shell
scrapy crawl quotes -o result.json
2023-08-29 18:47:06 [scrapy.utils.log] INFO: Scrapy 2.10.0 started (bot: quotes_js_scraper)
2023-08-29 18:47:06 [scrapy.utils.log] INFO: Versions: lxml 4.9.3.0, libxml2 2.10.3, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 22.10.0, Python 3.10.12 (main, Jul  5 2023, 18:45:42) [GCC 11.2.0], pyOpenSSL 23.2.0 (OpenSSL 3.1.2 1 Aug 2023), cryptography 41.0.3, Platform Linux-6.2.0-26-generic-aarch64-with-glibc2.35
2023-08-29 18:47:06 [scrapy.addons] INFO: Enabled addons:
[]
2023-08-29 18:47:06 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'quotes_js_scraper',
 'NEWSPIDER_MODULE': 'quotes_js_scraper.spiders',
 'SPIDER_MODULES': ['quotes_js_scraper.spiders']}
2023-08-29 18:47:06 [py.warnings] WARNING: /home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/utils/request.py:248: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2023-08-29 18:47:06 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2023-08-29 18:47:06 [scrapy.extensions.telnet] INFO: Telnet Password: 5a8772b9605781b8
2023-08-29 18:47:06 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
Unhandled error in Deferred:
2023-08-29 18:47:06 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 245, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 249, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1947, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1857, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 134, in crawl
    self.engine = self._create_engine()
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 148, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/core/engine.py", line 98, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/core/downloader/__init__.py", line 97, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 67, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 44, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/utils/misc.py", line 188, in create_instance
    instance = objcls.from_crawler(crawler, *args, **kwargs)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy_selenium/middlewares.py", line 67, in from_crawler
    middleware = cls(
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy_selenium/middlewares.py", line 51, in __init__
    self.driver = driver_klass(**driver_kwargs)
builtins.TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

2023-08-29 18:47:06 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 134, in crawl
    self.engine = self._create_engine()
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/crawler.py", line 148, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/core/engine.py", line 98, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/core/downloader/__init__.py", line 97, in __init__
    DownloaderMiddlewareManager.from_crawler(crawler)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 67, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/middleware.py", line 44, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy/utils/misc.py", line 188, in create_instance
    instance = objcls.from_crawler(crawler, *args, **kwargs)
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy_selenium/middlewares.py", line 67, in from_crawler
    middleware = cls(
  File "/home/gareth/Downloads/venv/lib/python3.10/site-packages/scrapy_selenium/middlewares.py", line 51, in __init__
    self.driver = driver_klass(**driver_kwargs)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
```

### Operating System

Ubuntu 22.04.3 LTS (Jammy Jellyfish) ARM64

### Selenium version

Selenium 4.10.0, 4.11.2

### What are the browser(s) and version(s) where you see this issue?

Mozilla Firefox 115.0.2

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.33.0 ( 2023-07-11)

**Comment by diemol** [comment]
Please reach out to them asking to upgrade Selenium. The error seems to be raised in their internal code. If they need help, I will leave some links below you can share.

**Comment by titusfortner** [comment]
Yes, we moved that parameter to Service class. Here is how you do it now:
https://www.selenium.dev/documentation/webdriver/drivers/service/#driver-location
