### ISSUE TITLE
[🐛 Bug]: Selenium Manager 4.11.2 not finding or auto-downloading the Web Driver

### ISSUE THREAD

**Issue by altoorodevelead** [SeleniumHQ/selenium#12627]
### What happened?

Hello,
I'm trying to run Selenium 4.11 and to use the Selenium Manager to auto download the browser/driver.
This is the code:
```py
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("https://www.google.com")
```
But i'm getting the usual:
```
Unable to obtain driver for chrome using Selenium Manager...
```
- I do have Chrome installed
- I also have Chrome for Testing installed
- I'm running Selenium on a Mac using PyCharm
If I download ChromeDriver manually, and then add it to the bin(so that it is in the PATH), and then use the path in the code, it works.
How do you suggest fixing this issue?
Thank you for any assistance that you can provide.

### How can we reproduce the issue?

```shell
Not 100% sure if it is reproducible or an isolated issue, because I tried the suggested solution found on GitHub, but it did not work.

- Python version 3.11.2
- PyCharm on Mac
- macOS Monterey 12.6.3
```

### Relevant log output

```shell
service = <selenium.webdriver.chrome.service.Service object at 0x105e33590>
options = <selenium.webdriver.chrome.options.Options object at 0x105e33550>

    @staticmethod
    def get_path(service: Service, options: BaseOptions) -> str:
        path = service.path
        try:
            path = SeleniumManager().driver_location(options) if path is None else path
        except Exception as err:
            msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
>           raise NoSuchDriverException(msg) from err
E           selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py:41: NoSuchDriverException
```

### Operating System

macOS Monterey

### Selenium version

Python 4.11.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 116

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Can you turn on logging and post results — https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by altoorodevelead** [comment]
> Can you turn on logging and post results — https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

Thank you for the reply.
I will make sure to do so and update you.

**Comment by matt-riemer** [comment]
Hello my friends :)

My ruby on rails CircleCI builds have begun to fail today, Aug 29th 2023

![CleanShot 2023-08-29 at 16 48 57](https://github.com/SeleniumHQ/selenium/assets/954468/136ac5b6-7e21-4b73-80cd-3a91365021cd)

Maybe related?

Thanks

**Comment by diemol** [comment]
Your issue looks different. Starting from ChromeDriver 115 the download url has changed.

https://googlechromelabs.github.io/chrome-for-testing/

**Comment by altoorodevelead** [comment]
We turned on the logging, but not much extra was logged, an output was put in a file:
```
Selenium Manager binary found at: /Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager
Executing process: /Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --debug --output json
```
- We are using PyTest as well

**Comment by titusfortner** [comment]
Pytest makes it incredibly difficult to actually see the logs.

Can you execute that last line manually in Terminal?

**Comment by altoorodevelead** [comment]
Here you go:
```
Traceback (most recent call last):
  File "/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 126, in run
    output = json.loads(stdout)
             ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 90, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 129, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

**Comment by titusfortner** [comment]
Execute this in the command line so we don't have to deal with PyTest getting in the way of the info:
```
/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --debug --output json
```

**Comment by altoorodevelead** [comment]
So super weird thing just happened, I opened a new terminal window, ran the command and got a "Permission denied" sort of message.

Then, ran the same command with `sudo` prefixed, a JSON was outputted with a list of drivers:
```json
{
  "logs": [
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Checking chromedriver in PATH"
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Running command: chromedriver --version"
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Output: \"ChromeDriver 116.0.5845.96 (1a391816688002153ef791ffe60d9e899a71a037-refs/branch-heads/5845@{#1382})\""
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Running command: which chromedriver"
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Output: \"/usr/local/bin/chromedriver\""
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Found chromedriver 116.0.5845.96 in PATH: /usr/local/bin/chromedriver"
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "chrome detected at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Using shell command to find out chrome version"
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Running command: /Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --version"
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Output: \"Google Chrome 116.0.5845.110 \""
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Detected browser: chrome 116.0.5845.110"
    },
    {
      "level": "DEBUG",
      "timestamp": 1693403830,
      "message": "Required driver: chromedriver 116.0.5845.96"
    },
    {
      "level": "INFO",
      "timestamp": 1693403830,
      "message": "Driver path: /usr/local/bin/chromedriver"
    },
    {
      "level": "INFO",
      "timestamp": 1693403830,
      "message": "Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    }
  ],
  "result": {
    "code": 0,
    "message": "/usr/local/bin/chromedriver",
    "driver_path": "/usr/local/bin/chromedriver",
    "browser_path": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  }
}
```
I assumed that this meant that the `SeleniumManager` should work, so I executed this code once more:
```py
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("https://www.google.com")
```
And it worked flawlessly, the browser opened and everything!

Thinking that the permission might reset if I restart the laptop, I did so, but no, running the same command without sudo this time it kept working, and the Python code now runs normally.

**Comment by altoorodevelead** [comment]
Update, the "permission issue" is back when calling:
```
/Users/julian/Desktop/Altooro/automation_tests/env/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --debug --output json
```
Here is the output:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/metadata.rs:164:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    5581 abort       --browser chrome --debug --output json
``` 
If we run with sudo it works, but only for a few hours.

**Comment by titusfortner** [comment]
Selenium can't fix permission issues on your computer. Elevate privileges of user or allow executing files in that directory to all users

We are going to put the driver in a specific location in 4.13 that might make it easier.

**Comment by chamodi179** [comment]
i am using the firefox 113 and i want to know weather the following code is correct or not.                                                                                                                                       

self.options = Options()self.options.add_argument('--ignore-certificate-errors')
self.options.add_argument('--ignore-ssl-errors')
self.profile = webdriver.FirefoxProfile()
        if os.environ.get('IS_SERVER') == "1":
            self.profile.set_preference("browser.cache.disk.enable", False)
            self.profile.set_preference("browser.cache.memory.enable", False)
            self.profile.set_preference("browser.cache.offline.enable", False)
            self.profile.set_preference("network.http.use-cache", False)
            # self.options.add_argument('--headless')
            self.options.headless = True

def my_driver(self):
           try:
                self.helper.check_connection()
                # self.tor_handler.renew_connection()
                options = FirefoxOptions()
                self.profile.update_preferences()
                firefox_driver = webdriver.Firefox(options=options)
                webdriver_wait = WebDriverWait(firefox_driver, 25, poll_frequency=1)
                firefox_driver.set_page_load_timeout(200)
                return True, firefox_driver, webdriver_wait
           except:
                traceback.print_exc()
                return False
