### ISSUE TITLE
[🐛 Bug]: Edge web driver couldn't correctly use `edge.options` under Linux

### ISSUE THREAD

**Issue by hi-i-m-GTooth** [SeleniumHQ/selenium#12636]
### What happened?

I would like to use Edge as my web driver. One thing I noticed is that Linux doesn't support GUI so I need to add `options.add_argument('--headless')` to prevent occurring bugs. 

However, when I used `options` package for Edge, things went wrong. Interestingly, I used `options` package for Chrome to solve this bug.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.edge.options import Options

options = Options()
options.add_argument('--headless')
driver = webdriver.Edge(options=options)

# To solve this problem, replace 2nd row with below codes:
from selenium.webdriver.chrome.options import Options
```

### Relevant log output

```shell
The version of edge cannot be detected. Trying with latest driver version
Traceback (most recent call last):
  File "/mldrive1/andersonliu/git/edb-sourcecode-spider/test_sqler_se.py", line 148, in <module>
    driver = webdriver.Edge(options=options)
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/edge/webdriver.py", line 45, in __init__
    super().__init__(
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find msedge binary
Stacktrace:
#0 0x55689d867793 <unknown>
#1 0x55689d56acf1 <unknown>
#2 0x55689d596ed0 <unknown>
#3 0x55689d594500 <unknown>
#4 0x55689d5d7305 <unknown>
#5 0x55689d5ce343 <unknown>
#6 0x55689d5a03c1 <unknown>
#7 0x55689d5a15de <unknown>
#8 0x55689d835836 <unknown>
#9 0x55689d83871d <unknown>
#10 0x55689d838209 <unknown>
#11 0x55689d838be5 <unknown>
#12 0x55689d83fd6b <unknown>
#13 0x55689d838f93 <unknown>
#14 0x55689d815a25 <unknown>
#15 0x55689d853678 <unknown>
#16 0x55689d8537ff <unknown>
#17 0x55689d860fb6 <unknown>
#18 0x7fd89a894b43 <unknown>
```

### Operating System

Ubuntu 22.04.3 LTS

### Selenium version

Python 3.10, Selenium 4.11.2

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge

### What are the browser driver(s) and version(s) where you see this issue?

edgedriver_linux64 ver=116.0.1938.62

**Comment by titusfortner** [comment]
Do you have Edge installed? Is it installed in the "normal" place? The error is saying that Selenium doesn't see it in the place it expects to see it. You can set the `binary_location` property on edge options instance to make sure it gets used properly.

Other notes:
* you can also use this as a shortcut: `options = webdriver.EdgeOptions()`
* prefer `--headless=new` to just `--headless`

**Comment by hi-i-m-GTooth** [comment]
> Do you have Edge installed? Is it installed in the "normal" place? The error is saying that Selenium doesn't see it in the place it expects to see it. You can set the `binary_location` property on edge options instance to make sure it gets used properly.
> 
> Other notes:
> 
> * you can also use this as a shortcut: `options = webdriver.EdgeOptions()`
> * prefer `--headless=new` to just `--headless`

Hi, @titusfortner ! Thanks for the reply! In fact, I've tried this method _(This is the first method I tried when I met this bug message XD)_.  
I am sorry that the result was not attached. I will reproduce it below.

## `binary_location`
Let's say I placed the driver binary under `./driver` and named it as `msedgedriver_linux`. So, the path of binary should be `./driver/msedgedriver_linux`.  

Hence, I add `options.binary_location = "./driver/msedgedriver_linux"` into my program. Note that I used `Options` for edge here.

After executing the program, I met below bug message: 
``` bash
Traceback (most recent call last):
  File "/mldrive1/andersonliu/git/edb-sourcecode-spider/test_sqler_se.py", line 149, in <module>
    driver = webdriver.Edge(options=options)
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/edge/webdriver.py", line 45, in __init__
    super().__init__(
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: msedge failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location ./driver/msedgedriver_linux is no longer running, so msedgedriver is assuming that msedge has crashed.)
Stacktrace:
#0 0x55e3483e6793 <unknown>
#1 0x55e3480e9cf1 <unknown>
#2 0x55e34811801a <unknown>
#3 0x55e348113500 <unknown>
#4 0x55e348156305 <unknown>
#5 0x55e34814d343 <unknown>
#6 0x55e34811f3c1 <unknown>
#7 0x55e3481205de <unknown>
#8 0x55e3483b4836 <unknown>
#9 0x55e3483b771d <unknown>
#10 0x55e3483b7209 <unknown>
#11 0x55e3483b7be5 <unknown>
#12 0x55e3483bed6b <unknown>
#13 0x55e3483b7f93 <unknown>
#14 0x55e348394a25 <unknown>
#15 0x55e3483d2678 <unknown>
#16 0x55e3483d27ff <unknown>
#17 0x55e3483dffb6 <unknown>
#18 0x7f4984e94b43 <unknown>
```

This message really confused me. The reason is: the message tells me that the driver exited abnormally, however, when I execute driver directly by terminal, it works normal:
```
Starting Microsoft Edge WebDriver 116.0.1938.62 (493f2197e519d4dde5309fdf4abf4f719089372d) on port 9515
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
```

## Change to Chrome driver
After meeting this bug, I tried to change the driver type. I still preserved the `options.binary_location = "PATH_TO_CHROME_DRIVER"`. Then I got aother error message:
```
Traceback (most recent call last):
  File "/mldrive1/andersonliu/git/edb-sourcecode-spider/test_sqler_se.py", line 149, in <module>
    driver = webdriver.Chrome(options=options)
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/mldrive1/andersonliu/conda3/envs/crawl/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location ./driver/chromedriver_linux is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56145a11e133 <unknown>
#1 0x561459e52966 <unknown>
#2 0x561459e7c21a <unknown>
#3 0x561459e7807b <unknown>
#4 0x561459eb79ad <unknown>
#5 0x561459eb718f <unknown>
#6 0x561459eae9a3 <unknown>
#7 0x561459e8346a <unknown>
#8 0x561459e8455e <unknown>
#9 0x56145a0ddcae <unknown>
#10 0x56145a0e18fe <unknown>
#11 0x56145a0eaf20 <unknown>
#12 0x56145a0e2923 <unknown>
#13 0x56145a0b5c0e <unknown>
#14 0x56145a105b08 <unknown>
#15 0x56145a105c97 <unknown>
#16 0x56145a116113 <unknown>
#17 0x7f71c2294b43 <unknown>
```
I also followed this [stackoverflow post](https://stackoverflow.com/questions/56637973/how-to-fix-selenium-devtoolsactiveport-file-doesnt-exist-exception-in-python), I tried to add the argument `options.add_argument("--remote-debugging-port=9222")`. Then the error message returned to the same one.

I also tried `options.add_argument('--no-sandbox')` and `options.add_argument("--disable-dev-shm-usage")`, but they didn't help.

That's all error messages I've met so far.

**Comment by titusfortner** [comment]
Devtools active port is a known bug that is supposed to be fixed in chromedriver 117.

The binary location property is to help find the browser, not the driver. selenium can't find the edge browser. It'll handle the driver as necessary.

**Comment by mucsi96** [comment]
@titusfortner  

> Devtools active port is a known bug that is supposed to be fixed in chromedriver 117.

Can you please give some reference to a bug so me can track it?

**Comment by titusfortner** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403&q=DevToolsActivePort&can=1&sort=-id

**Comment by hi-i-m-GTooth** [comment]
Thanks for all the help!

**Comment by titusfortner** [comment]
"DevToolsActivePort not found" bug fix: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35
