### ISSUE TITLE
[🐛 Bug]: RemoteWebDriver.builder() doesn't work on selenium grid (hub/node)(2 machines)

### ISSUE THREAD

**Issue by zoran1987** [SeleniumHQ/selenium#12646]
### What happened?

"RemoteWebDriver.builder()" doesn't work properly if you run it on different machines(hub/node) 
- opens empty browsers on the node but returns error in Intelij (Unable to establish websocket connection)

"new RemoteWebDriver" works fine with the same ChromeOptions, but I need to add ClientConfig also

### How can we reproduce the issue?

```shell
ChromeOptions options = new ChromeOptions();
                options.addArguments("--window-size=1940,1050");
                options.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
                options.addArguments("chrome.switches", "-disable-extensions");
                DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
                desiredCapabilities.setPlatform(Platform.ANY);
                options.merge(desiredCapabilities);
                options.setCapability("se:downloadsEnabled", true);
                options.setCapability(ChromeOptions.LOGGING_PREFS, logs);
                Map<String, Object> prefs = new HashMap<>();
                prefs.put("credentials_enable_service", false);
                prefs.put("profile.password_manager_enabled", false);
                prefs.put("profile.content_settings.exceptions.clipboard", getClipBoardSettingsMap(1));
                options.setExperimentalOption("prefs", prefs);
                options.setPageLoadStrategy(PageLoadStrategy.NONE);
                options.addArguments("--remote-allow-origins=*");

1. case (doesn't work)
RemoteWebDriver.builder().address(new URL(sBase + ":4444/wd/hub"))
                            .oneOf(options)
                            .build()

2. case (works fine)
new RemoteWebDriver(new URL(sBase + ":4444/wd/hub"), options); 


start hub:
java -jar selenium-server-4.11.0.jar hub --session-request-timeout 28800

start node:
java -jar selenium-server-4.11.0.jar node --selenium-manager true --session-timeout 1200 --enable-managed-downloads true --publish-events <hubip:4442> --subscribe-events <hubip:4443>
```

### Relevant log output

```shell
org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://192.168.1.178:4444/session/108cccae30945927c965ba823a2b9ec0/se/cdp
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: driver.version: unknown

	at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:116)
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:147)
	at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:104)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:83)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:36)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$3(SeleniumCdpConnection.java:103)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:103)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:49)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:49)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:29)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:191)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:162)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.build(RemoteWebDriverBuilder.java:371)
	at tests.SetDriverNonStatic.setDriver(SetDriverNonStatic.java:99)
	at tests.SetDriverNonStatic.<init>(SetDriverNonStatic.java:33)
	at tests.Test2.Test2_Test(Test2.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Operating System

Windows 10

### Selenium version

4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 116.0.5845.141

### What are the browser driver(s) and version(s) where you see this issue?

selenium-manager true

### Are you using Selenium Grid?

4.11.0

**Comment by diemol** [comment]
You need to configure the [`--grid-url`](https://www.selenium.dev/documentation/grid/configuration/cli_options/#node).
