### ISSUE TITLE
[🐛 Bug]: Run tests fails on Jenkins pipeline 

### ISSUE THREAD

**Issue by hizir-bc** [SeleniumHQ/selenium#12653]
### What happened?

Test run works on the local just fine, however when I attach them to the jenkins pipeline, it fails with the following error message

### How can we reproduce the issue?

I am using this command to execute the tests. 
```shell
extest get-vscode && extest get-chromedriver && npx tsc tests/ui-test/*.test.ts --skipLibCheck && extest run-tests tests/ui-test/*.test.js
```

### Relevant log output

```shell
*failed* | Writing code settings to /vscode/test-resources/settings/User/settings.json
*failed* | Launching browser...
*failed* |   1) "before all" hook in "{root}"
*failed* |   2) "after all" hook in "{root}"
*failed* |   0 passing (20ms)
*failed* |   2 failing
*failed* |   1) "before all" hook in "{root}":
*failed* |      Error: spawn /vscode/test-resources/chromedriver ENOENT
*failed* |       at /vscode/node_modules/selenium-webdriver/remote/index.js:260:24
*failed* |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
*failed* |   2) "after all" hook in "{root}":
*failed* |      TypeError: Cannot read properties of undefined (reading 'manage')
*failed* |       at VSBrowser.<anonymous> (node_modules/vscode-extension-tester/out/browser.js:152:48)
*failed* |       at Generator.next (<anonymous>)
*failed* |       at /vscode/node_modules/vscode-extension-tester/out/browser.js:31:71
*failed* |       at new Promise (<anonymous>)
*failed* |       at __awaiter (node_modules/vscode-extension-tester/out/browser.js:27:12)
*failed* |       at VSBrowser.quit (node_modules/vscode-extension-tester/out/browser.js:151:16)
*failed* |       at Context.<anonymous> (node_modules/vscode-extension-tester/out/suite/runner.js:108:35)
*failed* |       at Generator.next (<anonymous>)
*failed* |       at /vscode/node_modules/vscode-extension-tester/out/suite/runner.js:31:71
*failed* |       at new Promise (<anonymous>)
*failed* |       at __awaiter (node_modules/vscode-extension-tester/out/suite/runner.js:27:12)
*failed* |       at Context.<anonymous> (node_modules/vscode-extension-tester/out/suite/runner.js:106:24)
```

### Operating System

Linux 5.15.107

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver - 108.0.5359.71 || vscode-extension-tester - 5.9.1

**Comment by hizir-bc** [comment]
all information is provided

**Comment by diemol** [comment]
The only error your logs show is `TypeError: Cannot read properties of undefined (reading 'manage')`, and that is not related to Selenium. 

If you need help, you should come to our chat and the community can give you a hand.

**Comment by hizir-bc** [comment]
Hi Diego, we also have this chrome diver error `Error: spawn /vscode/test-resources/chromedriver ENOENT`
That would be awesome, I will try chat to find out what wrong
