### ISSUE TITLE
[🐛 Bug]: unnecessary console.debug messages in seleniumManager.js

### ISSUE THREAD

**Issue by dtopuzov** [SeleniumHQ/selenium#12676]
### What happened?

Too many `console.debug` messages are printed when running tests.

I think it will be better if by default only warning/error messages are logged.

Some options to control the log level of NodeJS binding can be also useful.

### How can we reproduce the issue?

```shell
Create a simple project with NodeJS bindings and run the tests.
```

### Relevant log output

```shell
> npx jest tests/e2e

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Selenium Manager binary found at /Users/topuzov/git/kendo-e2e/node_modules/selenium-webdriver/bin/macos/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Driver path: /Users/topuzov/.cache/selenium/chromedriver/mac-x64/116.0.5845.96/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  console.debug
    Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

 PASS  tests/e2e/browser/screenshot.tests.ts
  ✓ should be able screenshot viewport (1871 ms)

 PASS  tests/e2e/components/grid.tests.ts
  ✓ should render cells (1918 ms)
  ✓ should render headers (233 ms)
  ✓ should be sorted (205 ms)
```

### Operating System

All

### Selenium version

4.12.0

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

All

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Default logging for JS is supposed to be `OFF`. https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by diemol** [comment]
I thought the same, @harsha509 do you know?

**Comment by dtopuzov** [comment]
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/ looks to be for selenium commands only.

I am talking about verbose logs from Selenium Manager and I am not sure the logging options above have any impact on this:
https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/common/seleniumManager.js#L57

**Comment by 1RandomDev** [comment]
Having the same problem it seems like those 3 debug messages are hardcoded and are not affected by the configured log level. Really annoying if you want to use the output of your script in are bash script or something similar.

```
Selenium Manager binary found at ...
Driver path: ...
Browser path: ...
```

Edit: For now the problem can be solved by setting console.debug to an empty function before creating the selenium object.

**Comment by titusfortner** [comment]
Yes, the Logging solution we have in JS is not ideal. If anyone has time to help us clean it up, it would be greatly appreciated.

**Comment by danielrozenberg** [comment]
I took a stab at fixing this issue (and other similar ones) with #12909
