### ISSUE TITLE
[🐛 Bug]: Session not created when se:downloadsEnabled capability

### ISSUE THREAD

**Issue by baflQA** [SeleniumHQ/selenium#12695]
### What happened?

I run the selenium standalone grid on docker: https://github.com/baflQA/selenium-debug/blob/main/runGridStandalone.sh
I the config file, I enable `enable-managed-downloads = true`.
In the new session payload, I add the `"se:downloadsEnabled", true` capability. 
When I create a new session, the new node container is created, but the session creation request fails with a timeout error. 
When the capability is not present, the session is created successfully.

### How can we reproduce the issue?

```shell
Run grid with https://github.com/baflQA/selenium-debug/blob/main/runGridStandalone.sh
and then run https://github.com/baflQA/selenium-debug/blob/main/src/test/java/seleniumdebug/ManagedDownloadsSessionTest.java
```

### Relevant log output

```shell
2023-09-06 11:42:25 org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. New session request timed out 
2023-09-06 11:42:25 Host info: host: '7b7c8880a9cf', ip: '172.18.0.3'
2023-09-06 11:42:25 Build info: version: '4.12.1', revision: '8e34639b11'
2023-09-06 11:42:25 System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.20.1'
2023-09-06 11:42:25 Driver info: driver.version: unknown
2023-09-06 11:42:25 Build info: version: '4.12.1', revision: '8e34639b11'
2023-09-06 11:42:25 System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit-pr', java.version: '11.0.20.1'
2023-09-06 11:42:25 Driver info: driver.version: unknown
2023-09-06 11:42:25     at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
2023-09-06 11:42:25     at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
2023-09-06 11:42:25     at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
2023-09-06 11:42:25     at org.openqa.selenium.grid.node.docker.DockerSessionFactory.apply(DockerSessionFactory.java:206)
2023-09-06 11:42:25     at org.openqa.selenium.grid.node.docker.DockerSessionFactory.apply(DockerSessionFactory.java:88)
2023-09-06 11:42:25     at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
2023-09-06 11:42:25     at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:468)
2023-09-06 11:42:25     at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:648)
2023-09-06 11:42:25     at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:565)
2023-09-06 11:42:25     at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:829)
2023-09-06 11:42:25     at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:785)
2023-09-06 11:42:25     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-09-06 11:42:25     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-09-06 11:42:25     at java.base/java.lang.Thread.run(Thread.java:829)
```

### Operating System

macOS

### Selenium version

4.12.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 116

### Are you using Selenium Grid?

4.12

**Comment by karanjeetbirdeye** [comment]
I have faced the same issue, although it is not persistent but 3 out of 10 times it is there.

**Comment by krmahadevan** [comment]
@baflQA - If you apply the below patch to your repo, your test class should work

```diff
diff --git a/runGridStandalone.sh b/runGridStandalone.sh
old mode 100644
new mode 100755
index 350d52e..2a221dd
--- a/runGridStandalone.sh
+++ b/runGridStandalone.sh
@@ -3,7 +3,7 @@
 docker stop selenium-standalone
 docker rm selenium-standalone
 
-IMAGE_VERSION='4.15'
+IMAGE_VERSION='4.15.0'
 cat <<EOF >config.toml
 [docker]
 configs = [
@@ -12,7 +12,7 @@ configs = [
 ]
 url = "http://127.0.0.1:2375"
 [logging]
-log-level = FINE
+log-level = INFO
 [node]
 drivers = ["chrome", "firefox"]
 max-sessions = 4
@@ -35,6 +35,7 @@ docker run -d -p 4444:4444 --shm-size="2g" \
   -e SE_SCREEN_WIDTH=1920 \
   -e SE_SCREEN_HEIGHT=1080 \
   -e SE_VNC_NO_PASSWORD=1 \
+  -e SE_OPTS='--enable-managed-downloads true' \
   -e SE_START_VNC=true \
   -v "${PWD}"/config.toml:/opt/bin/config.toml \
   -v "${PWD}"/assets:/opt/selenium/assets \
```

Analysis:

* I think by default the standalone image always ends up generating the configuration ( see [here](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Standalone/start-selenium-standalone.sh#L14) ) which means it keeps overwriting your configuration that you are trying to create/mount
* Since the standalone ends up getting a new session request which needs selenium to manage downloads automatically, it ends up rejecting the new session (because we didn't start it with the `--enable-managed-downloads true` flag) but that error is not perhaps getting translated properly. See below for the logs
* The fix is to add `SE_OPTS='--enable-managed-downloads true' ` when you start the container using `docker run selenium/standalone-docker:4.15.0` command


```shell
2023-11-02 18:48:36 Driver info: driver.version: unknown 
2023-11-02 18:48:36 Host info: host: 'a8d6a037b76c', ip: '192.168.48.2'
2023-11-02 18:48:36 Build info: version: '4.15.0', revision: '1d14b5521b'
2023-11-02 18:48:36 System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.4.16-linuxkit', java.version: '11.0.20.1'
2023-11-02 18:48:36 Driver info: driver.version: unknown
2023-11-02 18:48:36 13:18:36.225 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to create session: java.util.concurrent.TimeoutException
2023-11-02 18:48:36 Build info: version: '4.15.0', revision: '1d14b5521b'
2023-11-02 18:48:36 System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.4.16-linuxkit', java.version: '11.0.20.1'
2023-11-02 18:48:36 Driver info: driver.version: unknown 
2023-11-02 18:48:36 Host info: host: 'a8d6a037b76c', ip: '192.168.48.2'
2023-11-02 18:48:36 Build info: version: '4.15.0', revision: '1d14b5521b'
2023-11-02 18:48:36 System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.4.16-linuxkit', java.version: '11.0.20.1'
2023-11-02 18:48:36 Driver info: driver.version: unknown
2023-11-02 18:48:36     at org.openqa.selenium.grid.node.docker.DockerSessionFactory.apply(DockerSessionFactory.java:219)
2023-11-02 18:48:36     at org.openqa.selenium.grid.node.docker.DockerSessionFactory.apply(DockerSessionFactory.java:87)
2023-11-02 18:48:36     at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
2023-11-02 18:48:36     at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)
2023-11-02 18:48:36     at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)
2023-11-02 18:48:36     at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)
2023-11-02 18:48:36     at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)
2023-11-02 18:48:36     at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)
2023-11-02 18:48:36     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-11-02 18:48:36     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-11-02 18:48:36     at java.base/java.lang.Thread.run(Thread.java:829)
2023-11-02 18:48:36 
```

**Comment by krmahadevan** [comment]
@diemol - Do you think we can close this issue, based on the above analysis ?

**Comment by baflQA** [comment]
@krmahadevan thanks a lot! My tests are passing now after adjusting my script. 
I will close this issue with joy!
