### ISSUE TITLE
[🐛 Bug]: Deadlock in FluentWait

### ISSUE THREAD

**Issue by jramirezmorales** [SeleniumHQ/selenium#12693]
### What happened?

deadlock in FluentWait(explicitwait)

### How can we reproduce the issue?

```shell
possible duplicate for https://github.com/SeleniumHQ/selenium/issues/12576
```

### Relevant log output

```shell
I'm seeing this in selenium 4.12.1 with java17 macOS ventura 13.5
`"main" Id=1 TIMED_WAITING
	at java.base@17.0.3/java.lang.Thread.sleep(Native Method)
	at app//org.openqa.selenium.support.ui.Sleeper.lambda$static$0(Sleeper.java:25)
	at app//org.openqa.selenium.support.ui.Sleeper$$Lambda$408/0x0000000801024d68.sleep(Unknown Source)
	at app//org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:234)
	at app//com.squareup.myClass(MyClass.java:208)
	at app//com.squareup.myClassTest(MyClassTest.java:44)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at app//org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
	at app//com.squareup.someClass$1.evaluate(FlakyRule.java:54)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at app//org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at app//org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at app//org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
	at app//org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at app//com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at app//org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at app//org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at app//com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at app//com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:145)
	at app//com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76)

"Reference Handler" Id=2 RUNNABLE (daemon)
	at java.base@17.0.3/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@17.0.3/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
	at java.base@17.0.3/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@5c7d8f46 (daemon)
	at java.base@17.0.3/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@5c7d8f46
	at java.base@17.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@17.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.base@17.0.3/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)

"Signal Dispatcher" Id=4 RUNNABLE (daemon)

"Notification Thread" Id=11 RUNNABLE (daemon)

"Common-Cleaner" Id=12 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@3a5d1a57 (daemon)
	at java.base@17.0.3/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@3a5d1a57
	at java.base@17.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@17.0.3/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)
	at java.base@17.0.3/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)

"process reaper" Id=13 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@48c497a6 (daemon)
	at java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@48c497a6
	at java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.3/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
	at java.base@17.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

"Attach Listener" Id=14 RUNNABLE (daemon)

"ForkJoinPool.commonPool-worker-1" Id=16 TIMED_WAITING on java.util.concurrent.ForkJoinPool@473d8bba (daemon)
	at java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@473d8bba
	at java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410)
	at java.base@17.0.3/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726)
	at java.base@17.0.3/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
	at java.base@17.0.3/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"AsyncHttpClient-1-1" Id=17 TIMED_WAITING (daemon)
	at java.base@17.0.3/java.lang.Thread.sleep(Native Method)
	at app//io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:600)
	at app//io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:496)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

"Driver Service Executor" Id=22 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@770a3ba4 (daemon)
	at java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@770a3ba4
	at java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
	at java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
	at java.base@17.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	at java.base@17.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	at java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
	at java.base@17.0.3/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

"Driver Service Executor" Id=23 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@770a3ba4 (daemon)
	at java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@770a3ba4
	at java.base@17.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
	at java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
	at java.base@17.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	at java.base@17.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	at java.base@17.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
	at java.base@17.0.3/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

"UrlChecker-2" Id=24 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@255718b0 (daemon)
	at java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@255718b0
	at java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.3/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
	at java.base@17.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

"AsyncHttpClient-1-2" Id=26 RUNNABLE (in native) (daemon)
	at java.base@17.0.3/sun.nio.ch.EPoll.wait(Native Method)
	at java.base@17.0.3/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:118)
	at java.base@17.0.3/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@4942d21b
	-  locked sun.nio.ch.EPollSelectorImpl@6289f0d2
	at java.base@17.0.3/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:146)
	at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:879)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

"AsyncHttpClient-1-3" Id=27 RUNNABLE (daemon)
	at java.base@17.0.3/sun.nio.ch.EPoll.wait(Native Method)
	at java.base@17.0.3/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:118)
	at java.base@17.0.3/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@4478303c
	-  locked sun.nio.ch.EPollSelectorImpl@59f7329b
	at java.base@17.0.3/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:146)
	at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:879)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

"AsyncHttpClient-1-4" Id=28 RUNNABLE (daemon)
	at java.base@17.0.3/java.util.concurrent.ConcurrentLinkedQueue.clear(ConcurrentLinkedQueue.java:984)
	at app//org.asynchttpclient.netty.ws.NettyWebSocket.onClose(NettyWebSocket.java:264)
	at app//org.asynchttpclient.netty.handler.WebSocketHandler.handleChannelInactive(WebSocketHandler.java:162)
	at app//org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelInactive(AsyncHttpClientHandler.java:144)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at app//io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at app//io.netty.handler.codec.MessageAggregator.channelInactive(MessageAggregator.java:436)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at app//io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
	at app//io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at app//io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at app//io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)

"SIGTERM handler" Id=29 RUNNABLE (daemon)
	at java.management@17.0.3/sun.management.ThreadImpl.dumpThreads0(Native Method)
	at java.management@17.0.3/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
	at java.management@17.0.3/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
	at app//com.google.testing.junit.runner.internal.StackTraces.printAll(StackTraces.java:43)
	at app//com.google.testing.junit.runner.internal.junit4.JUnit4TestStackTraceListener$WriteStackTraceSignalHandler.handle(JUnit4TestStackTraceListener.java:52)
	at app//com.google.testing.junit.runner.internal.SignalHandlers$2.handle(SignalHandlers.java:62)
	at app//com.google.testing.junit.runner.internal.SignalHandlers$2.handle(SignalHandlers.java:65)
	at jdk.unsupported@17.0.3/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
	at java.base@17.0.3/jdk.internal.misc.Signal$1.run(Signal.java:219)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)


Done full thread dump.`
```

### Operating System

macOS ventura 13.5

### Selenium version

java17

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

**Comment by jramirezmorales** [comment]
I'm just doing a simple explicit wait , not sure if this is causing the thread lock:
` wait.until(ExpectedConditions.visibilityOfElementLocated(
        By.xpath("//market-blade[@class='market-blade']")));`
Also I was thinking that the problem was because of a single new WebDriverWait(webDriver, Duration.ofSeconds(30)); object for all waits, so I created new object for every wait.until, but the problem continues

**Comment by joerg1985** [comment]
@jramirezmorales 
I can't see a dead lock here, the `main` thread is waiting for the next round of polling.
A timeout exception should be raised after a while, depending on the timeout of the `wait` object.

Could you provide code to reproduce this?

**Comment by jramirezmorales** [comment]
@joerg1985  this is the timeout you mentioned , seems that the timeout may be causing the browser to crash
[thread dump.txt](https://github.com/SeleniumHQ/selenium/files/12541361/thread.dump.txt)

**Comment by jramirezmorales** [comment]
@joerg1985 here is another thread dump running same tests, so if the problem are timeouts, which another setting could I use for timeout, apart from 
`driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(60));`
and 
`new WebDriverWait(webDriver, Duration.ofSeconds(60));`
[another thread dump.txt](https://github.com/SeleniumHQ/selenium/files/12543166/another.thread.dump.txt)

**Comment by jramirezmorales** [comment]
also see this issue just one time
<img width="1436" alt="Screenshot 2023-09-06 at 4 56 58 PM" src="https://github.com/SeleniumHQ/selenium/assets/121830872/b39d2a3a-f2f1-4b43-b12a-9d902d9551c8">

**Comment by joerg1985** [comment]
@jramirezmorales Could you provide code to reproduce this?
Without the code it is not possible to debug this.

**Comment by jramirezmorales** [comment]
@joerg1985  let me try to wok on a test code to provide it since the code where this issue arise is private

**Comment by msharma2020** [comment]
Fluent wait is not working as expected post chrome version 114.
I am using Chrome Version 117 and this piece of code stopped working as expected.
WebElement myelementowaitfor = 
(new WebDriverWait(driver,Duration.ofSeconds(10))).until(ExpectedConditions.presenceOfElementLocated(By.name("frameMenu")));

previosly this was -
WebElement myelementowaitfor = (new WebDriverWait(driver,10)).until(ExpectedConditions.presenceOfElementLocated(By.name("frameMenu")));

**Comment by diemol** [comment]
@msharma2020 how is this related to this issue?

@jramirezmorales did you find a way to reproduce this? Otherwise the issue will stale and be closed.

**Comment by jramirezmorales** [comment]
@diemol not so far, have a lot of work to do, not having chance to work on this, I just Ignored all my tests using selenium4 for now :(

**Comment by diemol** [comment]
I will close this as we did not get more information from the OP. We can reopen it in case more information is provided.
