### ISSUE TITLE
Unable to setSize for windows in last chrome

### ISSUE THREAD

**Issue by admizh** [SeleniumHQ/selenium#1272]
Unable to setSize for windows in chrome, and i get randomly error on method:
```java
        window.setSize(screenResolution);
        window.setPosition(new org.openqa.selenium.Point(0, 0));
```
Chrome:  46.0.2490.86
Chrome driver: 2.20
Selenium 2.48.2
java 1.8 updt 66

```java
org.openqa.selenium.WebDriverException: unknown error: Cannot read property 'getCurrent' of undefined
JavaScript stack:
TypeError: Cannot read property 'getCurrent' of undefined
    at updateWindow (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:66:17)
    at eval (eval at executeAsyncScript (unknown source), <anonymous>:2:23)
    at executeAsyncScript (<anonymous>:321:26)
    at apply.height (<anonymous>:337:29)
    at callFunction (<anonymous>:229:33)
    at apply.height (<anonymous>:239:23)
    at <anonymous>:240:3
    at Object.InjectedScript._evaluateOn (<anonymous>:875:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)
    at Object.InjectedScript.evaluate (<anonymous>:664:21)
  (Session info: chrome=46.0.2490.86)
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 5.1 SP3 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.58 seconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: ..., os.name: 'Windows XP', os.arch: 'x86', os.version: '5.1', java.version: '1.8.0_66'
Driver info: org.openqa.selenium.chrome.ChromeDriver
selenide.url: https://sfqa.online-onboarding.com/SFQA/XpressHRLogin.aspx
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=E:\Utils\USERPR~1\TEMP\scoped_dir1908_9849}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.86, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
selenide.baseUrl: http://localhost
Session ID: 8c4ab685c49ed23d38266ea0ba1b4399
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.setSize(RemoteWebDriver.java:853)
```

**Comment by lukeis** [comment]
please log chrome driver issues with the chrome driver project:

https://bugs.chromium.org/p/chromedriver/issues/list
