### ISSUE TITLE
[🐛 Bug]: Python selenium msedge does not work with headless mode disabled. Message: unknown error: msedge failed to start: crashed

### ISSUE THREAD

**Issue by niemawolnychusername** [SeleniumHQ/selenium#12735]
### What happened?

I have a problem with a python selenium web scraper that uses microsoft edge as a webdriver.  The msedgedriver works fine only when one of these is present:

    edge_options.add_argument("--user-data-dir=C:\\Users\\xxx\\Desktop\\Edge_user_data")
    edge_options.add_argument('--headless')

In case i want to use both, the program crashes, i have tried:

-giving msedge permissions
-reseting msedge browser
-duplicating the profile folder
-many other solutions from stackoverflow of git, but nothing has worked

### How can we reproduce the issue?

```shell
# Define Edge options
    edge_options = webdriver.EdgeOptions()


    edgepath = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
    edge_options.setBinary = edgepath
    service = webdriver.EdgeService(service_args=['--log-level=SEVERE', '--disable-build-check'])

    # Using the user profile
    edge_options.add_argument("--user-data-dir=C:\\Users\\xxx\\Desktop\\Edge_user_data")

    # Options
    logger = logging.getLogger()
    logger.setLevel(logging.CRITICAL) 
    #logging.basicConfig(level=logging.WARNING)
    edge_options.add_argument('--remote-debugging-port=0')
    edge_options.add_argument('--no-first-run')
    edge_options.add_argument('--no-default-browser-check')

    edge_options.add_argument('--headless')
    edge_options.add_argument('--log-level=3')
    edge_options.add_argument("--disable-logging")
    edge_options.add_argument('--start-maximized') 
    edge_options.add_argument('--disable-infobars') 
    edge_options.add_experimental_option('excludeSwitches', ['disable-popup-blocking'])

    driver = webdriver.Edge(options=edge_options, service=service)
    
    return driver
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\opus-test17.py", line 3414, in <module>
    slower_process(urls, result_file_path)
  File "C:\Users\xxx\Desktop\opus-test17.py", line 3338, in slower_process
    result = check_url(url)
             ^^^^^^^^^^^^^^
  File "C:\Users\xxx\Desktop\opus-test17.py", line 42, in check_url
    result = 123_check(url, username)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Desktop\opus-test17.py", line 534, in 123_check
    driver = initialize_driver5()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Desktop\opus-test17.py", line 321, in initialize_driver5
    driver = webdriver.Edge(options=edge_options, service=service)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\edge\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: msedge failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)
Stacktrace:
        GetHandleVerifier [0x00007FF74D583DB2+61490]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF74D516002+740642]
        (No symbol) [0x00007FF74D2EB8AE]
        (No symbol) [0x00007FF74D31CBFE]
        (No symbol) [0x00007FF74D317F13]
        (No symbol) [0x00007FF74D35B7F8]
        (No symbol) [0x00007FF74D3536E3]
        (No symbol) [0x00007FF74D325EAA]
        (No symbol) [0x00007FF74D32518B]
        (No symbol) [0x00007FF74D326634]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF74D748D69+1207369]
        (No symbol) [0x00007FF74D3A5304]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF74D4690F1+32273]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF74D4619E9+1801]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF74D747944+1202212]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF74D51E998+19784]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF74D51AE54+4612]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF74D51AF86+4918]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF74D50F451+713073]
        BaseThreadInitThunk [0x00007FF87E917614+20]
        RtlUserThreadStart [0x00007FF87FD226B1+33]
```

### Operating System

Windows 10 Pro

### Selenium version

Python 3.11.4

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge Version 116.0.1938.81 (Official build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

msedgedriver Version: 116.0.1938.81

**Comment by titusfortner** [comment]
Try using `--headless=new`

**Comment by niemawolnychusername** [comment]
It works! Thank you very much, to be honset I wasn't even aware that the headless mode got an upgrade. The only minor inconvenience is that i keeps printing
`DevTools listening on ws://127.0.0.1:61482/devtools/browser/b0be3fe6-ace7-40d1-b63c-de8db12070d1`
for each iteration (each url in my case), and it brakes the progess bar, as it has to be "reprinted".

DevTools listening on ws://127.0.0.1:61482/devtools/browser/b0be3fe6-ace7-40d1-b63c-de8db12070d1
17%|██████████████                                                                      | 1/6 [00:12<01:00, 12.12s/it]
DevTools listening on ws://127.0.0.1:61545/devtools/browser/a2b40fa8-5322-403c-b370-0ca1f62b8228
33%|████████████████████████████                                                        | 2/6 [00:22<00:45, 11.35s/it]
DevTools listening on ws://127.0.0.1:61590/devtools/browser/e36c0255-460e-4ea3-9dc0-30f722354eb9
50%|██████████████████████████████████████████

Is there any way to get rid of it? I have tried this but nothing works:
    `edge_options.add_argument('--remote-debugging-port=0')`
    `service = webdriver.EdgeService(service_args=['--log-level=SEVERE', '--disable-build-check'])`
    `log_file_path = os.path.join(script_dir, 'edgedriver.log')`
    `edge_options.add_argument(f'--log-path={log_file_path}')`
    `edge_options.add_argument('--log-level=3')`
    `edge_options.add_argument("--disable-logging")`

I hope that the question is not an off topic. Once again, thank you very much for help.

**Comment by titusfortner** [comment]
Use the service class to send the output to a file instead?
https://www.selenium.dev/documentation/webdriver/browsers/edge/#log-file-features

I'll close this issue as resolved. Feel free to reach out in chat if you'd like - https://www.selenium.dev/support/#ChatRoom

**Comment by niemawolnychusername** [comment]
I'll definitely try, thank you very much for your help.
