### ISSUE TITLE
[🐛 Bug]: Selenium v4.12.0+ causing page to crash 

### ISSUE THREAD

**Issue by niall-oboyle** [SeleniumHQ/selenium#12766]
### What happened?

When attempting to complete an Adobe E-Sign process via Selenium automation on Workday, certain core Selenium calls (such as isDisplayed, click, among others) within the iframe cause the WD page to crash and all fields on the page become inaccessible - we had to downgrade our selenium version to v11 to resolve this issue.

https://github.com/SeleniumHQ/selenium/assets/30829709/f99dda15-7e78-4c6b-8d41-8f5ef58feba3

[adobe.txt](https://github.com/SeleniumHQ/selenium/files/12647019/adobe.txt)

### How can we reproduce the issue?

```shell
Paste the HTML provided in the What Happened section into Google Chrome, and the affected page should be displayed - calling isDisplayed, click (or other core element calls) should cause the page to crash with errors in the console
```

### Relevant log output

```shell
app-main.js:491 Uncaught TypeError: _.pick is not a function
    at m.constructor (app-main.js:491:10400)
    at new m (app-main.js:452:163422)
    at m.showSignaturePad (app-esign.js:82:470553)
    at C (app-main.js:452:118629)
    at m.<anonymous> (app-main.js:452:118849)
    at m.<anonymous> (app-main.js:452:111524)
    at b (app-main.js:452:133152)
    at Object.trigger (app-main.js:452:132416)
    at m.openSigPanel (component-viewfields.js:21:237877)
    at m.doSigningAction (component-viewfields.js:21:239511)
constructor @ app-main.js:491
m @ app-main.js:452
showSignaturePad @ app-esign.js:82
C @ app-main.js:452
(anonymous) @ app-main.js:452
(anonymous) @ app-main.js:452
b @ app-main.js:452
trigger @ app-main.js:452
openSigPanel @ component-viewfields.js:21
doSigningAction @ component-viewfields.js:21
onInputClick @ component-viewfields.js:21
C @ app-main.js:452
(anonymous) @ app-main.js:452
(anonymous) @ app-main.js:452
dispatch @ app-main.js:25
cb.handle @ app-main.js:25
eval @ VM461:3
executeScript @ VM460:369
apply.element-6066-11e4-a52e-4f735466cecf @ VM460:374
callFunction @ VM460:338
(anonymous) @ VM460:351
(anonymous) @ VM460:352

app-esign.js:48 Uncaught TypeError: _.values is not a function
    at m.getTodoCount (app-esign.js:48:46826)
    at m.isDone (app-esign.js:48:46905)
    at m.areTodosDone (app-esign.js:48:126573)
    at m.onInputFocus (app-esign.js:48:102355)
    at C (app-main.js:452:118629)
    at m.<anonymous> (app-main.js:452:118849)
    at m.<anonymous> (app-main.js:452:111524)
    at b (app-main.js:452:133211)
    at Object.trigger (app-main.js:452:132416)
    at m.setFocused (component-viewfields.js:21:182608)

Uncaught Error: Argument to isShown must be of type Element
    at Ic (eval at executeScript (esign:367:16), <anonymous>:94:352)
    at eval (eval at executeScript (esign:367:16), <anonymous>:102:797)
    at m.isAnySigned (app-esign.js:48:34759)
    at m.getSubmitData (app-esign.js:48:35802)
    at m.l [as getSubmitData] (app-main.js:452:163181)
    at e.show (component-viewfields.js:21:230872)
    at ez.eF [as _enter] (app-main.js:458:53267)
    at HTMLDivElement.<anonymous> (app-main.js:458:52183)
    at HTMLDivElement.handle (app-main.js:25:49785)
    at HTMLDivElement.dispatch (app-main.js:25:45085)
```

### Operating System

MacOS Ventura 13.5.2 (occurring on remote servers too)

### Selenium version

v4.12.0 and higher

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
This was fixed in trunk and will be available as soon as we can get a new release out.

#12659

**Comment by niall-oboyle** [comment]
Thanks @titusfortner 👍
