### ISSUE TITLE
[🐛 Bug]: Selenium Manager - Exec format error on aarch64

### ISSUE THREAD

**Issue by bananensplit** [SeleniumHQ/selenium#12778]
### What happened?

I recently ran into something I think is a bug. I was recently working on a docker deployment for one of my projects and ran into the following issue. I tried running Selenium in a docker container but couldn't get it to work because every time I executed my python script an exception was thrown.

Below is a minimal reproduction of the problem i am encoutnering.

### What I think happens
As seen in the log below, the first error states that `selenium-manager` is not in the correct exec format. This usually means that the exec file is not compiled for the architecture the system is currently running (in my case `aarch64`).

Therefore the manager can not be executed and can not fulfill it's duty as a driver-manager.

### How can we reproduce the issue?

```shell
# Create a dockercontainer
docker run -dt --rm --name python-box python:3.11-bookworm

# Enter the container bash
docker exec -it python-box bash

# In the container bash run the following
cd /usr/src/
apt update
apt install firefox-esr
pip install selenium
echo "from selenium import webdriver
driver = webdriver.Firefox()" > main.py

# Run the script
export DISPLAY=:20
python main.py
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 126, in run
    completed_proc = subprocess.run(args, capture_output=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 95, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 132, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /usr/local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --output json


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/main.py", line 3, in <module>
    driver = webdriver.Firefox()
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Host: Ubuntu 22.04.1 LTS (jammy)

### Selenium version

Python 4.12.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 102.15.1esr

### What are the browser driver(s) and version(s) where you see this issue?

the script doesn't even get as far as installing a driver

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
Yes, the issue is that we do not support aarch64 on Linux, yet.
Details here - https://www.selenium.dev/documentation/selenium_manager/#alternative-architecture
