### ISSUE TITLE
All Ruby build integration tests fail with error in before(:suite) hook [🐛 Bug]: 

### ISSUE THREAD

**Issue by MatzFan** [SeleniumHQ/selenium#12779]
### What happened?

I am trying to run Selenium tests locally, have installed the deps and successfully run the unit tests, but all integration tests fail in the before(:suite) hook in the `spec_helper`. An example:

`bazel test //rb/spec/integration/selenium/webdriver:element --define browser=firefox` gives the log output below.

I've checked `firefox` and `geckodriver` are in my PATH. Running the test with the `--config ruby_debug` option does not seem to highlight the problem.

### How can we reproduce the issue?

```shell
Follow build instructions for Ruby and run `bazel test //rb/spec/integration/selenium/webdriver:element --define browser=firefox`
```

### Relevant log output

```shell
Running Ruby specs:


An error occurred in a `before(:suite)` hook.
Failure/Error: e = error

Selenium::WebDriver::Error::UnknownError:
  Process unexpectedly closed with status 1
# ./rb/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
# ./rb/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
# ./rb/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
# ./rb/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
# ./rb/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
# ./rb/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
# ./rb/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
# ./rb/lib/selenium/webdriver/remote/bridge.rb:53:in `create_session'
# ./rb/lib/selenium/webdriver/common/driver.rb:317:in `block in create_bridge'
# ./rb/lib/selenium/webdriver/common/driver.rb:316:in `create_bridge'
# ./rb/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
# ./rb/lib/selenium/webdriver/firefox/driver.rb:43:in `initialize'
# ./rb/lib/selenium/webdriver/common/driver.rb:53:in `new'
# ./rb/lib/selenium/webdriver/common/driver.rb:53:in `for'
# /home/me/dev/selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:225:in `firefox_driver'
# /home/me/dev/selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:147:in `create_driver!'
# /home/me/dev/selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:61:in `driver_instance'
# /home/me/dev/selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:182:in `current_env'
# /home/me/dev/selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:42:in `print_env'
# /home/me/dev/selenium/rb/spec/integration/selenium/webdriver/spec_helper.rb:41:in `block (2 levels) in <top (required)>'
```

### Operating System

Ubuntu 23.04

### Selenium version

Ruby 4.12.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 102.15.1esr

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.33.0

**Comment by titusfortner** [comment]
Try with:
```
bazel test //rb/spec/integration/selenium/webdriver:element --define browser=firefox --test_output streamed --test_env DEBUG=1
```

**Comment by runephilosof-abtion** [comment]
I also get an unknown error.
Running in a Docker container on Linux.
It might be because `Error: no DISPLAY environment variable specified`.
Can that error message be transported back up the chain, so you don't have to turn on debug to see it?

```
root@9ac8c4414fe7:/selenium# bazel test //rb/spec/integration/selenium/webdriver:element --define browser=firefox --test_output streamed --test_env DEBUG=1
Starting local Bazel server and connecting to it...
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed target //rb/spec/integration/selenium/webdriver:element (426 packages loaded, 13466 targets configured).
INFO: Found 1 test target...
INFO: From Running Cargo build script bzip2-sys:
Build Script Warning: bzip2-1.0.8/compress.c: In function 'sendMTFValues':
Build Script Warning: bzip2-1.0.8/compress.c:243:19: warning: variable 'nBytes' set but not used [-Wunused-but-set-variable]
Build Script Warning:   243 |    Int32 nGroups, nBytes;
Build Script Warning:       |                   ^~~~~~

Running Ruby specs:

2023-11-07 07:27:03 DEBUG Selenium [:selenium_manager] Selenium Manager binary found at /selenium/bazel-bin/rb/bin/linux/selenium-manager 
2023-11-07 07:27:03 DEBUG Selenium [:selenium_manager] Executing Process ["/selenium/bazel-bin/rb/bin/linux/selenium-manager", "--browser", "firefox", "--browser-version", "stable", "--output", "json", "--debug"] 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] geckodriver not found in PATH 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] firefox detected at /usr/bin/firefox 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] Running command: /usr/bin/firefox -v 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] Output: "Mozilla Firefox 115.4.0esr" 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] Detected browser: firefox 115.4.0 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] Discovered online firefox version (119) is different to the detected local firefox version (115) 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] Required browser: firefox 119.0b9 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] Downloading firefox 119.0b9 from https://ftp.mozilla.org/pub/firefox/releases/119.0b9/linux-x86_64/en-US/firefox-119.0b9.tar.bz2 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] firefox 119.0b9 is available at /root/.cache/selenium/firefox/linux64/119.0b9/firefox 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] Required driver: geckodriver 0.33.0 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] geckodriver 0.33.0 already in the cache 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] Driver path: /root/.cache/selenium/geckodriver/linux64/0.33.0/geckodriver 
2023-11-07 07:27:26 DEBUG Selenium [:selenium_manager] Browser path: /root/.cache/selenium/firefox/linux64/119.0b9/firefox 
2023-11-07 07:27:26 DEBUG Selenium [:driver_service] port prober could not bind to ::1:4444 (Cannot assign requested address - bind(2) for "::1" port 4444) 
2023-11-07 07:27:26 DEBUG Selenium [:driver_service] Executing Process ["/root/.cache/selenium/geckodriver/linux64/0.33.0/geckodriver", "--port=4444"] 
2023-11-07 07:27:26 DEBUG Selenium [:process] Starting process: ["/root/.cache/selenium/geckodriver/linux64/0.33.0/geckodriver", "--port=4444"] with {[:out, :err]=>#<IO:<STDOUT>>, :pgroup=>true} 
2023-11-07 07:27:26 DEBUG Selenium [:process]   -> pid: 28449 
2023-11-07 07:27:26 DEBUG Selenium [:driver_service] polling for socket on ["127.0.0.1", 4444] 
1699342046259	geckodriver	INFO	Listening on 127.0.0.1:4444
2023-11-07 07:27:26 DEBUG Selenium [:command] -> POST session 
2023-11-07 07:27:26 DEBUG Selenium [:command]    >>> http://127.0.0.1:4444/session | {"capabilities":{"alwaysMatch":{"acceptInsecureCerts":true,"browserName":"firefox","moz:firefoxOptions":{"binary":"/root/.cache/selenium/firefox/linux64/119.0b9/firefox"},"moz:debuggerAddress":true}}} 
2023-11-07 07:27:26 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.16.0.nightly (ruby linux)", "Content-Length"=>"200"} 
1699342046527	mozrunner::runner	INFO	Running command: MOZ_CRASHREPORTER="1" MOZ_CRASHREPORTER_NO_REPORT="1" MOZ_CRASHREPORTER_SHUTDOWN="1" MOZ_NO_REMOTE="1" "/roo ... tte" "--remote-debugging-port" "9222" "--remote-allow-hosts" "localhost" "-no-remote" "-profile" "/tmp/rust_mozprofilejGXzGF"
Error: no DISPLAY environment variable specified
2023-11-07 07:27:26 DEBUG Selenium [:header]    <<<  {"content-type"=>["application/json; charset=utf-8"], "cache-control"=>["no-cache"], "content-length"=>["105"], "date"=>["Tue, 07 Nov 2023 07:27:26 GMT"]} 
2023-11-07 07:27:26 DEBUG Selenium [:command] <- {"value":{"error":"unknown error","message":"Process unexpectedly closed with status 1","stacktrace":""}} 

An error occurred in a `before(:suite)` hook.
Failure/Error: e = error

Selenium::WebDriver::Error::UnknownError:
  Process unexpectedly closed with status 1
# ./rb/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
# ./rb/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
# ./rb/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
# ./rb/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
# ./rb/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
# ./rb/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
# ./rb/lib/selenium/webdriver/remote/bridge.rb:601:in `execute'
# ./rb/lib/selenium/webdriver/remote/bridge.rb:53:in `create_session'
# ./rb/lib/selenium/webdriver/common/driver.rb:317:in `block in create_bridge'
# ./rb/lib/selenium/webdriver/common/driver.rb:316:in `create_bridge'
# ./rb/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
# ./rb/lib/selenium/webdriver/firefox/driver.rb:43:in `initialize'
# ./rb/lib/selenium/webdriver/common/driver.rb:53:in `new'
# ./rb/lib/selenium/webdriver/common/driver.rb:53:in `for'
# /selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:225:in `firefox_driver'
# /selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:147:in `create_driver!'
# /selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:61:in `driver_instance'
# /selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:182:in `current_env'
# /selenium/rb/spec/integration/selenium/webdriver/spec_support/test_environment.rb:42:in `print_env'
# /selenium/rb/spec/integration/selenium/webdriver/spec_helper.rb:41:in `block (2 levels) in <top (required)>'


Finished in 23.58 seconds (files took 0.39019 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

2023-11-07 07:27:26 DEBUG Selenium [:process] Checking if 28449 is exited: 
2023-11-07 07:27:26 DEBUG Selenium [:process] Checking if 28449 is exited: 
2023-11-07 07:27:26 DEBUG Selenium [:process] Sending TERM to process: 28449 
2023-11-07 07:27:26 DEBUG Selenium [:process] Polling 20 seconds for exit of 28449 
2023-11-07 07:27:26 DEBUG Selenium [:process] Checking if 28449 is exited: 
2023-11-07 07:27:26 DEBUG Selenium [:process] Checking if 28449 is exited: 
2023-11-07 07:27:26 DEBUG Selenium [:process]   -> exit code is 15 
2023-11-07 07:27:26 DEBUG Selenium [:process] Checking if 28449 is exited: 
2023-11-07 07:27:26 DEBUG Selenium [:process]   -> exit code is 15 
2023-11-07 07:27:26 DEBUG Selenium [:process]   -> stopped 28449 
FAIL: //rb/spec/integration/selenium/webdriver:element (see /root/.cache/bazel/_bazel_root/ac0d4680205ef33acb63908a9af1e1ad/execroot/selenium/bazel-out/k8-fastbuild/testlogs/rb/spec/integration/selenium/webdriver/element/test.log)
Target //rb/spec/integration/selenium/webdriver:element up-to-date:
  bazel-bin/rb/spec/integration/selenium/webdriver/element.rb.sh
INFO: Elapsed time: 589.946s, Critical Path: 110.97s
INFO: 394 processes: 145 internal, 2 local, 247 processwrapper-sandbox.
INFO: Build completed, 1 test FAILED, 394 total actions
//rb/spec/integration/selenium/webdriver:element                         FAILED in 24.7s
  /root/.cache/bazel/_bazel_root/ac0d4680205ef33acb63908a9af1e1ad/execroot/selenium/bazel-out/k8-fastbuild/testlogs/rb/spec/integration/selenium/webdriver/element/test.log

Executed 1 out of 1 test: 1 fails locally.
```

**Comment by MatzFan** [comment]
@runephilosof-abtion looks like a different error to mine. @titusfortner happy you close the original issue I raised here as I've changed OS (to LMDE) in the meantime and won't be able to reproduce it :smile:

**Comment by titusfortner** [comment]
@runephilosof-abtion that error logging is coming from geckodriver. Selenium error includes what mozilla provides in the actual response, so it would be up to them to add it.
