### ISSUE TITLE
[🐛 Bug]: Rails minitest Unable to execute system tests

### ISSUE THREAD

**Issue by aashishpsaini** [SeleniumHQ/selenium#12792]
### What happened?

While upgrading from selenium-webdriver from 4.9.0 to 4.12.0, getting this error:

```
Minitest::UnexpectedError:         Selenium::WebDriver::Error::NoSuchDriverError: Unable to obtain chromedriver using Selenium Manager; wrong number of arguments (given 2, expected 0..1); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/driver_finder.rb:31:in `rescue in path'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/driver_finder.rb:27:in `path'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/local_driver.rb:41:in `process_options'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/local_driver.rb:27:in `initialize_local_driver'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/chrome/driver.rb:34:in `initialize'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver.rb:89:in `for'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:83:in `browser'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:104:in `visit'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/session.rb:280:in `visit'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/dsl.rb:52:in `call'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/dsl.rb:52:in `visit'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/site_prism-4.0.3/lib/site_prism/page.rb:194:in `load_html_website'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/site_prism-4.0.3/lib/site_prism/page.rb:80:in `load'
```

Note we are using Selenium Webdriver along with Capybara and SitePrism.
Based on the stacktrace, looks like issue is happening in `Webdriver::Logger` class `initialize` method:

```
3] pry(Selenium::WebDriver::DriverFinder)> WebDriver::Logger.new('Selenium', default_level: :debug, **{})
ArgumentError: wrong number of arguments (given 2, expected 0..1)
from /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/logger.rb:51:in `initialize'
```

### How can we reproduce the issue?

```shell
Upgrade selenium-webdriver from 4.9.0 to 4.12.0
```

### Relevant log output

```shell
Minitest::UnexpectedError:         Selenium::WebDriver::Error::NoSuchDriverError: Unable to obtain chromedriver using Selenium Manager; wrong number of arguments (given 2, expected 0..1); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/driver_finder.rb:31:in `rescue in path'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/driver_finder.rb:27:in `path'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/local_driver.rb:41:in `process_options'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/local_driver.rb:27:in `initialize_local_driver'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/chrome/driver.rb:34:in `initialize'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.12.0/lib/selenium/webdriver.rb:89:in `for'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:83:in `browser'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:104:in `visit'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/session.rb:280:in `visit'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/dsl.rb:52:in `call'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/dsl.rb:52:in `visit'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/site_prism-4.0.3/lib/site_prism/page.rb:194:in `load_html_website'
            /Users/aashishsaini/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/site_prism-4.0.3/lib/site_prism/page.rb:80:in `load'
```

### Operating System

macOS Ventura 13.5.2

### Selenium version

4.12.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Please update to the latest version of Capybara
