### ISSUE TITLE
[🐛 Bug]: 在docker中并发使用selenium控制浏览器会报错

### ISSUE THREAD

**Issue by Z-YHDD** [SeleniumHQ/selenium#12815]
### What happened?

selenium版本：4.0.0-alpha-1
![image](https://github.com/SeleniumHQ/selenium/assets/100017088/c0c225f2-b6c4-4e9c-a476-44eea82571ee)

ChromeDriver版本：91.0.4472.101

chrome版本：91.0.4472.77

我在docker中并发创建了4个ChromeDriver，用这4个chromeDriver对象分别控制一个浏览器，去完成我需要的操作，但是四个对象同时报错，4个对象的报错中除了端口不一样，别的报错信息都一样
![image](https://github.com/SeleniumHQ/selenium/assets/100017088/6d4775ca-4b05-48a6-a9c6-e88b60f6b689)
![image](https://github.com/SeleniumHQ/selenium/assets/100017088/cd0f91c4-c0ba-478f-9f6d-a4ba78f32c10)
![image](https://github.com/SeleniumHQ/selenium/assets/100017088/d5f0b763-a3c2-42f9-bb56-1361c8c5200d)
![image](https://github.com/SeleniumHQ/selenium/assets/100017088/f8fcfe97-63e6-4061-b2bd-d0b805bbaa6e)

奇怪的是，我在windows上进行同样的并发操作，却没有报错，程序可以正常执行。并且，在docker中当我去掉并发，执行这个操作时，不会出现此类报错，程序可以正常依次执行下去，直至结束。

### How can we reproduce the issue?

```shell
@Async("timePushTaskExecutor")
    public void testBoardSend(BoardTimePushDto dto){

        String appId = dto.getAppId();

        // 查询产品信息
        SendTimePushDto checkApp = boardTimePushMapper.selectAppInfo(appId);
        String appName = checkApp.getAppName();

        if (ObjectUtils.isEmpty(checkApp)){
            log.error("看板定时推送: [{}]产品不存在", appId);
            throw new RuntimeException("看板定时推送: 产品不存在");
        }

        // 获取文件保存路径
        String uuid = UUIDUtil.getUuid().split("-")[0];
        String downloadPath = OSSUtil.getUploadPath().getAbsolutePath() + "\\boardTimePush\\" + appName + "\\" + uuid;
        // 获取chromeDriver路径
//        String chromeDriverPath = System.getProperty("user.dir") + "/src/main/resources/static/chromedriver-107.exe";
        String chromeDriverPathWindows = "src/main/resources/static/chromedriver-107.exe";
        String chromeDriverPathLinux = "/opt/google/chromedriver/chromedriver-91-101";

        // 根据此时的运行环境来改变下载地址
        if (OsUtil.getOS().toLowerCase().contains("windows")) {
            // 设置启动参数
            System.setProperty("webdriver.chrome.driver", chromeDriverPathWindows);
            downloadPath = downloadPath.replaceAll("/", "\\\\");
        } else if (OsUtil.getOS().toLowerCase().contains("linux")) {
            // 设置启动参数
            System.setProperty("webdriver.chrome.driver", chromeDriverPathLinux);
            downloadPath = downloadPath.replaceAll("\\\\", "/");
        }

        // 检查文件夹是否存在，不存在则创建
        File file = new File(downloadPath);
        if (!file.exists() && !file.isDirectory()) {
            file.mkdirs();
            log.info("看板定时推送: [{}]文件夹不存在，创建文件夹", appName);
        }

        // 谷歌浏览器启动配置项
        ChromeOptions options = new ChromeOptions();

        // 设置无头模式
        options.setHeadless(true);
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");

        // 设置浏览器下载地址
        Map<String, Object> chromePrefs = new HashMap<>();
        chromePrefs.put("profile.default_content_settings.popups", 0);
        chromePrefs.put("download.default_directory", downloadPath);
        chromePrefs.put("SE_NODE_MAX_SESSIONS", 5);
        options.setExperimentalOption("prefs", chromePrefs);

        //ssl证书支持
        options.setCapability("acceptSslCerts", true);
        //截屏支持
        options.setCapability("takesScreenshot", true);
        //css搜索支持
        options.setCapability("cssSelectorsEnabled", true);

        // 创建一个谷歌浏览器驱动对象，并把启动配置项对象传入
        ChromeDriver driver = new ChromeDriver(options);

        // 设置浏览器窗口大小
        driver.manage().window().setSize(new Dimension(1920, 21000));

        // 设置全局等待120秒
        driver.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);
        driver.manage().timeouts().pageLoadTimeout(120, TimeUnit.SECONDS);
        driver.manage().timeouts().setScriptTimeout(120, TimeUnit.SECONDS);
        try {

            log.info("看板定时推送: [{}]启动浏览器，访问bi页面", appName);
            // 1.访问bi页面
            driver.get(openUrl);

            log.info("看板定时推送: [{}]等待页面加载", appName);
            // 2.等待/找到右上角的‘选择产品’按钮
            driver.findElement(By.cssSelector("div[title=\"选择产品\"]"));

            log.info("看板定时推送: [{}]页面加载完成，开始检查公司和产品", appName);

            // 3.检查公司和app
            WebElement appElement = driver.findElement(By.cssSelector("div[title=\"选择产品\"]"));
            // 执行下面的click()时发生了我所描述的报错
            appElement.click();

        } catch (Exception e) {
            log.error("看板定时推送: [{}]推送出现异常:", appName, e);
            throw new RuntimeException(e);
        }finally {
            log.info("看板定时推送: [{}]推送全部结束，关闭浏览器，删除文件夹", appName);
            driver.quit();
        }
    }
```

### Relevant log output

```shell
org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:1841
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'gn-bi-manage-7df44c54cf-frsg2', ip: '10.244.0.164', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.88.1.el7.x86_64', java.version: '1.8.0_292'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at cn.modo.dmpmanage.service.biz.BoardTimePushService.checkCompanyAndApp(BoardTimePushService.java:1753)
	at cn.modo.dmpmanage.service.biz.BoardTimePushService.testBoardSend(BoardTimePushService.java:1535)
	at cn.modo.dmpmanage.service.biz.BoardTimePushService$$FastClassBySpringCGLIB$$8c22047c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:1841
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 15 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	... 36 common frames omitted
```

### Operating System

CentOS Linux release 7.9.2009 (Core)

### Selenium version

openjdk version "1.8.0_372"

### What are the browser(s) and version(s) where you see this issue?

Chrome 91.0.4472.77

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 91.0.4472.101

### Are you using Selenium Grid?

没有使用

**Comment by titusfortner** [comment]
We can only support the latest version of Selenium. Please update to 4.12 and let us know if you have a problem.
