### ISSUE TITLE
[🐛 Bug]: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): operation timed out

### ISSUE THREAD

**Issue by ashwakpasha** [SeleniumHQ/selenium#12826]
### What happened?

Facing this issue when trying to launch the chrome driver. 

I can see chrome driver under /.cache/selenium/chromedriver/mac-arm64

If i delete the chromedriver folder under .cache, and run the below lines, for some time (few runs)it will launch the driver by downloading chromedriver under .cache, But after few runs it wont launch. 

is there any possibility of chromedriver getting crashed ? or something related to proxy connection ?

### How can we reproduce the issue?

```shell
ChromeOptions op = new ChromeOptions();
op.setCapability(LogType.BROWSER, Level.ALL);
Proxy proxy = new Proxy();
proxy.setHttpProxy("myip:port");
op.setCapability(CapabilityType.PROXY, proxy);
WebDriver driver = new ChromeDriver(op);
```

### Relevant log output

```shell
WARNING: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): operation timed out
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browser: ALL, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}, error Command failed with code: 65, executed: [--browser, chrome, --output, json]
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): operation timed out
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.5.2', java.version: '17.0.7'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at com.onereport.tests.TestFrameworks.sample.main(sample.java:17)
Caused by: org.openqa.selenium.WebDriverException: Command failed with code: 65, executed: [--browser, chrome, --output, json]
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): operation timed out
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.5.2', java.version: '17.0.7'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:144)
	at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:299)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)
	... 6 more
```

### Operating System

macOS

### Selenium version

4.12.1

### What are the browser(s) and version(s) where you see this issue?

chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 117.0.5938.92

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
There were a few improvements in 4.13.0, please upgrade and try again.

**Comment by ashwakpasha** [comment]
the issue was related to proxy, i have fixed it with proper proxy. 
@titusfortner Thank you

**Comment by Jorge2M** [comment]
> There were a few improvements in 4.13.0, please upgrade and try again.

Thakyou @titusfortner , this has work fine for me
