### ISSUE TITLE
[🐛 Bug]: Expected to read a START_MAP but instead have: STRING when getting URI

### ISSUE THREAD

**Issue by bhecquet** [SeleniumHQ/selenium#12839]
### What happened?

Hello, 

I started up a distributed selenium grid (router, distributor, sessionmap, ...)
When requesting a new session, I get
```
Expected to read a START_MAP but instead have: STRING. Last 0 characters read
```

On router logs (see below), I see that it's the RemoteSessionMap.getUri() method which fails.
In fact, calling `http://<host>:5556/se/grid/session/<session_id>/uri` returns a string: `"http:\u002f\u002f<host>:5555"` but 
RemoteSessionMap.getUri tries to parse it as Json map
https://github.com/SeleniumHQ/selenium/blob/1992155adecbef8f8be87bd28d9ab4c96ad3593a/java/src/org/openqa/selenium/grid/sessionmap/remote/RemoteSessionMap.java#L100

### How can we reproduce the issue?

```shell
Set up all the 6 components locally, 

driver = new ChromeDriver()
driver.manage().window().maximize()
```

### Relevant log output

```shell
16:46:09.058 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request for an existing session: Expected to read a START_MAP but instead have: STRING. Last 0 characters read: 
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
16:46:09.058 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: STRING. Last 0 characters read: 
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:443)
	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:331)
	at org.openqa.selenium.grid.web.Values.get(Values.java:54)
	at org.openqa.selenium.grid.sessionmap.remote.RemoteSessionMap.makeRequest(RemoteSessionMap.java:118)
	at org.openqa.selenium.grid.sessionmap.remote.RemoteSessionMap.getUri(RemoteSessionMap.java:100)
	at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:208)
	at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)
	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:160)
	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:382)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:87)
	at org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:69)
	at org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:75)
	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:271)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

16:46:09.059 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "ddfd73a634415882a608d5bee31a98e8","eventTime": 1695998769058373700,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Expected to read a START_MAP but instead have: STRING. Last 0 characters read: \nBuild info: version: '4.13.0', revision: 'ba948ece5b*'\nSystem info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: STRING. Last 0 characters read: \nBuild info: version: '4.13.0', revision: 'ba948ece5b*'\nSystem info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'\nDriver info: driver.version: unknown\r\n\tat org.openqa.selenium.json.JsonInput.expect(JsonInput.java:443)\r\n\tat org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:331)\r\n\tat org.openqa.selenium.grid.web.Values.get(Values.java:54)\r\n\tat org.openqa.selenium.grid.sessionmap.remote.RemoteSessionMap.makeRequest(RemoteSessionMap.java:118)\r\n\tat org.openqa.selenium.grid.sessionmap.remote.RemoteSessionMap.getUri(RemoteSessionMap.java:100)\r\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:208)\r\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)\r\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:160)\r\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:382)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:87)\r\n\tat org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:69)\r\n\tat org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:75)\r\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:271)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\r\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\r\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\r\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\r\n\tat java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)\r\n\tat java.util.concurrent.FutureTask.run(FutureTask.java)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\n","exception.type": "org.openqa.selenium.json.JsonException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "<host>:4444","http.method": "POST","http.request_content_length": "23","http.scheme": "HTTP","http.target": "\u002fsession\u002f3a1061893b3bb860b54bb80d8cb27983\u002ftimeouts","http.user_agent": "selenium\u002f4.11.0 (java windows)","session.id": "3a1061893b3bb860b54bb80d8cb27983"}}
```

### Operating System

Windows

### Selenium version

4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome / not related to browser

### What are the browser driver(s) and version(s) where you see this issue?

not related to browser

### Are you using Selenium Grid?

4.13.0

**Comment by pujagani** [comment]
I have tried to reproduce this with Selenium 4.13.0. I am unable to see the error. The result is as expected. 
Do you see this every time? Was this not happening in the previous version? Anything else we can do on our end to reproduce it?

**Comment by bhecquet** [comment]
Hello

I don't know what happened, I did the test today, and the problem wasn't there anymore ...
