### ISSUE TITLE
[🐛 Bug]: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by lpcoutinho** [SeleniumHQ/selenium#12841]
### What happened?

Hey everyone!!! Can someone help me?

I use Selenium 4.13.0, Ubuntu 22.04.2 and Chrome 117.0.5938.132

When trying to run the script with the Chrome screen open, I notice that the script breaks and I can't even access the desired page. This does not occur when I use the "--headless" argument. The output logs are displayed below.

I noticed that when I run the browser in the background with the  "--headless"  argument everything happens normally and the screen is printed at the end.

I researched a lot before asking here, I don't know if this is the right place for this, but can anyone help?

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-extensions")

options.add_argument(r"--user-data-dir=/home/luiz/.config/google-chrome/")
options.add_argument(r'--profile-directory=Default')

driver = webdriver.Chrome(options=options)

url="https://www.google.com"
driver.get(url)
driver.save_screenshot('img.png')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/luiz/projects/scrap/scrap.py", line 17, in <module>
    driver = webdriver.Chrome(options=options)
  File "/home/luiz/projects/scrap/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/luiz/projects/scrap/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/luiz/projects/scrap/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/home/luiz/projects/scrap/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/luiz/projects/scrap/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/home/luiz/projects/scrap/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x562f745d26b3 <unknown>
#1 0x562f742a81e7 <unknown>
#2 0x562f742db526 <unknown>
#3 0x562f742d769c <unknown>
#4 0x562f7431a23a <unknown>
#5 0x562f74310e93 <unknown>
#6 0x562f742e3934 <unknown>
#7 0x562f742e471e <unknown>
#8 0x562f74597cb8 <unknown>
#9 0x562f7459bbf0 <unknown>
#10 0x562f745a619c <unknown>
#11 0x562f7459c808 <unknown>
#12 0x562f7456927f <unknown>
#13 0x562f745c0e88 <unknown>
#14 0x562f745c1059 <unknown>
#15 0x562f745d1843 <unknown>
#16 0x7f8c8b294b43 <unknown>
```

### Operating System

Ubuntu 22.04.2

### Selenium version

4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 117.0.5938.132

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 117.0.5938.132

**Comment by titusfortner** [comment]
Aha, there is a recommended fix now:

https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35
