### ISSUE TITLE
[🐛 Bug]: No space left on device (os error 28) when working with selenium on Pterodactyl

### ISSUE THREAD

**Issue by tudubucket** [SeleniumHQ/selenium#12846]
### What happened?

I am currently having a Website Screenshot script by using Python. The code seems to be working normally on my computer, automatically download ChromeDriver which the code should do. But on Pterodactyl Server, even with more than 50 GB disk allocated, but the code return an error: 
```
{'code': 65, 'message': 'No space left on device (os error 28)', 'driver_path': '', 'browser_path': ''}
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```
In my opinion, this seems like selenium didn't use Pterodactyl working path `/home/container` (just maybe, not actually sure about it)

### How can we reproduce the issue?

```shell
1. Got a Pterodactyl Server with Python Egg installed here: 
   https://github.com/YajTPG/pterodactyl-eggs/blob/universal/egg-python--universal.json
2. Continue setting up server, allocate enough disk storage (my server already having more than 100 GB allocated with 55 GB free)
3. Run this code: https://gist.github.com/tudubucket/a7bc798d010a3f2054e155bb12f37f1d
4. Get the error 'No space left on device (os error 28), code 65'
```

### Relevant log output

```shell
container@pterodactyl~ Server marked as running...
DEBUG:selenium.webdriver.common.selenium_manager:Selenium Manager binary found at: /home/container/.local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG:selenium.webdriver.common.selenium_manager:Executing process: /home/container/.local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json
DEBUG:selenium.webdriver.common.selenium_manager:chromedriver not found in PATH
DEBUG:selenium.webdriver.common.selenium_manager:chrome not found in PATH
DEBUG:selenium.webdriver.common.selenium_manager:chrome not found in the system
DEBUG:selenium.webdriver.common.selenium_manager:Required browser: chrome 117.0.5938.92
DEBUG:selenium.webdriver.common.selenium_manager:Discovering versions from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
DEBUG:selenium.webdriver.common.selenium_manager:Downloading chrome 117.0.5938.92 from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chrome-linux64.zip
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 95, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 141, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}.\n{result}{stderr}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /home/container/.local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json.
{'code': 65, 'message': 'No space left on device (os error 28)', 'driver_path': '', 'browser_path': ''}
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/screensite.py", line 53, in <module>
    browser_pool = BrowserPool()
                   ^^^^^^^^^^^^^
  File "/home/container/screensite.py", line 20, in __init__
    self.create_pool()
  File "/home/container/screensite.py", line 41, in create_pool
    browser = webdriver.Chrome(options=chrome_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/container/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Pterodactyl Server on Linux

### Selenium version

Python 4.12.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117.0.5938.92

**Comment by titusfortner** [comment]
You can create an environment variable or add to a config file to change where Selenium downloads the drivers and browsers: https://www.selenium.dev/documentation/selenium_manager/#configuration
