### ISSUE TITLE
[🐛 Bug]: Getting this error when running tab switch scenario using iOS Safari with Selenium 4.9.0 and above versions || Caused by: java.lang.IllegalArgumentException: Illegal key values seen in w3c capabilities: [autoAcceptAlerts, nativeWebTap, safariAllowPopups]

### ISSUE THREAD

**Issue by sharutkarsh** [SeleniumHQ/selenium#12851]
### What happened?

Getting this error when running tab switch scenario using iOS Safari with Selenium 4.9.0 and above, while it was working fine when running with version 4.8.0 and previous versions using w3C capabilities.

Error we are getting:

Caused by: java.lang.IllegalArgumentException: Illegal key values seen in w3c capabilities: [autoAcceptAlerts, nativeWebTap, safariAllowPopups]

### How can we reproduce the issue?

```shell
Set up an appium server/xcode and test on an iOS device for safari. 

Use W3C capabilities and along with that use these capabilities

              	capabilities.setCapability("autoAcceptAlerts", "true");
        	capabilities.setCapability("safariAllowPopups", "true");
        	capabilities.setCapability("nativeWebTap", "true");

You will start getting an error if you update your selenium version above v4.8.0 (like 4.9 and above versions).

This is making difficult for us to test with latest selenium versions on Safari iOS.
```

### Relevant log output

```shell
`org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '********', ip: '*****************'
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.2', java.version: '17.0.3'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {autoAcceptAlerts: true, appium:options: {appiumVersion: 2.0.1, build: Switch tab on iOS 1, debug: true, deviceName: iPhone 12, local: false, osVersion: 14, seleniumVersion: 4.11.0}, nativeWebTap: true, safariAllowPopups: true}]}]
Capabilities {autoAcceptAlerts: true, appium:options: {appiumVersion: 2.0.1, build: Switch tab on iOS 1, debug: true, deviceName: iPhone 12, local: false, osVersion: 14, seleniumVersion: 4.11.0}, nativeWebTap: true, safariAllowPopups: true}
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at tabSwitch.main(tabSwitch.java:37)
Caused by: java.lang.IllegalArgumentException: Illegal key values seen in w3c capabilities: [autoAcceptAlerts, nativeWebTap, safariAllowPopups]
	at org.openqa.selenium.remote.NewSessionPayload.lambda$validate$4(NewSessionPayload.java:175)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:540)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.remote.NewSessionPayload.validate(NewSessionPayload.java:179)
	at org.openqa.selenium.remote.NewSessionPayload.<init>(NewSessionPayload.java:91)
	at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:124)
	at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:112)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:165)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 4 more
`
```

### Operating System

MacOS Monterey

### Selenium version

4.9.0

### What are the browser(s) and version(s) where you see this issue?

iOS Safari browser on mobile devices

### What are the browser driver(s) and version(s) where you see this issue?

RemoteWebDriver, iPhone 12 iOS 14 on Safari browser

### Are you using Selenium Grid?

yes

**Comment by titusfortner** [comment]
Selenium is enforcing w3c standards compliance. You should be able to pass these values in for use with an Appium server by prepending those keys with `appium:`

**Comment by sharutkarsh** [comment]
> Selenium is enforcing w3c standards compliance. You should be able to pass these values in for use with an Appium server by prepending those keys with `appium:`

Thanks, it did resolve the issue!!
