### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by notSoTechnical** [SeleniumHQ/selenium#12855]
### What happened?

I was just trying to launch google chrome. I did not modify any other code besides code in main. 

I'm getting: Exception in thread "main" java.lang.IllegalAccessError: class org.openqa.selenium.remote.service.DriverService$Builder (in module org.seleniumhq.selenium.remote_driver) cannot access class com.google.common.io.ByteStreams (in unnamed module @0x1f021e6c) because module org.seleniumhq.selenium.remote_driver does not read unnamed module @0x1f021e6c

### How can we reproduce the issue?

```shell
/**
 * 
 */
package com.Chrome;

import org.openqa.selenium.chrome.ChromeDriver;


/**
 * 
 */
public class autoApply {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		String url = "https://www.google.com/";
		// TODO Auto-generated method stub
		ChromeDriver driver = new ChromeDriver();
		driver.get(url);

	}

}




//  (version 9 : 53.0, no super bit)
 module org.seleniumhq.selenium.api  {
  // Version: 

  requires java.base;
  requires java.management;
  requires transitive java.logging;

  exports org.openqa.selenium;
  exports org.openqa.selenium.federatedcredentialmanagement;
  exports org.openqa.selenium.html5;
  exports org.openqa.selenium.interactions;
  exports org.openqa.selenium.internal;
  exports org.openqa.selenium.logging;
  exports org.openqa.selenium.logging.profiler;
  exports org.openqa.selenium.mobile;
  exports org.openqa.selenium.net;
  exports org.openqa.selenium.print;
  exports org.openqa.selenium.virtualauthenticator;

  opens org.openqa.selenium.logging to org.openqa.selenium.json;
  opens org.openqa.selenium.mobile to org.openqa.selenium.json;
  opens org.openqa.selenium.virtualauthenticator to org.openqa.selenium.json;
  opens org.openqa.selenium.interactions to org.openqa.selenium.json;
  opens org.openqa.selenium.print to org.openqa.selenium.json;
  opens org.openqa.selenium.net to org.openqa.selenium.json;
  opens org.openqa.selenium.html5 to org.openqa.selenium.json;
  opens org.openqa.selenium.federatedcredentialmanagement to org.openqa.selenium.json;
  opens org.openqa.selenium.internal to org.openqa.selenium.json;
  opens org.openqa.selenium to org.openqa.selenium.json;
  opens org.openqa.selenium.logging.profiler to org.openqa.selenium.json;
```

### Relevant log output

```shell
Exception in thread "main" java.lang.IllegalAccessError: class org.openqa.selenium.remote.service.DriverService$Builder (in module org.seleniumhq.selenium.remote_driver) cannot access class com.google.common.io.ByteStreams (in unnamed module @0x1f021e6c) because module org.seleniumhq.selenium.remote_driver does not read unnamed module @0x1f021e6c
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.service.DriverService$Builder.parseLogOutput(DriverService.java:472)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriverService$Builder.loadSystemProperties(ChromeDriverService.java:257)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:495)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:137)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:51)
        at t HelloChrome/com.Chrome.auto.main(auto.java:21)
```

### Operating System

Mac M1

### Selenium version

Java 4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

Version 117.0.5938.132 (Official Build) (arm64)

### Are you using Selenium Grid?

4.13.0

**Comment by titusfortner** [comment]
What build tool are you using?

**Comment by diemol** [comment]
I will close this as we did not get more information from the OP.
