### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by rajeshsrinivas1991** [SeleniumHQ/selenium#12867]
### What happened?

Hi, I am seeing this error since a month now. Running 4.13 version of selenium with OpenJDK 17 and TestNG with POM

Issue comes only with Chrome and CFT and with Firefox too

Below is the full log

org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.6', java.version: '17.0.8.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [1ddeb631ff39948cf1e952fe0b830fec, clickElement {id=257A9E3168B91396320569FC114382F4_element_526}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 117.0.5938.149, chrome: {chromedriverVersion: 117.0.5938.92 (67649b10b92b..., userDataDir: /var/folders/r4/rlfbnf8n0jl...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62718}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:62718/devtoo..., se:cdpVersion: 117.0.5938.149, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on mac (1ddeb631ff39948cf1e952fe0b830fec)] -> xpath: //a[@class='signOut']]
Session ID: 1ddeb631ff39948cf1e952fe0b830fec

	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:96)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:188)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:224)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at jdk.proxy2/jdk.proxy2.$Proxy18.click(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:816)
	at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:785)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:761)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:806)
	at org.testng.TestRunner.run(TestRunner.java:601)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 50 more

### What browsers and operating systems are you seeing the problem on?

Using Mac OS Ventura 13.6
Chrome Version 117.0.5938.149 (Official Build) (x86_64)

**Comment by titusfortner** [comment]
Can you turn on logging - https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by rajeshsrinivas1991** [comment]
> Can you turn on logging - https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

Hi @titusfortner  thanks for replying quick, i have enabled logging at INFO level and saw the same issue coming at AfterTest method of TestNG Annotations. Below is the logs, i can give the full test run logs but it contains some sensitive info so i am not authorised to share it here.


`2023-10-04 22:13:23 FINE Selenium [RemoteWebDriver] Executing: findElement [3844733b36a4072d5b12fddb1cf5ea79, findElement {using=xpath, value=//div[@class='headerContent']/nav/div/button}] 
2023-10-04 22:13:23 FINE Selenium [W3CHttpResponseCodec decode] Decoding response. Response code was: 200 and content: {"value":{"element-6066-11e4-a52e-4f735466cecf":"29AFE2C590983DB67AABEF5744E53673_element_519"}} 
2023-10-04 22:13:23 FINE Selenium [RemoteWebDriver] Executed: findElement (Response: SessionID: 3844733b36a4072d5b12fddb1cf5ea79, State: success, Value: {element-6066-11e4-a52e-4f735466cecf=29AFE2C590983DB67AABEF5744E53673_element_519}) 
2023-10-04 22:13:23 FINE Selenium [RemoteWebDriver] Executing: isElementDisplayed [3844733b36a4072d5b12fddb1cf5ea79, isElementDisplayed {id=29AFE2C590983DB67AABEF5744E53673_element_519}] 
2023-10-04 22:13:23 FINE Selenium [W3CHttpResponseCodec decode] Decoding response. Response code was: 200 and content: {"value":true} 
2023-10-04 22:13:23 FINE Selenium [RemoteWebDriver] Executed: isElementDisplayed (Response: SessionID: 3844733b36a4072d5b12fddb1cf5ea79, State: success, Value: true) 
2023-10-04 22:13:23 FINE Selenium [RemoteWebDriver] Executing: actions [3844733b36a4072d5b12fddb1cf5ea79, actions {actions=[org.openqa.selenium.interactions.Sequence@3337d04c]}] 
2023-10-04 22:13:23 FINE Selenium [RemoteWebDriver] Executing: findElement [3844733b36a4072d5b12fddb1cf5ea79, findElement {using=xpath, value=//div[@class='headerContent']/nav/div/button}] 
2023-10-04 22:13:23 FINE Selenium [W3CHttpResponseCodec decode] Decoding response. Response code was: 200 and content: {"value":{"element-6066-11e4-a52e-4f735466cecf":"29AFE2C590983DB67AABEF5744E53673_element_519"}} 
2023-10-04 22:13:23 FINE Selenium [RemoteWebDriver] Executed: findElement (Response: SessionID: 3844733b36a4072d5b12fddb1cf5ea79, State: success, Value: {element-6066-11e4-a52e-4f735466cecf=29AFE2C590983DB67AABEF5744E53673_element_519}) 
2023-10-04 22:13:23 FINE Selenium [W3CHttpResponseCodec decode] Decoding response. Response code was: 200 and content: {"value":null} 
2023-10-04 22:13:23 FINE Selenium [RemoteWebDriver] Executed: actions (Response: SessionID: 3844733b36a4072d5b12fddb1cf5ea79, State: success, Value: null) 
2023-10-04 22:13:24 FINE Selenium [RemoteWebDriver] Executing: findElement [3844733b36a4072d5b12fddb1cf5ea79, findElement {using=xpath, value=//a[@class='signOut']}] 
2023-10-04 22:13:24 FINE Selenium [W3CHttpResponseCodec decode] Decoding response. Response code was: 200 and content: {"value":{"element-6066-11e4-a52e-4f735466cecf":"29AFE2C590983DB67AABEF5744E53673_element_520"}} 
2023-10-04 22:13:24 FINE Selenium [RemoteWebDriver] Executed: findElement (Response: SessionID: 3844733b36a4072d5b12fddb1cf5ea79, State: success, Value: {element-6066-11e4-a52e-4f735466cecf=29AFE2C590983DB67AABEF5744E53673_element_520}) 
2023-10-04 22:13:24 FINE Selenium [RemoteWebDriver] Executing: clickElement [3844733b36a4072d5b12fddb1cf5ea79, clickElement {id=29AFE2C590983DB67AABEF5744E53673_element_520}] 
2023-10-04 22:16:24 FINE Selenium [RemoteWebDriver] Exception: clickElement java.util.concurrent.TimeoutException
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.6', java.version: '17.0.8.1'
Driver info: driver.version: RemoteWebDriver 

org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.6', java.version: '17.0.8.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3844733b36a4072d5b12fddb1cf5ea79, clickElement {id=29AFE2C590983DB67AABEF5744E53673_element_520}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 117.0.5938.149, chrome: {chromedriverVersion: 117.0.5938.92 (67649b10b92b..., userDataDir: /var/folders/r4/rlfbnf8n0jl...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49195}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:49195/devtoo..., se:cdpVersion: 117.0.5938.149, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on mac (3844733b36a4072d5b12fddb1cf5ea79)] -> xpath: //a[@class='signOut']]
Session ID: 3844733b36a4072d5b12fddb1cf5ea79

	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:96)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:188)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:224)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at jdk.proxy2/jdk.proxy2.$Proxy18.click(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:816)
	at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:785)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:761)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:806)
	at org.testng.TestRunner.run(TestRunner.java:601)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 50 more`

**Comment by titusfortner** [comment]
Selenium is clicking on the button and the action is timing out after 3 minutes.

This looks like an actual bug in your application or a problem with your network. For some reason the browser does not finish loading after the click so the driver does not send anything back to the user.

You can turn on the logs for the drivers and see if there is any more information (I created a library to make this easier: https://github.com/titusfortner/selenium-logger#driver-usage)

But either way there isn't an issue with Selenium code to fix.

**Comment by rajeshsrinivas1991** [comment]
> Selenium is clicking on the button and the action is timing out after 3 minutes.
> 
> This looks like an actual bug in your application or a problem with your network. For some reason the browser does not finish loading after the click so the driver does not send anything back to the user.
> 
> You can turn on the logs for the drivers and see if there is any more information (I created a library to make this easier: https://github.com/titusfortner/selenium-logger#driver-usage)
> 
> But either way there isn't an issue with Selenium code to fix.

Thanks @titusfortner, I'll check from the driver level by enabling logs. Have a nice day :)
