### ISSUE TITLE
Exception thrown by selenium-webdriver version 2.48.x

### ISSUE THREAD

**Issue by tempoc** [SeleniumHQ/selenium#1286]
See http://stackoverflow.com/questions/33433914/error-using-selenium-js-chrome-webdriver

```shell
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.20/chromedriver_mac32.zip...
chromedriver_2.20.zip downloaded to /Users/blah/projects/mine/amo-ui/node_modules/gulp-protractor/node_modules/protractor/selenium/chromedriver_2.20.zip
selenium-server-standalone-2.48.2.jar downloaded to /Users/blah/projects/mine/amo-ui/node_modules/gulp-protractor/node_modules/protractor/selenium/selenium-server-standalone-2.48.2.jar
```

```shell
undefined:1190
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/Users/blah/projects/mine/amo-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/Users/blah/projects/mine/amo-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /Users/blah/projects/mine/amo-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Object.Context.closure.goog.retrieveAndExecModule_ (/Users/blah/projects/mine/amo-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/Users/blah/projects/mine/amo-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/Users/blah/projects/mine/amo-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/Users/blah/projects/mine/amo-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
```

Node version: v0.12.4

**Comment by jleyba** [comment]
Run with --harmony. First bullet point on the 2.48.0 release notes:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v2480
