### ISSUE TITLE
[🐛 Bug]: Unable to open two browser instances while using the same user profile path

### ISSUE THREAD

**Issue by IamHarsimranjeet** [SeleniumHQ/selenium#12889]
### What happened?

We are using C# selenium driver. When we try to open two different browsers instances using the same user profile path (via user-data-dir argument) we got an exception as 
session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (SessionNotCreated)

### How can we reproduce the issue?

```shell
Here is a small sample code to reproduce the issue. The exception is thrown on the second call to StartNewDriver() method.

IWebDriver driver1 = StartNewDriver();
IWebDriver driver2 = StartNewDriver();

driver1.Quit();
driver2.Quit();

static IWebDriver StartNewDriver()
{
    string? path = Directory.GetParent(Environment.CurrentDirectory)?.Parent?.Parent?.FullName;
    ChromeOptions chromeOptions = new();
    string userProfilePath = @"C:\Users\harsisin\AppData\Local\Google\Chrome\User Data\Profile 1";
    chromeOptions.AddArguments("user-data-dir=" + userProfilePath);
    IWebDriver driver = new ChromeDriver(chromeDriverDirectory: path + @"\drivers\", chromeOptions);
    return driver;
}
```

### Relevant log output

```shell
System.InvalidOperationException
  HResult=0x80131509
  Message=session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (SessionNotCreated)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at Program.<<Main>$>g__StartNewDriver|0_0() in C:\Users\harsisin\source\repos\TestConsole\TestConsole\Program.cs:line 17
   at Program.<Main>$(String[] args) in C:\Users\harsisin\source\repos\TestConsole\TestConsole\Program.cs:line 6
```

### Operating System

Windows 10

### Selenium version

C# 4.13.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117

**Comment by titusfortner** [comment]
The error is a Chromedriver bug, they've given this suggestion: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35
