### ISSUE TITLE
[🐛 Bug]: 4.14.0 compiled with Java 11

### ISSUE THREAD

**Issue by xtianus** [SeleniumHQ/selenium#12915]
### What happened?

4.14.0 has been compiled with Java 11 so I get this error when running with Java 8:

`Caused by: java.lang.UnsupportedClassVersionError: org/openqa/selenium/TimeoutException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [org.openqa.selenium.TimeoutException])
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2397)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:855)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467)
	... 25 common frames omitted
`

### How can we reproduce the issue?

```shell
Run with java 8
```

### Relevant log output

```shell
Caused by: java.lang.UnsupportedClassVersionError: org/openqa/selenium/TimeoutException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [org.openqa.selenium.TimeoutException])
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2397)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:855)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467)
	... 25 common frames omitted
```

### Operating System

Windows 10

### Selenium version

Java 4.14.0

### What are the browser(s) and version(s) where you see this issue?

---

### What are the browser driver(s) and version(s) where you see this issue?

---

**Comment by xtianus** [comment]
I see that Java JDK version 11 or greater is a requirement now. Closing issue.
