### ISSUE TITLE
[Selenium Manager failed to handle the driver management??? 🐛 Bug]: 

### ISSUE THREAD

**Issue by Gray-Falcon** [SeleniumHQ/selenium#12931]
### Webdriver should be handled automatically???

"If you're using Selenium version 4.12.0 or newer, and you're relying on Selenium Manager to handle the driver management"
script:
```
import logging
from selenium import webdriver

# Configure logging to capture all levels
logging.basicConfig(level=logging.DEBUG)  # Set the logging level to DEBUG

# Get the logger for 'selenium'
logger = logging.getLogger('selenium')

# Instantiate Chrome webdriver
driver = webdriver.Chrome()

# Open a website
driver.get("https://www.google.com/")
```
if im understanding this correctly, i cant execute script because webdriver is missing, even it should be handled automatically? 

### How can we reproduce the issue?

```shell
well i dont really know whats happening, i tested same script on my windows machine and its working normally,

i have same selenium version on both machines
im using chromium and chrome on my win machine but that shouldn't be the problem?
```

### Relevant log output

```shell
console log:

ubuntu@instance-20230620-2312:~/bot$  xvfb-run --server-args="-screen 0 1920x1080x24" python3 AiSupport.py
DEBUG:selenium.webdriver.common.selenium_manager:Selenium Manager binary found at: /home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG:selenium.webdriver.common.selenium_manager:Executing process: /home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 129, in run
    completed_proc = subprocess.run(args, capture_output=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 98, in driver_location
    output = self.run(args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 135, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/bot/AiSupport.py", line 11, in <module>
    driver = webdriver.Chrome()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```
```


### Operating System

Ubuntu aarch64 aarch64 aarch64 GNU/Linux headless

### Selenium version

python selenium Version: 4.14.0

### What are the browser(s) and version(s) where you see this issue?

Chromium 117.0.5938.149 snap

### What are the browser driver(s) and version(s) where you see this issue?

drivers should be handled automatically?!, but i have chromium-chromedriver newest version (1:85.0.4183.83-0ubuntu2.22.04.1) but it seems lagged, i cant get it to default system path no matter what i do

### Are you using Selenium Grid?

not sure how to find out on headless machine

**Comment by Gray-Falcon** [comment]
im banging my head for 3 days now i just dont underestand why is this happening :(((

**Comment by AutomatedTester** [comment]
My guess is that because Chrome doesn't have an arm64 Linux build on https://googlechromelabs.github.io/chrome-for-testing/#stable we can't find anything and then revert to the old way... and can't find anything. 

I think we need @bonigarcia opinion here but that's what I think is the issue

**Comment by Gray-Falcon** [comment]
can i somehow make it work?

**Comment by titusfortner** [comment]
We do not support aarch64 on linux right now. See https://www.selenium.dev/documentation/selenium_manager/#alternative-architecture

Even if we built one, we could only support Firefox since that's the only browser that releases an officially compatible driver.
