### ISSUE TITLE
[🐛 Bug]: Unable to obtain chrome using Selenium Manager. Issue on corporate Virtual Machine

### ISSUE THREAD

**Issue by YoungerThuggg** [SeleniumHQ/selenium#12944]
### What happened?

I have updated to the latest version of Selenium to be able to use selenium manager and not have to use a webdrivermanager package to manage the chromedriver.exe files. When I try to run IWebDriver Driver = new ChromeDriver(); I get an exception saying that selenium is unable to obtain chrome using selenium manager. This happens on the virtual machines that I test with but not my local machine

### How can we reproduce the issue?

```shell
IWebDriver Driver = new ChromeDriver();
```

### Relevant log output

```shell
Exception:
OpenQA.Selenium.NoSuchDriverException: Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location ---> OpenQA.Selenium.WebDriverException: Error starting process: \\...\Debug\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --output json ---> OpenQA.Selenium.WebDriverException: Selenium Manager process exited abnormally with 65 code: \\...\Debug\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --output json
Standard Output >>

   at OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments)
   at OpenQA.Selenium.SeleniumManager.DriverPath(DriverOptions options)
   at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
   at OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor()
   at SharedClasses.PatchTest.LaunchBrowser(BrowserType browser) in C:\DTCDev\Repos\ARCQA\ARCQA\PatchTestAutomation\SharedClasses\PatchTest.cs:line 1864
Stack Trace:
   at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
   at OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor()
{
  "logs": [
    {
      "level": "ERROR",
      "timestamp": 1697134586,
      "message": "error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)"
    }
  ],
  "result": {
    "code": 65,
    "message": "error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)",
    "driver_path": "",
    "browser_path": ""
  }
}
```

### Operating System

Windows 11

### Selenium version

C# 4.14.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 118.0.5993.71

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 118.0.5993.70

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
> tcp connect error: No connection could be made

You need to make sure your VM might be going through a proxy in a way that your normal system is not?
Either way it's a network issue with your VM, and nothing for Selenium code to fix.

**Comment by ChristialPro** [comment]
Hey guys, im having this same issue except im not using a VM: I've tried to use chatGPT to help me trouble shoot for 3 days to no avail, I've double checked to see if my drivers are all updated, checked to see if my dependencies are correct, etc. Pleasee help. 

I ran this code:  npx mocha tests/firstTest.js 

Here's my output :) 

1) successfully adds a todo to application


  0 passing (952ms)
  1 failing

  1) Selenium Tests
       successfully adds a todo to application:
     WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=118.0.5993.70)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
      at async Context.<anonymous> (tests/firstTest.js:24:5)


ChatGPT says: 

1. throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15): This indicates that an error was thrown in the Selenium WebDriver library. The specific function throwDecodedError in the error.js module is where the error occurred.

I told her this: If you don't have a module called error.js in your project, then the reference to error.js in the stack trace is likely coming from the internal implementation of the Selenium WebDriver library. The error you're encountering is not in your own code but rather in the Selenium WebDriver library itself. This could be due to various reasons, including compatibility issues with specific versions of WebDriver, browsers, or underlying dependencies.

**Comment by ChristialPro** [comment]
Hii update, so I realized I need to update my npm because of the Oct 4th thing, I'm still having trouble updating to the current version not sure which steps im doing wrong pls help: 

1. I made myself as a root by executing this code: sudo chown -R $(whoami) ~/.npm 

2. then I ran:  sudo code --user-data-dir="~/.vscode-root"
3. then I ran: npm install -g npm@latest
