### ISSUE TITLE
[🐛 Bug]:  Can not execute tests on Selenium Grid

### ISSUE THREAD

**Issue by youvegotnigel** [SeleniumHQ/selenium#12965]
### What happened?

When I execute a simple test on Selenium Grid, I get this error.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 18, 2023 4:32:02 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. java.io.IOException: HTTP/1.1 header parser received no bytes 
Host info: host: '60bfcb5af633', ip: '192.168.144.2'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-78-generic', java.version: '11.0.20.1'
Driver info: driver.version: unknown
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, browserVersion: 118.0, goog:chromeOptions: {args: [--remote-allow-origins=*, --start-maximized], extensions: []}, platformName: linux}]}]
Capabilities {browserName: chrome, browserVersion: 118.0, goog:chromeOptions: {args: [--remote-allow-origins=*, --start-maximized], extensions: []}, platformName: linux}

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:163)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at com.vh.auto.team.basics.selenium_grid.SeleniumGridTest.setup(SeleniumGridTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
	at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:663)
	at org.testng.TestRunner.beforeRun(TestRunner.java:652)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
```

However when I execute it using WebDriver there is no any issues.

Please find the error log attached of the selenium grid
```
C:\dev\selenium-grid>java -jar selenium-server-4.14.0.jar standalone --selenium-manager true
16:12:54.094 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
16:12:54.104 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:12:56.124 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
16:12:58.747 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","platformName": "Windows 10"} 8 times
16:12:58.748 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox","platformName": "Windows 10"} 8 times
16:12:58.750 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge","platformName": "Windows 10"} 8 times
16:12:58.752 INFO [NodeOptions.report] - Adding Internet Explorer for {"browserName": "internet explorer","platformName": "Windows 10"} 1 times
16:12:58.796 INFO [Node.<init>] - Binding additional locator mechanisms: relative
16:12:58.834 INFO [GridModel.setAvailability] - Switching Node ba8cf78b-9ad7-47e9-b4cc-0478a1b51a52 (uri: http://192.168.1.2:4444) from DOWN to UP
16:12:58.835 INFO [LocalDistributor.add] - Added node ba8cf78b-9ad7-47e9-b4cc-0478a1b51a52 at http://192.168.1.2:4444. Health check every 120s
16:12:59.433 INFO [Standalone.execute] - Started Selenium Standalone 4.14.0 (revision e5a96349ce): http://192.168.1.2:4444
16:18:15.913 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "5270e85ea8702883452afde908f03708","eventTime": 1697626095906369100,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "192.168.1.2:4444","http.method": "POST","http.request_content_length": "355","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.12.1 (java windows)"}}

16:24:30.496 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "c3420c919eeca41e18173af841996d02","eventTime": 1697626470495663000,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "192.168.1.2:4444","http.method": "POST","http.request_content_length": "355","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.12.1 (java windows)"}}
```

NOTE:
After this issue accord we also got an alert from Sentinel One (EDR tool)

![image](https://github.com/SeleniumHQ/selenium/assets/48122863/6d42c0e0-d742-48b3-a70f-b0815498a15c)

### How can we reproduce the issue?

```shell
Start selenium grid 4.14.0


Try to run this test
`

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.edge.EdgeOptions;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.Assert;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.AfterTest;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;

public class SeleniumGridTest {

    private static final ThreadLocal<WebDriver> driver = new ThreadLocal<>();
    private static final String REMOTE_URL = "http://localhost:4444";
    private static final By USERNAME_TEXT_BOX = By.id("user-name");
    private static final By PASSWORD_TEXT_BOX = By.id("password");
    private static final By LOGIN_BUTTON = By.id("login-button");
    private static final By BACKPACK_BUTTON = By.cssSelector("[data-test=add-to-cart-sauce-labs-backpack]");
    private static final By BIKE_LIGHT_BUTTON = By.cssSelector("[data-test=add-to-cart-sauce-labs-bike-light]");
    private static final By CART_ITEMS = By.cssSelector(".shopping_cart_badge");
    private static final By SHOPPING_CART_BUTTON = By.id("shopping_cart_container");
    private static final By CHECKOUT_BUTTON = By.id("checkout");
    private static final By CONTINUE_BUTTON = By.id("continue");
    private static final By FINISH_BUTTON = By.id("finish");


    //@Parameters({"browser", "browser_version"})
    @BeforeTest
    //private void setup(String browser, String version) {
    private void setup() {

        String browser = "chrome";

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setPlatform(Platform.LINUX);
        capabilities.setBrowserName(browser); //MicrosoftEdge, chrome, firefox
        capabilities.setVersion("118.0");
        switch (browser) {

            case "chrome":
                ChromeOptions chromeOptions = new ChromeOptions();
                chromeOptions.addArguments("--start-maximized");
                capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
                break;

            case "firefox":
                FirefoxOptions firefoxOptions = new FirefoxOptions();
                //firefoxOptions.addArguments("-headless");
                firefoxOptions.addArguments("--start-maximized");
                capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, firefoxOptions);
                break;

            case "MicrosoftEdge":
                EdgeOptions edgeOptions = new EdgeOptions();
                edgeOptions.addArguments("--start-maximized");
                capabilities.setCapability(EdgeOptions.CAPABILITY, edgeOptions);
                break;
        }

        // Create a RemoteWebDriver instance with the Selenium Grid URL and desired capabilities
        try {
            driver.set(new RemoteWebDriver(new URL(REMOTE_URL), capabilities));
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }

        // Navigate to the login page
        getDriver().get("https://www.saucedemo.com/");
        getDriver().manage().window().maximize();

        // getDriver().manage().window().setSize(new Dimension(1440, 900));
    }

    //@Parameters("browser")
    @Test
    public void login_test() {

        getDriver().findElement(USERNAME_TEXT_BOX).sendKeys("standard_user");
        getDriver().findElement(PASSWORD_TEXT_BOX).sendKeys("secret_sauce");
        getDriver().findElement(LOGIN_BUTTON).click();

        Assert.assertEquals(getDriver().getCurrentUrl(), "https://www.saucedemo.com/inventory.html"); // verify landing page
    }

    //@Parameters("browser")
    @Test
    public void add_to_cart_test() {
        getDriver().findElement(BACKPACK_BUTTON).click(); // add backpack to cart
        getDriver().findElement(BIKE_LIGHT_BUTTON).click(); // add bike light to cart
        String totalItems = getDriver().findElement(CART_ITEMS).getText().trim();

        Assert.assertEquals(totalItems, "2"); // verify items added to cart
    }

    //@Parameters("browser")
    @Test
    public void checkout_test() {
        getDriver().findElement(SHOPPING_CART_BUTTON).click();
        getDriver().findElement(CHECKOUT_BUTTON).click();

        fillCheckoutInformation("First Name", "John");
        fillCheckoutInformation("Last Name", "Taylor");
        fillCheckoutInformation("Zip/Postal Code", "60611");
        getDriver().findElement(CONTINUE_BUTTON).click();

        Assert.assertEquals(getAmountForLabel(".summary_subtotal_label"), "Item total: $39.98");
        Assert.assertEquals(getAmountForLabel(".summary_tax_label"), "Tax: $3.20");
        Assert.assertEquals(getAmountForLabel(".summary_info_label.summary_total_label"), "Total: $43.18");
    }

    //@Parameters("browser")
    @Test
    public void complete_checkout_test() {
        getDriver().findElement(FINISH_BUTTON).click();

        Assert.assertEquals(getDriver().getCurrentUrl(), "https://www.saucedemo.com/checkout-complete.html"); // verify landing page
        Assert.assertEquals(getDriver().findElement(By.xpath("//h2")).getText().trim(), "Thank you for your order!");
    }

    private void fillCheckoutInformation(String question, String answer) {
        String xpath = String.format("//input[@placeholder='%s']", question);
        getDriver().findElement(By.xpath(xpath)).sendKeys(answer);
    }

    private String getAmountForLabel(String label) {
        return getDriver().findElement(By.cssSelector(label)).getText().trim();
    }

    private static WebDriver getDriver() {
        return driver.get();
    }

    @AfterTest
    private void teardown() {
        getDriver().quit();
        driver.remove();
    }
}

```

### Relevant log output

```shell
***************************** SELENIUM GRID LOG ***************************************************
selenium-hub    | 11:01:49.368 INFO [GridModel.setAvailability] - Switching Node 687c6bc7-52d0-4281-9541-f7b2e52495ee (uri: http://192.168.144.6:5555) from DOWN to UP
selenium-hub    | 11:01:49.370 INFO [LocalDistributor.add] - Added node 687c6bc7-52d0-4281-9541-f7b2e52495ee at http://192.168.144.6:5555. Health check every 120s
edge_1          | 11:01:49.377 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
selenium-hub    | 11:02:04.647 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
selenium-hub    |  [Capabilities {browserName: chrome, browserVersion: 118.0, goog:chromeOptions: {args: [--remote-allow-origins=*, --start-maximized], extensions: []}, platformName: linux}]
chrome_1        | 11:02:05.354 WARN [SeleniumManager.lambda$runCommand$1] - Exception managing chrome: Unable to discover proper chromedriver version in offline mode
selenium-hub    | 11:02:06.599 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "14367e78ac3a4984da45bdb4232e6caa","eventTime": 1697626924645581762,"eventName": "Session request received by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, browserVersion: 118.0, goog:chromeOptions: {args: [--remote-allow-origins=*, --start-maximized], extensions: []}, platformName: linux}]"}}
selenium-hub    |
selenium-hub    | 11:02:06.599 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. java.io.IOException: HTTP/1.1 header parser received no bytes
selenium-hub    | Host info: host: '60bfcb5af633', ip: '192.168.144.2'
selenium-hub    | Build info: version: '4.14.1', revision: '03f8ede370'
selenium-hub    | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-78-generic', java.version: '11.0.20.1'
selenium-hub    | Driver info: driver.version: unknown
selenium-hub    | 11:02:06.599 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. java.io.IOException: HTTP/1.1 header parser received no bytes
selenium-hub    | Host info: host: '60bfcb5af633', ip: '192.168.144.2'
selenium-hub    | Build info: version: '4.14.1', revision: '03f8ede370'
selenium-hub    | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-78-generic', java.version: '11.0.20.1'
selenium-hub    | Driver info: driver.version: unknown
selenium-hub    |       at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:648)
selenium-hub    |       at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:563)
selenium-hub    |       at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:823)
selenium-hub    |       at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:783)
selenium-hub    |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
selenium-hub    |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
selenium-hub    |       at java.base/java.lang.Thread.run(Thread.java:829)
selenium-hub    | Caused by: java.io.UncheckedIOException: java.io.IOException: HTTP/1.1 header parser received no bytes
selenium-hub    |       at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:443)
selenium-hub    |       at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
selenium-hub    |       at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
selenium-hub    |       at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:359)
selenium-hub    |       at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
selenium-hub    |       at org.openqa.selenium.grid.security.AddSecretFilter.lambda$apply$0(AddSecretFilter.java:40)
selenium-hub    |       at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
selenium-hub    |       at org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:129)
selenium-hub    |       at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:644)
selenium-hub    |       ... 6 more
selenium-hub    | Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
selenium-hub    |       at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:327)
selenium-hub    |       at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:673)
selenium-hub    |       at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:297)
selenium-hub    |       at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:263)
selenium-hub    |       at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
selenium-hub    |       at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
selenium-hub    |       at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
selenium-hub    |       ... 3 more
selenium-hub    | Caused by: java.io.EOFException: EOF reached while reading
selenium-hub    |       at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:591)
selenium-hub    |       at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:632)
selenium-hub    |       at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:833)
selenium-hub    |       at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
selenium-hub    |       at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
selenium-hub    |       at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
selenium-hub    |       at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
selenium-hub    |       at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:763)
selenium-hub    |       at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:941)
selenium-hub    |       at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:245)
selenium-hub    |       at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
selenium-hub    |       at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
selenium-hub    |       at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
selenium-hub    |       at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)
selenium-hub    |
selenium-hub    | 11:02:06.600 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "14367e78ac3a4984da45bdb4232e6caa","eventTime": 1697626926595102059,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. java.io.IOException: HTTP\u002f1.1 header parser received no bytes \nHost info: host: '60bfcb5af633', ip: '192.168.144.2'\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-78-generic', java.version: '11.0.20.1'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. java.io.IOException: HTTP\u002f1.1 header parser received no bytes \nHost info: host: '60bfcb5af633', ip: '192.168.144.2'\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-78-generic', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:648)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:563)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:823)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:783)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: java.io.UncheckedIOException: java.io.IOException: HTTP\u002f1.1 header parser received no bytes\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:443)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:359)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)\n\tat org.openqa.selenium.grid.security.AddSecretFilter.lambda$apply$0(AddSecretFilter.java:40)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)\n\tat org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:129)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:644)\n\t... 6 more\nCaused by: java.io.IOException: HTTP\u002f1.1 header parser received no bytes\n\tat java.net.http\u002fjdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:327)\n\tat java.net.http\u002fjdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:673)\n\tat java.net.http\u002fjdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:297)\n\tat java.net.http\u002fjdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:263)\n\tat java.net.http\u002fjdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)\n\tat java.net.http\u002fjdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)\n\tat java.net.http\u002fjdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)\n\t... 3 more\nCaused by: java.io.EOFException: EOF reached while reading\n\tat java.net.http\u002fjdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:591)\n\tat java.net.http\u002fjdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:632)\n\tat java.net.http\u002fjdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:833)\n\tat java.net.http\u002fjdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)\n\tat java.net.http\u002fjdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)\n\tat java.net.http\u002fjdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)\n\tat java.net.http\u002fjdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)\n\tat java.net.http\u002fjdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:763)\n\tat java.net.http\u002fjdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:941)\n\tat java.net.http\u002fjdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:245)\n\tat java.net.http\u002fjdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)\n\tat java.net.http\u002fjdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)\n\tat java.base\u002fjava.util.ArrayList.forEach(ArrayList.java:1541)\n\tat java.net.http\u002fjdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, browserVersion: 118.0, goog:chromeOptions: {args: [--remote-allow-origins=*, --start-maximized], extensions: []}, platformName: linux}]"}}
selenium-hub    |
selenium-hub    | 11:02:06.608 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "14367e78ac3a4984da45bdb4232e6caa","eventTime": 1697626926606680085,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "10.127.91.203:4444","http.method": "POST","http.request_content_length": "355","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.12.1 (java windows)"}}
selenium-hub    |
selenium_grid_chrome_1 exited with code 137
```

### Operating System

Windows 10

### Selenium version

Java - 4.12.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 118

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 118

### Are you using Selenium Grid?

4.14.0

**Comment by diemol** [comment]
Your environment is blocking what Selenium Manager is doing. Also, from the alert you are showing. When did this start happening? Or are you trying it for the first time?

What does "However when I execute it using WebDriver there is no any issues.", mean?

**Comment by youvegotnigel** [comment]
Hi @diemol 

The organization enviroment is not blocking anything.

This is the first time this happened and I noticed it maybe about 4 hours ago.

Previously all our tests were working fine running on the Selenium grid.


`What does "However when I execute it using WebDriver there is no any issues.", mean?`  --
When I run my test in my local machine without using Remote WebDriver, there is no any issue. 

But when I run the same test on Selenium Grid I get the above errors and test test does not even start.

**Comment by youvegotnigel** [comment]
To reproduce this issue.

I started  selenium grid (I used standalone 4.14)
And ran this test

```java
@Test
    public void test() throws MalformedURLException {

        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--start-maximized");

        DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setPlatform(Platform.ANY);
        capabilities.setBrowserName("chrome");
        capabilities.setVersion("118.0");
        capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

        WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), capabilities);
        driver.get("https://www.google.com");
        driver.quit();
    }
```

I got this error in the logs

```bash
18:15:13.420 INFO [Standalone.execute] - Started Selenium Standalone 4.14.0 (revision e5a96349ce): http://192.168.1.6:4444
18:21:51.135 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "3982bdf69ea35c0875c8412e6077da08","eventTime": 1697633511127003500,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "314","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.14.0 (java windows)"}}`
```

Please let me know if I'm doing something wrong here.

**Comment by diemol** [comment]
You can put all this:
```
    capabilities.setPlatform(Platform.ANY);
    capabilities.setBrowserName("chrome");
    capabilities.setVersion("118.0");
```

in `ChromeOptions` and get rid of `DesiredCapabilities`. 

If you do not have Chrome 118 installed on the Grid machine, Selenium Manager will download it and this can slow down things. 

To continue, please double-check your environment works, as the Sentinel alter makes me doubt.

**Comment by youvegotnigel** [comment]
Hi @diemol 

I've changed the code as you mentioned but I got the same result.
On my personal laptop, I do not have Sentinel installed so it should not have any effect now. 

```java
 @Test
    public void test() throws MalformedURLException {

        ChromeOptions chromeOptions = new ChromeOptions();

        chromeOptions.addArguments("--start-maximized");
        chromeOptions.setCapability(CapabilityType.PLATFORM_NAME, Platform.ANY.name());
        chromeOptions.setCapability(CapabilityType.BROWSER_NAME, Browser.CHROME.browserName());
        chromeOptions.setCapability(CapabilityType.BROWSER_VERSION, "stable");

        WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), chromeOptions);
        driver.get("https://www.google.com");
        driver.quit();
    }
```

**Comment by diemol** [comment]
What was the issue?

**Comment by youvegotnigel** [comment]
Hi @diemol

After deleting all the previous docker containers and images and restarting my personal laptop, I was able to run the tests without any issues on the Grid.
But however, the above issue is still there on the server environment which I now suspect it is due the Sentinel One.
I maybe need to discuss this with our internal IT team more about this and resolve it.

Thank you for your help and time.
