### ISSUE TITLE
[🐛 Bug]: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by reyoreyo** [SeleniumHQ/selenium#12982]
### What happened?

10月 22, 2023 10:14:03 上午 org.openqa.selenium.remote.http.WebSocket$Listener onError
警告: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1178)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketT
ube.java:841)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.jav
a:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadab
le(SocketTube.java:782)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java
:965)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:1467)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:1412)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1412)

### How can we reproduce the issue?

```shell
10月 22, 2023 10:14:03 上午 org.openqa.selenium.remote.http.WebSocket$Listener onError
警告: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1178)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketT
ube.java:841)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.jav
a:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadab
le(SocketTube.java:782)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java
:965)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:1467)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:1412)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1412)
```

### Relevant log output

```shell
10月 22, 2023 10:14:03 上午 org.openqa.selenium.remote.http.WebSocket$Listener onError
警告: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1178)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketT
ube.java:841)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.jav
a:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadab
le(SocketTube.java:782)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java
:965)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:1467)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:1412)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1412)
```

### Operating System

Windows 10

### Selenium version

jdk21+selenium-server-4.14.1.jar

### What are the browser(s) and version(s) where you see this issue?

Chrome 已是最新版本 版本 118.0.5993.89（正式版本） （64 位）

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriverVersion：118.0.5993.70

### Are you using Selenium Grid?

selenium-server-4.14.1.jar

**Comment by reyoreyo** [comment]
2023-10-24 01:52:15=>start...http://basic.10jqka.com.cn/688693/concept.html
2023-10-24 01:52:15=>http://activity.10jqka.com.cn/acmake/cache/304.html?sessionId=183%2E67%2E61%2E212&info=&groupId=website_basic&isPc=true&reqType=&returnUrl=http%3A%2F%2Fbasic%2E10jqka%2Ecom%2Ecn%2F688693%2Fconcept%2Ehtml&acHost=%2F%2Fbasic%2E10jqka%2Ecom%2Ecn&sessionId=183%2E67%2E61%2E212&info=&groupId=website_basic&isPc=true&reqType=&returnUrl=http%3A%2F%2Fbasic%2E10jqka%2Ecom%2Ecn%2F688693%2Fconcept%2Ehtml&acHost=%2F%2Fbasic%2E10jqka%2Ecom%2Ecn
ChromeDriver was started successfully.
24-Oct-2023 01:52:35.292 警告 [pool-257-thread-3] org.openqa.selenium.remote.http.WebSocket$Listener.onError Connection reset
        java.net.SocketException: Connection reset
                at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
                at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
                at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1178)
                at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:841)
                at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
                at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
                at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
                at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
                at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:782)
                at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:965)
                at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
                at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:1467)
                at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:1412)
                at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
                at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1412)
2023-10-24 01:52:35=>success:http://basic.10jqka.com.cn/688693/concept.html

**Comment by reyoreyo** [comment]
the issue occurs after successfully accessing a page, where the program is redirected to a new webpage and then attempts to access elements on the new page

**Comment by reyoreyo** [comment]
The key issue here is that this phenomenon doesn't occur every time and has a certain level of randomness.

**Comment by pujagani** [comment]
> The key issue here is that this phenomenon doesn't occur every time and has a certain level of randomness.

Hence, it is crucial to have a reproducible test script. Only if we can reproduce the issue locally, can we help triage and fix it. Please provide the code snippet to reproduce the issue.

**Comment by reyoreyo** [comment]
```java
public boolean seleniumTest(String url, boolean headless) {
    ChromeDriverManager manager = ChromeDriverManager.INSTANCE;

    try {
        WebDriver driver = manager.getDriver(headless);
        driver.get(url);

        if (!headless) {
            driver.manage().window().maximize();
        }

        WebElement moveElement = Utils.waitWebElement(driver, By.id("slider"), 5);
        WebElement moveImgElement = Utils.waitWebElement(driver, By.id("slicaptcha-img"), 5);

        if (moveElement == null || moveImgElement == null) {
            return false;
        }

        int rand = RandomUtils.produceNumber(30);
        String bUrl = moveImgElement.getAttribute("src");
        File b = new File(SystemVar.webtempDir + "reyo_shadow_sign" + rand + ".jpg");
        Utils.downloadFile(bUrl, b);

        String bwidthStr = getAttributeWithoutDot(moveImgElement, "style", "width: ");
        int bwidth = Integer.parseInt(bwidthStr);

        String bheightStr = getAttributeWithoutDot(moveImgElement, "style", "height: ");
        int bheight = Integer.parseInt(bheightStr);

        WebElement moveBlockElement = Utils.waitWebElement(driver, By.id("slicaptcha-block"), 5);

        if (moveBlockElement == null) {
            return false;
        }

        String sUrl = moveBlockElement.getAttribute("src");
        File s = new File(SystemVar.webtempDir + "reyo_shadow_min" + rand + ".png");
        Utils.downloadFile(sUrl, s);

        int top = Integer.parseInt(getAttributeWithoutDot(moveBlockElement, "style", "top: "));
        int width = Integer.parseInt(getAttributeWithoutDot(moveBlockElement, "style", "width: "));
        int height = Integer.parseInt(getAttributeWithoutDot(moveBlockElement, "style", "height: "));

        int distance = (int) Double.parseDouble(getDistance(
            SystemVar.webtempDir + "reyo_shadow_sign" + rand + ".jpg",
            SystemVar.webtempDir + "reyo_shadow_min" + rand + ".png",
            bwidth, bheight, width, height, top, rand
        ));

        Utils.move(driver, moveElement, distance);
        Thread.sleep(3000);

//waiting for jump other page...
// the issue occurs after successfully accessing a page, where the program is redirected to a new webpage and then attempts to access elements on the new page

        WebElement btnElement = null;
        try {
            btnElement = driver.findElement(By.id("slicaptcha"));
        } catch (NoSuchElementException e) {
            // Ignore
        }

        return btnElement == null;
    } catch (Exception e) {
        System.out.println(DateTimeUtils.getCurrentTime() + "=>自动验证失败：" + e.toString());
        return false;
    } finally {
        manager.closeDriver();
    }
}

private String getAttributeWithoutDot(WebElement element, String attribute, String prefix) {
    String attributeValue = element.getAttribute(attribute);
    attributeValue = attributeValue.substring(attributeValue.indexOf(prefix) + prefix.length);
    if (attributeValue.contains(".")) {
        attributeValue = attributeValue.substring(0, attributeValue.indexOf("."));
    }
    return attributeValue;
}

```

**Comment by pujagani** [comment]
Thank you for sharing the example. However, it still contains some util classes used internally. I would appreciate if you could share minimum reproducible test script for us to reproduce the issue.

**Comment by reyoreyo** [comment]
Selenium-server-4.15.0 resolves this bug.

**Comment by reyoreyo** [comment]
How can I dismiss this prompt, or is it customizable?

11月 08, 2023 10:05:11 上午 org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
警告: Unable to find CDP implementation matching 119
11月 08, 2023 10:05:11 上午 org.openqa.selenium.chromium.ChromiumDriver lambda$new$5
警告: Unable to find version of CDP to use for 119.0.6045.106. You may need to include a dependency on a specifi
c version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.15.0` where t
he version ("v86") matches the version of the chromium-based browser you're using and the version number of th
e artifact is the same as Selenium's.

**Comment by titusfortner** [comment]
> How can I dismiss this prompt

Upgrade to Selenium 4.15 which supports 119 directly

**Comment by diemol** [comment]
I will close this as we did not get more information from the OP. We can reopen it in case more information is provided.
