### ISSUE TITLE
[🐛 Bug]:  Driver info: driver.version: unknown

### ISSUE THREAD

**Issue by soan1d** [SeleniumHQ/selenium#13062]
### What happened?

Hi  Selenium team,
I'm pretty new, I'm trying to execute this code to selenium grid by docker and get below erreur.
I spent the week to debug it, could you please help ? Selenium is running in my localhost

<img width="1284" alt="Screenshot 2023-10-29 at 11 21 17" src="https://github.com/SeleniumHQ/selenium/assets/47155665/90b501d1-e232-4ee8-b413-ff1bf82eae5b">

Thank you very much

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.firefox.options import Options as FirefoxOptions

options = Options()
cloud_options = {}
cloud_options['build'] = "build_1"
cloud_options['name'] = "test_abc"
options.set_capability('cloud:options', cloud_options)
driver = webdriver.Remote("http://localhost:4444/wd/hub", options=options)


try:
    # Accéder à une URL
    driver.get("https://www.example.com")

    # Effectuer des actions sur la page
    element = driver.find_element(By.ID, "exampleId")
    element.send_keys("Exemple de texte")
    element.send_keys(Keys.RETURN)

    # Attendre quelques secondes pour les résultats
    driver.implicitly_wait(10)

    # Autres actions et vérifications...

finally:
    # Fermer le navigateur à la fin des tests
    driver.quit()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/mennou/Dev/script.py", line 12, in <module>
    driver = webdriver.Remote("http://localhost:4444/wd/hub", options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'b7bd83bedd55', ip: '172.17.0.2'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.4.16-linuxkit', java.version: '11.0.20.1'
Driver info: driver.version: unknown
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.4.16-linuxkit', java.version: '11.0.20.1'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply (DriverServiceSessionFactory.java:225)
    at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply (DriverServiceSessionFactory.java:72)
    at org.openqa.selenium.grid.node.local.SessionSlot.apply (SessionSlot.java:147)
    at org.openqa.selenium.grid.node.local.LocalNode.newSession (LocalNode.java:464)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession (LocalDistributor.java:644)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession (LocalDistributor.java:563)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest (LocalDistributor.java:823)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1 (LocalDistributor.java:783)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
```

### Operating System

MacOS

### Selenium version

Selenium Grid 4.14.1 (revision 03f8ede370)

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver last

### Are you using Selenium Grid?

Selenium Grid 4.14.1 (revision 03f8ede370)

**Comment by jameskohjunwei** [comment]
Hi is there any update to this issue?

**Comment by soan1d** [comment]
hi, not at all ;(

**Comment by jameskohjunwei** [comment]
@soan1d that's sad. Then why is it closed?

**Comment by satya081** [comment]
why the ticket is closed?

**Comment by diemol** [comment]
We provided URLs where you can go and ask the question and get help troubleshooting. Have you tried those?

**Comment by soan1d** [comment]
Hi diemol, 
Indeed i posted my issue but not getted help unfortunatly
https://groups.google.com/g/selenium-users/c/VWkhLjtIoiI/m/D8bZYZrqBgAJ

**Comment by diemol** [comment]
You also have a Slack channel and other options.

**Comment by titusfortner** [comment]
This is a Google issue, try: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35

**Comment by jameskohjunwei** [comment]
@soan1d I managed to solve my issue.

**Before:**
`web = webdriver.Remote('http://localhost:4444/wd/hub', webdriver.DesiredCapabilities.CHROME)`

**After**
`web = webdriver.Remote('http://localhost:4444/wd/hub', options=webdriver.ChromeOptions())`

I changed this argument at the end for webdriver. Not sure if it works for you but it's worth a shot. Hope this helps!
