### ISSUE TITLE
BiDi tests failing with Firefox browser (Ruby)

### ISSUE THREAD

**Issue by MatzFan** [SeleniumHQ/selenium#13079]
### What happened?

I've followed the build instructions for Ruby and when I run the integration tests with the `--define browser=firefox` flag the following tests fail:-
`//rb/spec/integration/selenium/webdriver:bidi`
`//rb/spec/integration/selenium/webdriver:bidi`
`//rb/spec/integration/selenium/webdriver:bidi`

10 specs fail in the three tests and all of them are either `TimeoutError` or `Errno::ECONNREFUSED` at 127.0.0.1:9222 - which makes me think there is something wrong with my build environment.

### How can we reproduce the issue?

```shell
Follow the Ruby build instructions with build environment specified below and run
`bazel test //rb/spec/integration/... --define browser=firefox`
```

### Relevant log output

```shell
INFO: From Testing //rb/spec/integration/selenium/webdriver:bidi:
==================== Test output for //rb/spec/integration/selenium/webdriver:bidi:

Running Ruby specs:

 browser: firefox
  driver: firefox
 version: 115.4.0
platform: linux
      ci: 
    ruby: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]

FF..

Failures:

  1) Selenium::WebDriver::BiDi gets session status
     Failure/Error: status = driver.bidi.session.status

     Selenium::WebDriver::Error::TimeoutError:
       timed out after 30 seconds
     # ./rb/lib/selenium/webdriver/common/wait.rb:73:in `until'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:63:in `send_cmd'
     # ./rb/lib/selenium/webdriver/bidi.rb:45:in `send_cmd'
     # ./rb/lib/selenium/webdriver/bidi/session.rb:31:in `status'
     # ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:34:in `block (2 levels) in <module:WebDriver>'

  2) Selenium::WebDriver::BiDi can navigate and listen to errors
     Failure/Error: log_inspector = BiDi::LogInspector.new(driver)

     Errno::ECONNREFUSED:
       Connection refused - connect(2) for "127.0.0.1" port 9222
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:150:in `initialize'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:150:in `new'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:150:in `socket'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:76:in `process_handshake'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:41:in `initialize'
     # ./rb/lib/selenium/webdriver/bidi.rb:28:in `new'
     # ./rb/lib/selenium/webdriver/bidi.rb:28:in `initialize'
     # ./rb/lib/selenium/webdriver/common/driver_extensions/has_bidi.rb:31:in `new'
     # ./rb/lib/selenium/webdriver/common/driver_extensions/has_bidi.rb:31:in `bidi'
     # ./rb/lib/selenium/webdriver/bidi/log_inspector.rb:49:in `initialize'
     # ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:41:in `new'
     # ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:41:in `block (2 levels) in <module:WebDriver>'

Finished in 1 minute 5.73 seconds (files took 0.36799 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:33 # Selenium::WebDriver::BiDi gets session status
rspec ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:39 # Selenium::WebDriver::BiDi can navigate and listen to errors
```

### Operating System

LMDE 6 (Faye) built on Debian 12

### Selenium version

selenium-webdriver (4.14.0) gem

### What are the browser(s) and version(s) where you see this issue?

Firefox 115.4.0esr

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 118.0.5993.88

**Comment by titusfortner** [comment]
My guess is that this is an issue with running in parallel. Trying  `--test_output streamed` or `--local_test_jobs 1`.
I'll see if that fixes it for me.

**Comment by MatzFan** [comment]
Many thanks, `--local_test_jobs 1` did it.
