### ISSUE TITLE
unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response[🐛 Bug]: 

### ISSUE THREAD

**Issue by Anandh1924** [SeleniumHQ/selenium#13084]
### What happened?

I am using robot framework with Selenium Library - I had update Successfully installed selenium-4.15.0 , Successfully installed robotframework-seleniumlibrary-6.1.3 , My IDE Is Pycharm still getting above error can you help me .
Only facing issue in chrome

### How can we reproduce the issue?

```shell
Started breaking from today morning on scripts
```

### Relevant log output

```shell
msg timestamp="20231102 13:03:22.727" level="INFO" html="true">&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan="3"&gt;&lt;a href="screenshots/selenium-screenshot-157.png"&gt;&lt;img src="screenshots/selenium-screenshot-157.png" width="800px"&gt;&lt;/a&gt;</msg>
<msg timestamp="20231102 13:03:22.728" level="FAIL">WebDriverException: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: headless chrome=119.0.6045.105)
Stacktrace:
```

### Operating System

mac os

### Selenium version

selenium-4.15.0 

### What are the browser(s) and version(s) where you see this issue?

Version 119.0.6045.105 (Official Build) (x86_64)

### What are the browser driver(s) and version(s) where you see this issue?

Version 119.0.6045.105 (Official Build) (x86_64)

### Are you using Selenium Grid?

no

**Comment by Anandh1924** [comment]
Issue is resolved by updating chrome driver version

**Comment by MawenkaMMM** [comment]
my tests not running after chrome=119.0.6045.106 updates. im facing this error  org.openqa.selenium.WebDriverException: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.106) . Im using IJ, Selenium .

**Comment by MawenkaMMM** [comment]
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1699041524.921][WARNING]: This version of ChromeDriver has not been tested with Chrome version 119.
2023-11-03T15:58:45.022-04:00  WARN 15164 --- [           main] o.o.selenium.devtools.CdpVersionFinder   : Unable to find CDP implementation matching 119
2023-11-03T15:58:45.023-04:00  WARN 15164 --- [           main] o.o.selenium.chromium.ChromiumDriver     : Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.5.3` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
https://tds.testrail.net
  Given User is on Home page                                                                      # tds_pos.stepDefinitions.HomePageSteps.user_is_on_home_page()
  Then Validate pos link is displayed                                                             # tds_pos.stepDefinitions.HomePageSteps.validate_pos_link_is_displayed()
      org.openqa.selenium.WebDriverException: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.106)
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [9e2df111575c93f7b6c9d3e8be19a77c, getCurrentUrl {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 119.0.6045.106, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: C:\Users\MARIAD~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55596}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:55596/devtoo..., se:cdpVersion: 119.0.6045.106, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9e2df111575c93f7b6c9d3e8be19a77c
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:596)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:322)
	at tds_pos.pages.BasePage.getCurrentUrl(BasePage.java:99)
	at tds_pos.stepDefinitions.HomePageSteps.validate_pos_link_is_displayed(HomePageSteps.java:30)
	at ✽.Validate pos link is displayed(file:///C:/......................


Step failed
org.openqa.selenium.WebDriverException: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.106)
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [9e2df111575c93f7b6c9d3e8be19a77c, getCurrentUrl {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 119.0.6045.106, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: C:\Users\...., fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55596}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:55596/devtoo..., se:cdpVersion: 119.0.6045.106, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9e2df111575c93f7b6c9d3e8be19a77c
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:596)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:322)
	at tds_pos.pages.BasePage.getCurrentUrl(BasePage.java:99)
	at tds_pos.stepDefinitions.HomePageSteps.validate_pos_link_is_displayed(HomePageSteps.java:30)
	at ✽.Validate pos link is displayed(file:///C:/Users/...............................................

**Comment by titusfortner** [comment]
This seems suboptimal: `Build info: version: '4.5.3', revision: '4b786a1e430'`
Make sure you don't have chromedriver 118 in a directory listed on PATH.

If you turn on logging you might be able to see where it's coming from - https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
