### ISSUE TITLE
[🐛 Bug]: Invalid Json parse with windows path in TOML configuration

### ISSUE THREAD

**Issue by lacell75** [SeleniumHQ/selenium#13107]
### What happened?

I have an Appium server connected to Grid. I used the TOML example [config](https://www.selenium.dev/documentation/grid/configuration/toml_options/#relaying-commands-to-a-service-endpoint-that-supports-webdriver)
I added the windows path to the application but this path is not correctly parse by the server. The TOML file is valid.

`Caused by: org.openqa.selenium.json.JsonException: Unable to parse: {"browserName": `"Manufacturing.Dev",` "platformName": "WINDOWS", "appium:platformVersion": "11", "ms:experimental-webdriver": true, "appium:appArguments": "-noCloseConfirmationPopUp -shouldDisplayDiesToTake",  "appium:app": "C:\Program Files\internal\Manufacturing.Dev\Client.exe"}`

### How can we reproduce the issue?

Please see the TOML file below:

```shell
[node]
detect-drivers = false

[relay]
# Default Appium/Cloud server endpoint
url = "http://localhost:4723/wd/hub"
status-endpoint = "/status"
# Stereotypes supported by the service. The initial number is "max-sessions", and will allocate 
# that many test slots to that particular configuration
configs = [
  "1", "{\"browserName\": \"EXCEL\", \"platformName\": \"WINDOWS\", \"appium:platformVersion\": \"11\", \"ms:experimental-webdriver\": true}",
  "1", "{\"browserName\": \"DieManufacturing.Dev\", \"platformName\": \"WINDOWS\", \"appium:platformVersion\": \"11\", \"ms:experimental-webdriver\": true, \"appium:appArguments\": \"-noCloseConfirmationPopUp -shouldDisplayDiesToTake\",  \"appium:app\": \"C:\\Program Files\\internal\\Manufacturing.Dev\\Client.exe\"}"
]
```

The command to start the server:
`java -jar selenium-server-4.15.0.jar standalone --config configAppium.toml`
```


### Relevant log output

```shell
java -jar selenium-server-4.15.0.jar standalone --config configAppium.toml
12:37:53.531 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
12:37:53.543 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
12:37:57.668 INFO [NodeOptions.getSessionFactories] - Detected 12 available processors
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:166)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:217)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:47)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:262)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 14 more
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: {"browserName": "DieManufacturing.Dev", "platformName": "WINDOWS", "appium:platformVersion": "11", "ms:experimental-webdriver": true, "appium:appArguments": "-noCloseConfirmationPopUp -shouldDisplayDiesToTake",  "appium:app": "C:\Program Files\internal\Manufacturing.Dev\Client.exe"}
        at org.openqa.selenium.json.Json.toType(Json.java:169)
        at org.openqa.selenium.json.Json.toType(Json.java:152)
        at org.openqa.selenium.grid.node.relay.RelayOptions.getSessionFactories(RelayOptions.java:144)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:98)
        ... 22 more
Caused by: org.openqa.selenium.json.JsonException: Unexpected escape code: P. Last 128 characters read: experimental-webdriver": true, "appium:appArguments": "-noCloseConfirmationPopUp -shouldDisplayDiesToTake",  "appium:app": "C:\P
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: unknown
        at org.openqa.selenium.json.JsonInput.readEscape(JsonInput.java:601)
        at org.openqa.selenium.json.JsonInput.readString(JsonInput.java:537)
        at org.openqa.selenium.json.JsonInput.nextString(JsonInput.java:262)
        at org.openqa.selenium.json.StringCoercer.lambda$apply$0(StringCoercer.java:44)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:171)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146)
        at org.openqa.selenium.json.ObjectCoercer.lambda$apply$0(ObjectCoercer.java:71)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:171)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146)
        at org.openqa.selenium.json.MapCoercer.lambda$apply$0(MapCoercer.java:71)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:75)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:171)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146)
        at org.openqa.selenium.json.Json.toType(Json.java:206)
        at org.openqa.selenium.json.Json.toType(Json.java:167)
        ... 25 more
```

### Operating System

Windows 10

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

appium 1.22.3

### What are the browser driver(s) and version(s) where you see this issue?

appium

**Comment by krmahadevan** [comment]
@lacell75 - Its because of bad escape sequencing. Can you please have your `Client.exe` path updated with something like this and try again ?

```
\"appium:app\": \"C:\\\\Program Files\\\\internal\\\\Manufacturing.Dev\\\\Client.exe\"
```

Notice how I am using `\\\\` (4 back slashes) instead of `\\` (2 back slashes)

**Comment by lacell75** [comment]
> @lacell75 - Its because of bad escape sequencing. Can you please have your `Client.exe` path updated with something like this and try again ?
> 
> ```
> \"appium:app\": \"C:\\\\Program Files\\\\internal\\\\Manufacturing.Dev\\\\Client.exe\"
> ```
> 
> Notice how I am using `\\\\` (4 back slashes) instead of `\\` (2 back slashes)

great, That works. Thanks!
