### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status       from no such window

### ISSUE THREAD

**Issue by LiudmilaSantos** [SeleniumHQ/selenium#13116]
### What happened?

I'm running those test cases randomly I'm getting like 30% of them with this issue. What happens is that the test starts, charges the URL the test continues with the user and password, and then suddenly it closes the window and rinses this error. I was trying to find a way to fix reading your pass tickets but looks like nobody gave a correct answer to it. Can you help?.

Capabilities: 
 capabilities = {
                    "name": scenario_name,
                    "build": build_name,
                    "projectName": project_name,
                    "browserName": cls.drivers[browser][0],
                    "version": cls.drivers[browser][1],
                    "platform": os.getenv("PLATFORM"),
                    "network": True,
                    "visual": True,
                    "video": True,
                    "console": True,
                    "resolution": "1280x1024",
                    "idleTimeout": "270",
                    "infraProvider":"MS",
                }

BROWSER_VERSION="104.0"
PLATFORM="MacOS Ventura"

### How can we reproduce the issue?

```shell
@MT-TC-491-03-53-477-472-489-Admin_Adding_customer_waitlist_Unlimited_membership(PAS)
  Scenario: @MT-TC-491-03-53-477-572-489-Admin_Adding_customer_waitlist_Unlimited_membership(PAS)  # features/daily_excecutions/schedule.feature:201
    Given The user is on the SignIn Page                                                           # features/steps/common_steps.py:14
    Given The user is on the SignIn Page                                                           # features/steps/common_steps.py:14 28.125s
      Traceback (most recent call last):
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/common_steps.py", line 20, in step_impl
          Page(context).open(url)
        File "/Users/liudmilasantos/Documents/automation/ui-repo/ui-automation-tests/utils/page.py", line 23, in open
          self.browser.get(path)
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 349, in get
          self.execute(Command.GET, {'url': url})
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 338, in execute
          self.error_handler.check_response(response)
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 230, in check_response
          raise exception_class(message, screen, stacktrace)
      selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
      from no such window
        (Session info: chrome=114.0.5735.90)
```

### Relevant log output

```shell
@MT-TC-491-03-53-477-472-489-Admin_Adding_customer_waitlist_Unlimited_membership(PAS)
  Scenario: @MT-TC-491-03-53-477-572-489-Admin_Adding_customer_waitlist_Unlimited_membership(PAS)  # features/daily_excecutions/schedule.feature:201
    Given The user is on the SignIn Page                                                           # features/steps/common_steps.py:14
    Given The user is on the SignIn Page                                                           # features/steps/common_steps.py:14 28.125s
      Traceback (most recent call last):
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/common_steps.py", line 20, in step_impl
          Page(context).open(url)
        File "/Users/liudmilasantos/Documents/automation/ui-repo/ui-automation-tests/utils/page.py", line 23, in open
          self.browser.get(path)
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 349, in get
          self.execute(Command.GET, {'url': url})
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 338, in execute
          self.error_handler.check_response(response)
        File "/Users/liudmilasantos/Documents/automation/selenium_behave_framework/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 230, in check_response
          raise exception_class(message, screen, stacktrace)
      selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
      from no such window
        (Session info: chrome=114.0.5735.90)
```

### Operating System

MacOs

### Selenium version

3.141.0

### What are the browser(s) and version(s) where you see this issue?

chrome=114.0.5735.90

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver last version

**Comment by titusfortner** [comment]
Try with the latest version of Chrome/chromedriver. Beyond that, we only support the latest version of Selenium, so we'd need a reproducible example in 4.15 to investigate further.

Most likely it's the chromedriver version, though
