### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.SessionNotCreatedException thrown when using http.proxyHost and http.proxyPort

### ISSUE THREAD

**Issue by tony-parasoft** [SeleniumHQ/selenium#13121]
### What happened?

As of Selenium 4.15.0, setting the http.proxyHost and http.proxyPort system properties causes Selenium to send webdriver commands through a proxy when the webdriver is running on localhost.

Setting http.nonProxyHosts to "localhost" does not work around the problem. The issue is new as of Selenium 4.15.0. It does not reproduce in Selenium 4.14, nor does it reproduce in earlier versions of Selenium that relied on Netty for communication.

Please note that setting "http.nonProxyHosts" has never been necessary, but is mentioned here as a possible workaround we tried.

We believe the issue was introduced with e8c3e9db75b9881eb306cc7830b6638014f4f0c8

To reproduce, run the code included with this submission with a chromewebdriver instance available on the local machine.

### How can we reproduce the issue?

```shell
System.setProperty("webdriver.chrome.driver", "/path/to/chromedriver");
System.setProperty("http.proxyHost", "www.example.com");
System.setProperty("http.proxyPort", "80");
System.setProperty("http.nonProxyHosts", "localhost");

WebDriver driver = new ChromeDriver();
try {
    // passes in 4.14, 4.13, etc. Fails in 4.15.0
    driver.get("http://www.example.com");
} finally {
    driver.close();
}
```

### Relevant log output

```shell
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>404 - Not Found</title>
	</head>
	<body>
		<h1>404 - Not Found</h1>
	</body>
</html>
 
Host info: host: 'machinename', ip: '127.0.1.1'
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:607)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:52)
	at com.parasoft.sandbox.DemonstrateBug.main(DemonstrateBug.java:13)
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>404 - Not Found</title>
	</head>
	<body>
		<h1>404 - Not Found</h1>
	</body>
</html>

	at org.openqa.selenium.json.Json.toType(Json.java:169)
	at org.openqa.selenium.json.Json.toType(Json.java:152)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:122)
	... 13 more
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-87-generic', java.version: '17.0.6'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:166)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:167)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146)
	at org.openqa.selenium.json.Json.toType(Json.java:206)
	at org.openqa.selenium.json.Json.toType(Json.java:167)
	... 15 more
```

### Operating System

Ubuntu

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

Any version, for example Chrome 119.0.6045.105

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 119.0.6045.105, but probably any version reproduces the issue

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Here's the commit the changed things: https://github.com/SeleniumHQ/selenium/commit/e8c3e9db75b9881eb306cc7830b6638014f4f0c8

**Comment by pujagani** [comment]
Thank you for the details. I am working on a fix.

**Comment by pujagani** [comment]
I reverted the changes. Turns out, it was not needed. I triaged it wrong earlier, sincere apologies. If one wants to proxy everything through a proxy including web socket requests, setting the system property is essential and should work.
Fixed it via https://github.com/SeleniumHQ/selenium/commit/3ae7ae2f71ef074af5f62ada541ac773d0203c08
