### ISSUE TITLE
[🐛 Bug]: Issue with UiPath studio and selenium manager binary location [4.15.0]

### ISSUE THREAD

**Issue by jduust** [SeleniumHQ/selenium#13137]
### What happened?

It seems to have issue locating the selenium manager. It looks for it in the UiPath install location (Unable to locate or obtain Selenium Manager binary at C:\\Program Files\\UiPath\\Studio\\selenium-manager\\windows\\selenium-manager.exe), but UiPath installs it in %USERPROFILE%\.nuget\packages\selenium.webdriver\4.15.0\manager\windows. I think the bug is due to how the current folder is fetched in the selenium code. 

I used to use webdrivermanager.net to go around this bug, but it has conflicts with UiPath now (System.Text.Json version), so i'm hoping it will get solved in SeleniumManager.

### How can we reproduce the issue?

```shell
//Download UiPath Studio, community if you don't own it
//add selenium packages (4.15) and relevant namespaces 
//(OpenQA.Selenium, OpenQA.Selenium.Chrome, 
//OpenQA.Selenium.Support.UI). Add below code in a 
//"invoke code" activity using C# and press debug.

var options = new ChromeOptions();
//options.AddArgument("--headless=new");
var downloadsFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Downloads");
options.AddUserProfilePreference("download.default_directory", downloadsFolder);
options.AddUserProfilePreference("download.prompt_for_download", false);
options.AddUserProfilePreference("download.directory_upgrade", true);

var driverService = ChromeDriverService.CreateDefaultService();
driverService.HideCommandPromptWindow = true;
// Initialize the ChromeDriver with options
var driver = new ChromeDriver(driverService, options, TimeSpan.FromMinutes(14));
```

### Relevant log output

```shell
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> OpenQA.Selenium.NoSuchDriverException: Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
 ---> System.TypeInitializationException: The type initializer for 'OpenQA.Selenium.SeleniumManager' threw an exception.
 ---> OpenQA.Selenium.WebDriverException: Unable to locate or obtain Selenium Manager binary at C:\\Program Files\\UiPath\\Studio\\selenium-manager\\windows\\selenium-manager.exe
   at OpenQA.Selenium.SeleniumManager..cctor()
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.SeleniumManager.DriverPath(DriverOptions options)
   at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
   at OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
```

### Operating System

Windows 10

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 106.0.5249.62 (Officiel version) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

I'm trying to fetch the drivers from SeleniumManager

**Comment by nvborisenko** [comment]
I would say it is bug in `UiPath`, but seems it's time to introduce fallback strategy to locate selenium manager binary. Before any further conclusions, @jduust please help us to understand the environment you are in.

To do it I propose to execute the following code:

```csharp
ListDirectories(System.AppContext.BaseDirectory); // this is used by Selenium

ListDirectories(System.IO.Path.GetDirectoryName(typeof(OpenQA.Selenium.By).Assembly.Location));

ListDirectories(System.Environment.CurrentDirectory);
```

where `ListDirectories` is method like:

```csharp
public void ListDirectories(string path)
{
    Console.WriteLine($"Listing path: {path}");

    foreach (var dir in Directory.GetDirectories(path))
    {
        Console.WriteLine(dir);
    }
}
```

And please share results (console output). I believe we can resolve it together.

**Comment by jduust** [comment]
@titusfortner I agree it's most likely a bug with UiPath, but one i'm not able to resolve unfortunately, so being able to manually set the binary path or having another fallback would be greatly appreciated.

I had to rewrite the code a bit due to UiPaths invoke code limitations.. 

```
string baseDirectory = System.AppContext.BaseDirectory;
string seleniumDirectory = System.IO.Path.GetDirectoryName(typeof(OpenQA.Selenium.By).Assembly.Location);
string currentDirectory = System.Environment.CurrentDirectory;

Console.WriteLine($"Listing base directory: {baseDirectory}");
foreach (var dir in System.IO.Directory.GetDirectories(baseDirectory))
{
    Console.WriteLine(dir);
}

Console.WriteLine($"Listing Selenium directory: {seleniumDirectory}");
foreach (var dir in System.IO.Directory.GetDirectories(seleniumDirectory))
{
    Console.WriteLine(dir);
}

Console.WriteLine($"Listing current directory: {currentDirectory}");
foreach (var dir in System.IO.Directory.GetDirectories(currentDirectory))
{
    Console.WriteLine(dir);
}
```

Here's the output:
```
11/13/2023 12:22:39 => [Debug] Listing base directory: C:\Program Files\UiPath\Studio\
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\CredentialProvider
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\de
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\Diagnostic Tool
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\en
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\es
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\es-MX
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\ffmpeg
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\fr
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\host
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\ja
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\ko
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\net461
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\Packages
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\Platform
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\PreLoadedEmptyWorkflows
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\Profiles
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\ProjectTemplates
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\pt
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\pt-BR
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\refs
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\Resources
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\ru
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\Rules
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\shared
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\Snippets
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\StudioVNCClient
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\TemplatePackages
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\tr
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\UiPath
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\UiPathAssistant
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\web
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\WorkflowTemplates
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\zh-CN
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\zh-TW
11/13/2023 12:22:39 => [Debug] C:\Program Files\UiPath\Studio\zu
11/13/2023 12:22:39 => [Debug] Listing Selenium directory: C:\Users\Username\.nuget\packages\selenium.webdriver\4.15.0\lib\netstandard2.0
11/13/2023 12:22:39 => [Debug] Listing current directory: C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess
11/13/2023 12:22:39 => [Debug] C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess\.entities
11/13/2023 12:22:39 => [Debug] C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess\.git
11/13/2023 12:22:39 => [Debug] C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess\.local
11/13/2023 12:22:39 => [Debug] C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess\.objects
11/13/2023 12:22:39 => [Debug] C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess\.project
11/13/2023 12:22:39 => [Debug] C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess\.settings
11/13/2023 12:22:39 => [Debug] C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess\.templates
11/13/2023 12:22:39 => [Debug] C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess\.tmh
```

**Comment by diemol** [comment]
This is possible since Selenium 4.13. Check https://www.selenium.dev/documentation/selenium_manager/#alternative-architectures, for `SE_MANAGER_PATH`.

>However, as of Selenium 4.13.0, the Selenium bindings allow locating the Selenium Manager binary using an environment variable called SE_MANAGER_PATH. If this variable is set, the bindings will use its value as the Selenium Manager path in the local filesystem. This feature will allow users to provide a custom compilation of Selenium Manager, for instance, if the default binaries (compiled for Windows, Linux, and macOS) are incompatible with a given system (e.g., ARM64 in Linux).

**Comment by titusfortner** [comment]
@nvborisenko might we still want to do something differently in Selenium code for this?

**Comment by nvborisenko** [comment]
No way.

- `System.AppContext.BaseDirectory` - C:\Program Files\UiPath\Studio\
- `System.IO.Path.GetDirectoryName(typeof(OpenQA.Selenium.By).Assembly.Location)` - C:\Users\Username\.nuget\packages\selenium.webdriver\4.15.0\lib\netstandard2.0
- `System.Environment.CurrentDirectory` - C:\Users\Username\Cloud - Code\UiPath\Processer\Project\MyProcess

This is absolutely untraditional setup used by UiPath. @diemol suggested good resolution via environment variables. To prevent next question "how to set env variable in UiPath", @jduust , I think the following should be a good solution in your case:

```csharp
System.Environment.SetEnvironmentVariable("SE_MANAGER_PATH", System.IO.Path.GetDirectoryName(typeof(OpenQA.Selenium.By).Assembly.Location) + "\\..\\..\\manager\\windows\\selenium-manager.exe");
```

PS: This `\\..\\..\\manager\\windows\\selenium-manager.exe` part of the path might be changed without any announcements.

**Comment by jduust** [comment]
Thank you so much, all of you @nvborisenko, @titusfortner, @diemol! I resolved it with the following code to make it more dynamic depending on what you might change in your newer releases, it searches for any \*manager\*.exe inside the current version folder.


```
string[] pathParts = System.IO.Path.GetDirectoryName(typeof(OpenQA.Selenium.By).Assembly.Location).Split(Path.DirectorySeparatorChar);

int seleniumFolderIndex = Array.IndexOf(pathParts, "selenium.webdriver");
string newPath="";
if (seleniumFolderIndex != -1 && seleniumFolderIndex < pathParts.Length - 1)
{
    string versionFolder = pathParts[seleniumFolderIndex + 1];
    
    string versionFolderPath = string.Join("\\", pathParts.Take(seleniumFolderIndex + 2));
    DirectoryInfo versionDirectory = new DirectoryInfo(versionFolderPath);
    
    newPath = Directory.GetFiles(versionDirectory.FullName, "*manager*.exe", SearchOption.AllDirectories).FirstOrDefault();
    System.Environment.SetEnvironmentVariable("SE_MANAGER_PATH", newPath);
}

```
