### ISSUE TITLE
[🐛 Bug]: Not able to create devtool instance after latest selenium update

### ISSUE THREAD

**Issue by invincibleSachi** [SeleniumHQ/selenium#13148]
### What happened?

Updated to selenium 4.15.0
using chrome version: 119.0.6045
using following lines of code to start selenium dev tool instance
this.devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
this.devTools.addListener(Network.requestWillBeSent(), entry -> {
			NetworkRequest networkRequest = new NetworkRequest();
			networkRequest.setMethod(entry.getRequest().getMethod());
			networkRequest.setHeaders(entry.getRequest().getHeaders());
			Optional<String> postData = entry.getRequest().getPostData();
			Gson gson = new GsonBuilder().setPrettyPrinting().create();
			postData.ifPresentOrElse(p -> networkRequest.setPostData(gson.toJson(JsonParser.parseString(p))),()->networkRequest.setPostData(null));
			networkRequest.setUrl(entry.getRequest().getUrl());
			networkRequest.setResponse(entry.getRedirectResponse());
			networkRequests.add(networkRequest);
		});

but getting following logs

WARNING: Unable to process: {"method":"Network.requestWillBeSent","params":{"requestId":"927D974F6D81F8DF9B3880F9DA2A49C1","loaderId":"927D974F6D81F8DF9B3880F9DA2A49C1","documentURL":"https://abc.com?url=%2F","request":{"url":"SOMEUR url=%2F","method":"GET","headers":{"Referer":"https:abc.com/","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","sec-ch-ua":"\"Google Chrome\";v=\"119\", \"Chromium\";v=\"119\", \"Not?A_Brand\";v=\"24\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"macOS\""},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin","isSameSite":true},"timestamp":198866.992765,"wallTime":1699953388.652327,"initiator":{"type":"script","stack":{"callFrames":[{"functionName":"","scriptId":"6","url":"https://master-story2.master.canary.eu10.projectorca.cloud/","lineNumber":18,"columnNumber":27}]}},"redirectHasExtraInfo":false,"type":"Document","frameId":"0A7842FB52D114E180A6E2B03743FE08","hasUserGesture":false},"sessionId":"F54AD12FA1BD68F96CE30BC59F3FDE8B"}
org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v119.network.model.RequestWillBeSent
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.1', java.version: '17.0.7'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:174)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:149)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:421)
	at org.openqa.selenium.devtools.v119.network.Network.lambda$requestWillBeSent$41(Network.java:525)
	at org.openqa.selenium.devtools.Connection.lambda$handle$4(Connection.java:306)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:296)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:57)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:224)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 21 more
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v119.network.model.Initiator
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.1', java.version: '17.0.7'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:174)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:149)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:421)
	at org.openqa.selenium.devtools.v119.network.model.RequestWillBeSent.fromJson(RequestWillBeSent.java:172)
	... 26 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 30 more
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v119.runtime.model.StackTrace
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.1', java.version: '17.0.7'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:174)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:149)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:421)
	at org.openqa.selenium.devtools.v119.network.model.Initiator.fromJson(Initiator.java:122)
	... 35 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 39 more
Caused by: java.lang.NoSuchMethodError: 'java.util.List org.openqa.selenium.json.JsonInput.readArray(java.lang.reflect.Type)'
	at org.openqa.selenium.devtools.v119.runtime.model.StackTrace.fromJson(StackTrace.java:68)
	... 44 more

### How can we reproduce the issue?

```shell
//create a driver with selenium manager
driver = new ChromeDriver(chromeOptions);
//create dev tool sessions 
this.devTools = ((HasDevTools) this.driver).getDevTools();
//once enable network logs
this.devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
this.devTools.addListener(Network.requestWillBeSent(), entry -> {
			NetworkRequest networkRequest = new NetworkRequest();
			networkRequest.setMethod(entry.getRequest().getMethod());
			networkRequest.setHeaders(entry.getRequest().getHeaders());
			Optional<String> postData = entry.getRequest().getPostData();
			Gson gson = new GsonBuilder().setPrettyPrinting().create();
			postData.ifPresentOrElse(p -> networkRequest.setPostData(gson.toJson(JsonParser.parseString(p))),()->networkRequest.setPostData(null));
			networkRequest.setUrl(entry.getRequest().getUrl());
			networkRequest.setResponse(entry.getRedirectResponse());
			networkRequests.add(networkRequest);
		});
once network listener is enabled and as soon as we try to navigate any url we are getting error
```

### Relevant log output

```shell
WARNING: Unable to process: {"method":"Network.requestWillBeSent","params":{"requestId":"927D974F6D81F8DF9B3880F9DA2A49C1","loaderId":"927D974F6D81F8DF9B3880F9DA2A49C1","documentURL":"https://abc.com?url=%2F","request":{"url":"SOMEUR url=%2F","method":"GET","headers":{"Referer":"https:abc.com/","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","sec-ch-ua":"\"Google Chrome\";v=\"119\", \"Chromium\";v=\"119\", \"Not?A_Brand\";v=\"24\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"macOS\""},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin","isSameSite":true},"timestamp":198866.992765,"wallTime":1699953388.652327,"initiator":{"type":"script","stack":{"callFrames":[{"functionName":"","scriptId":"6","url":"https://master-story2.master.canary.eu10.projectorca.cloud/","lineNumber":18,"columnNumber":27}]}},"redirectHasExtraInfo":false,"type":"Document","frameId":"0A7842FB52D114E180A6E2B03743FE08","hasUserGesture":false},"sessionId":"F54AD12FA1BD68F96CE30BC59F3FDE8B"}
org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v119.network.model.RequestWillBeSent
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.1', java.version: '17.0.7'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:174)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:149)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:421)
	at org.openqa.selenium.devtools.v119.network.Network.lambda$requestWillBeSent$41(Network.java:525)
	at org.openqa.selenium.devtools.Connection.lambda$handle$4(Connection.java:306)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:296)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:57)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:224)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 21 more
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v119.network.model.Initiator
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.1', java.version: '17.0.7'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:174)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:149)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:421)
	at org.openqa.selenium.devtools.v119.network.model.RequestWillBeSent.fromJson(RequestWillBeSent.java:172)
	... 26 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 30 more
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.devtools.v119.runtime.model.StackTrace
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.1', java.version: '17.0.7'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:174)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:149)
	at org.openqa.selenium.json.JsonInput.read(JsonInput.java:421)
	at org.openqa.selenium.devtools.v119.network.model.Initiator.fromJson(Initiator.java:122)
	... 35 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
	... 39 more
Caused by: java.lang.NoSuchMethodError: 'java.util.List org.openqa.selenium.json.JsonInput.readArray(java.lang.reflect.Type)'
	at org.openqa.selenium.devtools.v119.runtime.model.StackTrace.fromJson(StackTrace.java:68)
	... 44 more
```

### Operating System

MAC OS

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

yes using selenium manager

### Are you using Selenium Grid?

Local

**Comment by diemol** [comment]
Upgrade to 4.15.0, you log shows 4.13.0
>Build info: version: '4.13.0', revision: 'ba948ece5b*'

**Comment by diemol** [comment]
If you need more help, I will leave some links below where you can ask more questions.
