### ISSUE TITLE
[🐛 Bug]: Chromedriver 119 cannot connect if http.proxyHost is set

### ISSUE THREAD

**Issue by fjf2002** [SeleniumHQ/selenium#13154]
### What happened?

I am behind a corporate proxy and I have set the `http.proxyHost` and `https.proxyHost` variables therefore.
I also have set the `http.nonProxyHosts` and `https.nonProxyHosts` variables.

The chromedriver v119 does not work. It fails with

> Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: [...]

As far as I can tell, your libaries try to establish a connection to localhost.

This simply fails because the connection runs through the proxy, which responds with some HTML stuff that your libraries did not expect.

As far as I can tell, `org.openqa.selenium.remote.http.jdk.JdkHttpClient` reads the system properties `http.proxyHost` and `https.proxyHost`, but does not respect `http.nonProxyHosts` and `https.nonProxyHosts` .

I can workaround the bug by setting
```java
System.clearProperty("http.proxyHost");
System.clearProperty("https.proxyHost");
```
but I consider this a kludge since it trashed my proxy settings java-program-wide.

Can you confirm and fix that? Thank You.

### How can we reproduce the issue?

```shell
* Set up `http.proxyHost` and `https.proxyHost` system properties.
* Set up `http.nonProxyHosts` and `https.nonProxyHosts` system properties to exclude localhost.

Now try to connect to ChromeDriver v119. It should fail as described.
```

### Relevant log output

```shell
Log output, shortened and censored.

Picked up JAVA_TOOL_OPTIONS: -Dhttp.proxyHost=***myproxy***
-Dhttp.proxyPort=80
-Dhttps.proxyHost=***myproxy***
-Dhttps.proxyPort=80
-Dhttp.nonProxyHosts=localhost|127.*|[::1]|0.0.0.0|[::0]
-Dhttps.nonProxyHosts=localhost|127.*|[::1]|0.0.0.0|[::0]
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="de" lang="de" xml:lang="de" xmlns="http://www.w3.org/1999/xhtml">

[...]

 
Host info: host: 'KM-PC-888', ip: '10.1.248.63'
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:607)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:52)
	at examples.SearchGoogle.main(SearchGoogle.java:20)
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="de" lang="de" xml:lang="de" xmlns="http://www.w3.org/1999/xhtml">

[...]

	at org.openqa.selenium.json.Json.toType(Json.java:169)
	at org.openqa.selenium.json.Json.toType(Json.java:152)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:122)
	... 13 more
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.2'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:166)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:167)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146)
	at org.openqa.selenium.json.Json.toType(Json.java:206)
	at org.openqa.selenium.json.Json.toType(Json.java:167)
	... 15 more
```

### Operating System

Windows 10

### Selenium version

OpenJDK 19

### What are the browser(s) and version(s) where you see this issue?

Chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 119

**Comment by diemol** [comment]
This was fixed by https://github.com/SeleniumHQ/selenium/commit/3ae7ae2f71ef074af5f62ada541ac773d0203c08, which should be part of the next release.

**Comment by diemol** [comment]
You can already try it through the Nightly build https://www.selenium.dev/downloads/#nightly
