### ISSUE TITLE
[🐛 Bug]: Had to revert to earlier version of Selenium[Java] due to fatal error with new versions.

### ISSUE THREAD

**Issue by tbiyl** [SeleniumHQ/selenium#13186]
### What happened?

Works fine with older versions of Selenium[Java].  After updating, trying to run anything fails immediately upon launch of any program with fatal error.
I had to downgrade.
Please note that I'm required to use the latest FREE version of Java which is Java 8.
Please fix so that I can upgrade Selenium[Java] and not be stuck back at this older version forever.
Following is the error stack dump:
Could not instrument class org/openqa/selenium/WebDriverException: Unsupported class file major version 55.
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/selenium/WebDriverException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)

### How can we reproduce the issue?

```shell
Use Java 8 runtime and attempt to launch any Java 8 program using Selenium webdriver with one of the latest versions of Selenium[Java].
```

### Relevant log output

```shell
Could not instrument class org/openqa/selenium/WebDriverException: Unsupported class file major version 55.
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/selenium/WebDriverException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```

### Operating System

Windows 10

### Selenium version

Java 8, Selenium 4.15.0

### What are the browser(s) and version(s) where you see this issue?

MSEdge 

### What are the browser driver(s) and version(s) where you see this issue?

Latest MSEdge and msedgeDriver Version: 119.0.2151.72

### Are you using Selenium Grid?

no

**Comment by baflQA** [comment]
The newest selenium requires at least Java11. Please upgrade Your JDK since it's out of date and not maintained anymore.

**Comment by diemol** [comment]
What @baflQA is correct. Please follow their advice.

**Comment by diemol** [comment]
Also, there are many free, open source Java distributions. An example is https://openjdk.org/
