### ISSUE TITLE
[🐛 Bug]: Python upgrading to selenium 4.15.2 raises exception: selenium.common.exceptions.WebDriverException: Message:

### ISSUE THREAD

**Issue by wangdong2516** [SeleniumHQ/selenium#13233]
### What happened?

when I used selenium==4.15.2 and proxy, I got this error:
I can't open baidu.com , logging message is empty, so I can't find where is error happen

### How can we reproduce the issue?

```shell
code:

class ScmpSpider(scrapy.Spider):
    name = "scmp"
    allowed_domains = ["www.scmp.com"]
    start_urls = ["https://www.scmp.com/"]
    source = SourceEnum.SCMP.value

    def __init__(self, *args, **kwargs):
        options = webdriver.ChromeOptions()
        options.binary_location = '/Users/wangodong/Desktop/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'
        service = Service(executable_path=CHROME_EXECUTE_PATH)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
        )
        super(ScmpSpider, self).__init__(*args, **kwargs)
        self.driver = webdriver.Chrome(options=options, service=service, keep_alive=True)
        # self.driver = webdriver.Chrome(options=options, executable_path=CHROME_EXECUTE_PATH)

    def parse(self, response, **kwargs):
        # print(response.url)
        self.driver.get('https://www.baidu.com')

I use clashx in my macbook-pro, I set http_proxy in my bash_profile
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/scrapy/crawler.py", line 155, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/scrapy/crawler.py", line 169, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/scrapy/spiders/__init__.py", line 59, in from_crawler
    spider = cls(*args, **kwargs)
  File "/Users/wangodong/Desktop/workspace/news_spider/news_spider/spiders/scmp.py", line 24, in __init__
    self.driver = webdriver.Chrome(options=options, service=service, keep_alive=True)
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Users/wangodong/anaconda3/envs/news/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message:
```

### Operating System

macos 14.1

### Selenium version

4.15.2

### What are the browser(s) and version(s) where you see this issue?

119.0.6045.105

### What are the browser driver(s) and version(s) where you see this issue?

119.0.6045.105

### Are you using Selenium Grid?

no

**Comment by wangdong2516** [comment]
this is my environment variable
export https_proxy=http://127.0.0.1:7890 
export http_proxy=http://127.0.0.1:7890 
export all_proxy=socks5://127.0.0.1:7890

**Comment by wangdong2516** [comment]
related bug 
https://github.com/SeleniumHQ/selenium/issues/10710

**Comment by diemol** [comment]
You need to set the proxy to let the session use it explicitly. 
Here are some examples from tests:
- https://github.com/SeleniumHQ/selenium/blob/trunk/py/test/unit/selenium/webdriver/firefox/firefox_options_tests.py#L70
- https://github.com/SeleniumHQ/selenium/blob/trunk/py/test/selenium/webdriver/common/proxy_tests.py
