### ISSUE TITLE
[🐛 Bug]: Firefox browser initialization fails with Snap-installed Firefox and Selenium Python version >= 4.11

### ISSUE THREAD

**Issue by jn-chrn** [SeleniumHQ/selenium#13252]
### What happened?

When initializing the Firefox webdriver with a Selenium version higher or equal to 4.11, an `InvalidArgumentException` occurs. The message states: `binary is not a Firefox executable`. **Firefox was installed with Snap.**

This issue does not occur with Firefox installed using `apt` (tested on a different machine) or with a version of Selenium <= 4.10. This thus seems to be a regression issue.

### How can we reproduce the issue?

```shell
import logging
import selenium.webdriver

logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)

options = selenium.webdriver.firefox.options.Options()
options.add_argument('-headless')
browser = selenium.webdriver.Firefox(options=options)
```

### Relevant log output

```shell
DEBUG:selenium.webdriver.common.selenium_manager:Selenium Manager binary found at: /home/foo/miniconda3/envs/my_env/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG:selenium.webdriver.common.selenium_manager:Executing process: /home/foo/miniconda3/envs/my_env/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --debug --output json
DEBUG:selenium.webdriver.common.selenium_manager:Found geckodriver 0.33.0 in PATH: /snap/bin/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:firefox detected at /usr/bin/firefox
DEBUG:selenium.webdriver.common.selenium_manager:Running command: /usr/bin/firefox -v
DEBUG:selenium.webdriver.common.selenium_manager:Output: "Mozilla Firefox 120.0.1"
DEBUG:selenium.webdriver.common.selenium_manager:Detected browser: firefox 120.0.1
DEBUG:selenium.webdriver.common.selenium_manager:Required driver: geckodriver 0.33.0
DEBUG:selenium.webdriver.common.selenium_manager:Driver path: /snap/bin/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:Browser path: /usr/bin/firefox
DEBUG:selenium.webdriver.common.selenium_manager:Using driver at: /snap/bin/geckodriver
DEBUG:selenium.webdriver.common.service:Started executable: `/snap/bin/geckodriver` in a child process with pid: 71586
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:52427/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:debuggerAddress": true, "pageLoadStrategy": "normal", "browserVersion": null, "moz:firefoxOptions": {"binary": "/usr/bin/firefox", "args": ["-headless"]}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:52427
DEBUG:urllib3.connectionpool:http://localhost:52427 "POST /session HTTP/1.1" 400 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=400 | data={"value":{"error":"invalid argument","message":"binary is not a Firefox executable","stacktrace":""}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '101', 'date': 'Wed, 06 Dec 2023 10:55:42 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "/home/foo/Documents/foobar/selenium_testbed.py", line 9, in <module>
    browser = selenium.webdriver.Firefox(options=options)
  File "/home/foo/miniconda3/envs/my_env/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/foo/miniconda3/envs/my_env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/foo/miniconda3/envs/my_env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/foo/miniconda3/envs/my_env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/foo/miniconda3/envs/my_env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
```

### Operating System

Ubuntu 22.04

### Selenium version

Python 3.10.12, Selenium 4.10

### What are the browser(s) and version(s) where you see this issue?

Firefox 120.0.1,  installed with Snap

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.33.0

**Comment by titusfortner** [comment]
Snap is a pain because it can't use the geckodriver defaults. You have to specify locations yourself:
https://www.selenium.dev/documentation/selenium_manager/#custom-package-managers

**Comment by jn-chrn** [comment]
For anyone stumbling upon this issue, the solution is not as straightforward as one may think: the executables for firefox and geckodriver are not simply `/snap/bin/firefox` and `/snap/bin/geckodriver`, but they are in the `/snap/firefox/current/usr/lib/firefox/` directory.

A working solution would be:

```python
import logging
import selenium.webdriver
import selenium.webdriver.firefox.service


logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)

firefox_bin = "/snap/firefox/current/usr/lib/firefox/firefox"
firefoxdriver_bin = "/snap/firefox/current/usr/lib/firefox/geckodriver"

options = selenium.webdriver.firefox.options.Options()
options.add_argument('--headless')
options.binary_location = firefox_bin

service = selenium.webdriver.firefox.service.Service(executable_path=firefoxdriver_bin)

browser = selenium.webdriver.Firefox(service=service, options=options)
```

**Comment by titusfortner** [comment]
Thanks for the complete answer here!
