### ISSUE TITLE
[🐛 Bug]: session not created: Chrome failed to start: exited normally.

### ISSUE THREAD

**Issue by mikececco** [SeleniumHQ/selenium#13255]
### What happened?

Trying to run selenium webdriver but not able because:
```
#0 0x56360579cdc3 <unknown>: session not created: Chrome failed to start: exited normally. (Selenium::WebDriver::Error::SessionNotCreatedError)
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/mikececco/.cache/selenium/chrome/linux64/120.0.6099.62/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

### How can we reproduce the issue?

```shell
Simply running this:
require 'selenium-webdriver'

puts "STARTING"

# Use Firefox options for Firefox browser
options = Selenium::WebDriver::Firefox::Options.new(args: ['-headless'])

driver = Selenium::WebDriver.for(:firefox, options: options)

driver.get('http://stackoverflow.com/')

puts "STARTING coming"

puts driver.title

driver.quit
```

### Relevant log output

```shell
#0 0x56360579cdc3 <unknown>: session not created: Chrome failed to start: exited normally. (Selenium::WebDriver::Error::SessionNotCreatedError)
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/mikececco/.cache/selenium/chrome/linux64/120.0.6099.62/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
        from #1 0x563605459f87 <unknown>
        from #2 0x56360549187e <unknown>
        from #3 0x56360548e4de <unknown>
        from #4 0x5636054dea90 <unknown>
        from #5 0x5636054d30e3 <unknown>
        from #6 0x56360549b044 <unknown>
        from #7 0x56360549c44e <unknown>
        from #8 0x5636057618f1 <unknown>
        from #9 0x563605765815 <unknown>
        from #10 0x56360574f315 <unknown>
        from #11 0x5636057664af <unknown>
        from #12 0x56360573329f <unknown>
        from #13 0x56360578a0b8 <unknown>
        from #14 0x56360578a287 <unknown>
        from #15 0x56360579bf64 <unknown>
        from #16 0x7f6892661b43 <unknown>
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/bridge.rb:601:in `execute'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/bridge.rb:53:in `create_session'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/common/driver.rb:317:in `block in create_bridge'
        from <internal:kernel>:90:in `tap'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/common/driver.rb:316:in `create_bridge'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/chrome/driver.rb:35:in `initialize'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
        from /home/mikececco/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver.rb:89:in `for'
        from lib/scraper.rb:17:in `<main>'
```

### Operating System

Ubuntu

### Selenium version

4.16

### What are the browser(s) and version(s) where you see this issue?

Chrome/Firefox

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 120.0.6099.62

**Comment by titusfortner** [comment]
duplicate #12841
