### ISSUE TITLE
[🐛 Bug]: Python 3.12.0 | Selenium 4.16.0 | ChromeForTesting 120.0.6099.71: selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Browser window not found"}

### ISSUE THREAD

**Issue by rhynot-ryan** [SeleniumHQ/selenium#13257]
### What happened?

Updated ChromeForTesting and ChromeDriver from 117.0.5938.149 to latest stable, 120.0.6099.71

After doing so, browser window would open then crash/close when setting window size. Downgrading to older Chrome version resolves the behavior.

Removing the `browser.set_window_size(1300,1000)` line and replacing with `browser.get("https://www.google.com")` prevents the crash/exception but the browser doesn't actually load the page. Browser address bar displays only `data:,` after executing the `browser.get()` command.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
import os

# Assumes ChromeForTesting and related/same version ChromeDriver has been downloaded to 
# C:\users\username\appdata\roaming\ChromeForTesting\chrome-win64\
# and
# C:\users\username\appdata\roaming\ChromeForTesting\chromedriver-win64\
# respectively

global_cftPath = os.environ.get("APPDATA").replace("\\","/") + "/ChromeForTesting/"
browserOpts = webdriver.ChromeOptions()
cftPath = global_cftPath + "chrome-win64/chrome.exe"
browserOpts.binary_location = cftPath
cdPath = global_cftPath + "chromedriver-win64/chromedriver.exe"
service = ChromeService(executable_path= cdPath)
browserPrefs = {"credentials_enable_service": False,"profile.password_manager_enabled": False}
browserOpts.add_experimental_option("excludeSwitches", ["enable-automation","enable-logging"])
browserOpts.add_experimental_option("prefs", browserPrefs)
browserOpts.add_experimental_option("detach", True)
browserOpts.add_argument("--disable-single-click-autofill")
browserOpts.set_capability("goog:loggingPrefs", {"performance": "ALL"})
browser = webdriver.Chrome(options=browserOpts,service=service)
browser.set_window_size(1300,1000)
# browser.get("https://www.google.com")
print(browser.capabilities["browserVersion"])
```

### Relevant log output

```shell
"C:/Program Files/Python312/python.exe" c:/Users/username/Dropbox/Vintage/PythonProjects/loop_so_entry/testChromeLaunch.py

Traceback (most recent call last):
  File "c:\Users\username\Dropbox\Vintage\PythonProjects\loop_so_entry\testChromeLaunch.py", line 21, in <module>
    browser.set_window_size(1300,1000)
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 865, in set_window_size
    self.set_window_rect(width=int(width), height=int(height))
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 946, in set_window_rect
    return self.execute(Command.SET_WINDOW_RECT, {"x": x, "y": y, "width": width, "height": height})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Browser window not found"}
  (Session info: chrome=120.0.6099.71)
Stacktrace:
        GetHandleVerifier [0x00007FF6483C4D02+56194]
        (No symbol) [0x00007FF6483304B2]
        (No symbol) [0x00007FF6481D76AA]
        (No symbol) [0x00007FF6481C112C]
        (No symbol) [0x00007FF6481BEE85]
        (No symbol) [0x00007FF6481BF7CE]
        (No symbol) [0x00007FF6481BF700]
        (No symbol) [0x00007FF6481B10D3]
        (No symbol) [0x00007FF6481B3135]
        (No symbol) [0x00007FF6482784B8]
        (No symbol) [0x00007FF648245E7A]
        (No symbol) [0x00007FF648262786]
        (No symbol) [0x00007FF648245C23]
        (No symbol) [0x00007FF648214A45]
        (No symbol) [0x00007FF648215AD4]
        GetHandleVerifier [0x00007FF64873D5BB+3695675]
        GetHandleVerifier [0x00007FF648796197+4059159]
        GetHandleVerifier [0x00007FF64878DF63+4025827]
        GetHandleVerifier [0x00007FF64845F029+687785]
        (No symbol) [0x00007FF64833B508]
        (No symbol) [0x00007FF648337564]
        (No symbol) [0x00007FF6483376E9]
        (No symbol) [0x00007FF648328094]
        BaseThreadInitThunk [0x00007FF9DE65257D+29]
        RtlUserThreadStart [0x00007FF9E094AA58+40]
```

### Operating System

Windows 11

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.71

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 120.0.6099.71

**Comment by diemol** [comment]
Does this mean it works for CfT 117 and not for CfT 120?

**Comment by rhynot-ryan** [comment]
> Does this mean it works for CfT 117 and not for CfT 120?

Apologies for not making that completely clear; yes. The provided code block executes flawlessly with CfT 117; with CfT 120 the provided exception is thrown.

Similarly, in CfT 117, executing the `browser.get("https://www.google.com")` command results in the browser navigating to the URL and rendering the results as expected. Executing the same line in CfT 120 results in nothing happening in the browser; the address bar remains displaying `data:,` and nothing is rendered in the browser.

Interestingly, if I launch CfT 120 on its own - e.g. executing chrome.exe from Windows Explorer (C:\users\username\appdata\roaming\ChromeForTesting\chrome-win64\chrome.exe) - and attempt to display Settings (Menu -> Settings) the browser just closes with no report of any error.

Will be happy to provide screen recording if requested

**Comment by rhynot-ryan** [comment]
> We need more information about this issue in order to troubleshoot.
> 
> Please turn on logging and re-run your code. Information on how to adjust logs for your language can be found in our [Troubleshooting documentation](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/).

Please see below for logging. Note the line `browser.get("https://www.google.com")` appears to have executed but the browser does not actually do anything. The address bar does not change and no page is rendered.

**Executed code:**
```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
import os
import logging

logger = logging.getLogger('selenium')

version = "-120.0.6099.71"
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(os.environ.get("HOMEDRIVE").replace("\\","/") + os.environ.get("HOMEPATH").replace("\\","/") + "/Desktop/testLog.txt")
logger.addHandler(handler)

global_cftPath = os.environ.get("APPDATA").replace("\\","/") + "/ChromeForTesting/"
browserOpts = webdriver.ChromeOptions()
cftPath = global_cftPath + "chrome-win64" + version + "/chrome.exe"
browserOpts.binary_location = cftPath
cdPath = global_cftPath + "chromedriver-win64" + version + "/chromedriver.exe"
service = ChromeService(executable_path= cdPath)
browserPrefs = {"credentials_enable_service": False,"profile.password_manager_enabled": False}
browserOpts.add_experimental_option("excludeSwitches", ["enable-automation","enable-logging"])
browserOpts.add_experimental_option("prefs", browserPrefs)
browserOpts.add_experimental_option("detach", True)
browserOpts.add_argument("--disable-single-click-autofill")
browserOpts.set_capability("goog:loggingPrefs", {"performance": "ALL"})
browser = webdriver.Chrome(options=browserOpts,service=service)
browser.get("https://www.google.com")
print(browser.capabilities["browserVersion"])
browser.set_window_size(1300,1000)
```


**Logs from execution:**
```
Started executable: `C:/Users/username/AppData/Roaming/ChromeForTesting/chromedriver-win64-120.0.6099.71/chromedriver.exe` in a child process with pid: 23672 using 0 to output -3
POST http://localhost:57650/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:loggingPrefs": {"performance": "ALL"}, "goog:chromeOptions": {"excludeSwitches": ["enable-automation", "enable-logging"], "prefs": {"credentials_enable_service": false, "profile.password_manager_enabled": false}, "detach": true, "extensions": [], "binary": "C:/Users/username/AppData/Roaming/ChromeForTesting/chrome-win64-120.0.6099.71/chrome.exe", "args": ["--disable-single-click-autofill"]}}}}
Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"120.0.6099.71","chrome":{"chromedriverVersion":"120.0.6099.71 (9729082fe6174c0a371fc66501f5efc5d69d3d2b-refs/branch-heads/6099_56@{#13})","userDataDir":"C:\\Users\\username\\AppData\\Local\\Temp\\scoped_dir23672_1967163772"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:57682"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"76444b7cb0a6e2d1bf03090304306a8d"}} | headers=HTTPHeaderDict({'Content-Length': '885', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:57650/session/76444b7cb0a6e2d1bf03090304306a8d/url {"url": "https://www.google.com"}
Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:57650/session/76444b7cb0a6e2d1bf03090304306a8d/window/rect {"x": null, "y": null, "width": 1300, "height": 1000}
Remote response: status=500 | data={"value":{"error":"unknown error","message":"unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"Browser window not found\"}\n  (Session info: chrome=120.0.6099.71)","stacktrace":"\tGetHandleVerifier [0x00007FF6ED324D02+56194]\n\t(No symbol) [0x00007FF6ED2904B2]\n\t(No symbol) [0x00007FF6ED1376AA]\n\t(No symbol) [0x00007FF6ED12112C]\n\t(No symbol) [0x00007FF6ED11EE85]\n\t(No symbol) [0x00007FF6ED11F7CE]\n\t(No symbol) [0x00007FF6ED11F700]\n\t(No symbol) [0x00007FF6ED1110D3]\n\t(No symbol) [0x00007FF6ED113135]\n\t(No symbol) [0x00007FF6ED1D84B8]\n\t(No symbol) [0x00007FF6ED1A5E7A]\n\t(No symbol) [0x00007FF6ED1C2786]\n\t(No symbol) [0x00007FF6ED1A5C23]\n\t(No symbol) [0x00007FF6ED174A45]\n\t(No symbol) [0x00007FF6ED175AD4]\n\tGetHandleVerifier [0x00007FF6ED69D5BB+3695675]\n\tGetHandleVerifier [0x00007FF6ED6F6197+4059159]\n\tGetHandleVerifier [0x00007FF6ED6EDF63+4025827]\n\tGetHandleVerifier [0x00007FF6ED3BF029+687785]\n\t(No symbol) [0x00007FF6ED29B508]\n\t(No symbol) [0x00007FF6ED297564]\n\t(No symbol) [0x00007FF6ED2976E9]\n\t(No symbol) [0x00007FF6ED288094]\n\tBaseThreadInitThunk [0x00007FF9DE65257D+29]\n\tRtlUserThreadStart [0x00007FF9E094AA58+40]\n"}} | headers=HTTPHeaderDict({'Content-Length': '1192', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
```


**Console Output from execution:**
```
PS C:\Users\username\Dropbox\Vintage\PythonProjects\loop_so_entry> & "C:/Program Files/Python312/python.exe" c:/Users/username/Dropbox/Vintage/PythonProjects/loop_so_entry/testChromeLaunch.py
120.0.6099.71
Traceback (most recent call last):
  File "c:\Users\username\Dropbox\Vintage\PythonProjects\loop_so_entry\testChromeLaunch.py", line 34, in <module>
    browser.set_window_size(1300,1000)
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 865, in set_window_size
    self.set_window_rect(width=int(width), height=int(height))
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 946, in set_window_rect
    return self.execute(Command.SET_WINDOW_RECT, {"x": x, "y": y, "width": width, "height": height})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Browser window not found"}
  (Session info: chrome=120.0.6099.71)
Stacktrace:
        GetHandleVerifier [0x00007FF6ED324D02+56194]
        (No symbol) [0x00007FF6ED2904B2]
        (No symbol) [0x00007FF6ED1376AA]
        (No symbol) [0x00007FF6ED12112C]
        (No symbol) [0x00007FF6ED11EE85]
        (No symbol) [0x00007FF6ED11F7CE]
        (No symbol) [0x00007FF6ED11F700]
        (No symbol) [0x00007FF6ED1110D3]
        (No symbol) [0x00007FF6ED113135]
        (No symbol) [0x00007FF6ED1D84B8]
        (No symbol) [0x00007FF6ED1A5E7A]
        (No symbol) [0x00007FF6ED1C2786]
        (No symbol) [0x00007FF6ED1A5C23]
        (No symbol) [0x00007FF6ED174A45]
        (No symbol) [0x00007FF6ED175AD4]
        GetHandleVerifier [0x00007FF6ED69D5BB+3695675]
        GetHandleVerifier [0x00007FF6ED6F6197+4059159]
        GetHandleVerifier [0x00007FF6ED6EDF63+4025827]
        GetHandleVerifier [0x00007FF6ED3BF029+687785]
        (No symbol) [0x00007FF6ED29B508]
        (No symbol) [0x00007FF6ED297564]
        (No symbol) [0x00007FF6ED2976E9]
        (No symbol) [0x00007FF6ED288094]
        BaseThreadInitThunk [0x00007FF9DE65257D+29]
        RtlUserThreadStart [0x00007FF9E094AA58+40]
```

**Comment by titusfortner** [comment]
What happens if you just do this:

```py
browserOpts = webdriver.ChromeOptions()
browserOpts.browser_version = "120"
browser = webdriver.Chrome(options=browserOpts)
browser.get("https://www.google.com")
browser.set_window_size(1300, 1000)
```

**Comment by rhynot-ryan** [comment]
> What happens if you just do this:

@titusfortner - to answer simply, it functions exactly as expected; no exceptions/error, and the url loads properly as expected. After a successful test with just the utter basics as proposed in your response, I added the additional options/arguments/flags back in one at a time to see if those produced any of the errors. No issues created by the addition of the prefs/options/etc. I was able to reproduce the reported issue as soon as I specified path to the Chrome binary, `browserOpts.binary_location = [path/to/binary]`. When using the Service class to specify the path to ChromeDriver, everything worked as expected also. **So the issue occurs ONLY when I specified the path to the Chrome binary.** (the Chrome binary was downloaded from the same source as where selenium manager obtains the binaries)

### Working:
**Executed code:** 
```
from selenium import webdriver
import os
import logging

logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(os.environ.get("HOMEDRIVE").replace("\\","/") + os.environ.get("HOMEPATH").replace("\\","/") + "/Desktop/testLog.txt")
logger.addHandler(handler)

browserOpts = webdriver.ChromeOptions()
browserOpts.browser_version = "120"
browserPrefs = {"credentials_enable_service": False,"profile.password_manager_enabled": False}
browserOpts.add_experimental_option("excludeSwitches", ["enable-automation","enable-logging"])
browserOpts.add_experimental_option("prefs", browserPrefs)
browserOpts.add_argument("--disable-single-click-autofill")
browserOpts.set_capability("goog:loggingPrefs", {"performance": "ALL"})
browser = webdriver.Chrome(options=browserOpts)
browser.get("https://www.google.com")
browser.set_window_size(1300,1000)
```

**Log output:**
```
Selenium Manager binary found at: C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe
Executing process: C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --browser-version 120 --debug --output json
chromedriver not found in PATH
chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe
Running command: wmic datafile where name='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' get Version /value
Output: "\r\r\n\r\r\nVersion=120.0.6099.63\r\r\n\r\r\n\r\r\n\r"
Detected browser: chrome 120.0.6099.63
Required driver: chromedriver 120.0.6099.71
chromedriver 120.0.6099.71 already in the cache
Driver path: C:\Users\username\.cache\selenium\chromedriver\win64\120.0.6099.71\chromedriver.exe
Browser path: C:\Program Files\Google\Chrome\Application\chrome.exe
Using driver at: C:\Users\username\.cache\selenium\chromedriver\win64\120.0.6099.71\chromedriver.exe
Started executable: `C:\Users\username\.cache\selenium\chromedriver\win64\120.0.6099.71\chromedriver.exe` in a child process with pid: 12076 using 0 to output -3
POST http://localhost:57559/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "browserVersion": null, "goog:loggingPrefs": {"performance": "ALL"}, "goog:chromeOptions": {"excludeSwitches": ["enable-automation", "enable-logging"], "prefs": {"credentials_enable_service": false, "profile.password_manager_enabled": false}, "extensions": [], "binary": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", "args": ["--disable-single-click-autofill"]}}}}
Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"120.0.6099.63","chrome":{"chromedriverVersion":"120.0.6099.71 (9729082fe6174c0a371fc66501f5efc5d69d3d2b-refs/branch-heads/6099_56@{#13})","userDataDir":"C:\\Users\\username\\AppData\\Local\\Temp\\scoped_dir12076_926393640"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:57619"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"76a82c6f3854de3863d62828b3f6d7c5"}} | headers=HTTPHeaderDict({'Content-Length': '884', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:57559/session/76a82c6f3854de3863d62828b3f6d7c5/url {"url": "https://www.google.com"}
Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:57559/session/76a82c6f3854de3863d62828b3f6d7c5/window/rect {"x": null, "y": null, "width": 1300, "height": 1000}
Remote response: status=200 | data={"value":{"height":1000,"width":1300,"x":10,"y":10}} | headers=HTTPHeaderDict({'Content-Length': '52', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
```

### Not Working:
**Code:**
```
from selenium import webdriver
import os
import logging

logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(os.environ.get("HOMEDRIVE").replace("\\","/") + os.environ.get("HOMEPATH").replace("\\","/") + "/Desktop/testLog.txt")
logger.addHandler(handler)

browserOpts = webdriver.ChromeOptions()

browserOpts.binary_location = "C:\\Users\\username\\AppData\\Roaming\\ChromeForTesting\\chrome-win64-120.0.6099.71\\chrome.exe"

browserOpts.browser_version = "120"
browserPrefs = {"credentials_enable_service": False,"profile.password_manager_enabled": False}
browserOpts.add_experimental_option("excludeSwitches", ["enable-automation","enable-logging"])
browserOpts.add_experimental_option("prefs", browserPrefs)
browserOpts.add_argument("--disable-single-click-autofill")
browserOpts.set_capability("goog:loggingPrefs", {"performance": "ALL"})
browser = webdriver.Chrome(options=browserOpts)
browser.get("https://www.google.com")
browser.set_window_size(1300,1000)
```

**Log:**
```
Selenium Manager binary found at: C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe
Executing process: C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --browser-version 120 --browser-path C:\Users\username\AppData\Roaming\ChromeForTesting\chrome-win64-120.0.6099.71\chrome.exe --debug --output json
chromedriver not found in PATH
Running command: wmic datafile where name='C:\\Users\\username\\AppData\\Roaming\\ChromeForTesting\\chrome-win64-120.0.6099.71\\chrome.exe' get Version /value
Output: "\r\r\n\r\r\nVersion=120.0.6099.71\r\r\n\r\r\n\r\r\n\r"
Detected browser: chrome 120.0.6099.71
Required driver: chromedriver 120.0.6099.71
chromedriver 120.0.6099.71 already in the cache
Driver path: C:\Users\username\.cache\selenium\chromedriver\win64\120.0.6099.71\chromedriver.exe
Browser path: C:\Users\username\AppData\Roaming\ChromeForTesting\chrome-win64-120.0.6099.71\chrome.exe
Using driver at: C:\Users\username\.cache\selenium\chromedriver\win64\120.0.6099.71\chromedriver.exe
Started executable: `C:\Users\username\.cache\selenium\chromedriver\win64\120.0.6099.71\chromedriver.exe` in a child process with pid: 4380 using 0 to output -3
POST http://localhost:62982/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "browserVersion": null, "goog:loggingPrefs": {"performance": "ALL"}, "goog:chromeOptions": {"excludeSwitches": ["enable-automation", "enable-logging"], "prefs": {"credentials_enable_service": false, "profile.password_manager_enabled": false}, "extensions": [], "binary": "C:\\Users\\username\\AppData\\Roaming\\ChromeForTesting\\chrome-win64-120.0.6099.71\\chrome.exe", "args": ["--disable-single-click-autofill"]}}}}
Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"120.0.6099.71","chrome":{"chromedriverVersion":"120.0.6099.71 (9729082fe6174c0a371fc66501f5efc5d69d3d2b-refs/branch-heads/6099_56@{#13})","userDataDir":"C:\\Users\\username\\AppData\\Local\\Temp\\scoped_dir4380_1205648217"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:63008"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"843a1ab5a55150f3386914e2ab8db533"}} | headers=HTTPHeaderDict({'Content-Length': '884', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:62982/session/843a1ab5a55150f3386914e2ab8db533/url {"url": "https://www.google.com"}
Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:62982/session/843a1ab5a55150f3386914e2ab8db533/window/rect {"x": null, "y": null, "width": 1300, "height": 1000}
Remote response: status=500 | data={"value":{"error":"unknown error","message":"unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"Browser window not found\"}\n  (Session info: chrome=120.0.6099.71)","stacktrace":"\tGetHandleVerifier [0x00007FF6A4804D02+56194]\n\t(No symbol) [0x00007FF6A47704B2]\n\t(No symbol) [0x00007FF6A46176AA]\n\t(No symbol) [0x00007FF6A460112C]\n\t(No symbol) [0x00007FF6A45FEE85]\n\t(No symbol) [0x00007FF6A45FF7CE]\n\t(No symbol) [0x00007FF6A45FF700]\n\t(No symbol) [0x00007FF6A45F10D3]\n\t(No symbol) [0x00007FF6A45F3135]\n\t(No symbol) [0x00007FF6A46B84B8]\n\t(No symbol) [0x00007FF6A4685E7A]\n\t(No symbol) [0x00007FF6A46A2786]\n\t(No symbol) [0x00007FF6A4685C23]\n\t(No symbol) [0x00007FF6A4654A45]\n\t(No symbol) [0x00007FF6A4655AD4]\n\tGetHandleVerifier [0x00007FF6A4B7D5BB+3695675]\n\tGetHandleVerifier [0x00007FF6A4BD6197+4059159]\n\tGetHandleVerifier [0x00007FF6A4BCDF63+4025827]\n\tGetHandleVerifier [0x00007FF6A489F029+687785]\n\t(No symbol) [0x00007FF6A477B508]\n\t(No symbol) [0x00007FF6A4777564]\n\t(No symbol) [0x00007FF6A47776E9]\n\t(No symbol) [0x00007FF6A4768094]\n\tBaseThreadInitThunk [0x00007FF9DE65257D+29]\n\tRtlUserThreadStart [0x00007FF9E094AA58+40]\n"}} | headers=HTTPHeaderDict({'Content-Length': '1192', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
```

I'll simply update my code to _not_ specify the chrome binary location and instead use `browserOpts.browser_version = "120"` to specify and keep using a specific version of Chrome & ChromeDriver. Thank you for helping troubleshoot and identify the issue.

**Comment by titusfortner** [comment]
Oh interesting. When you specify "120" it is getting the pre-installed browser (120.0.6099.63), not the CfT browser (120.0.6099.71). I wonder if it something specific to CfT that is the problem, or if it is something different between `*.63` and `*.71`.

Setting `browser_version` in 4.16 is now implicitly opting-in to using Selenium Manager, so it's slightly different behavior than what we had before. What do you get if you do:
```
browserOpts.browser_version = "stable"
```

**Comment by rhynot-ryan** [comment]
I hadn't noticed the sub sub version mismatch, apologies/thank you for pointing that out. 

**Setting `browserOpts.browser_version = "stable"` is still using the installed Chrome browser.** 

Executed code:
```
from selenium import webdriver
import os
import logging

logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(os.environ.get("HOMEDRIVE").replace("\\","/") + os.environ.get("HOMEPATH").replace("\\","/") + "/Desktop/testLog.txt")
logger.addHandler(handler)

browserOpts = webdriver.ChromeOptions()
browserOpts.browser_version = "stable"
browserPrefs = {"credentials_enable_service": False,"profile.password_manager_enabled": False}
browserOpts.add_experimental_option("excludeSwitches", ["enable-automation","enable-logging"])
browserOpts.add_experimental_option("prefs", browserPrefs)
browserOpts.add_argument("--disable-single-click-autofill")
browserOpts.set_capability("goog:loggingPrefs", {"performance": "ALL"})
browser = webdriver.Chrome(options=browserOpts)
browser.get("https://www.google.com")
browser.set_window_size(1300,1000)
```

Log:
```
Selenium Manager binary found at: C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe
Executing process: C:\Program Files\Python312\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --browser-version stable --debug --output json
chromedriver not found in PATH
chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe
Running command: wmic datafile where name='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' get Version /value
Output: "\r\r\n\r\r\nVersion=120.0.6099.63\r\r\n\r\r\n\r\r\n\r"
Detected browser: chrome 120.0.6099.63
Discovered online chrome version (120) is the same as the detected local chrome version
Required driver: chromedriver 120.0.6099.71
chromedriver 120.0.6099.71 already in the cache
Driver path: C:\Users\username\.cache\selenium\chromedriver\win64\120.0.6099.71\chromedriver.exe
Browser path: C:\Program Files\Google\Chrome\Application\chrome.exe
Using driver at: C:\Users\username\.cache\selenium\chromedriver\win64\120.0.6099.71\chromedriver.exe
Started executable: `C:\Users\username\.cache\selenium\chromedriver\win64\120.0.6099.71\chromedriver.exe` in a child process with pid: 45612 using 0 to output -3
POST http://localhost:51344/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "browserVersion": null, "goog:loggingPrefs": {"performance": "ALL"}, "goog:chromeOptions": {"excludeSwitches": ["enable-automation", "enable-logging"], "prefs": {"credentials_enable_service": false, "profile.password_manager_enabled": false}, "extensions": [], "binary": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", "args": ["--disable-single-click-autofill"]}}}}
Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"120.0.6099.63","chrome":{"chromedriverVersion":"120.0.6099.71 (9729082fe6174c0a371fc66501f5efc5d69d3d2b-refs/branch-heads/6099_56@{#13})","userDataDir":"C:\\Users\\username\\AppData\\Local\\Temp\\scoped_dir45612_1538098698"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:51356"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"ef385a69546706616a64646d6d1b774b"}} | headers=HTTPHeaderDict({'Content-Length': '885', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:51344/session/ef385a69546706616a64646d6d1b774b/url {"url": "https://www.google.com"}
Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:51344/session/ef385a69546706616a64646d6d1b774b/window/rect {"x": null, "y": null, "width": 1300, "height": 1000}
Remote response: status=200 | data={"value":{"height":1000,"width":1300,"x":10,"y":10}} | headers=HTTPHeaderDict({'Content-Length': '52', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
```

That said, I tried a few other versions to see the results:
- `browserOpts.browser_version = "117"` GOOD using CfT 117.0.5938.149
- `browserOpts.browser_version = "118"` GOOD using CfT 118.0.5993.70
- `browserOpts.browser_version = "119"` CfT 119.0.6045.105 - SAME PROBLEM - url does not load & resizing window throws exception
- `browserOpts.browser_version = "beta"` CfT 121.0.6167.8 - SAME PROBLEM - url does not load & resizing window throws exception
- `browserOpts.browser_version = "canary"` CfT 122.0.6170.0 - SAME PROBLEM - url does not load & resizing window throws exception

I then updated my installed (regular, not testing) Chrome to 120.0.6099.71:
- `browserOpts.browser_version = "stable"` Chrome REGULAR 120.0.6099.71 - NO ISSUE

Lastly, I renamed the directory of my installed regular Chrome and removed the relevant HKCU key so it wouldnt be found by Selenium Manager and force it to dowload CfT:
- `browserOpts.browser_version = "stable"` CfT 120.0.6099.71 - SAME PROBLEM - url does not load & resizing window throws exception

So it appears that the issue is related to CfT version 119 and later as 'regular' Chrome 120 does not exhibit the issue but CfT 119 thru 122 DOES give the error.

**Comment by titusfortner** [comment]
Excellent, thanks for gathering more data! Excellent differential here.

Since it is a CfT specific issue and not a general chromedriver issue, can you post this information to CfT repo — https://github.com/GoogleChromeLabs/chrome-for-testing/issues
