### ISSUE TITLE
[🐛 Bug]: ImportError: cannot import name 'DriverFinder' from 'selenium.webdriver.common.driver_finder'

### ISSUE THREAD

**Issue by iaroslavnikitin** [SeleniumHQ/selenium#13275]
### What happened?

i try to run some simple code to see if my set up works, i have configured a venv, python3, installed selenium via pip, so here is the issue i faced with:

<img width="2130" alt="Screenshot 2023-12-08 at 3 21 25 PM" src="https://github.com/SeleniumHQ/selenium/assets/42630604/ae644d57-f0cf-4cd9-ba91-fab7578623ef">

### How can we reproduce the issue?

```shell
the code i tried:

from selenium import webdriver
driver = webdriver.Chrome()
driver.get("https://google.com")
```

output is this one:
```
/Users/nktn/python-selenium-venv/bin/python3.11 /Users/nktn/PycharmProjects/pythonProject/main.py 
Traceback (most recent call last):
  File "/Users/nktn/PycharmProjects/pythonProject/main.py", line 2, in <module>
    from selenium import webdriver
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/__init__.py", line 19, in <module>
    from .chrome.webdriver import WebDriver as Chrome  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 20, in <module>
    from selenium.webdriver.common.driver_finder import DriverFinder
ImportError: cannot import name 'DriverFinder' from 'selenium.webdriver.common.driver_finder' (/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py)
```
```


### Relevant log output

```shell
output is this one:

/Users/nktn/python-selenium-venv/bin/python3.11 /Users/nktn/PycharmProjects/pythonProject/main.py 
Traceback (most recent call last):
  File "/Users/nktn/PycharmProjects/pythonProject/main.py", line 2, in <module>
    from selenium import webdriver
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/__init__.py", line 19, in <module>
    from .chrome.webdriver import WebDriver as Chrome  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 20, in <module>
    from selenium.webdriver.common.driver_finder import DriverFinder
ImportError: cannot import name 'DriverFinder' from 'selenium.webdriver.common.driver_finder' (/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py)
```
```


### Operating System

macOS Sonoma 14.1.2

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.71

### What are the browser driver(s) and version(s) where you see this issue?

driver = webdriver.Chrome()

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment]
What happens when you use 4.16.0? We cannot fix old versions.

**Comment by iaroslavnikitin** [comment]
> What happens when you use 4.16.0? We cannot fix old versions.

updated to 4.16.0 and a response in the console changed, now i see bunch of different errors:

```
/Users/nktn/python-selenium-venv/bin/python3.11 /Users/nktn/PycharmProjects/pythonProject/main.py 
Traceback (most recent call last):
  File "/Users/nktn/PycharmProjects/pythonProject/main.py", line 11, in <module>
    driver = webdriver.Chrome()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 52, in __init__
    executor = ChromiumRemoteConnection(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/chromium/remote_connection.py", line 30, in __init__
    super().__init__(remote_server_addr, keep_alive, ignore_proxy)
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 276, in __init__
    self._conn = self._get_connection_manager()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 247, in _get_connection_manager
    return urllib3.ProxyManager(self._proxy_url, **pool_manager_init_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nktn/python-selenium-venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 567, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Proxy URL had unsupported scheme myserver, should use http:// or https://

Process finished with exit code 1
```

**Comment by iaroslavnikitin** [comment]
i also tried to use logger and used this code:

```
import logging
from selenium import webdriver

logging.getLogger('selenium').setLevel(logging.DEBUG)
driver = webdriver.Chrome()
driver.quit()
```

the console's output is the same for it

**Comment by diemol** [comment]
>urllib3.exceptions.ProxySchemeUnknown: Proxy URL had unsupported scheme myserver, should use http:// or https://

Is there a proxy set as an environment variable?

**Comment by titusfortner** [comment]
try using a file handler for the logger. I think something isn't correct with how things are getting put to console. I need to investigate.

**Comment by iaroslavnikitin** [comment]
> > urllib3.exceptions.ProxySchemeUnknown: Proxy URL had unsupported scheme myserver, should use http:// or https://
> 
> Is there a proxy set as an environment variable?

proxy is commented in the bash profile, this is the only place i can imagine it could be taken from
<img width="762" alt="Screenshot 2023-12-08 at 4 43 47 PM" src="https://github.com/SeleniumHQ/selenium/assets/42630604/ec53730c-cf9e-4efb-b0af-f99455765462">

**Comment by iaroslavnikitin** [comment]
> try using a file handler for the logger. I think something isn't correct with how things are getting put to console. I need to investigate.

any code examples that i could try by any chance? thank you in advance

**Comment by titusfortner** [comment]
Sorry for the late reply — https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/?tab=python#logger-output

**Comment by iaroslavnikitin** [comment]
@titusfortner, thanks for that, here is the results:

```
/Users/nktn/python-selenium-venv/bin/python3.11 /Users/nktn/Applications/PyCharm Community Edition 2022.3.3.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py --target main.py::test_logging 
Testing started at 6:39 PM ...
/Users/nktn/Applications/PyCharm Community Edition 2022.3.3.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import iter_entry_points
Launching pytest with arguments main.py::test_logging --no-header --no-summary -q in /Users/nktn/PycharmProjects/pythonProject

============================= test session starts ==============================
collecting ... ERROR: not found: /Users/nktn/PycharmProjects/pythonProject/main.py::test_logging

main.py:None (main.py)
../../python-selenium-venv/lib/python3.11/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
../../python-selenium-venv/lib/python3.11/site-packages/_pytest/runner.py:372: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
../../python-selenium-venv/lib/python3.11/site-packages/_pytest/python.py:531: in collect
    self._inject_setup_module_fixture()
../../python-selenium-venv/lib/python3.11/site-packages/_pytest/python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
../../python-selenium-venv/lib/python3.11/site-packages/_pytest/python.py:310: in obj
    self._obj = obj = self._getobj()
../../python-selenium-venv/lib/python3.11/site-packages/_pytest/python.py:528: in _getobj
    return self._importtestmodule()
../../python-selenium-venv/lib/python3.11/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
../../python-selenium-venv/lib/python3.11/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1206: in _gcd_import
    ???
<frozen importlib._bootstrap>:1178: in _find_and_load
    ???
<frozen importlib._bootstrap>:1149: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
../../python-selenium-venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
main.py:16: in <module>
    driver = webdriver.Chrome()
../../python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__
    super().__init__(
../../python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:52: in __init__
    executor = ChromiumRemoteConnection(
../../python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/chromium/remote_connection.py:30: in __init__
    super().__init__(remote_server_addr, keep_alive, ignore_proxy)
../../python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py:276: in __init__
    self._conn = self._get_connection_manager()
../../python-selenium-venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py:247: in _get_connection_manager
    return urllib3.ProxyManager(self._proxy_url, **pool_manager_init_args)
../../python-selenium-venv/lib/python3.11/site-packages/urllib3/poolmanager.py:567: in __init__
    raise ProxySchemeUnknown(proxy.scheme)
E   urllib3.exceptions.ProxySchemeUnknown: Proxy URL had unsupported scheme myserver, should use http:// or https://
(no name '/Users/nktn/PycharmProjects/pythonProject/main.py::test_logging' in any of [<Module main.py>])

collected 0 items / 1 error

=============================== 1 error in 1.45s ===============================

Process finished with exit code 4
```

**Comment by titusfortner** [comment]
Well, the logging isn't working, but looking at the error message again... check your environment variables. 
We set proxy automatically based on these:
```
        if self._url.startswith("https://"):
            return os.environ.get("https_proxy", os.environ.get("HTTPS_PROXY"))
        if self._url.startswith("http://"):
            return os.environ.get("http_proxy", os.environ.get("HTTP_PROXY"))
```

**Comment by iaroslavnikitin** [comment]
thanks @titusfortner, but it means absolutely nothing to me, tbh, i have no idea how env vars must looks like, i have it like this right now:
<img width="909" alt="Screenshot 2024-01-06 at 2 40 36 PM" src="https://github.com/SeleniumHQ/selenium/assets/42630604/01ea1627-fa9e-4ead-b17b-3753903c94a6">
if there is any way to set it right or reset all my python environment, that help would be super nice, because i have another project on java + selenium and it works perfectly fine, but now i have to set up this framework on python, but have these issues, unfortunately

**Comment by titusfortner** [comment]
Python Selenium respects the value you've used for `HTTP_PROXY`, so if that isn't valid, you have to remove it for Selenium to work properly. Java should also respect it, but I haven't spent much time looking at how Java does this piece.
