### ISSUE TITLE
[🐛 Bug]: System.AggregateException : One or more errors occurred. (The HTTP request to the remote WebDriver server for URL http://localhost:50182/session timed out after 60 seconds.)

### ISSUE THREAD

**Issue by shyampatadia** [SeleniumHQ/selenium#13290]
### What happened?

I am using selenium 4.15.0, and I am getting this issue continuously, can someone educate me on that, mostly I feel that this is some bug, hence creating as a bug.

### How can we reproduce the issue?

```shell
I am triggering this on Azure Release pipelines the agent chosen is **windows-19**. Below is the script for the initialization of the ChromeDriver.


var options = new ChromeOptions();
options.AddArguments("--test-type");
options.AddArguments("--start-maximized");
options.AddArguments("--disable-infobars");
options.AddAdditionalChromeOption("useAutomationExtension", false);
options.AddArguments("--ignore-certificate-errors");
options.AddExcludedArgument("enable-automation");
options.AddUserProfilePreference("credentials_enable_service", false);
options.AddUserProfilePreference("profile.password_manager_enabled", false);
options.AddAdditionalChromeOption("useAutomationExtension", false);
options.AddUserProfilePreference("download.prompt_for_download", false);
options.AddUserProfilePreference("download.default_directory", System.IO.Path.GetFullPath(TestResultDownloadsFolder));
options.AddUserProfilePreference("safebrowsing.enabled", true);
options.AddArguments("window-size=1600,900");
 try
 {
     AddChromePdfReviewerExtension(options);
 }
 catch (Exception e)
 {
     Assert.False(true, $"Exception while AddChromePdfReviewerExtension " +
                        $": : {e.Message}");
 }
 _driver = new ChromeDriver(options);
 _driver.Manage().Window.Maximize();
```
```


### Relevant log output

```shell
2023-12-11T12:00:54.1832287Z Starting ChromeDriver 120.0.6099.71 (9729082fe6174c0a371fc66501f5efc5d69d3d2b-refs/branch-heads/6099_56@{#13}) on port 50182
2023-12-11T12:00:54.1833791Z Only local connections are allowed.
2023-12-11T12:00:54.1835871Z Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-12-11T12:00:54.1912779Z ChromeDriver was started successfully.
2023-12-11T12:02:02.6549014Z [xUnit.net 00:01:22.21]       System.AggregateException : One or more errors occurred. (The HTTP request to the remote WebDriver server for URL http://localhost:50182/session timed out after 60 seconds.) (Value cannot be null. (Parameter 's'))
2023-12-11T12:02:02.6553990Z [xUnit.net 00:01:22.21]       ---- OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:50182/session timed out after 60 seconds.
2023-12-11T12:02:02.6554561Z [xUnit.net 00:01:22.21]       -------- System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
2023-12-11T12:02:02.6556275Z ##[error][xUnit.net 00:01:22.21]     Study User Administration - M - Demo [FAIL]
2023-12-11T12:02:02.6557116Z [xUnit.net 00:01:22.21]       ------------ System.TimeoutException : The operation was canceled.
2023-12-11T12:02:02.6557500Z [xUnit.net 00:01:22.21]       ---------------- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
2023-12-11T12:02:02.6557915Z [xUnit.net 00:01:22.21]       -------------------- System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
2023-12-11T12:02:02.6558396Z [xUnit.net 00:01:22.21]       ------------------------ System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request.
2023-12-11T12:02:02.6558759Z [xUnit.net 00:01:22.21]       ---- System.ArgumentNullException : Value cannot be null. (Parameter 's')
2023-12-11T12:02:02.6559035Z [xUnit.net 00:01:22.21]       Stack Trace:
2023-12-11T12:02:02.6559237Z [xUnit.net 00:01:22.21]         
2023-12-11T12:02:02.6559479Z [xUnit.net 00:01:22.21]         ----- Inner Stack Trace #1 (OpenQA.Selenium.WebDriverException) -----
2023-12-11T12:02:02.6559821Z [xUnit.net 00:01:22.21]            at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2023-12-11T12:02:02.6560144Z [xUnit.net 00:01:22.22]            at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2023-12-11T12:02:02.6561985Z [xUnit.net 00:01:22.22]            at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2023-12-11T12:02:02.6562376Z [xUnit.net 00:01:22.22]            at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
2023-12-11T12:02:02.6562798Z [xUnit.net 00:01:22.22]            at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
2023-12-11T12:02:02.6563210Z [xUnit.net 00:01:22.22]            at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
2023-12-11T12:02:02.6563793Z [xUnit.net 00:01:22.22]            at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
2023-12-11T12:02:02.6564387Z [xUnit.net 00:01:22.22]            at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
```

### Operating System

windows-19

### Selenium version

C# 4.15.0

### What are the browser(s) and version(s) where you see this issue?

120.0.6099.71

### What are the browser driver(s) and version(s) where you see this issue?

120.0.6099.71

### Are you using Selenium Grid?

No selenium grid.

**Comment by pujagani** [comment]
Can you try 4.16.2? The latest release do C# and let us know if you still see the error.

**Comment by shyampatadia** [comment]
Yes will definitely try that and update here.

**Comment by shyampatadia** [comment]
I tried still the same issue persists, not only for chrome but the other browsers as well

**Comment by NCLnclNCL** [comment]
> I tried still the same issue persists, not only for chrome but the other browsers as well

use this
var service = ............ //
  _driver = new ChromeDriver(service,options,TimeSpan.FromSeconds(300));

**Comment by shyampatadia** [comment]
Thank you very much @NCLnclNCL the issue got resolve, using the solution that you suggested.
