### ISSUE TITLE
[🐛 Bug]: After updating from 4.15.0. to 4.16.1. getting "No drivers have been configured or have been found on PATH" but works in 4.15.0

### ISSUE THREAD

**Issue by anandseshadri** [SeleniumHQ/selenium#13295]
### What happened?

After updating from 4.15.0. to 4.16.1. I am getting the following error. The same configuration worked In 4.15.0

### How can we reproduce the issue?

```shell
I have the following configuration setup using toml
hub = "xxxxxxxxxxxxxxxxxxxx"
override-max-sessions = true
max-sessions = 80
session-timeout = 1800
enable-managed-downloads = true
detect-drivers = true
```

### Relevant log output

```shell
`java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:166)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:126)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:246)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 12 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:513)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:232)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:79)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 17 more
Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.grid.node.Node.getStatus()" because "this.node" is null
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
        at java.base/java.lang.Thread.run(Thread.java:1583)`
```

### Operating System

Windows 10

### Selenium version

4.16.2 C#

### What are the browser(s) and version(s) where you see this issue?

Chrome 120

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 120

### Are you using Selenium Grid?

4.16.1

**Comment by anasouardini** [comment]
I had the same issue one week ago before I moved my whole project to Playwright.

**Comment by diemol** [comment]
Can you share the full Node log?

**Comment by titusfortner** [comment]
Are you running headless? There is an issue with how Chrome 120 changed the name of the browser for headless

**Comment by zcindori** [comment]
The same problem when I try to start node on win 10: java -jar "c:\driver\selenium-server-4.16.1.jar" node --selenium-manager true --session-timeout 900 --enable-managed-downloads true --publish-events tcp://ip:4442 --subscribe-events tcp://ip:4443  --grid-url http://ip:4444

**Comment by diemol** [comment]
We can't say much without the full log to understand better the issue.

**Comment by zcindori** [comment]
```
java -jar "c:\driver\selenium-server-4.16.1.jar" node --selenium-manager true --session-timeout 900 --enable-managed-downloads true --publish-events tcp://192.168.1.158:4442 --subscribe-events tcp://192.168.1.158:4443  --grid-url http://192.168.1.158:4444 --log "c:\driver\grid.log" --log-level ALL
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:166)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:126)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:246)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:513)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:232)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:79)
        ... 22 more
Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.grid.node.Node.getStatus()" because "this.node" is null
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by zcindori** [comment]
```
13:12:30.152 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
13:12:30.152 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
13:12:30.277 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://192.168.1.158:4442 and tcp://192.168.1.158:4443
13:12:30.313 INFO [UnboundZmqEventBus.<init>] - Sockets created
13:12:31.325 INFO [UnboundZmqEventBus.<init>] - Event bus ready
13:12:31.325 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = JMImplementation:type=MBeanServerDelegate
13:12:31.341 FINER [Repository.addMBean] - name = JMImplementation:type=MBeanServerDelegate
13:12:31.341 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object JMImplementation:type=MBeanServerDelegate
13:12:31.341 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered JMImplementation:type=MBeanServerDelegate
13:12:31.341 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.RuntimeImpl
13:12:31.341 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:type=Runtime
13:12:31.341 FINER [Repository.addMBean] - name = java.lang:type=Runtime
13:12:31.341 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:type=Runtime
13:12:31.341 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=Runtime
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for com.sun.management.internal.HotSpotThreadImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:type=Threading
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:type=Threading
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:type=Threading
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=Threading
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for com.sun.management.internal.OperatingSystemImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:type=OperatingSystem
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:type=OperatingSystem
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:type=OperatingSystem
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=OperatingSystem
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryManagerImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=CodeCacheManager,type=MemoryManager
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=CodeCacheManager,type=MemoryManager
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=CodeCacheManager,type=MemoryManager
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=CodeCacheManager,type=MemoryManager
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryManagerImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=Metaspace Manager,type=MemoryManager
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=Metaspace Manager,type=MemoryManager
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=Metaspace Manager,type=MemoryManager
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=Metaspace Manager,type=MemoryManager
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=CodeHeap 'non-nmethods',type=MemoryPool
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=CodeHeap 'non-nmethods',type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=CodeHeap 'non-nmethods',type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=CodeHeap 'non-nmethods',type=MemoryPool
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=Metaspace,type=MemoryPool
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=Metaspace,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=Metaspace,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=Metaspace,type=MemoryPool
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=CodeHeap 'profiled nmethods',type=MemoryPool
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=CodeHeap 'profiled nmethods',type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=CodeHeap 'profiled nmethods',type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=CodeHeap 'profiled nmethods',type=MemoryPool
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=Compressed Class Space,type=MemoryPool
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=Compressed Class Space,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=Compressed Class Space,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=Compressed Class Space,type=MemoryPool
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=G1 Eden Space,type=MemoryPool
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=G1 Eden Space,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=G1 Eden Space,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=G1 Eden Space,type=MemoryPool
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=G1 Old Gen,type=MemoryPool
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=G1 Old Gen,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=G1 Old Gen,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=G1 Old Gen,type=MemoryPool
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=G1 Survivor Space,type=MemoryPool
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=G1 Survivor Space,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=G1 Survivor Space,type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=G1 Survivor Space,type=MemoryPool
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryPoolImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=CodeHeap 'non-profiled nmethods',type=MemoryPool
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:name=CodeHeap 'non-profiled nmethods',type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=CodeHeap 'non-profiled nmethods',type=MemoryPool
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=CodeHeap 'non-profiled nmethods',type=MemoryPool
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.CompilationImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:type=Compilation
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:type=Compilation
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:type=Compilation
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=Compilation
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.MemoryImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:type=Memory
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:type=Memory
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:type=Memory
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=Memory
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.ManagementFactoryHelper$PlatformLoggingImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.util.logging:type=Logging
13:12:31.356 FINER [Repository.addMBean] - name = java.util.logging:type=Logging
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.util.logging:type=Logging
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.util.logging:type=Logging
13:12:31.356 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.ClassLoadingImpl
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:type=ClassLoading
13:12:31.356 FINER [Repository.addMBean] - name = java.lang:type=ClassLoading
13:12:31.356 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:type=ClassLoading
13:12:31.356 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:type=ClassLoading
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = com.sun.management:type=DiagnosticCommand
13:12:31.372 FINER [Repository.addMBean] - name = com.sun.management:type=DiagnosticCommand
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object com.sun.management:type=DiagnosticCommand
13:12:31.372 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered com.sun.management:type=DiagnosticCommand
13:12:31.372 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for com.sun.management.internal.GarbageCollectorExtImpl
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=G1 Young Generation,type=GarbageCollector
13:12:31.372 FINER [Repository.addMBean] - name = java.lang:name=G1 Young Generation,type=GarbageCollector
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=G1 Young Generation,type=GarbageCollector
13:12:31.372 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=G1 Young Generation,type=GarbageCollector
13:12:31.372 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for com.sun.management.internal.GarbageCollectorExtImpl
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.lang:name=G1 Old Generation,type=GarbageCollector
13:12:31.372 FINER [Repository.addMBean] - name = java.lang:name=G1 Old Generation,type=GarbageCollector
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.lang:name=G1 Old Generation,type=GarbageCollector
13:12:31.372 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.lang:name=G1 Old Generation,type=GarbageCollector
13:12:31.372 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for com.sun.management.internal.HotSpotDiagnostic
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = com.sun.management:type=HotSpotDiagnostic
13:12:31.372 FINER [Repository.addMBean] - name = com.sun.management:type=HotSpotDiagnostic
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object com.sun.management:type=HotSpotDiagnostic
13:12:31.372 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered com.sun.management:type=HotSpotDiagnostic
13:12:31.372 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.ManagementFactoryHelper$1
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.nio:name=mapped,type=BufferPool
13:12:31.372 FINER [Repository.addMBean] - name = java.nio:name=mapped,type=BufferPool
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.nio:name=mapped,type=BufferPool
13:12:31.372 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.nio:name=mapped,type=BufferPool
13:12:31.372 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.ManagementFactoryHelper$1
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.nio:name=direct,type=BufferPool
13:12:31.372 FINER [Repository.addMBean] - name = java.nio:name=direct,type=BufferPool
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.nio:name=direct,type=BufferPool
13:12:31.372 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.nio:name=direct,type=BufferPool
13:12:31.372 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for sun.management.ManagementFactoryHelper$1
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = java.nio:name=mapped - 'non-volatile memory',type=BufferPool
13:12:31.372 FINER [Repository.addMBean] - name = java.nio:name=mapped - 'non-volatile memory',type=BufferPool
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object java.nio:name=mapped - 'non-volatile memory',type=BufferPool
13:12:31.372 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered java.nio:name=mapped - 'non-volatile memory',type=BufferPool
13:12:31.372 FINER [StandardMBean.getMBeanInfo] - Building MBeanInfo for jdk.management.jfr.FlightRecorderMXBeanImpl
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = jdk.management.jfr:type=FlightRecorder
13:12:31.372 FINER [Repository.addMBean] - name = jdk.management.jfr:type=FlightRecorder
13:12:31.372 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object jdk.management.jfr:type=FlightRecorder
13:12:31.372 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered jdk.management.jfr:type=FlightRecorder
13:12:31.388 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = org.seleniumhq.grid:type=Config,name=BaseServerConfig
13:12:31.388 FINER [Repository.addMBean] - name = org.seleniumhq.grid:type=Config,name=BaseServerConfig
13:12:31.390 FINER [DefaultMBeanServerInterceptor.registerWithRepository] - Send create notification of object org.seleniumhq.grid:name=BaseServerConfig,type=Config
13:12:31.390 FINER [DefaultMBeanServerInterceptor.sendNotification] - JMX.mbean.registered org.seleniumhq.grid:type=Config,name=BaseServerConfig
13:12:31.492 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.1.196:5555
13:12:31.492 FINER [DefaultMBeanServerInterceptor.registerDynamicMBean] - ObjectName = org.seleniumhq.grid:type=Config,name=BaseServerConfig
13:12:31.492 FINER [Repository.addMBean] - name = org.seleniumhq.grid:type=Config,name=BaseServerConfig
13:12:31.601 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
13:12:31.617 DEBUG [SeleniumManager.getBinary] - Selenium Manager binary found at: C:\Users\invbr\.cache\selenium\manager\0.4.16\selenium-manager.exe
13:12:31.617 DEBUG [SeleniumManager.runCommand] - Executing Process: [--browser, chrome, --output, json, --debug]
13:12:31.645 DEBUG [ExternalProcess$Builder.lambda$start$0] - completed to copy the output of process 10568
13:12:31.645 DEBUG [SeleniumManager.getBinary] - Selenium Manager binary found at: C:\Users\invbr\.cache\selenium\manager\0.4.16\selenium-manager.exe
13:12:31.645 DEBUG [SeleniumManager.runCommand] - Executing Process: [--browser, MicrosoftEdge, --output, json, --debug]
13:12:31.671 DEBUG [ExternalProcess$Builder.lambda$start$0] - completed to copy the output of process 11808
13:12:31.672 DEBUG [SeleniumManager.getBinary] - Selenium Manager binary found at: C:\Users\invbr\.cache\selenium\manager\0.4.16\selenium-manager.exe
13:12:31.672 DEBUG [SeleniumManager.runCommand] - Executing Process: [--browser, firefox, --output, json, --debug]
13:12:31.693 DEBUG [ExternalProcess$Builder.lambda$start$0] - completed to copy the output of process 3532
13:12:31.695 DEBUG [SeleniumManager.getBinary] - Selenium Manager binary found at: C:\Users\invbr\.cache\selenium\manager\0.4.16\selenium-manager.exe
13:12:31.695 DEBUG [SeleniumManager.runCommand] - Executing Process: [--browser, internet explorer, --output, json, --debug]
13:12:31.715 DEBUG [ExternalProcess$Builder.lambda$start$0] - completed to copy the output of process 11012
13:12:31.716 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
```

**Comment by diemol** [comment]
Is that the full log?

**Comment by zcindori** [comment]
yes, it is all from log file

**Comment by diemol** [comment]
@joerg1985 @bonigarcia do you have an idea why we don't see any more output from the `SeleniumManager` class?

**Comment by zcindori** [comment]
works fine with selenium-server-4.17.0-SNAPSHOT

**Comment by bonigarcia** [comment]
> do you have an idea why we don't see any more output from the `SeleniumManager` class?

I don't know the cause, sorry. I can say that Selenium Manager 0.4.16 includes a condition to panic when JSON output is specified but no logs are gathered. So, Selenium Manager should always return a list of log traces (or throw an error).

**Comment by joerg1985** [comment]
@diemol `NodeOptions.discoverDrivers` does filter the drivers via, `WebDriverInfo::isAvailable`, this method swallows all the `WebDriverException`s internally.

The `DriverFinder.getPath` should not translate any `Exception`s while calling the selenium manager into `NoSuchDriverException`s. The `NoSuchDriverException` in `WebDriverInfo::isAvailable`/`WebDriverInfo::isPresent` should be swallowed and all others `WebDriverException`s should at least be logged. I can do this change the next days, to ensure there are logs when discovery of driver fails.


I think the root cause of this issue is the same as in #13261, the need for the visual c++ redist x86 in 4.16.x

**Comment by joerg1985** [comment]
@anandseshadri and @zcindori could you try to manually start the selenium-manager.exe (from selenium 4.16.0) to see if there is a error message shown?

**Comment by zcindori** [comment]
@joerg1985 how I can do that? I found only selenium manager file in zip folder.. did you mean selenium-server-4.16.0>start selenium-manager-4.16.0.jar?

**Comment by krmahadevan** [comment]
@zcindori - If you extract the selenium jar to a directory, you will find the selenium manager binaries in the below path `org/openqa/selenium/manager` (under the directory wherein u extracted the jar using `jar -xvf selenium-server-4.16.1.jar` command


```shell
➜  tree .
.
├── SeleniumManager.class
├── SeleniumManagerOutput$Log.class
├── SeleniumManagerOutput$Result.class
├── SeleniumManagerOutput.class
├── linux
│   └── selenium-manager
├── macos
│   └── selenium-manager
└── windows
    └── selenium-manager.exe

4 directories, 7 files
```

**Comment by zcindori** [comment]
I got this error: 
Title: selenium-manager.exe -System Error 
Description:
The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem.

**Comment by krmahadevan** [comment]
@zcindori Ok. I guess that confirms @joerg1985 hunch. The fix I think will be made available only in next version perhaps.

**Comment by diemol** [comment]
Thank you everyone for confirming this is fixed for the upcoming release, which can be already tested on 4.17.0-SNAPSHOT

**Comment by mike-maliska** [comment]
Just to add to this.  I had the same problem but the problem only showed up on 1 our of 12 nodes.  11 Nodes all worked just fine.
