### ISSUE TITLE
[🐛 Bug]:  Getting error while running script.

### ISSUE THREAD

**Issue by Himanshu-Batham1630** [SeleniumHQ/selenium#13306]
### What happened?

Chrome version: 120
selenium IDE: 3.141.59
Eclipse !DEVersion: 2023-09 (4.29.0) Build id: 20230907-1323
JDK: 8u202

### How can we reproduce the issue?

```shell
1: setup with above configuration
2: Write simple code: package javaPackage;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;


public class Openbrowser {

	public static void main(String[] args) {
		
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\deqode\\Downloads\\Automation\\Software\\chrome-win32\\chrome.exe");
    WebDriver driver= new ChromeDriver();
    driver.get("https://www.facebook.com/");
    driver.manage().timeouts().pageLoadTimeout(20, TimeUnit.SECONDS);
    
    driver.close();

		 

	}

}

3: Run the above code.
```

### Relevant log output

```shell
[8864:10496:1214/225232.099:ERROR:policy_logger.cc(156)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-M0BI1R2', ip: '192.168.4.3', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.9'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:202)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:188)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at javaPackage.Openbrowser.main(Openbrowser.java:14)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:11455/status] to be available after 20008 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:197)
	... 9 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 10 more
```

### Operating System

windows 10

### Selenium version

3.141.5

### What are the browser(s) and version(s) where you see this issue?

Version 120.0.6099.110

### What are the browser driver(s) and version(s) where you see this issue?

120.0.6099.71

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
It looks like you need a getting started guide: https://www.selenium.dev/documentation/webdriver/getting_started/
This should walk you through what all is needed to get up and going with Selenium.
