### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read:

### ISSUE THREAD

**Issue by jjqi92** [SeleniumHQ/selenium#13304]
### What happened?

when i execute this code: 

`ChromeOptions optionss = new ChromeOptions();
optionss.addArguments("disable-infobars");
optionss.addArguments("--disable-gpu");
optionss.addArguments("--no-sandbox");
driver = new RemoteWebDriver(new URL("http://10.6.1.82:4444"), optionss);`

that prompts "Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Unable to parse remote response:  "

### How can we reproduce the issue?

```shell
hub: java -jar /opt/tomcat/bin/selenium-server-4.16.1.jar hub

Node: java --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true -jar selenium-server-4.16.1.jar node --selenium-manager true --enable-managed-downloads true --hub http://10.6.1.82:4444 --port 8088

ChromeOptions optionss = new ChromeOptions();
optionss.addArguments("disable-infobars");
optionss.addArguments("--disable-gpu");
optionss.addArguments("--no-sandbox");
driver = new RemoteWebDriver(new URL("http://10.6.1.82:4444"), optionss);
```

### Relevant log output

```shell
10:32:30.953 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Unable to parse remote response:
Host info: host: 'DST68050', ip: '10.32.114.128'
10:32:30.980 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Unable to parse remote response:
Host info: host: 'DST68050', ip: '10.32.114.128'
10:32:30.980 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response:
Host info: host: 'DST68050', ip: '10.32.114.128'
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:164)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:72)
        at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
        at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)
        at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:50)
        at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:193)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:62)
        at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:87)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.grid.node.Node.execute(Node.java:262)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.json.JsonException: Unable to parse:
        at org.openqa.selenium.json.Json.toType(Json.java:169)
        at org.openqa.selenium.json.Json.toType(Json.java:152)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:122)
        ... 28 more
Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read:
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.14.1'
Driver info: driver.version: unknown
        at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:467)
        at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:333)
        at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:171)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146)
        at org.openqa.selenium.json.Json.toType(Json.java:206)
        at org.openqa.selenium.json.Json.toType(Json.java:167)
        ... 30 more
```

### Operating System

windows10

### Selenium version

java11 selenium4.16.1

### What are the browser(s) and version(s) where you see this issue?

chrome 版本 87.0.4280.66（正式版本） （32 位）

### What are the browser driver(s) and version(s) where you see this issue?

chromeDriver4.16.1

### Are you using Selenium Grid?

4.16.1

**Comment by titusfortner** [comment]
Selenium Manager does not support chrome versions older than 113, so you need to manage the driver yourself to use a browser that old. Double check that the version of Chrome & chromedriver actually getting used match. 
You can turn on logging to verify — https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by titusfortner** [comment]
Also, you shouldn't need any of those capabilities (https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md)
