### ISSUE TITLE
[🐛 Bug]: SessionNotCreatedException is raised when trying to run Chromium headless

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#13324]
### What happened?

Hi  
I hope this is not actually a bug; any help resolving this is greatly appreciated.  
I'm developing a program in Python using selenium and the chromium browser running headless. I think I've set it up correctly. But after much Duckduckgo-ing, I am still struggling to discover why it's not working.  
I've made a small program to demonstrate the issue I'm having. You see it's raising a `SessionNotCreatedException`. This demonstrates the exact errors in the actual program.  
Thanks in advance!

### How can we reproduce the issue?

```shell
#!/usr/bin/env python3
import logging
from selenium import webdriver

log_path = './log'
logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(log_path)
logger.addHandler(handler)
logging.getLogger('selenium.webdriver.common').setLevel(logging.DEBUG)
logger.debug("this is detailed debug information:")

def main():
    with open(log_path, 'r') as fp:
        service = webdriver.ChromeService(executable_path='/usr/local/bin/chromedriver')
        options = webdriver.ChromeOptions()
        options.add_argument('--headless')
        options.add_argument("--remote-debugging-port=9999")
        driver = webdriver.Chrome(service=service, options=options)
        driver.quit()

if __name__ == '__main__':
    main()
```

### Relevant log output

```shell
$ test_chrome.py
Traceback (most recent call last):
  File "/workspace/3LS_TruFetch/modules/test_chrome.py", line 23, in <module>
    main()
  File "/workspace/3LS_TruFetch/modules/test_chrome.py", line 19, in main
    driver = webdriver.Chrome(service=service, options=options)
  File "/home/jfa/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/jfa/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/jfa/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "/home/jfa/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/jfa/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/home/jfa/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location /usr/local/bin/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```  
And logger output:  
```
$ more log 
this is detailed debug information:
Started executable: `/usr/local/bin/chromedriver` in a child process with pid: 2445 using 0 to output -3
POST http://localhost:54246/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": ["--headless", "--remote-debugging-port=9999"]}}}}
Remote response: status=500 | data={"value":{"error":"session not created","message":"session not created: Chrome failed to start: exited normally.\n  (chrome not reachable)\n  (The process started from chrome location /usr/local/bin/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)","stacktrace":""}} | headers=HTTPHeaderDict({'Content-Length': '300', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
```
```


### Operating System

OS: FreeBSD 14.0-RELEASE-p2

### Selenium version

Python: 3.9.18  Selenium: 4.16.0  

### What are the browser(s) and version(s) where you see this issue?

Chromium: 119.0.6045.199  

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver: 119.0.6045.199

### Are you using Selenium Grid?

?

**Comment by diemol** [comment]
Recent ChromeDriver versions need the browser binary path as well. This answer applies to your case
https://stackoverflow.com/a/53078276

```
options.binary_location = "/path/to/chrome "
```

If you have more questions, please use the links provided below.
