### ISSUE TITLE
[🐛 Bug]: Chrome MacOS - org.openqa.selenium.WebDriverException: disconnected: Unable to receive message from renderer

### ISSUE THREAD

**Issue by NickOppersdorff** [SeleniumHQ/selenium#13345]
### What happened?

Hello, I have recently started encountering the below issue in approximately 50% of the tests I am running when using ChromeDriver locally.  This is when running tests that have not changed in a while, so not sure what the issue might be.  I suspect an issue with driver.close() not closing the chromedriver process correctly. 

A colleague on an M1 Mac can run the same tests with no issues.  I get the issue when running on an M3 Max.  Raising for visibility.  I am working to create a simple case that recreates the issue.

[logsToFile15334819263966744144.log](https://github.com/SeleniumHQ/selenium/files/13743333/logsToFile15334819263966744144.log)

```
org.openqa.selenium.WebDriverException: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=120.0.6099.129)
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.2.1', java.version: '17.0.9'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [c40e72ecffabdae06708c4aa9921d22d, findElement {using=css selector, value=[data-testid*='velo-navigation-drawer-toggle-button-']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 120.0.6099.129, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: /var/folders/5w/4k1dkl0d1hl...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:53958}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:53958/devtoo..., se:cdpVersion: 120.0.6099.129, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: c40e72ecffabdae06708c4aa9921d22d

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:199)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:132)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:51)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:194)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:190)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:205)
	at com.velopayments.qa.base.BasePageObject.waitFor(BasePageObject.java:329)
	at com.velopayments.qa.base.BasePageObject.waitForVisibilityOf(BasePageObject.java:277)
	at com.velopayments.qa.pages.common.BasePortalMenu.waitForMenuToLoad(BasePortalMenu.java:13)
	at com.velopayments.qa.base.BasePortalTest.logInToBackOfficePortal(BasePortalTest.java:102)
	at com.velopayments.qa.backoffice.TestACHFundingAutoTopUps.backOfficeLogInAndGoToSourceAccountDetails(TestACHFundingAutoTopUps.java:263)
	at com.velopayments.qa.backoffice.TestACHFundingAutoTopUps.targetBalanceAndMinimumBalanceCannotBeSetToTheSameValue(TestACHFundingAutoTopUps.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
```

### How can we reproduce the issue?

```shell
Working on a simpler test to try and recreate, but can't reproduce outside of out existing test framework.
```

### Relevant log output

```shell
Attempting to get better logs than just the selenium stacktrace...
```

### Operating System

MacOS Sonoma 14.2.1 (23C71)

### Selenium version

4.10.0 / 4.16.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.109 & 120.0.6099.129

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 120.0.6099.109

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
In addition, please provide the sample code using the latest version of Selenium. We cannot fix issues in old versions.

**Comment by evalalos** [comment]
+1

I've just raised similar issue, but I can reproduce this one as well (with the same exception).
In both cases, new M3 chip is used. 

https://github.com/SeleniumHQ/selenium/issues/13348

**Comment by NickOppersdorff** [comment]
I get this issue on everything from waiting using expected conditions to navigating to URLs, but am struggling to recreate the issue with a simple example that can be shared.  I am hoping to have something completed this morning.

**Comment by NickOppersdorff** [comment]
This turned out to be related to running using a x64 version of my Java 17 SDK rather than the aarch64 version.

Steps I took to point me in the right direction:

1. Enabled verbose logging for Chromedriver:
`File logLocation = File.createTempFile("logsToFile", ".log");
                    System.out.println("Log location: " + logLocation.getAbsolutePath());
                    ChromeDriverService service =
                        new ChromeDriverService.Builder().withLogLevel(ChromiumDriverLogLevel.DEBUG).withVerbose(true).withLogFile(logLocation).build();
                    ChromeOptions macChromeOptions = getLocalChromeOptions();
                    macChromeOptions.setBinary("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome");
                    driver = new ChromeDriver(service, macChromeOptions);`

2. Run the test (which fails)
3. Inspect the Chromedriver logs (log file path is printed to the console)
4. I saw the following error on chrome startup in the logs:
_[64924:259:1222/111610.148149:ERROR:chrome_browser_main.cc(1072)] The use of Rosetta to run the x64 version of Chromium on Arm is neither tested nor maintained, and unexpected behavior will likely result. Please check that all tools that spawn Chromium are Arm-native._
5. Verified both Chrome and Chromedriver were arm64 (brew does a good job of installing the correct versions)
6. Checked Java platform in the release doc (it should say **OS_ARCH="aarch64"**
`vi /Library/Java/JavaVirtualMachines/JAVA_VERSION/Contents/Home/release` 

Closing this issue as it isn't a bug in Selenium.
