### ISSUE TITLE
[🐛 Bug]: find_element does not work in /html/rabby-kit// section, cannot locate any element from this section

### ISSUE THREAD

**Issue by andriipovkh** [SeleniumHQ/selenium#13380]
### What happened?

For instance, if you go to the website https://debank.com/ and press "Log in via web3 wallet", you won't be able to locate any element, using find_element, that pop-up in the "connect wallet" window, which is located in /html/rabby-kit// section.
![123](https://github.com/SeleniumHQ/selenium/assets/33901675/6cb0700d-c26c-4012-9424-db13174052d8)
![456](https://github.com/SeleniumHQ/selenium/assets/33901675/ba35d19f-f43d-4a9e-8520-72407960d3f9)

### How can we reproduce the issue?

```shell
Find any website (for example https://debank.com/) which have /html/rabby-kit// section and try to use find_element to locate any element from such section.
```

### Relevant log output

```shell
py .\debank.py

DevTools listening on ws://127.0.0.1:50304/devtools/browser/e56b2db4-181b-4922-a530-6d06f0a71e54
Traceback (most recent call last):
  File "C:\Users\Andrii\Desktop\debank.py", line 145, in <module>
    element = browser.find_element(By.ID, 'svelte-1brzyjm')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrii\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrii\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Andrii\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="svelte-1brzyjm"]"}
  (Session info: chrome=120.0.6099.130); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00007FF74B962142+3514994]
        (No symbol) [0x00007FF74B580CE2]
        (No symbol) [0x00007FF74B4276AA]
        (No symbol) [0x00007FF74B471860]
        (No symbol) [0x00007FF74B47197C]
        (No symbol) [0x00007FF74B4B4EE7]
        (No symbol) [0x00007FF74B49602F]
        (No symbol) [0x00007FF74B4B28F6]
        (No symbol) [0x00007FF74B495D93]
        (No symbol) [0x00007FF74B464BDC]
        (No symbol) [0x00007FF74B465C64]
        GetHandleVerifier [0x00007FF74B98E16B+3695259]
        GetHandleVerifier [0x00007FF74B9E6737+4057191]
        GetHandleVerifier [0x00007FF74B9DE4E3+4023827]
        GetHandleVerifier [0x00007FF74B6B04F9+689705]
        (No symbol) [0x00007FF74B58C048]
        (No symbol) [0x00007FF74B588044]
        (No symbol) [0x00007FF74B5881C9]
        (No symbol) [0x00007FF74B5788C4]
        BaseThreadInitThunk [0x00007FFC9DF67344+20]
        RtlUserThreadStart [0x00007FFC9F2C26B1+33]
```

### Operating System

Windows 10 Pro 22H2

### Selenium version

4.15.2

### What are the browser(s) and version(s) where you see this issue?

Google Chrome Version: 120.0.6099.109 (r1217362)

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 120.0.6099.109 (r1217362)

**Comment by titusfortner** [comment]
I thought we had Shadow Root examples in our docs, but doesn't look like it. You need to switch to the shadow root context to access those elements — https://titusfortner.com/2021/11/22/shadow-dom-selenium.html
