### ISSUE TITLE
[🐛 Bug]: openQA.Selenium.WebDriverException : unknown error: network conditions must be set before it can be retrieved

### ISSUE THREAD

**Issue by SuravinS** [SeleniumHQ/selenium#13390]
### What happened?

I am encountering a critical issue after upgrading to the latest versions of Allure.Net.Commons and Allure.NUnit. Previously, I was using the deprecated Allure version NUnit.Allure" Version=1.2.1.1, and my code was working fine. However, after migrating to the latest Allure versions, I had to make adjustments to my existing code, specifically in the usage of using Allure.Net.Commons;

`// Attachment code before upgrade
AllureLifecycle.Instance.AddAttachment("Page source", "application/xml", byteArray, "xml");
AllureApi.AddAttachment("Page source", "application/xml", byteArray, "xml");`

`// Attachment code after upgrade
AllureLifecycle.Instance.AddAttachment(screenshotPath);
AllureApi.AddAttachment(screenshotPath);`

### How can we reproduce the issue?

```shell
Reproducing the same issue will be possible by utilizing the mentioned libraries, having a Selenium C# project based on NUnit, implementing a page factory model, and using Chrome options to initialize the drive

   if (browser.Equals("chrome", StringComparison.OrdinalIgnoreCase))
   {
       new DriverManager().SetUpDriver(new ChromeConfig());
       ChromeOptions options = new ChromeOptions();
       options.AddArgument("--incognito");
       options.AddArgument("--disable-extensions");
       options.AddArgument("--disable-infobars");
       Drivers.Value = new ChromeDriver(options);
   }


<ItemGroup>
	  <PackageReference Include="Allure.Net.Commons" Version="2.11.0" />
	  <PackageReference Include="Allure.NUnit" Version="2.11.0" />
	  <PackageReference Include="JUnitTestLogger" Version="1.1.0" />
	  <PackageReference Include="NTextCat" Version="0.3.65" />
	  <PackageReference Include="NUnit" Version="4.0.1" />
	  <PackageReference Include="NUnit.Engine.Api" Version="3.16.3" />
	  <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0-preview-23577-04" />
	  <PackageReference Include="WebDriverManager" Version="2.17.1" />
	  <PackageReference Include="DotNetSeleniumExtras.PageObjects" Version="3.11.0" />
	  <PackageReference Include="DotNetSeleniumExtras.PageObjects.Core" Version="4.14.1" />
	  <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="NUnit.Console" Version="3.16.3" />
	  <PackageReference Include="System.Runtime" Version="4.3.1" />
	  <PackageReference Include="Selenium.Support" Version="4.16.2" />
	  <PackageReference Include="Selenium.WebDriver" Version="4.16.2" />
	  <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
  </ItemGroup>
```

### Relevant log output

```shell
Newtonsoft.Json.JsonSerializationException : Error getting value from 'NetworkConditions' on 'OpenQA.Selenium.Chrome.ChromeDriver'. ----> OpenQA.Selenium.WebDriverException : unknown error: network conditions must be set before it can be retrieved (Session info: chrome=120.0.6099.130)
```

### Operating System

Windows 11

### Selenium version

dotnet v4.16.2

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
* In 4.16, you shouldn't need `DriverManager` any longer, Selenium should be able to do everything for you natively.
* disable-infobars is deprecated — https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md#removed-flags

As for your specific issue, is there a stack trace? What code is it actually failing on?

**Comment by SuravinS** [comment]
Thank you for your response. @titusfortner 

It failed in my method class, as illustrated in the following example, where I am utilizing the DoubleClickOnElement method from the BasePage class. Similarly, almost all my cases failed in my base class with different methods I used. I identified one common factor across all methods: whenever I parametrize the IWebElement element, it fails. Besides that, I do not have any clues. I have used this interface in the same class as "protected IWebDriver driver."


Method class
    
```
[AllureStep]
     public RoundGroupListPage DoubleClickRoundGroup(string name)
     {
         List<IWebElement> rows = GetAllElements(roundGroupRows);
         foreach (var row in rows)
         {
             IWebElement nameCell = row.FindElement(By.XPath("./div[contains(@class,'l2')]"));
             if (GetElementText(nameCell) == name)
             {
                 DoubleClickOnElement(row);
                 break;
             }
         }
         return this;
     }
```

BasePage class
```
[AllureStep]
public void DoubleClickOnElement(IWebElement element)
{
    Actions act = new Actions(IWebDriverManager.GetDriver());
    WaitUtil.WaitForElementClickable(element);
    act.DoubleClick(element).Perform();
}
```

**Comment by titusfortner** [comment]
Right, which line of code? Is there a stacktrace for the error?

**Comment by SuravinS** [comment]
```
at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Allure.Net.Commons.Functions.FormatFunctions.Format(Object value, IReadOnlyDictionary`2 formatters)
   at Allure.Net.Commons.Steps.AllureStepParameterHelper.<>c__DisplayClass8_0.<GetStepParameters>b__1(ValueTuple`2 parameter, Object value)
   at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Allure.Net.Commons.Steps.AllureStepAspectBase.Around(String name, Object[] args, Func`2 target, MethodBase metadata, Type returnType)
   at automated_tests.Source.Core.BasePage.__a$_around_DoubleClickOnElement_100669356_w_0(Object[] )
   at automated_tests.Source.Core.BasePage.DoubleClickOnElement(IWebElement element)
   at automated_tests.Source.Main.Pages.Services.RoundGroupListPage.__a$_around_DoubleClickRoundGroup_100664664_o(String name) in F:\Jenkins\workspace\RegressionTests\automated-tests\Source\Main\Pages\Services\RoundGroupListPage.cs:line 23
   at automated_tests.Source.Main.Pages.Services.RoundGroupListPage.__a$_around_DoubleClickRoundGroup_100664664_u(Object[] )
   at Allure.Net.Commons.Steps.AllureAbstractStepAspect.WrapSync[T](Func`2 target, Object[] args, MethodBase metadata, String stepName, List`1 stepParameters)
--WebDriverException
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Chromium.ChromiumDriver.get_NetworkConditions()
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
```

**Comment by nvborisenko** [comment]
`WebDriver/WebElement` object is not supposed to be serialized. What I see `Newtonsoft.Json` tries to serialize `NetworkConditions` property, and it gets the error:
```
unknown error: network conditions must be set before it can be retrieved
```

I don't think selenium project can do something for you to fix it. Properties are basic things, they try wrapping a state of browser. For instance `driver.Url` - the remote call is hidden under this simple code. Probably, we may revisit this approach and use properties as object state representation, but I don't believe it is realistic scenario in near feature.

More realistic scenario is to ask allure project like "how to avoid serialization of some specific properties of some specific objects?".

In any case as a workaround to mitigate it you can use your own implementation of types passed as method's argument.

```csharp
[AllureStep]
void SomeMethod(IWebDriver driver) {}
```

Here you can define new class like
```csharp
class MyOwnDriver : IWebDriver
{
  IWebDriver driver;

  public MyOwnDriver(IWebDriver driver) { this.driver = driver; }

  // this property can be serialized
  public string Url { get { return driver.Url } }
}
```

Then allure will serialize your type instead of `ChromiumDriver`. It also means that you should use `MyOwnDriver` type across your code everywhere. Ugly..

Personally I prefer to not mark methods, which take `IWebDriver/IWebElement` arguments, with `[AllureStep]` attribute. Easy.
