### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by sbsutton98** [SeleniumHQ/selenium#13398]
### What happened?

I'm working on gathering data for a job, though I assumed I would be able to get it done faster than I have. 

I am trying to automate the downloading of data from this website  'https://lasd.org/transparency/part1and2crimedata/#part1,' but cannot seem to get through to it. The error I keep on getting I an attribute error. 

Any help is appreciated 

### How can we reproduce the issue?

```shell
import os
import selenium.webdriver as webdriver
from selenium.webdriver.firefox.service import Service
import time
from selenium.webdriver.firefox.options import Options



firefox_driver = os.path.join(os.getcwd(),'Drivers', 'gecko' )

def download_data(url, xpath, path):
    driver = webdriver.Firefox(firefox_driver)
    
    try:
        
        driver.get(url)
        
        time.sleep(5)
        
       
        button = driver.find_by_xpath(xpath)
        button.click()
        
        time.sleep(10)
        
        print(f"Downloaded data successfully and saved it to {path}")
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        driver.quit()

if __name__ == "__main__":
    
    url = 'https://lasd.org/transparency/part1and2crimedata/#part1'
    
    # Replace 'your_button_xpath' with the XPath of the button triggering the download
    xpath = '/html/body/div[1]/div[2]/div/div/div/div/div[6]/div[1]/div/div/div[2]/p[1]/a'
    
    # Replace 'your_file_name.extension' with the desired file name and extension
    path = '/Users/samuelsutton/Desktop/PHS_code/trial.csv'

    download_data(url, xpath, path)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/samuelsutton/Desktop/PHS_code/gecko_driver.py", line 46, in <module>
    download_data(url, xpath, path)
  File "/Users/samuelsutton/Desktop/PHS_code/gecko_driver.py", line 13, in download_data
    driver = webdriver.Firefox(firefox_driver)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'
```

### Operating System

macOS Sonoma 14.1.2

### Selenium version

selenium==4.16.0 for Python 3.11.4

### What are the browser(s) and version(s) where you see this issue?

Firefox 121

### What are the browser driver(s) and version(s) where you see this issue?

 geckodriver-v0.34.0-macos.tar.gz

**Comment by titusfortner** [comment]
Oh, you aren't having the problem I thought you were having.

This is not valid: `driver = webdriver.Firefox(firefox_driver)`

You should not need to specify the driver location, Selenium does this automatically now.
If you do need  to specify the driver, you need to pass it in to the Service class and pass that into the driver constructor: https://www.selenium.dev/documentation/webdriver/drivers/service/?tab=python#driver-location
