### ISSUE TITLE
[🐛 Bug]: Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: dev/failsafe/Policy

### ISSUE THREAD

**Issue by DcMnh** [SeleniumHQ/selenium#13412]
### What happened?

I was developing a JavaFX & Selenium automation application using IntelliJ IDEA. I created the project using the IntelliJ IDEA's JavaFX project structure, and then installed selenium-java library and then add it to the project's Maven dependency file (pom.xml).

The project's idea is to have a Java GUI that takes in some specific information from the user, and then pass the information to another Java file, which acts as a back-end and then perform all the automation using Selenium WebDriver.

The project itself was originally running selenium 4.3.0, when it comes across the line "driver.get("https://www.google.com");" line, the Chrome Browser did launch but it unfortunately got the bug in the #11036.

I later update the selenium-java version to 4.16.0, but not only did the Chrome Browser not launch, I got another bug, which was this issue all about.

I also tried downloading the dev.failsafe or net.jodah.failsafe library and then add them to my pom.xml but it doesn't help me. So please I need help with this :( What should I do?

### How can we reproduce the issue?

```shell
ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        WebDriver driver = new ChromeDriver(options);
        driver.get("https://www.google.com");
```

### Relevant log output

```shell
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: dev/failsafe/Policy
	at org.seleniumhq.selenium.http/org.openqa.selenium.remote.http.ClientConfig.<clinit>(ClientConfig.java:33)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)
	at com.example.demo3/main.automation.automationProcess(automation.java:33)
	at com.example.demo3/com.example.demo3.HelloApplication.lambda$start$0(HelloApplication.java:130)
	at javafx.base@21-ea/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21-ea/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21-ea/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21-ea/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@21-ea/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21-ea/javafx.scene.Node.fireEvent(Node.java:8875)
	at javafx.controls@21-ea/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@21-ea/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at javafx.controls@21-ea/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@21-ea/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@21-ea/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@21-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21-ea/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21-ea/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21-ea/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21-ea/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21-ea/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21-ea/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21-ea/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21-ea/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.graphics@21-ea/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21-ea/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21-ea/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21-ea/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21-ea/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21-ea/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: dev.failsafe.Policy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 50 more
```

### Operating System

Windows 11

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

ChromeDriver 120.0.6099.71

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 120.0.6099.71

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
It seems you need to package all dependencies so you can run you application. I do not have much experience with JavaFX but it is not a common use case. I would suggest to follow something like this https://stackoverflow.com/questions/70175403/how-to-generate-javafx-jar-from-gradle-including-all-dependencies and if you have more questions, please use the link below.
