### ISSUE TITLE
[🐛 Bug]: SafariDriver dotnet: System.Net.Http.HttpRequestException: Connection refused

### ISSUE THREAD

**Issue by Tiberriver256** [SeleniumHQ/selenium#13410]
### What happened?

Attempting to use the dotnet SafariDriver seems to produce an error message. The node safari driver works fine on the same machine, so I don't believe it has anything to do with how it is set up but I have a repo and build logs you can review.

Repo:
https://dev.azure.com/tiberriver256/azure-experiments/_git/selenium-safari

Build:
https://dev.azure.com/tiberriver256/azure-experiments/_build?definitionId=14

### How can we reproduce the issue?

Run the following c# code:

```cs
using OpenQA.Selenium.Safari;

var service = SafariDriverService.CreateDefaultService();
service.HostName = "127.0.0.1";
service.Start();
var driver = new SafariDriver(service, new SafariOptions(), TimeSpan.FromSeconds(120));
driver.Navigate().GoToUrl("https://www.google.com");
```

### Relevant log output

```txt
System.Net.Http.HttpRequestException: Connection refused (localhost:49195)
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenQA.Selenium.Safari.SafariDriverService.<>c__DisplayClass14_0.<<get_IsInitialized>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenQA.Selenium.Safari.SafariDriverService.get_IsInitialized()
```

### Operating System

macOS 12 Monterey

### Selenium version

Dotnet 4.16.2

### What are the browser(s) and version(s) where you see this issue?

Safari 17.2 (17617.1.17.11.11)

### What are the browser driver(s) and version(s) where you see this issue?

SafariDriver 17.2 (17617.1.17.11.11)

### Are you using Selenium Grid?

N/A

**Comment by Tiberriver256** [comment]
Looking into this further, it is running fine. It just takes long enough for the driver to initialize that my logs are flooded with the exceptions from [this line](https://github.com/SeleniumHQ/selenium/blob/e1e538e5b72a8558ef41a65fd5f01aae0ab7132a/dotnet/src/webdriver/DriverService.cs#L239C21-L239C51) in the `IsInitialized` boolean.

Is there a way to avoid printing those error logs to the console while the driver initializes?

**Comment by nvborisenko** [comment]
1. It should not print anything to Console (we should remove it).
2. Can you adjust your experiment to understand how long it needs to be initialized?
3. I see something deprecated in your code. `warning CS0618: 'SafariDriverService.CreateDefaultService(SafariOptions)' is obsolete: 'CreateDefaultService() now evaluates options in Driver constructor'`

**Comment by Tiberriver256** [comment]
Updated to use `BenchMarkDotNet` and got the following results:

| Method                     | Mean     | Error    | StdDev   | Median   |
|--------------------------- |---------:|---------:|---------:|---------:|
| SafariDriverServiceStartup | 516.9 ms | 69.97 ms | 195.0 ms | 434.0 ms |

[Build](https://dev.azure.com/tiberriver256/azure-experiments/_build/results?buildId=140&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7dae026f-9e99-5d65-075e-3f7579577f94)

Note the time it takes must be pretty variable as a configuration option controls that [here](https://github.com/SeleniumHQ/selenium/blob/e1e538e5b72a8558ef41a65fd5f01aae0ab7132a/dotnet/src/webdriver/DriverService.cs#L413C9-L426) `InitializationTimeout`.

**Comment by titusfortner** [comment]
@nvborisenko are there things we are writing to console that we can move to the logging solution you created?

**Comment by nvborisenko** [comment]
@titusfortner right, this is something for internal logging consumption.

@Tiberriver256 It is not clear what you have measured, let's measure the following:
```csharp
var service = SafariDriverService.CreateDefaultService();
service.HostName = "127.0.0.1";
service.Start();
var driver = new SafariDriver(service, new SafariOptions(), TimeSpan.FromSeconds(120));
```

I don't believe it takes ~500ms.

**Comment by nvborisenko** [comment]
OK, I see what you have measured:
```csharp
var service = SafariDriverService.CreateDefaultService();
service.Start();
```

And its mean value is  500ms. Then what is a problem? That it is spamming to console?

**Comment by Tiberriver256** [comment]
Yep, the only problem is the spamming
