### ISSUE TITLE
[🐛 Bug]: selenium-manager does not install drivers

### ISSUE THREAD

**Issue by konflic** [SeleniumHQ/selenium#13436]
### What happened?

Can't start standalone selenium server using --webdriver-manager true option. On screenshot it is seen that 4.15.0 starts ok.
![Screenshot from 2024-01-14 17-26-51](https://github.com/SeleniumHQ/selenium/assets/44262112/7e401144-4977-47e0-80a9-e05364347a9d)

### How can we reproduce the issue?

```shell
Try to run selenium server java -jar selenium-server standalone --selenium-manager true (using version 4.16.1)
```

### Relevant log output

```shell
PS C:\selenium> java -jar .\selenium-server-4.16.1.jar standalone --selenium-manager true
17:23:42.005 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
17:23:42.005 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
17:23:42.614 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
17:23:42.786 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:166)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:217)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:47)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:262)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:513)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:232)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:79)
        ... 22 more
PS C:\selenium> java -jar .\selenium-server-4.15.0.jar standalone --selenium-manager true
17:25:51.617 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
17:25:51.633 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
17:25:52.227 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
17:25:59.866 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","platformName": "Windows 10"} 4 times
17:25:59.882 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge","platformName": "Windows 10"} 4 times
17:25:59.882 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox","platformName": "Windows 10"} 4 times
17:25:59.882 INFO [NodeOptions.report] - Adding Internet Explorer for {"browserName": "internet explorer","platformName": "Windows 10"} 1 times
17:25:59.900 INFO [Node.<init>] - Binding additional locator mechanisms: relative
17:25:59.913 INFO [GridModel.setAvailability] - Switching Node 37812c2b-cb58-4344-a7b2-e0c92fbb0cdc (uri: http://192.168.0.111:4444) from DOWN to UP
17:25:59.913 INFO [LocalDistributor.add] - Added node 37812c2b-cb58-4344-a7b2-e0c92fbb0cdc at http://192.168.0.111:4444. Health check every 120s
17:26:00.118 INFO [Standalone.execute] - Started Selenium Standalone 4.15.0 (revision 1d14b5521b): http://192.168.0.111:4444
```

### Operating System

Windows 10

### Selenium version

Java 17, Selenium 4.16.1

### What are the browser(s) and version(s) where you see this issue?

None

### What are the browser driver(s) and version(s) where you see this issue?

None

### Are you using Selenium Grid?

4.16.1

**Comment by titusfortner** [comment]
It works for me. Can you add: ` --log-level FINE`

**Comment by krishtoautomate** [comment]
Turn off vpn if any and rerun test

**Comment by diemol** [comment]
I am closing this because we did not get more information.
