### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.json.JsonException: Unable to parse:

### ISSUE THREAD

**Issue by jesprisco** [SeleniumHQ/selenium#13431]
### What happened?

Getting a large number of test failures due to org.openqa.selenium.json.JsonException: Unable to parse: error. These errors were previously not happening and seem to be increasing in frequency which each build I run. These tests are running in Browserstack

### How can we reproduce the issue?

```shell
It doesnt seem to be isolated to a particular script. But here is one that has triggered the error below:

public void selectElementFromListByExactText(WebDriver webdriver, List<WebElement> elementList, String elementText){
		elementText = elementText.toUpperCase();
		boolean elementFound = false;
		for(WebElement anElement : elementList){
			if(this.isElementDisplayed(webdriver, anElement) && isTextEquals(webdriver, anElement, elementText)){
				elementFound = true;
				click(webdriver, anElement);
				break;
			}
		}
		if(!elementFound)
			throw new NoSuchElementException(generateErrorMessage(elementText));
	}
```

### Relevant log output

```shell
org.openqa.selenium.json.JsonException: Unable to parse: <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>
	at org.openqa.selenium.json.Json.toType(Json.java:57)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:313)
	at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:307)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:40)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:293)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:290)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at pages.Utils.PageBase.waitForVisibilityOfElement(PageBase.java:32)
	at pages.Utils.PageBase.isElementDisplayed(PageBase.java:1536)
	at pages.Utils.PageBase.selectElementFromListByExactText(PageBase.java:1015)
	at pages.IZ.Dialogues.CreateProfileField.selectFieldTypeOption(CreateProfileField.java:43)
	at pages.IZ.Dialogues.CreateProfileField.selectFieldType(CreateProfileField.java:52)
	at tests2.IZ.create.Contacts.ProfileFields.Demographics.createAndRemoveAllDemographicOptions(Demographics.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_382'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:126)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:141)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.Json.toType(Json.java:71)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	... 34 more
```

### Operating System

Windows 10

### Selenium version

Selenium Java 4.7.2

### What are the browser(s) and version(s) where you see this issue?

Chrome Latest

### What are the browser driver(s) and version(s) where you see this issue?

selenium-chrome-driver 4.7.2

**Comment by diemol** [comment]
The error happens because somehow BrowserStack is returning
```
<center><h1>500 Internal Server Error</h1></center>
```
and that is not a JSON.

It is better if you reach out to their customer support and report this. There is nothing we can do on the Selenium side.

**Comment by jesprisco** [comment]
Thank you!
