### ISSUE TITLE
[🐛 Bug]: Java17, input.readArray method not found

### ISSUE THREAD

**Issue by ixiaofu** [SeleniumHQ/selenium#13443]
### What happened?

In Java17, using selenium devtools, it was found that the input.readArray method does not exist.

<img width="1413" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/7697766/3cd82ce5-8ca0-4649-8b74-a4121d56c8ac">

### How can we reproduce the issue?

```shell
1. Create java workspace, use java 17.0.9
2. Use Selenium 4.16.1
3. Create ChromeDevTools
3.1 this.chromeDevTools.createSession();
3.2 this.chromeDevTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
3.3 this.chromeDriver.get("https://www.domain.com");
4. Run java workspace
5. java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'
```

### Relevant log output

```shell
INFO 37392 --- [  restartedMain] com.yyyyyyy.xxxxxxx.xxxxxxxApplication       : Starting xxxxxxxApplication using Java 17.0.9 with PID 37392 (/Users/yyyyyyy/custom/java/xxxxxxx/build/classes/java/main started by yyyyyyy in /Users/yyyyyyy/custom/java/xxxxxxx)
 INFO 37392 --- [  restartedMain] com.yyyyyyy.xxxxxxx.xxxxxxxApplication       : No active profile set, falling back to 1 default profile: "default"
 INFO 37392 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
 INFO 37392 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
 INFO 37392 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with ports 18443 (https), 18080 (http)
 INFO 37392 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
 INFO 37392 --- [  restartedMain] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.17]
 INFO 37392 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
 INFO 37392 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 487 ms
 INFO 37392 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
 INFO 37392 --- [  restartedMain] o.a.t.util.net.NioEndpoint.certificate   : Connector [https-jsse-nio-18443], TLS virtual host [_default_], certificate type [UNDEFINED] configured from keystore [/Users/yyyyyyy/.keystore] using alias [1] with trust store [null]
 INFO 37392 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on ports 18443 (https), 18080 (http) with context path ''
 INFO 37392 --- [  restartedMain] com.yyyyyyy.xxxxxxx.xxxxxxxApplication       : Started xxxxxxxApplication in 1.059 seconds (process running for 1.321)
 INFO 37392 --- [io-18080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
 INFO 37392 --- [io-18080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
 INFO 37392 --- [io-18080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
ERROR 37392 --- [io-18080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'] with root cause

java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'
  at org.openqa.selenium.devtools.v120.target.Target.getTargets(Target.java:153) ~[selenium-devtools-v120-4.16.1.jar:na]
  at org.openqa.selenium.devtools.v120.v120Target.getTargets(v120Target.java:55) ~[selenium-devtools-v120-4.16.1.jar:na]
  at org.openqa.selenium.devtools.DevTools.findTarget(DevTools.java:171) ~[selenium-remote-driver-4.14.1.jar:na]
  at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:131) ~[selenium-remote-driver-4.14.1.jar:na]
  at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:117) ~[selenium-remote-driver-4.14.1.jar:na]
  at com.yyyyyyy.xxxxxxx.utils.selenimu.LoginManager.initDriver(LoginManager.java:75) ~[main/:na]
  at com.yyyyyyy.xxxxxxx.utils.selenimu.LoginManager.doLogin(LoginManager.java:127) ~[main/:na]
  at com.yyyyyyy.xxxxxxx.controller.UserController.login(UserController.java:25) ~[main/:na]
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
  at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:262) ~[spring-web-6.1.2.jar:6.1.2]
  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190) ~[spring-web-6.1.2.jar:6.1.2]
  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.2.jar:6.1.2]
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917) ~[spring-webmvc-6.1.2.jar:6.1.2]
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829) ~[spring-webmvc-6.1.2.jar:6.1.2]
  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.2.jar:6.1.2]
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.2.jar:6.1.2]
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.2.jar:6.1.2]
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.2.jar:6.1.2]
  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.1.2.jar:6.1.2]
  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.17.jar:6.0]
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.2.jar:6.1.2]
  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.17.jar:6.0]
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.2.jar:6.1.2]
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.2.jar:6.1.2]
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.2.jar:6.1.2]
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.2.jar:6.1.2]
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.2.jar:6.1.2]
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.2.jar:6.1.2]
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:597) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.17.jar:10.1.17]
  at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]
```

### Operating System

MacOS 14.0

### Selenium version

4.16.1

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 120.0.6099.216 arm

### What are the browser driver(s) and version(s) where you see this issue?

selenium-chrome-driver-4.14.1.jar

**Comment by ixiaofu** [comment]
```java
package com.xxx;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.DevTools;
import org.openqa.selenium.devtools.v120.network.Network;

class Test {

  private WebDriver chromeDriver;

  private DevTools chromeDevTools;

  private WebDriver getDriver() {
      WebDriver driver = new ChromeDriver();
      driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
      return driver;
  }

  private boolean initDriver() {
      if (this.chromeDriver == null) {
          this.chromeDriver = getDriver();
      }
      if (this.chromeDevTools == null) {
          this.chromeDevTools = ((ChromeDriver) this.chromeDriver).getDevTools();
          this.chromeDevTools.createSession();
          this.chromeDevTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
      }
      return this.chromeDriver != null && this.chromeDevTools != null;
  }

  public Test() {
    initDriver();
  }

}

```


```bash
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.1'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.xxxxx'
version = '1.0.0'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.seleniumhq.selenium:selenium-java:4.16.1'
}

tasks.named('test') {
    useJUnitPlatform()
}

```

**Comment by joerg1985** [comment]
```
java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'
  at org.openqa.selenium.devtools.v120.target.Target.getTargets(Target.java:153) ~[selenium-devtools-v120-4.16.1.jar:na]
  at org.openqa.selenium.devtools.v120.v120Target.getTargets(v120Target.java:55) ~[selenium-devtools-v120-4.16.1.jar:na]
  at org.openqa.selenium.devtools.DevTools.findTarget(DevTools.java:171) ~[selenium-remote-driver-4.14.1.jar:na]
  at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:131) ~[selenium-remote-driver-4.14.1.jar:na]
  at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:117) ~[selenium-remote-driver-4.14.1.jar:na]
```
There are mixed versions (4.14.1 and 4.16.1) on your classpath, this is the reason for the failure.

**Comment by ixiaofu** [comment]
> ```
> java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'
>   at org.openqa.selenium.devtools.v120.target.Target.getTargets(Target.java:153) ~[selenium-devtools-v120-4.16.1.jar:na]
>   at org.openqa.selenium.devtools.v120.v120Target.getTargets(v120Target.java:55) ~[selenium-devtools-v120-4.16.1.jar:na]
>   at org.openqa.selenium.devtools.DevTools.findTarget(DevTools.java:171) ~[selenium-remote-driver-4.14.1.jar:na]
>   at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:131) ~[selenium-remote-driver-4.14.1.jar:na]
>   at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:117) ~[selenium-remote-driver-4.14.1.jar:na]
> ```
> 
> There are mixed versions (4.14.1 and 4.16.1) on your classpath, this is the reason for the failure.

Thank you very much. After investigation, it was found that after importing Springboot into the project, the Selenium version was automatically downgraded under Gradle management.
