### ISSUE TITLE
[🐛 Bug]: WebDriverError: no such execution context

### ISSUE THREAD

**Issue by slhck** [SeleniumHQ/selenium#13478]
### What happened?

I am getting the error

```
WebDriverError: no such execution context
```

when running a particular piece of code. This has only started recently, and I assume it's due to an update with Chrome or ChromeDriver? I should add that the code shown has always worked fine (it's a dummy example, the real code is much larger).

Repro case: https://github.com/slhck/selenium-execution-context-error

I realize there are existing issues here:

- https://github.com/SeleniumHQ/selenium/issues/13442 (lacks an answer, uses some other ChromeDriver)
- https://github.com/SeleniumHQ/selenium/issues/12967 (has no repro case)

Since I am able to always reproduce the issue, I've created a case that can be used to trace down the issue. Hence this new issue. If there is nothing that can be done from Selenium, please close this, but it is my understanding that there is no identified upstream issue there (yet?).

### How can we reproduce the issue?

```typescript
import webdriver, { By, until } from "selenium-webdriver";
import chrome from "selenium-webdriver/chrome.js";

const chromeOptions = new chrome.Options().addArguments(
  "--mute-audio",
  "--autoplay-policy=no-user-gesture-required"
);

const driver = new webdriver.Builder()
  .forBrowser("chrome")
  .setChromeOptions(chromeOptions)
  .build();

const testUrl = "https://www.youtube.com/watch?v=aqz-KE-bpKQ";
await driver.get(testUrl);

await driver.wait(until.elementLocated(By.css("#player .html5-video-player")));

await driver.executeScript(`
    let observer;
    function createObserver() {
        return new Promise(function(resolve) {
            observer = new MutationObserver(function() {
                const panel = document.querySelector('.html5-video-info-panel');
                if (!panel) return;
                observer.disconnect();
                resolve(panel);
            });
            observer.observe(document, { childList: true, subtree: true });
        });
    }
    (async function() {
        await createObserver();
    })();
  `);

await driver.quit();
```

### Relevant log output

```shell
WebDriverError: no such execution context
  (Session info: chrome=120.0.6099.234)
    at Object.throwDecodedError (/Users/werner/Desktop/selenium-execution-context-error/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/Users/werner/Desktop/selenium-execution-context-error/node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (/Users/werner/Desktop/selenium-execution-context-error/node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (/Users/werner/Desktop/selenium-execution-context-error/node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at <anonymous> (/Users/werner/Desktop/selenium-execution-context-error/index.ts:15:1) {
  remoteStacktrace: '0   chromedriver                        0x0000000100b444dc chromedriver + 4162780\n' +
    '1   chromedriver                        0x0000000100b3c664 chromedriver + 4130404\n' +
    '2   chromedriver                        0x00000001007939f8 chromedriver + 293368\n' +
    '3   chromedriver                        0x000000010077c65c chromedriver + 198236\n' +
    '4   chromedriver                        0x0000000100779e84 chromedriver + 188036\n' +
    '5   chromedriver                        0x000000010077ab30 chromedriver + 191280\n' +
    '6   chromedriver                        0x000000010078a74c chromedriver + 255820\n' +
    '7   chromedriver                        0x000000010079f4b4 chromedriver + 341172\n' +
    '8   chromedriver                        0x000000010077b1e0 chromedriver + 192992\n' +
    '9   chromedriver                        0x000000010079f19c chromedriver + 340380\n' +
    '10  chromedriver                        0x0000000100819bd8 chromedriver + 842712\n' +
    '11  chromedriver                        0x00000001007cd6bc chromedriver + 530108\n' +
    '12  chromedriver                        0x00000001007ce930 chromedriver + 534832\n' +
    '13  chromedriver                        0x0000000100b09e08 chromedriver + 3923464\n' +
    '14  chromedriver                        0x0000000100b0e3dc chromedriver + 3941340\n' +
    '15  chromedriver                        0x0000000100af2038 chromedriver + 3825720\n' +
    '16  chromedriver                        0x0000000100b0ef3c chromedriver + 3944252\n' +
    '17  chromedriver                        0x0000000100ae46f4 chromedriver + 3770100\n' +
    '18  chromedriver                        0x0000000100b2b980 chromedriver + 4061568\n' +
    '19  chromedriver                        0x0000000100b2baf8 chromedriver + 4061944\n' +
    '20  chromedriver                        0x0000000100b3c2e4 chromedriver + 4129508\n' +
    '21  libsystem_pthread.dylib             0x0000000194053fa8 _pthread_start + 148\n' +
    '22  libsystem_pthread.dylib             0x000000019404eda0 thread_start + 8\n'
}
```

### Operating System

macOS 13.6.3 (22G436)

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 120

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 120

**Comment by slhck** [comment]
Hm, I realize now this is really out of scope here and a ChromeDriver thing. Will close this. Maybe someone will find the info useful.

Edit: Couldn't find upstream bug, created one: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4687
