### ISSUE TITLE
[🐛 Bug]: marionette no known capability

### ISSUE THREAD

**Issue by ReMiOS** [SeleniumHQ/selenium#13497]
### What happened?

After upgrading selenium 4.8.2 to 4.16.0 an error appeared

selenium.common.exceptions.InvalidArgumentException: Message: marionette is not the name of a known capability or extension capability

### How can we reproduce the issue?

```shell
geckodriver =  os.path.join( filepath, 'geckodriver.exe' )
ff_service = Service( geckodriver )
firefox_options = Options()
firefox_options.set_capability( 'marionette', False )
browser = webdriver.Firefox( service = ff_service, options = firefox_options )
```

### Relevant log output

```shell
Traceback (most recent call last):
    browser = webdriver.Firefox( service = ff_service, options = firefox_options )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Python3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "C:\Python3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Python3\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: marionette is not the name of a known capability or extension capability
```

### Operating System

Windows 11

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 120.0.1 (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.33.0

### Are you using Selenium Grid?

-

**Comment by titusfortner** [comment]
Selenium only supports w3c. Setting marionette false was used to toggle the old Firefox Extension implementation and that hasn't been used in many years. Just delete it the capability.

**Comment by ReMiOS** [comment]
Thanks for clearing that up !
