### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.openqa.selenium.support.ui.WebDriverWait.<init>(org.openqa.selenium.WebDriver, java.time.Duration)' 	at ExplicitWait.main(ExplicitWait.java:22)[🐛 Bug]: 

### ISSUE THREAD

**Issue by RaoInam07** [SeleniumHQ/selenium#13530]
### What happened?

I am wokring explicit wait and getting this exception how should i resolved this 

![2024-01-31_12-22-53](https://github.com/SeleniumHQ/selenium/assets/138563669/b1f17c5a-42b9-46e4-9090-d030c2f71b33)

### How can we reproduce the issue?

```shell
import java.time.Duration;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

public class ExplicitWait {

	public static void main(String[] args) {
		WebDriverManager.chromedriver().setup();
		ChromeDriver driver = new ChromeDriver();
		
		driver.get("https://www.ebay.com/");
		driver.manage().window().maximize();
		WebElement element = driver.findElement(By.xpath("//*[@id=\"vl-flyout-nav\"]/ul/li[6]/a"));
		Actions action = new Actions(driver);
		action.moveToElement(element).perform();
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
	
		WebElement ebay =	wait.until(ExpectedConditions.visibilityOfElementLocated
		(By.xpath("//*[@id=\"vl-flyout-nav\"]/ul/li[6]/div[2]/div[1]/nav[2]/ul/li[1]/a")));
	ebay.click();
		
		
	}



}
```

### Relevant log output

```shell
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.openqa.selenium.support.ui.WebDriverWait.<init>(org.openqa.selenium.WebDriver, java.time.Duration)'
	at ExplicitWait.main(ExplicitWait.java:22)
```

### Operating System

Windows 11

### Selenium version

4.16.1

### What are the browser(s) and version(s) where you see this issue?

Version 121.0.6167.86

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by titusfortner** [comment]
I'm pretty sure you have a dependency conflict in your jars. See this — https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

I'll add some links below for if you have follow-up questions.

**Comment by RaoInam07** [comment]
Still not work
