### ISSUE TITLE
[🐛 Bug]: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Timed out waiting for driver server to bind the port

### ISSUE THREAD

**Issue by Lingam8454** [SeleniumHQ/selenium#13676]
### What happened?

While creating a WebDriver Session with grid service, Grid throws "could not start a new session"

If I was running the standalone service it was working fine, the same was not working with grid setup. 

### How can we reproduce the issue?

```shell
Setup a grid in linux os. Open Browser using Java. Driver not created exception will be throws
```

### Relevant log output

```shell
[SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Timed out waiting for driver server to bind the port.
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'
Driver info: driver.version: unknown 
Host info: host: 'desk-auto-10', ip: '192.168.63.218'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'
Driver info: driver.version: unknown
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'
Driver info: driver.version: unknown
	at org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:152)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:651)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:570)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:830)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:790)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

13:48:56.858 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Timed out waiting for driver server to bind the port.
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'
Driver info: driver.version: unknown 
Host info: host: 'desk-auto-10', ip: '192.168.63.218'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'
Driver info: driver.version: unknown
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'
Driver info: driver.version: unknown
13:48:56.859 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "762aac2315175a415be2a54332c99c07","eventTime": 1710145136855471074,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Timed out waiting for driver server to bind the port.\nBuild info: version: '4.18.1', revision: 'b1d3319b48'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'\nDriver info: driver.version: unknown \nHost info: host: 'desk-auto-10', ip: '192.168.63.218'\nBuild info: version: '4.18.1', revision: 'b1d3319b48'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'\nDriver info: driver.version: unknown\nBuild info: version: '4.18.1', revision: 'b1d3319b48'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Timed out waiting for driver server to bind the port.\nBuild info: version: '4.18.1', revision: 'b1d3319b48'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'\nDriver info: driver.version: unknown \nHost info: host: 'desk-auto-10', ip: '192.168.63.218'\nBuild info: version: '4.18.1', revision: 'b1d3319b48'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'\nDriver info: driver.version: unknown\nBuild info: version: '4.18.1', revision: 'b1d3319b48'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-150-generic', java.version: '17.0.10'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:152)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:651)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:570)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:830)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:790)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:842)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}, platformName: linux}]"}}
```

### Operating System

Ubuntu

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 120, Chrome 121, Chrome 122

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver - 120.0.6099.109  121.0.6167.184  122.0.6261.94

### Are you using Selenium Grid?

4.18.1

**Comment by joerg1985** [comment]
It might be a good idea to log the driver output in this case before killing it.
Are there any concerns, why not do so?

**Comment by diemol** [comment]
I am closing this because we never got more information.
