### ISSUE TITLE
[🐛 Bug]: sphinx fails

### ISSUE THREAD

**Issue by kloczek** [SeleniumHQ/selenium#13687]
### What happened?

Looks like with latest version it is a problem with building documentation.

### How can we reproduce the issue?

```shell
Just run `sphinx-build -n -T -b man docs/source build/sphinx/man` after repo clone clone.
```

### Relevant log output

```shell
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v7.2.6
making output directory... done
[autosummary] generating autosummary for: api.rst, common/selenium.common.exceptions.rst, index.rst, webdriver/selenium.webdriver.common.action_chains.rst, webdriver/selenium.webdriver.common.actions.action_builder.rst, webdriver/selenium.webdriver.common.actions.input_device.rst, webdriver/selenium.webdriver.common.actions.interaction.rst, webdriver/selenium.webdriver.common.actions.key_actions.rst, webdriver/selenium.webdriver.common.actions.key_input.rst, webdriver/selenium.webdriver.common.actions.mouse_button.rst, ..., webdriver_support/selenium.webdriver.support.abstract_event_listener.rst, webdriver_support/selenium.webdriver.support.color.rst, webdriver_support/selenium.webdriver.support.event_firing_webdriver.rst, webdriver_support/selenium.webdriver.support.expected_conditions.rst, webdriver_support/selenium.webdriver.support.relative_locator.rst, webdriver_support/selenium.webdriver.support.select.rst, webdriver_support/selenium.webdriver.support.wait.rst, webdriver_webkitgtk/selenium.webdriver.webkitgtk.options.rst, webdriver_webkitgtk/selenium.webdriver.webkitgtk.service.rst, webdriver_webkitgtk/selenium.webdriver.webkitgtk.webdriver.rst
WARNING: Failed to import selenium.webdriver.firefox.extension_connection.
Possible hints:
* AttributeError: module 'selenium.webdriver.firefox' has no attribute 'extension_connection'
* ModuleNotFoundError: No module named 'selenium.webdriver.firefox.extension_connection'
WARNING: Failed to import selenium.webdriver.common.html5.application_cache.
Possible hints:
* AttributeError: module 'selenium.webdriver.common' has no attribute 'html5'
* ModuleNotFoundError: No module named 'selenium.webdriver.common.html5'

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autosummary/generate.py", line 503, in generate_autosummary_docs
    name, obj, parent, modname = import_by_name(entry.name)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py", line 655, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named selenium.webdriver.common.html5.application_cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/events.py", line 97, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py", line 814, in process_generate_options
    generate_autosummary_docs(genfiles, suffix=suffix, base_path=app.srcdir,
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autosummary/generate.py", line 508, in generate_autosummary_docs
    name, obj, parent, modname = import_ivar_by_name(entry.name)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py", line 712, in import_ivar_by_name
    real_name, obj, parent, modname = import_by_name(name, prefixes)
  File "/usr/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py", line 655, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named selenium.webdriver.common.html5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 272, in __init__
    self._init_builder()
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 343, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3.9/site-packages/sphinx/events.py", line 108, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function process_generate_options at 0x7fa2aa8eb5e0> for event 'builder-inited' threw an exception (exception: no module named selenium.webdriver.common.html5)

Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x7fa2aa8eb5e0> for event 'builder-inited' threw an exception (exception: no module named selenium.webdriver.common.html5)
```

### Operating System

Linux x86/64

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment]
We are using a different version, check:

https://github.com/SeleniumHQ/selenium/blob/trunk/py/tox.ini#L8

**Comment by kloczek** [comment]
Hmm .. `sphinx` 1.8.2 has been released +5.5 years ago. https://github.com/sphinx-doc/sphinx/tags?after=v2.0.0b1
I'm almost sure that it will be not possible to render any documents format with so old version
In other words what is in tox.ini contains to low sphinx version (probably lowest still supported version is 6.x)

Other thing is that sphinx 7.0.x and `selenium` 4.17.0 I was able render man page 🤔

**Comment by diemol** [comment]
So maybe we can bump to 7.0.x and stay there? Do you think you can help with a PR?

**Comment by kloczek** [comment]
I have packaged only latest version 7.2.1 so will be not able to test that with 7.0.x 😞 
Nevertheless did you try to reproduce that with any 7.x? 🤔

**Comment by diemol** [comment]
I have not. If you wish, you can help us with a PR to bump the dependency to 7.0.x, which is already better than 1.8.2.
