### ISSUE TITLE
[🐛 Bug]: HasDownloads Interface missing in RemoteWebDriver class of org.openqa.selenium.remote

### ISSUE THREAD

**Issue by ShaderBoys** [SeleniumHQ/selenium#13693]
### What happened?

Issue when I was setting up my Controller in springboot, I am doing the following:

```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setBrowserName("chrome");
WebDriver driver = new RemoteWebDriver( new URL("http://localhost:4444/"), capabilities);
driver.manage().wait(1000);
// Navigate to Google
driver.get("https://www.google.com");
```

I tried different versions from 4.10.0 to 4.18.1 for all the dependencies. I cleaned the ~/.m2/repository/ as well. Checked class path. but the same error was popping as follows:

```
java.lang.ClassNotFoundException: org.openqa.selenium.HasDownloads
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
```

I checked the generated class files of selenium-remote-driver-4.16.1.jar. Got to know that Interface `org.openqa.selenium.HasDownloads` is imported and used in the class definition but not defined. 
<img width="836" alt="Screenshot 2024-03-14 at 4 50 49 PM" src="https://github.com/SeleniumHQ/selenium/assets/150319587/45a72f30-e5ce-4440-a0b0-14a6eeea964e">
<img width="836" alt="Screenshot 2024-03-14 at 4 50 57 PM" src="https://github.com/SeleniumHQ/selenium/assets/150319587/51c0d5e0-5255-4bde-a971-3256916cdcff">

### How can we reproduce the issue?

```shell
inside a java class file do the following:

//import below dependencies
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

// write the following inside the class

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setBrowserName("chrome");
WebDriver driver = new RemoteWebDriver( new URL("http://localhost:4444/"), capabilities);
driver.manage().wait(1000);
// Navigate to Google
driver.get("https://www.google.com");
if (driver!=null){
  driver.quit();
}
```

### Relevant log output

```shell
java.lang.ClassNotFoundException: org.openqa.selenium.HasDownloads
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:534) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:513) ~[na:na]
	at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:121) ~[spring-boot-devtools-3.2.3.jar:3.2.3]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
```

### Operating System

macOS Ventura 13.5

### Selenium version

Java 4.16.1

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver using RemoteWebDriver

**Comment by krmahadevan** [comment]
@ShaderBoys - it looks to me that something in your classpath (obtained via `<dependency>` tag if you are on maven for e.g.,) is causing this problem.

Can you show us what your `pom.xml` looks like ?

**Comment by ShaderBoys** [comment]
@krmahadevan here's my pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.3</version>
		<relativePath/>
	</parent>
	<groupId>com.example</groupId>
	<artifactId>executor</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>executor</name>
	<description>Executor</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-driver</artifactId>
			<version>4.16.1</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.16.1</version>
		</dependency>
		<dependency>
			<groupId>com.github.stephenc.monte</groupId>
			<artifactId>monte-screen-recorder</artifactId>
			<version>0.7.7.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-chrome-driver</artifactId>
        <version>4.16.1</version>
    </dependency>
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-firefox-driver</artifactId>
        <version>4.16.1</version>
    </dependency>
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-edge-driver</artifactId>
        <version>4.16.1</version>
    </dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by krmahadevan** [comment]
@ShaderBoys - I removed all other selenium dependencies and just included the below:

```xml
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.16.1</version>
		</dependency>
```

Please note that springboot seems to be having an affinity to some default versions of selenium which can be controlled by adding the property `<selenium.version>`

<img width="1353" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/909773/8bb17cab-d2b6-4252-b988-4ffcb3a25a7e">




Read more about it in the below links:

* https://stackoverflow.com/q/70881256
* https://docs.spring.io/spring-boot/docs/3.2.3/reference/htmlsingle/#appendix.dependency-versions
