### ISSUE TITLE
[🐛 Bug]: mirror repository for chrome driver version later than 115 not work

### ISSUE THREAD

**Issue by yu-chun-kit** [SeleniumHQ/selenium#13706]
### What happened?

mirror repository of chrome driver version after 115 is using [https://registry.npmmirror.com/-/binary/chrome-for-testing/](https://registry.npmmirror.com/-/binary/chrome-for-testing) instead of [https://registry.npmmirror.com/-/binary/chromedriver](https://registry.npmmirror.com/-/binary/chromedriver) to provide chromedriver, 

### How can we reproduce the issue?

```shell
WebDriverManager
	.chromedriver()
	.useMirror() // <-- this line of code
	.setup();

```
```


### Relevant log output

```shell
2024-03-19 09:24:54.581  INFO 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.WebDriverManager      : Using chromedriver 122.0.6261.128 (resolved driver for Chrome 122)
2024-03-19 09:24:55.015 ERROR 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.online.HttpClient     : Error HTTP 404 executing https://registry.npmmirror.com/-/binary/chromedriver/122.0.6261.128/
2024-03-19 09:24:55.016  INFO 5260 --- [ool-13-thread-1] i.g.b.wdm.cache.ResolutionCache          : Clearing WebDriverManager resolution cache
2024-03-19 09:24:55.019  WARN 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.WebDriverManager      : There was an error managing chromedriver 122.0.6261.128 (Error HTTP 404 executing https://registry.npmmirror.com/-/binary/chromedriver/122.0.6261.128/) ... trying again avoiding reading release from repository
2024-03-19 09:27:53.673  INFO 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.online.Downloader     : Downloading https://registry.npmmirror.com/-/binary/chromedriver/114.0.5735.90/chromedriver_win32.zip
2024-03-19 09:27:58.018  INFO 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.online.Downloader     : Extracting driver from compressed file chromedriver_win32.zip
2024-03-19 09:27:58.234  INFO 5260 --- [ool-13-thread-1] i.g.bonigarcia.wdm.WebDriverManager      : Exporting webdriver.chrome.driver as C:\Users\myusername\.cache\selenium\chromedriver\win32\114.0.5735.90\chromedriver.exe
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 122.0.6261.129 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe 
Host info: host: 'IRD25643X', ip: '10.31.101.116'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: D:\Bulk Upload\Download}}, goog:loggingPrefs: org.openqa.selenium.logging..., pageLoadStrategy: eager, unhandledPromptBehavior: accept and notify}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:139)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
...
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Operating System

Windows 10

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 122

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 122.0.6261.128

### Are you using Selenium Grid?

not using Selenium Grid

**Comment by mittaltripti** [comment]
I am facing the same issue 
LF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 122.0.6261.129 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
Host info: host: 'Triptis-MacBook-Pro.local', ip: '2405:201:22:7aa2:8810:55f7:1d26:3909%en0'
Build info: version: '4.16.0', revision: '15400459dd*'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.0', java.version: '17.0.9'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}]}]

selenium-java 4.16
webdrivermanager 5.5.2

**Comment by yu-chun-kit** [comment]
> I am facing the same issue LF4J: No SLF4J providers were found. SLF4J: Defaulting to no-operation (NOP) logger implementation SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114 Current browser version is 122.0.6261.129 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome Host info: host: 'Triptis-MacBook-Pro.local', ip: '2405:201:22:7aa2:8810:55f7:1d26:3909%en0' Build info: version: '4.16.0', revision: '15400459dd*' System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.0', java.version: '17.0.9' Driver info: org.openqa.selenium.chrome.ChromeDriver Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}]}]
> 
> selenium-java 4.16 webdrivermanager 5.5.2

It should be the problem of webdrivermanager, I have created a new issue on WebDriverManager repo [https://github.com/bonigarcia/webdrivermanager/issues/1264#issue-2205052625](https://github.com/bonigarcia/webdrivermanager/issues/1264#issue-2205052625)
