### ISSUE TITLE
[🐛 Bug]: Getting SessionNotCreatedException once selenium version is updated to latest from 4.16.1

### ISSUE THREAD

**Issue by maheshchinnagavi** [SeleniumHQ/selenium#13715]
### What happened?

After updating the selenium version to latest from 4.16.1 version getting SessionNotCreatedException exception

Provided the details and log. Please let me know if any more info required.

### How can we reproduce the issue?

```shell
Updated the selenium version to latest in pom.xml from 4.16.1

And start the driver and launch url.

WebDriver driver;
ChromeOptions options = new ChromeOptions();
options.addArguments("--headless=new");
options.addArguments("--start-fullscreen");
driver = new ChromeDriver(options);
driver.get("https://www.google.com");

Exception occuring at driver = new ChromeDriver(options);
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'hostname', ip: 'address'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless=new, --start-fullscreen], binary: C:\Program Files\Google\Chr..., extensions: []}}]}]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:537)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)
	at utilities.WebDriverManager.setupDriver(WebDriverManager.java:32)
	at utilities.WebDriverManager.setDriver(WebDriverManager.java:58)
	at tests.GatedPageTest.gatedPageTest(GatedPageTest.java:63)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:819)
	at org.testng.TestRunner.run(TestRunner.java:619)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/remote/http/HttpHeader
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:110)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	... 34 more
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.http.HttpHeader
	... 41 more
```

### Operating System

Windows 10

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 122.0.6261.129

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver Selenium Manager

### Are you using Selenium Grid?

No

**Comment by krmahadevan** [comment]
@maheshchinnagavi 

> Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.http.HttpHeader
	... 41 more

Indicates that you have a messed up classpath.

Please share your pom file contents so that we know what are you resolving to as dependencies.

**Comment by maheshchinnagavi** [comment]
@krmahadevan Thanks for checking. 

Using the below dependencies in pom.xml

	<dependencies>
		
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.9.0</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.18.1</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-http-jdk-client</artifactId>
			<version>4.13.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>5.1.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.2.5</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.5</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>2.0.29</version>
		</dependency>
			
		
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.30</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.16.1</version>
		</dependency>

	</dependencies>

**Comment by krmahadevan** [comment]
@maheshchinnagavi - 

Am going to assume that you are not working with parent pom file.

Please remove the below entry and try again.

```xml
<dependency>
		<groupId>org.seleniumhq.selenium</groupId>
		<artifactId>selenium-http-jdk-client</artifactId>
		<version>4.13.0</version>
</dependency>
```

**Comment by maheshchinnagavi** [comment]
@krmahadevan 

Thanks. It worked by removing the above dependency from pom file.

Is it not required with the latest version updated? Checking as I had some other issues earlier, so added that as per the instructions mentioned in https://www.selenium.dev/blog/2022/using-java11-httpclient/

**Comment by krmahadevan** [comment]
@maheshchinnagavi - Yes its very much needed but afaik you now don't need to specify it explicitly. Its automatically taken care of because that's the default implementation for making http clients.

@diemol @pujagani - I remember vaguely that we shared instructions about this somewhere in our blogs. But I can't seem to find it. Perhaps you could share it, if its available in handy ?
