### ISSUE TITLE
[🐛 Bug]: Unable to load custom chrome profile in selenium using pyhon

### ISSUE THREAD

**Issue by sajjadsaharkhan** [SeleniumHQ/selenium#13728]
### What happened?

I have installed the Chrome browser on Debian 12 and already have a Profile.

I want to start my selenium and use this Profile not from scratch!

here is my code:

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("--user-data-dir=/home/sajjad/.config/google-chrome")
options.add_argument('--profile-directory=Default')
driver = webdriver.Chrome(options=options)
driver.get("https://google.com/")
print(driver.current_url)
```

after running this code a Google Chrome window with my Default Profile was opened but this error appeared in the terminal immediately:

```bash
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

I updated my code and added an executing path to `driver`.

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

options = Options()
options.add_argument("--user-data-dir=/home/sajjad/.config/google-chrome")
options.add_argument('--profile-directory=Default')
driver = webdriver.Chrome(options=options,service=Service(executable_path="/opt/google/chrome/chrome"))
driver.get("https://google.com/")
print(driver.current_url)
```

after running this code a Google Chrome window with my Default Profile was opened but this error appeared in the terminal after few second:

```bash
Traceback (most recent call last):
  File "/home/lab/python/sample.py", line 69, in <module>
    driver = webdriver.Chrome(options=options,service=Service(executable_path="/opt/google/chrome/chrome"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/common/service.py", line 109, in start
    raise WebDriverException(f"Can not connect to the Service {self._path}")
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /opt/google/chrome/chrome
```

I just want to run a driver with my existing Chrome profile and open `google.com`!

### How can we reproduce the issue?

```shell
Run the above code in Linux Debian 12 or another distro with Google Chrome WebDriver and a custom profile.
```

### Relevant log output

```shell
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /opt/google/chrome/chrome
```

### Operating System

Linux Debian 12

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

122.0.6261.128 (Official Build) (64-bit) 

### What are the browser driver(s) and version(s) where you see this issue?

Google Chrome for Testing 123.0.6312.58

**Comment by diemol** [comment]
>service=Service(executable_path="/opt/google/chrome/chrome"

This is meant to be the ChromeDriver path.

The easiest is to avoid passing a service object and let [Selenium](https://www.selenium.dev/documentation/selenium_manager/) handle that. If you have more questions, please use the links shown below.
