### ISSUE TITLE
[🐛 Bug]: Chrome 123.0.6312.59 +  Driver 123.0.6312.58 from Selenium Manager

### ISSUE THREAD

**Issue by 0x80085** [SeleniumHQ/selenium#13729]
### What happened?

In the middle of a testing session, the tests start failing. Even though same interactions worked for other tests in same session

 the tests fail with errors like (for click, screenshot, element):

An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://localhost:59923/session/255cef397b3e6e2e7c4813e62b2018f3/element/f.D7CB72B8914BAFF6C2A96D5A826B8B9E.d.689861A0C08F6A27B601B3582B96E452.e.20/click. The exception message was: An error occurred while sending the request.
2024-03-25T10:05:47.2759088Z   ----> System.Net.Http.HttpRequestException : An error occurred while sending the request.
2024-03-25T10:05:47.2759829Z   ----> System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-03-25T10:05:47.2760621Z   ----> System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
2024-03-25T10:05:47.2761948Z TearDown : OpenQA.Selenium.WebDriverException : An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://localhost:59923/session/255cef397b3e6e2e7c4813e62b2018f3/screenshot. The exception message was: No connection could be made because the target machine actively refused it. (localhost:59923)
2024-03-25T10:05:47.2763377Z   ----> System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (localhost:59923)
2024-03-25T10:05:47.2764169Z   ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.

What causes this? We have not edited the tests in months and they started failing over the weekend with these errors. 
We already use the Selenium Manager to update the driver. So that shouldn't be the issue.

Any advice?

### How can we reproduce the issue?

```shell
unknown, they just started failing over the weekend.
```

### Relevant log output

```shell
2024-03-25T10:05:47.2756032Z   Error Message:
2024-03-25T10:05:47.2757591Z    OpenQA.Selenium.WebDriverException : An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://localhost:59923/session/255cef397b3e6e2e7c4813e62b2018f3/element/f.D7CB72B8914BAFF6C2A96D5A826B8B9E.d.689861A0C08F6A27B601B3582B96E452.e.20/click. The exception message was: An error occurred while sending the request.
2024-03-25T10:05:47.2759088Z   ----> System.Net.Http.HttpRequestException : An error occurred while sending the request.
2024-03-25T10:05:47.2759829Z   ----> System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2024-03-25T10:05:47.2760621Z   ----> System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
2024-03-25T10:05:47.2761948Z TearDown : OpenQA.Selenium.WebDriverException : An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL http://localhost:59923/session/255cef397b3e6e2e7c4813e62b2018f3/screenshot. The exception message was: No connection could be made because the target machine actively refused it. (localhost:59923)
2024-03-25T10:05:47.2763377Z   ----> System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (localhost:59923)
2024-03-25T10:05:47.2764169Z   ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
2024-03-25T10:05:47.2764700Z   Stack Trace:
2024-03-25T10:05:47.2765138Z      at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2024-03-25T10:05:47.2765777Z    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2024-03-25T10:05:47.2766352Z    at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2024-03-25T10:05:47.2767137Z    at OpenQA.Selenium.WebElement.Click()
2024-03-25T10:05:47.2767950Z    at Automation.Pages.Visitors.VisitorsPage.VerifyEmergencyListPrintWindow() in C:\agent\_work\52\s\tests\Pages\Visitors\VisitorsPage.cs:line 143
2024-03-25T10:05:47.2769019Z    at Automation.Tests.Visitor.VisitorsHeadedTests.WhenIClickOnEmergencyButton_ItOpensPrintWindowWithEmergencyList() in C:\agent\_work\52\s\tests\Tests\Visitor\VisitorsHeadedTests.cs:line 23
2024-03-25T10:05:47.2769773Z --HttpRequestException
2024-03-25T10:05:47.2770339Z    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-03-25T10:05:47.2772205Z    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2024-03-25T10:05:47.2773006Z    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-03-25T10:05:47.2773908Z    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2024-03-25T10:05:47.2774944Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2024-03-25T10:05:47.2775575Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.<>c__DisplayClass33_0.<<Execute>b__0>d.MoveNext()
2024-03-25T10:05:47.2776120Z --- End of stack trace from previous location ---
2024-03-25T10:05:47.2776612Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2024-03-25T10:05:47.2777450Z --IOException
2024-03-25T10:05:47.2778007Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-03-25T10:05:47.2778756Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
2024-03-25T10:05:47.2779478Z    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-03-25T10:05:47.2780009Z --SocketException
2024-03-25T10:05:47.2780220Z 
2024-03-25T10:05:47.2780504Z --TearDown
2024-03-25T10:05:47.2780937Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2024-03-25T10:05:47.2781484Z    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2024-03-25T10:05:47.2782076Z    at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2024-03-25T10:05:47.2782571Z    at OpenQA.Selenium.WebDriver.GetScreenshot()
2024-03-25T10:05:47.2783283Z    at Automation.Util.WebDriverUtil.TakeScreenshot(IWebDriver driver, String pathToScreenshot) in C:\agent\_work\52\s\tests\Util\WebDriverUtil.cs:line 33
2024-03-25T10:05:47.2784245Z    at Automation.Tests.BaseTest.BaseTearDown() in C:\agent\_work\52\s\tests\Tests\BaseTest.cs:line 52
2024-03-25T10:05:47.2784814Z --HttpRequestException
2024-03-25T10:05:47.2785449Z    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024-03-25T10:05:47.2786250Z    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-03-25T10:05:47.2787517Z    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-03-25T10:05:47.2788413Z    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
2024-03-25T10:05:47.2789065Z    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
2024-03-25T10:05:47.2789797Z    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-03-25T10:05:47.2790593Z    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2024-03-25T10:05:47.2791364Z    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2024-03-25T10:05:47.2792277Z    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2024-03-25T10:05:47.2793329Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2024-03-25T10:05:47.2793918Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.<>c__DisplayClass33_0.<<Execute>b__0>d.MoveNext()
2024-03-25T10:05:47.2797672Z --- End of stack trace from previous location ---
2024-03-25T10:05:47.2798227Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2024-03-25T10:05:47.2798903Z --SocketException
2024-03-25T10:05:47.2799443Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-03-25T10:05:47.2800143Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2024-03-25T10:05:47.2801463Z    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
2024-03-25T10:05:47.2803191Z    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2024-03-25T10:05:47.2803877Z 
2024-03-25T10:05:47.2804168Z   Sta
```

### Operating System

Windows

### Selenium version

dotnet 6

### What are the browser(s) and version(s) where you see this issue?

latest Chrome 123.0.6312.59

### What are the browser driver(s) and version(s) where you see this issue?

selenium 123.0.6312.58

**Comment by 0x80085** [comment]
Accidentally closed it 👴

**Comment by diemol** [comment]
I was reading about the issue and cannot say what the problem might be. It seems to be a network issue, but I have no context for your environment. What analysis have you done so far? What pieces have moved in your infrastructure? Did you update any version of any component?

**Comment by 0x80085** [comment]
We just found the issue ourselves.
The test which fails was apparently enabled by accident during a codebase cleanup.

Will close this issue. 
I apologize for your time wasted... But thanks for you swift reply. 
Sorry!
