### ISSUE TITLE
[🐛 Bug]: Unknown error: missing or invalid columnNumber

### ISSUE THREAD

**Issue by xxyz30** [SeleniumHQ/selenium#13738]
### What happened?

When i use  `driver.get(url)`, the exception was throw.
the url is `http://wqb.huzhou.gov.cn/art/2022/8/18/art_1229207131_58835927.html`  a sample news website

here is my code:
```python
import logging
import os.path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service

driver_path = r'C:\Program Files\Google\Chrome\Application\chromedriver.exe'
browser_path = r'C:\Program Files\Google\Chrome\Application\chrome.exe'

options = webdriver.ChromeOptions()
options.binary_location = browser_path

webview = webdriver.Chrome(options=options, service=Service(driver_path))

file_name = os.path.abspath('index.html')

print(file_name)
try:
    webview.get('http://wqb.huzhou.gov.cn/art/2022/8/18/art_1229207131_58835927.html')
    print('ok')
except Exception as ex:
    print(ex)
    pass

input('enter close process')

```

### How can we reproduce the issue?

```shell
I make a simple html page what can cause this exception
Code are in Zip file below
use `python ./main.py` to run it
```

### Relevant log output

```shell
>_ driver.get('http://localhost:8080/index.html')

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\86181\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\86181\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\86181\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: missing or invalid columnNumber
  (Session info: chrome=123.0.6312.59)
Stacktrace:
	GetHandleVerifier [0x00007FF618C97062+63090]
	(No symbol) [0x00007FF618C02CB2]
	(No symbol) [0x00007FF618A9EC65]
	(No symbol) [0x00007FF618A8301E]
	(No symbol) [0x00007FF618A822C2]
	(No symbol) [0x00007FF618A8D3B1]
	(No symbol) [0x00007FF618A8DBA5]
	(No symbol) [0x00007FF618A8D825]
	(No symbol) [0x00007FF618A8D104]
	(No symbol) [0x00007FF618A8D021]
	(No symbol) [0x00007FF618A8C097]
	(No symbol) [0x00007FF618AAA6A4]
	(No symbol) [0x00007FF618B2376C]
	(No symbol) [0x00007FF618B06D83]
	(No symbol) [0x00007FF618AD83A8]
	(No symbol) [0x00007FF618AD9441]
	GetHandleVerifier [0x00007FF6190925CD+4238301]
	GetHandleVerifier [0x00007FF6190CF72D+4488509]
	GetHandleVerifier [0x00007FF6190C7A0F+4456479]
	GetHandleVerifier [0x00007FF618D705A6+953270]
	(No symbol) [0x00007FF618C0E57F]
	(No symbol) [0x00007FF618C09254]
	(No symbol) [0x00007FF618C0938B]
	(No symbol) [0x00007FF618BF9BC4]
	BaseThreadInitThunk [0x00007FFCE065257D+29]
	RtlUserThreadStart [0x00007FFCE10CAA58+40]
```

### Operating System

Windows 11

### Selenium version

Python 4.18.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 123.0.6312.59

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 123.0.6312.59

**Comment by xxyz30** [comment]
[bug.zip](https://github.com/SeleniumHQ/selenium/files/14755181/bug.zip)
Here is sample code

**Comment by diemol** [comment]
That error comes directly from [ChromeDriver](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/chrome/test/chromedriver/chrome/console_logger.cc#196) and [here](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/chrome/test/chromedriver/chrome/console_logger.cc#247).

It seems related to an issue with the JavaScript code you are loading on your test site. Why do you need an empty JS file loaded? But if you need more details about this, please feel free to contact the ChromeDriver folks.
