### ISSUE TITLE
[🐛 Bug]: SessionNotCreatedException: Could not start a new session with 4.16.1

### ISSUE THREAD

**Issue by vams05** [SeleniumHQ/selenium#13751]
### What happened?

while try run in github actions getting session isssue but in my local working fine

name: Extent Report

on:
  workflow_dispatch:  # Manually trigger the workflow from the GitHub UI
   inputs:
      CUSTOMER_LOGIN_EMAIL:
        description: 'CUSTOMER_LOGIN_EMAIL'
        required: false
      CUSTOMER_FRONT_DOMAIN:
        description: 'CUSTOMER_FRONT_DOMAIN'
        required: false
      CUSTOMER_LOGIN_MOBILE_NUMBER:
        description: 'CUSTOMER_LOGIN_MOBILE_NUMBER'
        required: false
      CUSTOMER_LOGIN_PWD:
        description: 'CUSTOMER_LOGIN_PWD'
        required: false
env:
  CUSTOMER_LOGIN_EMAIL: ${{ github.event.inputs.CUSTOMER_LOGIN_EMAIL }}
  CUSTOMER_FRONT_DOMAIN: ${{ github.event.inputs.CUSTOMER_FRONT_DOMAIN }}
  CUSTOMER_LOGIN_MOBILE_NUMBER: ${{ github.event.inputs.CUSTOMER_LOGIN_MOBILE_NUMBER }}
  CUSTOMER_LOGIN_PWD: ${{ github.event.inputs.CUSTOMER_LOGIN_PWD }}
 
jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameter: [ "SignInPageTest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
         
      - name: Run Selenium Tests
        run: |
          if [ "${{ matrix.parameter }}" == "SignInPageTest" ]; then
            mvn -B clean test --file /pom.xml -Dtest=SignInPageTest
          else
            echo "Invalid parameter provided."
            exit 1
          fi

      - name: Upload Extent HTML report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: go-rest-report
          path: /ExtentReport/extent-report.html

### How can we reproduce the issue?

```shell
<?xml version="1.0" encoding="UTF-8"?>
<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0   
https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>AASAAN</groupId>
	<artifactId>AASAAN</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
</properties>
	<dependencies>
		<!--
		https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.16.1</version>
			<!-- Adjust the version to the latest -->
			<exclusions>
				<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>guava</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.32</version> <!-- Use the latest version -->
</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.testng/testng -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.14.3</version>
			<scope>test</scope>
		</dependency>
		<!--
		https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager -->
		
		<!-- https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox -->
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>2.0.29</version>
		</dependency>
		<dependency>
			<groupId>com.sun.mail</groupId>
			<artifactId>javax.mail</artifactId>
			<version>1.6.2</version>
			<!-- Use the latest version available -->
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.23</version>
			<!-- Use the version you downloaded -->
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.4</version>
			<scope>provided</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/junit/junit -->
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>23.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.2</version>
		</dependency>
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>3.13.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.testng/testng -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.14.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.15.0</version>
		</dependency>
		<!-- Jackson Annotations -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.15.0</version>
		</dependency>
		<!-- Jackson Databind -->
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20210307</version>
			<!-- Use the latest version available -->
		</dependency>
		<!-- Jackson Dataformat XML -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.11.0</version>
		</dependency>
		<!-- Dependency for POI API -->
		<!-- http://mvnrepository.com/artifact/org.apache.poi/poi -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.6</version>
		</dependency>
		<!-- http://mvnrepository.com/artifact/org.apache.poi/poi-ooxml -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.6</version>
		</dependency>
		<!-- http://mvnrepository.com/artifact/org.apache.xmlbeans/xmlbeans -->
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.3</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.12.5</version>
			<!-- Use the latest version -->
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-xml</artifactId>
			<version>2.12.5</version>
			<!-- Use the latest version -->
		</dependency>
		<dependency>
			<groupId>net.sf.json-lib</groupId>
			<artifactId>json-lib</artifactId>
			<version>2.4</version>
			<classifier>jdk15</classifier>
		</dependency>
		<dependency>
  <groupId>org.projectlombok</groupId>
  <artifactId>lombok</artifactId>
  <version>1.18.20</version>
  <scope>provided</scope>
</dependency>
		<dependency>
			<groupId>xom</groupId>
			<artifactId>xom</artifactId>
			<version>1.2.5</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18.1</version>
				<configuration>
					<suiteXmlFiles>
						<suiteXmlFile>testng.xml</suiteXmlFile>
					</suiteXmlFiles>
					<testFailureIgnore>true</testFailureIgnore>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

### Relevant log output

```shell
Running Test.SignInPageTest
Configuring TestNG with: TestNG652Configurator
Tests run: 6, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 2.133 sec <<< FAILURE! - in Test.SignInPageTest
setup(Test.SignInPageTest)  Time elapsed: 1.904 sec  <<< FAILURE!
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Argument --remote-allow-origins can't be set via capabilities 
Host info: host: 'fv-az1544-9[59](https://github.com/Lightbooks-Technologies/aasaan-automation-qa/actions/runs/8461972516/job/23182587639#step:4:60)', ip: '10.1.0.42'
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-1016-azure', java.version: '17.0.10'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [--remote-allow-origins=*, --no-sandbox, --disable-dev-shm-usage, --headless, --disable-gpu, --window-size=1400,800], binary: /usr/bin/firefox}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:157)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:152)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:113)
	at Base.BaseTest.GetDriver(BaseTest.java:[60](https://github.com/Lightbooks-Technologies/aasaan-automation-qa/actions/runs/8461972516/job/23182587639#step:4:61))
	at Test.SignInPageTest.setup(SignInPageTest.java:27)
```

### Operating System

ubuntu-latest

### Selenium version

4.16.1

### What are the browser(s) and version(s) where you see this issue?

chrome and firefox

### What are the browser driver(s) and version(s) where you see this issue?

123

**Comment by diemol** [comment]
>Argument --remote-allow-origins can't be set via capabilities

The browser you have locally may differ from the version you use in GitHub Actions. 

You should remove that, upgrade to the latest Selenium version, and let us know in a comment if the issue is still present, then we will happily reopen this when a code sample to reproduce the problem is shared.
