### ISSUE TITLE
Unable to find an exact match for CDP version 123, returning the closest version; found: 122; Please update to a Selenium version that supports CDP version 123 Exception in thread 🐛 Bug]: 

### ISSUE THREAD

**Issue by sifar1234** [SeleniumHQ/selenium#13752]
### What happened?

WARNING: Unable to find an exact match for CDP version 122, returning the closest version; found: 120; Please update to a Selenium version that supports CDP version 122

### How can we reproduce the issue?

```shell
When I execute Selenium scripts in eclipse i am getting this Warning message.
```

### Relevant log output

```shell
Mar 28, 2024 9:32:21 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 123, returning the closest version; found: 122; Please update to a Selenium version that supports CDP version 123
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: invalid argument
  (Session info: chrome=123.0.6312.86)
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [01a4973ddae8acfc4c6c421fe4db2f6a, get {url=http.www.google.com/}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 123.0.6312.86, chrome: {chromedriverVersion: 123.0.6312.86 (9b72c47a0536..., userDataDir: C:\Users\sifar.a\AppData\Lo...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64182}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64182/devtoo..., se:cdpVersion: 123.0.6312.86, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 01a4973ddae8acfc4c6c421fe4db2f6a
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:301)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:1064)
	at automationFramework.FirstTestCase.main(FirstTestCase.java:15)
```

### Operating System

Windows 11 64bit

### Selenium version

Selenium 4.18.1

### What are the browser(s) and version(s) where you see this issue?

chrome, browser Version: 123.0.6312.86

### What are the browser driver(s) and version(s) where you see this issue?

chrome, driver  Version: 123.0.6312.86

**Comment by diemol** [comment]
That is a WARNING, not an error. You can still run your automation scripts.

However, if you upgrade to Selenium 4.19, the warning will disappear because Chrome 123 is supported in that version.

**Comment by sifar1234** [comment]
Thanks for the update. Warming message is no longer reproducible.
