### ISSUE TITLE
[🐛 Bug]: Service chromedriver unexpectedly exited.  Status code was: 255

### ISSUE THREAD

**Issue by voanhtuanvn12** [SeleniumHQ/selenium#13773]
### What happened?

When I started running on my local, it works as usual. But when I run it on docker (ubuntu - apache/airflow:2.8.1) with codes:

        
```
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument('--disable-blink-features=AutomationControlled')
        chrome_options.set_capability('goog:loggingPrefs', {'performance': 'ALL'})
        chrome_options.add_argument('--disable-web-security')
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument('--allow-running-insecure-content')
        chrome_options.add_argument('--headless')
        chrome_options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36");
                path = ChromeDriverManager(driver_version="114.0.5735.90").install()
        print(f"path {path}")
        service=ChromeService(executable_path=path)
        browser = webdriver.Chrome(service=service, options=chrome_options)
```
I got the error

```
[2024-04-04, 00:31:56 KST] {logging_mixin.py:188} INFO - Starting the browser...
[2024-04-04, 00:31:56 KST] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-04-04, 00:31:56 KST] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2024-04-04, 00:31:57 KST] {logger.py:11} INFO - Driver downloading response is 200
[2024-04-04, 00:32:00 KST] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2024-04-04, 00:32:00 KST] {logging_mixin.py:188} INFO - path /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver
[2024-04-04, 00:32:00 KST] {service.py:204} DEBUG - Started executable: `/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver` in a child process with pid: 2009
[2024-04-04, 00:32:01 KST] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_trend/google_trend_dag.py", line 68, in get_google_trend_charts
    google_trend_crawler = GoolgeTrendCrawler(current_date)
  File "/opt/airflow/dags/utils/google_trend/google_trend_crawler.py", line 21, in __init__
    self.scraper = GoogleTrendsScraper(sleep=10, headless=True)
  File "/opt/airflow/dags/utils/google_trend/google_trend_scraper.py", line 252, in __init__
    self.start_browser()
  File "/opt/airflow/dags/utils/google_trend/google_trend_scraper.py", line 300, in start_browser
    self.browser = webdriver.Chrome(service=service, options=chrome_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 97, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 255
```

please help take a look at it. 

### How can we reproduce the issue?

```shell
I did provided above
```

### Relevant log output

```shell
I did provided above
```

### Operating System

Ubuntu

### Selenium version

selenium==4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114.0.5735.90

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 114.0.5735.90

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Please increase the log level and share the logs again: https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
