### ISSUE TITLE
[🐛 Bug]: Python easyocr causes Selenium to fail

### ISSUE THREAD

**Issue by Hedonical** [SeleniumHQ/selenium#13784]
### What happened?

I have code that imports both easyocr and selenium. When I was importing selenium by itself, it ran with no errors, but when I try to run selenium with easyocr imported, it fails with the error message:
```
Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
I have tried `chrome_options.add_argument('--remote-debugging-pipe')`, but this leads to a rendering timeout. I have also tried disabling the GPU to resolve the error but this also leads to a rendering timeout. I am unsure why this is occurring since to my knowledge neither package shares any dependencies or any other clear points of conflict. Many thanks ahead of time! (Python 3.12.2 )

### How can we reproduce the issue?

```shell
import easyocr
from selenium import webdriver
driver = webdriver.Chrome()
```

### Relevant log output

```shell
>>> from selenium import webdriver
>>> driver = webdriver.Chrome()
>>> 
KeyboardInterrupt
>>> import easyocr
>>> driver = webdriver.Chrome()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hedonics/anaconda3/envs/space/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/hedonics/anaconda3/envs/space/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/hedonics/anaconda3/envs/space/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/hedonics/anaconda3/envs/space/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hedonics/anaconda3/envs/space/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/hedonics/anaconda3/envs/space/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x585b084fa873 <unknown>
#1 0x585b081f08c6 <unknown>
#2 0x585b08224d34 <unknown>
#3 0x585b08220d3d <unknown>
#4 0x585b08269aed <unknown>
#5 0x585b0825d343 <unknown>
#6 0x585b0822e593 <unknown>
#7 0x585b0822ef5e <unknown>
#8 0x585b084be85b <unknown>
#9 0x585b084c27b5 <unknown>
#10 0x585b084ac581 <unknown>
#11 0x585b084c3342 <unknown>
#12 0x585b0849188f <unknown>
#13 0x585b084e9738 <unknown>
#14 0x585b084e990b <unknown>
#15 0x585b084f99c4 <unknown>
#16 0x7f8db3094ac3 <unknown>
```

### Operating System

Ubuntu 22.04

### Selenium version

Python 4.19.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 123

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 123.0.6312.105

**Comment by Hedonical** [comment]
Note that I have tried this now with `keras_ocr`, which uses tensorflow instead of pytorch. Loading `keras_ocr` causes the same error above.

**Comment by Hedonical** [comment]
I have also tested with only `pytesseract` which causes no errors (does not use pytorch or tensorflow). Therefore, I assume this error is being caused by a GPU conflict with Chrome.

**Comment by diemol** [comment]
If the issue is caused when easyocr is used, unfortunately, there is not much we can do. Why don't you raise the issue at https://github.com/JaidedAI/EasyOCR?
