### ISSUE TITLE
[🐛 Bug]: Ubuntu SessionNotCreatedException no chrome binary at /usr/bin/google-chrome but google chrome is there and working

### ISSUE THREAD

**Issue by nienienienie** [SeleniumHQ/selenium#13783]
### What happened?

When I run simple Kotlin program on Ubuntu I'm getting error:
```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: no chrome binary at /usr/bin/google-chrome 
Host info: host: 'jenkins-ubuntu-s-1vcpu-512mb-10gb-fra1-01', ip: '127.0.1.1'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-9-generic', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], binary: /usr/bin/google-chrome, extensions: [], prefs: {download.default_directory: /Users/meUser/Download..., download.directory_upgrade: true, download.prompt_for_download: false, safebrowsing.enabled: true}}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:139)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)
```

but it seems that binary is **indeed** in that location, proof:
```
$ which google-chrome
/usr/bin/google-chrome
```

and even more proof:
```
$ google-chrome --headless --disable-gpu --dump-dom http://example.com
[0405/205306.178528:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/opt/chrome/policies/managed
[0405/205306.180807:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/opt/chrome/policies/recommended
[0405/205306.329071:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[0405/205306.351842:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[0405/205307.262878:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0405/205307.448623:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
<!DOCTYPE html>
<html><head>
    <title>Example Domain</title>

    <meta charset="utf-8">
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
...
```

### How can we reproduce the issue?

the program:
```Kotlin
fun main(args: Array<String>) {
    val downloadDir = "/Users/meUser/Downloads/eKrsSeleniumWorkDir"

    val chromeOptions = ChromeOptions()
    chromeOptions.setExperimentalOption("prefs", mapOf(
        "download.default_directory" to downloadDir,
        "download.prompt_for_download" to false,
        "download.directory_upgrade" to true,
        "safebrowsing.enabled" to true
    ))
    val driver: WebDriver = ChromeDriver(chromeOptions) // <- exception happens here
...
```
```


### Relevant log output

```shell
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: no chrome binary at /usr/bin/google-chrome 
Host info: host: 'jenkins-ubuntu-s-1vcpu-512mb-10gb-fra1-01', ip: '127.0.1.1'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-9-generic', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], binary: /usr/bin/google-chrome, extensions: [], prefs: {download.default_directory: /Users/meUser/Download..., download.directory_upgrade: true, download.prompt_for_download: false, safebrowsing.enabled: true}}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:139)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)
```
```


### Operating System

Ubuntu

### Selenium version

org.seleniumhq.selenium:selenium-java:4.18.1

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 123.0.6312.105

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 123.0.6312.105 (399174dbe6eff0f59de9a6096129c0c827002b3a-refs/branch-heads/6312@{#761})

### Are you using Selenium Grid?

no

**Comment by nienienienie** [comment]
logs with https://github.com/titusfortner/selenium-logger set to `SeleniumLogger.enable()`

logs from Ubuntu
```
2024-04-08 11:26:54 FINE Selenium [SeleniumManager getBinary] Selenium Manager binary found at: /home/meUser3000/.cache/selenium/manager/0.4.18/selenium-manager 
2024-04-08 11:26:54 FINE Selenium [SeleniumManager runCommand] Executing Process: [--browser, chrome, --language-binding, java, --output, json, --debug] 
2024-04-08 11:26:58 FINE Selenium [ExternalProcess] completed to copy the output of process 233304 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] Sending stats to Plausible: Props { browser: "chrome", browser_version: "", os: "linux", arch: "x86_64", lang: "java", selenium_version: "4.18" } 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] Found chromedriver 123.0.6312.105 in PATH: /usr/bin/chromedriver 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] chrome detected at /usr/bin/google-chrome 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] Running command: /usr/bin/google-chrome --version 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] Output: "Google Chrome 123.0.6312.105 " 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] Detected browser: chrome 123.0.6312.105 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] Discovering versions from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] Required driver: chromedriver 123.0.6312.105 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] Driver path: /usr/bin/chromedriver 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager] Browser path: /usr/bin/google-chrome 
2024-04-08 11:26:58 FINE Selenium [SeleniumManager getDriverPath] Using driver at location: /usr/bin/chromedriver, browser at location /usr/bin/google-chrome 
2024-04-08 11:26:59 FINE Selenium [RemoteWebDriver] Executing: newSession [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-dev-shm-usage], binary: /usr/bin/google-chrome, extensions: [], prefs: {download.default_directory: /Users/meUser/Download..., download.directory_upgrade: true, download.prompt_for_download: false, safebrowsing.enabled: true}}}]}] 
2024-04-08 11:26:59 FINE Selenium [DriverService start] Starting driver at /usr/bin/chromedriver with [--port=23299] 
2024-04-08 11:26:59 FINE Selenium [UrlChecker waitUntilAvailable] Waiting for [http://localhost:23299/status] 
2024-04-08 11:26:59 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:26:59 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:26:59 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:26:59 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:26:59 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:26:59 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:27:00 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:27:00 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:27:00 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:27:01 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:27:01 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:27:01 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:27:02 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:27:02 FINE Selenium [UrlChecker] Polling http://localhost:23299/status 
2024-04-08 11:27:02 FINE Selenium [JdkHttpClient execute0] Executing request: (POST) /session 
2024-04-08 11:27:03 FINE Selenium [JdkHttpClient execute0] Ending request (POST) /session in 359ms 
2024-04-08 11:27:03 FINE Selenium [UrlChecker waitUntilUnavailable] Waiting for http://localhost:23299/shutdown 
2024-04-08 11:27:03 FINE Selenium [UrlChecker] Polling http://localhost:23299/shutdown 
2024-04-08 11:27:03 FINE Selenium [UrlChecker] Polling http://localhost:23299/shutdown 
2024-04-08 11:27:03 FINE Selenium [ExternalProcess] completed to copy the output of process 233382 
2024-04-08 11:27:03 FINE Selenium [RemoteWebDriver] Exception: newSession Could not start a new session. Response code 500. Message: unknown error: no chrome binary at /usr/bin/google-chrome 
Host info: host: 'jenkins-ubuntu-s-1vcpu-512mb-10gb-fra1-01', ip: '127.0.1.1'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-9-generic', java.version: '17.0.10'
Driver info: driver.version: ChromeDriver 
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: no chrome binary at /usr/bin/google-chrome 
Host info: host: 'jenkins-ubuntu-s-1vcpu-512mb-10gb-fra1-01', ip: '127.0.1.1'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-9-generic', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-dev-shm-usage], binary: /usr/bin/google-chrome, extensions: [], prefs: {download.default_directory: /Users/meUser/Download..., download.directory_upgrade: true, download.prompt_for_download: false, safebrowsing.enabled: true}}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:139)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)
	at MainKt.main(Main.kt:29)
```

**Comment by nienienienie** [comment]
similar logs but from Fedora
```
2024-04-08 14:18:14 FINE Selenium [SeleniumManager getBinary] Selenium Manager binary found at: /root/.cache/selenium/manager/0.4.18/selenium-manager 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager runCommand] Executing Process: [--browser, chrome, --language-binding, java, --output, json, --debug] 
2024-04-08 14:18:14 FINE Selenium [ExternalProcess] completed to copy the output of process 2337 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] chromedriver not found in PATH 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] chrome not found in PATH 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] chrome not found in the system 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] Required browser: chrome 123.0.6312.105 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] chrome 123.0.6312.105 already exists 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] chrome 123.0.6312.105 is available at /root/.cache/selenium/chrome/linux64/123.0.6312.105/chrome 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] Required driver: chromedriver 123.0.6312.105 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] chromedriver 123.0.6312.105 already in the cache 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] Driver path: /root/.cache/selenium/chromedriver/linux64/123.0.6312.105/chromedriver 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager] Browser path: /root/.cache/selenium/chrome/linux64/123.0.6312.105/chrome 
2024-04-08 14:18:14 FINE Selenium [SeleniumManager getDriverPath] Using driver at location: /root/.cache/selenium/chromedriver/linux64/123.0.6312.105/chromedriver, browser at location /root/.cache/selenium/chrome/linux64/123.0.6312.105/chrome 
2024-04-08 14:18:15 FINE Selenium [RemoteWebDriver] Executing: newSession [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless], binary: /root/.cache/selenium/chrom..., extensions: [], prefs: {download.default_directory: /root/eKrsSelenium-1.0-SNAP..., download.directory_upgrade: true, download.prompt_for_download: false, safebrowsing.enabled: true}}}]}] 
2024-04-08 14:18:15 FINE Selenium [DriverService start] Starting driver at /root/.cache/selenium/chromedriver/linux64/123.0.6312.105/chromedriver with [--port=12977] 
2024-04-08 14:18:15 FINE Selenium [UrlChecker waitUntilAvailable] Waiting for [http://localhost:12977/status] 
2024-04-08 14:18:15 FINE Selenium [UrlChecker] Polling http://localhost:12977/status 
2024-04-08 14:18:15 FINE Selenium [JdkHttpClient execute0] Executing request: (POST) /session 
2024-04-08 14:18:16 FINE Selenium [JdkHttpClient execute0] Ending request (POST) /session in 555ms 
2024-04-08 14:18:16 FINE Selenium [UrlChecker waitUntilUnavailable] Waiting for http://localhost:12977/shutdown 
2024-04-08 14:18:16 FINE Selenium [UrlChecker] Polling http://localhost:12977/shutdown 
2024-04-08 14:18:16 FINE Selenium [ExternalProcess] completed to copy the output of process 2348 
2024-04-08 14:18:16 FINE Selenium [UrlChecker] Polling http://localhost:12977/shutdown 
2024-04-08 14:18:16 FINE Selenium [RemoteWebDriver] Exception: newSession Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /root/.cache/selenium/chrome/linux64/123.0.6312.105/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'seleniumtest1-fedora-s-1vcpu-2gb-ams3-01', ip: '127.0.0.1'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.6-300.fc39.x86_64', java.version: '17.0.9'
Driver info: driver.version: ChromeDriver 
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /root/.cache/selenium/chrome/linux64/123.0.6312.105/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'seleniumtest1-fedora-s-1vcpu-2gb-ams3-01', ip: '127.0.0.1'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.6-300.fc39.x86_64', java.version: '17.0.9'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless], binary: /root/.cache/selenium/chrom..., extensions: [], prefs: {download.default_directory: /root/eKrsSelenium-1.0-SNAP..., download.directory_upgrade: true, download.prompt_for_download: false, safebrowsing.enabled: true}}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:139)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)
	at MainKt.main(Main.kt:46)
```

**Comment by diemol** [comment]
@bonigarcia do you know why this can happen? Was it because the browser path is a symlink?

**Comment by bonigarcia** [comment]
From what I can see, the Rust side is working correctly. SM returns both the chromedriver and Chrome path.

@diemol Answering your question, the fact that the browser path is a symlink should not be a problem. In fact, in most Linux systems, the Chrome path is a symlink, and the Selenium session should be started correctly by the bindings. I have just executed a simple [Java test](https://github.com/bonigarcia/selenium-examples/blob/main/src/test/java/io/github/bonigarcia/selenium/logging/ChromeLoggingTest.java) in a Linux machine:

```
Apr 09, 2024 11:15:41 AM org.openqa.selenium.manager.SeleniumManager getBinary
FINE: Selenium Manager binary found at: /home/user/.cache/selenium/manager/0.4.19/selenium-manager
Apr 09, 2024 11:15:41 AM org.openqa.selenium.manager.SeleniumManager runCommand
FINE: Executing Process: [--browser, chrome, --language-binding, java, --output, json, --debug]
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Sending stats to Plausible: Props { browser: "chrome", browser_version: "", os: "linux", arch: "x86_64", lang: "java", selenium_version: "4.19" }
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: chromedriver not found in PATH
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: chrome detected at /usr/bin/google-chrome
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Running command: /usr/bin/google-chrome --version
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Output: "Google Chrome 120.0.6099.199 "
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Detected browser: chrome 120.0.6099.199
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Discovering versions from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Required driver: chromedriver 120.0.6099.109
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: chromedriver 120.0.6099.109 already in the cache
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Driver path: /home/user/.cache/selenium/chromedriver/linux64/120.0.6099.109/chromedriver
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
FINE: Browser path: /usr/bin/google-chrome
Apr 09, 2024 11:15:42 AM org.openqa.selenium.manager.SeleniumManager getDriverPath
FINE: Using driver at location: /home/user/.cache/selenium/chromedriver/linux64/120.0.6099.109/chromedriver, browser at location /usr/bin/google-chrome
Apr 09, 2024 11:15:47 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find CDP implementation matching 120
Apr 09, 2024 11:15:47 AM org.openqa.selenium.chromium.ChromiumDriver lambda$new$5
WARNING: Unable to find version of CDP to use for 120.0.6099.199. You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.19.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
```

```
user@ubuntu-vm:~/dev/selenium-examples$ ls -l /usr/bin/google-chrome
lrwxrwxrwx 1 root root 31 ene  2 23:46 /usr/bin/google-chrome -> /etc/alternatives/google-chrome
```

I don't know why the bindings raised the error `no chrome binary at`. I would check the condition checked by Java to fail with that error.

Also, maybe it is worth bumping Selenium to 4.19, the latest stable currently.

**Comment by diemol** [comment]
The error is returned directly by ChromeDriver, not the Java bindings, so I wondered about the symlink. 

@nienienienie can you check and execute the binary found at `/usr/bin/google-chrome`? If that works, can you please start ChromeDriver (`/usr/bin/chromedriver`) and post the following payload to it?

```
curl --request POST \
  --url http://localhost:9515/session \
  --header 'Content-Type: application/json; charset=utf-8' \
  --data '{
  "capabilities": {
		"alwaysMatch": {
			"browserName": "chrome",
			"goog:chromeOptions": {
				binary: "/usr/bin/google-chrome"
			},
		},
    "firstMatch": [{}]
  }
}'
```

**Comment by nienienienie** [comment]
after starting ChromeDriver and posting the above payload, I'm getting an error:
```
{
   "value":{
      "error":"invalid argument",
      "message":"invalid argument: missing command parameters",
      "stacktrace":"#0 0x56424c037073 \u003Cunknown>\n#1 0x56424bd45a66 \u003Cunknown>\n#2 0x56424bdac010 \u003Cunknown>\n#3 0x56424bdab46e \u003Cunknown>\n#4 0x56424bd1325f \u003Cunknown>\n#5 0x56424bffe8ef \u003Cunknown>\n#6 0x56424c002757 \u003Cunknown>\n#7 0x56424bfece78 \u003Cunknown>\n#8 0x56424c0031cd \u003Cunknown>\n#9 0x56424bfd356e \u003Cunknown>\n#10 0x56424bd118c4 \u003Cunknown>\n#11 0x7f9b68474d90 \u003Cunknown>\n"
   }
}
```
which - unfortutanely - is unreadable for me

**Comment by diemol** [comment]
I missed quotes on "binary", please try:

```
curl --request POST \
  --url http://localhost:9515/session \
  --header 'Content-Type: application/json; charset=utf-8' \
  --data '{
  "capabilities": {
		"alwaysMatch": {
			"browserName": "chrome",
			"goog:chromeOptions": {
				"binary": "/usr/bin/google-chrome"
			}
		},
    "firstMatch": [{}]
  }
}
'
```

**Comment by nienienienie** [comment]
also no good, after starting
```
$ /usr/bin/chromedriver &
```

and then curling
```
curl --request POST   --url http://localhost:9515/session   --header 'Content-Type: application/json; charset=utf-8'   --data '{"capabilities": {"alwaysMatch": {"browserName": "chrome","goog:chromeOptions": {"binary": "/usr/bin/google-chrome"},},"firstMatch": [{}]}}'
```

it gives
```
{
   "value":{
      "error":"invalid argument",
      "message":"invalid argument: missing command parameters",
      "stacktrace":"#0 0x5620bdb06073 \u003Cunknown>\n#1 0x5620bd814a66 \u003Cunknown>\n#2 0x5620bd87b010 \u003Cunknown>\n#3 0x5620bd87a46e \u003Cunknown>\n#4 0x5620bd7e225f \u003Cunknown>\n#5 0x5620bdacd8ef \u003Cunknown>\n#6 0x5620bdad1757 \u003Cunknown>\n#7 0x5620bdabbe78 \u003Cunknown>\n#8 0x5620bdad21cd \u003Cunknown>\n#9 0x5620bdaa256e \u003Cunknown>\n#10 0x5620bd7e08c4 \u003Cunknown>\n#11 0x7f0e888a1d90 \u003Cunknown>\n"
   }
}
```

**Comment by nienienienie** [comment]
on the other hand, when I run other command I get different error
```
farmazon3000@jenkins-ubuntu-s-1vcpu-512mb-10gb-fra1-01:~$ chromedriver --port=4444 &
[1] 308138
farmazon3000@jenkins-ubuntu-s-1vcpu-512mb-10gb-fra1-01:~$ Starting ChromeDriver 123.0.6312.105 (399174dbe6eff0f59de9a6096129c0c827002b3a-refs/branch-heads/6312@{#761}) on port 4444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
farmazon3000@jenkins-ubuntu-s-1vcpu-512mb-10gb-fra1-01:~$ curl -X POST http://localhost:4444/session -d '{"desiredCapabilities": {"browserName": "chrome"}}'
{"sessionId":"fffe74ed4c8ed7e5ca2f0c06d3a53595","status":33,"value":{"message":"session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /snap/chromium/2811/usr/lib/chromium-browser/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\n  (Driver info: chromedriver=123.0.6312.105 (399174dbe6eff0f59de9a6096129c0c827002b3a-refs/branch-heads/6312@{#761}),platform=Linux 6.5.0-9-generic x86_64)"}}

```

**Comment by diemol** [comment]
OK, the recent comment shows that there is something wrong with the environment in which you are executing ChromeDriver. It seems to be a Jenkins server, so ensure you have a window manager like FluxBox and a virtual display like XVFB.
