### ISSUE TITLE
[🐛 Bug]: Cannot use Firefox on linux ubuntu 23.10

### ISSUE THREAD

**Issue by EzGrade** [SeleniumHQ/selenium#13782]
### What happened?

I was trying to use firefox on linux ubuntu 23.10. But I was either getting timeout error or marionette error.
Code:
```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager

options = Options()
options.add_argument('--headless')
driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()), options=options)

driver.get("https://python.org")
print(driver.title)
driver.close()
```

### How can we reproduce the issue?

```shell
Install geckodriver:
Use this link to download:
https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
Unzip it:
tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
Then:
chmod +x geckodriver
Move it:
sudo mv geckodriver /usr/local/bin/
Install firefox:
sudo apt-get install firefox

Try to run this code:
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager

options = Options()
options.add_argument('--headless')
driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()), options=options)

driver.get("https://python.org")
print(driver.title)
driver.close()
```

### Relevant log output

```shell
(venv) root@scrapper:~/MembersScrapper# python3 test.py
DEBUG:selenium.webdriver.common.selenium_manager:Selenium Manager binary found at: /root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG:selenium.webdriver.common.selenium_manager:Executing process: /root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --debug --language-binding python --output json
DEBUG:selenium.webdriver.common.selenium_manager:Found geckodriver 0.34.0 in PATH: /usr/local/bin/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:firefox detected at /usr/bin/firefox
DEBUG:selenium.webdriver.common.selenium_manager:Running command: /usr/bin/firefox -v
DEBUG:selenium.webdriver.common.selenium_manager:Output: "Mozilla Firefox 124.0.2"
DEBUG:selenium.webdriver.common.selenium_manager:Detected browser: firefox 124.0.2
DEBUG:selenium.webdriver.common.selenium_manager:Required driver: geckodriver 0.34.0
DEBUG:selenium.webdriver.common.selenium_manager:Driver path: /usr/local/bin/geckodriver
DEBUG:selenium.webdriver.common.selenium_manager:Browser path: /usr/bin/firefox
DEBUG:selenium.webdriver.common.selenium_manager:Using driver at: /usr/local/bin/geckodriver
DEBUG:selenium.webdriver.common.service:Started executable: `/usr/local/bin/geckodriver` in a child process with pid: 31949 using 0 to output -3
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:50087/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'firefox', 'acceptInsecureCerts': True, 'moz:debuggerAddress': True, 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'moz:firefoxOptions': {'binary': '/usr/bin/firefox', 'args': ['--headless']}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:50087
DEBUG:urllib3.connectionpool:http://localhost:50087 "POST /session HTTP/1.1" 500 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=500 | data={"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":""}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '105', 'date': 'Fri, 05 Apr 2024 08:45:30 GMT'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "/root/MembersScrapper/test.py", line 12, in <module>
    driver = webdriver.Firefox(options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette
```

### Operating System

Linux Ubuntu 23.10

### Selenium version

Python 4.19.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 124.0.2

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.34.0

**Comment by diemol** [comment]
Get rid of `from webdriver_manager.firefox import GeckoDriverManager` and let Selenium handle the browser driver. Let us know how it goes.

**Comment by EzGrade** [comment]
Here is updated code:
```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

options = Options()
options.add_argument('--headless')
driver = webdriver.Firefox(options=options)

driver.get("https://python.org")
print(driver.title)
driver.close()
```

Error I got:
```
(venv) root@ubuntu-s-2vcpu-4gb-120gb-intel-fra1-01:~/MembersScrapper# python3 test.py
Traceback (most recent call last):
  File "/root/MembersScrapper/test.py", line 6, in <module>
    driver = webdriver.Firefox(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/MembersScrapper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Failed to read marionette port
```

**Comment by EzGrade** [comment]
Also, I just tried to run same code inside docker container. Here what I got:
```
2024-04-06 17:18:41 Traceback (most recent call last):
2024-04-06 17:18:41   File "/app/main.py", line 6, in <module>
2024-04-06 17:18:41     driver = webdriver.Firefox(options=options)
2024-04-06 17:18:41              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-06 17:18:41   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 69, in __init__
2024-04-06 17:18:41     super().__init__(command_executor=executor, options=options)
2024-04-06 17:18:41   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
2024-04-06 17:18:41     self.start_session(capabilities)
2024-04-06 17:18:41   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
2024-04-06 17:18:41     response = self.execute(Command.NEW_SESSION, caps)["value"]
2024-04-06 17:18:41                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-06 17:18:41   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
2024-04-06 17:18:41     self.error_handler.check_response(response)
2024-04-06 17:18:41   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
2024-04-06 17:18:41     raise exception_class(message, screen, stacktrace)
2024-04-06 17:18:41 selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 255
2024-04-06 17:18:41
```

**Comment by diemol** [comment]
This seems to be an issue with the environment setup. Perhaps you can get some ideas after reading this SO post https://stackoverflow.com/questions/72374955/failed-to-read-marionette-port-when-running-selenium-geckodriver-firefox-a.

If the issue still persists after following the recommendations from that link, you should report the issue to the GeckoDriver folks (links below).
