### ISSUE TITLE
[🐛 Bug]: driver.getDevTools().createsession() throwing error

### ISSUE THREAD

**Issue by sudha1218** [SeleniumHQ/selenium#13799]
### What happened?

```shell
Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'
	at org.openqa.selenium.devtools.v123.target.Target.getTargets(Target.java:150)
	at org.openqa.selenium.devtools.v123.v123Target.getTargets(v123Target.java:55)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:95)
	at org.openqa.selenium.devtools.DevTools.createSessionIfThereIsNotOne(DevTools.java:89)
	at utils.Devtools.seltest(Devtools.java:22)
	at utils.Devtools.main(Devtools.java:28)
```

### How can we reproduce the issue?

```java
ChromeOptions opt = new ChromeOptions();
opt.addArguments("--remote-allow-origins=*");
WebDriverManager.chromedriver().setup();
driver = new ChromeDriver(opt);
DevTools devtools = driver.getDevTools();
devtools.createSession();
```

### Relevant log output

```shell
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 123.0.6312.105 (399174dbe6eff0f59de9a6096129c0c827002b3a-refs/branch-heads/6312@{#761}) on port 52224
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Apr 10, 2024 11:42:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Apr 10, 2024 11:42:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found exact CDP implementation for version 123
Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'
	at org.openqa.selenium.devtools.v123.target.Target.getTargets(Target.java:150)
	at org.openqa.selenium.devtools.v123.v123Target.getTargets(v123Target.java:55)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:95)
	at org.openqa.selenium.devtools.DevTools.createSessionIfThereIsNotOne(DevTools.java:89)
	at utils.Devtools.seltest(Devtools.java:22)
	at utils.Devtools.main(Devtools.java:28)
```

### Operating System

Win 10

### Selenium version

4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 123

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 123

### Are you using Selenium Grid?

No

**Comment by krmahadevan** [comment]
@sudha1218 - Couple of things.

1. Please remove this line `WebDriverManager.chromedriver().setup();` and also corresponding maven/gradle dependency from your build file. This is NO longer needed because Selenium internally takes care of this.
2. Please show us what your dependencies look like. If you are using a parent pom file (in the maven world) then we would need to see the complete pom file as well.

It looks like something could be messing up your CLASSPATH and for that to be confirmed we need to see how your dependencies are being setup.

**Comment by sudha1218** [comment]
Thanks for your Quick response. 

Here is my POM file

[POM.txt](https://github.com/SeleniumHQ/selenium/files/14941384/POM.txt)

**Comment by krmahadevan** [comment]
@sudha1218 - The problem is in your pom file. You have a lot of stale dependencies related to selenium. I have cleaned up the selenium related dependencies and tried the sample. It works. 

Please have your dependencies section look like below:

```xml
	<dependencies>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-jvm-deps</artifactId>
			<version>1.0.6</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.19.1</version>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.24.2</version>
			<scope>compile</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.testng/testng -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.6.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/info.cukes/cucumber-jvm-deps -->
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm-deps</artifactId>
			<version>1.0.5</version>
			<scope>provided</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/info.cukes/cucumber-java -->
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.5</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm</artifactId>
			<version>1.2.5</version>
			<type>pom</type>
		</dependency>
		<!-- https://mvnrepository.com/artifact/info.cukes/cucumber-core -->
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>1.2.5</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/info.cukes/cucumber-html -->
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-html</artifactId>
			<version>0.2.3</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/info.cukes/gherkin -->
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>gherkin</artifactId>
			<version>2.12.2</version>
			<scope>provided</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/info.cukes/cucumber-testng -->
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>1.2.5</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.hamcrest/hamcrest-all -->
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
			<scope>compile</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/info.cukes/cucumber-picocontainer -->
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>1.2.5</version>
			<scope>compile</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.aventstack/extentreports -->
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>3.1.2</version>
		</dependency>
		<dependency>
			<groupId>com.vimalselvam</groupId>
			<artifactId>cucumber-extentsreport</artifactId>
			<version>3.0.2</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.freemarker/freemarker -->
		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
			<version>2.3.31</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/net.masterthought/cucumber-reporting -->
		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>5.7.5</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>4.1.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.13.0</version>
		</dependency>
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports-cucumber4-adapter</artifactId>
			<version>1.0.6</version>
		</dependency>
	</dependencies>
```

Note: I would suggest that you spend some time cleaning up your dependencies. You. seem to have a lot of old versions and also a lot of redundant dependencies as well.

Note:

You no longer require the below dependency for managing your webdriver binaries. @bonigarcia has helped integrate the core functionality of webdriver manager into selenium itself. So if you just use the selenium dependencies alone, that should suffice. Everything else is taken care of by selenium.

```xml
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>5.5.2</version>
			<exclusions>
				<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>guava</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

Always remember to use the latest released version of selenium `4.19.1` as of today.

To learn more about the selenium manager, please refer to the official blog post on this [here](https://www.selenium.dev/blog/2022/introducing-selenium-manager/)

**Comment by sudha1218** [comment]
Thank you so much @krmahadevan. 

I will try with this POM file.

I will work on your note points. 

Thank you...

**Comment by sudha1218** [comment]
It worked @krmahadevan
