### ISSUE TITLE
[🐛 Bug]: java.lang.NoClassDefFoundError: org/openqa/selenium/remote/http/netty/NettyClient$Factory

### ISSUE THREAD

**Issue by sudha1218** [SeleniumHQ/selenium#13800]
### What happened?

I have removed dependency for http jdk client and used selenium latest version 4.19.1. 
Getting this error.
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/http/netty/NettyClient$Factory

### How can we reproduce the issue?

```shell
Use latest version of selenium and remove all selenium dependencies
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/http/nettty/NettyClient$Factory
at java.base/Java.lang.ClassLoader.defineClass1(Native Method)
```

### Operating System

Win 10

### Selenium version

4.19.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 123

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 123

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
When this has been reported it has always been an issue with the dependencies you use in your pom. Can you share your full pom.xml file?

4.19.1 has been out for over two weeks; if this had been a real issue, it would have been reported all over the place.

**Comment by sudha1218** [comment]
I can not provide the POM file as it is in my client machine.
I can provide the screenshots

**Comment by sudha1218** [comment]
![1](https://github.com/SeleniumHQ/selenium/assets/32418307/8a652643-8637-4d0f-87e5-44221809a1b3)
![2](https://github.com/SeleniumHQ/selenium/assets/32418307/85d21c33-cef3-4788-9132-eeacfc6c3974)
![3](https://github.com/SeleniumHQ/selenium/assets/32418307/d1e27aec-f003-482c-a473-d17d9f4c44b2)
![4](https://github.com/SeleniumHQ/selenium/assets/32418307/e60f87de-42b0-4401-82a5-bd4c98d5674f)
![5](https://github.com/SeleniumHQ/selenium/assets/32418307/b1ed1af8-f91d-4705-ac94-a28ceabdc54f)
![6](https://github.com/SeleniumHQ/selenium/assets/32418307/69d2e41e-b8d3-4df4-afeb-35001ad8ce87)
![7](https://github.com/SeleniumHQ/selenium/assets/32418307/3c3599ee-83fa-49df-8fae-a8d0f2ad3dd5)
![8](https://github.com/SeleniumHQ/selenium/assets/32418307/b0d4abbc-ad65-47f2-a396-1985d68fd7a4)

**Comment by krmahadevan** [comment]
@sudha1218 - providing screenshots is NOT going to help because we would need to find out what in your dependencies is causing this goof up. I believe for an earlier issue you shared the pom file. So why not this time again?

If its still a problem. Here are a few maven commands that you can use and which will tell us what we need

`mvn dependency:tree` - Ensure that you share the complete output of this. This will tell us on the command line as to what you are resolving via maven. Quick tip: You can use this command along with a grep to tell you what are the selenium dependencies (for e.g., `mvn dependency:tree | grep 'selenium'`
`mvn dependency:analyze-report` - This will help you in your effort to clean-up your pom file. You will see a nice little html file under `target/site/dependency-analysis.html`

Read more about these in https://maven.apache.org/plugins/maven-dependency-plugin/plugin-info.html

**Comment by sudha1218** [comment]
Last time I was implemented in my personal laptop, So I shared POM file. But this time I am facing the issue  in my client machine that I could not able to share.

Okay. I will try to solve

**Comment by kakliniew** [comment]
I faced the same issue. Was using serenity 3.9.8, but updated to 4.1.4 (which uses selenium 4.18.1). I guess its something with dependencies, but checked and all of them should use seleniumVersion 4.18.1. I am using selenium hub (can it be connected to older version of hub?). I was trying to solve the problem with jdk-http but still the same. 
I saw similar issue here: https://github.com/SeleniumHQ/selenium/issues/9173 but don't know how to apply it with gradle (tried to set gradle.properties) 

Found also here: https://github.com/SeleniumHQ/selenium/issues/12924


**EDIT: Removing Selenide resolved my issue. Luckily it was easy in my case** 
```
serenity_version=4.1.4
spring_boot_version=2.7.18
assertj_core_version=3.24.2
drivers_version=4.18.1
selenide_version=6.19.1
webdrivermanagerVersion=5.7.0
seleniumVersion=4.18.1

```
```
  implementation "net.serenity-bdd:serenity-core:${serenity_version}"                 
    implementation "net.serenity-bdd:serenity-junit:${serenity_version}"
    implementation "net.serenity-bdd:serenity-spring:${serenity_version"
    implementation "net.serenity-bdd:serenity-cucumber:${serenity_version}"
    

    implementation "org.springframework.boot:spring-boot-autoconfigure:${spring_boot_version}"
    implementation "org.springframework.boot:spring-boot-starter-test:${spring_boot_version}"
 
    implementation "org.assertj:assertj-core:${assertj_core_version}"
    
    implementation "com.galenframework:galen-java-support:2.4.4"
   
    implementation "com.codeborne:selenide:${selenide_version}"
    
    implementation "io.github.bonigarcia:webdrivermanager:${webdrivermanagerVersion}"
    implementation "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"
    implementation 'org.seleniumhq.selenium:selenium-http-jdk-client:4.5.0'
    
    implementation "org.seleniumhq.selenium:selenium-firefox-driver:${drivers_version}"
    implementation "org.seleniumhq.selenium:selenium-chrome-driver:${drivers_version}"
    implementation "org.seleniumhq.selenium:selenium-edge-driver:${drivers_version}"
    implementation "org.seleniumhq.selenium:selenium-safari-driver:${drivers_version}"
    implementation "org.seleniumhq.selenium:selenium-remote-driver:${drivers_version}"
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.8.1"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:5.8.1"
    testImplementation "org.junit.vintage:junit-vintage-engine:5.8.1"
```

```
 java.lang.NoClassDefFoundError: org/openqa/selenium/remote/http/netty/NettyClient$Factory
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1210)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
        at java.base/java.util.Spliterators$IteratorSpliterator.trySplit(Spliterators.java:1776)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:308)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.openqa.selenium.remote.http.HttpClient$Factory.create(HttpClient.java:55)
        at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:74)
        at org.openqa.selenium.remote.RemoteWebDriver.createExecutor(RemoteWebDriver.java:190)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
        at net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider.newInstance(RemoteDriverProvider.java:86)
        at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:164)
        at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:142)
        at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:178)
        at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:169)
        at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:120)
```

**Comment by mustafasahin0** [comment]
any updates on this error: java.lang.NoClassDefFoundError: org/openqa/selenium/remote/http/netty/NettyClient$Factory
I am also getting this error starting from Selenium Version 4.14.1

**Comment by diemol** [comment]
@mustafasahin0 this is an issue with dependencies, please follow @krmahadevan's [advice](https://github.com/SeleniumHQ/selenium/issues/13800#issuecomment-2050903207). 

I am closing this issue because it is not related to Selenium.
