### ISSUE TITLE
 [🐛 Bug]: chromedriver (version 123) on Mac Sonoma getting timed out when going to Wellsfargo.com due to missing font

### ISSUE THREAD

**Issue by thp2016** [SeleniumHQ/selenium#13805]
### What happened?

You will ONLY see this issue as described. Using Chrome will not see the pop-up as seen below.

Navigate to www.wellsfargo.com on Mac chromedriver then you will see a Google Chrome Helper pop-up that will timeout unless you select a choice.

![image](https://github.com/SeleniumHQ/selenium/assets/18434029/6454e998-767b-48e5-9cd8-d02ae27aaf20)

### How can we reproduce the issue?

```shell
Run chromedriver on Mac to see issue (works fine in Windows 10 and 11)
```

### Relevant log output

```shell
org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.19.1', revision: 'abe0ee07dc'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.4.1', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [7217ef11d3daa722b8d39982beafd58d, getCurrentUrl {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 123.0.6312.107, chrome: {chromedriverVersion: 123.0.6312.122 (31f8248cdd9..., userDataDir: /var/folders/d_/1vb4t0fs7y1...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64581}, networkConnectionEnabled: false, pageLoadStrategy: none, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:64581/devtoo..., se:cdpVersion: 123.0.6312.107, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 7217ef11d3daa722b8d39982beafd58d
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:396)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:352)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:187)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:591)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:312)
```

### Operating System

Mac Sonoma

### Selenium version

Java 4.19.1

### What are the browser(s) and version(s) where you see this issue?

chrome 123

### What are the browser driver(s) and version(s) where you see this issue?

latest chromedriver through Selenium

**Comment by thp2016** [comment]
I can't tell which test is related to my ticket from that link.
https://wpt.fyi/results/webdriver/tests?label=experimental&label=master&aligned
