### ISSUE TITLE
[🐛 Bug]: Selenium 4.4.0 | Chrome123.0.6312.106 | JDK 17|Timed out waiting for driver server to stop

### ISSUE THREAD

**Issue by Vikas6206** [SeleniumHQ/selenium#13832]
### What happened?

I am doing a loop over an element (pagination icon) if its displayed perform clique operation and then once the element is not displayed then an exception will be thrown. I am handling exception via Exception. With the exception I am fetching some other element values from the UI and finally returning the value.

### How can we reproduce the issue?

```shell
Ex:- For calendar element I can navigate to next month or previous month . However, after navigating in any one direction multiple time the navigator icon will disappear leading to exception.  I am capturing the last month and year value from the calendar.

Sample code:- 

`try{
            while(pageNavigator.isDisplayed()){
                pageNavigator.click();
                visibilityHelper.waitFor(500);
            }

        }catch (Exception exception){
            monthYear = hook.getDriver().findElement(By.xpath("//div[@class='abc']")).getText();
        }
return monthYear;
` 

After the operation the driver is not closed. Getting the exception stating the driver is not closed.
```

### Relevant log output

```shell
org.openqa.selenium.WebDriverException: Timed out waiting for driver server to stop.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'xxxx', ip: 'xxxxx', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [0abcf96c3c3e086b83e8a08dab07d104, quit {}]
 at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:132)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:606)
 at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:443)
 at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:280)
......
Caused by: java.util.concurrent.ExecutionException: org.openqa.selenium.TimeoutException: Process timed out after waiting for 20000 ms.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'xxxxxx', ip: 'xxxxxxxx', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: unknown
 at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
 at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
 at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:128)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:606)
 at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:443)
 at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:280)
.....
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
 at io.cucumber.java.Invoker.invoke(Invoker.java:24)
 at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
 at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:64)
 at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46)
 at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
 at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
 at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
 at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
 at io.cucumber.core.runner.TestCase.run(TestCase.java:90)
 at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
 at io.cucumber.junit.PickleRunners$NoStepDescriptions.lambda$run$0(PickleRunners.java:151)
 at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
 at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
 at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
 at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:148)
 at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144)
 at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28)
 at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 at io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137)
 at io.cucumber.junit.Cucumber.runChild(Cucumber.java:196)
 at io.cucumber.junit.Cucumber.runChild(Cucumber.java:89)
 at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 at io.cucumber.junit.Cucumber$RunBeforeAllHooks.evaluate(Cucumber.java:266)
 at io.cucumber.junit.Cucumber$RunAfterAllHooks.evaluate(Cucumber.java:281)
 at io.cucumber.junit.Cucumber$StartTestRun.evaluate(Cucumber.java:233)
 at io.cucumber.junit.Cucumber$FinishTestRun.evaluate(Cucumber.java:248)
 at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
 at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
 at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
 at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
 at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
 at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
 at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.openqa.selenium.TimeoutException: Process timed out after waiting for 20000 ms.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'xxxxxx', ip: 'xxxxxxx1', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: unknown
 at org.openqa.selenium.os.OsProcess.waitFor(OsProcess.java:174)
 at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:114)
 at org.openqa.selenium.remote.service.DriverCommandExecutor.lambda$execute$2(DriverCommandExecutor.java:122)
 at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.lang.Thread.run(Thread.java:833)


org.openqa.selenium.WebDriverException: Timed out waiting for driver server to stop.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'xxxxxxx', ip: 'xxxxxxx', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [0abcf96c3c3e086b83e8a08dab07d104, quit {}]
Session ID: 0abcf96c3c3e086b83e8a08dab07d104

 at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:132)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:606)
 at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:443)
 at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:280)
......
Caused by: java.util.concurrent.ExecutionException: org.openqa.selenium.TimeoutException: Process timed out after waiting for 20000 ms.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'xxxxxxx', ip: 'xxxxxxxx', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: unknown
 at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
 at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
 at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:128)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:606)
 at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:443)
 at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:280)
......
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
 at io.cucumber.java.Invoker.invoke(Invoker.java:24)
 at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
 at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:64)
 at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46)
 at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
 at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
 at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:85)
 at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
 at io.cucumber.core.runner.TestCase.run(TestCase.java:90)
 at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
 at io.cucumber.junit.PickleRunners$NoStepDescriptions.lambda$run$0(PickleRunners.java:151)
 at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)
 at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
 at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)
 at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:148)
 at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144)
 at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28)
 at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 at io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137)
 at io.cucumber.junit.Cucumber.runChild(Cucumber.java:196)
 at io.cucumber.junit.Cucumber.runChild(Cucumber.java:89)
 at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 at io.cucumber.junit.Cucumber$RunBeforeAllHooks.evaluate(Cucumber.java:266)
 at io.cucumber.junit.Cucumber$RunAfterAllHooks.evaluate(Cucumber.java:281)
 at io.cucumber.junit.Cucumber$StartTestRun.evaluate(Cucumber.java:233)
 at io.cucumber.junit.Cucumber$FinishTestRun.evaluate(Cucumber.java:248)
 at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
 at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
 at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
 at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
 at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
 at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
 at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.openqa.selenium.TimeoutException: Process timed out after waiting for 20000 ms.
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'xxxxxx', ip: 'xxxxxxxx', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: unknown
 at org.openqa.selenium.os.OsProcess.waitFor(OsProcess.java:174)
 at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:114)
 at org.openqa.selenium.remote.service.DriverCommandExecutor.lambda$execute$2(DriverCommandExecutor.java:122)
 at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.lang.Thread.run(Thread.java:833)
```

### Operating System

Windows 11

### Selenium version

4.4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome - 123.0.6312.106

### What are the browser driver(s) and version(s) where you see this issue?

WebDriver Version - 5.6.4

**Comment by diemol** [comment]
Several things have changed between the version you are using and the latest one. Please upgrade and let us know the result.

**Comment by diemol** [comment]
I will close this because we didn't get any more information.
