### ISSUE TITLE
[🐛 Bug]: Driver info: driver.version: unknown

### ISSUE THREAD

**Issue by JJena** [SeleniumHQ/selenium#13848]
### What happened?

I'm using Jmeter WebDriverSampler to run a Selenium Test using Chrome Driver. On Local (mac m1) using Jmeter gui I'm able to run the webdriver sampler test. Then I created a docker image to run the same test inside the container. The image contains all required components i.e. jmeter, jmeter-webdriver-sampler plugin, java, chromedriver, chrome binary etc. When I start the test, it gives below Warning:

```
Creating summariser <summary>
Created the tree successfully using Test.jmx
Starting standalone test @ 2024 Apr 20 14:40:47 BST (1713620447744)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
This command is not for general use and should only be run as the result of a call to
ProcessBuilder.start() or Runtime.exec() in a java application 
```

Jmeter Log:

```
2024-04-20 14:40:49,267 INFO o.a.j.t.JMeterThread: Thread started: Thread Group - Test 1-1
2024-04-20 14:41:09,485 ERROR o.a.j.t.JMeterThread: Error calling threadStarted
org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start.
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.7.9-200.fc39.aarch64', java.version: '17.0.9'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:209) ~[selenium-remote-driver-4.13.0.jar:?]
        at com.googlecode.jmeter.plugins.webdriver.config.ChromeDriverConfig.getThreadService(ChromeDriverConfig.java:47) ~[jmeter-plugins-webdriver-4.13.0.0.jar:?]
```

### How can we reproduce the issue?

```shell
- Setup Apache Jmeter 5.6.2

- Install webdriver sampler plugin

- Create a simple script using WebDriver Sampler and Chrome Driver Config (https://github.com/undera/jmeter-plugins-webdriver)

- Once the script works fine on local, use this docker image to run the jmeter script. https://hub.docker.com/r/justb4/jmeter and https://github.com/justb4/docker-jmeter

- To run the script with docker, download the jmeter-plugins-webdriver, chromedriver and anything else you may have used in your jmx to your local. Extract all jars to a path which can then be mounted to the container.

Sample command: docker run --name jmeter -i -v $PWD/jars:/plugins -v $PWD/jmxfiles:/opt -v $PWD/chromedriver:/opt newjmeter:latest -n -t /opt/Test.jmx
```

### Relevant log output

```shell
2024-04-20 14:40:49,267 INFO o.a.j.t.JMeterThread: Thread started: Thread Group - Test 1-1
2024-04-20 14:41:09,485 ERROR o.a.j.t.JMeterThread: Error calling threadStarted
org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start.
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.7.9-200.fc39.aarch64', java.version: '17.0.9'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:209) ~[selenium-remote-driver-4.13.0.jar:?]
        at com.googlecode.jmeter.plugins.webdriver.config.ChromeDriverConfig.getThreadService(ChromeDriverConfig.java:47) ~[jmeter-plugins-webdriver-4.13.0.0.jar:?]
```
```


### Operating System

alpine

### Selenium version

4.13

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment]
I'm not sure how we can help with the little actionable information you are providing.

My only guess would be that the docker image has a x86 architecture and you are trying to run the container in an M1 (ARM).

To rule that out, use a compatible image with your host machine architecture (check the docker seleniarm project) or try your docker container on a host with x86 architecture. 

Given that we provide tested docker images with Selenium and browser images (docker selenium and docker seleniarm), we don't troubleshoot docker images that we don't.

Please check the options we suggest, and if you find a specific error related to Selenium, please create a new issue with a deterministic way of reproducing it (no narrative but instead code we can run to reproduce the problem).
