### ISSUE TITLE
[🐛 Bug]: Unable to start BiDi session via grid

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#13852]
### What happened?

Looks like the BiDi spec changed the flag to start the session:

https://w3c.github.io/webdriver-bidi/#establishing

### How can we reproduce the issue?

```shell
Try to start a BiDi session with:

options.setCapability("bidi", true);
```

### Relevant log output

```shell
[DEBUG]   00:00:03 EXCEPTION: Illegal key values seen in w3c capabilities: [bidi]
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Build info: version: '4.19.1', revision: 'abe0ee07dc'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.16.1'
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: false, bidi: true, browserName: chrome, goog:chromeOptions: ...
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:536)
	at ...
Caused by: java.lang.IllegalArgumentException: Illegal key values seen in w3c capabilities: [bidi]
	at org.openqa.selenium.remote.NewSessionPayload.lambda$validate$5(NewSessionPayload.java:163)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.remote.NewSessionPayload.validate(NewSessionPayload.java:167)
	at org.openqa.selenium.remote.NewSessionPayload.<init>(NewSessionPayload.java:70)
	at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:99)
	at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:60)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	... 24 more
```

### Operating System

Win 10 x64

### Selenium version

4.19.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 124

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 124

### Are you using Selenium Grid?

4.19.1

**Comment by joerg1985** [comment]
@pujagani it would be great if this could be fixed with `4.20.0`

**Comment by diemol** [comment]
I am not following, where does it say that a user needs to send "bidi: true", now?

**Comment by joerg1985** [comment]
@diemol sorry i did fail reading the spec.

But for what ever reason i get "se:bidiEnabled: false" from the chromedriver since v124 with "webSocketUrl=true" set.

**Comment by diemol** [comment]
`se:bidiEnabled` is added by the Grid.

**Comment by joerg1985** [comment]
@diemol something is broken, a ChromeDriver has webSocketUrl set and a RemoteWebDriver does not

```
        System.setProperty(
                "webdriver.chrome.driver", 
                "..\\chromedriver.exe"
        );
        org.openqa.selenium.grid.Bootstrap.main("standalone --host 127.0.0.1 --port 4567".split(" "));
        
        ChromeOptions opts = new ChromeOptions();
        opts.setCapability("webSocketUrl", true);
        ChromeDriver driver = new ChromeDriver(opts);
        driver.getBiDi();
        System.out.println("caps: " + ((HasCapabilities) driver).getCapabilities());
        
        WebDriver driver2 = new RemoteWebDriver(new URL("http://localhost:4567"), opts);
        driver2 = new Augmenter().augment(driver2);
        System.out.println("caps2: " + ((HasCapabilities) driver2).getCapabilities());
        ((HasBiDi) driver2).getBiDi(); // <<--- ClassCastException

```

```
    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.19.1</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-grid</artifactId>
            <version>4.19.1</version>
        </dependency>
    </dependencies>
```

**Comment by joerg1985** [comment]
`ChromeDriverInfo.isSupportingBiDi` did return false, this has already been fixed in https://github.com/SeleniumHQ/selenium/commit/aaa7e791a4b6be6314250966a4538cd594576254
