### ISSUE TITLE
[🐛 Bug]: Docker Unable to obtain driver for chrome using Selenium Manager

### ISSUE THREAD

**Issue by brendonzimmer** [SeleniumHQ/selenium#13874]
### What happened?

I can't run chrome in my simple docker container. I have a simple dockerfile and a bare python file. Seems like for some reason selenium can't get a driver although docs say this version it should get it itself.

### How can we reproduce the issue?

```shell
### docker-compose.yaml ###

services:
  messenger:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:ro
    command: ["python3", "-m", "mypythonmodule.main"]

### Dockerfile ###

FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

### main.py ###

from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument("--headless=new")
driver = webdriver.Chrome(options=options)

### command ###
docker-compose -p myproject up --build
```

### Relevant log output

```shell
Traceback (most recent call last):
messenger-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
messenger-1  |     path = SeleniumManager().driver_location(options) if path is None else path
messenger-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
messenger-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 89, in driver_location
messenger-1  |     args = [str(self.get_binary()), "--browser", browser]
messenger-1  |                 ^^^^^^^^^^^^^^^^^
messenger-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 63, in get_binary
messenger-1  |     raise WebDriverException(f"Unsupported platform/architecture combination: {sys.platform}/{arch}")
messenger-1  | selenium.common.exceptions.WebDriverException: Message: Unsupported platform/architecture combination: linux/aarch64
messenger-1  | 
messenger-1  | 
messenger-1  | The above exception was the direct cause of the following exception:
messenger-1  | 
messenger-1  | Traceback (most recent call last):
messenger-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
messenger-1  |   File "<frozen runpy>", line 88, in _run_code
messenger-1  |   File "/app/mypythonmodule/main.py", line 9, in <module>
messenger-1  |     driver = webdriver.Chrome(options=options)
messenger-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
messenger-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
messenger-1  |     super().__init__(
messenger-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
messenger-1  |     self.service.path = DriverFinder.get_path(self.service, options)
messenger-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
messenger-1  |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
messenger-1  |     raise NoSuchDriverException(msg) from err
messenger-1  | selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

M1 macOS running docker image python:3.11-slim

### Selenium version

Python3.11 selenium 4.19.0

### What are the browser(s) and version(s) where you see this issue?

Tested for chrome

### What are the browser driver(s) and version(s) where you see this issue?

Unknown

### Are you using Selenium Grid?

No

**Comment by Pepan** [comment]
similar problem in  **Ruby OnRails 7.1.3.2**
in method `ActionDispatch::SystemTesting::Browser#resolve_driver_path` 

_ruby/gems/actionpack-7.1.3.2/lib/action_dispatch/system_testing/browser.rb_
```
def resolve_driver_path(namespace)
    namespace::Service.driver_path = ::Selenium::WebDriver::DriverFinder.path(options, namespace::Service)
end
```

`undefined method path for Selenium::WebDriver::DriverFinder:Class`

**Comment by diemol** [comment]
@Pepan, it is not the same issue. @brendonzimmer is using Python.

**Comment by diemol** [comment]
@brendonzimmer, The problem arises because you use an ARM Linux "machine." Selenium Manager tries to find ChromeDriver and Chrome for ARM on Linux, but they do not exist. Google does not have an official binary that supports that architecture. Hence, Selenium Manager says, `Message: Unsupported platform/architecture combination: linux/aarch64`.

You can check https://github.com/seleniumhq-community/docker-seleniarm/, and find ideas how to implement it yourself, or extend those images.

**Comment by diemol** [comment]
https://www.selenium.dev/documentation/selenium_manager/#alternative-architectures

**Comment by zatte123** [comment]
What was the fix?
