### ISSUE TITLE
[🐛 Bug]: SessionNotCreatedException: Could not start a new session. Response code 400

### ISSUE THREAD

**Issue by Airat102vb** [SeleniumHQ/selenium#13894]
### What happened?

Hello, I try to figure out with SessionNotCreatedException: Could not start a new session. Response code 400; when starting firefox session.

Some notes
It's seems as versions of driver and browser is appropriated
No problem with google browser
I've noticed that in /usr/bin for firfox is  biniry
```
file /usr/bin/firefox
/usr/bin/firefox: POSIX shell script, ASCII text executable
```
while for chrome it'is simlinck.

Should either I manually create simlink for firefox
Can I get some advises?

### How can we reproduce the issue?

```shell
OS Ubuntu 22.04.4 LTS

lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
```

the simplest code 
```
`package org.example;

import com.titusfortner.logging.SeleniumLogger;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Main {
  public static void main(String[] args) {
    SeleniumLogger.enable();
    WebDriver driver = new FirefoxDriver();
    driver.get("https://google.com");
    driver.quit();
  }
}`
```
```


### Relevant log output

```shell
`2024-05-01 12:00:32 FINE Selenium [SeleniumManager getBinary] Selenium Manager binary found at: /home/contributor/.cache/selenium/manager/0.4.20/selenium-manager 
2024-05-01 12:00:32 FINE Selenium [SeleniumManager runCommand] Executing Process: [--browser, firefox, --language-binding, java, --output, json, --debug] 
2024-05-01 12:00:32 FINE Selenium [ExternalProcess] completed to copy the output of process 17999 
2024-05-01 12:00:33 FINE Selenium [SeleniumManager] Found geckodriver 0.34.0 in PATH: /snap/bin/geckodriver 
2024-05-01 12:00:33 FINE Selenium [SeleniumManager] firefox detected at /usr/bin/firefox 
2024-05-01 12:00:33 FINE Selenium [SeleniumManager] Running command: /usr/bin/firefox -v 
2024-05-01 12:00:33 FINE Selenium [SeleniumManager] Output: "Mozilla Firefox 125.0.3" 
2024-05-01 12:00:33 FINE Selenium [SeleniumManager] Detected browser: firefox 125.0.3 
2024-05-01 12:00:33 FINE Selenium [SeleniumManager] Required driver: geckodriver 0.34.0 
2024-05-01 12:00:33 FINE Selenium [SeleniumManager] Driver path: /snap/bin/geckodriver 
2024-05-01 12:00:33 FINE Selenium [SeleniumManager] Browser path: /usr/bin/firefox 
2024-05-01 12:00:33 FINE Selenium [RemoteWebDriver] Executing: newSession [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {binary: /usr/bin/firefox}}]}] 
2024-05-01 12:00:33 FINE Selenium [DriverService start] Starting driver at /snap/bin/geckodriver with [--port=27929, --websocket-port=28789, --allow-origins, http://127.0.0.1:28789, http://localhost:28789, http://[::1]:28789] 
2024-05-01 12:00:33 FINE Selenium [JdkHttpClient execute0] Executing request: (POST) /session 
2024-05-01 12:00:33 FINE Selenium [JdkHttpClient execute0] Ending request (POST) /session in 65ms 
2024-05-01 12:00:33 FINE Selenium [ExternalProcess] completed to copy the output of process 18244 
2024-05-01 12:00:33 FINE Selenium [RemoteWebDriver] Exception: newSession Could not start a new session. Response code 400. Message: binary is not a Firefox executable 
Host info: host: 'airat-ThinkPad-E14-Gen-2', ip: '127.0.1.1'
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-28-generic', java.version: '17.0.10'
Driver info: driver.version: FirefoxDriver 
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: binary is not a Firefox executable 
Host info: host: 'airat-ThinkPad-E14-Gen-2', ip: '127.0.1.1'
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-28-generic', java.version: '17.0.10'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {binary: /usr/bin/firefox}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:114)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:232)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:155)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:150)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:132)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:102)
	at org.example.Main.main(Main.java:10)

Process finished with exit code 1`
```

### Operating System

OS Ubuntu 22.04.4 LTS

### Selenium version

4.20.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 125.0.3 (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.34.0

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
It seems you are using `snap` to manage `geckodriver`, either delete it and let Selenium Manager handle the driver or manually set the [driver/browser binary location](https://www.selenium.dev/documentation/selenium_manager/#custom-package-managers).
