### ISSUE TITLE
Error: ECONNREFUSED connect ECONNREFUSED 10.10.36.60:4444 on a Linux machine

### ISSUE THREAD

**Issue by debbiesrain** [SeleniumHQ/selenium#1402]
I have a selenium server setup in a Red Hat Enterprise Linux 7 Linux machine using the command line:

java -jar selenium-server-standalone-2.48.2.jar -role node -hub http://10.10.36.60:4444/grid/register -port 4444 -browser browserName="firefox" &

Then in my driver Builder, i set the server address to use this:
        $browser = new $driver.Builder().usingServer('http://10.10.36.60:4444/wd/hub')

The server starts up fine. However, i get a connection error when running my nodejs tests:

Error: ECONNREFUSED connect ECONNREFUSED 10.10.36.60:4444
[08:13:27][npm test]       at ClientRequest.<anonymous> (/home/teamcity/buildagent2/buildAgent-BUILD_32407/work/e86740b8fd19f8ce/node_modules/selenium-webdriver/http/index.js:174:16)
[08:13:27][npm test]       at Socket.socketErrorListener (_http_client.js:259:9)
[08:13:27][npm test]       at emitErrorNT (net.js:1253:8)
[08:13:27][npm test]   From: Task: WebDriver.createSession()

Can somebody please help me with this? I would appreciate it. Thanks

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

This seems to be related to network (mis)configuration.
