### ISSUE TITLE
[🐛 Bug]: Incorrect handling of child process in Ruby 3.3.1

### ISSUE THREAD

**Issue by Sergeykot** [SeleniumHQ/selenium#14032]
### What happened?

I am using Selenium WebDriver with Ruby 3.3.1 and `teaspoon`. The test suite runs successfully however there seems to be an issue with process handling: it does fail with `No child processes (Errno::ECHILD)`

It was possible to fix the error by patching `Selenium::WebDriver::ChildProcess#exited?` in the following way:

```
module Selenium
  module WebDriver
    class ChildProcess
      def exited?
        return false unless @pid
        WebDriver.logger.debug("Checking if #{@pid} is exited:", id: :process)
        begin
          _, @status = Process.waitpid2(@pid, Process::WNOHANG | Process::WUNTRACED) if @status.nil?
        rescue Errno::ECHILD
          # do nothing, already killed
          return true
        end

        return false if @status.nil?

        exit_code = @status.exitstatus || @status.termsig
        WebDriver.logger.debug("  -> exit code is #{exit_code.inspect}", id: :process)

        !!exit_code
      end
    end # ChildProcess
  end # WebDriver
end # Selenium

```

### How can we reproduce the issue?

```shell
Run `rake teaspoon` with Ruby 3.3.1, `selenium-webdriver (4.21.1)`, `teaspoon (1.4.0)`
```

### Relevant log output

```
rake aborted!
Errno::ECHILD: No child processes (Errno::ECHILD)
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `waitpid2'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `exited?'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:125:in `process_exited?'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:108:in `stop_process'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:71:in `ensure in stop'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:71:in `stop'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/driver.rb:175:in `quit'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/driver/selenium.rb:40:in `run_specs'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:56:in `run_specs'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:45:in `block in execute_without_handling'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `each'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `inject'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `execute_without_handling'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:28:in `execute'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:24:in `failures?'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/tasks/teaspoon.rake:14:in `block in <main>'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
$HOMEDIR/$CODEDIR//lib/tasks/teaspoon.rake:6:in `block (3 levels) in <main>'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/headless-2.3.1/lib/headless.rb:143:in `run'
$HOMEDIR/$CODEDIR//lib/tasks/teaspoon.rake:5:in `block (2 levels) in <main>'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'

Caused by:
Errno::ECHILD: No child processes (Errno::ECHILD)
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `waitpid2'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `exited?'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:100:in `poll_for_exit'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:67:in `stop'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/driver.rb:175:in `quit'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/driver/selenium.rb:40:in `run_specs'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:56:in `run_specs'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:45:in `block in execute_without_handling'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `each'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `inject'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `execute_without_handling'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:28:in `execute'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:24:in `failures?'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/tasks/teaspoon.rake:14:in `block in <main>'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
$HOMEDIR/$CODEDIR//lib/tasks/teaspoon.rake:6:in `block (3 levels) in <main>'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/headless-2.3.1/lib/headless.rb:143:in `run'
$HOMEDIR/$CODEDIR//lib/tasks/teaspoon.rake:5:in `block (2 levels) in <main>'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
Tasks: TOP => teaspoon
(See full trace by running task with --trace)
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `waitpid2': No child processes (Errno::ECHILD)
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `exited?'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:125:in `process_exited?'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:108:in `stop_process'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:71:in `ensure in stop'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:71:in `stop'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:53:in `block in start'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/platform.rb:152:in `block in exit_hook'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `waitpid2': No child processes (Errno::ECHILD)
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `exited?'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:125:in `process_exited?'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:64:in `stop'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:53:in `block in start'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/platform.rb:152:in `block in exit_hook'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:230:in `exit': exit (SystemExit)
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:230:in `exit_because_of_exception'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:224:in `rescue in standard_exception_handling'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:213:in `standard_exception_handling'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
        from bin/rake:9:in `<main>'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `waitpid2': No child processes (Errno::ECHILD)
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `exited?'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:125:in `process_exited?'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:108:in `stop_process'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:71:in `ensure in stop'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:71:in `stop'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/driver.rb:175:in `quit'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/driver/selenium.rb:40:in `run_specs'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:56:in `run_specs'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:45:in `block in execute_without_handling'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `each'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `inject'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `execute_without_handling'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:28:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:24:in `failures?'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/tasks/teaspoon.rake:14:in `block in <main>'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
        from $HOMEDIR/$CODEDIR//lib/tasks/teaspoon.rake:6:in `block (3 levels) in <main>'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/headless-2.3.1/lib/headless.rb:143:in `run'
        from $HOMEDIR/$CODEDIR//lib/tasks/teaspoon.rake:5:in `block (2 levels) in <main>'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:83:in `block in run'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
        from bin/rake:9:in `<main>'
$HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `waitpid2': No child processes (Errno::ECHILD)
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:86:in `exited?'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/child_process.rb:100:in `poll_for_exit'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/service_manager.rb:67:in `stop'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/selenium-webdriver-4.21.1/lib/selenium/webdriver/common/driver.rb:175:in `quit'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/driver/selenium.rb:40:in `run_specs'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:56:in `run_specs'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:45:in `block in execute_without_handling'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `each'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `inject'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:43:in `execute_without_handling'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:28:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/teaspoon/console.rb:24:in `failures?'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/teaspoon-1.4.0/lib/tasks/teaspoon.rake:14:in `block in <main>'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
        from $HOMEDIR/$CODEDIR//lib/tasks/teaspoon.rake:6:in `block (3 levels) in <main>'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/headless-2.3.1/lib/headless.rb:143:in `run'
        from $HOMEDIR/$CODEDIR//lib/tasks/teaspoon.rake:5:in `block (2 levels) in <main>'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:83:in `block in run'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
        from $HOMEDIR/.rvm/gems/ruby-3.3.1/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'

```

### Operating System

OpenSUSE

### Selenium version

Ruby 3.3.1

### What are the browser(s) and version(s) where you see this issue?

headless/

### What are the browser driver(s) and version(s) where you see this issue?

n/a

**Comment by titusfortner** [comment]
@p0deje can you look at this one?

**Comment by p0deje** [comment]
Thank you for the report, will be fixed in the next release.
