### ISSUE TITLE
[🐛 Bug]:  org.openqa.selenium.devtools.DevToolsException continuously rendering in console after I have switch to new tab/window and close old tab/window 

### ISSUE THREAD

**Issue by jaydjana87** [SeleniumHQ/selenium#14061]
### What happened?

I have open new tab in chrome browser then close old tab . AFter that I am continously getting DevToolsException in console and my console is getting stuck 

### How can we reproduce the issue?

```shell
// Get the original window handle
		String originalWindow = driver.getWindowHandle();

		// Open a new window using JavaScript
		((JavascriptExecutor) driver).executeScript("window.open()");

		// Get all window handles
		Set<String> allWindows = driver.getWindowHandles();

		// Switch to the new window
		for (String windowHandle : allWindows) {
			if (!windowHandle.equals(originalWindow)) {
				driver.switchTo().window(windowHandle);
				break;
			}
		}

		// Navigate to a new URL in the new window
//			driver.get(properties.getProperty("url"));
//			String title = driver.getTitle();
//			System.out.println("New window title: " + title);

		// Close the original window
		driver.switchTo().window(originalWindow);
		driver.close();

		// Optionally, switch back to the new window if further actions are needed
		for (String windowHandle : allWindows) {
			if (!windowHandle.equals(originalWindow)) {
				driver.switchTo().window(windowHandle);
				break;
			}

		}
		driver.get(properties.getProperty("url"));
```

### Relevant log output

```shell
WARNING: Unable to process: {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-330.0","request":{"url":"https://guardian-sit2.crm9.dynamics.com/api/data/v9.0/GetClientMetadata(ClientMetadataQuery=@ClientMetadataQuery)?@ClientMetadataQuery={%22MetadataType%22%3A%22entity%22,%22MetadataSubtype%22%3A%22{\\%22systemuser\\%22:[]}%22,%22GetDefault%22%3Afalse,%22ChangedAfter%22%3A%22228329132%22}&umv=228329132&mv=228713547&rde=1&api-version=9.1","method":"GET","headers":{"Cookie":"ARRAffinity=dac938fcdeaf10ca75bf0122af2e62e128beb82c714d9a08173f2d13cce5ea315ab954b42cfa12ad9f33ddc80a07e15dd633bd57139a65479392e46e5242529408DC81EEDAB53D151166036094; ReqClientId=b4c09539-bd36-4586-8d9b-d8aa9fa826aa; CrmOwinAuth=MAAAANkNU34XERHvn4UAHdgGAy0jChXcMF3SSC47F9-Ra1jV-9FcAjObIrrIbojdAm6UNh-LCAAAAAAABADFWGuPo8gV7d6enZkdaVeJVpov0UojpT9ESXBTvBlllIDx2wYbsGn4gngUD2Me5m1-QH5Kfmdw9_RuZhQpm3FnUrJLuLh1z6m6t44v3FxdXf0gNWEyTNMohFxVBtdX11e3_fCNVbm36GOjkXP_2DlPV0_t-upDUJZZ8f7uriiLQe_MTZtikMDyjiAhTmEUi2AW5SAEcBzEcjyAYC6NM5iDQg_Cu-urm7AoLvVxOQerfANoQGMAA4D949ld761pmkGDD9Lcv8NQFNzdr5aKE8DY-n2YlNCHOUVcjJzY3v8JGbbZR2QK_arILyzHKa_RX42IY5civv8IVTz4LQZx6ORpkXrlwEnjO-dghXFxZ_X5n8SwDFK3yPuJOUwcWNw0oXV5gn13dm6WYQyfgk0A5ituwEvHDKwieJth6wUvz_kZlyT4iJ2JUC1N__L1ffhsg9v4UKRW9rCmpjgvi7zrP6ELkzIsT09bXlR5YsXw2xm_2nCXs_jrl7HwwxomZx7fAOZyEq_CxHTSPHtR5hW83N3LMLNcN_8BkOyAoQcAoAOAU5f7fXNI_Z5p0KfY36-lwTDcdKLqnERsBCQFJQxBDJaqHImTWSmp21ZXUGAIu1hUxwd973T6XlfmwgYY6gpb7XVyqc4DMV6VojDe6ycQ6Jje9mOR2K2IVbxqDM04GHIqK9u5uN2OWmnE81okC9sTOVWB7qv-hw-XL-rFOYqvHrLpOUL5eVZ_Khufp1Fq76FTPo56IcxvcZLGaItkEcbFLYRwCRthSWAhpEt6JIA2jdvPEcg0yXIYm0XoIgoCEBLBAIL3JgSFkyiJsASLMxTKMghOMSyDMRRAGJKm8WfY7qwK3d8AFMX7o4XxKIMDavQM5_ibPKDQAXfvc5a23Mtac-xGk4JRQOcXQk37DvfUmp-veIIbjgaXYwtfpiHnxPsl9H9SbF-1Tl1YudN61eqIcxqNVogwY6FkkPOQlxf7o7zXN2weXU75xxImVlKaOfTDNDELJ83gN-IzxIH8r_L_kUXo3v4a75eTu7767ceD_jfOEIbKYCLtLvfKfln4qyz5X7C5qcrwbTI3vO54oHwUiRZlVZGkMeGeIbo3NcxvwOAZSvgXTegWtzbNerZHuAgOPRYherFBGEDgCE3ZgCUgQ5IoeznW6zYuzDhzwpcYyfbh-IpF1KszdI_8Aqe-Ku7DkpsiLF8A5qsCv037SQMnjwfn8rVMoz7pTxn8XspgMnOHaZL0f3jnk9gXuD1H95SYefmP118m3ZzP8Vwz6n8LiZcegnmmJLLOA2W3R6a-y3C-0O_ClmPXSAy4ABFITWLWkEJ3-7AS71OLhCnbTG28Q2t0Ku3FHdNmO0Xah6a1Hcr1rkVIkmeOk6OmIdkBr_OZZXYs7UKemE7oE7YbO8Je0lrJobepznk-utYPsBuuFwoI1uZqbFsrY0ZV05YezVHJqQlH4uTkqOD53t3S4ez-vtU3yHGvNhhTLu0lo5RgNTIYEVOndBd75FirNFcXNM-g_ZiHqKe7bjDh44263dSFG8dtxuYeB32D38cLYs1P7GG-zrr5dK9HXKcsO2WByc00d-vDvDuIslzbMEKSMIt8MmCSiBxSTNI2FLvxY0HuksA_djG5lKmUnfkqyW7d2kFHWDkf28I8o-bbHSrOZ4yCrZe1XJYcvXaWTEqK7Cw4HdRqMefRYr60U41rj8v8Hsojyl3Th8Twpmy8ay2awmCILcsZSUqaMx7FdBG7I2xhnUKlUxqyXe8A0peLZO2OxhK9xBY7oZN1BZxKmpr7CO0eBc5nO7LsKCRaHRmTiISprkJMWzSh5-gRNqk21f1M1uO1661CAVl3KWVI6m4ScKRdL-md3fmpvlhwc34qAjOGI6PSlWhP5elGFHO_MrbHdtLurZNEJwqSmF7aZRjVHgNlj5MHZczi5VqUtwIhl5Nxp42HBZQaWXAsexEvjw1j2o4PyoMVtNNg7u74UBOOI4EorbG35WcNt4mmmelgB3Gi0vqh9R1XiNRSDA5RSwXdxgiwtaNhuT9ZxW5ab6a0AvFqPK93njsxt8chUQ9h4IoGe5L8Q7Azop0FhMUJsSFcMoixaVyg0phSBz6juCKlNYEalyYdUYFEbpeoM1yDEyt307rBaVrrVHwMHeEwkpcsmu78PSdqoV0J44pPbc8OZvkprK3KvFek4hQpnB-wNZwVp0XnBw1GjY7VtJnPTDEKMT3anWDTPwbPlXoXavwxvccbnqxVY3rMOXxVkIpp6vF0SU2UTGiksS-ByVpb8gpf6F3l57OMTGqOBvJIm1qIgfOdltsopfNHdIIaj7rx5qNu-PnPL2AIDP303uHf3LtpyfJ3S7DwFuOZuU_u7UZzMKw12gYU2-n0ySoK3f9sdW7n_tv--90gh26Y97r2hyfx9Csrd0MrQXoFxs5qyA56VlZfDBUPddD3gwIWRV95KaVVwluUpizMISCCEw5ECBL3EAY6HmK7nkcTngdQD_tx0Cu1EymP82bjvK8e__KE9_Bg9kutlSaHMIGPLyrSOE6Tu_Ssxtjdg4uP0K8HsM162sVPalD9-R0K3s2r5B2G4sQ7FH-P0e9R9N1kpb4ahEVRQfcnxSr_xQr71OqfCk27jhgUAAA; orgId=37bed117-9bc5-ed11-aed1-001dd804f3a9","Referer":"https://guardian-sit2.crm9.dynamics.com/main.aspx?forceUCI=1&pagetype=apps","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36","accept":"application/json","clienthost":"Browser","content-type":"application/json","prefer":"odata.include-annotations=\"*\"","sec-ch-ua":"\"Google Chrome\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","x-ms-app-id":"","x-ms-app-name":"__ unavailable__","x-ms-client-request-id":"f1ce2045-bbae-4333-8fdf-c49e89967885","x-ms-client-session-id":"3b2bcc39-f294-45ad-aa82-cdb071cd851a","x-ms-correlation-id":"ff413b01-37bb-4b2b-8c45-033f048eb485","x-ms-gcm-object":"true","x-ms-metadatareductionlevel":"5","x-ms-sw-objectid":"35727a59-8d3a-4d4b-951a-5d5f51eb73b6","x-ms-sw-tenantid":"45e36269-2a6c-41cc-acf1-2d7382c0efee","x-ms-user-agent":"PowerApps-UCI/1.4.8639-2404.3 (Browser; AppName=__ unavailable__)"},"initialPriority":"High","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"E93EBE2D6444B31A2178652D8F5F71E0","resourceType":"XHR"},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
org.openqa.selenium.devtools.DevToolsException: {"id":632,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:193)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:89)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$5(Network.java:258)
	at org.openqa.selenium.devtools.Connection.lambda$handle$5(Connection.java:345)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:308)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:236)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.openqa.selenium.WebDriverException: {"id":632,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:272)
	... 4 more

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: {"id":632,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.openqa.selenium.devtools.DevToolsException: {"id":632,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:193)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:89)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$5(Network.java:258)
	at org.openqa.selenium.devtools.Connection.lambda$handle$5(Connection.java:345)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:308)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:236)
	... 3 more
Caused by: org.openqa.selenium.WebDriverException: {"id":632,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:272)
	... 4 more
Jun 01, 2024 8:57:17 AM org.openqa.selenium.devtools.Connection$Listener lambda$onText$0
WARNING: Unable to process: {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-329.0","request":{"url":"https://guardian-sit2.crm9.dynamics.com/api/data/v9.0/GetClientMetadata(ClientMetadataQuery=@ClientMetadataQuery)?@ClientMetadataQuery={%22MetadataType%22%3A%22entity%22,%22MetadataSubtype%22%3A%22{\\%22systemuser\\%22:[],\\%22team\\%22:[]}%22,%22GetDefault%22%3Afalse,%22ChangedAfter%22%3A%22228329132%22}&umv=228329132&mv=228713547&rde=1&api-version=9.1","method":"GET","headers":{"Cookie":"ARRAffinity=dac938fcdeaf10ca75bf0122af2e62e128beb82c714d9a08173f2d13cce5ea315ab954b42cfa12ad9f33ddc80a07e15dd633bd57139a65479392e46e5242529408DC81EEDAB53D151166036094; ReqClientId=b4c09539-bd36-4586-8d9b-d8aa9fa826aa; CrmOwinAuth=MAAAANkNU34XERHvn4UAHdgGAy0jChXcMF3SSC47F9-Ra1jV-9FcAjObIrrIbojdAm6UNh-LCAAAAAAABADFWGuPo8gV7d6enZkdaVeJVpov0UojpT9ESXBTvBlllIDx2wYbsGn4gngUD2Me5m1-QH5Kfmdw9_RuZhQpm3FnUrJLuLh1z6m6t44v3FxdXf0gNWEyTNMohFxVBtdX11e3_fCNVbm36GOjkXP_2DlPV0_t-upDUJZZ8f7uriiLQe_MTZtikMDyjiAhTmEUi2AW5SAEcBzEcjyAYC6NM5iDQg_Cu-urm7AoLvVxOQerfANoQGMAA4D949ld761pmkGDD9Lcv8NQFNzdr5aKE8DY-n2YlNCHOUVcjJzY3v8JGbbZR2QK_arILyzHKa_RX42IY5civv8IVTz4LQZx6ORpkXrlwEnjO-dghXFxZ_X5n8SwDFK3yPuJOUwcWNw0oXV5gn13dm6WYQyfgk0A5ituwEvHDKwieJth6wUvz_kZlyT4iJ2JUC1N__L1ffhsg9v4UKRW9rCmpjgvi7zrP6ELkzIsT09bXlR5YsXw2xm_2nCXs_jrl7HwwxomZx7fAOZyEq_CxHTSPHtR5hW83N3LMLNcN_8BkOyAoQcAoAOAU5f7fXNI_Z5p0KfY36-lwTDcdKLqnERsBCQFJQxBDJaqHImTWSmp21ZXUGAIu1hUxwd973T6XlfmwgYY6gpb7XVyqc4DMV6VojDe6ycQ6Jje9mOR2K2IVbxqDM04GHIqK9u5uN2OWmnE81okC9sTOVWB7qv-hw-XL-rFOYqvHrLpOUL5eVZ_Khufp1Fq76FTPo56IcxvcZLGaItkEcbFLYRwCRthSWAhpEt6JIA2jdvPEcg0yXIYm0XoIgoCEBLBAIL3JgSFkyiJsASLMxTKMghOMSyDMRRAGJKm8WfY7qwK3d8AFMX7o4XxKIMDavQM5_ibPKDQAXfvc5a23Mtac-xGk4JRQOcXQk37DvfUmp-veIIbjgaXYwtfpiHnxPsl9H9SbF-1Tl1YudN61eqIcxqNVogwY6FkkPOQlxf7o7zXN2weXU75xxImVlKaOfTDNDELJ83gN-IzxIH8r_L_kUXo3v4a75eTu7767ceD_jfOEIbKYCLtLvfKfln4qyz5X7C5qcrwbTI3vO54oHwUiRZlVZGkMeGeIbo3NcxvwOAZSvgXTegWtzbNerZHuAgOPRYherFBGEDgCE3ZgCUgQ5IoeznW6zYuzDhzwpcYyfbh-IpF1KszdI_8Aqe-Ku7DkpsiLF8A5qsCv037SQMnjwfn8rVMoz7pTxn8XspgMnOHaZL0f3jnk9gXuD1H95SYefmP118m3ZzP8Vwz6n8LiZcegnmmJLLOA2W3R6a-y3C-0O_ClmPXSAy4ABFITWLWkEJ3-7AS71OLhCnbTG28Q2t0Ku3FHdNmO0Xah6a1Hcr1rkVIkmeOk6OmIdkBr_OZZXYs7UKemE7oE7YbO8Je0lrJobepznk-utYPsBuuFwoI1uZqbFsrY0ZV05YezVHJqQlH4uTkqOD53t3S4ez-vtU3yHGvNhhTLu0lo5RgNTIYEVOndBd75FirNFcXNM-g_ZiHqKe7bjDh44263dSFG8dtxuYeB32D38cLYs1P7GG-zrr5dK9HXKcsO2WByc00d-vDvDuIslzbMEKSMIt8MmCSiBxSTNI2FLvxY0HuksA_djG5lKmUnfkqyW7d2kFHWDkf28I8o-bbHSrOZ4yCrZe1XJYcvXaWTEqK7Cw4HdRqMefRYr60U41rj8v8Hsojyl3Th8Twpmy8ay2awmCILcsZSUqaMx7FdBG7I2xhnUKlUxqyXe8A0peLZO2OxhK9xBY7oZN1BZxKmpr7CO0eBc5nO7LsKCRaHRmTiISprkJMWzSh5-gRNqk21f1M1uO1661CAVl3KWVI6m4ScKRdL-md3fmpvlhwc34qAjOGI6PSlWhP5elGFHO_MrbHdtLurZNEJwqSmF7aZRjVHgNlj5MHZczi5VqUtwIhl5Nxp42HBZQaWXAsexEvjw1j2o4PyoMVtNNg7u74UBOOI4EorbG35WcNt4mmmelgB3Gi0vqh9R1XiNRSDA5RSwXdxgiwtaNhuT9ZxW5ab6a0AvFqPK93njsxt8chUQ9h4IoGe5L8Q7Azop0FhMUJsSFcMoixaVyg0phSBz6juCKlNYEalyYdUYFEbpeoM1yDEyt307rBaVrrVHwMHeEwkpcsmu78PSdqoV0J44pPbc8OZvkprK3KvFek4hQpnB-wNZwVp0XnBw1GjY7VtJnPTDEKMT3anWDTPwbPlXoXavwxvccbnqxVY3rMOXxVkIpp6vF0SU2UTGiksS-ByVpb8gpf6F3l57OMTGqOBvJIm1qIgfOdltsopfNHdIIaj7rx5qNu-PnPL2AIDP303uHf3LtpyfJ3S7DwFuOZuU_u7UZzMKw12gYU2-n0ySoK3f9sdW7n_tv--90gh26Y97r2hyfx9Csrd0MrQXoFxs5qyA56VlZfDBUPddD3gwIWRV95KaVVwluUpizMISCCEw5ECBL3EAY6HmK7nkcTngdQD_tx0Cu1EymP82bjvK8e__KE9_Bg9kutlSaHMIGPLyrSOE6Tu_Ssxtjdg4uP0K8HsM162sVPalD9-R0K3s2r5B2G4sQ7FH-P0e9R9N1kpb4ahEVRQfcnxSr_xQr71OqfCk27jhgUAAA; orgId=37bed117-9bc5-ed11-aed1-001dd804f3a9","Referer":"https://guardian-sit2.crm9.dynamics.com/main.aspx?forceUCI=1&pagetype=apps","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36","accept":"application/json","clienthost":"Browser","content-type":"application/json","prefer":"odata.include-annotations=\"*\"","sec-ch-ua":"\"Google Chrome\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","x-ms-app-id":"","x-ms-app-name":"__ unavailable__","x-ms-client-request-id":"ca863610-b50d-441f-8a85-8fe895e9d7c2","x-ms-client-session-id":"3b2bcc39-f294-45ad-aa82-cdb071cd851a","x-ms-correlation-id":"ff413b01-37bb-4b2b-8c45-033f048eb485","x-ms-gcm-object":"true","x-ms-metadatareductionlevel":"5","x-ms-sw-objectid":"35727a59-8d3a-4d4b-951a-5d5f51eb73b6","x-ms-sw-tenantid":"45e36269-2a6c-41cc-acf1-2d7382c0efee","x-ms-user-agent":"PowerApps-UCI/1.4.8639-2404.3 (Browser; AppName=__ unavailable__)"},"initialPriority":"High","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"E93EBE2D6444B31A2178652D8F5F71E0","resourceType":"XHR"},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
org.openqa.selenium.devtools.DevToolsException: {"id":646,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:193)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:89)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$5(Network.java:258)
	at org.openqa.selenium.devtools.Connection.lambda$handle$5(Connection.java:345)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:308)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:236)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.openqa.selenium.WebDriverException: {"id":646,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:272)
	... 4 more

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: {"id":646,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.openqa.selenium.devtools.DevToolsException: {"id":646,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:193)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:89)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$5(Network.java:258)
	at org.openqa.selenium.devtools.Connection.lambda$handle$5(Connection.java:345)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:308)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:236)
	... 3 more
Caused by: org.openqa.selenium.WebDriverException: {"id":646,"error":{"code":-32602,"message":"Invalid InterceptionId."},"sessionId":"FD235F0379725FF49703F87F8E5325A0"}
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:272)
	... 4 more
```

### Operating System

Windows 11

### Selenium version

Selenium 4.18.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 125

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 

### Are you using Selenium Grid?

No

**Comment by jaydjana87** [comment]
Btween Java Version 17
