### ISSUE TITLE
[🐛 Bug]: TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'

### ISSUE THREAD

**Issue by tscandalitta** [SeleniumHQ/selenium#14087]
### What happened?

I'm running some automation tests on a webkit based browser

Code:
```python
from selenium.webdriver import WebKitGTK

webdriver_path: str = "/usr/bin/WebKitWebDriver"
driver = WebKitGTK(executable_path=webdriver_path)
driver.get("https://google.com")
```

Error:
```
python3.11 mytest.py 
Traceback (most recent call last):
  File "/tests/mytest.py", line 4, in <module>
    driver = WebKitGTK(executable_path=webdriver_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tests/.venv/lib/python3.11/site-packages/selenium/webdriver/webkitgtk/webdriver.py", line 66, in __init__
    super().__init__(
TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'
```
As you can see inspecting `selenium.webdriver.webkitgtk.webdriver.py`, the constructor of RemoteWebDriver does not accept `desired_capabilities`
![Screenshot from 2024-06-05 15-41-05](https://github.com/SeleniumHQ/selenium/assets/38343557/b40bc9ad-e4e7-4c8a-a897-b05cc052a239)

If I remove that param `desired_capabilities=desired_capabilities` I get:
```
python3.11 test_drivers.py 
Traceback (most recent call last):
  File "/tests/mytest.py", line 4, in <module>
    driver = WebKitGTK(executable_path=webdriver_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tests/.venv/lib/python3.11/site-packages/selenium/webdriver/webkitgtk/webdriver.py", line 66, in __init__
    super().__init__(
  File "/tests/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in __init__
    capabilities = options.to_capabilities()
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_capabilities'
```
So I have to replace `desired_capabilities=desired_capabilities` with `options=options`

![Screenshot from 2024-06-05 17-31-37](https://github.com/SeleniumHQ/selenium/assets/38343557/2531807d-e1c8-40e4-9525-9138022420bf)

And then it just runs ok! 

Is it a bug or I'm missing something??

### How can we reproduce the issue?

```shell
from selenium.webdriver import WebKitGTK

webdriver_path: str = "/usr/bin/WebKitWebDriver"
driver = WebKitGTK(executable_path=webdriver_path)
driver.get("https://google.com")
```

### Relevant log output

```shell
python3.11 mytest.py 
Traceback (most recent call last):
  File "/tests/mytest.py", line 4, in <module>
    driver = WebKitGTK(executable_path=webdriver_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tests/.venv/lib/python3.11/site-packages/selenium/webdriver/webkitgtk/webdriver.py", line 66, in __init__
    super().__init__(
TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'
```

### Operating System

Ubuntu 20.04.6 LTS

### Selenium version

Python 4.21.0

### What are the browser(s) and version(s) where you see this issue?

MiniBrowser

### What are the browser driver(s) and version(s) where you see this issue?

WebkitGTKDriver

**Comment by titusfortner** [comment]
These special webkit classes aren't really maintained as well as the other drivers; desired_capabilities should be deleted, and a default options class should be created by default.

**Comment by iampopovich** [comment]
@titusfortner 
I believe it can be done like in safari.webdriver, but I will ask before opening a pull request: 
did I understand correctly that in this class we should stop accepting desired_capabilities as argument and create default options inside the class instance, as it was done in the [commit](https://github.com/iampopovich/selenium/commit/1b8b5809188e6dbaa0cdbf296c5a3fe83afdc87b) ?
