### ISSUE TITLE
[🐛 Bug]: Running ./scripts/format.sh on macOS cause an error with downloading coreutils

### ISSUE THREAD

**Issue by iampopovich** [SeleniumHQ/selenium#14086]
### What happened?

i tried to apply formatting locally by running command in root selenium folder
`./scripts/format.sh`
then I got error with downloading coreuitls from github releases

the root of problem is coreutils [releases](https://github.com/uutils/coreutils/releases/) doesn't have architecture x86_64 for darwin platform. it's actually [coreutils-0.0.26-aarch64-apple-darwin.tar.gz](https://github.com/uutils/coreutils/releases/download/0.0.26/coreutils-0.0.26-aarch64-apple-darwin.tar.gz) 

I'm trying to figure out how to fix this using the build system tools, but I'm afraid it's not possible to explicitly specify the URL of a dependency. Is this behavior a bug in Bazel?

### How can we reproduce the issue?

```shell
just run `./scripts/format.sh` in root directory of selenium project on macOS
```

### Relevant log output

```shell
./scripts/format.sh
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
WARNING: Build option --run_under has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
Analyzing: target //scripts:google-java-format (0 packages loaded, 0 targets configured)
Analyzing: target //scripts:google-java-format (0 packages loaded, 0 targets configured)
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
INFO: Analyzed target //scripts:google-java-format (0 packages loaded, 4712 targets configured).
INFO: Found 1 target...
Target //scripts:google-java-format up-to-date:
  bazel-bin/scripts/google-java-format
  bazel-bin/scripts/google-java-format.jar
INFO: Elapsed time: 0.572s, Critical Path: 0.21s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: /bin/bash -c 'echo bazel-bin/scripts/google-java-format '
- Buildifier
    buildifier
WARNING: Build option --run_under has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
INFO: Analyzed target //:buildifier (0 packages loaded, 764 targets configured).
INFO: Found 1 target...
Target //:buildifier up-to-date:
  bazel-bin/buildifier.bash
INFO: Elapsed time: 0.355s, Critical Path: 0.11s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/buildifier.bash
- Java
    google-java-format
- Javascript
    javascript/node/selenium-webdriver - prettier
WARNING: Download from https://github.com/uutils/coreutils/releases/download/0.0.26/coreutils-0.0.23-x86_64-apple-darwin.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository aspect_bazel_lib~~toolchains~coreutils_darwin_amd64 instantiated at:
  <builtin>: in <toplevel>
Repository rule coreutils_platform_repo defined at:
  /private/var/tmp/_bazel_alexpopov/0d0b789b125293cf47ad44fa1c4bc483/external/aspect_bazel_lib~/lib/private/coreutils_toolchain.bzl:197:42: in <toplevel>
ERROR: An error occurred during the fetch of repository 'aspect_bazel_lib~~toolchains~coreutils_darwin_amd64':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_alexpopov/0d0b789b125293cf47ad44fa1c4bc483/external/aspect_bazel_lib~/lib/private/coreutils_toolchain.bzl", line 183, column 30, in _coreutils_platform_repo_impl
                rctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/uutils/coreutils/releases/download/0.0.26/coreutils-0.0.23-x86_64-apple-darwin.tar.gz] to /private/var/tmp/_bazel_alexpopov/0d0b789b125293cf47ad44fa1c4bc483/external/aspect_bazel_lib~~toolchains~coreutils_darwin_amd64/temp10049011723120948715/coreutils-0.0.23-x86_64-apple-darwin.tar.gz: GET returned 404 Not Found
ERROR: <builtin>: fetching coreutils_platform_repo rule //:aspect_bazel_lib~~toolchains~coreutils_darwin_amd64: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_alexpopov/0d0b789b125293cf47ad44fa1c4bc483/external/aspect_bazel_lib~/lib/private/coreutils_toolchain.bzl", line 183, column 30, in _coreutils_platform_repo_impl
                rctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/uutils/coreutils/releases/download/0.0.26/coreutils-0.0.23-x86_64-apple-darwin.tar.gz] to /private/var/tmp/_bazel_alexpopov/0d0b789b125293cf47ad44fa1c4bc483/external/aspect_bazel_lib~~toolchains~coreutils_darwin_amd64/temp10049011723120948715/coreutils-0.0.23-x86_64-apple-darwin.tar.gz: GET returned 404 Not Found
ERROR: no such package '@@aspect_bazel_lib~~toolchains~coreutils_darwin_amd64//': java.io.IOException: Error downloading [https://github.com/uutils/coreutils/releases/download/0.0.26/coreutils-0.0.23-x86_64-apple-darwin.tar.gz] to /private/var/tmp/_bazel_alexpopov/0d0b789b125293cf47ad44fa1c4bc483/external/aspect_bazel_lib~~toolchains~coreutils_darwin_amd64/temp10049011723120948715/coreutils-0.0.23-x86_64-apple-darwin.tar.gz: GET returned 404 Not Found
ERROR: /Users/alexpopov/IdeaProjects/selenium/javascript/BUILD.bazel:5:29: //javascript:prettier depends on @@aspect_bazel_lib~~toolchains~coreutils_darwin_amd64//:coreutils_toolchain in repository @@aspect_bazel_lib~~toolchains~coreutils_darwin_amd64 which failed to fetch. no such package '@@aspect_bazel_lib~~toolchains~coreutils_darwin_amd64//': java.io.IOException: Error downloading [https://github.com/uutils/coreutils/releases/download/0.0.26/coreutils-0.0.23-x86_64-apple-darwin.tar.gz] to /private/var/tmp/_bazel_alexpopov/0d0b789b125293cf47ad44fa1c4bc483/external/aspect_bazel_lib~~toolchains~coreutils_darwin_amd64/temp10049011723120948715/coreutils-0.0.23-x86_64-apple-darwin.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//javascript:prettier' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.707s, Critical Path: 0.10s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: 
    Fetching repository @@aspect_bazel_lib~~toolchains~copy_directory_darwin_amd64; starting
    Fetching repository @@aspect_bazel_lib~~toolchains~bsd_tar_darwin_amd64; starting
```
```


### Operating System

macos sonoma 14.5

### Selenium version

Java 4.21

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

-

### Are you using Selenium Grid?

_No response_

**Comment by titusfortner** [comment]
I just merged 16d3905975fc0cbfaf723d9b68c945fc0cfe4f7a to require code that includes this PR https://github.com/aspect-build/bazel-lib/pull/853/ which is the temporary fix until coreutils gets a new release with all the right architectures
