### ISSUE TITLE
[🐛 Bug]: Selenium Grid cannot create a session without --enable-managed-downloads true

### ISSUE THREAD

**Issue by eugenedani** [SeleniumHQ/selenium#14125]
### What happened?

Run Selenium server as a standalone or hub/node without --enable-managed-downloads true parameter
for example, java -jar /root/selenium-server-<version>.jar standalone

Run a Selenium for any download files supported browser with driver option setEnableDownloads(true)

Receive error message org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

Is it a bug or expected behavior?
If this is expected behavior could error exception be more informative? For example, say something about  --enable-managed-downloads  parameter 

	

### How can we reproduce the issue?

```shell
Run Selenium server as a standalone or hub/node without --enable-managed-downloads true parameter
for example, java -jar /root/selenium-server-<version>.jar standalone

Run a Selenium test for any download files supported browser with driver option setEnableDownloads(true)

for example
`ChromeOptions options = new ChromeOptions();
options.setEnableDownloads(true);
WebDriver driver = new RemoteWebDriver(new URL("http://gridUrl:4444"), chromeOptions);
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'host', ip: '1xx.1xx.1.79'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:536)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:232)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:147)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: DelegatingWebDriver
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:399)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:355)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:89)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	... 54 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:382)
	... 62 more
```

### Operating System

Window, Linux

### Selenium version

4.21.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 126, Edge 125, Firefox ESR 115.12.0

### What are the browser driver(s) and version(s) where you see this issue?

 Chrome WebDriver 126.0.6478.55, Gecko 0.34.0

### Are you using Selenium Grid?

4.21.0

**Comment by titusfortner** [comment]
The capabilities you pass in are telling the grid to only provide a session with those capabilities. 
When options.setEnableDownloads(true)
The grid can't satisfy the session request because it wasn't enabled.

Is this the right error message for that? Can it be improved? Maybe someone with more grid understanding can answer.

**Comment by eugenedani** [comment]
I supposed setEnableDownloads(true) should not have influence on session creation. I expect it will just ignore this option for this case.

If my expectation is not right then I would expect more informative error message. I spent couple of hours before I found out the problem

**Comment by eugenedani** [comment]
Or possible error can be noted in documentation

**Comment by titusfortner** [comment]
Amy time you ask for a session with a capability that the grid cannot satisfy it should error.
Hopefully we can improve the error message.

**Comment by eugenedani** [comment]
Thank you for explanation
It would be great to have better error message.

**Comment by sbabcoc** [comment]
@titusfortner In the case of error messages, more information is better. Unfortunately, **DefaultSlotMatcher** is only able to return `true` or `false` from its `matches(Capabilities, Capabilities)` method. The specific capability mismatch that causes any given slot to be rejected is neither recorded nor reported. The other challenge is that a Grid instance can be expected to provide multiple slots that supply a variety of different types of sessions. The only way I can think of to provided more detailed diagnostic information would be to collect the details of each mismatch, returning this information in the exception if none of the available slots is able to satisfy the "new session" request.

**Comment by diemol** [comment]
This is expected because when Grid receives a request with a non-supported capability, it holds it for a while, expecting a node that supports the capability to join the Grid in the next minutes.

If you want to have an immediate response in these cases, start the Hub or Distributor with `--reject-unsupported-caps true`.

https://www.selenium.dev/documentation/grid/configuration/cli_options/#distributor
