### ISSUE TITLE
[🐛 Bug]: a value is required for '--proxy ' but none was supplied with ProxyType.DIRECT

### ISSUE THREAD

**Issue by Jobvdb** [SeleniumHQ/selenium#14162]
### What happened?

Im developing a test automation app that uses Selenium and with upgrading from 4.18.1 to 4.21.0, I got this error: Unable to obtain: chromedriver, error Command failed with code: 2, executed: [--browser, chrome, --proxy, --language-binding, java, --output, json] error: a value is required for '--proxy <PROXY>' but none was supplied For more information, try '--help'.

In the example below, I'm using ProxyType.DIRECT, but any type will trigger this behavior (including AUTODETECT)

### How can we reproduce the issue?

```shell
@Test
    void withProxy() {
        org.openqa.selenium.Proxy proxy = new org.openqa.selenium.Proxy();
        proxy.setProxyType(org.openqa.selenium.Proxy.ProxyType.DIRECT);
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setProxy(proxy);
        new ChromeDriver(chromeOptions);
    }
```

### Relevant log output

```shell
org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: chromedriver, error Command failed with code: 2, executed: [--browser, chrome, --proxy, --language-binding, java, --output, json]
error: a value is required for '--proxy <PROXY>' but none was supplied

For more information, try '--help'.

        at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:121)
        at org.openqa.selenium.remote.service.DriverFinder.getDriverPath(DriverFinder.java:55)
        at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
        at nl.testautomaat.test.driver.web.RemoteTest.withProxy(RemoteTest.java:27)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.openqa.selenium.WebDriverException: Command failed with code: 2, executed: [--browser, chrome, --proxy, --language-binding, java, --output, json]
error: a value is required for '--proxy <PROXY>' but none was supplied

For more information, try '--help'.

        at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:169)
        at org.openqa.selenium.manager.SeleniumManager.getBinaryPaths(SeleniumManager.java:244)
        at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:102)
        ... 9 more
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: error: a value is required for '--proxy <PROXY>' but none was supplied

For more information, try '--help'.

        at org.openqa.selenium.json.Json.toType(Json.java:169)
        at org.openqa.selenium.json.Json.toType(Json.java:152)
        at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:154)
        ... 11 more
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: e. Last 1 characters read: e, next 107 characters to read: rror: a value is required for '--proxy <PROXY>' but none was supplied

For more information, try '--help'.

Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.0', java.version: '21.0.1'
Driver info: driver.version: ChromeDriver
        at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:166)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:167)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146)
        at org.openqa.selenium.json.Json.toType(Json.java:206)
        at org.openqa.selenium.json.Json.toType(Json.java:167)
        ... 13 more
```

### Operating System

macOS

### Selenium version

Java 4.21.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 126.0.6478.62 (Official build) (arm64)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 126.0.6478.62

**Comment by titusfortner** [comment]
Thanks for reporting, the bindings need to pass along the proxy information to Selenium Manager only when things need to be routed through a host instead of always,

**Comment by Jobvdb** [comment]
Thanks for picking this up! In the meantime, is there a work-around for this, except for not using the proxy setting?

**Comment by titusfortner** [comment]
Looks like it was [added back in 4.9](https://github.com/SeleniumHQ/selenium/pull/12036), which is too far back to make sense to downgrade versions. 

Can either remove proxy or manage the drivers yourself for now.

**Comment by Jobvdb** [comment]
Alright, that was what I was going for, except I’m currently running 4.18.1 and it is working on that version. Not sure if that helps?

**Comment by titusfortner** [comment]
Oh, that's interesting. Can you turn on debugging and see what's different between the two?
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by Jobvdb** [comment]
Added Logger, but it seems to not log anything at all, before throwing the `NoSuchDriverException`. Maybe I'm doing it wrong? Here is my updated code:

```
@Test
    void withProxy() {
        Logger logger = Logger.getLogger("Proxy logger");
        logger.setLevel(Level.FINEST);
                Arrays.stream(logger.getHandlers()).forEach(handler -> {
            handler.setLevel(Level.FINEST);
        });

        org.openqa.selenium.Proxy proxy = new org.openqa.selenium.Proxy();
        proxy.setProxyType(org.openqa.selenium.Proxy.ProxyType.DIRECT);
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setProxy(proxy);
    }
```

**Comment by diemol** [comment]
You can try this tomorrow after the [Nightly build](https://www.selenium.dev/downloads/#nightly) has been generated. This will be also part of the 4.23 release.

**Comment by Jobvdb** [comment]
Perfect thanks! Tested and it works with the `4.23.0-SNAPSHOT` version
