### ISSUE TITLE
[🐛 Bug]: Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/util/Timer

### ISSUE THREAD

**Issue by zeus200003** [SeleniumHQ/selenium#14210]
### What happened?

After adding all the files needed and changing the working env. to JRE 22 , new problem occurred which preventing selenium from starting  

### How can we reproduce the issue?

```shell
package samplePackage;

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.*;

public class WebDriverDemo {

	public static void main(String[] args) {

		System.setProperty("webdriver.chrome.driver", "C:\\Users\\peter\\OneDrive\\Desktop\\Selenium Jars & Drivers\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver() ;
		driver.navigate().to("www.google.com");

	}

}
```

### Relevant log output

```shell
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/util/Timer
	at org.openqa.selenium.remote.http.netty.NettyClient$Factory.createClient(NettyClient.java:135)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:116)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:94)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.<init>(DriverCommandExecutor.java:88)
	at org.openqa.selenium.chromium.ChromiumDriverCommandExecutor.<init>(ChromiumDriverCommandExecutor.java:40)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.<init>(ChromeDriver.java:111)
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:101)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:52)
	at samplePackage.WebDriverDemo.main(WebDriverDemo.java:11)
Caused by: java.lang.ClassNotFoundException: io.netty.util.Timer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 11 more
```

### Operating System

Windows 11

### Selenium version

selenium-java-4.22.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver latest stable version available

**Comment by MHabiib** [comment]
hi @zeus200003 
Make sure your pom.xml file specifies <java.version>22</java.version> to ensure compatibility with Java 22. Also, correct the usage of driver.get() in your Selenium script by including the full URL with the protocol e.g., driver.get("http://www.google.com");. 
These steps should resolve the issues you're encountering with Selenium not starting and ensure proper navigation in your WebDriver script.
