### ISSUE TITLE
[🐛 Bug]: [Selenium + Edge] TimeoutException when calculating distances on Google Maps

### ISSUE THREAD

**Issue by skyySea1** [SeleniumHQ/selenium#14240]
### What happened?

Descrição:
i'm using selenium webdriver to automate a intern demmand at my work, basically  massive webscarpping for get distance between determinates cities in google maps (xpath to locate) (using a origin list per headquarter , and city lists for regions, i'm using nested looping to iterate for each origin and another for each destiny. Don't hace calculus, just finders and locater

Steps to play:
1. initialize WebDriver and open the Edge browser.
2. Navigate to Google Maps and try to calculate the distance between various origins and destinations in Bahia.
3. Wait for the distance element to load on the page.
4. Note that a TimeoutException is often thrown when trying to locate the distance element.

Expected behavior:
I expect Selenium to find and capture the distance element correctly after the search is performed on Google Maps for all elements in the looping

Comportamento observado:
Uma TimeoutException é lançada frequentemente após um certo tempo (acredito que entre a vigésima e trigésima vez) tentar acessar o elemento de distância após a pesquisa.

Ambiente de teste:
- edgeWebDriver 126.0.2592.87
- selenium Version: 4.22.0
- Microsoft Edge V 126.0.2592.87 (Compilation oficial) (64 bits)
- Windows 11

error message:
[27968:26468:0709/101447.066:ERROR:fallback_task_provider.cc(127)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.

attachment :

[crawler_distancia.zip](https://github.com/user-attachments/files/16144196/crawler_distancia.zip)

- Log 
[selenium log.txt](https://github.com/user-attachments/files/16144140/selenium.log.txt)
[terminal output.txt](https://github.com/user-attachments/files/16144141/terminal.output.txt)
 
- Capturas de tela do problema
![image](https://github.com/SeleniumHQ/selenium/assets/112349436/14d790e3-7057-45b8-8652-0c270b217cc5)
![image](https://github.com/SeleniumHQ/selenium/assets/112349436/14d790e3-7057-45b8-8652-0c270b217cc5)
![image](https://github.com/SeleniumHQ/selenium/assets/112349436/328a9ce5-3ac7-4bbf-9307-76cfd3e7bde6)
![image](https://github.com/SeleniumHQ/selenium/assets/112349436/8c6b4a17-8479-40e1-bdb6-bee492dd61c1)

Passos adicionais para investigação:
- Verifique se há alguma atualização recente do WebDriver do Edge que possa ter introduzido esse problema.
- Teste o código em diferentes configurações de sistema operacional (por exemplo, Windows 11, macOS) para verificar se o problema é específico para o Windows 10.

Qualquer assistência para resolver este problema seria muito apreciada. Obrigado!

### How can we reproduce the issue?

```shell
To reproduce the issue, you can use the following code snippet with Selenium and Microsoft Edge:


from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from msedge.selenium_tools import EdgeOptions, EdgeService

# Setup Edge WebDriver
service = EdgeService()
options = EdgeOptions()
# Add any necessary options here

driver = webdriver.Edge(service=service, options=options)

# Example code to navigate Google Maps and calculate distances
origem = "Salvador, Bahia"
destino = "Abaíra, BA"

try:
    driver.get("https://www.google.com/maps/dir/Salvador,+Bahia/Abaíra,+BA")
    wait = WebDriverWait(driver, 15)
    element = wait.until(EC.element_to_be_clickable((By.XPATH, "//*[@id='omnibox-directions']/div/div[2]/div/div/div/div[2]/button")))
    element.click()

    origem_input = driver.find_element(By.XPATH, '//*[@id="sb_ifc50"]/input')
    origem_input.clear()
    origem_input.send_keys(origem)

    destino_input = driver.find_element(By.XPATH, '//*[@id="sb_ifc51"]/input')
    destino_input.clear()
    destino_input.send_keys(destino)
    destino_input.send_keys(Keys.ENTER)

    # Wait for the distance element to be visible
    distancia = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="section-directions-trip-0"]/div[1]/div/div[1]/div[2]/div')))
    print(distancia.text)

except Exception as e:
    print(f"An error occurred: {str(e)}")

finally:
    driver.quit()
This code snippet demonstrates an attempt to calculate distances between "Salvador, Bahia" and "Abaíra, BA" using Selenium WebDriver with Microsoft Edge. However, it often results in a TimeoutException when trying to locate the distance element on the Google Maps page.

Please let me know if you need further details or if there's anything else I can provide to help diagnose the issue.
```

### Relevant log output

```shell
S C:\Users\Henrique RIbeiro\Documents\webscrapping>
PS C:\Users\Henrique RIbeiro\Documents\webscrapping>  c:; cd 'c:\Users\Henrique RIbeiro\Documents\webscrapping'; & 'c:\Users\Henrique RIbeiro\AppData\Local\Microsoft\WindowsApps\python3.12.exe' 'c:\Users\Henrique RIbeiro\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '62942' '--' 'C:\Users\Henrique RIbeiro\Documents\webscrapping\crawler_distancia.py'

DevTools listening on ws://127.0.0.1:62954/devtools/browser/8c1b90f9-57fd-4f7f-8926-eeb166ddb4d5
[27968:26468:0709/101447.066:ERROR:fallback_task_provider.cc(127)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
[27968:26468:0709/102146.540:ERROR:device_event_log_impl.cc(240)] [10:21:46.543] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Elemento n├úo encontrado. (0x490)

distancia = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="section-directions-trip-0"]/div[1]/div/div[1]/div[2]/div')))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Henrique RIbeiro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Henrique RIbeiro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Henrique RIbeiro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Henrique RIbeiro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Henrique RIbeiro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: MicrosoftEdge=126.0.2592.87)
Stacktrace:
	GetHandleVerifier [0x00007FF775908132+13538]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF775891DE9+595465]
	(No symbol) [0x00007FF7756AE6CF]
	(No symbol) [0x00007FF775699D4F]
	(No symbol) [0x00007FF775699C20]
	(No symbol) [0x00007FF7756B0B31]
	(No symbol) [0x00007FF77572AB2F]
	(No symbol) [0x00007FF775711C63]
	(No symbol) [0x00007FF7756E766E]
	(No symbol) [0x00007FF7756E683C]
	(No symbol) [0x00007FF7756E7221]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF775AC96D4+1099860]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF77580D8FC+53532]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF775800E25+1605]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF775AC8665+1095653]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF77589C961+27777]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF775896CE4+4100]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF775896E1B+4411]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF77588CFA0+575424]
	BaseThreadInitThunk [0x00007FFA8273257D+29]
	RtlUserThreadStart [0x00007FFA83CAAF28+40]
```

### Operating System

win10

### Selenium version

python 3.12

### What are the browser(s) and version(s) where you see this issue?

edge x64 126.0.2592.87

### What are the browser driver(s) and version(s) where you see this issue?

 edgeWebDriver 126.0.2592.87

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
The error comes directly from the browser, please report it to them.
