### ISSUE TITLE
[🐛 Bug]: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

### ISSUE THREAD

**Issue by hladi-kc** [SeleniumHQ/selenium#14268]
### What happened?

I am using Java 17.0.4, OS: windows 10, Selnium 4.22.0, Chrome: 126, and TestNg: 7.10.0

From the last few days after starting automation, the first few test cases are running properly and then cases are skipped due to failing to create the new session.

I am running an EC2 instance and my cases will run on the same machine. Usually, I ran from Jenkins which is set in the same machine after this I tried through Jenkins and also through the command prompt. The strange thing is I am running this suit properly in my Ubuntu machine.

### **Chome Logs:** 
[1721166377.943][INFO]: Starting ChromeDriver 126.0.6478.126 (d36ace6122e0a59570e258d82441395206d60e1c-refs/branch-heads/6478@{#1591}) on port 36456
[1721166377.943][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1721166406.438][INFO]: [bd7d51464fae95fc6a1728af296ef841] COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "browserName": "chrome",
         "goog:chromeOptions": {
            "args": [ "enable-automation", "--window-size=1920,1080", "--no-sandbox", "--disable-extensions", "--dns-prefetch-disable", "--disable-gpu", "--remote-allow-origins=*", "--headless" ],
            "extensions": [  ],
            "prefs": {
               "download.default_directory": "path",
               "profile.default_content_settings.popups": 0
            }
         },
         "pageLoadStrategy": "normal"
      } ]
   }
}
[1721166406.438][INFO]: Browser search. Trying... C:\Windows\system32\config\systemprofile\.cache\selenium\chromedriver\win64\126.0.6478.126\chrome.exe
[1721166406.438][INFO]: Browser search. Trying... C:\Windows\system32\config\systemprofile\.cache\selenium\chromedriver\win64\126.0.6478.126\chrome.exe
[1721166406.438][INFO]: Browser search. Trying... C:\Windows\system32\config\systemprofile\.cache\selenium\chromedriver\win64\126.0.6478.126\chromium.exe
[1721166406.440][INFO]: Browser search. Trying... C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe
[1721166406.440][INFO]: Browser search. Trying... C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[1721166406.440][INFO]: Browser search. Trying... C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[1721166406.441][INFO]: Browser search. Trying... C:\Program Files\Google\Chrome\Application\chrome.exe
[1721166406.441][INFO]: Browser search. Found at  C:\Program Files\Google\Chrome\Application\chrome.exe
[1721166415.938][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "download": {
      "default_directory": "path"
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 0,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1721166415.939][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1721166415.941][INFO]: ChromeDriver supports communication with Chrome via pipes. This is more reliable and more secure.
[1721166415.941][INFO]: Use the --remote-debugging-pipe Chrome switch instead of the default --remote-debugging-port to enable this communication mode.
[1721166415.942][INFO]: Cannot switch to US keyboard layout - some keys may be interpreted incorrectly
[1721166415.942][INFO]: Launching chrome: "C:\Program Files\Google\Chrome\Application\chrome.exe" --allow-pre-commit-input --disable-background-networking --disable-backgrounding-occluded-windows --disable-client-side-phishing-detection --disable-default-apps --disable-extensions --disable-gpu --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --dns-prefetch-disable --enable-automation --enable-logging --headless --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-allow-origins=* --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Windows\SystemTemp\scoped_dir10124_1289139637" --window-size=1920,1080 data:,
[1721166480.738][INFO]: Failed to connect to Chrome. Attempting to kill it.
[1721166489.572][INFO]: [bd7d51464fae95fc6a1728af296ef841] RESPONSE InitSession ERROR session not created: DevToolsActivePort file doesn't exist
[1721166489.572][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1721166489.572][DEBUG]: Log type 'browser' lost 0 entries on destruction

### How can we reproduce the issue?

```shell
Run automation as a suit with some amount of test cases.

mvn clean test -Dgroups=smoke
```

### Relevant log output

```shell
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'EC2AMAZ-RNTDGP0', ip: '172.31.13.240'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:536)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:232)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at com.kc.coursefinder.selenium.base.BaseClass.setBroswer(BaseClass.java:235)
	at com.kc.coursefinder.selenium.base.BaseClass.preConditions(BaseClass.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:600)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.openqa.selenium.WebDriverException: Failed waiting for driver server to start.
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:253)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:117)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	... 30 more
Caused by: java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4'
Driver info: driver.version: unknown
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:234)
	... 32 more
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:278)
	at org.openqa.selenium.remote.service.DriverService.lambda$start$1(DriverService.java:212)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:38947/status] to be available after 20001 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:96)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:274)
	... 5 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:89)
	... 6 more

[ERROR] com.kc.coursefinder.selenium.test.login.VerifyLogoutFunctionalityTest.preConditions -- Time elapsed: 48.71 s <<< FAILURE!
org.openqa.selenium.SessionNotCreatedException: 
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'EC2AMAZ-RNTDGP0', ip: '172.31.13.240'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:536)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:232)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at com.kc.coursefinder.selenium.base.BaseClass.setBroswer(BaseClass.java:235)
	at com.kc.coursefinder.selenium.base.BaseClass.preConditions(BaseClass.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:600)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to bind the port.
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:249)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:117)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	... 30 more
```

### Operating System

Windows 10

### Selenium version

Java 17.0.3 and Selenium 4.22.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 126

### What are the browser driver(s) and version(s) where you see this issue?

Selenium Manager i am using

**Comment by diemol** [comment]
It looks like ChromeDriver is having issues starting on that instance
>Timed out waiting for driver server to bind the port.

If you know that your code works because you have checked it on your machine, then it is an issue with the setup of the AWS instance. If some tests work at the beginning but then some fail afterward, it might be a resource issue (CPU/Memory). Try with a bigger instance or check that the browsers and drivers are effectively getting closed.

This is out of the scope because it all points to be a setup issue. You can ask more questions by using the links below.
