### ISSUE TITLE
[🐛 Bug]: After using ChromiumDriver.register(UsernameAndPassword()) The terminal keeps outputting the log of devtools

### ISSUE THREAD

**Issue by lushangkan** [SeleniumHQ/selenium#14262]
### What happened?

1. create a new ChromiumDriver
4. use ((ChromiumDriver) driver).register(() -> new UsernameAndPassword("USER", "PASS")); add the account password for proxy authentication
5. Run it, then you will see the log of devtools in the terminal.

### How can we reproduce the issue?

```shell
fun catchChromeLog() {
        val option = ChromeOptions()

        val driver = ChromeDriver(option)

        (driver as ChromiumDriver).register {
            UsernameAndPassword(
                "USER",
                "PASS"
            )
        }

        driver.get("https://www.google.com")
    }
```
```


### Relevant log output

```shell
7月 14, 2024 10:00:46 下午 org.openqa.selenium.devtools.Connection send
信息: -> {
  "params": {
  },
  "method": "Target.getTargets",
  "id": 1
}
7月 14, 2024 10:00:46 下午 org.openqa.selenium.devtools.Connection handle
信息: <- {"id":1,"result":{"targetInfos":[{"targetId":"D391BDDA7C098155D92824D9E99E7704","type":"page","title":"data:,","url":"data:,","attached":true,"canAccessOpener":false,"browserContextId":"ACF90523AD2F7D48A43A4C529DBD72D4"}]}}
7月 14, 2024 10:00:46 下午 org.openqa.selenium.devtools.Connection send
信息: -> {
  "params": {
    "targetId": "D391BDDA7C098155D92824D9E99E7704",
    "flatten": true
  },
  "method": "Target.attachToTarget",
  "id": 2
}

.....
```

### Operating System

Windows 11

### Selenium version

Kotlin 2.0 Java 17

### What are the browser(s) and version(s) where you see this issue?

Chrome 126.0.6478.127

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 126.0.6478.127

### Are you using Selenium Grid?

v4.22.0

**Comment by lushangkan** [comment]
Are there any temporary fixes? My project has a time limit

**Comment by lushangkan** [comment]
It seems that adding this line of code produces `Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: java.util.concurrent.TimeoutException`

Logs:
```
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:242)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:197)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:90)
	at org.openqa.selenium.devtools.v126.v126Network.createSeMessages(v126Network.java:123)
	at org.openqa.selenium.devtools.v126.v126Network.createSeMessages(v126Network.java:40)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$5(Network.java:215)
	at org.openqa.selenium.devtools.DevTools.lambda$addListener$0(DevTools.java:104)
	at org.openqa.selenium.devtools.Connection.lambda$handle$5(Connection.java:348)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:311)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:239)
	... 3 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:186)
	... 21 more
Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: java.io.IOException: closed output
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:242)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.openqa.selenium.WebDriverException: java.io.IOException: closed output
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.send(JdkHttpClient.java:301)
	at org.openqa.selenium.remote.http.WebSocket.sendText(WebSocket.java:32)
	at org.openqa.selenium.devtools.Connection.send(Connection.java:174)
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:185)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:90)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$5(Network.java:273)
	at org.openqa.selenium.devtools.DevTools.lambda$addListener$0(DevTools.java:104)
	at org.openqa.selenium.devtools.Connection.lambda$handle$5(Connection.java:348)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:311)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:239)
	... 3 more
Caused by: java.io.IOException: closed output
	at java.net.http/jdk.internal.net.http.RawChannelTube.write(RawChannelTube.java:340)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.write(TransportImpl.java:114)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.tryCompleteWrite(TransportImpl.java:601)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:537)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$WriteEvent.handle(TransportImpl.java:749)
	at java.net.http/jdk.internal.net.http.RawChannelTube$WriteSubscription.cancel(RawChannelTube.java:140)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalWriteSubscriber$WriteSubscription.cancel(SocketTube.java:486)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalWriteSubscriber.signalError(SocketTube.java:435)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalWriteSubscriber.tryFlushCurrent(SocketTube.java:370)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalWriteSubscriber.signalWritable(SocketTube.java:423)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalWriteSubscriber$WriteEvent.signalEvent(SocketTube.java:450)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:979)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:934)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:934)
```

**Comment by diemol** [comment]
What is the actual issue?

**Comment by lushangkan** [comment]
> What is the actual issue?

It seems that calling ChromiumDriver.register() brings up Chrome Devtools logs in the console that shouldn't be there.

**Comment by diemol** [comment]
I believe that has been the behavior since Selenium 4 was launched. Do you only see that with the code snippet you supplied?

**Comment by lushangkan** [comment]
> I believe that has been the behavior since Selenium 4 was launched. Do you only see that with the code snippet you supplied?

Yes, but I don't have much experience with Selenium.

**Comment by diemol** [comment]
OK, I understand. So, yes, we are handling this differently for [WebDriver BiDi ](https://github.com/w3c/webdriver-bidi) but for CDP, this is the behavior.
