### ISSUE TITLE
[🐛 Bug]: NoSuchMethodError when calling DevTools#createSession

### ISSUE THREAD

**Issue by Tiiita** [SeleniumHQ/selenium#14288]
### What happened?

```java
Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'
	at org.openqa.selenium.devtools.v126.target.Target.getTargets(Target.java:150)
	at org.openqa.selenium.devtools.v126.v126Target.getTargets(v126Target.java:55)
	at org.openqa.selenium.devtools.DevTools.findTarget(DevTools.java:157)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:121)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:109)
	at de.tiiita.util.NetworkListener.<init>(NetworkListener.java:20)
	at de.tiiita.task.TaskStarter.<init>(TaskStarter.java:24)
	at de.tiiita.task.TaskPreparator.startTasks(TaskPreparator.java:40)
	at de.tiiita.Main.login(Main.java:60)
	at de.tiiita.Main.run(Main.java:36)
	at de.tiiita.Main.main(Main.java:98)
```	

### How can we reproduce the issue?

```java
DevTools devTools = ((ChromiumDriver) webDriver).getDevTools();
devTools.createSession();`
```

### Relevant log output

```shell
Starting ChromeDriver 126.0.6478.182 (5b5d8292ddf182f8b2096fa665b473b6317906d5-refs/branch-heads/6478@{#1776}) on port 19958
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

### Operating System

Windows 11

### Selenium version

Java 17, Selenium 4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome v126

### What are the browser driver(s) and version(s) where you see this issue?

Newest version: 126.0.6478.182

### Are you using Selenium Grid?

4.8.0

**Comment by Tiiita** [comment]
I think my pom.xml is important so:
[POM.txt](https://github.com/user-attachments/files/16321547/POM.txt)
