### ISSUE TITLE
[🐛 Bug]: Chrome-Linux64 driver cannot start: chromedriver unexpectedly exited. Status code was: 127

### ISSUE THREAD

**Issue by arabellastrange** [SeleniumHQ/selenium#14310]
### What happened?

I have been using the chrome-linux driver in python + `selenium==4.22.0` with this call:

```
            options = Options()
            options.page_load_strategy = "eager"
            options.add_argument("--headless")
            with webdriver.Chrome(options=options) as dr:
                dr.set_page_load_timeout(timeout)
                .......

```

and this call:

```
            options = Options()
            options.page_load_strategy = "eager"
            options.add_argument("--headless")
            options.add_argument("--no-sandbox")
            options.add_argument("--disable-dev-shm-usage")

            options.add_argument("start-maximized")
            options.add_argument("disable-infobars")
            options.add_argument("--disable-extensions")
            options.add_argument("--disable-gpu")
            options.add_argument("--disable-dev-shm-usage")
            result = ""
            try:
                driver = webdriver.Chrome(options=options)
                driver.set_page_load_timeout(timeout)
                ......
            except selenium.common.exceptions.WebDriverException:
                traceback.print_exc()
                return .....
```
Which until, to the best of my knowledge, 23.07.2024 was working well. As of 25.07.2024 however, I am now seeing this error when I try to initialise the driver: 

```
selenium.common.exceptions.WebDriverException: Message: Service /home/user/.cache/selenium/chromedriver/linux64/127.0.6533.72/chromedriver unexpectedly exited. Status code was: 127
```

The error appears when I try to deploy my app on a server (I've tried a local reverse Nginx proxy (Linux) and HuggingFace spaces (Linux)) but not when I run the code locally on my (Windows) machine. 

I've tried to solve this issue by: 
- Trying to use a Firefox driver 
- Trying to include chromium and chromedriver-autoinstaller in my requirements
- Upgrading to `selenium==4.23.0`
- Manually installing the chrome driver and linking the path (returns a different error (not a valid driver) but doesn't function still)
- Using `webdriver-manager` with `ChromeService`

So far, I've had no luck. Any ideas what the problem might be?

### How can we reproduce the issue?

```shell
The huggingface version of this code is available on this repo: https://huggingface.co/spaces/arabellastrange/search-assistant/tree/main. 

Specifically in the file, line 81: https://huggingface.co/spaces/arabellastrange/search-assistant/blob/main/web_search.py
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/user/app/web_search.py", line 81, in process_url
    driver = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/user/.cache/selenium/chromedriver/linux64/127.0.6533.72/chromedriver unexpectedly exited. Status code was: 127
```

### Operating System

Debian

### Selenium version

4.22.0

### What are the browser(s) and version(s) where you see this issue?

Chrome (latest)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver-Linux64 (latest)

### Are you using Selenium Grid?

No

**Comment by arabellastrange** [comment]
Update on running the code with a manually installed local chromedriver, back to the same error: 

```
Traceback (most recent call last):
  File "/home/user/app/web_search.py", line 86, in process_url
    driver = webdriver.Chrome(service=ChromeService(executable_path='chromedriver-linux64/chromedriver'), options=options)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service chromedriver-linux64/chromedriver unexpectedly exited. Status code was: 127
```

**Comment by samaritan1998** [comment]
same question

**Comment by diemol** [comment]
Chrome 127 was released in that timeframe, please report the issue to the Chrome folks.
