### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.InvalidSelectorException: Message: invalid selector

### ISSUE THREAD

**Issue by L-ZJoker** [SeleniumHQ/selenium#14333]
### What happened?

Cannot locate elements in shadow dom

![image](https://github.com/user-attachments/assets/55f44353-55d2-4001-82e0-040523a8d618)

### How can we reproduce the issue?

```shell
from time import sleep

from selenium import webdriver
from selenium.webdriver.common.by import By


driver = webdriver.Chrome()

driver.get("https://wujie-micro.github.io/demo-main-react/?vue3=%2Fdemo-vue3%2Fhome#/vue3")
sleep(20)
title = driver.title
print(title)
shadow_host = driver.find_element(By.TAG_NAME, 'wujie-app')
shadow_root = shadow_host.shadow_root
btn = shadow_root.find_element(By.CSS_SELECTOR, '.el-button')

print('btn', btn)
btn.click()
sleep(20)
driver.quit()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\ZJoker\program\location-shadow-root\location-el-of-shadow-dom.py", line 15, in <module>
    btn = shadow_root.find_element(By.CSS_SELECTOR, '.el-button')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZJoker\program\location-shadow-root\.venv\Lib\site-packages\selenium\webdriver\remote\shadowroot.py", line 53, in find_element
    return self._execute(Command.FIND_ELEMENT_FROM_SHADOW_ROOT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZJoker\program\location-shadow-root\.venv\Lib\site-packages\selenium\webdriver\remote\shadowroot.py", line 82, in _execute
    return self.session.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZJoker\program\location-shadow-root\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "D:\ZJoker\program\location-shadow-root\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector
from javascript error: {"status":10,"value":"stale element not found in the current frame"}
  (Session info: chrome=127.0.6533.88); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	GetHandleVerifier [0x00007FF7B2539632+30946]
	(No symbol) [0x00007FF7B24EE3C9]
	(No symbol) [0x00007FF7B23E6FDA]
	(No symbol) [0x00007FF7B23EDA57]
	(No symbol) [0x00007FF7B23EFD31]
	(No symbol) [0x00007FF7B23EFDD0]
	(No symbol) [0x00007FF7B2437F69]
	(No symbol) [0x00007FF7B243854C]
	(No symbol) [0x00007FF7B242BD1C]
	(No symbol) [0x00007FF7B245CAAF]
	(No symbol) [0x00007FF7B242BBB6]
	(No symbol) [0x00007FF7B245CC80]
	(No symbol) [0x00007FF7B247B041]
	(No symbol) [0x00007FF7B245C813]
	(No symbol) [0x00007FF7B242A6E5]
	(No symbol) [0x00007FF7B242B021]
	GetHandleVerifier [0x00007FF7B266F83D+1301229]
	GetHandleVerifier [0x00007FF7B267BDB7+1351783]
	GetHandleVerifier [0x00007FF7B2672A03+1313971]
	GetHandleVerifier [0x00007FF7B256DD06+245686]
	(No symbol) [0x00007FF7B24F758F]
	(No symbol) [0x00007FF7B24F3804]
	(No symbol) [0x00007FF7B24F3992]
	(No symbol) [0x00007FF7B24EA3EF]
	BaseThreadInitThunk [0x00007FFCE09D1102+34]
	RtlUserThreadStart [0x00007FFCE24E9F64+52]
```

### Operating System

window 10

### Selenium version

4.23.1

### What are the browser(s) and version(s) where you see this issue?

chrome 127

### What are the browser driver(s) and version(s) where you see this issue?

remote driver

**Comment by diemol** [comment]
I am not sure what the issue is with Chrome, but your code works well in Firefox:

```python
from time import sleep

from selenium import webdriver
from selenium.webdriver.common.by import By


driver = webdriver.Firefox()
driver.get("https://wujie-micro.github.io/demo-main-react/?vue3=%2Fdemo-vue3%2Fhome#/vue3")
sleep(10)
title = driver.title
print(title)
shadow_host = driver.find_element(By.TAG_NAME, 'wujie-app')
shadow_root = shadow_host.shadow_root
btn = shadow_root.find_element(By.CSS_SELECTOR, '.el-button')
print('btn', btn)
btn.click()
sleep(10)
driver.quit()
```

Please report the issue to the Chrome folks.
