### ISSUE TITLE
[🐛 Bug]: Unable to start selenium within AWS MWAA 

### ISSUE THREAD

**Issue by ylhan** [SeleniumHQ/selenium#14355]
### What happened?

I'm trying to run selenium within AWS MWAA but the webdriver unexpected exits with status code 5 each time.

### How can we reproduce the issue?

```shell
Grab the image from https://github.com/aws/aws-mwaa-local-runner and run it

Once the container is running you can bash into it, install selenium and the webdriver-manager and run the following script.


from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromiumService
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.os_manager import ChromeType
from selenium.webdriver.chrome.options import Options
options = Options()
options.add_argument("--headless=new")
driver = webdriver.Chrome(
    service=ChromiumService(
        ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()
    ),
    options=options,
)
```

### Relevant log output

```shell
options = Options()
>>> options.add_argument("--headless=new")
>>> driver = webdriver.Chrome(
...             service=ChromiumService(
...                 ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()
...             ),
...             options=options,
...         )

DEBUG:selenium.webdriver.common.driver_finder:Skipping Selenium Manager; path to chrome driver specified in Service class: /usr/local/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver
DEBUG:selenium.webdriver.common.service:Started executable: `/usr/local/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver` in a child process with pid: 19414 using 0 to output -3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: -5
```
```


### Operating System

linux running within a docker container

### Selenium version

Python selenium==4.21.0

### What are the browser(s) and version(s) where you see this issue?

114.0.5735.90

### What are the browser driver(s) and version(s) where you see this issue?

drivers/chromedriver/linux64/114.0.5735.90/chromedriver

### Are you using Selenium Grid?

No

**Comment by pujagani** [comment]
Thank you for the details. Is your Linux server running arm64?
What happens if you try using the latest Chromedriver?
What happens if you try to run it with Firefox?

**Comment by ylhan** [comment]
> Is your Linux server running arm64?

```
[airflow@fe40981652d3 ~]$ uname -a
Linux fe40981652d3 6.6.16-linuxkit #1 SMP Fri Feb 16 11:54:02 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by ylhan** [comment]
Will try with the latest chrome and firefox

**Comment by ylhan** [comment]
I believe I am already using the latest release for chrome https://chromedriver.storage.googleapis.com/LATEST_RELEASE

Both firefox and chrome fail

```
Python 3.11.7 (main, Jun  3 2024, 14:06:39) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver

>>> from selenium.webdriver.firefox.service import Service as FirefoxService
>>> from webdriver_manager.firefox import GeckoDriverManager
>>>
>>> driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

>>>
>>>
>>>
>>>
>>> # selenium 4
>>> from selenium import webdriver
>>> from selenium.webdriver.chrome.service import Service as ChromiumService
>>> from webdriver_manager.chrome import ChromeDriverManager
>>> from webdriver_manager.core.os_manager import ChromeType
>>>
>>> driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: -5

>>>
```

**Comment by diemol** [comment]
Please avoid `ChromeDriverManager` as [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) handles that for you now.

You do not need to create a driver service anymore.

**Comment by ylhan** [comment]
@diemol can you please reopen this? I cannot upgrade to the latest version of selenium because of airflow's version contraints.

**Comment by diemol** [comment]
We cannot troubleshoot old versions

**Comment by diemol** [comment]
You are already using a relatively recent version. You just need to get rid of what I mentioned above.

**Comment by pujagani** [comment]
@diemol  Our documentation states this "`If you are running Linux on arm64/aarch64, 32-bit architecture, or a Raspberry Pi, Selenium Manager will not work for you. The biggest issue for people is that they used to get custom-built drivers and put them on PATH and have them work. Now that Selenium Manager is responsible for locating drivers on PATH, this approach no longer works, and users need to use a Service class and [set the location directly](https://www.selenium.dev/documentation/webdriver/drivers/service/#driver-location).`" - Do we need to update it?

**Comment by diemol** [comment]
Oh, I missed the bit about the architecture. Then yes, you are correct, @pujagani. 

@ylhan You need to find the drivers that work for your architecture because so far, there are no official ones released by the browser vendors.

**Comment by ylhan** [comment]
I see, thank you for the follow up!
