### ISSUE TITLE
[🐛 Bug]: Memory not being properly released

### ISSUE THREAD

**Issue by freyfrey01** [SeleniumHQ/selenium#14364]
### What happened?

I've noticed that selenium chromeDriver (have also tested edgeDriver) in c# has not properly been releasing memory. I've been using RamMap to track memory usage. When not running the following scripts, memory usage does not steadily increase. Currently using Chrome and chromeDriver v127 and Selenium 4.23.0 (have also tried selenium 4.15.0)

Root of concern as shown in the screenshots is "Unused - Active" goes from 7000KB to 50000KB in the span of 5 minutes. Over the course of 24 hours, if that continues, that's an increase of nearly 12384000KB or about 12 GB. This is causing a major performance problem as after a week of running, the machine gets over 80% usage of RAM that's just unused but still considered "Active".

### How can we reproduce the issue?
I've tried the following implementations. I then create 15 scheduled tasks using Task Scheduler to run the script every minute for 5 minutes.
```c#
using OpenQA.Selenium.Chrome;
namespace ChromeBotTest
{
    public class Program
    {
        private static async Task Main(string[] args)
        {
            using (ChromeDriver? chromeDriver = new()) //using statement for automatic disposal
            {
                await Task.Delay(3000); //allow chrome to open for some short time
                chromeDriver.Close(); //close all windows
                chromeDriver.Quit(); //quit to fully close browser and release resources
            }
        }
    }
}

using OpenQA.Selenium.Chrome;
namespace ChromeBotTest
{
    public class Program
    {
        private static async Task Main(string[] args)
        {
            ChromeDriver chromeDriver = new(); 
            await Task.Delay(3000); //allow chrome to open for some short time
            chromeDriver.Quit(); //quit to fully close browser and release resources
        }
    }
}

using OpenQA.Selenium.Chrome;
namespace ChromeBotTest
{
    public class Program
    {
        private static async Task Main(string[] args)
        {
            using (ChromeDriver? chromeDriver = new()) //using statement for automatic disposal
            {
                await Task.Delay(3000); //allow chrome to open for some short time
                chromeDriver.Quit(); //quit to fully close browser and release resources
            }
        }
    }
}

using OpenQA.Selenium.Chrome;
namespace ChromeBotTest
{
    public class Program
    {
        private static async Task Main(string[] args)
        {
            ChromeDriver? chromeDriver = new();
            await Task.Delay(3000); //allow chrome to open for some short time
            chromeDriver.Close(); //close all windows
            chromeDriver.Quit(); //quit to fully close browser and release resources
            chromeDriver?.Dispose(); //dispose incase chromeDriver is not properly disposed
            chromeDriver = null; //set to null to ensure its cleared
        }
    }
}

    using OpenQA.Selenium.Chrome;
    namespace ChromeBotTest
    {
        public class Program
        {
            private static async Task Main(string[] args)
            {
                ChromeDriver? chromeDriver = new();
                await Task.Delay(3000); //allow chrome to open for some short time
                chromeDriver.Close(); //close all windows
                chromeDriver.Quit(); //quit to fully close browser and release resources
                chromeDriver?.Dispose(); //dispose incase chromeDriver is not properly disposed
                chromeDriver = null; //set to null to ensure its cleared
                await Task.Delay(2000); //allow 2 second delay
                GC.Collect();
                GC.WaitForPendingFinalizers(); //clean up garabage collection
                GC.Collect();
                await Task.Delay(10000); //wait 10 seconds to allow garbage collection sufficent time to execute
            }
        }
    }
```

### Relevant log output

```shell
Before running scripts: https://i.sstatic.net/TH8o9XJj.png
10 minutes of no activity before running scripts: https://i.sstatic.net/2YTPurM6.png
Running scripts for 5 minutes: https://i.sstatic.net/wjVFDiIY.png
10 minutes of no activity after running scripts: https://i.sstatic.net/QX6aJsnZ.png
```

### Operating System

Windows 10

### Selenium version

C# 4.23.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 127.0.6533.99

**Comment by freyfrey01** [comment]
Just started receiving this error during testing. Selenium is no longer working on the machine.

Trying this (worked when submitting this bug report but was not properly releasing memory)

```
using OpenQA.Selenium.Chrome;
namespace ChromeBotTest
{
    public class Program
    {
        private static async Task Main(string[] args)
        {
            using (ChromeDriver? chromeDriver = new()) //using statement for automatic disposal
            {
                await Task.Delay(3000); //allow chrome to open for some short time
                chromeDriver.Quit(); //quit to fully close browser and release resources
            }
        }
    }
}
```

Unhandled exception. OpenQA.Selenium.WebDriverException: Error starting process: E:\Test\ChromeBotTest\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
 ---> OpenQA.Selenium.WebDriverException: Selenium Manager process exited abnormally with 65 code: E:\Test\ChromeBotTest\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
Standard Output >>
{
  "logs": [
    {
      "level": "ERROR",
      "timestamp": 1723225434,
      "message": "error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)"
    }
  ],
  "result": {
    "code": 65,
    "message": "error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)",
    "driver_path": "",
    "browser_path": ""
  }
}

<<

   at OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments)
   at OpenQA.Selenium.SeleniumManager.BinaryPaths(String arguments)
   at OpenQA.Selenium.DriverFinder.BinaryPaths()
   at OpenQA.Selenium.DriverFinder.GetDriverPath()
   at OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at ChromeBotTest.Program.Main(String[] args) in C:\Users\Freddy\source\repos\test\ChromeBotTest\Program.cs:line 10
   at ChromeBotTest.Program.<Main>(String[] args)

**Comment by nvborisenko** [comment]
Interesting!

I have tried on my end and memory consumption stays stable.

@freyfrey01 which piece of code we should consider to reproduce the issue?

**Comment by freyfrey01** [comment]
Hello @nvborisenko, all of the code I provided causes the issue. Create a C# Console App with any of the implementations above (your most preferred for properly cleaning up after driver use). Create 15 scheduled tasks that run the program every minute for 5 minutes. Every minute you should see 15 instances of chromedriver.exe start then go away. After the 5 minutes are completed, observe the memory usage using Microsoft's RamMap software particularly the row with "Usage" column as "Unused" and observe the "Active" column for that row before and after testing.  Also recommend testing on a machine that has lots of available RAM that is unused to get proper metrics as running on laptop can give sparse metrics as memory get reallocated when usuage is too high.

All code I provided is for simple reproduction but in our production environment where we use the driver, we perform the logic most similar to this:

```
using OpenQA.Selenium.Chrome;
namespace ChromeBotTest
{
    public class Program
    {
        private static async Task Main(string[] args)
        {
            ChromeDriver? chromeDriver = new();
            await Task.Delay(3000); //allow chrome to open for some short time
            ///EXECUTE WHATEVER DRIVER NEEDS TO DO
            
            chromeDriver.Close(); //close all windows
            chromeDriver.Quit(); //quit to fully close browser and release resources
            chromeDriver?.Dispose(); //dispose incase chromeDriver is not properly disposed
            chromeDriver = null; //set to null to ensure its cleared
        }
    }
}
```

**Comment by nvborisenko** [comment]
`ChromeDriver` with default options? Or you use `--sandbox` argument parameter?

**Comment by freyfrey01** [comment]
@nvborisenko default options, on our production machine we provide options such as --no-sandbox, --headless, --incognito, and --start-maximized but for the purposes of my testing for this issue, I've kept it as minimal as possible just using default options, launching chrome, waiting 3 seconds, then quitting chrome.

**Comment by nvborisenko** [comment]
Most likely this is your case: https://issues.chromium.org/issues/42323783

**Comment by freyfrey01** [comment]
@nvborisenko can you elaborate? I actually don't see any zombie/orphaned processes within task manager or resource monitor. For my testing which was outlined above with the screenshots and sample code, --no-sandbox was **not** used so don't see the connection between the issue linked and my example codes?

As mentioned as well, this is also the case with edgeDriver, do not see different results whether I use EdgeDriver or ChromeDriver

**Comment by nvborisenko** [comment]
Then it becomes harder...

There is 2 types of resources: managed and unmanaged. I don't believe we don't release managed resources, it is kinda "impossible". Can you monitor what exactly eats your memory?
- network connection
- open file descriptor
- external processes (seleniummanager, chromedriver, chrome)
- something else?

**Comment by freyfrey01** [comment]
@nvborisenko I am very sure it has something to do with the selenium implementation but unsure where. This memory increase **never** occurs when the chrome bots are not running. 
I've also taken the liberty of running the following code in Visual Studio and using Diagnostic tools to view the memory usage.
I took 3 snapshots of memory as follows:
1. Before starting the chrome driver.
2. Directly after starting chrome driver (after the Task.Delay(10000))
3. After chromeDriver.Quit() (after the second Task.Delay(10000))

I would have expected my heap size and Objects Diff to have decreased after doing chromeDriver.Quit()
![image](https://github.com/user-attachments/assets/fd7e6a37-6c65-42fc-8cdd-5b8a2f5ec632)

```c#
public class Program
{
    private static async Task Main(string[] args)
    {
        ChromeDriver chromeDriver = new();
        await Task.Delay(10000); //allow chrome to open for some short time
        chromeDriver.Quit(); //quit to fully close browser and release resources
        await Task.Delay(10000); //allow chrome to open for some short time

        Console.ReadKey();
    }
}
```


This is an inspection of the managed memory comparing the first snapshot (chromedriver not launched yet) and the final snapshot (chromedriver should be terminated):
![image](https://github.com/user-attachments/assets/b9920062-4244-41d4-af7f-1ff79d4fd41c)

**Comment by nvborisenko** [comment]
I tested this code:

```csharp
for (int i = 0; i < 10; i++)
{
    ChromeDriver chromeDriver = new();
    await Task.Delay(3000); //allow chrome to open for some short time
    chromeDriver.Quit(); //quit to fully close browser and release resources
}
```

And memory consumption looks like:
![image](https://github.com/user-attachments/assets/f59dc82f-4e41-4124-887f-200f7ab5069f)

I don't see any mystic.

Then I tried the following:

```csharp
for (int i = 0; i < 50; i++)
{
    ChromeDriver chromeDriver = new();
    chromeDriver.Quit(); //quit to fully close browser and release resources
}
```

And the results:
![image](https://github.com/user-attachments/assets/855fd1c2-6f82-4dac-9f8f-db76ee916db2)

I don't see memory leak of .net managed resources.

**Comment by freyfrey01** [comment]
@nvborisenko would you be able to provide screenshots of RamMap from Microsoft similar to the ones I provided for before and after running the code you provided?

**Comment by nvborisenko** [comment]
Unfortunately no, I don't want to care about how .net manages memory and ,moreover, what RamMap shows to you. What I see that actual OS memory is not eaten by selenium.

UPD: I looked at your screenshots and I don't see criminal. Please come back with reproducible scenario when selenium eats **Gigabytes**.

**Comment by freyfrey01** [comment]
@nvborisenko has there been a proper fix to https://github.com/SeleniumHQ/selenium/issues/13656. This is the root of my problems
