### ISSUE TITLE
[🐛 Bug]: Selenium Manager error 

### ISSUE THREAD

**Issue by freyfrey01** [SeleniumHQ/selenium#14366]
### What happened?

Just started receiving this error during testing (Started in the last hour). Selenium is no longer working on the machine. Related to my other Bug report. This one is far more critical as chromedriver is not working entirely.

### How can we reproduce the issue?

```shell
using OpenQA.Selenium.Chrome;
namespace ChromeBotTest
{
    public class Program
    {
        private static async Task Main(string[] args)
        {
            using (ChromeDriver? chromeDriver = new()) //using statement for automatic disposal
            {
                await Task.Delay(3000); //allow chrome to open for some short time
                chromeDriver.Quit(); //quit to fully close browser and release resources
            }
        }
    }
}
```

Running 

```
E:\Test\ChromeBotTest\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
```
Gives same error output
```


### Relevant log output

```shell
Unhandled exception. OpenQA.Selenium.WebDriverException: Error starting process: E:\Test\ChromeBotTest\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
 ---> OpenQA.Selenium.WebDriverException: Selenium Manager process exited abnormally with 65 code: E:\Test\ChromeBotTest\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
Standard Output >>
{
  "logs": [
    {
      "level": "WARN",
      "timestamp": 1723228724,
      "message": "Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)"
    },
    {
      "level": "INFO",
      "timestamp": 1723228724,
      "message": "Driver path: E:\\Test\\ChromeBotTest\\chromedriver.exe"
    },
    {
      "level": "INFO",
      "timestamp": 1723228724,
      "message": "Browser path: C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
    }
  ],
  "result": {
    "code": 0,
    "message": "",
    "driver_path": "E:\\Test\\ChromeBotTest\\chromedriver.exe",
    "browser_path": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
  }
}

<<

   at OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments)
   at OpenQA.Selenium.SeleniumManager.BinaryPaths(String arguments)
   at OpenQA.Selenium.DriverFinder.BinaryPaths()
   at OpenQA.Selenium.DriverFinder.GetDriverPath()
   at OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at ChromeBotTest.Program.Main(String[] args) in C:\Users\Freddy\source\repos\test\ChromeBotTest\Program.cs:line 10
   at ChromeBotTest.Program.<Main>(String[] args)
```

### Operating System

Windows 10

### Selenium version

C# 4.23.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 127.0.6533.99

**Comment by freyfrey01** [comment]
Edge works correctly it seems

E:\Test\ChromeBotTest\selenium-manager\windows\selenium-manager.exe  --browser "edge" --language-binding csharp --output json
{
  "logs": [
    {
      "level": "INFO",
      "timestamp": 1723227429,
      "message": "Driver path: C:\\Users\\Freddy_P\\.cache\\selenium\\msedgedriver\\win64\\127.0.2651.98\\msedgedriver.exe"
    },
    {
      "level": "INFO",
      "timestamp": 1723227429,
      "message": "Browser path: C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
    }
  ],
  "result": {
    "code": 0,
    "message": "",
    "driver_path": "C:\\Users\\Freddy_P\\.cache\\selenium\\msedgedriver\\win64\\127.0.2651.98\\msedgedriver.exe",
    "browser_path": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
  }
}

**Comment by freyfrey01** [comment]
Seems to have fixed itself
