### ISSUE TITLE
[🐛 Bug]:  Path too long exception #7181 REBOOT

### ISSUE THREAD

**Issue by spacewalkingninja** [SeleniumHQ/selenium#14374]
### What happened?

PLEASE NOTICE:
Fix this as this is necessary to bypass some sites auto protection against bots *they stale at infinite tls handshreks
#7181 REBOOT <3

🐛 Bug Report

Starting FirefoxDriver with FirefoxProfile leads to Exception:

    The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

Catch: this is behavior for Windows User "Administrator", with shorter user name like "xxxxx" there is no such exception observed.

This behavior most likely depends on profile used - there are some addons installed (+-15) -
IMHO issue is that method OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory) doesn't expect long paths - If LOCAL TEMP folder + anonymous.GUID.webdriver-profile folder from selenium + folder structure inside firefox profile are beyond the limit then Exception emerge.

(In another project i use ZetaLongPaths to deal with such behavior, also .net 4.6.2+ seems to support long paths)

Stack Trace

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
  at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
  at System.IO.DirectoryInfo.Create()
  at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
  at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
  at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
  at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
  at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
  at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
  at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
  at OpenQA.Selenium.Firefox.FirefoxProfile.WriteToDisk()
  at OpenQA.Selenium.Firefox.FirefoxProfile.ToBase64String()
  at OpenQA.Selenium.Firefox.FirefoxOptions.GenerateFirefoxOptionsDictionary()
  at OpenQA.Selenium.Firefox.FirefoxOptions.ToCapabilities()
  at OpenQA.Selenium.Firefox.FirefoxDriver.ConvertOptionsToCapabilities(FirefoxOptions options)
  at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)

To Reproduce

with long enough user name + TEMP PATH + FF profile (in my case Ghostery addon have long inner folder path)

FirefoxProfile _FirefoxProfile = new FirefoxProfile(SeleniumFirefoxProfileDirectory); //"C:\\Temp\\FirefoxProfiles\\p2"
FirefoxDriverService driverService = FirefoxDriverService.CreateDefaultService();
FirefoxOptions options = new FirefoxOptions();
options.Profile = _FirefoxProfile;

IWebDriver driver = new FirefoxDriver(driverService,options,TimeSpan.FromMinutes(3));

Detailed steps to reproduce the behavior:
Expected behavior

I would expect browser started with custom profile.
Test script or set of commands reproducing this issue
Environment

OS: Windows 10
Browser: Firefox
Browser version: 66.0.4
Browser Driver version: GeckoDriver 0.24
Language Bindings version: C# 4.0.0 alpha
Selenium Grid version (if applicable):

### How can we reproduce the issue?

```shell
PLEASE NOTICE:
Fix this as this is necessary to bypass some sites auto protection against bots *they stale at infinite tls handshreks
```

### Relevant log output

```shell
PLEASE NOTICE:
Fix this as this is necessary to bypass some sites auto protection against bots *they stale at infinite tls handshreks
```

### Operating System

PLEASE NOTICE: Fix this as this is necessary to bypass some sites auto protection against bots *they stale at infinite tls handshreks

### Selenium version

PLEASE NOTICE: Fix this as this is necessary to bypass some sites auto protection against bots *they stale at infinite tls handshreks

### What are the browser(s) and version(s) where you see this issue?

PLEASE NOTICE: Fix this as this is necessary to bypass some sites auto protection against bots *they stale at infinite tls handshreks

### What are the browser driver(s) and version(s) where you see this issue?

PLEASE NOTICE: Fix this as this is necessary to bypass some sites auto protection against bots *they stale at infinite tls handshreks

### Are you using Selenium Grid?

PLEASE NOTICE: Fix this as this is necessary to bypass some sites auto protection against bots *they stale at infinite tls handshreks

**Comment by spacewalkingninja** [comment]
_

> my goalll is to use my normallll profilllllll in selenium to baypas the proteckshan

_
