### ISSUE TITLE
[🐛 Bug]: linux机器启动driver报错

### ISSUE THREAD

**Issue by jjqi92** [SeleniumHQ/selenium#14394]
### What happened?

driver = new RemoteWebDriver(new URL(String.format("http://%s:4444", hubIp)), options);

### How can we reproduce the issue?

```shell
When both the hub and the node are on the Linux machine, and the node is registered successfully. Creating a driver will report an error
```

### Relevant log output

```shell
20:00:30.553 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [disable-infobars, --disable-gpu, --test-type, --ignore-certificate-errors, --ignore-ssl-errors, no-default-browser-check, --disable-dev-shm-usage, --disable-web-security, se:vncEnabled, --user-agent=Mozilla/5.0 (W..., --headless, --whitelisted-ips], extensions: []}, goog:loggingPrefs: {browser: ALL, performance: ALL}, pageLoadStrategy: normal}]
20:00:41.345 INFO [Node.<init>] - Binding additional locator mechanisms: relative
20:01:01.500 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [disable-infobars, --disable-gpu, --test-type, --ignore-certificate-errors, --ignore-ssl-errors, no-default-browser-check, --disable-dev-shm-usage, --disable-web-security, se:vncEnabled, --user-agent=Mozilla/5.0 (W..., --headless, --whitelisted-ips], extensions: []}, goog:loggingPrefs: {browser: ALL, performance: ALL}, pageLoadStrategy: normal}]
20:01:03.738 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "bf7ac8a7ebe1714db052bbe28bfe9735","eventTime": 1723636683705157169,"eventName": "Session request received by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [disable-infobars, --disable-gpu, --test-type, --ignore-certificate-errors, --ignore-ssl-errors, no-default-browser-check, --disable-dev-shm-usage, --disable-web-security, se:vncEnabled, --user-agent=Mozilla\u002f5.0 (W..., --headless, --whitelisted-ips], extensions: []}, goog:loggingPrefs: {browser: ALL, performance: ALL}, pageLoadStrategy: normal}]"}}

20:01:03.738 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. java.util.concurrent.TimeoutException
Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.80-trip20240626.el9.x86_64', java.version: '11.0.14.1'
Driver info: driver.version: unknown 
Host info: host: 'r100021942-71111192-0', ip: '10.119.101.54'
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:655)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:570)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:830)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:790)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
```

### Operating System

linux ubuntu

### Selenium version

java 4.23.0

### What are the browser(s) and version(s) where you see this issue?

chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 107

### Are you using Selenium Grid?

hub:4.17.0 node 4.23.0

**Comment by diemol** [comment]
Use the same versions in Hub and Nodes; also, Chrome 107 is rather old. You should update to the most recent versions.
