### ISSUE TITLE
[🐛 Bug]: does not start when calling the ChromeDriver function

### ISSUE THREAD

**Issue by argenalmaz00** [SeleniumHQ/selenium#14402]
### What happened?

I call the function `ChromeDriver` and immediately an error occurred

### How can we reproduce the issue?

```shell
`
        ChromeOptions options = new ChromeOptions();
        if (Main.myConfig.chromeOptions != null){
            if (!Main.myConfig.chromeOptions.arguments.isEmpty()){
                options.addArguments(Main.myConfig.chromeOptions.arguments);
            }
        }
        chrome = new ChromeDriver(options);
`
```

### Relevant log output

```shell
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Exception in thread "Thread-1" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}, error Command failed with code: -1073740791, executed: [--browser, chrome, --output, json]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 183, kind: AlreadyExists, message: "The file cannot be created because it already exists." }', src\main.rs:210:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:51)
	at com.my.paser.channel.myModule.PaserChannel.ChromePaserChannel.<init>(ChromePaserChannel.java:30)
	at com.my.paser.channel.Main$1.run(Main.java:71)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.openqa.selenium.WebDriverException: Command failed with code: -1073740791, executed: [--browser, chrome, --output, json]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 183, kind: AlreadyExists, message: "The file cannot be created because it already exists." }', src\main.rs:210:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:145)
	at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:302)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)
	... 8 more
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 183, kind: AlreadyExists, message: "The file cannot be created because it already exists." }', src\main.rs:210:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

	at org.openqa.selenium.json.Json.toType(Json.java:169)
	at org.openqa.selenium.json.Json.toType(Json.java:152)
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:130)
	... 10 more
Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: BOOLEAN. Last 0 characters read: 
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.11'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:443)
	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:331)
	at org.openqa.selenium.json.InstanceCoercer.lambda$apply$0(InstanceCoercer.java:76)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:174)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:149)
	at org.openqa.selenium.json.Json.toType(Json.java:206)
	at org.openqa.selenium.json.Json.toType(Json.java:167)
	... 12 more
```

### Operating System

Windows 11

### Selenium version

Java 17.0.11

### What are the browser(s) and version(s) where you see this issue?

Chrome 127.0.6533.101

### What are the browser driver(s) and version(s) where you see this issue?

selenium-java:4.13.0

**Comment by diemol** [comment]
Please update to 4.23.1 and let us know the results. If it fails, please enable debug logging.

**Comment by argenalmaz00** [comment]
chrome starts and abruptly closes and displays an error

by any chance do these dependencies also need to be updated?

`
    implementation 'org.seleniumhq.selenium:selenium-java:4.23.1'

    implementation 'org.seleniumhq.selenium:selenium-chrome-driver:3.141.59'
    implementation 'org.seleniumhq.selenium:selenium-http-jdk-client:4.13.0'
`

`
Exception in thread "Thread-1" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP2', ip: '169.254.228.3'
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], binary: C:\Program Files\Google\Chr..., extensions: []}}]}]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at kg.my.paser.channel.myModule.PaserChannel.ChromePaserChannel.<init>(ChromePaserChannel.java:30)
	at kg.my.paser.channel.Main$1.run(Main.java:71)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NoSuchMethodError: 'java.util.function.Supplier org.openqa.selenium.remote.http.HttpRequest.getContent()'
	at org.openqa.selenium.remote.http.jdk.JdkHttpMessages.notChunkingBodyPublisher(JdkHttpMessages.java:125)
	at org.openqa.selenium.remote.http.jdk.JdkHttpMessages.createRequest(JdkHttpMessages.java:83)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:366)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:347)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:89)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	... 9 more
`
