### ISSUE TITLE
[🐛 Bug]: Getting connect reset error and browser getting closed ( java.net.SocketException:)

### ISSUE THREAD

**Issue by Sowdy007** [SeleniumHQ/selenium#14401]
### What happened?

 Hi , I am facing issue for past 2 days. Please help me to figure out the issue

Currently using Selenium 4.20.0 version, Chrome 127, Driver 127

Exporting webdriver.chrome.driver as C:\Users\sowde\.cache\selenium\chromedriver\win64\127.0.6533.119\chromedriver.exe
WARNING: Unable to find an exact match for CDP version 127, returning the closest version; found: 124; Please update to a Selenium version that supports CDP version 127
Aug 15, 2024 10:22:26 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
java.net.SocketException: Connection reset
Connection reset
Chrome version : Version 127.0.6533.120 (Official Build) (64-bit)

### How can we reproduce the issue?

```shell
Try with below configurations

Currently using Selenium 4.20.0 version, Chrome 127, Driver 127
```

### Relevant log output

```shell
Aug 15, 2024 10:22:25 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 127, returning the closest version; found: 124; Please update to a Selenium version that supports CDP version 127
Aug 15, 2024 10:22:26 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1170)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:833)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:774)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:957)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:979)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:934)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:934)

15-Aug-2024 10:22:26:945 FATAL [PoolService-0] unknown error: session deleted because of page crash 
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
```

### Operating System

windows 10

### Selenium version

4.20.0

### What are the browser(s) and version(s) where you see this issue?

127.0.6533.120

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 127.0.6533.119

### Are you using Selenium Grid?

4.20.0

**Comment by diemol** [comment]
Update to Selenium 4.23.1

**Comment by Sowdy007** [comment]
Still I am facing the issue, even after updated to Selenium 4.23.1

**Comment by InvestigUser** [comment]
Same here:
It's happend because the Chrome version is  127.0.6533.120
And Chromedriver is 127.0.6533.119
Error is in french: "OSError: [WinError 193] %1 n’est pas une application Win32 valide"


I try on older computer with older version of chrome and It works (before I update Chrome, and that Chromedriver 127.0.6533.119 was installed.)
