### ISSUE TITLE
[🐛 Bug]: Debian: selenium-manager not found

### ISSUE THREAD

**Issue by blackbit42** [SeleniumHQ/selenium#14400]
### What happened?

I installed `python3-selenium` on a Debian stable amd64 system and ran the [example code](https://selenium-python.readthedocs.io/getting-started.html#simple-usage) from the selenium website:
```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

driver = webdriver.Firefox()
driver.get("http://www.python.org")
assert "Python" in driver.title
elem = driver.find_element(By.NAME, "q")
elem.clear()
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()
```

This yielded:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 97, in start
    path = SeleniumManager().driver_location(browser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/selenium_manager.py", line 75, in driver_location
    str(self.get_binary()),
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/selenium_manager.py", line 56, in get_binary
    raise SeleniumManagerException(f"{path} is missing.  Please open an issue on {tracker}")
selenium.common.exceptions.SeleniumManagerException: Message: /usr/lib/python3/dist-packages/selenium/webdriver/common/linux/selenium-manager is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blackbit/src/lang/python/selenium_playground/selenium_playground.py", line 5, in <module>
    driver = webdriver.Firefox()
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 194, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 100, in start
    raise err
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 218, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
```

To my surprise, I wasn't able to find a `selenium-manager` in any Debian package (checked with `apt-file search selenium-manager`).

Am I doing something stupid here?

### How can we reproduce the issue?

```shell
Install `python3-selenium` on a Debian stable system and run the example code mentioned above.
```

### Relevant log output

```shell
N/A. See above.
```

### Operating System

Debian

### Selenium version

4.8.3+dfsg-1

### What are the browser(s) and version(s) where you see this issue?

irrelevant

### What are the browser driver(s) and version(s) where you see this issue?

irrelevant

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
I am not sure where `python3-selenium` comes from, but the official package (with Selenium Manager inside it) can be found at https://pypi.org/project/selenium/.

If you are using a different packaging system, you need to configure the browser driver and browser on your own. 

https://www.selenium.dev/documentation/webdriver/drivers/service/
