### ISSUE TITLE
[🐛 Bug]: java.lang.ArrayIndexOutOfBoundsException: Index N out of bounds for length N

### ISSUE THREAD

**Issue by jherncandle** [SeleniumHQ/selenium#14414]
### What happened?

Starting my TestNG automated tests and setting capabilities for the driver I am using and every now and then I get this error in the selenium stack:

java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 11
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.accept(SortedOps.java:369)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1576)
	at java.base/java.util.TreeMap$EntrySpliterator.forEachRemaining(TreeMap.java:2962)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1601)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openqa.selenium.SharedCapabilitiesMethods.abbreviate(SharedCapabilitiesMethods.java:117)
	at org.openqa.selenium.SharedCapabilitiesMethods.toString(SharedCapabilitiesMethods.java:84)
	at org.openqa.selenium.MutableCapabilities.toString(MutableCapabilities.java:138)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at org.openqa.selenium.SharedCapabilitiesMethods.abbreviate(SharedCapabilitiesMethods.java:120)
	at org.openqa.selenium.SharedCapabilitiesMethods.lambda$abbreviate$4(SharedCapabilitiesMethods.java:116)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openqa.selenium.SharedCapabilitiesMethods.abbreviate(SharedCapabilitiesMethods.java:117)
	at org.openqa.selenium.SharedCapabilitiesMethods.toString(SharedCapabilitiesMethods.java:84)
	at org.openqa.selenium.MutableCapabilities.toString(MutableCapabilities.java:138)

### How can we reproduce the issue?

```shell
Not sure how since I observe the problem occasionally, not all the time, but it stems from a
AbstractDriverOptions.toString() call
         Log.trace("new remote webdriver: " + driverOptions.toString());

where driverOptions is:
        AbstractDriverOptions driverOptions = Browser.getDriverOptions(driverType);
and Browser.getDriverOptions is:
    public static AbstractDriverOptions getDriverOptions(Driver.DriverType type) {
        switch (type) {
            case CHROME:
                return (new Chrome()).getChromeOptions();
            case EDGE:
                return (new Edge()).getEdgeOptions();
            case FIREFOX:
                return (new Firefox()).getFirefoxOptions();
            case IE:
                return (new IE()).getInternetExplorerOptions();
            case SAFARI:
                return (new Safari()).getSafariOptions();
            default:
                throw new IllegalArgumentException("invalid driver type:" + type);
        }
    }
```

### Relevant log output

```shell
java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 11
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.accept(SortedOps.java:369)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1576)
	at java.base/java.util.TreeMap$EntrySpliterator.forEachRemaining(TreeMap.java:2962)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1601)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openqa.selenium.SharedCapabilitiesMethods.abbreviate(SharedCapabilitiesMethods.java:117)
	at org.openqa.selenium.SharedCapabilitiesMethods.toString(SharedCapabilitiesMethods.java:84)
	at org.openqa.selenium.MutableCapabilities.toString(MutableCapabilities.java:138)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at org.openqa.selenium.SharedCapabilitiesMethods.abbreviate(SharedCapabilitiesMethods.java:120)
	at org.openqa.selenium.SharedCapabilitiesMethods.lambda$abbreviate$4(SharedCapabilitiesMethods.java:116)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openqa.selenium.SharedCapabilitiesMethods.abbreviate(SharedCapabilitiesMethods.java:117)
	at org.openqa.selenium.SharedCapabilitiesMethods.toString(SharedCapabilitiesMethods.java:84)
	at org.openqa.selenium.MutableCapabilities.toString(MutableCapabilities.java:138)
```

### Operating System

We see this on Windows11, MacOs Ventura(13.5)

### Selenium version

Java 11 with Selenium 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome, Edge, Firefox and Safari

### What are the browser driver(s) and version(s) where you see this issue?

geckodriverVersion: 0.35.0, Safari browserVersion: 17.1, chromedriverVersion: 127.0.6533.72, MicrosoftEdge, browserVersion: 127.0.2651.74

### Are you using Selenium Grid?

No

**Comment by jherncandle** [comment]
Here is the code that produces the problem:
org.openqa.selenium.MutableCapabilities.toString();

**Comment by diemol** [comment]
That is not enough code to reproduce the issue. Can you please provide a complete test script that reproduces it? Otherwise this issue will stale.

**Comment by shbenzer** [comment]
This seems like correct functionality to me, shouldn't the indices for a list of length 11 be: [0,1,2,3,4,5,6,7,8,9,10]?

**Comment by jherncandle** [comment]
As I mentioned initially, the problem is intermittent, and yes, the exception is correct in that it points out that the abbreviate method is attempting to modify an element in a map beyond its boundary. 
I don't think the script(s) per se are relevant as this is the setup even before our script code gets executed, I would have thought that the stack would be sufficient.
Anyway, we can add a try catch block in our code to circumvent the error in the selenium code (or maybe it is in the JDK?) if the issue can't/won't be resolved, just thought I would let you know about it.

**Comment by diemol** [comment]
In any case we need a way to reproduce the issue, otherwise we cannot triage it.

**Comment by diemol** [comment]
We are closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/) that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/), where the community can also assist you.
