### ISSUE TITLE
[🐛 Bug]: Error running webdriver 4.23.0 with Chrome v127 (JS)

### ISSUE THREAD

**Issue by zlatinejc** [SeleniumHQ/selenium#14413]
### What happened?

It is not possible to run selenium tests using selenium-webdriver: 4.23.0 and Chrome: 127.0.6533.120.

I am running:
- Node 18.17.1
- selenium-webdriver: 4.23.0
- Chrome: 127.0.6533.120 (Official Build) (64-bit)

### How can we reproduce the issue?

```shell
const {Builder, Browser} = require('selenium-webdriver');
const Chrome = require('selenium-webdriver/chrome');

(async function helloSelenium() {
  const options = new Chrome.Options()
			.addArguments(/*'headless',*/ '--ignore-certificate-errors', 
				'--no-sandbox', 'window-size=1920,1080', 
				'--disable-dev-shm-usage',
				'--disable-search-engine-choice-screen');
		
		options.setUserPreferences({
			'download.prompt_for_download': false,
			'download.directory_upgrade': true,
			'download.default_directory': 'C:\\',
			'safebrowsing.enabled': true,
		});

  let driver = await new Builder().forBrowser('chrome').setChromeOptions(options).build();

  await driver.get('https://selenium.dev');

  await driver.quit();
})();
```

### Relevant log output

```shell
C:\Projects\issue-14353\node_modules\selenium-webdriver\lib\error.js:521
    let err = new ctor(data.message)
              ^

SessionNotCreatedError: session not created: DevToolsActivePort file doesn't exist
    at Object.throwDecodedError (C:\Projects\issue-14353\node_modules\selenium-webdriver\lib\error.js:521:15)
    at parseHttpResponse (C:\Projects\issue-14353\node_modules\selenium-webdriver\lib\http.js:514:13)        
    at Executor.execute (C:\Projects\issue-14353\node_modules\selenium-webdriver\lib\http.js:446:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: '\tGetHandleVerifier [0x00007FF604669642+30946]\n' +
    '\t(No symbol) [0x00007FF60461E3D9]\n' +
    '\t(No symbol) [0x00007FF604516FDA]\n' +
    '\t(No symbol) [0x00007FF604555CF5]\n' +
    '\t(No symbol) [0x00007FF6045516BC]\n' +
    '\t(No symbol) [0x00007FF6045978B9]\n' +
    '\t(No symbol) [0x00007FF604596F20]\n' +
    '\t(No symbol) [0x00007FF60458C813]\n' +
    '\t(No symbol) [0x00007FF60455A6E5]\n' +
    '\t(No symbol) [0x00007FF60455B021]\n' +
    '\tGetHandleVerifier [0x00007FF60479F84D+1301229]\n' +
    '\tGetHandleVerifier [0x00007FF6047ABDC7+1351783]\n' +
    '\tGetHandleVerifier [0x00007FF6047A2A13+1313971]\n' +
    '\tGetHandleVerifier [0x00007FF60469DD16+245686]\n' +
    '\t(No symbol) [0x00007FF60462759F]\n' +
    '\t(No symbol) [0x00007FF604623814]\n' +
    '\t(No symbol) [0x00007FF6046239A2]\n' +
    '\t(No symbol) [0x00007FF60461A3FF]\n' +
    '\tBaseThreadInitThunk [0x00007FF8E4177374+20]\n' +
    '\tRtlUserThreadStart [0x00007FF8E42BCC91+33]\n'
}
```

### Operating System

Windows 10

### Selenium version

Javascript

### What are the browser(s) and version(s) where you see this issue?

Chrome: 127.0.6533.120 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver: 127.0.6533.0

### Are you using Selenium Grid?

/

**Comment by diemol** [comment]
You need to toggle the options to see what this new version of Chrome needs, for example, removing `--disable-dev-shm-usage`. 

If that does not work, please report it to the Chrome folks.
