### ISSUE TITLE
[🐛 Bug]: How do I enable bidi

### ISSUE THREAD

**Issue by fenchu** [SeleniumHQ/selenium#14425]
### What happened?

testing out bidi on selenium v4.22.0, but how do I enable it, it refers to capabilities but that is under service.

and https://www.selenium.dev/documentation/webdriver/bidi/logging/ 
says: Remember that to use WebDriver BiDi, you must [enable it in Options](http://www.example.com/) 

just a placeholder?

### How can we reproduce the issue?

```shell
#!/usr/bin/env python3
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.service import Service as ChromeService

options = webdriver.ChromeOptions()
options.add_argument("--incognito")
options.add_argument("--disable-search-engine-choice-screen")

# do not need the first entry in list if chromedriver is in your PATH
service = ChromeService(service_args=['C:\\dist\\webdrivers\\chromedriver.exe', "--verbose", "--log-path=./chromedriver.log"])
driver = webdriver.Chrome(service=service, options=options)
driver.get('https://www.buypass.no')
log1 = []
driver.script.add_console_message_handler(log1.append)
WebDriverWait(driver, 5).until(lambda _: log1)
for l in log1:
    print(l)
```
```


### Relevant log output

```shell
DevTools listening on ws://127.0.0.1:49190/devtools/browser/716d0c15-2324-4465-9288-57e9aa0e649d
Traceback (most recent call last):
  File "C:\dist\trk-fullstack-test\bin\chrome-console.py", line 20, in <module>
    driver.script.add_console_message_handler(log1.append)
    ^^^^^^^^^^^^^
  File "C:\dist\venvs\trk-fullstack-test\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1076, in script
    self._start_bidi()
  File "C:\dist\venvs\trk-fullstack-test\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1087, in _start_bidi
    raise WebDriverException("Unable to find url to connect to from capabilities")
selenium.common.exceptions.WebDriverException: Message: Unable to find url to connect to from capabilities

```
```


### Operating System

windows 11

### Selenium version

python 3.12.5

### What are the browser(s) and version(s) where you see this issue?

Chrome v127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 127.0.6533.119

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment]
We need to improve the docs there, any help is appreciated. 

For now, you can check https://www.selenium.dev/blog/2024/selenium-4-22-released/
