### ISSUE TITLE
[🐛 Bug]: Getting timeout error while executing scripts in parallel in Selenium 4.16.1 Grid

### ISSUE THREAD

**Issue by snehalbhosle** [SeleniumHQ/selenium#14477]
### What happened?

When I am executing selenium scripts in parallel using jenkins with multiple builds it is throwing below error in Selenium Grid 4.16.1 spun through Kubernetes and Java 17:
 org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 10.000
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]             (Session info: chrome=120.0.6099.109)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           Build info: version: '4.16.1', revision: '9b4c83354e'
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1035-gkeop', java.version: '17.0.2'
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           Driver info: org.openqa.selenium.remote.RemoteWebDriver
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           Command: [670fceda27ee841998ee7bd7ca3859c0, screenshot {}]
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 120.0.6099.109, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {args: [start-maximized, start-fullscreen, remote-allow-origins=*, remote-debugging-pipe, --no-sandbox, --disable-extension, --dns-prefetch-disable, --disable-gpu, --ignore-certificate-errors, --force-device-scale-factor=1], extensions: []}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: wss://selenium-dev.dd.c..., se:vnc: wss://selenium-dev.dd.c..., se:vncEnabled: true, se:vncLocalAddress: ws://10.207.80.95:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}

Dependencies used:
    api group: 'org.mockito', name: 'mockito-core', version: '2.25.0'
    api group: 'com.atlassian.oai', name: 'swagger-request-validator-restassured', version: '2.0.0-rc1'
    api 'org.codehaus.groovy:groovy-all:3.0.22'
    api 'com.google.code.gson:gson:2.8.5'
    api 'io.rest-assured:rest-assured:3.3.0'
    api 'com.google.inject:guice:4.2.2'
    api group: 'com.google.guava', name: 'guava', version: '28.1-jre'
    api 'info.cukes:cucumber-guice:1.2.5'
    api 'info.cukes:cucumber-junit:1.2.5'
    api 'junit:junit:4.12'
    api group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.16.1'
    api group: 'io.appium', name: 'java-client', version: '8.5.0'
    api group: 'commons-dbutils', name: 'commons-dbutils', version: '1.7'
    api group: 'org.apache.kafka', name: 'kafka-clients', version: '0.10.1.0'
    api group: "com.typesafe.akka", name: "akka-stream-kafka_2.11", version: "0.13"
    api group: 'org.apache.kafka', name: 'kafka_2.11', version: '0.10.1.0'
    api group: 'org.apache.zookeeper', name: 'zookeeper', version: '3.4.12'
    api group: 'net.masterthought', name: 'cucumber-reporting', version: '3.17.1'
    api group: 'org.awaitility', name: 'awaitility', version: '3.1.6'
    api group: 'org.seleniumhq.selenium', name: 'htmlunit-driver', version: '2.34.0'
    api group: 'com.microsoft.sqlserver', name: 'sqljdbc4', version: '4.0'
//    compile group: 'com.denodo', name: 'denododriver', version: '6.0'
    api group: 'org.apache.commons', name: 'commons-collections4', version: '4.3'
    api 'org.apache.poi:poi:5.0.0'
    api 'org.apache.poi:poi-ooxml:5.0.0'
    api group: 'org.skyscreamer', name: 'jsonassert', version: '1.5.0'
    api group: 'com.datastax.cassandra', name: 'cassandra-driver-core', version: '3.6.0'
    api group: 'com.datastax.cassandra', name: 'cassandra-driver-mapping', version: '3.6.0'
    api group: 'com.datastax.cassandra', name: 'cassandra-driver-extras', version: '3.6.0'
    api group: 'org.apache.pdfbox', name: 'pdfbox', version: '2.0.16'
    api group: 'io.qameta.allure', name: 'allure-cucumber-jvm', version: '2.13.0'
    api group: 'org.apache.avro', name: 'avro', version: '1.8.2'
    api 'com.google.cloud:google-cloud-spanner-jdbc:0.4.0'
    api group: 'mysql', name: 'mysql-connector-java', version: '8.0.16'
    api group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '5.6.3'
    api group: 'com.squareup.okhttp3', name: 'okhttp', version: '3.11.0'
    api group: 'io.netty', name: 'netty-all', version: '4.1.110.Final'
    // https://mvnrepository.com/artifact/com.github.mkolisnyk/cucumber-runner
    api group: 'com.github.mkolisnyk', name: 'cucumber-runner', version: '1.3.5'
    api group: 'com.luhuiguo', name: 'aspose-pdf', version: '23.1'
 

### How can we reproduce the issue?

```shell
Not sure how it can be reproduced at your end
```

### Relevant log output

```shell
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 10.000
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]             (Session info: chrome=120.0.6099.109)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           Build info: version: '4.16.1', revision: '9b4c83354e'
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1035-gkeop', java.version: '17.0.2'
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           Driver info: org.openqa.selenium.remote.RemoteWebDriver
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           Command: [670fceda27ee841998ee7bd7ca3859c0, screenshot {}]
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 120.0.6099.109, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {args: [start-maximized, start-fullscreen, remote-allow-origins=*, remote-debugging-pipe, --no-sandbox, --disable-extension, --dns-prefetch-disable, --disable-gpu, --ignore-certificate-errors, --force-device-scale-factor=1], extensions: []}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: wss://selenium-dev.dd.c..., se:vnc: wss://selenium-dev.dd.c..., se:vncEnabled: true, se:vncLocalAddress: ws://10.207.80.95:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           Session ID: 670fceda27ee841998ee7bd7ca3859c0
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:596)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:326)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at jdk.internal.reflect.GeneratedMethodAccessor242.invoke(Unknown Source)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at dd.beacon.ui.element.EventFiringDriver$2.invoke(EventFiringDriver.java:84)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at jdk.proxy3/jdk.proxy3.$Proxy35.getScreenshotAs(Unknown Source)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at dd.beacon.ui.element.EventFiringDriver.getScreenshotAs(EventFiringDriver.java:270)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at dd.beacon.cucumber.GenericHooks.afterUIScenario(GenericHooks.java:149)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at cucumber.runtime.Utils$1.call(Utils.java:40)
10:13:08  2024-09-06T15:13:08.208+0000 [DEBUG] [TestEventLogger]           	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at cucumber.runtime.Utils.invoke(Utils.java:34)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at cucumber.runtime.ExtendedRuntime.runHookIfTagsMatch(ExtendedRuntime.java:236)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at cucumber.runtime.ExtendedRuntime.runHooks(ExtendedRuntime.java:224)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at cucumber.runtime.ExtendedRuntime.runAfterHooks(ExtendedRuntime.java:218)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at com.github.mkolisnyk.cucumber.runner.ExtendedExecutionUnitRunner.run(ExtendedExecutionUnitRunner.java:32)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at com.github.mkolisnyk.cucumber.runner.ExtendedFeatureRunner.runChild(ExtendedFeatureRunner.java:81)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at com.github.mkolisnyk.cucumber.runner.ExtendedFeatureRunner.runChild(ExtendedFeatureRunner.java:23)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at dd.beacon.cucumber.CustomCucumber.runChild(CustomCucumber.java:129)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at dd.beacon.cucumber.CustomCucumber.runChild(CustomCucumber.java:36)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at dd.beacon.cucumber.CustomCucumber.run(CustomCucumber.java:136)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
10:13:08  2024-09-06T15:13:08.209+0000 [DEBUG] [TestEventLogger]           	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

### Operating System

Linux

### Selenium version

JAva 17

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.109

### What are the browser driver(s) and version(s) where you see this issue?

120.0.6099.109

### Are you using Selenium Grid?

Selenium Grid 4.16.1

**Comment by pujagani** [comment]
Can you please try the latest Grid version? We don't do patch releases.

**Comment by diemol** [comment]
We are closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/) that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/), where the community can also assist you.
