### ISSUE TITLE
[🐛 Bug]: Getting issue with Selenium 4.6.0 - Unable to launch chromedriver with display of Exception as  java.lang.IllegalStateException:

### ISSUE THREAD

**Issue by karishmayadava23** [SeleniumHQ/selenium#14487]
### What happened?

Using Selenium Verison - 4.6.0
Jdk - 19
Below is the code

`package basics;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.manager.SeleniumManager;

public class LaunchBrowser {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		WebDriver driver  =  new ChromeDriver();
		driver.get("https://google.com");
		System.out.println(driver.getTitle());
		driver.close();
	}

}
`

### How can we reproduce the issue?

```shell
Use the above versions and call Chromedriver
```

### Relevant log output

```shell
Sept 11, 2024 4:51:22 PM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Error running command: [C:\Users\karis\AppData\Local\Temp\selenium-manager12238203631445002804995746287263881\selenium-manager.exe, --driver, chromedriver]
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.1'
Driver info: driver.version: ChromeDriver
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:148)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:39)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:233)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:450)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:128)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:49)
	at basics.LaunchBrowser.main(LaunchBrowser.java:14)
![Screenshot 2024-09-11 170125](https://github.com/user-attachments/assets/ff452bd1-0f96-468c-82ff-f02647bc9646)
```

### Operating System

Windows 11 Home Single Language

### Selenium version

Selenium - 4.6.0

### What are the browser(s) and version(s) where you see this issue?

128.0.6613.138 

### What are the browser driver(s) and version(s) where you see this issue?

Selenium manager should auto download

**Comment by diemol** [comment]
You need to upgrade to the latest Selenium (4.24 currently).
