### ISSUE TITLE
[🐛 Bug]: Failed to initialize BiDi Mapper when starting Chrome with Profile

### ISSUE THREAD

**Issue by huyennguyen-katalon** [SeleniumHQ/selenium#14496]
### What happened?

I run automation test with Chrome Profile and enable Bidirectional by adding property `webSockerUrl: true`. It starts with right Chrome Profile for 1 seconds and crash with following message:
```
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Failed to initialize BiDi Mapper: TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at generatePage (<anonymous>:888:1056)
    at <anonymous>:906:295
    at <anonymous>:906:1106
  (Session info: chrome=128.0.6613.138) 
Host info: host: 'Huyens-MacBook-Pro-2.local', ip: 'fe80:0:0:0:18ec:1fad:f951:2306%en0'
Build info: version: '4.22.0', revision: 'c5f3146703'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.4.1', java.version: '17.0.10'
```
- When I turn off Bidirectional, it works well. But I need Bidirectional to add some scripts and take some screenshots.
- When I run without Chrome Profile, it also works well with temp Profile Selenium created. But I cannot test without Profile.
- I tried to add possible Desired Capabilities as below but seems not work:
```
{args: [
 --enable-logging=stderr, 
 --user-data-dir=/Users/huye..., 
 --profile-directory=Profile 6, 
 --disable-web-security,
 --remote-allow-origins=*,
 --allow-running-insecure-content,
 --disable-client-side-phishing-detection,
 --disable-dev-shm-usage,
 --disable-gpu,
 --disable-domain-reliability,
 --disable-default-apps,
 --no-default-browser-check,
 --no-sandbox]}
```
- I also try to allow third-party cookie and disable Safe browsing in Chrome setting, not work either.

### How can we reproduce the issue?

```java
import org.openqa.selenium.MutableCapabilities;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;

System.setProperty("webdriver.chrome.driver", <Path to Chrome Driver>);
ChromeOptions options = new ChromeOptions();
options.addArguments("--user-data-dir=<user data dir>", "--profile-directory=<Profile name>");
options.setCapability("webSocketUrl", true);
ChromeDriver driver = new ChromeDriver(options);
driver.get("https://google.com");
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Failed to initialize BiDi Mapper: TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at generatePage (<anonymous>:888:1056)
    at <anonymous>:906:295
    at <anonymous>:906:1106
  (Session info: chrome=128.0.6613.138) 
Host info: host: '192.168.1.13', ip: '2405:4802:8036:4000:9979:b98c:85ad:8dcd%en0'
Build info: version: '4.22.0', revision: 'c5f3146703'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.4.1', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--user-data-dir=/Users/huye..., --profile-directory=Profile 6], extensions: []}, webSocketUrl: true}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:114)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:232)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
```

### Operating System

Mac Ventura

### Selenium versio
- Java Coretto 17
- Selenium 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 128.0.6613.138

### What are the browser driver(s) and version(s) where you see this issue?

 Chrome Driver 128.0.6613.137

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment]
I think someone recently reported the same. Please report it to the Chrome folks and share the link report here so it can be traced.

**Comment by MJB222398** [comment]
@huyennguyen-katalon This issue is affecting me too, did you report it to Chrome?

**Comment by huyennguyen-katalon** [comment]
Yes, @MJB222398 I have created here, but still waiting for their response https://issues.chromium.org/issues/366886096
