### ISSUE TITLE
Program freezes when accessing Chrome driver after clicking __blank link which opens a xml

### ISSUE THREAD

**Issue by conradoplg** [SeleniumHQ/selenium#1450]
Python 2.7.9, Ubuntu 14.04.3 x64, Selenium 2.48.0, Chrome 47.0.2526.106 (64-bit), ChromeDriver 2.20

When using Chrome driver, if you click a link with selenium with target="_blank", and the linked url points to a xml file, then when switching to the xml window and accessing driver properties such as current_url will freeze the script. If you Ctrl+C then you get this backtrace:

````pytb
Traceback (most recent call last):
  File "/tmp/bug.py", line 10, in <module>
    print driver.current_url
  File "/tmp/.env/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "/tmp/.env/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 199, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/tmp/.env/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 395, in execute
    return self._request(command_info[0], url, body=data)
  File "/tmp/.env/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 426, in _request
    resp = self._conn.getresponse()
  File "/opt/python/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/opt/python/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/opt/python/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/opt/python/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
````

The attached script and files reproduce the problem and are also listed below

bug.py
````py
from selenium import webdriver

chrome_profile = webdriver.ChromeOptions()
driver = webdriver.Chrome(chrome_options=chrome_profile)

driver.get('file:///tmp/index.html')
a = driver.find_element_by_tag_name('a')
a.click()
driver.switch_to.window(driver.window_handles[1])
print driver.current_url
````

index.html
````html
<!doctype html>
<a target="_blank" href="doc.xml">doc</a>
````

doc.xml
````xml
<?xml version="1.0" encoding="UTF-8"?>
<doc></doc>
````

[freeze_open_blank_xml.zip](https://github.com/SeleniumHQ/selenium/files/81354/freeze_open_blank_xml.zip)

**Comment by lukeis** [comment]
chromedriver specific issues should be logged on that project:
https://bugs.chromium.org/p/chromedriver/issues/list
