### ISSUE TITLE
[🐛 Bug]: Tracing seems to be affected with the Selenium version org.seleniumhq.selenium:selenium-java:4.24.0

### ISSUE THREAD

**Issue by rishabhjainrj01** [SeleniumHQ/selenium#14519]
### What happened?

I do have **tracing support present in my framework**, 
and using below libraries for same
        // For Jaeger Tracing
        exporter_otlp           : 'io.opentelemetry:opentelemetry-exporter-otlp:1.42.1',
        exporter_jaeger         : 'io.opentelemetry:opentelemetry-exporter-jaeger:1.34.1',
                 

with **java11 and selenium 4.23**
this was working fine and i was able to push traces to selenium jaeger, was able to view them on the jaegerUI

------------------------------------

Now I have recently upgraded my automation repo from java11 to **java17** and have also upgrade from selenium 4.23 to **selenium 4.24**, 
But with this upgrade i have started observing issues in tracing support, 

**it shows below exception** 
java.util.ServiceConfigurationError: io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider: Provider io.opentelemetry.exporter.logging.otlp.internal.LoggingSpanExporterProvider not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at io.opentelemetry.sdk.autoconfigure.internal.SpiHelper.load(SpiHelper.java:152)
        at io.opentelemetry.sdk.autoconfigure.internal.SpiHelper.loadConfigurable(SpiHelper.java:70)
        at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.spanExporterSpiManager(SpanExporterConfiguration.java:82)
        at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureSpanExporters(SpanExporterConfiguration.java:64)
        at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:58)
        at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:465)
        at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.createTracer(OpenTelemetryTracer.java:85)
        at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.getInstance(OpenTelemetryTracer.java:59)
        at org.openqa.selenium.remote.RemoteWebDriver.createExecutor(RemoteWebDriver.java:197)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
        at com.spr.core.ui.browser.Browser.createDriverWithTimeout(Browser.java:120)
        at com.spr.core.ui.browser.Browser.getRemoteDriver(Browser.java:40)
        at com.spr.core.ui.WebDriverThread.setExecutionStyle(WebDriverThread.java:152)
        at com.spr.core.ui.WebDriverThread.getDriver(WebDriverThread.java:65)
        at com.spr.core.ui.BrowserInit.lambda$initDriver$0(BrowserInit.java:54)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at com.spr.core.ui.BrowserInit.getDriver(BrowserInit.java:91)
        at com.spr.core.ui.listeners.ReportingEventListener.afterInvocation(ReportingEventListener.java:123)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:59)
        at org.testng.internal.invokers.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:80)
        at org.testng.internal.invokers.TestInvoker.invokeListenersForSkippedTestResult(TestInvoker.java:498)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:599)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
        
        
        **I have tried using latest dependencies for both of these but it did not work,** 
        opentelemetry-exporter-otlp
        opentelemetry-exporter-jaeger
   
        **I have also tried adding below flag as suggested** but this also did not work
        -Dotel.java.global-autoconfigure.enabled=true

**Now when i am adding above flag** 

I am seeing some different exception, which is 

`java.util.ServiceConfigurationError: io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider: Provider io.opentelemetry.exporter.logging.otlp.internal.LoggingSpanExporterProvider not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at io.opentelemetry.sdk.autoconfigure.internal.SpiHelper.load(SpiHelper.java:152)
        at io.opentelemetry.sdk.autoconfigure.internal.SpiHelper.loadConfigurable(SpiHelper.java:70)
        at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.spanExporterSpiManager(SpanExporterConfiguration.java:82)
        at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureSpanExporters(SpanExporterConfiguration.java:64)
        at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:58)
        at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:465)
        at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.createTracer(OpenTelemetryTracer.java:85)
        at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.getInstance(OpenTelemetryTracer.java:59)
        at org.openqa.selenium.remote.RemoteWebDriver.createExecutor(RemoteWebDriver.java:197)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
        at com.spr.core.ui.browser.Browser.createDriverWithTimeout(Browser.java:120)
        at com.spr.core.ui.browser.Browser.getRemoteDriver(Browser.java:40)
        at com.spr.core.ui.WebDriverThread.setExecutionStyle(WebDriverThread.java:152)
        at com.spr.core.ui.WebDriverThread.getDriver(WebDriverThread.java:65)
        at com.spr.core.ui.BrowserInit.lambda$initDriver$0(BrowserInit.java:54)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at com.spr.core.ui.BrowserInit.getDriver(BrowserInit.java:91)
        at com.spr.core.ui.BrowserInit.checkSession(BrowserInit.java:72)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.MethodInvocationHelper$2.runConfigurationMethod(MethodInvocationHelper.java:453)
        at com.spr.core.ui.BrowserInit.run(BrowserInit.java:324)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeConfigurable(MethodInvocationHelper.java:467)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:387)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
        at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:577)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)`
        

### How can we reproduce the issue?

```shell
Use java 17 and sel version 4.24, 

and 

below dependencies for traces 
        exporter_otlp           : 'io.opentelemetry:opentelemetry-exporter-otlp:1.42.1',
        exporter_jaeger         : 'io.opentelemetry:opentelemetry-exporter-jaeger:1.34.1',


try exporting traces from your tests to jaeger.
```

### Relevant log output

```shell
java.util.ServiceConfigurationError: io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider: Provider io.opentelemetry.exporter.logging.otlp.internal.LoggingSpanExporterProvider not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at io.opentelemetry.sdk.autoconfigure.internal.SpiHelper.load(SpiHelper.java:152)
        at io.opentelemetry.sdk.autoconfigure.internal.SpiHelper.loadConfigurable(SpiHelper.java:70)
        at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.spanExporterSpiManager(SpanExporterConfiguration.java:82)
        at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureSpanExporters(SpanExporterConfiguration.java:64)
        at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:58)
        at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:465)
        at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.createTracer(OpenTelemetryTracer.java:85)
        at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.getInstance(OpenTelemetryTracer.java:59)
        at org.openqa.selenium.remote.RemoteWebDriver.createExecutor(RemoteWebDriver.java:197)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
        at com.spr.core.ui.browser.Browser.createDriverWithTimeout(Browser.java:120)
        at com.spr.core.ui.browser.Browser.getRemoteDriver(Browser.java:40)
        at com.spr.core.ui.WebDriverThread.setExecutionStyle(WebDriverThread.java:152)
        at com.spr.core.ui.WebDriverThread.getDriver(WebDriverThread.java:65)
        at com.spr.core.ui.BrowserInit.lambda$initDriver$0(BrowserInit.java:54)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at com.spr.core.ui.BrowserInit.getDriver(BrowserInit.java:91)
        at com.spr.core.ui.listeners.ReportingEventListener.afterInvocation(ReportingEventListener.java:123)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:59)
        at org.testng.internal.invokers.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:80)
        at org.testng.internal.invokers.TestInvoker.invokeListenersForSkippedTestResult(TestInvoker.java:498)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:599)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
```

### Operating System

macOS

### Selenium version

4.24

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

### Are you using Selenium Grid?

4.23.0

**Comment by 1234abd** [comment]
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by rishabhjainrj01** [comment]
cc: @rookieInTraining

**Comment by rishabhjainrj01** [comment]
https://github.com/SeleniumHQ/selenium/commit/c8676eff107a7e5e617c6fc953baad45305cc680#diff-0cf141b01e48a733ec9037c51d8e610e7727d05a6b79aa0176def7c3a0fc311bR142

i have also came across this recent change, 
please help in understanding what is changed here that is affecting this.

**Comment by rishabhjainrj01** [comment]
@diemol 
Can you please have a look here once

**Comment by diemol** [comment]
The change does not affect tracing, it simply offers a way to disable it.

**Comment by rishabhjainrj01** [comment]
okay, 
what about the stacktraces that i have started observing here, 
anything on this please ?

cc: @pujagani

**Comment by joerg1985** [comment]
@rishabhjain-qait i think the jaeger exporter is outdated, so this might be related to incompatible versions in the transitive dependencies 
https://opentelemetry.io/blog/2023/jaeger-exporter-collector-migration/

**Comment by rishabhjainrj01** [comment]
Thanks @joerg1985, this helped 

System.setProperty("otel.traces.exporter", "jaeger");
io.opentelemetry:opentelemetry-exporter-jaeger:1.34.1
**I was using above** 

System.setProperty("otel.traces.exporter", "otlp");
i have used **io.opentelemetry:opentelemetry-exporter-logging-otlp:1.42.1**
**now i have moved to above** 

and it seems to have worked fine without any issues
