### ISSUE TITLE
[🐛 Bug]: self.execute(Command.NEW_SESSION, caps)["value"] on very minimal script

### ISSUE THREAD

**Issue by GregB98** [SeleniumHQ/selenium#14535]
### What happened?

Selenium fails to start driver even tough wether it is in the path, not in the path, is in C:\Windows, nothing helps

### How can we reproduce the issue?

```shell
I do not know because I can't figure it out

Code: 
from selenium import webdriver as wd
driver = wd.Chrome()
driver.get('https://google.com')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "c:\Users\x\Documents\EOD automatizalas\eodautmatizalas.py", line 5, in <module>
    driver = webdriver.Chrome()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\x\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\x\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "C:\Users\x\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\x\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: <!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
</body>
</html>
```

### Operating System

Windows 10

### Selenium version

4.25.0

### What are the browser(s) and version(s) where you see this issue?

chrome 129

### What are the browser driver(s) and version(s) where you see this issue?

chrome 129.0.668

**Comment by navin772** [comment]
Hi @GregB98, you mentioned `self.execute(Command.NEW_SESSION, caps)["value"]` in the issue title but the reproducible code doesn't include this, can you give a standalone minimal reproducible example that can be run to get this issue?

**Comment by diemol** [comment]
I will close this as the issue has not had any more activity.
