### ISSUE TITLE
[🐛 Bug]: Ruby - Selenium Manager throwing error

### ISSUE THREAD

**Issue by kevin-roe** [SeleniumHQ/selenium#14622]
### What happened?

When running tests today Selenium started failing with this message:

```
/Users/kevin.roe/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/selenium_manager.rb:79:in `run': undefined method `positive?' for nil:NilClass (NoMethodError)

          return result unless status.exitstatus.positive? || result.nil?
```

I was able to reproduce the issue with this simple code:

```ruby
require 'selenium-webdriver'

driver = Selenium::WebDriver.for :chrome
driver.get("https://www.google.com")
driver.quit
```

I tracked it down to [here](https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/common/selenium_manager.rb#L63), where the command is returning `pid 4961 SIGKILL (signal 9)` on the `status` on line 67, causing line 79 to eventually cause the process to die. 

This randomly started happening to me earlier today, and eventually 4 other members of my team started experiencing this as well.  I don't have a ton of knowledge on how Selenium Manager works, but due to the random nature of this I imagine some process on my machine is pulling in some updated version of the `bin/macos/seneium-manager` executable and that is causing problems, but that's just my best guess.   

### How can we reproduce the issue?

```shell
gem install selenium-webdriver -v 4.25.0


```ruby
require 'selenium-webdriver'

driver = Selenium::WebDriver.for :chrome
driver.get("https://www.google.com")
driver.quit
```
```


### Relevant log output

```shell
2024-10-18 13:49:48 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2024-10-18 13:49:48 DEBUG Selenium [:selenium_manager] Selenium Manager binary found at /Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/bin/macos/selenium-manager 
2024-10-18 13:49:48 DEBUG Selenium [:selenium_manager] Executing Process ["/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/bin/macos/selenium-manager", "--browser", "chrome", "--language-binding", "ruby", "--output", "json", "--debug"] 
2024-10-18 13:49:48 ERROR Selenium Exception occurred: undefined method `positive?' for nil:NilClass

          return result unless status.exitstatus.positive? || result.nil?
                                                ^^^^^^^^^^
2024-10-18 13:49:48 ERROR Selenium Backtrace:
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/selenium_manager.rb:79:in `run'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/selenium_manager.rb:44:in `binary_paths'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/driver_finder.rb:58:in `paths'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/driver_finder.rb:35:in `browser_path'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/driver_finder.rb:43:in `browser_path?'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/local_driver.rb:43:in `process_options'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/local_driver.rb:27:in `initialize_local_driver'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/chrome/driver.rb:34:in `initialize'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver.rb:89:in `for'
	/Users/kevin.roe/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/qa_automation_sdk-3.4.7/lib/qa_automation_sdk/drivers/selenium_adapter.rb:19:in `create_webdriver'
```

### Operating System

MacOS Sequoia

### Selenium version

Ruby 4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 130.0.6723.59, Firefox 131.0.3

### What are the browser driver(s) and version(s) where you see this issue?

Can't get the driver - that is the problem

### Are you using Selenium Grid?

No

**Comment by kevin-roe** [comment]
We were able to fix the problem by reverting back to `4.24.0`.  We also had to uninstall `4.25.0` for the fix to work

**Comment by kevin-roe** [comment]
Is there an update on this?  We would prefer not have to remain on 4.24.0 for the foreseeable future.

**Comment by titusfortner** [comment]
Sorry it has taken so long to address this. Should be available for next release
