### ISSUE TITLE
Duration value for swipe.

### ISSUE THREAD

**Issue by johnny2k** [SeleniumHQ/selenium#1473]
I'm trying to set a value for the duration of a swipe. Using Appium and the Ruby appium_lib Gem. 

The following log shows that only a duration of "0" is accepted.

The wording in the error message seems unclear as well. What is the range of allowed values? Is it 0.5 and above IF the value is an integer, integers less than 60? Floats or ints between 0.5 and 60?

```
[188] pry(main)> swipinate(0)
duration: 0
#<Appium::TouchAction:0x007f9e22ac1ad0 @actions=[{:action=>:press, :options=>{:x=>173, :y=>921.26}}, {:action=>:wait, :options=>{:ms=>0}}, {:action=>:moveTo, :options=>{:x=>173, :y=>111}}, {:action=>:release}]>
[189] pry(main)> swipinate(10)
duration: 10
Selenium::WebDriver::Error::JavascriptError: duration value must be greater than or equal to 0.5 or less than 60
from /Users/jkohls/.rvm/gems/ruby-head@calabash_android/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
[190] pry(main)> swipinate(0.6)
duration: 0.6
Selenium::WebDriver::Error::JavascriptError: duration value must be greater than or equal to 0.5 or less than 60
from /Users/jkohls/.rvm/gems/ruby-head@calabash_android/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
[191] pry(main)> swipinate(59)
duration: 59
Selenium::WebDriver::Error::JavascriptError: duration value must be greater than or equal to 0.5 or less than 60
from /Users/jkohls/.rvm/gems/ruby-head@calabash_android/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
```

**Comment by titusfortner** [comment]
milliseconds - https://github.com/appium/ruby_lib/issues/178
