### ISSUE TITLE
[🐛 Bug]: Selenium driver (C#) doesn't clean up session if timing out when creating session?

### ISSUE THREAD

**Issue by genne** [SeleniumHQ/selenium#14743]
### What happened?

I often encounter timeout errors when attempting to create sessions:

```
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://4.207.73.132:4444/wd/hub/session timed out after 60 seconds. 
  ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing. 
  ---> System.TimeoutException: The operation was canceled. 
  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. 
  ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. 
  ---> System.Net.Sockets.SocketException (125): Operation canceled 
    --- End of inner exception stack trace --- 
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) 
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) 
    at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async) 
    at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
    --- End of inner exception stack trace --- 
    at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) 
    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) 
    --- End of inner exception stack trace --- 
    --- End of inner exception stack trace --- 
    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) 
    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) 
    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo) 
    at OpenQA.Selenium.Remote.HttpCommandExecutor.ExecuteAsync(Command commandToExecute) 
    --- End of inner exception stack trace --- 
    at OpenQA.Selenium.Remote.HttpCommandExecutor.ExecuteAsync(Command commandToExecute) 
    at OpenQA.Selenium.WebDriver.ExecuteAsync(String driverCommandToExecute, Dictionary`2 parameters) 
    at OpenQA.Selenium.WebDriver.StartSession(ICapabilities capabilities) 
    at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities) 
```

At the same time, I notice the grid queue builds up, and the sessions seem to run for a couple of minutes before being closed:

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/b3f4dcd4-5297-42fc-b7e0-aeafe77622c8">

From analyzing the code, it appears that StartSession doesn’t clean up properly when it fails:

```c#
Response response = this.Execute(DriverCommand.NewSession, parameters);
```

If this throws an exception, the sessionId is never set:

```c#
this.sessionId = new SessionId(response.SessionId);
```

As a result, Dispose does nothing:

```c#
if (this.sessionId != null)
    this.Execute(DriverCommand.Quit, (Dictionary<string, object>) null);
```

The session is still created, but since the session ID is never returned to the client, it remains stuck until it’s automatically terminated after a few minutes. This also causes subsequent sessions to time out as they wait for the hung session, which further compounds the issue by adding more stuck sessions to the queue.

### How can we reproduce the issue?

```shell
#
    
    [Test]
    public void Timeout()
    {
        var seleniumRemoteUrl = "http://localhost:4444/wd/hub";

        {
            // Create new session
            using var existingSession = new RemoteWebDriver(new(seleniumRemoteUrl), new ChromeOptions());
            
            // Second session will timeout as the first session is still running
            Assert.Throws<WebDriverException>(() =>
                new RemoteWebDriver(new(seleniumRemoteUrl), new ChromeOptions())
            );
            
            // Scope ends, session is closed
        }

        // This now fails as the second session wasn't closed properly
        Assert.DoesNotThrow(() =>
        {
            using var newSession = new RemoteWebDriver(new(seleniumRemoteUrl), new ChromeOptions());
        });
    }
```

### Relevant log output

```shell
Expected: No Exception to be thrown
  But was:  <OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:4444/wd/hub/session timed out after 60 seconds.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.ExecuteAsync(Command commandToExecute)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.ExecuteAsync(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.ExecuteAsync(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities capabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities capabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities capabilities, TimeSpan commandTimeout)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities capabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, DriverOptions options)
```

### Operating System

Both macOS 14.6.1 and Linux

### Selenium version

C# 4.24.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Selenium.WebDriver.ChromeDriver 130.0.6723.11600

### Are you using Selenium Grid?

4.26.0 (revision 69f9e5e)

**Comment by nvborisenko** [comment]
It is impossible to dispose a session which doesn't exists. Why the session could not be created in time... this should be resolved. @genne any ideas?

**Comment by genne** [comment]
> It is impossible to dispose a session which doesn't exists. Why the session could not be created in time... this should be resolved. @genne any ideas?

@nvborisenko perhaps instead of relying on the session id returned by the endpoint, you include a request id (GUID) when creating the session? Then you can use that to kill the session?

```c#    
var requestId = Guid.New();
parameters["RequestId"] = requestId;
try
{
    Response response = this.Execute(DriverCommand.NewSession, parameters);
}
catch
{
    var quitParameters = new()...;
    quitParameters["RequestId"] = requestId;
    this.Execute(DriverCommand.Quit, quitParameters);
}
```

**Comment by nvborisenko** [comment]
@diemol from one point of you it works as expected. It is normal just to close this issue.

But from other point of view the issue looks like an issue and, seems, it is valid.

**Comment by joerg1985** [comment]
@nvborisenko This might be an issue of unaligned timeouts?
The client timeout should be bigger than the `--session-timeout` used by the grid to avoid this.
The default client timeout of the #c client is 60s and default session-timeout of the grid is 300s.

It is in general a good idea to have a client timeout >300s, see https://github.com/SeleniumHQ/selenium/issues/12368#issuecomment-1843214009

**Comment by nvborisenko** [comment]
We can increase default timeout, but it is not a solution :( The issue here is about how to determine that client is offline, and server can clean up all resources potentially allocated by the client.

**Comment by joerg1985** [comment]
I have recently added canceling the upstream request in https://github.com/SeleniumHQ/selenium/commit/71753492d070eb910dafbacfb78e73c0f556e39e so the grid should be able to stop the new session request without a request id.

**Comment by nvborisenko** [comment]
So it should be implicitly fixed in the next release of Grid?

**Comment by joerg1985** [comment]
Maybe, it depends on how the webdriver does handle the client closing the socket before the browser has been started.

In case the webdriver does not propper handle this, the grid could handle it.

**Comment by joerg1985** [comment]
I have created `DistributedTest#clientTimeoutDoesNotLeakARunningBrowser` and added handling this case to the grid.
As soon as https://github.com/SeleniumHQ/selenium/pull/14756 is merged this issue is fixed.

**Comment by genne** [comment]
@joerg1985 @nvborisenko thanks for the quick fix ⭐

**Comment by genne** [comment]
Hi @joerg1985 @nvborisenko the latest version doesn't work for me anymore, I get a timeout error every time I try to connect:
![image](https://github.com/user-attachments/assets/3fead39f-c7f8-4f9e-bd27-253440bffd2e)
Could be related to this change?

**Comment by genne** [comment]
> Hi @joerg1985 @nvborisenko the latest version doesn't work for me anymore, I get a timeout error every time I try to connect: ![image](https://private-user-images.githubusercontent.com/2142735/389430727-3fead39f-c7f8-4f9e-bd27-253440bffd2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjI3MTksIm5iZiI6MTczMjUyMjQxOSwicGF0aCI6Ii8yMTQyNzM1LzM4OTQzMDcyNy0zZmVhZDM5Zi1jN2Y4LTRmOWUtYmQyNy0yNTM0NDBiZmZkMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMDgxMzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWUwNjRiOTA2YmNmOWI4YjVhNjgwY2YwMWUwMzg2NjJhNjk4MjBmMTMzZGVjMDE4ZWRkNzg3OTFlNWIzMzRiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mxAUzxYCIvTC1NAkcJW-jBi_qcQ1aAclzXvu5BxztRc) Could be related to this change?

Just restarting the container seems to have fixed it.
