### ISSUE TITLE
[🐛 Bug]: Unable to setup: Critical : selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114 Current browser version is 131.0.6778.70

### ISSUE THREAD

**Issue by laxmithurv** [SeleniumHQ/selenium#14758]
### What happened?

[INFO] 2024-11-15 12:56:07,218 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: Starting web interface at http://localhost:8089 (accepting connections from all network int
erfaces)
[INFO] 2024-11-15 12:56:07,244 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: Starting Locust 2.31.5
[INFO] 2024-11-15 12:56:07,244 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: No run time limit set, use CTRL+C to interrupt
[INFO] 2024-11-15 12:56:07,298 LAPTOP-7RK7NGFK/locust.runners [thread: Thread-1]: Ramping to 1 users at a rate of 1.00 per second
[INFO] 2024-11-15 12:56:07,299 LAPTOP-7RK7NGFK/locust.runners [thread: Thread-1]: All users spawned: {"WebUser": 1} (1 total users)
[INFO] 2024-11-15 12:56:07,300 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: For Test Run -> User Role: "Customer : Administrator"
[INFO] 2024-11-15 12:56:07,300 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Getting User Data Of Account Type: "Customer" with Role: "Administrator" with Account: "None"
[INFO] 2024-11-15 12:56:07,302 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Step started: User_Launch_And_Login_Bridge_Marketplace_And_Switch_Account
[INFO] 2024-11-15 12:56:07,302 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: ====== WebDriver manager ======
[INFO] 2024-11-15 12:56:11,645 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Get LATEST chromedriver version for google-chrome
[INFO] 2024-11-15 12:56:11,858 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chrom
edriver_win32.zip
[INFO] 2024-11-15 12:56:12,035 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Driver downloading response is 200
[INFO] 2024-11-15 12:56:15,356 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Get LATEST chromedriver version for google-chrome
[INFO] 2024-11-15 12:56:18,056 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Get LATEST chromedriver version for google-chrome
[INFO] 2024-11-15 12:56:20,509 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Driver has been saved in cache [C:\Users\LaxmiTG\.wdm\drivers\chromedriver\win64\114.0.5735.90]

DevTools listening on ws://127.0.0.1:64429/devtools/browser/f2501f68-d9b7-4727-b586-23fe3a4201c7
[ERROR] 2024-11-15 12:56:29,777 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.70 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

### How can we reproduce the issue?

```shell
Traceback (most recent call last):
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\common_test_foundation\helpers\taskset_handler.py", line 185, in decorator
    res = fnc(*args, **kwargs)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\locust\user\task.py", line 385, in execute_task
    task(self)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\helpers\kb_helper.py", line 40, in log_step
    func(self, *args, **kwargs)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\tests\kb\taskset_common.py", line 40, in user_launch_and_login_bridge_marketplace_and_switch_account
    self.client.set_driver(proxy=self.proxy)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\common_test_foundation\lib\selenium_locust\core.py", line 140, in set_driver
    self.driver = ChromeDriver(
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\common_test_foundation\lib\webdrivers\drivers.py", line 113, in __new__
    driver = webdriver.Chrome(service=ChromeService(DriverBinarySingleton.binary_path), options=options)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.70 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00F1A813+48355]
        (No symbol) [0x00EAC4B1]
        (No symbol) [0x00DB5358]
        (No symbol) [0x00DD61AC]
        (No symbol) [0x00DD1EF3]
        (No symbol) [0x00DD0579]
        (No symbol) [0x00E00C55]
        (No symbol) [0x00E0093C]
        (No symbol) [0x00DFA536]
        (No symbol) [0x00DD82DC]
        (No symbol) [0x00DD93DD]
        GetHandleVerifier [0x0117AABD+2539405]
        GetHandleVerifier [0x011BA78F+2800735]
        GetHandleVerifier [0x011B456C+2775612]
        GetHandleVerifier [0x00FA51E0+616112]
        (No symbol) [0x00EB5F8C]
        (No symbol) [0x00EB2328]
        (No symbol) [0x00EB240B]
        (No symbol) [0x00EA4FF7]
        BaseThreadInitThunk [0x7569FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x7720809E+286]
        RtlGetAppContainerNamedObjectPath [0x7720806E+238]
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\common_test_foundation\helpers\taskset_handler.py", line 185, in decorator
    res = fnc(*args, **kwargs)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\locust\user\task.py", line 385, in execute_task
    task(self)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\helpers\kb_helper.py", line 40, in log_step
    func(self, *args, **kwargs)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\tests\kb\taskset_common.py", line 40, in user_launch_and_login_bridge_marketplace_and_switch_account
    self.client.set_driver(proxy=self.proxy)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\common_test_foundation\lib\selenium_locust\core.py", line 140, in set_driver
    self.driver = ChromeDriver(
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\common_test_foundation\lib\webdrivers\drivers.py", line 113, in __new__
    driver = webdriver.Chrome(service=ChromeService(DriverBinarySingleton.binary_path), options=options)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\LaxmiTG\Downloads\Workspace\projectname\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.70 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00F1A813+48355]
        (No symbol) [0x00EAC4B1]
        (No symbol) [0x00DB5358]
        (No symbol) [0x00DD61AC]
        (No symbol) [0x00DD1EF3]
        (No symbol) [0x00DD0579]
        (No symbol) [0x00E00C55]
        (No symbol) [0x00E0093C]
        (No symbol) [0x00DFA536]
        (No symbol) [0x00DD82DC]
        (No symbol) [0x00DD93DD]
        GetHandleVerifier [0x0117AABD+2539405]
        GetHandleVerifier [0x011BA78F+2800735]
        GetHandleVerifier [0x011B456C+2775612]
        GetHandleVerifier [0x00FA51E0+616112]
        (No symbol) [0x00EB5F8C]
        (No symbol) [0x00EB2328]
        (No symbol) [0x00EB240B]
        (No symbol) [0x00EA4FF7]
        BaseThreadInitThunk [0x7569FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x7720809E+286]
        RtlGetAppContainerNamedObjectPath [0x7720806E+238]
```

### Operating System

Windows10

### Selenium version

pip show selenium Name: selenium Version: 4.22.0, python --version Python 3.10.2

### What are the browser(s) and version(s) where you see this issue?

browser version is 131.0.6778.70

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver - 114.0.5735.90 gets downloaded

### Are you using Selenium Grid?

No

**Comment by laxmithurv** [comment]
help-wanted

**Comment by shbenzer** [comment]
While I can see you're using locust for performance/stress testing, we will still need a code example for us to reproduce locally.

**Comment by laxmithurv** [comment]
Hi @shbenzer, Lets leave the locust code, when I try to run a sample program also, I'm receiving same error.

<img width="947" alt="image" src="https://github.com/user-attachments/assets/ecd38e2f-6a8a-42c8-a03d-af7ab8d2808c">




**Note: Its working while I use firefox. Doesn't work for Chrome alone**

Code:
====

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.firefox import GeckoDriverManager

import time



browserName = "chrome"

if browserName == "chrome":
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
elif browserName == "firefox":
    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
else:
    print("Please enter the correct browserName: " +browserName)
    raise Exception("Driver not found")


driver.implicitly_wait(6)
driver.get("https://app.hubspot.com/login")

print(driver.title)


Output:
=====


C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\Scripts\python.exe C:\Users\LaxmiTG\PycharmProjects\HelloWorld\SeleniumSessions\Webdrivermanager_Crossbrowser.py 
Traceback (most recent call last):
  File "C:\Users\LaxmiTG\PycharmProjects\HelloWorld\SeleniumSessions\Webdrivermanager_Crossbrowser.py", line 15, in <module>
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in __init__
    self.start_session(capabilities)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 325, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.70 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00FEA813+48355]
	(No symbol) [0x00F7C4B1]
	(No symbol) [0x00E85358]
	(No symbol) [0x00EA61AC]
	(No symbol) [0x00EA1EF3]
	(No symbol) [0x00EA0579]
	(No symbol) [0x00ED0C55]
	(No symbol) [0x00ED093C]
	(No symbol) [0x00ECA536]
	(No symbol) [0x00EA82DC]
	(No symbol) [0x00EA93DD]
	GetHandleVerifier [0x0124AABD+2539405]
	GetHandleVerifier [0x0128A78F+2800735]
	GetHandleVerifier [0x0128456C+2775612]
	GetHandleVerifier [0x010751E0+616112]
	(No symbol) [0x00F85F8C]
	(No symbol) [0x00F82328]
	(No symbol) [0x00F8240B]
	(No symbol) [0x00F74FF7]
	BaseThreadInitThunk [0x7569FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x7720809E+286]
	RtlGetAppContainerNamedObjectPath [0x7720806E+238]


Process finished with exit code 1

**Comment by navin772** [comment]
@laxmithurv I wasn't able to reproduce the above issue but I think your driver version is outdated and `webdriver_manager`, the external pypi package you are using is reusing the cached driver (version 114) instead of downloading the newer driver for Chrome 131.

Can you try letting selenium manager download the driver instead of `webdriver_manager`, like this:

```py
from selenium import webdriver

browserName = "chrome"

if browserName == "chrome":
    driver = webdriver.Chrome()
elif browserName == "firefox":
    driver = webdriver.Firefox()
else:
    print("Please enter the correct browserName: " + browserName)
    raise Exception("Driver not found")

driver.implicitly_wait(6)
driver.get("https://app.hubspot.com/login")

print(driver.title)

driver.quit()
```

**Comment by laxmithurv** [comment]
Hi @navin772, the above code runs successfully with google.com, not with hubspot website. The website gets loads loads but it is not launched.

getting below errors in terminal

Screenshot
=======

<img width="957" alt="image" src="https://github.com/user-attachments/assets/ad489a36-2fa1-4ea8-8df4-0a77a4b9e1ad">


Terminal:
======


C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\Scripts\python.exe C:\Users\LaxmiTG\PycharmProjects\sampleproject\newfile.py 
Traceback (most recent call last):
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\LaxmiTG\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\LaxmiTG\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\LaxmiTG\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\LaxmiTG\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\newfile.py", line 16, in <module>
    driver.get("https://app.hubspot.com/login")
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 389, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 391, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 415, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\LaxmiTG\PycharmProjects\sampleproject\.venv\lib\site-packages\urllib3\connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=58888): Read timed out. (read timeout=120)

Process finished with exit code 1

Code:
=====
import time

from selenium import webdriver

browserName = "chrome"

if browserName == "chrome":
    driver = webdriver.Chrome()
elif browserName == "firefox":
    driver = webdriver.Firefox()
else:
    print("Please enter the correct browserName: " + browserName)
    raise Exception("Driver not found")

driver.implicitly_wait(6)
driver.get("https://app.hubspot.com/login")
time.sleep(5)
print(driver.title)

driver.quit()

**Comment by navin772** [comment]
Since you mentioned that `google.com` loads with the script, it is likely not an issue with selenium. I am able to get both of the websites to work with the script.

> The website gets loads loads but it is not launched.

I didn't got what you meant here, does the HubSpot site load, but the wait time is too short for it to load completely? Or perhaps the network speed is too slow for the page to load? In that case, try adjusting the sleep times.

**Comment by laxmithurv** [comment]
Hi @navin772 I tried and it works now. But can you answer my original question now, Do I need to downgrade webdriver manager or what? As the webdriver is pointed to cache version of 114 chromedriver version, do I need to remove the cache so that will it work?

Python 3.10.2

Name: selenium
Version: 4.22.0

Name: webdriver-manager
Version: 4.0.2

Please help me in this regard, as I'm getting driver mismatch error for past 1 month and unable to fix


Code
====

$ ./run-ui-code.sh
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---
Running test case: XXXXXXXX
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---
[INFO] 2024-11-18 20:58:58,031 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: Starting web interface at http://localhost:8089 (accepting connections from all network interfaces)
[INFO] 2024-11-18 20:58:58,047 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: Starting Locust 2.31.5
[INFO] 2024-11-18 20:58:58,047 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: No run time limit set, use CTRL+C to interrupt
[INFO] 2024-11-18 20:58:58,084 LAPTOP-7RK7NGFK/locust.runners [thread: Thread-1]: Ramping to 1 users at a rate of 1.00 per second
[INFO] 2024-11-18 20:58:58,100 LAPTOP-7RK7NGFK/locust.runners [thread: Thread-1]: All users spawned: {"WebUser": 1} (1 total users)
[INFO] 2024-11-18 20:58:58,100 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: For Test Run -> User Role: "Customer : Administrator"
[INFO] 2024-11-18 20:58:58,100 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Getting User Data Of Account Type: "Customer" with Role: "Administrator" with Account: "None"
[INFO] 2024-11-18 20:58:58,116 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Service Detail for the test run is:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[INFO] 2024-11-18 20:58:58,116 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Step started: User_Launch_And_Login_Bridge_Marketplace_And_Switch_Account
[INFO] 2024-11-18 20:58:58,116 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: ====== WebDriver manager ======
[INFO] 2024-11-18 20:59:02,390 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Get LATEST chromedriver version for google-chrome
[INFO] 2024-11-18 20:59:02,644 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip
[INFO] 2024-11-18 20:59:02,791 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Driver downloading response is 200
[INFO] 2024-11-18 20:59:05,902 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Get LATEST chromedriver version for google-chrome
[INFO] 2024-11-18 20:59:08,286 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Get LATEST chromedriver version for google-chrome
[INFO] 2024-11-18 20:59:10,414 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Driver has been saved in cache [C:\Users\LaxmiTG\.wdm\drivers\chromedriver\win64\114.0.5735.90]

DevTools listening on ws://127.0.0.1:61883/devtools/browser/2ebd28e8-31e9-48ee-ae54-c4e8d530889d
[ERROR] 2024-11-18 20:59:19,517 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.70 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x008DA813+48355]
        (No symbol) [0x0086C4B1]
        (No symbol) [0x00775358]
        (No symbol) [0x007961AC]
        (No symbol) [0x00791EF3]
        (No symbol) [0x00790579]
        (No symbol) [0x007C0C55]
        (No symbol) [0x007C093C]
        (No symbol) [0x007BA536]
        (No symbol) [0x007982DC]
        (No symbol) [0x007993DD]
        GetHandleVerifier [0x00B3AABD+2539405]
        GetHandleVerifier [0x00B7A78F+2800735]
        GetHandleVerifier [0x00B7456C+2775612]
        GetHandleVerifier [0x009651E0+616112]
        (No symbol) [0x00875F8C]
        (No symbol) [0x00872328]
        (No symbol) [0x0087240B]
        (No symbol) [0x00864FF7]
        BaseThreadInitThunk [0x7569FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x7720809E+286]
        RtlGetAppContainerNamedObjectPath [0x7720806E+238]
Traceback (most recent call last):
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\ctf\helpers\taskset_handler.py", line 185, in decorator
    res = fnc(*args, **kwargs)
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\locust\user\task.py", line 385, in execute_task
    task(self)
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\helpers\kb_helper.py", line 40, in log_step
    func(self, *args, **kwargs)
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\tests\kb\taskset_common.py", line 40, in user_launch_and_login_bridge_marketplace_and_switch_account
    self.client.set_driver(proxy=self.proxy)
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\ctf\lib\selenium_locust\core.py", line 140, in set_driver
    self.driver = ChromeDriver(
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\ctf\lib\webdrivers\drivers.py", line 113, in __new__
    driver = webdriver.Chrome(service=ChromeService(DriverBinarySingleton.binary_path), options=options)
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.70 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x008DA813+48355]
        (No symbol) [0x0086C4B1]
        (No symbol) [0x00775358]
        (No symbol) [0x007961AC]
        (No symbol) [0x00791EF3]
        (No symbol) [0x00790579]
        (No symbol) [0x007C0C55]
        (No symbol) [0x007C093C]
        (No symbol) [0x007BA536]
        (No symbol) [0x007982DC]
        (No symbol) [0x007993DD]
        GetHandleVerifier [0x00B3AABD+2539405]
        GetHandleVerifier [0x00B7A78F+2800735]
        GetHandleVerifier [0x00B7456C+2775612]
        GetHandleVerifier [0x009651E0+616112]
        (No symbol) [0x00875F8C]
        (No symbol) [0x00872328]
        (No symbol) [0x0087240B]
        (No symbol) [0x00864FF7]
        BaseThreadInitThunk [0x7569FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x7720809E+286]
        RtlGetAppContainerNamedObjectPath [0x7720806E+238]

[INFO] 2024-11-18 20:59:19,663 LAPTOP-7RK7NGFK/root [thread: Thread-4]: Iteration limit reached (1), stopping test
[INFO] 2024-11-18 20:59:28,877 LAPTOP-7RK7NGFK/root [thread: Thread-4]: --autoquit time reached, shutting down
[INFO] 2024-11-18 20:59:28,946 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: writing html report to file: .\kb-functional-test-report.html
[INFO] 2024-11-18 20:59:28,946 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: Shutting down (exit code 1)

**Comment by navin772** [comment]
@laxmithurv again that is a [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager) package issue and not a selenium issue, you can open an issue there.

I think we can close this issue as it's unrelated to selenium.

**Comment by laxmithurv** [comment]
Sure @navin772 , I have opened a new issue - https://github.com/SergeyPirogov/webdriver_manager/issues/687. Thanks for your help

**Comment by VietND96** [comment]
Can you also try to adapt your test using selenium manager itself instead of relying on another external lib and can repetitively occur?

**Comment by neupanesandesh** [comment]
Somehow putting this version of driver directly (although it doesn't exists in the url provided in ChromeDriverManager class) solved same problem for me , its related to chrome driver version but latest version of driver it has rn is 114.
```
from webdriver_manager.chrome import ChromeDriverManager
        driver = webdriver.Chrome(service=Service(ChromeDriverManager(driver_version="120.0.6099.10900").install()), options=options)

```
