### ISSUE TITLE
[🐛 Bug]: Selenium 4.26.0 has memory leak.

### ISSUE THREAD

**Issue by shinobi01** [SeleniumHQ/selenium#14789]
### What happened?

I'm using Java + Cucumber + testNG + Appium to do automation test on mobile devices. I got some errors as following
**Caused by: java.lang.OutOfMemoryError: Compressed class space**
So I checked with VisualVM, the Metaspace and Classes are always increasing.
<img width="1071" alt="error" src="https://github.com/user-attachments/assets/173c69ce-7a9c-422f-8859-4a052aa01314">
The loaded classs are not unloaded.
After downgrade to 4.23.0, this issue is gone
<img width="969" alt="Screenshot 2024-11-22 at 13 43 05" src="https://github.com/user-attachments/assets/3caafdb9-4387-47f2-957a-948a225dde24">

### How can we reproduce the issue?

```shell
Sorry I can't share my code, but create a cucumber test cases and rerun it several times should be able to reproduce.
```

### Relevant log output

```shell
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Exception in provider
org.apache.maven.surefire.booter.SurefireExecutionException: Exception in provider
	at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:91)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1144)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:41)
Caused by: java.lang.OutOfMemoryError: Compressed class space
```

### Operating System

macos 14.4.1

### Selenium version

Java 17 + Java-Client 9.3.0 (Selenium 4.26.0)

### What are the browser(s) and version(s) where you see this issue?

Android and iOS

### What are the browser driver(s) and version(s) where you see this issue?

None

### Are you using Selenium Grid?

None

**Comment by joerg1985** [comment]
@shinobi01 could you share a histogram of your memory dump? The easiest way is to call `jmap -histo {pid}`

It would be helpful to know the exact version when it did break. Thanks in advance

**Comment by shinobi01** [comment]
@joerg1985 This is the log running on Linux jenkins slave. 
The first time I have this error is on September, but the reproduce rate is not frequently.
But on 4.26.0, it is 100% reproduce.

**Comment by joerg1985** [comment]
@shinobi01 this crash dump does not contain the infos i need, the output should look like [this](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr014.html#BABFEDHC)

**Comment by shinobi01** [comment]
Test start
[jmap.txt](https://github.com/user-attachments/files/17879187/jmap.txt)
5 minutes later
[jmap2.txt](https://github.com/user-attachments/files/17879190/jmap2.txt)

**Comment by joerg1985** [comment]
@shinobi01 are you using the `WebDriverDecorator`?
I think i could reproduce the root issue, each invocation does return a new class.
Are you intentionally keeping hunderts references to WebElements found?
Each WebElement brings it's own class definition, due to the Proxy and this could kill your class space.

This is a extension to the DecoratedWebDriverTest to reproduce the issue.
```

  @Test
  void doesNotCreateTooManyClasses() {
    final WebElement found = mock(WebElement.class);
    Function<WebDriver, WebElement> f = $ -> $.findElement(By.id("test"));
    Fixture fixture = new Fixture();
    when(f.apply(fixture.original)).thenReturn(found);

    WebElement proxy1 = f.apply(fixture.decorated);
    WebElement proxy2 = f.apply(fixture.decorated);
    WebElement proxy3 = f.apply(fixture.decorated);

    assertThat(proxy1.getClass()).isSameAs(proxy2.getClass());
    assertThat(proxy1.getClass()).isSameAs(proxy3.getClass());
  }
```

**Comment by shinobi01** [comment]
@joerg1985 sorry, i have no idea about WebDriverDecorator, i started the webdriver by using selenide appium.

**Comment by joerg1985** [comment]
This might be related to https://github.com/appium/java-client/issues/2119 but in any case the WebDriverDercorator does create to mutch classes without the PR above.

**Comment by luckhiem** [comment]
@shinobi01 after downgrading to use Selenium 4.23.0, you still keep using Appium 9.3.0 right?

**Comment by luckhiem** [comment]
after downgrading to use Selenium 4.21.0 my code still have performance problem? 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>groupId</groupId>
    <artifactId>7eleven-automate-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <testng.version>7.10.2</testng.version>
        <appium.version>9.2.2</appium.version>
        <hamcrest.version>1.3</hamcrest.version>
        <cucumber.version>7.18.0</cucumber.version>
        <selenium.version>4.21.0</selenium.version>
        <cucumber.reporting.version>5.3.1</cucumber.reporting.version>
        <slf4j.version>2.0.13</slf4j.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <!--  ############################# Cucumber ############################## -->
        <!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-core -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-java -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!--  ##################################################################### -->

        <!--  ############################## appium/ selenium ############################### -->
        <!-- https://mvnrepository.com/artifact/io.appium/java-client -->
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>${appium.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <!--  ##################################################################### -->

        <!--  ############################# TestNG ############################## -->
        <!-- https://mvnrepository.com/artifact/io.cucumber/cucumber-testng -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>${cucumber.version}</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.testng/testng -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.seleniumhq.selenium</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!--  ##################################################################### -->

        <!--  ############################# Others ############################## -->
        <!-- https://mvnrepository.com/artifact/org.hamcrest/hamcrest-all -->
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>${hamcrest.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/net.masterthought/cucumber-reporting -->
        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>5.6.1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.aventstack/extentreports -->
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>5.1.1</version>
        </dependency>
        <!--  ##################################################################### -->

        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <version>[x,]</version>
            <type>maven-plugin</type>
        </dependency>

        <!--  Logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple -->
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>

        <dependency>
            <groupId>javax.json</groupId>
            <artifactId>javax.json-api</artifactId>
            <version>1.0</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.json</artifactId>
            <version>1.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20140107</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.12.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.5.0</version>
        </dependency>
    </dependencies>

    <build>
        <testResources>
            <testResource>
                <!--<directory>src/test/java</directory>-->
                <directory>${project.basedir}/src/test/resources</directory>
                <excludes>
                    <exclude>**/*.java</exclude>
                </excludes>
            </testResource>
        </testResources>
        <plugins>
            <!-- START: To run Cucumber Test through Maven -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>src/test/resources/TestSuite/testng.xml</suiteXmlFile>
                    </suiteXmlFiles>
                </configuration>
            </plugin>
            <!-- END: To run Cucumber Test through Maven -->
            <!-- START: To include plugin builds your test source code to AWS device farm-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- END: To include plugin builds your test source code to AWS device farm-->

            <!-- START: copies your dependencies into the dependency-jars directory -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/dependency-jars/</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- END: copies your dependencies into the dependency-jars directory -->
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>maven_central</id>
            <name>Maven Central</name>
            <url>https://repo.maven.apache.org/maven2/</url>
        </repository>
    </repositories>

</project>
```
<img width="1728" alt="Screenshot 2024-12-02 at 21 11 35" src="https://github.com/user-attachments/assets/7c0d807f-253d-4366-959b-87a8fa4929b3">

**Comment by shinobi01** [comment]
@luckhiem , yes, I'm still using java-client 9.3.0, just fix the selenium version in POM file.
Maybe you could share the histogram of your memory dump with jmap -histo {pid} to developer as well, so they could identify the root cause

**Comment by Auto81** [comment]
I have just updated from v4.25.0 (no memory leak) to v4.28.0-SNAPSHOT (which includes  https://github.com/SeleniumHQ/selenium/pull/14793) and unfortunately still seeing the Memory Leak occurring.

I'm also using the PageFactory with Field Decorators.

v4.25.0 stays below 200MB usage for the entire suite (1000 tests).

These are some rough numbers for test suite using 4.28.0-SNAPSHOT.

| Test Number | Heap Size MB |
|--------|---------|
| 1 | 181 |
| 10 | 278 |
| 50 | 871 |
| 100 | 1300 |

@shinobi01 Are you able to see the same happening still with your setup?

**Comment by joerg1985** [comment]
@Auto81 could you share a memory histogram created with jmap?

**Comment by Auto81** [comment]
I have narrowed it down to the PageFactory.initElements() method when using the AppiumFieldDecorator

```
PageFactory.initElements(new AppiumFieldDecorator(driver, Duration.ofSeconds(5)), this); //Leaks
```

```
PageFactory.initElements(driver, this); //No Leaks
```

Shall i move discussion over to https://github.com/appium/java-client/issues/2247 ?
