### ISSUE TITLE
[🐛 Bug]: selenium-manager is missing.

### ISSUE THREAD

**Issue by Lucian-Linton** [SeleniumHQ/selenium#14785]
### What happened?

Error received was:
selenium.common.exceptions.SeleniumManagerException: Message: /usr/lib/python3/dist-packages/selenium/webdriver/common/linux/selenium-manager is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues

### How can we reproduce the issue?

```shell
The error happened when running this test program:
-----------------------------
import bs4
from selenium import webdriver

def main():

        driver = webdriver.Firefox(options=webdriver.FirefoxOptions())
        driver.get("https://example.com")
        driver.implicitly_wait(20)

if __name__ == "__main__":
        main()
-----------------------------

Selenium and Python3 are installed through Debian's package manager
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 97, in start
    path = SeleniumManager().driver_location(browser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/selenium_manager.py", line 75, in driver_location
    str(self.get_binary()),
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/selenium_manager.py", line 56, in get_binary
    raise SeleniumManagerException(f"{path} is missing.  Please open an issue on {tracker}")
selenium.common.exceptions.SeleniumManagerException: Message: /usr/lib/python3/dist-packages/selenium/webdriver/common/linux/selenium-manager is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/testcode/./selenium-dynamic.py", line 14, in <module>
    main()
  File "/home/me/testcode/./selenium-dynamic.py", line 9, in main
    driver = webdriver.Firefox(options=webdriver.FirefoxOptions())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 194, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 100, in start
    raise err
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 218, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

### Operating System

Debian 12 stable

### Selenium version

Python 3.11.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 128.4.0esr (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

I'm unsure how to find this, and beleive Selenium picked a default

### Are you using Selenium Grid?

No

**Comment by VietND96** [comment]
> Selenium version
Python 3.11.2

Please correct this field, this is the version of Python Selenium client.

> Selenium and Python3 are installed through Debian's package manager

Do you have link to this package in Deb repo?

**Comment by diemol** [comment]
I will close this because there was no activity.

**Comment by cgoldberg** [comment]
FWIW, the package for the Selenium Python bindings (python3-selenium) in the Debian/Ubuntu repos is broken... do not use it. Install from PyPI instead.

This issue has been brought up with Debian maintainers and there is no current resolution.
