### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

### ISSUE THREAD

**Issue by mrsalesi** [SeleniumHQ/selenium#14797]
### What happened?

I have the same [issue ](https://github.com/SeleniumHQ/selenium/issues/12519) . I try to start selenuim and this error shows for every possible way that I test.

this is my code :

```
package seleniumant;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class SeleniumAnt {
    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("-----------------------------");
        System.setProperty("webdriver.chrome.driver", "D:\\chromedriver-win64-v-131.0.6778.85\\chromedriver-win64\\chromedriver.exe");
        ChromeOptions options = new ChromeOptions();
        options.setBinary("D:\\chrome-win64-v-131.0.6778.85\\chrome-win64\\chrome.exe");
        WebDriver driver = new ChromeDriver(options);
        driver.get("https://www.google.com");
        System.out.println("Page Title: " + driver.getTitle());
        driver.quit();
    }
}
```

### How can we reproduce the issue?

```shell
Download 
chromedriver-win64 version 131.0.6778.85
And
chrome-win64 vesrsion 131.0.6778.85

D:\\chromedriver-win64-v-131.0.6778.85\\chromedriver-win64\\chromedriver.exe
and
D:\\chrome-win64-v-131.0.6778.85\\chrome-win64\\chrome.exe

I add  "D:\\chromedriver-win64-v-131.0.6778.85\\chromedriver-win64\\" to "path" in Enviroment variables and sytem variables too.

I  use
netbeans IDE 23
JDK-23
Selenum 4.26.2 for java 

I create new java-Ant project project and add all jar files was in selenium-java-4.26.0.zip.

After reset windows, the error was occourd again.
After test on an other Laptop, the error was occourd again.
After using firefox, geckodriver-v0.34.0-win64 and simple changes in codes the error was occourd again.
After change in chromedriver.exe permission, the error was occourd again.
After using the last version Installed of chrom, the error was occourd again.
```

### Relevant log output

```shell
run:
-----------------------------
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-B950D77', ip: '172.17.72.249'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at seleniumant.SeleniumAnt.main(SeleniumAnt.java:13)
Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.
Build info: version: '4.26.0', revision: '69f9e5e'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '23'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:246)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:117)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	... 7 more
C:\Users\rayanet\AppData\Local\NetBeans\Cache\23\executor-snippets\run.xml:111: The following error occurred while executing this line:
C:\Users\rayanet\AppData\Local\NetBeans\Cache\23\executor-snippets\run.xml:68: Java returned: 1
BUILD FAILED (total time: 1 second)
```

### Operating System

Windows 10 pro

### Selenium version

java 4.26.2

### What are the browser(s) and version(s) where you see this issue?

Version 131.0.6778.86 (Official Build) (64-bit) and chrome-win64 for test vesrsion 131.0.6778.85

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver-win64 version 131.0.6778.85

### Are you using Selenium Grid?

No

**Comment by pujagani** [comment]
Hello! Thank you for sharing the details. Does the same error occur in Firefox?

**Comment by mrsalesi** [comment]
yes It dose,
I try for last version of Firefox and chrome and it was same result.

**Comment by edudelta** [comment]
I'm facing same issue on Docker for AMD64 and AARCH/64 builds. Execution is unstable and getting this issue in 10% or even more of the results.
No issue when running on Firefox build, though.

- selenium/standalone-firefox:latest STABLE
- FROM selenium/standalone-chromium:latest UNSTABLE, issues like this.

When running locally it runs ok. 
But on Docker it's the issue. I already tried dozens of same build/selenium Java package.

**Comment by diemol** [comment]
@edudelta, the error in the log might be the same, but the source can be different. Please create a new issue with all details in the docker-selenium project.

**Comment by diemol** [comment]
@mrsalesi please use a dependency management tool like Maven or Gradle. We can't be sure if things work well when files are being moved by hand.
