### ISSUE TITLE
[🐛 Bug]: Python selenium 4.27.0 not installable from sdist due to invalid `pyproject.toml`

### ISSUE THREAD

**Issue by mgorny** [SeleniumHQ/selenium#14805]
### What happened?

When trying to install selenium 4.27.0 from sdist, the install fails because the `license` key in `pyproject.toml` is invalid:

```
      ValueError: invalid pyproject.toml config: `project.license`.
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):
      
          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']
```

### How can we reproduce the issue?

```shell
$ pip install --no-binary selenium selenium
```

### Relevant log output

```shell
Collecting selenium
  Using cached selenium-4.27.0.tar.gz (973 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):
      
          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']
      
      DESCRIPTION:
          `Project license <https://peps.python.org/pep-0621/#license>`_.
      
      GIVEN VALUE:
          "Apache 2.0"
      
      OFFENDING RULE: 'oneOf'
      
      DEFINITION:
          {
              "oneOf": [
                  {
                      "properties": {
                          "file": {
                              "type": "string",
                              "$$description": [
                                  "Relative path to the file (UTF-8) which contains the license for the",
                                  "project."
                              ]
                          }
                      },
                      "required": [
                          "file"
                      ]
                  },
                  {
                      "properties": {
                          "text": {
                              "type": "string",
                              "$$description": [
                                  "The license of the project whose meaning is that of the",
                                  "`License field from the core metadata",
                                  "<https://packaging.python.org/specifications/core-metadata/#license>`_."
                              ]
                          }
                      },
                      "required": [
                          "text"
                      ]
                  }
              ]
          }
      Traceback (most recent call last):
        File "/tmp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k8j69brd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k8j69brd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-k8j69brd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 38, in <module>
        File "/tmp/pip-build-env-k8j69brd/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k8j69brd/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-k8j69brd/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 648, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-k8j69brd/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 72, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k8j69brd/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 140, in read_configuration
          validate(subset, filepath)
        File "/tmp/pip-build-env-k8j69brd/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 61, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.license`.
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):
      
          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Operating System

Gentoo Linux

### Selenium version

Python 4.27.0

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

**Comment by VietND96** [comment]
@sandeepsuryaprasad I think it relates to recent change around this. Do you have any idea?

**Comment by VietND96** [comment]
@mgorny, in this case, are you installing directly from source?

**Comment by sandeepsuryaprasad** [comment]
> @sandeepsuryaprasad I think it relates to recent change around this. Do you have any idea?

I am looking into this..

**Comment by mgorny** [comment]
> @mgorny, in this case, are you installing directly from source?

I'm packaging selenium for Gentoo. All distros are going to be hit by this, as well as all users who install from source.

**Comment by sandeepsuryaprasad** [comment]
Yes, I am getting this issue on my  Ubuntu 24.04.1 and Mac as well.

**Comment by VietND96** [comment]
If having time, can you evaluate the package with fix https://test.pypi.org/project/selenium/4.28.0.202411261236/#files
Download .tar.gz, extract, and install from that source. If everything is fine, the patch `4.27.1` will be out.

**Comment by mgorny** [comment]
Yep, that looks good. Thanks!
