### ISSUE TITLE
[🐛 Bug]: `Selenium::WebDriver::SeleniumManager.binary errors if cannot find` spec filure

### ISSUE THREAD

**Issue by voxik** [SeleniumHQ/selenium#14925]
### What happened?

Trying to execute the Ruby selenium-webdroverhe test suite, I observe `Selenium::WebDriver::SeleniumManager.binary errors if cannot find` spec error.

Reading the code, I can't see that `File.exist?`, which is stubbed by the test case, would be anywhere as part of the `Selenium::WebDriver::SeleniumManager.binary` call. But then why you don't see the failure upstream? Sorry, I cannot wrap my head about the usage of Bazel and where I could spot the error in GH actions 🤷

### How can we reproduce the issue?

```shell
$ rspec spec/unit/selenium/webdriver/common/selenium_manager_spec.rb:61
Run options: include {:locations=>{"./spec/unit/selenium/webdriver/common/selenium_manager_spec.rb"=>[61]}}

Selenium::WebDriver::SeleniumManager
  .binary
    errors if cannot find (FAILED - 1)

Failures:

  1) Selenium::WebDriver::SeleniumManager.binary errors if cannot find
     Failure/Error: expect { described_class.send(:binary) }.to raise_error(Error::WebDriverError, /not a file/)
       expected Selenium::WebDriver::Error::WebDriverError with message matching /not a file/ but nothing was raised
     # ./spec/unit/selenium/webdriver/common/selenium_manager_spec.rb:64:in `block (3 levels) in <module:WebDriver>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'

Finished in 0.00954 seconds (files took 0.201 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/unit/selenium/webdriver/common/selenium_manager_spec.rb:61 # Selenium::WebDriver::SeleniumManager.binary errors if cannot find
```

### Operating System

Fedora Rawhide

### Selenium version

Ruby 3.3.6, selenium-webdriver 4.27.0

**Comment by voxik** [comment]
Ah, I got the problem. The repo does not contain any binary in the `bin` directory, while the gem ships the binaries. But then the `File.exist?` stub is completely useless and the test case is a bit bogus.

https://github.com/SeleniumHQ/selenium/blob/c0b45ad714fb954a529aa10c0a83908b68fcf4b4/rb/spec/unit/selenium/webdriver/common/selenium_manager_spec.rb#L62

**Comment by voxik** [comment]
What is the point of closing the issue if there was no response?

**Comment by diemol** [comment]
These tests are run through Bazel, and Bazel puts the file in the expected place.

**Comment by diemol** [comment]
`bazel test //rb/spec/unit/selenium/webdriver/common:selenium_manager`

If you need help to set up bazel, join us in the chat room https://www.selenium.dev/support/
