### ISSUE TITLE
[🚀 Feature]: Ruby 3.4 support

### ISSUE THREAD

**Issue by voxik** [SeleniumHQ/selenium#14934]
### Feature and motivation

Is there Ruby 3.4 support planned any time soon? The official release should be out in just two days

### Usage example

Observing test failures such as:

~~~
  1) Selenium::WebDriver::Chrome::Options#as_json errors when unrecognized capability is passed
     Failure/Error:
       expect {
         options.as_json
       }.to raise_error(Error::WebDriverError, 'These options are not w3c compliant: {:foo=>"bar"}')

       expected Selenium::WebDriver::Error::WebDriverError with "These options are not w3c compliant: {:foo=>\"bar\"}", got #<Selenium::WebDriver::Error::WebDriverError: These options are not w3c compliant: {foo: "bar"}> with backtrace:
         # ./lib/selenium/webdriver/common/options.rb:118:in 'Selenium::WebDriver::Options#as_json'
         # ./spec/unit/selenium/webdriver/chrome/options_spec.rb:249:in 'block (4 levels) in <module:Chrome>'
         # ./spec/unit/selenium/webdriver/chrome/options_spec.rb:250:in 'block (3 levels) in <module:Chrome>'
         # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'
     # ./spec/unit/selenium/webdriver/chrome/options_spec.rb:250:in 'block (3 levels) in <module:Chrome>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

  2) Selenium::WebDriver::Edge::Options#as_json errors when unrecognized capability is passed
     Failure/Error:
       expect {
         options.as_json
       }.to raise_error(Error::WebDriverError, 'These options are not w3c compliant: {:foo=>"bar"}')

       expected Selenium::WebDriver::Error::WebDriverError with "These options are not w3c compliant: {:foo=>\"bar\"}", got #<Selenium::WebDriver::Error::WebDriverError: These options are not w3c compliant: {foo: "bar"}> with backtrace:
         # ./lib/selenium/webdriver/common/options.rb:118:in 'Selenium::WebDriver::Options#as_json'
         # ./spec/unit/selenium/webdriver/edge/options_spec.rb:211:in 'block (4 levels) in <module:Edge>'
         # ./spec/unit/selenium/webdriver/edge/options_spec.rb:212:in 'block (3 levels) in <module:Edge>'
         # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'
     # ./spec/unit/selenium/webdriver/edge/options_spec.rb:212:in 'block (3 levels) in <module:Edge>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

  3) Selenium::WebDriver::Support::Guards#disposition is pending without provided reason
     Failure/Error:
       expect(guards.disposition).to eq [:pending,
                                         'Test guarded; Guarded by {:foo=>false, :reason=>"No reason given"};']

       expected: [:pending, "Test guarded; Guarded by {:foo=>false, :reason=>\"No reason given\"};"]
            got: [:pending, "Test guarded; Guarded by {foo: false, reason: \"No reason given\"};"]

       (compared using ==)

       Diff:
       @@ -1,3 +1,3 @@
        [:pending,
       - "Test guarded; Guarded by {:foo=>false, :reason=>\"No reason given\"};"]
       + "Test guarded; Guarded by {foo: false, reason: \"No reason given\"};"]
     # ./spec/unit/selenium/webdriver/guard_spec.rb:80:in 'block (3 levels) in <module:Support>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

  4) Selenium::WebDriver::Support::Guards#disposition is skipped without provided reason
     Failure/Error: expect(guards.disposition).to eq [:skip, message]

       expected: [:skip, "Test does not apply to this configuration; Guarded by {:foo=>true, :reason=>\"No reason given\"};"]
            got: [:skip, "Test does not apply to this configuration; Guarded by {foo: true, reason: \"No reason given\"};"]

       (compared using ==)

       Diff:
       @@ -1,3 +1,3 @@
        [:skip,
       - "Test does not apply to this configuration; Guarded by {:foo=>true, :reason=>\"No reason given\"};"]
       + "Test does not apply to this configuration; Guarded by {foo: true, reason: \"No reason given\"};"]
     # ./spec/unit/selenium/webdriver/guard_spec.rb:89:in 'block (3 levels) in <module:Support>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

  5) Selenium::WebDriver::Support::Guards::Guard#message defaults to no reason given
     Failure/Error: expect(guard.message).to eq('Test guarded; Guarded by {:reason=>"No reason given"};')

       expected: "Test guarded; Guarded by {:reason=>\"No reason given\"};"
            got: "Test guarded; Guarded by {reason: \"No reason given\"};"

       (compared using ==)
     # ./spec/unit/selenium/webdriver/guard_spec.rb:161:in 'block (3 levels) in <module:Support>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

  6) Selenium::WebDriver::Support::Guards::Guard#message accepts String
     Failure/Error: expect(guard.message).to eq('Test guarded; Guarded by {:reason=>"because"};')

       expected: "Test guarded; Guarded by {:reason=>\"because\"};"
            got: "Test guarded; Guarded by {reason: \"because\"};"

       (compared using ==)
     # ./spec/unit/selenium/webdriver/guard_spec.rb:174:in 'block (3 levels) in <module:Support>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

  7) Selenium::WebDriver::Support::Guards::Guard#message has special message for exclude
     Failure/Error: expect(guard.message).to eq('Test skipped because it breaks test run; Guarded by {:reason=>"because"};')

       expected: "Test skipped because it breaks test run; Guarded by {:reason=>\"because\"};"
            got: "Test skipped because it breaks test run; Guarded by {reason: \"because\"};"

       (compared using ==)
     # ./spec/unit/selenium/webdriver/guard_spec.rb:194:in 'block (3 levels) in <module:Support>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

  8) Selenium::WebDriver::Support::Guards::Guard#message has special message for flaky
     Failure/Error: expect(guard.message).to eq(msg)

       expected: "Test skipped because it is unreliable in this configuration; Guarded by {:reason=>\"because\"};"
            got: "Test skipped because it is unreliable in this configuration; Guarded by {reason: \"because\"};"

       (compared using ==)
     # ./spec/unit/selenium/webdriver/guard_spec.rb:201:in 'block (3 levels) in <module:Support>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'

  9) Selenium::WebDriver::Support::Guards::Guard#message has special message for exclusive
     Failure/Error: expect(guard.message).to eq('Test does not apply to this configuration; Guarded by {:reason=>"because"};')

       expected: "Test does not apply to this configuration; Guarded by {:reason=>\"because\"};"
            got: "Test does not apply to this configuration; Guarded by {reason: \"because\"};"

       (compared using ==)
     # ./spec/unit/selenium/webdriver/guard_spec.rb:207:in 'block (3 levels) in <module:Support>'
     # /usr/share/gems/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'
~~~

These seems to be caused by `Hash#inspect` formatting change:

https://bugs.ruby-lang.org/issues/20433

I'd contributed the fixes, but I can't sign the CLA 🤷

**Comment by voxik** [comment]
This would be the patch:

~~~patch
From 197157e98ce42550eed6a3c387eb89a0e99cfa3e Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?V=C3=ADt=20Ondruch?= <vondruch@redhat.com>
Date: Mon, 23 Dec 2024 16:55:02 +0100
Subject: [PATCH] Fix `Hash#inspect` formatting for Ruby 3.4 compatibility

https://bugs.ruby-lang.org/issues/20433

Fixes #14934
---
 .../unit/selenium/webdriver/chrome/options_spec.rb |  2 +-
 .../unit/selenium/webdriver/edge/options_spec.rb   |  2 +-
 rb/spec/unit/selenium/webdriver/guard_spec.rb      | 14 +++++++-------
 3 files changed, 9 insertions(+), 9 deletions(-)

diff --git a/rb/spec/unit/selenium/webdriver/chrome/options_spec.rb b/rb/spec/unit/selenium/webdriver/chrome/options_spec.rb
index a87f073e50..8eb6ebe042 100644
--- a/rb/spec/unit/selenium/webdriver/chrome/options_spec.rb
+++ b/rb/spec/unit/selenium/webdriver/chrome/options_spec.rb
@@ -247,7 +247,7 @@ module Selenium
 
             expect {
               options.as_json
-            }.to raise_error(Error::WebDriverError, 'These options are not w3c compliant: {:foo=>"bar"}')
+            }.to raise_error(Error::WebDriverError, %|These options are not w3c compliant: #{{:foo=>"bar"}}|)
           end
 
           it 'returns added options' do
diff --git a/rb/spec/unit/selenium/webdriver/edge/options_spec.rb b/rb/spec/unit/selenium/webdriver/edge/options_spec.rb
index eccaeadf6e..1bced2acaf 100644
--- a/rb/spec/unit/selenium/webdriver/edge/options_spec.rb
+++ b/rb/spec/unit/selenium/webdriver/edge/options_spec.rb
@@ -209,7 +209,7 @@ module Selenium
 
             expect {
               options.as_json
-            }.to raise_error(Error::WebDriverError, 'These options are not w3c compliant: {:foo=>"bar"}')
+            }.to raise_error(Error::WebDriverError, %|These options are not w3c compliant: #{{:foo=>"bar"}}|)
           end
 
           it 'returns added options' do
diff --git a/rb/spec/unit/selenium/webdriver/guard_spec.rb b/rb/spec/unit/selenium/webdriver/guard_spec.rb
index 60a17ac67e..5c45311389 100644
--- a/rb/spec/unit/selenium/webdriver/guard_spec.rb
+++ b/rb/spec/unit/selenium/webdriver/guard_spec.rb
@@ -78,14 +78,14 @@ module Selenium
             guards.add_condition(:foo, false)
 
             expect(guards.disposition).to eq [:pending,
-                                              'Test guarded; Guarded by {:foo=>false, :reason=>"No reason given"};']
+                                              %|Test guarded; Guarded by #{{:foo=>false, :reason=>"No reason given"}};|]
           end
 
           it 'is skipped without provided reason', exclusive: {foo: true} do |example|
             guards = described_class.new(example)
             guards.add_condition(:foo, false)
 
-            message = 'Test does not apply to this configuration; Guarded by {:foo=>true, :reason=>"No reason given"};'
+            message = %|Test does not apply to this configuration; Guarded by #{{:foo=>true, :reason=>"No reason given"}};|
             expect(guards.disposition).to eq [:skip, message]
           end
         end
@@ -158,7 +158,7 @@ module Selenium
           it 'defaults to no reason given' do
             guard = described_class.new({}, :only)
 
-            expect(guard.message).to eq('Test guarded; Guarded by {:reason=>"No reason given"};')
+            expect(guard.message).to eq(%|Test guarded; Guarded by #{{:reason=>"No reason given"}};|)
           end
 
           it 'accepts integer' do |example|
@@ -171,7 +171,7 @@ module Selenium
           it 'accepts String' do
             guard = described_class.new({reason: 'because'}, :only)
 
-            expect(guard.message).to eq('Test guarded; Guarded by {:reason=>"because"};')
+            expect(guard.message).to eq(%|Test guarded; Guarded by #{{:reason=>"because"}};|)
           end
 
           it 'accepts Symbol of known message' do
@@ -191,20 +191,20 @@ module Selenium
           it 'has special message for exclude' do
             guard = described_class.new({reason: 'because'}, :exclude)
 
-            expect(guard.message).to eq('Test skipped because it breaks test run; Guarded by {:reason=>"because"};')
+            expect(guard.message).to eq(%|Test skipped because it breaks test run; Guarded by #{{:reason=>"because"}};|)
           end
 
           it 'has special message for flaky' do
             guard = described_class.new({reason: 'because'}, :flaky)
 
-            msg = 'Test skipped because it is unreliable in this configuration; Guarded by {:reason=>"because"};'
+            msg = %|Test skipped because it is unreliable in this configuration; Guarded by #{{:reason=>"because"}};|
             expect(guard.message).to eq(msg)
           end
 
           it 'has special message for exclusive' do
             guard = described_class.new({reason: 'because'}, :exclusive)
 
-            expect(guard.message).to eq('Test does not apply to this configuration; Guarded by {:reason=>"because"};')
+            expect(guard.message).to eq(%|Test does not apply to this configuration; Guarded by #{{:reason=>"because"}};|)
           end
         end
       end
~~~

**Comment by VietND96** [comment]
There is the PR for Ruby update is going on https://github.com/SeleniumHQ/selenium/pull/14791
cc: @aguspe

**Comment by aguspe** [comment]
This week I will be wrapping up #14900 and afterward, I will go back to the 3.2.2 upgrade, we need to do a procedural upgrade also to validate that all the tests and dependencies work as expected, so hopefully after successfully upgrading to 3.2.2 we can work towards 3.4.0 :)

**Comment by voxik** [comment]
> This issue is stale because it has been open 280 days with no activity.

Maybe 180 days?

**Comment by vizcay** [comment]
Hi, I'm stuck with

```
     Selenium::WebDriver::Error::WebDriverError:
       These options are not w3c compliant: {"prefs"=>{:"intl.accept_languages"=>"en-US"}}
```

in Ruby 3.3.8 while trying to do https://github.com/cobrateam/splinter/issues/492#issuecomment-479567362.

Any solution for this? Thanks

**Comment by voxik** [comment]
There have been applied some medicine here:

https://github.com/SeleniumHQ/selenium/commit/212fc8be3566e333ee3823e153b770162c3902b8

But to me, the RegExps which are used there are quite unfortunate. If they were at lease in a form of `/(oldrubystring|newerrubystring)/`.

IOW The original issue is addressed, but I'd sill suggest to use my proposal to achieve the same.

**Comment by aguspe** [comment]
Regarding the upgrade to Ruby 3.4, I'm quoting @titusfortner :

Policy is to support all Ruby versions that aren't EOL, so support for the new version is added in Dec/Jan and we remove the EOL version in March/April (and get to update syntax to support the new oldest version).

We aren't upgrading to 3.4 until March 2027

**Comment by titusfortner** [comment]
Sorry, I misunderstood the issue. We aren't "upgrading to 3.4" because we must still support 3.2 until EOL. That doesn't mean that we ignore issues with 3.4.

We run unit tests in both 3.2.3 and 3.4.3 (and jruby & truffleruby) right now, and when Ruby 4 is released, we'll update to run unit tests with 3.2.x and 4.0.x to make sure everything works for that as well. 

@aguspe if you want to try running unit tests with the 4.0 preview to see if anything breaks, that could be a good way to ensure we're ready for 4.0. You can also bump 3.2 and 3.4 to latest patch releases

@p0deje should we be testing with latest versions of truffleruby & jruby? 

Finally, we'll happily take pull requests for any regexp improvements that pass the unit tests. Thank you for raising the issue.
