### ISSUE TITLE
[🐛 Bug]: Chrome for Testing browser is crashing

### ISSUE THREAD

**Issue by sandeshmms** [SeleniumHQ/selenium#14996]
### What happened?

While invoking the Chrome for Testing browser, it is crashing.

**Code:**
```
		ChromeOptions options = new ChromeOptions();

		if(headless)
		{
			// Window size increased to overcome the problem of overlapping success messages on transition buttons.
			options.addArguments("--headless=new", "--disable-gpu", "--window-size=1920,1200", "--start-maximized", "--incognito", 
					"disable-features=NetworkServiceInProcess", "--ignore-certificate-errors");
		}
		
		// Forcing the browser to download the artifacts directly to the tempdir.
		HashMap<String, Object> chromePref = new HashMap<>();
		chromePref.put("download.default_directory", System.getProperty("java.io.tmpdir"));
		chromePref.put("profile.default_content_settings.popups", 0);
		options.setExperimentalOption("prefs", chromePref);
		options.setExperimentalOption("excludeSwitches", Arrays.asList("disable-popup-blocking"));
		
		//Handle SSL certificate issue in the browser.
		options.setAcceptInsecureCerts(true);
		
		options.setProxy(proxy());

		options.setBrowserVersion("130.0.6723.116");

		// Open the browser
		WebDriver driver = new ChromeDriver(options);
		
		// Below code is to download the file in headless mode
		if(headless)
			((ChromeDriver)driver).executeCdpCommand("Page.setDownloadBehavior", Map.of("behavior", "allow", "downloadPath", System.getProperty("java.io.tmpdir")));
        
		// Maximize the browser only in windows machine
		if (FileOperations.isWindows())
			driver.manage().window().maximize();

		LOG.info("Browser Version: " + ((RemoteWebDriver)driver).getCapabilities().getBrowserVersion());

		return driver;


```
**Expected Result:**
It should launch the CfT version 130.0.6723.116.

**Actual Result:**
It launches the browser but it is crashing.

**Screenshot:**
<img width="781" alt="CfT Screenshot" src="https://github.com/user-attachments/assets/3cddd9c2-e168-4a1c-a2f3-59c8fdf5c780" />

### How can we reproduce the issue?

```shell
Code snippet shared above.
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'INM122110', ip: '192.168.0.105'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at com.rc.alm.it.tests.utilities.setup.WebBrowserConfigurator.invokeChromeDriver(WebBrowserConfigurator.java:115)
	at com.rc.alm.it.tests.utilities.setup.WebBrowserConfigurator.openBrowser(WebBrowserConfigurator.java:58)
	at com.rc.alm.it.gadgetbasetests.GadgetBaseTest.setup(GadgetBaseTest.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:423)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:89)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	... 35 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2792)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Operating System

Windows 10, Linux

### Selenium version

Selenium 4.27.0 and Java version 11

### What are the browser(s) and version(s) where you see this issue?

Chrome for Testing version 130.0.6723.116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver version 130.0.6723.116

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
The snippet is incomplete. For example, you call a method called `proxy(),` which cannot be seen anywhere. 

Please strip different options in your code until you get a starting session. If you still have issues, please join us in our community chat.
