### ISSUE TITLE
Applitools Eyes - IE PDF - parameter not valid exception

### ISSUE THREAD

**Issue by pmelia1** [SeleniumHQ/selenium#1556]
Selenium Eyes version: 1.52.0
IE version: IE 11
Selenium Web Driver version: 2.48.2

Problem general description:
---------------------------------------------------------------

when a pdf file is opened in IE and examined by selenium eyes an exception of parameter not valid is thrown. 

basically the first test step is navigate that contains the location of the pdf file, using the eyes api we are calling CheckWindow() and the exception is thrown.

i believe the issue is the instance of the Selenium IE Web Driver.

<stacktrace below>

this same operation works fine in FF and Chrome.

 
System.ArgumentException was caught
  HResult=-2147024809
  Message=Parameter is not valid.
  Source=System.Drawing
  StackTrace:
       at System.Drawing.Bitmap..ctor(Stream stream)
       at Applitools.EyesBase.CompressScreenshot64_(Rectangle region, Bitmap lastScreenshot, Byte[]& uncompressed)
       at Applitools.EyesBase.GetAppOutput_(Rectangle region, Bitmap lastScreenshot)
       at Applitools.EyesBase.<CheckWindowBase>b__8(Rectangle r, Bitmap lastScreenshot)
       at Applitools.MatchWindowTask.GetAppOutput_(Rectangle region)
       at Applitools.MatchWindowTask.MatchWindow(IList`1 userInputs, Rectangle region, String tag, Boolean shouldRunOnceOnRetryTimeout, Boolean ignoreMismath, Int32 retryTimeout)
       at Applitools.EyesBase.CheckWindowBase(Func`1 getRegion, String tag, Boolean ignoreMismatch, Int32 retryTimeout)
       at Applitools.EyesBase.CheckWindowBase(String tag, Boolean ignoreMismatch, Int32 retryTimeout)
       at Applitools.Eyes.CheckWindow(String tag)
       at PayxAutomationFramework.Engine.Applitools.ApplitoolsAutomationCheckWindow.MethodAction(StepExecution exec) in c:\_DEV\toolagnosticframework\PayxAutomationFramework.Engine.Applitools\AutomationObjectApplitools.cs:line 86

**Comment by lukeis** [comment]
Please contact Applitools for issues with their tool. This issue tracker is for issues with the core selenium library.
