### ISSUE TITLE
PyPI package for 2.51.0 is broken

### ISSUE THREAD

**Issue by snuxoll** [SeleniumHQ/selenium#1592]
The 2.51.0 package on PyPI fails to install because README.rst is not included in the sdist.

**Comment by levi-rs** [comment]
Broken for me as well, in the same place
```
Collecting selenium>=2.49.1 (from armory==0.0.1)
  Using cached selenium-2.51.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/53/x53ckqjs3jjgjc1bq1r_130w0000gn/T/pip-build-p4oyxtg8/selenium/setup.py", line 37, in <module>
        'long_description': open(join(abspath(dirname(__file__)), "py", "README.rst")).read(),
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/53/x53ckqjs3jjgjc1bq1r_130w0000gn/T/pip-build-p4oyxtg8/selenium/py/README.rst'
```

**Comment by lukeis** [comment]
looking into fixing this...

**Comment by snuxoll** [comment]
Looks like MANIFEST.in file still specifies py/README, so it is not getting included in the sdist. Update that line to py/README.rst and it should work.

**Comment by levi-rs** [comment]
https://github.com/SeleniumHQ/selenium/pull/1593

**Comment by lukeis** [comment]
2.51.1 now available

**Comment by lukeis** [comment]
thanks @snuxoll and @levi-rs !
