### ISSUE TITLE
2.51.0 sdist missing py/README.rst

### ISSUE THREAD

**Issue by cboylan** [SeleniumHQ/selenium#1594]
Pip fails to install the new 2.51.0 sdist from pypi because `python setup.py egg_info` fails with the following:

> Complete output from command python setup.py egg_info:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/tmp/pip-build-NoAXbv/selenium/setup.py", line 37, in <module>
>     'long_description': open(join(abspath(dirname(__file__)), "py", "README.rst")).read(),
>     IOError: [Errno 2] No such file or directory: '/tmp/pip-build-NoAXbv/selenium/py/README.rst'

If you grab the sdist from pypi you can confirm that the file is missing:
> wget https://pypi.python.org/packages/source/s/selenium/selenium-2.51.0.tar.gz#md5=1b04ab2b891de9e843ddd2c49477b678
> tar -ztf selenium-2.51.0.tar.gz | grep README.rst

**Comment by cboylan** [comment]
Looks like this was just addressed in a new 2.51.1 release.
