### ISSUE TITLE
goog.global.setTimeout(function() { throw exception; }, 0); Error: ECONNREFUSED connect ECONNREFUSED 192.168.3.227:64224

### ISSUE THREAD

**Issue by dineshsprabu** [SeleniumHQ/selenium#1643]
Hi,

I'm facing the below error on my project. This is happening when i try to quit my driver with driver.quit()
i'm using "selenium-webdriver": "^2.48.2", Mac OSX. Please help me out on this.

/Users/user/Desktop/code/node_scraper/klenty/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^

Error: ECONNREFUSED connect ECONNREFUSED 192.168.3.227:64224
    at ClientRequest.<anonymous> (/Users/user/Desktop/code/node_scraper/klenty/node_modules/selenium-webdriver/http/index.js:174:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
From: Task: WebDriver.navigate().to(function () {
    return this[Math.floor(Math.random() * this.length)]
})
    at webdriver.WebDriver.schedule (/Users/user/Desktop/code/node_scraper/klenty/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:15)
    at webdriver.WebDriver.Navigation.to (/Users/user/Desktop/code/node_scraper/klenty/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1099:23)
    at webdriver.WebDriver.get (/Users/user/Desktop/code/node_scraper/klenty/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:793:26)
    at /Users/user/Desktop/code/node_scraper/klenty/crawlers/crawler.js:193:17
    at Promise._execute (/Users/user/Desktop/code/node_scraper/klenty/node_modules/bluebird/js/release/debuggability.js:180:9)
    at Promise._resolveFromExecutor (/Users/user/Desktop/code/node_scraper/klenty/node_modules/bluebird/js/release/promise.js:460:18)
    at new Promise (/Users/user/Desktop/code/node_scraper/klenty/node_modules/bluebird/js/release/promise.js:76:14)
    at usePhantom (/Users/user/Desktop/code/node_scraper/klenty/crawlers/crawler.js:192:9)
    at crawlMultipleURL (/Users/user/Desktop/code/node_scraper/klenty/crawlers/crawler.js:231:3)
    at getData (/Users/user/Desktop/code/node_scraper/klenty/crawlers/crawler.js:614:10)
    at initiateCrawler (/Users/user/Desktop/code/node_scraper/klenty/routes/index.js:81:19)
    at fn (/Users/user/Desktop/code/node_scraper/klenty/node_modules/async/lib/async.js:746:34)
    at /Users/user/Desktop/code/node_scraper/klenty/node_modules/async/lib/async.js:1213:16
    at /Users/user/Desktop/code/node_scraper/klenty/node_modules/async/lib/async.js:166:37
    at /Users/user/Desktop/code/node_scraper/klenty/node_modules/async/lib/async.js:706:43
    at /Users/user/Desktop/code/node_scraper/klenty/node_modules/async/lib/async.js:167:37

npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.0
npm ERR! npm  v3.5.4
npm ERR! code ELIFECYCLE
npm ERR! node_scraper@0.0.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node_scraper@0.0.1 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node_scraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node_scraper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node_scraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Desktop/code/node_scraper/klenty/npm-debug.log

**Comment by jleyba** [comment]
Have you tried with 2.52.0?

**Comment by jleyba** [comment]
Closing issue due to lack of response. Please reopen if you experience any issues with the latest release.
