### ISSUE TITLE
unicode utf8 chars

### ISSUE THREAD

**Issue by clarkk** [SeleniumHQ/selenium#1647]
Have problems with sending keywords to input fields

**command line**

```
# works
python selenium_scrape.py --query "test"

# returns error (ISO 8859-1)
python selenium_scrape.py --query "bogføringsprogram"

# returns error (UTF-8)
python selenium_scrape.py --query "bogfÃ¸ringsprogram"
```

**code**

``` python
query = ''
opts, args = getopt.getopt(sys.argv[1:], '', ['query='])
for opt, arg in opts:
    if opt == '--query':
        query = arg

box = driver.wait.until(EC.presence_of_element_located(
    (By.NAME, 'q')))
box.send_keys(query)
```

**error**

```
Error: Traceback (most recent call last):
  File "selenium_scrape.py", line 95, in <module>
    main()
  File "selenium_scrape.py", line 86, in main
    lookup(driver, query)
  File "selenium_scrape.py", line 28, in lookup
    box.send_keys(query)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 334, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 469, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 199, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 392, in execute
    data = utils.dump_json(params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/utils.py", line 32, in dump_json
    return json.dumps(json_struct)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 0: invalid start byte
```

**full script**

``` python
import sys
import time
import getopt
import urllib
from pyvirtualdisplay import Display
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.proxy import *

def error(str):
    print>>sys.stderr, str
    sys.exit(1)

def wait_results(driver):
    driver.wait.until(EC.presence_of_element_located(
        (By.ID, 'resultStats')))

def lookup(driver, query):
    if query:
        url = 'https://www.google.dk'
        driver.get(url)

        try:
            box = driver.wait.until(EC.presence_of_element_located(
                (By.NAME, 'q')))
            box.send_keys(query)
            button = driver.wait.until(EC.element_to_be_clickable(
                (By.NAME, 'btnG')))
            button.click()
        except TimeoutException:
            error('Box or Button not found in google.com')

        try:
            wait_results(driver)
            driver.get(url+'/search?q='+urllib.quote_plus(query)+'&start=0&num=100')
            wait_results(driver)
            print driver.find_element_by_tag_name('body').get_attribute('innerHTML').encode('utf-8')
        except TimeoutException:
            error('No results returned by Google. Could be HTTP 503 response')
    else:
        error('Query not set')

def main():
    use_proxy = True

    #   Start display
    display = Display(visible=0, size=(800, 600))
    display.start()

    #   Init args
    query = ''
    proxy_string = ''
    try:
        opts, args = getopt.getopt(sys.argv[1:], '', ['query=','proxy='])
        for opt, arg in opts:
            if opt == '--query':
                query = arg
            elif opt == '--proxy':
                proxy_string = arg
    except getopt.GetoptError as err:
        error(str(err))

    #   Init proxy
    proxy = ''
    if proxy_string:
        proxy = Proxy({
            'proxyType': ProxyType.MANUAL,
            'httpProxy': proxy_string,
            'ftpProxy': proxy_string,
            'sslProxy': proxy_string,
            'noProxy': ''
        })

    #   Init driver
    try:
        if (use_proxy and proxy):
            driver = webdriver.Firefox(proxy=proxy)
        else:
            driver = webdriver.Firefox()
        driver.wait = WebDriverWait(driver, 5)
    except selenium.common.exceptions.WebDriverException as err:
        error(str(err))

    lookup(driver, query)

    time.sleep(5)
    driver.quit()

    #   Stop display
    display.stop()

if __name__ == '__main__':
    main()
```

**Comment by lukeis** [comment]
as a workaround you can do this:

query.decode("utf-8")

**Comment by clarkk** [comment]
I still get the same error.. See in the beginning of my post

```
# works
python selenium_scrape.py --query "test"

# returns error (latin-1)
python selenium_scrape.py --query "bogføringsprogram"

# returns error (utf-8)
python selenium_scrape.py --query "bogfÃ¸ringsprogram"
```

**Comment by alexjosesilva** [comment]
find_elements_by_xpath("td")[3].encode('utf-8')
AttributeError: 'WebElement' object has no attribute 'encode'
