### ISSUE TITLE
Failed to open TCP connection to 127.0.0.1:7055

### ISSUE THREAD

**Issue by mdlx** [SeleniumHQ/selenium#1668]
## Actual Behavior -
Hi, I'm facing an issue on find_element method
the error is:
**Failed to open TCP connection to 127.0.0.1:7055 (Connection refused - connect(2) for "127.0.0.1" port 7055)**
I actually use selenium 2.49.0 with Firefox 32, I've got the same issue using Firefox 44.
**_Note: port number changes between 7055 and 7058_**
Any proposition will be welcome
Thanks in advance for your time
```
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:878:in `connect'
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start'
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/home/ubuntu/dev/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-2.49.0/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
/home/ubuntu/dev/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-2.49.0/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
/home/ubuntu/dev/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-2.49.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/home/ubuntu/dev/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-2.49.0/lib/selenium/webdriver/remote/bridge.rb:645:in `raw_execute'
/home/ubuntu/dev/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-2.49.0/lib/selenium/webdriver/remote/bridge.rb:623:in `execute'
/home/ubuntu/dev/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-2.49.0/lib/selenium/webdriver/remote/bridge.rb:592:in `find_element_by'
/home/ubuntu/dev/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-2.49.0/lib/selenium/webdriver/common/search_context.rb:61:in `find_element'
```

**Comment by p0deje** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
