### ISSUE TITLE
Selenium-java-2.51.0  :- FirefoxDriver: Session not found Exception 

### ISSUE THREAD

**Issue by jagrutv** [SeleniumHQ/selenium#1705]
Selenium-Java-2.51 / Selenium-Java-2.52
Firefox 44.02
when the FirefoxDriver constructor is called, a Firefox window actually opens on my system, then disappears, and then opens up again.

**Code to Create Driver:**

DesiredCapabilities dc = DesiredCapabilities.firefox();
dc.setCapability(CapabilityType.ForSeleniumServer.ENSURING_CLEAN_SESSION, true);
webDriver = new FirefoxDriver(dc);

**Error**
org.openqa.selenium.WebDriverException: Session not found: bc736afa-0123-40f2-8237-33453998f1e0
Command duration or timeout: 47 milliseconds
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:11:55'
System info: host: 'VDDK03P-C26991F', ip: '10.172.139.144', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_80'
*** Element info: {Using=xpath, value=//div[(contains(@data-name,'VI07-Modal') or @data-name='VM03') and contains(@class,'FormPane')]}
Session ID: bc736afa-0123-40f2-8237-33453998f1e0
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=44.0.2}]
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:388)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:504)
	at org.openqa.selenium.By$ByXPath.findElements(By.java:356)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:351)
	at com.lmig.pm.sepg.automation.cfingauto.components.tiles.vehicleinfo.VI07.executeComponent(VI07.java:45)
	at com.lmig.pm.sepg.automation.framework.core.TestRunner.processTestComponent(TestRunner.java:143)
	at com.lmig.pm.sepg.automation.framework.core.TestRunner.processTestDefinition(TestRunner.java:197)
	at com.lmig.pm.sepg.automation.framework.core.TestRunner.execute(TestRunner.java:238)
	at com.lmig.pm.sepg.automation.cfingauto.TestDriver.main(TestDriver.java:18)
Caused by: org.openqa.selenium.WebDriverException: Session not found: bc736afa-0123-40f2-8237-33453998f1e0
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:11:55'
System info: host: 'VDDK03P-C26991F', ip: '10.172.139.144', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_80'
Driver info: driver.version: unknown
	at <anonymous class>.nsCommandProcessor.prototype.execute(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12645)
	at <anonymous class>.Dispatcher.executeAs/<(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9511)
	at <anonymous class>.Resource.prototype.handle(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9658)
	at <anonymous class>.Dispatcher.prototype.dispatch(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9605)
	at <anonymous class>.WebDriverServer/<.handle(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:12458)
	at <anonymous class>.createHandlerFunc/<(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:2054)
	at <anonymous class>.ServerHandler.prototype.handleResponse(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:2387)
	at <anonymous class>.Connection.prototype.process(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1223)
	at <anonymous class>.RequestReader.prototype._handleResponse(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1677)
	at <anonymous class>.RequestReader.prototype._processBody(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1525)
	at <anonymous class>.RequestReader.prototype.onInputStreamReady(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous5797977237632393683webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1393)

**Comment by lukeis** [comment]
your stacktrace is not related to the sample code you provided (it's failing on a call to findElements). Also it shows running 2.51, please upgrade to 2.52

can either reopen or you can create a new bug with a test case to reproduce your errror

**Comment by jagrutv** [comment]
I am getting same error with 2.52 as well. Error occurs when new instance of firefox is created
