### ISSUE TITLE
Selenium-java-2.52 / 2.51, Firefox 44.02 :- FirefoxDriver: Session not found Exception

### ISSUE THREAD

**Issue by jagrutv** [SeleniumHQ/selenium#1707]
modified #1705 with correct StackTrace Information

Tried both Selenium-Java-2.51 and Selenium-Java-2.52 and got same error. I believe Selenium 2.51 was a first version verified against Firefox 44

when the FirefoxDriver constructor is called, a Firefox window actually opens on my system, then disappears, and then opens up again.

Code to Create Driver:

DesiredCapabilities dc = DesiredCapabilities.firefox();
dc.setCapability(CapabilityType.ForSeleniumServer.ENSURING_CLEAN_SESSION, true);
webDriver = new FirefoxDriver(dc);

StackTrace: 

org.openqa.selenium.WebDriverException: Session not found: ccf10884-caf0-4046-9fde-107fab28b762
Command duration or timeout: 125 milliseconds
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:11:55'
System info: host: 'VDDK03P-C26991F', ip: '10.172.139.144', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_80'
Session ID: ccf10884-caf0-4046-9fde-107fab28b762
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=44.0.2}]
at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at org.openqa.selenium.firefox.FirefoxDriver.access$0(FirefoxDriver.java:1)
at org.openqa.selenium.firefox.FirefoxDriver$1$1.implicitlyWait(FirefoxDriver.java:244)
at com.lmig.pm.sepg.automation.framework.core.ApplicationManager.setDriverTimeout(ApplicationManager.java:508)
at com.lmig.pm.sepg.automation.framework.core.ApplicationManager.setCustomTimeout(ApplicationManager.java:489)
at com.lmig.pm.sepg.automation.framework.core.ApplicationManager.resetDriverTimeout(ApplicationManager.java:460)
at com.lmig.pm.sepg.automation.framework.core.ApplicationManager.initializeDriverDefaults(ApplicationManager.java:351)
at com.lmig.pm.sepg.automation.framework.core.ApplicationManager.launchWebDriver(ApplicationManager.java:627)
at com.lmig.pm.sepg.automation.cfingauto.components.TestHarness.executeComponent(TestHarness.java:70)
at com.lmig.pm.sepg.automation.framework.core.TestRunner.processTestComponent(TestRunner.java:143)
at com.lmig.pm.sepg.automation.framework.core.TestRunner.processTestDefinition(TestRunner.java:197)
at com.lmig.pm.sepg.automation.framework.core.TestRunner.execute(TestRunner.java:238)
at com.lmig.pm.sepg.automation.cfingauto.TestDriver.main(TestDriver.java:18)
Caused by: org.openqa.selenium.WebDriverException: Session not found: ccf10884-caf0-4046-9fde-107fab28b762
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:11:55'
System info: host: 'VDDK03P-C26991F', ip: '10.172.139.144', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_80'
Driver info: driver.version: unknown
at .nsCommandProcessor.prototype.execute(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12645)
at .Dispatcher.executeAs/<(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9511)
at .Resource.prototype.handle(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9658)
at .Dispatcher.prototype.dispatch(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9605)
at .WebDriverServer/<.handle(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:12458)
at .createHandlerFunc/<(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:2054)
at .ServerHandler.prototype.handleResponse(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:2387)
at .Connection.prototype.process(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1223)
at .RequestReader.prototype._handleResponse(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1677)
at .RequestReader.prototype._processBody(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1525)
at .RequestReader.prototype.onInputStreamReady(file:///C:/Users/n0198227/AppData/Local/Temp/anonymous1722157769046412429webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1393)

**Comment by lukeis** [comment]
again, your stacktrace does not match the code supplied. And still lists 2.51 being used

**Comment by barancev** [comment]
Seems to be an issue of ApplicationManager that attempts to manipulate drivers.

**Comment by Hemanthvinayac** [comment]
I am using firefox 44.0.2.5884 and Selenium-java-2.51, but firefox browser is not opening. Can anyone please help me

**Comment by jagrutv** [comment]
Are you getting same error as above? I tried different browser capabilities but didn't help much

**Comment by Hemanthvinayac** [comment]
No I am not getting the above error but the browser is not opening and any of the selenium commands not working. And the other thing is like if I run through simple java application it is opening the browser but if I do it in web application using tomcat server browser is not opening.

**Comment by dfdf-santosh** [comment]
I am using "selenium-server-standalone-2.52.0.jar" but still seeing this issue with Firefox driver.

[17:58:10] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[17:58:10] I/launcher - Running 1 instances of WebDriver

[17:58:14] E/launcher - Process exited with error code 1
E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\error.js:27
super(opt_error);
^
WebDriverError: Connection reset
at WebDriverError (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\error.js:27:10)
at Object.checkLegacyResponse (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\error.js:580:13)
at E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\lib\webdriver.js:64:13
at Promise.invokeCallback_ (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\lib\promise.js:1329:14)
at TaskQueue.execute_ (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\lib\promise.js:2790:14)
at TaskQueue.executeNext_ (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\lib\promise.js:2773:21)
at E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\lib\promise.js:2652:27
at E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\lib\promise.js:639:7
at process._tickCallback (node.js:368:9)
From: Task: WebDriver.createSession()
at acquireSession (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\lib\webdriver.js:62:22)
at Function.createSession (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\lib\webdriver.js:295:12)
at Builder.build (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\selenium-webdriver\builder.js:458:24)
at Hosted.DriverProvider.getNewDriver (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\protractor\built\driverProviders\driverProvider.js:37:33)
at Runner.createBrowser (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\protractor\built\runner.js:182:43)
at E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\protractor\built\runner.js:255:30
at _fulfilled (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\q\q.js:834:54)
at self.promiseDispatch.done (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\q\q.js:863:30)
at Promise.promise.promiseDispatch (E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\q\q.js:796:13)
at E:\Eclipse\SwarmJavaComponentUpload\SeleniumProtractorIntellisense\node_modules\q\q.js:556:49

Need help in this regards.

Thanks,
Santhosh

**Comment by dfdf-santosh** [comment]
I tried with WebDriver Hub to create a session for firefox.
http://127.0.0.1:4444/wd/hub/static/resource/hub.html

But it is giving message "Unable to create session"

**Comment by Manusoni** [comment]
which version of Firefox is compatible for selenium 2.53?

**Comment by Hemanthvinayac** [comment]
Firefox version 43 will work
