### ISSUE TITLE
Python/Webdriver, not able to perform any selenese commands

### ISSUE THREAD

**Issue by elenagasilina** [SeleniumHQ/selenium#1753]
## Expected Behavior -
Script runs
## Actual Behavior -
Getting errors:
ERROR: test_1 (__main__.Test1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test1.py", line 23, in test_1
    driver.find_element_by_link_text("Login").click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 282, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: {"method":"link text","selector":"Login"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///var/folders/xz/td457dt94m7001pgpht81bx00000gp/T/tmp869uIK/extensions/fxdriver@googlecode.com/components/driver-component.js:10723)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///var/folders/xz/td457dt94m7001pgpht81bx00000gp/T/tmp869uIK/extensions/fxdriver@googlecode.com/components/driver-component.js:623)

----------------------------------------------------------------------
Ran 1 test in 44.475s

FAILED (errors=1)

## Steps to reproduce -
Run script (python & web driver both recently installed and up to date)

**Comment by lukeis** [comment]
Your traceback shows simply the element was not found on the page. 

Please send further questions to the selenium-users mailing list:
https://groups.google.com/forum/#!forum/selenium-users
