### ISSUE TITLE
directConnect fails for firefox for  firefox-profile 0.3.11,  q 1.4.1

### ISSUE THREAD

**Issue by astrolog** [SeleniumHQ/selenium#1762]
## Expected Behavior -
protractor tests start firefox with directConnect: false without problem while changing to 
directConnect: true gives following output: 
## Actual Behavior -
C:/Users/pl019jaktymo/AppData/Roaming/npm/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337
      return callbackFn(this.value_);
             ^
TypeError: profile.writeToDisk is not a function
    at C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:255:22
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (C:/Users/pl019jaktymo/AppData/Roaming/npm/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriv
er/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (C:/Users/pl019jaktymo/AppData/Roaming/npm/node_modules/protractor/node_module
s/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (C:/Users/pl019jaktymo/AppData/Roaming/npm/node_modules/protractor/node_modules/seleniu
m-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
    at process._tickCallback (node.js:364:9)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:131:30)
    at new Driver (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:278:36)
    at [object Object].DirectDriverProvider.getNewDriver (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\lib\driverProviders\direct.js:74:16)
    at [object Object].Runner.createBrowser (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\lib\runner.js:190:37)
    at C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\lib\runner.js:280:21
    at _fulfilled (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
[launcher] Process exited with error code 1

**Comment by jleyba** [comment]
The provided stack trace isn't from selenium-webdriver 2.52.

> TypeError: profile.writeToDisk is not a function
> at C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:255:22

https://github.com/SeleniumHQ/selenium/blob/selenium-2.51.0/javascript/node/selenium-webdriver/firefox/index.js#L255

Odd that line 255 would fail, but the setPreference call on 254 would pass.

Do things work when you actually use selenium-webdriver 2.52?

**Comment by astrolog** [comment]
I want to use Firefox directly as it is only way to start Firefox with predefined user profile:
directConnect: true,
firefox_profile: myProfile, 
https://github.com/angular/protractor/blob/master/docs/server-setup.md
Without directConnect it uses selenium driver and it works fine. But updating a profile functions are ignored.
I thought it might be a problem with R/W rights so I added custom directory to the call:
var myProfile = new FirefoxProfile(new File("C:/Temp"));
exports.config = {
     directConnect: true,
   browserName: 'firefox', 
   firefox_profile: myProfile, 
}
but it fails in the same way as just only with directConnect: true

**Comment by jleyba** [comment]
I'm not sure what the protractor docs say, but as I understand it, `directConnect: true` just means use the selenium-webdriver package's native FirefoxDriver client instead of going through Selenium's standalone java server.

That said, have you tried upgrading to Selenium 2.52.0?

**Comment by astrolog** [comment]
yes, it is upgraded to 2.52 and works by it fine when I set directConnect to false. But I want to call FirefoxDriver... maybe I posted my issue on wrong forum. I should look for firefox driver support?

**Comment by jleyba** [comment]
What is the error you get with directConnect when using selenium-webdriver 2.52.0?

**Comment by astrolog** [comment]
No error. It works. I have a problem when using Firefox driver only.

**Comment by jleyba** [comment]
Oh, you're using the [firefox-profile](https://www.npmjs.com/package/firefox-profile) package. This module is not API compatible with the `selenium-webdriver` package.

Stop using that and use the `Profile` class from [`selenium-webdriver/firefox`](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/index.html)

**Comment by astrolog** [comment]
How possible? It was made for for selenium WebDriverJs and it cannot be used without it
Please see:
https://www.npmjs.com/package/firefox-profile

**Comment by jleyba** [comment]
Read the documentation I linked to.

**Comment by astrolog** [comment]
OK I tried that but I have again similar issue:
C:/Users/pl019jaktymo/AppData/Roaming/npm/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337
      return callbackFn(this.value_);
             ^
TypeError: profile.writeToDisk is not a function
    at C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:255:22
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (C:/Users/pl019jaktymo/AppData/Roaming/npm/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriv
er/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (C:/Users/pl019jaktymo/AppData/Roaming/npm/node_modules/protractor/node_module
s/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (C:/Users/pl019jaktymo/AppData/Roaming/npm/node_modules/protractor/node_modules/seleniu
m-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
    at process._tickCallback (node.js:364:9)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:131:30)
    at new Driver (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:278:36)
    at Object.<anonymous> (D:\apps\jenkins.home.pre\jobs\Cribis-protractor-production-release-test\workspace\localConf_production.js:14:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[launcher] Process exited with error code 1


 var FirefoxProfile  = require('C:/Users/pl019jaktymo/AppData/Roaming/npm/node_modules/protractor/node_modules/selenium-webdriver/firefox')  

 var myProfile = new FirefoxProfile.Profile("D:/workspace"); 	
 var options = new FirefoxProfile.Options().setProfile(myProfile);
  var driver = new FirefoxProfile.Driver(options);

... 
 
     directConnect: true, 
   browserName: 'firefox', 



and when I try to use binary:

D:\apps\jenkins.home.pre\jobs\Cribis-protractor-production-release-test\workspace>protractor localConf_production.js
ERROR - failed loading configuration file localConf_production.js
C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\lib\configParser.js:204
    throw e;
    ^

TypeError: (intermediate value).setBinary is not a function
    at Object.<anonymous> (D:\apps\jenkins.home.pre\jobs\Cribis-protractor-production-release-test\workspace\localConf_production.js:16:51)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at ConfigParser.addFileConfig (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\lib\configParser.js:195:22)
    at Object.init (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\lib\launcher.js:103:18)
    at Object.<anonymous> (C:\Users\pl019jaktymo\AppData\Roaming\npm\node_modules\protractor\lib\cli.js:140:23)

**Comment by jleyba** [comment]
```
$ npm install selenium-webdriver
selenium-webdriver@2.52.0 node_modules/selenium-webdriver
├── tmp@0.0.24
├── adm-zip@0.4.4
├── ws@1.0.1 (options@0.0.6, ultron@1.0.2)
├── rimraf@2.5.2 (glob@7.0.3)
└── xml2js@0.4.4 (sax@0.6.1, xmlbuilder@5.0.1)
```

```javascript
// profile_test.js
var path = require('path'),
    webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    firefox = require('selenium-webdriver/firefox');

// Configure a profile to use a sample extension used in Selenium's own test suite.
var profile = new firefox.Profile();
profile.addExtension(
    path.join(__dirname, 'node_modules/selenium-webdriver/lib/test/data/firefox/sample.xpi'));

var driver = new webdriver.Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(new firefox.Options().setProfile(profile))
    .build();

driver.get('data:text/html,<html><div>content</div></html>');
driver.getPageSource().then(source => console.log(source));
driver.sleep(2000);
driver.quit();
```

Please direct further questions about using the Selenium API to the user list or ask in the \#selenium IRC channel.
