### ISSUE TITLE
new secound chromedirver but can't run

### ISSUE THREAD

**Issue by wozhapen** [SeleniumHQ/selenium#1798]
## Expected Behavior -
open a new window and can get url run ok

## Actual Behavior -
open a new window, but can't start

## Steps to reproduce -
ubuntu 14.04
google-chrome 49.0.2623.87
chromedriver v2.9.248304
```
ChromeDriver driver1 = new ChromeDriver(chromeDriverService, options);
driver1.get("https://www.stackoverflow.com");
// do something...
ChromeDriver driver2 = new ChromeDriver(chromeDriverService, options);
driver2.get("https://www.google.com");
```

the first driver run ok, but the secound opened a new window and throw error following:
```
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited normally
  (Driver info: chromedriver=2.9.248304,platform=Linux 3.13.0-79-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.02 seconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'zhixiongchen-Latitude-E5440', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-79-generic', java.version: '1.7.0_40'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:159)
	at com.qunar.fresh.EnhanceApp.main(EnhanceApp.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

I find it can't start new session, but I don't what to do... 
when the first driver closed and new the secound new, all is run ok...

**Comment by wozhapen** [comment]
Forgive my poor English...
I just want to new multi chromedriver, and every handle self task.. 
When I use firefox instead of chrome, it ok....but our project only for chrome..

**Comment by barancev** [comment]
You're using chromedriver version 2.9, whereas the latest one is 2.21, please upgrade.
https://sites.google.com/a/chromium.org/chromedriver/

**Comment by wozhapen** [comment]
sorry... I upgrade to 2.21.371461, same problem...

**Comment by wozhapen** [comment]
when I remove
```
options.addArguments("user-data-dir=" + profile_data_path);
```
it ok...

but I need to start chrome with config **Local State**, how can I do..
and remove it I find It can't normal connect when use proxy
```
options.addArguments("proxy-server=\"socks5://127.0.0.1:1080\"");
```

**Comment by barancev** [comment]
Then you have to report this to the chromedriver issue tracker:
https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by wozhapen** [comment]
thank you...
