### ISSUE TITLE
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

### ISSUE THREAD

**Issue by hajarbabour** [SeleniumHQ/selenium#1801]
hi guys i have this problem after running this code 

package test1;

import java.net.MalformedURLException;
import java.net.URL;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.ios.IOSDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
/*
 * 
 
 * 
 */
public class FirsTest1 {
	
	public static AppiumDriver dr;
	
	
	public static void main(String[] args)
throws MalformedURLException{
		 DesiredCapabilities capabilities = new DesiredCapabilities();
		 capabilities.setCapability("deviceName","iPhone 5");
	     capabilities.setCapability("platformName","iOS");
	     capabilities.setCapability("platformVersion","8.1");
	     capabilities.setCapability("appPackage","Setting");
	 dr=new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
	//capabilities.setCapability("appActivity","com.android.contacts.activities.PeopleActivity");
}}

Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:03:33'
System info: host: 'users-iMac.local', ip: '192.168.1.21', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_80'
Driver info: driver.version: IOSDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:162)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:171)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:56)
	at test1.FirsTest1.main(FirsTest1.java:31)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:03:33'
System info: host: 'users-iMac.local', ip: '192.168.1.21', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_80'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 11 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:67)
	... 12 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 25 more

**Comment by lukeis** [comment]
The error suggests you do not have an appium server running on the port shown in the stacktrace. 

If there is an issue here it belongs on the appium project, please log your issue there

**Comment by hajarbabour** [comment]
but i have run the appium  at first and after i run the code and i have
 this error

>
>

**Comment by hajarbabour** [comment]
I change the port to 0.0.0.0 and i still have this error

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException:
A new session could not be created. (Original error: Please provide the
'app' or 'browserName' capability or start appium with the --app or
--browser-name argument. Alternatively, you may provide the 'bundleId' and
'udid' capabilities for an app under test on a real device.) (WARNING: The
server did not provide any stacktrace information)

Command duration or timeout: 330 milliseconds

Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11
19:03:33'

System info: host: 'users-iMac.local', ip: '192.168.1.21', os.name: 'Mac OS
X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_80'

Driver info: io.appium.java_client.ios.IOSDriver

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(
NativeConstructorAccessorImpl.java:57)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(
DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

at org.openqa.selenium.remote.ErrorHandler.createThrowable(
ErrorHandler.java:206)

at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(
ErrorHandler.java:158)

at org.openqa.selenium.remote.RemoteWebDriver.execute(
RemoteWebDriver.java:678)

at io.appium.java_client.DefaultGenericMobileDriver.execute(
DefaultGenericMobileDriver.java:42)

at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)

at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)

at org.openqa.selenium.remote.RemoteWebDriver.startSession(
RemoteWebDriver.java:249)

at org.openqa.selenium.remote.RemoteWebDriver.<init>(
RemoteWebDriver.java:131)

at org.openqa.selenium.remote.RemoteWebDriver.<init>(
RemoteWebDriver.java:144)

at io.appium.java_client.DefaultGenericMobileDriver.<init>(
DefaultGenericMobileDriver.java:37)

at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:162)

at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:171)

at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:56)

at test1.FirsTest1.main(FirsTest1.java:31)

2016-03-14 14:38 GMT+00:00 babour hajar <hajarbabour@gmail.com>:

> but i have run the appium  at first and after i run the code and i have
>  this error
>
>>
>>

**Comment by hajarbabour** [comment]
plz help me

2016-03-14 15:19 GMT+00:00 babour hajar <hajarbabour@gmail.com>:

> I change the port to 0.0.0.0 and i still have this error
>
> Exception in thread "main" org.openqa.selenium.SessionNotCreatedException:
> A new session could not be created. (Original error: Please provide the
> 'app' or 'browserName' capability or start appium with the --app or
> --browser-name argument. Alternatively, you may provide the 'bundleId' and
> 'udid' capabilities for an app under test on a real device.) (WARNING: The
> server did not provide any stacktrace information)
>
> Command duration or timeout: 330 milliseconds
>
> Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11
> 19:03:33'
>
> System info: host: 'users-iMac.local', ip: '192.168.1.21', os.name: 'Mac
> OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_80'
>
> Driver info: io.appium.java_client.ios.IOSDriver
>
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(
> NativeConstructorAccessorImpl.java:57)
>
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(
> DelegatingConstructorAccessorImpl.java:45)
>
> at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>
> at org.openqa.selenium.remote.ErrorHandler.createThrowable(
> ErrorHandler.java:206)
>
> at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(
> ErrorHandler.java:158)
>
> at org.openqa.selenium.remote.RemoteWebDriver.execute(
> RemoteWebDriver.java:678)
>
> at io.appium.java_client.DefaultGenericMobileDriver.execute(
> DefaultGenericMobileDriver.java:42)
>
> at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
>
> at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
>
> at org.openqa.selenium.remote.RemoteWebDriver.startSession(
> RemoteWebDriver.java:249)
>
> at org.openqa.selenium.remote.RemoteWebDriver.<init>(
> RemoteWebDriver.java:131)
>
> at org.openqa.selenium.remote.RemoteWebDriver.<init>(
> RemoteWebDriver.java:144)
>
> at io.appium.java_client.DefaultGenericMobileDriver.<init>(
> DefaultGenericMobileDriver.java:37)
>
> at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:162)
>
> at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:171)
>
> at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:56)
>
> at test1.FirsTest1.main(FirsTest1.java:31)
>
> 2016-03-14 14:38 GMT+00:00 babour hajar <hajarbabour@gmail.com>:
>
>> but i have run the appium  at first and after i run the code and i have
>>  this error
>>
>>>
>>>
>

**Comment by lukeis** [comment]
this is not an appium support forum

Discussion Group - https://discuss.appium.io/
Issues - https://github.com/appium/appium/issues
Appium Chat - http://appium.io/chat

**Comment by hadtinfo** [comment]
To fix this error in linux, you need change director of file log
