### ISSUE TITLE
[ FirefoxDriver]  java.lang.NoClassDefFoundError: org/openqa/selenium/io/CircularOutputStream

### ISSUE THREAD

**Issue by Toilal** [SeleniumHQ/selenium#1823]
## Meta -
OS: Ubuntu 14.04
Selenium Version: 2.53
Browser: Firefox
Browser Version: 45.0

## Expected Behavior -
Creating an instance of FirefoxDriver should work.

## Actual Behavior -
I crash with following message : java.lang.NoClassDefFoundError: org/openqa/selenium/io/CircularOutputStream

## Steps to reproduce -
```java
import org.openqa.selenium.firefox.FirefoxDriver;

public class SeleniumCrash {

    public static void main(String[] args) {
        new FirefoxDriver();
    }

}
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/io/CircularOutputStream
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:60)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at SeleniumCrash.main(SeleniumCrash.java:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.io.CircularOutputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```

**Comment by Toilal** [comment]
I had in my classpath an older version of selenium-remote-driver artefact (because of phantomJS webdriver). Sorry for noise.

**Comment by Buckstabue** [comment]
How did you resolve this? I tried to use an older version of selenium but it cannot handle new firefox versions. I need to include in my project firefoxdriver as well as ghostdriver

**Comment by Toilal** [comment]
`mvn dependency:tree` helped me. Some dependencies of Selenium were resolved to inconsistent versions.

**Comment by AjatshatruSingh** [comment]
Getting this again for selenium 2.53.1 and firefox 44.0.2

Can some one please check this. It used to be working fine till a few days back.

**Comment by kenorb** [comment]
Related: [How to fix NoClassDefFoundError: CircularOutputStream error?](https://stackoverflow.com/q/36586726/55075)
