### ISSUE TITLE
Problem with Jar inside Jar (packaged with spring-boot)

### ISSUE THREAD

**Issue by computerlyrik** [SeleniumHQ/selenium#1840]
## Meta -
OS: Windows 7
Selenium Version: 2.52.0
Browser: Firefox

## Expected Behavior -
I am working with a maven Projekt wich makes use of ‘’’spring boot’’’ framework.
The spring boot application runs Selenium Server, should start a firefox Browser and execute some Selenium Tests.

Spring Boot has the possibility to run the application via '''mvn spring-boot:run'''
**This works perfectly.**

Also, it allowes to package the application inside a JAR-File and execute it with '''java -jar myProject.jar'''
The myproject.jar includes all dependencies inside the lib folder.

The outcome should be the same - start firefox and run the Tests.

## Actual Behavior -

The below error occurs _only_ if I package a jar file an call it with
```java –jar myProject.jar```

```
2016-03-17 17:51:50.731 DEBUG 348 --- [           main] o.o.s.b.locators.FirefoxLocator          : Discovering Firefox 3...
2016-03-17 17:51:50.731 DEBUG 348 --- [           main] o.o.s.b.locators.BrowserLocator          : Discovering Firefox...

2016-03-17 17:51:50.731 DEBUG 348 --- [           main] o.o.s.b.locators.BrowserLocator          : Checking whether Firefox launcher at :'C:\Program Files\Firefox-3\firefox.exe' is valid...
2016-03-17 17:51:50.731 DEBUG 348 --- [           main] o.o.s.b.locators.BrowserLocator          : Checking whether Firefox launcher at :'C:\Program Files (x86)\Firefox-3\firefox.exe' is valid...
2016-03-17 17:51:50.731 DEBUG 348 --- [           main] o.o.s.b.locators.BrowserLocator          : Checking whether Firefox launcher at :'C:\Program Files\Mozilla Firefox\firefox.exe' is valid...
2016-03-17 17:51:50.731 DEBUG 348 --- [           main] o.o.s.b.locators.BrowserLocator          : Checking whether Firefox launcher at :'C:\Program Files (x86)\Mozilla Firefox\firefox.exe' is valid...
2016-03-17 17:51:50.731 DEBUG 348 --- [           main] o.o.s.b.locators.BrowserLocator          : Discovered valid Firefox launcher  : 'C:\Program Files (x86)\Mozilla Firefox\firefox.exe'
jar:file:/D:/myProject-0.0.1-SNAPSHOT.jar!/lib/selenium-server-2.52.0.jar!/customProfileDirCUSTFFCHROME
java.lang.RuntimeException: java.io.FileNotFoundException: D:\myProject-0.0.1-SNAPSHOT.jar!\lib\selenium-server-2.52.0.jar (Das System kann den angegebenen Pfad nicht finden)
        at org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.launch(FirefoxChromeLauncher.java:96)
        at org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.launchHTMLSuite(FirefoxChromeLauncher.java:313)
        at org.openqa.selenium.server.browserlaunchers.FirefoxLauncher.launchHTMLSuite(FirefoxLauncher.java:98)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:146)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:72)
        at mypackage.SeleniumRunner.runTestSuite(SeleniumRunner.java:66)
        at mypackage.SeleniumRunner.run(SeleniumRunner.java:45)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:790)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:777)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
        at mypackage.Application.main(Application.java:13)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: D:\myProject-0.0.1-SNAPSHOT.jar!\lib\selenium-server-2.52.0.jar (Das System kann den angegebenen Pfad nicht finden)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at org.openqa.selenium.server.browserlaunchers.ResourceExtractor.extractResourcePathFromJar(ResourceExtractor.java:75)
        at org.openqa.selenium.server.browserlaunchers.ResourceExtractor.extractResourcePath(ResourceExtractor.java:51)
        at org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.extractProfileFromJar(FirefoxChromeLauncher.java:154)
        at org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.makeCustomProfile(FirefoxChromeLauncher.java:196)
        at org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.launch(FirefoxChromeLauncher.java:85)
```

The selenium-server-jar is inside the myproject.jar in lib/-Folder.
It definitively contains the File Path (customProfileDirCUSTFFCHROME) – I checked the /lib-Folder inside the Jar
=> selenium-server-2.52.0.jar is there
I opened the selenium-server-2.52.0.jar and
=> The described folder is inside.

I think it the call to the folder is unable to get recursively in the jar, but I am not sure.

## Steps to reproduce -
- clone testproject at  https://github.com/computerlyrik/selenium-spring-boot-example
- try ```mvn spring-boot:run```=> this should open http://google.com and exit.
- try ```mvn package``` and ```java -jar target/selenium-spring-boot-example-0.0.1-SNAPSHOT.jar``` => should fail similar to above exception

**Comment by barancev** [comment]
How can we help you?

**Comment by computerlyrik** [comment]
I like to run from package jar without the Exception.

How do i achive this?

See "Steps to reproduce"  - **Step 3 **should work as **Step 2** does.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by computerlyrik** [comment]
This is fixed now by https://github.com/computerlyrik/selenium-spring-boot-example/commit/009df06a88f9edc61ec7303bf924750dc11ac239

See https://github.com/computerlyrik/selenium-spring-boot-example/blob/master/README.md also.
