### ISSUE TITLE
Edge & Phantomjs can't run via server in 3.0-beta

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#1847]
Note: aa924a8 was the first commit since 2.53 where I could even start the remote server to run tests against.

Even after the commit, trying to run phantomjs:
```
-> POST session
   >>> http://127.0.0.1:4445/wd/hub/session | {"desiredCapabilities":{"browserName":"phantomjs","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false}}

13:46:40.848 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
13:46:40.872 INFO - Executing: [new session: Capabilities [{rotatable=false, nativeEvents=false, browserName=phantomjs, takesScreenshot=true, javascriptEnabled=true, version=, platform=ANY, cssSelectorsEnabled=true}]])
13:46:40.887 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: The best matching driver provider org.openqa.selenium.chrome.ChromeDriver can't create a new driver instance for Capabilities [{rotatable=false, nativeEvents=false, browserName=phantomjs, takesScreenshot=true, javascriptEnabled=true, version=, platform=ANY, cssSelectorsEnabled=true}]
Build info: version: '3.0.0-beta1', revision: 'cc199ba', time: '2016-03-19 18:40:53'
System info: host: 'titus-To-be-filled-by-O-E-M', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-32-generic', java.version: '1.8.0_74'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
```
This is essentially the same error for Edge:
```
-> POST session
   >>> http://127.0.0.1:4444/wd/hub/session | {"desiredCapabilities":{"browserName":"MicrosoftEdge","browserVersion":"any","platformName":"any","platformVersion":"any","acceptSslCerts":false,"takesScreenshot":false,"takesElementScreenshot":false,"pageLoadStrategy":"normal","platform":"WINDOWS"}}

12:05:39.927 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
12:05:39.974 INFO - Executing: [new session: Capabilities [{platform=WINDOWS, platformVersion=any, acceptSslCerts=false, browserVersion=any, platformName=any, browserName=MicrosoftEdge, takesElementScreenshot=false, takesScreenshot=false, pageLoadStrategy=normal}]])
12:05:40.048 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: The best matching driver provider org.openqa.selenium.ie.InternetExplorerDriver can't create a new driver instance for Capabilities [{platform=WINDOWS, platformVersion=any, acceptSslCerts=false, browserVersion=any, platformName=any, browserName=MicrosoftEdge, takesElementScreenshot=false, takesScreenshot=false, pageLoadStrategy=normal}]
Build info: version: '3.0.0-beta1', revision: '980fb83', time: '2016-03-19 19:00:02'
System info: host: 'DESKTOP-GQAOG4L', ip: '10.0.2.15', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_79'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
```

Phantomjs & Edge work just fine running directly via Ruby

**Comment by lukeis** [comment]
so in the fun that is crazy-fun, the phantomjs third party jar isn't getting extracted into the standalone, also EdgeDriver and SafariDriver aren't getting included. Tried looking into it, but there's too much black magic happening in crazy fun for me to easily trace what the heck is going on.

@barancev
