### ISSUE TITLE
[Chrome] unknown error: Cannot read property 'getCurrent' of undefined JavaScript stack: TypeError: Cannot read property 'getCurrent' of undefined     at updateWindow

### ISSUE THREAD

**Issue by Mobrockers** [SeleniumHQ/selenium#1853]
## Meta -
OS: Windows 10, Windows server 2008 R2
Selenium Version: 2.52.0
Browser:  Google Chrome
Browser Version: 49

## Expected Behavior -

Error message should be descriptive, or not appear.

## Actual Behavior -

Unknown unfixable error message randomly comes up.

## Steps to reproduce -
No clue. It happens at random, sometimes not for weeks, sometimes a couple times a week.
Issue was reported on google code on 2015-10-07 17:54:32
Old issue found at: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/8714

**Comment by lukeis** [comment]
Issues with chromedriver should be logged on the chromedriver project:
https://sites.google.com/a/chromium.org/chromedriver/help

Also please include what command caused the error and a full stacktrace.

**Comment by Mobrockers** [comment]
It fails on maximizing the browser:
```
org.openqa.selenium.remote.RemoteWebDriver
$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:945)
```
I logged it here because honestly I find the chromedriver project issues to be rather.. user unfriendly, and because I was hoping it was something I was doing wrong and not a bug with chromedriver, so someone here might know.

Full stacktrace:

```
org.openqa.selenium.WebDriverException: unknown error: Cannot read property 'getCurrent' of undefined
JavaScript stack:
TypeError: Cannot read property 'getCurrent' of undefined
    at updateWindow (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:66:17)
    at eval (eval at executeAsyncScript (unknown source), <anonymous>:2:23)
    at executeAsyncScript (<anonymous>:329:26)
    at apply.state (<anonymous>:345:29)
    at callFunction (<anonymous>:237:33)
    at apply.state (<anonymous>:247:23)
    at <anonymous>:248:3
    at Object.InjectedScript._evaluateOn (<anonymous>:878:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:811:34)
    at Object.InjectedScript.evaluate (<anonymous>:667:21)
  (Session info: chrome=49.0.2623.87)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 91 milliseconds
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: '####', ip: '####', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
Session ID: 69ee99850021ab42a4d3a3a0cb123652
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\700028~1\AppData\Local\Temp\scoped_dir8096_6777, chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.87, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, nativeEvents=true, webStorageEnabled=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
Command duration or timeout: 123 milliseconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: '####', ip: '####', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0'
Session ID: acc6190e-8eb9-4607-8543-ac8d0cea2755
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\700028~1\AppData\Local\Temp\scoped_dir8096_6777, chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, webdriver.remote.sessionid=acc6190e-8eb9-4607-8543-ac8d0cea2755, version=49.0.2623.87, takesHeapSnapshot=true, databaseEnabled=false, cssSelectorsEnabled=true, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:945)
	at nl.adaption.it.selenium_test.util.webdrivers.Selenium.getRemoteWebDriver(Selenium.java:58)
	at nl.adaption.it.selenium_test.util.webdrivers.Selenium.getChromeDriver(Selenium.java:42)
	at nl.adaption.it.selenium_test.util.webdrivers.Selenium.getDriverFor(Selenium.java:29)
	at nl.adaption.it.selenium_test.tests.dossier.ITmultiStopVisible.whenOrderTypeIsNormalDossier_AndScenarioIsTransportOnly_AndHasMultiStop_MultiStopRegionShouldExist(ITmultiStopVisible.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.openqa.selenium.WebDriverException: unknown error: Cannot read property 'getCurrent' of undefined
JavaScript stack:
TypeError: Cannot read property 'getCurrent' of undefined
    at updateWindow (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:66:17)
    at eval (eval at executeAsyncScript (unknown source), <anonymous>:2:23)
    at executeAsyncScript (<anonymous>:329:26)
    at apply.state (<anonymous>:345:29)
    at callFunction (<anonymous>:237:33)
    at apply.state (<anonymous>:247:23)
    at <anonymous>:248:3
    at Object.InjectedScript._evaluateOn (<anonymous>:878:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:811:34)
    at Object.InjectedScript.evaluate (<anonymous>:667:21)
  (Session info: chrome=49.0.2623.87)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 91 milliseconds
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: '#####', ip: '#####', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
Session ID: 69ee99850021ab42a4d3a3a0cb123652
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\700028~1\AppData\Local\Temp\scoped_dir8096_6777, chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.87, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, nativeEvents=true, webStorageEnabled=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: '#####', ip: '########', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:825)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWindow.maximize(EventFiringWebDriver.java:630)
	at org.openqa.selenium.remote.server.handler.MaximizeWindow.call(MaximizeWindow.java:30)
	at org.openqa.selenium.remote.server.handler.MaximizeWindow.call(MaximizeWindow.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:170)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
