### ISSUE TITLE
Selenium webdriver exception

### ISSUE THREAD

**Issue by rajeev2013** [SeleniumHQ/selenium#1887]
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/WebDriver
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.WebDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by lukeis** [comment]
Be sure to put selenium on your class path. 

Please follow up with the selenium-users Google group

**Comment by ddavison** [comment]
also, next time you file an issue, please follow the template that was provided. this helps us very much discern what the issue could be.
