### ISSUE TITLE
Couldn't locate element ID with FF 45.0.1 and selenium 2.53.0

### ISSUE THREAD

**Issue by louis57** [SeleniumHQ/selenium#1890]
OS: OSX Capitan
Selenium Version: 2.52.0 and 2.53.0. IDE IntelliJ
Browser: Firefox
Browser Version: 45.0.1

Since new version FF 45.0.1, there's some problem with connection to FF. I tried with the latest Selenium 2.52.0 and 2.53.0, both of them worked, but unfortunately, some elements with ID don't work anymore (which they worked fine before upgrading to FF 45.0.1). Elements with ID couldn't be located and I got exception like: "org.openqa.selenium.WebDriverException: Element is not clickable at point (411, 675). Other element would receive the click: ..." . So I use xpath instead, and it works with xpath

**Comment by gknvenkatakrishnan** [comment]
hi, I have been facing the same issue in Windows 7. My firefox version is FF 45.0.1 and the Selenium Webdriver version is 2.53.

Below is the entire error message that I have encountered. 
Am running this test as a Maven test through POM.XML and getting the error message.

But when I just run the same test as a testng test, it works fine

Can someone please help.

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building mavenArtifact 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mavenArtifact ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\vnarav1\workspace\mavenArtifact\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ mavenArtifact ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ mavenArtifact ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ mavenArtifact ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ mavenArtifact ---
[WARNING] useSystemClassloader setting has no effect when not forking
[INFO] Surefire report directory: C:\Users\vnarav1\workspace\mavenArtifact\target\surefire-reports
Running TestSuite
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
can of loop@mozilla.org
1459347510388	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"WO6Hq98Gs3Fh","location":"app-global","version":"45.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1458092953000,"updateDate":1458092953000,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0.1","maxVersion":"45.0.1"}],"targetPlatforms":[],"seen":true}
1459347510388	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1459347510389	DeferredSave.extensions.json	DEBUG	Save changes
1459347510389	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1459347510389	addons.xpi-utils	DEBUG	Updating add-on states
1459347510390	addons.xpi-utils	DEBUG	Writing add-ons list
1459347510392	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1459347510393	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 0.1
1459347510403	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1459347510403	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1459347510403	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1459347510413	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1459347510413	addons.manager	DEBUG	Provider finished startup: XPIProvider
1459347510413	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1459347510413	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1459347510413	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1459347510413	addons.manager	DEBUG	Starting provider: GMPProvider
1459347510417	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1459347510417	addons.manager	DEBUG	Provider finished startup: GMPProvider
1459347510417	addons.manager	DEBUG	Starting provider: PluginProvider
1459347510417	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1459347510417	addons.manager	DEBUG	Provider finished startup: PluginProvider
1459347510417	addons.manager	DEBUG	Completed startup sequence
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU[GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU|[1][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU[GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
1459347510744	DeferredSave.extensions.json	DEBUG	Starting write
1459347510926	addons.repository	DEBUG	No addons.json found.
1459347510927	DeferredSave.addons.json	DEBUG	Save changes
1459347510928	DeferredSave.addons.json	DEBUG	Starting timer
1459347510953	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1459347510953	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1459347510953	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1459347510955	DeferredSave.extensions.json	DEBUG	Write succeeded
1459347510955	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1459347510992	DeferredSave.addons.json	DEBUG	Starting write
1459347511000	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:275)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at mavenGroup.mavenArtifact.AppTest.pearsonopen(AppTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:647)
	at org.testng.TestRunner.run(TestRunner.java:615)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:155)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:81)
	at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:82)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:974)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:824)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:722)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Mar 30, 2016 10:19:15 AM org.openqa.selenium.os.UnixProcess$SeleniumWatchDog destroyHarder
INFO: Command failed to close cleanly. Destroying forcefully (v2). org.openqa.selenium.os.UnixProcess$SeleniumWatchDog@18460128
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 46.517 sec <<< FAILURE! - in TestSuite
pearsonopen(mavenGroup.mavenArtifact.AppTest)  Time elapsed: 46.407 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
can of loop@mozilla.org
1459347510388	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"WO6Hq98Gs3Fh","location":"app-global","version":"45.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1458092953000,"updateDate":1458092953000,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0.1","maxVersion":"45.0.1"}],"targetPlatforms":[],"seen":true}
1459347510388	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1459347510389	DeferredSave.extensions.json	DEBUG	Save changes
1459347510389	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1459347510389	addons.xpi-utils	DEBUG	Updating add-on states
1459347510390	addons.xpi-utils	DEBUG	Writing add-ons list
1459347510392	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1459347510393	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 0.1
1459347510403	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1459347510403	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1459347510403	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1459347510413	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1459347510413	addons.manager	DEBUG	Provider finished startup: XPIProvider
1459347510413	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1459347510413	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1459347510413	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1459347510413	addons.manager	DEBUG	Starting provider: GMPProvider
1459347510417	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1459347510417	addons.manager	DEBUG	Provider finished startup: GMPProvider
1459347510417	addons.manager	DEBUG	Starting provider: PluginProvider
1459347510417	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1459347510417	addons.manager	DEBUG	Provider finished startup: PluginProvider
1459347510417	addons.manager	DEBUG	Completed startup sequence
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU[GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU|[1][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU[GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
1459347510744	DeferredSave.extensions.json	DEBUG	Starting write
1459347510926	addons.repository	DEBUG	No addons.json found.
1459347510927	DeferredSave.addons.json	DEBUG	Save changes
1459347510928	DeferredSave.addons.json	DEBUG	Starting timer
1459347510953	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1459347510953	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1459347510953	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1459347510955	DeferredSave.extensions.json	DEBUG	Write succeeded
1459347510955	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1459347510992	DeferredSave.addons.json	DEBUG	Starting write
1459347511000	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'USBOSWL-DWKSD72', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:275)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at mavenGroup.mavenArtifact.AppTest.pearsonopen(AppTest.java:16)


Results :

Failed tests: 
  AppTest.pearsonopen:16 » WebDriver Failed to connect to binary FirefoxBinary(C...

Tests run: 3, Failures: 1, Errors: 0, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.539 s
[INFO] Finished at: 2016-03-30T10:19:15-04:00
[INFO] Final Memory: 20M/288M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project mavenArtifact: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\vnarav1\workspace\mavenArtifact\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by csnathan** [comment]
I am also facing the same trouble on FF 45.0.2 and Selenium 2.53

Intermittently, the test runs but most of the time it fails because of unable to open Firefox browser.

Any help would be greatly appreciated.

Thanks!

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
