### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/selenium/io/CircularOutputStream on Junit test startup.

### ISSUE THREAD

**Issue by insacuri** [SeleniumHQ/selenium#1892]
## Meta -
OS: OSX 10.10.2
Selenium Version: 2.53.0 
Browser: Firefox
Browser Version: 45.0.1
IDE: Intellij 

## Expected Behavior -
Junit test would launch the browser and begin testing using concordion.

## Actual Behavior -
No browser launched and this stack trace.

java.lang.NoClassDefFoundError: org/openqa/selenium/io/CircularOutputStream

	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:60)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
	at org.openqa.selenium.firefox.FirefoxDriver.getBinary(FirefoxDriver.java:203)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)
	at <redacted>.web.Browser.<init>(Browser.java:221)
	at <redacted>.web.BrowserUtil.getBrowser(BrowserUtil.java:134)
	at <redacted>.web.BrowserUtil.getBrowser(BrowserUtil.java:62)
	at <redacted>.web.WebConcordionTestBase.getBrowser(WebConcordionTestBase.java:121)
	at <redacted>.web.WebConcordionTestBase.before(WebConcordionTestBase.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.io.CircularOutputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more

## Steps to reproduce -
Nothing special, in intellij, run a junit test that is using 2.53.0 selenium-java and this error occurs.

After playing with the versions, I find that this error message doesn't occur at 2.50.0 but it starts appearing at 2.50.1.  I suspect this commit might have caused it: https://github.com/SeleniumHQ/selenium/commit/976b5e9357229b8acf29f2f0857e0be9d4619306

Using this version and lower ones results in a "org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms." error with a long stack trace (when used with FF45) so downgrading the selenium version isn't an option.

**Comment by insacuri** [comment]
I might've found what it is,  after that commit, the CircularOutputStream was moved to selenium.io but locally for me it remained in selenium.remote.internal.  Though purging my .m2/repository and my .idea/* folders hasn't made a difference.  Any ideas?

**Comment by lukeis** [comment]
@insacuri you should check your dependency graph and see where you might be pulling in old versions of selenium (like if you're depending on phantomjs and aren't excluding it).

**Comment by insacuri** [comment]
@lukeis thanks a bunch, that suggestion was spot on.  Phantomjs was bringing in version 2.44 of the remote driver and making everything fall over.
