### ISSUE TITLE
Refreshing page with different webdriver object not working

### ISSUE THREAD

**Issue by tlktoash** [SeleniumHQ/selenium#1924]
## Meta -
OS: Window 7 
Selenium  Version:2.52.0
Browser:  IE 11 , Chrome  49.0.2623.110 , Firefox
Browser Version: 64 bit

## Expected Behavior -
It should refresh page every time 
## Actual Behavior -
It is not refreshing.
## Steps to reproduce -
I have set of test cases which has to refresh page. 

Steps
1) Navigate to website url
2) login to website
3) Landing page has to refresh again.

above steps is common for most of test cases so we put in common action method. But first test case it succeed and rest of test case it fail only on refreshing page. If i go to website url with out login refresh page in two different test method it work fine. 

FYI: I am killing webdriver instance after each test case finish and creating new one when test start.

 Browser = WebDriverBrowser.Browser.Chrome;
            new LoginPage().NavigateTo<LoginPage>("{url}")
            .LoginToWC2<MenuPage>()
            .WaitFor<MenuPage>(4000)
            .Refresh();
            new MenuPage().WaitFor<MenuPage>(4000);

**Comment by tlktoash** [comment]
Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:38382
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

   
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteNavigator.Refresh()

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
