### ISSUE TITLE
RemoteWebDriver doesn't work with Turkish locale

### ISSUE THREAD

**Issue by poyrazus** [SeleniumHQ/selenium#1930]
## Meta -

OS: Windows 7 (Turkish)
Selenium Version: 2.53.0
Browser: Chrome
Browser Version: 49.0.2623.110 m
## Expected Behavior -

When trying to use RemoteWebDriver, it throws a NullPointerException. When running locally, it works as expected. Whatever driver you use doesn't matter (firefox/chrome/ie). When I add "-Duser.language=en" parameter when running the server, it works as expected. It may be caused by Turkish locale (my OS is in Turkish language).
The stack trace is below:

```
Session ID: 556a79ff-7f85-414e-9ba9-13da336c2ee4
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
    at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:122)
    at SleniumTest2.main(SleniumTest2.java:17)
Caused by: java.lang.NullPointerException
    at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:50)
    at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:1)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```
## Actual Behavior -

The code should work as expected.
## Steps to reproduce -

The following client code could be tested. For those who doesn't have a Turkish OS can reproduce the error by running the server with "-Duser.language=tr" parameter. 

```
public static void main(String[] args) throws MalformedURLException {
        RemoteWebDriver remoteWebDriver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
        remoteWebDriver.get("http://www.google.com");
        WebElement element = remoteWebDriver.findElement(By.name("q"));
        element.sendKeys("hello world");
    }
```

**Comment by barancev** [comment]
I can't reproduce this issue in Selenium Server 3.5.3 running with `-Duser.language=tr` option. Let's pretent the issue has been fixed. If it's still actual don't hesitate to reopen it.
