### ISSUE TITLE
java.lang.AssertionError: org.openqa.selenium.NoSuchWindowException: Unable to find element on closed window (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by Swapan1230** [SeleniumHQ/selenium#1934]
java.lang.AssertionError: org.openqa.selenium.NoSuchWindowException: Unable to find element on closed window (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'WS-IS-SBHOWMIK', ip: '10.0.102.75', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_66'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:5182/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=true, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: e6e17784-40cd-4ba5-94c2-fc1f2817251c
*** Element info: {Using=xpath, value=//a[@href='/content/JuicePlus/en/buy.html']}
	at org.testng.Assert.fail(Assert.java:94)
	at com.jp.us.pagefactory.USJPOrderPersonalPage.uspersnladdqty(USJPOrderPersonalPage.java:61)
	at com.jp.testscripts.USJuicePlusOrderSuite.usjporderpersonalpage(USJuicePlusOrderSuite.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by Swapan1230** [comment]
Please help me to solve the issue.

**Comment by Swapan1230** [comment]
This is solution for Firefox 47 and updated version with selenium beta version (3.0.0-beta2)

DesiredCapabilities capabilities = DesiredCapabilities.firefox();
			capabilities.setCapability("marionette", true);
			System.setProperty("webdriver.firefox.marionette",
					System.getProperty("user.dir") + System.getProperty("file.separator") + "BrowserDrivers"
							+ System.getProperty("file.separator") + "geckodriver.exe");

			driver = new FirefoxDriver(capabilities);

**Comment by Swapan1230** [comment]
This is solution for Firefox 47 and updated version with selenium beta version (3.0.0-beta2)

DesiredCapabilities capabilities = DesiredCapabilities.firefox();
			capabilities.setCapability("marionette", true);
			System.setProperty("webdriver.firefox.marionette",
					System.getProperty("user.dir") + System.getProperty("file.separator") + "BrowserDrivers"
							+ System.getProperty("file.separator") + "geckodriver.exe");

			driver = new FirefoxDriver(capabilities);

**Comment by Swapan1230** [comment]
If you find any problem, please comment it.  I will response you as soon as possible.

**Comment by lukeis** [comment]
if you're using firefox 47, you must ensure you are using 47.0.1

47.0 does not work with webdriver.

Also if you're using the latest GeckoDriver (marionette) you need to be using Firefox 48+

**Comment by Swapan1230** [comment]
I am using  Firefox 47.0.1 and GeckoDriver(0.9) and marionette. It works fine for me.Thanks anyway.
