### ISSUE TITLE
last version of firefox doesn't work with webdriver

### ISSUE THREAD

**Issue by Fantasim** [SeleniumHQ/selenium#1945]
hey,
 
i made a bot that worked perfectly with the previous version of firefox using selenium but now after updating firefox, i've a little issue that i dont really understand. here is my code (where error is):

```
def init():
        firefox_profile = webdriver.FirefoxProfile()
        #firefox_profile = webdriver.FirefoxProfile("/Applications/Firefox.app/Contents/MacOS")
        firefox_profile.set_preference("browser.privatebrowsing.autostart", True)
        driver = webdriver.Firefox(firefox_profile=firefox_profile)
        #driver = webdriver.Firefox()
        driver.set_window_size(480, 320)
        driver.set_window_position(1100, 0)
        return (driver)
```

(when i run my script it's open a new firefox window, it wait 10 secondes on index page and window crash with an error in console)
i have try too without profile, i've same error on line driver = webdriver.Firefox().

and here's the error i get:

```
Traceback (most recent call last):
  File "/Users/fantasim/ecole42/devPython/automatic_twitter/./following.py", line 85, in <module>
    driver = connexion.init()
  File "/Users/fantasim/ecole42/devPython/automatic_twitter/connexion.py", line 10, in init
    driver = webdriver.Firefox(firefox_profile)
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/Library/Python/2.7/site-packages/selenium-2.48.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 103, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details
```

have u any idea?

thank's

**Comment by Fantasim** [comment]
Ok sorry i've find error
I needed to update selenium
