### ISSUE TITLE
Firefox 38.7 does not open in selenium

### ISSUE THREAD

**Issue by SumathiChn** [SeleniumHQ/selenium#1991]
## Meta -
OS:  Windows 7
Selenium Version:  2.44
Browser:  Firefox
Browser Version:  38.7

## Steps to reproduce - Error message mentioned below.

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ing provider: PluginProvider
1461130843741	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1461130843742	addons.manager	DEBUG	Provider finished startup: PluginProvider
1461130843742	addons.manager	DEBUG	Completed startup sequence
2016-04-20 11:10:52: stackwalker.cc:125: INFO: Couldn't load symbols for: wntdll.pdb|CBFD5777D96446E6B2A2062BB8C5EE832
2016-04-20 11:10:52: stackwalker.cc:125: INFO: Couldn't load symbols for: wkernelbase.pdb|E7143382C83F4B9FAD4A421DEFE4D14A1
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x58347c
2016-04-20 11:10:52: stackwalker.cc:125: INFO: Couldn't load symbols for: DgApi.pdb|089DDCB6C5B84B028F4E7D2EB35DE1171
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x5833c8
2016-04-20 11:10:52: stackwalker.cc:125: INFO: Couldn't load symbols for: wkernel32.pdb|85B61A7739C74C638917100792BA161A2
2016-04-20 11:10:52: stackwalker.cc:125: INFO: Couldn't load symbols for: xul.pdb|524D32682A1B4B42800B9944CC68A3312
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x5340ce
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0xebc030f
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x240fd93
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0xeba02a7
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x240fd93
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0xeb9fd47
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x530900
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x3ee9167c
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x3
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x4eb74b8
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x4eb74e8
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0xe424190
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x5
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x1fb6a8
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x4eb74e8
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x2cf1b00
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x2c615c0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0xc
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x2b9
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x2c615c0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0xdc1c460
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x1fb718
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x1fe4d8
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x1
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x1fe398
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x1fe4d8
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x2c615c0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x1
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x2c615c0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x1fb618
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x0
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x1
2016-04-20 11:10:52: basic_code_modules.cc:88: INFO: No module at 0x4e5
JavaScript error: jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/browser/omni.ja!/components/nsBrowserGlue.js, line 1703: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIPrefBranch.getComplexValue]

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:221)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
	at com.aonhewitt.aft.keyword.UseSeleniumWebDriver.Launch(UseSeleniumWebDriver.java:920)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.aonhewitt.aft.keyword.InvokeKeywordForExecution.performAction(InvokeKeywordForExecution.java:50)
	at com.aonhewitt.aft.drivers.ExcelDriver.handleReusablePageComponent(ExcelDriver.java:2122)
	at com.aonhewitt.aft.drivers.ExcelDriver.TestCaseProcessor(ExcelDriver.java:522)
	at com.aonhewitt.aft.drivers.ExcelDriver.Executor(ExcelDriver.java:202)
	at com.aonhewitt.aft.mainClass.AFTMobileAutomation.AFTExecutor(AFTMobileAutomation.java:68)
	at com.aonhewitt.aft.mainClass.AFTMobileAutomation.main(AFTMobileAutomation.java:21)

**Comment by p0deje** [comment]
Please. update to latest Selenium. If the problem persists, re-open the issue.

**Comment by SumathiChn** [comment]
Hi,
Tested with selenium 2.53, still getting error
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.aonhewitt.aft.keyword.InvokeKeywordForExecution.performAction(InvokeKeywordForExecution.java:50)
	at com.aonhewitt.aft.drivers.ExcelDriver.handleReusablePageComponent(ExcelDriver.java:2122)
	at com.aonhewitt.aft.drivers.ExcelDriver.TestCaseProcessor(ExcelDriver.java:522)
	at com.aonhewitt.aft.drivers.ExcelDriver.Executor(ExcelDriver.java:202)
	at com.aonhewitt.aft.mainClass.AFTMobileAutomation.AFTExecutor(AFTMobileAutomation.java:68)
	at com.aonhewitt.aft.mainClass.AFTMobileAutomation.main(AFTMobileAutomation.java:21)
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/remote/internal/CircularOutputStream
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:60)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
	at org.openqa.selenium.firefox.FirefoxDriver.getBinary(FirefoxDriver.java:208)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
	at com.aonhewitt.aft.keyword.UseSeleniumWebDriver.Launch(UseSeleniumWebDriver.java:920)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.internal.CircularOutputStream
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more

**Comment by p0deje** [comment]
This seems to be a problem in your environment (e.g. all the dependencies are not compiled). I'm not Java expert, but it's definitely not a bug in Selenium. You can get a help at [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
