### ISSUE TITLE
Firefox 38.7 does not open in selenium

### ISSUE THREAD

**Issue by SumathiChn** [SeleniumHQ/selenium#1996]
## Meta -
OS:  windows 7
Selenium Version:  2.53
Browser:  Firefox
Browser Version:  38.7

## Steps to reproduce -
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.aonhewitt.aft.keyword.InvokeKeywordForExecution.performAction(InvokeKeywordForExecution.java:50)
	at com.aonhewitt.aft.drivers.ExcelDriver.handleReusablePageComponent(ExcelDriver.java:2122)
	at com.aonhewitt.aft.drivers.ExcelDriver.TestCaseProcessor(ExcelDriver.java:522)
	at com.aonhewitt.aft.drivers.ExcelDriver.Executor(ExcelDriver.java:202)
	at com.aonhewitt.aft.mainClass.AFTMobileAutomation.AFTExecutor(AFTMobileAutomation.java:68)
	at com.aonhewitt.aft.mainClass.AFTMobileAutomation.main(AFTMobileAutomation.java:21)
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/remote/internal/CircularOutputStream
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:60)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
	at org.openqa.selenium.firefox.FirefoxDriver.getBinary(FirefoxDriver.java:208)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
	at com.aonhewitt.aft.keyword.UseSeleniumWebDriver.Launch(UseSeleniumWebDriver.java:920)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.internal.CircularOutputStream
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by p0deje** [comment]
Why do you create another issue? It's the same as #1991

**Comment by SumathiChn** [comment]
issue is not yet resolved.

**Comment by SumathiChn** [comment]
tried with latest version as well

**Comment by p0deje** [comment]
See my comment in #1991
