### ISSUE TITLE
Not able to enter email and password in this site. "Permission denied for 'handle-event'"

### ISSUE THREAD

**Issue by PrabhatPandey** [SeleniumHQ/selenium#2019]
## Meta -

OS: <Ubuntu 14.04? -->
Selenium Version: <2.53.0>
Browser: <Firefox->
Browser Version: <46.0>
## Expected Behavior -

Should enter user name and password in the text box 
## Actual Behavior -

Shows this error message: 

Exception in thread "main" org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Command duration or timeout: 183 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'prabhat-Inspiron-3543', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_80'
**\* Element info: {Using=name, value=email}
Session ID: 8da8e7b8-8148-4d52-8b2b-263aa8b47f5a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=46.0}]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:461)
    at org.openqa.selenium.By$ByName.findElement(By.java:303)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
    at PostInToggle.PivotalTracker.OpenToggleAndLogIn(PivotalTracker.java:43)
    at PostInToggle.PivotalTracker.main(PivotalTracker.java:34)
Caused by: org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'prabhat-Inspiron-3543', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_80'
Driver info: driver.version: unknown
    at <anonymous class>.[55]</</</</<@https://toggl.com/javascripts/5ff8fd43.toggl.js(?)
## Steps to reproduce -

Site where this is happening is "Toggl.com/login"

I wrote the following code 

private static void OpenToggleAndLogIn(WebDriver driver)
            throws InterruptedException {
        String url = "https://toggl.com/login";
        driver.get(url);
        Thread.sleep(20000);
        assert driver.findElements(By.className("login__page--form")).size() != 0;
 //While executing below line , Selenium stops working.  
                WebElement element = driver.findElement(By.name("email"));
        element.sendKeys("Prabhat_pandey");
        driver.findElement(By.xpath("//type[@name='password']")).sendKeys(
                "283119111");
        driver.findElement(By.xpath("button[@type='submit']")).click();

```
}
```

**Comment by lukeis** [comment]
the javascript on the page has a custom event listener that expects the values passed to it to be accessible, something with how selenium is interacting with the page causes the javascript on that page to not be able to access the 'handleEvent' property. I'm not sure what the object in question is, nor how selenium is providing it (if it is). Would be nicer if we could see the d49be1ce.toggl.js file un-minified.

**Comment by PrabhatPandey** [comment]
I was stuck in this issue long time ago. 

I gave up because I couldn't find any solution which worked. 

Thanks for the help anyway.

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
