### ISSUE TITLE
Error forwarding the new session Empty pool of VM for setup Capabilities [{platform=ANY, browserName=firefox, version=46.0}]

### ISSUE THREAD

**Issue by chai4444** [SeleniumHQ/selenium#2043]
## Meta -
OS:  WINDOWS 7

Selenium Version:  
Standalone server 2.53.0

Browser:  
 Firefox
Browser Version:  
 46.0 (64-bit

## Expected Behavior -
should open a fire fox driver where node is running
## Actual Behavior -
getting error on executing the code given below 
error is :- 
Exception in thread "main" org.openqa.selenium.WebDriverException: Error forwarding the new session Empty pool of VM for setup Capabilities [{platform=ANY, browserName=firefox, version=46.0}]
Command duration or timeout: 484 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'ofss312865', ip: '10.180.32.62', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at Drivers.main(Drivers.java:45)
Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session Empty pool of VM for setup Capabilities [{platform=ANY, browserName=firefox, version=46.0}]
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'ofss312865', ip: '10.180.32.62', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_25'
Driver info: driver.version: unknown
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:115)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)

## Steps to reproduce -
created a hub on hum machine : - java -jar selenium-server-standalone-2.53.0.jar -role hub.

created a node on remote machine :-  java -Dwebdriver.server.session.timeout=864000000 -jar selenium-server-standalone-2.53.0.jar -role webdriver -hub http://10.180.32.62:
4444/grid/register -port 4444 -browser browserName=firefox,maxInstances=2 -browser browserName=chrome,maxInstances=2 -browser browserName=iexplore,maxInstances=2 -maxSession 2

node is registed with the hud, verified it on console.

code in Main method including all packages :- 
		 DesiredCapabilities cap =DesiredCapabilities.firefox();
	cap.setBrowserName("firefox");
		cap.setPlatform(Platform.ANY);
		cap.setVersion("46.0");
	
		
		 //RemoteWebDriver d = new RemoteWebDriver(new URL("http://localhost:4444/"),cap);
		 URL TESTURL = new URL("http://localhost:4444/wd/hub");
		 
		WebDriver driver = new RemoteWebDriver(TESTURL, cap);

**Comment by mrchacon** [comment]
Reading a different thread, I found a similar error. The solution was to remove the `-role hub` part and it should work.

This's the thread. https://github.com/angular/protractor/issues/1226

**Comment by lukeis** [comment]
You are specifying a browser in your requested capabilities yet you have no node configured with that version. Browser Name, OS, version are the main things grid hub looks at to decide if the new session request can be forwarded to a node. 

Either specify the browser version when registering the node, or don't specify one when requesting a new session

**Comment by myselfsufiyan** [comment]
@mrchacon , thanks your recommendation for removing `-role hub` works for me.
I am using CentOS 6.8 and its a VPS currently hosting websites for me, I am running selenium 3.0.1.
for selenium remote standalone server with phantomjs (headless) and created a c# .net client that connects and browse to website.. 

I have written all the above, so that anyone else trying to achieve
![screenshot 2017-02-13 23 36 40](https://cloud.githubusercontent.com/assets/5661467/22896270/778646be-f245-11e6-8484-0f968be59242.png)
 things like me can get help...

**Comment by Amrkamel1** [comment]
im getting this error 
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: Unable to create session from {
  "desiredCapabilities": {
    "appActivity": "com.sfdmobile.MainActivity",
    "appPackage": "com.sarajevo.food.dictionary",
    "clearSystemFiles": true,
    "keyPassword": "@0122882435abA",
    "platformVersion": "7.0",
    "automationName": "uiautomator2",
    "autoGrantPermissions": "true",
    "platformName": "Android",
    "deviceName": "192.168.1.9:5556",
    "systemPort": "8240"
  },
  "capabilities": {
    "firstMatch": [
      {
        "platformName": "android"
      },
      {
        "appium:appActivity": "com.sfdmobile.MainActivity",
        "appium:appPackage": "com.sarajevo.food.dictionary",
        "appium:autoGrantPermissions": "true",
        "appium:automationName": "uiautomator2",
        "appium:clearSystemFiles": true,
        "appium:deviceName": "192.168.1.9:5556",
        "appium:keyPassword": "@0122882435abA",
        "platformName": "android",
        "appium:platformVersion": "7.0",
        "appium:systemPort": "8240"
      }
    ]
  }
}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'ws-mirelsp-osx', ip: '192.168.1.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_201'
Driver info: driver.version: unknown
Command duration or timeout: 33 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ws-mirelsp-osx', ip: '192.168.1.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_152-release'
Driver info: driver.version: AndroidDriver

**any idea how to solve this**
