### ISSUE TITLE
Chrome Test Failure

### ISSUE THREAD

**Issue by awaiskhalil** [SeleniumHQ/selenium#2044]
## Meta -
OS:  

Windows 7 , 64-bit
Selenium Version:  

2.53.0 
Browser:  

Google Chrome
Browser Version:  

50.0 (64-bit)
## Expected Behavior -
Test Script should work on Google chrome. 
## Actual Behavior -

Result Message:	Initialization method UnitTestHRPortal.LoginTests.Init threw exception. System.InvalidOperationException: System.InvalidOperationException: unknown error: unrecognized Blink revision: 0c319c380220abe3daf0277e40a2d0b22a7c4550
  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.1 x86_64).
Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor()
   at HRPortalAutomation.Driver.Initialize() in c:\Users\dell\Documents\Visual Studio 2012\Projects\HRPortalAutomation\HRPortalAutomation\Driver.cs:line 18
   at UnitTestHRPortal.LoginTests.Init() in c:\Users\dell\Documents\Visual Studio 2012\Projects\HRPortalAutomation\UnitTestHRPortal\LoginTests.cs:line 16

## Steps to reproduce -

Google chrome Test Script failure while i try to run the same script for firefox and it runs successfully but does not work for chrome.

**Comment by Mobrockers** [comment]
You are using an outdated chromedriver version. Use chromedriver version 2.21 instead.

**Comment by p0deje** [comment]
Please upgrade Chrome and ChromeDriver and try again.

If the issue is still present, please report the bug using [chromedriver bug tracker](https://bugs.chromium.org/p/chromedriver/issues/list).
