### ISSUE TITLE
Random TypeError: no implicit conversion of String into Integer when running with parallel_tests multiple processes

### ISSUE THREAD

**Issue by sauliusgrigaitis** [SeleniumHQ/selenium#2061]
OS:  Ubuntu 14.04 LTS
Selenium Version:  2.53
Browser:  Google Chrome
Browser Version:  50.0.2661.94

Expected Behavior - tests passes without random `TypeError: no implicit conversion of String into Integer`` errors.

Actual Behavior - throws random `TypeError: no implicit conversion of String into Integer` errors when running with `parallel_tests` on multiple processes. It doesn't throw these errors when running with `parallel_tests` with concurency "1" ( single process ). 

Looks like there are some other people experiencing same http://stackoverflow.com/questions/35731868/selenium-combo-throwing-an-error-on-element-id-from

```
 Failure/Error: fill_in 'Email', with: company.email

          TypeError:
            no implicit conversion of String into Integer
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/bridge_helper.rb:47:in `[]'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/bridge_helper.rb:47:in `element_id_from'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:609:in `block in find_elements_by'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:609:in `each'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:609:in `map'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:609:in `find_elements_by'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/search_context.rb:84:in `find_elements'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/selenium/driver.rb:70:in `find_xpath'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:108:in `find_xpath'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/selector_query.rb:112:in `block in resolve_for'  
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:81:in `synchronize'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/selector_query.rb:108:in `resolve_for'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/finders.rb:35:in `block in find'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:85:in `synchronize'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/finders.rb:33:in `find'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/actions.rb:59:in `fill_in'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'  
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
          # ./spec/features/direct_app/sessions_spec.rb:78:in `block (3 levels) in <top (required)>'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/testing.rb:15:in `__set_test_mode'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/testing.rb:29:in `fake!'
          # ./spec/spec_helper.rb:173:in `block (2 levels) in <top (required)>'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:98:in `block in run'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `loop'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:88:in `run'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/rspec-retry-0.4.5/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
          # /var/lib/jenkins/jobs/Project/bundle/ruby/2.3.0/gems/rspec-retry-0.4.5/lib/rspec/retry.rb:22:in `block (2 levels) in setup'
```

**Comment by sauliusgrigaitis** [comment]
This error raises because id here actually is:

Array["message", "chrome not reachable\n (Session info: chrome=50.0.2661.94)\n (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 3.13.0-85-generic x86_64)"]

I would be better to cover such case, because now error is not informative.

**Comment by sauliusgrigaitis** [comment]
This error raises because ```id``` [here](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/bridge_helper.rb#L47) actually is:

 ``` Array["message", "chrome not reachable\n  (Session info: chrome=50.0.2661.94)\n  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 3.13.0-85-generic x86_64)"]```

**Comment by titusfortner** [comment]
That message will happen whenever what is getting passed in as the `id` parameter is not a hash. If you set `$DEBUG = true` you can see exactly what is getting returned from the driver/server. But without further evidence this appears to be a system issue not a Selenium issue.
