### ISSUE TITLE
Getting Unable to locate an element with the xpath expression ./*[self::thead or self::tbody or self::tfoot]/tr

### ISSUE THREAD

**Issue by TARIFABBAS** [SeleniumHQ/selenium#2090]
I am getting the below error, it was working fine with IEDriverServer_v_2.52 but with v_2.53 it is giving this error.
Anyone can suggest why this is happening or its a bug in IE Driver.

STR:-
I have locate the table object.
Then i tried to find all its row within 'thead,tbody,tfoot'.

 org.openqa.selenium.InvalidSelectorException: Unable to locate an element with the xpath expression ./*[self::thead or self::tbody or self::tfoot]/tr because of the following error:
 [object Error] (WARNING: The server did not provide any stacktrace information)
 Command duration or timeout: 67 milliseconds
 For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
 Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
 System info: host: 'WIN-H0KUUCLPECI', ip: '10.0.0.90', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
 Driver info: org.openqa.selenium.ie.InternetExplorerDriver
 Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=false, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=10, platform=WINDOWS, proxy={proxyType=}, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=true, browserName=internet explorer, initialBrowserUrl=http://localhost:44423/, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=ignore}]
 Session ID: 192fca71-ff86-46fd-86bc-a4f806fedd5f
 *** Element info: {Using=xpath, value=./*[self::thead or self::tbody or self::tfoot]/tr}
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
 	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
 	at org.openqa.selenium.remote.RemoteWebElement.findElements(RemoteWebElement.java:214)
 	at org.openqa.selenium.remote.RemoteWebElement.findElementsByXPath(RemoteWebElement.java:299)
 	at org.openqa.selenium.By$ByXPath.findElements(By.java:356)
 	at org.openqa.selenium.remote.RemoteWebElement.findElements(RemoteWebElement.java:190)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 	at java.lang.reflect.Method.invoke(Unknown Source)
 	at com.crestech.opkey.plugin.functiondispatch.CallableMethod.call(CallableMethod.java:30)
 	at com.crestech.opkey.plugin.functiondispatch.CallableMethod.call(CallableMethod.java:11)
 	at java.util.concurrent.FutureTask.run(Unknown Source)
 	at java.lang.Thread.run(Unknown Source)

**Comment by AutomatedTester** [comment]
a reproducible test case requires a sample url or html along with the code to generate the exception. We can try to help / reopen this issue when that is provided
