### ISSUE TITLE
Blank Firefox window and error message in eclipse

### ISSUE THREAD

**Issue by Monloop3r** [SeleniumHQ/selenium#2094]
## Meta -

OS:  Windows 7

Selenium Version:  

Browser:  Firefox

Browser Version:  46

## Steps to reproduce -

code from eclipse--
package eezar_test;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class test_sample {
    public static void main(String[] args) {

```
     WebDriver driver = new FirefoxDriver();
     driver.get("www.gmail.com");
}
```

}

Error:
Exception in thread "main" org.openqa.selenium.WebDriverException: Target URL www.gmail.com is not well-formed.
Command duration or timeout: 620 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'admin-PC', ip: '192.168.0.102', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 14d90792-c7c9-4828-a2d2-0de6707c86c5
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
    at eezar_test.test_sample.main(test_sample.java:15)
Caused by: org.openqa.selenium.WebDriverException: Target URL www.gmail.com is not well-formed.
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'admin-PC', ip: '192.168.0.102', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: unknown
    at <anonymous class>.FirefoxDriver.prototype.get(file:///C:/Users/Monojit/AppData/Local/Temp/anonymous3216851504162366486webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10636)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/Monojit/AppData/Local/Temp/anonymous3216851504162366486webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///C:/Users/Monojit/AppData/Local/Temp/anonymous3216851504162366486webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12666)
    at <anonymous class>.DelayedCommand.prototype.execute/<(file:///C:/Users/Monojit/AppData/Local/Temp/anonymous3216851504162366486webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12608)

**Comment by hazmeister** [comment]
You need to include the protocol when you get a url, try ```driver.get("https://www.gmail.com");```

**Comment by barancev** [comment]
Yes, 'get' command requires a well-formed URL as a parameter.
