### ISSUE TITLE
WebDriverException (Unexpected error. Bad request) occurred during creating a Firefox instance 

### ISSUE THREAD

**Issue by pavelilyinsky** [SeleniumHQ/selenium#2102]
## Meta

OS:  Windows 7
Selenium Version:  2.53.0
Browser:  Firefox 
Browser Version:  46.0 and 46.0.1
## Expected Behavior

The test should continue without the error.
## Actual Behavior

OpenQA.Selenium.WebDriverException was unhandled by user code
  HResult=-2146233088
  Message=Unexpected error. Bad request

  Source=WebDriver
  StackTrace:
       at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
       at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
       at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
       at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile, ICapabilities capabilities, TimeSpan commandTimeout)
       at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile, TimeSpan commandTimeout)
       at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile)
       at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxProfile profile)
       at DigitalkAcceptanceTests.WebTestBase.OpenBrowser() in d:\projects\DigiTalk\DigitalkAcceptanceTests\Base\WebTestBase.cs:line 200
       at DigitalkAcceptanceTests.WebTestBase.TestInitialize() in d:\projects\DigiTalk\DigitalkAcceptanceTests\Base\WebTestBase.cs:line 114
## Steps to reproduce

1) Update Firefox browser to 46.0 or 46.0.1 (note: 45.0.2 version works fine)
2) Try to create instance of Firefox
## Code

`IWebDriver driver;
FirefoxProfile profile = new FirefoxProfile();
profile.SetPreference("browser.download.dir", ResourcePath);
profile.SetPreference("browser.download.folderList", 2);
profile.SetPreference("browser.helperApps.neverAsk.saveToDisk",
"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel,        application/octet-stream, text/csv");
driver = new FirefoxDriver(profile);  // there is the exception`
## Screenshot

![image](https://cloud.githubusercontent.com/assets/16336175/15245871/d5d55970-1911-11e6-8e81-5da4bc712c0a.png)

**Comment by iamgauravkhanna** [comment]
Its working fine for me with same configuration: 

OS: Windows 7
Selenium Version: 2.53.0
Browser: Firefox 
Browser Version: 46.0.1

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
