### ISSUE TITLE
Test failed with UnreachableBrowserException during local automation, but was able to obtain screenshot immediately afterward

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/selenium#2179]
## Meta -
OS:  OSX 10.10.5

Selenium Version:  2.53.0

Browser:  Chrome

Browser Version:  50.0.2661.102 (64-bit)

Driver Version: 2.21.371459

## Expected Behavior -
Driver should have switched to default content.

## Actual Behavior -
```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'C02LM0FDFD59', ip: '10.71.24.187', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=/var/folders/w6/sfgz6j2j5074zm575cbd3qfnhv5szw/T/.org.chromium.Chromium.LvVRqm}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=50.0.2661.102, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 9e444e20f07dc2a1fbc2318c5738511c
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.defaultContent(RemoteWebDriver.java:1039)
	at com.rei.selenous.pages.Page.switchTo(Page.java:377)
	at com.rei.selenous.pages.PageMethodInterceptor.intercept(PageMethodInterceptor.java:68)
	at com.rei.online.test.pages.account.YourAccountLoginPage$$EnhancerByCGLIB$$af8226b0.checkPageLoadCondition(<generated>)
	at com.rei.online.test.pages.account.YourAccountLoginPage.validateLoaded(YourAccountLoginPage.java:28)
	at com.rei.online.test.pages.account.YourAccountLoginPage$$EnhancerByCGLIB$$af8226b0.CGLIB$validateLoaded$6(<generated>)
	at com.rei.online.test.pages.account.YourAccountLoginPage$$EnhancerByCGLIB$$af8226b0$$FastClassByCGLIB$$16df6888.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.rei.selenous.pages.PageMethodInterceptor.intercept(PageMethodInterceptor.java:78)
	at com.rei.online.test.pages.account.YourAccountLoginPage$$EnhancerByCGLIB$$af8226b0.validateLoaded(<generated>)
	at com.rei.selenous.pages.PageValidator$1.apply(PageValidator.java:171)
	at com.rei.selenous.pages.PageValidator$1.apply(PageValidator.java:167)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.rei.selenous.pages.PageValidator.validatePageLoaded(PageValidator.java:119)
	at com.rei.selenous.pages.Pages.validatePageLoaded(Pages.java:93)
	at com.rei.selenous.pages.Pages.initPage(Pages.java:77)
	at com.rei.selenous.support.WebDriverTestSupport.getPageAtUrl(WebDriverTestSupport.java:175)
	at com.rei.selenous.support.WebDriverTestSupport.getPageAtUrl(WebDriverTestSupport.java:160)
	at com.rei.selenous.support.WebDriverTestSupport.getPageAtPath(WebDriverTestSupport.java:128)
	at com.rei.selenous.support.WebDriverTestSupport.getAnnotatedPage(WebDriverTestSupport.java:192)
	at com.rei.online.test.support.ReiOnlineTestSupport.loginToYourAccount(ReiOnlineTestSupport.java:591)
	at com.rei.online.test.support.ReiOnlineTestSupport.createUserAccountAndLogin(ReiOnlineTestSupport.java:437)
	at com.rei.online.test.AccountBillingIT.testNoCVV2FieldInPaymentPreferences(AccountBillingIT.java:379)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
	at com.sun.proxy.$Proxy34.receiveResponseHeader(Unknown Source)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 36 common frames omitted
```
## Steps to reproduce -

The test associated with this failure had progressed quite far by the time the failure occurred. The assertion that the browser may have died is in serious doubt, given that the test framework was able to grab a screenshot and page source, then gracefully closed out the session.

This is a random failure with no easy repro steps. Apparently, if the "SwitchToFrame" command had been retried, it may have succeeded, as commands that were issued afterward were processed successfully.

Could this potentially be an issue with http-thread-pool settings of chromedriver? I don't think these are configurable, but this issue happens more frequently when I run more tests in parallel.

**Comment by lukeis** [comment]
For chrome issues, please log them (with an attempt at a reproducible test case) with chromedriver:

https://sites.google.com/a/chromium.org/chromedriver/help
