### ISSUE TITLE
webelement sreenshot() methoed NOT working

### ISSUE THREAD

**Issue by chenhuahuan** [SeleniumHQ/selenium#2181]
I can take screenshot  with webdriver's member method, however failed with webelement' sreenshot() method, and the error message shows below, does anyone know what's going on? 
I was running the code in Windows, and use selenium

Environment:
Selenium Version: 2.53.2,
Language: Python2.7
OS: Windows 7

#coding=utf-8
from selenium import webdriver
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait # available since 2.4.0
from selenium.webdriver.support import expected_conditions as EC # available since 2.26.0
from selenium.webdriver.common.keys import Keys

driver = webdriver.Firefox()
driver.get('http://global.bing.com/')
driver.get_screenshot_as_file('C:\\bing.png')   #running good so far, the bing.png is saved.

bing_id_elem = driver.find_element_by_id("sbox")
bing_id_elem.screenshot("C:\\test_webelement.png")         #failed here !!!!!                    
driver.close()

Traceback (most recent call last):
  File "C:\Users\chenhh8\workspace\redfish_app_project\KPIFISH_PPT\webelement_screenshot_test.py", line 17, in <module>
    bing_id_elem.screenshot("C:\\test_webelement.png")                   
  File "C:\Python27\lib\site-packages\selenium-2.53.2-py2.7.egg\selenium\webdriver\remote\webelement.py", line 408, in screenshot
    png = self.screenshot_as_png
  File "C:\Python27\lib\site-packages\selenium-2.53.2-py2.7.egg\selenium\webdriver\remote\webelement.py", line 395, in screenshot_as_png
    return base64.b64decode(self.screenshot_as_base64.encode('ascii'))
  File "C:\Python27\lib\site-packages\selenium-2.53.2-py2.7.egg\selenium\webdriver\remote\webelement.py", line 385, in screenshot_as_base64
    return self._execute(Command.ELEMENT_SCREENSHOT)['value']
  File "C:\Python27\lib\site-packages\selenium-2.53.2-py2.7.egg\selenium\webdriver\remote\webelement.py", line 457, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium-2.53.2-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.53.2-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 165, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Unrecognized command: GET /session/afba48dc-2c3e-4ad3-a89d-ae595c7e6029/screenshot/{3331b665-5005-4b78-abcc-90ce309ba5fb}

**Comment by cgoldberg** [comment]
> bing_id_elem.screenshot("C:\test_webelement.png")

in python, backslashes are used as escape characters.. so you can't use them as path separators unless you escape them with another backslash.  You can also use a raw string so this doesn't happen.  you can also use forward slashes when specifying a path (it's legal in Windows).

**Comment by lukeis** [comment]
element screenshots are only implemented in IEDriver i believe. We won't be adding it to FirefoxDriver provided by SeleniumHQ. I would suggest trying GeckoDriver (aka marionette). If it doesn't work there with firefox you can log a bug with mozilla.
