### ISSUE TITLE
Timeout X milliseconds, multiple times, random behaviour

### ISSUE THREAD

**Issue by Gorgia** [SeleniumHQ/selenium#2216]
## Meta -
OS:  Debian 8
Selenium Version:  '2.53.0'
Browser:  Firefox, PhantomJS, Selenium Grid, RemoteWebDriver
Browser Version:  

## Expected Behavior
No exception is expected
## Actual Behavior -
Sometimes, whitout any reason nor clue it raise this exception on command like
"remoteWebDriver.manage().deleteAllCookies()"
"remoteWebDriver.close()"
"remoteWebDriver.navigate.refresh()"
org.openqa.selenium.WebDriverException: Session [12f4af00-2bd6-11e6-9ba7-11adcda9f531] was terminated due to TIMEOUT
Command duration or timeout: 9 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'andrea-Z820-Ubu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-23-generic', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=2.0.0, platform=LINUX, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.2.0, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 12f4af00-2bd6-11e6-9ba7-11adcda9f531
	at sun.reflect.GeneratedConstructorAccessor70.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.deleteAllCookies(RemoteWebDriver.java:773)
[...]
Caused by: org.openqa.grid.common.exception.GridException: Session [12f4af00-2bd6-11e6-9ba7-11adcda9f531] was terminated due to TIMEOUT
	at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:105)
	at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:425)
	at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:240)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:120)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doDelete(DriverServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	... 1 common frames omitted

## Steps to reproduce -
Issue commands for about 15 minutes multiple times on the same instance of remote driver
"remoteWebDriver.manage().deleteAllCookies()"
"remoteWebDriver.close()"
"remoteWebDriver.navigate.refresh()"

**Comment by lukeis** [comment]
Please create / provide a complete sample of test code for people to attempt to reproduce, don't make others work at attempting to reproduce the issue you're encountering.

**Comment by ameyms** [comment]
Hi @Gorgia! Did you figure out a fix for this?

**Comment by ameyms** [comment]
The exception I am seeing is slightly different:

```
Session ID: d59dd11a-8c52-4b00-8fa0-17f7639b0c13
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:614)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.deleteAllCookies(RemoteWebDriver.java:685)
	at com.quantserve.quantjs.QuantJS.tearDown(QuantJS.java:125)
Caused by: org.openqa.selenium.WebDriverException: Session [d59dd11a-8c52-4b00-8fa0-17f7639b0c13] was terminated due to TIMEOUT
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'US01606-ml.corp.qc', ip: '192.168.2.23', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_102'
Driver info: driver.version: unknown
	at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:105)
	at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:423)
	at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:238)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:119)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doDelete(DriverServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.seleniumhq.jetty7.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.seleniumhq.jetty7.servlet.ServletHandler.doHandle(ServletHandler.java:479)
	at org.seleniumhq.jetty7.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.seleniumhq.jetty7.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.seleniumhq.jetty7.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.seleniumhq.jetty7.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.seleniumhq.jetty7.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.seleniumhq.jetty7.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.seleniumhq.jetty7.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.seleniumhq.jetty7.server.Server.handle(Server.java:349)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
	at org.seleniumhq.jetty7.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:47)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:884)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:938)
	at org.seleniumhq.jetty7.http.HttpParser.parseNext(HttpParser.java:634)
	at org.seleniumhq.jetty7.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.seleniumhq.jetty7.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:66)
	at org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:254)
	at org.seleniumhq.jetty7.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Gorgia** [comment]
Close to it.
I think that the problem occurs when you try to send a command to a remote webdriver, before another one has ended its execution.
What I do now, since I use java, is to use a synchronized version of my WebDriver instance.
Probably a better implementation should use a semaphore...

**Comment by ameyms** [comment]
@gorgia thanks. Do you mean you created a `class` that inherits from `RemoteWebDriver` and has all its methods `synchronized`?

**Comment by Gorgia** [comment]
Yes, or use [Synchronized Statements](https://docs.oracle.com/javase/tutorial/essential/concurrency/locksync.html) over each and every WebDriver instance

**Comment by alinpa** [comment]
@gorgia Can you help me with an example how it looks your synchronized class?

**Comment by gorgia** [comment]
I have implemented a Command Pattern with Factory, Spring and Kotlin (_warning: extension function pattern here_):

By the way each call to a function is wrapped in a Synchronized Statement

```
synchronized(webDriver!!) {
            this.webDriver!!.infiniteScroll(heartBitSeconds = heartBeat, maxTimeInMinutes = maxTimeInMinutes, by = by, maxScrollCount = scrollTimes)
        }
```
This way I'd try to avoid multiple call on single remote webdriver.
What I suggest moreover is to keep each task as [atomic](https://en.wikipedia.org/wiki/Linearizability) as possible. This of course include to shutdown and free the webdriver at the end of each the test (or the crawling)
