### ISSUE TITLE
With Windows 10 and IE11, the same issue #8302(JavaScriptExecutor fails) exists.

### ISSUE THREAD

**Issue by ThangaGanesh** [SeleniumHQ/selenium#2232]
## Meta -
OS:  Windows 10
Selenium Version:   2.53.0
Browser: IE11
Browser Version:  11.0.10240.16841(64-bit)

## Error Log:
2016-06-07T22:05:38.333+0530  WARNING  Cannot determine whether page supports ready state. Abandoning wait.
org.openqa.selenium.WebDriverException: JavaScript error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 143 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'INLN50908341A', ip: '192.168.43.239', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.7.0_79'
Session ID: d21453eb-a448-4950-bdcd-3b3a32eb7bfb
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, ie.enableFullPageScreenshot=true, unexpectedAlertBehaviour=dismiss, ie.fileUploadDialogTimeout=3000, ie.forceShellWindowsApi=false, version=11, pageLoadStrategy=normal, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:46412/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=}]
	at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at com.sap.viz.browser.selenium.VizBrowserTestDriver.testPageLoaded(VizBrowserTestDriver.java:1697)
	at com.sap.viz.browser.selenium.VizBrowserTestDriver.waitForPageLoaded(VizBrowserTestDriver.java:351)
	at com.sap.viz.browser.selenium.VizBrowserTestDriver.seleniumDriverOK(VizBrowserTestDriver.java:1220)
	at com.sap.viz.browser.selenium.VizBrowserTestDriver.input(VizBrowserTestDriver.java:1178)
	at com.sap.viz.execution.TestCaseExecution.input(TestCaseExecution.java:1383)
	at com.sap.viz.execution.TestCaseExecution.executebyKeyword(TestCaseExecution.java:905)
	at com.sap.viz.execution.XMLExecutor.ExecuteTestStep(XMLExecutor.java:838)
	at com.sap.viz.execution.XMLExecutor.ExecuteTestStep(XMLExecutor.java:803)
	at com.sap.viz.execution.XMLExecutor.ExecuteTestCase(XMLExecutor.java:780)
	at com.sap.viz.execution.XMLExecutor.ExecuteTestCase(XMLExecutor.java:758)
	at com.sap.viz.execution.XMLExecutor.ExecuteTestSet(XMLExecutor.java:706)
	at com.sap.viz.execution.XMLExecutor.ExecuteAllTestSetsByPlatform(XMLExecutor.java:582)
	at com.sap.viz.execution.XMLExecutor.ExecuteAllTestSets(XMLExecutor.java:575)
	at com.sap.viz.execution.XMLExecutionThread.run(XMLExecutionThread.java:108)
	at java.lang.Thread.run(Thread.java:745)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
