### ISSUE TITLE
Opera driver is not working or help needed to setup i am getting error

### ISSUE THREAD

**Issue by mandalm** [SeleniumHQ/selenium#2243]
OS:  OSX
Selenium Version:  2.53.0 (Standalone)
Browser:  opera 
Browser Version:  37.0

I am trying to make opera integration working but its now working. I have downloaded opera driver. 

I have tried with opera config like this..

```
"capabilities":[
{
      "platform": "MAC",
      "browserName": "opera",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver",
      "chromeOptions":{
        "args":[],
        "extensions":[],
        "binary": "/Applications/Opera.app/Contents/MacOS/Opera"
      },
      "operaOptions":{
        "binary": "/Applications/Opera.app/Contents/MacOS/Opera"
      },
      "binary":"/Applications/Opera.app/Contents/MacOS/Opera"
    }]
```
I have tried all possible help from internet and finally come up with this.

while trying to run as node I am noticing 2 warnings.

01:38:21.708 INFO - Launching a Selenium Grid node
Setting system property webdriver.chrome.driver to /Users/mandalm/Public/selenium_grid/node_modules/selenium-standalone/.selenium/chromedriver/2.21-x64-chromedriver
01:38:22.033 INFO - Java: Oracle Corporation 25.91-b14
01:38:22.033 INFO - OS: Mac OS X 10.10.5 x86_64
01:38:22.037 INFO - v2.53.0, with Core v2.53.0. Built from revision 35ae25b
01:38:22.078 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
01:38:22.078 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
01:38:22.079 INFO - **Driver class not found: com.opera.core.systems.OperaDriver**
01:38:22.079 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
01:38:22.080 INFO - **Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver**
01:38:22.080 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
01:38:22.112 INFO - Selenium Grid node is up and ready to register to the hub
01:38:22.133 INFO - Starting auto registration thread. Will try to register every 5000 ms.
01:38:22.133 INFO - Registering the node to the hub: http://localhost:4444/grid/register
01:38:22.141 INFO - The node is registered to the hub and ready to use

when i am trying to use opera browser this is the error log i have seen. 

01:56:55.406 INFO - Executing: [new session: Capabilities [{rotatable=true, build=2016-06-08T20:26:54.311Z, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@b02f3ab, browserName=opera, javascriptEnabled=true, handlesAlerts=true, maxInstances=1, requestOrigins={name=webdriverio, version=4.0.9, url=http://webdriver.io}}]])
01:56:55.674 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: **The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{rotatable=true, build=2016-06-08T20:26:54.311Z, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@b02f3ab, browserName=opera, project=TGXv2 ads rendering, javascriptEnabled=true, handlesAlerts=true, maxInstances=1, requestOrigins={name=webdriverio, version=4.0.9, url=http://webdriver.io}}]**
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'BAN-MANDALMMAC.local', ip: '192.168.1.104', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_91'
**Driver info: driver.version: unknown**
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: **The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{rotatable=true, build=2016-06-08T20:26:54.311Z, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@b02f3ab, browserName=opera, project=TGXv2 ads rendering, javascriptEnabled=true, handlesAlerts=true, maxInstances=1, requestOrigins={name=webdriverio, version=4.0.9, url=http://webdriver.io}}]**
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'BAN-MANDALMMAC.local', ip: '192.168.1.104', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_91'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:62)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
01:56:55.680 WARN - Exception: The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{rotatable=true, build=2016-06-08T20:26:54.311Z, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@b02f3ab, browserName=opera, project=TGXv2 ads rendering, javascriptEnabled=true, handlesAlerts=true, maxInstances=1, requestOrigins={name=webdriverio, version=4.0.9, url=http://webdriver.io}}]
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_91'
Driver info: driver.version: unknown

Let me know if i missing something. what should i do to fix it?

regards
Mithun Mandal

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
