### ISSUE TITLE
Crashing with Firefox 47

### ISSUE THREAD

**Issue by rachel-carvalho** [SeleniumHQ/selenium#2261]
## Meta -
OS:  OSX 10.11.4
Selenium Version:  2.53.1
Browser:  Firefox
Browser Version:  47.0 64-bit

## Expected Behavior -
It should open Firefox and perform actions

## Actual Behavior -
Firefox quits unexpectedly [(dump)](https://gist.github.com/rachel-carvalho/fdcc3f7dac32e15d6ff31cb0fbd69ed0)

## Steps to reproduce -
[Run ruby API Example from wiki](https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#api-example) will try to open Firefox, it will crash and there's a timeout

```
/Users/rcarvalho/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/firefox/launcher.rb:90:in `connect_until_stable': unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)
	from /Users/rcarvalho/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/firefox/launcher.rb:55:in `block in launch'
	from /Users/rcarvalho/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/common/socket_lock.rb:43:in `locked'
	from /Users/rcarvalho/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/firefox/launcher.rb:51:in `launch'
	from /Users/rcarvalho/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/firefox/bridge.rb:43:in `initialize'
	from /Users/rcarvalho/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/common/driver.rb:53:in `new'
	from /Users/rcarvalho/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/common/driver.rb:53:in `for'
	from /Users/rcarvalho/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver.rb:84:in `for'
	from ../selenium.rb:3:in `<main>'
```

**Comment by lukeis** [comment]
duplicate #2110
