### ISSUE TITLE
java.util.ConcurrentModificationException on grids with many nodes

### ISSUE THREAD

**Issue by ekuefler** [SeleniumHQ/selenium#2263]
## Meta -

OS:  Linux
Selenium Version:  2.53.0 Grid
Browser:  Firefox
Browser Version:  38.3.0 ESR
## Expected Behavior -

A selenium hub should be able to accommodate an arbitrary number of nodes without error
## Actual Behavior -

When running a grid with 256 nodes, I frequently see the following stack trace on the hub:

```
19:17:43.916 ERROR - cannot forward the request null
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
    at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
    at org.apache.http.pool.AbstractConnPool.purgePoolMap(AbstractConnPool.java:469)
    at org.apache.http.pool.AbstractConnPool.closeIdle(AbstractConnPool.java:500)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.closeIdleConnections(PoolingHttpClientConnectionManager.java:358)
    at org.openqa.selenium.remote.internal.HttpClientFactory.getGridHttpClient(HttpClientFactory.java:116)
    at org.openqa.grid.internal.TestSession.getClient(TestSession.java:204)
    at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:365)
    at org.openqa.grid.internal.TestSession.forward(TestSession.java:228)
    at org.openqa.grid.web.servlet.handler.RequestHandler.forwardRequest(RequestHandler.java:97)
    at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:130)
    at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
    at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
    at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
```

This causes tests to fail with exceptions like `org.openqa.selenium.WebDriverException: Session [3216d4b3-1d92-4dbd-a9b2-d682e3406272] was terminated due to FORWARDING_TO_NODE_FAILED`
## Steps to reproduce -

Run a hub with a large number of selenium nodes and attempt to start a large number of tests simultaneously

**Comment by barancev** [comment]
The root cause is this issue: https://issues.apache.org/jira/browse/HTTPCLIENT-1453
Selenium now uses more recent httpclient version that has this issue fixed.
