### ISSUE TITLE
Firefox 47.0

### ISSUE THREAD

**Issue by marcelosato** [SeleniumHQ/selenium#2264]
## Meta -
OS:  Mac OS

Selenium Version:  2.53

Browser:  Firefox 47

Browser Version:  

## Expected Behavior -
Open Firefox
## Actual Behavior -
Not Open

**Comment by lukeis** [comment]
dup #2110

**Comment by marcelosato** [comment]
Ok, sorry!

**Comment by marcelosato** [comment]
Exception in thread "Thread-2" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'unknown68a86d26ce14', ip: '192.168.15.90', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_40'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at com.wavecode.controller.PregaoController.autenticarLicitacoesE(PregaoController.java:478)
	at com.wavecode.controller.PregaoController.run(PregaoController.java:124)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:7055 [/127.0.0.1] failed: Connection refused
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:162)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:160)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:380)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 9 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	... 24 more

**Comment by marcelosato** [comment]
Hi 
Hi Luke,
i am verify  #2110 but the problem not be solved and the issue has closed...

the problem persist ->
The stacktrace ->
Exception in thread "Thread-2" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'System info: host: 'unknown68a86d26ce14', ip: '192.168.15.90', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_40'Driver info: driver.version: FirefoxDriverat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:131)at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:218)at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:211)at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:207)at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:120)at com.wavecode.controller.PregaoController.autenticarLicitacoesE(PregaoController.java:478)at com.wavecode.controller.PregaoController.run(PregaoController.java:124)at java.lang.Thread.run(Thread.java:745)Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:7055 [/127.0.0.1] failed: Connection refused

Thanks,





Atenciosamente,


Marcelo Kinjiro Sato
MSN: marceloks@hotmail.com
Skype: marceloksato

Date: Fri, 10 Jun 2016 12:59:10 -0700

**Comment by lukeis** [comment]
#2110 is still open, please read the comments there
