### ISSUE TITLE
Unable to execute WebDriver scripts using Ant, Maven and testng

### ISSUE THREAD

**Issue by gitissuepost** [SeleniumHQ/selenium#2305]
## Meta -
OS:  Windows 7

Selenium Version:  2.53

Browser:  Firefox

Browser Version:  2.46

## Expected Behavior -
Ant build.xml will run my webdriver script
## Actual Behavior -
It is ending up with an exception below.
com.google.common.collect.Multimaps.transformValues(Lcom/google/common/collect/ListMultimap;Lcom/google/common/base/Function;)Lcom/google/common/collect/ListMultimap;
                        	at com.google.common.net.MediaType.toString(MediaType.java:668)
                        	at org.openqa.selenium.remote.http.JsonHttpCommandCodec.encode(JsonHttpCommandCodec.java:232)
                        	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:139)
                        	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:160)
                        	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:380)
                        	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
                        	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
                        	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
                        	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
                        	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
                        	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
                        	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
                        	at testng.advanced.practice.TestNGAnnotations.superTest(Unknown Source)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:498)
                        	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
                        	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
                        	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
                        	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
                        	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
                        	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
                        	at org.testng.TestRunner.privateRun(TestRunner.java:782)
                        	at org.testng.TestRunner.run(TestRunner.java:632)
                        	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
                        	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
                        	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
                        	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
                        	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
                        	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
                        	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
                        	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
                        	at org.testng.TestNG.run(TestNG.java:1064)
                        	at org.testng.TestNG.privateMain(TestNG.java:1385)
                        	at org.testng.TestNG.main(TestNG.java:1354)
## Steps to reproduce -

Build.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="TestNG Advanced" default="build">
	<property environment="env" />
	<property name="project.version" value="0.0.1" />
	<property name="project.name" value="selenium-wrapper" />

	<property name="src.dir" value="${basedir}/src" />
	<property name="target.dir" value="${basedir}/target" />
	<property name="archive.dir" value="${basedir}/archives" />
	<property name="resource.dir" value="${basedir}/resources" />
	<property name="distribution.dir" value="${basedir}/dist" />

	<property name="testng.report.src" value="${basedir}/test-output" />

	<property name="maven.classpath" value="${user.home}/.m2/repository" />
	<property name="maven.compile.dir" value="${target.dir}/classes" />
	<property name="compile.dir" value="${maven.compile.dir}" />
	<property name="classpath.dir" value="${maven.classpath}" />

	<path id="project_classpath">
		<fileset dir="${classpath.dir}" includes="**/*.jar" />
	</path>

	<path id="execution_classpath">
		<path location="${compile.dir}" />
		<path refid="${project_classpath}" />
	</path>

	<tstamp>
		<format property="time.stamp" pattern="yyyyMMdd_HHmmss" />
	</tstamp>

	<target name="-clean">
		<delete dir="${compile.dir}" includeemptydirs="true" failonerror="true" />
		<delete dir="${testng.report.src}" includeemptydirs="true" failonerror="true" />
	</target>

	<target name="-setup" depends="-clean">
		<mkdir dir="${compile.dir}" />
		<mkdir dir="${testng.report.src}" />
	</target>

	<target name="-compile" depends="-setup">
		<copy todir="${compile.dir}" overwrite="true">
			<fileset dir="${src.dir}" excludes="**/*.java" />
		</copy>
		<javac srcdir="${src.dir}" destdir="${compile.dir}" classpathref="project_classpath" includeantruntime="false" />
	</target>

	<taskdef name="testng" classname="org.testng.TestNGAntTask">
		<classpath id="testng.classpath">
			<path refid="project_classpath" />
			<path location="${compile.dir}" />
		</classpath>
	</taskdef>

	<target name="build" depends="-compile">
		<testng outputDir="${testng.report.src}" classpathref="testng.classpath">
			<xmlfileset dir="${basedir}" includes="testng.xml" />
			<sysproperty key="org.uncommons.reportng.escape-output" value="false" />
		</testng>
	</target>
</project>

pom.xml - 
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>TestNG_Advanced</groupId>
	<artifactId>TestNG_Advanced</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<log4j.version>1.2.17</log4j.version>
		<selenium.version>2.53.0</selenium.version>
		<testng.version>6.9.10</testng.version>
	</properties>

	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<suiteXmlFiles>
						<suiteXmlFile>testng.xml</suiteXmlFile>
					</suiteXmlFiles>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testng.version}</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>${selenium.version}</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>${log4j.version}</version>
		</dependency>
	</dependencies>
</project>

testng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="TestNG Advanced">
	<listeners>
		<listener class-name="org.uncommons.reportng.HTMLReporter" />
		<listener class-name="org.uncommons.reportng.JUnitXMLReporter" />
	</listeners>
	<test name="TestNG Advanced">
		<classes>
			<class name="testng.advanced.practice.TestNGAnnotations" />
		</classes>
	</test>
</suite>

TestAnnonations.java
package testng.advanced.practice;

import java.io.IOException;
import java.util.Date;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Reporter;
import org.testng.annotations.Test;

public class TestNGAnnotations {
	@Test(dependsOnMethods = { "superTest", "dependTest" })
	public void testNGTest() {
		Reporter.log("In Test");
	}

	@Test
	public void dependTest() throws IOException {
		Reporter.log("Depend Test");
	}

	@Test
	public void superTest() {
		Reporter.log("Super Test");
		WebDriver driver = new FirefoxDriver();
		driver.get("http://www.google.com");
	}
}

**Comment by gitissuepost** [comment]
Not sure why I am unable to see the testng.xml. Here it is
<suite name="TestNG Advanced">
	<test name="TestNG Advanced">
		<classes>
			<class name="testng.advanced.practice.TestNGAnnotations" />
		</classes>
	</test>
</suite>

**Comment by lukeis** [comment]
We only troubleshoot selenium issues here, not ant. You can try to ask for help on the selenium-users google group. 

Since you mentioned Firefox, I'm going to assume you're using the latest (47) and if so this is a duplicate issue of #2110
