### ISSUE TITLE
Selenium 3: if Marionette Session gets closed in between tests then the Exception generated doesn't tell connection has been closed or something like that

### ISSUE THREAD

**Issue by abhinav1708** [SeleniumHQ/selenium#2357]
## Meta -
OS:  Win 7 64

Selenium Version: Selenium 3 Beta  

Browser:  Firefox 47

Browser Version:  

## Expected Behavior - 
It should Generated Exception clearly display that Connection is closed or Something like that

## Actual Behavior -
Exception Generated in this Case
org.openqa.selenium.WebDriverException: Failed to decode response from marionette (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 19 milliseconds
Build info: version: '2.42.2', revision: '75f266f', time: '2014-07-30 09:11:33'
System info: host: 'NOI1-CIS616', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160604131506, version=47.0, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=47.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: c0018882-0a3a-45f7-8a48-43fca8499b7b
*** Element info: {Using=css selector, value=#username}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:683)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:377)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:498)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:429)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:369)

## Steps to reproduce -

Start your Test
Click Marionette instance in between your tests
WebDriver will generate this exception and exit

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
