### ISSUE TITLE
Selenium 3 : Virtual - driver.manage().window().fullscreen() throwing org.openqa.selenium.UnsupportedCommandException

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2365]
## Meta -

OS:  Win 8.1

Selenium Version:  Selenium 3 Beta

Browser:  FF 

Browser Version:  30

## Expected Behavior -

driver.manage().window().fullscreen(); should not throw exception.
## Actual Behavior -

driver.manage().window().fullscreen(); function throws exception after opening the page in full window. 
## Steps to reproduce -

1) Try using driver.manage().window().fullscreen() function in any of your project.
2) Execute the script.
## Stack Trace-

org.openqa.selenium.UnsupportedCommandException: POST /session/2bec213d-fb74-49cf-92f9-664ecd567843/window/fullscreen did not match a known command (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8 milliseconds
Build info: version: '2.42.2', revision: '75f266f', time: '2014-07-30 09:11:33'
System info: host: 'nd0308002035289', ip: '192.168.172.151', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_65'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160604131506, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=47.0, platformVersion=6.3, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 2bec213d-fb74-49cf-92f9-664ecd567843
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
                at java.lang.reflect.Constructor.newInstance(Unknown Source)
                at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
                at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:683)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:706)
                at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.fullscreen(RemoteWebDriver.java:958)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
                at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
                at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
                at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
                at org.testng.TestRunner.beforeRun(TestRunner.java:641)
                at org.testng.TestRunner.run(TestRunner.java:609)
                at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
                at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
                at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
                at org.testng.SuiteRunner.run(SuiteRunner.java:240)
                at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
                at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
                at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
                at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
                at org.testng.TestNG.run(TestNG.java:1057)
                at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
                at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
                at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by acikojevic** [comment]
Same issue on Selenium 2.53.1
OS: WIN 8.1
Browser: FF
Version: 47.0.1

**Comment by BigVOVA** [comment]
Same issue on Selenium 2.53.1
OS: OS x 10.12
Browser: Chrome
Version: 53.0.2785.116

**Comment by imageica** [comment]
Same issue on Selenium 3.0.1
OS: OS x 10.11.6 
Browser: Safari
Version: 10

**Comment by karankural** [comment]
Same Issue on selenium 3.4.0
OS : Mac OS Sierra 10.12.2 
Browser : Chrome
Version : 59

**Comment by Bose27** [comment]
Same Issue on selenium 3.3.1
OS : Mac OS Sierra 10.12.4
Browser : Firefox 
Version : 52

**Comment by p0deje** [comment]
This command is only supported in GeckoDriver since 0.17. Please try with latest GeckoDriver and, if it still doesn't work, provide a [concise reproducible test case](http://sscce.org/) so that we could act on this issue.
