### ISSUE TITLE
sendKeys throwing error with contenteditable

### ISSUE THREAD

**Issue by jsdevel** [SeleniumHQ/selenium#2392]
## Meta -
OS:  Linux
Selenium Version:  2.53.2
Browser:  PhantomJS
Browser Version:  2.1.7

## Expected Behavior -
.sendKeys is able to send key sequences to contenteditable elements.

## Actual Behavior -
The following error is returned:
```
     WebDriverError: {"errorMessage":"undefined is not an object (evaluating 'b.value.length')","request":{"headers":{"Accept":"application/json; charset=utf-8","Connection":"close","Content-Length":"55","Content-Type":"application/json;charset=UTF-8","Host":"192.168.5.3:55158"},"httpVersion":"1.1","method":"POST","post":"{\"value\":[\"f\",\"f\",\"f\",\"f\",\"d\",\"f\",\"d\",\"f\",\"d\",\"f\",\"d\"]}","url":"/value","urlParsed":{"anchor":"","query":"","file":"value","directory":"/","path":"/value","relative":"/value","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/value","queryKey":{},"chunks":["value"]},"urlOriginal":"/session/78624e40-3d08-11e6-b2de-f52277c9effa/element/:wdc:1467101730092/value"}}
         at WebDriverError (/home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/error.js:26:26)
         at Object.checkLegacyResponse (/home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/error.js:639:15)
         at parseHttpResponse (/home/joseph/projects/jernl/node_modules/selenium-webdriver/http/index.js:538:13)
         at /home/joseph/projects/jernl/node_modules/selenium-webdriver/http/index.js:472:11
         at ManagedPromise.invokeCallback_ (/home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/promise.js:1379:14)
         at TaskQueue.execute_ (/home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/promise.js:2913:14)
         at TaskQueue.executeNext_ (/home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/promise.js:2896:21)
         at /home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/promise.js:2820:25
         at /home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/promise.js:639:7
         at process._tickCallback (node.js:377:9)
     From: Task: WebElement.sendKeys()
         at Driver.schedule (/home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
         at WebElementPromise.schedule_ (/home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/webdriver.js:1744:25)
         at WebElementPromise.sendKeys (/home/joseph/projects/jernl/node_modules/selenium-webdriver/lib/webdriver.js:1924:19)
         at World.module.exports.__setDriver.fillFormWithProfile.typeTextInElementWithinElement (/home/joseph/projects/jernl/e2e/web-support/actions.js:38:115)
         at doNTCallback0 (node.js:428:9)
```

## Steps to reproduce -
```
<div contenteditable=true></div>
```

Call `.sendKeys('asdf')` on it.

**Comment by lukeis** [comment]
for issues with phantomjs please log an issue with the ghostdriver project:
https://github.com/detro/ghostdriver
