### ISSUE TITLE
Failed to load module node_modules/selenium-webdriver

### ISSUE THREAD

**Issue by SergeyBondarenko** [SeleniumHQ/selenium#2405]
## Meta -
OS:  Ubuntu 14

Selenium Version: 2.53  

Browser:  Chrome

Browser Version:  51.0.2704.103 (64-bit)

## Expected Behavior -
The selenium-driver is imported.

## Actual Behavior -
```
Got following parameters:
seleniumserver.port: 4444
chrome.driver.path: selenium/chromedriver/linux64/chromedriver
kibi.url: http://192.168.50.10
kibi.shield.password: undefined
kibi.shield.username: undefined
Running "intern:community" (intern) task
Error: Failed to load module node_modules/selenium-webdriver from /home/trex/Development/Siren/kibi-integration/node_modules/selenium-webdriver.js (parent: tests/functional/support/page/Datasource)
  at ReadFileContext.callback  <node_modules/intern/node_modules/dojo/loader.ts:831:119>
  at FSReqWrap.readFileAfterOpen [as oncomplete]  <fs.js:303:13>
Warning: Test failure; check output above for details. Use --force to continue.
```

## Steps to reproduce -

/*global define*/
An exempt of my code.
```
define([
  'intern!object',
  'intern/chai!assert',
  'require',
  '../support/page/EnhSearchTable',
  '../support/page/KibiDashboard',
  '../support/page/Datasource'
], function (registerSuite, assert, require, EnhSearchTable, KibiDashboard, Datasource) {
  var intern = require('intern');
  var args = intern.args;
  var webdriver = require('selenium-webdriver');
  var driver = new webdriver.Builder().build();
...
...
...
});
```

**Comment by jleyba** [comment]
You've provided no information to indicate this is a bug with selenium and not your particular environment. We can revisit this if you can provide a precise reproducible test case.

Also, from my end:

```
$ npm install selenium-webdriver
selenium-webdriver@2.53.3 node_modules/selenium-webdriver
├── tmp@0.0.24
├── adm-zip@0.4.4
├── ws@1.1.1 (options@0.0.6, ultron@1.0.2)
├── xml2js@0.4.4 (xmlbuilder@8.2.2, sax@0.6.1)
└── rimraf@2.5.2 (glob@7.0.5)

$ node -e "console.log(typeof (require('selenium-webdriver')))"
object
```
