### ISSUE TITLE
ChromeDriver Timed Out after 60 seconds on new ChromeDriver()

### ISSUE THREAD

**Issue by paulodrjr** [SeleniumHQ/selenium#2424]
## Meta -
OS:  Windows 10 and others

Selenium Version:  2.53.1

Browser:  Chrome 

Browser Version:  51.0.2704.106 m

## Expected Behavior -
ChromeDriver server to respond
## Actual Behavior -
Inside Visual Studio, both in debug or run modes, ChromeDriver server console opens and runs as expected, almost instantly. However, running outside Visual Studio, in a Windows Service application, the server keeps timing out, every time, with the following messages and Call Stack:

Message: 
The HTTP request to the remote WebDriver server for URL http://localhost:9413/session timed out after 60 seconds.

Call Stack:
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)

## Steps to reproduce -
using (Driver = new ChromeDriver())
{
   //some code
}

**Comment by AlanMcCann** [comment]
I am having what appears to be the same issue

OS: Windows 10 and others
Selenium Version: 2.53.4 (backtested to 2.53.0)
Browser: Chrome
Browser Version: 51.0.2704.106 m

```
[2] pry(main)> driver = Selenium::WebDriver.for :chrome
EOFError: end of file reached
from /Users/alanmccann/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
```

**Comment by paulodrjr** [comment]
I found the reason of the problem in another forum: I was schedulling the service with the default Windows account. It has to be run under a user account. Maybe in OS X it is similar?

**Comment by AlanMcCann** [comment]
Mine must be unrelated then. I will create another issue.

**Comment by lukeis** [comment]
Glad you found the solution to the problem

**Comment by Dan-DeAraujo** [comment]
@paulodrjr would you mind sharing the solution details (or a link to said forum)? I'm having identical symptoms and thought my setup was configured for a user account, but maybe i screwed something up.... ¯\_(ツ)_/¯

Thanks
Dan

**Comment by paulodrjr** [comment]
@Dan-DeAraujo, I can't remember where I found this solution. However, it was simple as I said: I just configured the service with my own user account. Good luck!
