### ISSUE TITLE
Launching Safari WebDriver is opening a localhost:xxxx page and gives error UnreachableBrowserException

### ISSUE THREAD

**Issue by BartVanRaemdonck** [SeleniumHQ/selenium#2427]
## Meta -
OS:  
OSX
Selenium Version:  
2.53
Browser:  
Safari

Browser Version:  
9.1.1 (10601.6.17)

## Expected Behavior -
Opens up a Safari browser en goes to a page

## Actual Behavior -

Opens up a Safari browser and tries going to localhost:xxxx  and then launches an error:

```
jul 05, 2016 2:03:01 PM org.openqa.selenium.safari.SafariDriverServer start
INFO: Server started on port 42753
jul 05, 2016 2:03:01 PM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFO: Launching Safari
jul 05, 2016 2:03:01 PM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFO: Waiting for SafariDriver to connect
jul 05, 2016 2:03:11 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
jul 05, 2016 2:03:11 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping Safari
jul 05, 2016 2:03:12 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
jul 05, 2016 2:03:12 PM org.openqa.selenium.safari.SafariDriverServer stop
INFO: Stopping server
jul 05, 2016 2:03:12 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
jul 05, 2016 2:03:12 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
jul 05, 2016 2:03:12 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
jul 05, 2016 2:03:12 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete

org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10069 ms
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'MacBook-Pro-van-MacBook-2.local', ip: '192.168.0.100', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_45'
Driver info: driver.version: SafariDriver

	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:121)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:72)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:58)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:42)
	at tests.MostRecentComponentTest.setUp(MostRecentComponentTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

```

## Steps to reproduce -

install the safari extension
install the safari certificate

WebDriver driver = new SafariDriver();
driver.get("google.be");

**Comment by shahp00ja** [comment]
@BartVanRaemdonck 
it works flawlessly on 
```
Safari: 9.1.1 (10601.6.17)
Selenium : 2.53
Mac: 10.10.5 
```
I had safari 8 but upgraded to  safari 9.1.1 (10601.6.17) to cross check if thats the trouble with you, but it works on both of them, in my understanding you have not added the extension properly

*To try out again:*
download extension from http://selenium-release.storage.googleapis.com/index.html?path=2.48/
and double click to install, confirm if its enabled ->safari->preferences->extensions
![image](https://cloud.githubusercontent.com/assets/12966925/16614689/2fc20a16-4390-11e6-8b43-b198ed2533ab.png)

**Comment by BartVanRaemdonck** [comment]
I already did this and I also installed the safari certificate.

**Comment by shahp00ja** [comment]
[and click here to see this awesome step by step guide for the same issue](http://elementalselenium.com/tips/69-safari) by @tourdedave to cross check if your setup is fine

**Comment by p00j4** [comment]
[and click here to see this awesome step by step guide for the same issue](http://elementalselenium.com/tips/69-safari) by @tourdedave to cross check if your setup is fine

**Comment by p00j4** [comment]
Oo, then I find the issue thread here https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7133 did you check this?

**Comment by BartVanRaemdonck** [comment]
I think I found the problem:

I think I used the wrong dependencies in my POM file:

I used:

>  <dependency>
>       <groupId>org.seleniumhq.selenium</groupId>
>       <artifactId>selenium-api</artifactId>
>       <version>2.53.0</version>
>       <scope>test</scope>
>     </dependency>
>     <dependency>
>       <groupId>org.seleniumhq.selenium</groupId>
>       <artifactId>selenium-firefox-driver</artifactId>
>       <version>2.53.0</version>
>     </dependency>
>     <dependency>
>       <groupId>org.seleniumhq.selenium</groupId>
>       <artifactId>selenium-support</artifactId>
>       <version>2.48.2</version>
>       <scope>test</scope>
>     </dependency>
>     <dependency>
>       <groupId>org.seleniumhq.selenium</groupId>
>       <artifactId>selenium-chrome-driver</artifactId>
>       <version>2.48.2</version>
>       <scope>test</scope>
>     </dependency>
>     <dependency>
>       <groupId>org.seleniumhq.selenium</groupId>
>       <artifactId>selenium-safari-driver</artifactId>
>       <version>2.48.0</version>
>       <scope>test</scope>
>     </dependency>
> 

Now I'm just using:

>    <dependency>
>       <groupId>org.seleniumhq.selenium</groupId>
>       <artifactId>selenium-java</artifactId>
>       <version>2.48.2</version>
>       <scope>test</scope>
>     </dependency>

**Comment by p00j4** [comment]
I see, you can actually change it to 2.53.0 also and should work
looks like a classic case of compatibility mismatch (as your safari driver dependency was behind)

*Status* Not an issue, can close it.

**Comment by BartVanRaemdonck** [comment]
Ok, thank you all for your comments!
