### ISSUE TITLE
IDE > Error forwarding the new session cannot find : Capabilities [{browserName=*webdriver}]

### ISSUE THREAD

**Issue by nextofsearch** [SeleniumHQ/selenium#2431]
## Meta -

OS:  
hub: Mac OS X 10.11.5, node: Windows 10

Selenium Version: 2.53.1
IDE: 2.9.1

Browser Version:  
Firefox 47 (and 42), Internet Explorer 11, Chrome
## Expected Behavior -

Selenium IDE works just fine with Firefox or with Chrome + Webdriver playback in a standalone Selenium server. Also it works fine with a grid set-up which is comprised of a hub (Mac OS X) and a node (Windows 10) of Selenium servers when I run test cases using a ruby code and webdriver. It doesn't matter if I use chrome or internet explorer for webDriver.
## Actual Behavior -

But when I use a grid set-up with Selenium IDE webdriver playback feature, it fails with the error (a log of hub) below.

```
18:55:46.989 INFO - Got a request to create a new session: Capabilities [{browserName=internet explorer}]
18:55:46.990 INFO - Available nodes: [http://10.0.1.6:7777]
18:55:46.990 INFO - Trying to create a new session on node http://10.0.1.6:7777
18:55:46.990 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, browserName=internet explorer, maxInstances=5, version=11, platform=WINDOWS}
18:55:50.745 INFO - Got a request to create a new session: Capabilities [{browserName=*webdriver}]
2016-07-06 18:55:50.745:WARN:osjs.ServletHandler:qtp1484594489-34: /selenium-server/driver/
java.io.IOException: org.openqa.grid.common.exception.GridException: Error forwarding the new session cannot find : Capabilities [{browserName=*webdriver}]
    at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:126)
    at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
    at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by:
org.openqa.grid.common.exception.GridException: Error forwarding the new session cannot find : Capabilities [{browserName=*webdriver}]
    at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:115)
    at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
    at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
    at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by:
org.openqa.grid.common.exception.CapabilityNotPresentOnTheGridException: cannot find : Capabilities [{browserName=*webdriver}]
    at org.openqa.grid.internal.ProxySet.verifyAbilityToHandleDesiredCapabilities(ProxySet.java:182)
    at org.openqa.grid.internal.Registry.addNewSessionRequest(Registry.java:247)
    at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:109)
    at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
    at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
    at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
```
## Steps to reproduce -
1. run a hub
   `java -jar selenium-server-standalone-2.53.1.jar -role hub -timeout 30 -browserTimeout 60
   `
2. run a node
   `Java -jar selenium-server-standalone-2.53.1.jar -role node -port 7777 -hub http://10.0.1.2:4444/grid/register/ -maxSession 10 -browser "browserName=chrome,version=51, platform=WINDOWS, maxInstances=5, seleniumProtocol=WebDriver" -browser "browserName=internet explorer, version=11, platform=WINDOWS, maxInstances=5, seleniumProtocol=WebDriver"`
3. open Firefox and Selenium IDE and run any test case

Please help.

**Comment by nextofsearch** [comment]
I tried 2.50.1 and 2.48.2,which failed just like 2.53.1. Versions from 2.47.1 to 2.40.0 do not work with a log below:

```
19:40:22.840 INFO - Trying to create a new session on node http://10.0.1.6:7777
19:40:22.840 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, browserName=chrome, maxInstances=5, version=51, platform=WINDOWS}
19:40:26.917 INFO - Got a request to create a new session: Capabilities [{browserName=*webdriver}]
19:40:26.938 INFO - Got a request to create a new session: Capabilities [{browserName=chrome}]
```

**Comment by nextofsearch** [comment]
2.39.0 does not work on my set up.

**Comment by nitinsr013** [comment]
Hi All

I am getting below error when I run from Jenkins Server
Silenium version:2.53.1
FirFox:47.1

Test Files
    D:\Risk\DCI_EndToEndTests\DCI_EndToEnd_Tests\bin\Debug\DCI_EndToEnd_Tests.dll

1467802162971	addons.manager	DEBUG	Application has been upgraded
1467802163033	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1467802163037	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1467802163043	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1467802163046	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1467802163048	addons.manager	DEBUG	Starting provider: XPIProvider
1467802163048	addons.xpi	DEBUG	startup
1467802163050	addons.xpi	INFO	Mapping fxdriver@googlecode.com to C:\Users\jenkinsuser\AppData\Local\Temp\anonymous.44273d20cf514655988f92acc3df03ee.webdriver-profile\extensions\fxdriver@googlecode.com
1467802163051	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1467802163052	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1467802163053	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1467802163054	addons.xpi	INFO	Mapping loop@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1467802163056	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1467802163056	addons.xpi	DEBUG	Skipping unavailable install location app-system-share
1467802163057	addons.xpi	DEBUG	Skipping unavailable install location app-system-local
1467802163058	addons.xpi	DEBUG	checkForChanges
1467802163059	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1467802163059	addons.xpi	DEBUG	New add-on fxdriver@googlecode.com in app-profile
1467802163060	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1467802163096	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1467802163097	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1467802163098	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1467802163099	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1467802163099	addons.xpi	DEBUG	New add-on loop@mozilla.org in app-system-defaults
1467802163099	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1467802163101	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1467802163101	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1467802163101	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\jenkinsuser\\AppData\\Local\\Temp\\anonymous.44273d20cf514655988f92acc3df03ee.webdriver-profile\\extensions\\fxdriver@googlecode.com","st":1467802162077,"mt":1467195758000}},"app-system-defaults":{"e10srollout@mozilla.org":{"d":"C:\\Program Files\\Mozilla

**Comment by nextofsearch** [comment]
@nitinsr013 Hi, is your issue relevant to this issue? If not, please create a new issue.

**Comment by lukeis** [comment]
@nextofsearch somewhere in your code is requesting a browser named "*webdriver" this makes no sense to the grid, it expects things like "internet explorer", "google chrome", "firefox". Please take a look at the code (since you haven't provided it here, I can't tell you why). If you require further assistance please ask on the selenium-users google group.

**Comment by nextofsearch** [comment]
@lukeis Hi, I only use Selenium IDE, no other code. I know it's strange that 'webdriver' is requested but again I don't use any code but Selenium IDE.

**Comment by nextofsearch** [comment]
I suspect Selenium IDE has a bug with Selenium grid system.

**Comment by lukeis** [comment]
oh my... didn't realize IDE allowed you to remotely execute WebDriver directly from it. Yep, looks like a bug with IDE, it shouldn't be specifying "*webdriver" as the browserName.

**Comment by nextofsearch** [comment]
@lukeis Is there any chance that someone might take a look at this issue and fix it in the near future? I am wondering if Selenium IDE is an active project or not and if I should move on to other alternatives. I will appreciate your answer.

**Comment by lukeis** [comment]
Selenium IDE is only maintained by one person currently and only intermittently. It could use more developers contributing to the project. 

If you look at the age of other issues labeled with IDE, you'll see that the likelihood of this issue being resolved soon is not very likely.

**Comment by OlegAgeyev** [comment]
Have the same problem using IDE:

org.openqa.grid.common.exception.CapabilityNotPresentOnTheGridException: cannot find : Capabilities [{browserName=*webdriver}]

Is there any solution or workaround for this problem?

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
