### ISSUE TITLE
Selenium remote server can not run test failed with Unable to connect to host 127.0.0.1 on port 7055

### ISSUE THREAD

**Issue by HackToday** [SeleniumHQ/selenium#2491]
## Meta -
OS:  Linux CentOS 7

Selenium Version:  2.53.1

Browser:  Firefox

Browser Version:  47.0

## Expected Behavior -
Selienum could run ok for test
## Actual Behavior -

 Exception: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Error: GDK_BACKEND does not match available displays

## Steps to reproduce -

1.Setup a Selenium server  and run it like below:
java -jar selenium-server-standalone-2.53.1.jar 

2. Start firefox in above selenium server like below:
Xvfb :10 -ac
export DISPLAY=:10
firefox

3.  I have a second server which is for writing test scripts, like bleow example

```
#!/usr/bin/env python

from selenium import webdriver

driver = webdriver.Remote(
            desired_capabilities=webdriver.DesiredCapabilities.FIREFOX,
            command_executor='http://<selienum-server-ip>:4444/wd/hub'
            )
driver.get('http://saucelabs.com/test/guinea-pig')
id = self.driver.session_id
print 'Link to your job: https://saucelabs.com/jobs/%s' % id
driver.quit()

```

4. Run above python script and got error below:

```
Traceback (most recent call last):
  File "remotekick.py", line 7, in <module>
    command_executor='http://10.15.240.120:4444/wd/hub'
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Error: GDK_BACKEND does not match available displays

Stacktrace:
    at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start (NewProfileExtensionConnection.java:112)
    at org.openqa.selenium.firefox.FirefoxDriver.startClient (FirefoxDriver.java:271)
    at org.openqa.selenium.remote.RemoteWebDriver.<init> (RemoteWebDriver.java:119)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:218)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:211)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:129)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:526)
    at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor (FirefoxDriverProvider.java:91)
    at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance (FirefoxDriverProvider.java:68)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance (DefaultDriverFactory.java:60)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:222)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:1)
    at java.util.concurrent.FutureTask.run (FutureTask.java:262)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:615)
    at java.lang.Thread.run (Thread.java:745)

```

**Comment by lukeis** [comment]
You need to be sure to use 47.0.1 (47.0 will not work with selenium)

**Comment by HackToday** [comment]
@lukeis  Still got the same issue with firefox 47.0.1, I did not think it was firefox version issue, as output error is

```
selenium.common.exceptions.WebDriverException: Message: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Error: GDK_BACKEND does not match available displays

Stacktrace:
    at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start (NewProfileExtensionConnection.java:112)
    at org.openqa.selenium.firefox.FirefoxDriver.startClient (FirefoxDriver.java:271)
    at org.openqa.selenium.remote.RemoteWebDriver.<init> (RemoteWebDriver.java:119)

```

**Comment by HackToday** [comment]
I have found the reason, it was because I did not export display in selenium server shell(I opened a new shell, directly run `java -jar selenium-server-standalone-2.53.1.jar`), that selenium server could not launch firefox in that shell, I think.

**Comment by SirNexus** [comment]
Just found this solution. It was very helpful, thank you!
