### ISSUE TITLE
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

### ISSUE THREAD

**Issue by skhanam** [SeleniumHQ/selenium#2520]
## Meta -
OS:  
Mac OS x
Selenium Version:  
WebDRiver 2.53
Browser:  
 Firefox - 47

Log trace:
-------------

org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows: 
internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1431984092000,"updateDate":1469452774000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0.1","maxVersion":"47.0.1"}],"targetPlatforms":[],"seen":true}
1469473440774	DeferredSave.extensions.json	DEBUG	Save changes
1469473440774	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1469473440774	addons.xpi-utils	DEBUG	Updating add-on states
1469473440775	addons.xpi-utils	DEBUG	Writing add-ons list
1469473440783	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1469473440783	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1469473440800	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1469473440818	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1469473440819	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1469473440821	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1469473440821	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1469473440822	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1469473440825	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1469473440827	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1469473440827	addons.manager	DEBUG	Provider finished startup: XPIProvider
1469473440827	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1469473440827	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1469473440828	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1469473440828	addons.manager	DEBUG	Starting provider: GMPProvider
1469473440835	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1469473440835	addons.manager	DEBUG	Provider finished startup: GMPProvider
1469473440835	addons.manager	DEBUG	Starting provider: PluginProvider
1469473440836	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1469473440836	addons.manager	DEBUG	Provider finished startup: PluginProvider
1469473440837	addons.manager	DEBUG	Completed startup sequence
1469473441052	DeferredSave.extensions.json	DEBUG	Starting timer
1469473441064	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1469473441064	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1469473441065	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1469473441112	DeferredSave.extensions.json	DEBUG	Starting write
1469473441235	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1469473441235	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1469473441235	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1469473441249	DeferredSave.extensions.json	DEBUG	Write succeeded
1469473441249	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17

Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Shabanas-MBP.lan', ip: '192.168.1.213', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_91'
Driver info: driver.version: AbstractDriver
at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
at com.test.ee.config.AbstractDriver.setUp(AbstractDriver.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1431984092000,"updateDate":1469452774000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0.1","maxVersion":"47.0.1"}],"targetPlatforms":[],"seen":true}
1469473440774	DeferredSave.extensions.json	DEBUG	Save changes
1469473440774	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1469473440774	addons.xpi-utils	DEBUG	Updating add-on states
1469473440775	addons.xpi-utils	DEBUG	Writing add-ons list
1469473440783	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1469473440783	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1469473440800	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1469473440818	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1469473440819	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1469473440821	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1469473440821	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1469473440822	addons.xpi	DEBUG	Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1469473440825	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1469473440827	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1469473440827	addons.manager	DEBUG	Provider finished startup: XPIProvider
1469473440827	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1469473440827	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1469473440828	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1469473440828	addons.manager	DEBUG	Starting provider: GMPProvider
1469473440835	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1469473440835	addons.manager	DEBUG	Provider finished startup: GMPProvider
1469473440835	addons.manager	DEBUG	Starting provider: PluginProvider
1469473440836	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1469473440836	addons.manager	DEBUG	Provider finished startup: PluginProvider
1469473440837	addons.manager	DEBUG	Completed startup sequence
1469473441052	DeferredSave.extensions.json	DEBUG	Starting timer
1469473441064	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1469473441064	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1469473441065	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1469473441112	DeferredSave.extensions.json	DEBUG	Starting write
1469473441235	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1469473441235	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1469473441235	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1469473441249	DeferredSave.extensions.json	DEBUG	Write succeeded
1469473441249	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17

at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
... 31 more

java.lang.NullPointerException
at com.test.ee.config.AbstractDriver.tearDown(AbstractDriver.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

If the issue is with Microsoft Edge consider logging an issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If the issue is with Firefox GeckoDriver (aka Marionette) consider loogging an issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver

-->

Browser Version:

**Comment by lukeis** [comment]
you need to use selenium 2.53.1, your stacktrace shows you are using 2.53.0
