### ISSUE TITLE
ChromeDriver and OperaDriver fail when running tests on Visual Studio Team Services (VS Online)

### ISSUE THREAD

**Issue by CosminGramada** [SeleniumHQ/selenium#2605]
Firstly, I have no idea where the problem actually is, in Selenium code, ChromeDriver code or maybe something caused by the VS side, so I apologize in advance if this is not the proper place to place this.

OS:  Windows 10
Selenium Version: 2.53.1
Browser:  Chrome and Opera

We're using MSTest with Team Services (Visual Studio Online) builds to run our Selenium Tests. FirefoxDriver and InternetExplorerDriver are running correctly, however ChromeDriver and OperaDriver are failing everytime, without even being able to open the browser. They fail everytime with the following stacktrace:

Initialization method WebUnitTests.Tests.DatacenterTests.TestInitialize threw exception. OpenQA.Selenium.WebDriverException:
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:1410/session timed out after 60 seconds. ---> 
System.Net.WebException: The operation has timed out.

at System.Net.HttpWebRequest.GetResponse()
at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
--- End of inner exception stack trace ---
at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
at WebUnitTests.Framework.Utilities.Driver.StartBrowser(BrowserTypes browserType, Int32 defaultTimeOut) in C:\agent2\_work\1\s\WebUnitTests\Framework\Utilities\Driver.cs:line 37
at WebUnitTests.Framework.Utilities.BaseTests.InitializeBrowser(TestContext testContext) in C:\agent2\_work\1\s\WebUnitTests\Framework\Utilities\BaseTests.cs:line 328
at WebUnitTests.Framework.Utilities.BaseTests.TestInitialize() in C:\agent2\_work\1\s\WebUnitTests\Framework\Utilities\BaseTests.cs:line 147
What I'm using to start the driver:

var chromeOptions = new ChromeOptions();
chromeOptions.AddArgument("--ignore-certificate-errors");
var chromeBrowser = new ChromeDriver(chromeOptions);
One very important thing to mention is that if I'm running the tests on my local machine everything works fine, the issue is only when they're run in CI.

Any ideas in what I could try to find the root problem? Any workarounds to solve this?

**Comment by lukeis** [comment]
CI? Windows? Please make sure the environment is not run in a 'Headless' mode of windows or as a service. Nearly all of the drivers / browsers require a full Windows Session logged in, in order to run.

Also for further questions please post them to the mailing list:
https://groups.google.com/forum/#!forum/selenium-users
