### ISSUE TITLE
Cannot run test.py on OSX with wires 10.0 selenium 3.0.0b2 FF 45

### ISSUE THREAD

**Issue by damorton** [SeleniumHQ/selenium#2631]
Issue on Mac OSX EL Capitan

gekodriver / wires = 10.0
selenium = 3.0.0b2
FF = 45

```
(env) macbook:test dmorton$ python test.py 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    browser = webdriver.Firefox()
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 73, in __init__
    keep_alive=True)
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: entity not found

(env) macbook:test dmorton$ pip list
pip (8.1.2)
selenium (3.0.0b2)
setuptools (25.2.0)
wheel (0.29.0)
(env) macbook:test dmorton$ 
```

```
from selenium import webdriver

browser = webdriver.Firefox()
browser.get('http://seleniumhq.org/')

```

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by AutomatedTester** [comment]
Firefox 45 is not supported with GeckoDriver unfortunately.
