### ISSUE TITLE
WebdriverJS hangs until timeout in case of error in `before` hook

### ISSUE THREAD

**Issue by vitalets** [SeleniumHQ/selenium#2636]
## Meta -
OS:  OSX
Selenium Version:  npm selenium-webdriver 3.0.0-beta-2
Browser:  does not matter

If error is thrown in `before` hook webdriverjs hangs until timeout elapsed. 

## Expected Behavior -
Suite should shutdown with 1 error message about thrown error in before hook.

## Actual Behavior -
Suite shutdown only after timeout elapsed with 2 errors:
- error about before hook that was thrown
- error about timeout in after hook

It looks like `driver.quit()` hangs because `driver.session_` is rejected promise.

## Steps to reproduce -
Run following test with mocha and webdriverjs
```js
var webdriver = require('selenium-webdriver'),
  test = require('selenium-webdriver/testing');

test.describe('suite', function() {
  let driver;

  test.before(function() {
    console.log('before');
    driver = new webdriver.Builder()
      .forBrowser('chrome')
      .build();

    throw new Error('Error on first tick in before hook');
  });

  test.after(function() {
    console.log('after');
    driver.quit();
  });

  test.it('test1', function() {
    console.log('ok1');
  });
});
```
Result:
```
  suite
before
    1) "before all" hook
after
    2) "after all" hook

  // delay of 2000 ms (!!!)

  0 passing (2s)
  2 failing

  1) suite "before all" hook:
     Error: Error on first tick in before hook
      at ...

  2) suite "after all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

The quick fix I tried is to re-throw error up to controlFlow here:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/testing/index.js#L156

```js
...
    }, runnable.fullTitle()).then(seal(done), e => {
      done(e);
     // re-throw error to stop controlflow
      throw e;
    });
```
But it is not a solution as it breaks all tests in case of single error.

**Comment by jleyba** [comment]
Reduced test case:

```js

'use strict';

const assert = require('assert');

const webdriver = require('selenium-webdriver');
const test = require('selenium-webdriver/testing');
const flow = webdriver.promise.controlFlow();

test.describe.only('suite', function() {
  let seen = [];

  function record(n) {
    seen.push(n);
    console.log(`saw ${n}`);
  }

  test.before(function() {
    console.log('before');
    flow.execute(() => record(1));
    Promise.resolve().then(() => {
      return flow.execute(() => record(2));
    });
    throw Error('before failed');
  });

  test.after(function() {
    console.log('after');
    assert.deepEqual(seen, []);
  });

  test.it('test', () => record(3));
});
```

```
$ mocha test


  suite
before
saw 2
    1) "before all" hook
after
    2) "after all" hook


  0 passing (21ms)
  2 failing

  1) suite "before all" hook:
     Error: before failed
      at Error (native)
      at Context.<anonymous> (test.js:45:11)
      at node_modules/selenium-webdriver/testing/index.js:161:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1029:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:138:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2738:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2720:21)
      at node_modules/selenium-webdriver/lib/promise.js:2642:25
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: suite "before all" hook
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:137:10)

  2) suite "after all" hook:

      AssertionError: [ 2 ] deepEqual []
      + expected - actual

      -[
      -  2
      -]
      +[]
      
      at Context.<anonymous> (test.js:50:12)
      at node_modules/selenium-webdriver/testing/index.js:161:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1029:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:138:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2738:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2720:21)
      at node_modules/selenium-webdriver/lib/promise.js:2642:25
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: suite "after all" hook
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:137:10)
```

**Comment by vitalets** [comment]
thanks 👍
