### ISSUE TITLE
WebDriver Exception is being thrown in place of NoSuchElementException or TimeoutException for FindElement

### ISSUE THREAD

**Issue by shashwat51** [SeleniumHQ/selenium#2650]
## Meta -
OS:  Linux 3.13.0-74-generic x86_64

Selenium Version:  2.47.1

Browser:  Google Chrome

Browser Version:   51.0.2704.106

## Expected Behavior -
driver.findElementbyID should through either NoSuchElementException or TimeoutException

## Actual Behavior -
driver.findElementbyID is throwing WebDriverException

## Steps to reproduce -
I am trying to scrape a website and seeing this issue on the website.
The stacktrace is below
The Html pages contain some user information which I am seeking a permission to share with you .But would like you to kindly suggest by having a look at the below stacktrace.
The browser is working perfectly for multiple websites and for one particular website I am receiving this error.

I have tried with the latest chromedriver as well as previous versions as well.

Aug 23, 2016 6:03:15 AM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.id: ABC)
org.openqa.selenium.WebDriverException: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}
  (Session info: chrome=51.0.2704.106)
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 3.13.0-74-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 624 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'ip-172-31-36-46', ip: '172.31.36.46', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-74-generic', java.version: '1.7.0_101'
*** Element info: {Using=id, value=ABC}
Session ID: 261ad282e17a0d2d511b4f6e6fd0149c
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.org.chromium.Chromium.7Tpf1F, chromedriverVersion=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1)}, networkConnectionEnabled=false, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=51.0.2704.106, takesHeapSnapshot=true, databaseEnabled=false, cssSelectorsEnabled=true, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:348)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:389)
	at org.openqa.selenium.By$ById.findElement(By.java:215)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:340)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:861)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)

**Comment by lukeis** [comment]
Please provide a way for us to reproduce the issue, with link to page or recreation of the page using jsfiddle.net along with a script that demonstrates the problem. 

Please don't expect others to work at trying to reproduce your issue. When this is provided we can reopen this bug report

**Comment by ildar-aim** [comment]
I have the same issue

sleep(10); before driver.findElementbyID helps me

Another solution for php-webdriver

```
diff --git a/tests/selenium_tests/php-webdriver/PHPWebDriver/WebDriverWait.php b/tests/selenium_tests/php-webdriver/PHPWebDriver/WebDriverWait.php
index 7350aab..8e98c2e 100644
--- a/tests/selenium_tests/php-webdriver/PHPWebDriver/WebDriverWait.php
+++ b/tests/selenium_tests/php-webdriver/PHPWebDriver/WebDriverWait.php
@@ -33,7 +33,12 @@ class PHPWebDriver_WebDriverWait {
                   return $value;
                 }
             } catch (PHPWebDriver_NoSuchElementWebDriverError $e) {
-
+            } catch (PHPWebDriver_UnhandledWebDriverError $e) {
+				// Ignore this error on paypal side, may be bug in chromedriver ?
+				$msg = $e->getMessage();
+				if (strpos($msg, 'unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}') === false) {
+					throw $e;
+				}
             }
             usleep(intval($this->poll * 1000000));
         }
```

```
09:03:02.611 INFO - Executing: [find element: By.xpath: id("transactionCart")/span[2]/descendant::*/span])
09:03:10.925 ERROR - Unexpected exception during findElement
org.openqa.selenium.WebDriverException: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}
  (Session info: chrome=53.0.2785.101)
  (Driver info: chromedriver=2.22,platform=Linux 4.7.2-1-ARCH x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.87 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'cormorant.crtdev.local', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.7.2-1-ARCH', java.version: '1.7.0_111'
*** Element info: {Using=xpath, value=id("transactionCart")/span[2]/descendant::*/span}
Session ID: 355c2e4b94b43e38cf9034ba430405d9
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.org.chromium.Chromium.tmCLE7, chromedriverVersion=2.22}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=53.0.2785.101, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
        at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
        at com.sun.proxy.$Proxy1.findElement(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:188)
        at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
        at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
09:03:10.936 WARN - Exception thrown
org.openqa.selenium.WebDriverException: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}
  (Session info: chrome=53.0.2785.101)
  (Driver info: chromedriver=2.22,platform=Linux 4.7.2-1-ARCH x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.87 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'cormorant.crtdev.local', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.7.2-1-ARCH', java.version: '1.7.0_111'
*** Element info: {Using=xpath, value=id("transactionCart")/span[2]/descendant::*/span}
Session ID: 355c2e4b94b43e38cf9034ba430405d9
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.org.chromium.Chromium.tmCLE7, chromedriverVersion=2.22}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=53.0.2785.101, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
        at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
        at com.sun.proxy.$Proxy1.findElement(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:188)
        at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
        at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
09:03:10.936 WARN - Exception: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}
  (Session info: chrome=53.0.2785.101)
  (Driver info: chromedriver=2.22,platform=Linux 4.7.2-1-ARCH x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.87 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'cormorant.crtdev.local', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.7.2-1-ARCH', java.version: '1.7.0_111'
*** Element info: {Using=xpath, value=id("transactionCart")/span[2]/descendant::*/span}
Session ID: 355c2e4b94b43e38cf9034ba430405d9
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.org.chromium.Chromium.tmCLE7, chromedriverVersion=2.22}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=53.0.2785.101, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
09:03:10.968 INFO - Executing: [take screenshot])
09:03:12.349 INFO - Done: [take screenshot]
09:03:12.395 INFO - Executing: [get page source])
09:03:12.579 INFO - Done: [get page source]

```

**Comment by pshorally** [comment]
Issue Description:
After upgrading Selenium webdriver 3.4.0 version and chrome browser 59

Following issue noticed :
java.lang.AssertionError: unknown error: unhandled inspector error: {"code":-32000,"message":"Unable to capture screenshot"}

Steps to reproduce:
randomly occuring below issue

java.lang.AssertionError: unknown error: unhandled inspector error: {"code":-32000,"message":"Unable to capture screenshot"}
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 495 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'QA553', ip: '10.59.51.31', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41), userDataDir=C:\Users\PARAME~1\AppData\Local\Temp\scoped_dir2332_13297}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=WIN8_1, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: c33556aacbb08a995906407cba54f2a1
	at com.lucernex.qa.utils.Assert.fail(Assert.java:96)
	at com.lucernex.qa.views.BaseView.takeScreenshot(BaseView.java:188)
	at com.lucernex.qa.views.admin.lxadmin.SetupFirmWizardView.clickButton(SetupFirmWizardView.java:82)
	at com.lucernex.qa.SetupFirmWizardSteps.I_click_the_button_in_the_setup_firm_wizard(SetupFirmWizardSteps.java:144)
	at ?.And I click the "Reset" button in the setup firm wizard(target/test-classes/CreateEnterpriseCompany.feature:119)

Could you please suggest

**Comment by EchoSmile** [comment]
I have the same issue:
Chrome :63.0.3239.132
WebDriver :2.34.522940 
Python:3.6
``Traceback (most recent call last):
  File "C:/practise/Python/Python/week2/simulate_writepm.py", line 113, in <module>
    pm.simulate_login()
  File "C:/practise/Python/Python/week2/simulate_writepm.py", line 73, in simulate_login
    driver.find_element_by_id('myForm')
  File "C:\Program Files\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Program Files\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Program Files\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)``

**Comment by t-node** [comment]
I am facing the same issue, it keep happening intermittantly. chrome version 62 and chrome driver version 2.34
