### ISSUE TITLE
python ：expected an indented block

### ISSUE THREAD

**Issue by EkkoTi** [SeleniumHQ/selenium#2659]
python 3
----------
window 7
------------
>>> from selenium import  #webdriver
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    from selenium import webdriver
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium-3.0.0b2-py3.5.egg\selenium\webdriver\__init__.py", line 25, in <module>
    from .safari.webdriver import WebDriver as Safari  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium-3.0.0b2-py3.5.egg\selenium\webdriver\safari\webdriver.py", line 48
    executable_path = os.environ.get("SELENIUM_SERVER_JAR")
                  ^
IndentationError: expected an indented block

**Comment by lukeis** [comment]
already fixed, will be in the next release
