### ISSUE TITLE
Using Selenium with PhantonJS

### ISSUE THREAD

**Issue by YuanZheCSYZ** [SeleniumHQ/selenium#2663]
## Meta -
OS:  Ubuntu 16.04
Selenium Version: Python-Selenium 2.47.1  
Browser:  PhantonJS

Browser Version:  2.1.1 64bit

I'm trying to run my Python Selenium testing with PhantomJS but I came across several issues.
The first test is very basic, but this is how I used to use I think
```python
from selenium import webdriver
driver = webdriver.PhantomJS()
```
## Actual Behavior -
And I receive below stacktrace
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    driver = webdriver.PhantomJS()
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 87, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 136, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 196, in execute
    self.error_handler.check_response(response)
  File "/home/someone/bin/pyvenv-3.5/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 102, in check_response
    value = json.loads(value_json)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any help is appreciate!

**Comment by lukeis** [comment]
I don't have this issue on OSX.  Likely if you run `phantomjs` directly it may have an exception that is causing it to fail on startup.

**Comment by cgoldberg** [comment]
@YuanZheCSYZ check which version of PhantomJS you are using with `phantomjs --version`.   If you are on 2.x, you will need to remove it and install PhantomJS 1.9.8

**Comment by YuanZheCSYZ** [comment]
@cgoldberg Thanks for the follow up. I was running 2.1.1 the Ubuntu package version and I think that's the problem as the download version works fine.
