### ISSUE TITLE
Can't execute JavaScript on an element with python

### ISSUE THREAD

**Issue by Goosky** [SeleniumHQ/selenium#2666]
## Meta -
OS:  windows 10

Selenium Version:  2.53.6

Browser:  All,Python language, Anaconda

Browser Version:  All

## Expected Behavior -
execute JavaScript on an element
## Actual Behavior -
```python
2016-08-25 16:34:41 ERROR <selenium.webdriver.remote.webelement.WebElement (session="a9e189011f674ce0daed53b9a7ec1b29", element="0.7036613755364336-1")> is not JSON serializable
Traceback (most recent call last):
  File "framework\Element.py", line 484, in execute_script
    self.driver.execute_script(script, args)
  File "C:\Users\xxx\Anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "C:\Users\xxx\Anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\xxx\Anaconda2\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 398, in execute
    data = utils.dump_json(params)
  File "C:\Users\xxx\Anaconda2\lib\site-packages\selenium\webdriver\remote\utils.py", line 34, in dump_json
    return json.dumps(json_struct)
  File "C:\Users\xxx\Anaconda2\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\xxx\Anaconda2\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\xxx\Anaconda2\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\xxx\Anaconda2\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <selenium.webdriver.remote.webelement.WebElement (session="a9e189011f674ce0daed53b9a7ec1b29", element="0.7036613755364336-1")> is not JSON serializable
```
## Steps to reproduce -

```python
element = driver.find_element_by_id('p')
driver.execute_script('arguments[0].setAttribute("style", "color: red; border: 5px solid red;");',element)
```

**Comment by lukeis** [comment]
something else must be going on here... i can't reproduce your issue:

    >>> d = w.Chrome()
    >>> d.get('http://google.com')
    >>> element = d.find_element_by_name('q')
    >>> d.execute_script('arguments[0].setAttribute("style", "color: red; border: 5px solid red;");',element)
    >>> element.get_attribute("style")
    u'color: red; border: 5px solid red;'
    >>>

**Comment by jmbowman** [comment]
In case somebody else encounters this, the problem might have been that the reporter was using a custom subclass of WebElement with Firefox.  I recently encountered a similar issue with needle and submitted a [patch](https://github.com/bfirsh/needle/pull/70) for it; basically, selenium checks when serializing arguments to `execute_script()` that an object is a subclass of the appropriate web element for that driver when deciding in `_wrap_value()` whether to treat it as an element with a custom serialized representation or a generic object to be dumped to JSON.  For this to work as intended, you have to use subclasses of FirefoxWebElement with the Firefox driver; a subclass of WebElement that doesn't inherit from that class won't work correctly.  That seems like a bug to me (it should probably just check for inheritance from WebElement instead), but it's not a problem with most standard selenium usage.
