### ISSUE TITLE
close() & quit() commands dont work in Firefox Browser Version 48.0

### ISSUE THREAD

**Issue by Easyman123** [SeleniumHQ/selenium#2667]
## Meta -
OS:  Windows 7 Enterprise 64 Bit

Selenium Version:  selenium-server-standalone-3.0.0-beta2.jar Package

Browser:  Firefox Browser Version 48.0

Geckodriver Version: geckodriver-v0.10.0-win64

## Expected Behavior -
in Firefox Browser:
The driver.close() command should close the current browser window on which the focus is set.
The driver.quit() command should close all opened browser windows and end the whole WebDriver session.

## Actual Behavior -
When I run my test in Selenium WebDriver using Java everything works fine so far. But with execution of driver.quit() command in the @After hook I get the following error:

`[Child 12868] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2046`

One second later the firefox browser closes as wished but directly followed by UnreachableBrowserException with below stacktrace and the test results in a fail:

`Failure in after hook:StepDefinitionsBrowserCombinationTestWithHooks.tearDownFirefox()
Message: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'PC45770', ip: '141.77.197.75', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: RemoteWebDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160817112116, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: fef2d090-008f-4d43-ba5b-6ec66cae2aab
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:706)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:531)
	at cucumber.features.StepDefinitionsBrowserCombinationTestWithHooks.tearDownFirefox(StepDefinitionsBrowserCombinationTestWithHooks.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:205)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:121)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
Caused by: java.lang.IllegalStateException: UnixUtils may not be used on Windows
	at org.openqa.selenium.os.ProcessUtils.getProcessId(ProcessUtils.java:188)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.getPID(UnixProcess.java:222)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$300(UnixProcess.java:201)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:132)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:155)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:94)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:649)
	... 19 more`

When I use the close() command instead nothing happens as if Selenium would ignore this code line.
That means that currently I have to manually close all browser windows after every test execution to not to receive UnreachableBrowserException which ends up in a failed test.
With IE and Google Chrome Browser I dont experience the issue described as above.

## Steps to reproduce -
Just try to run a simple test (like open the browser, wait a few seconds and close the browser again) against Firefox Browser Version 48.0 using Selenium beta2 Version and geckodriver. Try out both - close() and quit() - methods.

Is there anyone else facing the same problem? Any help is appreciated!
Thanks in advance

**Comment by Easyman123** [comment]
Now I have downloaded and embedded the second newest geckodriver v0.9.0 (64 bit) which was released on 30 Jun but this one causes Socket- and Connection-Errors (the browser is not even opening) and is therefore not an appropriate solution.
Which geckodriver supports firefox version 48.0.2 because thats the version I want to run my automated tests against?

**Comment by Easyman123** [comment]
What I found out now is that if you use the second newest geckodriver (v0.9.0) in combination with the selenium server beta1 instead of the selenium server beta2 version everything works fine again.

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by patyveron** [comment]
Hi!! the version is working is geckodrive 0.9.0 with 3.0.0-beta1 Selenium, and we must also add the Path variable windows taskkill.exe path (C: \ Windows \ System32). Browser close sucessfully...

**Comment by jagradang** [comment]
is there currently any resolution to this issue?  i'm hitting the same with firefox v49 and selenium 3.0.0.b3

**Comment by Anojan** [comment]
Is there any improvements in this? Currently I use gecko driver firefox v1.50.1 with selenium 3.0.1. And I get the same error.

**Comment by punkRahul** [comment]
**OS**: Windows 7 Enterprise 64 Bit
**Selenium Version**: selenium-server-standalone-3.0.1
**Browser:** Firefox Browser Version 50.1.0
**Geckodriver Version**: geckodriver-v0.10.0-win64

I got same error for above configuration, tests run completely fine and later on driver.close() it throws following error.

`[Child 7016] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
Jan 23, 2017 11:52:40 AM org.openqa.selenium.os.UnixProcess destroy`

**Comment by ppzzss** [comment]
I facing same problem on Win7 64bit / Selenium 3.3.0 / Firefox 52.0+geckodriver1.15  | Chrome 57+chromedriver2.28 while calling driver.quit();

But driver.close() works on above env.
