### ISSUE TITLE
WebDriverError: Unable to parse new session response, when doing the google_search tutorial test

### ISSUE THREAD

**Issue by xeppen** [SeleniumHQ/selenium#2678]
## Meta -
OS:  OSX 10.11.6

Selenium Version:  2.52.0

Browser:  Firefox 48.0.1, Chrome 52.0

Followed the [Quick Start Guide](https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs) exactly with both geckodriver and chromedriver in my path.

## Expected Behavior -
Firefox: That the test gets executed.
Chrome: That browser open and test gets executed.

## Actual Behavior -
Firefox: browser opens but the test isn't executed. Get error:

    $ node google_search
    /Users/selj/node_modules/selenium-webdriver/lib/promise.js:654
        throw error;
        ^

    WebDriverError: Unable to parse new session response: {"error":"unknown error","message":"connection refused"}
        at WebDriverError (/Users/selj/node_modules/selenium-webdriver/lib/error.js:26:26)
        at /Users/selj/node_modules/selenium-webdriver/lib/http.js:333:17
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: WebDriver.createSession()
        at Function.createSession (/Users/selj/node_modules/selenium-webdriver/lib/webdriver.js:366:24)
        at Driver (/Users/selj/node_modules/selenium-webdriver/firefox/index.js:537:38)
        at Builder.build (/Users/selj/node_modules/selenium-webdriver/index.js:549:16)
        at Object.<anonymous> (/Users/selj/Development/Projects/Test Automation/google_search.js:8:6)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:146:18)
    From: Task: WebDriver.navigate().to(http://www.google.com/ncr)
        at Driver.schedule (/Users/selj/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
        at Navigation.to (/Users/selj/node_modules/selenium-webdriver/lib/webdriver.js:1042:25)
        at Driver.get (/Users/selj/node_modules/selenium-webdriver/lib/webdriver.js:832:28)
        at Object.<anonymous> (/Users/selj/Development/Projects/Test Automation/google_search.js:10:8)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:146:18)

Chrome: No browser opens. Throws error:

    $ node google_search      
    /Users/selj/node_modules/selenium-webdriver/lib/promise.js:654
        throw error;
        ^

    SessionNotCreatedError: session not created exception
    from disconnected: unable to connect to renderer
      (Session info: chrome=52.0.2743.116)
      (Driver info: chromedriver=2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0),platform=Mac OS X 10.11.6 x86_64)
        at WebDriverError (/Users/selj/node_modules/selenium-webdriver/lib/error.js:26:26)
        at SessionNotCreatedError (/Users/selj/node_modules/selenium-webdriver/lib/error.js:213:26)
        at Object.checkLegacyResponse (/Users/selj/node_modules/selenium-webdriver/lib/error.js:505:15)
        at parseHttpResponse (/Users/selj/node_modules/selenium-webdriver/lib/http.js:396:13)
        at /Users/selj/node_modules/selenium-webdriver/lib/http.js:328:11
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: WebDriver.createSession()
        at Function.createSession (/Users/selj/node_modules/selenium-webdriver/lib/webdriver.js:366:24)
        at Driver (/Users/selj/node_modules/selenium-webdriver/chrome.js:804:38)
        at Builder.build (/Users/selj/node_modules/selenium-webdriver/index.js:546:16)
        at Object.<anonymous> (/Users/selj/Development/Projects/Test Automation/google_search.js:8:6)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:146:18)
    From: Task: WebDriver.navigate().to(http://www.google.com/ncr)
        at Driver.schedule (/Users/selj/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
        at Navigation.to (/Users/selj/node_modules/selenium-webdriver/lib/webdriver.js:1042:25)
        at Driver.get (/Users/selj/node_modules/selenium-webdriver/lib/webdriver.js:832:28)
        at Object.<anonymous> (/Users/selj/Development/Projects/Test Automation/google_search.js:10:8)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:146:18)

## Steps to reproduce -

I followed the [Quick Start Guide](https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs) exactly with both geckodriver and chromedriver in my path.

**Comment by jleyba** [comment]
You need to update to a newer version than 2.52.0.

The google search example works on Firefox and Chrome for 2.53.3 and 3.0.0-beta-2:

```
$ node --version
v4.4.4

$ npm install selenium-webdriver
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
selenium-webdriver@2.53.3 node_modules/selenium-webdriver
├── tmp@0.0.24
├── adm-zip@0.4.4
├── ws@1.1.1 (options@0.0.6, ultron@1.0.2)
├── xml2js@0.4.4 (xmlbuilder@8.2.2, sax@0.6.1)
└── rimraf@2.5.4 (glob@7.0.6)

$ node node_modules/selenium-webdriver/example/google_search
$ SELENIUM_BROWSER=chrome node node_modules/selenium-webdriver/example/google_search

$ npm install selenium-webdriver@3.0.0-beta-2
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
selenium-webdriver@3.0.0-beta-2 node_modules/selenium-webdriver
├── tmp@0.0.24
├── adm-zip@0.4.4
├── ws@1.1.1 (options@0.0.6, ultron@1.0.2)
├── xml2js@0.4.4 (xmlbuilder@8.2.2, sax@0.6.1)
└── rimraf@2.5.4 (glob@7.0.6)


$ node node_modules/selenium-webdriver/example/google_search
$ SELENIUM_BROWSER=chrome node node_modules/selenium-webdriver/example/google_search
```

**Comment by hectorggp** [comment]
Hi, @jleyba. I just read about this e2e testing framework and intented to run the examples but, regardless of I have actual versions of node and selenium-webdriver, it shows me the same issue. Please help to me.

**Comment by mo** [comment]
@hectorggp FWIW, I upgraded my old geckodriver (from v0.14) to the latest version (v0.17) and the error went away
