### ISSUE TITLE
Possible compatibility problem with mocha 3.0.2

### ISSUE THREAD

**Issue by doberkofler** [SeleniumHQ/selenium#2690]
## Meta -
OS:
Windows 7
Selenium Version:  
2.53.3
Browser:  
Firefox

Browser Version:  
48.0.2 (64-bit)

## Expected Behavior -
no error

## Actual Behavior -

The following error is reported:
----------
Message:
    Test `title` should be a "string" but "function" was given instead.
Stack:
Error: Test `title` should be a "string" but "function" was given instead.
    at new Test (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\mocha\lib\test.js:24:11)
    at context.it.context.specify (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\mocha\lib\interfaces\bdd.js:84:18)
    at Object.it (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\selenium-webdriver\testing\index.js:95:14)
    at Suite.<anonymous> (D:\MyDev\ljs_app\trunk\periscope\build\test\selenium\tests\1-pageobjects\BasePage-test.js:251:8)
    at Object.create (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\mocha\lib\interfaces\common.js:114:19)
    at Object.context.describe.context.context [as describe] (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Suite.<anonymous> (D:\MyDev\ljs_app\trunk\periscope\build\test\selenium\tests\1-pageobjects\BasePage-test.js:250:7)
    at Object.create (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\mocha\lib\interfaces\common.js:114:19)
    at Object.context.describe.context.context [as describe] (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Object.<anonymous> (D:\MyDev\ljs_app\trunk\periscope\build\test\selenium\tests\1-pageobjects\BasePage-test.js:50:6)
----------

## Steps to reproduce -
I'm using the selenium webdriver for JavaScript in conjunction with gulp.
The tests are written using mocha and executed using the gulp-mocha plugin.
Everything worked as expected until the gulp-mocha plugin needed to be upgraded from version 2.2.0 to 3.0.1 and therefore also pulling in a new version of the mocha package that went from 2.5.3 to 3.0.2.
After upgrading mocha in the following code example an error "Test `title` should be a "string" but "function" was given instead." is reported in line 2.

----------
const test = require('selenium-webdriver/testing');
test.describe('module', function () {});
----------

**Comment by jleyba** [comment]
I'm not able to reproduce this. You'll need to provide a complete reproducible test case.

```js
'use strict';

const assert = require('assert');
const test = require('selenium-webdriver/testing');

test.describe('thing', function() {
  test.it('works', function() {
  });

  test.it('fails', function() {
    assert.fail('boom!');
  });
});
```

```
$ ./node_modules/mocha/bin/mocha --version
3.0.2
$ ./node_modules/mocha/bin/mocha test.js 


  thing
    ✓ works
    1) fails


  1 passing (22ms)
  1 failing

  1) thing fails:
     AssertionError: 'boom!' undefined undefined
      at Context.<anonymous> (test.js:11:12)
      at node_modules/selenium-webdriver/testing/index.js:153:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1029:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:138:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2736:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2719:21)
      at node_modules/selenium-webdriver/lib/promise.js:2642:25
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: thing fails
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:137:10)
```

**Comment by doberkofler** [comment]
@jleyba Thank's a lot for your quick feedback and sorry for not having prepared a proper test case. I can confirm that your test case works and will have to dig a little deeper in my use case before I will be able to get back to you.

**Comment by doberkofler** [comment]
This test case should now reproduce the problem:
```
'use strict';

const assert = require('assert');
const test = require('selenium-webdriver/testing');

test.describe('thing', function () {
	test.it('pending');

	test.it('works', function () {
	});

	test.it('fails', function () {
		assert.fail('boom!');
	});
});
```

Error message:
```
Message:
    Test `title` should be a "string" but "function" was given instead.
Stack:
Error: Test `title` should be a "string" but "function" was given instead.
    at new Test (D:\MyDev\ljs_app\trunk\periscope\examples\bugs\gulp-mocha-selenium\node_modules\mocha\lib\test.js:24:11)
    at context.it.context.specify (D:\MyDev\ljs_app\trunk\periscope\examples\bugs\gulp-mocha-selenium\node_modules\mocha\lib\interfaces\bdd.js:84:18)
    at Object.it (D:\MyDev\ljs_app\trunk\periscope\examples\bugs\gulp-mocha-selenium\node_modules\selenium-webdriver\testing\index.js:95:14)
    at Suite.<anonymous> (D:\MyDev\ljs_app\trunk\periscope\examples\bugs\gulp-mocha-selenium\test.js:7:7)
    at Object.create (D:\MyDev\ljs_app\trunk\periscope\examples\bugs\gulp-mocha-selenium\node_modules\mocha\lib\interfaces\common.js:114:19)
    at Object.context.describe.context.context [as describe] (D:\MyDev\ljs_app\trunk\periscope\examples\bugs\gulp-mocha-selenium\node_modules\mocha\lib\interfac
es\bdd.js:42:27)
    at Object.<anonymous> (D:\MyDev\ljs_app\trunk\periscope\examples\bugs\gulp-mocha-selenium\test.js:6:6)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

```

**Comment by jleyba** [comment]
I'm only able to reproduce this with `selenium-webdriver@2.53.3`; please upgrade to the latest release: `selenium-webdriver@3.0.0-beta-2`


```
$ npm install selenium-webdriver@3.0.0-beta-2
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
selenium-webdriver@3.0.0-beta-2 node_modules/selenium-webdriver
├── tmp@0.0.24
├── adm-zip@0.4.4
├── ws@1.1.1 (options@0.0.6, ultron@1.0.2)
├── xml2js@0.4.4 (xmlbuilder@8.2.2, sax@0.6.1)
└── rimraf@2.5.4 (glob@7.0.6)
$ ./node_modules/mocha/bin/mocha test.js 


  thing
    - pending
    ✓ works
    1) fails


  1 passing (23ms)
  1 pending
  1 failing

  1) thing fails:
     AssertionError: 'boom!' undefined undefined
      at Context.<anonymous> (test.js:13:12)
      at node_modules/selenium-webdriver/testing/index.js:153:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1029:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:138:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2736:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2719:21)
      at node_modules/selenium-webdriver/lib/promise.js:2642:25
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: thing fails
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:137:10)
```

**Comment by idchlife** [comment]
@doberkofler had same error, seems like I forgot to provide first argument in it() as string (title).

Also I mistakenly tried to use it as expect like it(object).should.be...etc

Maybe it was your case?

**Comment by doberkofler** [comment]
@idchlife nope. In my case, the pending tests throw the exception.
