### ISSUE TITLE
-Dwebdriver.chrome.driver option throw an exception during seting up selenium Grid node

### ISSUE THREAD

**Issue by semakd** [SeleniumHQ/selenium#2693]
## Meta -
OS:  Windows 10

Selenium Version:  selenium-server-standalone-3.0.0-beta2

Browser:  Remote

Browser Version:  

## Expected Behavior -
Node is regestered to the hub
## Actual Behavior -
Node throwing exeption. 
`C:\SeleniumServer>java -jar selenium-server-standalone-3.0.0-beta2.jar -role node -hub http://localhost:4444/grid/register -Dwebdriver.chrome.driver="C:/chromedriver_win32/chromedriver.exe" -Dwebdriver.gecko.driver="C:/geckodriver/geckodriver.exe"
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -Dwebdriver.chrome.driver=C:/chromedriver_win32/chromedriver.exe
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
        at org.openqa.grid.selenium.GridLauncherV3$3.setConfiguration(GridLauncherV3.java:231)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:130)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:67)`
## Steps to reproduce -

1.Create simple hub:
`java -jar selenium-server-standalone-3.0.0-beta2.jar -role hub`
2. Create simple node:
`java -jar selenium-server-standalone-3.0.0-beta2.jar -role node -hub http://localhost:4444/grid/register -Dwebdriver.chrome.driver="C:/chromedriver_win32/chromedriver.exe"`

**Comment by semakd** [comment]
Find solution at previous tickets. https://github.com/SeleniumHQ/selenium/issues/2566
