### ISSUE TITLE
Selenium 3 beta 3 - Safaridriver search for Plugin

### ISSUE THREAD

**Issue by Lightmoor** [SeleniumHQ/selenium#2726]
OS:  OSX 10.11.6 ( fresh reinstalled) 

Selenium Version: 3 beta3
Browser:  Safari 10

When i start my test

```
DesiredCapabilities safariCap = DesiredCapabilities.safari();
WebDriver driver = new SafariDriver(safariCap);
driver.get("http://google.de");	
```
		

Safari open and try to connect with the SafariDriver extension. 
I have no Browser extension installed 
its look like library attempts to start the old variant with the Browser extension

![bildschirmfoto 2016-09-06 um 18 57 44](https://cloud.githubusercontent.com/assets/4245019/18284262/9a7b9eda-7469-11e6-86b2-86c31ff3a40f.png)

```
Sep 06, 2016 6:57:38 PM org.openqa.selenium.safari.SafariDriverServer start
INFORMATION: Server started on port 2721
Sep 06, 2016 6:57:38 PM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFORMATION: Launching Safari
Sep 06, 2016 6:57:38 PM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFORMATION: Waiting for SafariDriver to connect
Sep 06, 2016 6:57:48 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFORMATION: Shutting down
Sep 06, 2016 6:57:48 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFORMATION: Stopping Safari
Sep 06, 2016 6:57:48 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFORMATION: Stopping server
Sep 06, 2016 6:57:48 PM org.openqa.selenium.safari.SafariDriverServer stop
INFORMATION: Stopping server
Sep 06, 2016 6:57:48 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFORMATION: Shutdown complete
Sep 06, 2016 6:57:48 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFORMATION: Shutting down
Sep 06, 2016 6:57:48 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFORMATION: Stopping server
Sep 06, 2016 6:57:48 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFORMATION: Shutdown complete
FAILED: shortShoppingTest
org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10072 ms
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:57:44 -0700'
System info: host: 'testqss-Mac-mini.local', ip: '10.66.11.176', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_101'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:118)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:116)
	at org.openqa.selenium.remote.RemoteWebDriver.startClient(RemoteWebDriver.java:284)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:78)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:69)
	at de.test.test.Test.shortShoppingTest(Test.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

```

I try in grid mode. The result was the same. 

```
DesiredCapabilities capabilities = DesiredCapabilities.safari();
        try {        	
		driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);
		} catch (MalformedURLException e) {}
             
    	driver.get("http://google.de");	

```

Selenium Log

```
./start_selenium.sh 
19:00:13.683 INFO - Selenium build info: version: '3.0.0-beta3', revision: 'c7b525d'
19:00:13.684 INFO - Launching a standalone Selenium Server
2016-09-06 19:00:13.704:INFO::main: Logging initialized @282ms
19:00:13.773 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
19:00:13.773 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
19:00:13.774 INFO - Driver class not found: com.opera.core.systems.OperaDriver
19:00:13.774 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
19:00:13.777 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
19:00:13.777 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
2016-09-06 19:00:13.806:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2016-09-06 19:00:13.832:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@69d9c55{/,null,AVAILABLE}
2016-09-06 19:00:13.861:INFO:osjs.ServerConnector:main: Started ServerConnector@6d8a00e3{HTTP/1.1}{0.0.0.0:4444}
2016-09-06 19:00:13.862:INFO:osjs.Server:main: Started @440ms
19:00:13.862 INFO - Selenium Server is up and running
19:00:27.247 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
19:00:27.280 INFO - Executing: [new session: Capabilities [{browserName=safari, version=, platform=MAC}]])
19:00:27.300 INFO - Creating a new session for Capabilities [{browserName=safari, version=, platform=MAC}]
19:00:27.372 INFO - Server started on port 24193
19:00:27.379 INFO - Launching Safari
19:00:27.390 INFO - Waiting for SafariDriver to connect
19:00:37.396 INFO - Shutting down
19:00:37.396 INFO - Stopping Safari
19:00:37.485 INFO - Stopping server
19:00:37.485 INFO - Stopping server
19:00:37.492 INFO - Shutdown complete
19:00:37.493 INFO - Shutting down
19:00:37.493 INFO - Stopping server
19:00:37.493 INFO - Shutdown complete
19:00:37.496 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.0-beta3', revision: 'c7b525d', time: '2016-09-01 14:57:03 -0700'
System info: host: 'testqss-Mac-mini.local', ip: '10.66.11.176', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_101'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:185)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.0-beta3', revision: 'c7b525d', time: '2016-09-01 14:57:03 -0700'
System info: host: 'testqss-Mac-mini.local', ip: '10.66.11.176', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_101'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
	... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10101 ms
Build info: version: '3.0.0-beta3', revision: 'c7b525d', time: '2016-09-01 14:57:03 -0700'
System info: host: 'testqss-Mac-mini.local', ip: '10.66.11.176', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_101'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:118)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:116)
	at org.openqa.selenium.remote.RemoteWebDriver.startClient(RemoteWebDriver.java:284)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:78)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:69)
	... 14 more
19:00:37.507 WARN - Exception: Failed to connect to SafariDriver after 10101 ms
Build info: version: '3.0.0-beta3', revision: 'c7b525d', time: '2016-09-01 14:57:03 -0700'
System info: host: 'testqss-Mac-mini.local', ip: '10.66.11.176', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_101'
Driver info: driver.version: SafariDriver
19:00:37.591 WARN - Exception thrown
java.lang.NullPointerException
	at java.util.HashMap.putMapEntries(HashMap.java:500)
	at java.util.HashMap.putAll(HashMap.java:784)
	at org.openqa.selenium.remote.DesiredCapabilities.<init>(DesiredCapabilities.java:54)
	at org.openqa.selenium.remote.server.handler.NewSession.setJsonParameters(NewSession.java:53)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:99)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:185)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pbi-qfs** [comment]
This is a bug in the startup sequence of SafariDriver. You can use the code from PR #2733, were the error is fixed.

**Comment by JordiGiros** [comment]
I'm facing the same issue and I don't know how to apply the fix @pbi-qfs suggests... What do I have to do?

**Comment by sivashankarcgs** [comment]
Hi All, 

 I am facing the same issue, Please help me on this:

OS:Sierra
Browser:Safari 10.0



Sep 23, 2016 12:08:06 PM org.openqa.selenium.safari.SafariDriverServer start
INFO: Server started on port 37566
Sep 23, 2016 12:08:06 PM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFO: Launching Safari
Sep 23, 2016 12:08:06 PM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFO: Waiting for SafariDriver to connect
Sep 23, 2016 12:08:16 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
Sep 23, 2016 12:08:16 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping Safari
Sep 23, 2016 12:08:17 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
Sep 23, 2016 12:08:17 PM org.openqa.selenium.safari.SafariDriverServer stop
INFO: Stopping server
Sep 23, 2016 12:08:17 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
Sep 23, 2016 12:08:17 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
Sep 23, 2016 12:08:17 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
Sep 23, 2016 12:08:17 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10230 ms
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:52:30 -0700'
System info: host: 'EXIMR-IM-177.local', ip: '10.1.5.187', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_91'
Driver info: driver.version: TestDriver
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:118)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:116)
	at org.openqa.selenium.remote.RemoteWebDriver.startClient(RemoteWebDriver.java:284)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:78)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:69)
	at com.exi.TestDriver.main(TestDriver.java:12)

**Comment by lukeis** [comment]
We've changed the code in the project recently. If you want to use the old SafariDriver (deprecated) extension. Then you should use 2.53.1 standalone server on the node.

If you do have Safari 10 on OS X El Capitan or on mac OS Sierra. Then /usr/bin/safaridriver should be present. You will first have to manually configure your system to allow automation and then will be able to use Selenium 3.0.0* versions. See more information here:
https://webkit.org/blog/6900/webdriver-support-in-safari-10/

Please retest with that latest server -
http://ci.seleniumhq.org:8080/job/Build_All_Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar

**Comment by thecodesmith** [comment]
Hitting this issue as well. @lukeis Which release will have the fix in the build you linked?

**Comment by lukeis** [comment]
beta4 (not yet released) or you can grab the latest:
http://ci.seleniumhq.org:8080/job/Build_All_Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar
