### ISSUE TITLE
Cannot click on a blank area with chrome

### ISSUE THREAD

**Issue by testerjoe2** [SeleniumHQ/selenium#2728]
OS:  Windows 7 64 bit
ChromeDriver version: 2.9.248315
Selenium Version: 2.53.0
Browser:  52.0.2743.116 m

I wanted to learn how to click on a blank area on a page using selenium. The commonly suggested method is to click the html element. This method fails with chrome, but not with firefox.

` import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Temp {
    private static final WebDriver browser = new ChromeDriver();

    private static String url = "https://www.google.com/";

    public static void main(String[] args) {
        browser.get(url);
        browser.findElement(By.tagName("html")).click();
    }

 }`

`Starting ChromeDriver (v2.9.248315) on port 15072
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 334 milliseconds
Session ID: 69ce4de350c6ade8abcbcd0b1b2093f6
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
    at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
    at src.Temp.main(Temp.java:14)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`

**Comment by lukeis** [comment]
'html' is a special element, what you want is 'body' (the first DOM element that is 'visible')

for getting started and asking questions like this, please post on the selenium-users google group instead:
https://groups.google.com/forum/#!forum/selenium-users
