### ISSUE TITLE
I am getting this error in selenium webdriver, please help 

### ISSUE THREAD

**Issue by Saraswati-rajkumar** [SeleniumHQ/selenium#2729]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Actual Behavior - error Exception in thread "main" java.lang.IllegalStateException: The driver executable does not exist: C:\Users\Aurora\Downloads\geckodriver-v0.8.0-win32.zip\geckodriver.exe
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:121)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:116)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:38)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:91)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
	at org.openqa.selenium.firefox.FirefoxDriver.createCommandExecutor(FirefoxDriver.java:245)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at learn.learn.main(learn.java:12)

## Steps to reproduce - code  package learn;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class learn {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.gecko.driver",
				"C:\\Users\\Aurora\\Downloads\\geckodriver-v0.8.0-win32.zip\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		

	}

}

**Comment by lukeis** [comment]
try extracting the file from the zip first and then using that path instead... also 0.10 is the latest geckodriver

for further questions related to selenium, please consider posting to the selenium-users google group:
https://groups.google.com/forum/#!forum/selenium-users
