### ISSUE TITLE
Unable To Run Any Selenium Unit Tests

### ISSUE THREAD

**Issue by silne30** [SeleniumHQ/selenium#2732]
## Meta -
OS:  OSX 10.11.6

Selenium Version:  
3.0.0b2
Browser:  
FF 48.0.2 **(I am aware of the issue using geckodriver. Geckodriver is currently in the PATH)**

## Expected Behavior -
running `./go test_py` Would run all python tests for them to pass.
## Actual Behavior -
All tests fail with the E (error code) They all have the same error.

```
======================================================================
ERROR: test_we_can_launch_multiple_firefox_instances (__main__.FirefoxLauncherTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ff_launcher_tests.py", line 39, in test_we_can_launch_multiple_firefox_instances
    self.webdriver1 = webdriver.Firefox(capabilities=capabilities)
  File "/Users/jdorlus/.virtualenvs/selenium-test/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 85, in __init__
    self.binary, timeout)
  File "/Users/jdorlus/.virtualenvs/selenium-test/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Users/jdorlus/.virtualenvs/selenium-test/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/Users/jdorlus/.virtualenvs/selenium-test/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/py/xhpmll4n68s689s14p8tktlh0000gp/T/tmpzPfr_B If you specified a log_file in the FirefoxBinary constructor, check it for details.
```
## Steps to reproduce -
1.) Download and upgrade Selenium 3.0.0b2 to latest commit
2.) Download geckodriver and build from source from latest commit 
3.) Put gecko driver in PATH (i.e. /usr/local/bin)
4.) Navigate to selenium root folder
5.) Make sure you have FF 48.0.2 installed
6.) Run `./go test_py`

**Comment by davehunt** [comment]
@silne30 running `./go test_py` runs the FirefoxDriver which will not work with Firefox 48. Try `./go //py:marionette_test:run` to run the Marionette tests with Firefox 48, or switch to Firefox 47.0.1 to run the FirefoxDriver tests.
