### ISSUE TITLE
chrome not opening in new selenium-server-standalone-3.0.0-beta3

### ISSUE THREAD

**Issue by bismayp** [SeleniumHQ/selenium#2743]
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:109)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:116)
	at sikuli.Br.main(Br.java:46)

**Comment by ddavison** [comment]
just as the exception states...

> The path to the driver executable must be set by the webdriver.chrome.driver system property

please [read the page](https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver#troubleshooting) that the stacktrace mentioned.  should shed some light.

**Comment by bismayp** [comment]
@ddavison  -  Thank you so much for your reply, actually i am new to Selenium, 
but as per the link you provide , i have checked , but getting error, below is the code.
Please let me know if i am missing any thing or doing something wrong :

WebDriver driver;
 System.setProperty("webdriver.gecko.driver", "C:\\Users\\bismay\\Desktop\\jar\\geckodriver-v0.10.0-win64\\geckodriver.exe");
driver =new ChromeDriver();
driver.navigate().to("my URL");

**Comment by JMVM** [comment]
@bismayp 

You are setting for gecko, but later creating an instance for ChromeDriver.

It looks like wrong.

Cheers,

**Comment by Vinyanka** [comment]
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:339)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at Openurl.openbrowser(Openurl.java:13)
	at Openurl.main(Openurl.java:30)




This my code:
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;//

public class Openurl {
	WebDriver driver;
	public void openbrowser()
	{
		try {
			System.setProperty("webdriver.crome.driver","F:\\Priyanka\\Selenium\\SELENIUM NEW\\eclipse-workspace\\Practise1\\Driver\\chromedriver.exe");
			driver = new ChromeDriver();
			driver.manage().deleteAllCookies();
			driver.manage().window().maximize();
			driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
			driver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);
			driver.get("https://www.facebook.com");
		} 
		catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		}
	
 public static void main(String[] args) {
	
	 Openurl URL = new Openurl();
	 URL.openbrowser();
}
	
	
	}

**Comment by cgoldberg** [comment]
@bismayp 
you need to point `webdriver.gecko.driver` to your chromedriver executable.  (geckodriver is for Firefox)

**Comment by cgoldberg** [comment]
@lamyberber https://sites.google.com/a/chromium.org/chromedriver/getting-started
