### ISSUE TITLE
Node.js: Testing methods not available in global variable

### ISSUE THREAD

**Issue by paazmaya** [SeleniumHQ/selenium#2787]
## Meta

* OS:  macOS 10.11.6
* Node.js v6.3.1
* npm v3.10.3
* Selenium Version:  npm published `3.0.0-beta-2`, tested also `2.53.1`
* Browser:  Chrome, but did not get that far...

## Expected Behavior

Tests executed as defined in the comments of 
https://github.com/SeleniumHQ/selenium/blob/ede98def1f85600ec120536bd1f36f244a331b86/javascript/node/selenium-webdriver/testing/index.js

## Actual Behavior

Tests not executed due to missing property throwing.

```
exports.describe.skip = global.describe.skip;
                                       ^

TypeError: Cannot read property 'skip' of undefined
    at Object.<anonymous> (node_modules/selenium-webdriver/testing/index.js:226:40)
```

## Steps to reproduce -

```js
const webdriver = require('selenium-webdriver'),
  chrome = require('selenium-webdriver/chrome'),
  test = require('selenium-webdriver/testing'),
  By = webdriver.By,
  until = webdriver.until;

const BASE_URL = 'https://paazmaya.fi/';

test.describe('Front Page', function() {
  let driver;

  test.before(function() {
    driver = new chrome.Driver();
  });

  test.after(function() {
    driver.quit();
  });

  test.it('has proper main description', function() {
    driver.get(BASE_URL);
    driver.wait(until.elementLocated(By.css('.main-description')), 3000).then(() => {
      console.log(driver.findElement(By.css('.main-description')).text);
    });
  });
});
```

**Comment by jleyba** [comment]
The testing package provides adapters for mocha - you have to actually run with mocha (which defines those globals), not node.

**Comment by mattrlong** [comment]
Plus one on this issue. I also see the error mentioned when running through Mocha when using the --require option.

**Comment by paazmaya** [comment]
Sorry, the command used was missing from the reproduction section:

```sh
node script-that-has-the-above-contents.js
```

**Comment by jleyba** [comment]
@mattrlong What command are you running that's failing? I just tried running with `mocha --require ws`, which is admittedly simple, but it still worked.

**Comment by mattrlong** [comment]
@jleyba this is the command:
./node_modules/.bin/mocha --require ./hooks.js ./test/specs --timeout 10000 

mocha fails with the following error:
```
exports.describe.skip = global.describe.skip;
                                       ^

TypeError: Cannot read property 'skip' of undefined
    at Object.<anonymous> (/.../node_modules/selenium-webdriver/testing/index.js:226:40)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/.../hooks.js:2:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /.../node_modules/mocha/bin/_mocha:310:3
    at Array.forEach (native)
    at Object.<anonymous> (/.../node_modules/mocha/bin/_mocha:309:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

The line of hooks.js that the error is referring to is
```
var webdriver = require('selenium-webdriver'),
	test = require('selenium-webdriver/testing'); <-- this one
```
