### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by debasisj** [SeleniumHQ/selenium#2800]
## Meta -
OS:  Win7 Enterprise

Selenium Version:  
Selenium.WebDriver.2.53.1
selenium-server-standalone-2.53.1
Browser:  
Firefox

Browser Version:  
47

## Expected Behavior -
Initiate remote driver - ff
## Actual Behavior -
Java heap issue 
## Steps to reproduce -
This is my code snippet in C#

        private static FirefoxProfile GetFirefoxProfile()
        {
            FirefoxProfile profile = new FirefoxProfile();
           FirefoxProfileManager mgr = new FirefoxProfileManager();
            profile = mgr.GetProfile("default");
            return profile;

        }

        private static IWebDriver GetRemoteDriver()
        {

            DesiredCapabilities cap =  DesiredCapabilities.Firefox();
            var Profile = GetFirefoxProfile();
            cap.SetCapability(FirefoxDriver.ProfileCapabilityName, Profile.ToBase64String());
            cap.SetCapability(CapabilityType.BrowserName, "firefox");
            cap.SetCapability(CapabilityType.Platform,"Windows 7");
            IWebDriver driver = new RemoteWebDriver(new Uri("http://<IP address for the node>/wd/hub"), cap, TimeSpan.FromSeconds(180));
            return driver;
        }

But getting the java heap issue at the node 
19:18:03.980 WARN - Error for /wd/hub/session
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source
)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuffer.append(Unknown Source)
        at java.io.StringWriter.write(Unknown Source)
        at com.google.gson.stream.JsonWriter.string(JsonWriter.java:561)
        at com.google.gson.stream.JsonWriter.value(JsonWriter.java:419)
        at com.google.gson.internal.bind.TypeAdapters$25.write(TypeAdapters.java
:690)
        at com.google.gson.internal.bind.TypeAdapters$25.write(TypeAdapters.java
:704)
        at com.google.gson.internal.bind.TypeAdapters$25.write(TypeAdapters.java
:642)
        at com.google.gson.internal.Streams.write(Streams.java:68)
        at com.google.gson.JsonElement.toString(JsonElement.java:324)
        at java.lang.String.valueOf(Unknown Source)
        at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConv
erter.java:89)
        at org.openqa.selenium.remote.JsonToBeanConverter.convertMap(JsonToBeanC
onverter.java:344)
        at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConv
erter.java:215)
        at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConv
erter.java:43)
        at org.openqa.selenium.remote.http.JsonHttpCommandCodec.decode(JsonHttpC
ommandCodec.java:274)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleReques
t(JsonHttpCommandHandler.java:74)
       at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverS
ervlet.java:204)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.
java:166)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet
.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.jav
a:428)
        at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler
.java:680)
        at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.j
ava:571)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
        at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
        at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)

**Comment by tommywo** [comment]
@debasisj try to give java more heap using -Xmx flag

**Comment by lukeis** [comment]
as previous comment said, you'll need to tune your jvm settings if you're running into this

**Comment by debasisj** [comment]
Tried few option to increase JVM but no luck - still same issue for a simple script 
Can you let me know steps to set the JVM heap size (command line or control panel or env setting ..where?)

**Comment by manoj9788** [comment]
https://docs.oracle.com/cd/E15523_01/web.1111/e13814/jvm_tuning.htm#PERFM169
