### ISSUE TITLE
NullPointerException when trying to load grid console page

### ISSUE THREAD

**Issue by mhardin** [SeleniumHQ/selenium#2804]
## Meta -
OS:  OSX 10.11.6
Selenium Version:  selenium-server 3.0.0-beta3

## Expected Behavior -

Hi, we're pulling down selenium-server as a maven dependency as part of my open source project.  We were previously using org.openqa.grid.selenium.GridLauncher as an entry point .  However, when using org.openqa.grid.selenium.GridLauncherV3 as the main class and "-role hub" as the program arguments, we get a NullPointerException when trying to load the grid console page (http://127.0.0.1:4444/grid/console) in a web browser.  Here is the stack trace seen in the console:

``` Sep 20, 2016 10:28:18:164 AM - WARN  [qtp764358458-22] [/] unavailable
java.lang.NullPointerException: null
	at org.openqa.grid.web.servlet.beta.ConsoleServlet.getVersion(ConsoleServlet.java:264) ~[selenium-server-3.0.0-beta3.jar:na]
	at org.openqa.grid.web.servlet.beta.ConsoleServlet.<init>(ConsoleServlet.java:57) ~[selenium-server-3.0.0-beta3.jar:na]
	at org.openqa.grid.web.servlet.beta.ConsoleServlet.<init>(ConsoleServlet.java:52) ~[selenium-server-3.0.0-beta3.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_65]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_65]
	at org.seleniumhq.jetty9.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.newInstance(ServletHolder.java:1203) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.initServlet(ServletHolder.java:584) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.getServlet(ServletHolder.java:468) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.ensureInstance(ServletHolder.java:763) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.prepare(ServletHolder.java:748) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Sep 20, 2016 10:28:18:165 AM - WARN  [qtp764358458-22] [ServletHandler] 
javax.servlet.ServletException: java.lang.NullPointerException
	at org.seleniumhq.jetty9.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1176) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.newInstance(ServletHolder.java:1203) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.initServlet(ServletHolder.java:584) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.getServlet(ServletHolder.java:468) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.ensureInstance(ServletHolder.java:763) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.prepare(ServletHolder.java:748) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: java.lang.NullPointerException: null
	at org.openqa.grid.web.servlet.beta.ConsoleServlet.getVersion(ConsoleServlet.java:264) ~[selenium-server-3.0.0-beta3.jar:na]
	at org.openqa.grid.web.servlet.beta.ConsoleServlet.<init>(ConsoleServlet.java:57) ~[selenium-server-3.0.0-beta3.jar:na]
	at org.openqa.grid.web.servlet.beta.ConsoleServlet.<init>(ConsoleServlet.java:52) ~[selenium-server-3.0.0-beta3.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_65]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_65]
	at org.seleniumhq.jetty9.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	... 20 common frames omitted
Sep 20, 2016 10:28:18:303 AM - WARN  [qtp764358458-23] [/] unavailable
java.lang.NullPointerException: null
	at org.openqa.grid.web.servlet.DisplayHelpServlet.getVersion(DisplayHelpServlet.java:105) ~[selenium-server-3.0.0-beta3.jar:na]
	at org.openqa.grid.web.servlet.DisplayHelpServlet.<init>(DisplayHelpServlet.java:40) ~[selenium-server-3.0.0-beta3.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_65]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_65]
	at org.seleniumhq.jetty9.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.newInstance(ServletHolder.java:1203) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.initServlet(ServletHolder.java:584) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.getServlet(ServletHolder.java:468) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.ensureInstance(ServletHolder.java:763) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.prepare(ServletHolder.java:748) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Sep 20, 2016 10:28:18:304 AM - WARN  [qtp764358458-23] [ServletHandler] 
javax.servlet.ServletException: java.lang.NullPointerException
	at org.seleniumhq.jetty9.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1176) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.newInstance(ServletHolder.java:1203) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.initServlet(ServletHolder.java:584) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.getServlet(ServletHolder.java:468) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.ensureInstance(ServletHolder.java:763) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHolder.prepare(ServletHolder.java:748) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: java.lang.NullPointerException: null
	at org.openqa.grid.web.servlet.DisplayHelpServlet.getVersion(DisplayHelpServlet.java:105) ~[selenium-server-3.0.0-beta3.jar:na]
	at org.openqa.grid.web.servlet.DisplayHelpServlet.<init>(DisplayHelpServlet.java:40) ~[selenium-server-3.0.0-beta3.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_65]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_65]
	at org.seleniumhq.jetty9.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	at org.seleniumhq.jetty9.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166) ~[jetty-repacked-9.2.13.v20160825.jar:3.1.0]
	... 20 common frames omitted ```

**Comment by tommywo** [comment]
I think @shs96c fixed it in 5772b63b
can you try with this jar http://ci.seleniumhq.org:8080/job/Build_All_Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar ?

**Comment by mhardin** [comment]
@tommywo that seems to have addressed the problem.

Is there a way to incorporate the 'latest' jar via Maven?  If not, when should the next beta release be cut?

**Comment by lukeis** [comment]
@mhardin if you clone the selenium repo you can run `./go mvn-install` this will copy the selenium artifacts (after building the world) into your ~/.m2/repository/  folder. It will use the version specified in the file:
https://github.com/SeleniumHQ/selenium/blob/master/SELENIUM_VERSION

so, right now it will overwrite your local install of beta3.

**Comment by lukeis** [comment]
sorry, that should have been `./go maven-install`
