### ISSUE TITLE
WebDriverJS Example Not Running And Throwing Errors

### ISSUE THREAD

**Issue by joshmgrant** [SeleniumHQ/selenium#2806]
## Details

OS:  Win 10
Selenium Version:  2.53.1
Browser:  Firefox
Browser Version: 49.0  
## Steps to Reproduce -

Using the code from the [WebDriverJS documents](https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs), I did the following: 
- Installed v0.9.0 of the GeckoDriver and added it (correctly) to my PATH
- Installed the `selenium-webdriver` module
- Copied the code from the middle section into a file called `google_search.js`
- Ran `node google_search.js`
## Expected Behavior -

The script would run without any issues and complete the given steps using the WebDriver. 
## Actual Behavior -

The script failed throwing an error with the following stack trace: 

``` bash
C:\Users\joshua.grant\node_modules\selenium-webdriver\lib\promise.js:654
    throw error;
    ^

Error: Could not locate Firefox on the current system
    at Error (native)
    at C:\Users\joshua.grant\node_modules\selenium-webdriver\firefox\binary.js:115:11
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\joshua.grant\node_modules\selenium-webdriver\lib\webdriver.js:329:24)
    at Driver (C:\Users\joshua.grant\node_modules\selenium-webdriver\firefox\index.js:386:38)
    at Builder.build (C:\Users\joshua.grant\node_modules\selenium-webdriver\builder.js:467:16)
    at Object.<anonymous> (C:\Users\joshua.grant\google_search.js:8:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
From: Task: WebDriver.navigate().to(http://www.google.com/ncr)
    at Driver.schedule (C:\Users\joshua.grant\node_modules\selenium-webdriver\lib\webdriver.js:377:17)
    at Navigation.to (C:\Users\joshua.grant\node_modules\selenium-webdriver\lib\webdriver.js:1027:25)
    at Driver.get (C:\Users\joshua.grant\node_modules\selenium-webdriver\lib\webdriver.js:795:28)
    at Object.<anonymous> (C:\Users\joshua.grant\google_search.js:10:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

Changing the browser type from `firefox` to `chrome` ran without issues (with a ChromeDriver properly installed in my machine). It appears this is an issue with the WebDriverJS not locating the Firefox EXE path on Win 10 by default.

**Comment by christian-bromann** [comment]
@joshmgrant you need to have Firefox installed on your system to run tests in Firefox. It is out of scope of the `selenium-webdriver` binding to install the browser for you.
