### ISSUE TITLE
FirefoxProfile for Remote fails

### ISSUE THREAD

**Issue by Andrei-Stepanov** [SeleniumHQ/selenium#2810]
Remote: 
Linux RHEL 7.2.z 
firefox-45.3.0-1.el7_2.x86_64
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
java -jar selenium-server-standalone-3.0.0-beta2.jar -port 55555

Client:
Linux RHEL 7.2.z + python selenium bindings 2.53.6

I use http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp#using-a-firefoxprofile as a guide.

Python code:

fp = webdriver.FirefoxProfile()
driver = webdriver.Remote(command_executor, webdriver.DesiredCapabilities.FIREFOX, browser_profile=fp)

fails in:

10:30:49.528 INFO - Executing: [new session: Capabilities [{marionette=false, browserName=firefox, javascriptEnabled=true, version=, platform=ANY, firefox_profile=UEsDBBQAAAAIANhTNUm6C19U6QMAA...}]])
10:30:49.531 INFO - Creating a new session for Capabilities [{marionette=false, browserName=firefox, javascriptEnabled=true, version=, platform=ANY, firefox_profile=UEsDBBQAAAAIANhTNUm6C19U6QMAA...}]
10:30:49.597 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'astepano-ws.brq.redhat.com', ip: '10.34.130.239', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-505.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'astepano-ws.brq.redhat.com', ip: '10.34.130.239', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-505.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:100)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:68)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:90)
	... 9 more
Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
null
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'astepano-ws.brq.redhat.com', ip: '10.34.130.239', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-505.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:129)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:315)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:232)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:132)
	... 14 more
Caused by: org.openqa.selenium.WebDriverException: java.io.IOException: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'astepano-ws.brq.redhat.com', ip: '10.34.130.239', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-505.el7.x86_64', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.extractAndCheck(FirefoxBinary.java:169)
	at org.openqa.selenium.firefox.FirefoxBinary.modifyLinkLibraryPath(FirefoxBinary.java:130)
	at org.openqa.selenium.firefox.FirefoxBinary.startProfile(FirefoxBinary.java:91)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:100)
	... 20 more
Caused by: java.io.IOException: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so
	at org.openqa.selenium.io.FileHandler.locateResource(FileHandler.java:88)
	at org.openqa.selenium.io.FileHandler.copyResource(FileHandler.java:57)
	at org.openqa.selenium.firefox.FirefoxBinary.extractAndCheck(FirefoxBinary.java:162)
	... 23 more
10:30:49.598 WARN - Exception: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so

Without pointing specifying: browser_profile=fp it works fine.

**Comment by inferrna** [comment]
Same error with Selenium 3.0.0-beta3 and nativeEvents=true

**Comment by lukeis** [comment]
this appears to be fixed in beta4. Please update here if not

**Comment by robythomas** [comment]
I doubt this is fixed upstream. I'm using Selenium 3.0.1 in a grid and I see the exception thrown in from the node log. The client code is Python (via RobotFramework) with 2.53.x selenium python libraries.

```
Oct 27, 2016 8:53:37 AM org.openqa.grid.selenium.GridLauncherV3 main
INFO: Selenium build info: version: '3.0.1', revision: '1969d75'
Oct 27, 2016 8:53:37 AM org.openqa.grid.selenium.GridLauncherV3$3 launch
INFO: Launching a Selenium Grid node
Oct 27, 2016 8:53:37 AM org.openqa.selenium.remote.server.DefaultDriverSessions registerDriverProvider
...
Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows:
null
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'XXXXXX', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-45-generic', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:129)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:347)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)
        ... 14 more
Caused by: org.openqa.selenium.WebDriverException: java.io.IOException: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'XXXXXX', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-45-generic', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.FirefoxBinary.extractAndCheck(FirefoxBinary.java:169)
        at org.openqa.selenium.firefox.FirefoxBinary.modifyLinkLibraryPath(FirefoxBinary.java:130)
        at org.openqa.selenium.firefox.FirefoxBinary.startProfile(FirefoxBinary.java:91)
        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:100)
        ... 20 more
Caused by: java.io.IOException: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so
        at org.openqa.selenium.io.FileHandler.locateResource(FileHandler.java:88)
        at org.openqa.selenium.io.FileHandler.copyResource(FileHandler.java:57)
        at org.openqa.selenium.firefox.FirefoxBinary.extractAndCheck(FirefoxBinary.java:162)
        ... 23 more


```

The hub & node is running on an Ubuntu Xenial system

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial


$ dpkg -l firefox
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-============================================================
ii  firefox                     49.0+build4-0ubunt amd64              Safe and easy web browser from Mozilla

```

**Comment by inferrna** [comment]
Same with java code on 12.04 and Selenium 3.0.1

**Comment by lukeis** [comment]
@robythomas your stacktraces shows attempting to use Selenium's Firefox webdriver.xpi, but that is only compatible up to firefox 47.0.1, to use 48+ of firefox, you must use GeckoDriver.

**Comment by inferrna** [comment]
I tried to add folders **x86** and **amd64** with binaries from selenium-firefox-driver-2.53.1.jar  into selenium-firefox-driver-3.0.1.jar and got following error:
```java
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'autotest', ip: '10.1.1.107', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-44-pve', java.version: '1.8.0_101'
Driver info: driver.version: FirefoxDriver
	at Full.AvtorizPolz.Fiz.Promokody.AbstractFilter.<init>(AbstractFilter.java:30)
Caused by: org.openqa.selenium.firefox.NotConnectedException: 
Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Provider
1478079829752	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1478079829752	addons.manager	DEBUG	Provider finished startup: GMPProvider
1478079829752	addons.manager	DEBUG	Starting provider: PluginProvider
1478079829752	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1478079829753	addons.manager	DEBUG	Provider finished startup: PluginProvider
1478079829753	addons.manager	DEBUG	Completed startup sequence
1478079831844	DeferredSave.extensions.json	DEBUG	Starting write
1478079832120	addons.repository	DEBUG	No addons.json found.
1478079832121	DeferredSave.addons.json	DEBUG	Save changes
1478079832126	DeferredSave.addons.json	DEBUG	Starting timer
1478079832166	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1478079832167	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1478079832168	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1478079832177	DeferredSave.extensions.json	DEBUG	Write succeeded
1478079832177	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1478079832179	DeferredSave.addons.json	DEBUG	Starting write
1478079832254	DeferredSave.addons.json	DEBUG	Write succeeded
```
firefox version 49, both paths has set up properly before init new driver:
        System.setProperty("webdriver.firefox.marionette", "path_to_geckodriver");
        System.setProperty("webdriver.gecko.driver", "path_to_geckodriver");

**Comment by cgoldberg** [comment]
@inferrna 
as stated previously in this thread:
> "to use 48+ of firefox, you must use GeckoDriver."

Your log shows:
> Driver info: driver.version: FirefoxDriver

**Comment by inferrna** [comment]
@cgoldberg 
Are you meaning I should
```import org.openqa.selenium.firefox.GeckoDriver;```
instead of
```import org.openqa.selenium.firefox.FirefoxDriver;```
 or smth else?

**Comment by lukeis** [comment]
@inferrna do NOT set `System.setProperty("webdriver.firefox.marionette",...)` if you set it to anything except `true` it will disable GeckoDriver and force use the Selenium project's webdriver extension (which only works up to 47.0.1)

**Comment by inferrna** [comment]
@lukeis 
Thanks, it was sort of helpful. Now error differs:
```java
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.671 sec <<< FAILURE! - in Full.AvtorizPolz.Fiz.Promokody.AbstractFilter
testPageOpening(Full.AvtorizPolz.Fiz.Promokody.AbstractFilter)  Time elapsed: 0.019 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: 
java.lang.reflect.InvocationTargetException
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'autotest', ip: '10.1.1.107', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-44-pve', java.version: '1.8.0_101'
Driver info: driver.version: unknown
	at Full.AvtorizPolz.Fiz.Promokody.AbstractFilter.<init>(AbstractFilter.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at Full.AvtorizPolz.Fiz.Promokody.AbstractFilter.<init>(AbstractFilter.java:30)
Caused by: org.openqa.selenium.WebDriverException: 
The driver server has unexpectedly died!
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'autotest', ip: '10.1.1.107', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-44-pve', java.version: '1.8.0_101'
Driver info: driver.version: FirefoxDriver
	at Full.AvtorizPolz.Fiz.Promokody.AbstractFilter.<init>(AbstractFilter.java:30)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:6725 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at Full.AvtorizPolz.Fiz.Promokody.AbstractFilter.<init>(AbstractFilter.java:30)
Caused by: java.net.ConnectException: Connection refused
	at Full.AvtorizPolz.Fiz.Promokody.AbstractFilter.<init>(AbstractFilter.java:30)
```
I'll continue tries

**Comment by rosariomgomez** [comment]
I believe I'm experiencing this same issue with version: 3.0.1.

Hub and nodes are running on:
Linux Ubuntu Trusty 14.04 VMs
firefox-47.0.2 (linux-x86_64)

xvfb-run java -Dwebdriver.firefox.bin='firefox/firefox-bin' -jar selenium-server-standalone-3.0.1.jar   -role node -hub http://<hub_ip>:4444/grid/register -port 5555 -maxSession 5 -browser browserName=firefox,maxInstances=5,seleniumProtocol=WebDriver

Client:
Python selenium bindings 2.53.6

Python code:
`caps = webdriver.DesiredCapabilities.FIREFOX
caps["marionette"] = False
fp = webdriver.FirefoxProfile()
fp.set_preference("general.useragent.override", "Mozilla/5.0 (iPad; CPU OS 4_3_5 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8L1 Safari/6533.18.5")
driver_ = webdriver.Remote(desired_capabilities=caps, browser_profile=fp, command_executor=hub_ip)
set_browser_size(driver_, 1024, 768)`

fails in:
`WebDriverException: Message: java.io.IOException: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: '<host>', ip: '<ip>', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-47-generic', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
Stacktrace:
    at org.openqa.selenium.firefox.FirefoxBinary.extractAndCheck (FirefoxBinary.java:169)
    at org.openqa.selenium.firefox.FirefoxBinary.modifyLinkLibraryPath (FirefoxBinary.java:130)
    at org.openqa.selenium.firefox.FirefoxBinary.startProfile (FirefoxBinary.java:91)
    at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start (NewProfileExtensionConnection.java:100)
    at org.openqa.selenium.firefox.FirefoxDriver.startClient (FirefoxDriver.java:347)
    at org.openqa.selenium.remote.RemoteWebDriver.<init> (RemoteWebDriver.java:116)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:259)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:247)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:242)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:135)
    at sun.reflect.GeneratedConstructorAccessor12.newInstance (None:-1)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:423)
    at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor (FirefoxDriverProvider.java:86)
    at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance (FirefoxDriverProvider.java:64)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance (DefaultDriverFactory.java:60)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:222)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:209)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)`


Notes: 
1. Without specifying a profile, the error is not happening
`caps = webdriver.DesiredCapabilities.FIREFOX
caps["marionette"] = False
driver_ = webdriver.Remote(desired_capabilities=caps, command_executor=hub_ip)
set_browser_size(driver_, 1920, 1080)`

2. With the same exact configuration (browser and selenium server versions), but running on MacOS (OS X El Capitan) is also not happening.

Any hint on what the issue might be?

Thanks for helping!
