### ISSUE TITLE
Error when running jUnit tests with Firefox 47 and Selenium 2.53

### ISSUE THREAD

**Issue by larisagrecu** [SeleniumHQ/selenium#2820]
I am running jUnit tests locally on my Windows 8 machine and I get very often, not all the time, this error:

`java.lang.RuntimeException: Process refused to die after 10 seconds, and couldn't taskkill it: Timeout waiting for process to die
at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:143)
at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:247)
at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$200(UnixProcess.java:201)
at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:125)
at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:155)
at org.openqa.selenium.firefox.FirefoxBinary.quit(FirefoxBinary.java:246)
at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit(NewProfileExtensionConnection.java:194)
at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit(FirefoxDriver.java:364)
at org.openqa.selenium.firefox.FirefoxDriver.stopClient(FirefoxDriver.java:310)
at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:529)
at net.thucydides.core.webdriver.WebDriverFacade.forcedQuit(WebDriverFacade.java:125)
at net.thucydides.core.webdriver.WebDriverFacade.reset(WebDriverFacade.java:117)
at net.thucydides.core.webdriver.WebdriverProxyFactory.resetDriver(WebdriverProxyFactory.java:86)
at net.serenitybdd.junit.runners.SerenityRunner.prepareBrowserForTest(SerenityRunner.java:480)
at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:427)
at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:52)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:242)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)`

I use Firefox 47 and Serenity 1.1.38 (which is using Selenium 2.53). I tried with lower versions like Firefox 45.3 and Selenium 2.48 but still the same.
One combination that worked was  Firefox 41 and Serenity 1.1.21 (which uses Selenium 2.48), but I hope that another solution exists, other than keeping these lower versions. 
Any ideas about how could I fix this issue? 
Thank you!

**Comment by AutomatedTester** [comment]
You need to be using Firefox 47.0.1 for this to work or move Firefox to ESR45
