### ISSUE TITLE
client.end() should return its promise operand

### ISSUE THREAD

**Issue by jtlapp** [SeleniumHQ/selenium#2828]
OS:  OS: Mac OS X 10.11.4 x86_64
Selenium Version:  v2.53.1, with Core v2.53.1. Built from revision a36b8b1
Browser:  Firefox (but n/a)

When a callback provided to Selenium throws an exception or returns a rejected promise, the client properly bubbles up the error, except when chaining `.end()`.

I tested errors generated as follows:

- `throw new Error("an exception happens here")`
- `return Promise.reject(new Error("a promise gets rejected"))`
- `return Promise.reject("a promise gets rejected")`

Here is a demonstration of throwing an exception that works properly:

```js
var promise = webdriverio
    .remote(options).init()
    .url('http://www.google.com')
    .getTitle().then(function(title) {
        throw new Error("an exception happens here");
        console.log('Title was: ' + title);
    });
    promise.end();
showError(promise);

function showError(promise) {
    if (typeof promise.then === 'function') {
        promise.catch(function (err) {
            if (err instanceof Error)
                console.log(err);
            else
                console.log("Rejected promise: "+ err);
        });
    }
    else
        console.log("not a promise");
}

// Error: an exception happens here
//     at Object.<anonymous> (/repos/arepo/tests/test_errs.js:26:15)
//     at Object.exec (/repos/arepo/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
//     at Object.resolve (/repos/arepo/node_modules/webdriverio/build/lib/webdriverio.js:189:29)
```

If we instead return the result of chaining `.end()`, we get this:

```js
var promise = webdriverio
    .remote(options).init()
    .url('http://www.google.com')
    .getTitle().then(function(title) {
        throw new Error("an exception happens here");
        console.log('Title was: ' + title);
    })
    .end();
showError(promise);

// Error: an exception happens here
//     at title() - getTitle.js:29:28
//     at end() - webdriverio.js:16:6
```

For completeness, here are comparisons of chaining vs not chaining returning rejected promises:

```js
        return Promise.reject(new Error("a promise gets rejected"));

/* NOT CHAINED */
// Error: a promise gets rejected
//     at Object.<anonymous> (/repos/arepo/tests/test_errs.js:56:31)
//     at Object.exec (/repos/arepo/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
//     at Object.resolve (/repos/arepo/node_modules/webdriverio/build/lib/webdriverio.js:189:29)

/* CHAINED */
// Error: a promise gets rejected
//     at title() - getTitle.js:29:28
//     at end() - test_errs.js:45:6
```

```js
        return Promise.reject("a promise gets rejected");

/* NOT CHAINED */
// Rejected promise: a promise gets rejected

/* CHAINED */
// (nothing is output in this scenario)
```

I suspect a decision must be made about whether `.end()` should return a promise that propagates a callback error. If the answer is yes, it should be made consistent. If the answer is no, `.end()` should return no error information instead of a confused mix of information. The inconsistencies had me pulling my hair out looking for the proper resolution.

My preference is to be able to include include the following in my tests and have it properly propagate errors to the test harness:

```js
var t = require('tap');

t.test("load the home page", function (t) {
    return webdriverio
        .remote(options).init()
        .url('http://www.google.com')
        .getTitle().then(function(title) {
            console.log('Title was: ' + title);
        })
        .end();
});
```

Note that [`tap`](https://github.com/tapjs/node-tap) properly handles the returned promise in all of these cases, reporting the error.

**Comment by jtlapp** [comment]
Oops, I meant to file this under webdriver.io. Apologies.
