### ISSUE TITLE
Internet Explorer Driver throws "WebDriverException: Command not found" during execution command getAvailableLogTypes()

### ISSUE THREAD

**Issue by Ulyana-Yeryksonava** [SeleniumHQ/selenium#2831]
## Meta

OS:  Windows 7
Selenium Version:  3.0.0-beta3
Browser:  Internet Explorer
Browser Version:  2.48.0.0
## Actual Behavior - the following exception:

Exception in thread "main" org.openqa.selenium.WebDriverException: Command not found: GET /session/56680036-a901-4d38-8875-0c239ce16041/log/types
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:57:44 -0700'
System info: host:  ip: '10.6.186.3', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:41578/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 56680036-a901-4d38-8875-0c239ce16041
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:631)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:654)
    at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:33)
    at org.openqa.selenium.remote.RemoteLogs.getAvailableLogTypes(RemoteLogs.java:103)
## Steps to reproduce:

```
System.setProperty("webdriver.ie.driver", "D://DRIVERS//iexplore.exe");
DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
WebDriver driver = new InternetExplorerDriver(capabilities);
driver.get("http://www.example.com");
Logs logs = driver.manage().logs();
logs.getAvailableLogTypes();
```

**Comment by jimevans** [comment]
Unfortunately, the IE driver doesn't support any of the logging API. This feature has never been implemented in the driver itself.
