### ISSUE TITLE
Unable to invoke Edge Browser on Windows from MAC (Selenium GRID in JavaScript)

### ISSUE THREAD

**Issue by smunukuntla** [SeleniumHQ/selenium#2877]
## Meta -
OS:  

Selenium Version:  

Browser:  

## Expected Behavior -
Edge browser should be able to start and redirect to the provided url

## Actual Behavior -
Throwing the below error - 

/usr/local/bin/node /Users/smunukuntla/Documents/Selenium_JavaScript/test/Selenium3_Edge.js
/Users/smunukuntla/Documents/Selenium_JavaScript/node_modules/selenium-webdriver/lib/promise.js:2291
        throw error;
        ^

WebDriverError: The best matching driver provider org.openqa.selenium.opera.OperaDriver can't create a new driver instance for Capabilities [{browserName=MicrosoftEdge, platform=WIN10}]
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'SHIRISHs-MacBook-Pro.local', ip: '172.25.183.18', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_101'
Driver info: driver.version: unknown
    at WebDriverError (/Users/smunukuntla/Documents/Selenium_JavaScript/node_modules/selenium-webdriver/lib/error.js:27:10)
    at Object.checkLegacyResponse (/Users/smunukuntla/Documents/Selenium_JavaScript/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/smunukuntla/Documents/Selenium_JavaScript/node_modules/selenium-webdriver/lib/http.js:398:13)
    at /Users/smunukuntla/Documents/Selenium_JavaScript/node_modules/selenium-webdriver/lib/http.js:330:11
    at process._tickCallback (node.js:369:9)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/smunukuntla/Documents/Selenium_JavaScript/node_modules/selenium-webdriver/lib/webdriver.js:366:24)
    at Builder.build (/Users/smunukuntla/Documents/Selenium_JavaScript/node_modules/selenium-webdriver/index.js:548:24)
    at Object.<anonymous> (/Users/smunukuntla/Documents/Selenium_JavaScript/test/Selenium3_Edge.js:14:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
From: Task: WebDriver.navigate().to(http://www.seleniumhq.org)
    at WebDriver.schedule (/Users/smunukuntla/Documents/Selenium_JavaScript/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Navigation.to (/Users/smunukuntla/Documents/Selenium_JavaScript/node_modules/selenium-webdriver/lib/webdriver.js:1042:25)
    at Object.<anonymous> (/Users/smunukuntla/Documents/Selenium_JavaScript/test/Selenium3_Edge.js:15:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Process finished with exit code 1

**Comment by mach6** [comment]
Will you please try with 3.0.0-beta4? Also, will you please clarify.. What type of host is the `node` running on? It needs to be a Windows host with Edge and Edge driver installed. Also, for completeness, what type of host is the `hub` running on?

**Comment by smunukuntla** [comment]
@mach6 I don't know but magically it worked 👍  I have updated to latest 3.0.0-beta-3 version of javascript node.js bindings. Thanks Simmons
