### ISSUE TITLE
Can't get the screenshot of the current element

### ISSUE THREAD

**Issue by Goosky** [SeleniumHQ/selenium#2898]
# Meta -
OS:  Windows 10

Selenium Version:  2.53.6

Browser:  Chrome

Browser Version:  53.0.2785.116 m (64-bit)

## Expected Behavior -
Gets the screenshot of the current element as a binary data.
## Actual Behavior -
It raise WebDriverException
```python
Traceback (most recent call last):
  File "C:\python2.7\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-73528134d358>", line 1, in <module>
    element.screenshot_as_png
  File "C:\python2.7\lib\site-packages\selenium\webdriver\remote\webelement.py", line 400, in screenshot_as_png
    return base64.b64decode(self.screenshot_as_base64.encode('ascii'))
  File "C:\python2.7\lib\site-packages\selenium\webdriver\remote\webelement.py", line 390, in screenshot_as_base64
    return self._execute(Command.ELEMENT_SCREENSHOT)['value']
  File "C:\python2.7\lib\site-packages\selenium\webdriver\remote\webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "C:\python2.7\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\python2.7\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 163, in check_response
    raise exception_class(value)
WebDriverException: Message: unknown command: session/b29be55e0ac21893f180da11ac203787/screenshot/0.20772185933294707-1
```
## Steps to reproduce -

with python2.7
```python
from selenium import webdriver
driver= webdriver.Chrome()
driver.get("http://www.google.com")
element = driver.find_element_by_id('lst-ib')
print element.screenshot_as_png
```

**Comment by lukeis** [comment]
Please log issues for chromedriver with that project:
https://bugs.chromium.org/p/chromedriver/issues/list

Element screenshots are a new thing introduced in the w3c spec, but not widely implemented. I suggest logging a bug with the chromedriver project.

**Comment by AdaNammaAyyasamy** [comment]
I get the same Issue. @GoverSky were you able to find any solution.

**Comment by GoverSky** [comment]
@AdaNammaAyyasamy Yes,I've got a solution like this:
```pyhton
from selenium import webdriver
from PIL import Image
driver= webdriver.Chrome()
driver.get('https://www.python.org/')
element = driver.find_element_by_class_name('python-logo')
driver.get_screenshot_as_file('screenshot.png')
left = int(element.location['x']) 
top = int(element.location['y']) 
right = int(element.location['x'] + element.size['width']) 
bottom = int(element.location['y'] + element.size['height']) 
print (left, top, right, bottom)
im = Image.open('screenshot.png')
im = im.crop((left, top, right, bottom))
im.save('new_screenshot.png')
```

**Comment by cgoldberg** [comment]
`element.screenshot('/tmp/screenshot.png')`
