### ISSUE TITLE
incorrect 'unexpected response, code=404' when manipulating DOM elements with Safari using ruby selenium-webdriver 3 beta4 

### ISSUE THREAD

**Issue by samnissen** [SeleniumHQ/selenium#2904]
Sites load with Safari, but driver always reports response code 404 when trying to manipulate the site.

``` ruby
w = Watir::Browser.new :safari
 => #<Watir::Browser:0x7f985ddd94f371e6 url="" title="">
w.goto "http://google.com"
 => "http://google.com"
w.text_field(:id => "lst-ib").when_present.set("some data")
Selenium::WebDriver::Error::WebDriverError: unexpected response, code=404, content-type=""
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/remote/http/default.rb:86:in `request'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/remote/bridge.rb:631:in `execute'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/remote/bridge.rb:579:in `element_displayed?'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.0.beta4.0/lib/selenium/webdriver/common/element.rb:191:in `displayed?'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/elements/element.rb:403:in `block in visible?'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/elements/element.rb:621:in `element_call'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/elements/element.rb:403:in `visible?'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/elements/element.rb:425:in `present?'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/wait.rb:136:in `wait_until'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/wait.rb:114:in `block in method_missing'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/wait.rb:41:in `block in until'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/wait.rb:78:in `block in run_with_timer'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/wait/timer.rb:14:in `wait'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/wait.rb:77:in `run_with_timer'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/wait.rb:40:in `until'
    from /Users/samuel.nissen/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.3/lib/watir-webdriver/wait.rb:114:in `method_missing'
    from (irb):5
    from /Users/samuel.nissen/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

macOS Sierra 10.12
ruby 2.3.1
selenium-webdriver 3.0.0.beta4.0
Safari 10.0

**Comment by lmtierney** [comment]
This is actually a safaridriver issue, you cannot currently get the "displayed" state of an element in the new safaridriver which is what is actually happening in your stacktrace (in the when_present before it attempts to send keys)

**Comment by distortia** [comment]
I get the same 404 when I attempt to interact with any element. I can get text from a link but as soon as i try to click it, i get the 404.

```
2.3.0 :007 > element = @browser.link(:href, '/about/')
 => #<Watir::Anchor:0x..fc42fc7aeef7c6c08 located=false selector={:href=>"/about/", :tag_name=>"a"}>
2.3.0 :008 > element.click
Selenium::WebDriver::Error::WebDriverError: unexpected response, code=404, content-type=""
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:86:in `request'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:631:in `execute'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:579:in `element_displayed?'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/element.rb:191:in `displayed?'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/elements/element.rb:386:in `visible?'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/elements/element.rb:410:in `present?'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:46:in `block in until'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:89:in `block in run_with_timer'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait/timer.rb:19:in `block in wait'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait/timer.rb:18:in `loop'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait/timer.rb:18:in `wait'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:88:in `run_with_timer'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:45:in `until'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:125:in `wait_until'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/wait.rb:173:in `wait_until_present'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/elements/element.rb:520:in `wait_for_present'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/elements/element.rb:535:in `wait_for_enabled'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/elements/element.rb:658:in `element_call'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/watir-6.0.2/lib/watir/elements/element.rb:114:in `click'
        from (irb):8
        from /Users/me/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'2.3.0 :009 > element.text
 => "About"
```

It's kinda weird, the element I get back has `located=false`. Not sure if this has anything to do with it.

**Comment by lmtierney** [comment]
This is because Watir calls the same logic of making sure the element is present and displayed? before clicking it. If you look in the stack trace, the 7th one down:

```
from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/element.rb:191:in `displayed?'
```

**Comment by lmtierney** [comment]
If you were to call `element.wd.click` I think you might have a different result. This uses the selenium element click method instead of the Watir wrapped version

**Comment by distortia** [comment]
All I get back from `element.wd.click` is `{}`and it does not perform the click. 

It does however work in chrome using `element.wd.click` and `element.click`

**Comment by distortia** [comment]
You may be onto something @lmtierney with the present and displayed though

**Comment by lmtierney** [comment]
I'm not sure why wd.click wouldn't work unless there's an issue with safaridriver there as well. Both of those stack traces point to the "displayedness" of the element which safaridriver does not currently support (afaik)

**Comment by lmtierney** [comment]
If you instead did `element.wd.displayed?` you should also get the same error

**Comment by distortia** [comment]
Yeah the same error:
```
Selenium::WebDriver::Error::WebDriverError: unexpected response, code=404, content-type=""
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:86:in `request'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:631:in `execute'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:579:in `element_displayed?'
        from /Users/me/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/element.rb:191:in `displayed?'
        from (irb):7
        from /Users/me/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

**Comment by lmtierney** [comment]
I just tried this manually with the displayed method and it is, in fact, not implemented yet with safaridriver:

```
curl localhost:7050/session/93509CEB-844F-4F9A-A5F3-B456B37E9986/element/node-11B4B7A7-297B-4B79-91A3-7FE8D15B8FEC/displayed
curl localhost:7050/session/93509CEB-844F-4F9A-A5F3-B456B37E9986/element/node-11B4B7A7-297B-4B79-91A3-7FE8D15B8FEC/location
{"status":0,"sessionId":"93509CEB-844F-4F9A-A5F3-B456B37E9986","value":{"x":181,"y":545}}
```

**Comment by lmtierney** [comment]
I just tried this with the lastest Safari Technical Preview (from Nov 16) and it appears to be working in the safaridriver bundled with it

```
curl localhost:7050/session/92AEDDD6-231F-4113-88A3-10E2F06DECBD/element/node-EB9A6AAB-6D0E-4711-B865-3260609468F5/displayed
{"status":0,"sessionId":"92AEDDD6-231F-4113-88A3-10E2F06DECBD","value":true}
```

If you download the latest Safari Technology Preview, you should be able to use it with Watir via:

```
Selenium::WebDriver::Safari.driver_path = "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver"
browser = Watir::Browser.new :safari
```

Or straight selenium with:

```
Selenium::WebDriver::Safari.driver_path = "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver"
driver = Selenium::WebDriver.for :safari
```

**Comment by distortia** [comment]
Thanks dude, ill give this a try.

**Comment by distortia** [comment]
Well, I don't get the 404 anymore, but nothing happens when I `element.click`, or `element.wd.click`. 

```
element.click
 => nil
```
```
element.wd.click
 => {}
```

**Comment by titusfortner** [comment]
Can you run your example with `$DEBUG = true` and paste in the response?

Also of note, for anyone else finding this issue, pointing to Technical Preview only works on MacOS, not merely El Capitan with Safari 10.

**Comment by distortia** [comment]
`element.click` : 
```
-> GET session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/element/node-EB6F62F9-6E75-41F4-B308-B05311406357/enabled
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":true}
-> GET session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/window_handle
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":"page-4D7D9042-EE81-4BFE-A5F8-9861D9205320"}
-> GET session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/window_handles
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":["page-4D7D9042-EE81-4BFE-A5F8-9861D9205320"]}
-> POST session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/frame
   >>> http://127.0.0.1:7050/session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/frame | {"id":null}
     > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"11"}
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":{}}
-> GET session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/element/node-EB6F62F9-6E75-41F4-B308-B05311406357/enabled
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":true}
-> GET session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/element/node-EB6F62F9-6E75-41F4-B308-B05311406357/displayed
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":true}
-> GET session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/element/node-EB6F62F9-6E75-41F4-B308-B05311406357/enabled
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":true}
-> GET session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/element/node-EB6F62F9-6E75-41F4-B308-B05311406357/enabled
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":true}
-> POST session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/element/node-EB6F62F9-6E75-41F4-B308-B05311406357/click
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":{}}
 => nil
```

`element.wd.click` : 
```
GET session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/element/node-EB6F62F9-6E75-41F4-B308-B05311406357/enabled
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":true}
-> POST session/1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A/element/node-EB6F62F9-6E75-41F4-B308-B05311406357/click
<- {"status":0,"sessionId":"1EB0F0A5-E847-4CF4-8241-CFD57FE2ED9A","value":{}}
 => {}
```

**Comment by lmtierney** [comment]
That all looks good. I just tried this with curl as well and it didn't follow the link either. Chalking this up to another safaridriver issue

**Comment by titusfortner** [comment]
Yup, safaridriver issue. Please file a bug with Apple. Thanks.

**Comment by distortia** [comment]
I submitted a bug report.

Ill continue to update this issue for others to see.

**Comment by samnissen** [comment]
Thanks, all. @distortia: Can you please share the issue ID so we can follow?

**Comment by distortia** [comment]
@samnissen Here you go, 29346515

**Comment by distortia** [comment]
They marked my bug as a duplicate. Here is the original one: 28593580.

**Comment by lmtierney** [comment]
Where are these bugs? Do you have a link?

**Comment by distortia** [comment]
Apple just gave me the parent bug report number. As far as i know, apple
doesnt let you look up other bug reports. As seen here,
http://stackoverflow.com/questions/144873/can-i-browse-other-peoples-apple-bug-reports.

**Comment by lmtierney** [comment]
So they gave you the number of the original bug report, which you then can't see? Or because they marked it duplicate, at least you can see it?

**Comment by distortia** [comment]
I cant view the original. All I get is `Duplicate of 28593580 (Open)` on my report. Maybe ill get updates as that one goes on. We will see.

**Comment by burg** [comment]
Hi folks, sorry about the lack of visibility on Radar.

I'm looking into this bug, but I'm not able to readily reproduce it. If someone else can, I'd like to collect some diagnostic logs. Please send me an email (bburg at apple) and I'll follow up with you there.

**Comment by samnissen** [comment]
@burg I cannot reproduce now either. However, I haven't kept my dev environment stable since then. I can easily access the relevant selenium tools, but can't roll back my Safari (10.0 -> 10.1) and macOS (10.12.0 -> 10.12.2) versions so simply.

**Comment by Fjan** [comment]
For me, this problem went away in the Safari Tech Preview
