### ISSUE TITLE
Cannot create new remote session, connection refused!

### ISSUE THREAD

**Issue by sophiecdd** [SeleniumHQ/selenium#2911]
## Meta -
OS:  Sierra

Selenium Version:  3.0.0-beta4

Browser:  safari 10

## Expected Behavior -
expect selenium server starts fine and work fine with apple's safari driver

## Actual Behavior -
throw the following error
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:29:23 -0700'
System info: host: 'Sophies-MacBook-Pro.local', ip: '9.24.158.132', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_101'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
	... 9 more
Caused by: org.openqa.selenium.WebDriverException: The driver server has unexpectedly died!

selenium was started manually on mac, then start a test case (using intern framework), loading a login page to do a login.

It failed because of unknown reason, and in selenium log, it shows the connection was refused.

by checking the processes, the selenium server and safari driver are both active:
 1471 ttys001    0:03.97 /usr/bin/java -jar dev/selenium/selenium-server-standalone-3.0.0-beta4.jar
 1474 ttys001    0:00.01 /usr/bin/safaridriver --port 37924

Anybody is seeing similar issue or know of how to solve this problem please let know.

**Comment by sophiecdd** [comment]
It just started working after upgrade safari technology preview to release 15. I am pretty sure it is not the problem but it just worked.
