### ISSUE TITLE
Simple javascript webdriver example fails with chrome 54

### ISSUE THREAD

**Issue by krausest** [SeleniumHQ/selenium#2924]
## Meta -
OS:  
OSX
Selenium Version:  
tested with 3.0.0-beta-3 and 2.53.3
Browser:  
Chrome

Browser Version:  
 54.0.2840.59 

The simple javascript example from https://www.npmjs.com/package/selenium-webdriver stopped working with Chrome 54.

The browser windows opens, loads the url, but doesn't perform any further actions.

## Steps to reproduce -
package.json:
```
{
  "name": "webdriver-bug",
  "version": "1.0.0",
  "description": "example for issue report",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "BSD-2-Clause",
  "dependencies": {
    "chromedriver": "^2.24.1",
    "selenium-webdriver": "^3.0.0-beta-3"
  }
}
```
example.js:
```
var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .setChromeOptions()
    .build();

driver.get('http://www.google.com/ncr');
driver.findElement(By.name('q')).sendKeys('webdriver');
driver.findElement(By.name('btnG')).click();
driver.wait(until.titleIs('webdriver - Google Search'), 1000);
driver.quit();
```
To run the test
````
export PATH=node_modules/chromedriver/lib/chromedriver/:$PATH
node example.js
```
The java bindings work for chromedriver 2.24.1 and selenium 2.53.1, thus I've filed the bug here.

**Comment by ddavison** [comment]
have you tried the stable 3.0.0 release?  you appear to be using the beta4 release

**Comment by krausest** [comment]
Where do I get the 3.0 final version from for the javascript bindings? On https://www.npmjs.com/package/selenium-webdriver is says 3.0.0-beta-3 is current.

**Comment by krausest** [comment]
After a pretty long time I got an exception:
```
/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/promise.js:654
    throw error;
    ^

TimeoutError: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -0.003
  (Session info: chrome=54.0.2840.59)
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.1 x86_64)
    at WebDriverError (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/error.js:27:5)
    at TimeoutError (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/error.js:342:5)
    at Object.checkLegacyResponse (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/promise.js:639:7
From: Task: WebDriver.navigate().to(http://www.google.com/ncr)
    at Driver.schedule (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
    at Navigation.to (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/webdriver.js:1027:25)
    at Driver.get (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/node_modules/selenium-webdriver/lib/webdriver.js:795:28)
    at Object.<anonymous> (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-bug/webdriverbug.js:10:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

**Comment by jleyba** [comment]
3.0 final for js won't be out for another week or so. I'm waiting for Node
to bump their LTS. I'll look at this bug today

**Comment by lukeis** [comment]
that's a chromedriver bug -
https://bugs.chromium.org/p/chromedriver/issues/detail?id=817

it was fixed for other scenarios, but still pokes itself up in different ways.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=402

**Comment by krausest** [comment]
Just as an update:
* The same test with Chrome 54, chromedriver 2.24.1, selenium-webdriver 2.53.1 works on Linux and Windows
* The problems happens on OSX for both Javascript and Java bindings. My Java test driver runs fine so far within the IntelliJ IDE, but fails every time when invoked via mvn exec  (sounds very strange - I know)
I'll open a new bug report for the chromedriver project since it used to work fine in my project for chrome >= 49 and only fails reproducibly since the update to chrome 54 (the bugs you referenced seem to have a sporadic behaviour in common, which is not the case here).

**Comment by jessyZu** [comment]
+1 :chromedriver 2.26  chrome 55.0.2883.87
