### ISSUE TITLE
Unable to find element with css selector  if I set phantomjs custom headers

### ISSUE THREAD

**Issue by eromoe** [SeleniumHQ/selenium#2940]
## Meta -
OS:   win 8, ubuntu 14.04
Selenium Version:  2.53.6
Browser:  phantomjs 2.1.1

My code to set custom headers for phamtomjs
```
from selenium import webdriver
from selenium.webdriver import DesiredCapabilities

headers = { 'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Encoding':'gzip, deflate',
    'Accept-Language':'zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0',
    'Connection': 'keep-alive'
}

desired_capabilities = DesiredCapabilities.PHANTOMJS.copy()

for key, value in headers.iteritems():
    desired_capabilities['phantomjs.page.customHeaders.{}'.format(key)] = value

desired_capabilities['phantomjs.page.settings.userAgent'] = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'

driver = webdriver.PhantomJS(service_args=service_args, desired_capabilities=desired_capabilities)

url = 'https://cn.bing.com'

driver.get(url)

title = driver.find_element_by_css_selector('title')
print title.get_attribute('innerHTML')
```
No matter which site choosed, all get
```
Traceback (most recent call last):
  File "main.py", line 142, in <module>
    title = driver.find_element_by_css_selector('title')
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in find_element_by_css_selector

    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: {"errorMessage":"Unable to find element with css selector 't
itle'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Leng
th":"96","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:54171","User-Agent":"Python-urllib/2.7"},"htt
pVersion":"1.1","method":"POST","post":"{\"using\": \"css selector\", \"sessionId\": \"4c2c8d90-9433-11e6-bf0b-871d1231e
9ec\", \"value\": \"title\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","pat
h":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":
"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/4c2c8d90-9433-11e6-bf0b-871d1231e9ec/
element"}}
Screenshot: available via screen
```

All `driver.find_element_XXX` method failed, and I found driver.page_source is in a mess, looks like wrong decoding content or something similar.

remove `desired_capabilities` is fine, but I need custom header to crawl some site.

**Comment by lukeis** [comment]
You should be using  `driver.title` instead to get the title of the page. Also any issues with phantomjs driver should be logged against the ghostdriver repo:
https://github.com/detro/ghostdriver

**Comment by eromoe** [comment]
I just write that css select for example, because all find method failed, not matter which element. I would repost one to ghostdriver.
