### ISSUE TITLE
window().maximize() throws unknown command for firefox geckodriver

### ISSUE THREAD

**Issue by alterhu2016** [SeleniumHQ/selenium#2960]
## Meta -
OS:  Window 7

Selenium Version:  3.0.0 beta4

Browser:  Firefox 49.0.1 

Browser Version:  49.0.1

## Expected Behavior -
maximize() should work for firefox browser.
## Actual Behavior -

				WARNING: Exception thrown
				org.openqa.selenium.UnsupportedCommandException: POST /session/572a2c7b-5d3d-4250-8a00-3b3529006bb5/window/				current/maximize did not match a known command (WARNING: The server did not provide any stacktrace 				information)
				Command duration or timeout: 29 milliseconds
				Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:57 -0700'
				System info: host: 'PAS-VXI-142', ip: '10.50.14.142', os.name: 'Windows 7', os.arch: 'amd64', os.version: 				'6.1', java.version: '1.8.0_101'
				Driver info: org.openqa.selenium.firefox.FirefoxDriver
				Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, 				firefoxOptions={args=[], profile=UEsDBBQACAgIACSTUkkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc61Xy27jNhTd9ysCr6ZAxEkmnc10l				cYpUCCYFOMGszFAUOSVxZgiWT6suF/fSz1sJ5YlZ9qVTfF1H+ecexk9OGodFB9muTM1johnBTT/pV6RiqmaOSCgWa5AzC4vCqY8/PzrT3G/U7C				Aa6xxIW0pgalQtmOCizaST+zXEGrj1oTFYCoWJM90UFWGw5IEF30AkUUnPe6eWba1TGUshBIcrCROOsJNdXn8pTIacPG6GWh4CeADC9ANuWKz1				2b0AShBWXC31nqiYYP//BqDsoG/zFz6dTKCWaskR0uN/mh4gJD54IChEQcTLxlehCd7D+LNxD/SnprEqcsqqiAtc6Fd+sZML1fa6CZYyqykJta				Zly2ahaE6EdgyBEtsKX25zdK0Zd5nCvQqlLjv0+fPw4FAlwT+CAiATorfpfPhFpPMFQxeJ0yFgHmhvHSmAuq5kzZQFzUNskpbbq6GLxKm1sowQ				XBu3v2fSzd4Sb8nsNwTxKZ+1HfKeBiGlgeOyAlbdKJgGFaKmfVGM0U5uJByuQCF3l3c9thjSm1PAGNnZsU0WyWqlKb+XoJeIP4T9odtwPxUNvh				kMa2MYGqCTbAJxihPwDnjuNHeqEMCHYekQ4SDCqoc3KIZ+uHTdyxH6CHefDDIbsRhxIQVaCjljvlyfK+Sek2MBU0TqRxGM6Ho3ZpQJDx9i3r4s				hpy4STSjzLOAXEUdacFTer8KDiE9FaxLYj766vFV4NpTfj4ZXgxfhKP+rvUmF9/fUUkXmSevj00TM9NDF9yxfR6dgz21iGKkKHPHoOR7JRt6I9				te7ESw41rSV3KAAqFCg/4O0p3CgkJBmsZSEfjHnXoXMLCaAAUCp1D5o1DzSfcRktKpKvFs2kNiifqRpdSOpviQWEUCsQDenIMgAQN3UCMRCuS7				mrMQ7F9wiXvLiPRpvvuR33pmV5IBfiPoCRLHqhxEkWSWoMSux3HtYYaOUo650dS/8rQ9mSSPi5iXsmGV382H28b5J5XNgePGfV4R+UuiymDuPK				Exu5Ji27WDdiPk2aKAtdBxlLxQ6iamuZb2mnnaIkZqt3NAVkqTxKGObFLGve2g+q4rzvoKeZDWyJmd1+Wy2SDt4zDV6iXy7vIY6OErLIKlsu+p				vjZFEZH6dLzEcmLUhvclrTS3qz/NLV29Ojev/unh1tyQ9geOMdBe2Yb1tbW0arwFh49ycexfWy3g+em/I9e0lInHX9eq4fq7g1fQxhffpCgBLB				5q3wLjjhOgLq+OlUz2lOpRkRugGIXp8NEQTzoJx6RJZP25Artb0T8rMR6r6hBy5wUQHMo2UaahN7rU+WZOV52qJyiREVaPhMRK3sWJnY0Ev+VQ				qgUZ3HnFcD7QIxrQi/kbxX8ZhhSFxpWWGHQklZ9Lqblp9/aVtasV7/				0TIgTcOnWnlD2rhGe7oAPuhzf9GD7LgcrQIThHvgg6IkWw0YcyIRp25KmX/1D37Ut5ckWvusvaFMsBGZAr2hK/UTdvfg/				WmyPjy9FeAl8PW+P+62deX8DQ5gQMvnNJsr54MP3Rx+8+CRbpY9d3z5awA/UpPH4DosJxieXKsVTy1UZ1ImW5WBrf+OP1IKdJJEKXwINnGfp9e				DgTYz2zWt6bCA98Mkw0b3upUwVPtq2j9v3lf8CUEsHCJqI+tHQBAAAehAAAFBLAQIUABQACAgIACSTUkmaiPrR0AQAAHoQAAAHAAAAAAAAAAAA				AAAAAAAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAAUFAAAAAA==}, appBuildId=20160922113459, version=, platform=XP, 				proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=11040, browserVersion=49.0.1, 				platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, 				takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, device=desktop, 				firefox_profile=UEsDBBQACAgIACOTUkkAAAAAAAAAA...}]
				Session ID: 572a2c7b-5d3d-4250-8a00-3b3529006bb5
					at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
					at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
					at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
					at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
					at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
					at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
					at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:780)
					at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:799)
					at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(				RemoteWebDriver.java:1030)
					at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWindow.maximize(				EventFiringWebDriver.java:640)
					at org.openqa.selenium.remote.server.handler.MaximizeWindow.call(MaximizeWindow.java:30)
					at org.openqa.selenium.remote.server.handler.MaximizeWindow.call(MaximizeWindow.java:22)
					at java.util.concurrent.FutureTask.run(FutureTask.java:266)
					at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
					at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
					at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
					at java.lang.Thread.run(Thread.java:745)

				Oct 18, 2016 6:25:40 PM org.openqa.selenium.remote.server.rest.ResultConfig handle
				WARNING: Exception: POST /session/572a2c7b-5d3d-4250-8a00-3b3529006bb5/window/current/maximize did not match 				a known command (WARNING: The server did not provide any stacktrace information)
				Command duration or timeout: 29 milliseconds
				Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:57 -0700'
				System info: host: 'PAS-VXI-142', ip: '10.50.14.142', os.name: 'Windows 7', os.arch: 'amd64', os.version: 				'6.1', java.version: '1.8.0_101'
				Driver info: org.openqa.selenium.firefox.FirefoxDriver
				Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, 				firefoxOptions={args=[], profile=UEsDBBQACAgIACSTUkkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc61Xy27jNhTd9ysCr6ZAxEkmnc10l				cYpUCCYFOMGszFAUOSVxZgiWT6suF/fSz1sJ5YlZ9qVTfF1H+ecexk9OGodFB9muTM1johnBTT/pV6RiqmaOSCgWa5AzC4vCqY8/PzrT3G/U7C				Aa6xxIW0pgalQtmOCizaST+zXEGrj1oTFYCoWJM90UFWGw5IEF30AkUUnPe6eWba1TGUshBIcrCROOsJNdXn8pTIacPG6GWh4CeADC9ANuWKz1				2b0AShBWXC31nqiYYP//BqDsoG/zFz6dTKCWaskR0uN/mh4gJD54IChEQcTLxlehCd7D+LNxD/SnprEqcsqqiAtc6Fd+sZML1fa6CZYyqykJta				Zly2ahaE6EdgyBEtsKX25zdK0Zd5nCvQqlLjv0+fPw4FAlwT+CAiATorfpfPhFpPMFQxeJ0yFgHmhvHSmAuq5kzZQFzUNskpbbq6GLxKm1sowQ				XBu3v2fSzd4Sb8nsNwTxKZ+1HfKeBiGlgeOyAlbdKJgGFaKmfVGM0U5uJByuQCF3l3c9thjSm1PAGNnZsU0WyWqlKb+XoJeIP4T9odtwPxUNvh				kMa2MYGqCTbAJxihPwDnjuNHeqEMCHYekQ4SDCqoc3KIZ+uHTdyxH6CHefDDIbsRhxIQVaCjljvlyfK+Sek2MBU0TqRxGM6Ho3ZpQJDx9i3r4s				hpy4STSjzLOAXEUdacFTer8KDiE9FaxLYj766vFV4NpTfj4ZXgxfhKP+rvUmF9/fUUkXmSevj00TM9NDF9yxfR6dgz21iGKkKHPHoOR7JRt6I9				te7ESw41rSV3KAAqFCg/4O0p3CgkJBmsZSEfjHnXoXMLCaAAUCp1D5o1DzSfcRktKpKvFs2kNiifqRpdSOpviQWEUCsQDenIMgAQN3UCMRCuS7				mrMQ7F9wiXvLiPRpvvuR33pmV5IBfiPoCRLHqhxEkWSWoMSux3HtYYaOUo650dS/8rQ9mSSPi5iXsmGV382H28b5J5XNgePGfV4R+UuiymDuPK				Exu5Ji27WDdiPk2aKAtdBxlLxQ6iamuZb2mnnaIkZqt3NAVkqTxKGObFLGve2g+q4rzvoKeZDWyJmd1+Wy2SDt4zDV6iXy7vIY6OErLIKlsu+p				vjZFEZH6dLzEcmLUhvclrTS3qz/NLV29Ojev/unh1tyQ9geOMdBe2Yb1tbW0arwFh49ycexfWy3g+em/I9e0lInHX9eq4fq7g1fQxhffpCgBLB				5q3wLjjhOgLq+OlUz2lOpRkRugGIXp8NEQTzoJx6RJZP25Artb0T8rMR6r6hBy5wUQHMo2UaahN7rU+WZOV52qJyiREVaPhMRK3sWJnY0Ev+VQ				qgUZ3HnFcD7QIxrQi/kbxX8ZhhSFxpWWGHQklZ9Lqblp9/aVtasV7/				0TIgTcOnWnlD2rhGe7oAPuhzf9GD7LgcrQIThHvgg6IkWw0YcyIRp25KmX/1D37Ut5ckWvusvaFMsBGZAr2hK/UTdvfg/				WmyPjy9FeAl8PW+P+62deX8DQ5gQMvnNJsr54MP3Rx+8+CRbpY9d3z5awA/UpPH4DosJxieXKsVTy1UZ1ImW5WBrf+OP1IKdJJEKXwINnGfp9e				DgTYz2zWt6bCA98Mkw0b3upUwVPtq2j9v3lf8CUEsHCJqI+tHQBAAAehAAAFBLAQIUABQACAgIACSTUkmaiPrR0AQAAHoQAAAHAAAAAAAAAAAA				AAAAAAAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAAUFAAAAAA==}, appBuildId=20160922113459, version=, platform=XP, 				proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=11040, browserVersion=49.0.1, 				platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, 				takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, device=desktop, 				firefox_profile=UEsDBBQACAgIACOTUkkAAAAAAAAAA...}]
				Session ID: 572a2c7b-5d3d-4250-8a00-3b3529006bb5				

## Steps to reproduce -
1. Start selenium server ,POST maximize() command for firefox 49.0.1 using Geckodriver ,like below:

				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 >> "POST /session/572a2c7b-5d3d-4250-8a00-3b3529006bb5/				window/current/maximize HTTP/1.1[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 >> "Content-Type: application/json; 				charset=utf-8[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 >> "Content-Length: 45[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 >> "Host: localhost:42969[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 >> "Connection: Keep-Alive[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 >> "User-Agent: Apache-HttpClient/4.5.2 (				Java/1.8.0_101)[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 >> "Accept-Encoding: gzip,deflate[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 >> "[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:86 - http-outgoing-11 >> "{"windowHandle":"current","handle":"current"}"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 << "HTTP/1.1 404 Not Found[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 << "Connection: close[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 << "Content-Length: 144[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 << "Content-Type: application/json[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 << "Date: Wed, 19 Oct 2016 01:25:40 GMT[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:72 - http-outgoing-11 << "[\r][\n]"
				2016-10-18 18:25:40 DEBUG wire:86 - http-outgoing-11 << "{"error":"unknown command","message":"POST /				session/572a2c7b-5d3d-4250-8a00-3b3529006bb5/window/current/maximize did not match a known command"}"
				2016-10-18 18:25:40 DEBUG headers:124 - http-outgoing-11 << HTTP/1.1 404 Not Found		

I had raised a defect to geckodriver team and from their side confirmed that the maxinum command url should be `/session/{session id}/window/maximize`,But from our [JsonHttpCommandCodec](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/http/JsonHttpCommandCodec.java) i saw we use command is `   defineCommand(MAXIMIZE_CURRENT_WINDOW, post("/session/:sessionId/window/:windowHandle/maximize"));`	
 I think this's why geckodriver is failed for firefox using this command .please advise how to fix this issue  ,thanks .	
See geckodriver issue I mentioned here: https://github.com/mozilla/geckodriver/issues/276

**Comment by lukeis** [comment]
Can you show the selenium code / setup that you are using to reproduce this?

Using java directly goes through the W3CHttpCommandCodec rather than the JsonHttpCommandCodec. And works for me.

**Comment by lukeis** [comment]
also I just used a standalone server and python

    from selenium import webdriver as w
    d = w.Remote(desired_capabilities={'browserName':'firefox'})
    d.maximize_window()

and works successfully.

Please provide a way to reproduce, when you do we can reopen the issue.

**Comment by alterhu2016** [comment]
It's very simple if you just use Selenium 3.0.0 beta4 and geckodriver 0.11.1

        System.setProperty("webdriver.gecko.driver","C:\\geckodriver.exe");
		FirefoxDriver driver=new FirefoxDriver();
		
		driver.manage().window().maximize();
		
		driver.get("https://www.google.com");

**Comment by lukeis** [comment]
please upgrade to 3.0.0 or 3.0.1 then

**Comment by alterhu2016** [comment]
thanks @lukeis  ,I had found the root cause is from I rewrite the back-end selenium code but not notice that in new selenium 3.0.0 we use two implements ,one is from old selnium 2 implement using `JsonHttpCommandCodec` when the `createSession` return JSONString have `status` node , It will use the `JsonHttpCommandCodec` ,or else it will use `W3CHttpCommandCodec` .
Thanks very much ,i had rewrite the code ,we can close it .
