### ISSUE TITLE
Ruby, remote chrome: No implicit conversion of Symbol into Integer in W3CBridge#edge_check 

### ISSUE THREAD

**Issue by shemusok** [SeleniumHQ/selenium#2965]
## Meta -
OS:  Ubuntu 16.04

Selenium Version: 3.0.0 

Browser:  Remote Chrome from ruby bindings

Browser Version:  Unrelevant

## Expected Behavior - 
``` ruby
Selenium::WebDriver.for(:remote, url: "http://selenium_hub:4444/wd/hub", desired_capabilities: :chrome)
```

must create driver

## Actual Behavior -
```
/var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/remote/w3c_bridge.rb:102:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/remote/w3c_bridge.rb:102:in `edge_check'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/remote/w3c_bridge.rb:66:in `initialize'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/driver.rb:55:in `new'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/driver.rb:55:in `for'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver.rb:82:in `for'
	from ./test.rb:5:in `<main>'
```

at lib/selenium/webdriver/remote/w3c_bridge.rb:102:
```ruby
return unless caps && caps[:browser_name] && caps[:browser_name] == 'MicrosoftEdge'
```
**caps** is somehow equal to :chrome symbol

## Steps to reproduce -
``` ruby
#/usr/bin/env ruby
require 'selenium-webdriver'
Selenium::WebDriver.for(:remote, url: "http://selenium_hub:4444/wd/hub", desired_capabilities: :chrome)
```

**Comment by titusfortner** [comment]
The `desired_capabilities` parameter takes a Capabilities object not a symbol.
You need:
```ruby
capabilities = Selenium::WebDriver::Remote::Capabilities.firefox
driver = Selenium::WebDriver.for(:remote, url: "http://selenium_hub:4444/wd/hub", desired_capabilities: capabilities)
```
