### ISSUE TITLE
Gecko driver does not work with FF48.0.1

### ISSUE THREAD

**Issue by dsb84** [SeleniumHQ/selenium#3000]
Gecko driver version: 0.11.1
Selenium version: 3.0.1
FF version:48.0.1
______________________________________________________________________________________________________
Firefox does not open when I try this code:

String firefoxDriverPath;
firefoxDriverPath = System.getProperty("firefoxDriverPath","/fakepath/Drivers/geckodriver");
        File firefoxFile = new File (firefoxDriverPath);
        System.setProperty("webdriver.gecko.driver", firefoxFile.getAbsolutePath());
        WebDriver driver = new FirefoxDriver();
        driver.get("https://www.google.com/");
        driver.quit();

_____________________________________________________________________________________________________
Exception
_____________________________________________________________________________________________________
1477332127681	geckodriver	INFO	Listening on 127.0.0.1:25707
Oct 24, 2016 2:02:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Oct 24, 2016 2:02:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol.
Oct 24, 2016 2:02:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@59e5ddf, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@59e5ddf, version=, platform=ANY}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '350cf60', time: '2016-10-13 10:48:57 -0700'
System info: host: 'brmac0017.bris.cdi.com', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
