### ISSUE TITLE
Selenium Server Standalone 3.0.1: Exception in thread "main" com.beust.jcommander.ParameterException: no main parameter was defined

### ISSUE THREAD

**Issue by Ser-Gius** [SeleniumHQ/selenium#3009]
## Meta -
OS:  MacOS 10.12
Selenium Version: selenium-server-standalone-3.0.1.jar
Browser:  NA

## Expected Behavior -
Launch hub for selenium grid for parallel execution in Appium

## Actual Behavior -
```
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter 'http://127.0.0.1:4444/grid/console/' but no main parameter was defined
	at com.beust.jcommander.JCommander.getMainParameter(JCommander.java:914)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:759)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
	at org.openqa.grid.selenium.GridLauncherV3$2.setConfiguration(GridLauncherV3.java:236)
	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:147)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:73)

```

## Steps to reproduce -
executing following command in terminal:

`java -jar ~/Downloads/selenium-server-standalone-3.0.1.jar -role hub http://127.0.0.1:4444/grid/console/`

**Comment by lukeis** [comment]
it's just `java -jar ~/Downloads/selenium-server-standalone-3.0.1.jar -role hub`

the exception is because you are putting "http://127.0.0.1:4444/grid/console/" on the command line... that's not a command line parameter of any kind that grid knows what to do with.

**Comment by skullz03** [comment]
java -jar selenium-server-standalone-3.11.0.jar –role webdriver –hub http://<ip>:4444/grid/register –port 5555
