### ISSUE TITLE
(Java) Safari UnsupportedCommandException isDisplayed

### ISSUE THREAD

**Issue by williamrussellajb** [SeleniumHQ/selenium#3029]
## Meta -
OS:  
OSX Sierra
Selenium Version:  
3.0.1 - Java Client
Browser:  
Safari 10.0

Browser Version:  
Version 10.0 (12602.1.50.0.10)

## Expected Behavior 
element.isDisplayed should be supported for Safari

## Actual Behavior -
```
org.openqa.selenium.UnsupportedCommandException: Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host ', ip: '10.3.21.48', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12602.1.50, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 8D02DFC3-E37E-4626-B84B-B3DAAF040AC2
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:274)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:315)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy16.isDisplayed(Unknown Source)
	at org.openqa.selenium.WebElement$isDisplayed.call(Unknown Source)
```

## Steps to reproduce -
```
@FindBy(className = "someClass")
private WebElement someElement;

public WebElement isSomeElementDisplayed(){
         someElement.isDisplayed();
}


@Test 
public void isElementDisplayedTest(){
    MyPage page = new MyPage(driver);
   page.isSomeElementDisplayed();
}
```
This code is throwing the UnsupportedCommandException

*NOTE*: this works fine with Firefox, Chrome.

**Comment by lukeis** [comment]
Please log Safari driver issues with Apple.

https://bugreport.apple.com/

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by lukeis** [comment]
safaridriver is new and still being worked on actively, not all commands are supported yet :)

**Comment by sagar-navtech** [comment]
**#System Configuration -**
caps.setCapability("browser", "Safari");
caps.setCapability("browser_version", "10.0");
caps.setCapability("os", "OS X");
caps.setCapability("os_version", "Sierra");
caps.setCapability("browserstack.debug", "true");
caps.setCapability("resolution", "1024x768

JAVA 1.8
Selenium 2.47.1

**# Expected Behavior**

WebElement.isDisplayed() should return true or false


**# Actual Behavior -**

Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'mac-185-44-128-250.browserstack.com', ip: '185.44.128.250', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_51'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12602.1.50, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Command duration or timeout: 275 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'xxxxxxxxxx', ip: 'xxx.xxx.xx.xx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12602.1.50, cleanSession=true, platform=MAC, nativeEvents=true, webdriver.remote.sessionid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:273)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:314)
	at com.retrotax.exp_testcases.IndependentTestBS.main(TestClass2.java:53)
Caused by: org.openqa.selenium.UnsupportedCommandException: Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'mac-185-44-128-250.browserstack.com', ip: 'xxx.xx.xxx.xxx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_51'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12602.1.50, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: xxxxxxxxxxxx
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'xxxxxxxx', ip: 'xxxx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_112'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:274)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:315)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:331)
	at com.sun.proxy.$Proxy5.isDisplayed(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.isDisplayed(EventFiringWebDriver.java:385)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy6.isDisplayed(Unknown Source)
	at org.openqa.selenium.remote.server.handler.GetElementDisplayed.call(GetElementDisplayed.java:32)
	at org.openqa.selenium.remote.server.handler.GetElementDisplayed.call(GetElementDisplayed.java:23)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


**# Steps to reproduce -**

public class POMClass
{
  WebDriver driver;
  
  public POMClass(WebDriver driver)
  {
      this.driver = driver;
  }
   By firstNameTextBox = By.id("firstname");	
  
  public WebElement getFirstName()
  {
	return driver.findElement(firstNameTextBox);
  }
}

@Test 
public void expandedOrNot()
{
   WebDriver driver = new FirefoxDriver();
   POMClass obj = POMClass(driver);
   Assert.assertTrue(obj.getFirstName().isDisplayed() == false);
}


Instead of returning TRUE or FALSE, it is returning Exception.

**Comment by sagar-navtech** [comment]
I'm facing this issue only with Safari 10 and not with Safari 5.1, 6.0, 6.2, 7.1, 8.0. 9.1

**Comment by NinoSkopac** [comment]
Same issue here with Safari 10/Sierra/Browserstack.

```php
if (method_exists($link, 'isDisplayed') && $link->isDisplayed())
    $link->click();
```

```
Facebook\WebDriver\Exception\UnknownCommandException: Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'mac-46-249-62-72.browserstack.com', ip: '46.249.62.72', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_51'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12602.1.50, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 4F3F623B-35E4-409B-8B78-FE412F93FE4B
```

Works fine on Safari 9.1 .

**Comment by titusfortner** [comment]
Safari 10 uses a new safaridriver that is written by Apple. It does not yet implement displayed command. If you are using macos Sierra, you can download the safari technology preview, and set your tests to use the safaridriver that comes with it. That has implemented displayed commands. Unfortunately the current tech preview broke safaridriver, so you need to wait for next release regardless.

**Comment by ankitsingh7392** [comment]
Try This 
from selenium import  webdriver

def is_Displayed(class_name):
    ele=driver.execute_script("return document.getElementsByClassName('"+class_name+"')[0].style.visibility = 'visible';")
    if ele=="visible":
        return True
    else:
        return False

def test_check_element():
    global driver
    driver=webdriver.Safari()//e.g Firefox() , Chrome()
    driver.maximize_window()
    driver.implicitly_wait(30)
    driver.get("url")
    submitBtn=driver.find_element_by_xpath("//button[@title='Submit']").get_attribute("class")


    if is_Displayed(submitBtn)== True:
        print "Displayed "
    else:
        print "Not Displayed"
