### ISSUE TITLE
Chromedriver creation throwing http.client.BadStatusLine: ''

### ISSUE THREAD

**Issue by BrydenR** [SeleniumHQ/selenium#3036]
## Meta -
OS:  OSX
Selenium Version:  3.0.1
Browser:  chromedriver (2.24.1) using Google Chrome

Browser Version:  54.0.2840.71 (64-bit I think)

## Steps to reproduce - 
Code:
Bash:
```
source venv/bin/activate
python
```
python
```
from selenium import webdriver
driver = pythonscripts.md()
```
python pythonscripts.py file
```
def md():
    return webdriver.Chrome("./venv/selenium/webdriver/chromedriver")
```

## Expected Behavior - 
Creates a new chromedriver instance, and stores it to variable `driver`. This was what it was doing last time I used it on October 24, 2016.
## Actual Behavior -
Creates new chromedriver instance, and throws `http.client.BadStatusLine: ''` error. `driver` is not defined.

I also tried changing pythonscripts.py's md() method to:
```
def md():
    try:
         return webdriver.Chrome("./venv/selenium/webdriver/chromedriver")
     except Exception:
         return webdriver.Chrome("./venv/selenium/webdriver/chromedriver")
```

This creates two new chromedriver windows, throws two `http.client.BadStatusLine: ''` errors, and `driver` is still not defined.

### Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brydenr/server_scripts/cad_tests/pythonscripts.py", line 68, in md
    return webdriver.Chrome("./venv/selenium/webdriver/chromedriver")
  File "/Users/brydenr/server_scripts/venv/lib/python3.4/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/brydenr/server_scripts/venv/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Users/brydenr/server_scripts/venv/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Users/brydenr/server_scripts/venv/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/brydenr/server_scripts/venv/lib/python3.4/site-packages/selenium/webdriver/remote/remote_connection.py", line 407, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/brydenr/server_scripts/venv/lib/python3.4/site-packages/selenium/webdriver/remote/remote_connection.py", line 439, in _request
    resp = self._conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''
```

**Comment by lukeis** [comment]
so chromedriver either crashed or something else occurred in their driver to cause it to not reply with an appropriate response.

Please log a bug with the chromedriver project and include a chromedriver.log file when this occurs.

https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by lukeis** [comment]
also the latest chromedriver is 2.25, please upgrade to that.

https://chromedriver.storage.googleapis.com/index.html?path=2.25/

**Comment by BrydenR** [comment]
This fixed it, thank you. Part of the problem is that the most recent version of pip doesn't have chromedriver 2.25.
