### ISSUE TITLE
Loading default user profile does not work (Selenium 3.0.0)

### ISSUE THREAD

**Issue by Rup1** [SeleniumHQ/selenium#3070]
## Meta -
OS:  Windows 10 and OSX

Selenium Version: Webdriver JS  3.0.0

Browser:  Chrome latest version

Browser Version:  Chrome 54.x.x.x latest

## Expected Behavior - 
Loading the following code should launch chrome with my default profile:
```
var webdriver = require('selenium-webdriver'),
    chrome = require('selenium-webdriver/chrome'),
    By = webdriver.By,
    until = webdriver.until,
    button = webdriver.Button,
    promise = webdriver.promise;
    fs = require('fs');

    var o = new chrome.Options();
    o.addArguments("user-data-dir=/Users/conquerjs/Library/Application Support/Google/Chrome/");
    var driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).setChromeOptions(o).build();

driver.get('http://www.google.com');

  driver.sleep(5000);
  driver.quit();


```
## Actual Behavior -

This actually does launch the browser with my default profile and all extensions loaded, but never navigates to page `driver.get('news.google.com');` it just hangs there. It seems that the "Chrome automation extension" that drives the automation doesn't get loaded, that's the only thing I can see that's different. Is this a bug?

EDIT: I forgot to include the error: 

```
WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
    at WebDriverError (/Users/conquerjs/Desktop/rebelmail/rebelmail-acceptance/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/Users/conquerjs/Desktop/rebelmail/rebelmail-acceptance/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/conquerjs/Desktop/rebelmail/rebelmail-acceptance/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/conquerjs/Desktop/rebelmail/rebelmail-acceptance/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/conquerjs/Desktop/rebelmail/rebelmail-acceptance/node_modules/selenium-webdriver/lib/webdriver.js:776:24)
    at Function.createSession (/Users/conquerjs/Desktop/rebelmail/rebelmail-acceptance/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/Users/conquerjs/Desktop/rebelmail/rebelmail-acceptance/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/Users/conquerjs/Desktop/rebelmail/rebelmail-acceptance/node_modules/selenium-webdriver/index.js:639:16)
    at Object.<anonymous> (/Users/conquerjs/Desktop/rebelmail/rebelmail-acceptance/testing.js:11:112)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
Rups-Mac:rebelmail-acceptance conquerjs$

```

## Steps to reproduce -
run above code.

**Comment by jleyba** [comment]
Sounds like an [issue with the chromedriver](https://bugs.chromium.org/p/chromedriver/issues/list) itself. Did this work before?

**Comment by Rup1** [comment]
It works when I let webdriver create a new profile by specifying a new path, but if I want to load my already existing default profile, no good.

**Comment by jleyba** [comment]
Yeah, this is an issue with the chromedriver. Please file a bug here:

https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by KavyaGopal** [comment]
@Rup1 
chrome.setDefaultService(new chrome.ServiceBuilder(chromedriver.path).build());
setting default service helped me
