### ISSUE TITLE
[Selenium-Server] Cannot start up server with -D params in version 3.0.1

### ISSUE THREAD

**Issue by ReinhardXu2007** [SeleniumHQ/selenium#3080]
## Meta -
OS:  
Win 7
Selenium Version:  
3.0.1 server stand alone
Browser:  
ALL

## Actual Behavior -
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown opti
on: -Dwebdriver.ie.driver=IEDriverServer_2.53.1.exe
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
        at org.openqa.grid.selenium.GridLauncherV3$3.setConfiguration(GridLaunch
erV3.java:257)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.
java:147)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:73)
Press any key to continue . . .

## Steps to reproduce -
java -jar selenium-server-standalone-3.0.1.jar -Dwebdriver.ie.driver=IEDriverServer_2.53.1.exe

**Comment by lukeis** [comment]
Java system properties specified on the command line go in front of the -jar:

java-Dwebdriver.ie.driver=.... -jar selenium-server-standalone.jar

**Comment by ReinhardXu2007** [comment]
@lukeis  thx.
But the script provided in steps, it used to work fine on version 2.48

**Comment by lukeis** [comment]
yes, it did, but we changed our command line parser to use another standard library rather than maintaining custom code in the selenium project. And libraries don't attempt to redefine behavior that the java tooling provides
