### ISSUE TITLE
ReadExistingPreferences() exception occured due to duplicate preferences on 'user.js' config

### ISSUE THREAD

**Issue by couchpotatodude** [SeleniumHQ/selenium#3090]
## Meta -
OS:  Windows (any)

Selenium Version:  3.0.0

Browser:  Firefox

Browser Version:  Any

## Expected Behavior -
Calling FirefoxProfile constructor with profile path, e.g.:
var profile = new FirefoxProfile(%PATH_TO_PROFILE%);

We should get FirefoxProfile object instance.

## Actual Behavior -
An exception has been thrown: System.ArgumentException: An item with the same key has already been added.
                         at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
                         at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
                         at OpenQA.Selenium.Firefox.FirefoxProfile.ReadExistingPreferences()
                         at OpenQA.Selenium.Firefox.FirefoxProfile..ctor(String profileDirectory, Boolean deleteSourceOnClean)
                         at OpenQA.Selenium.Firefox.FirefoxProfileManager.GetProfile(String profileName)

## Steps to reproduce -
Add duplicate strings on 'user.js' file in profile and call constructor with profile path.
You use Dictionary<string,string> to store user preferences but some 3-rd party applications like antiviruses can modify 'user.js' config with duplicate strings. It`s better to check if dictionary already contains key before adding.

**Comment by diemol** [comment]
@couchpotatodude apologies for the poor handling of this issue. 
It seems there is something wrong with the profile being used. If this issue is still present in the latest Selenium and Firefox versions, could you please create a new issue with all the information required by the template so we can have a look?
Closing this issue for now.
