### ISSUE TITLE
Firefox does not start via Grid when adding a profile

### ISSUE THREAD

**Issue by phoenix384** [SeleniumHQ/selenium#3127]
## Meta -
OS:  Windows 8.1 (code execution), Ubuntu 16.04 (node)
Selenium Version:  3.0.1
Browser:  Firefox
Browser Version:  45.4.0 ESR

## Expected Behavior -
Firefox starts when adding a profile

## Actual Behavior -
Firefox does not start and the node logs an exception:

Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/opt/firefox-esr/firefox) on port 7055; process output follows:
null
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'vm-115', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-47-generic', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:129)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:347)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)
        ... 14 more
Caused by: org.openqa.selenium.WebDriverException: java.io.IOException: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'vm-115', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-47-generic', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.FirefoxBinary.extractAndCheck(FirefoxBinary.java:169)
        at org.openqa.selenium.firefox.FirefoxBinary.modifyLinkLibraryPath(FirefoxBinary.java:130)
        at org.openqa.selenium.firefox.FirefoxBinary.startProfile(FirefoxBinary.java:91)
        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:100)
        ... 20 more
Caused by: java.io.IOException: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so
        at org.openqa.selenium.io.FileHandler.locateResource(FileHandler.java:88)
        at org.openqa.selenium.io.FileHandler.copyResource(FileHandler.java:57)
        at org.openqa.selenium.firefox.FirefoxBinary.extractAndCheck(FirefoxBinary.java:162)
        ... 23 more
16:10:23.634 WARN - Exception: java.io.IOException: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'vm-115', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-47-generic', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
16:10:23.662 WARN - Exception thrown
java.lang.NullPointerException
        at java.util.HashMap.putMapEntries(HashMap.java:500)
        at java.util.HashMap.putAll(HashMap.java:784)
        at org.openqa.selenium.remote.DesiredCapabilities.<init>(DesiredCapabilities.java:54)
        at org.openqa.selenium.remote.server.handler.NewSession.setJsonParameters(NewSession.java:53)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:99)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:189)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
16:10:23.662 WARN - Exception: null

## Steps to reproduce -
Run a Grid node and a hub with the latest selenium-server-standalone-3.0.1.jar.
Execute the following code:

`
public class Main {
  public static void main(String[] args) throws MalformedURLException {
    DesiredCapabilities cap = DesiredCapabilities.firefox();
    cap.setCapability(FirefoxDriver.MARIONETTE, false);
    cap.setCapability(FirefoxDriver.PROFILE, new FirefoxProfile());
    RemoteWebDriver driver = new RemoteWebDriver(new URL("..."), cap);
  }
}
`
Without the FirefoxProfile line Firefox starts normally.

The exception mentioned above says something about /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so that is not found. And that is correct since there is no such path in the selenium-server-standalone-3.0.1.jar.
But I found that folder inside the previously used selenium-server-standalone-2.53.1.jar.
I tried to copy the amd64 (and the also missing x86 folder) from the 2.53.1 jar to the 3.0.1 jar and got Firefox work again.

**Comment by awilkins** [comment]
Confirm this behaviour ; built a specific Firefox 38 version of the Docker images because that's our target audience (don't ask...) and using a profile to turn on `focusmanager.testmode` fails with this exception about the missing native library.

Just because 3.0.1 is concurrent with Firefox 48 and up and thus is in the "Geckodriver" era doesn't mean that people aren't using it to test older setups.

I shall be rebuilding my firefox-38 image on 2.53.1 for now...

**Comment by barancev** [comment]
This issue was fixed in 3.2.0 (also checked that 3.8.1 contains this resource file).
