### ISSUE TITLE
 Chrome failed to start: crashed

### ISSUE THREAD

**Issue by milkdeliver** [SeleniumHQ/selenium#3132]
Hello selenium expert,

Could you please take you time to see the following error? Thank you so much.

OS:  Ubuntu 14.04TLS

Selenium Version:  

Browser:  Chrome 54.0.2840.100
ChromeDriver version: 2.25.426924

**Error**
```
[WARNING] useSystemClassloader setting has no effect when not forking
[INFO] Surefire report directory: /var/jenkins_home/workspace/sbou01/target/surefire-reports
Starting ChromeDriver 2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e) on port 20750
Only local connections are allowed.
Creation of webdriver failed, retrying...
Starting ChromeDriver 2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e) on port 20750
Only local connections are allowed.
Running com.sap.ui5.selenium.qunit.QUnitTest
Starting ChromeDriver 2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e) on port 20750
Only local connections are allowed.
Creation of webdriver failed, retrying...
Starting ChromeDriver 2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e) on port 20750
Only local connections are allowed.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 120.171 sec <<< FAILURE! - in com.sap.ui5.selenium.qunit.QUnitTest
initializationError(com.sap.ui5.selenium.qunit.QUnitTest)  Time elapsed: 0.004 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-45-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.06 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: '8f6e07f9a119', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-45-generic', java.version: '1.8.0_65'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
    at com.sap.ui5.selenium.utils.Browser$1.createLocal(Browser.java:61)
    at com.sap.ui5.selenium.utils.Browser.create(Browser.java:250)
    at com.sap.ui5.selenium.utils.WebDriverPool.getFreeDriver(WebDriverPool.java:117)
    at com.sap.ui5.selenium.qunit.QUnitTest.getFreeDriver(QUnitTest.java:285)
    at com.sap.ui5.selenium.qunit.QUnitTest.getFreeDriver(QUnitTest.java:270)
    at com.sap.ui5.selenium.qunit.QUnitTest.findTests(QUnitTest.java:403)


Results :

Tests in error: 
  QUnitTest.findTests:403->getFreeDriver:270->getFreeDriver:285 » WebDriver unkn...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[ERROR] There are test failures.
```

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
