### ISSUE TITLE
Selenium 3.0.1 unable to launch Firefox

### ISSUE THREAD

**Issue by chrisspen** [SeleniumHQ/selenium#3136]
OS:  Ubuntu 16.04
Selenium Version: 3.0.1
Browser:  Firefox 45.0.2

Installing selenium==3.0.1 into my Python virtual environment and running my Selenium unittests now fail with the error:

    Traceback (most recent call last):
      File "/myproject/tests/selenium_tests.py", line 720, in setUp
        super(SeleniumTests, self).setUp()
      File "/myproject/tests/selenium_tests.py", line 280, in setUp
        self.driver = webdriver.Firefox(p)
      File "/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
        self.service.start()
      File "/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 71, in start
        os.path.basename(self.path), self.start_error_message)
    WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by AutomatedTester** [comment]
Follow the steps in https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by lukeis** [comment]
If you'd like to use the previous firefox extension with older selenium then you need to set a capability. Change your `self.driver = webdriver.Firefox(p)` to:

    self.driver = webdriver.Firefox(p, capabilities={'marionette':False})

Otherwise if you'd like to use the latest Firefox version you should download [geckodriver](https://github.com/mozilla/geckodriver/releases) and put it somewhere on your system path.

**Comment by chrisspen** [comment]
Thanks, that works.
