### ISSUE TITLE
installing py selenium in development mode

### ISSUE THREAD

**Issue by stupidnetizen** [SeleniumHQ/selenium#3138]
## Meta -
OS:  
Ubuntu
Selenium Version:  
3.0.1
Client: Python  

-->
## Expected Behavior -
After executing `./go py_prep_for_install_release` `python setup.py develop` should correctly install selenium in development/editable mode. 
## Actual Behavior -
Output of `python setup.py develop`

```
running develop
running egg_info
creating selenium.egg-info
writing selenium.egg-info/PKG-INFO
writing top-level names to selenium.egg-info/top_level.txt
writing dependency_links to selenium.egg-info/dependency_links.txt
writing manifest file 'selenium.egg-info/SOURCES.txt'
reading manifest file 'selenium.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'py/selenium/selenium.py'
writing manifest file 'selenium.egg-info/SOURCES.txt'
running build_ext
Creating /home/jitendra/.virtualenvs/pyselexp/lib/python2.7/site-packages/selenium.egg-link (link to .)
Adding selenium 3.0.1 to easy-install.pth file
Installed /home/jitendra/gitprojects/selenium3
Processing dependencies for selenium==3.0.1
Finished processing dependencies for selenium==3.0.1
```

Output of `python -c 'import selenium;print("OK");'` 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named selenium
```

## Steps to reproduce -
1. Clone the repository using `git clone git@github.com:SeleniumHQ/selenium.git`
2. Execute `./go py_prep_for_install_release` 
3. Execute `python setup.py develop`

Please see below 02 lines as mentioned in the output of `python setup.py develop`
```
Adding selenium 3.0.1 to easy-install.pth file
Installed /home/jitendra/gitprojects/selenium3

```
As I am using `virtualenv`, I added `/py` after `/home/jitendra/gitprojects/selenium3` in my `easy-install.pth` file as shown below 
```
cat /home/jitendra/.virtualenvs/pyselexp/lib/python2.7/site-packages/easy-install.pth
import sys; sys.__plen = len(sys.path)
/home/jitendra/gitprojects/selenium3/py
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)

```
and i was able to successfully execute ` python -c 'import selenium;print("OK");' `.

**Comment by AutomatedTester** [comment]
I can't reproduce this 
```
[-] PARSING BUCK FILES...FINISHED 0.0s
[-] BUILDING...FINISHED 1.8s [100%]
Compiling: //javascript/firefox-driver:bad-cert-listener as build/javascript/firefox-driver/bad-cert-listener.js
Compiling: //javascript/firefox-driver:session as build/javascript/firefox-driver/session.js
Compiling: //javascript/firefox-driver:session-store as build/javascript/firefox-driver/session-store.js
Compiling: //javascript/firefox-driver:command-processor as build/javascript/firefox-driver/command-processor.js
Building: //javascript/firefox-driver:command-processor-xpt as build/javascript/firefox-driver/nsICommandProcessor.xpt
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/nsICommandProcessor.xpt
Building: //javascript/firefox-driver:coordinates-xpt as build/javascript/firefox-driver/wdICoordinate.xpt
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/wdICoordinate.xpt
Compiling: //javascript/firefox-driver:modifier-keys as build/javascript/firefox-driver/modifier-keys.js
Building: //javascript/firefox-driver:modifier-keys-xpt as build/javascript/firefox-driver/wdIModifierKeys.xpt
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/wdIModifierKeys.xpt
Compiling: //javascript/firefox-driver:driver-component as build/javascript/firefox-driver/driver-component.js
Building: //javascript/firefox-driver:httpd-xpt as build/javascript/firefox-driver/nsIHttpServer.xpt
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/nsIHttpServer.xpt
Building: //javascript/firefox-driver:mouse-xpt as build/javascript/firefox-driver/wdIMouse.xpt
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/wdIMouse.xpt
Compiling: //javascript/firefox-driver:prompt-service as build/javascript/firefox-driver/prompt-service.js
Building: //javascript/firefox-driver:response-handler-xpt as build/javascript/firefox-driver/nsIResponseHandler.xpt
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/nsIResponseHandler.xpt
Building: //javascript/firefox-driver:status-xpt as build/javascript/firefox-driver/wdIStatus.xpt
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/wdIStatus.xpt
Compiling: //javascript/firefox-driver:synthetic-mouse as build/javascript/firefox-driver/synthetic-mouse.js
Compiling: //javascript/firefox-driver:web-element-cache as build/javascript/firefox-driver/web-element-cache.js
Preparing: //javascript/firefox-driver:webdriver as build/javascript/firefox-driver/webdriver.xpi
[-] PARSING BUCK FILES...FINISHED 0.0s
[-] BUILDING...FINISHED 1.4s [100%]
cp build/cpp/i386/libnoblur.so py/selenium/webdriver/firefox/x86/x_ignore_nofocus.so
cp build/cpp/amd64/libnoblur64.so py/selenium/webdriver/firefox/amd64/x_ignore_nofocus.so
cp buck-out/gen/javascript/atoms/fragments/is-displayed.js py/selenium/webdriver/remote/isDisplayed.js
cp buck-out/gen/javascript/webdriver/atoms/getAttribute.js py/selenium/webdriver/remote/getAttribute.js
cp build/javascript/firefox-driver/webdriver.xpi py/selenium/webdriver/firefox/
cp build/javascript/firefox-driver/webdriver_prefs.json py/selenium/webdriver/firefox/
dburns in ~/development/test-foo on master λ rmvirtualenv bug3138
Removing bug3138...
dburns in ~/development/test-foo on master λ mkvirtualenv bug3138
New python executable in /Users/dburns/.virtualenvs/bug3138/bin/python2.7
Also creating executable in /Users/dburns/.virtualenvs/bug3138/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/dburns/.virtualenvs/bug3138/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/dburns/.virtualenvs/bug3138/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/dburns/.virtualenvs/bug3138/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/dburns/.virtualenvs/bug3138/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/dburns/.virtualenvs/bug3138/bin/get_env_details
(bug3138) dburns in ~/development/test-foo on master λ python setup.py develop
running develop
running egg_info
creating selenium.egg-info
writing selenium.egg-info/PKG-INFO
writing top-level names to selenium.egg-info/top_level.txt
writing dependency_links to selenium.egg-info/dependency_links.txt
writing manifest file 'selenium.egg-info/SOURCES.txt'
reading manifest file 'selenium.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'py/selenium/selenium.py'
writing manifest file 'selenium.egg-info/SOURCES.txt'
running build_ext
Creating /Users/dburns/.virtualenvs/bug3138/lib/python2.7/site-packages/selenium.egg-link (link to .)
Adding selenium 3.0.1 to easy-install.pth file

Installed /Users/dburns/development/test-foo
Processing dependencies for selenium==3.0.1
Finished processing dependencies for selenium==3.0.1
```

**Comment by AutomatedTester** [comment]
I tested this with sha 68d51cf4494829c464a21e79fe0fd23bb752e7d9

**Comment by stupidnetizen** [comment]
Hi @AutomatedTester , are you able to import selenium after `python setup.py develop`
I tried again after pulling in the latest changes.
below is the output:
```bash
[-] PARSING BUCK FILES...FINISHED 0.0s [100%]
[-] BUILDING...FINISHED 9.5s [100%]
cp build/cpp/i386/libnoblur.so py/selenium/webdriver/firefox/x86/x_ignore_nofocus.so
cp build/cpp/amd64/libnoblur64.so py/selenium/webdriver/firefox/amd64/x_ignore_nofocus.so
cp buck-out/gen/javascript/atoms/fragments/is-displayed.js py/selenium/webdriver/remote/isDisplayed.js
cp buck-out/gen/javascript/webdriver/atoms/getAttribute.js py/selenium/webdriver/remote/getAttribute.js
cp build/javascript/firefox-driver/webdriver.xpi py/selenium/webdriver/firefox/
cp build/javascript/firefox-driver/webdriver_prefs.json py/selenium/webdriver/firefox/
(bug3138)jitendra@expat:selenium_py$ python setup.py develop
running develop
running egg_info
creating selenium.egg-info
writing selenium.egg-info/PKG-INFO
writing top-level names to selenium.egg-info/top_level.txt
writing dependency_links to selenium.egg-info/dependency_links.txt
writing manifest file 'selenium.egg-info/SOURCES.txt'
reading manifest file 'selenium.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'py/selenium/selenium.py'
writing manifest file 'selenium.egg-info/SOURCES.txt'
running build_ext
Creating /home/jitendra/.virtualenvs/bug3138/lib/python2.7/site-packages/selenium.egg-link (link to .)
Adding selenium 3.0.1 to easy-install.pth file

Installed /home/jitendra/gitprojects/selenium_py
Processing dependencies for selenium==3.0.1
Finished processing dependencies for selenium==3.0.1
(bug3138)jitendra@expat:selenium_py$ python -c 'import selenium;print("OK");'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named selenium
```

**Comment by AutomatedTester** [comment]
this is because we are using a mono repo, 

do `cd py/` and then try again and it works.

**Comment by stupidnetizen** [comment]
but in that case , I don't need to use `python setup.py develop` I suppose.
