### ISSUE TITLE
PortProber.pollPort - Address already in use (Bind failed)

### ISSUE THREAD

**Issue by ltoinel** [SeleniumHQ/selenium#3178]
## Meta -
OS:  Linux Ubuntu 16.04LTS

Selenium Version:   selenium-html-runner-3.0.1.jar

Browser:  Chromium (ubuntu package)

I'm starting a default test using the Selenium HTML Runner. The test crash with an "Address already in use" each time.

## Expected Behavior -
Test running

## Actual Behavior -

`INFO: Detected dialect: OSS
2016-11-28 22:46:54.301:INFO::main: Logging initialized @3265ms
2016-11-28 22:46:54.361:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2016-11-28 22:46:54.376:INFO:osjsh.ContextHandler:main: Started o.s.j.s.h.ContextHandler@2e005c4b{/tests,null,AVAILABLE}
2016-11-28 22:46:54.389:INFO:osjs.ServerConnector:main: Started ServerConnector@1076ccc5{HTTP/1.1}{0.0.0.0:27931}
2016-11-28 22:46:54.390:INFO:osjs.Server:main: Started @3354ms
2016-11-28 22:46:54.393:INFO:osjs.ServerConnector:main: Stopped ServerConnector@1076ccc5{HTTP/1.1}{0.0.0.0:27931}
2016-11-28 22:46:54.394:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@2e005c4b{/tests,null,UNAVAILABLE}
Nov 28, 2016 10:46:54 PM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *googlechrome
java.io.IOException: java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:180)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:108)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:154)
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:137)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:174)
        ... 3 more
Caused by: java.net.BindException: Address already in use (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.Socket.bind(Socket.java:644)
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:146)
        ... 5 more
`

## Steps to reproduce -

 sudo xvfb-run java -jar -Dwebdriver.chrome.driver=/opt/selenium/drivers/chromedriver "/opt/selenium/selenium-runner.jar" -htmlSuite *googlechrome http://www.xxxx.com /home/xxxx/suite.html chrome-results.html

**Comment by lukeis** [comment]
this was fixed by ea09fb26ffb0878417149e06e33b2f5f4d8b5fe7

and other fixes by barancev which are on the history here -

https://github.com/SeleniumHQ/selenium/commits/master/java/server/src/org/openqa/selenium/server/htmlrunner

**Comment by clavat** [comment]
When new version of htmlrunner will be out ?
We can only download 3.0.1 with this bug
