### ISSUE TITLE
Error when trying execute js script 

### ISSUE THREAD

**Issue by PKostya** [SeleniumHQ/selenium#3187]
## Meta -
OS:  Windows 10 

Selenium Version:  3.0.1

Browser: Firefox GeckoDriver 

Browser Version:  50.0.1

## Actual Behavior - 
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], prefs={}}, appBuildId=20161123182536, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=10848, brow
serVersion=50.0.1, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: 49ca5227-b4f9-4796-9124-8401f1fad44e
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
  at java.lang.reflect.Constructor.newInstance(Unknown Source)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
  at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
  at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
  at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:537)

## Steps to reproduce -
import org.openqa.selenium.JavascriptExecutor
import org.openqa.selenium.firefox.FirefoxDriver

class Driver(url:String) {
  System.setProperty("webdriver.gecko.driver", "d:/geckodriver.exe")
  var driver = new FirefoxDriver()
  var js = driver.asInstanceOf[JavascriptExecutor]
  driver.get(url)
  driver.executeScript("alert('hello world');")
  //driver.executeScript("document.getElementById('movie_player').getPlayerState()")*/

}

object Main extends App {
  val url = some_url
  val driver = new Driver(url)
}

**Comment by lukeis** [comment]
alert is a tricky one here. It's a blocking call... and although selenium's firefox driver handled this case explicitly it doesn't look like geckodriver does. Please log a bug with the geckodriver project -
https://github.com/mozilla/geckodriver

As a workaround for this specific case you can do:
driver.executeScript("setTimeout(function(){alert('hi')}, 100)")
