### ISSUE TITLE
org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver

### ISSUE THREAD

**Issue by saurabh-gaur** [SeleniumHQ/selenium#3202]
## Meta -
OS:  
Mac OSX 
OS version: 
10.11.4
Selenium Version:  
2.53.0
Browser:  
Safari
Browser Version:
9.1 (11601.5.17.1)

## Expected Behavior -

Test case should be pass on safari browser on every run.

## Actual Behavior -

Sometime getting failed.

## Description -

I have already installed [SafariDriver.safariextz](http://selenium-release.storage.googleapis.com/index.html?path=2.48/), but when I'm trying to launch **Safari Browser** using `RemoteWebDriver` as below

## Code -

 ```
    URL server = new URL("http://localhost:4444/wd/hub");
    DesiredCapabilities capabilities = DesiredCapabilities.safari();
    WebDriver webDriver = new RemoteWebDriver(server, capabilities);
    webDriver.get("https://www.google.co.in");
```

**It's failing sometime with following error**

## Stacktrace -

```
org.openqa.selenium.WebDriverException: Failed to connect to SafariDriver after 10200 ms
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'bqurious-Mac-mini.local', ip: '192.168.3.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_112'
Driver info: driver.version: SafariDriver
Command duration or timeout: 12.34 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'bqurious-Mac-mini.local', ip: '192.168.3.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.remote.RemoteWebDriver

Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10200 ms
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'bqurious-Mac-mini.local', ip: '192.168.3.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_112'
Driver info: driver.version: SafariDriver
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'bqurious-Mac-mini.local', ip: '192.168.3.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_112'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:121)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:76)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:62)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at
https://bugreport.apple.com/

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
