### ISSUE TITLE
ableToSwitchFrames(0) throws 'missing id' error.

### ISSUE THREAD

**Issue by Rup1** [SeleniumHQ/selenium#3206]
## Meta -
OS:  Windows 10.

Selenium Version:   Webdriver 3.0.1

Browser:  Chrome chromedriver 2.25.1

Browser Version:  Latest Chrome

## Steps to reproduce -

Here is my code: 
`find('#email').sendKeys( userEmail);`
    `find('#password').sendKeys(userPass);`
    `find('.btn').click();`
    `createCampaign(); //simply clicks "createCampaign" button`
    `fillForms(); //fills out preliminary info that's required'`
   ` selectTemplate('2'); //clicks template from a dropdown`
    `populateCampaign();//moves onto 'populate campaign page where the iFrame lives'`
    `driver.wait(until.ableToSwitchToFrame(0), 10000); ` <--- Error

Here is the error:

```
WebDriverError: unknown error: missing 'id'
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 10.0.14971 x86_64)
    at WebDriverError (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\error.js:27:5)
    at Object.checkLegacyResponse (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.switchTo().frame(undefined)
    at thenableWebDriverProxy.schedule (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
    at TargetLocator.frame (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\webdriver.js:1735:25)
    at attemptToSwitchFrames (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\until.js:90:30)
    at C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\webdriver.js:947:14
    at TaskQueue.execute_ (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2860:25)
    at C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: <anonymous>
    at pollCondition (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2101:19)
    at C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2097:7
    at new ManagedPromise (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:1067:7)
    at ControlFlow.promise (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2396:12)
    at C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2096:22
    at TaskQueue.execute_ (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: Waiting to be able to switch to frame
    at scheduleWait (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2094:20)
    at ControlFlow.wait (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\promise.js:2408:12)
    at thenableWebDriverProxy.wait (C:\Users\ConquerJS\Desktop\acceptance\node_modules\selenium-webdriver\lib\webdriver.js:943:29)
    at Object.<anonymous> (C:\Users\ConquerJS\Desktop\acceptance\test\smoketest.js:51:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```
when I use `driver.switchTo().frame(0);`  this works, however I need a wait condition otherwise I need to use driver.sleep() before being able to find elements.

I haven't found any examples on how to actually use this method in javascript (the doc just has a super dry explanation and a link to the source code), so it is possible I've gone about it the wrong way.

**Comment by joshuarichard** [comment]
I'm seeing this too - any update?
