### ISSUE TITLE
[Node.js] Unhandled Rejection in checkLegacyResponse() at error.js:505

### ISSUE THREAD

**Issue by zixia** [SeleniumHQ/selenium#3232]
## Meta -
OS:  
Linux 4.4.0-51-generic x86_64 (Travis CI)
Selenium Version:  
3.0.0
Browser:  
chrome

Browser Version:  
Google Chrome 54.0.2840.90 

## Expected Behavior -

Should not has Unhandled Rejection

## Actual Behavior -

Unhandled Rejection at selenium-webdriver/lib/error.js:505

## Steps to reproduce -

https://travis-ci.org/wechaty/wechaty/jobs/182802278#L3134

```shell
Unhandled Rejection at: Promise Promise {
  <rejected> { WebDriverError: unknown error: Chrome failed to start: was killed
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-51-generic x86_64)
    at Object.checkLegacyResponse (/home/travis/build/wechaty/wechaty/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/home/travis/build/wechaty/wechaty/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/travis/build/wechaty/wechaty/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7) name: 'WebDriverError' } } reason: { WebDriverError: unknown error: Chrome failed to start: was killed
```

P.S. This exception often appears in my CI tests. I checked many times to confirm that I do all the `catch` work for promises in my code.

**Comment by jleyba** [comment]
Is this still a problem with the latest build? I can't reproduce it.

**Comment by zixia** [comment]
Hi @jleyba ,

Thanks for following!

I have been not monitoring this issue for a while, will check it for you recently.

**Comment by zixia** [comment]
Hello, I did not see this bug in the past few months. 

I guess it was fixed in some version.
