### ISSUE TITLE
Selenium sometimes fails to load the first page (IE issue)

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#3259]
## Meta -
Selenium Version:  2.53.4
Browser:  IE11 Win10
*Selenium Grid*

## Behavior
When running the `.load` command, issues sometimes arise (Can vary from not at all to a few times). The problematic command is when we load up the main website. I've raised an issue on siteprism as it's their command I'm loading and they've told me it's not a SitePrism / Capybara issue.

## Steps to reproduce
I don't really have much to reproduce it outside of the Browser / Selenium Info given. This only seems to happen on the grid (Although we run 10* more testing there, so perhaps just not seen locally). The issue seems to occur 1/2 scenarios in the 9 when we notice it, and it always seems to be on this one node (Mentioned above).

https://github.com/natritmeyer/site_prism/issues/173

**Comment by lukeis** [comment]
load isn't a selenium webdriver command. Is it translated to webdriver.get? Or if you could show the endpoint logged in grid that would be helpful.

**Comment by luke-hill** [comment]
This is a C+P from the previous issue: If you need more info let me know. Although I'm still getting to grips with grid.

Working steps:
`@nofeatures/search/f_and_h.feature:46`
`Scenario: Flight & Hotel to The Canaries from Oslo with full payment`
Failing steps:
```
Given I am on the "no" home page
features/search/step_definitions/home_search_steps.rb:1
Running on Sandbox0
Failed to navigate to https://www.ebeach.no/?otb_variant=BA. This usually means that a call to the COM method IWebBrowser2::Navigate2() failed. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 32 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'node138107', ip: '172.23.4.148', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=true, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:6930/, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: d6d95fd0-c18a-460b-af2e-8045d0af93a1 (org.openqa.selenium.WebDriverException) (Selenium::WebDriver::Error::UnknownError)
[remote server] sun.reflect.NativeConstructorAccessorImpl():-2:in `newInstance0'
[remote server] sun.reflect.NativeConstructorAccessorImpl():-1:in `newInstance'
[remote server] sun.reflect.DelegatingConstructorAccessorImpl():-1:in `newInstance'
[remote server] java.lang.reflect.Constructor():-1:in `newInstance'
[remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):206:in `createThrowable'
[remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):158:in `throwIfResponseFailed'
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):678:in `execute'
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):316:in `get'
[remote server] sun.reflect.NativeMethodAccessorImpl():-2:in `invoke0'
[remote server] sun.reflect.NativeMethodAccessorImpl():-1:in `invoke'
[remote server] sun.reflect.DelegatingMethodAccessorImpl():-1:in `invoke'
[remote server] java.lang.reflect.Method():-1:in `invoke'
[remote server] org.openqa.selenium.support.events.EventFiringWebDriver$2(EventFiringWebDriver.java):103:in `invoke'
[remote server] com.sun.proxy.$Proxy3():-1:in `get'
[remote server] org.openqa.selenium.support.events.EventFiringWebDriver(EventFiringWebDriver.java):163:in `get'
[remote server] org.openqa.selenium.remote.server.handler.ChangeUrl(ChangeUrl.java):40:in `call'
[remote server] org.openqa.selenium.remote.server.handler.ChangeUrl(ChangeUrl.java):1:in `call'
[remote server] java.util.concurrent.FutureTask():-1:in `run'
[remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
[remote server] java.util.concurrent.ThreadPoolExecutor():-1:in `runWorker'
[remote server] java.util.concurrent.ThreadPoolExecutor$Worker():-1:in `run'
[remote server] java.lang.Thread():-1:in `run'
[remote server] sun.reflect.NativeConstructorAccessorImpl():-2:in `newInstance0'
[remote server] sun.reflect.NativeConstructorAccessorImpl():-1:in `newInstance'
[remote server] sun.reflect.DelegatingConstructorAccessorImpl():-1:in `newInstance'
[remote server] java.lang.reflect.Constructor():-1:in `newInstance'
[remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):206:in `createThrowable'
[remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):158:in `throwIfResponseFailed'
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):678:in `execute'
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):316:in `get'
[remote server] sun.reflect.NativeMethodAccessorImpl():-2:in `invoke0'
[remote server] sun.reflect.NativeMethodAccessorImpl():-1:in `invoke'
[remote server] sun.reflect.DelegatingMethodAccessorImpl():-1:in `invoke'
[remote server] java.lang.reflect.Method():-1:in `invoke'
[remote server] org.openqa.selenium.support.events.EventFiringWebDriver$2(EventFiringWebDriver.java):103:in `invoke'
[remote server] com.sun.proxy.$Proxy3():-1:in `get'
[remote server] org.openqa.selenium.support.events.EventFiringWebDriver(EventFiringWebDriver.java):163:in `get'
[remote server] org.openqa.selenium.remote.server.handler.ChangeUrl(ChangeUrl.java):40:in `call'
[remote server] org.openqa.selenium.remote.server.handler.ChangeUrl(ChangeUrl.java):1:in `call'
[remote server] java.util.concurrent.FutureTask():-1:in `run'
[remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
[remote server] java.util.concurrent.ThreadPoolExecutor():-1:in `runWorker'
[remote server] java.util.concurrent.ThreadPoolExecutor$Worker():-1:in `run'
[remote server] java.lang.Thread():-1:in `run'
./features/support/app.rb:71:in `ensure_stage1_has_loaded'
./features/search/step_definitions/home_search_steps.rb:6:in `/^I am on the "([^"]*)" home page$/'
```

There is also a small snippet at the bottom of Jenkins after the scenario saying
```
-1# Couldn't get snippet for [remote server] sun.reflect.NativeConstructorAccessorImpl():-2:in `newInstance0'
0# gem install syntax to get syntax highlighting
```

**Comment by luke-hill** [comment]
One thing to note (With all my issues I'm raising), is we use Selenium-webdriver gem `2.53.4` but Grid `2.53.1`. I'm not sure if this has any issues (And not sure why we haven't updated the grid higher, will find out)

**Comment by jimevans** [comment]
If the COM method is returning an error, there's nothing the driver can do about it.
