### ISSUE TITLE
Selenium WebDriver issue in Eclipse IDE when trying to perform a simple test with Firefox driver

### ISSUE THREAD

**Issue by petarmatic46** [SeleniumHQ/selenium#3265]
Hello everyone, I am having issues while trying to make my 1st simple test case in WebDriver.
I was searching for a solution on the web but i am kinda stuck so if anyone could help me i would appreciate it.
The code for the test case looks like this:

`package testAutomation;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class FirstTestCase {

	public static void main(String[] args) throws InterruptedException {
		// Create a new instance of the Firefox driver
		System.setProperty("webdriver.chrome.driver", "C:\\selenium-3.0.1\\lib\\selenium-firefox-driver-3.0.1.jar");
		WebDriver driver = new FirefoxDriver();
				
		        //Launch the Online Store Website
				driver.get("http://www.store.demoqa.com");

		        // Print a Log In message to the screen
		        System.out.println("Successfully opened the website www.Store.Demoqa.com");

				//Wait for 5 Sec
				Thread.sleep(5);
				
		        // Close the driver
		        driver.quit();
	}
}`
When trying to run the test in Eclipse i get the following errors:

Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/RenderedWebElement
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at testAutomation.FirstTestCase.main(FirstTestCase.java:12)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.RenderedWebElement
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more

Thanks!

**Comment by cgoldberg** [comment]
you didn't include the entire stacktrace, so it's hard to tell what is wrong.

but this line looks problematic:
`System.setProperty("webdriver.chrome.driver", "C:\\selenium-3.0.1\\lib\\selenium-firefox-driver-3.0.1.jar");`
you are setting the location of chrome driver for a Firefox test??

**Comment by petarmatic46** [comment]
Hello and thanks for the reply, yes i noticed i made a mistake..
Before copying the code i wanted to try to switch to chrome driver and see the results and thats why it is there, i made the changes after and still get the same errors.. Regarding the entire stacktrace i tried to add the following:

public class Main {
	    public void throwsException() {
	        throw new UnsupportedOperationException();
	    }

	    public void main(String[] args) throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
	        Main.class.getMethod("throwsException").invoke(null);
	    }

but im not able to get the full stacktrace..

**Comment by cgoldberg** [comment]
I don't know what that code is supposed to do...  but the exception you are encountering is: `NoClassDefFoundError`.  your original stacktrace is missing the last 13 lines.   

`... 13 more`

**Comment by lukeis** [comment]
Seems like you have conflicting and old versions of selenium on you classpath. Please check your project settings. As on selenium-users google group for more help

**Comment by jpatelhmt** [comment]
I am also getting the same error.

package selpk;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class FirstScript {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub

		WebDriver driver = new FirefoxDriver();
		driver.get("www.google.com");
		System.out.println("Successfully opened the website www.Store.Demoqa.com");
		Thread.sleep(5000);
		
		driver.quit();
	}

}


Error: Unable to initialize main class selpk.FirstScript
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/WebDriver

I have added external jars in the module path in project and the selenium version is also latest.
