### ISSUE TITLE
"[Errno 98] Address already in use" Calling free_port()

### ISSUE THREAD

**Issue by speedplane** [SeleniumHQ/selenium#3296]
## Meta
OS: linux, using the Docker image at `gcr.io/google_appengine/python-compat-multicore`
Selenium Version: 2.53.6
Browser: PhantomJS

## Expected Behavior
I am attempting to startup Selenium on a server with `port=0`. I understand that when `port` is `0`, Selenium looks for an open port to bind to.

Note that on this server, there are other instances of Selenium running, so it is possible that this is some type of race condition.

## Actual Behavior
There is a crash with the following call stack during startup:
```
Traceback (most recent call last):
  File "/home/vmagent/app/[redacted].py", line 188, in login
    driver = self._get_driver()
  File "/home/vmagent/app/[redacted].py", line 159, in _get_driver
    use_proxy = self.use_proxy, use_browsermob = self.use_proxy)
  File "/home/vmagent/app/[redacted].py", line 405, in get_driver
    service_log_path = log_file_name)
  File "/env/local/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 51, in __init__
    log_path=service_log_path)
  File "/env/local/lib/python2.7/site-packages/selenium/webdriver/phantomjs/service.py", line 50, in __init__
    service.Service.__init__(self, executable_path, port=port, log_file=open(log_path, 'w'))
  File "/env/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 35, in __init__
    self.port = utils.free_port()
  File "/env/local/lib/python2.7/site-packages/selenium/webdriver/common/utils.py", line 36, in free_port
    free_socket.bind(('0.0.0.0', 0))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

## Steps to reproduce
This is happening every few minutes on my server, but it's not easy to reproduce. It's almost certainly a race with other instances of selenium running on the same server.

**Comment by lmtierney** [comment]
Sorry but without a reproducible test scenario, we cannot investigate this
