### ISSUE TITLE
Unable to create new remote session. desired capabilities = Capabilities [{browserName=safari

### ISSUE THREAD

**Issue by arunkumar468** [SeleniumHQ/selenium#3299]
## Meta -
OS:  MAC

Selenium Version:  3.0.1

Browser:  SAFARI 9.0.3

Browser Version:  
 9.0.3

## Expected Behavior -
Safari Browser should launch and open URL
## Actual Behavior -
Unable to create new remote session. desired capabilities = Capabilities [{browserName=safari, safari.options=org.openqa.selenium.safari.SafariOptions@10e45, webdriver.safari.noinstall=true, version=, platform=MAC}], required capabilities = Capabilities [{}] Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700' System info: host: 'DS-SGH450Q8LH', ip: '10.166.88.126', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112' Driver info: driver.version: RemoteWebDriver

org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91) 
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141) 
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601) 
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241) 
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128) 
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155) 
at com.cnn.expansion.test.webdriver.DriverFactory.generateDriver(DriverFactory.java:208) 
at com.cnn.expansion.test.webdriver.WdFace.go(WdFace.java:143) 
at com.cnn.expansion.test.library.BaseTest.testHomePage(BaseTest.java:1475) 
at com.cnn.expansion.test.SmokeRefTests.HomePage(SmokeRefTests.java:24) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86) 
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:197) 
at com.cnn.expansion.test.core.BaseTest.run(BaseTest.java:83) 
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:209) 
at org.testng.internal.Invoker.invokeMethod(Invoker.java:639) 
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820) 
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75) 
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745) 
19 lines not shown
## Steps to reproduce -

Recently we are migrating from Selenium 2.53.1 to 3.0.1
All Browsers are working except Safari

**Comment by lukeis** [comment]
3.X no longers supports Safari earlier than 10, it relies now only on Apple's provided driver which is included in Safari 10.

If you want to still run tests using the old (and no longer supported) Safari Driver extension, you will need to use Selenium 2.X for driving it.

**Comment by thanhltx** [comment]
Hi everyone,

Do you have resloved this problem yet ?

I have same issues. My Safari version is 10.x.x

org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{browserName=safari, version=, platform=MAC}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'Thanhs-MacBook-Pro.local', ip: '10.0.1.86', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: driver.version: RemoteWebDriver

**Comment by TriveniReddyB** [comment]
Thanks Lukeis for the safari version update.

**Comment by sjenasears** [comment]
Did anyone found a solution for this issue.
i am getting the same error.

**Comment by Snehal6790** [comment]
Hey Everyone,

Even same problem I m facing.:


org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{appPackage=com.furlenco.andriod, appActivity=com.furlenco.android.ui.activity.SplashActivity, browserName=Android, platformName=Android, deviceName=ca51d02e, version=4.4.2}], required capabilities = Capabilities [{}]
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'Snehals-MacBook-Pro.local', ip: 'fe80:0:0:0:a0ff:67ff:fe2e:8bab%10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_121'
Driver info: driver.version: RemoteWebDriver



Please suggest some workaround for it
