### ISSUE TITLE
Python Selenium Chrome Driver No such session.

### ISSUE THREAD

**Issue by mkaya93** [SeleniumHQ/selenium#3303]
## Meta -
OS:   OSX 10.12.2

Selenium Version:  2.52.0 Scrapy

Browser:  Chrome

Browser Version:   55.0.2883.95 (64-bit)

Hi,

I'm trying to use selenium on my project. But I'm getting No such session error. when I use it with latest chrome driver. Also You can find error below. 

```
Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/user/Downloads/Test-2/ecommerce_bot/ecommerce_bot/spiders/hepsiburada.py", line 67, in parseProductComments
    self.browser.get(response.url)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: no such session
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.2 x86_64)


```

Also This my code.
```
self.browser.get("url")
xpath = self.browser.find_element_by_xpath("/html/head/script[17]")
```

**Comment by cgoldberg** [comment]
> self.browser.get("url")

you are trying to fetch a string named "url".  unquote that so it's a variable name, and make sure you define `url` somewhere.

**Comment by mkaya93** [comment]
@cgoldberg I'm actually fetching url I just changed it for writing issue.

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
