### ISSUE TITLE
Firefox / Windows: setting preferences with an empty profile directory on longer works

### ISSUE THREAD

**Issue by fippo** [SeleniumHQ/selenium#3307]
## Meta -
OS:  Windows 10
Selenium Version:  
nodejs [selenium-webdriver](https://www.npmjs.com/package/selenium-webdriver) 3.0.1
Browser: 
Firefox

Browser Version:  
50.0.2
using marionette with geckodriver 0.11.1

## Expected Behavior -
Creating a Firefox profile with an empty template directory and setting a preference starts Firefox with that preference set.

## Actual Behavior -
The preference is not set.

This works fine on Linux and used to work on Windows previously. It still works for me when using 3.0.0-beta-3 (even though that opens Firefox Nightly instead of 50.0.2

## Steps to reproduce -
Execute the following script in a directory that contains an empty directory 'someprofile':
```
var os = require('os');
var path = require('path');
var webdriver = require('selenium-webdriver');
var firefox = require('selenium-webdriver/firefox');

var profile = new firefox.Profile(path.join(process.cwd(), 'someprofile'));
profile.setPreference('media.navigator.streams.fake', true);
var firefoxOptions = new firefox.Options()
  .setProfile(profile);

var driver = new webdriver.Builder()
    .setFirefoxOptions(firefoxOptions)
    .forBrowser('firefox');
driver.getCapabilities().set('marionette', true);
driver = driver.build();
```
Note that this opens the firstrun page which does not happen if the template directory is omitted.
Navigate to about:config, search for **media.navigator.streams.fake** which is not there.

```firefoxOptions``` has preferences_ and template_ set correctly. The template directory created during writeToDisk looks fine as well.

**Comment by jleyba** [comment]
I can't reproduce this on OSX with geckodriver 0.13.0

Does this still happen for you with? If you checkout the latest code, you can run the test I added in 8d8ffdd0fd2bce8fa864452cc265cf47e779dfa1 with:

```
# Assuming you are in your cloned Selenium repo
$ npm install -g mocha
$ cd javascript/node/selenium-webdriver
$ mocha -t 120000 test/firefox/firefox_test.js --grep "preferences"
```

**Comment by fippo** [comment]
fails (horay), here is the output:
```
Not using buckd because watchman isn't installed.
  [firefox]
    firefox
      Options
        can start Firefox with custom preferences
          √ profile created from scratch (3447ms)
          1) profile created from template


  1 passing (32s)
  1 failing

  1) [firefox] firefox Options can start Firefox with custom preferences profile created from template:

      AssertionError: 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0' === 'foo;bar'
      + expected - actual

      -Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
      +foo;bar

      at testing\assert.js:342:14
      at evaluate (testing\assert.js:92:3)
      at Assertion.isEqualTo (testing\assert.js:341:12)
      at Assertion.equalTo (testing\assert.js:325:17)
      at test\firefox\firefox_test.js:88:31
      at next (native)
      at pump (lib\promise.js:3288:25)
      at callNext (lib\promise.js:3274:7)
      at ManagedPromise.invokeCallback_ (lib\promise.js:1366:14)
      at TaskQueue.execute_ (lib\promise.js:3037:14)
      at TaskQueue.executeNext_ (lib\promise.js:3020:27)
      at asyncRun (lib\promise.js:2880:27)
      at lib\promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: [firefox] firefox Options can start Firefox with custom preferences profile created from template
      at Context.ret (testing\index.js:183:10)
```
I got frequent NoSuchWindowError but worked around that by changing the order of tests.

Works fine on Linux as well so probably an OS-specific issue :-/

**Comment by jleyba** [comment]
Do the other Firefox-specific tests pass?

```sh
$  mocha -t 1200000 test/firefox/

extension
    ✓ can install a jetpack xpi file (46ms)
    ✓ can install a normal xpi file
    ✓ can install an extension from a directory

  [firefox]
    firefox
      Options
        ✓ can start Firefox with a jetpack extension (3647ms)
        ✓ can start Firefox with a normal extension (2582ms)
        ✓ can start Firefox with multiple extensions (2976ms)
        can start Firefox with custom preferences
          ✓ profile created from scratch (3069ms)
          ✓ profile created from template (2402ms)
      binary management
        ✓ can start multiple sessions with single binary instance (3868ms)
      context switching
        ✓ can get context
        ✓ can set context (42ms)
        ✓ throws on unknown context

  Profile
    setPreference
      ✓ allows setting custom properties
      ✓ allows overriding mutable properties
      ✓ throws if setting a frozen preference
    writeToDisk
      ✓ copies template directory recursively (207ms)
      ✓ does not copy lock files (109ms)
      user.js
        ✓ writes defaults (104ms)
        ✓ merges template user.js into preferences (99ms)
        ✓ ignores frozen preferences when merging template user.js (100ms)
      extensions
        ✓ are copied into new profile directory (106ms)
    encode
      ✓ excludes the bundled WebDriver extension


  22 passing (48s)
```

I'm trying to determine if this is a geckodriver bug or if I'm building the profile incorrectly on Windows.  I don't have easy access to a Windows VM at the moment, so I'm going to have to lean on you for debugging :)

**Comment by fippo** [comment]
i'm your remote :open_hands:
Still on 8d8ffdd0fd2bce8fa864452cc265cf47e779dfa1
```
Not using buckd because watchman isn't installed.
  extension
    √ can install a jetpack xpi file (47ms)
    √ can install a normal xpi file
    √ can install an extension from a directory (44ms)

  [firefox]
    firefox
      Options
Skipping test: could not find Firefox Dev Edition: Error: Could not locate Firefox on the current system
        √ can start Firefox with a jetpack extension
Skipping test: could not find Firefox Dev Edition: Error: Could not locate Firefox on the current system
        √ can start Firefox with a normal extension
Skipping test: could not find Firefox Dev Edition: Error: Could not locate Firefox on the current system
        √ can start Firefox with multiple extensions
        can start Firefox with custom preferences
          √ profile created from scratch (3551ms)
          1) profile created from template
      binary management
        √ can start multiple sessions with single binary instance (6373ms)
      context switching
        √ can get context
        √ can set context (106ms)
        √ throws on unknown context

  Profile
    setPreference
      √ allows setting custom properties
      √ allows overriding mutable properties
      √ throws if setting a frozen preference
    writeToDisk
      2) copies template directory recursively
      3) does not copy lock files
      user.js
        4) writes defaults
        5) merges template user.js into preferences
        6) ignores frozen preferences when merging template user.js
      extensions
        7) are copied into new profile directory
    encode
      8) excludes the bundled WebDriver extension


  14 passing (49s)
  8 failing

1) [firefox] firefox Options can start Firefox with custom preferences profile created from template:

      AssertionError: 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0' === 'foo;bar'
      + expected - actual

      -Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
      +foo;bar

      at testing\assert.js:342:14
      at evaluate (testing\assert.js:92:3)
      at Assertion.isEqualTo (testing\assert.js:341:12)
      at Assertion.equalTo (testing\assert.js:325:17)
      at test\firefox\firefox_test.js:88:31
      at next (native)
      at pump (lib\promise.js:3288:25)
      at callNext (lib\promise.js:3274:7)
      at ManagedPromise.invokeCallback_ (lib\promise.js:1366:14)
      at TaskQueue.execute_ (lib\promise.js:3037:14)
      at TaskQueue.executeNext_ (lib\promise.js:3020:27)
      at asyncRun (lib\promise.js:2880:27)
      at lib\promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: [firefox] firefox Options can start Firefox with custom preferences profile created from template
      at Context.ret (testing\index.js:183:10)

  2) Profile writeToDisk copies template directory recursively:
     Error: the string "Invalid filename" was thrown, throw an Error :)


  3) Profile writeToDisk does not copy lock files:
     Error: the string "Invalid filename" was thrown, throw an Error :)


  4) Profile writeToDisk user.js writes defaults:
     Error: the string "Invalid filename" was thrown, throw an Error :)


  5) Profile writeToDisk user.js merges template user.js into preferences:
     Error: the string "Invalid filename" was thrown, throw an Error :)


  6) Profile writeToDisk user.js ignores frozen preferences when merging template user.js:
     Error: the string "Invalid filename" was thrown, throw an Error :)


  7) Profile writeToDisk extensions are copied into new profile directory:
     Error: the string "Invalid filename" was thrown, throw an Error :)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  8) Profile encode excludes the bundled WebDriver extension:

      AssertionError: false == true
      + expected - actual

      -false
      +true

      at test\firefox\profile_test.js:172:16
```

geckodriver version is still 0.13.0

**Comment by jleyba** [comment]
Any chance you're running through the Selenium standalone server instead of using geckodriver directly? I was able to reproduce this failure on OSX when running the tests against the java server.

```sh
$ java -jar selenium-server-standalone-3.1.0.jar &
$ SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub mocha -t 12000000 test/firefox/firefox_test.js --grep "custom preferences"
Running tests against [firefox]
Using remote server http://localhost:4444/wd/hub
Promise manager is enabled? true

  [firefox]
    firefox
      Options
        can start Firefox with custom preferences
          ✓ profile created from scratch (2772ms)
          1) profile created from template


  1 passing (25s)
  1 failing

  1) [firefox] firefox Options can start Firefox with custom preferences profile created from template:

      AssertionError: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0' === 'foo;bar'
      + expected - actual

      -Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0
      +foo;bar
      
      at testing/assert.js:342:14
      at evaluate (testing/assert.js:92:3)
      at Assertion.isEqualTo (testing/assert.js:341:12)
      at Assertion.equalTo (testing/assert.js:325:17)
      at test/firefox/firefox_test.js:86:31
      at Generator.next (<anonymous>)
      at pump (lib/promise.js:3343:25)
      at callNext (lib/promise.js:3329:7)
      at ManagedPromise.invokeCallback_ (lib/promise.js:1384:14)
      at TaskQueue.execute_ (lib/promise.js:3092:14)
      at TaskQueue.executeNext_ (lib/promise.js:3075:27)
      at asyncRun (lib/promise.js:2935:27)
      at lib/promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: [firefox] firefox Options can start Firefox with custom preferences profile created from template
      at Context.ret (testing/index.js:183:10)
```

**Comment by fippo** [comment]
I'm not using selenium-server but can reproduce the situation when doing so as well. Hopefully the same issue

**Comment by fippo** [comment]
Seems to work again with Firefox 52, selenium-webdriver 3.3.0 and geckodriver 1.4.0.

Lets close the issue?

**Comment by fippo** [comment]
seems I spoke too soon :-/
Also happens in Firefox 47.
