### ISSUE TITLE
node issue

### ISSUE THREAD

**Issue by Sigura** [SeleniumHQ/selenium#3313]
osx
node 4.6.2

```
> $ mocha ./test/checklist.js
/Users/sigura/work/taxlien/taxliencloud/app/node_modules/selenium-webdriver/index.js:115
  static createSession(...args) {}
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sigura/work/taxlien/taxliencloud/app/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/sigura/work/taxlien/taxliencloud/app/test/checklist.js:2:1)
    at Module._compile (module.js:409:26)
    at loader (/Users/sigura/work/taxlien/taxliencloud/app/node_modules/babel-register/lib/node.js:144:5)
```

same result with `mocha --require ./server.babel.js --require babel-polyfill --compilers js:babel-register ./test/checklist.js`

tried run dummy test:

```
before('Init', () => this.timeout(200000));

class Test {
  static createSession(...args) {
    console.log(args);
  }
}

describe('Main workflow', () => {
  Test.createSession(1, 2, 3)
});
```

works fine

**Comment by Sigura** [comment]
works correct only on node@7

**Comment by Sigura** [comment]
solved by adding:

"ignore": false,

to `.babelrc`

**Comment by AutomatedTester** [comment]
closing since this was solved by user

**Comment by trotzig** [comment]
Could this be a real issue after all? `selenium-webdriver` claims to support Node 4 and up, yet it is using [rest parameters](https://github.com/SeleniumHQ/selenium/blob/d943ee2950e25a2f4a3492058107cfd005d6f7fd/javascript/node/selenium-webdriver/lib/http.js#L161) which isn't supported by default in Node 4 and 5 (if I'm not mistaken). I'm getting errors in Node v4 and v5 (but not v6 and v7) when running a jest test with selenium-webdriver 3.0.1: 

```
 SyntaxError: Unexpected token ...
      
      at transformAndBuildScript (node_modules/jest/node_modules/jest-cli/node_modules/jest-runtime/build/transform.js:320:12)
      at Object.<anonymous> (node_modules/selenium-webdriver/http/index.js:29:17)
      at Object.<anonymous> (node_modules/selenium-webdriver/firefox/index.js:119:12)
```

I believe this is coming from https://github.com/SeleniumHQ/selenium/blob/d943ee2950e25a2f4a3492058107cfd005d6f7fd/javascript/node/selenium-webdriver/lib/http.js#L161

It looks like Node 4 and 5 [do support rest parameters](http://node.green/#rest-parameters), but only with the `--harmony` flag.

**Comment by jleyba** [comment]
As of [3.0](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v300), selenium-webdriver requires [node 6.9 or newer](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/package.json#L23).

**Comment by trotzig** [comment]
I see. I just re-read the docs, and even though they are a little confusing it's stated that LTS (6.9.1) and stable (7 something) are the only supported versions. Makes sense, thanks for clarifying @jleyba!
