### ISSUE TITLE
running Protractor 5.0.0 & Selenium standalone server 3.0.0beta4 & Firefox 37

### ISSUE THREAD

**Issue by IgalOre** [SeleniumHQ/selenium#3404]
Bug report
---

Following issue number [#3993](https://github.com/angular/protractor/issues/3993), running Protractor 5.0.0 & Selenium standalone server 3.0.0beta4 & Firefox 37
Reason for not upgrading yet to FF 50, since testing VM's should be compatible with older version of Selenium on Java test suits.
Applying fix using Selenium standalone server 3.0.0beta4 not seems to be working.

- Node Version: `6.9.1`
- Protractor Version: `5.0.0`
- Angular Version: `1.5.8`
- Browser(s): `Firefox`
- Operating System and Version os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_77'
- Your protractor configuration file
```
exports.config = {
    // seleniumAddress: 'http://localhost:4444/wd/hub',
    seleniumServerJar: '../../node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.0.0-beta4.jar',
    specs: ['**/*-spec.js'],
    // specs: ['specs/sidebar-spec.js', 'specs/back_button-spec.js'],
    baseUrl: 'http://localhost:3000',
    directConnect: false,
    capabilities: {
      browserName: 'firefox'
    },
    // jvmArgs: ['-Dwebdriver.firefox.bin=c:/Program Files (x86)/Mozilla Firefox/firefox.exe'],
    jvmArgs: ['-Dwebdriver.firefox.bin=c:/Program Files (x86)/Mozilla Firefox/firefox.exe',
        '-Dwebdriver.gecko.driver=./node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.13.0.exe'],
    onPrepare: function() {
        'use strict';
        var reporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new reporters.TeamCityReporter());
        var junitReporter = new reporters.JUnitXmlReporter({savePath: 'test/coverage/protractor/', filePrefix: 'UI-TEST-results'});
        jasmine.getEnv().addReporter(junitReporter);
    },
    debug:true
    // nodeDebug: true
};
```
- A relevant example test
- Output from running the test
```
[16:24:27] D/launcher - Running with --troubleshoot
[16:24:27] D/launcher - Protractor version: 5.0.0
[16:24:27] D/launcher - Your base url for tests is http://localhost:3000
[16:24:27] I/local - Starting selenium standalone server...
[16:24:27] I/launcher - Running 1 instances of WebDriver
[16:24:27] I/local - Selenium standalone server started at http://172.16.105.37:62875/wd/hub
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://172.16.105.37:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://172.16.105.37:3001
 --------------------------------------
[BS] Serving files from: demo
[16:24:39] E/launcher - Unable to create new remote session. desired capabilities = Capabilities [{count=1, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@44fa6589, browserName=firefox, moz:firefoxOptions={}}], required capabilities = Capabilities [{}]
Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:29:23 -0700'
System info: host: 'DevRegAppW01', ip: '172.16.105.37', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
[16:24:39] E/launcher - SessionNotCreatedError: Unable to create new remote session. desired capabilities = Capabilities [{count=1, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@44fa6589, browserName=firefox, moz:firefoxOptions={}}], required capabilities = Capabilities [{}]
Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:29:23 -0700'
System info: host: 'DevRegAppW01', ip: '172.16.105.37', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
    at WebDriverError (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
    at SessionNotCreatedError (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:214:5)
    at Object.checkLegacyResponse (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:640:55)
    at createDriver (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\index.js:629:16)
    at Local.getNewDriver (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\lib\driverProviders\driverProvider.ts:57:29)
    at Runner.createBrowser (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\lib\runner.ts:187:39)
    at driverprovider_.setupEnv.then (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\lib\runner.ts:279:27)
    at _fulfilled (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\q\q.js:796:13)
[16:24:39] E/launcher - Process exited with error code 199
[16:24:39] Protractor run failed with code : 199

```
- Steps to reproduce the bug
Re-run protractor tests

**Comment by barancev** [comment]
Please profice a reproduction scenario using just Selenium client library, without Protractor

**Comment by IgalOre** [comment]
I'm not sure to follow your comment, since in our project we exclusively using Protractor for UI testing i'm not sure how to build example that will reproduce issue without it, since it will be not relevant for what we doing. Can you point me out to example where only Selenium client library are used ?

**Comment by barancev** [comment]
OK, at least provide a [concise reproducible test case](http://sscce.org/) using Protractor. And of course, retest on the latest Selenium version that is 3.4.0 at the moment.

**Comment by barancev** [comment]
Closing the issue, there is no reporoduction scenario provided.
