### ISSUE TITLE
Chrome Driver Error

### ISSUE THREAD

**Issue by Kurimatzu** [SeleniumHQ/selenium#3417]
[1664:7196:0126/161642:ERROR:connection.cc(1892)] Shortcuts sqlite error 26, errno 0: file is encrypted or is not a database, sql: PRAGMA auto_vacuum
[1664:7196:0126/161642:ERROR:connection.cc(1892)] Shortcuts sqlite error 26, errno 0: file is encrypted or is not a database, sql: SELECT COUNT(*) FROM sqlite_master
[1664:7196:0126/161642:ERROR:connection.cc(1892)]  sqlite error 26, errno -2: file is encrypted or is not a database, sql: ATTACH DATABASE ? AS ?
[1664:7196:0126/161642:ERROR:connection.cc(1892)] Shortcuts sqlite error 26, errno 0: file is encrypted or is not a database, sql: PRAGMA auto_vacuum
[1664:7196:0126/161642:ERROR:connection.cc(1892)] Shortcuts sqlite error 26, errno 0: file is encrypted or is not a database, sql: PRAGMA journal_mode = TRUNCATE
[1664:7196:0126/161642:ERROR:connection.cc(1892)] Shortcuts sqlite error 26, errno 0: file is encrypted or is not a database, sql: SELECT name FROM sqlite_master WHERE type=? AND name=? COLLATE NOCASE
[1664:7196:0126/161642:ERROR:connection.cc(1892)] Shortcuts sqlite error 26, errno 0: file is encrypted or is not a database, sql: SELECT name FROM sqlite_master WHERE type=? AND name=? COLLATE NOCASE
[1664:7196:0126/161642:ERROR:connection.cc(1892)] Shortcuts sqlite error 26, errno 0: file is encrypted or is not a database, sql: CREATE TABLE omni_box_shortcuts (id VARCHAR PRIMARY KEY, text VARCHAR, fill_into_edit VARCHAR, url VARCHAR, contents VARCHAR, contents_class VARCHAR, description VARCHAR, description_class VARCHAR, transition INTEGER, type INTEGER, keyword VARCHAR, last_access_time INTEGER, number_of_hits INTEGER)
[1664:7196:0126/161642:ERROR:connection.cc(1892)] Shortcuts sqlite error 26, errno 0: file is encrypted or is not a database, sql: SELECT id, text, fill_into_edit, url, contents, contents_class, description, description_class, transition, type, keyword, last_access_time, number_of_hits FROM omni_box_shortcuts
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'DESKTOP-0ULK73N', ip: '192.168.0.3', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_112'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:174)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:163)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:120)
	at vsfgsfsg.f.main(f.java:12)
Caused by: java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...
	at org.apache.commons.exec.DefaultExecuteResultHandler.getException(DefaultExecuteResultHandler.java:76)
	at org.openqa.selenium.os.UnixProcess.checkForError(UnixProcess.java:173)
	at org.openqa.selenium.os.CommandLine.checkForError(CommandLine.java:185)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:177)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:166)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	... 7 more

**Comment by lmtierney** [comment]
Please read this [Bug Reports](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports) and update your issue
