### ISSUE TITLE
IE Browser - Unable to create new remote session

### ISSUE THREAD

**Issue by RoccoRaj** [SeleniumHQ/selenium#3456]
## Meta -
OS:  Windows Server 2008/2012 (Virtual machine)
Selenium Version:  2.48.2/3.0.1
Browser:  Internet Explorer 
Browser Version:  11.0.9600.18059
Executables used: IEDriverServer 2.53.1, 3.0.0 (both 32-bit)

## Expected Behavior - 
IE Browser must launch using IEDriverServer.exe 32-bit file and perform every other actions on it
 
## Actual Behavior - 
While trying to launch IE browser using IEDriverServer.exe 2.53.1(32-bit) file on a **remote** machine, then throws the following error:

**Unable to create new remote session. desired capabilities = Capabilities [{ensureCleanSession=true, nativeEvents=false, ie.forceCreateProcessApi=true, browserName=internet explorer, ignoreProtectedModeSettings=true, version=, platform=WINDOWS}], required capabilities = Capabilities [{}] Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700' System info: host: 'CTST40Q-SHR-08', ip: '172.25.43.62', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_102' Driver info: driver.version: RemoteWebDriver** 

**Full Stack trace  information:**
org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91), org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141), org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601), org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241), org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:128), org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:155), sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method), sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62), sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45), java.lang.reflect.Constructor.newInstance(Constructor.java:423), org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77), org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102), org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194), actions.selenium.Browser.run(Browser.groovy:279), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90), groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233), groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085), groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909), org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848), org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831), org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:164), redwood.launcher.Launcher.runAction(Launcher.groovy:155), redwood.launcher.Launcher$runAction.callStatic(Unknown Source), org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:165), redwood.launcher.Launcher$_main_closure1_closure6_closure7.doCall(Launcher.groovy:73), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90), groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233), org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272), groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909), groovy.lang.Closure.call(Closure.java:411), groovy.lang.Closure.call(Closure.java:427), org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForLine(DefaultGroovyMethods.java:3883), org.codehaus.groovy.runtime.IOGroovyMethods.eachLine(IOGroovyMethods.java:463), org.codehaus.groovy.runtime.IOGroovyMethods.eachLine(IOGroovyMethods.java:416), org.codehaus.groovy.runtime.IOGroovyMethods.eachLine(IOGroovyMethods.java:400), org.codehaus.groovy.runtime.dgm$654.invoke(Unknown Source), org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271), org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53), org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45), org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108), org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116), redwood.launcher.Launcher$_main_closure1_closure6.doCall(Launcher.groovy:67), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90), groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233), org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272), groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909), groovy.lang.Closure.call(Closure.java:411), org.codehaus.groovy.runtime.SocketGroovyMethods.withStreams(SocketGroovyMethods.java:60), org.codehaus.groovy.runtime.dgm$868.invoke(Unknown Source), org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271), org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53), org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45), org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108), org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116), redwood.launcher.Launcher$_main_closure1.doCall(Launcher.groovy:65), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90), groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233), org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272), groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909), groovy.lang.Closure.call(Closure.java:411), groovy.lang.Closure.call(Closure.java:427), org.codehaus.groovy.runtime.SocketGroovyMethods.invokeClosureWithSocket(SocketGroovyMethods.java:189), org.codehaus.groovy.runtime.SocketGroovyMethods.access$000(SocketGroovyMethods.java:42), org.codehaus.groovy.runtime.SocketGroovyMethods$1.run(SocketGroovyMethods.java:178), java.lang.Thread.run(Thread.java:745)]

## Steps to reproduce -
Try launching the IE browser using the following code and using the above ## Meta

def serviceIE = new InternetExplorerDriverService.Builder().usingPort(9516).usingDriverExecutable(new File("IEDriverServer.exe")).build()
serviceIE.start()
DesiredCapabilities d = DesiredCapabilities.internetExplorer()
d.setCapability("nativeEvents", false)
d.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true)
d.setCapability(InternetExplorerDriver.FORCE_CREATE_PROCESS, true);
d.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
Driver = new RemoteWebDriver(serviceIE.getUrl(),d)

**Note:**
The following changes were made on a machine
1.	IE-ESC was disabled
2.	Enhanced Protected Mode was disabled i.e. Enable Enhanced Protected Mode was not ticked
3.	Protected Mode Security setting were same for all the Zones(Disabled)
4.	Created DWORD value for the key HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE for a 64-bit machine

Please let me know if you require any other information.

Thanks!

**Comment by AsDuang** [comment]
同问

**Comment by jimevans** [comment]
@RoccoRaj Are you trying to launch `IEDriverServer.exe` on one machine, and use `RemoteWebDriver` to automate it directly, without running the Java standalone server? If so, that won't work. `IEDriverServer.exe` is configured to reject all HTTP requests coming from other than localhost. This is by design, and is a security feature.

**Comment by jimevans** [comment]
No response from reporter. Closing issue.

**Comment by vana24** [comment]
I am still facing the same issue "org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{ensureCleanSession=true, browserName=internet explorer, javascriptEnabled=true, version=, platform=WINDOWS}], required capabilities = Capabilities [{}]"

Please let me know if there is a solution or workaround. thanks

**Comment by brobee** [comment]
Same issue here. Standalone server is running, node is running, in the node console I see my tests are connected to it but I got the error what the original reporter posted. Any solution?

**Comment by kyxap** [comment]
Same here:
Node console:
```09:54:25.889 INFO - The node is registered to the hub and ready to use
2018-01-26 09:54:46.636:INFO:osjshC.ROOT:qtp1908981452-13: org.openqa.selenium.r
emote.server.WebDriverServlet-59474f18: Initialising WebDriverServlet
09:54:46.662 INFO - Found handler: org.openqa.selenium.remote.server.commandhand
ler.BeginSession@5b145a6c
09:54:46.668 INFO - /session: Executing POST on /session (handler: BeginSession)

09:54:46.744 INFO - Capabilities are: Capabilities {acceptSslCerts: true, browse
rName: internet explorer, enableElementCacheCleanup: true, ensureCleanSession: t
rue, ie.browserCommandLineSwitches: true, ie.ensureCleanSession: true, ie.forceC
reateProcessApi: true, ignoreProtectedModeSettings: true, javascriptEnabled: tru
e, platform: WINDOWS, requireWindowFocus: true, version: 11}
09:54:46.747 INFO - Capabilities {acceptSslCerts: true, browserName: internet ex
plorer, enableElementCacheCleanup: true, ensureCleanSession: true, ie.browserCom
mandLineSwitches: true, ie.ensureCleanSession: true, ie.forceCreateProcessApi: t
rue, ignoreProtectedModeSettings: true, javascriptEnabled: true, platform: WINDO
WS, requireWindowFocus: true, version: 11} matched class org.openqa.selenium.rem
ote.server.ServicedSession$Factory (provider: org.openqa.selenium.ie.InternetExp
lorerDriverService)```

Failed with: ```java.lang.AssertionError: Unable to create new service: InternetExplorerDriverService```

**Comment by CScharer** [comment]
Ditto:

org.openqa.selenium.SessionNotCreatedException: Unable to create session from org.openqa.selenium.remote.NewSessionPayload@3cb627e5
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'CSCHARER-LAPTOP', ip: '169.254.184.113', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:367)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:113)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at com.cjs.qa.selenium.SeleniumDriver.initializeWebDriver(SeleniumDriver.java:359)
	at com.cjs.qa.junit.tests.Scenarios.jenkins_WebDriverValidate(Scenarios.java:514)
	at com.cjs.qa.junit.tests.Scenarios.Jenkins(Scenarios.java:501)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create session from org.openqa.selenium.remote.NewSessionPayload@3cb627e5
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'CSCHARER-LAPTOP', ip: '169.254.184.113', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'CSCHARER-LAPTOP', ip: '169.254.184.113', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$4(NewSessionPipeline.java:75)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$5(NewSessionPipeline.java:74)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$1(WebDriverServlet.java:246)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by barancev** [comment]
Please don't hijack issue closed more than year ago, you definitely don't have the *same* issue.
