### ISSUE TITLE
Erro in class invisibility_of_element_located

### ISSUE THREAD

**Issue by reinaldorossetti** [SeleniumHQ/selenium#3465]
OS:  
Windows 10
Selenium Version:  
3.0.2, IDE ATOM
Browser:  
Firefox and Chromium

Browser Version:  
FF 51.01 (64-bit)
Chromie Versão 55.0.2883.87 m

Script Test:

```
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from time import sleep
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.common.exceptions import ElementNotVisibleException
from selenium.common import exceptions

driver = webdriver.Firefox()
driver.get("http://www.jqueryrain.com/?eKV1bCMa")

def wait_element_present(driver, elem):
    present = WebDriverWait(driver, 60).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, elem))
    )
    print(present)
    return present

def wait_element_not_present(driver, elem):
    present = WebDriverWait(driver, 15, ignored_exceptions=\
            exceptions.NoSuchElementException).until(
        expected_conditions.invisibility_of_element_located((By.CSS_SELECTOR, elem))
    )
    print(present)
    return present

driver.switch_to.frame(0)
button = wait_element_present(driver, "button#quick_demo")
button.click()

test = wait_element_present(driver, ".loadingoverlay")
test2 = wait_element_not_present(driver, ".loadingoverlay")
```

Show Error:

```
<selenium.webdriver.firefox.webelement.FirefoxWebElement (session="f2103a91-b8b9-46a0-bc0b-b8600151608e", element="a1573d62-794a-4fd8-8a06-6ee16b6046be")>
<selenium.webdriver.firefox.webelement.FirefoxWebElement (session="f2103a91-b8b9-46a0-bc0b-b8600151608e", element="977eaa87-b6ee-4404-84df-3776569a314b")>
<selenium.webdriver.firefox.webelement.FirefoxWebElement (session="f2103a91-b8b9-46a0-bc0b-b8600151608e", element="977eaa87-b6ee-4404-84df-3776569a314b")>
<selenium.webdriver.firefox.webelement.FirefoxWebElement (session="f2103a91-b8b9-46a0-bc0b-b8600151608e", element="977eaa87-b6ee-4404-84df-3776569a314b")>
<selenium.webdriver.firefox.webelement.FirefoxWebElement (session="f2103a91-b8b9-46a0-bc0b-b8600151608e", element="977eaa87-b6ee-4404-84df-3776569a314b")>
<selenium.webdriver.firefox.webelement.FirefoxWebElement (session="f2103a91-b8b9-46a0-bc0b-b8600151608e", element="977eaa87-b6ee-4404-84df-3776569a314b")>
{"error":"no such element","message":"Unable to locate element: .loadingoverlay"}
Traceback (most recent call last):
  File "D:\Dropbox\Dropbox\Meu Curso de Selenium\testes\loading_page.py", line 32, in <module>
    test2 = wait_element_not_present(driver, ".loadingoverlay")
  File "D:\Dropbox\Dropbox\Meu Curso de Selenium\testes\loading_page.py", line 22, in wait_element_not_present
    expected_conditions.invisibility_of_element_located((By.CSS_SELECTOR, elem))  File "C:\Python35-32\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Python35-32\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 197, in __call__
    return _element_if_visible(_find_element(driver, self.locator), False)
  File "C:\Python35-32\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 99, in _element_if_visible
    return element if element.is_displayed() == visibility else False
AttributeError: 'str' object has no attribute 'is_displayed'

Process returned 1 (0x1)   execution time : 24.619 s
Pressione qualquer tecla para continuar. . .
```

I look the code in selenium this is wrong code in _find_element(driver, self.locator) because exception inside the function is string, exception webdriver not work, return string not one webelement, this not  has no attribute 'is_displayed':

    def __init__(self, locator):
        self.locator = locator

    def __call__(self, driver):
        try:
            return _element_if_visible(_find_element(driver, self.locator), False)
        except (NoSuchElementException, StaleElementReferenceException):
            # In the case of NoSuchElement, returns true because the element is
            # not present in DOM. The try block checks if the element is present
            # but is invisible.
            # In the case of StaleElementReference, returns true because stale
            # element reference implies that element is no longer visible.
            return True

    try:
>>> Do not give a webdriver exception here
        return driver.find_element(*by)
    except NoSuchElementException as e:
        raise e
    except WebDriverException as e:
        raise e

Need verified element before to Solve this problem in function _find_element:
```
    try:
        element  = driver.find_element(*by)
        if isinstance(element, str) or isinstance(element, dict):
            raise StaleElementReferenceException("Invalid locator")
        return element

```

**Comment by lmtierney** [comment]
Closing as the script is no longer valid. If you are still experiencing this with the latest versions, please create a new issue.
