### ISSUE TITLE
Selenium::WebDriver::Error::JavascriptError: Element reference not seen before

### ISSUE THREAD

**Issue by bob2build** [SeleniumHQ/selenium#3471]
This seems to be an issue isolated only with new release 3.0.6. The code works perfectly fine with older releases including 3.0.5. I had updated geckodriver driver to the latest version and issue still persists. 

## Meta -
OS:  
Linux (Feodra, CENTOS)
Selenium Version:  
3.0.6
Browser:  
firefox

Browser Version:  
Mozilla Firefox 48.0.1

## Expected Behavior -
No exception.

## Actual Behavior -
```
     Selenium::WebDriver::Error::JavascriptError:
       Element reference not seen before: %7B%22element-6066-11e4-a52e-4f735466cecf%22=%3E%223799ee0c-b2df-499d-9f7e-d6acd93d2661%22%7D
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/remote/http/common.rb:85:in `new'
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/remote/http/common.rb:85:in `create_response'
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/remote/http/common.rb:63:in `call'
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/remote/w3c_bridge.rb:638:in `raw_execute'
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/remote/w3c_bridge.rb:613:in `execute'
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/remote/w3c_bridge.rb:546:in `element_displayed?'
     # /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.6/lib/selenium/webdriver/common/element.rb:205:in `displayed?'
     # /var/lib/gems/2.3.0/gems/capybara-2.12.0/lib/capybara/selenium/node.rb:130:in `visible?'
     # /var/lib/gems/2.3.0/gems/capybara-2.12.0/lib/capybara/node/element.rb:269:in `block in visible?'
     # /var/lib/gems/2.3.0/gems/capybara-2.12.0/lib/capybara/node/base.rb:81:in `synchronize'
     # /var/lib/gems/2.3.0/gems/capybara-2.12.0/lib/capybara/node/element.rb:269:in `visible?'
     # /var/lib/gems/2.3.0/gems/capybara-2.12.0/lib/capybara/queries/selector_query.rb:78:in `matches_filters?'
     # /var/lib/gems/2.3.0/gems/capybara-2.12.0/lib/capybara/result.rb:29:in `block in initialize'
```
## Steps to reproduce -
Attaching a simple code that fails
```
require 'capybara/rspec'
require 'headless'

# Capybara
Capybara.default_driver = :selenium
Capybara.default_max_wait_time = 20
Capybara.app_host = 'http://ozlo.ai'
Capybara.server_port = 3000
Capybara.run_server = false #Whether start server when testing
Capybara.default_selector = :css #:xpath #default selector , you can change to :css
Capybara.javascript_driver = :selenium #default driver when you using @javascript tag

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
    expectations.syntax = [:should, :expect]
  end
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
  config.include Capybara::DSL
end

RSpec.describe "Website Smoke Tests", :type => :request do
  describe "ozlo.ai" do
    headless = Headless.new(display: 99, autopick: true, reuse: false, destroy_at_exit: true).start
    it "home page contains You can try him out here" do
      visit "https://ozlo.ai"
      expect(page).to have_text 'You can try him out here'
    end
end
```

**Comment by bob2build** [comment]
Current workaround is to lock selenium-webdriver version to 3.0.5 in GemFile
```
gem 'selenium-webdriver', '= 3.0.5'
```

**Comment by twalpole** [comment]
3.0.6 has a bug where the id on elements returned from `find_elements_by` with marionette isn't set correctly - https://github.com/SeleniumHQ/selenium/commit/7ab196ed17d289a0dc67ac32b7751ea23f876666

**Comment by titusfortner** [comment]
Can you send me a reproduction in Selenium & not Capybara? Or you can set `$DEBUG = true` and send me the output.

[All of the specs are passing](https://travis-ci.org/SeleniumHQ/selenium/builds/198719087) (including the one that @twalpole updated), and this example is working for me just fine:

```
2.4.0 :007 > driver = Selenium::WebDriver.for :firefox
 => #<Selenium::WebDriver::Driver:0x612493705458d9a6 browser=:firefox> 
2.4.0 :008 > driver.navigate.to "https://ozlo.ai"
 => #<Selenium::WebDriver::Remote::Response:0x007fca899e5560 @code=200, @payload={}> 
2.4.0 :009 > driver.find_element(tag_name: 'body').text
 => "Ozlo Avatar\nThe friendly assistant who helps you get things done — find restaurants, discover recipes, order delivery, buy movie tickets and more!\nDownload on the\nApp Store\nGET IT ON\nGoogle Play\nOzlo is made to use on the go — download the app to access all his features.\nYou can try him out here 👉\nGreetings, human! I'm Ozlo.\nI'm a friendly assistant who can help you find places to eat, things to do and more.\nWhere should we start?\nSwipe to see more\nSign in/Sign up\nSee my stats\nShare with friends\nWhat can you do, Ozlo?\nDinner tonight 🍴\nWeekend brunch\nMovies in theaters 🎥\nWeather nearby\nToday's top headlines\nPokéStops nearby 💦🐢\nBars with outdoor seating here\nHappy hour around here\nBest Chinese restaurant nearby\nRestaurants that serve noodles\nGood pasta restaurant nearby\nSports bars around here\nSushi for dinner near me\nSomething else\nSend\nJobs\nSupport\nPrivacy Policy\nTerms of Service\n© 2017 Ozlo Inc. All rights reserved.\nCrafted in Palo Alto & Seattle" 
```

**Comment by titusfortner** [comment]
Oh, and Firefox 48 is no longer supported. In the past Selenium has supported Production, Production - 1; ESR & ESR - 1. Additionally, at this point, we're recommending people use Firefox Nightly since that has the most up to date implementation of Marionette.

**Comment by titusfortner** [comment]
Ah, looks like an issue when comparing with javascript execute_script which we didn't have a fix for.
3.0.6 has been yanked, and 3.0.7 is now released.
