### ISSUE TITLE
Cannot create instance of selenium-webdriver with node 5.4.1

### ISSUE THREAD

**Issue by linhtran174** [SeleniumHQ/selenium#3482]
I were able to successfully build and run your demo with lastest node (6.9.5) which is stated to have "best-effort", but not with node 5.4.1 which is stated "supported".

$ node index.js
C:\Users\8470p\Desktop\Se2Node\node_modules\selenium-webdriver\index.js:115
  static createSession(...args) {}
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\8470p\Desktop\Se2Node\index.js:1:79)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)

**Comment by jleyba** [comment]
The versions in the README were all for hypothetical examples. To avoid confusion, I've updated the docs to reference the current LTS.

For reference, the minimum supported version was pegged at 6.9.0 LTS with the release of selenium-webdriver 3.0.0:

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v300
