### ISSUE TITLE
IE browser throwing 'Browser window was closed' error in selenium 3.0.1

### ISSUE THREAD

**Issue by ambikashri** [SeleniumHQ/selenium#3487]
OS:  
Windows 10
Selenium Version:  
3.0.1
Browser:  
Internet Explorer 11

I am trying to make my script run in IE 11 using Selenium grid 3.0.1. The IE 11 browser opens and goes to the specified url but after some time the script stop and throws "browser window was closed" error although I can see the the IE browser still open.

Below is the error

`"browser window was closed"
"[\"[remote server] sun.reflect.NativeConstructorAccessorImpl():-2:in `newInstance0'\", \"[remote server] sun.reflect.NativeConstructorAccessorImpl():-1:in `newInstance'\", \"[remote server] sun.reflect.DelegatingConstructorAccessorImpl():-1:in `newInstance'\", \"[remote server] java.lang.reflect.Constructor():-1:in `newInstance'\", \"[remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):216:in `createThrowable'\", \"[remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):168:in `throwIfResponseFailed'\", \"[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):635:in `execute'\", \"[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):322:in `get'\", \"[remote server] sun.reflect.NativeMethodAccessorImpl():-2:in `invoke0'\", \"[remote server] sun.reflect.NativeMethodAccessorImpl():-1:in `invoke'\", \"[remote server] sun.reflect.DelegatingMethodAccessorImpl():-1:in `invoke'\", \"[remote server] java.lang.reflect.Method():-1:in `invoke'\", \"[remote server] org.openqa.selenium.support.events.EventFiringWebDriver$2(EventFiringWebDriver.java):103:in `invoke'\", \"[remote server] com.sun.proxy.$Proxy6():-1:in `get'\", \"[remote server] org.openqa.selenium.support.events.EventFiringWebDriver(EventFiringWebDriver.java):162:in `get'\", \"[remote server] org.openqa.selenium.remote.server.handler.ChangeUrl(ChangeUrl.java):40:in `call'\", \"[remote server] org.openqa.selenium.remote.server.handler.ChangeUrl(ChangeUrl.java):25:in `call'\", \"[remote server] java.util.concurrent.FutureTask():-1:in `run'\", \"[remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'\", \"[remote server] java.util.concurrent.ThreadPoolExecutor():-1:in `runWorker'\", \"[remote server] java.util.concurrent.ThreadPoolExecutor$Worker():-1:in `run'\", \"[remote server] java.lang.Thread():-1:in `run'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:81:in `new'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:86:in `request'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:631:in `execute'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:136:in `get'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/navigation.rb:32:in `to'\", \"C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/browser.rb:77:in `goto'\"]"
"Unable to get browser (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 7 milliseconds\nBuild info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'\nSystem info: host: '****', ip: '*.*.*.*', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_31'\nDriver info: org.openqa.selenium.ie.InternetExplorerDriver\nCapabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=false, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=true, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=false, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=true, browserName=internet explorer, initialBrowserUrl=http://localhost:11590/, javascriptEnabled=true, ignoreProtectedModeSettings=true, enableElementCacheCleanup=true, unexpectedAlertBehaviour=accept}]\nSession ID: 02fd3f97-4249-4736-a169-e88d4a97d745 (org.openqa.selenium.NoSuchWindowException)"`

The same is working fine with 2.53.1 grid version.

**Comment by Vrushabhh** [comment]
Actually some time when you goes to find element, It would not be present on the DOM at that time due to slow internet or other reason, that's why are sometime able to click and sometime not.

To overcome this issue you should try using WebDriverWait with ExpectedConditions.elementToBeClickable to wait before click on element until element visible on the DOM and clickable as below :-

WebDriverWait wait = new WebDriverWait(driver, 10);
el = wait.until(ExpectedConditions.elementToBeClickable(By.id("kfiDocumentLink")));
el.click();

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
