### ISSUE TITLE
Portable Firefox - Selenium connection problem

### ISSUE THREAD

**Issue by gamerchandu** [SeleniumHQ/selenium#3499]
## Meta -
OS:   Windows 7 
Selenium Version:   Selenium-server-standalone-3.0.1
Browser:   Portable Firefox
Browser Version:   V 51.0.1 

## Expected Behavior -
 Should open a webdriver connection and there to Google.com

## Actual Behavior -
Only Firefox profile page will open and "org.openqa.selenium.SessionNotCreatedException" exception

## Steps to reproduce -
  System.setProperty(GeckoDriverService.GECKO_DRIVER_EXE_PROPERTY," Path to \\geckodriver.exe");
   DesiredCapabilities capabilities = DesiredCapabilities.firefox();
 capabilities.setCapability("firefox_binary","path to FirefoxPortable.exe");
 WebDriver driver = new FirefoxDriver(desiredCapabilities);
driver.get("http://www.google.com");
    
Screenshot of actual output :
![firefoxerror](https://cloud.githubusercontent.com/assets/5535949/22885602/167f518c-f220-11e6-97d8-10404bf4354d.jpg)
 

Exception in Eclipse:

Feb 13, 2017 6:01:43 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Feb 13, 2017 6:22:50 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol.
Feb 13, 2017 6:43:57 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired 

capabilities = Capabilities [{firefox_binary=C:\Users\chanagondac\Downloads\FirefoxPortable\FirefoxPortable.exe, 

marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@1b68ddbd, browserName=firefox, 

moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@1b68ddbd, version=, platform=ANY, 

firefox_profile=org.openqa.selenium.firefox.F...}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'KIHYDL0433', ip: '172.31.224.217', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', 

java.version: '1.8.0_101'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)
	at sourceCode.Stack42154400.createFFDriver(Stack42154400.java:107)
	at sourceCode.Stack42154400.main(Stack42154400.java:86)

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
