### ISSUE TITLE
Exception in thread "Thread-4" org.openqa.selenium.UnsupportedCommandException: Error 404: Not Found File not found 

### ISSUE THREAD

**Issue by ascoolakash** [SeleniumHQ/selenium#3539]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lmtierney** [comment]
Please read this and update accordingly
https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports

**Comment by ascoolakash** [comment]
Exception in thread "Thread-4" org.openqa.selenium.UnsupportedCommandException: Error 404: Not Found
File not found
Command duration or timeout: 7.02 seconds
Build info: version: '2.25.0', revision: '17482', time: '2012-07-18 21:08:56'
System info: os.name: 'Windows Vista', os.arch: 'x86', os.version: '6.1', java.version: '1.6.0_02-ea'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:188)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:498)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:268)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:297)
	at org.openqa.selenium.By$ById.findElement(By.java:215)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:260)
	at sp_screens.transactionTypeRunnable.run(transactionTypeRunnable.java:23)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-5" org.openqa.selenium.UnsupportedCommandException: Error 404: Not Found
File not found
Command duration or timeout: 10 milliseconds
Build info: version: '2.25.0', revision: '17482', time: '2012-07-18 21:08:56'
System info: os.name: 'Windows Vista', os.arch: 'x86', os.version: '6.1', java.version: '1.6.0_02-ea'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:188)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:498)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:244)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:77)
	at sp_screens.transactionSubTypeRunnable.run(transactionSubTypeRunnable.java:19)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-6" java.lang.NullPointerException
	at sp_screens.orderTypeRunnable.run(orderTypeRunnable.java:18)
	at java.lang.Thread.run(Unknown Source)
org.openqa.selenium.UnsupportedCommandException: Error 404: Not Found
File not found
Command duration or timeout: 1.02 seconds
Build info: version: '2.25.0', revision: '17482', time: '2012-07-18 21:08:56'
System info: os.name: 'Windows Vista', os.arch: 'x86', os.version: '6.1', java.version: '1.6.0_02-ea'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:188)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:498)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:244)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:87)
	at sp_screens.CREATE_TRADE_MANUALLY.create_trade_order(CREATE_TRADE_MANUALLY.java:507)
	at resources.Utility.redirectDPMain(Utility.java:3001)
	at resources.AC_MAIN_V.main(AC_MAIN_V.java:327)
Exception: ORA-00904: "FAILURE_REASON": invalid identifier

I am getting this error while using multithreading and I don't understand how to use SynchronizedInternetExplorerDriver.java I am new to it any advice

**Comment by lmtierney** [comment]
The issue template is there to give us enough information to help you out. Please fill it out.
