### ISSUE TITLE
InvalidOperationException when setting timeouts using geckodriver

### ISSUE THREAD

**Issue by SeanKilleen** [SeleniumHQ/selenium#3544]
Hi all,

Attempting to upgrade our solution's Selenium bits and switch over to Geckodriver, but it seems I've hit a snag. Wanted to check here to see if this is to be expected at this point.

I'm cross-posting this in both places ( [geckodriver github issue here](https://github.com/mozilla/geckodriver/issues/486) ) as I am not certain how to narrow down what might be the cause (I have a feeling it may be on the geckodriver side given it's in early days):

## Meta -
* **OS:**  Windows 7 Enterprise
* **Platform:** .NET
* **Selenium Version:** 3.1.0
* **Browser:** Firefox v51.0.1 (32-bit)
* **Driver:** geckodriver 0.14

## Steps to reproduce
Access timeout values via `Instance.Manage().Timeouts()` and try to set those values

 * E.g. `Instance.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(seconds));`
 * I saw this was deprecated and so also tried `Instance.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(seconds);`

This problem appears when setting any of the timeout settings

## Expected Behavior
This code would not need to change and things would keep working. 

## Actual Behavior
Receive an `InvalidOperationException` error. 

Stack trace (project name redacted):
```
SetUp : System.InvalidOperationException : Missing 'type' parameter (IndexOutOfBounds)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTimeouts.ExecuteSetTimeout(String timeoutType, TimeSpan timeToWait)
   at OpenQA.Selenium.Remote.RemoteTimeouts.set_ImplicitWait(TimeSpan value)
   at REDACTED.UIAutomationFramework.Selenium.Driver.SetImplicitWait(Int32 seconds) in C:\dev\REDACTED\Src\Tests\AAT\REDACTED.UIAutomationFramework\Selenium\Driver.cs:line 484
   at REDACTED.UIAutomationFramework.Selenium.Driver.TurnOnWait() in C:\dev\REDACTED\Src\Tests\AAT\REDACTED.UIAutomationFramework\Selenium\Driver.cs:line 672
   at REDACTED.UIAutomationFramework.Selenium.Driver.Initialize(String baseUrl) in C:\dev\REDACTED\Src\Tests\AAT\REDACTED.UIAutomationFramework\Selenium\Driver.cs:line 84
   at REDACTED.AutomatedAcceptanceTestSetUpFixture.SetUpBeforeAllTests() in C:\dev\REDACTED\Src\Tests\AAT\REDACTED\AutomatedAcceptanceTestSetUpFixture.cs:line 20
```

**Comment by Rain9333** [comment]
You are not alone. Same error here even on PageLoad property of the driver:
`driver.Manage().Timeouts().PageLoad = DriverTimeout;`

```
Missing 'type' parameter (IndexOutOfBounds)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTimeouts.ExecuteSetTimeout(String timeoutType, TimeSpan timeToWait)
   at OpenQA.Selenium.Remote.RemoteTimeouts.set_PageLoad(TimeSpan value)
```

**Comment by Grifan** [comment]
Hi. I've got same problem

**Comment by mightflypig** [comment]
I'm also having this issue. Thanks for raising.

**Comment by npomoAtWork** [comment]
I also have this problem.

**Comment by SeanKilleen** [comment]
After some review on their side, I believe the appropriate issue belongs at https://github.com/mozilla/geckodriver/issues/486.

I'll leave it to the maintainers but I'm fine closing this as a duplicate to refer others to that issue.

**Comment by lmtierney** [comment]
The code was updated to match the w3c spec, the next version of geckodriver will play nice. See https://github.com/mozilla/geckodriver/issues/486 per @SeanKilleen
