### ISSUE TITLE
selenium-html-runner-3.1.0 TimeoutException: Error loading page, timed out

### ISSUE THREAD

**Issue by dcrozz** [SeleniumHQ/selenium#3546]
## Meta -
OS:  
Ubuntu 16.04

Selenium Version:  
selenium-html-runner-3.1.0
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Browser:  
Firefox

Browser Version:  
Mozilla Firefox 51.0.1 with geckodriver-v0.14.0-linux64

## Actual Behavior -

```
1487646588284	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/51.0.1/20170201180315/Linux_x86_64-gcc3/null/release-cck- ubuntu/Linux%204.4.0-62-generic%20(GTK%203.18.9%2Clibpulse%208.0.0)/canonical/1.0/update.xml
1487646588799	addons.productaddons	INFO	Completed downloading document
1487646589182	addons.productaddons	INFO	downloadXHR File download. status=200
1487646589188	addons.productaddons	INFO	Downloaded file will be saved to /tmp/tmpaddon
2017-02-21 11:13:49.123:INFO:osjs.ServerConnector:main: Stopped ServerConnector@7d21fea9{HTTP/1.1}{0.0.0.0:8688}
2017-02-21 11:13:49.125:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@130d63be{/tests,null,UNAVAILABLE}
[Child 16768] WARNING: pipe error (3): Connection reset by peer: file /build/firefox-z5GTBX/firefox-51.0.1+build2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 323
[Child 16768] ###!!! ABORT: Aborting on channel error.: file /build/firefox-z5GTBX/firefox-51.0.1+build2/ipc/glue/MessageChannel.cpp, line 2056
[Child 16768] ###!!! ABORT: Aborting on channel error.: file /build/firefox-z5GTBX/firefox-51.0.1+build2/ipc/glue/MessageChannel.cpp, line 2056
Feb 21, 2017 11:13:49 AM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *firefox
org.openqa.selenium.TimeoutException: Error loading page, timed out (onDOMContentLoaded)
Build info: version: '3.1.0', revision: '', time: '2017-02-21 10:20:14 +0800'
System info: host: 'ci', ip: 'x.x.x.x', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20170201180315, version=51.0.1, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=16700, browserVersion=51.0.1, platformVersion=4.4.0-62-generic, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=linux, firefox_profile=UEsDBBQACAgIABZZVUoAAAAAAAAAA...}]
Session ID: 2dbaa439-df79-41f7-beb9-47175432436d
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:322)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:110)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)
```

## Steps to reproduce -
selenium-html-runner-3.1.0.jar build with [selenium 3.1.0](https://github.com/SeleniumHQ/selenium/releases)/tag/selenium-3.1.0
[geckodriver-v0.14.0](https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz)
[selTest.html](https://gist.githubusercontent.com/gchr/300a16b0b3b5271247609a28b2e98a1f/raw/29ed38cdba0ac92358025b0fec00678570967987/selTest.html)

for convenience sake, I use the example from #3076 directly. 

java -jar /home/ubuntu/selenium/selenium-html-runner-3.1.0.jar -htmlSuite *firefox "http://www.google.com" "./selTest.html" SeResults

**Comment by lmtierney** [comment]
Can you try this with `3.2.0`?

**Comment by dcrozz** [comment]
@lmtierney Thank you for your reply, but it seems that 3.2.0 doesn't work neither, which turns out to be the same Error message

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
