### ISSUE TITLE
using latest npm @2.7.3

### ISSUE THREAD

**Issue by robertbaker** [SeleniumHQ/selenium#356]
Happens with PYHTON 2.7.x

```text
D:\CodeRoot\node_
lenium-webdriver\node_modules\ws\node_modules\utf-8-validate>if not de
config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\no
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuil
gyp ERR! configure error
gyp ERR! stack Error: spawn C:\Python34 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proce
:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\CodeRoot\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-valid
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.0.1
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
selenium-webdriver@2.45.1 node_modules\selenium-webdriver
├── tmp@0.0.24
├── adm-zip@0.4.4
├── xml2js@0.4.4 (xmlbuilder@2.6.2, sax@0.6.1)
├── rimraf@2.3.2 (glob@4.5.3)
└── ws@0.7.1 (options@0.0.6, ultron@1.0.1)
```

**Comment by andreastt** [comment]
This means it can't find the Python 3.4 binary.  Sounds like system issue on your end.

**Comment by robertbaker** [comment]
No I even switched it to 2.7.x and it still fails. It seems to be an issues with the 2 utf-8-validate.

**Comment by andreastt** [comment]
No, it's an issue with failing to execute Python: `gyp ERR! stack Error: spawn C:\Python34 ENOENT`

ENOENT == no such file or directory

**Comment by robertbaker** [comment]
apologies, it's actually an issue with node-gyp 1.0.3.

I reinstalled the sdk, python27, added the path, the var, and set it via gyp command.

I'm sure it's an issue with node-gyp.

https://github.com/TooTallNate/node-gyp/issues/596

**Comment by andreastt** [comment]
Good to know (-:  Thanks for reporting an issue.
