### ISSUE TITLE
Unable to launch firefox 47 with Webdriver 3.1.0 (Protractor)

### ISSUE THREAD

**Issue by sharvarik** [SeleniumHQ/selenium#3572]
## Meta -
OS:  'Windows 7'

Selenium Version:  3.1.0

Browser:  Firefox 

Browser Version:  47.0

## Actual Behavior - getting below error. 

`[11:36:19] I/launcher - Running 1 instances of WebDriver
[11:36:19] I/local - Starting selenium standalone server...
[11:36:23] I/local - Selenium standalone server started at http://10.51.235.0:6666/wd/hub
[11:36:23] E/launcher - The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
[11:36:23] E/launcher - WebDriverError: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
    at WebDriverError (C:\Projects\work\Web\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
    at Object.checkLegacyResponse (C:\Projects\work\Web\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\Projects\work\Web\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Projects\work\Web\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Projects\work\Web\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (C:\Projects\work\Web\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:640:55)
    at createDriver (C:\Projects\work\Web\node_modules\protractor\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (C:\Projects\work\Web\node_modules\protractor\node_modules\selenium-webdriver\index.js:629:16)
    at Local.getNewDriver (C:\Projects\work\Web\node_modules\protractor\lib\driverProviders\driverProvider.ts:60:29)
    at Runner.createBrowser (C:\Projects\work\Web\node_modules\protractor\lib\runner.ts:225:39)
    at q.then.then (C:\Projects\work\Web\node_modules\protractor\lib\runner.ts:391:27)
    at _fulfilled (C:\Projects\work\Web\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Projects\work\Web\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Projects\work\Web\node_modules\q\q.js:796:13)
[11:36:23] E/launcher - Process exited with error code 199`

**Comment by lmtierney** [comment]
As your stacktrace states, you need to use [geckodriver](https://github.com/mozilla/geckodriver)

**Comment by sharvarik** [comment]
Hi,

Thank you for your quick response. I do have geckodriver downloaded in my
node_modules. My webdriver does not seem to pickup from there.
Is there any configuration that I need to do?

**Comment by lmtierney** [comment]
The easiest way is to add it to your system's path http://seleniumhq.github.io/selenium/docs/api/javascript/index.html

**Comment by sharvarik** [comment]
I added the path to geckodriver.exe to systems path. Now I am getting a different error. 
``
 E/launcher - WebDriverError: Firefox option was set, but is not a FirefoxOption: {}

**Comment by lmtierney** [comment]
Sounds like an issue with Protractor https://github.com/angular/protractor#getting-help

**Comment by qadeerqureshi** [comment]
Please try these configurations. I hope it works for you :)
`seleniumServerJar: 'C:/Users/Qadeer.a/AppData/Roaming/npm/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.4.0.jar',
    localSeleniumStandaloneOpts: {
        jvmArgs: ['-Dwebdriver.ie.driver=C:/Users/Qadeer.a/AppData/Roaming/npm/node_modules/protractor/node_modules/webdriver-manager/selenium/IEDriverServer.exe','-Dwebdriver.gecko.driver=C:/Users/Qadeer.a/AppData/Roaming/npm/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.16.1.exe']
    },`
