### ISSUE TITLE
Selenium IEDriverServer can not create driver instance more than 30

### ISSUE THREAD

**Issue by sunbeams001** [SeleniumHQ/selenium#3591]
## Meta -
OS:  win7 bit, win10 64bit
Selenium Version:  latest
Browser:   Internet Explorer
Browser Version:  11
Python version: 2.7.11
IEDriverServer (x86 edition)
protect mode all checked in security zone

## Expected Behavior -
I want to create at least 100 IE driver instances in one machine with follow test code:
```
for i in xrange(100):
	dcap = DesiredCapabilities.INTERNETEXPLORER.copy()
	driver = webdriver.Ie(executable_path=path_to_ie_driver_server,capabilities=dcap)
```
## Actual Behavior -
The code above can create about 29 driver instances in my dev pc, and then throw an exception
```
Traceback (most recent call last):
  File "D:\Dev\PyCharm Community Edition\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Dev\PyCharm Community Edition\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/workspace/tidy/credit.kolibre.creditreference.webcrawler/src/test.py", line 33, in <module>
    d = get_a_driver()
  File "C:/workspace/tidy/credit.kolibre.creditreference.webcrawler/src/test.py", line 26, in get_a_driver
    driver = webdriver.Ie(executable_path=r"D:\Dev\phantomjs-2.1.1-windows\bin\IEDriverServer.exe",capabilities=dcap)
  File "D:\Dev\Python27\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 57, in __init__
    desired_capabilities=capabilities)
  File "D:\Dev\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Dev\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "D:\Dev\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "D:\Dev\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unexpected error launching Internet Explorer. IELaunchURL() returned HRESULT 80070012 ('There are no more files.') for URL 'http://localhost:51782/'
```
## Personal guess
As I know, when selenium create driver instance, it will pass a `NEW_SESSION` command parameter
It maybe not a selenium bug, cause I can reproduce it by manually create new session in IE(File-New session), and can only create 29 IE session too.
And I found this problem was mentioned [here](http://superuser.com/questions/249733/running-more-than-30-ie8-sessions-with-nomerge) but not solved.

Thanks for any idea about this problem.

**Comment by cgoldberg** [comment]
> I can reproduce it by manually create new session in IE

so then it sounds totally unrelated to selenium... it's an IE/Windows limitation

**Comment by sunbeams001** [comment]
@cgoldberg Yes, seems so, and I just want to confirm whether someone have encountered this problem. After all, it's the default behavior(new session) when IEDriver creates new instance.

**Comment by jimevans** [comment]
I'm closing this issue. If it reproduces manually, there is nothing the driver can do about it. Consider it a limitation.
