### ISSUE TITLE
Python Selenium 2.45 appears broken with Firefox 36.0.4

### ISSUE THREAD

**Issue by Martin-Spamer** [SeleniumHQ/selenium#360]
Attempts to start the driver with  self.driver = webdriver.Firefox()  fails with 

```text
ERROR:root:Message: "Can't load the profile. Profile Dir: c:\\users\\martin~1\\appdata\\local\\temp\\tmpldmwnd Firefox output: None" 
Traceback (most recent call last):
  File "C:\Python\SeaMonsters\test\acceptance\__init__.py", line 63, in setUp
    self.driver = webdriver.Firefox()
  File "C:\Python\SeaMonsters\env\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 59, in __init__
    self.binary, timeout),
  File "C:\Python\SeaMonsters\env\lib\site-packages\selenium\webdriver\firefox\extension_connection.py", line 47, in __init__
    self.binary.launch_browser(self.profile)
  File "C:\Python\SeaMonsters\env\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 64, in launch_browser
    self._wait_until_connectable()
  File "C:\Python\SeaMonsters\env\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 108, in _wait_until_connectable
    self.profile.path, self._get_firefox_output()))
```

**Comment by andreastt** [comment]
I'm unable to reproduce this with the Python bindings of Selenium 2.45.0 and Firefox 36.0.4.

**Comment by lukeis** [comment]
Not able to reproduce with Selenium 2.45.0  Firefox 36.0.4 Python 2.7.9 on windows 7.

**Comment by ddavison** [comment]
@Martin-Spamer if you are still having problems, you can either try the selenium user group, or stackoverflow

**Comment by Martin-Spamer** [comment]
No, scub this issue.  I screwed up and was running the tests with virtual env with older version.

**Comment by andreastt** [comment]
@Martin-Spamer: Glad to hear it's working okay for you now! 👍🏻
