### ISSUE TITLE
Selenium-java 3.3.0 classcast exception using firefox driver

### ISSUE THREAD

**Issue by pethers** [SeleniumHQ/selenium#3620]
## Meta -
OS:  
Ubuntu 16.04
Selenium Version:  
Selenium-java 3.3.30
Browser:  
Firefox 52.0

Just trying to upgrade from 3.2.0 -> 3.3.0. 
Get classcastexception when trying to create a FirefoxDriver using code as below

`
		final DesiredCapabilities capabilities = new FirefoxOptions()
			      .setProfile(new FirefoxProfile())
			      .addTo(DesiredCapabilities.firefox());
		capabilities.setCapability("marionette", false);
		capabilities.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);

		final WebDriver driver = new FirefoxDriver(capabilities);

`

Get exception

`java.lang.ClassCastException: org.openqa.selenium.remote.service.DriverCommandExecutor cannot be cast to org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:309)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:243)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:121)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:164)
	at com.keypasco.demo.application.WebIntegrationTest.getWebDriver(WebIntegrationTest.java:83)
`

Best regards

**Comment by diemol** [comment]
I think you need to check your geckodriver version, according to the [changelog](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG), version v0.15 is the supported one.

**Comment by pethers** [comment]
Worked when I did set  `capabilities.setCapability("marionette", true);` and installed geckodriver 0.15.0.

**Comment by lmtierney** [comment]
marionette defaults to true with selenium 3.0 and greater, you don't need to set it
