### ISSUE TITLE
promise.js:2634 WebDriverError: unknown error: Runtime.executionContextCreated has invalid 'context'

### ISSUE THREAD

**Issue by ucipass** [SeleniumHQ/selenium#3659]
## Meta -
OS:  
ubuntu 16.10
Selenium Version:  
3.3.0
Browser:  
Chrome 

Browser Version:  
57.0.2987.98 (64-bit)

## Expected Behavior -
would like just to just load the selenium-webdriver with a single line of code
 webdriver = require('selenium-webdriver');
running node 7.7.2
ChromeDriver (v2.9.248304)

## Actual Behavior -
node ./bin/firsttest.js 
/home/aarato/node/ucipassweb/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

WebDriverError: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"21966.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=57.0.2987.98)
  (Driver info: chromedriver=2.9.248304,platform=Linux 4.8.0-41-generic x86_64)
    at Object.checkLegacyResponse (/home/aarato/node/ucipassweb/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/home/aarato/node/ucipassweb/node_modules/selenium-webdriver/lib/http.js:516:11)
    at doSend.then.response (/home/aarato/node/ucipassweb/node_modules/selenium-webdriver/lib/http.js:432:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.navigate().to(http://www.google.com/ncr)
    at thenableWebDriverProxy.schedule (/home/aarato/node/ucipassweb/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at Navigation.to (/home/aarato/node/ucipassweb/node_modules/selenium-webdriver/lib/webdriver.js:1140:25)
    at thenableWebDriverProxy.get (/home/aarato/node/ucipassweb/node_modules/selenium-webdriver/lib/webdriver.js:997:28)
    at Object.<anonymous> (/home/aarato/node/ucipassweb/bin/firsttest.js:35:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

**Comment by jonathansamines** [comment]
I just got this error today, and seemed related to the fact that the chrome driver used along with my google chrome version was not supported. (I was using an old driver version).

**Comment by jleyba** [comment]
This error is coming from chrome/chromedriver. You should definitely upgrade your version of chromedriver - you say you're using 2.9, but that's 3 years old! You can find the latest release (2.28) here:

https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by lotosotol** [comment]
> This error is coming from chrome/chromedriver. You should definitely upgrade your version of chromedriver - you say you're using 2.9, but that's 3 years old! You can find the latest release (2.28) here:
> 
> https://sites.google.com/a/chromium.org/chromedriver/downloads

This is the correct fix for the issue. Thank you **jleyba**!
