### ISSUE TITLE
firefox node raises exception when starting test session

### ISSUE THREAD

**Issue by bmannix** [SeleniumHQ/selenium#367]
I am using the docker containers (2.45.0) to create a grid.

On the same host machine I run:
```
docker run -d -p 4444:4444 --name selenium-hub selenium/hub:2.45.0
docker run --rm --name=ff --link selenium-hub:hub selenium/node-firefox:2.45.0
```

The node registers properly.  However once I start a test run, I see the exception below in the log.  It's happening right as I attempt to create the remote webdriver.

```
browser = webdriver.Remote('http://client:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
```

FWIW - the chromedriver node runs perfectly.

```
20:01:01.356 INFO - Registering the node to hub :http://172.17.0.21:4444/grid/register
20:01:13.949 INFO - Executing: [new session: Capabilities [{firefox_profile=UEsDBBQAAAAIACZoeEZh7yP8ZwMAA..., platform=ANY, javascriptEnabled=true, browserName=firefox, proxy={httpProxy=172.28.128.11:9923, sslProxy=172.28.128.11:9923, proxyType=MANUAL}, version=}]])
20:01:13.974 INFO - Creating a new session for Capabilities [{firefox_profile=UEsDBBQAAAAIACZoeEZh7yP8ZwMAA..., platform=ANY, javascriptEnabled=true, browserName=firefox, proxy={httpProxy=172.28.128.11:9923, sslProxy=172.28.128.11:9923, proxyType=MANUAL}, version=}]
20:01:59.418 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'fa59fe32da9b', ip: '172.17.0.23', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-46-generic', java.version: '1.7.0_75'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:110)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:172)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'fa59fe32da9b', ip: '172.17.0.23', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-46-generic', java.version: '1.7.0_75'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	... 9 more
Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows:

(process:40): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Xlib:  extension "RANDR" missing on display ":99".
process 40: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.

Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'fa59fe32da9b', ip: '172.17.0.23', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-46-generic', java.version: '1.7.0_75'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:134)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	... 14 more
Caused by: org.openqa.selenium.WebDriverException: java.lang.InterruptedException: Process timed out after waiting for 45000 ms.
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'fa59fe32da9b', ip: '172.17.0.23', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-46-generic', java.version: '1.7.0_75'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:131)
	at org.openqa.selenium.firefox.FirefoxBinary.waitFor(FirefoxBinary.java:222)
	at org.openqa.selenium.firefox.FirefoxBinary.clean(FirefoxBinary.java:242)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:91)
	... 19 more
Caused by: java.lang.InterruptedException: Process timed out after waiting for 45000 ms.
	at org.openqa.selenium.os.UnixProcess.waitFor(UnixProcess.java:148)
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:129)
	... 22 more
20:01:59.423 WARN - Exception: Process timed out after waiting for 45000 ms.
20:01:59.505 INFO - Executing: [new session: Capabilities [{firefox_profile=UEsDBBQAAAAIAD1oeEZh7yP8ZwMAA..., platform=ANY, javascriptEnabled=true, browserName=firefox, proxy={httpProxy=172.28.128.11:9923, sslProxy=172.28.128.11:9923, proxyType=MANUAL}, version=}]])
20:01:59.509 INFO - Creating a new session for Capabilities [{firefox_profile=UEsDBBQAAAAIAD1oeEZh7yP8ZwMAA..., platform=ANY, javascriptEnabled=true, browserName=firefox, proxy={httpProxy=172.28.128.11:9923, sslProxy=172.28.128.11:9923, proxyType=MANUAL}, version=}]
```

**Comment by bmannix** [comment]
I should note that my local selenium bindings are python version 2.45.0

**Comment by mtscout6** [comment]
For some reason xvfb is not getting the RANDR flag passed in [here](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeBase/entry_point.sh#L21). Are you using a modified version of that docker image?

**Comment by bmannix** [comment]
@mtscout6 no this is a completely stock docker container (version 2.45.0)

**Comment by mtscout6** [comment]
How your docker host doing on resource consumption. Other folks have seen this issue when system resources are strained.

**Comment by bmannix** [comment]
The docker host has 8GB ram and 2 CPUs.  It was just reboot as well, so I do not believe this to be a resource issue.

**Comment by mtscout6** [comment]
Bummer, can't say that I know what the problem is then.

**Comment by lukeis** [comment]
this doesn't seem like a 'selenium' bug, but rather a 'docker-selenium' one. Can we move this issue over there?

**Comment by mtscout6** [comment]
:+1:

**Comment by bmannix** [comment]
I think this is essentially a dup of https://github.com/SeleniumHQ/docker-selenium/issues/31
