### ISSUE TITLE
Creating session using hash to request Chrome browser fails with error in InternetExplorerDriver

### ISSUE THREAD

**Issue by crypes** [SeleniumHQ/selenium#3676]
## Meta -
OS:  
win8.1 Enterprise 64bit

Selenium Version:  
Selenium server version: 3.3.1, revision: 5234b32

Ruby version: 2.3.3p222 x64
Java version: '1.8.0_102'
IEDriverServer (3.0.0.0)
IE version 11.0.9600.18538
ChromeDriver 2.27.440174
Chrome version 56.0.2924.87 (64 bit)
Selenium server version: 3.3.1, revision: 5234b32
Gems: 
	childprocess (0.5.9)
		ffi (\~> 1.0, >= 1.0.11)
	ffi (1.9.14)
	rubyzip (1.2.0)
	selenium-webdriver (3.0.5)
		childprocess (\~> 0.5)
		rubyzip (\~> 1.0)
		websocket (\~> 1.0)
	watir (6.1.0)
		selenium-webdriver (\~> 3.0)
	websocket (1.2.3)

## Expected Behavior -
Requesting a Chrome browser by passing a hash to Watir::Browser.new should open a Chrome browser.

## Actual Behavior -
A short program to exercise this (small_case.rb):
```
require 'watir'

cr_caps = {
  browser_name: 'chrome',
  chromeOptions: { args: [ '--proxy-server=127.0.0.1:9999' ] }
}

browser = Watir::Browser.new(
  :remote,
  url: 'http://127.0.0.1:4444/wd/hub',
  desired_capabilities: cr_caps
)
browser.goto 'https://github.com/'
sleep 5
browser.close
```

Gets exception with message:
```
[remote server] org.openqa.selenium.remote.server.DefaultDriverFactory(DefaultDriverFactory.java):62:in `newInstance': The best matching driver provider org.openqa.selenium.ie.InternetExplorerDriver can't create a new driver instance for Capabilities [{browser_name=chrome, chromeOptions={args=[--proxy-server=127.0.0.1:9999]}}] (Selenium::WebDriver::Error::UnknownError)
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'xxx', ip: 'xxx', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_102'
Driver info: driver.version: unknown (org.openqa.selenium.WebDriverException)
	from [remote server] org.openqa.selenium.remote.server.DefaultSession$BrowserCreator(DefaultSession.java):222:in `call'
	from [remote server] org.openqa.selenium.remote.server.DefaultSession$BrowserCreator(DefaultSession.java):209:in `call'
	from [remote server] java.util.concurrent.FutureTask():-1:in `run'
	from [remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
	from [remote server] java.util.concurrent.ThreadPoolExecutor():-1:in `runWorker'
	from [remote server] java.util.concurrent.ThreadPoolExecutor$Worker():-1:in `run'
	from [remote server] java.lang.Thread():-1:in `run'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/http/common.rb:85:in `new'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/http/common.rb:85:in `create_response'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/http/common.rb:63:in `call'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/bridge.rb:645:in `raw_execute'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/bridge.rb:109:in `create_session'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/bridge.rb:69:in `initialize'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/common/driver.rb:57:in `new'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/common/driver.rb:57:in `for'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver.rb:82:in `for'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/watir-6.1.0/lib/watir/browser.rb:46:in `initialize'
	from C:/dev/spikes/se_browser/small_case.rb:8:in `new'
	from C:/dev/spikes/se_browser/small_case.rb:8:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```
It seems to be asking the Internet Explorer driver to create a session, although the requested browser name was 'Chrome'.

Note that similar invocation works correctly with Firefox and IE.

Also using capabilities objects works correctly, e.g.
`Selenium::WebDriver::Remote::Capabilities.chrome(CHROME_OPTIONS)`

## Steps to reproduce -

1. Set up Selenium Hub and Selenium node
2. For "small_case.rb", just execute `ruby small_case.rb`
3. For the larger "my_script.rb", set environment variable GRID_URL to http://127.0.0.1:4444/wd/hub, if running locally.  Also set DESIRED_BROWSER to chrome, ie, or ff.
4. Verify that the correct browser comes up.
[selenium_issue_20170317.zip](https://github.com/SeleniumHQ/selenium/files/851755/selenium_issue_20170317.zip)

**Comment by lmtierney** [comment]
When you use a raw hash for a remote, that's what we use. That means we aren't converting your `browser_name` key to `browserName` like it needs to be.

Try using `browserName: 'chrome'`

**Comment by barancev** [comment]
Also, if the registered browser name is 'Chrome' you should pas the same value, it's case sensitive.

**Comment by crypes** [comment]
That did the job:  `browserName: 'chrome' ` works properly.

Thanks for your help!
