### ISSUE TITLE
Edge - Clear local storage command doesn't work

### ISSUE THREAD

**Issue by ronkorland** [SeleniumHQ/selenium#3702]
## Meta
OS:  
Windows 10
Selenium Version:  
3.3.1
Browser:  
Microsoft Edge
Browser Version:  
14.14393 (64Bit)

## Expected Behavior
/session/:sessionId/local_storage (DELETE method) command should clear local storage data

## Actual Behavior
Command failed with error:
09:40:16.620 INFO - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, webStorageEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@49ebe69, browserName=MicrosoftEdge, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}]]
09:40:16.995 INFO - Executing: [clear local storage])
09:40:16.995 WARN - Exception thrown
org.openqa.selenium.UnsupportedCommandException: driver (org.openqa.selenium.edge.EdgeDriver) does not support org.openqa.selenium.html5.WebStorage
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'WIN10-TEST', ip: '172.16.1.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.handler.html5.Utils.convert(Utils.java:93)
	at org.openqa.selenium.remote.server.handler.html5.Utils.getWebStorage(Utils.java:62)
	at org.openqa.selenium.remote.server.handler.html5.ClearLocalStorage.call(ClearLocalStorage.java:31)
	at org.openqa.selenium.remote.server.handler.html5.ClearLocalStorage.call(ClearLocalStorage.java:23)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by jimevans** [comment]
"Unsupported" commands, or commands that haven't been implemented by the browser-specific driver, are the responsibility of the driver vendor to implement. The Selenium project does not develop or maintain the Edge driver, Microsoft does. One would need to raise an issue with them to have this fixed.

**Comment by ronkorland** [comment]
@jimevans Ok, thank you
I opened issue to Edge team: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11372324/
