### ISSUE TITLE
Unable to launch chrome browser using selenium 3.3.1

### ISSUE THREAD

**Issue by didi112113** [SeleniumHQ/selenium#3703]
Hi,

I have windows 7 and my Chrome Version is: 57.0.2987.110 (64-bit).  I updated pom.xml with the latest version of Selenium

       <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.3.1</version>
        </dependency>

I was unable to run the tests. I also got the error described by Sanojqa on February 20th and more:
Unable to launch chrome browser using selenium 3.1.0 #3540

Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Vat org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:302)
at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:146)

Thank you for your help

**Comment by BogdanLivadariu** [comment]
@didi112113 
what chromedriver version do you have ?
what's your OS ?

**Comment by didi112113** [comment]
Hi 
I have the latest Chrome driver: 2.28 and I have Windows 7.  Thank you.

**Comment by espenaf** [comment]
I experienced the same problem, and looking at the changelog I see that there has been an update to Guava 21.0. While examining maven dependencies of my project, I found that google-collections 1.0 was being pulled inn by another artifact, so replacing it with guava fixed it for me.

**Comment by khalistan** [comment]
Hello I am facing same problem.
I am using:
Environment-> Centos 7
version.org.seleniumhq.selenium.selenium-java ->3.3.1
version.org.seleniumhq.selenium.selenium-support ->3.3.1
version.com.google.guava.guava -> 21.0
version.junit.junit -> 4.+
ChromeDriver -> 2.28 ( https://chromedriver.storage.googleapis.com/index.html?path=2.28/ )

Error I am getting "com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Vat "

Exception starts from "org.openqa.selenium.remote.service" at line 111 on method 
```
 checkState(exePath != null, "The path to the driver executable must be set by the %s system property;"
            + " for more information, see %s. "
            + "The latest version can be downloaded from %s",
            exeProperty, exeDocs, exeDownload);

```

**Comment by LinuxSuRen** [comment]
用最新的驱动就可以

**Comment by ph-ms** [comment]
@espenaf did you have to use <excludes> to make it work for you?  Can to share a link to you pom.xml ?

**Comment by espenaf** [comment]
To make it work you need to remove any sign of the google-collections dependency being pulled into your project, one way to check for this is looking at the Maven dependency graph, run the following at the root of your project:

```bash
 mvn dependency:tree
```

Then search for instances of google-collections being pulled in transitivly in your dependency graph. In my case I had to exclude google-collections from a dependency not directly related to Selenium, but nevertheless part of the pom. Guava is a superset of google-collections, so excluding it and using Guava instead wasn't a problem. Excluding google-collections from a dependency can be done like this:

```xml
<dependency>
    <groupId>org.codehaus.plexus</groupId>
    <artifactId>plexus-container-default</artifactId>
    <version>1.7.1</version>
    <exclusions>
      <exclusion>
      <groupId>com.google.collections</groupId>
      <artifactId>google-collections</artifactId>
      </exclusion>
    </exclusions> 
</dependency>
```

**Comment by barancev** [comment]
Please run mvn dependency:tree and show your classpath.

**Comment by megakoresh** [comment]
Same problem here
```
[INFO] com.megakoresh:javaee-tomcat:war:0.1
[INFO] +- javax:javaee-web-api:jar:7.0:provided
[INFO] +- org.glassfish:javax.faces:jar:2.3.0:compile
[INFO] +- javax.servlet:jstl:jar:1.2:compile
[INFO] +- org.jboss.weld.servlet:weld-servlet:jar:2.3.4.Final:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-javaee:jar:2.0.0-alpha-10:test
[INFO] |  +- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-javaee:jar:2.0.0-alpha-10:test
[INFO] |  |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-base:jar:2.0.0-alpha-10:test
[INFO] |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-base:jar:2.0.0-alpha-10:test
[INFO] +- org.jboss.arquillian.container:arquillian-container-test-api:jar:1.1.13.Final:test
[INFO] |  \- org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6:test
[INFO] +- org.jboss.arquillian.junit:arquillian-junit-container:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.junit:arquillian-junit-core:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.test:arquillian-test-api:jar:1.1.13.Final:test
[INFO] |  |  \- org.jboss.arquillian.core:arquillian-core-api:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.test:arquillian-test-spi:jar:1.1.13.Final:test
[INFO] |  |  \- org.jboss.arquillian.core:arquillian-core-spi:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-test-spi:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.core:arquillian-core-impl-base:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.test:arquillian-test-impl-base:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-impl-base:jar:1.1.13.Final:test
[INFO] |  |  +- org.jboss.arquillian.config:arquillian-config-api:jar:1.1.13.Final:test
[INFO] |  |  \- org.jboss.arquillian.config:arquillian-config-impl-base:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-test-impl-base:jar:1.1.13.Final:test
[INFO] |  \- org.jboss.shrinkwrap:shrinkwrap-impl-base:jar:1.2.6:test
[INFO] |     \- org.jboss.shrinkwrap:shrinkwrap-spi:jar:1.2.6:test
[INFO] +- org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-spi:jar:1.1.13.Final:test
[INFO] |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-spi:jar:2.0.0-alpha-10:test
[INFO] +- com.google.guava:guava:jar:21.0:test
[INFO] +- org.seleniumhq.selenium:selenium-java:jar:3.3.1:test
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.3.1:test
[INFO] |  |  \- org.seleniumhq.selenium:selenium-remote-driver:jar:3.3.1:test
[INFO] |  |     +- org.seleniumhq.selenium:selenium-api:jar:3.3.1:test
[INFO] |  |     +- cglib:cglib-nodep:jar:3.2.4:test
[INFO] |  |     +- org.apache.commons:commons-exec:jar:1.3:test
[INFO] |  |     +- com.google.code.gson:gson:jar:2.8.0:test
[INFO] |  |     +- org.apache.httpcomponents:httpclient:jar:4.5.2:test
[INFO] |  |     |  \- org.apache.httpcomponents:httpcore:jar:4.4.4:test
[INFO] |  |     \- net.java.dev.jna:jna-platform:jar:4.1.0:test
[INFO] |  |        \- net.java.dev.jna:jna:jar:4.1.0:test
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.3.1:test
[INFO] |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.3.1:test
[INFO] |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.3.1:test
[INFO] |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.3.1:test
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.3.1:test
[INFO] |  +- com.codeborne:phantomjsdriver:jar:1.4.0:test
[INFO] |  \- org.seleniumhq.selenium:htmlunit-driver:jar:2.24:test
[INFO] |     +- org.seleniumhq.selenium:selenium-support:jar:3.3.1:test (version selected from constraint [2.53.0,4.0.0))
[INFO] |     |  \- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |     \- net.sourceforge.htmlunit:htmlunit:jar:2.24:test
[INFO] |        +- xalan:xalan:jar:2.7.2:test
[INFO] |        |  \- xalan:serializer:jar:2.7.2:test
[INFO] |        +- org.apache.commons:commons-lang3:jar:3.5:test
[INFO] |        +- org.apache.httpcomponents:httpmime:jar:4.5.2:test
[INFO] |        +- commons-codec:commons-codec:jar:1.10:test
[INFO] |        +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.23:test
[INFO] |        +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.24:test
[INFO] |        |  \- xerces:xercesImpl:jar:2.11.0:test
[INFO] |        |     \- xml-apis:xml-apis:jar:1.4.01:test
[INFO] |        +- net.sourceforge.cssparser:cssparser:jar:0.9.21:test
[INFO] |        |  \- org.w3c.css:sac:jar:1.3:test
[INFO] |        +- commons-io:commons-io:jar:2.5:test
[INFO] |        +- commons-logging:commons-logging:jar:1.2:test
[INFO] |        \- org.eclipse.jetty.websocket:websocket-client:jar:9.2.20.v20161216:test
[INFO] |           +- org.eclipse.jetty:jetty-util:jar:9.2.20.v20161216:test
[INFO] |           +- org.eclipse.jetty:jetty-io:jar:9.2.20.v20161216:test
[INFO] |           \- org.eclipse.jetty.websocket:websocket-common:jar:9.2.20.v20161216:test
[INFO] |              \- org.eclipse.jetty.websocket:websocket-api:jar:9.2.20.v20161216:test
[INFO] +- org.seleniumhq.selenium:selenium-server:jar:3.3.1:test
[INFO] |  +- com.beust:jcommander:jar:1.48:test
[INFO] |  +- net.jcip:jcip-annotations:jar:1.0:test
[INFO] |  +- org.seleniumhq.selenium:jetty-repacked:jar:9.4.1.v20170120:test
[INFO] |  |  \- javax.servlet:javax.servlet-api:jar:3.1.0:test
[INFO] |  \- org.yaml:snakeyaml:jar:1.15:test
[INFO] \- org.jboss.arquillian.container:arquillian-tomcat-managed-8:jar:1.0.0:test
[INFO]    +- org.jboss.arquillian.container:arquillian-tomcat-managed-common:jar:1.0.0:test
[INFO]    +- org.jboss.arquillian.container:arquillian-tomcat-common:jar:1.0.0:test
[INFO]    +- org.jboss.shrinkwrap:shrinkwrap-depchain:pom:1.2.6:test
[INFO]    +- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-depchain:pom:2.0.0-alpha-10:test
[INFO]    |  +- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-jboss:jar:2.0.0-alpha-10:test
[INFO]    |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-jboss:jar:2.0.0-alpha-10:test
[INFO]    +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-depchain:pom:2.2.6:test
[INFO]    |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api:jar:2.2.6:test
[INFO]    |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi:jar:2.2.6:test
[INFO]    |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven:jar:2.2.6:test
[INFO]    |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi-maven:jar:2.2.6:test
[INFO]    |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven-archive:jar:2.2.6:test
[INFO]    |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven:jar:2.2.6:test
[INFO]    |  |  +- org.eclipse.aether:aether-api:jar:1.0.0.v20140518:test
[INFO]    |  |  +- org.eclipse.aether:aether-impl:jar:1.0.0.v20140518:test
[INFO]    |  |  +- org.eclipse.aether:aether-spi:jar:1.0.0.v20140518:test
[INFO]    |  |  +- org.eclipse.aether:aether-util:jar:1.0.0.v20140518:test
[INFO]    |  |  +- org.eclipse.aether:aether-connector-basic:jar:1.0.0.v20140518:test
[INFO]    |  |  +- org.eclipse.aether:aether-transport-wagon:jar:1.0.0.v20140518:test
[INFO]    |  |  +- org.apache.maven:maven-aether-provider:jar:3.2.5:test
[INFO]    |  |  +- org.apache.maven:maven-model:jar:3.2.5:test
[INFO]    |  |  +- org.apache.maven:maven-model-builder:jar:3.2.5:test
[INFO]    |  |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:test
[INFO]    |  |  +- org.apache.maven:maven-repository-metadata:jar:3.2.5:test
[INFO]    |  |  +- org.apache.maven:maven-settings:jar:3.2.5:test
[INFO]    |  |  +- org.apache.maven:maven-settings-builder:jar:3.2.5:test
[INFO]    |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.21:test
[INFO]    |  |  +- org.codehaus.plexus:plexus-utils:jar:3.0.20:test
[INFO]    |  |  +- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:test
[INFO]    |  |  |  \- org.sonatype.plexus:plexus-cipher:jar:1.4:test
[INFO]    |  |  +- org.apache.maven.wagon:wagon-provider-api:jar:2.6:test
[INFO]    |  |  +- org.apache.maven.wagon:wagon-file:jar:2.6:test
[INFO]    |  |  |  \- commons-lang:commons-lang:jar:2.6:test
[INFO]    |  |  \- org.apache.maven.wagon:wagon-http-lightweight:jar:2.6:test
[INFO]    |  |     \- org.apache.maven.wagon:wagon-http-shared:jar:2.6:test
[INFO]    |  |        \- org.jsoup:jsoup:jar:1.7.2:test
[INFO]    |  \- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven-archive:jar:2.2.6:test
[INFO]    |     +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi-maven-archive:jar:2.2.6:test
[INFO]    |     +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0.M1:test
[INFO]    |     |  +- javax.enterprise:cdi-api:jar:1.0:test
[INFO]    |     |  |  +- javax.annotation:jsr250-api:jar:1.0:test
[INFO]    |     |  |  \- javax.inject:javax.inject:jar:1:test
[INFO]    |     |  \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0.M1:test
[INFO]    |     \- org.codehaus.plexus:plexus-compiler-javac:jar:2.3:test
[INFO]    |        \- org.codehaus.plexus:plexus-compiler-api:jar:2.3:test
[INFO]    +- org.jboss.arquillian.testenricher:arquillian-testenricher-cdi:jar:1.1.13.Final:test
[INFO]    +- org.jboss.arquillian.testenricher:arquillian-testenricher-resource:jar:1.1.13.Final:test
[INFO]    \- org.jboss.arquillian.testenricher:arquillian-testenricher-initialcontext:jar:1.1.13.Final:test
```
