### ISSUE TITLE
Python webdriver, ActionChains.perform action raises a exception

### ISSUE THREAD

**Issue by avolkov** [SeleniumHQ/selenium#3733]
## Meta -
OS:  
Debian 9.0
Selenium Version:  
Selenium Webdriver 3.3.1 python bindings
Browser:  
Firefox 52.0.1 (64-bit) with geckodriver 0.14.0

## Expected Behavior -
The code will trigger browser interaction -- hover over an autocomplete field

## Actual Behavior -
The following traceback is triggered

```Traceback (most recent call last):
  File "add_a_channel.py", line 78, in test_add_a_channel
    hover.perform()
  File "/home/avolkov/.virtualenvs/selenium/local/lib/python2.7/site-packages/selenium/webdriver/common/action_chains.py", line 77, in perform
    self.w3c_actions.perform()
  File "/home/avolkov/.virtualenvs/selenium/local/lib/python2.7/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/home/avolkov/.virtualenvs/selenium/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/home/avolkov/.virtualenvs/selenium/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Missing or invalid type argument for pointer action
```

## Steps to reproduce -
Run the following code over any input field. 
```
autocomplete = driver.find_element_by_name("source_id__autocomplete")
hover = webdriver.ActionChains(driver).move_to_element(autocomplete)
hover.perform()
```

**Comment by fangli88** [comment]
@avolkov Have you tried to use geckodriver 0.15? This issue seems to be fixed not long ago.
https://github.com/SeleniumHQ/selenium/issues/2285

geckodriver 0.15.0
https://github.com/mozilla/geckodriver/releases/tag/v0.15.0

**Comment by lmtierney** [comment]
as @fangli88 said, you need to use geckodriver 0.15

**Comment by avolkov** [comment]
Updating to geckodriver 0.15.0 fixed the issue.

Thank you.
