### ISSUE TITLE
Potential bug with catch() for promises (JavaScript)

### ISSUE THREAD

**Issue by ORESoftware** [SeleniumHQ/selenium#3781]
I am on Node.js v6.9.5, using "selenium-webdriver": "^3.3.0",

 with `promise.USE_PROMISE_MANAGER` set to `true` =>

I have this sequence:

```js
  before('upload file', {timeout: 30000}, h => {
      driver.get(cdthost + '/#!/home');
      let acq = acqs[0].companyName === 'DUMMY_ACQ' ? acqs[1] : acqs[0];
      let acqId = acq._id;
      assert(acqId, 'acqId is not defined.');
      console.log(' => Acquisition name => ', acq.companyName);
      // on the next line we wait to ensure that the page is loaded
      driver.wait(until.elementLocated(By.id(`open-editing-acqId-${acqId}`)), 5000).then(function(){
        console.log(`XXX open-editing-acqId-${acqId} has been located.`);
      });
      driver.findElement(By.id(`open-editing-acqId-${acqId}`)).click();
      let file = path.resolve($root + '/csv-data/IT-DE-Jasper.csv');
      console.log(' => file to be loaded => ', file);
      let el = driver.findElement(By.id(`import-file-acqId-${acqId}`));
      driver.wait(until.elementIsVisible(el), 2000).then(function(){
        console.log(`XXX import-file-acqId-${acqId} is now visible`);
      });
      el.sendKeys(file);
      driver.findElement(By.id(`submit-file-acqId-${acqId}`)).click();
      return Promise.delay(1000)
      .catch(function (err) {
        console.error('\n\n', ' => Caught promise rejection => ', err.stack || err);
        return Promise.reject(err);
      });
    });
```

**what's very strange is that  XXX is does not get logged, why would that be?** everything else gets logged fine, it's not an issue with template literals as I am on node v6.9.5.

**Comment by ORESoftware** [comment]
Sometimes, I get this unhandle-rejection as well:
```

Unhandled Rejection at: Promise  Promise {
  <rejected> { TimeoutError: Waiting until element is visible
Wait timed out after 4931ms
    at WebDriverError (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/selenium-webdriver/lib/error.js:27:5)
    at TimeoutError (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/selenium-webdriver/lib/error.js:238:5)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/selenium-webdriver/lib/promise.js:2209:17
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) name: 'TimeoutError' } } 
```

so in either case, my catch block is not getting picked up, as far as I can tell.

**Comment by ORESoftware** [comment]
Maybe it's something to do with `promise.USE_PROMISE_MANAGER`?

should I set it to true or false? Having read the docs, it seems this should be set to `false`, for most use case in 2017 and beyond.

**Comment by ORESoftware** [comment]
Another weird thing, with  promise.USE_PROMISE_MANAGER set to true =>

I have:
 
```js
 before('upload file', {timeout: 30000}, h => {
      driver.get(cdthost + '/#!/home');
      let acq = acqs[0].companyName === 'DUMMY_ACQ' ? acqs[1] : acqs[0];
      let acqId = acq._id;
      assert(acqId, 'acqId is not defined.');
      console.log(' => Acquisition name => ', acq.companyName);
      // on the next line we wait to ensure that the page is loaded
      driver.wait(until.elementLocated(By.id(`open-editing-acqId-${acqId}`)), 5000).then(function(){
        console.log(`XXX open-editing-acqId-${acqId} has been located.`);
      });
      driver.findElement(By.id(`open-editing-acqId-${acqId}`)).click();
      let file = path.resolve($root + '/csv-data/IT-DE-Jasper.csv');
      console.log(' => file to be loaded => ', file);
      let el = driver.findElement(By.id(`import-file-acqId-${acqId}`));
      driver.wait(until.elementIsVisible(el), 2000).then(function(){
        console.log(`XXX import-file-acqId-${acqId} is now visible`);
      });
      el.sendKeys(file);
      driver.findElement(By.id(`submit-file-acqId-${acqId}`)).click();
      return Promise.delay(1000)
      .catch(function (err) {
        console.error('\n\n', ' => Suman caught promise rejection => ', err.stack || err);
        return Promise.reject(err);
      });
    });
```

**what's very strange is that  XXX is does not get logged, why would that be?**

**Comment by ORESoftware** [comment]
Ok, I figured it out! Slight learning curve here with your promise management stuff, which is nice. Actually very similar to sqlite3 library which is cool.

Here is the fix:

```js

before('upload file', {timeout: 30000}, h => {
      driver.get(cdthost + '/#!/home');
      let acq = acqs[0].companyName === 'DUMMY_ACQ' ? acqs[1] : acqs[0];
      let acqId = acq._id;
      assert(acqId, 'acqId is not defined.');
      console.log(' => Acquisition name => ', acq.companyName);
      // on the next line we wait to ensure that the page is loaded
      driver.wait(until.elementLocated(By.id(`open-editing-acqId-${acqId}`)), 5000).then(function(){
        console.log(`XXX open-editing-acqId-${acqId} has been located.`);
      });
      driver.findElement(By.id(`open-editing-acqId-${acqId}`)).click();
      let file = path.resolve($root + '/csv-data/IT-DE-Jasper.csv');
      console.log(' => file to be loaded => ', file);
      let el = driver.findElement(By.id(`import-file-acqId-${acqId}`));
      driver.wait(until.elementIsVisible(el), 2000).then(function(){
        console.log(`XXX import-file-acqId-${acqId} is now visible`);
      });
      el.sendKeys(file);
      return driver.findElement(By.id(`submit-file-acqId-${acqId}`)).click().then(function(){
        return Promise.delay(2000)
      })
      .catch(function (err) {
        console.error('\n\n', ' => Suman caught promise rejection => ', err.stack || err);
        return Promise.reject(err);
      });
    });
```

the change is primarily with this code:


```js
      return driver.findElement(By.id(`submit-file-acqId-${acqId}`)).click().then(function(){
        return Promise.delay(2000)
      })
```

I wonder if there is a way you could hook into Bluebird promise and make it talk with your library, that would be cool.

**Comment by jleyba** [comment]
This is working as intended.

```js
 driver.findElement(By.id(`submit-file-acqId-${acqId}`)).click();
return Promise.delay(1000)
    .catch(function (err) {
      console.error('\n\n', ' => Caught promise rejection => ', err.stack || err);
      return Promise.reject(err);
    });
```

Promise.delay() is from another promise library, so the promise manager never sees it. Changing the code to explicitly link them (as you did) is one option. The other is to use `driver.sleep()`

```js
driver.findElement(By.id(`submit-file-acqId-${acqId}`)).click();
return driver.sleep(1000)
    .catch(function (err) {
      console.error('\n\n', ' => Caught promise rejection => ', err.stack || err);
      return Promise.reject(err);
    });
```
