### ISSUE TITLE
fail always

### ISSUE THREAD

**Issue by lbottoni** [SeleniumHQ/selenium#3793]
## Meta -
OS:  Windows 10 64bit
Selenium Version:  2.9.1 IDE
Browser:  
Internet Explorer11 / edge

always i have thie error. if i use standard firefox not have any issue.
start server ok, the test case open the edge browser but after:

`luca.bottoni@LAP-PC-122 C:\Users\luca.bottoni\Downloads\Selenium\driver
> java -jar -Dwebdriver.ie.driver=%HOMEPATH%\Downloads\Selenium\driver\MicrosoftWebDriver.exe %HOMEPATH%\Downloads\Selenium\driver\selenium-server-standalone-3.3.1.jar
17:11:26.367 INFO - Selenium build info: version: '3.3.1', revision: '5234b32'
17:11:26.380 INFO - Launching a standalone Selenium Server
2017-04-07 17:11:26.405:INFO::main: Logging initialized @323ms to org.seleniumhq.jetty9.util.log.StdErrLog
17:11:26.458 INFO - Driver class not found: com.opera.core.systems.OperaDriver
17:11:26.459 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
17:11:26.460 INFO - Driver class not found: com.opera.core.systems.OperaDriver
17:11:26.461 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
17:11:26.467 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WIN10
2017-04-07 17:11:26.520:INFO:osjs.Server:main: jetty-9.2.20.v20161216
2017-04-07 17:11:26.563:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@6d4b1c02{/,null,AVAILABLE}
2017-04-07 17:11:26.753:INFO:osjs.AbstractConnector:main: Started ServerConnector@64bfbc86{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-04-07 17:11:26.754:INFO:osjs.Server:main: Started @672ms
17:11:26.754 INFO - Selenium Server is up and running
17:17:23.095 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
17:17:23.121 INFO - Executing: [new session: Capabilities [{browserName=internet explorer}]])
17:17:23.130 INFO - Creating a new session for Capabilities [{browserName=internet explorer}]
[17:17:23.605] - Listening on http://localhost:21751/
17:17:25.889 INFO - Detected dialect: OSS
17:17:25.918 INFO - Done: [new session: Capabilities [{browserName=internet explorer}]]
17:17:47.871 INFO - Executing: [new session: Capabilities [{browserName=internet explorer}]])
17:17:47.875 INFO - Creating a new session for Capabilities [{browserName=internet explorer}]
[17:17:47.948] - Listening on http://localhost:12584/
17:17:48.475 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'LAP-PC-122', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:190)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:122)
        at org.seleniumhq.jetty9.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
        at org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
        at org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'LAP-PC-122', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:111)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
        ... 9 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{browserName=internet explorer}], required capabilities = Capabilities [{}]
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'LAP-PC-122', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: InternetExplorerDriver
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:230)
        at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:180)
        at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:172)
        at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:148)
        ... 14 more
17:17:48.487 WARN - Exception: Unable to create new remote session. desired capabilities = Capabilities [{browserName=internet explorer}], required capabilities = Capabilities [{}]
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'LAP-PC-122', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: InternetExplorerDriver`

Browser Version:  Edge/11.9 64bit

**Comment by aneeshchandy** [comment]
Does the info here help?

http://stackoverflow.com/questions/40172788/unable-to-create-new-remote-session/40201575#40201575

**Comment by barancev** [comment]
If you want to use MicrosoftWebDriver.exe and run Edge you have to set browserName=edge

**Comment by lbottoni** [comment]
i use this command

> java -jar -Dwebdriver.ie.driver=%HOMEPATH%\Downloads\Selenium\driver\MicrosoftWebDriver.exe %HOMEPATH%\Downloads\Selenium\driver\selenium-server-standalone-3.3.1.jar

 and now in selenium ide tab options>webdriver i have set "edge"

`Caused by: org.openqa.selenium.WebDriverException: The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't create a new driver instance for Capabilities [{browserName=edge}]
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'LAP-PC-122', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:62)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)`

**Comment by lbottoni** [comment]
@aneeshchandy 
i have removed all security level in IE, but selenium open edge

**Comment by lbottoni** [comment]
test from code (without IDE) and PHP
cli
## EDGE
> java -jar -Dwebdriver.ie.driver=%HOMEPATH%\Downloads\Selenium\driver\MicrosoftWebDriver.exe %HOMEPATH%\Downloads\Selenium\driver\selenium-server-standalone-3.3.1.jar

`$capabilities = DesiredCapabilities::microsoftEdge();`
WORK

## FIREFOX
> java -jar  %HOMEPATH%\Downloads\Selenium\driver\selenium-server-standalone-3.3.1.jar

`$capabilities = DesiredCapabilities::firefox();`
WORK

## CHROME
> java -jar -Dwebdriver.chrome.driver=%HOMEPATH%\Downloads\Selenium\driver\chromedriver.exe %HOMEPATH%\Downloads\Selenium\driver\selenium-server-standalone-3.3.1.jar

`$capabilities = DesiredCapabilities::chrome();`
FAILED

### PHP ERROR
`$ php example.php

Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\UnknownServerException' with message ' in C:\wamp\www\selenium\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 114

Facebook\WebDriver\Exception\UnknownServerException: java.net.SocketException: Connection reset
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'LAP-PC-122', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: EventFiringWebDriver in C:\wamp\www\selenium\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 114

Call Stack:
    0.0189     249424   1. {main}() C:\wamp\www\selenium\example.php:0
    2.1854     758832   2. Facebook\WebDriver\Remote\RemoteWebDriver->get() C:\wamp\www\selenium\example.php:21
    2.1854     759416   3. Facebook\WebDriver\Remote\RemoteWebDriver->execute() C:\wamp\www\selenium\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php:214
    2.1855     759552   4. Facebook\WebDriver\Remote\HttpCommandExecutor->execute() C:\wamp\www\selenium\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php:535
    4.2743    1262904   5. Facebook\WebDriver\Exception\WebDriverException::throwException() C:\wamp\www\selenium\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:320


Variables in local scope (#5):
  $message = 'java.net.SocketException: Connection reset\nBuild info: version: \'3.3.1\', revision: \'5234b32\', time: \'2017-03-10 09:04:52 -0800\'\nSystem info: host: \'LAP-PC-122\', ip: \'10.0.75.1\', os.name: \'Windows 10\', os.arch: \'amd64\', os.version: \'10.0\', java.version: \'1.8.0_121\'\nDriver info: driver.version: EventFiringWebDriver'
  $results = array ('state' => 'unknown error', 'sessionId' => '833f682c-2007-4e11-af0b-cfa812f5e58c', 'hCode' => 742976928, 'value' => array ('additionalInformation' => '\nDriver info: driver.version: EventFiringWebDriver', 'localizedMessage' => 'java.net.SocketException: Connection reset\nBuild info: version: \'3.3.1\', revision: \'5234b32\', time: \'2017-03-10 09:04:52 -0800\'\nSystem info: host: \'LAP-PC-122\', ip: \'10.0.75.1\', os.name: \'Windows 10\', os.arch: \'amd64\', os.version: \'10.0\', java.version: \'1.8.0_121\'\nDriver info: driver.version: EventFiringWebDriver', 'supportUrl' => NULL, 'systemInformation' => 'System info: host: \'LAP-PC-122\', ip: \'10.0.75.1\', os.name: \'Windows 10\', os.arch: \'amd64\', os.version: \'10.0\', java.version: \'1.8.0_121\'', 'cause' => array (...), 'stackTrace' => array (...), 'suppressed' => array (...), 'message' => 'java.net.SocketException: Connection reset\nBuild info: version: \'3.3.1\', revision: \'5234b32\', time: \'2017-03-10 09:04:52 -0800\'\nSystem info: host: \'LAP-PC-122\', ip: \'10.0.75.1\', os.name: \'Windows 10\', os.arch: \'amd64\', os.version: \'10.0\', java.version: \'1.8.0_121\'\nDriver info: driver.version: EventFiringWebDriver', 'hCode' => 2088183345, 'class' => 'org.openqa.selenium.WebDriverException', 'buildInformation' => array (...), 'screen' => 'iVBORw0KGgoAAAANSUhEUgAAB4AAAAQ4CAIAAABnsVYUAACAAElEQVR42uy9C3hUVYLvmz739txz74h67zdDur+5dr75Tp/DN2e4zRl1Ok6jnW5wOtrtNKev04PtuWcyo/ZktAfSOGJAGkxHoFDAgIDhJUHsJqKECAoh2hIRMEQgRcgTSMibCsFYQgLhnbv23lW79mPtXZVK5VX5/b7fp1Vrv9deFVb9s7J2Qp+ZWzZuBrkR5HqQa0GuGrgCEO+0H+rF4ZVGCAAAMcHYidV7tnpfV+/96v1he1e5DwAAAAAAXElwCaBvGjBGz5bcWe/B9xq4DBC/tB64hMMrjRAAAAaIseNqyaMtSbQlg7bE0HydAAAAAADoRwAdycBnS+5siZsvBekBiF+aP+3G4ZVGCAAAA0TvtVoiaUsSHclQaL5RAAAAAACED6AvVvzdV95Hvip/xC889kjX0R93Hflx1+c/Pl/2sLCz9OHz5en6qGc9ejaGzlpXvjvIRYD4pfET...'), 'class' => 'org.openqa.selenium.remote.Response', 'status' => 13)
  $status_code = 13`

### SERVER ERROR
`08:58:23.385 INFO - Selenium build info: version: '3.3.1', revision: '5234b32'
08:58:23.387 INFO - Launching a standalone Selenium Server
2017-04-10 08:58:23.409:INFO::main: Logging initialized @257ms to org.seleniumhq.jetty9.util.log.StdErrLog
08:58:23.461 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:58:23.461 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
08:58:23.462 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:58:23.462 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
08:58:23.469 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WIN10
2017-04-10 08:58:23.517:INFO:osjs.Server:main: jetty-9.2.20.v20161216
2017-04-10 08:58:23.556:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@6d4b1c02{/,null,AVAILABLE}
2017-04-10 08:58:23.726:INFO:osjs.AbstractConnector:main: Started ServerConnector@64bfbc86{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-04-10 08:58:23.727:INFO:osjs.Server:main: Started @574ms
08:58:23.727 INFO - Selenium Server is up and running
08:58:36.682 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
08:58:36.708 INFO - Executing: [new session: Capabilities [{browserName=chrome, platform=ANY}]])
08:58:36.716 INFO - Creating a new session for Capabilities [{browserName=chrome, platform=ANY}]
Starting ChromeDriver (v2.9.248315) on port 1457
08:58:38.452 INFO - Detected dialect: OSS
08:58:38.651 INFO - Done: [new session: Capabilities [{browserName=chrome, platform=ANY}]]
08:58:38.690 INFO - Executing: [get: http://www.seleniumhq.org/])
08:58:40.744 WARN - Exception thrown
org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'LAP-PC-122', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: EventFiringWebDriver
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:91)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:325)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:104)
        at com.sun.proxy.$Proxy4.get(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:163)
        at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:40)
        at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:142)
        at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:88)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        ... 16 more
08:58:40.752 WARN - Exception: java.net.SocketException: Connection reset
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'LAP-PC-122', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: EventFiringWebDriver`
