### ISSUE TITLE
Unable to connect to host XXX.X.X.X on port 7055 after 45000 ms. Firefox console output:

### ISSUE THREAD

**Issue by sudamwellappuli** [SeleniumHQ/selenium#3820]
Facing this when try to use selenium 2.53.0 and FF 38.0 esr

## Meta -
OS: 
 Windows 10
Selenium Version:  
2.53.0
Browser:  
  Firefox 

Browser Version:  
38.0 ESR

## Expected Behavior -
Firefox browser should launch and start the execution
## Actual Behavior -
Giving following error.

Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
DeferredSave.extensions.json	DEBUG	Save changes
1491970368131	DeferredSave.extensions.json	DEBUG	Save changes
1491970368132	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"ulJcs_c7FXDR","location":"app-global","version":"38.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1491908647511,"updateDate":1491908647511,"applyBackgroundUpdates":1,"skinnable":true,"size":3169,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"38.0","maxVersion":"38.0"}],"targetPlatforms":[]}
1491970368132	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1491970368133	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1491970368134	addons.xpi-utils	DEBUG	Updating add-on states
1491970368134	addons.xpi-utils	DEBUG	Writing add-ons list
1491970368145	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1491970368145	addons.manager	DEBUG	Provider finished startup: XPIProvider
1491970368145	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1491970368145	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1491970368146	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1491970368146	addons.manager	DEBUG	Starting provider: GMPProvider
1491970368148	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1491970368148	addons.manager	DEBUG	Provider finished startup: GMPProvider
1491970368148	addons.manager	DEBUG	Starting provider: PluginProvider
1491970368148	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1491970368149	addons.manager	DEBUG	Provider finished startup: PluginProvider
1491970368149	addons.manager	DEBUG	Completed startup sequence
1491970371298	DeferredSave.extensions.json	DEBUG	Starting timer
1491970371328	DeferredSave.extensions.json	DEBUG	Starting write
1491970371759	DeferredSave.extensions.json	DEBUG	Write succeeded
1491970371759	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 16
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
JavaScript error: , line 0: uncaught exception: [object Object]
JavaScript error: chrome://fxdriver/content/server.js, line 61: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
1491970373029	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1491970373029	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1491970373030	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1491970394156	addons.manager	DEBUG	shutdown
1491970394156	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1491970394156	addons.xpi	DEBUG	shutdown
1491970394157	addons.xpi-utils	DEBUG	shutdown
1491970394157	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1491970394157	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1491970394159	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1491970394159	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1491970394161	addons.xpi	DEBUG	Notifying XPI shutdown observers
1491970394172	addons.manager	DEBUG	Async provider shutdown done

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at com.thoughtworks.selenium.SeleneseTestNgHelperVir.startBrowserSession(SeleneseTestNgHelperVir.java:305)
	at com.thoughtworks.selenium.SeleneseTestNgHelperVir.setTestContext(SeleneseTestNgHelperVir.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)

**Comment by mikejramsey56** [comment]
I am seeing this on Windows 10, selenium 3.3.1, geckodriver 0.15.0, Firefox 52.0.2 (32-bit).  Same configuration (except firefox is 64-bit) works on linux (Ubuntu 16.04),

**Comment by p0deje** [comment]
I can't reproduce this on the same environment.

Please provide a [concise reproducible test case](http://sscce.org/) so we could reproduce the error.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sudamwellappuli** [comment]
I have update as follow.
Firefox : 47.0.1
Selenium : 2.53.1

But still i'm facing same issue.

**Comment by akshat62** [comment]
Provide code, and update selenium.

**Comment by barancev** [comment]
1) You're using an outdated Selenium (not 2.53)
or
2) You're using too new a browser (newer than FF ESR 45), check version in the browser when it starts
or
3) You have something that blocks connections to port 7055 (antivirus, firewall)
