### ISSUE TITLE
Selenium with Chrome 57 and Firefox 52 fails to start when run arguments are added

### ISSUE THREAD

**Issue by lucianenache** [SeleniumHQ/selenium#3855]
## Meta -
OS: OSX 10.12.3 Sierra

Selenium Version:  <= 3.3.1
I have tried with Selenium 3.X.X

Browser:  
Chrome Version 57.0.2987.133 (64-bit)
Firefox Version 52.0.2

Browser Version:  
Chrome Version 57.0.2987.133 (64-bit)
Firefox Version 52.0.2

## Expected Behavior -
Browser runs in a single instance and is possible to command the window correctly.

## Actual Behavior -
Browser starts in multiple instances for every invocation and the address bar displays the following text: `data:,`

And the following stack trace from the Groovy GEB test framework

```
geb.driver.DriverCreationException: failed to create driver from callback 'script14925194474451929324735$_run_closure1@7f62396e'
	at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:35)
	at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy:85)
	at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy)
	at geb.driver.CachingDriverFactory$SimpleCache.get(CachingDriverFactory.groovy:32)
	at geb.driver.CachingDriverFactory.getDriver(CachingDriverFactory.groovy:84)
	at geb.Configuration.createDriver(Configuration.groovy:382)
	at geb.Configuration.getDriver(Configuration.groovy:371)
	at geb.Browser.getDriver(Browser.groovy:111)
	at geb.navigator.factory.BrowserBackedNavigatorFactory.<init>(BrowserBackedNavigatorFactory.groovy:35)
	at geb.Configuration.createNavigatorFactory(Configuration.groovy:417)
	at geb.Browser.createNavigatorFactory(Browser.groovy:133)
	at geb.Browser.getNavigatorFactory(Browser.groovy:121)
	at geb.Page.init(Page.groovy:144)
	at geb.Browser.createPage(Browser.groovy:855)
	at geb.Browser.to(Browser.groovy:548)
	at geb.Browser.to(Browser.groovy:537)
	at geb.spock.GebSpec.methodMissing(GebSpec.groovy:56)
	at com.test.home.specs.SomeTestIntegrationSpec.Sign in as administrator(DnsDomainIntegrationSpec.groovy:27)
Caused by: org.openqa.selenium.WebDriverException: unknown error: No current window
JavaScript stack:
Error: No current window
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:67:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 59 milliseconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'XXXXXX', ip: 'XXX.XXX.XXX.XXX', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b), userDataDir=/var/folders/3f/5plz7gb928g8y6mlllpsj4g8drptgw/T/.org.chromium.Chromium.FX6Wrh}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=57.0.2987.133, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 93f201e0461548dd3c5773d7cab1bc54
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:661)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:895)
	at script14925194474451929324735.run_closure1(script14925194474451929324735.groovy:40)
	at script14925194474451929324735.run_closure1(script14925194474451929324735.groovy)
	at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:29)
	... 17 more 
```

## Steps to reproduce -
Create a browser instance trough selenium 3.3.1 and try adding arguments as follows:

```
        ChromeOptions options = new ChromeOptions()
        options.addArguments("-incognito")             // If these two lines are commented out
        options.addArguments("enable-automation")      // the browser starts and works correctly

        DesiredCapabilities capabilities = DesiredCapabilities.chrome()
        capabilities.setCapability(ChromeOptions.CAPABILITY, options)

        ChromeDriverManager.getInstance().setup()
        driverInstance = new ChromeDriver(capabilities)
```

The above configuration used to work correctly before the browser version were updated to the ones stated in the description.

**Comment by lmtierney** [comment]
Try incognito with either 2 `-` or none. Arguments should have either `--` or none at all

**Comment by debanjan-selenium** [comment]
I feel @Imtierney suggestion will solve the issue.

**Comment by lucianenache** [comment]
I have tried using both suggestions (```--``` and no dashes) without any luck.

The arguments I am trying to add are the following:
```
 options.addArguments("incognito")
 options.addArguments("enable-automation")
 options.addArguments("disable-infobars")
```

**Comment by p0deje** [comment]
Are you using ChromeDriver that is compatible with this Chrome version?

**Comment by lucianenache** [comment]
Hi, I am using Selenium 3.4.0 as for maven.

The driver is provided by this dependency io.github.bonigarcia:webdrivermanager:1.6.2 and it is also at it's latest.

**Comment by p0deje** [comment]
Just to be precise, can you reproduce this issue without using webdrivermanager (i.e. by setting `webdriver.chrome.driver` property and starting driver)?

**Comment by lucianenache** [comment]
Gonna try it out over the next days and come back with the results, I am quite busy in this period :/

**Comment by barancev** [comment]
I can't reproduce this issue with Java binding. Is it still actual? What exception do you get in version 3.4.0 of Java binding?

**Comment by lucianenache** [comment]
@barancev I have upgraded chrome to ```Version 60.0.3112.40 (Official Build) beta (64-bit)``` and using Selenium 3.4.0 and everything seems to work as expected now. Thanks.
