### ISSUE TITLE
I tried running the example failed

### ISSUE THREAD

**Issue by zhuweiyou** [SeleniumHQ/selenium#3857]
env:

- macOS 10.12.4
- node 7.7.2
- google chrome 57.0.2987.133 (64-bit)
- chrome driver: http://chromedriver.storage.googleapis.com/2.9/chromedriver_mac32.zip

run code:

```js
var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .build();

driver.get('http://www.google.com/ncr');
driver.findElement(By.name('q')).sendKeys('webdriver');
driver.findElement(By.name('btnG')).click();
driver.wait(until.titleIs('webdriver - Google Search'), 1000);
driver.quit();
```

result:

```
/selenium-webdriver-demo/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

Error: spawn EACCES
    at exports._errnoException (util.js:1033:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:386:9)
    at exec (/selenium-webdriver-demo/node_modules/selenium-webdriver/io/exec.js:116:27)
    at resolveCommandLineFlags.then.args (/selenium-webdriver-demo/node_modules/selenium-webdriver/remote/index.js:219:25)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/selenium-webdriver-demo/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/selenium-webdriver-demo/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/selenium-webdriver-demo/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/selenium-webdriver-demo/node_modules/selenium-webdriver/index.js:639:16)
    at Object.<anonymous> (/selenium-webdriver-demo/test.js:7:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by lmtierney** [comment]
Sounds like you don't have permissions setup correctly.

This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

**Comment by zhuweiyou** [comment]
thanks

**Comment by zhuweiyou** [comment]
thanks
