### ISSUE TITLE
FF#52 versus FF#54: org.openqa.selenium.InvalidArgumentException: Expected [object Undefined] undefined to be a string

### ISSUE THREAD

**Issue by zosrothko** [SeleniumHQ/selenium#3858]
## Meta -
OS:  Win7 Pro

Selenium Version:  3.3.1 Server

Browser:  FireFox 

Browser Version:  FireFox 52.0.2 (32 bits) & FireFox 54.0a2 (2017-04-18) (64 bits) 

## Reference
Please see [bug 1357661](https://bugzilla.mozilla.org/show_bug.cgi?id=1357661) where all contexts are specified. The Firefox support team closed this issue as invalid, stating it was an issue for Selenium.

**Comment by jimevans** [comment]
I believe this to be already fixed in current sources for both Selenium and Geckodriver, but proper operation requires the most recent (and as yet unreleased) bits of both projects.

**Comment by zosrothko** [comment]
So wait&see...

**Comment by jaykhimani** [comment]
Similar issue on Linux (ubuntu) as well following are the logs, in case it provides some more information.
```
Caused by: org.openqa.selenium.InvalidArgumentException: Expected [object Undefined] undefined to be a string
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'SFDWSLIN01', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-72-generic', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/tmp/rust_mozprofile.5D8N1nchgBL3, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0, platformVersion=4.4.0-72-generic, moz:processID=5036, browserName=firefox, platformName=linux}]
Session ID: e48faf4b-5f89-4b5b-bdd1-a1a572eb55d4
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:43)
```

**Comment by SaravananJothimani** [comment]
Getting same issue in below configuration. 

OS : Win 7
Selenium : 3.3.1
Browser & Version : FF & 53(64 bit)
