### ISSUE TITLE
Why returned error java.lang.NoClassDefFoundError: com/google/gson/JsonElement?

### ISSUE THREAD

**Issue by drno-reg** [SeleniumHQ/selenium#3881]
Hello,

I have 
OS windows 10,
browser Google Chrome 57.0.2987.133 (64-bit), 
webdriver chrome
ChromeDriver 2.29.461591 (62ebf098771772160f391d75e589dc567915b233), 
Java
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode).

Tried to run Code on Java

```
           System.setProperty("webdriver.chrome.driver", "C:\\Server\\templates\\selenium\\chromedriver.exe");
           WebDriver driver = new ChromeDriver();
        driver.get("http://www.google.com");
```

and returned error

```
Starting ChromeDriver 2.29.461591 (62ebf098771772160f391d75e589dc567915b233) on port 9464
Only local connections are allowed.
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/JsonElement
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:139)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:178)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:167)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:124)
```

How to solve this problem?

**Comment by drno-reg** [comment]
Changed slf4 version to 1.7.25 resolved problem.

**Comment by nizar2yas** [comment]
I'm having the same issue even If I'm not using SLF4J
