### ISSUE TITLE
selenium.interactions.Keyboard is throwing exception

### ISSUE THREAD

**Issue by prasanna532** [SeleniumHQ/selenium#3882]
Keyboard board = ((HasInputDevices) driver).getKeyboard();
        board.pressKey(Keys.ENTER);

throwing exception

Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-9ISPGDN', ip: '192.168.1.122', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:220)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:118)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteKeyboard.pressKey(RemoteKeyboard.java:43)

**Comment by lmtierney** [comment]
I'm going to assume this is related to #3693.

I'll re-open if you can provide a [concise reproducible test case](http://sscce.org/) to show otherwise. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by prasanna532** [comment]
public static void main(String[] args) throws InterruptedException
    {
        System.setProperty("webdriver.gecko.driver", "./geckodriver.exe");
        WebDriver  driver =  new FirefoxDriver();
        driver.get("http://google.com");
        driver.findElement(By.className("gsfi")).sendKeys("Test");
        Keyboard board = ((HasInputDevices) driver).getKeyboard();
        board.pressKey(Keys.ENTER);
    }

Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-9ISPGDN', ip: '192.168.1.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:220)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:118)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteKeyboard.pressKey(RemoteKeyboard.java:43)
	at com.Test.main(Test.java:25)
