### ISSUE TITLE
Not able to set cookie using browser.setCookie API for safari web driver but it works for chrome

### ISSUE THREAD

**Issue by karanbajaj2209** [SeleniumHQ/selenium#3886]
I always get this error while I'm trying to set the cookie using setCookie API for safari web driver, it works fine and does not throw any exception for chrome:

[22:44:16] COMMAND	POST "/wd/hub/session/76fcc0dd-eadc-4db8-9f9d-e8317ab53b25/url"
[22:44:16] DATA	{"url":"http://webdriver.io"}
[22:44:21] RESULT	undefined
[22:44:21] COMMAND	POST "/wd/hub/session/76fcc0dd-eadc-4db8-9f9d-e8317ab53b25/cookie"
[22:44:21] DATA	{"cookie":{"name":"sessionid","value":"test"}}
[22:44:21] COMMAND	GET "/wd/hub/session/76fcc0dd-eadc-4db8-9f9d-e8317ab53b25/screenshot"
[22:44:21] DATA	{}
[22:44:22] RESULT "iVBORw0KGgoAAAANSUhEUgAACvAAAB5kCAYAAABt7ALQAAAAAXNSR0IArs4c6QAAQABJREFUeAHsfQmYHVWZ9lt36+7b3enudDp7QhKSkIQkyA4joIRFQQVkFHFFdBxccB9cZkRHUf9xYUYF+VHHYfndUHQQ3FBZFNnEyE6AEAhkXzrdSa93rf/7qurcqnu77u0l6e7 ... (8107334 more bytes)
[22:44:22] Saved screenshot: ERROR_safari_2017-04-21T05-44-21.489Z.png
Error: An unknown server-side error occurred while processing the command.
at Object.wait (/Users/Karan/git/test-framework/node_modules/fibers/future.js:449:15)
at Object.setCookie (/Users/Karan/git/test-framework/node_modules/wdio-sync/build/index.js:264:31)
at Object.before (/Users/Karan/git/test-framework/wdio.conf.js:168:17)
at execHook (/Users/Karan/git/test-framework/node_modules/wdio-sync/build/index.js:143:35)
- - - - -
at cookie("POST", [object Object]) - setCookie.js:17:17
at setCookie([object Object]) - index.js:244:37
at url("http://webdriver.io") - index.js:244:37
at windowHandleSize([object Object]) - setViewportSize.js:83:26

Code Snippet:

In Wdio.conf.js

    browser.url('http://webdriver.io')
    browser.setCookie({
        name: "sessionid",
        value: "test",
    });
    
    var cookies = browser.getCookie();
    console.log("here are the cookies - "  + cookies);
    
 },

Selenium logs:

11:53:10.401 INFO - Selenium build info: version: '3.3.1', revision: '5234b32'
11:53:10.401 INFO - Launching a standalone Selenium Server
2017-04-21 11:53:10.417:INFO::main: Logging initialized @217ms to org.seleniumhq.jetty9.util.log.StdErrLog
11:53:10.472 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
11:53:10.473 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
11:53:10.473 INFO - Driver class not found: com.opera.core.systems.OperaDriver
11:53:10.473 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
11:53:10.473 INFO - Driver class not found: com.opera.core.systems.OperaDriver
11:53:10.473 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
2017-04-21 11:53:10.513:INFO:osjs.Server:main: jetty-9.2.20.v20161216
2017-04-21 11:53:10.542:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@1bce4f0{/,null,AVAILABLE}
2017-04-21 11:53:10.569:INFO:osjs.AbstractConnector:main: Started ServerConnector@3fee998{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-04-21 11:53:10.570:INFO:osjs.Server:main: Started @370ms
11:53:10.570 INFO - Selenium Server is up and running
11:53:10.821 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
Selenium started
11:53:32.084 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@4f98a545, browserName=safari, javascriptEnabled=true, handlesAlerts=true, maxInstances=1, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}]])
11:53:32.097 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@4f98a545, browserName=safari, javascriptEnabled=true, handlesAlerts=true, maxInstances=1, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}]
11:53:33.010 INFO - Detected dialect: OSS
11:53:33.024 INFO - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@4f98a545, browserName=safari, javascriptEnabled=true, handlesAlerts=true, maxInstances=1, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}]]
11:53:33.050 INFO - Executing: [get window size])
11:53:33.064 INFO - Done: [get window size]
11:53:33.077 INFO - Executing: [execute script: return (function getViewportSize() {
return {
screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),
screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)
};
}).apply(null, arguments), []])
11:53:33.181 INFO - Done: [execute script: return (function getViewportSize() {
return {
screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),
screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)
};
}).apply(null, arguments), []]
11:53:33.187 INFO - Executing: [set window size])
11:53:33.196 INFO - Done: [set window size]
11:53:33.202 INFO - Executing: [execute script: return (function getViewportSize() {
return {
screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),
screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)
};
}).apply(null, arguments), []])
11:53:33.214 INFO - Done: [execute script: return (function getViewportSize() {
return {
screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),
screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)
};
}).apply(null, arguments), []]
11:53:33.219 INFO - Executing: [get: http://webdriver.io])
11:53:35.533 INFO - Done: [get: http://webdriver.io]
11:53:35.544 INFO - Executing: [add cookie: sessionid=test; path=/])
11:53:35.559 WARN - Exception thrown
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12602.4.8, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 636692AC-458B-4F5D-83E8-0802D08D1E6B
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.addCookie(RemoteWebDriver.java:731)
at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringOptions.addCookie(EventFiringWebDriver.java:514)
at org.openqa.selenium.remote.server.handler.AddCookie.call(AddCookie.java:43)
at org.openqa.selenium.remote.server.handler.AddCookie.call(AddCookie.java:31)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
11:53:35.561 WARN - Exception: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds

**Comment by p0deje** [comment]
As far as I know, Safari doesn't support changing cookies. You can log this issue to [SafariDriver](https://bugreport.apple.com/).

**Comment by lukeis** [comment]
Please log Safari driver issues with Apple.

https://bugreport.apple.com/

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by chenry35** [comment]
Hello, any news from Apple? We have open an issue about 'adding cookies' with the new safaridriver, but it got closed because it was a duplicate of another issue.

**Comment by lmtierney** [comment]
We cannot see the bugs either and Apple will not let us know when it's fixed

**Comment by dbow** [comment]
Just a heads up for anyone running into this that ([as reported here](https://github.com/webdriverio/webdriverio/issues/2004)), this appears to be fixed in the current Safari Technology Preview release
