### ISSUE TITLE
unable to launch tests on windows slave

### ISSUE THREAD

**Issue by marcokh** [SeleniumHQ/selenium#3889]
## Meta -
OS:  windows 7

Selenium Version:  
selenium-html-runner-3.0.1.jar

Browser:  firefox

Browser Version:  
52.0.2 32 bits

## Expected Behavior -
running the suite on remote windows slave
## Actual Behavior -
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. 

Hello, I'm attempting to switch to geckodriver as my tests suddenly stopped working after firefox upgraded automatically. I've been playing around for a while now but so far the closest I came to see things running again seems to be using selenium-html-runner-3.0.1.jar (launching with TestNG won't work either but with different error and launching with selenium-server-standalone-3.3.1.jar is telling me to use the html runner jar) and the new gecko driver. 

The test suite have been generated using the IDE

This is the console output of where I'm stuck. Would really appreciate if some could help me out here.

$ java -jar selenium-html-runner-3.0.1.jar -htmlSuite *firefox http://192.168.0.16 c:\jenkins\workspace\tests\bigsuite\TestSuiteLevel1.html c:\jenkins\workspace\tests\TestResultsLevel1.html
Multi-window mode is longer used as an option and will be ignored.
1493020930379	geckodriver	INFO	Listening on 127.0.0.1:15398
Apr 24, 2017 3:02:10 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1493020931558	mozprofile::profile	INFO	Using profile path C:\Windows\rust_mozprofile.dLjuFmoNRjI4
1493020931583	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args []
1493020931626	geckodriver::marionette	INFO	Connecting to Marionette on localhost:53932
1493020932783	addons.manager	DEBUG	Application has been upgraded
1493020933226	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1493020933237	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1493020933257	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1493020933268	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1493020933274	addons.manager	DEBUG	Starting provider: XPIProvider
1493020933276	addons.xpi	DEBUG	startup
1493020933279	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1493020933286	addons.xpi	INFO	Mapping aushelper@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1493020933288	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1493020933290	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1493020933293	addons.xpi	INFO	Mapping webcompat@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1493020933298	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1493020933302	addons.xpi	DEBUG	checkForChanges
1493020933304	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1493020933307	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1493020933314	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1493020933318	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1493020933322	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1493020933325	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1493020933328	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1493020933331	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1493020933335	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1493020933336	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1493020933341	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1493020933344	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1493020933347	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","st":1492660048132},"e10srollout@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","st":1492660048132},"firefox@getpocket.com":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","st":1492660048132},"webcompat@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","st":1492660047867}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1492660048148}}}
1493020933387	addons.xpi-utils	DEBUG	Opening XPI database C:\Windows\rust_mozprofile.dLjuFmoNRjI4\extensions.json
1493020933395	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1493020933454	DeferredSave.extensions.json	DEBUG	Save changes
1493020933459	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1493020933483	DeferredSave.extensions.json	DEBUG	Starting timer
1493020933496	DeferredSave.extensions.json	DEBUG	Save changes
1493020933497	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1493020933548	DeferredSave.extensions.json	DEBUG	Save changes
1493020933550	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1493020933580	DeferredSave.extensions.json	DEBUG	Save changes
1493020933586	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1493020933607	DeferredSave.extensions.json	DEBUG	Save changes
1493020933610	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1493020933649	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1493020933674	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1493020933674	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1493020933677	DeferredSave.extensions.json	DEBUG	Save changes
1493020933679	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1493020933683	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1493020933696	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.9
1493020933706	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1493020933709	DeferredSave.extensions.json	DEBUG	Save changes
1493020933712	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1493020933718	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1493020933739	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1493020933739	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1493020933742	DeferredSave.extensions.json	DEBUG	Save changes
1493020933744	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1493020933748	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1493020933759	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.0
1493020933760	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1493020933763	DeferredSave.extensions.json	DEBUG	Save changes
1493020933764	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1493020933768	DeferredSave.extensions.json	DEBUG	Save changes
1493020933771	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{3f568115-ada7-4205-83a1-3ec94371a108}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","installDate":1492660048132,"updateDate":1492660048132,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8488,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0.2","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1493020933772	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1493020933776	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{77fd0c4a-2112-4c85-8005-68045e70369c}","location":"app-system-defaults","version":"1.9","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","installDate":1492660048132,"updateDate":1492660048132,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":7183,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0.2","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1493020933776	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1493020933781	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{8d4cf3ef-44a7-4e49-8f37-634103f609a2}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","installDate":1492660048132,"updateDate":1492660048132,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":920281,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0.2","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1493020933782	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1493020933785	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{3aaffa63-0548-48e0-b519-9c9b363d6ce9}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","installDate":1492660047867,"updateDate":1492660047867,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1456,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0.2","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1493020933786	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1493020933790	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{551efd35-3c70-48ed-b059-830ba7985886}","location":"app-global","version":"52.0.2","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1492660048148,"updateDate":1492660048148,"applyBackgroundUpdates":1,"skinnable":true,"size":19587,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0.2","maxVersion":"52.0.2"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false}
1493020933793	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1493020933801	DeferredSave.extensions.json	DEBUG	Save changes
1493020933802	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1493020933803	addons.xpi-utils	DEBUG	Updating add-on states
1493020933808	addons.xpi-utils	DEBUG	Writing add-ons list
1493020933821	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1493020933824	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1493020933837	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1493020933842	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.9
1493020933846	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1493020933851	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1493020933858	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1493020933861	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1493020933874	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1493020933876	addons.manager	DEBUG	Provider finished startup: XPIProvider
1493020933876	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1493020933877	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1493020933880	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1493020933883	addons.manager	DEBUG	Starting provider: GMPProvider
1493020933925	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1493020933928	addons.manager	DEBUG	Provider finished startup: GMPProvider
1493020933928	addons.manager	DEBUG	Starting provider: PluginProvider
1493020933930	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1493020933932	addons.manager	DEBUG	Provider finished startup: PluginProvider
1493020933936	addons.manager	DEBUG	Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1493020935615	Marionette	INFO	Listening on port 53932
1493020938497	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1493020938498	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1493020938501	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1493020938619	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1493020938623	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1493020938627	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1493020938643	DeferredSave.extensions.json	DEBUG	Starting write
1493020940475	DeferredSave.extensions.json	DEBUG	Write succeeded
1493020940482	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
Apr 24, 2017 3:02:29 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol.
Apr 24, 2017 3:02:29 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection
Apr 24, 2017 3:02:29 PM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *firefox
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@74868d, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@74868d}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:44 -0700'
System info: host: 'windoz', ip: '169.254.188.116', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.createDriver(HTMLLauncher.java:285)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:107)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)

**Comment by marcokh** [comment]
Just realized 3.4.0 was out with a new version of the runner and there's also a new gecko v16
I upgraded everything and tests seems to launch now :)
