### ISSUE TITLE
Remote fails to create driver for certain browsers

### ISSUE THREAD

**Issue by alycda** [SeleniumHQ/selenium#3945]
## Meta -
OS:  OSX
Selenium Version:  Node
Browser:  Safari, Internet Explorer, Edge

Browser Version:  
10.0, 11.0, 14.14393

## Expected Behavior -
Sauce Labs Automated test should run and provide output.

## Actual Behavior -
Sauce Labs Automated Test errors (not fails), may or may not have any browser/platform specified.

## Steps to reproduce -
```javascript

new Builder()
  .forBrowser('chrome')
  .build()
    .then(driver => {
      // work with driver...
    })
    .catch(reason => {
      console.warn(reason)
    });

```

`$  SELENIUM_REMOTE_URL=http://username:accessKey@ondemand.saucelabs.com:80/wd/hub SELENIUM_BROWSER='internet explorer' npm test`

```shell
TypeError: (intermediate value).forBrowser(...).build(...).then is not a function
      at global.startWebdriver (test/bootstrap.js:66:14)
      at Suite._callee$ (testSuite.js:73:23)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:299:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:154:20)
      at node_modules/regenerator-runtime/runtime.js:201:11
      at new Promise (node_modules/core-js/modules/es6.promise.js:191:7)
      at callInvokeWithMethodAndArg (node_modules/regenerator-runtime/runtime.js:200:16)
      at AsyncIterator.enqueue (node_modules/regenerator-runtime/runtime.js:223:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at Object.runtime.async (node_modules/regenerator-runtime/runtime.js:244:14)
      at Context._callee (tcom-apps/global-nav-refresh/test/secondary-nav/desktop/TOY-15210-layout.js:72:126)
```

If SauceLabs acknowledges a job (most of the time a new job does not even show up in the dashboard), then it remains unnamed and is marked as an error (not test failure), sometimes with no associated browser/platform. Clicking on any of these jobs gives me the following error message: `Your test errored. The new session request was cancelled before a Sauce Labs virtual machine was found. For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages`. This only happens for IE & Safari, not firefox or chrome on any platform

`$  SELENIUM_REMOTE_URL=http://username:accessKey@ondemand.saucelabs.com:80/wd/hub SELENIUM_BROWSER='safari' npm test`

`$  SELENIUM_REMOTE_URL=http://username:accessKey@ondemand.saucelabs.com:80/wd/hub SELENIUM_BROWSER='safari:10.0' npm test`

`$  SELENIUM_REMOTE_URL=http://username:accessKey@ondemand.saucelabs.com:80/wd/hub SELENIUM_BROWSER='safari:10.0:MAC' npm test`

`$  SELENIUM_REMOTE_URL=http://username:accessKey@ondemand.saucelabs.com:80/wd/hub SELENIUM_BROWSER='MicrosoftEdge' npm test`

`$  SELENIUM_REMOTE_URL=http://username:accessKey@ondemand.saucelabs.com:80/wd/hub SELENIUM_BROWSER='MicrosoftEdge:latest' npm test`

`$  SELENIUM_REMOTE_URL=http://username:accessKey@ondemand.saucelabs.com:80/wd/hub SELENIUM_BROWSER='MicrosoftEdge:14.14393' npm test`

`$  SELENIUM_REMOTE_URL=http://username:accessKey@ondemand.saucelabs.com:80/wd/hub SELENIUM_BROWSER='MicrosoftEdge:14.14393:Windows 10' npm test`

`$  SELENIUM_REMOTE_URL=http://username:accessKey@ondemand.saucelabs.com:80/wd/hub SELENIUM_BROWSER='internet explorer:11.0:Windows 8.1' npm test`

**Comment by barancev** [comment]
How can we help on the client side if SauceLabs can't start a job?

**Comment by barancev** [comment]
Closing the issue, considering it's a SauceLabs issue unless found a testimony of the opposite.
