### ISSUE TITLE
Selenium 3.4.0 RemoteWebDriver NoClassDefFoundError

### ISSUE THREAD

**Issue by lemoncodes91** [SeleniumHQ/selenium#3948]
## Meta -
OS:  Win7

Selenium Version:  
 - selenium-server: 3.4.0

Browser:  
 - unrelated

Browser Version:  
 - unrelated

## Expected Behavior -
when i try to execute my java code using this source 
```
WebDriver driver = new RemoteWebDriver(remoteURL, DesiredCapabilities.chrome());
driver.get("http://www.google.com");
```
using selenium-server 3.4.0. it will run the remote chrome.exe and access the URL.

## Actual Behavior -
when i try to execute my java code using this source 
```
WebDriver driver = new RemoteWebDriver(new URL("http://192.168.0.102:5555/wd/hub"), DesiredCapabilities.chrome());
driver.get("http://www.google.com");
```

below error will occur on console log
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Function
	at demo.selenium.remote.remote_driver_test.App.main(App.java:18)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Function
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more

```
using selenium-server 3.4.0. the above error will occur

## Steps to reproduce -
 - On your IDE, create a java project
 - modify pom.xml file, add the above dependencies (see Selenium Version)
 - on main(), add the following source

```
WebDriver driver = new RemoteWebDriver(new URL("http://192.168.0.102:5555/wd/hub"), DesiredCapabilities.chrome());
driver.get("http://www.google.com");
```

## Note -
i tried using selenium-server 3.0.1, everything checks out fine.

**Comment by barancev** [comment]
Update dependency on guava to version 21

**Comment by lemoncodes91** [comment]
guava is already ver 21.0 on my maven

**Comment by lemoncodes91** [comment]
btw when i try using 3.0.1 version. everything is fine.. but when i use 3.4.0 PLUST selenium-standalone-server.2.53.0.jar everything is OK.. is "selenium-standalone-server.2.53.0.jar" really needed to be on your buildpath? i thought this is only use for starting remote drivers

**Comment by barancev** [comment]
Run mvn dependency:tree and paste the result.

**Comment by lemoncodes91** [comment]
dep-tree result

```
[[1;34mINFO[m] Scanning for projects...
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1mBuilding remote-driver-test 0.0.1-SNAPSHOT[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;33mWARNING[m] The POM for org.apache.commons:commons-lang3:jar:3.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mmaven-dependency-plugin:2.8:tree[m [1m(default-cli)[m @ [36mremote-driver-test[0;1m ---[m
[[1;34mINFO[m] demo.selenium.remote:remote-driver-test:jar:0.0.1-SNAPSHOT
[[1;34mINFO[m] +- junit:junit:jar:3.8.1:test
[[1;34mINFO[m] \- org.seleniumhq.selenium:selenium-server:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-java:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-api:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:selenium-support:jar:3.4.0:compile
[[1;34mINFO[m]    +- com.beust:jcommander:jar:1.48:compile
[[1;34mINFO[m]    +- cglib:cglib-nodep:jar:3.2.4:compile
[[1;34mINFO[m]    +- org.apache.commons:commons-exec:jar:1.3:compile
[[1;34mINFO[m]    +- org.apache.commons:commons-lang3:jar:3.5:compile
[[1;34mINFO[m]    +- commons-codec:commons-codec:jar:1.10:compile
[[1;34mINFO[m]    +- commons-io:commons-io:jar:2.5:compile
[[1;34mINFO[m]    +- commons-logging:commons-logging:jar:1.2:compile
[[1;34mINFO[m]    +- org.w3c.css:sac:jar:1.3:compile
[[1;34mINFO[m]    +- net.sourceforge.cssparser:cssparser:jar:0.9.22:compile
[[1;34mINFO[m]    +- com.google.code.gson:gson:jar:2.8.0:compile
[[1;34mINFO[m]    +- com.google.guava:guava:jar:21.0:compile
[[1;34mINFO[m]    +- org.hamcrest:hamcrest-core:jar:1.3:compile
[[1;34mINFO[m]    +- net.sourceforge.htmlunit:htmlunit:jar:2.26:compile
[[1;34mINFO[m]    +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.26:compile
[[1;34mINFO[m]    +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.25:compile
[[1;34mINFO[m]    +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[[1;34mINFO[m]    +- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[[1;34mINFO[m]    +- org.apache.httpcomponents:httpmime:jar:4.5.3:compile
[[1;34mINFO[m]    +- net.jcip:jcip-annotations:jar:1.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:jetty-repacked:jar:9.4.1.v20170120:compile
[[1;34mINFO[m]    +- org.eclipse.jetty:jetty-io:jar:9.4.1.v20170120:compile
[[1;34mINFO[m]    +- org.eclipse.jetty:jetty-util:jar:9.4.1.v20170120:compile
[[1;34mINFO[m]    +- net.java.dev.jna:jna:jar:4.1.0:compile
[[1;34mINFO[m]    +- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[[1;34mINFO[m]    +- com.codeborne:phantomjsdriver:jar:1.4.0:compile
[[1;34mINFO[m]    +- org.seleniumhq.selenium:htmlunit-driver:jar:2.26:compile
[[1;34mINFO[m]    +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[[1;34mINFO[m]    +- org.eclipse.jetty.websocket:websocket-api:jar:9.4.3.v20170317:compile
[[1;34mINFO[m]    +- org.eclipse.jetty.websocket:websocket-client:jar:9.4.3.v20170317:compile
[[1;34mINFO[m]    |  \- org.eclipse.jetty:jetty-client:jar:9.4.3.v20170317:compile
[[1;34mINFO[m]    |     \- org.eclipse.jetty:jetty-http:jar:9.4.3.v20170317:compile
[[1;34mINFO[m]    +- org.eclipse.jetty.websocket:websocket-common:jar:9.4.3.v20170317:compile
[[1;34mINFO[m]    +- xalan:serializer:jar:2.7.2:compile
[[1;34mINFO[m]    +- xalan:xalan:jar:2.7.2:compile
[[1;34mINFO[m]    +- xerces:xercesImpl:jar:2.11.0:compile
[[1;34mINFO[m]    +- xml-apis:xml-apis:jar:1.4.01:compile
[[1;34mINFO[m]    \- org.yaml:snakeyaml:jar:1.15:compile
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;32mBUILD SUCCESS[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time: 4.399 s
[[1;34mINFO[m] Finished at: 2017-05-01T22:51:52+08:00
[[1;34mINFO[m] Final Memory: 15M/158M
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
```

**Comment by barancev** [comment]
http://google.github.io/guava/releases/21.0/api/docs/com/google/common/base/Function.html
It is there. Investigate your project classpath in IDE. Re-import the POM file to IDE.

**Comment by lemoncodes91** [comment]
There is an issue on my IDE itself.. when using ordinary eclipse neon 4.6.3 it id OK. But when using spring studio 3.8.4 above error occurs. Buildpath/classpath issue on sts ide.
