### ISSUE TITLE
Unable to start chrome driver on Windows using C# and Chrome Canary

### ISSUE THREAD

**Issue by jdmesalosada** [SeleniumHQ/selenium#3970]
## Meta -
OS:  
Windows

Selenium Version:  
2.53.1

Browser:  
Versión 60.0.3088.0 (Build oficial) canary (64 bits)

Browser Version:  
Versión 60.0.3088.0 (Build oficial) canary (64 bits)

## Actual Behavior -
When you create the chrome driver instance an exception is being displayed.

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at UnitTestProject1.UnitTest1.TestMethod1() in C:\UnitTest1.cs:line 26
Result Message:	
Test method UnitTestProject1.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: unknown error: chrome failed to start
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.10240 x86_64)

## Steps to reproduce -
I'm using the following code in order to run chrome headless:

ChromeOptions chromeOptions = new ChromeOptions();
            chromeOptions.BinaryLocation = chromeCanaryDirectoryPath;
            chromeOptions.AddArgument("--headless");
            IWebDriver driver = new ChromeDriver(chromeDirectory, chromeOptions);

**Comment by lmtierney** [comment]
Isn't headless chrome only available on Linux?

**Comment by lmtierney** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=686608
