### ISSUE TITLE
Selenium Firefox driver doesn't work with Firefox ESR 45.9.0 under Debian Jessie

### ISSUE THREAD

**Issue by gouessej** [SeleniumHQ/selenium#3993]
OS:  Debian Jessie
Architecture: ARM 7 (armhf v7)
Selenium Version: 3.4.0
Browser:  Firefox
Browser Version: 45.9.0
Gecko driver version: 0.16.1

## Expected Behavior -
new FirefoxDriver() doesn't throw any exception.

## Actual Behavior -
org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'A20-OLinuXino', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'arm', os.version: '3.4.103-00033-g9a1cd03-dirty', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0: 0xb6de95b3 - backtrace::backtrace::trace::h8166ac046b01de0f
   1: 0xb6de9acb - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
   2: 0xb6dab093 - geckodriver::marionette::MarionetteHandler::create_connection::h826627e00cb80122
   3: 0xb6db30fb - >::handle_command::hea45c68e72b3846e
   4: 0xb6da784f - webdriver::server::start::{{closure}}::h3085395b806d111c
   5: 0xb6d79be3 - std::panicking::try::do_call::h86a6e0cb77ef092f
   6: 0xb6f06157 - panic_unwind::__rust_maybe_catch_panic
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libpanic_unwind/lib.rs:98
   7: 0xb6d8bc1f - >::call_box::h995a340dc6da2f87
   8: 0xb6efff53 - alloc::boxed::{{impl}}::call_once<(),()>
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/liballoc/boxed.rs:624
                 - std::sys_common::thread::start_thread
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/sys_common/thread.rs:21
                 - std::sys::imp::thread::{{impl}}::new::thread_start
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/sys/unix/thread.rs:84
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
    at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
    at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
    at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:137)
    at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:191)
    at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:108)
    at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:137)

## Steps to reproduce -
```
import org.openqa.selenium.firefox.FirefoxDriver;
public class Main {
    public static void main(String[] args) {
           new FirefoxDriver();
    }
}
```

**Comment by AutomatedTester** [comment]
Unfortunately GeckoDriver doesnt support Firefox 45. You will need to downgrade Selenium to 3.3, maybe... and maybe 0.15 for GeckoDriver or set the capability `marionette` to `false` and use the old FirefoxDriver

**Comment by gouessej** [comment]
I already tried to use Selenium 2.53.0, it didn't work:
http://stackoverflow.com/questions/43834782/selenium-firefox-driver-doesnt-seem-to-work-with-firefox-esr-under-debian-jessi

I'll try to use another web driver but it's really annoying as I wanted to mimic Firefox behaviour. I hope that chromium is supported.
