### ISSUE TITLE
Pageload Timeout does not work in 3.4.1

### ISSUE THREAD

**Issue by hadojae** [SeleniumHQ/selenium#4004]
## Meta -
OS:  Ubuntu 16.04
Selenium Version:  3.4.1 (Python)
Browser:  Firefox
Browser Version:  53.0 

## Expected Behavior -

>>> browser.set_page_load_timeout(30)
>>> 

## Actual Behavior -

>>> browser.set_page_load_timeout(30)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 727, in set_page_load_timeout
    'type': 'page load'})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unrecognised timeout: page load

## Steps to reproduce -

Just call browser.set_page_load_timeout(30)

## Notes

Expected behaviour occurs when making the below change at https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L762

Broken
`                'type': 'page load'})`

Working
`                'type': 'pageLoad'})`

**Comment by lmtierney** [comment]
What version of geckodriver are you using?

**Comment by AutomatedTester** [comment]
Closing as no answer to question
