### ISSUE TITLE
Firefox Webdriver Fails with call to get when using FirefoxProfile

### ISSUE THREAD

**Issue by jprince14** [SeleniumHQ/selenium#4009]
The selenium firefox webdriver is crashing for me during calls to the "get" function. The error only occurs when I am using a firefox_profile, when firefox_profile=None everything works fine. I am using Windows 10, Firefox 53.0.2 64-Bit, Gecko Driver v0.16.1 win64, selenium 3.4.1 and python 3.5.1

Below is my code
```
from selenium import webdriver
import os

downloadsDir = os.path.join(os.getenv('HOMEPATH'),"Downloads")
geckoDriverPath = ""
for file in os.listdir(downloadsDir):
    if file.startswith("geckodriver") and not file.endswith(".log"):
        geckoDriverPath = os.path.join(downloadsDir, file)
        break

profilesDir = os.path.join(os.getenv('APPDATA') , "Mozilla", "Firefox", "Profiles")
ffProfileDir = ""
for profile in os.listdir(profilesDir):
    if profile.endswith(".default"):
        ffProfileDir = os.path.join(profilesDir, profile)
        break

firefoxDeskopProfile = webdriver.FirefoxProfile(profile_directory=ffProfileDir)            

#If I change the line below to "firefoxDesktopDriver = webdriver.Firefox(executable_path=geckoDriverPath)" then the code succeeds
firefoxDesktopDriver = webdriver.Firefox(firefox_profile=firefoxDeskopProfile, executable_path=geckoDriverPath)

firefoxDesktopDriver.get("https://www.google.com")
```

Below is the error I receive

```
   C:\Users\username\Downloads>python test.py
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    firefoxDesktopDriver.get("https://www.google.com")
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 264, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: No such content frame; perhaps the listener was not registered?
```

**Comment by p0deje** [comment]
I've tried reproducing this and it works fine (however, I tried on Mac, not sure if this changes anything though).

There is a chance something is broken in your profile which leads to this issue. I'd recommend not using your default profile but rather to start with a fresh one.

I'm going to close this issue as it's not on Selenium side. Feel free to reopen in [geckodriver issues](https://github.com/mozilla/geckodriver/issues).
