### ISSUE TITLE
Selenium server -3.4.0 expects a  value to be passed for -debug throws exception

### ISSUE THREAD

**Issue by skhanam** [SeleniumHQ/selenium#4010]
## Meta -
OS:  Mac OSSierra

Selenium Version:  
Selenium server 3.4.0

java -jar selenium-server-standalone-3.4.0.jar  -role hub  -debug

exception :

Exception in thread "main" com.beust.jcommander.ParameterException: Expected a value after parameter -debug
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:883)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:857)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
	at org.openqa.grid.selenium.GridLauncherV3$2.setConfiguration(GridLauncherV3.java:245)
	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:155)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:75)

## Steps to reproduce -
java -jar selenium-server-standalone-3.4.0.jar  -role hub  -debug on terminal

**Comment by lmtierney** [comment]
This is the intended use for `3.4` (you can see by passing `-h` when starting up standalone). However, this was decided to be changed back to the behavior you're expecting with 8f325df and will be in the next release.
