### ISSUE TITLE
selenium Grid

### ISSUE THREAD

**Issue by liaeb** [SeleniumHQ/selenium#4018]
i am beginner in selenium webdriver
i am use grid for parallel but have an error "Can not Parse capability:chrome option"
stacktrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at FirstPackage.Methods.SetupTest() in C:\Users\ebrahimpour.l\Documents\Visual Studio 2015\Projects\FirstPackage\FirstPackage\Methods.cs:line 80

and complete of error is:
unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: Arguments
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.01 seconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'SF13', ip: '172.16.1.18', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver

//
os:windows 10
chrome version: 58.0.3029.110
serverr standalone: selenium-server-standalone-2.47.1.jar
chromedriver version:2.29
//
please help me ....
i have this error 4 days and i am tired:(
@juliemr

**Comment by liaeb** [comment]
@os:windows 10
chrome version: 58.0.3029.110
serverr standalone: selenium-server-standalone-2.47.1.jar
chromedriver version:2.29

**Comment by liaeb** [comment]
have another problem...!
i have 2 tests that wanna to parallel .
but grid opened two browsers but implement just one browser

**Comment by jimevans** [comment]
This tracker is not the proper place for usage questions. The [selenium-users making list](https://groups.google.com/forum/#!forum/selenium-users) is a more appropriate forum for questions.
