### ISSUE TITLE
Unsupported Command Error when using Safari

### ISSUE THREAD

**Issue by JasonLunn** [SeleniumHQ/selenium#4030]
## Meta -
OS:  
macOS 10.12.4 Sierra
Selenium Version:  
3.4.0
Browser:  
Safari

Browser Version:  
10.1 / 12603.1.30.0.34

## Expected Behavior -

Invoking `switch_to.active_element` works without raising an exception when using Safari

## Actual Behavior -

Invoking `switch_to.active_element` raises an exception when using Safari

```
Backtrace of #<Selenium::WebDriver::Error::UnknownCommandError: HTTP method 'POST' is not supported for command '/session/35BC3FC0-42ED-4052-BEDD-930E9BB6A9BF/element/active'.
Command duration or timeout: 4 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'experimental-01', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12603.1.30.0.34, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, platformName=macOS, cssSelectorsEnabled=true}]
Session ID: 35BC3FC0-42ED-4052-BEDD-930E9BB6A9BF (org.openqa.selenium.UnsupportedCommandException)>:

[remote server] sun.reflect.NativeConstructorAccessorImpl(NativeConstructorAccessorImpl.java):-2:in `newInstance0'
[remote server] sun.reflect.NativeConstructorAccessorImpl(NativeConstructorAccessorImpl.java):62:in `newInstance'
[remote server] sun.reflect.DelegatingConstructorAccessorImpl(DelegatingConstructorAccessorImpl.java):45:in `newInstance'
[remote server] java.lang.reflect.Constructor(Constructor.java):423:in `newInstance'
[remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):215:in `createThrowable'
[remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):167:in `throwIfResponseFailed'
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):671:in `execute'
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):694:in `execute'
[remote server] org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator(RemoteWebDriver.java):1015:in `activeElement'
[remote server] org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringTargetLocator(EventFiringWebDriver.java):608:in `activeElement'
[remote server] org.openqa.selenium.remote.server.handler.FindActiveElement(FindActiveElement.java):36:in `call'
[remote server] org.openqa.selenium.remote.server.handler.FindActiveElement(FindActiveElement.java):27:in `call'
[remote server] java.util.concurrent.FutureTask(FutureTask.java):266:in `run'
[remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
[remote server] java.util.concurrent.ThreadPoolExecutor(ThreadPoolExecutor.java):1142:in `runWorker'
[remote server] java.util.concurrent.ThreadPoolExecutor$Worker(ThreadPoolExecutor.java):617:in `run'
[remote server] java.lang.Thread(Thread.java):748:in `run'
/Users/vagrant/.rvm/gems/jruby-9.1.7.0@player/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
/Users/vagrant/.rvm/gems/jruby-9.1.7.0@player/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
/Users/vagrant/.rvm/gems/jruby-9.1.7.0@player/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/Users/vagrant/.rvm/gems/jruby-9.1.7.0@player/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
/Users/vagrant/.rvm/gems/jruby-9.1.7.0@player/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
/Users/vagrant/.rvm/gems/jruby-9.1.7.0@player/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:678:in `raw_execute'
/Users/vagrant/.rvm/gems/jruby-9.1.7.0@player/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:656:in `execute'
/Users/vagrant/.rvm/gems/jruby-9.1.7.0@player/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:616:in `active_element'
/Users/vagrant/.rvm/gems/jruby-9.1.7.0@player/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/target_locator.rb:91:in `active_element'
```

## Steps to reproduce -

```ruby
require 'selenium-webdriver'
wd = Selenium::WebDriver.for :remote, desired_capabilities: { browserName: 'safari' }
wd.navigate.to 'http://example.com'
wd.switch_to.active_element
```

**Comment by lmtierney** [comment]
This is because safaridriver isn't telling us that it is accepting w3c commands, so we are sending the oss command (which was a `POST`, w3c is a `GET`)

Please log any Safari issue with Apple: https://bugreport.apple.com/

**Comment by JasonLunn** [comment]
@lmtierney - I've opened an issue with apple (problem id 32247008). What do you think about reopening this issue until that one is resolved for tracking purposes?

**Comment by lmtierney** [comment]
Apple issues are only visible to the reporter. You can always comment back here once it's resolved for tracking purposes, but as it's not an issue with selenium the issue will stay closed.

**Comment by JasonLunn** [comment]
https://openradar.appspot.com/radar?id=6176713348218880

**Comment by burg** [comment]
Hi friends, this was recently fixed on our side and should make it into an upcoming Safari Technology Preview release.

**Comment by JasonLunn** [comment]
@burg Thanks much!
