### ISSUE TITLE
"InvalidArgumentError: Could not convert 'text' to string" on selenium 3.4.0/firefox 53

### ISSUE THREAD

**Issue by dmaii** [SeleniumHQ/selenium#4041]
## Meta -
OS:  Ubuntu Xenial
Selenium Version:  3.4.0
Browser:  Firefox

Browser Version:  53

## Expected Behavior -
The [google_search.js example](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/example/google_search.js) should run without issues using the latest version of the `selenium/standalone-firefox` .

## Actual Behavior -

I get the following error:

```
/usr/src/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

InvalidArgumentError: Could not convert 'text' to string
    at WebDriverError (/usr/src/node_modules/selenium-webdriver/lib/error.js:27:5)
    at InvalidArgumentError (/usr/src/node_modules/selenium-webdriver/lib/error.js:64:5)
    at Object.throwDecodedError (/usr/src/node_modules/selenium-webdriver/lib/error.js:489:11)
    at parseHttpResponse (/usr/src/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebElement.sendKeys()
    at thenableWebDriverProxy.schedule (/usr/src/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at WebElementPromise.schedule_ (/usr/src/node_modules/selenium-webdriver/lib/webdriver.js:2024:25)
    at WebElementPromise.sendKeys (/usr/src/node_modules/selenium-webdriver/lib/webdriver.js:2187:19)
    at driver.get.then._ (/usr/src/node_modules/selenium-webdriver/example/google_search.js:47:49)
    at ManagedPromise.invokeCallback_ (/usr/src/node_modules/selenium-webdriver/lib/promise.js:1384:14)
    at TaskQueue.execute_ (/usr/src/node_modules/selenium-webdriver/lib/promise.js:3092:14)
    at TaskQueue.executeNext_ (/usr/src/node_modules/selenium-webdriver/lib/promise.js:3075:27)
    at asyncRun (/usr/src/node_modules/selenium-webdriver/lib/promise.js:2935:27)
    at /usr/src/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

## Steps to reproduce -
`docker build` and `docker run` this [`Dockerfile`](https://gist.github.com/dmaii/56151055abd9453ffa875b8920f90719), which uses the latest versions of the `selenium/standalone-firefox` docker image and `selenium-webdriver` npm module.

**Comment by bighitbiker3** [comment]
I'm getting this as well

**Comment by lmtierney** [comment]
This is fixed in 6907a12, will be in the next release of javascript bindings

**Comment by mo** [comment]
@jleyba did you decide on a date for 3.4.1 yet?

**Comment by gkushang** [comment]
Is this fix released yet?

**Comment by bighitbiker3** [comment]
@gkushang Nope, looks like we're still on 3.4.0

**Comment by TK23061984** [comment]
still we have this issue in 3.4.0

**Comment by mo** [comment]
@jleyba is there someone other than you who can prepare a new release?

**Comment by gkushang** [comment]
+1
