### ISSUE TITLE
build() command fails on latest versions of selenium/geckodriver/ff53

### ISSUE THREAD

**Issue by omar62** [SeleniumHQ/selenium#4062]
Hello,

I'm fairly new to this selenium/webdriver thing. I have this script that used to work fine under firefox 52 and earlier:
    
```
(on cmd: node C:\web\_scripts\utils\checkHotmail.js)

var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;  
                            
var driver = new webdriver.Builder()
    .forBrowser('firefox')
    .build(); 
```                

One morning firefox autoupdated and poof!, all broken down. I updated everything, and now this is what I get:

```
C:\SDKs\nodejs\node_modules\selenium-webdriver\lib\promise.js:2517
        throw error;

WebDriverError: Unable to parse new session response: {"value": {"sessionId":"6003ff7a-0781-43a7-af07-c1d3e6d49ca3","cap
abilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"53.0.3","moz:accessibilityChecks":fals
e,"moz:processID":1464,"moz:profile":"C:\\Users\\JULIUS~1\\AppData\\Local\\Temp\\rust_mozprofile.LOoCU5TYK9vm","pageLoad
Strategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeout
s":{"implicit":0,"pageLoad":300000,"script":30000}}}}
    at WebDriverError (C:\SDKs\nodejs\node_modules\selenium-webdriver\lib\error.js:27:5)
    at doSend.then.response (C:\SDKs\nodejs\node_modules\selenium-webdriver\lib\http.js:445:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\SDKs\nodejs\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (C:\SDKs\nodejs\node_modules\selenium-webdriver\firefox\index.js:640:55)
    at createDriver (C:\SDKs\nodejs\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (C:\SDKs\nodejs\node_modules\selenium-webdriver\index.js:642:16)
    at Object.<anonymous> (C:\web\_scripts\utils\checkHotmail.js:13:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

That  _(C:\web\_scripts\utils\checkHotmail.js:13:6)_ is where the _.build(_) command sits.

I'm using the very last latest uptatedest version of everything. Any ideas? 

Thanks

## Firefox Version
53.0.3, 32 bit

## Platform
win7

**Comment by jleyba** [comment]
This isn't reproducible with geckodriver 0.19.0 (the latest release)
