### ISSUE TITLE
node.js (Unexpected token ...) at require

### ISSUE THREAD

**Issue by dxwc** [SeleniumHQ/selenium#4099]
OS:  Ubuntu 17.04
Selenium Version: ^3.4.0
Node: v4.7.2

## Expected Behavior -
Require module without error.

## Actual Behavior -

    pwd/node_modules/selenium-webdriver/index.js:115
      static createSession(...args) {}
			       ^^^
    SyntaxError: Unexpected token ...
	at exports.runInThisContext (vm.js:53:16)
	at Module._compile (module.js:373:25)
	at Object.Module._extensions..js (module.js:416:10)
	at Module.load (module.js:343:32)
	at Function.Module._load (module.js:300:12)
	at Module.require (module.js:353:17)
	at require (internal/module.js:12:17)
	at repl:1:1
	at REPLServer.defaultEval (repl.js:272:27)
	at bound (domain.js:287:14)

## Steps to reproduce -

- `npm install selenium-webdriver --save-dev`
- `node`
- `> require('selenium-webdriver')`

**Comment by AutomatedTester** [comment]
Node 4 came out of active LTS in April 2017 and is only receiving security updates according to https://github.com/nodejs/LTS. Please try a supported Node JS version (released or in active LTS)
