### ISSUE TITLE
InvalidOperationException when newing up new RemoteWebDriver on 3.4.0 only.

### ISSUE THREAD

**Issue by StrangeWill** [SeleniumHQ/selenium#4100]
## Meta -
OS:  
Hub: Debian 8, Servers: Windows 2012 R2
Selenium Version:  
3.4.0 (both hub and servers)
Browser:  
Chrome

Browser Version:  
N/A

## Expected Behavior -
Grid should hook up and run.

## Actual Behavior -
`new RemoteWebDriver(new Uri("http://[hostname]:4444/wd/hub"), DesiredCapabilities.Chrome(), TimeSpan.FromMinutes(15));` throws a InvalidOperationException with an empty string as the message, with the following stack trace:

```
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
```

## Steps to reproduce -
Update to web driver 3.4.0, instantiate a new web driver.

---

I was able to roll back to 2.3.0 of the .NET libs and the issue goes away, the worst part is I'm getting an empty error message which is leaving me to believe it's this line:
https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L1384

Being as the other lines that throw InvalidOperationExceptions should at least give me an empty string with formatting in it.

I  have the hub set up with full logging, I see absolutely nothing come in prior to this error.

**Comment by jimevans** [comment]
This is another manifestation of #3808. Thanks for the report, but it's not the .NET bindings at fault here.
