### ISSUE TITLE
ERROR - Failed to start new browser session, shutdown browser and clear all session data

### ISSUE THREAD

**Issue by saharawolf** [SeleniumHQ/selenium#4118]
Hi, 

I am having difficulties running cases on selenium standalone server. 
My platform is on a CENTOS 6 server, SELENIUM 2.45 (I followed a guide) and Firefox last version.

i run my server using this command 
/usr/bin/java -jar /opt/selenium/selenium-server-standalone.jar -port 4444 -browserTimeout 300 -firefoxProfileTemplate /home/selenium/firefox-profile

Server starts successfully and shows these lines : 
15:55:06.427 INFO - Launching a standalone server
15:55:06.462 INFO - Java: Sun Microsystems Inc. 23.41-b41
15:55:06.462 INFO - OS: Linux 2.6.32-696.3.1.el6.x86_64 amd64
15:55:06.478 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
15:55:06.535 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match with current platform: LINUX
15:55:06.599 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
15:55:06.600 INFO - Version Jetty/5.1.x
15:55:06.601 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
15:55:06.601 INFO - Started HttpContext[/selenium-server,/selenium-server]
15:55:06.601 INFO - Started HttpContext[/,/]
15:56:50.749 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@4604764b
15:56:50.749 INFO - Started HttpContext[/wd,/wd]
15:56:50.756 INFO - Started SocketListener on 0.0.0.0:4444
15:56:50.756 INFO - Started org.openqa.jetty.jetty.Server@39a44220

After that i tried to run a simple scenario that i created using the IDE, but get this error:

on client : 
UNKNOWN: Error requesting http://"selenium":4444/selenium-server/driver/:
Failed to start new browser session: org.openqa.selenium.server.RemoteCommandException: Error while launching browser

on server : 
15:57:08.456 INFO - Command request: getNewBrowserSession[*firefox, http://mywebsite:8004] on session null
15:57:08.458 INFO - creating new remote session
15:57:08.475 WARN - Caution: '/usr/bin/firefox': file is a script file, not a real executable.  The browser environment is no longer fully under RC control
15:57:08.476 INFO - Allocated session 3f94301f39a044cb8335b1dc7e834db3 for http://myserver:8004, launching...
jar:file:/opt/selenium/selenium-server-standalone-2.45.0.jar!/customProfileDirCUSTFFCHROME
15:57:08.552 INFO - Preparing Firefox profile...
15:57:28.665 ERROR - Failed to start new browser session, shutdown browser and clear all session data
java.lang.RuntimeException: Timed out waiting for profile to be created!
        at org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.waitForFullProfileToBeCreated(FirefoxChromeLauncher.java:304)
        at org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.populateCustomProfileDirectory(FirefoxChromeLauncher.java:116)
        at org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.launch(FirefoxChromeLauncher.java:86)
        at org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.launchRemoteSession(FirefoxChromeLauncher.java:343)
        at org.openqa.selenium.server.browserlaunchers.FirefoxLauncher.launchRemoteSession(FirefoxLauncher.java:102)
        at org.openqa.selenium.server.BrowserSessionFactory.createNewRemoteSession(BrowserSessionFactory.java:400)
        at org.openqa.selenium.server.BrowserSessionFactory.getNewBrowserSession(BrowserSessionFactory.java:144)
        at org.openqa.selenium.server.BrowserSessionFactory.getNewBrowserSession(BrowserSessionFactory.java:105)
        at org.openqa.selenium.server.SeleniumDriverResourceHandler.getNewBrowserSession(SeleniumDriverResourceHandler.java:809)
        at org.openqa.selenium.server.SeleniumDriverResourceHandler.doCommand(SeleniumDriverResourceHandler.java:435)
        at org.openqa.selenium.server.SeleniumDriverResourceHandler.handleCommandRequest(SeleniumDriverResourceHandler.java:405)
        at org.openqa.selenium.server.SeleniumDriverResourceHandler.handle(SeleniumDriverResourceHandler.java:151)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
        at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
        at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
        at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
        at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
        at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
        at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
        at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
15:57:28.672 INFO - Got result: Failed to start new browser session: org.openqa.selenium.server.RemoteCommandException: Error while launching browser on session null

Can anyone help please ?

thank you

**Comment by cgoldberg** [comment]
if you want to test against recent versions of Firefox, you must upgrade your selenium version and also install geckodriver.

**Comment by AutomatedTester** [comment]
could you upgrade to Firefox 53 and Selenium 3.4.0?

**Comment by barancev** [comment]
Closing due to inactivity.
