### ISSUE TITLE
Unable to convert: {actions=[org.openqa.selenium.interactions.Sequence@4fa4f485]}

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [SeleniumHQ/selenium#4127]
Selenium WebDriver 3.4.0 fails to execute line of code:
actions().moveToElement($(SEARCH_FIELD)).perform();
and fails with 
org.openqa.selenium.WebDriverException: Unable to convert: {actions=[org.openqa.selenium.interactions.Sequence@4fa4f485]}
message.
I'm using Firefox 53.0 (32-bit) with  Configuration.browser = "marionette"; setting and
RemoteWebDriver remote = (RemoteWebDriver) getWebDriver(); driver setting.
As far as any test reach a code like: actions().moveToElement($(SEARCH_FIELD)).**perform()**;
it fails with a message below:
`org.openqa.selenium.WebDriverException: Unable to convert: {actions=[org.openqa.selenium.interactions.Sequence@4fa4f485]}
	at org.openqa.selenium.remote.BeanToJsonConverter.convert(BeanToJsonConverter.java:68)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:229)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:118)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:703)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:631)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:593)
	at core.pages.Header.searchProduct(Header.java:180)
	at test.publicSite.SearchTest.keyWordSearchTest(SearchTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: org.openqa.selenium.WebDriverException: Unable to convert: {actions=[org.openqa.selenium.interactions.Sequence@4fa4f485]}
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:87)
	at org.openqa.selenium.remote.BeanToJsonConverter.convert(BeanToJsonConverter.java:65)
	... 34 more
Caused by: org.openqa.selenium.WebDriverException: Unable to convert: {id=default mouse, type=pointer, parameters={pointerType=mouse}, actions=[{duration=100, x=0, y=0, type=pointerMove, origin=<input class="form-control" maxlength="100" name="q" placeholder="Enter Keyword or Style #" type="text"></input>}]}
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:87)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:203)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:154)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:142)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:85)
	... 35 more
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'hostName', ip: 'IP', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:221)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:142)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:154)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:142)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:85)
	... 39 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.remote.BeanToJsonConverter.mapObject(BeanToJsonConverter.java:261)
	at org.openqa.selenium.remote.BeanToJsonConverter.convertObject(BeanToJsonConverter.java:219)
	... 43 more
Caused by: java.lang.IllegalArgumentException: Method isImage() is only applicable for img elements
	at com.codeborne.selenide.commands.IsImage.execute(IsImage.java:15)
	at com.codeborne.selenide.commands.IsImage.execute(IsImage.java:10)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:140)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:86)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:62)
	at com.sun.proxy.$Proxy15.isImage(Unknown Source)
	... 49 more`

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by AlexanderPoleschuk** [comment]
@AutomatedTester Or even fix it for you, yeah man?)

I've created a light-weight project that might be used to reproduce the issue.
https://github.com/AlexanderPoleschuk/Selenium
Please use Firefox 53.0(32-bit) to reproduce. I use IDEA as IDE.

**Comment by asolntsev** [comment]
@AlexanderPoleschuk You need to add `.toWebElement()`:

```java
actions().moveToElement($(".gsfi").toWebElement()).perform();
```

The point is that `$(".gsfi")` is not a "real" `WebElement`, but a proxy object (created by Selenide).
If you call "usual" methods on this proxy objects, everything works.

But actions builder doesn't call "usual" methods, but uses black magic (which fails with the proxy object).

Namely, actions builder calls `BeanToJsonConverter` which uses reflection and iterates all _properties_ of given java bean (which WebDriver actually is *not* supposed to be) to save them in JSON format. It iterates all methods starting with `get` or `is`, finds method `isImage()`, calls it and gets `IllegalArgumentException: Method isImage() is only applicable for img elements.`

The only question is: why the hell does somebody need to convert `WebElement` to json?
