### ISSUE TITLE
Selenium3.4.0-Java-ChromeDriver v2.29 : org.openqa.selenium.WebDriverException observed when browser.manage().window().fullscreen() is used

### ISSUE THREAD

**Issue by debanjan-selenium** [SeleniumHQ/selenium#4131]
## Meta -
OS:  Windows 8 Pro, 64 bit OS, x64-based processor

Selenium Version:  Selenium-Server-Standalone-3.4.0

ChromeDriver Version: v0.16.1

Browser:  Google Chrome

Browser Version:  Version 58.0.3029.110 (64-bit)

## Steps to reproduce -
Here is the minimal code block to reproduce the issue:

	package demo;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.chrome.ChromeDriver;
	import org.openqa.selenium.chrome.ChromeOptions;

	public class Q44356271_fullScreen {

		public static void main(String[] args) {

		System.setProperty("webdriver.chrome.driver", "C:\\Utility\\BrowserDrivers\\chromedriver.exe");
		ChromeOptions options = new ChromeOptions();
		options.addArguments("start-maximized");
		options.addArguments("disable-infobars");
		WebDriver browser = new ChromeDriver(options);
		browser.get("http://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?classic#form-fieldtypes");
		browser.manage().window().fullscreen();
		}

	}

Here is the error stack trace from the console:

	Jun 06, 2017 4:33:36 PM org.openqa.selenium.remote.ProtocolHandshake createSession
	INFO: Detected dialect: OSS
	Exception in thread "main" org.openqa.selenium.WebDriverException: unimplemented command: session/72e928485961047f2410258fcf900451/window/fullscreen
	Command duration or timeout: 18 milliseconds
	Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
	System info: host: 'ATECHM-03', ip: '192.168.0.105', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_77'
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\ATECHM~1\AppData\Local\Temp\scoped_dir5508_32454}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.110, platform=WIN8, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
	Session ID: 72e928485961047f2410258fcf900451
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
		at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
		at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.fullscreen(RemoteWebDriver.java:929)
		at demo.Q44356271_fullScreen.main(Q44356271_fullScreen.java:14)

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
