### ISSUE TITLE
IEDriver does not support fullscreen command

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4133]
## Meta -
OS:  Windows 8 Pro, 64 bit OS, x64-based processor

Selenium Version:  Selenium-Server-Standalone-3.4.0

IEDriverServer Version: v3.4.0

Browser:  Internet Explorer

Browser Version:  10.0.9200

## Steps to reproduce -
Here is the minimal code block to reproduce the issue:

	package demo;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.ie.InternetExplorerDriver;

	    public class Q44356271_fullScreen {

	    public static void main(String[] args) {

	            System.setProperty("webdriver.ie.driver", "C:\\Utility\\BrowserDrivers\\IEDriverServer.exe");
	            WebDriver browser = new InternetExplorerDriver();
	            browser.get("http://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?classic#form-fieldtypes");
	            browser.manage().window().fullscreen();

		}

	}

Here is the error stack trace from the console:

	Started InternetExplorerDriver server (64-bit)
	3.4.0.0
	Listening on port 46832
	Only local connections are allowed
	Jun 06, 2017 5:44:23 PM org.openqa.selenium.remote.ProtocolHandshake createSession
	INFO: Detected dialect: OSS
	Exception in thread "main" org.openqa.selenium.WebDriverException: Command not found: POST /session/4b6e7ba7-051c-4830-974e-f884050d77f2/window/fullscreen
	Command duration or timeout: 8 milliseconds
	Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
	System info: host: 'ATECHM-03', ip: '192.168.0.105', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_77'
	Driver info: org.openqa.selenium.ie.InternetExplorerDriver
	Capabilities [{se:ieOptions={browserAttachTimeout=0.0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0, ie.useLegacyFileUploadDialogHandling=false, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:46832/, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true}, browserName=internet explorer, pageLoadStrategy=normal, javascriptEnabled=true, version=10, platform=WINDOWS, unexpectedAlertBehaviour=dismiss}]
	Session ID: 4b6e7ba7-051c-4830-974e-f884050d77f2
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
		at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
		at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.fullscreen(RemoteWebDriver.java:929)
		at demo.Q44356271_fullScreen.main(Q44356271_fullScreen.java:12)

**Comment by p0deje** [comment]
Apparently IEDriver doesn't support [fullscreen command](https://w3c.github.io/webdriver/webdriver-spec.html#fullscreen-window) yet.

**Comment by lmtierney** [comment]
Fullscreen is a w3c command. This was implemented in IEServerDriver starting with version `3.5.1.1` https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG#L24
