### ISSUE TITLE
Unable to launch firefox53 and selenium 3.4 with AppiumDriver

### ISSUE THREAD

**Issue by anukriti-chawla** [SeleniumHQ/selenium#4134]
Windows 10( Want to launch firefox on windows using appium driver)
Selenium 3.4
Firefox 53
gecko 0.16
java client 4.2
```java
               AppiumDriver driver = null;
               DesiredCapabilities cap = DesiredCapabilities.firefox();
		FirefoxProfile prof = new FirefoxProfile();
		cap.setCapability(FirefoxDriver.PROFILE, prof);
		DesiredCapabilities required = new DesiredCapabilities();
		System.setProperty("webdriver.gecko.driver", "D:\\geckodriver.exe");
		cap.setBrowserName("firefox");
		URL sURL= null;
		cap.setCapability("firefox_binary",  "C:\\Program Files\\Mozilla Firefox\\firefox.exe");   
		sURL = new URL("http://localhost:5555/wd/hub"); 
		driver =  new AndroidDriver(sURL, cap);
```

Its throwing error and not launching firefox. The exception is :
```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'INNOSZPC00536', ip: '192.168.99.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_25'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x48916f - <no info>
   1:           0x489f59 - <no info>
   2:           0x43c175 - <no info>
   3:           0x443eba - <no info>
   4:           0x41dbb1 - <no info>
   5:           0x407997 - <no info>
   6:           0x6bbb39 - <no info>
   7:           0x415b39 - <no info>
   8:           0x6b6043 - <no info>
   9:     0x7ffa46d78102 - BaseThreadInitThunk
Command duration or timeout: 828 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse$$Lambda$68/33282348.apply(Unknown Source)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.JsonWireProtocolResponse$$Lambda$70/4730422.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$77/20601846.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:69)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:92)
```

**Comment by AutomatedTester** [comment]
My suspicion is that the mixing of AndroidDriver and FirefoxDriver is the cause of this. Please retry with FirefoxDriver instead.

**Comment by anukriti-chawla** [comment]
@AutomatedTester The requirement is to use AppiumDriver to launch firefox.

**Comment by AutomatedTester** [comment]
Since your requirement is for AppiumDriver and we dont support it I suggest asking them. Realistically you should probably be using a builder pattern to pick a driver as you need.
