### ISSUE TITLE
Browser not displayed when remote node is invoked locally using power shell

### ISSUE THREAD

**Issue by DeepakTiwari13** [SeleniumHQ/selenium#4140]
## Meta -
OS:  Windows 7 64 bit
Selenium Version: selenium-server-standalone: 3.0.0
Hub and node version: selenium-server-standalone-2.41.0.jar
Browser:  
Node :- Chrome 59 remote single node
Node :- IE 9 remote single node

Powershell version :- Major 3 Minor 0 Build -1 Revision -1

**Steps to reproduce :-**

1. Run hub on local machine.
Command:
java -jar selenium-server-standalone-2.41.0.jar -port 4444 -role hub
2. Run Chrome node remotely using power shell.
In your local machine ,Go to start, Type powershell,Run "Windows Power Shell" command prompt and Run as an administrator.
Execute following commands:
Enable-PSRemoting -Force
Test-WsMan machinename 
Invoke-Command -ComputerName machinename -ScriptBlock { Get-ChildItem E:\} -credential USERNAME
Invoke-Command -ComputerName machinename -ScriptBlock { E:\"Selenium Grid 2"\Chromenode.bat} -credential USERNAME
OR
Invoke-Command -ComputerName machinename -ScriptBlock { E:\"Selenium Grid 2"\IE9node.bat} -credential USERNAME

---------------------------------------------------------------------------------------------------------------
Here Chromenode.bat file contains following command 
java -Dwebdriver.chrome.driver="E:\Selenium Grid 2\chromedriver.exe" -jar "E:\Selenium Grid 2\selenium-server-standalone-2.41.0.jar" -port 5229 -role node -hub http://IP:4444/grid/register -browser browserName=chrome,maxInstances=3 -maxSession 1

Here IE9.bat file contains following command 

java -Dwebdriver.ie.driver="E:\Selenium Grid 2\IEDriverServer.exe" -jar "E:\Selenium Grid 2\selenium-server-standalone-2.41.0.jar" -port 5559 -role node -hub http://IP:4444/grid/register -browser browserName=iexplore,version=9,maxInstances=3 -maxSession 1
---------------------------------------------------------------------------------------------------------------
3. If you face below error 
Error occurred during initialization of VM Could not reserve enough space for object heap
Then fire this command at remote machine's power shell command prompt [Run as admin]
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="1000"}'

4. Wait for node to register.
5. Launch test on Chrome node using testng.xml file.

**Actual Result :-** [ Chrome Browser ]
1: Browser not displayed at remote end.
2. It says RemoteWebDriver instances should connect to: http://127.0.0.1:5229/wd/hub. But it should be hub IP, which is not a loop back IP.
3. Received following exception.

PS C:\Windows\system32> Invoke-Command -ComputerName idtp340 -ScriptBlock { E:\"Selenium Grid 2"\Chrome59node.bat} -credential sguser

C:\Users\sguser\Documents>java -Dwebdriver.chrome.driver="E:\Selenium Grid 2\chromedriver.exe" -jar "E:\Selenium Grid 2
\selenium-server-standalone-2.41.0.jar" -port 5229 -role node -hub http://172.25.23.63:4444/grid/register -browser brow
serName=chrome,maxInstances=3 -maxSession 1
Jun 07, 2017 4:00:55 PM org.openqa.grid.selenium.GridLauncher main
    + CategoryInfo          : NotSpecified: (Jun 07, 2017 4:...idLauncher main:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : idtp340

INFO: Launching a selenium grid node
Jun 07, 2017 4:00:55 PM org.openqa.grid.common.RegistrationRequest addCapabilityFromString
INFO: Adding browserName=chrome,maxInstances=3
16:00:56.384 INFO - Java: Oracle Corporation 25.121-b13
16:00:56.400 INFO - OS: Windows 7 6.1 amd64
16:00:56.400 INFO - v2.41.0, with Core v2.41.0. Built from revision 3192d8a
================================================================
16:00:56.462 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:5229/wd/hub
================================================================
16:00:56.462 INFO - Version Jetty/5.1.x
16:00:56.462 INFO - Started HttpContext[/selenium-server,/selenium-server]
16:00:56.462 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@1ad282e0
16:00:56.462 INFO - Started HttpContext[/wd,/wd]
16:00:56.462 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
16:00:56.462 INFO - Started HttpContext[/,/]
16:00:56.462 INFO - Started SocketListener on 0.0.0.0:5229
16:00:56.462 INFO - Started org.openqa.jetty.jetty.Server@527740a2
16:00:56.462 INFO - using the json request : {"capabilities":[{"seleniumProtocol":"WebDriver","browserName":"chrome","m
axInstances":"3","platform":"VISTA"}],"configuration":{"role":"node","remoteHost":"http://172.25.23.64:5229","hubHost":
"172.25.23.63","hubPort":4444,"url":"http://172.25.23.64:5229","proxy":"org.openqa.grid.selenium.proxy.DefaultRemotePro
xy","hub":"http://172.25.23.63:4444/grid/register","port":5229,"browser":"browserName=chrome,maxInstances=3","host":"17
2.25.23.64","maxSession":1,"registerCycle":5000,"register":true},"class":"org.openqa.grid.common.RegistrationRequest"}
16:00:56.462 INFO - Starting auto register thread. Will try to register every 5000 ms.
16:00:56.462 INFO - Registering the node to hub :http://172.25.23.63:4444/grid/register
16:01:13.061 INFO - couldn't register this node : Hub is down or not responding: Connection refused: connect
16:01:18.068 INFO - Registering the node to hub :http://172.25.23.63:4444/grid/register
16:02:44.492 INFO - couldn't register this node : Hub is down or not responding: Connection refused: connect
16:02:49.578 INFO - Registering the node to hub :http://172.25.23.63:4444/grid/register
16:03:01.013 INFO - Executing: [new session: Capabilities [{chrome.binary=\drivers\chromedriver.exe, browserName=chrome
, javascriptEnabled=true, version=, platform=WINDOWS}]] at URL: /session)
16:03:01.013 INFO - Creating a new session for Capabilities [{chrome.binary=\drivers\chromedriver.exe, browserName=chro
me, javascriptEnabled=true, version=, platform=WINDOWS}]
Starting ChromeDriver 2.29.461591 (62ebf098771772160f391d75e589dc567915b233) on port 5089
Only local connections are allowed.
16:04:03.376 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException:
java.lang.reflect.InvocationTargetException
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: 'IDTP340', ip: '172.25.23.64', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1',
java.version: '1.8.0_121'
Driver info: driver.version: unknown
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:177)
    at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:113)
    at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:90)
    at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:96)
    at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:63)
    at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:202)
    at org.openqa.selenium.remote.server.JsonHttpRemoteConfig.handleRequest(JsonHttpRemoteConfig.java:193)
    at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:174)
    at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:140)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:112)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
    at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
    at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
    at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
    at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
    at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
    at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
    at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
    at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
    at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: 'IDTP340', ip: '172.25.23.64', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1',
java.version: '1.8.0_121'
Driver info: driver.version: unknown
    at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:72)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:56)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:216)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:170)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:62)
    ... 8 more
Caused by: org.openqa.selenium.WebDriverException: unknown error: un
able to discover open pages
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1
x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 61.27 seconds
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: 'IDTP340', ip: '172.25.23.64', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1',
java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.chrome.ChromeDriver.startSession(ChromeDriver.java:181)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:160)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:128)
    ... 13 more
16:04:03.392 WARN - Exception: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1
x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 61.27 seconds
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: 'IDTP340', ip: '172.25.23.64', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1',
java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver

--------------------------------------------------------------------------------------------------------------

**Actual Result :-** [ IE9 Browser ]
1. Browser not displayed at node machine.
2. Browser runs in headless mode.
3. Console shows logs.
4. Execution hangs.

**Comment by barancev** [comment]
16:04:03.392 WARN - Exception: unknown error: unable to discover open pages
(Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1
x86_64) (WARNING: The server did not provide any stacktrace information)

This is an error thrown by chromedriver. Please retest with the latest chromedriver version. If the issue persists report it to chromedriver tracker: https://sites.google.com/a/chromium.org/chromedriver/help
