### ISSUE TITLE
WebDriverException: Message: connection refused

### ISSUE THREAD

**Issue by chrisspen** [SeleniumHQ/selenium#4144]
I'm unable to use Selenium to control Firefox using Geckodriver.

## Platform and application details
* Platform: Ubuntu 16.04
* Firefox: 52.1.0
* Selenium: 3.4.3
* Geckodriver: 0.16.1

My code:

    from selenium import webdriver
    driver = webdriver.Firefox(capabilities={'marionette': True})

which throws the exception:

    Traceback (most recent call last):
      File "/usr/local/myproject/tests.py", line 393, in setUp
        driver = webdriver.Firefox(capabilities={'marionette': True})
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
        keep_alive=True)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
        self.start_session(desired_capabilities, browser_profile)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
        response = self.execute(Command.NEW_SESSION, parameters)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
        self.error_handler.check_response(response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
        raise exception_class(message, screen, stacktrace)
    WebDriverException: Message: connection refused

The contents of my geckodriver.log are:

    1496858900767	geckodriver	INFO	Listening on 127.0.0.1:51811
    1496858900821	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox with args ["-marionette"]
    ExceptionHandler::GenerateDump cloned child 26504
    ExceptionHandler::SendContinueSignalToChild sent continue signal to child
    ExceptionHandler::WaitForContinueSignal waiting for continue signal...

**Comment by barancev** [comment]
Is this issue still actual in geckodriver 0.18 and firefox 55?

**Comment by barancev** [comment]
Let's suppose it's fixed, geckodriver evolved drastically since 0.16
