### ISSUE TITLE
WebDriverException, Status code was: -6

### ISSUE THREAD

**Issue by piotrros** [SeleniumHQ/selenium#4155]
## Meta -
OS:  
macOS Sierra 
10.12.4

Selenium Version:  
3.4.0

Browser:  
Chrome 

-->

Browser Version:  
61.0.3124.4 64-bit

## Expected Behavior -
Open a chrome browser.

## Actual Behavior -
App crashes with:

```
Traceback (most recent call last):
  File "accountmaker.py", line 37, in <module>
    driver = webdriver.Chrome(executable_path=CHROMEDRIVER_DIR + 'chromedriver') #,chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /Users/makalele/Documents/rozne/chromedriver unexpectedly exited. Status code was: -6
```

## Steps to reproduce -
```
from selenium import webdriver
CHROMEDRIVER_DIR = '/Users/makalele/Documents/rozne/'
sys.path.append(CHROMEDRIVER_DIR)
driver = webdriver.Chrome(executable_path=CHROMEDRIVER_DIR + 'chromedriver')
```

path is right for 100%, I've also added it to $PATH.

Where can I find what status codes mean and where's the problem?

**Comment by piotrros** [comment]
Looks like I've resolved the problem.
I forgot to mention I've builded chromedriver from source. I've copied chromedriver binary to other directory and pointed that directory from code (also in PATH). When I used the orginal directory (a lot more files with chromedriver inside) it worked.
