### ISSUE TITLE
NPE in standalone-chrome when setting `implicitlyWait`

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#4221]
Moving an issue created by @phtrivier in the docker-selenium repo on [Jun 15 2017 17:48 GMT+2](https://github.com/SeleniumHQ/docker-selenium/issues/500)

## Meta -
Image(s):  
* standalone-node
Docker-Selenium Image Version(s):  
* 3.4.0
OS: 
* ubuntu 17.04 

## Expected Behavior -

* Start the image locally 

```
docker run -d -p 4444:4444 selenium/standalone-chrome:3.4.0-dysprosium
```

* Set env variable to test npm `selenium` package to use the image

```
export SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub
```

* Run a very basic script that just creates a driver

```
var webdriver = require('selenium-webdriver');
var chromeCapabilities = webdriver.Capabilities.chrome();
var driver = new webdriver.Builder().withCapabilities(chromeCapabilities).build();
driver.manage().timeouts().implicitlyWait(2000);
```

* The last line (setting `implicitlyWait`) triggers an NPE in the image: 

```
15:42:05.668 WARN - Exception thrown
java.lang.NullPointerException
	at org.openqa.selenium.remote.server.handler.ConfigureTimeout.setJsonParameters(ConfigureTimeout.java:39)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:99)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:190)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
```

## Actual Behavior -

It does not seem like the error prevents the test from working, but it pollutes log, and I suspect it means I'm doing something wrong. 

=======
Additional debug info from @diemol

At the beginning I thought it was related to the [deprecation](https://github.com/SeleniumHQ/selenium/blob/selenium-3.4.0/javascript/node/selenium-webdriver/lib/webdriver.js#L1576) of `driver.manage().timeouts().implicitlyWait(2000);`, but the same behaviour is seen by using `driver.manage().setTimeouts({implicit: 2000});`. 

This happens when I used the `selenium/standalone-chrome:3.4.0-dysprosium` and also when I start a Selenium standalone with `java -jar selenium-server-standalone-3.4.0.jar -role standalone`.

The JS code I used to reproduce this issue was:

```
var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;
var chromeCapabilities = webdriver.Capabilities.chrome();
var driver = new webdriver.Builder().withCapabilities(chromeCapabilities).build();
driver.manage().setTimeouts({implicit: 2000});
driver.get('http://www.google.com/ncr');
driver.findElement(By.name('q')).sendKeys('webdriver');
driver.findElement(By.name('btnG')).click();
driver.wait(until.titleIs('webdriver - Google Search'), 1000);
driver.quit();
```

Dependencies:
```
  "dependencies": {
    "selenium-webdriver": "^3.4.0"
  }
```

And I executed the code with this command:

```
SELENIUM_REMOTE_URL="http://localhost:4444/wd/hub" node simple-test.js
```

**Comment by krmahadevan** [comment]
Here's my analysis : 

The sample that @diemol shared, when hitting the end-point `/session/<SessionIdGoesHere>/timeouts` generates the below payload as part of the POST request

```json
{
	"implicit": 2000
}
```

I then ran a Java variant of the same NodeJS sample which looks like below:

```java
public static void main(String[] args) throws Exception {
    RemoteWebDriver driver = null;
    try {
        URL url = new URL("http://localhost:4444/wd/hub");
        DesiredCapabilities caps = DesiredCapabilities.chrome();
        driver = new RemoteWebDriver(url, caps);
        driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    } finally {
        if (driver != null) {
            driver.quit();
        }
    }
}
```

I noticed that the payload which reaches the end-point `/session/<SessionIdGoesHere>/timeouts` looks like below : 

```json
{
	"type": "implicit",
	"ms": 2000
}
``` 
I am guessing that perhaps the NodeJS client bindings is already constructing payloads adhering to the [W3C spec standards](https://w3c.github.io/webdriver/webdriver-spec.html#set-timeouts) whereas neither the Selenium server nor the Java client bindings are there yet.

I have attempted at fixing this as part of the Pull Request : https://github.com/SeleniumHQ/selenium/pull/4315

Hopefully it will get merged.
