### ISSUE TITLE
Node.js WebDriverError: Failed to unzip profile

### ISSUE THREAD

**Issue by technomark** [SeleniumHQ/selenium#4225]
## Meta -
OS:
Windows 8.1
Selenium Version:  
Node selenium-webdriver v7.10.0
Browser:  
geckodriver.exe
Browser Version:  
v0.17.0

## Expected Behavior -
Following instructions here: http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/index.html

With this code:

`let profile = new firefox.Profile('/usr/local/home/bob/.mozilla/firefox/3fgog75h.testing');`
`let options = new firefox.Options().setProfile(profile);`
`let driver = new webdriver.Builder().forBrowser('firefox').setFirefoxOptions(options).build();`

I expect geckodriver to start using "bob's" profile

## Actual Behavior -

Console output:

> C:\dev\fftut>node google_test.js
C:\dev\node_modules\selenium-webdriver\lib\promise.js:2634
        throw error;
        ^
 WebDriverError: Failed to unzip profile
    at Object.throwDecodedError (C:\dev\node_modules\selenium-webdriver\lib\error.js:489:11)
    at parseHttpResponse (C:\dev\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response (C:\dev\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\dev\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (C:\dev\node_modules\selenium-webdriver\firefox\index.js:667:55)
    at createDriver (C:\dev\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (C:\dev\node_modules\selenium-webdriver\index.js:642:16)
    at Object.<anonymous> (C:\dev\fftut\google_test.js:15:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

## Steps to reproduce -
Use code above (with imports) with Node.js and set your existing profile directory path in the code. Execute code from a terminal and view the console output.

**Comment by jleyba** [comment]
I'm unable to reproduce this with various profiles/extensions, so this is probably something specific to the profile you are trying to use.

**Comment by barancev** [comment]
Closing due to inactivity
