### ISSUE TITLE
Failed to run on firefox

### ISSUE THREAD

**Issue by loginXin** [SeleniumHQ/selenium#4235]
## Meta -
OS:  windows 7 64bit

Selenium Version:  3.4.0(javascript)

Browser:  Firefox

Browser Version:  54.0(32-bit)

## Expected Behavior -
The browser firefox opens, loads URL and search the keywords as expected,

## Actual Behavior -
Browser firefox opens, loads the url above, but failed to send keys
## Steps to reproduce -

run the file below:
`var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .withCapabilities(webdriver.Capabilities.firefox())
    .build();

driver.get('https://www.baidu.com');
driver.findElement(By.id('kw')).sendKeys('webdriver');
driver.findElement(By.id('su')).click();
driver.wait(until.titleIs('webdriver_百度搜索'), 1000);
driver.quit();`

log:
`G:\selenium\node_modules>node baidu_search.js
G:\selenium\node_modules\selenium-webdriver\lib\promise.js:2634
        throw error;
        ^

InvalidArgumentError: Could not convert 'text' to string
    at Object.throwDecodedError (G:\selenium\node_modules\selenium-webdriver\lib
\error.js:489:11)
    at parseHttpResponse (G:\selenium\node_modules\selenium-webdriver\lib\http.j
s:519:13)
    at doSend.then.response (G:\selenium\node_modules\selenium-webdriver\lib\htt
p.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
From: Task: WebElement.sendKeys()
    at thenableWebDriverProxy.schedule (G:\selenium\node_modules\selenium-webdri
ver\lib\webdriver.js:816:17)
    at WebElementPromise.schedule_ (G:\selenium\node_modules\selenium-webdriver\
lib\webdriver.js:2024:25)
    at WebElementPromise.sendKeys (G:\selenium\node_modules\selenium-webdriver\l
ib\webdriver.js:2187:19)
    at Object.<anonymous> (G:\selenium\node_modules\baidu_search.js:49:33)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
`

**Comment by loginXin** [comment]
geckodriver:v0.17.0(32-bit)

**Comment by p0deje** [comment]
This is fixed in 6907a12, will be in the next release of javascript bindings
