### ISSUE TITLE
selenium-webdriver not running in digitalocean droplet(headless, disable-gpu options are added)

### ISSUE THREAD

**Issue by thebluewhale** [SeleniumHQ/selenium#4248]
## Meta -
OS:  Ubuntu 16.04

Selenium Version:  node selenium-webdriver 3.4.0

Browser: chrome

Browser Version:  node chromedriver 2.30.1

## Expected Behavior -
headless browser start.

## Actual Behavior -
headless, disable-gpu option is added, but browser didn't run with error

I'm now trying to run node app.
My app running with selenium webdriver(chrome).
I made droplet (ubuntu 16.04, nodejs 6.11, 512M RAM, 20G HDD).
but when I start the app, an error occured and selenium not run.
error log is like below.

Error: Server terminated early with status 127
at Error (native)
at earlyTermination.catch.e (/home/master/Project/react-jobscrapper/nodemodules/selenium-webdriver/remote/index.js:252:52)
at process.tickDomainCallback (internal/process/nexttick.js:135:7)
From: Task: WebDriver.createSession()
at Function.createSession (/home/master/Project/react-jobscrapper/nodemodules/selenium-webdriver/lib/webdriver.js:777:24)
at Function.createSession (/home/master/Project/react-jobscrapper/nodemodules/selenium-webdriver/chrome.js:719:29)
at createDriver (/home/master/Project/react-jobscrapper/nodemodules/selenium-webdriver/index.js:167:33)
at Builder.build (/home/master/Project/react-jobscrapper/nodemodules/selenium-webdriver/index.js:639:16)
at kakaoCrawler.executeCrawling (/home/master/Project/react-jobscrapper/server/crawler/kakaoCrawler.js:108:11)
at /home/master/Project/react-jobscrapper/server/crawler/kakaoCrawler.js:32:10
at Array.forEach (native)
at /home/master/Project/react-jobscrapper/server/crawler/kakaoCrawler.js:31:15
at process.tickDomainCallback (internal/process/nexttick.js:135:7)
at Function.Module.runMain (module.js:606:11)
at Object.<anonymous> (/home/master/Project/react-jobscrapper/nodemodules/babel-cli/lib/babel-node.js:154:22)
at Module.compile (module.js:570:32)
at Object.Module.extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module.load (module.js:438:3)

I setted selenium headless option('headless', 'disable-gpu') but selenium doesn't run.

**Comment by p0deje** [comment]
There might be various reason for that. One of them could be insufficient amount of RAM.

However, this is a question rather than a Selenium issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
