### ISSUE TITLE
Having java.nio.file.FileSystemException issue while running my code using Selenium 3.4.0 with Maven Project only

### ISSUE THREAD

**Issue by VijenderChhokar** [SeleniumHQ/selenium#4251]
OS:  
Windows 10(64-bit)
Selenium Version:  3.4.0

Browser:  Chrome  
Browser Version:  - Version 59.0.3071.115 (64-bit) and Chrome driver - 2.30

## Issue -  
While running the below code, I am getting the below error. This code is working fine with Selenium 2.53.1 Browser details: Chrome - Version 59.0.3071.115 (64-bit) Chrome driver - 2.30

Below code works perfectly with normal Java project. Facing issue with Maven Project only.

## Code 
package rough;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class TestSel {

	public static void main(String[] args) {
		System.setProperty("WebDriver.chrome.driver", "D:\\chrome\\chromedriver.exe");
		WebDriver driver=new ChromeDriver();
		
		driver.get("https://gmail.com");
		driver.manage().window().maximize();
		System.out.println("Testing Complete");

	}

}

## Error logs

Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 45031
Only local connections are allowed.
Jul 03, 2017 2:22:32 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.WebDriverException: java.nio.file.FileSystemException: C:\Users\vijender\AppData\Local\Temp\new-session7102896761568860479.json: The process cannot access the file because it is being used by another process.

Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'LC-VIJENDERC', ip: '192.168.6.83', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_92'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:91)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:184)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:124)
	at rough.TestSel.main(TestSel.java:10)
Caused by: java.nio.file.FileSystemException: C:\Users\vijender\AppData\Local\Temp\new-session7102896761568860479.json: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:168)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	... 8 more

## Steps to reproduce -
1. Create a Maven Project.
2. Copy the given code and run.

**Comment by p0deje** [comment]
I can't reproduce using https://github.com/p0deje/se-java-example Maven project:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.example.se.AppTest
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 36667
Only local connections are allowed.
Jul 03, 2017 4:19:05 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Testing Complete
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.71 sec
```

Is there anything else I miss?

**Comment by VijenderChhokar** [comment]
Have you tried to run the above code using Maven project?

**Comment by p0deje** [comment]
I ran it using `mvn test`.

**Comment by VijenderChhokar** [comment]
Can you please try the below steps once again:
1. Create a maven project.
2. Copy above code.
3. Add below dependency in pom.xml
   <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>3.4.0</version>
</dependency>

4. Now right click on project(which is just created) and click on Run as Java application.

**Comment by VijenderChhokar** [comment]
The issue was my system specific. Resolved by window reset.
