### ISSUE TITLE
Coded UI selenium components/chrome driver not working for chrome version>53

### ISSUE THREAD

**Issue by prateekchawla** [SeleniumHQ/selenium#4259]
I have been trying all the combinations for Chrome Driver(latest 2.30) and Chrome browser latest version. There has been no success for Chrome working for versions >53.
Is there any work around for getting coded ui to work on chrome browser which has version >53.

chrome=58.0.3029.81
chromedriver=2.30
Selenium dot net bindings - 3.4.0

**Comment by zac11** [comment]
Please add the error logs and the code that you've used.

**Comment by luke-hill** [comment]
Whilst I'm not a maintainer, the version of chromedriver you are using according to your post is over 2 years old. Yet the one you mention at the top says `2.30` which is the latest.

I'd clear up first of all "which" version of chromedriver you are using.

2.30 is the latest. 2.29 is the next latest (Not 2.9, yes I know it appears at the bottom))

**Comment by prateekchawla** [comment]
I am using 
Chrome Driver - 2.30.477700
Please disregard the above mentioned. I will edit that

**Comment by prateekchawla** [comment]
@zac11 
Code - 
 BrowserWindow.CurrentBrowser = "Chrome";
 BrowserWindow bw = BrowserWindow.Launch(new Uri("myurl"));

Exception - 
An exception of type 'System.ArgumentNullException' occurred in Microsoft.VisualStudio.TestTools.UITesting.dll but was not handled in user code

Additional information: Value cannot be null.

**Comment by zac11** [comment]
This looks like half or portion of your code. This exception occurs when null is passed to a method that doesn't accept null as the parameter. Can you please post your full code. Also what is "myurl", and where is it defined.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by prateekchawla** [comment]
I am using the same code which works well on chrome version < 53 using Coded UI cross browser selenium components. 
Using chrome driver version - 2.28.
There has been an issue with > 53 chrome browser version. 
Hence I would like to know if there is any update or workaround for this issue.

**Comment by p0deje** [comment]
In order to fix issue, we need to reproduce it, so please provide a code that I could run locally to see the issue.

**Comment by jameslem** [comment]
```
package scrapingdp;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class Fristscrape {

	WebDriver wd;
	
	public void invokeBrowser() {
		
		try {
			System.setProperty("webdriver.chrome.driver", "C:\\Users\\r-r\\Downloads\\EclipseSelenium\\chromedriver_win32\\chromedriver.exe");
			
		    ChromeOptions options = new ChromeOptions();
		    options.addArguments("test-type");
		    
			wd = new ChromeDriver(options);
			wd.manage().deleteAllCookies();
			wd.manage().window().maximize();
			wd.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
			wd.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);
			
			wd.get("https://www.google.com.ph/");
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Fristscrape fs = new Fristscrape();
		fs.invokeBrowser();

	}

}

```
Can you check this instance?

- selenium-server-3.4.0.zip
- selenium-server-standalone-3.4.0.jar
- chrome=59.0.3071.115
- chromedriver=2.9.248315
- platform=Windows NT 6.3 x86_64

Here's the Error. This will launch chrome containing **data:,** in the url, and a extension Disable popup.

```
Starting ChromeDriver (v2.9.248315) on port 2571
Jul 20, 2017 4:04:51 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
org.openqa.selenium.WebDriverException: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"7000.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 76 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'JAMES', ip: '192.168.254.9', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, chrome={userDataDir=C:\Users\r-r\AppData\Local\Temp\scoped_dir9792_29387}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=59.0.3071.115, platform=WIN8_1, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 29993e70e35e624dbd1b0c9d661174c9
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:364)
	at scrapingdp.Fristscrape.invokeBrowser(Fristscrape.java:23)
	at scrapingdp.Fristscrape.main(Fristscrape.java:35)

```

**Comment by p0deje** [comment]
Sorry for getting back that late - I was on vacation with limited access to the internet.

@jameslem The example you provided works fine on my machine. I however, see that you use ChromeDriver 2.9 which is extremely old version. Can you try with 2.30? Also, how is this relevant for this issue?

@prateekchawla Is the issue resolved for you? If not, can you please provide us a test script to reproduce?

**Comment by barancev** [comment]
Closing due to inactivity.
