### ISSUE TITLE
Multiple IE browser open when I run the selenium script and the error is as below,

### ISSUE THREAD

**Issue by shardulSalunke** [SeleniumHQ/selenium#4267]
## Meta -
OS:  Windows 7

Selenium Version:  3.0.1

Browser:  IE 11

Browser Version: IE 11.1358.14393.0  

## Actual Behavior - Multiple browser opens up.

Error is 
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{ignoreProtectedModeSettings=true}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1'

Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:227)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:180)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:172)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:148)
	at com.qpid.automation.util.DriverFactory.createNewDriverInstance(DriverFactory.java:65)
	at com.qpid.automation.util.DriverFactory.initialize(DriverFactory.java:34)
	at com.qpid.automation.util.DriverFactory.<init>(DriverFactory.java:29)
	at com.qpid.automation.feature.hooks.setUp(hooks.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	at com.qpid.automation.feature.RunCukeTest.feature(RunCukeTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)

**Comment by shardulSalunke** [comment]
I have added the IEDriverServer.exe in drivers 
and defined the DriverFactory.java,

System.setProperty("webdriver.ie.driver",
					System.getProperty("user.dir") + "//drivers//IEDriverServer.exe");
			DesiredCapabilities capability = new DesiredCapabilities();
			capability.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);			
			driver = new InternetExplorerDriver(capability);
			ie = driver;

**Comment by aamonto** [comment]
I have the same issue (IE is opening 2 different windows) while running my script using JUnit (this was working last Wednesday 7/5), I am getting the following error message:

_Only local connections are allowed
Jul 07, 2017 4:40:39 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Jul 07, 2017 4:40:40 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection
Jul 07, 2017 4:40:40 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol._

I am using the below code to set IE browser:

_DesiredCapabilities caps = DesiredCapabilities.internetExplorer();
caps.setCapability("nativeEvents",false);
System.setProperty("webdriver.ie.driver",<<path of IE driver in my local machine>>);
driver = new InternetExplorerDriver(caps);_

Thank you for your support.

**Comment by p0deje** [comment]
Please upgrade to Selenium 3.4.0 and try again.

**Comment by aamonto** [comment]
Hello Alex,

Sorry, I am new using Selenium and I am not sure what I need to update in order to use Selenium 3.4.0, what I have done is to update mi IE driver to the 3.4.0 version, is this enough? or do I need to download/update something else?

Thank you for your support.


Best Regards,
Andres Montoya.


-------- Original message --------

**Comment by p0deje** [comment]
You also need to update Java package to 3.4.0 using Maven.

**Comment by aamonto** [comment]
Thank you, my issue got corrected by updating the IE driver (3.4.0) and the Stand Alone Server (3.4.0), thank you for your support

**Comment by p0deje** [comment]
Glad it worked out!
