### ISSUE TITLE
Click on a link -> Opens a New Window -> Switch to New Window is Not Working - IE11 - IEDriverServer.exe (64 bit) - Selenium 3.4

### ISSUE THREAD

**Issue by newton143** [SeleniumHQ/selenium#4298]
## Meta -
OS:  
Windows 7 
Selenium Version:  
WebDriver 3.4.0.0
Browser:  
Internet Explorer 11.0.9600.18697IS
Language: C#

##Description
Click on a link, opens a new window, Unable to switch to new window. - webdriver timeout exception

       var options = new InternetExplorerOptions();
            options.BrowserAttachTimeout = new TimeSpan(00, 00, 120);
            options.IntroduceInstabilityByIgnoringProtectedModeSettings = true;
            options.EnsureCleanSession = true;
            options.RequireWindowFocus = true;
            IWebDriver driver = new InternetExplorerDriver(options);
            driver.Manage().Timeouts().PageLoad = new TimeSpan(00, 00, 60);
            driver.Navigate().GoToUrl("http://qa01.csod.com");
            string window1 = driver.CurrentWindowHandle;
             //Click on WebElement
           var webelement = driver.FindElement(By.XPath("//a[@title='Imports and Feeds']"));
           driver.ExecuteJavaScript("arguments[0].click();", webelement);
           WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(60));
            wait.Until(wnd => wnd.WindowHandles.Count == (previousWinCount + 1));
            string window2 = "";
            var windowHandles = driver.WindowHandles;
            foreach (string handle in windowHandles)
            {
                if (handle != window1)
                {
                    window2 = handle;
                    break;
                }
            }
            driver.SwitchTo().Window(window2);    //This line throws timeout exception

##Exception Details
{"The HTTP request to the remote WebDriver server for URL http://localhost:45255/session/b5fc19b8-510c-4b9d-bbc7-7d97c3624c60/window timed out after 60 seconds."}

##StackTrace:
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTargetLocator.Window(String windowHandleOrName)
   at FireFoxDriver.Program.Main(String[] args) in C:\Temp\FireFoxDriver\FireFoxDriver\Program.cs:line 69
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

##InnerException:
{"The operation has timed out"}

##Note:
However if i open a new window using a javascript, 
driver.ExecuteJavaScript(string.Format("window.open('{0}','xyz');", @"http://google.com"));
I'm able to switch to new window smoothly.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

Also set IntroduceInstabilityByIgnoringProtectedModeSettings to false, we don't fix the issues that occurs in "unstable mode" only.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/), the site http://qa01.csod.com/ is not available, it must be an internal address.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing due to inactivity
