### ISSUE TITLE
Unable to launch Mozilla Firefox 33

### ISSUE THREAD

**Issue by SuhaThevar90** [SeleniumHQ/selenium#430]
Tried Launching Mozilla Firefox 33 with selenim version 2.44 with language java and Windows 7 OS
But getting the below error 

Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.selenium.logging.LocalLogs.getNullLogger()Lorg/openqa/selenium/logging/LocalLogs;
Tried Using with Firefox profile and without profile 
All the time i end up getting the same error

Have searched for the root cause behind it every where but could not find any solution

Kindly please let me know the root cause when this error appears.
I am stuck with this issue since a long time

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the selenium [user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by SuhaThevar90** [comment]
Hi this is not a question
This is an issue which i am facing while executing my testcase

PFB the below error
Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.selenium.logging.LocalLogs.getNullLogger()Lorg/openqa/selenium/logging/LocalLogs;
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.<init>(FirefoxDriver.java:332)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.<init>(FirefoxDriver.java:334)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
	at test.TestFireFox.main(TestFireFox.java:31)



The code used for execution is 
                ProfilesIni profile = new ProfilesIni();
		 FirefoxProfile ffprofile = profile.getProfile("Selenium");
		 RemoteWebDriver driver = new FirefoxDriver(new FirefoxBinary(new File("C:\\Users\\Su\\AppData\\Local\\Mozilla Firefox\\firefox.exe")), ffprofile);
driver.get("http://scanr-test3.test.att.com/workflow-builder");

I have checked the profiles folder as well.There exists a profile for Selenium as well


Can you please let me know the solution for this

**Comment by lukeis** [comment]
you have a java classpath issue somewhere. The method does exist and has existed for quite some time:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/logging/LocalLogs.java#L46

please follow up on the Selenium-users mailing list for further help.
