### ISSUE TITLE
WebElement.submit did not mach a known command (Firefox)

### ISSUE THREAD

**Issue by alallier** [SeleniumHQ/selenium#4359]
## Meta -
OS:  Windows 10 Build 15063.483

Selenium Version:  3.5.0 (npm) 3.4.0 (GitHub repo)

Browser:  Firefox

Browser Version:  Firefox 54.0.1

## Expected Behavior -

Form submitting to work.

## Actual Behavior -

Error is thrown stacktrace:

```
Sent Keys Successfully
Submit Form Error:  { UnknownCommandError: POST /session/50fdf01e-92d2-4a55-8e49-4d0805520506/element/c663e911-41a5-4271-847a-3150d56c2957/submit did not match a known command
    at Object.throwDecodedError (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\error.js:497:15)
    at parseHttpResponse (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\http.js:524:13)
    at doSend.then.response (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\http.js:444:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
From: Task: WebElement.submit()
    at thenableWebDriverProxy.schedule (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at WebElementPromise.schedule_ (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\webdriver.js:2015:25)
    at WebElementPromise.submit (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\webdriver.js:2342:17)
    at C:\Users\alallier\Documents\blah\test\ui\login-firefox.js:95:19
    at ManagedPromise.invokeCallback_ (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\promise.js:1384:14)
    at TaskQueue.execute_ (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\promise.js:3092:14)
    at TaskQueue.executeNext_ (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\promise.js:3075:27)
    at asyncRun (C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\promise.js:2935:27)
    at C:\Users\alallier\Documents\blah\node_modules\selenium-webdriver\lib\promise.js:676:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  name: 'UnknownCommandError',
  remoteStacktrace: 'stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x43ce8d - <no info>\n   3:           0x4319fd - <no info>\n   4:           0x425ca5 - <no info>\n   5:           0x407eba - <no info>\n   6:           0x6d95b9 - <no info>\n   7:           0x417655 - <no info>\n   8:           0x6d38b3 - <no info>\n   9:     0x7ffac3792774 - BaseThreadInitThunk' }
```

## Steps to reproduce -

Submit a form.

```js
driver.get('http://localhost:43711/login');

userField = driver.findElement(by.id('username'));

userField.sendKeys('Foo')
  .then(function() {
    console.log('Sent Keys Successfully');
    userField.submit()
      .then(function() {
        console.log('Submitted Form Successfully');
      }).catch(function(err) {
        console.error('Submit Form Error: ', err);
      });
  }).catch(function(err) {
    console.error('Send Keys Error: ', err);
  });
```

**Comment by p0deje** [comment]
There is no submit command in [W3C WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html) so it's not implemented.

**Comment by alallier** [comment]
Maybe I'm a bit confused as this is working in Chrome and the docs say you can use it, as long as it is in a form (which it is)

![image](https://user-images.githubusercontent.com/13004518/28618616-05def05c-71d3-11e7-93e4-80985525936a.png)

**Comment by p0deje** [comment]
Yeah, there is a certain inconsistency in OSS vs W3C implementations (ChromeDriver is OSS, GeckoDriver - W3C). This is something Selenium team needs to figure out and I guess we'll discuss this in #4349.
