### ISSUE TITLE
NullPointerException in RemoteWebDriver.findElements for chrome

### ISSUE THREAD

**Issue by andrejserafim** [SeleniumHQ/selenium#4375]
## Meta
OS: Ubuntu
Selenium Version: 3.4.0
Browser: Chrome
Browser Version: docker image for selenium-chrome-debug 3.4.0

## Steps to reproduce

Unable to reproduce reliably, seems like some kind of race condition.

Relevant stack trace

```
Caused by: java.lang.NullPointerException
        at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:446)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:513)
        at org.openqa.selenium.By$ByXPath.findElements(By.java:356)
        at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:398)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:104)
        at com.sun.proxy.$Proxy4.findElements(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.findElements(EventFiringWebDriver.java:177)
        at org.openqa.selenium.remote.server.handler.FindElements.call(FindElements.java:50)
        at org.openqa.selenium.remote.server.handler.FindElements.call(FindElements.java:35)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by andrejserafim** [comment]
@lmtierney I did mention it's a race occurring some % of calls. How do you usually approach crtc for those?

**Comment by barancev** [comment]
Provide a scenario that being run in a loop 1000 or 100000 times allows to reproduce the issue in some % of calls.
