### ISSUE TITLE
Windows 10 + Firefox 46.0.1 + Selenium 2.53.0 : Don't work

### ISSUE THREAD

**Issue by schetibi** [SeleniumHQ/selenium#4390]
**OS:  Windows 10
Selenium Version:  2.53.0
Browser:   Firefox 46.0.1 (x64)**

I am getting error while using Firefox with WebDriver 

**IMPORTANT**
With this configuration, I have no error
**OS:  Windows 7
Selenium Version:  2.53.0
Browser:   Firefox 46.0.1 (x64)**

Error :
```
Browser Path: C:/Users/schetibi/Documents/DEV/firefox-46.0.1.win64.sdk/firefox-sdk/bin/firefox.exe
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"46.0.1","maxVersion":"46.0.1"}],"targetPlatforms":[],"seen":true}
1501491107993	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1501491107995	DeferredSave.extensions.json	DEBUG	Save changes
1501491107995	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1501491107995	addons.xpi-utils	DEBUG	Updating add-on states
1501491107997	addons.xpi-utils	DEBUG	Writing add-ons list
1501491108006	addons.xpi	DEBUG	Registering manifest for C:\Users\schetibi\Documents\DEV\firefox-46.0.1.win64.sdk\firefox-sdk\bin\browser\features\e10srollout@mozilla.org.xpi
1501491108007	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1501491108007	addons.xpi	DEBUG	Registering manifest for C:\Users\schetibi\Documents\DEV\firefox-46.0.1.win64.sdk\firefox-sdk\bin\browser\features\firefox@getpocket.com.xpi
1501491108009	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0
1501491108012	addons.xpi	DEBUG	Registering manifest for C:\Users\schetibi\Documents\DEV\firefox-46.0.1.win64.sdk\firefox-sdk\bin\browser\features\loop@mozilla.org.xpi
1501491108012	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.2.6
1501491108035	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1501491108035	addons.manager	DEBUG	Provider finished startup: XPIProvider
1501491108035	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1501491108035	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1501491108035	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1501491108036	addons.manager	DEBUG	Starting provider: GMPProvider
1501491108046	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1501491108046	addons.manager	DEBUG	Provider finished startup: GMPProvider
1501491108046	addons.manager	DEBUG	Starting provider: PluginProvider
1501491108046	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1501491108046	addons.manager	DEBUG	Provider finished startup: PluginProvider
1501491108047	addons.manager	DEBUG	Completed startup sequence
1501491108678	DeferredSave.extensions.json	DEBUG	Starting write
1501491108684	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1501491108684	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1501491108685	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1501491109256	addons.repository	DEBUG	No addons.json found.
1501491109256	DeferredSave.addons.json	DEBUG	Save changes
1501491109259	DeferredSave.addons.json	DEBUG	Starting timer
1501491109277	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1501491109277	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1501491109277	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1501491109279	DeferredSave.extensions.json	DEBUG	Write succeeded
1501491109280	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1501491109375	DeferredSave.addons.json	DEBUG	Starting write
1501491109408	DeferredSave.addons.json	DEBUG	Write succeeded
JavaScript error: chrome://fxdriver/content/server.js, line 61: uncaught exception: [object Object]
JavaScript error: chrome://fxdriver/content/server.js, line 61: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
console.error: 
  Could not write session state file 
  Message: Win error 32 during operation move on file C:\Windows\TEMP\anonymous8270369280512093371webdriver-profile\sessionstore-backups\recovery.js.tmp (Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

)
  

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at com.jalios.test.functional.configuration.impl.FirefoxFunctionalTestConfiguration.doInitDriver(FirefoxFunctionalTestConfiguration.java:81)
	at com.jalios.test.functional.configuration.AbstractFunctionalTestConfiguration.getDriver(AbstractFunctionalTestConfiguration.java:133)
	at com.jalios.test.functional.util.ActionUtils.goToURL(ActionUtils.java:455)
	at com.jalios.test.functional.util.JcmsActionUtils.login(JcmsActionUtils.java:47)
	at com.jalios.test.functional.FunctionalTestCase.setUpBeforeClass(FunctionalTestCase.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
10:52:34.086 [main] WARN  [com.jalios.test.functional.configuration.impl.FirefoxFunctionalTestConfiguration] Failed to connect to binary FirefoxBinary(C:\Users\schetibi\Documents\DEV\firefox-46.0.1.win64.sdk\firefox-sdk\bin\firefox.exe) on port 7055; process output follows: 
22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"46.0.1","maxVersion":"46.0.1"}],"targetPlatforms":[],"seen":true}
1501491107993	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1501491107995	DeferredSave.extensions.json	DEBUG	Save changes
1501491107995	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1501491107995	addons.xpi-utils	DEBUG	Updating add-on states
1501491107997	addons.xpi-utils	DEBUG	Writing add-ons list
1501491108006	addons.xpi	DEBUG	Registering manifest for C:\Users\schetibi\Documents\DEV\firefox-46.0.1.win64.sdk\firefox-sdk\bin\browser\features\e10srollout@mozilla.org.xpi
1501491108007	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1501491108007	addons.xpi	DEBUG	Registering manifest for C:\Users\schetibi\Documents\DEV\firefox-46.0.1.win64.sdk\firefox-sdk\bin\browser\features\firefox@getpocket.com.xpi
1501491108009	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0
1501491108012	addons.xpi	DEBUG	Registering manifest for C:\Users\schetibi\Documents\DEV\firefox-46.0.1.win64.sdk\firefox-sdk\bin\browser\features\loop@mozilla.org.xpi
1501491108012	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.2.6
1501491108035	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1501491108035	addons.manager	DEBUG	Provider finished startup: XPIProvider
1501491108035	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1501491108035	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1501491108035	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1501491108036	addons.manager	DEBUG	Starting provider: GMPProvider
1501491108046	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1501491108046	addons.manager	DEBUG	Provider finished startup: GMPProvider
1501491108046	addons.manager	DEBUG	Starting provider: PluginProvider
1501491108046	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1501491108046	addons.manager	DEBUG	Provider finished startup: PluginProvider
1501491108047	addons.manager	DEBUG	Completed startup sequence
1501491108678	DeferredSave.extensions.json	DEBUG	Starting write
1501491108684	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1501491108684	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1501491108685	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1501491109256	addons.repository	DEBUG	No addons.json found.
1501491109256	DeferredSave.addons.json	DEBUG	Save changes
1501491109259	DeferredSave.addons.json	DEBUG	Starting timer
1501491109277	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1501491109277	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1501491109277	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1501491109279	DeferredSave.extensions.json	DEBUG	Write succeeded
1501491109280	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1501491109375	DeferredSave.addons.json	DEBUG	Starting write
1501491109408	DeferredSave.addons.json	DEBUG	Write succeeded
JavaScript error: chrome://fxdriver/content/server.js, line 61: uncaught exception: [object Object]
JavaScript error: chrome://fxdriver/content/server.js, line 61: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
console.error: 
  Could not write session state file 
  Message: Win error 32 during operation move on file C:\Windows\TEMP\anonymous8270369280512093371webdriver-profile\sessionstore-backups\recovery.js.tmp (Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

)
  

Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'tolstoi', ip: '172.27.3.236', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
```

Is it related to the OS? What should I do?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by schetibi** [comment]
Thank you for your answer, it is a problem when a test does not start + I have an excepetion. No?
Ok for creating the question in the group

**Comment by barancev** [comment]
It's an exception that occurs in the browser, so it must be a system misconfiguration.

Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
console.error: 
  Could not write session state file
