### ISSUE TITLE
Operadriver on Linux

### ISSUE THREAD

**Issue by simpleC0de** [SeleniumHQ/selenium#4400]
Hey there, my current problem is that im not able to start the OperaDriver from Debian 8.
I installed it and uploaded the driver.

The following stacktrace shows up:

Starting driver...
Starting OperaDriver 2.27 (f61056e560d197467fd6d27c7fbd7fea572fe8bd) on port 2336
Only local connections are allowed.
opera: Unknown argument: --disable-background-networking
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Opera failed to start: exited normally
  (Driver info: OperaDriver=2.27 (f61056e560d197467fd6d27c7fbd7fea572fe8bd),platform=Linux 3.16.0-4-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.15 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'vmd17391.contaboserver.net', ip: '173.212.209.215', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-4-amd64', java.version: '1.8.0_144'
Driver info: driver.version: OperaDriver
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
        at org.openqa.selenium.opera.OperaDriver.<init>(OperaDriver.java:169)
        at org.openqa.selenium.opera.OperaDriver.<init>(OperaDriver.java:137)
        at spidate.main.main.Main.init(Main.java:259)
        at spidate.main.main.Main.main(Main.java:32)

My code for launching:

  public static void init(){

        //DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
       // capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
       // capabilities.setCapability("requireWindowFocus", true);

        //System.setProperty("webdriver.ie.driver", "C:\\Users\\" + System.getProperty("user.name") +"\\Desktop\\driver\\ie.exe");

        System.setProperty("webdriver.opera.driver", "/home/spidate/od");
        //driver = new InternetExplorerDriver();
        System.setProperty("webdriver.chrome.driver", "/home/spidate/od");
        if(driver != null){
            driver.quit();
        }

        Map<String, Object> chromeOptions = new HashMap<String, Object>();
        chromeOptions.put("binary", "/usr/lib/opera/opera");

        DesiredCapabilities capabilities = DesiredCapabilities.opera();
        capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

        capabilities.setCapability("opera.binary" , "/usr/bin/opera");

        capabilities.setCapability("binary" , "/usr/bin/opera");

        System.out.println("Starting driver...");
        driver = new OperaDriver(capabilities);
        System.out.println("Started driver.");

    }

**Comment by barancev** [comment]
Selenium does not send "--disable-background-networking" or any other options to the browser. Please remort this issue to the operadriver tracker: https://github.com/operasoftware/operachromiumdriver/issues
