### ISSUE TITLE
Issue with selenium webdriver

### ISSUE THREAD

**Issue by nvphaneendra** [SeleniumHQ/selenium#441]
Hi all,

I am using Windows 8.1 and IE 11 and firefox 37 versions. 
I am trying to execute my selenium program, I am getting an exceptions. Can anyone resolved my issue

My sample code is
===============

package com.phani.first;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.Test;

public class Consts {

@Test
public static void createBasicAccount()
{
WebDriver driver = new FirefoxDriver();
driver.get("http://www.paymants.amazon.com/overview");
//driver.findElement(By.xpath("")).sendKeys("");
driver.close();
}
}

My TestNG result is
=================

[TestNG] Running:
C:\Users\lenovo\AppData\Local\Temp\testng-eclipse--1106206622\testng-customsuite.xml

FAILED: createBasicAccount
java.lang.NoClassDefFoundError: com/google/common/base/Function
at com.phani.first.Consts.createBasicAccount(Consts.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:617)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
at org.testng.SuiteRunner.run(SuiteRunner.java:240)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
at org.testng.TestNG.run(TestNG.java:1057)
at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Function
at java.net.URLClassLoader$1.run(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 25 more

===============================================
Default test
Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@626b2d4a: 19 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@73a8dfcc: 46 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@6f2b958e: 11 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 7 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@aec6354: 63 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@c2e1f26: 8 ms

Please, resolved my issue. and also tell me i need to change my OS or i need to make code changes or anything else... Thank you in advance...

**Comment by lukeis** [comment]
you have a java class path issue. Please use the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) mailing list for follow up questions and help.

**Comment by nvphaneendra** [comment]
But, I have set classpath also. Even though, I got the same issue... Is it problem with OS or any thing else. I need to add any other jar files. If you have any document regarding this please attach to me. 

Thank you, In advance...

**Comment by barancev** [comment]
you have a java class path issue. Please use the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) mailing list for follow up questions and help.
