### ISSUE TITLE
Exception in thread "main" java.lang.

### ISSUE THREAD

**Issue by dxcqcv** [SeleniumHQ/selenium#4412]
## Meta -
OS:  arch linux

Selenium Version:3.0.1  

Browser:  firefox

Browser Version:  54.0.1 (64-bit)

## Expected Behavior -
no error
## Actual Behavior -
error
## Steps to reproduce -

==================

I use [vue-cli](https://github.com/vuejs/vue-cli), and use `webpack` template, then I got this error when I run `npm run test` on arch linux

the full error info is 

```
Starting selenium server... There was an error while starting the Selenium server:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncherV4 : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ttv@1.0.0 e2e: `node test/e2e/runner.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ttv@1.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/clyde/.npm/_logs/2017-08-06T09_38_47_280Z-debug.log
error Command failed with exit code 1.

```

**Comment by ddavison** [comment]
Your IDE language level is misconfigured. Google

 ```
Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
```

and you should find the solution.

as this isn't a selenium issue, closing
