### ISSUE TITLE
Selenium IE Webdriver ClassCastException If register EventListener

### ISSUE THREAD

**Issue by bernaps** [SeleniumHQ/selenium#4449]
## Meta -
OS:  Windows 7

Selenium Version:  3.4.0

Browser:  Internet Explorer 

Browser Version:  IE 11.0.9600.18762

## Expected Behavior -
When registering an EventListener with an EventFiringWebDriver(Webdriver)
Should be able to access webpage with driver.get("myurl")

## Actual Behavior -
Get ClassCastException
java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List
	at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:83)
	at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:77)
	at com.notimportant.seleniumbugwithie.RunningEventListener.getBrowserLogs(RunningEventListener.java:91)
	at com.notimportant.seleniumbugwithie.RunningEventListener.beforeNavigateTo(RunningEventListener.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$1.invoke(EventFiringWebDriver.java:81)
	at com.sun.proxy.$Proxy0.beforeNavigateTo(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:162)
	at com.notimportant.seleniumbugwithie.ShowBug.runit(ShowBug.java:72)
	at com.notimportant.seleniumbugwithie.ShowBug.main(ShowBug.java:82)

## Steps to reproduce -
Clone SSCCE from https://github.com/bernaps/SeleniumBugWithIE.git 
Start IE Web driver version 3.5.0.0 64 Bit (Win7) Download from here
 * http://selenium-release.storage.googleapis.com/index.html
 *
 IEDriverServer.exe /port=6666
run maven project

**Comment by bernaps** [comment]
Run maven 
mvn -Dexec.args="-classpath %classpath com.notimportant.seleniumbugwithie.ShowBug" -Dexec.executable=java process-classes org.codehaus.mojo:exec-maven-plugin:1.2.1:exec

**Comment by barancev** [comment]
Off the top of my head, this issue should be fixed in 3.5, but let me check...

**Comment by barancev** [comment]
Yes, it works in 3.5
