### ISSUE TITLE
 3.5.0 - .NET w3c payload issue

### ISSUE THREAD

**Issue by unickq** [SeleniumHQ/selenium#4465]
@shs96c https://github.com/SeleniumHQ/selenium/issues/4461#issuecomment-322561827
> .Net bindings have set up the w3c payload to New Session.

**Code:**
```
var driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), DesiredCapabilities.Chrome());
driver.Manage().Window.Maximize();
driver.Quit();
```
**Throws exception:**
```
OpenQA.Selenium.WebDriverException : Unexpected error. 
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at Example.Class1.x() in C:\git\Unickq.SeleniumHelper\Example\Class1.cs:line 20
```
**Selenium server 3.5 logs:**
```
java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"desiredCapabilities":{"browserName":"chrome","version":"","platform":"ANY","javascriptEnabled":true,"YOUR CAP":"CAP Value"},"capabilities":{"firstMatch":[{"browserName":"chrome","javascriptEnabled":true,"YOUR CAP":"CAP Value"}]}}
...
Caused by:
java.lang.IllegalArgumentException: W3C payload contained keys that do not comply with the spec: [javascriptEnabled]
```

**Comment by unickq** [comment]
Fixed in 3.5.1
