### ISSUE TITLE
Selenium 3.5.0-geckodriver 0.18.0-Mozilla 53.0 :  org.openqa.selenium.WebDriverException raised when trying to access URL.

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4475]
## Meta -
OS:  Windows 8 Pro, 64 bit
Selenium Version:  3.5.0
GeckoDriver Version : 0.18.0
Browser:  Mozilla Firefox 53.0 (64-bit)

Browser Version:  
Mozilla Firefox 53.0 (64-bit)

## Actual Behavior -
WebDriver throws `org.openqa.selenium.WebDriverException` exception with error as `Reached error page: about:neterror?e=dnsNotFound&u=https%3A//nop.xpanama.net/if.html%3Fadflag%3D1%26cb%3DK1DJpXlFTk&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20find%20the%20server%20at%20nop.xpanama.net.` while opening the URL `https://www.merriam-webster.com/browse/medical/a`
## Steps to reproduce -
Code Block:

	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;

	public class A_Firefox 
	{
		public static void main(String[] args) 
		{
			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			WebDriver driver =  new FirefoxDriver();
			driver.get("https://www.merriam-webster.com/browse/medical/a");
		}
	}

Exception observed on the console:

	1502877129735	geckodriver	INFO	geckodriver 0.18.0
	1502877129749	geckodriver	INFO	Listening on 127.0.0.1:5604
	1502877131238	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
	1502877165597	Marionette	INFO	Listening on port 31843
	Aug 16, 2017 3:22:47 PM org.openqa.selenium.remote.ProtocolHandshake createSession
	INFO: Detected dialect: W3C
	Exception in thread "main" org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//nop.xpanama.net/if.html%3Fadflag%3D1%26cb%3DK1DJpXlFTk&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20find%20the%20server%20at%20nop.xpanama.net.
	Build info: version: '3.5.0', revision: '8def36e068', time: '2017-08-10T23:00:22.093Z'
	System info: host: 'ATECHM-03', ip: '192.168.1.48', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_77'
	Driver info: org.openqa.selenium.firefox.FirefoxDriver
	Capabilities [{moz:profile=C:\Users\ATECHM~1\AppData\Local\Temp\rust_mozprofile.yzYs6lpjV0N8, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0, platformVersion=6.2, moz:processID=5464.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
	Session ID: 80709181-37c2-4b0c-bf24-7cd7e555ee27
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
		at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:368)
		at demo.A_Firefox.main(A_Firefox.java:12)

**Comment by shs96c** [comment]
This was due to the W3C WebDriver spec having loose language around network errors.

https://github.com/mozilla/geckodriver/issues/770
