### ISSUE TITLE
Using Chromedriver with Electron unable to Maximize / Unmaximize / Set Window Position

### ISSUE THREAD

**Issue by rbarros-daitan** [SeleniumHQ/selenium#4504]
## Meta -
OS:  
Windows 10

Browser:  
Electron

Browser Version:  
Electron 1.7.5
Chromedriver 2.27

## Expected Behavior -
Maximize / Unmaximize / Set Window Position should work as expected.

## Actual Behavior -
Exception with stacktrace bellow is launched and can be seen on automation logs:

----MAXIMIZE----
06:02:06.030	TRACE	Arguments: [  ]	
06:02:06.030	DEBUG	POST http://192.168.227.2:4445/wd/hub/session/e22e66c552ca56f75f2b95dbb5b060d2/window/current/maximize {"windowHandle": "current", "sessionId": "e22e66c552ca56f75f2b95dbb5b060d2"}	
06:02:16.141	DEBUG	Finished Request	
06:02:16.296	FAIL	WebDriverException: Message: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: content shell=)
  (Driver info: chromedriver=2.27 (44a803957cb27610c38f7e859016ac257959aeb5),platform=Windows NT 10.0.14393 x86_64)
06:02:16.296	DEBUG	Traceback (most recent call last):
  File "<decorator-gen-21>", line 2, in maximize_browser_window
  File "/home/rodrigo/SAT-Robot/env/local/lib/python2.7/site-packages/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/home/rodrigo/SAT-Robot/env/local/lib/python2.7/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 242, in maximize_browser_window
    self._current_browser().maximize_window()
  File "/home/rodrigo/SAT-Robot/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 588, in maximize_window
    self.execute(command, {"windowHandle": "current"})
  File "/home/rodrigo/SAT-Robot/env/local/lib/python2.7/site-packages/Selenium2Library/webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "/home/rodrigo/SAT-Robot/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/home/rodrigo/SAT-Robot/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)

## Steps to reproduce -
Having a Ubuntu Machine managing Chromedriver running over Windows 10 machine with Electron App.
Maximize / Unmaximize / Set Window Position.

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).

**Comment by rodrigobarros-symphony** [comment]
@p0deje , hi. 

We have confirmed that latest Chromedriver (2.31) is also failing to MAXIMIZE Chrome as well. Should this ticket get reopened or should I file a new one? Here is the log for error on Chrome:

ubuntu@ip-100-120-1-174:~/tmp/docker_chrome_60/docker-selenium$ 13:37:30.235 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
13:37:30.236 INFO - Launching a standalone Selenium Server
2017-08-24 13:37:30.251:INFO::main: Logging initialized @194ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:37:30.294 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
13:37:30.294 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
13:37:30.294 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:37:30.294 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
13:37:30.295 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:37:30.295 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
13:37:30.295 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
2017-08-24 13:37:30.328:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-08-24 13:37:30.356:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@4c70fda8{/,null,AVAILABLE}
2017-08-24 13:37:30.370:INFO:osjs.AbstractConnector:main: Started ServerConnector@204f30ec{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-08-24 13:37:30.370:INFO:osjs.Server:main: Started @312ms
13:37:30.370 INFO - Selenium Server is up and running
13:38:11.745 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
13:38:12.218 INFO - Executing: [new session: Capabilities [{browserName=chrome, javascriptEnabled=true, chromeOptions={args=[--use-fake-device-for-media-stream, --use-fake-ui-for-media-stream, --auto-select-desktop-capture-source=Entire screen], extensions=[Q3IyNAIAAAAmAQAAAAEAADCCASIw...}, version=, platform=ANY}]])
13:38:12.241 INFO - Creating a new session for Capabilities [{browserName=chrome, javascriptEnabled=true, chromeOptions={args=[--use-fake-device-for-media-stream, --use-fake-ui-for-media-stream, --auto-select-desktop-capture-source=Entire screen], extensions=[Q3IyNAIAAAAmAQAAAAEAADCCASIw...}, version=, platform=ANY}]
Starting ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8) on port 15870
Only local connections are allowed.
13:39:12.617 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '52f81d31746c', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1031-aws', java.version: '1.8.0_131'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:190)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '52f81d31746c', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1031-aws', java.version: '1.8.0_131'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:110)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:96)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:102)
        ... 9 more
Caused by: org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.4.0-1031-aws x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.06 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '52f81d31746c', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1031-aws', java.version: '1.8.0_131'
Driver info: driver.version: ChromeDriver
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:184)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:148)
        ... 14 more

**Comment by sahana2610** [comment]
Hi was this resolved. I posted the question in ChromeDriver issues and this is the response I get. 
" ChromeDriver sends a Browser.getWindowForTarget command to the Browser. This command is valid for Google Chrome, but apparently Electron doesn't support it. Thus getting or changing window size doesn't work there.

It's up to the maintainers of Electron to decide which commands it supports. Please contact them to find out if or when Electron can support window size related commands."

https://bugs.chromium.org/p/chromedriver/issues/detail?id=2505&can=2&start=0&num=100&q=&colspec=ID%20Status%20Pri%20Owner%20Summary&groupby=&sort=

**Comment by cgoldberg** [comment]
@sahana2610 that is a question for maintainers of Electron
