### ISSUE TITLE
[IEDriverServer / Java] Command line server for the IE driver has stopped working

### ISSUE THREAD

**Issue by dave-curo** [SeleniumHQ/selenium#451]
I am having reliability problems with the IEDriver. It does occasionally work, but often fails with a windows popup saying "Command line server for the IE driver has stopped working".

This is reproducible for me with the following snippet:
```java
public static void main(String[] args) throws InterruptedException {
	System.setProperty("webdriver.ie.driver", "c:\\IEDriverServer_x32.exe");
	InternetExplorerDriverService service = InternetExplorerDriverService.createDefaultService();

	for (int count = 0; 1 < 10; count++) {
		WebDriver driver = new InternetExplorerDriver(service);
		driver.navigate().to("http://www.google.co.uk/");
		new WebDriverWait(driver, 5).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//input")));
		String title = driver.getTitle();
		System.out.println("Window title " + count + ": " + title);
		driver.quit();
		Thread.sleep(1000);
	}
}
```
This doesn't always fail on the first iteration, but for me 10 iterations is enough for it to always fail.

I'm using selenium-java and IEDriverServer (2.45) from:
http://selenium-release.storage.googleapis.com/index.html?path=2.45/
Internet Explorer 10.0.9200.17267
Windows 7

I get the same with both 64bit and 32bit versions of IEDriverServer. This snippet runs fine if switched to ChromeDriver.

When it blows up, i get the following stacktrace from the java InternetExplorerDriver:
```
Started InternetExplorerDriver server (32-bit)
2.45.0.0
Listening on port 33281
Window title 0: Google
Started InternetExplorerDriver server (32-bit)
2.45.0.0
Listening on port 33281
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'win7_ie9', ip: '192.168.122.63', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:593)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:225)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:182)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:174)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:158)
	at IeStoppedWorking.main(IeStoppedWorking.java:17)
Caused by: org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'win7_ie9', ip: '192.168.122.63', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:75)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	... 6 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:126)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:72)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:133)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:66)
	... 7 more
```

This seems similar to the behaviour reported here: https://code.google.com/p/selenium/issues/detail?id=6933

**Comment by jimevans** [comment]
I've run this in a loop that launches IE 100 times, and I get no crashes of IEDriverServer.exe. I'd be more inclined to keep this issue open with a log from IEDriverServer that demonstrates where the crash happens, but bear in mind that commit 6c807c7 papers over the crash, preventing the executable from exiting.

**Comment by dave-curo** [comment]
using https://github.com/SeleniumHQ/selenium/blob/6c807c71afda60c35d6caaa4fdc1817b8e62203e/cpp/prebuilt/x64/Release/IEDriverServer.exe (and the equivalent 32 bit binary), as expected the binary doesn't crash, but the errors are now exposed as other failures.

```
Unexpected error launching Internet Explorer. Found browser window using ShellWindows API, but could not attach to the browser IWebBrowser2 object. (WARNING: The server did not provide any stacktrace information)

Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to navigate to http://www.google.co.uk/. This usually means that a call to the COM method IWebBrowser2::Navigate2() failed. (WARNING: The server did not provide any stacktrace information)
```
This might be less frequent than with the previous binaries, but still fails within 10 iterations for me.

Debug log from v2.45
```
I 2015-04-14 17:50:12:997 server.cc(72) Starting WebDriver server on port: '19969' on host: ''
D 2015-04-14 17:50:12:998 server.cc(110) Civetweb ACL is -0.0.0.0/0,+127.0.0.1
D 2015-04-14 17:50:13:838 server.cc(243) Command: GET /status {}
D 2015-04-14 17:50:13:838 server.cc(317) Response: {"sessionId":"","status":0,"value":{"build":{"version":"2.45.0.0"},"os":{"arch":"x64","name":"windows","version":"6.1.7601"}}}

D 2015-04-14 17:50:13:850 server.cc(243) Command: POST /session {"desiredCapabilities":{"ensureCleanSession":true,"browserName":"internet explorer","version":"","platform":"WINDOWS"}}
D 2015-04-14 17:50:13:850 IESession.cpp(49) Mutex acquired for session initalization
D 2015-04-14 17:50:13:850 IESession.cpp(94) Using legacy driver implementation per user request
D 2015-04-14 17:50:13:853 IESession.cpp(128) Releasing session initialization mutex
D 2015-04-14 17:50:13:853 command.cc(33) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"ensureCleanSession":true,"browserName":"internet explorer","version":"","platform":"WINDOWS"}} }
D 2015-04-14 17:50:13:853 BrowserFactory.cpp(77) Ignoring Protected Mode Settings: 0
D 2015-04-14 17:50:13:853 BrowserFactory.cpp(80) Checking validity of Protected Mode settings.
D 2015-04-14 17:50:13:853 BrowserFactory.cpp(999) Detected IE version: 10, detected Windows version: 6
D 2015-04-14 17:50:13:853 BrowserFactory.cpp(1089) Found Protected Mode setting value of 0 for zone 1
D 2015-04-14 17:50:13:853 BrowserFactory.cpp(1089) Found Protected Mode setting value of 0 for zone 2
D 2015-04-14 17:50:13:853 BrowserFactory.cpp(1089) Found Protected Mode setting value of 0 for zone 3
D 2015-04-14 17:50:13:853 BrowserFactory.cpp(1089) Found Protected Mode setting value of 0 for zone 4
D 2015-04-14 17:50:13:853 BrowserFactory.cpp(83) Has Valid Protected Mode Settings: 1
D 2015-04-14 17:50:13:856 BrowserFactory.cpp(179) Starting IE using the IELaunchURL API
D 2015-04-14 17:50:14:085 BrowserFactory.cpp(133) IE launched successfully with process ID 5504
D 2015-04-14 17:50:14:085 BrowserFactory.cpp(139) Process with ID 5504 is executing iexplore.exe
D 2015-04-14 17:50:15:477 BrowserFactory.cpp(322) Ignoring zoom setting: 0
D 2015-04-14 17:50:15:511 BrowserFactory.cpp(590) Browser zoom level is 100%
I 2015-04-14 17:50:15:512 IECommandExecutor.cpp(662) Persistent hovering set to: 1
D 2015-04-14 17:50:15:512 ProxyManager.cpp(119) Using existing system proxy settings.
D 2015-04-14 17:50:15:524 server.cc(317) Response: {"sessionId":"a8bfc727-95e7-430c-b597-7b72ce7e6850","status":303,"value":"/session/a8bfc727-95e7-430c-b597-7b72ce7e6850"}

D 2015-04-14 17:50:15:534 server.cc(243) Command: GET /session/a8bfc727-95e7-430c-b597-7b72ce7e6850 {}
D 2015-04-14 17:50:15:535 command.cc(33) Raw JSON command: { "name" : "getSessionCapabilities", "locator" : { "sessionid" : "a8bfc727-95e7-430c-b597-7b72ce7e6850" }, "parameters" : {} }
D 2015-04-14 17:50:15:535 IECommandExecutor.cpp(556) No alert handle is found
D 2015-04-14 17:50:15:535 server.cc(317) Response: {"sessionId":"a8bfc727-95e7-430c-b597-7b72ce7e6850","status":0,"value":{"browserAttachTimeout":0,"browserName":"internet explorer","cssSelectorsEnabled":true,"elementScrollBehavior":0,"enableElementCacheCleanup":true,"enablePersistentHover":true,"handlesAlerts":true,"ie.browserCommandLineSwitches":"","ie.ensureCleanSession":false,"ie.forceCreateProcessApi":false,"ie.usePerProcessProxy":false,"ignoreProtectedModeSettings":false,"ignoreZoomSetting":false,"initialBrowserUrl":"http://localhost:19969/","javascriptEnabled":true,"nativeEvents":true,"platform":"WINDOWS","requireWindowFocus":false,"takesScreenshot":true,"unexpectedAlertBehaviour":"dismiss","version":"10"}}

D 2015-04-14 17:50:15:548 server.cc(243) Command: POST /session/a8bfc727-95e7-430c-b597-7b72ce7e6850/url {"url":"http://www.google.co.uk/"}
D 2015-04-14 17:50:15:548 command.cc(33) Raw JSON command: { "name" : "get", "locator" : { "sessionid" : "a8bfc727-95e7-430c-b597-7b72ce7e6850" }, "parameters" : {"url":"http://www.google.co.uk/"} }
D 2015-04-14 17:50:15:548 IECommandExecutor.cpp(556) No alert handle is found
W 2015-04-14 17:50:15:553 Browser.cpp(317) -2147024726 [The requested resource is in use.]: Call to IWebBrowser2::Navigate2 failed
W 2015-04-14 17:50:15:553 response.cc(74) Error response has status code 13 and message 'Failed to navigate to http://www.google.co.uk/. This usually means that a call to the COM method IWebBrowser2::Navigate2() failed.' message
D 2015-04-14 17:50:15:562 server.cc(317) Response: {"sessionId":"a8bfc727-95e7-430c-b597-7b72ce7e6850","status":13,"value":{"message":"Failed to navigate to http://www.google.co.uk/. This usually means that a call to the COM method IWebBrowser2::Navigate2() failed."}}

D 2015-04-14 17:50:15:942 ElementRepository.cpp(107) Refreshing managed element cache. Found 0 to remove from cache.
```

and from 6c807c7
```
I 2015-04-14 17:44:56:616 server.cc(72) Starting WebDriver server on port: '16575' on host: ''
D 2015-04-14 17:44:56:617 server.cc(110) Civetweb ACL is -0.0.0.0/0,+127.0.0.1
D 2015-04-14 17:44:57:452 server.cc(243) Command: GET /status {}
D 2015-04-14 17:44:57:452 server.cc(317) Response: {"sessionId":"","status":0,"value":{"build":{"version":"2.45.0.1"},"os":{"arch":"x64","name":"windows","version":"6.1.7601"}}}

D 2015-04-14 17:44:57:466 server.cc(243) Command: POST /session {"desiredCapabilities":{"ensureCleanSession":true,"browserName":"internet explorer","version":"","platform":"WINDOWS"}}
D 2015-04-14 17:44:57:466 IESession.cpp(49) Mutex acquired for session initalization
D 2015-04-14 17:44:57:466 IESession.cpp(94) Using legacy driver implementation per user request
D 2015-04-14 17:44:57:469 IESession.cpp(128) Releasing session initialization mutex
D 2015-04-14 17:44:57:469 command.cc(33) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"ensureCleanSession":true,"browserName":"internet explorer","version":"","platform":"WINDOWS"}} }
D 2015-04-14 17:44:57:469 BrowserFactory.cpp(77) Ignoring Protected Mode Settings: 0
D 2015-04-14 17:44:57:469 BrowserFactory.cpp(80) Checking validity of Protected Mode settings.
D 2015-04-14 17:44:57:469 BrowserFactory.cpp(1011) Detected IE version: 10, detected Windows version: 6
D 2015-04-14 17:44:57:469 BrowserFactory.cpp(1101) Found Protected Mode setting value of 0 for zone 1
D 2015-04-14 17:44:57:469 BrowserFactory.cpp(1101) Found Protected Mode setting value of 0 for zone 2
D 2015-04-14 17:44:57:469 BrowserFactory.cpp(1101) Found Protected Mode setting value of 0 for zone 3
D 2015-04-14 17:44:57:469 BrowserFactory.cpp(1101) Found Protected Mode setting value of 0 for zone 4
D 2015-04-14 17:44:57:469 BrowserFactory.cpp(83) Has Valid Protected Mode Settings: 1
D 2015-04-14 17:44:57:473 BrowserFactory.cpp(179) Starting IE using the IELaunchURL API
D 2015-04-14 17:44:57:773 BrowserFactory.cpp(133) IE launched successfully with process ID 5244
D 2015-04-14 17:44:57:773 BrowserFactory.cpp(139) Process with ID 5244 is executing iexplore.exe
W 2015-04-14 17:44:59:437 BrowserFactory.cpp(393) -2147467262 [No such interface supported]: Call to IHTMLDocument2::get_parentWindow failed
D 2015-04-14 17:44:59:438 BrowserFactory.cpp(309) Failed to find IWebBrowser2 using ActiveAccessibility: 
D 2015-04-14 17:44:59:438 BrowserFactory.cpp(314) Using IShellWindows to find IWebBrowser2 interface
W 2015-04-14 17:44:59:440 IECommandExecutor.cpp(656) Unable to attach to browser COM object
W 2015-04-14 17:44:59:440 response.cc(74) Error response has status code 6 and message 'Unexpected error launching Internet Explorer. Found browser window using ShellWindows API, but could not attach to the browser IWebBrowser2 object.' message
W 2015-04-14 17:44:59:440 IECommandExecutor.cpp(533) Unable to get current browser
D 2015-04-14 17:44:59:443 server.cc(194) Shutdown session is not found
D 2015-04-14 17:44:59:443 server.cc(317) Response: {"sessionId":"bee5c185-a01d-42e9-84dd-5fc9d92c0d86","status":6,"value":{"message":"Unexpected error launching Internet Explorer. Found browser window using ShellWindows API, but could not attach to the browser IWebBrowser2 object."}}
``` 

Any thing else that would be useful?

**Comment by dave-curo** [comment]
Hi Jim,

Can you reopen this, or should I raise a new issue with the debug logs attached? I'm still experiencing this issue and it makes Internet Explorer unusable for me...

Is there anything else I can do to triage this problem?

Thanks,
Dave

**Comment by jimevans** [comment]
I'm not going to reopen this issue. The reported problem, the crash, has been mitigated. Feel free to open another issue, but be aware that if, due to configuration issues in your specific environment, the driver can't attach to the instance of Internet Explorer that it launches via either Active Accessibility or via the ShellWindows API, there's not anything that we can do to resolve it. This is doubly so if the symptoms you describe aren't reproducible outside your specific environment.

I did make some slight changes as of 5b9bca3 to increase the amount of logging so that we might be better able to pinpoint where the problem is happening, but again, this would be diagnostic only, not an actual resolution to the issue.

I'll be perfectly happy to fix the issue, as long as I can get it to reproduce. Up to now, I'm entirely unable to do so.

**Comment by dave-curo** [comment]
Fair enough - I completely understand that identifying why it's not working is essential to fixing it, something much more complicated with intermittent problems. I can't help wonder if there is a race happening during initilizing the browser - i.e. perhaps we're trying to connect and sometimes the browser has not yet initialised?

I'll assemble more details and raise a separate issue.

Dave

**Comment by Gongsunshu** [comment]
So,how to solve it?
