### ISSUE TITLE
Problem with Firefox 37.0.1 with Selenium 2.45.0 (Permission denied to access property "handleEvent")

### ISSUE THREAD

**Issue by fazeli** [SeleniumHQ/selenium#452]
Since FF version 36.0 we have this problem. The problem basically happens when webdriver is triggering click event on an element during test execution.
This problem happens quite randomly on elements in a same page that webderiver wants to trigger their click events.
One workaround that I did to fix this issue was to add 'Driver.switchTo().activeElement()' before clicking on the element and the error doesn't happen again.
The problem is that now we have over 100 test cases and it seems we have to put this code snippet before all the click events!

Any idea why is this happening?

Below is the stack trace:
org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Command duration or timeout: 116 milliseconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'xxxx', ip: 'my ip address', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_67'
*** Element info: {Using=css selector, value=div div.acknowledge-warning-container a.acknowledge-warning}
Session ID: 1e3b4b2b-d776-4e39-8056-29874789dc1c
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=37.0.1}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:441)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:426)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at hbon.web.utility.HBONSetup.InitiateSetUp(HBONSetup.java:96)
	at hbon.web.utility.HBONSetup.InitiateSetUp(HBONSetup.java:71)
	at hbon.web.InfoButtonTest.setUp(InfoButtonTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'

**Comment by lukeis** [comment]
Please read https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports

Namely the paragraph about a concise reproducible test case.

We can't reproduce this stacktrace without an associated webpage. Please provide one and then we can reopen the issue.

**Comment by DmitryLapshov** [comment]
@fazeli I'm facing the same problem and in my case it looks like it's enough to call Driver.switchTo().activeElement() only once right after the page is opened.

**Comment by andrerav** [comment]
Hi,

We are facing the same issue, and we suspect this to be related to a third party script. Here is a test case:

        [TestMethod]
        public void CurrentPilotages()
        {
            Browser.Navigate().GoToUrl("test.shiprep.no/shiprepwebuihavn/CurrentPilotages.aspx");
            var something = new SelectElement(Browser.FindElement(By.Id("ctl00_MainContent_PilotageDispatchDepartmentDropDown")));
            something.SelectByIndex(1); // System.InvalidOperationException: Permission denied to access property "handleEvent"
        }

**Comment by andrerav** [comment]
Update: Turns out bugsnag 2.4.5 was the culprit. We will update bugsnag to the latest version and report back. No need to re-open this issue yet.

**Comment by DmitryLapshov** [comment]
@andrerav It's a known issue http://stackoverflow.com/a/30061843/2972197
"This is fixed by rescuing from this exception in Bugsnag v2.4.8. Arguably selenium shouldn't be adding native handlers to in-page events, but oh well :)"

**Comment by andrerav** [comment]
@DmitryLapshov Certainly is -- I was not aware that we were using this library :)
