### ISSUE TITLE
Creating PhantomJs Sessions is Broken since 3.5.0

### ISSUE THREAD

**Issue by rhehl** [SeleniumHQ/selenium#4524]
In my current setup I've web driver-manager as wrapper for Selenium Standalone and I run my tests with protractor.

Since Selenium Standalone 3.5.0 is released I get the following error if I try to start a PhantomJS Session:

```
[17:29:18] I/launcher - Running 1 instances of WebDriver
[17:29:18] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[17:29:18] E/launcher - Unable to create new service: PhantomJSDriverService
Build info: version: '3.5.1', revision: '9c21bb67ef', time: '2017-08-16T21:10:06.092Z'
System info: host: 'xxx-xxxxx', ip: '10.x.x.x', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_121'
Driver info: driver.version: unknown
[17:29:18] E/launcher - SessionNotCreatedError: Unable to create new service: PhantomJSDriverService
Build info: version: '3.5.1', revision: '9c21bb67ef', time: '2017-08-16T21:10:06.092Z'
System info: host: 'xxx-xxxxx', ip: '10.x.x.x', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_121'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at createDriver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:632:14)
    at Hosted.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:52:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:194:43)
    at q.then.then (/usr/local/lib/node_modules/protractor/built/runner.js:338:29)
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
[17:29:18] E/launcher - Process exited with error code 199
```

If I manually start Selenium Standalone version 3.4.0 or start the webdriver-manager with --versions.standalone=3.4.0 this fixes my problem.
Another solution is starting Selenium Standalone 3.5.x with "-enablePassThrough false"

**Comment by lmtierney** [comment]
Sounds like protractor isn't updated to use w3c compliant endpoints. If you can reproduce it with selenium outside of protractor then we can take a look.

**Comment by barancev** [comment]
@rhehl Provide Selenium Server logs, may be we'll be able to get enough info from the logs without reproduction scenario.

**Comment by 7170** [comment]
+1

Reproduced on my side, works fine with welenium 3.4.0, but impossible to get an URL with version 3.5.X

I'm not sure, but the ERROR we are looking for could be this one (related to sessions):
``[ERROR - 2017-09-14T21:58:00.450Z] RouterReqHand - _handle.error - 
{"message":"{\"headers\":{\"Accept\":\"text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\",\"Cache-Control\":\"no-cache\",
\"Connection\":\"close\",\"Host\":\"localhost:29742\",\"Pragma\":\"no-cache\",\"User-Agent\":\"Java/1.8.0_141\"},
\"httpVersion\":\"1.1\",\"method\":\"DELETE\",\"url\":\"/session/c5e5...\",\"urlParsed\":{\"anchor\":\"\",
\"query\":\"\",\"file\":\"c5e5...\",\"directory\":\"/session/\",\"path\":\"/session/c5e5...\",
\"relative\":\"/session/c5e5...\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",
\"authority\":\"\",\"protocol\":\"\",\"source\":\"/session/c5e5...\",\"queryKey\":{},\"chunks\":
[\"session\",\"c5e5...\"]}}","name":"Variable Resource Not Found","line":123,"sourceId":71128944,
"sourceURL":":/ghostdriver/request_handlers/session_manager_request_handler.js","stack":"
Variable Resource Not Found: {\"headers\":{\"Accept\":\"text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\",\"Cache-Control\":\"no-cache\",
\"Connection\":\"close\",\"Host\":\"localhost:29742\",\"Pragma\":\"no-cache\",\"User-Agent\":\"Java/1.8.0_141\"},\"httpVersion\":\"1.1\",
\"method\":\"DELETE\",\"url\":\"/session/c5e5...\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",
\"file\":\"c5e5...\",\"directory\":\"/session/\",\"path\":\"/session/c5e5...\",
\"relative\":\"/session/c5e5...\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",
\"authority\":\"\",\"protocol\":\"\",\"source\":\"/session/c5e5...\",\"queryKey\":{},
\"chunks\":[\"session\",\"c5e5...\"]}}\n    at :/ghostdriver/request_handlers/session_manager_request_handler.js:123\n    
at :/ghostdriver/request_handlers/session_manager_request_handler.js:53\n    at :/ghostdriver/request_handlers/router_request_handler.js:70","stackArray":[{"sourceURL":":/ghostdriver/request_handlers/session_manager_request_handler.js","line":123},{"sourceURL":":/ghostdriver/request_handlers/session_manager_request_handler.js","line":53},{"sourceURL":":/ghostdriver/request_handlers/router_request_handler.js","line":70}]}
``
More information about the running env:
I'm using codeception, and the test fails when I try to GET an URL

I'm hoping it could help you, good luck :)

**Comment by barancev** [comment]
Closing this issue, there is not information to act on.

Also note that PhantomJS project has been discontinued, as well as the driver for this browser.
