### ISSUE TITLE
"timeouts" endpoint removed in Geckodriver

### ISSUE THREAD

**Issue by minusnine** [SeleniumHQ/selenium#4529]
In the latest release of Geckodriver, they removed the `timeouts` endpoint in favor of the `setTimeouts` endpoint:

https://reviewboard.mozilla.org/r/151730/diff/3#index_header
https://bugzilla.mozilla.org/show_bug.cgi?id=1375425
https://github.com/mozilla/geckodriver/blob/release/CHANGES.md#0180-2017-07-10

This manifests in WebDriver as an exception:

```
2017/08/21 17:33:36 -> POST http://127.0.0.1:35559/wd/hub/session/7233d556-2d30-40b8-8b59-3c8b26534aa3/timeouts/async_script
{"ms":0}                                                                      
17:33:36.967 INFO - Executing: [set script timeout: 0])                               
17:33:36.991 INFO - HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
17:33:36.998 WARN - Exception thrown                                                                                                                           
org.openqa.selenium.WebDriverException: timeouts                                                                                                               
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'                                                                                             
System info: host: 'ekg03', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-87-generic', java.version: '1.8.0_112-google-v7'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/tmp/rust_mozprofile.FCiQ1MbjzLEv, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=nor
mal, moz:headless=false, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=57.0a1, platformVersion
=4.4.0-87-generic, moz:processID=20716.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
Session ID: 5ea22d4f-1cc6-46b4-b8d2-cda7e13a9717
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.setScriptTimeout(RemoteWebDriver.java:874)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringTimeouts.setScriptTimeout(EventFiringWebDriver.java:565)
        at org.openqa.selenium.remote.server.handler.SetScriptTimeout.call(SetScriptTimeout.java:45)
        at org.openqa.selenium.remote.server.handler.SetScriptTimeout.call(SetScriptTimeout.java:27)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by minusnine** [comment]
D'oh. I was using a slightly older version of Geckodriver. This got fixed in 0.18.0. Sorry for the noise.
