### ISSUE TITLE
IEDriver stalls at startup sporadically

### ISSUE THREAD

**Issue by binodpanta** [SeleniumHQ/selenium#454]
I am starting IEDriver using java client

```java
        // Some setup for registry etc. I can provide details on what we do for each one of these, but we have had to build these up over the years for various reasons.
		setupProtectedMode();
		formatRegistryForIE11();
		turnAutocompleteOff();
		turnOffPopupBlocking();
		turnOffIEMaxScriptStatementsWarning();
		resetCompatViewForIntranetSetting();

// Actual driver startup section
        caps = DesiredCapabilities.internetExplorer();
	caps.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
	final WebDriver d = new InternetExplorerDriver(serv,
					caps);
```

Here are my specs:

    Windows 7 64 bit 
    IE11 11.0.9600.17691CO
    IEDriver: 2.45.0.0 (32 bit version)
    Most Recent Windows update ran on this host was: Security Update for Windows 7 for x64-based Systems (KB3035131). I can get more updates info if relevant

Java thread dump shows 'newSession' is being attempted:

```ruby
  "Forwarding newSession on session null to remote" prio=6 tid=0x00000000022ef000 nid=0x1030 runnable [0x00000000025bd000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:126)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:72)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:133)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:225)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:182)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:174)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:162)
```

At this time, even closing the IE browser does not unlock this, and the stall continues. Killing IEDriver is the only resort.

How do I go about further debugging this? Should I setup IEDriver VS for debugging or can I get some more diagnostics first?

**Comment by jimevans** [comment]
You're passing the `ie.ensureCleanSession` capability. This has the effect of calling the "delete browsing history" utility before every single session. This is a very time-consuming and expensive operation. The equivalent command line is:

    rundll32.exe inetcpl.cpl ClearMyTracksByProcess 2559

If you execute this manually, you'll see that it takes some time for the process to exit. Additionally, if you enable logging on `IEDriverServer.exe` at the debug level, you'll see where this process gets started and when it finishes.

**Comment by mamta2009** [comment]
Just want to circle back on this, and thank you for the tip. I think this had reduced stall rate by a huge  amount. However, I still have 1/10 runs stalling. I have yet to understand the cause. Perhaps some of the other settings I am applying have to do with this? I can send more details if necessary

**Comment by binodpanta** [comment]
Hi I should circle back on this and thank you for providing the tip! My failure rate now has drastically reduced, however I still have about 1/10 runs stalling at the same point. I have yet to understand why. I am suspicious whether some of the other settings I am applying have to do with this. I will be trying to grab more logs and see if it points to the root of the issue. And I can provide more details on the various settings I am applying.
