### ISSUE TITLE
Headless IE with selenium not working on Windows server 

### ISSUE THREAD

**Issue by PascalGit1** [SeleniumHQ/selenium#4551]
**OS:  Windows Server 2008 R2
Selenium Version:  3.4.0
Browser:  Internet Explorer (version 11.0.9600.18738 - 32bit)
IEDriverServer.exe version: 3.4.0** 

I was running my tests on a windows 2008 R2 server but i had to be logged in for it to work on IE because it doesn't have a headless version. 
So I looked online to find a way arround this and found this:
https://github.com/kybu/headless-selenium-for-win

First i tried running it locally and it worked great, it would run all my tests without any issue and headless. But when i tried to run them on the server the test would fail and the screenshots would show up black, meaning it didn't run IE headless. 
My logs don't show any errors besides the expected one from not being able to find the element

Driver setup:

```
  System.setProperty("webdriver.ie.driver", "drivers/windows/headless_ie_selenium.exe");
       System.setProperty("webdriver.ie.driver.loglevel","WARN");
       driver = new InternetExplorerDriver();
```

Log: 

```
Running nl.esize.cucumber.runner.MainRunnerTest
Feature: Login Esize 8
Started InternetExplorerDriver server (32-bit)
3.4.0.0
Listening on port 46411
Log level is set to WARN
Only local connections are allowed
aug 23, 2017 2:11:46 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
W 2017-08-23 14:11:53:046 CommandHandlers\SendKeysCommandHandler.cpp(176) Specified element is not the active element. Keystrokes may go to an unexpected DOM element.
W 2017-08-23 14:11:54:318 CommandHandlers\SendKeysCommandHandler.cpp(176) Specified element is not the active element. Keystrokes may go to an unexpected DOM element.
W 2017-08-23 14:11:54:516 InteractionsManager.cpp(1054) From X appears to be < 0. Rounding to 0. -1
W 2017-08-23 14:11:54:516 InteractionsManager.cpp(1058) From Y appears to be < 0. Rounding to 0. -1
Selenium driver found at: C:\Jenkins\workspace\CucumberIntegration-BrenchTest\drivers\windows\IEDriverServer.exe

Started InternetExplorerDriver server (32-bit)
3.4.0.0
Listening on port 21658
Log level is set to WARN
Only local connections are allowed
aug 23, 2017 2:12:32 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

  Scenario: Login with admin credentials                            # Login.feature:4
    Given Start application                                         # StartDefinition.startApplication()
    When login user                                                  # StartDefinition.loginUserAndPassword(String,String)
    Then find inputfield: "form-header-search:search-general_input" # ElementDefinition.findInputfield(String)
      org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.id: form-header-search:search-general_input (tried for 15 second(s) with 500 MILLISECONDS interval)
      	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
      	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:232)
      	at nl.esize.cucumber.stepdefinition.ElementDefinition.findInputfield(ElementDefinition.java:61)
      	at ?.Then find inputfield: "form-header-search:search-general_input"(Login.feature:7)
      Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: form-header-search:search-general_input
      For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
      Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
      System info: host: 'EHGD-PLS-APP02', ip: '10.3.62.240', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_51'
      Driver info: driver.version: unknown
      	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:883)
      	at org.openqa.selenium.support.ui.ExpectedConditions$$Lambda$99/802255644.get(Unknown Source)
      	at java.util.Optional.orElseThrow(Optional.java:290)
      	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:882)
      	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
      	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:206)
      	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:202)
      	at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:644)
      	at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:641)
      	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
      	at nl.esize.cucumber.stepdefinition.ElementDefinition.findInputfield(ElementDefinition.java:61)
      	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      	at java.lang.reflect.Method.invoke(Method.java:497)
      	at cucumber.runtime.Utils$1.call(Utils.java:40)
      	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
      	at cucumber.runtime.Utils.invoke(Utils.java:34)
      	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
      	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
      	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
      	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
      	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
      	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
      	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
      	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
      	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
      	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
      	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
      	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
      	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
      	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
      	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
      	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
      	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
      	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
      	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
      	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
      	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
      	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
      	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
      	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
      	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
      	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
      	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
      	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
      	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
      	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
      	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
      	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Comment by jimevans** [comment]
The IE driver does not support execution without an active, logged-in desktop session running. You'll need to take this up with the author of the solution you're using to achieve "headless" (scare quotes intentional) execution of IE.

**Comment by PascalGit1** [comment]
Is there a specific reason for this? since the other browser do support this.
Because it would make sense to be able to run your automated tests overnight without having an active desktop session.

**Comment by jimevans** [comment]
The specific reason is that IE doesn't support it. You can't take a screenshot without an active session. Mouse and keyboard simulation won't work without an active session. It's a browser limitation, not a driver limitation.
