### ISSUE TITLE
Null pointer exception when calling webDriver.findElements

### ISSUE THREAD

**Issue by ClintonMorrison** [SeleniumHQ/selenium#4555]
## Meta -
OS:  OSX
Selenium Version:  3.3.1, IntelliJ
Browser:  Chrome 60

Browser Version:  
Version 60.0.3112.90 (Official Build) (64-bit)

## Expected Behavior -
No null pointer exception when calling `webDriver.findElements`

## Actual Behavior -
Occasionally, calling `webDriver.findElements(By.cssSelector(query))` causes a null pointer exception. Here is the stack trace:
```
java.lang.NullPointerException
    at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:450)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementsByCssSelector(RemoteWebDriver.java:509)
    at org.openqa.selenium.By$ByCssSelector.findElements(By.java:441)
    at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:402)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.openqa.selenium.remote.Augmenter$CompoundHandler.intercept(Augmenter.java:189)
    at org.openqa.selenium.remote.RemoteWebDriver$$EnhancerByCGLIB$$88202d8c.findElements(<generated>)
```

## Steps to reproduce -
It seems to happen only rarely happen so it's hard to reliably reproduce. I think it is a race condition. There was a recently a report of a similar issue in: https://github.com/SeleniumHQ/selenium/issues/4375

**Comment by barancev** [comment]
Actually, it's a chromedriver issue. It **must** return a list of web elements (or an empty list) on this operation. But sometimes it breaks the contract and returns null. *Sigh*

So we have to be more defensive and convert null to an empty list on the client side. All language bindings can suffer from this issue.

**Comment by barancev** [comment]
Fixed in Java binding by 4a3ec2d5bbc44ca258f5a9d71c82835de319cffa

**Comment by ClintonMorrison** [comment]
Thanks @barancev!

**Comment by ClintonMorrison** [comment]
What release will this be in?

**Comment by p0deje** [comment]
Fixed in Ruby bindings in d4d843398eedfdbf6354be6bfeaa04521532d384.

**Comment by lmtierney** [comment]
Does this only affect `findElements` and not `findChildElements`?

**Comment by lmtierney** [comment]
Fixed in python 4fcce6e

**Comment by IvantsovAV** [comment]
A moment ago (but don't reproduce):

InternetExplorerDriver server (32-bit) 3.6.0.0
selenium-java 3.7.1

`java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203)
at java.util.Optional.<init>(Optional.java:96)
at java.util.Optional.of(Optional.java:108)
at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:193)
at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:190)
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:881)
at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:43)
at org.openqa.selenium.support.ui.ExpectedConditions$20.apply(ExpectedConditions.java:579)
at org.openqa.selenium.support.ui.ExpectedConditions$20.apply(ExpectedConditions.java:575)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
`


May be it returns _list of null(s)_?

**Comment by BrandonDudek** [comment]
In Selenium 3.14.0, I see cases where `response` is returning an empty string as the value.
Can this case be covered as well?

**Comment by diemol** [comment]
It seems it was implemented in all bindings except .NET, in case any one finds an issue there, please open a new issue.

**Comment by sushmanarla** [comment]
The problem for me was that the path to find chrome browser was missing ".exe" in it. I'm referring to the "VM options:" in Run>Edit Configurations>JDK Settings

-Dwebdriver.chrome.driver="D:\\Work\\Softwares\\chromedriver_win32.\\chromedriver.exe"
