### ISSUE TITLE
py[3.5.0]: __package__ may be None in selenium.webdriver.remote.webelement

### ISSUE THREAD

**Issue by tkhyn** [SeleniumHQ/selenium#4558]
## Meta -
OS:  Windows 7
Selenium Version:  selenium-py 3.5.0, on python 3.6.2
Browser:  N/A

## Expected Behavior -
`selenium.webdriver.remote.webelement` can be imported without issue

## Actual Behavior -
In some situations (I encountered that when launching a test suite from PyCharm), importing `selenium.webdriver.remote.webelement` (indirectly via `selenium.webdriver`) raises an `AttributeError` coming from the fact that `__package__` is `None` when calling `pkgutil.get_data(__package__, ...)` [here](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py#L41).

```
  File "d:\dev\.env\buildout\eggs\selenium-3.5.0-py3.6.egg\selenium\webdriver\remote\webelement.py", line 45, in <module>
    getAttribute_js = pkgutil.get_data(__package__, 'getAttribute.js').decode('utf8')
  File "C:\Python\3.6\Lib\pkgutil.py", line 616, in get_data
    spec = importlib.util.find_spec(package)
  File "D:\dev\.env\venv\buildout\lib\importlib\util.py", line 83, in find_spec
    fullname = resolve_name(name, package) if name.startswith('.') else name
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Looking for a way to resolve that, I discovered that `__package__` is not set consistently by python within modules (see [here](https://stackoverflow.com/questions/4437394/package-is-none-when-importing-a-python-module), while it's hard to understand why it's not set in that situation), and that it may be better to rely on `__name__` instead. Hence I'd think of replacing:

```
getAttribute_js = pkgutil.get_data(__package__, 'getAttribute.js').decode('utf8')
isDisplayed_js = pkgutil.get_data(__package__, 'isDisplayed.js').decode('utf8')
```

by:

```
_pkg = '.'.join(__name__.split('.')[:-1])
getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
isDisplayed_js = pkgutil.get_data(_pkg, 'isDisplayed.js').decode('utf8')
```

## Steps to reproduce -
Not sure if it can be reproduced on any machine, but for me it's simply 'launch a script importing `selenium.webdriver` at some point from PyCharm'. Launching the same script in the console works, for some reason.

**Comment by lmtierney** [comment]
Are you by chance using the source from the git repo instead of installing the package itself? That's the only way I can see this happen... The package needs to be installed so that it can pull in extra required files. Alternatively, you can build those extra files, but unless you're going to contribute to the project you should be installing the package.

**Comment by tkhyn** [comment]
Thanks @lmtierney for the quick reply,
No, I'm just using zc.buildout, which installs packages as eggs rather than in a virtual environment. Which makes me think that it's very likely to be related, as PyCharm takes care of including the required egg directories on its side before launching the script. On the other hand if I use `python bin/my-test-script.py` in the console the directories are added 'in-script'  to `sys.path`.

**Comment by lmtierney** [comment]
I've never used zc.buildout, and I'm not sure how it works; but apparently it isn't getting those files. This is where you can find them normally, which are packaged with the source on pypi:

https://github.com/SeleniumHQ/selenium/blob/master/py/setup.py#L78-L79

**Comment by tkhyn** [comment]
The files (getAttribute.js and isDisplayed.js) are there and there is no problem for `pkgutil.get_data` to fetch them provided it is passed the string `'selenium.webdriver.remote'` as a first argument.

The problem is that `__package__` is `None`, and therefore `pkgutil.get_data(None, ...)` fails.

**Comment by lmtierney** [comment]
Ah sorry, I didn't read your entire description. I'll have to see what @AutomatedTester or @davehunt think about changing that

**Comment by rodolfojcj** [comment]
I'm facing a similar situation to the original one reported by @tkhyn. My environment is docker based, with xvfb because no graphical display is available. Also, Python virtualenvwrapper is used.

Also, the quick fix of @tkhyn with the following lines worked for me:

    _pkg = '.'.join(__name__.split('.')[:-1])
    getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
    isDisplayed_js = pkgutil.get_data(_pkg, 'isDisplayed.js').decode('utf8')

For my virtual environment I replaced those lines in the file `/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py`.

The problem started to appear for me, after installing the `pytest-splinter` plugin via _pip_.

The pytest plugins installed are: xvfb-1.0.0, splinter-1.8.5, django-3.1.2, bdd-2.18.2

Note: running a command like `pytest -h` also failed for the same reason.

Here more details:
    ================
    (e2e) root@dd4d05dc7d9e:/tmp/lz/e2e# pytest -so
    ================
    
    Traceback (most recent call last):
      File "/root/virtual_envs/e2e/bin/pytest", line 11, in <module>
        sys.exit(main())
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 49, in main
        config = _prepareconfig(args, plugins)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 168, in _prepareconfig
        pluginmanager=pluginmanager, args=args)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
        return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
        return self._inner_hookexec(hook, methods, kwargs)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
        _MultiCall(methods, kwargs, hook.spec_opts).execute()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
        return _wrapped_call(hook_impl.function(*args), self.execute)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
        wrap_controller.send(call_outcome)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
        config = outcome.get_result()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
        raise ex[1].with_traceback(ex[2])
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
        self.result = func()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
        res = hook_impl.function(*args)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 957, in pytest_cmdline_parse
        self.parse(args)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 1121, in parse
        self._preparse(args, addopts=addopts)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 1084, in _preparse
        self.pluginmanager.load_setuptools_entrypoints('pytest11')
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
        plugin = ep.load()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2316, in load
        return self.resolve()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/pytest_splinter/plugin.py", line 18, in <module>
        import splinter  # pragma: no cover
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/splinter/__init__.py", line 5, in <module>
        from splinter.browser import Browser # NOQA
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/splinter/browser.py", line 9, in <module>
        from splinter.driver.webdriver.firefox import WebDriver as FirefoxWebDriver
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/splinter/driver/webdriver/__init__.py", line 15, in <module>
        from selenium.webdriver.common.action_chains import ActionChains
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/__init__.py", line 18, in <module>
        from .firefox.webdriver import WebDriver as Firefox  # noqa
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 34, in <module>
        from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 26, in <module>
        from .webelement import WebElement
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 41, in <module>
        getAttribute_js = pkgutil.get_data(__package__, 'getAttribute.js').decode('utf8')
      File "/usr/local/lib/python3.6/pkgutil.py", line 616, in get_data
        spec = importlib.util.find_spec(package)
      File "/root/virtual_envs/e2e/lib/python3.6/importlib/util.py", line 83, in find_spec
        fullname = resolve_name(name, package) if name.startswith('.') else name
    AttributeError: 'NoneType' object has no attribute 'startswith'
    
    
    
    ================
    (e2e) root@dd4d05dc7d9e:/tmp/lz/e2e# pip freeze                                                                                                                        
    ================
    
    Django==1.11.1                                                                                                                                                         
    djangorestframework==3.6.3                                                                                                                                             
    djangorestframework-jsonapi==2.2.0                                                                                                                                     
    djoser==0.5.4                                                                                                                                                          
    drf-base64==0.9.2                                                                                                                                                      
    EasyProcess==0.2.3                                                                                                                                                     
    glob2==0.6                                                                                                                                                             
    inflection==0.3.1                                                                                                                                                      
    Mako==1.0.7                                                                                                                                                            
    MarkupSafe==1.0                                                                                                                                                        
    parse==1.8.2                                                                                                                                                           
    parse-type==0.3.4                                                                                                                                                      
    py==1.4.34                                                                                                                                                             
    pytest==3.2.1                                                                                                                                                          
    pytest-bdd==2.18.2                                                                                                                                                     
    pytest-django==3.1.2                                                                                                                                                   
    pytest-splinter==1.8.5
    pytest-xvfb==1.0.0
    pytz==2017.2
    PyVirtualDisplay==0.2.1
    selenium==3.5.0
    six==1.10.0
    splinter==0.7.6

**Comment by rodolfojcj** [comment]
I'm facing a similar situation to the original one reported by @tkhyn. My environment is docker based, with xvfb because no graphical display is available. Also, Python virtualenvwrapper is used.

Also, the quick fix of @tkhyn with the following lines worked for me:

    _pkg = '.'.join(__name__.split('.')[:-1])
    getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
    isDisplayed_js = pkgutil.get_data(_pkg, 'isDisplayed.js').decode('utf8')

For my virtual environment I replaced those lines in the file `/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py`.

The problem started to appear for me, after installing the `pytest-splinter` plugin via _pip_.

The pytest plugins installed are: xvfb-1.0.0, splinter-1.8.5, django-3.1.2, bdd-2.18.2

Note: running a command like `pytest -h` also failed for the same reason.

Here more details:
    ================
    (e2e) root@dd4d05dc7d9e:/tmp/lz/e2e# pytest -so
    ================
    
    Traceback (most recent call last):
      File "/root/virtual_envs/e2e/bin/pytest", line 11, in <module>
        sys.exit(main())
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 49, in main
        config = _prepareconfig(args, plugins)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 168, in _prepareconfig
        pluginmanager=pluginmanager, args=args)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
        return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
        return self._inner_hookexec(hook, methods, kwargs)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
        _MultiCall(methods, kwargs, hook.spec_opts).execute()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
        return _wrapped_call(hook_impl.function(*args), self.execute)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
        wrap_controller.send(call_outcome)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
        config = outcome.get_result()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
        raise ex[1].with_traceback(ex[2])
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
        self.result = func()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
        res = hook_impl.function(*args)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 957, in pytest_cmdline_parse
        self.parse(args)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 1121, in parse
        self._preparse(args, addopts=addopts)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/config.py", line 1084, in _preparse
        self.pluginmanager.load_setuptools_entrypoints('pytest11')
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
        plugin = ep.load()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2316, in load
        return self.resolve()
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/pytest_splinter/plugin.py", line 18, in <module>
        import splinter  # pragma: no cover
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/splinter/__init__.py", line 5, in <module>
        from splinter.browser import Browser # NOQA
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/splinter/browser.py", line 9, in <module>
        from splinter.driver.webdriver.firefox import WebDriver as FirefoxWebDriver
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/splinter/driver/webdriver/__init__.py", line 15, in <module>
        from selenium.webdriver.common.action_chains import ActionChains
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/__init__.py", line 18, in <module>
        from .firefox.webdriver import WebDriver as Firefox  # noqa
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 34, in <module>
        from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 26, in <module>
        from .webelement import WebElement
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
        py.builtin.exec_(co, mod.__dict__)
      File "/root/virtual_envs/e2e/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 41, in <module>
        getAttribute_js = pkgutil.get_data(__package__, 'getAttribute.js').decode('utf8')
      File "/usr/local/lib/python3.6/pkgutil.py", line 616, in get_data
        spec = importlib.util.find_spec(package)
      File "/root/virtual_envs/e2e/lib/python3.6/importlib/util.py", line 83, in find_spec
        fullname = resolve_name(name, package) if name.startswith('.') else name
    AttributeError: 'NoneType' object has no attribute 'startswith'
    
    
    
    ================
    (e2e) root@dd4d05dc7d9e:/tmp/lz/e2e# pip freeze                                                                                                                        
    ================
    
    Django==1.11.1                                                                                                                                                         
    djangorestframework==3.6.3                                                                                                                                             
    djangorestframework-jsonapi==2.2.0                                                                                                                                     
    djoser==0.5.4                                                                                                                                                          
    drf-base64==0.9.2                                                                                                                                                      
    EasyProcess==0.2.3                                                                                                                                                     
    glob2==0.6                                                                                                                                                             
    inflection==0.3.1                                                                                                                                                      
    Mako==1.0.7                                                                                                                                                            
    MarkupSafe==1.0                                                                                                                                                        
    parse==1.8.2                                                                                                                                                           
    parse-type==0.3.4                                                                                                                                                      
    py==1.4.34                                                                                                                                                             
    pytest==3.2.1                                                                                                                                                          
    pytest-bdd==2.18.2                                                                                                                                                     
    pytest-django==3.1.2                                                                                                                                                   
    pytest-splinter==1.8.5
    pytest-xvfb==1.0.0
    pytz==2017.2
    PyVirtualDisplay==0.2.1
    selenium==3.5.0
    six==1.10.0
    splinter==0.7.6

**Comment by lmtierney** [comment]
ping @davehunt  :)

**Comment by lmtierney** [comment]
@tkhyn care to create a PR for this change?

**Comment by 0uk** [comment]
@lmtierney done!

**Comment by krodyrobi** [comment]
Can we get this merged? As I'm hitting the same problem with a vanilla virtualenv nothing more.
```
pytest==3.2.2
pytest-selenium==1.11.1
```

**Comment by lmtierney** [comment]
The PR for this change has been merged and will be in the next release
