### ISSUE TITLE
browsermob-proxy not working with Selenium 3.5.x

### ISSUE THREAD

**Issue by SankySyS** [SeleniumHQ/selenium#4562]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.5.1, 3.5.2
Browser:  
All
Browser Version:  
FF 55, 56; Chrome 60, IE 11

## Expected Behavior -
Can open URL
## Actual Behavior -
Can't open URL
```
Caused by: org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=netReset&u=http%3A//google.com/&c=UTF-8&f=regular&d=The%20connection%20to%20the%20server%20was%20reset%20while%20the%20page%20was%20loading.
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'DL-R90G0MZM', ip: '172.19.201.143', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_141'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\leontieva\AppData\Local\Temp\rust_mozprofile.Mz5ZlFMpjaom, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=ANY, proxy=Proxy(manual, http=DL-R90G0MZM, ssl=DL-R90G0MZM), specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=56.0, platformVersion=6.1, moz:processID=6296, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: b0b9937b-bf5e-4056-b6d3-422bd8e9d234
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:368)
	at core.libs.SeleniumCore$seleniumHelper.loadURL(SeleniumCore.java:366)
	... 35 more
```
## Steps to reproduce -
1. Create proxy:
```
BrowserMobProxy proxyServer = new BrowserMobProxyServer();
proxyServer .start();
Proxy proxy = ClientUtil.createSeleniumProxy(proxyServer);
```
2. Initialize driver
```
DesiredCapabilities capabilities = DesiredCapabilities.chrome();
capabilities.setCapability(CapabilityType.PROXY, proxy);
```
3. Try to open any URL

Work as expected with selenium 3.4.x but not working with 3.5.x

**Comment by manoj9788** [comment]
Can you raise this issue in the BrowerMob Proxy project repo?

**Comment by SankySyS** [comment]
@manoj9788, done.
[#688](https://github.com/lightbody/browsermob-proxy/issues/688)

**Comment by barancev** [comment]
Also look at https://github.com/lightbody/browsermob-proxy/issues/681

**Comment by barancev** [comment]
Closing as there is nothing to be done on Selenium side.
