### ISSUE TITLE
UnsupportedCommandException: mouseMoveTo error when trying to perform new Actions(WebDriver).moveToElement(WebElement) using EventFiringWebDriver

### ISSUE THREAD

**Issue by doctordrue** [SeleniumHQ/selenium#4589]
## Meta -
OS:  
Windows 7, Windows 10
Selenium Version:  
Selenium-Java 3.5.2
IeDriverServer x32 3.5.1
GeckoDriver 0.18.0
Browser:  
Internet Explorer, Firefox 52.3.0 ESR
## Expected Behavior -
moveToElement(WebElement), moveByOffset(int, int) and moveToElement(WebElement, int, int) methods are expected to work without errors as they work when using pure drivers
## Actual Behavior -
When running on Firefox(with geckodriver initialization) or IeDriverServer exception throws (however it works fine when running on chrome or Firefox ESR with legacy initialization):
```
FAILED: moveToElementTest
org.openqa.selenium.UnsupportedCommandException: mouseMoveTo
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: '-', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:222)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:119)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteMouse.mouseMove(RemoteMouse.java:89)
	at org.openqa.selenium.support.events.internal.EventFiringMouse.mouseMove(EventFiringMouse.java:58)
	at org.openqa.selenium.interactions.MoveMouseAction.perform(MoveMouseAction.java:43)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:36)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:646)
	at com.epam.java.MouseMoveTest.moveToElementTest(MouseMoveTest.java:78)
```
## Steps to reproduce -
```
public class MouseMoveTest {
    public WebDriver driver;
    private static final String BROWSER = "ie";

    @BeforeSuite
    public void setupDriver() {
	switch (BROWSER) {
	case "chrome":
	    System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
	    ChromeOptions options = new ChromeOptions();
	    options.setExperimentalOption("excludeSwitches", Arrays.asList("ignore-certificate-errors"));
	    options.addArguments("--disable-extensions");
	    options.addArguments("disable-infobars");

	    Map<String, Object> prefs = new HashMap<String, Object>();
	    prefs.put("credentials_enable_service", false);
	    prefs.put("profile.password_manager_enabled", false);
	    options.setExperimentalOption("prefs", prefs);
	    driver = new EventFiringWebDriver(new ChromeDriver(options));
	    break;
	case "ie":
	    System.setProperty("webdriver.ie.driver", "src/main/resources/IEDriverServer.exe");
	    DesiredCapabilities ieCapabilities = DesiredCapabilities.internetExplorer();
	    ieCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,
		    false);
	    ieCapabilities.setCapability(InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, true);
	    driver = new EventFiringWebDriver(new InternetExplorerDriver(ieCapabilities));
	    break;
	case "firefox":
		System.setProperty("webdriver.gecko.driver", "src/main/resources/geckodriver.exe");
		FirefoxOptions geckoOptions = new FirefoxOptions()
		        .addPreference("log", "{level: error}")
		        .addCapabilities(new DesiredCapabilities(
		                ImmutableMap.of("pageLoadStrategy", "eager")))
		        .setLogLevel(Level.SEVERE);
	    driver = new EventFiringWebDriver(new FirefoxDriver(geckoOptions));
	    break;
	}
	driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	// driver.manage().window().maximize();
    }

    @BeforeTest
    public void goToPage() throws InterruptedException {
	driver.get("http://google.com");
    }

    @Test
    public void moveToElementTest() {
	WebElement target = driver.findElement(By.name("q"));
	Actions actions = new Actions(driver).moveToElement(target);
	actions.build().perform();
    }

    @Test
    public void moveByOffsetTest() {
	Actions actions = new Actions(driver).moveByOffset(500, 500);
	actions.build().perform();
    }

    @Test
    public void moveToElementWithOffsetTest() {
	WebElement target = driver.findElement(By.name("q"));
	Actions actions = new Actions(driver).moveToElement(target, 50, 50);
	actions.build().perform();
    }

    @AfterSuite(alwaysRun = true)
    public void closeDriver() {
	driver.quit();
    }

}
```

**Comment by doctordrue** [comment]
Looks like problem is here:
```
 @Override
    public void perform() {
      if (driver == null) {
        // One of the deprecated constructors was used. Fall back to the old way for now.
        fallBack.perform();
        return;
      }

      try {
        ((Interactive) driver).perform(sequences.values());
      } catch (ClassCastException | UnsupportedCommandException e) {
        // Fall back to the old way of doing things. Old Skool #ftw
        fallBack.perform();
      }
    }
```
due to EventFiringWebDriver instance can't be cast to Interactive

**Comment by DustinPham** [comment]
I am having the same issue, but using Node.js:

# Meta
OS:
Ubuntu 16.04 LTS

Selenium Version:
Selenium-Java 3.5.3
GeckoDriver 0.18.0

Browser:
Firefox 55.0.2

# Expected Behavior
Google is opened and then mouseMove moves the mouse 500 pixels down from the Google logo and exits.

# Actual Behavior 
```
/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

UnsupportedOperationError: mouseMoveTo
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'dustin-z440', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-93-generic', java.version: '1.8.0_144'
Driver info: driver.version: unknown
    at WebDriverError (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/error.js:27:5)
    at UnsupportedOperationError (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/error.js:327:5)
    at Object.checkLegacyResponse (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/error.js:529:15)
    at parseHttpResponse (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: mouseMove
    at thenableWebDriverProxy.schedule (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at actions.map.action (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/actions.js:124:23)
    at Array.map (native)
    at /home/dustin/selenium/test/node_modules/selenium-webdriver/lib/actions.js:123:29
    at TaskQueue.execute_ (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:3092:14)
    at TaskQueue.executeNext_ (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:3075:27)
    at asyncRun (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:2935:27)
    at /home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: ActionSequence.perform
    at ActionSequence.perform (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/actions.js:122:33)
    at Object.<anonymous> (/home/dustin/selenium/test/test2.js:28:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

# Steps to reproduce
```
var util = require('util');
var webdriver = require('selenium-webdriver'),
	By = webdriver.By,
	until = webdriver.until;

var firefox = require('selenium-webdriver/firefox');

var driver = new webdriver.Builder()
	.forBrowser('firefox')
	.usingServer('http://127.0.0.1:4444/wd/hub')
	.build();

driver.get('https://google.com');
driver.manage().window().setSize(1920, 1080);
driver.manage().window().setPosition(0, 0);

var actionDriver = new webdriver.ActionSequence(driver);

var element = driver.findElement(By.id('hplogo'));
actionDriver.mouseMove(element, {x: 0, y: -500})
		.perform();

driver.quit();
```

**Comment by barancev** [comment]
@DustinPham It's a different issue, please report is as a separate one, otherwise your comment can be lost.

**Comment by DustinPham** [comment]
@barancev Will do, thank you!

**Comment by bboycs** [comment]
Windows 8.1
Selenium Version:
Selenium-Java 3.4
IeDriverServer x32 3.5.1
Browser:
Internet Explorer

I am having the issue on UnsupportedOperationError: mouseMoveTo on IE11 when executing 
browser.actions().doubleClick(element).perform();
i am not sure whether it is related

Is this a selenium issue or IEDriverServer issue ?

Thanks

**Comment by jimevans** [comment]
@bboycs From the [CHANGELOG for the IE driver](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG):

> To successfully use this version of the IE driver, you should be using version 3.5 or above of the language bindings. Those are the only versions of language bindings that will understand the payload required to be sent during the creation of a new session. Earlier versions of the language bindings are not guaranteed to be fully compatible with this release of the IE driver.

**Comment by timrsfo** [comment]
this was happening to me. for me it was a maven pom.xml issue. I had several selenium jars individually included.  try the following 

    <properties>
      <sel-ver>3.8.1</sel-ver>
      <maven.compiler.target>1.8</maven.compiler.target>
      <maven.compiler.source>1.8</maven.compiler.source>
     </properties>

    <dependency>
       <groupId>org.seleniumhq.selenium</groupId>
       <artifactId>selenium-java</artifactId>
       <version>${sel-ver}</version>
      </dependency>
      <dependency>
       <groupId>org.seleniumhq.selenium</groupId>
       <artifactId>selenium-server</artifactId>
       <version>${sel-ver}</version>
      </dependency>
