### ISSUE TITLE
Unable to launch Edge browser when another edge instance exists

### ISSUE THREAD

**Issue by shiyaf** [SeleniumHQ/selenium#4600]
OS:  windows 10 (version : 1703, build no : 15063.540)
Selenium Version: 3.4.0
Browser: Microsoft Edge
WebDriver version : 4.15063

I am creating some automated tests on Microsoft edge browser on a web application using C# selenium.
Here i am facing an issue like i am not able to launch edge browser in my second test if the first test has failed and Edge instance of that test exists.

Below is the code i am using for launching Edge:

EdgeOptions options = new EdgeOptions();
options.PageLoadStrategy = EdgePageLoadStrategy.Eager;
Iwebdriver driver = new EdgeDriver("webdriver path", TimeSpan.FromSeconds(20));

Error message : Unexpected error. Unknown error
Stack trace : 
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 1441
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 1187
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 1114
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:line 141
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout) in c:\Projects\webdriver\dotnet\src\webdriver\Edge\EdgeDriver.cs:line 105
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(String edgeDriverDirectory, EdgeOptions options, TimeSpan commandTimeout) in c:\Projects\webdriver\dotnet\src\webdriver\Edge\EdgeDriver.cs:line 83

**Comment by barancev** [comment]
Please report the issue to Microsoft Edge bug tracker [1]

[1 ]https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

**Comment by inyrcgscgcg** [comment]
any update on this?
