### ISSUE TITLE
NoClassDefFoundError:com/google/common/base/Function

### ISSUE THREAD

**Issue by mujumalesagar** [SeleniumHQ/selenium#4627]
I am trying to start internet explorer and opening Google.com, its giving me below error,

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Function
	at sel.main(sel.java:14)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Function
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)

My Code is here:- 

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;

public class sel {

	public static void main(String[] args) {
	
		System.out.println("Internet Explorer is selected");
		System.setProperty("webdriver.ie.driver","D:\\Installables\\IEDriverServer\\IEDriverServer.exe");

			WebDriver driver = new InternetExplorerDriver();
			driver.manage().window().maximize();
			
			driver.get("http://www.google.com");
				
	}
}

**Comment by barancev** [comment]
Selenium requires guava library to be in classpath.
