### ISSUE TITLE
 UnsupportedOperationError: mouseMoveTo on Geckdriver 0.18.0 and Selenium 3.5.3

### ISSUE THREAD

**Issue by DustinPham** [SeleniumHQ/selenium#4657]
## Meta -
OS:
Ubuntu 16.04 LTS

Selenium Version:
Selenium-Java 3.5.3
GeckoDriver 0.18.0

Browser:
Firefox 55.0.2

## Expected Behavior -
Google is opened and then mouseMove moves the mouse 500 pixels down from the Google logo and exits. The same code works as expected when using `.forBrowser('chrome')` on the same OS/Selenium version, Google Chrome version 60.0.3112.113, and chromedriver version 2.32.

## Actual Behavior -
```
/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

UnsupportedOperationError: mouseMoveTo
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'dustin-z440', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-93-generic', java.version: '1.8.0_144'
Driver info: driver.version: unknown
    at WebDriverError (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/error.js:27:5)
    at UnsupportedOperationError (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/error.js:327:5)
    at Object.checkLegacyResponse (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/error.js:529:15)
    at parseHttpResponse (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: mouseMove
    at thenableWebDriverProxy.schedule (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at actions.map.action (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/actions.js:124:23)
    at Array.map (native)
    at /home/dustin/selenium/test/node_modules/selenium-webdriver/lib/actions.js:123:29
    at TaskQueue.execute_ (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:3092:14)
    at TaskQueue.executeNext_ (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:3075:27)
    at asyncRun (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:2935:27)
    at /home/dustin/selenium/test/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: ActionSequence.perform
    at ActionSequence.perform (/home/dustin/selenium/test/node_modules/selenium-webdriver/lib/actions.js:122:33)
    at Object.<anonymous> (/home/dustin/selenium/test/test2.js:18:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

## Steps to reproduce
```
var webdriver = require('selenium-webdriver'),
	By = webdriver.By,
	until = webdriver.until;

var driver = new webdriver.Builder()
	.forBrowser('firefox')
	.usingServer('http://127.0.0.1:4444/wd/hub')
	.build();

driver.get('https://google.com');
driver.manage().window().setSize(1920, 1080);
driver.manage().window().setPosition(0, 0);

var actionDriver = new webdriver.ActionSequence(driver);

var element = driver.findElement(By.id('hplogo'));
actionDriver.mouseMove(element, {x: 0, y: -500})
		.perform();

driver.quit();
```

**Comment by arjunjh10** [comment]
I got the same issue using 
 ```{
      'os': 'OS X',
      'browser': 'Firefox',
      'browser_version': '56.0 beta'
}```

on browserstack.

**Comment by lmtierney** [comment]
This is because the nodejs bindings currently do not implement the new w3c actions. See #4564
