### ISSUE TITLE
Getting UnhandledAlertException even after handling

### ISSUE THREAD

**Issue by DeepthiBalla** [SeleniumHQ/selenium#4661]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.4.0
Browser:  
Firefox 45.5.1

## Steps to reproduce -
Project i am working on needed window authentication, handled and it was working fine until last week and suddenly it started throwing the following error, any help would be really appreciated 
Cheers,
Following is the error and code

**# Error**
Test Name:	verifyLocationStatus("1 Amarina Avenue, Greenacre","OFF-NET")
Test FullName:	PricingTool.AutomationTests.Tests.PTStatusTests.verifyLocationStatus("1 Amarina Avenue, Greenacre","OFF-NET")
Test Source:	C:\Projects\QA\PricingTool.AutomationTests\Tests\PTStatusTests.cs : line 16
Test Outcome:	Failed
Test Duration:	0:00:07.112

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementById(String id)
   at OpenQA.Selenium.By.<>c__DisplayClass2.<Id>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.Click()
   at PricingTool.AutomationTests.Steps.PTSteps.click_On_BuildNewPriceList() in C:\Projects\QA\PricingTool.AutomationTests\Steps\PTSteps.cs:line 51
   at PricingTool.AutomationTests.Tests.PTStatusTests.verifyLocationStatus(String pointA_Address, String status) in C:\Projects\QA\PricingTool.AutomationTests\Tests\PTStatusTests.cs:line 18
--TearDown
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClasse.<XPath>b__c(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.Click()
   at PricingTool.AutomationTests.Steps.PTSteps.navigate_To_Dashboard() in C:\Projects\QA\PricingTool.AutomationTests\Steps\PTSteps.cs:line 580
   at PricingTool.AutomationTests.Steps.PTSteps.delete_Created_Pricelist_And_Close_Window() in C:\Projects\QA\PricingTool.AutomationTests\Steps\PTSteps.cs:line 585
   at PricingTool.AutomationTests.Tests.PTStatusTests.testTearDown() in C:\Projects\QA\PricingTool.AutomationTests\Tests\PTStatusTests.cs:line 31
Result Message:	
OpenQA.Selenium.UnhandledAlertException : 
TearDown : OpenQA.Selenium.UnhandledAlertException :

# **Code**
using System;
using System.Collections.Generic;
using System.Threading;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.PageObjects;
using OpenQA.Selenium.Support.UI;
using PricingTool.AutomationTests.PageObjects;
using OpenQA.Selenium.Remote;

namespace PricingTool.AutomationTests.Steps
{
    public class PTSteps
    {
        IWebDriver driver;

            
        HomePage homePage = new HomePage();
        ListBuilderPage listBuilderPage = new ListBuilderPage();
        List<string> serviceSpeedList = new List<string>();

        internal void login_To_NPTDirect()
        {
            driver = new FirefoxDriver();
            driver.Manage().Window.Maximize();
            driver.Url = "https://ptstaging.interactive.com.au";
             driver.SwitchTo().Alert();
               driver.SwitchTo().Alert().SendKeys("softwaretest" + Keys.Tab + "SoftTest17");
            driver.SwitchTo().Alert().SendKeys(Keys.Enter);

                 }

**Comment by barancev** [comment]
https://ptstaging.interactive.com.au is not publically available. Please provide a page to reproduce the issue on.

**Comment by DeepthiBalla** [comment]
unfortunately i don't have any page which is publically available, can you please let me know how to handle  exception in general

**Comment by barancev** [comment]
In general, you're handling it right. If it's actually an alert.
Sorry, we can't fix or even triage an issue unless we can reproduce it.
