### ISSUE TITLE
.NET Nunit Jenkins Windows Serrvice: OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:61220/session timed out after 60 seconds.

### ISSUE THREAD

**Issue by mitchellmaler** [SeleniumHQ/selenium#4691]
## Meta -
OS:  Windows Server 2016
Selenium Version:  3.5.2 .NET
Browser:  Firefox
Browser Version:  55

## Actual Behavior - Getting timeout error if running firefox tests under jenkins service.

OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:61220/session timed out after 60 seconds.
  ----> System.Net.WebException : The operation has timed out
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at (omitted class file name)
   at (omitted class file name)
--WebException
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)

I was watching task manager and I can see gecko and firefox opening but then it just gets those timeouts.

## Steps to reproduce -
Setup Jenkins Server (or slave) or any nunit runner to run nunit tests as a headless user that is not directly logged into the server or remoted in. IE Driver and ChromeDriver both work correctly but FireFoxDriver receives the above timeout errors. If I start jenkins manually though command line it works correctly and if I just run the nunit tests through the console it also works correctly.

**Comment by barancev** [comment]
Browsers are not designed to work in headless environment (unless you use special headless mode or headless browser), so inability to start is legit behavior in this case.
