### ISSUE TITLE
C# selenium 3.5.3 grid with Appium nodes configuration throws “Cannot extract a capabilities from the request error.”

### ISSUE THREAD

**Issue by kseeman** [SeleniumHQ/selenium#4758]
## Meta -
OS:  
Mac OS 10.12.6

Selenium Version:  
Selenium Standalone Server v3.5.3, Selenium.WebDriver NuGet Package v3.6.0, Appium Server v1.7.0

Browser:  
Chrome on Android, Safari on iOS

Browser Version:  
Chrome 61.0.3163.98 and Safari (whichever that comes with iOS 10.3.3)

## Expected Behavior - 
Launch app and run test

## Actual Behavior - 
Exception (from the Hub console): (I've edited out any sensitive information and replaced them with <>)

java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"desiredCapabilities":{"applicationName":"iPad","browserName":"safari","udid”:”< Device UDID >“,”automationName":"XCUITest","platformName":"ios","platformVersion":"10.3.3","xcodeOrgId”:”< XCode ID >”,”xcodeSigningId":"iPhone Developer","autoWebview":"true","app”:”< App Path >”},”capabilities":{"firstMatch":[{"applicationName":"iPad","browserName":"safari","udid":"< Device UDID >","automationName":"XCUITest","platformName":"ios","platformVersion":"10.3.3","xcodeOrgId”:”<XCode ID>”,”xcodeSigningId":"iPhone Developer","autoWebview":"true","app":"< App Path >"}]}}
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:135)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"desiredCapabilities":{"applicationName":"iPad","browserName":"safari","udid":"< Device UDID >","automationName":"XCUITest","platformName":"ios","platformVersion":"10.3.3","xcodeOrgId”:”< XCode ID >”,”xcodeSigningId":"iPhone Developer","autoWebview":"true","app”:”< App Path >”},”capabilities":{"firstMatch":[{"applicationName":"iPad","browserName":"safari","udid":"< Device UDID >","automationName":"XCUITest","platformName":"ios","platformVersion":"10.3.3","xcodeOrgId”:”< XCode ID >”,”xcodeSigningId":"iPhone Developer","autoWebview":"true","app":"< App Path >"}]}}
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:78)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.<init>(SeleniumBasedRequest.java:103)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.<init>(WebDriverRequest.java:40)
	at org.openqa.grid.web.servlet.handler.WebDriverRequestFactory.createFromRequest(WebDriverRequestFactory.java:30)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.createFromRequest(SeleniumBasedRequest.java:74)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:82)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.IllegalArgumentException: W3C payload contained keys that do not comply with the spec: [app, platformVersion, xcodeOrgId, automationName, autoWebview, udid, applicationName, xcodeSigningId]
	at org.openqa.selenium.remote.server.NewSessionPayload.validateSpecCompliance(NewSessionPayload.java:179)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.openqa.selenium.remote.server.NewSessionPayload.validate(NewSessionPayload.java:164)
	at org.openqa.selenium.remote.server.NewSessionPayload.<init>(NewSessionPayload.java:146)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:70)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.<init>(SeleniumBasedRequest.java:103)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.<init>(WebDriverRequest.java:40)
	at org.openqa.grid.web.servlet.handler.WebDriverRequestFactory.createFromRequest(WebDriverRequestFactory.java:30)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.createFromRequest(SeleniumBasedRequest.java:74)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:82)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

## Steps to reproduce -

Set up a selenium grid configuration with Appium Nodes. Run the following:

Hub: java -jar selenium-server-standalone-3.5.3.jar -role hub
Node: appium --nodeconfig /path/to/nodeconfigfile/nodeconfig.json

Example of the nodeconfig.json file:
{
  "capabilities":
      [
        { 
          "browserName": "safari",
          "version":"10.3.3",
          "maxInstances": 1,
          "platform":"ios",
          "applicationName": "iPad"
        }        
      ],
  "configuration":
  {
    "cleanUpCycle":2000,
    "timeout":30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url":"http://127.0.0.1:4740/wd/hub",
    "host": "127.0.0.1",
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "169.254.194.213"
  }
}

I’m currently using Visual Studio for Mac with the Selenium.Webdriver and Appium NuGet packages installed in the project. Then I’ll execute one of the NUnit tests with the following desired capabilities:
var cap = new DesiredCapabilities();

cap.SetCapability("applicationName", "iPad");
cap.SetCapability("browserName", "safari");
cap.SetCapability("udid", "< Device UDID >");
cap.SetCapability("automationName", "XCUITest");
cap.SetCapability("platformName", "ios");
cap.SetCapability("platformVersion", "10.3.3");
cap.SetCapability("xcodeOrgId", "< Xcode Org ID >");
cap.SetCapability("xcodeSigningId", "iPhone Developer");
cap.SetCapability("autoWebview", "true");
cap.SetCapability("app", "< App Path>");

driver = new RemoteWebDriver(new Uri("http://169.254.194.213:4444/wd/hub"), cap);

This works if I just start up a single Appium Server and hit that directly, but when I try to run it through the Selenium Grid I get this error.

**Comment by barancev** [comment]
Can you please retest with the latest Selenium version that is 3.6 at the moment?

**Comment by shs96c** [comment]
The hint is in the error message:

```
java.lang.IllegalArgumentException: W3C payload contained keys that do not comply with the spec: [app, platformVersion, xcodeOrgId, automationName, autoWebview, udid, applicationName, xcodeSigningId]
```

Looking at the code, the `DesiredCapabilities` object has been created with the no-arg constructor --- it believes it's spec compliant, that means that we hit [this code path](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L1108-L1119) when creating the new session. A casual read of this suggests that the normal capabilities are just copied directly into `firstMatch`, rather than filtering for spec compliance.

If this is a correct reading of the code (and it may not be :) ), this means that the w3c payload being sent from C# to the server contains invalid keys, leading to the result you see here.

To fix for now: do something like

```
ISpecificationCompliant specCaps = caps as ISpecificationCompliant;
specCaps.IsSpecificationCompliant = false;
```

**Comment by jimevans** [comment]
@shs96c That won't work, because the `ISpecificationCompliant` interface isn't public. The default for capabilities shouldn't be spec compliant yet. That boolean should be false by default, for now. It will be fixed soon.

**Comment by kseeman** [comment]
Thank you all for responding and helping out!

@barancev I'm still getting the same behavior with the 3.6 version.
@shs96c Are you thinking the issues I am seeing are related to the ISpecificationCompliant not being set to false by default?

**Comment by kseeman** [comment]
Is there any update on this? I'm still having the same issues.

**Comment by jimevans** [comment]
I’ve committed a fix to the source code. It hasn’t been released yet. Please do not ask for a public release date; I’m unable to give you one, for I’m unable to foresee when my schedule will permit an interim release of the .NET bindings.

**Comment by presidenten** [comment]
Did this ever get solved?
Im having the exact same problem when connecting android and ios nodes to the grid.
If solved, which version should I use?
I tried selenium 3.141.59, 3.7 and 3.6 and appium 1.12.1 and 1.8.1

The result is that the selenium client exits with error ”empty body”
