### ISSUE TITLE
Selenium.RemoteWebDriver error when mouseMoveTo on FF OS X Sierra

### ISSUE THREAD

**Issue by realfaisalk** [SeleniumHQ/selenium#4767]
# **Meta -**
OS: OS X Sierra
Selenium Version: 3.40 .NET
Browser: Firefox
Browser Version: 55.0

# Expected Behavior –
Hi, I have a script that performs a mouse move on the browser - Actions.MoveToElement(elem).Perform();
The script should move the mouse to the element without error.
This works on other configurations e.g. Firefox on Windows 10 and Chrome on OS X Sierra.
Note: For OS X I am running my scripts on BrowserStack, but as stated above the script works using Chrome on BrowserStrack.

# **Actual Behavior -**
Unknown error is thrown by Selenium.RemoteWebDriver:
```
error: mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'mac-46-249-62-100.browserstack.com', ip: 'fe80:0:0:0:1c3b:1e6:64fd:402c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_51'
Driver info: driver.version: RemoteWebDriver
An error ocurred:mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'mac-46-249-62-100.browserstack.com', ip: 'fe80:0:0:0:1c3b:1e6:64fd:402c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_51'
Driver info: driver.version: RemoteWebDriver
It was of type:NotImplementedException
```

## Stacktrace:
```
System.NotImplementedException: mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'mac-46-249-62-100.browserstack.com', ip: 'fe80:0:0:0:1c3b:1e6:64fd:402c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_51'
Driver info: driver.version: RemoteWebDriverSystem.NotImplementedException: mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'mac-46-249-62-100.browserstack.com', ip: 'fe80:0:0:0:1c3b:1e6:64fd:402c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_51'
Driver info: driver.version: RemoteWebDriver
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteMouse.MouseMove(ICoordinates where)
   at OpenQA.Selenium.Interactions.MoveMouseAction.Perform()
   at OpenQA.Selenium.Interactions.CompositeAction.Perform()
   at OpenQA.Selenium.Interactions.Actions.Perform()
   at VikingWebAutomation.StepDefinitions.CommonSteps.GivenINavigateToTheHomepage() in C:\Users\XXXX\Source\Workspaces\Automation Framework\src\02 Dev\VikingWebAutomation\StepDefinitions\CommonSteps.cs:line 58
   at lambda_method(Closure , IContextManager )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecRun.SpecFlowPlugin.Runtime.RunnerTestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at VikingWebAutomation.FeatureFiles.EnquiryBasketFeature.ScenarioCleanup()
   at VikingWebAutomation.FeatureFiles.EnquiryBasketFeature.EnquireNowPageSendYourInquiryWorks(String page_Url, String[] exampleTags) in C:\Users\XXXX\Source\Workspaces\Automation Framework\src\02 Dev\VikingWebAutomation\FeatureFiles\EnquiryBasket.feature:line 87
   at VikingWebAutomation.FeatureFiles.EnquiryBasketFeature.EnquireNowPageSendYourInquiryWorks_EnquiryEnquiry_Confirmation() in C:\Users\XXXX\Source\Workspaces\Automation Framework\src\02 Dev\VikingWebAutomation\FeatureFiles\EnquiryBasket.feature:line 79
   at TechTalk.SpecRun.Framework.TaskExecutors.StaticOrInstanceMethodExecutor.ExecuteInternal(ITestThreadExecutionContext testThreadExecutionContext)
   at TechTalk.SpecRun.Framework.TaskExecutors.StaticOrInstanceMethodExecutor.Execute(ITestThreadExecutionContext testThreadExecutionContext)
   at TechTalk.SpecRun.Framework.TestAssemblyExecutor.ExecuteTestNodeTask(TestNode testNode, ITaskExecutor task, TraceEventType eventType)

```
# Steps to reproduce –

const string Url = "http://www.google.com/";
private static IWebDriver driver;
driver = new FirefoxDriver(); 
driver.Navigate().GoToUrl(Url);
Actions move = new Actions(driver);
IWebElement btnFeelingLucky = driver.FindElement(By.XPath("//input[@name='btnI']"));
move.MoveToElement(btnFeelingLucky).Perform(); //Move mouse to button

**Comment by barancev** [comment]
Please retest with the latest Selenium version that is 3.6 at the moment.
Also, use the latest geckodriver version that is 0.19 at present.

**Comment by realfaisalk** [comment]
Sorry for the delay, but I am unable to test with the latest versions.
I can only run tests on OS X via Browserstack.com and they only support Selenium v3.5.2 and geckodriver v0.18 currently.
They will let me know when they update to the latest.

For anybody needing to know how to send capabilities as options in v3.6 then here is how to do it:

```
FirefoxOptions ffoptions = new FirefoxOptions();

            ffoptions.LogLevel = FirefoxDriverLogLevel.Trace;
            ffoptions.LogLevel = FirefoxDriverLogLevel.Default;

            ffoptions.SetLoggingPreference("Driver", LogLevel.Info);

            ffoptions.AddAdditionalCapability("browserstack.user", "USER", true); //IsGlobalCapability has to be set to true for FF
            ffoptions.AddAdditionalCapability("browserstack.key", "PASS", true);
            
            ffoptions.AddAdditionalCapability("browser", "Firefox", true);
            ffoptions.AddAdditionalCapability("browser_version", "55.0", true); 
            ffoptions.AddAdditionalCapability("os", "OS X", true);
            ffoptions.AddAdditionalCapability("os_version", "Sierra", true);
            ffoptions.AddAdditionalCapability("resolution", "1920x1080", true);

            ffoptions.AddAdditionalCapability("build", "MYBUILD", true);
            ffoptions.AddAdditionalCapability("project", "MYPROJECT", true);
            ffoptions.AddAdditionalCapability("browserstack.debug", "true", true);

            ffoptions.AddAdditionalCapability("browserstack.selenium_version", "3.5.2", true);
            ffoptions.AddAdditionalCapability("browserstack.geckodriver", "0.18.0", true); 
            

            SafariOptions sfoptions = new SafariOptions();
            sfoptions.AddAdditionalCapability("browserstack.user", "USER");
            sfoptions.AddAdditionalCapability("browserstack.key", "PASS");
            sfoptions.AddAdditionalCapability("build", "MYBUILD");
            sfoptions.AddAdditionalCapability("project", "MYPROJECT");
            sfoptions.AddAdditionalCapability("browserstack.debug", "true");
            sfoptions.AddAdditionalCapability("browser", "Safari");
            sfoptions.AddAdditionalCapability("browser_version", "10.1");
            sfoptions.AddAdditionalCapability("os", "OS X");
            sfoptions.AddAdditionalCapability("os_version", "Sierra");
            sfoptions.AddAdditionalCapability("resolution", "1920x1080");
            sfoptions.AddAdditionalCapability("browserstack.selenium_version", "3.5.2");
            sfoptions.AddAdditionalCapability("browserstack.safari.driver", "2.48");


            //driver = new SafariDriver();
            //driver = new FirefoxDriver(ffoptions);

            Uri bsUri = new Uri("http://hub-cloud.browserstack.com/wd/hub/");

            driver = new RemoteWebDriver(bsUri, ffoptions.ToCapabilities()); //or
            driver = new RemoteWebDriver(bsUri, sfoptions.ToCapabilities());
```

**Comment by barancev** [comment]
I can't reproduce the issue locally using Selenium 3.6.0 and geckodriver 0.19. so it seems to be browserstack configuration issue, they use outdated software.
