### ISSUE TITLE
Depending on Selenium 3.3.1 results in NoClassDefFound

### ISSUE THREAD

**Issue by andrewpmartinez** [SeleniumHQ/selenium#4793]
## Meta -
OS:  Windows 8, 10, Ubuntu 16.04
Selenium Version:  3.3.1
Browser:  N/A
Browser Version:  N/A

## Expected Behavior -
Version 3.3.1 continues to function.

## Actual Behavior -
Version 3.3.1 attempting to instantiate a WebDriver object, Selenium throws: java.lang.NoClassDefFoundError

## Steps to reproduce -
Use the included *.zip file as an example.
[selenium331ClassNoDefException.zip](https://github.com/SeleniumHQ/selenium/files/1349492/selenium331ClassNoDefException.zip)

1. Create a new Java project using Gradle, add this dependency:compile'org.seleniumhq.selenium:selenium-java:3.3.1'
1. Configure the project w/ the appropriate geckodriver location
1. In your main, attempt to instantiate a FirefoxDriver
1. Experience error

This started happening on September 27th when 3.6.0 was released in a project that was otherwise stable. Inspecting the dependency trees seems to indicate that even though I am attempting to use 3.3.1, a few 3.6.0 versions are being used.

Dependency tree snippet from example:
```
+--- org.seleniumhq.selenium:selenium-java:3.3.1
|    +--- org.seleniumhq.selenium:selenium-chrome-driver:3.3.1
|    |    \--- org.seleniumhq.selenium:selenium-remote-driver:3.3.1 -> 3.6.0
|    |         +--- org.seleniumhq.selenium:selenium-api:3.6.0
|    +--- org.seleniumhq.selenium:selenium-edge-driver:3.3.1
|    |    \--- org.seleniumhq.selenium:selenium-remote-driver:3.3.1 -> 3.6.0 (*)
|    +--- org.seleniumhq.selenium:selenium-firefox-driver:3.3.1
|    |    \--- org.seleniumhq.selenium:selenium-remote-driver:3.3.1 -> 3.6.0 (*)
|    +--- org.seleniumhq.selenium:selenium-ie-driver:3.3.1
|    |    \--- org.seleniumhq.selenium:selenium-remote-driver:3.3.1 -> 3.6.0 (*)
|    +--- org.seleniumhq.selenium:selenium-opera-driver:3.3.1
|    |    \--- org.seleniumhq.selenium:selenium-remote-driver:3.3.1 -> 3.6.0 (*)
|    +--- org.seleniumhq.selenium:selenium-safari-driver:3.3.1
|    |    \--- org.seleniumhq.selenium:selenium-remote-driver:3.3.1 -> 3.6.0 (*)
|    |    +--- org.seleniumhq.selenium:selenium-java:3.1.0 -> 3.3.1 (*)
|    |    \--- org.seleniumhq.selenium:selenium-remote-driver:3.1.0 -> 3.6.0 (*)
|    \--- org.seleniumhq.selenium:htmlunit-driver:2.24
|         +--- org.seleniumhq.selenium:selenium-support:[2.53.0,4.0.0) -> 3.6.0
|         |    +--- org.seleniumhq.selenium:selenium-api:3.6.0
|         |    +--- org.seleniumhq.selenium:selenium-remote-driver:3.6.0 (*)
```

Full stack trace from example project:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Application.main(Application.java:6)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.Killable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

Process finished with exit code 1
```

**Comment by barancev** [comment]
Killable interface was deprecated time ago and then deleted in version 3.6.0.

Version 3.6.0 was loaded as a transitive dependency of htmlunit-driver 2.24, that has too broad a range dependency version specification [2.53.0,4.0.0). This issue was fixed in htmlunit-driver 2.2.7 that has fixed dependency on selenium 3.4.0

**Comment by kazuki43zoo** [comment]
Hi @barancev , Is needs to use selenium 3.4.0 if use htmlunit-driver 2.27?
I've tried selenium 3.6 + htmlunit-driver 2.27. all tests are a success, however following stack trace is displayed.

```
$ ./mvnw test
...
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.692 s - in com.kazuki43zoo.jpetstore.JpetstoreApplicationTests
15:35:15.458 [Thread-4] INFO  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@6ca18a14: startup date [Fri Oct 06 15:34:57 JST 2017]; root of context hierarchy
Exception in thread "Thread-54" java.lang.NoClassDefFoundError: org/openqa/selenium/internal/Killable
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser.killBrowser(WebDriverThreadLocalContainer.java:197)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer$CloseBrowser.run(WebDriverThreadLocalContainer.java:187)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.Killable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
15:35:15.481 [Thread-4] INFO  com.zaxxer.hikari.HikariDataSource - testdb - Shutdown initiated...
15:35:15.485 [Thread-4] INFO  com.zaxxer.hikari.HikariDataSource - testdb - Shutdown completed.
...
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.366 s
[INFO] Finished at: 2017-10-06T15:35:15+09:00
[INFO] Final Memory: 58M/826M
[INFO] ------------------------------------------------------------------------
```

**Comment by barancev** [comment]
Yes, htmlunit-driver should be updated for 3.6.

**Comment by kazuki43zoo** [comment]
Thanks for your answer! Sorry, above stack track output by selenide rather than selenium.
Thanks again!!
