### ISSUE TITLE
Python method ActionChains.pause implemented incorrectly

### ISSUE THREAD

**Issue by AlexNk** [SeleniumHQ/selenium#4795]
## Meta -
OS:  Linux

Selenium Version:  3.6.0

Browser:  Firefox 

Browser Version:  55.0.2

## Expected Behavior -
ActionChains.pause to work as described in documentation.

## Steps to reproduce -

The following code
```python
from selenium import webdriver`
from selenium.webdriver import ActionChains`
from selenium.webdriver.common.keys import Keys`

driver = webdriver.Firefox()
driver.get("http://www.google.com")
elem = driver.find_element_by_name("q")
actions = ActionChains(driver)
actions.key_down(Keys.CONTROL, elem)
actions.pause(1)
actions.key_up(Keys.CONTROL, elem)
actions.perform()
driver.close()
```

generates the following error:
```python
Traceback (most recent call last):
  File "/media/work/_Down/coding/test.py", line 21, in <module>
    actions.pause(1)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/action_chains.py", line 319, in pause
    self.w3c_actions.pointer_action.pause(self, seconds)
TypeError: pause() takes from 1 to 2 positional arguments but 3 were given
```

which is likely caused by copy-paste:
````
    def pause(self, seconds):
        if self._driver.w3c:
            self.w3c_actions.pointer_action.pause(self, seconds)
            self.w3c_actions.key_action.pause(self, seconds)
        else:
            self._actions.append(lambda: self._driver.execute(
                time.sleep(seconds)
            ))
        return self
````

**Comment by lmtierney** [comment]
Fixed in 5e6b0c9, will be in the next release. Thanks for the bug report!
