### ISSUE TITLE
unknown exception when taking screenshot with chrome

### ISSUE THREAD

**Issue by epiehl** [SeleniumHQ/selenium#482]
I am trying to generate screenshots with webdriver.chrome.
After opening the link, i get the following error.

The full traceback:

Traceback (most recent call last):
  File "/Users/epiehl/Documents/Python Projects/screenshot_tool/app/main.py", line 10, in <module>
    screen.doSUS()
  File "/Users/epiehl/Documents/Python Projects/screenshot_tool/app/src/ScreenshotTool.py", line 90, in doSUS
    controller.takeScreenshot(fullname)
  File "/Users/epiehl/Documents/Python Projects/screenshot_tool/app/src/BrowserController.py", line 66, in takeScreenshot
    self.save_screenshot(fullname)
  File "/Users/epiehl/Documents/Python Projects/screenshot_tool/env/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 698, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/Users/epiehl/Documents/Python Projects/screenshot_tool/env/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 717, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/Users/epiehl/Documents/Python Projects/screenshot_tool/env/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 727, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/Users/epiehl/Documents/Python Projects/screenshot_tool/env/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 175, in execute
    self.error_handler.check_response(response)
  File "/Users/epiehl/Documents/Python Projects/screenshot_tool/env/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot take screenshot
from unknown error: Failed to capture tab: unknown error
JavaScript stack:
Error: Failed to capture tab: unknown error
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:37:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:73:7)
  (Session info: chrome=42.0.2311.90)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.3 x86_64)

I am using the save_screenshot method. This works fine with firefox but not with chrome. I am using a virtualenv.

**Comment by sevaseva** [comment]
https://code.google.com/p/chromedriver/issues/list is the appropriate place to report bugs in chromedriver. https://code.google.com/p/chromedriver/issues/detail?id=1083 is the same bug filed there. It would be helpful if you provide a *reproducible* steps/code in that bug.

**Comment by frmsaul** [comment]
Im having the same problems:

When I run this code:
[CODE](https://gist.github.com/frmsaul/5acf493bfef548a68272cf37346aab8c)

I get this error:
`Traceback (most recent call last):
  File "test_browser_capture.py", line 17, in <module>
    image.screenshot("Google.png");
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 446, in screenshot
    png = self.screenshot_as_png
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 433, in screenshot_as_png
    return base64.b64decode(self.screenshot_as_base64.encode('ascii'))
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 423, in screenshot_as_base64
    return self._execute(Command.ELEMENT_SCREENSHOT)['value']
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: GET /session/6fb0929a-fa17-d342-be72-34250d66dd3c/screenshot/ecc4ff0c-fed2-934f-8d7c-58cf476d666a did not match a known command`

Any idea what might be the cause and where I should look for a solution?
Im using MacOS El Capitan.
