### ISSUE TITLE
Gettinng error while trying to use driver.quit()

### ISSUE THREAD

**Issue by raghu-kunda** [SeleniumHQ/selenium#4853]
OS:  

Selenium Version:  

Browser:  

Browser Version:  

Gecko Driver version:

## Expected Behavior -
Should not throw any error after executing the test

## Actual Behavior -
Throwing below error : 

1507806007416	geckodriver	INFO	geckodriver 0.18.0
1507806007459	geckodriver	INFO	Listening on 127.0.0.1:5154
1507806007965	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1507806013967	Marionette	INFO	Listening on port 51172
Oct 12, 2017 4:30:18 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Oct 12, 2017 4:30:44 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
Exception in thread "main" org.openqa.selenium.WebDriverException: quit
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'LH7U0CNU324C0PF', ip: '10.196.11.25', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\rb5\AppData\Local\Temp\rust_mozprofile.4RcPizHY8da0, rotatable=false, timeouts={implicit=0.0, page load=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.2.1, platformVersion=6.1, moz:processID=10288.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 6f4734c9-ff4b-4f57-9e1c-62afeb3d116c
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:533)
	at com.pluralsight.WebDriverDemo.main(WebDriverDemo.java:11)

**Comment by tuhinmitra888** [comment]
Hi,

Please provide the following details, it helps in solving the issue -
OS:

Selenium Version:

Browser:

Browser Version:

Gecko Driver version:

P.S: As an alternate solution, you can try - driver.dispose()

**Comment by barancev** [comment]
From the log I see you are using geckodriver 0.18.0 and Firefox 52.2.1. Please upgrade driver to 0.19 and browser to 55+
