### ISSUE TITLE
Protractor tests stopped working after recent update of selenium+chrome

### ISSUE THREAD

**Issue by Jag-MW** [SeleniumHQ/selenium#4866]
## Meta -
OS:  Mac OS X' os.version: 10.12.6

Selenium Version:  
3.6.0
Browser:  
Chrome  61.0.3163.100
Node 7.5
java.version: '1.8.0_144'
Scenario:
All of sudden from October 5th after latest chrome driver and selenium are updated, I cannot run the tests as driver server cannot start, nothing seems to help me.

Browser Version:  
Chrome  61.0.3163.100

## Expected Behavior -
tests should just run
## Actual Behavior -
Tests do not run this is what I see in the console
```
node:22587) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[15:20:14] I/launcher - Running 1 instances of WebDriver
[15:20:14] I/local - Starting selenium standalone server...
[15:20:15] I/local - Selenium standalone server started at http://10.4.8.202:55567/wd/hub
[15:20:35] E/launcher - Timed out waiting for driver server to start.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: '*****.local', ip: 'fe80:0:0:0:93:890d:affc:6e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: unknown
[15:20:35] E/launcher - WebDriverError: Timed out waiting for driver server to start.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: '*****.local', ip: 'fe80:0:0:0:93:890d:affc:6e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:623:16)
    at Local.getNewDriver (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/*****/.nvm/versions/node/v7.5.0/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[15:20:35] E/launcher - Process exited with error code 199
```

## Steps to reproduce -
Not sure if it can be easily reproducible, but none of my tests work, so I tried to run with no dependencies and with a simple example, but no luck, not sure if I have some corrupted binaries.

```
// spec.js
describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');

    expect(browser.getTitle()).toEqual('Super Calculator');
  });
});

// conf.js
exports.config = {
  framework: 'jasmine',
  browserName: 'chrome',
  specs: ['spec.js']
}
```

**Comment by lmtierney** [comment]
Can you provide a reproducible script with just selenium and not protractor?

**Comment by Jag-MW** [comment]
Sorry, it was a configuration change on my system which caused this, to be more precise my /etc/hosts did not have localhost which was changed for a different test and never changed back and totally forgot about it. I am closing the issue, once again very sorry!
