### ISSUE TITLE
 WebDriverError: java.net.BindException: Address already in use: connect

### ISSUE THREAD

**Issue by dmitrynovik** [SeleniumHQ/selenium#4877]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.5.0
Browser:  
Google Chrome 61

IT WOULD BE GREAT IF THE EXCEPTION HAD AT LEAST THE PORT NUMBER WHICH IT ATTEMPTS TO BIND TO. THIS WOULD ELIMINATE THE GUESSWORK. THE 'ADDRESS ALREADY IN USE' WITHOUT DETAILS 'WHICH ADDRESS' IS BY ITSELF A TERRIBLE TERRIBLE EXAMPLE OF AN ERROR MESSAGE

---
     WebDriverError: java.net.BindException: Address already in use: connect
      at WebDriverError (node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
      at Object.checkLegacyResponse (node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:639:15)
      at parseHttpResponse (node_modules\protractor\node_modules\selenium-webdriver\http\index.js:538:13)
      at client_.send.then.response (node_modules\protractor\node_modules\selenium-webdriver\http\index.js:472:11)
      at ManagedPromise.invokeCallback_ (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
      at TaskQueue.execute_ (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
      at asyncRun (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2820:25)
      at node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: WebDriver.findElements(By(css selector, [data-automation="signin-button"]))
      at WebDriver.schedule (node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:377:17)
      at WebDriver.findElements (node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:926:22)
      at node_modules\protractor\built\element.js:173:44
      at ManagedPromise.invokeCallback_ (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
      at TaskQueue.execute_ (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
      at asyncRun (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2775:27)
      at node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:109:7)Error
      at ElementArrayFinder.applyAction_ (node_modules\protractor\built\element.js:461:27)
      at ElementArrayFinder._this.(anonymous function) [as click] (node_modules\protractor\built\element.js:103:30)
      at ElementFinder.(anonymous function) [as click] (node_modules\protractor\built\element.js:829:22)
      at SignInPage.signIn (C:/code/lanternpay/aces.apps/Aces.Apps/Aces.Apps.UI.Tests/specs/providers-app/page-objects/signin.page.js:11:22)
      at Context.<anonymous> (C:/code/lanternpay/aces.apps/Aces.Apps/Aces.Apps.UI.Tests/specs/providers-app/step-definitions/sign-in.steps.js:23:20)
      at node_modules\protractor\node_modules\selenium-webdriver\testing\index.js:144:19
      at new ManagedPromise (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1082:7)
      at controlFlowExecute (node_modules\protractor\node_modules\selenium-webdriver\testing\index.js:129:14)
      at TaskQueue.execute_ (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)

**Comment by p0deje** [comment]
It would be great indeed, pull requests are welcome!
