### ISSUE TITLE
 E/launcher - SessionNotCreatedError: Unable to create new service: GeckoDriverService Build info: version: '3.6.0'

### ISSUE THREAD

**Issue by piotro83** [SeleniumHQ/selenium#4889]
OS:   Windows 10 Home 
Selenium Version:   selenium-server-standalone-3.6.0
Browser:  FF 56.0 (32 bity
Geckodriver :geckodriver-v0.19.0
on chrome everything works ok

config.capabilities = {
  browserName: "firefox",
}

`Running "protractor:dev-firefox" (protractor) task
[15:07:27] I/launcher - Running 1 instances of WebDriver
[15:07:27] I/local - Starting selenium standalone server...
[15:07:28] I/local - Selenium standalone server started at http://192.168.1.9:61806/wd/hub
[15:07:28] E/launcher - Unable to create new service: GeckoDriverService
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'DL', ip: '192.168.1.9', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_141'
Driver info: driver.version: unknown
[15:07:28] E/launcher - SessionNotCreatedError: Unable to create new service: GeckoDriverService
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'DL', ip: '192.168.1.9', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_141'
Driver info: driver.version: unknown
    at WebDriverError (C:\local\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
    at SessionNotCreatedError (C:\local\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:214:5)
    at Object.checkLegacyResponse (C:\local\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\local\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\local\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\local\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (C:\local\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:640:55)
    at createDriver (C:\local\node_modules\protractor\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (C:\local\node_modules\protractor\node_modules\selenium-webdriver\index.js:629:16)
    at Local.getNewDriver (C:\local\node_modules\protractor\lib\driverProviders\driverProvider.ts:60:29)
    at Runner.createBrowser (C:\local\node_modules\protractor\lib\runner.ts:225:39)
    at q.then.then (C:\local\node_modules\protractor\lib\runner.ts:391:27)
    at _fulfilled (C:\local\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\local\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\local\node_modules\q\q.js:796:13)
    at C:\local\node_modules\q\q.js:604:44
    at runSingle (C:\local\node_modules\q\q.js:137:13)
    at flush (C:\local\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[15:07:28] E/launcher - Process exited with error code 199`

**Comment by barancev** [comment]
Please report this issue to Protractor tracker.
