### ISSUE TITLE
WebDriverError: disconnected: unable to connect to renderer

### ISSUE THREAD

**Issue by gkatsanos** [SeleniumHQ/selenium#4897]
## Meta -
OS:  OSX 10.12.6 (16G29)
Selenium Version: 
```bash 
~./node_modules/chromedriver/bin/chromedriver  -v
ChromeDriver 2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061)

~ $ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.7/Contents/Home

~ $ node -v
v6.11.2
```
Browser:  
Chrome Version 62.0.3202.62 (Official Build) (64-bit)

Browser Version:  
62.0.3202.62 (Official Build) (64-bit)

## Expected Behavior -
A Chrome session should start and the script should execute till the end
## Actual Behavior -
The browser is started but the script immedialy crashes.
```

> ucb-client@2.97.3 selenium-local /Users/Georgios/Development/rocket-internet/ucb-client
> node test/automation-tests/testcases/happy-path/Local_Guest_Cash.js

/Users/Georgios/Development/rocket-internet/ucb-client/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

WebDriverError: disconnected: unable to connect to renderer
  (Session info: chrome=62.0.3202.62)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.6 x86_64)
    at WebDriverError (/Users/Georgios/Development/rocket-internet/ucb-client/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/Users/Georgios/Development/rocket-internet/ucb-client/node_modules/selenium-webdriver/lib/error.js:529:15)
    at parseHttpResponse (/Users/Georgios/Development/rocket-internet/ucb-client/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/Georgios/Development/rocket-internet/ucb-client/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.manage().window().setSize(1280, 720)
    at thenableWebDriverProxy.schedule (/Users/Georgios/Development/rocket-internet/ucb-client/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Window.setSize (/Users/Georgios/Development/rocket-internet/ucb-client/node_modules/selenium-webdriver/lib/webdriver.js:1677:25)
    at Object.<anonymous> (/Users/Georgios/Development/rocket-internet/ucb-client/test/automation-tests/testcases/happy-path/Local_Guest_Cash.js:8:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```

## Actual script (beginning)
```js
require('chromedriver');
var webdriver = require('selenium-webdriver'),
By = webdriver.By,
until = webdriver.until;
var driver = new webdriver.Builder().forBrowser('chrome').build();
var timeout = 15000;
```

**Comment by barancev** [comment]
1) Latest chromedriver is 2.33 at the moment, try to upgrade.
2) chromedriver issues should be reported to https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by Aratthod1530** [comment]
WebDriverException: Message: disconnected: unable to connect to renderer
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.11.6 x86_64)

Getting same error.
upgraded chrome driver too, still getting same error.

**Comment by goknurbati** [comment]
Hi everybody,
I upgrated the version of the chromedriver but I continue the get the error that "org.openqa.selenium.WebDriverException: disconnected: unable to connect to renderer". When I upgrade the version of the chromedriver, I changed the version of chromedriver in pom.xml. IS it correct or not. What else I can upgrade it. 

Thanks for your assistances...

**Comment by kulavardan** [comment]
1. Upgrade chrome driver
2. Remove window size set keywords if you are using any

**Comment by DavidLeez** [comment]
I using: 
- selenium version: 3.10 
- chrome driver: 2.36 
- chrome version: 64 
- jre: 1.8 

and facing this issue. The more information, when I using external connection, it work well. But when I using internal connection, it crash and show message: 
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=64.0.3282.186)

**Comment by Prabhatjee10** [comment]
plz try aftr removing "driver.manage().window().maximize()"

**Comment by Jaysheel** [comment]
@DavidLeez, in your console , it says 2.35 though you have mentioned using 2.36

**Comment by skptricks** [comment]
It causes because page took long time to load , you need add additional line to your chromedriver option. Please refer the below link for more information : 
[Timed out receiving message from renderer in selenium](https://www.skptricks.com/2018/08/timed-out-receiving-message-from-renderer-selenium.html)

**Comment by rnagabandi** [comment]
am getting below error , can anyone please help?

org.openqa.selenium.SessionNotCreatedException: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=71.0.3578.33 (269aa0e3f0db08097f0fe231c7e6be200b6939f7),platform=Mac OS X 10.13.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.60 seconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'MyMacPro', ip: 'fe80:0:0:0:10c3:c79c:7347:14ef%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '10.0.1'
Driver info: driver.version: ChromeDriver
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
