### ISSUE TITLE
Unable to emulate captureEntirePageScreenshot on html-runner-3.6.0

### ISSUE THREAD

**Issue by jeirgino** [SeleniumHQ/selenium#4911]
## Meta -
OS:  Windows 8.1

Selenium Version:  selenium-html-runner-3.6.0.jar

Browser:  chrome 61.0 and firefox 53.0.3

## Expected Behavior - 
Hi, I want to perform a screenshot from selenium-html-runner-3.6.0.jar

## Actual Behavior -
Actually it's work fine with selenium IDE 2.9.1  
captureEntirePageScreenshot | C:\Users\jeirgino\Documents\myscreenshot.jpg |  |

but with html runner, I got this error:

oct. 19, 2017 3:20:50 PM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFOS: |captureEntirePageScreenshot | C:\Users\jeirgino\Documents\myscreenshot.jpg |  |
2017-10-19 15:20:50.045:INFO:osjs.AbstractConnector:main: Stopped ServerConnector@1506f20f{HTTP/1.1,[http/1.1]}{0.0.0.0:6804}
2017-10-19 15:20:50.049:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@7f6f61c8{/tests,null,UNAVAILABLE}
1508419250063   Marionette      INFO    New connections will no longer be accepted
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.openqa.selenium.os.ProcessUtils (file:/C:/Users/jeirgino/Desktop/Edito/selenium-html-runner-3.6.0.jar) to field java.lang.ProcessImpl.handle
WARNING: Please consider reporting this to the maintainers of org.openqa.selenium.os.ProcessUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
oct. 19, 2017 3:20:51 PM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
AVERTISSEMENT: Test of browser failed: *firefox
org.openqa.selenium.server.htmlrunner.CoreRunnerError: Unable to emulate captureEntirePageScreenshot [C:\Users\jeirgino\Documents\myscreenshot.jpg, ]
        at org.openqa.selenium.server.htmlrunner.ReflectivelyDiscoveredSteps.invokeMethod(ReflectivelyDiscoveredSteps.java:323)
        at org.openqa.selenium.server.htmlrunner.ReflectivelyDiscoveredSteps.lambda$null$1(ReflectivelyDiscoveredSteps.java:74)
        at org.openqa.selenium.server.htmlrunner.CoreTestCase$LoggableStep.execute(CoreTestCase.java:170)
        at org.openqa.selenium.server.htmlrunner.NextStepDecorator.evaluate(NextStepDecorator.java:46)
        at org.openqa.selenium.server.htmlrunner.CoreTestCase.run(CoreTestCase.java:71)
        at org.openqa.selenium.server.htmlrunner.CoreTestSuite.run(CoreTestSuite.java:73)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:118)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)

## Steps to reproduce -
java -jar selenium-html-runner-3.6.0.jar -htmlSuite *firefox http://myurl.com testSuite.html log.html -timeout 15

Anyone can help me please ?

**Comment by barancev** [comment]
Legacy Selenium IDE is deprecated. See https://github.com/SeleniumHQ/selenium-ide for the new version
