### ISSUE TITLE
how to catch ENETUNREACH error when network disconnect

### ISSUE THREAD

**Issue by jokyme** [SeleniumHQ/selenium#4921]
OS:  Windows10
Selenium Version:  3.6.0
Browser:  PhantomJS
Browser Version:  2.1.1

selenium throw an error when  the network disconnect,
how to catch this error?
```
Error: ENETUNREACH connect ENETUNREACH 10.211.55.9:60706
    at ClientRequest.<anonymous> (c:\spider\node_modules\selenium-webdriver\http\index.js:238:15)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From: Task: WebDriver.navigate().to(https://www.baidu.com)
    at thenableWebDriverProxy.schedule (c:\spider\node_modules\selenium-webdriver\lib\webdriver.js:807:17)

```

**Comment by jokyme** [comment]
i got it.
