### ISSUE TITLE
Issue with chrome driver

### ISSUE THREAD

**Issue by Gokulsathyan12** [SeleniumHQ/selenium#4924]
I am totally new to selenium and java. I tried a code to open a webpage using selenium and its showing the following error

java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:754)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:329)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at selenium.webdriver.test.SeleniumTest.invokeBrowser(SeleniumTest.java:14)
	at selenium.webdriver.test.SeleniumTest.main(SeleniumTest.java:40)
**-----------------------------------------------------------------------------------------------------------------**

**my code snippet is**

package selenium.webdriver.test;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class SeleniumTest {
	WebDriver driver;
	public void invokeBrowser() {
		try {
			
			
			WebDriver driver=new ChromeDriver();
			System.setProperty(" webdriver.chrome.driver", "E:\\chromedriver.exe");
			
			driver.manage().window().maximize();
			driver.manage().deleteAllCookies();
			driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
			driver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);
			getUrl();
		} catch (Exception e) {
			
			e.printStackTrace();
		}
	}
		
		public void getUrl() {
			try {
				driver.get("https://www.amazon.in");
				driver.findElement(By.linkText("nav-your-amazon")).click();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
	public static void main(String args[]) {
		SeleniumTest obj = new SeleniumTest();
		obj.invokeBrowser();
	}

}

please help.. Thank you

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
