### ISSUE TITLE
NodeJS#When I use selenium-webdriver new Builder() driver with setProxy, but return error Uncaught WebDriverError: unknown error: cannot parse capability: proxy from unknown error: proxyType is 'manual' but no manual proxy capabilities were found

### ISSUE THREAD

**Issue by wenJanus** [SeleniumHQ/selenium#4926]
## Meta -
OS:  Windows 7

Selenium Version:  
" types/selenium-webdriver": "^3.0.4",
"selenium-webdriver": - "^3.4.0",

Browser:  

Browser Version:  

Version 62.0.3202.62 (Official Build) (64-bit)

## Actual Behavior -
 1) Submit ideas Test Case #1: Unauthenticated cannot submit ideas:
     Uncaught WebDriverError: unknown error: cannot parse capability: proxy
from unknown error: proxyType is 'manual' but no manual proxy capabilities were found
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)
      at WebDriverError (node_modules\selenium-webdriver\lib\error.js:27:5)
      at Object.checkLegacyResponse (node_modules\selenium-webdriver\lib\error.js:517:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:509:13)
      at doSend.then.response (node_modules\selenium-webdriver\lib\http.js:441:30)
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: WebDriver.createSession()
      at Function.createSession (node_modules\selenium-webdriver\lib\webdriver.js:777:24)
      at Function.createSession (node_modules\selenium-webdriver\chrome.js:719:29)
      at createDriver (node_modules\selenium-webdriver\index.js:167:33)
      at Builder.build (node_modules\selenium-webdriver\index.js:639:16)
      at new Browser (dist\lib\browser.js:24:14)
      at Object.<anonymous> (dist\tests\test.js:16:38)
      at next (native)
      at dist\tests\test.js:7:71
      at __awaiter (dist\tests\test.js:3:12)
      at Context.before (dist\tests\test.js:15:18)

## Steps to reproduce -

import { Builder, Capabilities, ProxyConfig, ThenableWebDriver, WebElement, By, WebElementPromise } from 'selenium-webdriver';

  public constructor(private browserName: string) {  
    let proxy = require('selenium-webdriver/proxy');
    this.driver = new Builder()
      .forBrowser(browserName)
      .setProxy(proxy.manual({ 
        http : null,
        https : null,
        shocks : 'ecnshts3016.sh.cn.ao.se:8081'
        }))
      .build();
  }

**Comment by jimevans** [comment]
I don’t know the JavaScript language bindings well, but surely `shocks` isn’t a valid property name for the Proxy settings? Perhaps you meant `socks`?

**Comment by wenJanus** [comment]
@jimevans  Yes. I fix to 'socks' still throw this error.

 Uncaught WebDriverError: unknown error: cannot parse capability: proxy
from unknown error: proxyType is 'manual' but no manual proxy capabilities were found

**Comment by jleyba** [comment]
This is a bug in the chromedriver - that error gets returned if you do not specify a value for the http proxy with manual settings. Please file a bug against the [chromedriver project](https://sites.google.com/a/chromium.org/chromedriver/help).

**Comment by Bethannfrum** [comment]
Fix and restore to the original format and release old documents
