### ISSUE TITLE
Chrome driver crashes if you select Chrome window during maximizing/launching

### ISSUE THREAD

**Issue by jiteshsojitra** [SeleniumHQ/selenium#4953]
Chrome driver crashes if you select Chrome window during maximizing/launching

OS: Windows
Chrome driver version: 2.33

Steps:
1. Write code to launch browser with webDriver.manage().window().maximize();
2. Run the tests
3. When it launches browser, just click to browser immediately and move focus outside

It crashes and terminates execution with below error.

# Code:

	preferences.put("plugins.plugins_disabled", new String[] { "Adobe Flash Player", "Chrome PDF Viewer" });
	preferences.put("credentials_enable_service", false);
	preferences.put("password_manager_enabled", false);
	options.setExperimentalOption("prefs", preferences);
	options.addArguments("disable-infobars");

    System.setProperty("webdriver.chrome.driver", driverFilePath);
    options.setCapability("chrome.switches", Arrays.asList("--disable-extensions"));
    options.setCapability(ChromeOptions.CAPABILITY, options);
    options.setCapability(CapabilityType.LOGGING_PREFS, logs);
    webDriver = new ChromeDriver(options);
    webDriver.manage().window().maximize();

# Log:
```
host: 'PNQ-JSOJITRA', ip: '172.16.13.11', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_141'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=XP, acceptSslCerts=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, platformName=XP, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f), userDataDir=C:\Users\JITESH~1.SOJ\AppData\Local\Temp\scoped_dir3748_26415}, takesHeapSnapshot=true, pageLoadStrategy=normal, unhandledPromptBehavior=, databaseEnabled=false, handlesAlerts=true, version=62.0.3202.62, browserConnectionEnabled=false, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: 84cf8d8897a4812f8910b468f78c21e7
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:643)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:877)
```

**Comment by hazmeister** [comment]
Sounds like a Chrome / Chromedriver issue- could you log the same issue here?
https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by barancev** [comment]
Yes, if the browser or chromedriver executable crashes the issue should be reported to chromedriver tracker.

**Comment by makmakindia** [comment]
my scripts failed with same error, let us know if any solution please
