### ISSUE TITLE
Selenium 3.6.0 with gecko 0.19 and FF version 56 is not working with Desired  capabilities 

### ISSUE THREAD

**Issue by Smith191** [SeleniumHQ/selenium#4962]
OS:
Windows 8.1
Selenium Version:
3.6
Browser:
Firefox version 56.0.1

We are trying to run  Selenium Grid via selenium 3.6 jar file using geckodriver version 0.19 on firefox 56 but the browser is getting open but desired URL is not opening 

Steps to reproduce -
public class Grid
 {

	public static void main(String[] args) throws MalformedURLException 
{
		
		System.setProperty("webdriver.gecko.driver", "path of geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		
		DesiredCapabilities cap = DesiredCapabilities.firefox();
		cap.setBrowserName("firefox");
		cap.setPlatform(Platform.WIN8_1);
		
String nodeUrl = "http://localhost: 4444/wd/hub";
			driver = new RemoteWebDriver(new URL(nodeUrl),cap);
			 driver.get("http://www.google.com");
		  
	  }
	
	}

Browser Version:
56.0(32 bit)
Expected Behavior -

driver.get() should redirect to the URL(google)entered

Actual Behavior -
Browser is getting opened with blank URL and we are getting Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new service: ChromeDriverService
![desiredcapabilites](https://user-images.githubusercontent.com/33118230/32044681-d692c522-ba5b-11e7-9aff-dc14b30fb6f0.jpg)
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'

Note:
I have run hub by using below command
java -jar selenium-server-standalone-3.6.0.jar -role hub

2. I have run grid by using below command 
java -jar selenium-server-standalone-3.6.0.jar -role node  -hub http://localhost:4444/grid/register -port 5566

**Comment by Frankstar** [comment]
is `System.setProperty("webdriver.gecko.driver", "path of geckodriver.exe");` a typo or is it like this in your actually code ??

also do you have a stack trace ?

**Comment by Smith191** [comment]
Source Code:

System.setProperty("webdriver.gecko.driver", "D:\\Selenium_Latest\\geckodriver-v0.19.0-win64\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		
		DesiredCapabilities cap = DesiredCapabilities.firefox();
		cap.setBrowserName("firefox");
		cap.setPlatform(Platform.WIN8_1);
		
		// TODO Auto-generated method stub
		String	baseUrl= "http://www.google.com";
		String nodeUrl = "http://192.168.2.3:4444/wd/hub";
		
		
		 
			driver = new RemoteWebDriver(new URL(nodeUrl),cap);
		
			 driver.get("http://www.google.com");
		  
	  }
	
	}

**Comment by Smith191** [comment]
Stack Trace:
1509009751950	geckodriver	INFO	geckodriver 0.19.0
1509009751959	geckodriver	INFO	Listening on 127.0.0.1:22537
1509009752678	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\Abhaypc\\AppData\\Local\\Temp\\rust_mozprofile.gyowsKXp9hea"
1509009753876	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1509009754926	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\Abhaypc\AppData\Local\openvr\openvrpaths.vrpath
[Child 11400] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 11400] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1509009763396	Marionette	INFO	Listening on port 8869
1509009764358	Marionette	WARN	TLS certificate errors will be ignored for this session
1509009765265	Marionette	DEBUG	Register listener.js for window 4294967297
Oct 26, 2017 2:52:45 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new service: GeckoDriverService
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'SMITA', ip: '192.168.2.3', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_101'
Driver info: driver.version: unknown
Command duration or timeout: 31 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at Grid.main(Grid.java:28)
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create new service: GeckoDriverService
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'SMITA', ip: '192.168.2.3', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_101'
Driver info: driver.version: unknown
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'SMITA', ip: '192.168.2.3', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_101'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.ServicedSession$Factory.lambda$new$0(ServicedSession.java:163)
	at org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:173)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$createSession$16(ActiveSessionFactory.java:171)
	at java.util.Optional.map(Unknown Source)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.createSession(ActiveSessionFactory.java:171)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:72)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:232)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by hazmeister** [comment]
@Smith191 I think I see the problem here.  

        System.setProperty("webdriver.gecko.driver", "D:\Selenium_Latest\geckodriver-v0.19.0-win64\geckodriver.exe");

In Java, backslashes escape the following character, making your path to geckodriver `D:\elenium_Latest\eckodriver-v0.19.0-win64\eckodriver.exe` which as you can guess can't be found and is present in the stack trace you shared.  For windows paths on  java, you should either:
* Use forward slashes (which java will convert to back slashes when running on windows)
        System.setProperty("webdriver.gecko.driver", "D:/Selenium_Latest/geckodriver-v0.19.0-win64/geckodriver.exe");
* Escape each backslash with a second backslash.
        System.setProperty("webdriver.gecko.driver", "D:\\Selenium_Latest\\geckodriver-v0.19.0-win64\\geckodriver.exe");

**Comment by barancev** [comment]
Please provide the log from the console of a node that actually starts the browser.

**Comment by Smith191** [comment]
Hi,

I have used double backslash but giving me following Stack trace

-------------------------------------------------------------------------
1509118289543	geckodriver	INFO	geckodriver 0.19.0
1509118289557	geckodriver	INFO	Listening on 127.0.0.1:36027
1509118290260	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\Abhaypc\\AppData\\Local\\Temp\\rust_mozprofile.EeIygErjrPW2"
1509118290559	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1509118292693	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\Abhaypc\AppData\Local\openvr\openvrpaths.vrpath
[Child 220] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 220] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1509118300324	Marionette	INFO	Listening on port 4042
1509118300692	Marionette	WARN	TLS certificate errors will be ignored for this session
1509118300737	Marionette	DEBUG	Register listener.js for window 4294967297
Oct 27, 2017 9:01:40 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new service: GeckoDriverService
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'SMITA', ip: '192.168.1.2', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_101'
Driver info: driver.version: unknown
Command duration or timeout: 45 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at Grid.main(Grid.java:29)
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create new service: GeckoDriverService
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'SMITA', ip: '192.168.1.2', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_101'
Driver info: driver.version: unknown
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'SMITA', ip: '192.168.1.2', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_101'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.ServicedSession$Factory.lambda$new$0(ServicedSession.java:163)
	at org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:173)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$createSession$16(ActiveSessionFactory.java:171)
	at java.util.Optional.map(Unknown Source)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.createSession(ActiveSessionFactory.java:171)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:72)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:232)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by barancev** [comment]
The log you pasted here was generated by the line of the code
```
WebDriver driver = new FirefoxDriver();
```
and it works well.

The exception was thrown by another line of the code:
```
driver = new RemoteWebDriver(new URL(nodeUrl),cap);
```
So please go the machine where you run a grid node and find the log there.

**Comment by barancev** [comment]
Please provide the node logs for analysis.

**Comment by Smith191** [comment]
issue closed
