### ISSUE TITLE
Incomplete error stack when disabling the WebDriverJS promise manager (USE_PROMISE_MANAGER=false)

### ISSUE THREAD

**Issue by doberkofler** [SeleniumHQ/selenium#4982]
## Meta -
OS:  Windows 7
Selenium Version:  3.6.0
Browser:  Chrome
Browser Version:  62.0.3202.75 (Official Build) (64-bit)

## Expected Behavior -
(The examples are based on the new possibility to disable the WebDriverJS promise manager as described in https://github.com/SeleniumHQ/selenium/issues/2969)

When running with the promise manager and a promise gets rejected a complete error stack including the actual code line that caused the problem is shown as expected:

```cmd
D:\promise-manager>npm run test-promise

> example@0.0.0 test-promise D:\promise-manager
> mocha test/promise.js

  selenium-webdriver using promise manager
    √ works as expected

DevTools listening on ws://127.0.0.1:12879/devtools/browser/bb9b92f9-d19e-409a-843e-4f12e6071870
    1) shows the error stack when failing
[1030/213645.004:ERROR:angle_platform_impl.cc(46)] rx::SwapChain11::present(925): Present failed: the D3D11 device was removed, HRESULT: 0x887A0020
[1030/213645.006:ERROR:gles2_cmd_decoder.cc(15905)] Context lost because SwapBuffers failed.
[1030/213645.008:ERROR:gles2_cmd_decoder.cc(16248)] Onscreen context lost via ARB/EXT_robustness. Reset status = GL_UNKNOWN_CONTEXT_RESET_KHR


  1 passing (5s)
  1 failing

  1) selenium-webdriver using promise manager
       shows the error stack when failing:
     NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[name="thisdoesnotexist"]"}
  (Session info: chrome=62.0.3202.75)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)
      at Object.checkLegacyResponse (D:\promise-manager\node_modules\selenium-webdriver\lib\error.js:546:15)
      at parseHttpResponse (D:\promise-manager\node_modules\selenium-webdriver\lib\http.js:509:13)
      at doSend.then.response (D:\promise-manager\node_modules\selenium-webdriver\lib\http.js:441:30)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: WebDriver.findElement(By(css selector, *[name="thisdoesnotexist"]))
      at thenableWebDriverProxy.schedule (D:\promise-manager\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
      at thenableWebDriverProxy.findElement (D:\promise-manager\node_modules\selenium-webdriver\lib\webdriver.js:1014:17)
      at Context.it (D:\promise-manager\test\promise.js:26:10)
      at callFnAsync (D:\promise-manager\node_modules\mocha\lib\runnable.js:377:21)
      at Test.Runnable.run (D:\promise-manager\node_modules\mocha\lib\runnable.js:324:7)
      at Runner.runTest (D:\promise-manager\node_modules\mocha\lib\runner.js:442:10)
      at D:\promise-manager\node_modules\mocha\lib\runner.js:560:12
      at next (D:\promise-manager\node_modules\mocha\lib\runner.js:356:14)
      at D:\promise-manager\node_modules\mocha\lib\runner.js:366:7
      at next (D:\promise-manager\node_modules\mocha\lib\runner.js:290:14)
      at Immediate._onImmediate (D:\promise-manager\node_modules\mocha\lib\runner.js:334:5)
      at runCallback (timers.js:785:20)
      at tryOnImmediate (timers.js:747:5)
      at processImmediate [as _immediateCallback] (timers.js:718:5)
```

## Actual Behavior -

When running without the promise manager (`promise.USE_PROMISE_MANAGER = false`) the same code rewritten with async/await only reports a partial stack trace and does not include the actual code line causing the problem:

```cmd
D:\promise-manager>npm run test-async

> example@0.0.0 test-async D:\promise-manager
> mocha test/async.js



  selenium-webdriver without promise manager

DevTools listening on ws://127.0.0.1:12497/devtools/browser/c61c0eb4-1efe-4a4e-b60a-665229b68044
    √ works as expected (2066ms)
    1) shows the error stack when failing


  1 passing (4s)
  1 failing

  1) selenium-webdriver without promise manager
       shows the error stack when failing:
     NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[name="thisdoesnotexist"]"}
  (Session info: chrome=62.0.3202.75)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)
      at Object.checkLegacyResponse (D:\promise-manager\node_modules\selenium-webdriver\lib\error.js:546:15)
      at parseHttpResponse (D:\promise-manager\node_modules\selenium-webdriver\lib\http.js:509:13)
      at doSend.then.response (D:\promise-manager\node_modules\selenium-webdriver\lib\http.js:441:30)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Steps to reproduce -
After installing the dependencies just run `npm run test-promise` for the example using the promise manager and `npm run test-async` for the example with the disabled promise manager.

[promise-manager.zip](https://github.com/SeleniumHQ/selenium/files/1428723/promise-manager.zip)

**Comment by jleyba** [comment]
This is working as intended. Without the promise manager, it's just native promises which don't provide the long stack traces. I believe you can still get the long stack traces when debugging with the chrome inspector (see this [page for more](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27))

**Comment by doberkofler** [comment]
@jleyba Thank you for your feedback. I understand that native promises don't provide long stack traces but this will be a major drawback when having to debug failed selenium tests. Is there no way that this can be "emulated" within the selenium driver?
