### ISSUE TITLE
Problem with  Selenium web driver - unable to open page with Firefox

### ISSUE THREAD

**Issue by Namorkenilej** [SeleniumHQ/selenium#4985]
OS:  

Selenium Version:  

--
Browser:  
<Firefox>

I started with Selenium WebDriver with Java.
Script I want run:

```
package com.romantester.webdriver;

import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class MyFirstTest {

    public static void main(String[] args) {

        // Create a new instance of the Firefox driver
        WebDriver driver = new FirefoxDriver();

        //Launch the Online Store Website
        driver.get("http://www.google.com/");

        // Print a Log In message to the screen
        System.out.println("Successfully opened the website https://www.seznam.cz/");

        // Close the driver
        driver.quit();
    }

}

There is a problem due to run:
 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1509451689639	Marionette	INFO	Enabled via --marionette
[ODEBUG] [Explorer Probe] [disableSPDY]#In disableSPDY()[ODEBUG] [Explorer Probe] [disableSPDY]#Trying to get profile path from command line if exists[ODEBUG] [Explorer Probe] [disableSPDY]#Didn't get any profile from command line, get all FireFox profiles from AppData[ODEBUG] [Explorer Probe] [disableSPDY]#In disableSPDY()[ODEBUG] [Explorer Probe] [disableSPDY]#Trying to get profile path from command line if exists[ODEBUG] [Explorer Probe] [disableSPDY]#Didn't get any profile from command line, get all FireFox profiles from AppData[ODEBUG] [Explorer Probe] [disableSPDY]#In disableSPDY()[ODEBUG] [Explorer Probe] [disableSPDY]#Trying to get profile path from command line if exists[ODEBUG] [Explorer Probe] [disableSPDY]#Didn't get any profile from command line, get all FireFox profiles from AppDataUnable to read VR Path Registry from C:\Users\ro066244\AppData\Local\openvr\openvrpaths.vrpath
[Parent 43424] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\test\AppData\Local\openvr\openvrpaths.vrpath
[Child 44752] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 44752] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[ODEBUG] [Explorer Probe] [disableSPDY]#In disableSPDY()[ODEBUG] [Explorer Probe] [disableSPDY]#Trying to get profile path from command line if exists[ODEBUG] [Explorer Probe] [disableSPDY]#Didn't get any profile from command line, get all FireFox profiles from AppData1509451692847	Marionette	INFO	Listening on port 50416
1509451692919	Marionette	WARN	TLS certificate errors will be ignored for this session
1509451692997	Marionette	DEBUG	Register listener.js for window 4294967297
říj 31, 2017 1:08:13 ODP. org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1509451693366	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1509451694400	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1509451694402	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1509451694402	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1509451694430	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "about:neterror?e=connectionFailure&u=http%3A//www.google.com/&c=UTF-8&f=regular&d=Firefox%20nem%C5%AF%C5%BEe%20nav%C3%A1zat%20spojen%C3%AD%20se%20serverem%20www.google.com."
Exception in thread "main" org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=connectionFailure&u=http%3A//www.google.com/&c=UTF-8&f=regular&d=Firefox%20nem%C5%AF%C5%BEe%20nav%C3%A1zat%20spojen%C3%AD%20se%20serverem%20www.google.com.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'X5CG5457S2R', ip: '172.20.192.122', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '9.0.1'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\test\AppData\Local\Temp\rust_mozprofile.f36lqhJJAwaO, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=56.0.2, platformVersion=6.1, moz:processID=43424, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 75c5b271-9498-4d5d-8c44-bfcaa1b30b92
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:310)
	at com.romantester.webdriver.MyFirstTest.main(MyFirstTest.java:18)
```
Could you pleas help? Thank you very much

**Comment by p0deje** [comment]
It looks like you have connection problem since browser loads error page (`Reached error page`).

Anyway, this is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
