### ISSUE TITLE
SessionNotCreatedException: Unable to create new remote session with IE 11, iedriver 3.6.0. 

### ISSUE THREAD

**Issue by alokarya0** [SeleniumHQ/selenium#4994]
## Meta -
OS:  Windows 10 64 Bit.

Selenium Version:  3.6.0

Browser:  Internet Explorer 11.

## Expected Behavior - I am using the following code to launch the IE 11 browser:
logger.info("The IE Driver Server Path is: "+Constant.IE_DRIVER_SERVER_PATH);
System.setProperty("webdriver.ie.driver",Constant.IE_DRIVER_SERVER_PATH);
driver = new InternetExplorerDriver();

The browser should launch successfully and proceed with further login action code.

## Actual Behavior - 
Please find attached the screen shot of the browser.
The browser is launching but, throwing the following "org.openqa.selenium.**SessionNotCreatedException**" exception:
Started InternetExplorerDriver server (32-bit)
3.6.0.0
Listening on port 30197
Only local connections are allowed
2017-11-01 22:48:09 ERROR [main] (DriverInitialize.java:136) - Exception Occured During Initialization of the WebDriver!!
2017-11-01 22:48:09 ERROR [main] (DriverInitialize.java:136) - Exception Occured During Initialization of the WebDriver!!
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}], required capabilities = Capabilities [{}]
Build info: version: 'unknown', revision: '5234b32', time: '2017-03-10 09:00:17 -0800'
System info: host: 'VM-001-0', ip: '10.194.41.76', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:230)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:180)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:172)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:144)
	at com.emc.webtop.commonlibs.DriverInitialize.initializeDriver(DriverInitialize.java:77)
	at com.emc.webtop.commonlibs.ObjectDeclaration.<clinit>(ObjectDeclaration.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

## Steps to reproduce -
Try running the following code:
logger.info("The IE Driver Server Path is: "+Constant.IE_DRIVER_SERVER_PATH);
System.setProperty("webdriver.ie.driver",Constant.IE_DRIVER_SERVER_PATH);
driver = new InternetExplorerDriver();

**Comment by barancev** [comment]
According to the timestamp in the build info ('2017-03-10 09:00:17 -0800'), you're using Selenium 3.3.1, please upgrade.
