### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by sergiybuch** [SeleniumHQ/selenium#5008]
I have the similar issue that was closed recently, can you please help to figure out what the problem is?

OS: Windows 10 & 8.1
Selenium Version: 3.6.0 - 3.7.0
Browser: Firefox 
Browser Version: 56.0.2 (32-bit)
Geckodriver version: 0.19
Behave version: 1.2.5

**Python script that I am running**
```
import unittest
import time
import datetime
from datetime import date
from behave import *
from selenium.webdriver.common.keys import Keys
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class browsepython(unittest.TestCase):
    

    @given('we have behave installed using {browser} with version {version} on {platform}')
    def step_impl(context, platform, browser, version):
        context.browser = browser
        context.platform = platform
        context.version = version
        context.driver = webdriver.Remote(command_executor='http://172.16.31.133:4444/wd/hub',
         desired_capabilities={'platform': platform, 'browserName': browser, 'javascriptEnabled': True}
         )
        pass
    
    @when('we browse to a site at url {url}')
    def step_impl(context, url):
        context.url=url
        try:
           context.driver.get(url)
        except:
           assert "can not reach the url: "+context.url
    @then('the page is captured')
    def step_impl(context):
        today = datetime.datetime.now().strftime("%Y%b%d_%H%M_")
        try:          
           context.driver.save_screenshot('C:\\testBehave\\features\\browsepython\\reportstestBehave\\features\\browsepython\\reports\\screenscapture\\'+str(today)+'.png')
        except:
           assert "can not capture the page"
        finally:
           context.driver.quit()


```

**Feature file**

> `Feature: Browse Python with behave
> 
>   Scenario Outline: Run a simple search on Python site using <browser> with version <version> on <platform>
>       Given we have behave installed using <browser> with version <version> on <platform>
>       when we browse to a site at url <url>
>       then the page is captured
>   
>   Examples:
>   | platform | browser           | version |    url                | 
>   | WIN8_1   | firefox           |   ANY   | http://www.python.org |
>   | WINDOWS  | chrome            |   ANY   | http://www.python.org |
>   | WINDOWS  | internet explorer |   9     | http://www.python.org |
>   | WINDOWS  | firefox           |   47.0    | http://www.python.org |
>   | WINDOWS  | internet explorer |   11    | http://www.python.org |
>   | MAC      | safari            |  7.1.5  | http://www.python.org |
>   | WIN10    | internet explorer |   Edge  | http://www.python.org |
>   | WIN10    | firefox           |   56.0  | http://www.python.org |
>   | WIN10    | chrome            |   56.0  | http://www.python.org |
> `

**Errorlog** 
`Feature: Browse Python with behave # browsepython.feature:1

  Scenario Outline: Run a simple search on Python site using firefox with version ANY on WIN8_1 -- @1.1   # browsepython.feature:10
    Given we have behave installed using firefox with version ANY on WIN8_1                               # steps\browsepython.py:13
      Traceback (most recent call last):
        File "c:\python36-32\lib\site-packages\behave\model.py", line 1456, in run
          match.run(runner.context)
        File "c:\python36-32\lib\site-packages\behave\model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "steps\browsepython.py", line 19, in step_impl
          desired_capabilities={'platform': platform, 'browserName': browser, 'javascriptEnabled': True}
        File "c:\python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 151, in __init__
          self.start_session(desired_capabilities, browser_profile)
        File "c:\python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 240, in start_session
          response = self.execute(Command.NEW_SESSION, parameters)
        File "c:\python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
          self.error_handler.check_response(response)
        File "c:\python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
          raise exception_class(message, screen, stacktrace)
      selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities
      Build info: version: '3.7.0', revision: '2321c73', time: '2017-11-02T22:12:12.411Z'
      System info: host: 'QA5', ip: '172.16.31.136', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_121'
      Driver info: driver.version: unknown
      remote stacktrace: stack backtrace:
         0:           0x47e934 - <no info>
         1:           0x47f0a3 - <no info>
         2:           0x442511 - <no info>
         3:           0x4436da - <no info>
         4:           0x42a890 - <no info>
         5:           0x406f5e - <no info>
         6:           0x40cfc9 - <no info>
         7:           0x6bef19 - <no info>
         8:           0x420756 - <no info>
         9:           0x6b96e0 - <no info>
        10:     0x7fffa42e15dd - BaseThreadInitThunk
      Stacktrace:
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (None:-2)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance (None:-1)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (None:-1)
          at java.lang.reflect.Constructor.newInstance (None:-1)
          at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0 (W3CHandshakeResponse.java:57)
          at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2 (W3CHandshakeResponse.java:104)
          at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0 (ProtocolHandshake.java:123)
          at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
          at java.util.Spliterators$ArraySpliterator.tryAdvance (None:-1)
          at java.util.stream.ReferencePipeline.forEachWithCancel (None:-1)
          at java.util.stream.AbstractPipeline.copyIntoWithCancel (None:-1)
          at java.util.stream.AbstractPipeline.copyInto (None:-1)
          at java.util.stream.AbstractPipeline.wrapAndCopyInto (None:-1)
          at java.util.stream.FindOps$FindOp.evaluateSequential (None:-1)
          at java.util.stream.AbstractPipeline.evaluate (None:-1)
          at java.util.stream.ReferencePipeline.findFirst (None:-1)
          at org.openqa.selenium.remote.ProtocolHandshake.createSession (ProtocolHandshake.java:126)
          at org.openqa.selenium.remote.ProtocolHandshake.createSession (ProtocolHandshake.java:73)
          at org.openqa.selenium.remote.server.ServicedSession$Factory.apply (ServicedSession.java:218)
          at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$11 (ActiveSessionFactory.java:167)
          at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
          at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
          at java.util.stream.ReferencePipeline$11$1.accept (None:-1)
          at java.util.stream.ReferencePipeline$2$1.accept (None:-1)
          at java.util.Spliterators$ArraySpliterator.tryAdvance (None:-1)
          at java.util.stream.ReferencePipeline.forEachWithCancel (None:-1)
          at java.util.stream.AbstractPipeline.copyIntoWithCancel (None:-1)
          at java.util.stream.AbstractPipeline.copyInto (None:-1)
          at java.util.stream.AbstractPipeline.wrapAndCopyInto (None:-1)
          at java.util.stream.FindOps$FindOp.evaluateSequential (None:-1)
          at java.util.stream.AbstractPipeline.evaluate (None:-1)
          at java.util.stream.ReferencePipeline.findFirst (None:-1)
          at org.openqa.selenium.remote.server.ActiveSessionFactory.apply (ActiveSessionFactory.java:170)
          at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$1 (NewSessionPipeline.java:44)
          at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
          at java.util.Collections$2.tryAdvance (None:-1)
          at java.util.stream.ReferencePipeline.forEachWithCancel (None:-1)
          at java.util.stream.AbstractPipeline.copyIntoWithCancel (None:-1)
          at java.util.stream.AbstractPipeline.copyInto (None:-1)
          at java.util.stream.AbstractPipeline.wrapAndCopyInto (None:-1)
          at java.util.stream.FindOps$FindOp.evaluateSequential (None:-1)
          at java.util.stream.AbstractPipeline.evaluate (None:-1)
          at java.util.stream.ReferencePipeline.findFirst (None:-1)
          at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$2 (NewSessionPipeline.java:47)
          at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
          at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
          at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
          at java.util.stream.DistinctOps$1$2.accept (None:-1)
          at java.util.stream.ReferencePipeline$2$1.accept (None:-1)
          at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
          at java.util.stream.ReferencePipeline$2$1.accept (None:-1)
          at java.util.stream.Streams$StreamBuilderImpl.tryAdvance (None:-1)
          at java.util.stream.Streams$ConcatSpliterator.tryAdvance (None:-1)
          at java.util.stream.ReferencePipeline.forEachWithCancel (None:-1)
          at java.util.stream.AbstractPipeline.copyIntoWithCancel (None:-1)
          at java.util.stream.AbstractPipeline.copyInto (None:-1)
          at java.util.stream.AbstractPipeline.wrapAndCopyInto (None:-1)
          at java.util.stream.FindOps$FindOp.evaluateSequential (None:-1)
          at java.util.stream.AbstractPipeline.evaluate (None:-1)
          at java.util.stream.ReferencePipeline.findFirst (None:-1)
          at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession (NewSessionPipeline.java:50)
          at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute (BeginSession.java:77)
          at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:240)
          at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
          at java.util.concurrent.FutureTask.run (None:-1)
          at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
          at java.lang.Thread.run (None:-1)

    When we browse to a site at url http://www.python.org                                                 # None
    Then the page is captured                                                                             # None

Failing scenarios:
  browsepython.feature:10  Run a simple search on Python site using firefox with version ANY on WIN8_1 -- @1.1

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
0 steps passed, 1 failed, 2 skipped, 0 undefined
Took 0m0.655s`

**Config for Selenium Node**

> {
>   "capabilities":
>   [
>     {
>       "browserName": "firefox",
>       "seleniumProtocol": "WebDriver",
>       "platform": "WIN8_1",
>       "version": "56.0",
>       "maxInstances": 5
>     },
>     {
>       "browserName": "chrome",
>       "maxInstances": 5,
>       "platform": "WIN8_1",
>       "version": "62.0.W8.QA5",
>       "seleniumProtocol": "WebDriver"
>     }
>   ],
>   "maxSession": 5,
>   "port": 6666,
>   "register": true,
>   "registerCycle": 5000,
>   "hub": "http://172.16.31.133:4444",
>   "nodeStatusCheckTimeout": 5000,
>   "nodePolling": 5000,
>   "role": "node",
>   "unregisterIfStillDownAfter": 60000,
>   "downPollingLimit": 2,
>   "debug": false,
>   "servlets" : [],
>   "withoutServlets": [],
>   "custom": {}
> }
> 

I tried this on Firefox versions 44, 55 and 56
Used Geckodriver 0.16 - 0.19.
Chromedriver works perfect

**Comment by barancev** [comment]
Upgrade geckodriver to version 0.19.1 and try again, this version is more informative on initialization errors.

**Comment by davehunt** [comment]
I had reports against pytest-selenium, which is setting the 'platform' capability to 'ANY' [here](https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/drivers/remote.py#L18). It seems this capability is no longer supported. I'm not clear on whether this was intentional.

**Comment by sergiybuch** [comment]
Thank you for your answers!
'ANY' works with chrome. I tried both - specific version and ANY, did not help. And I Updated Geckodriver to 0.19.1 - did not help either.

Also I tried to run firefox on MAC
this error I am getting on my PC when i run behave
 ```
selenium.common.exceptions.WebDriverException: Message: Unable to create new service: GeckoDriverService
      Build info: version: '3.7.0', revision: '2321c73', time: '2017-11-02T22:12:12.411Z'
      System info: host: 'qa6.spiria.com', ip: 'fe80:0:0:0:8e2:26ae:9a3e:1ff0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
      Driver info: driver.version: 

```

And this i got on MAC terminal:

![image](https://user-images.githubusercontent.com/28896994/32446066-b2cc0be4-c2d5-11e7-9483-01e38f153dad.png)

**Comment by lmtierney** [comment]
@sergiybuch I'm not sure this is your problem, but all those `-D` properties need to be between `java` and `-jar`

**Comment by sergiybuch** [comment]
@lmtierney  Thank you for advice. I just checked both `-D` before and after `-jar`, no changes, Chrome works and Firefox no.

**Comment by sergiybuch** [comment]
After all possible configuration checks I am getting this 
on Node side
![image](https://user-images.githubusercontent.com/28896994/32496867-adfcbeba-c398-11e7-87ec-9e7b5c88b97c.png)
 and this on Machine where I am trying to run test

![image](https://user-images.githubusercontent.com/28896994/32496911-d4bcfbfa-c398-11e7-997e-eb3a0374bd14.png)

Using Geckodriver 0.19.1 x64
Firefox 56.0.2

**Comment by mittt** [comment]
I'm getting the same error using the C# client lib:
Unable to find a matching set of capabilities
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'ATE2-W10-FF', ip: '10.10.110.244', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_60'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4821c4 - <no info>
   1:           0x482933 - <no info>
   2:           0x445281 - <no info>
   3:           0x4462ca - <no info>
   4:           0x43026a - <no info>
   5:           0x40ba4e - <no info>
   6:           0x4119b9 - <no info>
   7:           0x6d2c89 - <no info>
   8:           0x426006 - <no info>
   9:           0x6cd490 - <no info>
  10:     0x7ff8bdea2774 - BaseThreadInitThunk (InsecureCertificate)

Using Geckodriver 0.19.1 x64
Firefox 56.0.2
.Net lib: Selenium.WebDriver 3.7.0
Hub jar: 3.7.1
Node jar: 3.7.1

**Comment by barancev** [comment]
I should note that I can't reproduce the issue with sever 3.7.1, python binging 3.7.0, the node config from the original post. We need help from geckodriver team. Summining @AutomatedTester

**Comment by sergiybuch** [comment]
This is what I get on Mac node when i try to run firefox
![image](https://user-images.githubusercontent.com/28896994/32587263-678fd776-c4d5-11e7-9a2c-22f05682da8a.png)

**Comment by CristianLopGon** [comment]
I'm getting also the same issue:

org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'W7'  ip: '172.17.17.205', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x47e934 - <no info>
   1:           0x47f0a3 - <no info>
   2:           0x442511 - <no info>
   3:           0x4436da - <no info>
   4:           0x42a890 - <no info>
   5:           0x406f5e - <no info>
   6:           0x40cfc9 - <no info>
   7:           0x6bef19 - <no info>
   8:           0x420756 - <no info>
   9:           0x6b96e0 - <no info>
  10:         0x774159cd - BaseThreadInitThunk
	
When I try another configuration for Chrome, for exmaple, I don't have any problem. 

There is some incompatibility between Firefox version and this selenium version?

**Comment by barancev** [comment]
It seems we have identified what causes this issue, follow #5084

**Comment by amit2rockon** [comment]
I also went through this problem and solved it through this link https://amit2rockon.github.io/codesync/blog/2018/02/02/webdrivers.html
