### ISSUE TITLE
selenium-java-3.7.0.jar is missing http-core jar which is resulting in error java.lang.NoClassDefFoundError: org/apache/http/config/RegistryBuilder

### ISSUE THREAD

**Issue by sighil** [SeleniumHQ/selenium#5012]
OS:  Windows 10
Selenium Version:  3.7
Browser:  Chrome, Firefox
Browser Version:  chrome  61.0.3163.100 (Official Build) (64-bit), FF 52.4.0 (32-bit)

## Expected Behavior -
Chrome / FF opens and url is loaded.

## Actual Behavior -
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/config/RegistryBuilder
	at org.openqa.selenium.remote.internal.HttpClientFactory.getClientConnectionManager(HttpClientFactory.java:69)
	at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClientFactory.java:57)
	at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClientFactory.java:60)
	at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.getDefaultHttpClientFactory(ApacheHttpClient.java:242)
	at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.<init>(ApacheHttpClient.java:219)
	at org.openqa.selenium.remote.HttpCommandExecutor.getDefaultClientFactory(HttpCommandExecutor.java:93)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:72)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:59)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.<init>(DriverCommandExecutor.java:50)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:158)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at com.xyz.HelloWorld.main(HelloWorld.java:9)
Caused by: java.lang.ClassNotFoundException: org.apache.http.config.RegistryBuilder
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more

## Steps to reproduce -
1. Download http://selenium-release.storage.googleapis.com/3.7/selenium-java-3.7.0.zip
2. Extract and add to build path 
3. Download chrome driver 3.3 / gecko driver 1.7  
4. Try Launching chrome or FF using web driver

## Comments
Seems like the latest (v3.7) Selenium-Java zip file contains lesser jars in the lib folder. v3.6 contained 10 lib jars but v3.7 contains only 7 jars. The missing jar which is causing all the issue for the op is 'httpcore-4.4.6.jar'. I am not sure whether the removal of jar is intentional or not. 

https://stackoverflow.com/questions/47104058/selenium-webdriver-java-eclipse-java-lang-noclassdeffounderror/47108693#47108693

**Comment by barancev** [comment]
Shipped 3.7.1 that fixes this issue.
