### ISSUE TITLE
Starting ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f) on port 8875 Only local connections are allowed.

### ISSUE THREAD

**Issue by Ganeshj09** [SeleniumHQ/selenium#5022]
Getting below Issue -
Browser - google chrome (Version 62.0.3202.75 (Official Build) (64-bit))
Selenium - version 3.7.1
google chrome driver - version 2.33  

Code -
package pack;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Firstclass {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub

		WebDriver driver = new ChromeDriver();
		System.setProperty("webdriver.chrome.driver", "C:\\eclipse\\Chrome\\chromedriver.exe");

		
		driver.get("http://www.google.com");

}
}

Error Discription -
Starting ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f) on port 8875
Only local connections are allowed.
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: failed to write automation extension zip
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10240 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 47 milliseconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:31.527Z'
System info: host: 'WS-077', ip: '172.24.1.167', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at pack.Firstclass.main(Firstclass.java:14)

**Comment by AdvanceAutomation** [comment]
Path issue. Make sure your chrome driver path is correct.

**Comment by lmtierney** [comment]
Oh, right, you mentioned it already...

**Comment by barancev** [comment]
Looks like you have no rights to write to a temp dir:
https://chromium.googlesource.com/experimental/chromium/src/+/69d7f89d6a93e0fbce451960287066195c6d4ea0/chrome/test/chromedriver/chrome_launcher.cc#47

In any case, this is chromedriver issue: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by alexgmuir** [comment]
Getting the same issue on ubuntu 17.04 with the latest versions of the chrome driver and chromium.

Chrome Driver 2.33.506092
Chromium Version 62.0.3202.89 (Official Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit)

**Comment by Zicer** [comment]
Same problem;

Selenium : 3.7.0
Chrome Driver: 2.33.506120
Chrome version:  62.0.3202.94

**Comment by sapins** [comment]
Same problem;

Windows 7
Selenium : 3.7.0
Chrome Driver:  2.32.498513
Chrome version:  60.0.3112.113

**Comment by priyankakul07** [comment]
same problem:

windows 10
selenium:3.13.0
chrome driver:  2.40.565498
chrome version: Version 68.0.3440.75 (Official Build) (64-bit)
![error on invoking chrome browser only local connections are allowed](https://user-images.githubusercontent.com/41773983/43380843-37910c80-93f0-11e8-8b00-a50df5db6086.jpg)

**Comment by sapins** [comment]
@ priyankakul07 
Please update selenium version and try again.
