### ISSUE TITLE
TypeError: Cannot read property 'manage' of undefined

### ISSUE THREAD

**Issue by wenJanus** [SeleniumHQ/selenium#5035]
## Meta -
OS:  windows 7

Selenium Version:  

"types/selenium-webdriver": "^3.0.4",
 "selenium-webdriver": "^3.4.0",
Browser:  
"chromedriver": "2.33.2",

Browser Version:  

## Expected Behavior -
Run webdriver testcase in local is will. 

## Actual Behavior -
But run in docker env show error.

 1) Test SSM login "before all" hook:
     TypeError: Cannot read property 'manage' of undefined
      at new Browser (build/test/lib/browser.js:60:21)
      at Object.<anonymous> (build/test/testcase/test-uam.js:23:38)
      at Generator.next (<anonymous>)
      at build/test/testcase/test-uam.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (build/test/testcase/test-uam.js:3:12)
      at Context.before (build/test/testcase/test-uam.js:21:18)

2) Test SSM login "after all" hook:
     TypeError: Cannot read property 'dispose' of undefined
      at Object.<anonymous> (build/test/testcase/test-uam.js:92:21)
      at Generator.next (<anonymous>)
      at build/test/testcase/test-uam.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (build/test/testcase/test-uam.js:3:12)
      at Context.after (build/test/testcase/test-uam.js:91:17)

## Steps to reproduce -

Error 1:TypeError: Cannot read property 'manage' of undefined 
this.driver.manage().window().maximize();

Error 2: TypeError: Cannot read property 'dispose' of undefined
public async dispose(): Promise<void> {
    await this.browser.close();
  }

public async close(): Promise<void> {
    await this.driver.close();
  }

**Comment by wenJanus** [comment]
Sorry,  someone change the testcode. The driver is null value.
