### ISSUE TITLE
Flick action fails with exception "Failed to construct 'Touch': member target is not of type EventTarget."

### ISSUE THREAD

**Issue by oleksiybondar** [SeleniumHQ/selenium#5085]
## Meta -
OS: Mac OSX 10.13.1
Selenium Version:  selenium-webdriver: v3.7.0, chromedriver: v2.33 
Browser:  Chrome v62

Flick action tries to interact with an element an than fails with an exception 

## Expected Behavior -
slide changed and there is no any exceptions

## Actual Behavior -
```
/Users/oleksiybondar/.rbenv/versions/2.1.10/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/oleksiybondar/Documents/Development/Upwork/qa/autotests/debug/test.rb
/Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': unknown error: Failed to construct 'Touch': member target is not of type EventTarget. (Selenium::WebDriver::Error::UnknownError)
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.1 x86_64)
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:168:in `execute'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/oss/bridge.rb:432:in `touch_element_flick'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/touch_screen.rb:91:in `flick'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/action_builder.rb:356:in `block in perform'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/action_builder.rb:355:in `each'
	from /Users/oleksiybondar/.qa_rubygems/ruby/2.1.0/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/action_builder.rb:355:in `perform'
	from /Users/oleksiybondar/Documents/Development/Upwork/qa/autotests/debug/test.rb:18:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

https://www.dropbox.com/s/m7ajmltig058urh/flick2.mov?dl=0

## Steps to reproduce -
```
require 'bundler/setup'
require 'selenium-webdriver'

#-------------------------------------------------------------------------------

mobile_emulation = { "deviceName" => "Nexus 5" }
caps = Selenium::WebDriver::Remote::Capabilities.chrome("chromeOptions" => { "mobileEmulation" => mobile_emulation })
driver = Selenium::WebDriver.for :chrome, desired_capabilities: caps
driver.extend Selenium::WebDriver::DriverExtensions::HasTouchScreen

driver.get "https://owlcarousel2.github.io/OwlCarousel2/demos/responsive.html"

carousel = driver.find_element css: '.owl-carousel.owl-theme.owl-loaded.owl-drag'
item        = carousel.find_element css: '.owl-item.active'
driver.touch.flick(item, - item.rect.width, 0, 150).perform
sleep 10 # to see the results in case if it works
```

**Comment by p0deje** [comment]
This looks like ChromeDriver bug, not Selenium. Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
