### ISSUE TITLE
Looking for wrong jar version

### ISSUE THREAD

**Issue by toien44** [SeleniumHQ/selenium#5098]
## Meta -
OS:  OSx 10.12.6

Selenium Version:  
3.7.1

Browser:  
N/A

## Expected Behavior -
Download and run the desired version on Selenium.
## Actual Behavior -
check-paths-existence.js is looking for 3.5.3 when 3.7.1 is installed.
```
selenium install:
from: https://selenium-release.storage.googleapis.com/3.7/selenium-server-standalone-3.7.1.jar
to: /Users/qa-administrator/jenkins/workspace/dev-demo-tim/node_modules/selenium-standalone/.selenium/selenium-server/3.7.1-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.33/chromedriver_mac64.zip
to: /Users/qa-administrator/jenkins/workspace/dev-demo-tim/node_modules/selenium-standalone/.selenium/chromedriver/2.33-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-macos.tar.gz
to: /Users/qa-administrator/jenkins/workspace/dev-demo-tim/node_modules/selenium-standalone/.selenium/geckodriver/0.18.0-x64-geckodriver


-----
selenium-standalone installation finished
-----
error in start selenium Error: Missing /Users/qa-administrator/jenkins/workspace/dev-demo-tim/node_modules/selenium-standalone/.selenium/selenium-server/3.5.3-server.jar
    at /Users/qa-administrator/jenkins/workspace/dev-demo-tim/node_modules/selenium-standalone/lib/check-paths-existence.js:15:20
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```
## Steps to reproduce -
Run a test however the Selenium file check-paths-existence.js fails

**Comment by barancev** [comment]
check-paths-existence.js is not a part of Selenium distribution, it's third party software, send the report to the owner of this software.
