### ISSUE TITLE
Error forwarding the new session cannot find

### ISSUE THREAD

**Issue by karnikmg** [SeleniumHQ/selenium#5100]
OS:Mac
Browser:Safari Version 11.0.1 (12604.3.5.1.1)

Have following error
org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities [{browserName=safari, version=, platform=MAC}]

Stack Trace

at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	at basetest.DriverFactory.getRemoteDriver(DriverFactory.java:136)
	at basetest.DriverFactory.createInstance(DriverFactory.java:60)
	at basetest.BaseTest.setUp(BaseTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities [{browserName=safari, version=, platform=MAC}]
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Mayurs-MacBook-Pro.local', ip: '10.0.1.86', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_121'
Driver info: driver.version: unknown
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:112)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	... 1 more

Test ignored.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by karnikmg** [comment]
In DriverFactory class i have created following objects
RemoteWebDriver driver;
DesiredCapabilities capabilities;

i have switch case to select browser accordingly
For safari i have following case
case "safari":
                capabilities = DesiredCapabilities.safari();
                driver = getRemoteDriver(capabilities);
                break;

And this is the getRemoteDriver method
AppUsername and AppPassword is for authentication purpose--Browser window will open and i have to enter username and password.

private static RemoteWebDriver getRemoteDriver(DesiredCapabilities capabilities){
        String SERVER_URL = BaseTest.Config.getProperty("RemoteURL");
        String APP_URL = BaseTest.Config.getProperty("AppURL");
        String userName= BaseTest.Config.getProperty("AppUsername");
        String password= BaseTest.Config.getProperty("AppPassword");
        String[] URL= APP_URL.split("//");
        String authenticatedURL=	URL[0]+"//"+userName+":"+password+"@"+URL[1];
        RemoteWebDriver driver = null;
        try {
            driver = new RemoteWebDriver(new URL(SERVER_URL + "/wd/hub"), capabilities);
            driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
            driver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS);
            driver.manage().deleteAllCookies();
            driver.manage().window().maximize();
            driver.get(authenticatedURL);
            driver.get(authenticatedURL);
            driver.get(APP_URL);
            driver.navigate().refresh();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        return driver;
    }

So when i pass browser as "safari" following error occur and it fails to execute. It works for chrome very well without any errors.
 
org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities [{browserName=safari, version=, platform=MAC}]

**Comment by p0deje** [comment]
Please provide versions for:

* Java bindings
* Grid hub
* Grid node

**Comment by karnikmg** [comment]
Please find below versions details
    Java bindings- did u mean java version i am using (1.0.8_121)
    Grid hub- 3.4.0
    Grid node- 3.4.0

**Comment by p0deje** [comment]
Please upgrade to latest Hub and Node and try again. This problem should be fixed there.

**Comment by karnikmg** [comment]
@p0deje Thanks for ur help...i will check and let you know.

**Comment by barancev** [comment]
And show your node configuration (either the config file or the command used to start it)

**Comment by karnikmg** [comment]
The command which i used to start are as follows
cd Documents/KloojjAutomation/Grid/  -- Navigate to the folder where grid is located
java -jar selenium-server-standalone-3.4.0.jar -role hub-- Launching Selenium Grid

java -jar selenium-server-standalone-3.4.0.jar -role node -hub http://10.0.1.86:4444/grid/register/ -- registering node

**Comment by barancev** [comment]
By default a node starts with no Safari slots configured.
