### ISSUE TITLE
getting number format exception in JsonToBeanConverter when json entry is a double value

### ISSUE THREAD

**Issue by michaelssun** [SeleniumHQ/selenium#511]
See below exception:
json attribute: 
"somevalue":0.5

this is caused by google gson translating above value into a LazilyParsedNumber and the double value above can not be directly converted to a long value. Selenium API may have to translate such values as double directly.

*****************************************************************************
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.JsonToBeanConverter.propertyWriteException(JsonToBeanConverter.java:291) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convertBean(JsonToBeanConverter.java:268) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConverter.java:178) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConverter.java:41) 
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.decode(JsonHttpResponseCodec.java:62) 
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136) 
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572) 
	... 8 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: ".5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_72]
	at java.lang.Integer.parseInt(Integer.java:481) ~[na:1.7.0_72]
	at java.math.BigInteger.<init>(BigInteger.java:338) ~[na:1.7.0_72]
	at java.math.BigInteger.<init>(BigInteger.java:476) ~[na:1.7.0_72]
	at com.google.gson.internal.LazilyParsedNumber.longValue(LazilyParsedNumber.java:51) 
	at com.google.gson.JsonPrimitive.getAsLong(JsonPrimitive.java:233) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convertJsonPrimitive(JsonToBeanConverter.java:205) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConverter.java:73) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convertMap(JsonToBeanConverter.java:301) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConverter.java:175) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convertList(JsonToBeanConverter.java:311) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConverter.java:162) 
	at org.openqa.selenium.remote.JsonToBeanConverter.convertBean(JsonToBeanConverter.java:266)

**Comment by jleyba** [comment]
Drive by comment:

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/JsonToBeanConverter.java#L206

The above should probably be changed to something like:

    Number number = json.getAsNumber();
    if (number.longValue() == number.doubleValue() {
    // ...

**Comment by lukeis** [comment]
I saw this locally in my environment when the version of gson used was older than the one selenium uses (2.3.1).

Please upgrade your version of the gson library. This will not occur then.

**Comment by michaelssun** [comment]
sounds great! thx for quick solution
