### ISSUE TITLE
Net::ReadTimeout for Chrome in Ruby Bindings

### ISSUE THREAD

**Issue by Overload119** [SeleniumHQ/selenium#5110]
## Meta 
OS:  OSX
Selenium Version:  ChromeDriver 2.33.506106
Browser: Chrome

## Expected Behavior -

It loads a browser.

## Actual Behavior -

```
"Net::ReadTimeout"
["/Users/amirsharif/Projects/knowledge/app/models/script.rb:19:in `eval'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:154:in `readuntil'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:164:in `readline'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:40:in `read_status_line'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:29:in `read_new'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1446:in `block in transport_request'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `catch'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1416:in `request'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:877:in `start'",
 "/Users/amirsharif/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1407:in `request'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:168:in `execute'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:101:in `create_session'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:52:in `handshake'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/chrome/driver.rb:56:in `initialize'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/driver.rb:44:in `new'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/driver.rb:44:in `for'",
 "/Users/amirsharif/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver.rb:84:in `for'",
 "/Users/amirsharif/Projects/knowledge/app/services/web_client.rb:9:in `initialize'",
```

Any suggestions on how to debug?

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
