### ISSUE TITLE
JAVA-Selenium Microsoft Edge Code Breaks with -1073741512(ExitCode) Error

### ISSUE THREAD

**Issue by SudeeptMohan** [SeleniumHQ/selenium#5123]
Problem - Microsoft Edge browser is not launched via Selenium

Command - (JAVA)
System.setProperty("webdriver.edge.driver","C:\\\\Marionette\\MicrosoftWebDriver.exe");
		WebDriver driver5 = new EdgeDriver();

Error Observed in Eclipse IDE-
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: -1073741512 (Exit value: -1073741512)
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:26.402Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: EdgeDriver
at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:140)
at org.openqa.selenium.edge.EdgeDriver.(EdgeDriver.java:150)
at org.openqa.selenium.edge.EdgeDriver.(EdgeDriver.java:139)
at org.openqa.selenium.edge.EdgeDriver.(EdgeDriver.java:96)
at packageFF.browserAutomation.main(browserAutomation.java:40)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:14371/status] to be available after 20002 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187)
... 9 more
Caused by: java.util.concurrent.TimeoutException
at java.util.concurrent.FutureTask.get(Unknown Source)
at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
... 10 more

**Comment by hazmeister** [comment]
Did Windows 10 update recently.  Ensure you have the correct `MicrosoftWebDriver.exe` for you version of Windows 10:
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

You can find your build number by opening a command prompt.

**Comment by SudeeptMohan** [comment]
A matching version of MicrosoftWebDriver.exe doesn't solve this problem.
Sharing the build number for my Windows 10- 15063.726.

**Comment by barancev** [comment]
Can we change something on the client side to fix this issue? If not -- it should be reported to Microsoft bug tracker.

**Comment by SudeeptMohan** [comment]
Not sure if something can be changed on client side - raised the bug here - 
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15019431/

**Comment by barancev** [comment]
Yes, sounds like it should be fixed on the driver side, closing the issue.
