### ISSUE TITLE
Selenium 3.7.0-Python-GeckoDriver 0.19.1 : print() throws UnicodeEncodeError when printing the characters obtained as Page Source.

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#5138]
## Meta - Selenium 3.7.1-Python-GeckoDriver 0.19.1 : print() throws **`UnicodeEncodeError: 'charmap' codec can't encode characters`** when printing the characters obtained as Page Source.

The complete error is : 

```
Traceback (most recent call last):
  File "C:\Users\AtechM_03\LearnAutmation\PythonProject\Stackoverflow\47548870_page_source.py", line 14, in <module>
    print(StrSource)
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 57354-57358: character maps to <undefined>
```

OS:  Windows 8, Pro
Selenium Version:  Selenium (Python) v3.7.0

Browser:  Firefox Quantum

Browser Version:  57.0 (64-bit)

## Steps to reproduce -
Minimum Code Block  : 

```
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Firefox()
driver.get("http://www.moneycontrol.com")
searchText = driver.find_element_by_xpath("//input[@id='search_str']")
searchText.send_keys("dlf")
search_button = driver.find_element_by_css_selector(".btn_black.btn_search.FR")
search_button.click()
WebDriverWait(driver, 10).until(EC.visibility_of_element_located((By.XPATH,"//h1[text()='DLF']")))
StrSource = driver.page_source
print(StrSource)
```
[geckodriver.log](https://github.com/SeleniumHQ/selenium/files/1513423/geckodriver.log)

**Comment by cgoldberg** [comment]
this is a Windows console issue, not a bug in Selenium.  see: https://wiki.python.org/moin/PrintFails
