### ISSUE TITLE
<urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by wkdtjsgur100** [SeleniumHQ/selenium#5155]
## Meta -
OS:  Ubuntu 16.04

Selenium Version:  3.8.0

Browser:  Firefox

Browser Version:  57.0 (64-bit)

## Steps to reproduce

I am crawling a site using django-rest-framework.
my sources are:
``` python
def create_driver_session(session_id, executor_url):
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver

    # Save the original function, so we can revert our patch
    org_command_execute = RemoteWebDriver.execute

    def new_command_execute(self, command, params=None):
        if command == "newSession":
            # Mock the response
            return {'success': 0, 'value': None, 'sessionId': session_id}
        else:
            return org_command_execute(self, command, params)

    # Patch the function before creating the driver object
    RemoteWebDriver.execute = new_command_execute

    new_driver = webdriver.Remote(command_executor=executor_url, desired_capabilities={})
    new_driver.session_id = session_id

    # Replace the patched function with original function
    RemoteWebDriver.execute = org_command_execute

    return new_driver

@api_view(['POST'])
def phone_auth_num(request):
    display = Display(visible=0, size=(800, 600))
    display.start()

    driver = webdriver.Firefox()
    data = request.POST

    driver.get('https://noom.co.kr/faq/')

    time.sleep(3)

    t = driver.find_element_by_css_selector('#accordion-5564-1 > div:nth-child(2) > div.panel-heading > h4')
    t.click()

    executor_url = driver.command_executor._url
    session_id = driver.session_id

    return Response({"message": "Success", "executor_url": executor_url, "session_id": session_id})

@api_view(['POST'])
def manufacture_list(request):
    data = request.POST

    driver = create_driver_session(data['session_id'],data['executor_url'])

    for _ in range(0,30):
        d = driver.find_element_by_css_selector("#accordion-5564-1 > div:nth-child(2) > div.panel-heading > h4")
        print(d.text)

    d.click()

    driver.quit()

    return Response({"message": "Success"})
```

`phone_auth_num` function will be called when `/phone-auth` url request, and  
`manufacture_list` function will be called when `/manufacture-list` url request.

When I continuously request `/phone-auth` and `/manufacture-list` at first time, it works well.
but When I request second time, it occurs error with below message:

``` shell
Internal Server Error: /manufacture-list/
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/rest_framework/decorators.py", line 52, in handler
    return func(*args, **kwargs)
  File "./inscheck/spider/views.py", line 194, in manufacture_list
    d = driver.find_element_by_css_selector("#accordion-5564-1 > div:nth-child(2) > div.panel-heading > h4")
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 512, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 858, in find_element
    'value': value})['value']
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 309, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 460, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/ubuntu/.pyenv/versions/3.6.0/envs/inscheck-3.6.0-env/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 522, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/ubuntu/.pyenv/versions/3.6.0/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by lmtierney** [comment]
This is not the intended use of selenium. When you start modifying internal methods, you're on your own. If there's a legit bug, please provide code for a normal use case. 

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).
