### ISSUE TITLE
Driver wait until.TextIs is not working

### ISSUE THREAD

**Issue by updatesvc** [SeleniumHQ/selenium#5168]
## Meta -
OS:  
Windows 10
Selenium-webdriver Version:  
3.6.0
Using the NodeJS implementation
Browser:  
Google Chrome

Browser Version:  
Version 62.0.3202.94 (Official Build) (64-bit)

## Actual Behavior -
I am trying to implement this feature [here](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/until.html#elementTextIs).
Like in the code below:
```
driver.wait(until.elementTextIs(By.css('body > div.site-wrapper > div > div 
> div.inner.cover > p:nth-child(3) > a.btn.btn-lg.btn-primary'),'Sign 
Up'),80000)
```
But I get this error:
`Uncaught TypeError: element.getText is not a function
    at C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\until.js:390:20
    at C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\webdriver.js:938:14
    at TaskQueue.execute_ (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: <anonymous>
    at pollCondition (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:2195:19)
    at C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:2191:7
    at new ManagedPromise (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:2190:22
    at TaskQueue.execute_ (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:668:7
    at <anonymous>
From: Task: Waiting until element text is
    at scheduleWait (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:2188:20)
    at ControlFlow.wait (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\promise.js:2517:12)
    at thenableWebDriverProxy.wait (C:\Users\bob\Documents\testElectron\node_modules\selenium-webdriver\lib\webdriver.js:934:29)
    at file:///C:/Users/bob/Documents/testElectron/browser.js:39:9`

## Expected Behavior -
The driver should wait for the Text for the button to be what I specify.

## Steps to reproduce -
```
driver.wait(until.elementTextIs(By.css('body > div.site-wrapper > div > div 
> div.inner.cover > p:nth-child(3) > a.btn.btn-lg.btn-primary'),'Sign 
Up'),80000)
```
Use the function above on any element.

**Comment by updatesvc** [comment]
Seems I was passing a locator instead of an element.
One should pass an element like below
`driver.wait(until.elementTextIs(driver.findElement(By.css('body > div.site-wrapper > div > div > div.inner.cover > p:nth-child(3) > a.btn.btn-lg.btn-primary')),'Sign Up'),80000)`
