### ISSUE TITLE
selenium web driver-firefox first test case

### ISSUE THREAD

**Issue by pradeepst** [SeleniumHQ/selenium#5197]
i use below code to launch the website but i am getting the errors in console..

package automationFramework;

import org.openqa.selenium.firefox.FirefoxDriver;
public class FirstTestCase {
 
	public static void main(String[] args) {
		
		// Create a new instance of the Firefox driver
		//System.setProperty("webdriver.gecko.driver","C:/selenium/geckodriver_1.exe" ); 
		System.setProperty("webdriver.firefox.marionette", "./geckodriver.exe");
		FirefoxDriver driver = new FirefoxDriver();
        //Launch the Online Store Website
		driver.get("https://www.google.com");

    }
}

Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.
Build info: version: '3.8.0', revision: '924c4067df', time: '2017-11-30T11:36:59.109Z'
System info: host: 'L-AH787883', ip: '192.168.1.10', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:131)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:116)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at automationFramework.FirstTestCase.main(FirstTestCase.java:11)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:34917/hub/status] to be available after 45002 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:129)
	... 8 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 9 more

**Comment by barancev** [comment]
"webdriver.firefox.marionette" is a boolean property (to use marionette+geckodriver or not), by default it's true.
