### ISSUE TITLE
 'SELENIUM_SERVER_JAR'

### ISSUE THREAD

**Issue by kamola** [SeleniumHQ/selenium#5213]
## Meta -
OS:  
MacOS High Sierra.Version 10.13 
Browser:  
Safar
## Expected Behavior -
1. Open browser
2. Login with given credentials
## Actual Behavior -
Getting the error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/safari/webdriver.py", line 51, in __init__
    executable_path = os.environ["SELENIUM_SERVER_JAR"]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'SELENIUM_SERVER_JAR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MyFirstSeleniumScript.py", line 3, in <module>
    driver = webdriver.Safari()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/safari/webdriver.py", line 54, in __init__
    'SELENIUM_SERVER_JAR'")
Exception: No executable path given, please add one to Environment Variable                 'SELENIUM_SERVER_JAR'

##Steps to reproduce - 

```
from selenium import webdriver
driver = webdriver.Safari()
driver.get("https://www.facebook.com/")
driver.maximize_window()
driver.get_screenshot_as_file("/Users/kamolochka/PycharmProjects/selenium/Screenshots/Facebook.png")
driver.find_element_by_id('email').send_keys('test@mail.com')
driver.find_element_by_name("pass").send_keys("demo")
driver.find_element_by_id("loginbutton").click()
driver.get_screenshot_as_file("/Users/kamolochka/PycharmProjects/selenium/Screenshots/Facebook1.png")
driver.quit()
```

The same test run before without error.

**Comment by lmtierney** [comment]
It appears that you're modifying the library file for `selenium.webdriver.safari.webdriver`. There is no attempt to get the `"SELENIUM_SERVER_JAR"` environment variable anywhere in the selenium library.
