### ISSUE TITLE
ystem.InvalidOperationException: Error forwarding the new session webdriver new session JSON response body did not contain a session ID

### ISSUE THREAD

**Issue by ashishraj14** [SeleniumHQ/selenium#524]
Hi there,
I am setting up the selenium grid and using following commands to set up hub and node respectively
java -Dwebdriver.chrome.driver="<path to chromedriver.exe>" -jar selenium-server-standalone-2.42.0.jar -role hub

java -Dwebdriver.chrome.driver="<path to chromedriver.exe>" -jar selenium-server-standalone-2.42.0.jar -role node -hub http://<hostname>:4444/grid/register

The tests run fine using chrome but they fail on Firefox
rmDriver = new RemoteWebDriver(new Uri("http://hostname:4444/wd/hub"), DesiredCapabilities.Firefox());
 rmDriver.Navigate().GoToUrl(homepage);

with the following trace
System.InvalidOperationException: Error forwarding the new session webdriver new session JSON response body did not contain a session ID
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at CBGrid.UnitTest1.TestMethod2() in C:\CBGrid\UnitTest1.cs:line 38

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Version 2.42 is out of date, the current version is 2.45
