### ISSUE TITLE
ModuleNotFoundError: No module named 'buck_logging'

### ISSUE THREAD

**Issue by jasonsword** [SeleniumHQ/selenium#5252]
Hi all, I'm new to selenium,I want to build selenium webdriver for testing ie
but when I start "go build" some error happened.

python C:/workspace/selenium/buck-out/crazy-fun/be2bf932342e5d67f58c9b26f5065c745d285d0d/buck.pex kill
Traceback (most recent call last):
  File "C:\workspace\selenium\buck-out\crazy-fun\be2bf932342e5d67f58c9b26f5065c745d285d0d\buck.pex\.bootstrap\_pex\pex.py", line 323, in execute
  File "C:\workspace\selenium\buck-out\crazy-fun\be2bf932342e5d67f58c9b26f5065c745d285d0d\buck.pex\.bootstrap\_pex\pex.py", line 256, in _wrap_coverage
  File "C:\workspace\selenium\buck-out\crazy-fun\be2bf932342e5d67f58c9b26f5065c745d285d0d\buck.pex\.bootstrap\_pex\pex.py", line 288, in _wrap_profiling
  File "C:\workspace\selenium\buck-out\crazy-fun\be2bf932342e5d67f58c9b26f5065c745d285d0d\buck.pex\.bootstrap\_pex\pex.py", line 366, in _execute
  File "C:\workspace\selenium\buck-out\crazy-fun\be2bf932342e5d67f58c9b26f5065c745d285d0d\buck.pex\.bootstrap\_pex\pex.py", line 424, in execute_entry
  File "C:\workspace\selenium\buck-out\crazy-fun\be2bf932342e5d67f58c9b26f5065c745d285d0d\buck.pex\.bootstrap\_pex\pex.py", line 429, in execute_module
  File "C:\Users\jason\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "C:\Users\jason\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\workspace\selenium\buck-out\crazy-fun\be2bf932342e5d67f58c9b26f5065c745d285d0d\buck.pex\programs\buck.py", line 9, in <module>
ModuleNotFoundError: No module named 'buck_logging'
Exception `RuntimeError' at uri:classloader:/gems/rake-10.5.0/lib/rake/file_utils.rb:66 - Command failed with status (1): [python C:/workspace/selenium/buck-out/craz...]
Exception `#<Class:#<RuntimeError:0x50e5032c>>' at uri:classloader:/gems/rake-10.5.0/lib/rake/file_utils.rb:66 - Command failed with status (1): [python C:/workspace/selenium/buck-out/craz...]
Exception `#<Class:#<RuntimeError:0x50e5032c>>' at uri:classloader:/gems/rake-10.5.0/lib/rake/file_utils.rb:66 - Command failed with status (1): [python C:/workspace/selenium/buck-out/craz...]
go aborted!
Command failed with status (1): [python C:/workspace/selenium/buck-out/craz...]
uri:classloader:/gems/rake-10.5.0/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
uri:classloader:/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `sh'
uri:classloader:/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:35:in `sh'
C:/workspace/selenium/rake-tasks/buck.rb:22:in `download'
C:/workspace/selenium/rake-tasks/buck.rb:57:in `buck_cmd'
C:/workspace/selenium/rake-tasks/buck.rb:257:in `block in (root)'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
uri:classloader:/gems/rake-10.5.0/bin/rake:33:in `<main>'
org/jruby/RubyKernel.java:973:in `load'
uri:classloader:/META-INF/jruby.home/bin/rake:1:in `<main>'
Tasks: TOP => ie => //java/client/src/org/openqa/selenium/ie

but when i unzip the buck.pex, the buck_logging exists,
any ideas? I'm not familiar with ruby.

OS:  Windows 10
Selenium Version:  3.8.1
Browser:  none
Browser Version:  none
## Steps to reproduce -

**Comment by barancev** [comment]
buck is not python3 compatible (see [1]), you have to use python2 to build selenium.

[1] https://github.com/facebook/buck/issues/774
