### ISSUE TITLE
While using pageLoadTimeout it fails to navigate to URL

### ISSUE THREAD

**Issue by mrunalgosar** [SeleniumHQ/selenium#5256]
## Meta -
OS:  Windows 7 (64-bit)

Selenium Version:  3.8.1 (Webdriver) - Java Bindings

Browser:  Firefox (57.0.2) Gecko driver version: 0.19.1

Browser Version:  Firefox (57.0.2)

## Expected Behavior -
When we try to set pageLoadTimeouts, the browser should wait till the set timeout while navigating to URL.

## Actual Behavior -
It fails to load the web application. It only launches the browser and fails with exception. if we don't set the pageLoadTimeout then it successfully loads the browser.

## Steps to reproduce -

JUnit test Case:
```
@Test
	public void test() {
		System.setProperty("webdriver.gecko.driver",
				"path to geckodriver.exe");
		WebDriver browser = new FirefoxDriver();
		browser.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS);
		browser.get("https://www.snapdeal.com/");
		System.out.println("Wait");
	}
```
If we don't set pageLoadTimeout then it successfully loads the web application. But if set the pageLoadTimeout then it fails with below exception:

```
org.openqa.selenium.WebDriverException: timeouts
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'MRUNAL-LAPTOP', ip: '192.168.0.100', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 57.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 1128, moz:profile: C:\Users\<username here>\AppData\Loc..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 6.1, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 9cff1de6-be3a-4b8b-80fe-600b911e81fb
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.pageLoadTimeout(RemoteWebDriver.java:847)
	at runner.FirefoxTest.test(FirefoxTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)


```
## Log
```
1514187158718	geckodriver	INFO	Listening on 127.0.0.1:2610
1514187159234	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1514187161306	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\<username here>\AppData\Local\openvr\openvrpaths.vrpath
[Parent 1128, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\<username here>\AppData\Local\openvr\openvrpaths.vrpath
[Child 2604, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1514187170623	Marionette	INFO	Listening on port 53942
1514187170979	Marionette	WARN	TLS certificate errors will be ignored for this session
1514187174692	Marionette	DEBUG	Register listener.js for window 4294967297
Dec 25, 2017 1:02:54 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Dec 25, 2017 1:02:55 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

```

**Comment by kool79** [comment]
Which version geckodriver do you use? With 0.19.1 win64 I don't have such issue (but log differs):
```
1514320818887	geckodriver	INFO	geckodriver 0.19.1
1514320818907	geckodriver	INFO	Listening on 127.0.0.1:4818
1514320819881	mozrunner::runner	INFO	Running command: "C:/Program Files/Mozilla Firefox 57.0.2/firefox.exe" "-marionette" "-profile" "C:\\Users\\O4937~1.KUL\\AppData\\Local\\Temp\\rust_mozprofile.n0M4qfgOXvmc"
1514320821278	Marionette	INFO	Enabled via --marionette
1514320824545	Marionette	INFO	Listening on port 56051
1514320824997	Marionette	WARN	TLS certificate errors will be ignored for this session
1514320825071	Marionette	DEBUG	Register listener.js for window 4294967297
1514320825305	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1514320826557	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1514320826558	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
Unable to read VR Path Registry from C:\Users\o.kulychok\AppData\Local\openvr\openvrpaths.vrpath
JavaScript warning: https://i3.sdlcdn.com/js/19dec1513600528734/snap/base.jquery111.min.js, line 20: unreachable code after return statement
JavaScript warning: https://i3.sdlcdn.com/js/19dec1513600528734/snap/base.jquery111.min.js, line 23: unreachable code after return statement
JavaScript warning: https://i3.sdlcdn.com/js/19dec1513600528734/snap/base.jquery111.min.js, line 20: unreachable code after return statement
1514320827767	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.snapdeal.com/"
1514320828214	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.snapdeal.com/"
Wait
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
```

**Comment by mrunalgosar** [comment]
Hi @kool79 
I am using 0.19.1 version of geckodriver. Also I have created a small gradle based project to recreate this issue. It is present at: https://github.com/mrunalgosar/jenkins_ci_test. would you be able to clone this repo and run at your end to check if it is reproduceable at your end.

**Comment by barancev** [comment]
Please change the code to increase logging:
```
FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(FirefoxDriverLogLevel.DEBUG);
WebDriver browser = new FirefoxDriver(options);
```
run the script again and attach the complete log here.

**Comment by mrunalgosar** [comment]
Hi @barancev 
Please find below the logs. I have also updated the test at the above git repo. Test Class: `PageLoadTimeoutTest`

## Logs
1514395935647	geckodriver	INFO	Listening on 127.0.0.1:41538
1514395936490	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1514395943686	Marionette	DEBUG	Received observer notification "profile-after-change"
1514395944193	Marionette	DEBUG	Received observer notification "command-line-startup"
1514395944193	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\<user>\AppData\Local\openvr\openvrpaths.vrpath
[Child 4688, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 4688, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1514395952359	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1514395956231	Marionette	DEBUG	Setting recommended pref browser.safebrowsing.passwords.enabled to false
1514395956231	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1514395956231	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1514395956232	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1514395956232	Marionette	DEBUG	Setting recommended pref extensions.shield-recipe-client.api_url to 
1514395956233	Marionette	DEBUG	New connections are accepted
1514395956233	Marionette	INFO	Listening on port 49510
1514395956898	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:49510
1514395957200	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:49554
1514395957208	Marionette	WARN	TLS certificate errors will be ignored for this session
1514395963270	Marionette	DEBUG	Register listener.js for window 4294967297
1514395963280	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"7062f5d4-26e1-4941-9643-c7887734a8fb","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"57.0.2","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":5560,"moz:profile":"C:\\Users\\<user>\\AppData\\Local\\Temp\\rust_mozprofile.ZPPfSieXNXBj","moz:webdriverClick":false,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
Dec 27, 2017 11:02:43 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1514395963374	webdriver::server	DEBUG	-> POST /session/7062f5d4-26e1-4941-9643-c7887734a8fb/timeouts {"pageLoad":10000}
1514395963389	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"unknown error","message":"timeouts","stacktrace":"stack backtrace:\n   0:           0x4bd56f - <no info>\n   1:           0x4bdcc9 - <no info>\n   2:           0x43dc4d - <no info>\n   3:           0x44db84 - <no info>\n   4:           0x44a1ca - <no info>\n   5:           0x4207bc - <no info>\n   6:           0x405e47 - <no info>\n   7:           0x6db3d9 - <no info>\n   8:           0x417847 - <no info>\n   9:           0x6d56d3 - <no info>\n  10:         0x778159cd - BaseThreadInitThunk"}}
Dec 27, 2017 11:02:43 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

org.openqa.selenium.WebDriverException: timeouts
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'MRUNAL-LAPTOP', ip: '192.168.0.102', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 57.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 5560, moz:profile: C:\Users\mrunal\AppData\Loc..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 6.1, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 7062f5d4-26e1-4941-9643-c7887734a8fb

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.pageLoadTimeout(RemoteWebDriver.java:847)
	at runner.PageLoadTimeoutTest.test(PageLoadTimeoutTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by barancev** [comment]
The log is incomplete, it's cut in the beginning, there should be other messages including a line that shows geckodriver version

**Comment by kool79** [comment]
@mrunalgosar , you have geckodriver v 0.17.0 at the path specified [here](https://github.com/mrunalgosar/jenkins_ci_test/blob/48811b25156ee496c01fb59f2abe25e6c9d061b6/src/test/java/runner/PageLoadTimeoutTest.java#L15)
To check version just run from command-line:
`geckodriver --help`

**Comment by kool79** [comment]
Issue can be closed: 
 It is not reproduced with latest releases of selenium and geckodriver. Author use outdated version of geckodriver

**Comment by mrunalgosar** [comment]
Hi @kool79 & @barancev 
Sincere apologies for the human error. I stand corrected. I was accidentally using the older version of geckodriver. Tried and tested at my end with latest geckodriver and its working. Thanks a lot!
