### ISSUE TITLE
Cannot start custom remote instance of browser.

### ISSUE THREAD

**Issue by S-Kerrigan** [SeleniumHQ/selenium#5260]
## Meta -
OS:  
Win7x64
Selenium Version:  
3.7.1 - 3.8.1
Browser:  
FF, Ch

I tried create new custom remote instance on any browser, but always get exception in this stage:
From RemoteWebDriver.java
```
protected Response execute(String driverCommand, Map<String, ?> parameters) {
...
response = this.executor.execute(command);
...
}
```

My code:
```
.........................
GeckoDriverService service_ff = new GeckoDriverService.Builder()
				.usingDriverExecutable(new File(path_to_driver.exe))
				.usingAnyFreePort()
				.build();
		service_ff.start();

		WebDriver driver = new CustomRemoteWebDriver(service_ff.getUrl(), DesiredCapabilities.firefox());
..........................
public static class CustomRemoteWebDriver extends RemoteWebDriver {
		public static String sessionIdPath = "c:\\automation\\sessionid";

		public CustomRemoteWebDriver(URL remoteAddress, Capabilities desiredCapabilities) {
			super(remoteAddress, desiredCapabilities);
		}

		@SuppressWarnings("Duplicates")
		@Override
		protected void startSession(Capabilities desiredCapabilities) {
			String sid = getPreviousSessionIdFromSomeStorage();
			if (sid != null) {
				setSessionId(sid);
				try {
					getCurrentUrl();
				} catch (WebDriverException e) {
					// session is not valid
					e.printStackTrace();
					sid = null;
				}
			}

			if (sid == null) {
				super.startSession(desiredCapabilities);
				saveSessionIdToSomeStorage(getSessionId().toString());
			}
		}

		private void saveSessionIdToSomeStorage(String sessionId) {
			try {
				FileUtils.writeStringToFile(new File(sessionIdPath), sessionId, Charset.defaultCharset());
			} catch (IOException e) {
				e.printStackTrace();
			}
		}

		private String getPreviousSessionIdFromSomeStorage() {
			String sessionId;
			try {
				List<String> sidText = FileUtils.readLines(new File(sessionIdPath), Charset.defaultCharset());
				sessionId = sidText.get(0);
			} catch (Exception e) {
				return null;
			}
			return sessionId;
		}
	}
```

Exception:
```
Connected to the target VM, address: '127.0.0.1:18126', transport: 'socket'
1514269556990	geckodriver	INFO	geckodriver 0.19.1
1514269557006	geckodriver	INFO	Listening on 127.0.0.1:22747
org.openqa.selenium.WebDriverException: No command or response codec has been defined. Unable to proceed
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'KARASEVDS', ip: '192.168.1.29', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_11'
Driver info: driver.version: PrototypeServer_WD$CustomRemoteWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:154)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:657)
	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:334)
	at ResearchDevelopment.PrototypeServer_WD$CustomRemoteWebDriver.startSession(PrototypeServer_WD.java:56)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at ResearchDevelopment.PrototypeServer_WD$CustomRemoteWebDriver.<init>(PrototypeServer_WD.java:46)
	at ResearchDevelopment.PrototypeServer_WD.main(PrototypeServer_WD.java:34)
Exception in thread "main" java.lang.NoSuchMethodError: com.google.gson.GsonBuilder.setLenient()Lcom/google/gson/GsonBuilder;
	at org.openqa.selenium.json.Json.<clinit>(Json.java:47)
	at org.openqa.selenium.logging.profiler.HttpProfilerLogEntry.constructMessage(HttpProfilerLogEntry.java:37)
	at org.openqa.selenium.logging.profiler.HttpProfilerLogEntry.<init>(HttpProfilerLogEntry.java:29)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at ResearchDevelopment.PrototypeServer_WD$CustomRemoteWebDriver.startSession(PrototypeServer_WD.java:65)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at ResearchDevelopment.PrototypeServer_WD$CustomRemoteWebDriver.<init>(PrototypeServer_WD.java:46)
	at ResearchDevelopment.PrototypeServer_WD.main(PrototypeServer_WD.java:34)
Disconnected from the target VM, address: '127.0.0.1:18126', transport: 'socket'
```

Exception not dependence at type of browser. However this code already was worked two month ago. I cannot understand, what was changed. I wrote this issue, because now i have advanced "Instance Engine" for my automated-test-platform, that by on this simple prototype. And today i get same problem in it. After that i decide a checking simple prototype...

Any suggestion will be are welcome!

**Comment by S-Kerrigan** [comment]
**UPD:**
Really, sorry of my the issue, i confused.
But i caned found the cause of trouble - it package from Yandex of extensions for WebDriver (subsystem for creation screenshots to full height of pages).  After i removed it from pom.xml  my code also working again. So, please, close issue.
