### ISSUE TITLE
Error if open Firefox Webdriver with Adblock Plus Extension (Python)

### ISSUE THREAD

**Issue by fdsghdsgfds** [SeleniumHQ/selenium#527]
I want to open Firefox 37.0.2 with Python Webdriver 2.45.0 and the Adblock Plus Extension.

Here's my code:

> from selenium import webdriver
> 
> ffprofile = webdriver.FirefoxProfile()
> ffprofile.add_extension(extension='adblock.xpi')
> driver = webdriver.Firefox(firefox_profile=ffprofile)

I get the following error:

```
Traceback (most recent call last): File "adblock_test.py", line 6, in ffprofile.add_extension(extension='adblock.xpi') File "C:\Python34\lib\site-packages\selenium\webdriver\firefox\firefox_profile .py", line 92, in add_extension self._install_extension(extension) File "C:\Python34\lib\site-packages\selenium\webdriver\firefox\firefox_profile .py", line 269, in _install_extension addon_details = self._addon_details(addon) File "C:\Python34\lib\site-packages\selenium\webdriver\firefox\firefox_profile .py", line 341, in _addon_details manifest = f.read() File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode return codecs.charmap_decode(input,self.errors,decoding_table)[0] UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 964: char acter maps to undefined
```

Other Extensions work with exactly this code without problems. Only the Adblock Plus Extension (https://addons.mozilla.org/de/firefox/addon/adblock-plus/) doesn't work.

A User at StackOverflow (http://stackoverflow.com/questions/30071156/open-firefox-webdriver-with-adblock-plus-extension-python) told me the reason:

> The reason for this is adblock plus manifest file contains some unicode characters.
> 
> Change code in selenium/webdriver/firefox/firefox_profile.py
>     with open(os.path.join(addon_path, 'install.rdf'), 'r') as f:
>     to with open(os.path.join(addon_path, 'install.rdf'), 'r', encoding='utf8') as f:

So I think this should be fixed at selenium side.

**Comment by FrnkVieira** [comment]
I have the same problem. I think selenium should let us choose the encoding...

**Comment by lmtierney** [comment]
Pending #1598

**Comment by lmtierney** [comment]
Is this still an issue now that Firefox uses WebExtensions?

**Comment by diemol** [comment]
#1598 deferred to #4093 which is already solved, and we never got a response from the OP here. Closing.
