### ISSUE TITLE
org.openqa.selenium.remote.ProtocolHandshake createSession INFO: Detected dialect: OSS FAILED: first

### ISSUE THREAD

**Issue by sjdptn** [SeleniumHQ/selenium#5321]
I was executing ios mobile app script . It installing the app and launching it....but immediately after this , script is failing:

package appium;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import io.appium.java_client.ios.IOSDriver;

public class NewTest {
	@SuppressWarnings({ "rawtypes" })
	private IOSDriver driver;

  @SuppressWarnings("rawtypes")
@Test
  public void first() throws MalformedURLException, InterruptedException {
	  DesiredCapabilities caps = new DesiredCapabilities();
	  caps.setCapability("platformName", "iOS");
	  caps.setCapability("platformVersion", "11.0"); 
	  caps.setCapability("deviceName", "iPhone 7"); 
	  caps.setCapability("automationName", "XCUITest");
	  caps.setCapability("app", "/Users/preeti/Library/Developer/Xcode/DerivedData/Kiosk-cqqwwmdzdfarneanaqslqyqicatp/Build/Products/Debug-iphonesimulator/Kiosk.app"); 
	  driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), caps);
	  driver.findElement(By.xpath("//XCUIElementTypeButton[@name=\"SKIP\"]")).click();
	  
	 

}
}

Getting the following error:
[RemoteTestNG] detected TestNG version 6.13.1
Jan 10, 2018 6:45:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
FAILED: first
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at io.appium.java_client.HasSessionDetails.lambda$0(HasSessionDetails.java:48)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at com.google.common.collect.CollectSpliterators$1.lambda$forEachRemaining$1(CollectSpliterators.java:115)
	at com.google.common.collect.CollectSpliterators$1.lambda$forEachRemaining$1(CollectSpliterators.java:115)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at com.google.common.collect.CollectSpliterators$1.forEachRemaining(CollectSpliterators.java:115)
	at com.google.common.collect.CollectSpliterators$1.forEachRemaining(CollectSpliterators.java:115)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.appium.java_client.HasSessionDetails.getSessionDetails(HasSessionDetails.java:51)
	at io.appium.java_client.HasSessionDetails.getSessionDetail(HasSessionDetails.java:55)
	at io.appium.java_client.HasSessionDetails.getPlatformName(HasSessionDetails.java:62)
	at io.appium.java_client.internal.JsonToMobileElementConverter.<init>(JsonToMobileElementConverter.java:52)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
	at appium.NewTest.first(NewTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

**Comment by barancev** [comment]
This is a configuration issue, you shoud add missing libraries to the classpath.

**Comment by sjdptn** [comment]
can you let me know what could be the missing library here. I added all the jar files to the Java build path . Attaching the screen shot.
![screen shot 2018-01-11 at 11 27 45 am](https://user-images.githubusercontent.com/35220394/34810617-802d80de-f6c2-11e7-810c-7788773697d1.png)

**Comment by barancev** [comment]
commons-lang3

Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
