### ISSUE TITLE
IllegalArgumentException on Hub using Chrome

### ISSUE THREAD

**Issue by AidanMcD** [SeleniumHQ/selenium#5340]
## Meta -
OS:  Windows 7
Selenium Version: 3.8.1
Browser:  Chrome

With the following setup I am getting an Exception on the hub 
Setup details and code are below.

Grid Config :
HUB:
selenium-server-standalone-3.8.1
command line :

java -jar selenium-server-standalone-3.8.1.jar -role hub -hubConfig hubconfig.json

Config file:

{
"port": 8100,
"newSessionWaitTimeout": -1,
"servlets" : [],
"withoutServlets": [],
"custom": {},
"capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
"registryClass": "org.openqa.grid.internal.DefaultGridRegistry",
"throwOnCapabilityNotPresent": true,
"cleanUpCycle": 5000,
"role": "hub",
"debug": false,
"browserTimeout": 0,
"timeout": 1800
}

Node:

ChromeDriver : v 2.34.522940
selenium-server-standalone-3.8.1

command line :
java -Dwebdriver.gecko.driver="pathtogecko\geckodriver.exe" -jar selenium-server-standalone-3.8.1.jar -role node -nodeConfig nodeconfig.json

Browsers:
Chrome : 63.0.3239.132
Config:

{
"capabilities":
[
{
"browserName": "firefox",
"marionette": true,
"maxInstances": 2,
"seleniumProtocol": "WebDriver"
},
{
"browserName": "chrome",
"maxInstances": 2,
"seleniumProtocol": "WebDriver"
}
],
"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
"maxSession": 5,
"port": 5555,
"register": true,
"registerCycle": 5000,
"hub": "http://10.24x.14x.xxx:8100",
"nodeStatusCheckTimeout": 5000,
"nodePolling": 5000,
"role": "node",
"unregisterIfStillDownAfter": 60000,
"downPollingLimit": 2,
"debug": false,
"servlets" : [],
"withoutServlets": [],
"custom": {}
}
Code:
Chrome:
try
{
ChromeOptions chromeoptions = new ChromeOptions();
chromeoptions.AddArgument("--start-maximized");
chromeoptions.AddArgument("incognito");
chromeoptions.AddUserProfilePreference("credentials_enable_service", false);
chromeoptions.AddUserProfilePreference("profile.password_manager_enabled", false);
_driver = new RemoteWebDriver(new Uri(hub_url),chromeoptions);
_driver.Manage().Cookies.DeleteAllCookies();
_driver.FileDetector = new LocalFileDetector();
}
catch (Exception e)
{
Console.Write(e.Message);
}

Errors

Chrome:

Actual Behaviour:

The following Exception appears ,
java.lang.IllegalArgumentException: Illegal key values seen in w3c capabilities: [chromeOptions, javascriptEnabled]  , on the hub.

**Comment by barancev** [comment]
Can you reproduce this issue without grid, using local chrome and `new ChromeDriver(chromeoptions)`?

**Comment by AidanMcD** [comment]
Hi Alexei
I'm using the following versions 

local 61.0.3163.100
Grid 63.0.3239.132

The local code looks like 
```
                 ChromeDriverService service = ChromeDriverService.CreateDefaultService(driverpath);
                  service.SuppressInitialDiagnosticInformation = true;
                  service.HideCommandPromptWindow = true;
                  service.EnableVerboseLogging = true;

                    var options = new ChromeOptions();
                    options.BinaryLocation=@"C:\xxxxxx\chrome\chrome.exe";
                    options.AddArgument("--enable-logging");
                    options.AddLocalStatePreference("verbose_logging", true);
                    options.AddArgument("start-maximized");
                    _driver = new ChromeDriver(service,options);
                    _driver.Manage().Cookies.DeleteAllCookies();
```
If I remove the service Chrome doesn't work ???

**Comment by AidanMcD** [comment]
The complete error is 

```
2018-01-16 10:36:35.917:WARN:osjs.HttpChannel:qtp336484883-16: /wd/hub/session
java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: 
{
	"desiredCapabilities":
	{
		"browserName":"chrome",
		"version":"","platform":"ANY",
		"javascriptEnabled":true,
		"chromeOptions":
		{
			"args":["--start-maximized","incognito"],
			"prefs":
			{
				"credentials_enable_service":false,
				"profile.password_manager_enabled":false
			}
		}
	}
	,"capabilities":
	{
		"firstMatch":
		[
			{
				"browserName":"chrome",
				"javascriptEnabled":true,
				"chromeOptions":
				{
					"args":["--start-maximized","incognito"],
					"prefs":
					{
						"credentials_enable_service":false,
						"profile.password_manager_enabled":false
					}
				}
			}
		]
	}
}
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:135)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:561)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:334)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:104)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
        at java.lang.Thread.run(Thread.java:748)
Caused by:
org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"desiredCapabilities":{"browserName":"chrome","versio
n":"","platform":"ANY","javascriptEnabled":true,"chromeOptions":{"args":["--start-maximized","incognito"],"prefs":{"credentials_enable_service":false,
"profile.password_manager_enabled":false}}},"capabilities":{"firstMatch":[{"browserName":"chrome","javascriptEnabled":true,"chromeOptions":{"args":["-
-start-maximized","incognito"],"prefs":{"credentials_enable_service":false,"profile.password_manager_enabled":false}}}]}}
        at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:76)
        at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.<init>(SeleniumBasedRequest.java:102)
        at org.openqa.grid.web.servlet.handler.WebDriverRequest.<init>(WebDriverRequest.java:36)
        at org.openqa.grid.web.servlet.handler.WebDriverRequestFactory.createFromRequest(WebDriverRequestFactory.java:30)
        at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.createFromRequest(SeleniumBasedRequest.java:73)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:82)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:561)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:334)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:104)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
        at java.lang.Thread.run(Thread.java:748)
Caused by:
java.lang.IllegalArgumentException: Illegal key values seen in w3c capabilities: [chromeOptions, javascriptEnabled]
        at org.openqa.selenium.remote.NewSessionPayload.lambda$validate$6(NewSessionPayload.java:211)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.openqa.selenium.remote.NewSessionPayload.validate(NewSessionPayload.java:215)
        at org.openqa.selenium.remote.NewSessionPayload.<init>(NewSessionPayload.java:163)
        at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:118)
        at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:66)
        at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.<init>(SeleniumBasedRequest.java:102)
        at org.openqa.grid.web.servlet.handler.WebDriverRequest.<init>(WebDriverRequest.java:36)
        at org.openqa.grid.web.servlet.handler.WebDriverRequestFactory.createFromRequest(WebDriverRequestFactory.java:30)
        at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.createFromRequest(SeleniumBasedRequest.java:73)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:82)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:561)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:334)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:104)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by AidanMcD** [comment]
Guys not sure because I can't test it 
But this could this be an issue with the Regex in NewSessionPayLoad.java line 86 
see "^[\\w-]+:.*$"

**Comment by shs96c** [comment]
The server is behaving according to the spec, as the `firstMatch` contains `javascriptEnabled`, which is not a valid W3C capability name. Nor is `chromeOptions`. I suspect this may have something to do with the way that the .Net `RemoteWebDriver` is encoding the session payload, but I'd need to dig deeper to be sure.

**Comment by shs96c** [comment]
Hmmm... This can only happen if the `ChromeOptions` capabilities claim to be spec compliant. Maybe I am entirely mistaken....

**Comment by AidanMcD** [comment]
Sry for the red herring with the regex

**Comment by AidanMcD** [comment]
Please close opened to through my own stupidity LOL

**Comment by shs96c** [comment]
Always happy to close an issue :) Glad things are better now!
