### ISSUE TITLE
EPIPE write EPIPE error

### ISSUE THREAD

**Issue by ionakathryn** [SeleniumHQ/selenium#5345]
## Meta -
OS:  Mac OS High Sierra

Selenium Version:  WebdriverJS 

Browser:  Chrome

Browser Version:  63.0

## Expected Behavior -
All tests should run, instead of passing undefined back to function, custom value should be passed back

## Actual Behavior -
I am getting the below error, which as a result is failing my step as the value being passed back is undefined as opposed to the value null, which I declared. This behaviour is sporadic and happens consistently however in different step definitions. After doing some reading, it looks like it might be as I'm using Promise.all() in one of the functions I'm using:

`
Error: EPIPE write EPIPE
    at ClientRequest.<anonymous> (/Users/iona-kathrynevans/Desktop/UIAutomation2/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:392:12)
    at onwrite (_stream_writable.js:414:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at Socket._destroy (net.js:556:3)`

**Comment by jleyba** [comment]
What version of selenium-webdriver are you using?

**Comment by ionakathryn** [comment]
I am using webdriver.js and the version is 0.1.1-r18456.
The version of Selenium webdriver itself is 3.4.0

**Comment by jleyba** [comment]
> I am using webdriver.js and the version is 0.1.1-r18456.

Not sure what this is, but it's not a version from this project.

> The version of Selenium webdriver itself is 3.4.0

The latest version on npm, `selenium-webdriver@4.0.0-alpha.1`, should handle EPIPE errors.

**Comment by ionakathryn** [comment]
OK thank you, installing the latest version of webdriver worked. I noticed some functions such as .manage() no longer work so will have to refactor. However this solved the EPIPE error, so thank you!
