### ISSUE TITLE
Improvement for org.openqa.selenium.interactions.Actions

### ISSUE THREAD

**Issue by raveeolee** [SeleniumHQ/selenium#5346]
## Meta
Selenium Version:  3.8.1,  selenium-java

I have come across an issue with custom or wrapped WebElements I usually write on different projects in order to better describe business logic, sometimes waits, hovers etc. 

While there is a pretty straightforward workaround for this issue. Out curiosity I've decided to ask community if this can improved on the framework level.

So please let me know your thoughts. Thank you!

## Expected Behavior

CustomWebElement implements WebElement and WrapsElement so it does indicate it is wrapper. Not sure I understand the reason of having to deal with _org.openqa.selenium.interactions.internal.Locatable_ as well.  

What makes me think so? dotnet implementation: 
https://github.com/SeleniumHQ/selenium/blob/116381906db8c62a85d84fea57024263ef6953d9/dotnet/src/webdriver/Interactions/Actions.cs#L49

And also in selenium-java

https://github.com/SeleniumHQ/selenium/blob/116381906db8c62a85d84fea57024263ef6953d9/java/client/src/org/openqa/selenium/remote/internal/WebElementToJsonConverter.java#L50

## Actual Behavior

```
Exception in thread "main" java.lang.ClassCastException: Main$CustomWebElement cannot be cast to org.openqa.selenium.interactions.internal.Locatable
	at org.openqa.selenium.interactions.Actions.moveToElement(Actions.java:388)
	at Main.main(Main.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

```

## Steps to reproduce
1. Create wrapped WebElement implementation.
```
public class CustomWebElement implements WebElement, WrapsElement {
        private final WebElement realWebElement;

        CustomWebElement(WebElement element) {
            this.realWebElement = element;
        }

        public WebElement getWrappedElement() {
            return realWebElement;
        }

        public void click() {
            realWebElement.click();
        }

        public void submit() {
            realWebElement.submit();
        }

        public void sendKeys(CharSequence... keysToSend) {
            realWebElement.sendKeys(keysToSend);
        }

        public void clear() {
            realWebElement.clear();
        }

        public String getTagName() {
            return realWebElement.getTagName();
        }

        public String getAttribute(String name) {
            return realWebElement.getAttribute(name);
        }

        public boolean isSelected() {
            return realWebElement.isSelected();
        }

        public boolean isEnabled() {
            return realWebElement.isEnabled();
        }

        public String getText() {
            return realWebElement.getText();
        }

        public List<WebElement> findElements(By by) {
            return realWebElement.findElements(by);
        }

        public WebElement findElement(By by) {
            return realWebElement.findElement(by);
        }

        public boolean isDisplayed() {
            return realWebElement.isDisplayed();
        }

        public Point getLocation() {
            return realWebElement.getLocation();
        }

        public Dimension getSize() {
            return realWebElement.getSize();
        }

        public Rectangle getRect() {
            return realWebElement.getRect();
        }

        public String getCssValue(String propertyName) {
            return realWebElement.getCssValue(propertyName);
        }

        public <X> X getScreenshotAs(OutputType<X> target) throws WebDriverException {
            return realWebElement.getScreenshotAs(target);
        }
    }
```
2. Try to use Actions class with CustomWebElement
```
public static void main(String[] args) {

        WebDriver driver = new ChromeDriver();
        driver.get("http://google.com");


        WebElement searchButton = driver.findElement(By.cssSelector("input[type='submit']:nth-of-type(1)"));
       // Wrap it in CustomWebElement
        WebElement customSearchElement = new CustomWebElement(searchButton);

        Actions actions = new Actions(driver);

        // This works
        actions.moveToElement(searchButton).build().perform();

        // The same for CustomWebElement throws exception java.lang.ClassCastException
        actions.moveToElement(customSearchElement).build().perform();
    }
```

## Possible fix
So in _org.openqa.selenium.interactions.Actions_ something like:
```
public Locatable getLocatableFromElement(WebElement element) {
        WebElement target = element;
        while (target instanceof WrapsElement) {
            target = ((WrapsElement) target).getWrappedElement();
        }
        return (Locatable) target;
    }
```

And to refactor methods in Actions and derived classes like: 
```
public Actions moveToElement(WebElement target) {
    WebElement realTarget = getLocatableFromElement(target);
    if (isBuildingActions()) {
      action.addAction(new MoveMouseAction(jsonMouse, realTarget));
    }

    return moveInTicks(target, 0, 0);
  }
```

## Workaround
CustomWebElement to implement org.openqa.selenium.interactions.internal.Locatable and to delegate Coordinates getCoordinates() to underlying realWebElement.

## Links
Also found people to raise similar issues:
https://github.com/SeleniumHQ/selenium/issues/5231
https://github.com/SeleniumHQ/selenium/issues/4577

Thank you. I look forward to hearing from you.

**Comment by diemol** [comment]
I will close this issue since it went stale and the community did not give more feedback to see if this was a needed use case.

In any case, if this is a needed feature, please feel free to raise a PR with enough context given in it.
