### ISSUE TITLE
Issues with using the new safari driver with selenium in javascript

### ISSUE THREAD

**Issue by paladox** [SeleniumHQ/selenium#5402]
## Meta -
OS:  OSX 10.13.3
Selenium Version:  3.7.1
Browser:  safari

Browser Version:  11.0.3 (13604.5.6)

## Expected Behavior -
tests to pass

## Actual Behavior -
tests are failing with this stack trace

```
safari 11.0.3            Tests failed: {"value":{"stacktrace":"org.openqa.selenium.SessionNotCreatedException: Could not create a session: The session timed out while connecting to a Safari instance. (WAR
NING: The server did not provide any stacktrace information)\nCommand duration or timeout: 30.44 seconds\nBuild info: version: \u00273.7.1\u0027, revision: \u00278a0099a\u0027, time: \u00272017-11-06T21:0
7:36.161Z\u0027\nSystem info: host: \u0027Patricks-MBP\u0027, ip: \u0027192.168.1.231\u0027, os.name: \u0027Mac OS X\u0027, os.arch: \u0027x86_64\u0027, os.version: \u002710.13.3\u0027, java.version: \u00271.8.0_161\u0027\nDriver info: driver.version: unknown\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)\n\tat org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)\n\tat org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)\n\tat org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)\n\tat org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)\n\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\n\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\n\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)\n\tat org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:218)\n\tat org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$11(ActiveSessionFactory.java:167)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\tat java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)\n\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\n\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\n\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\n\tat org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:170)\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$1(NewSessionPipeline.java:44)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.Collections$2.tryAdvance(Collections.java:4717)\n\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\n\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\n\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$2(NewSessionPipeline.java:47)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\tat java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405)\n\tat java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)\n\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\n\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\n\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:50)\n\tat org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:77)\n\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:240)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","stackTrace":[{"fileName":"NativeConstructorAccessorImpl.java","methodName":"newInstance0","className":"sun.reflect.NativeConstructorAccessorImpl","lineNumber":-2},{"fileName":"NativeConstructorAccessorImpl.java","methodName":"newInstance","className":"sun.reflect.NativeConstructorAccessorImpl","lineNumber":62},{"fileName":"DelegatingConstructorAccessorImpl.java","methodName":"newInstance","className":"sun.reflect.DelegatingConstructorAccessorImpl","lineNumber":45},{"fileName":"Constructor.java","methodName":"newInstance","className":"java.lang.reflect.Constructor","lineNumber":423},{"fileName":"ErrorHandler.java","methodName":"createThrowable","className":"org.openqa.selenium.remote.ErrorHandler","lineNumber":214},{"fileName":"ErrorHandler.java","methodName":"throwIfResponseFailed","className":"org.openqa.selenium.remote.ErrorHandler","lineNumber":166},{"fileName":"JsonWireProtocolResponse.java","methodName":"lambda$new$0","className":"org.openqa.selenium.remote.JsonWireProtocolResponse","lineNumber":53},{"fileName":"JsonWireProtocolResponse.java","methodName":"lambda$getResponseFunction$2","className":"org.openqa.selenium.remote.JsonWireProtocolResponse","lineNumber":91},{"fileName":"ProtocolHandshake.java","methodName":"lambda$createSession$0","className":"org.openqa.selenium.remote.ProtocolHandshake","lineNumber":123},{"fileName":"ReferencePipeline.java","methodName":"accept","className":"java.util.stream.ReferencePipeline$3$1","lineNumber":193},{"fileName":"Spliterators.java","methodName":"tryAdvance","className":"java.util.Spliterators$ArraySpliterator","lineNumber":958},{"fileName":"ReferencePipeline.java","methodName":"forEachWithCancel","className":"java.util.stream.ReferencePipeline","lineNumber":126},{"fileName":"AbstractPipeline.java","methodName":"copyIntoWithCancel","className":"java.util.stream.AbstractPipeline","lineNumber":498},{"fileName":"AbstractPipeline.java","methodName":"copyInto","className":"java.util.stream.AbstractPipeline","lineNumber":485},{"fileName":"AbstractPipeline.java","methodName":"wrapAndCopyInto","className":"java.util.stream.AbstractPipeline","lineNumber":471},{"fileName":"FindOps.java","methodName":"evaluateSequential","className":"java.util.stream.FindOps$FindOp","lineNumber":152},{"fileName":"AbstractPipeline.java","methodName":"evaluate","className":"java.util.stream.AbstractPipeline","lineNumber":234},{"fileName":"ReferencePipeline.java","methodName":"findFirst","className":"java.util.stream.ReferencePipeline","lineNumber":464},{"fileName":"ProtocolHandshake.java","methodName":"createSession","className":"org.openqa.selenium.remote.ProtocolHandshake","lineNumber":126},{"fileName":"ProtocolHandshake.java","methodName":"createSession","className":"org.openqa.selenium.remote.ProtocolHandshake","lineNumber":73},{"fileName":"ServicedSession.java","methodName":"apply","className":"org.openqa.selenium.remote.server.ServicedSession$Factory","lineNumber":218},{"fileName":"ActiveSessionFactory.java","methodName":"lambda$apply$11","className":"org.openqa.selenium.remote.server.ActiveSessionFactory","lineNumber":167},{"fileName":"ReferencePipeline.java","methodName":"accept","className":"java.util.stream.ReferencePipeline$3$1","lineNumber":193},{"fileName":"ReferencePipeline.java","methodName":"accept","className":"java.util.stream.ReferencePipeline$3$1","lineNumber":193},{"fileName":"ReferencePipeline.java","methodName":"accept","className":"java.util.stream.ReferencePipeline$11$1","lineNumber":373},{"fileName":"ReferencePipeline.java","methodName":"accept","className":"java.util.stream.ReferencePipeline$2$1","lineNumber":175},{"fileName":"Spliterators.java","methodName":"tryAdvance","className":"java.util.Spliterators$ArraySpliterator","lineNumber":958},{"fileName":"ReferencePipeline.java","methodName":"forEachWithCancel","className":"java.util.stream.ReferencePipeline","lineNumber":126},{"fileName":"AbstractPipeline.java","methodName":"copyIntoWithCancel","className":"java.util.stream.AbstractPipeline","lineNumber":498},{"fileName":"AbstractPipeline.java","methodName":"copyInto","className":"java.util.stream.AbstractPipeline","lineNumber":485},{"fileName":"AbstractPipeline.java","methodName":"wrapAndCopyInto","className":"java.util.stream.AbstractPipeline","lineNumber":471},{"fileName":"FindOps.java","methodName":"evaluateSequential","className":"java.util.stream.FindOps$FindOp","lineNumber":152},{"fileName":"AbstractPipeline.java","methodName":"evaluate","className":"java.util.stream.AbstractPipeline","lineNumber":234},{"fileName":"ReferencePipeline.java","methodName":"findFirst","className":"java.util.stream.ReferencePipeline","lineNumber":464},{"fileName":"ActiveSessionFactory.java","methodName":"apply","className":"org.openqa.selenium.remote.server.ActiveSessionFactory","lineNumber":170},{"fileName":"NewSessionPipeline.java","methodName":"lambda$null$:

```
## Steps to reproduce -
Use web component tester 2.5.0+ https://github.com/Polymer/web-component-tester

1. run tests with web-component-tester you could use gerrit to reproduce this, see https://github.com/GerritCodeReview/gerrit (needs bazel installed)
2. polygerrit_ui/app/run-test.sh

Im not sure if there needs to be any changes in wct to support the new safari driver?

**Comment by jleyba** [comment]
Looks like [wct is using](https://github.com/Polymer/web-component-tester/blob/master/runner/browserrunner.ts#L18) the [wd](https://www.npmjs.com/package/wd) library, which is not provided/supported by this project.

You'll need to file a bug against the [wd project](https://www.npmjs.com/package/wd)

**Comment by paladox** [comment]
@jleyba i guess the selenium-webdriver is similar to wd?

**Comment by jleyba** [comment]
Yes, but it's intended to be lower level and just focus on the Selenium API. wd aims to provide a more full featured test framework.

Take a look at the [examples](https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver/example).

For Safari, if you're running locally, it should just work for Safari 11:

```shell
npm install selenium-webdriver
SELENIUM_BROWSER=safari node node_modules/selenium-webdriver/example/google_search.js
```

**Comment by jgros32** [comment]
I also experience this using this version of my safari and macOS
1.	Safari Browser Version 11.0.3
2.	macOS Sierra Version 10.12.6

-	I’ve installed “SafariDriver.safariextz” manually.
-	Enable Remote Automation in the Develop menu. This is toggled via Develop > Allow Remote Automation in the menu bar.
-	Authorize safaridriver to launch the webdriverd service which hosts the local web server. To permit this, run /usr/bin/safaridriver once manually and complete the authentication prompt.

I open my hub to my windows machine and trying to run it on my macOS machine.
Same error was displayed on my node terminal. See logs below:

18:38:30.252 INFO - Launching Safari
18:38:30.275 INFO - Waiting for SafariDriver to connect
18:38:40.279 INFO - Shutting down
18:38:40.279 INFO - Stopping Safari
18:38:40.338 INFO - Stopping server
18:38:40.338 INFO - Stopping server
18:38:40.345 INFO - Shutdown complete
18:38:40.346 INFO - Shutting down
18:38:40.346 INFO - Stopping server
18:38:40.346 INFO - Shutdown complete
18:38:40.533 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'MLA1925591D', ip: '10.50.6.88', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_161'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'MLA1925591D', ip: '10.50.6.88', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_161'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
	... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10070 ms
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'MLA1925591D', ip: '10.50.6.88', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_161'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:121)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:76)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:62)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:53)
	... 14 more
18:38:40.538 WARN - Exception: Failed to connect to SafariDriver after 10070 ms
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'MLA1925591D', ip: '10.50.6.88', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_161'
Driver info: driver.version: SafariDriver

**Comment by gvrrvenkat** [comment]
Hi Could please provide the solution for this issue?

**Comment by InkUisitor** [comment]
Someone has found a solution to this issue ? I have the same problem. I have the same stacktrace and sometimes my test runs correctly. Why is this issue closed ?

**Comment by paladox** [comment]
@jleyba hi, is JavaScript supported for starting the safari driver?

**Comment by cgoldberg** [comment]
> Why is this issue closed ?

@InkUisitor 
Because the OP had an issue with `web-component-tester` from Polymer, which is based on the `wd` library.  Since the `wd` library is not provided by this project, the issue is not relevant here.

If you do have an issue with something supported by the Selenium project, please file a *new* issue report with proper details.

**Comment by anoop52172** [comment]
Any clue on resolving the issue as stated by jgros32 I am also facing the same issue


18:38:30.252 INFO - Launching Safari
 18:38:30.275 INFO - Waiting for SafariDriver to connect
 18:38:40.279 INFO - Shutting down
 18:38:40.279 INFO - Stopping Safari
 18:38:40.338 INFO - Stopping server
 18:38:40.338 INFO - Stopping server
 18:38:40.345 INFO - Shutdown complete
 18:38:40.346 INFO - Shutting down
 18:38:40.346 INFO - Stopping server
 18:38:40.346 INFO - Shutdown complete
 18:38:40.533 WARN - Exception thrown
 java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
 Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
 System info: host: 'MLA1925591D', ip: '10.50.6.88', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_161'
 Driver info: driver.version: unknown
 at java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.util.concurrent.FutureTask.get(FutureTask.java:192)
 at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
 at org.openqa.selenium.remote.server.DefaultSession.(DefaultSession.java:119)
 at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
 at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
 at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
 at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
 at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
 at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
 at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
 at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
 at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
 at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
 at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
 at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
 at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
 at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
 at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
 at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
 at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
 at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
 at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
 at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
 at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
 Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
 Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
 System info: host: 'MLA1925591D', ip: '10.50.6.88', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_161'
 Driver info: driver.version: unknown
 at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
 at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
 at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
 at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
 at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
 Caused by: java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
 ... 9 more
 Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10070 ms
 Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
 System info: host: 'MLA1925591D', ip: '10.50.6.88', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_161'
 Driver info: driver.version: SafariDriver
 at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:121)
 at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:76)
 at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:119)
 at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:144)
 at org.openqa.selenium.safari.SafariDriver.(SafariDriver.java:62)
 at org.openqa.selenium.safari.SafariDriver.(SafariDriver.java:53)
 ... 14 more
 18:38:40.538 WARN - Exception: Failed to connect to SafariDriver after 10070 ms
 Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
 System info: host: 'MLA1925591D', ip: '10.50.6.88', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_161'
 Driver info: driver.version: SafariDriver

**Comment by anoop52172** [comment]
For me the issue is Fixed first I tried 
Run safaridriver --enable once,from directory usr/bin (If you’re upgrading from a previous macOS release, you may need to use sudo. Safari’s executable is located at /usr/bin/safaridriver )
After that I used safari version 3.4.0 jar file to run node and hub command.
