### ISSUE TITLE
Timed out receiving message from renderer

### ISSUE THREAD

**Issue by AllenLink** [SeleniumHQ/selenium#5405]
## Meta -
OS:  Window XP
Selenium Version:  3.60
Browser:  chrome
Browser Version: 49.0.2623.112 (32-bit) 

 (Session info: chrome=49.0.2623.112)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 5.1 SP3 x86)
Traceback (most recent call last):
  File "<string>", line 141, in <module>
  File "E:\Code\Python\AutoOptimize\autooptimize\operateprocess\processFactory.py", line 42, in excecute
  File "E:\Code\Python\AutoOptimize\autooptimize\operateprocess\baiduMapProcess.py", line 45, in execute
  File "C:\Users\Administrator\AppData\Roaming\Python\Python34\site-packages\splinter\driver\webdriver\__init__.py", line 185, in visit
  File "C:\Users\Administrator\AppData\Roaming\Python\Python34\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in get
  File "C:\Users\Administrator\AppData\Roaming\Python\Python34\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
  File "C:\Users\Administrator\AppData\Roaming\Python\Python34\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.486
  (Session info: chrome=49.0.2623.112)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 5.1 SP3 x86)

My computer is old and very slow。But this problem happend inconditiontly.How can I add the time of renderer.

**Comment by barancev** [comment]
This is a chromedriver issue, you can try to report it to [1], but they will hardly fix it in so much outdated versions of the browser and the driver.

[1] https://sites.google.com/a/chromium.org/chromedriver/help
