### ISSUE TITLE
unable to use selenium with RPi 0 W

### ISSUE THREAD

**Issue by cubetastic33** [SeleniumHQ/selenium#5423]
## Meta -
OS:  
Raspbian
Browser:
Firefox

## Expected Behavior -
The program should run
## Actual Behavior -
It's not running. It is giving me the following error (python 3.5):

Traceback (most recent call last):
  File "/home/pi/Desktop/TNoodle/get_scramble.py", line 5, in <module>
    driver = webdriver.Firefox()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

**Comment by lmtierney** [comment]
First, make sure you're using the `ARM` version of geckodriver https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-arm7hf.tar.gz

Second, this would be an issue with geckodriver. Please report if there if you still have issues after using the arm version. https://github.com/mozilla/geckodriver/issues

**Comment by cubetastic33** [comment]
@lmtierney well, I tried again with the ARM version, and I am still getting an error. This seems to be with selenium:
Traceback (most recent call last):
  File "/home/pi/Desktop/TNoodle/get_scramble.py", line 5, in <module>
    driver = webdriver.Firefox()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -11

**Comment by lmtierney** [comment]
This does not appear to be a selenium issue, please report to geckodriver.
