### ISSUE TITLE
3.9.0 Grid - Java - SocketTimeout after around 6 tests firing simultaneously

### ISSUE THREAD

**Issue by thomhurst** [SeleniumHQ/selenium#5445]
## Meta -
OS:  
Windows Server - Grid
Selenium Version:  
3.9.0
Browser:  
Chrome

Using the grid, and firing 12 instances simultaneously at it, which loop a single test via a batch file, after around 6 or so tests kicked off (which seem to start and remain running), all the remaining tests fail immediately with a SocketTimeout, and keep looping and stacking up requests on the Grid

Exception:
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:97)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:47)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)

Grid requests:
58 requests waiting for a slot to be free.
Capabilities {browserName: chrome, goog:chromeOptions: {args: [start-maximized, disable-infobars], extensions: [], prefs: {credentials_enable_service: false}}, version: }Capabilities {browserName: chrome, goog:chromeOptions: {args: [start-maximized, disable-infobars], extensions: [], prefs: {credentials_enable_service: false}}, version: }Capabilities {browserName: chrome, goog:chromeOptions: {args: [start-maximized, disable-infobars], extensions: [], prefs: {credentials_enable_service: false}}, version: }Capabilities {browserName: chrome, goog:chromeOptions: {args: [start-maximized, disable-infobars], extensions: [], prefs: {credentials_enable_service: false}}, version: }Capabilities {browserName: chrome, goog:chromeOptions: {args: [start-maximized, disable-infobars], extensions: [], prefs: {credentials_enable_service: false}}, version: }

**Comment by mmanach** [comment]
Hello, 

Having same error since I updated selenium from 3.7.1 to 3.9.0 : 

```
Logout STANDARD_ERROR
    fÚvr. 07, 2018 3:21:23 PM org.openqa.selenium.support.ui.ExpectedConditions findElements
    AVERTISSEMENT: WebDriverException thrown by findElements(By.xpath: //div[contains(@class,'tc-notification-error')])
    org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
    Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:26:55.441Z'
    System info: host: 'xxx', ip: 'x.x.x.x', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
    Driver info: driver.version: RemoteWebDriver
    Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 57.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 32220, moz:profile
: C:\Users\xxxx\AppData\Lo..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000
, script: 30000}}
    Session ID: df3e423e-909f-41ea-bb01-e4000474ccfe
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
        at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:398)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:477)
        at org.openqa.selenium.By$ByXPath.findElements(By.java:356)
        at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:359)
        at net.thucydides.core.webdriver.WebDriverFacade.findElements(WebDriverFacade.java:261)
        at org.openqa.selenium.support.ui.ExpectedConditions.findElements(ExpectedConditions.java:914)
        at org.openqa.selenium.support.ui.ExpectedConditions.access$200(ExpectedConditions.java:44)
        at org.openqa.selenium.support.ui.ExpectedConditions$8.apply(ExpectedConditions.java:232)
        at org.openqa.selenium.support.ui.ExpectedConditions$8.apply(ExpectedConditions.java:229)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
        at net.serenitybdd.core.pages.RenderedPageObjectView.waitFor(RenderedPageObjectView.java:100)
        at net.serenitybdd.core.pages.RenderedPageObjectView.elementIsDisplayed(RenderedPageObjectView.java:206)
        at net.serenitybdd.core.pages.PageObject.isElementVisible(PageObject.java:854)
        at pages.BasePage.isErrorNotifPresent(BasePage.java:84)
        at steps.UICommonSteps.checkErrorNotification(UICommonSteps.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jbehave.core.steps.StepCreator$MethodInvoker.invoke(StepCreator.java:958)
        at org.jbehave.core.steps.StepCreator$BeforeOrAfterStep.perform(StepCreator.java:624)
        at org.jbehave.core.steps.StepCreator$BeforeOrAfterStep.doNotPerform(StepCreator.java:641)
        at org.jbehave.core.embedder.PerformableTree$SomethingHappened.run(PerformableTree.java:378)
        at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1090)
        at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:995)
        at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:904)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
        at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
        at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
        at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
        at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:230)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:97)
        at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:47)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:157)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        ... 36 more
    Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        ... 59 more
```

**Comment by HenningL** [comment]
the newest version 3.9.1 is working again
