### ISSUE TITLE
3.9.0 Java java.net.SocketTimeoutException: timeout when typing long string

### ISSUE THREAD

**Issue by baflQA** [SeleniumHQ/selenium#5447]
## Meta -
OS:  Mac OS X x86_64 10.13.3
Selenium Version:  3.9.0
Browser:  Chrome
Browser Version: 64
Driver: chromedriver 2.35

## Expected Behavior -
Text is typed in the textarea field
## Actual Behavior -
openqa.selenium.WebDriverException: java.net.SocketTimeoutException: timeout is thrown
## Steps to reproduce -
The page contains the textarea field with maxlength="500" attribute. I'm checking if only 500 chars can be typed in this field. 
Using Apache commons lang3 RandomStringUtils.randomAlphanumeric(501) method, I generate the String longer than 500chars, and then using sendKeys() method try to type this string in the textarea field. 
After some time, and some number of chars being sent, WebDriver throws the error. 

`Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:97)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:47)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:157)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)`

**Comment by Navsony** [comment]
Even I am facing same problem just for gmail login. @baflQA Did you get any solution for this.

OS: Windows 7 professional
Selenium Version: 3.9.0
Browser: Chrome
Browser Version: 64
Driver: chromedriver 2.33

org.openqa.selenium.WebDriverException: java.net.SocketTimeoutException: Read timed out
Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:26:55.441Z'
System info: host: 'BLR-DKS0831-2', ip: '172.16.123.170', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '9.0.1'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:325)
	at sample.LoginChrome.beforeMethod(LoginChrome.java:46)

**Comment by baflQA** [comment]
Yes, I found a really nice workaround - switched back to the 3.8.1 ;) 
It looks like @shs96c added some timeouts to OK Client already to handle this issue? Correct me if I'm wrong.

**Comment by barancev** [comment]
Please check if the issue is still actual in version 3.9.1

**Comment by Navsony** [comment]
i checked in 3.9.1. it's solved. Thanks @barancev

**Comment by baflQA** [comment]
I can confirm - 3.9.1 works fine.

**Comment by veerapulapakura** [comment]
3.9.1 working for me. thanks a lot

**Comment by SyedaQurat** [comment]
i am still facing this issue in 3.9.0. How to upgrade it on 3.9.1?
Please!
