### ISSUE TITLE
Can't launch chrome browser using latest selenium 3.9.0

### ISSUE THREAD

**Issue by jiteshsojitra** [SeleniumHQ/selenium#5453]
**Can't launch chrome browser using latest selenium 3.9.0**

OS: Windows 7 (shouldn't matter)
Selenium version: 3.9.0 latest
Chrome: 64.0 latest

Below code was working fine with 3.7.1 but started failing to launch chrome browser with latest 3.9.0.

# Regression of below change?

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/internal/OkHttpClient.java

# Code:

	ChromeOptions options = new ChromeOptions();
	Map<String, Object> preferences = new Hashtable<String, Object>();
	preferences.put("plugins.plugins_disabled", new String[] { "Adobe Flash Player", "Chrome PDF Viewer" });
	preferences.put("credentials_enable_service", false);
	preferences.put("password_manager_enabled", false);
	options.setExperimentalOption("prefs", preferences);
	options.addArguments("disable-infobars");
	options.addArguments("start-maximized");

	System.setProperty("webdriver.chrome.driver", driverFilePath);
	options.setCapability("chrome.switches", Arrays.asList("--disable-extensions"));
	options.setCapability(ChromeOptions.CAPABILITY, options);
	options.setCapability(CapabilityType.LOGGING_PREFS, logs);
	webDriver = new ChromeDriver(options);
	webDriver.manage().window().maximize();

# Exception:

	Caused by: java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:26)
		... 18 more
	Caused by: java.lang.NoClassDefFoundError: okhttp3/ConnectionPool
		at org.openqa.selenium.remote.internal.OkHttpClient$Factory.<init>(OkHttpClient.java:115)
		at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:72)
		at org.openqa.selenium.remote.HttpCommandExecutor.<clinit>(HttpCommandExecutor.java:49)
		at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
		at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
		at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
		at com.zimbra.qa.selenium.framework.core.ClientSession.webDriver(ClientSession.java:264)
		at com.zimbra.qa.selenium.projects.ajax.core.AjaxCore.<init>(AjaxCore.java:76)
		at com.zimbra.qa.selenium.projects.ajax.core.SetGroupMailByMessagePreference.<init>(SetGroupMailByMessagePreference.java:32)
		at com.zimbra.qa.selenium.projects.ajax.tests.mail.compose.delegates.SendOnBehalfOf.<init>(SendOnBehalfOf.java:28)
		... 23 more
	Caused by: java.lang.ClassNotFoundException: okhttp3.ConnectionPool
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 33 more

**Comment by amandeep12** [comment]
What is the chrome driver version you are using?
Try using the latest https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by jiteshsojitra** [comment]
I forgot to mention that, i'm using latest Chrome driver 2.35.

**Comment by jiteshsojitra** [comment]
Just now Selenium 3.9.1 released and provided some related fix but no luck!

v3.9.1
======

* OkHttp backed instances can now connect to servers requiring
  authorisation. Based on PR #5444 proposed by @valfirst.

v3.9.0
======

* Switched to OkHttp for all HTTP communication. The version used can
  be changed back to the Apache HttpClient by setting the
  `webdriver.http.factory` system property to `apache`.
* Removed passthrough mode for the server.
* Grid: (implementation note) Start migrating servlets used to be
  command handlers.
* Upgraded every dependency to latest versions.
* Added varargs methods to `ExpectedConditions` in order to avoid
  annoying `Arrays.asList`.
* Better logging when new session creation errors.

**Comment by barancev** [comment]
The error message "java.lang.NoClassDefFoundError: okhttp3/ConnectionPool" means that you have misconfigured classpath. Please tell us how do you run tests? What builder or IDE do you use? Provide the builder config file or project description.

**Comment by jiteshsojitra** [comment]
Thanks @barancev for giving me hint to fix the issue, expected in ivy was:
<dependency org="com.squareup.okhttp3" name="okhttp" rev="3.9.1"/>

**Comment by barancev** [comment]
selenium-java artifact has a dependency on okhttp, you can check here the list of dependencies: http://search.maven.org/#artifactdetails%7Corg.seleniumhq.selenium%7Cselenium-java%7C3.9.1%7Cjar
