### ISSUE TITLE
Connection exception error message is not helpful at all

### ISSUE THREAD

**Issue by JohnA2** [SeleniumHQ/selenium#5459]
Every once in a while I get exceptions like this when running Selenium tests on Grid

```
org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: java.net.ConnectException: Connection timed out: connect
Command duration or timeout: 0 milliseconds
org.openqa.selenium.WebDriverException: java.net.ConnectException: Connection timed out: connect
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:371)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:449)
	at org.openqa.selenium.By$ByName.findElement(By.java:303)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	...
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.WebDriverException: java.net.ConnectException: Connection timed out: connect
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'host where tests ran', ip: 'ip of the host where tests ran', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-696.18.7.el6.x86_64', java.version: '1.8.0_162'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

Unfortunately the only conclusion that I can make from this error is some connection somewhere timed out and the hostname/ip where the test itself was running.

It would be very useful to know where exactly the connection timeout occurred. As I understand it can be 4 cases:
- between the Selenium client and the Grid hub
- between the Grid hub and a Grid node (also need to know which one)
- between the Grid node and a WebDriver
- between the WebDriver and the browser

OS:
CentOS 6.9
Selenium Version:
3.8.1
Browser:
Chrome
Browser Version:
any

## Expected Behavior -
Ability to see the IPs/hostnames/ports and maybe type (client/hub/node/webdriver/browser) of instances between which the connection issue occurred.

## Actual Behavior -
No information where to look for issue.

## Steps to reproduce -
~~Run tests in a not 100% reliable environment to get a connection timeout or a similar issue.~~ See https://github.com/SeleniumHQ/selenium/issues/5631

**Comment by JohnA2** [comment]
If anybody is interested in the root cause for this particular error, see https://github.com/SeleniumHQ/selenium/issues/5631. The timeout happened between a Grid node and a WebDriver running on localhost, so it's not really a network issue as it seemed at first.

**Comment by diemol** [comment]
I will close this since we are not making any more changes to Grid 3.x
Nevertheless, Grid 4 has tracing enabled, which should allow you to understand better where the timeout happens on the Grid side. 
You can see an example repo showing this here https://github.com/manoj9788/tracing-selenium-grid
