### ISSUE TITLE
UnreachableBrowserException when running in Grid, depending on targetted host

### ISSUE THREAD

**Issue by mar1ged** [SeleniumHQ/selenium#5461]
## Meta -
OS:  
Red Hat Enterprise Linux 7.4
Selenium Version:  
3.8.1 (Grid), 3.6.0 test program
Browser:  
Firefox and Chrome

Browser Version:  
FireFox Mozilla Firefox 57.0.1
 (64-bit)

## Expected Behavior -
The test which reads the title of the targetted host should complete successfully, regardless of targetted host.
The same test runs fine for several hosts, some fail. All of them are https and when I curl the target from the Pod (I am on OpenShift) all of them can be reached without any problems.

## Actual Behavior -
After a delay of 30s the test fails with this exception thrown:

```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'foo', ip: '192.168.x.y', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: driver.version: RemoteWebDriver
Capabilities [{moz:profile=/tmp/rust_mozprofile.cSwF2S4YA8I7, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=LINUX, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=57.0.1, platformVersion=3.10.0-693.17.1.el7.x86_64, moz:processID=1649, browserName=firefox, javascriptEnabled=true, platformName=LINUX, moz:webdriverClick=false}]
Session ID: d7e4e1ea-239b-4412-8089-2dd376001597
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:607)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:310)
	at seleniumtestnomaven.TestBrowser.test(TestBrowser.java:135)
	at seleniumtestnomaven.TestBrowser.main(TestBrowser.java:40)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 22 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:87)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	... 3 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 22 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 8 more
```

Output of hub:
```
09:15:07.450 INFO - Got a request to create a new session: Capabilities {acceptInsecureCerts: true, browserName: firefox, name: Testing Selenium-2 Remote W..., version: }
09:15:07.450 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, se:CONFIG_UUID=2057a76f-2ed0-40da-a7a3-c453ce3cbfba, browserName=firefox, maxInstances=1, version=57.0.1, applicationName=, platform=LINUX}
09:16:46.973 WARN - The client is gone for session ext. key d7e4e1ea-239b-4412-8089-2dd376001597, terminating

```

Output of pod running Firefox (I excluded Chrome for the sake of brevity):

```
09:15:07.456 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@1c7618a1
09:15:07.457 INFO - /session: Executing POST on /session (handler: BeginSession)
09:15:07.463 INFO - Capabilities are: Capabilities {acceptInsecureCerts: true, browserName: firefox, name: ... version: }
09:15:07.463 INFO - Capabilities {acceptInsecureCerts: true, browserName: firefox, name: Testing Selenium-2 Remote W..., version: } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1518081307468   geckodriver     INFO    geckodriver 0.19.1
1518081307474   geckodriver     INFO    Listening on 127.0.0.1:20239
1518081307648   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.cSwF2S4YA8I7"
1518081308161   Marionette      INFO    Enabled via --marionette
1518081309733   Marionette      INFO    Listening on port 42301
1518081309817   Marionette      WARN    TLS certificate errors will be ignored for this session
1518081309915   Marionette      DEBUG   Register listener.js for window 2147483649
09:15:09.992 INFO - Detected dialect: W3C
09:15:10.091 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2b6fabb9
09:15:10.092 INFO - Handler thread for session d7e4e1ea-239b-4412-8089-2dd376001597 (firefox): Executing POST on /session/d7e4e1ea-239b-4412-8089-2dd376001597/url (handler: ServicedSession)
09:15:10.093 INFO - To upstream: {"url":"https://wwwundisclosed"}
1518081310097   Marionette      DEBUG   Received DOM event "beforeunload" for "about:blank"
1518081315225   Marionette      DEBUG   Received DOM event "pagehide" for "about:blank"
1518081315226   Marionette      DEBUG   Received DOM event "unload" for "about:blank"
1518081315681   Marionette      DEBUG   Received DOM event "DOMContentLoaded" for "https://wwwundisclosed"
1518081349475   addons.productaddons    WARN    Failed downloading XML, status: 0, reason: timeout
1518081406965   Marionette      DEBUG   Received DOM event "pageshow" for "https://wwwundisclosed"
09:16:46.969 INFO - To downstream: {"value": {}}
1518081439951   addons.productaddons    WARN    Failed downloading via XHR, status: 0, reason: error

```
## Steps to reproduce -
The code I run boils down to this, no fancy stuff in it:

```
WebDriver driver = new RemoteWebDriver(new URL(Config.hub), capabilities );
capabilities.setCapability("name", "nothing special");
driver.get(Config.target);  // <- This is the line where the exception is thrown
String source = driver.getPageSource();
String title = driver.getTitle();
```

Depending on the target the exception is being thrown.

**Comment by barancev** [comment]
Is there a reason to use different versions for the client and the server? Is the issue still actual if you use latest version (3.9.1 at the moment) for both the client and the server?

**Comment by mar1ged** [comment]
The only reason for this is that the company I work at is rather slow with updates ;-) We have lots of developers which are on different versions and the Grid we are experiencing these problems on is provided as a central service to all of them. This makes it rather difficult to update often.

But I had the same problem with 3.4 and 3.6.

**Comment by barancev** [comment]
What's the value of `Config.target`? Can you reproduce the issue on a special URL only or any one?

**Comment by mar1ged** [comment]
That's the strange thing: all URLs start with https, but some of them fail all the time. 

All are directly accessible in our Intranet zone, but it could be that those running in the same OpenShift or subnet work and those more "far away" fail. But all of them work fine with curl ... I'm confused ...

**Comment by luke-hill** [comment]
Ideally you should have the same `major.minor` on grid / hub and binding jar/gem/nuget package. They're designed to be used at that same level. And I know from personal experience around the 3.4->3.6 area that if you don't them you can come unstuck because quite a bit changed there.

**Comment by diemol** [comment]
Is still an issue?
It is not clear how we can help. If some URLs work and other ones don't, it is an indication that the issue could be related to the environment and the network rules (maybe certificates?) in the topology of your network.
If there is a way for us to reproduce, we are happy to help.

**Comment by diemol** [comment]
Closing this as the issue went stale.
