### ISSUE TITLE
throwOnCapabilityNotPresent flag is ignored

### ISSUE THREAD

**Issue by ClaytonAstrom** [SeleniumHQ/selenium#5464]
OS:  Win7

Selenium Version:  3.9.0

Browser:  N/A

Browser Version:  N/A

## Expected Behavior - 
`-throwOnCapabilityNotPresent false` should allow tests to queue regardless of registered nodes

## Actual Behavior - 
`-throwOnCapabilityNotPresent false` is ignored

## Steps to reproduce - 
Launching a hub with `java -jar selenium-server-standalone-3.9.0.jar -role hub -throwOnCapabilityNotPresent false` (or similar configuration via json) results in the grid being launched as:
![image](https://user-images.githubusercontent.com/3735885/35989128-006856fc-0cc6-11e8-9677-22a29e7b7994.png)

However, when actually trying to queue a test:

```bash
11:50:51.460 INFO - Got a request to create a new session: Capabilities {acceptSslCerts: true, browserName: chrome, chromeOptions: {args: [chrome.switches, --disable-extensions], extensions: []}, platform: WINDOWS, version: }
11:50:51.460 INFO - Error forwarding the new session Empty pool of VM for setup Capabilities {acceptSslCerts: true, browserName: chrome, chromeOptions: {args: [chrome.switches, --disable-extensions], extensions: []}, platform: WINDOWS, version: }
org.openqa.grid.common.exception.GridException: Empty pool of VM for setup Capabilities {acceptSslCerts: true, browserName: chrome, chromeOptions: {args: [chrome.switches, --disable-extensions], extensions: []}, platform: WINDOWS, version: }
        at org.openqa.grid.internal.ProxySet.verifyAbilityToHandleDesiredCapabilities(ProxySet.java:146)
        at org.openqa.grid.internal.DefaultGridRegistry.addNewSessionRequest(DefaultGridRegistry.java:228)
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:110)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:84)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by shoesel** [comment]
Any update on this? Still happens in 3.10.0

**Comment by diemol** [comment]
Hi,

Yes, this was broken since a few releases ago, when the ability to configure your own Registry was added.

I just pushed a commit that fixes this and restores the original behaviour, it will be available in the next release.
