### ISSUE TITLE
http async error

### ISSUE THREAD

**Issue by sarnathkj** [SeleniumHQ/selenium#5508]
## Meta -
OS:  Windows 7
Selenium Version:  4.0.0.1alpha
Browser:  All Browsers

## Actual Behavior -

\node_modules\selenium-webdriver\lib\http.js:454
  async execute(command) {
        ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\private\new-relic-synthetics\node_modules\selenium-webdriver\http\index.js:29:17)
    at Module._compile (module.js:556:32)

## Steps to reproduce -

Simple .get even doesn't work on the latest version.

**Comment by jleyba** [comment]
You are using node 7 or older. You need to use 8.9.0 (LTS) or newer
