### ISSUE TITLE
Unable to run Selenium / WebDriver scripts for Chrome, IOS Simulator while connected with LAN (For MAC System), It is working in WIFI & in Windows

### ISSUE THREAD

**Issue by siddtiwari** [SeleniumHQ/selenium#5529]
## Meta -
OS:  
MAC- 10.11.6? OSX? 
Selenium Version:  2.53.1
Browser:  
Chrome. V60
Chrome Driver: 2.32

I have tried with Chrome - V64 and ChromeDriver: 2.35 and Selenium 3.8

Chrome Browser Version:  
 60.0 (64-bit)

## Steps to reproduce -
WebDriver driver;
String exePath = "Path to Chromedriver";
System.setProperty("webdriver.chrome.driver", exePath);
driver = new ChromeDriver();
driver.get(URL);

Error message:
Starting ChromeDriver 2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061) on port 6945
Only local connections are allowed.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.36 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: '01hw382197', ip: '172.25.155.171', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '9.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:159)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:116)
	at dataAndConfig.Sample.main(Sample.java:31)

**Comment by lmtierney** [comment]
This has everything to do with your environment and nothing to do with selenium

**Comment by siddtiwari** [comment]
Could you please suggest me what needs to be done for environment set-up

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by siddtiwari** [comment]
Also I believe, I am facing issue because of this error and in hope of getting some help from this forum I posted here.
Closing the issue so soon was very unexpected, I understand there are people here who are very talented and dont want to answer for small issues, but in that case I guess people with small issues should not be allowed in this.
No hard feelings,  I just wanted to understand if someone also would have faced same issue then I could get some help.
Anyways Thanks for closing my issue :)

**Comment by lmtierney** [comment]
@siddtiwari that is what the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users) is for. Issues are only for issues with selenium itself. Unless you can provide a [concise reproducible test case](http://sscce.org/), then there's no way we would be able to diagnose the issue. In your case, you said it does work under a certain scenario but not on another. This leaves us nothing to go on.
