### ISSUE TITLE
EventFiringWebDriver not working with Page Factory

### ISSUE THREAD

**Issue by garry-edmonds** [SeleniumHQ/selenium#5536]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53 - 3.3 - 3.91
Browser:  
Chrome Browser
When trying to use the EventFiringWebDriver in c# using the pagefactory pattern and try and use the selenium Actions it errors with. 

System.Reflection.TargetException : Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenQA.Selenium.Support.PageObjects.WebDriverObjectProxy.InvokeMethod(IMethodCallMessage msg, Object representedValue)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.ILocatable.get_Coordinates()
   at OpenQA.Selenium.Interactions.MoveMouseAction.Perform()
   at OpenQA.Selenium.Interactions.CompositeAction.Perform()
   at TestSelenium.EventFireTest.EventFireError()

But when working with FindElements it works perfectly well, also have an issue using Execute Java Script not working in Page Factory.

See a very small test that has one working and one failing test.

Browser Version:  
Version 63.0.3239.132

## Expected Behavior -

Would expect the EventFireingWebDriver to not error and log to the console the control was found by Id as lst-ib

## Actual Behavior -

Errors with Object does not match target type. as above

## Steps to reproduce -  Attached small test that errors.

using System;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.Events;
using OpenQA.Selenium.Support.PageObjects;

namespace TestSelenium
{
    [TestFixture]
    public class EventFireTest
    {
        [FindsBy(How = How.Id, Using = "lst-ib")] public IWebElement GoogleSearchBox;

        private IWebDriver Driver { get; set; }
        private EventFiringWebDriver firingDriver { get; set; }

        [SetUp]
        public void Setup()
        {
            Driver = new ChromeDriver();
            firingDriver = new EventFiringWebDriver(Driver);
            firingDriver.FindElementCompleted += LogEventFiringWebDriverOnFindElementCompleted;
            firingDriver.Navigate().GoToUrl(new Uri("http://google.co.uk"));
        }

        [Test]
        public void EventFireError()
        {
            PageFactory.InitElements(firingDriver, this);                       // PageFactory Not Working

            Actions act = new Actions(firingDriver);
            act.MoveToElement(GoogleSearchBox).Build().Perform();
        }

        [Test]
        public void EventFireWorking()
        {
            var GoogleSearchBox = firingDriver.FindElement(By.Id("lst-ib"));    // FindElement Working
            
            Actions act = new Actions(firingDriver);
            act.MoveToElement(GoogleSearchBox).Build().Perform();
        }

        [TearDown]
        public void TearDown()
        {
            firingDriver?.Quit();
        }

        private void LogEventFiringWebDriverOnFindElementCompleted(object sender, FindElementEventArgs e)
        {
            Console.WriteLine(e.FindMethod);
        }
    }
}

**Comment by garry-edmonds** [comment]
Looks like I found a resolution for it, I have to unwrap the IWebElement from within the proxy to be able to use the actions class.  See 
https://stackoverflow.com/questions/35936035/selenium-movetoelement-with-transparent-proxy

But if someone knows a better way then please update for me.
