### ISSUE TITLE
"tinymce.activeEditor is undefined" after upgrading

### ISSUE THREAD

**Issue by matthewbyrne** [SeleniumHQ/selenium#5541]
## Meta -
OS:  
Ubuntu 14.04
Selenium Version:  
3.9.0
Browser:  
Firefox

Browser Version:  
FF58.0b9
## Expected Behavior -
TinyMCE4 javascript should run and execute (eg. inserting content to tinymce body).

## Actual Behavior -
It looks as though tinymce is not being initialised. 
```  Selenium::WebDriver::Error::JavascriptError: Exception TypeError: tinymce.activeEditor is undefined
  Stack Trace:
  stack backtrace:
     0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e
     1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9
     2:           0x442d88 - webdriver::error::WebDriverError::new::hea6d4dbf778b2b24
     3:           0x44cecc - geckodriver::marionette::MarionetteSession::response::h98d048d51a7ee2ba
     4:           0x42c729 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04
     5:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233
     6:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51
     7:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic
                          at /checkout/src/libpanic_unwind/lib.rs:98
     8:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5
     9:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>
                          at /checkout/src/liballoc/boxed.rs:661
                           - std::sys_common::thread::start_thread
                          at /checkout/src/libstd/sys_common/thread.rs:21
                           - std::sys::imp::thread::{{impl}}::new::thread_start
                          at /checkout/src/libstd/sys/unix/thread.rs:84
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/w3c/bridge.rb:292:in `execute_script'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/common/driver.rb:211:in `execute_script'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/browser.rb:265:in `execute_script'```

## Steps to reproduce -
I'm running a dockerised version of Ubuntu 14.04, running FF58.0b9 using geckodriver 0.19.0 and watir 6.10.3 and selenium 3.9.0.
Reverting my upgrade to use older versions works fine. 

Any guidance would be much appreciated.

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.
