### ISSUE TITLE
Unable to find a matching set of capabilities 

### ISSUE THREAD

**Issue by Giolegrand** [SeleniumHQ/selenium#5542]
## Meta -
OS:  Ubuntu 16.04

Selenium Version:  3.9.0

Browser:  Firefox

Browser Version:  58.0.2 (64-bit)

Geckodriver: 0.19.1

## Expected Behavior -
opening an headless firefox instance
## Actual Behavior -
failing to opening an firefox instance due being unable to find a matching set of capabilities
## Steps to reproduce -
```python
opts = FirefoxOptions()
opts.add_argument('-headless')

self.driver = webdriver.Firefox(firefox_options=opts)
```
## note
using the exact setup on windows it succeeds, upon the linux server with identical: FireFox, Selenium, Python (2.7.13) and code i get:
```python traceback
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:37767/session {"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true, "browserName": "firefox", "moz:firefoxOptions": {"args": ["-headless"]}}, "firstMatch": [{}]}, "desiredCapabilities": {"acceptInsecureCerts": true, "browserName": "firefox", "moz:firefoxOptions": {"args": ["-headless"]}}}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/experitybots/workspace/experity_statistics_robot.py", line 93, in <module>
    r.start_robot()
  File "/var/lib/jenkins/jobs/experitybots/workspace/experity_statistics_robot.py", line 54, in start_robot
    with firefox_driver() as driver:
  File "/var/lib/jenkins/jobs/experitybots/workspace/experity_statistics_robot.py", line 39, in __enter__
    firefox_options=opts
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by lmtierney** [comment]
Please try with the latest Selenium/Firefox/Geckodriver. The `unable to find a matching set...` error from geckodriver tends to cover a lot of errors even if they aren't related to capabilities (like Firefox not being able to be started)

**Comment by whimboo** [comment]
Also provide a trace log (https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) which will contain all the necessary information.

**Comment by barancev** [comment]
Closing the issue as both Selenium 3.9 and geckodriver 0.19 are out of date.
