### ISSUE TITLE
Selenium webdriver findElements getText throws exception

### ISSUE THREAD

**Issue by gusfran17** [SeleniumHQ/selenium#5549]
## Meta -
OS:  MacOS
Selenium Version:  "selenium-webdriver": "^4.0.0-alpha.1",
Browser:  Chrome, Safari, Firefox

Selenium webdriver findElements getText throws exception

I'm using cucumber-js with selenium-driver to create automated tests for my website. Now I'm trying to obtain a specific button by using its class and the text it has in it. When I use findElement function this works alright, I can use getText to obtain the text inside the **WebElementPromise** that I get from findElement:

```
When('I click on {string} button', async function (buttonClass) {
    const cta = currentDriver.findElement(seleniumWebDriver.By.className(buttonClass));
    cta.getText().then(console.log); // logs the text in the element
    await cta.click();
});
```
But when I use findElements in order to obtain an array of **WebElements** and iterate them to get their inner text I get an exception:

```
When('I click on {string} class {string} button', async function (buttonClass, buttonText) {
    let cta;
    currentDriver.findElements(seleniumWebDriver.By.className(buttonClass))
    .then(function(elements){
        elements.forEach(function(element, index) {
            element.getText().then(function(buttonInnerText) {
                console.log(buttonInnerText);
                if (buttonInnerText.trim() === buttonText.trim()) cta = element;
            }, console.log);
        });
    });
    if (cta) await cta.click();
});
```

**_console.log(buttonInnerText);_** Is usually not executed (some random but very sporadic times it did log the elements text which is very strange) and I get the following exceptions, logged by the rejection console.log callback function, for each time getText is called:

**Chrome driver**
{ NoSuchSessionError: no such session
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.3 x86_64)
    at Object.checkLegacyResponse (/Users/gustavofranco/Desktop/PrimaryBid/Projects/pb-web-tests/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/Users/gustavofranco/Desktop/PrimaryBid/Projects/pb-web-tests/node_modules/selenium-webdriver/lib/http.js:533:13)
    at Executor.execute (/Users/gustavofranco/Desktop/PrimaryBid/Projects/pb-web-tests/node_modules/selenium-webdriver/lib/http.js:468:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) name: 'NoSuchSessionError', remoteStacktrace: '' }

**Safari driver**
{ UnsupportedOperationError: A session with id = '9C117DB8-BF35-4CBE-81F9-1694C44D7BCC' was not found.
    at parseHttpResponse (/Users/gustavofranco/Desktop/PrimaryBid/Projects/pb-web-tests/node_modules/selenium-webdriver/lib/http.js:557:11)
    at Executor.execute (/Users/gustavofranco/Desktop/PrimaryBid/Projects/pb-web-tests/node_modules/selenium-webdriver/lib/http.js:468:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) name: 'UnsupportedOperationError', remoteStacktrace: '' }

**Firefox driver**
{ WebDriverError: An unknown server-side error occurred while processing the command.
    at Object.checkLegacyResponse (/Users/gustavofranco/Desktop/PrimaryBid/Projects/pb-web-tests/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/Users/gustavofranco/Desktop/PrimaryBid/Projects/pb-web-tests/node_modules/selenium-webdriver/lib/http.js:533:13)
    at Executor.execute (/Users/gustavofranco/Desktop/PrimaryBid/Projects/pb-web-tests/node_modules/selenium-webdriver/lib/http.js:468:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) name: 'WebDriverError', remoteStacktrace: '' }

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by gusfran17** [comment]
@barancev Thanks for your quick reply. Trying to achieve what you specify I came up with the following test cases:


    ```
this.driver = await new Builder()
    .forBrowser('firefox')
    .build();
    await this.driver.get('https://google.co.uk');
    let cta;
    let elements = await this.driver.findElements(seleniumWebDriver.By.className("_XIi"));
    elements.forEach(function(element, index) {
        element.getText().then(function(buttonInnerText) {
            console.log('buttonInnerText');
            console.log(buttonInnerText);
        }, console.log);
    });
```
 ```
this.driver = await new Builder()
    .forBrowser('chrome')
    .build();
    await this.driver.get('https://google.co.uk');
    let cta;
    let elements = await this.driver.findElements(seleniumWebDriver.By.className("_XIi"));
    elements.forEach(function(element, index) {
        element.getText().then(function(buttonInnerText) {
            console.log('buttonInnerText');
            console.log(buttonInnerText);
        }, console.log);
    });
```

```
    this.driver = await new Builder()
    .forBrowser('safari')
    .build();
    await this.driver.get('https://google.co.uk');
    let cta;
    let elements = await this.driver.findElements(seleniumWebDriver.By.className("_XIi"));
    elements.forEach(function(element, index) {
        element.getText().then(function(buttonInnerText) {
            console.log('buttonInnerText');
            console.log(buttonInnerText);
        }, console.log);
    });
```

It sometimes throws an exception and sometimes it executes fine logging "Be Internet Legends" in the console.

**Comment by barancev** [comment]
What exception is thrown?

**Comment by gusfran17** [comment]
The exception is...

**For safari**
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:53717
    at ClientRequest.<anonymous> (.../.../Projects/pb-web-tests/node_modules/selenium-webdriver/http/index.js:244:15)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at Socket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**For firefox**
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:53683
    at ClientRequest.<anonymous> (.../.../Projects/pb-web-tests/node_modules/selenium-webdriver/http/index.js:244:15)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at Socket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**For chrome**
{ NoSuchSessionError: no such session
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.3 x86_64)
    at Object.checkLegacyResponse (.../.../Projects/pb-web-tests/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (.../.../Projects/pb-web-tests/node_modules/selenium-webdriver/lib/http.js:533:13)
    at Executor.execute (.../.../Projects/pb-web-tests/node_modules/selenium-webdriver/lib/http.js:468:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) name: 'NoSuchSessionError', remoteStacktrace: '' }

And the success rate seems to increase when I add the following sleep order...


```
    this.driver = await new Builder()
    .forBrowser('firefox')
    .build();
    await this.driver.get('https://google.co.uk');
    let cta;
    let elements = await this.driver.findElements(seleniumWebDriver.By.className("_XIi"));
    //await this.driver.sleep(4000);
    elements.forEach(function(element, index) {
        element.getText().then(function(buttonInnerText) {
            console.log('buttonInnerText');
            console.log(buttonInnerText);
        }, console.log);
    });
```

**Comment by gusfran17** [comment]
The error I was having was due to the use of the forEach loop and Promises. I was trying to run each of the functions in the loop sequentially but that was not what was happening. I found the fix here:

https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop

Thanks for your help.
