### ISSUE TITLE
Unable to Upgrade from Selenium 3.4 - 3.5 - Error running on grid (.java files)

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#5554]
## Meta -
Preface: Running all of the below (Apart from not upgrading the versions), and keeping everything at 3.4 works (across all browsers, both locally and remotely)
3.4.0 binding / 3.4.0 IEDriverServer / 3.4.0 standalone / 1.12.16 GridExtras
Running all of the items upgraded *locally* works (Across all browsers)

OS:  
Win8.1 nodes running on Selenium Grid through Selenium Grid Extras 1.12.17
Selenium Version:  
3.5.0 server / 3.5.0 binding
Browser:  
Internet Explorer 11 - Latest patch - IEDriverServer 3.5.0 64bit (For some reason 32bit provides an invalid URL to download the driver)
Java is 1.8.0.102

## Expected Behavior -
I can run a test, any feature
## Actual Behavior -
```
Testing started at 16:03 ...
Tags: @@test
2018-03-01 16:03:46 INFO Selenium -> POST session
2018-03-01 16:03:46 INFO Selenium    >>> http://XXXXX:4444/wd/hub/session | {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":true,"rotatable":false,"enablePersistentHover":true,"ie.ensureCleanSession":true},"capabilities":{"firstMatch":[{"browserName":"internet explorer"}]}}
2018-03-01 16:03:46 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"332"}
2018-03-01 16:03:46 INFO Selenium <- {"value":{"stacktrace":"java.lang.NoSuchMethodError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;\r\n\tat org.openqa.selenium.net.UrlChecker.<init>(UrlChecker.java:64)\r\n\tat org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187)\r\n\tat org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)\r\n\tat org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:150)\r\n\tat org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$createSession$15(ActiveSessionFactory.java:148)\r\n\tat java.util.Optional.map(Unknown Source)\r\n\tat org.openqa.selenium.remote.server.ActiveSessionFactory.createSession(ActiveSessionFactory.java:148)\r\n\tat org.openqa.selenium.remote.server.BeginSession.execute(BeginSession.java:69)\r\n\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:231)\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\r\n\tat java.util.concurrent.FutureTask.run(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n","stackTrace":[{"fileName":"UrlChecker.java","methodName":"<init>","className":"org.openqa.selenium.net.UrlChecker","lineNumber":64},{"fileName":"DriverService.java","methodName":"waitUntilAvailable","className":"org.openqa.selenium.remote.service.DriverService","lineNumber":187},{"fileName":"DriverService.java","methodName":"start","className":"org.openqa.selenium.remote.service.DriverService","lineNumber":178},{"fileName":"ServicedSession.java","methodName":"apply","className":"org.openqa.selenium.remote.server.ServicedSession$Factory","lineNumber":150},{"fileName":"ActiveSessionFactory.java","methodName":"lambda$createSession$15","className":"org.openqa.selenium.remote.server.ActiveSessionFactory","lineNumber":148},{"fileName":null,"methodName":"map","className":"java.util.Optional","lineNumber":-1},{"fileName":"ActiveSessionFactory.java","methodName":"createSession","className":"org.openqa.selenium.remote.server.ActiveSessionFactory","lineNumber":148},{"fileName":"BeginSession.java","methodName":"execute","className":"org.openqa.selenium.remote.server.BeginSession","lineNumber":69},{"fileName":"WebDriverServlet.java","methodName":"lambda$handle$0","className":"org.openqa.selenium.remote.server.WebDriverServlet","lineNumber":231},{"fileName":null,"methodName":"call","className":"java.util.concurrent.Executors$RunnableAdapter","lineNumber":-1},{"fileName":null,"methodName":"run","className":"java.util.concurrent.FutureTask","lineNumber":-1},{"fileName":null,"methodName":"runWorker","className":"java.util.concurrent.ThreadPoolExecutor","lineNumber":-1},{"fileName":null,"methodName":"run","className":"java.util.concurrent.ThreadPoolExecutor$Worker","lineNumber":-1},{"fileName":null,"methodName":"run","className":"java.lang.Thread","lineNumber":-1}],"message":"com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;","error":"unknown error"},"status":13}
Tags: @@test

Selenium::WebDriver::Error::UnknownError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;
./features/support/hooks.rb:9:in `Before'

Skipped step * 10

EXACT SAME FAILURE HERE

Selenium::WebDriver::Error::UnknownError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;
./features/support/helpers/hooks.rb:62:in `log_failure_and_capture_screenshot'
./features/support/hooks.rb:29:in `After'
1 scenario (1 failed)
10 steps (10 skipped)
0m0.250s

Process finished with exit code 1
```

## Steps to reproduce -
- Selenium Grid Extras 1.12.17 installed with Windows 8.1 Nodes to hit.
- Ruby gem `3.5.0`

Driver instantiation: In Ruby 3.5.0 bindings (I'm aware this is through Capybara)
```
def register_remote_driver(capabilities)
  Capybara.register_driver :selenium do |app|
    Capybara::Selenium::Driver.new(
      app,
      browser: :remote,
      url: ENV['hub_url'],
      desired_capabilities: capabilities,
      http_client: remote_driver_browser_timeout,
    )
  end
end
```

Run a cucumber test (Anything should cause it to fail)

Special thanks to Lucas Tierney for spending half a day trying to debug it with me. I'm 99% sure this is something wrong in
- The Grid code
- My grid setup
- Some compatibility issue between the 2 cc/ @smccarthy incase this is GridExtras related

**Comment by cgoldberg** [comment]
https://github.com/groupon/Selenium-Grid-Extras/issues/355

according to this issue^^ , it was resolved with Selenium 3.6.0 and Grid Extras 1.12.17

**Comment by lmtierney** [comment]
He did try that when we were troubleshooting in IRC. I have since tried:
Ruby Bindings `3.5.0`
Grid `3.5.0`
IEDriver `3.5.0`
SGE `1.12.17`

And it all works for me fine. My guess is that the upgrade to `1.12.17` didn't fully work or there was a leftover guava package around.

**Comment by luke-hill** [comment]
One suggestion was maybe having both jars could cause issues. Today in google-time I'm going to try to manually re-create a grid system on 2 VM's (1 Hub and 1 Node), with exactly the same system. And if I can get it working on my "local" grid), then I know our sysadmins have something wrong their end.

One suggestion was to try Selenium 3.7 again which I'm not against. I just wanna do "some" upgrade. Now we're back able to :) Thanks for your suggestions / help though @cgoldberg

**Comment by luke-hill** [comment]
Is there a `guava -v` or something I can run on each node? Maybe that will spit out some help. Or some logging to triage the guava version>?

**Comment by shs96c** [comment]
I think the latest released versions of both GridExtras and Selenium play nicely together. This is definitely a mis-matched guava version --- it refers to a method that was removed a while ago.

**Comment by luke-hill** [comment]
One thing lucas explained to me Simon was we have a folder on our VM's with 4 or 5 versions of grid extras. So in the folder we have `1.12.12` / `1.12.14` / `1.12.16` and now we have also added `1.12.17`

When running it, we just run `java -jar` and don't physically install anything.

Is there any sysadminy style commands I can run to forcibly remove old guava and use new guava>?

Sorry I know gridextras isn't your remit. Just we're starting to get quite far behind again (As you can tell we're 5 versions behind), and I want to catch up again and try really hard to get us caught up to you guys

**Comment by barancev** [comment]
This issue (how to avoid conflicts and how to upgrade dependencies in selenium grid extras) would better be discussed in selenium grid extras tracker or a chat. Closing it.
