### ISSUE TITLE
Running Protractor scripts on IEDriver - Java script error

### ISSUE THREAD

**Issue by munna73** [SeleniumHQ/selenium#5589]
When I run my protractor scripts using IEDriver they fail stating Javascript errorsame script works fine on Chrome.
IEDriverServer_Win32_3.9.0,  selenium-server-standalone-3.10.0.jar,Windows 7, IE11

```
/html/body/app-root/main/div/div/app-rule/div/tabset  - Failed: JavaScript error
          at WebDriverError (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
          at JavascriptError (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:157:5)
          at Object.throwDecodedError (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:514:15)
          at parseHttpResponse (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:519:13)
          at doSend.then.response (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
          at process._tickCallback (internal/process/next_tick.js:109:7)
      From: Task: WebDriver.executeScript()
          at thenableWebDriverProxy.schedule (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
          at thenableWebDriverProxy.executeScript (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:878:16)
          at run (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\built\browser.js:59:33)
          at ProtractorBrowser.to.(anonymous function) [as executeScript] (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\built\browser.js:67:16)
          at utilities.highlightElement (c:\Users\ABC1234\git\udr-automation\udruiautomation\src\utils\utilities.js:59:24)
          at HomePage.navigateToDashBoard (c:\Users\ABC1234\git\udr-automation\udruiautomation\src\pages\HomePage.js:133:9)
          at UserContext.<anonymous> (c:\Users\ABC1234\git\udr-automation\udruiautomation\src\testspec\ListTests.js:106:12)
          at new ManagedPromise (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
          at ControlFlow.promise (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
      From: Task: Run it("Navigate to Conditions Tab,open existing phone list and Delete a record from phone list, Verify record is deleted by reopening the existing list") in control flow
          at ControlFlow.emit (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\events.js:62:21)
          at ControlFlow.shutdown_ (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2674:10)
          at shutdownTask_.MicroTask (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2599:53)
```

**Comment by jleyba** [comment]
That's the generic error returned by IE when the script passed to `executeScript()` throws -- there's not much we can do. For example:

```
driver.exectueScript("null.someMethod()")
```

Going to close this since it's a problem with the script you are passing to `executeScript` and not WebDriver itself (the bug might be the script Protractor is using though)
