### ISSUE TITLE
With Firefox move_to_element raises an exception. 

### ISSUE THREAD

**Issue by aaltat** [SeleniumHQ/selenium#5601]
## Meta -
OS:  
Ubuntu 17.10
Selenium Version:  
3.10.0
Browser:  
Firefox 58.0.2 and geckodriver 0.19.1

## Expected Behavior -
When doing `ActionChains(driver).move_to_element(element).perform()` the element should be scrolled in view and exception should not be raised. 

## Actual Behavior -
Element is not scrolled in view because this exception is raised:
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    ActionChains(driver).move_to_element(element).perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (183.5, 5330.85009765625) is out of bounds of viewport width (1280) and height (779)

```

## Steps to reproduce -
See details in here: https://gist.github.com/aaltat/a7f71e960d1bc3c6f90bfebb216162f0

**Comment by lmtierney** [comment]
This is by design per the spec. See:
https://www.w3.org/TR/webdriver/#pointer-actions
