### ISSUE TITLE
WebDriverError - Connection reset by peer

### ISSUE THREAD

**Issue by mjaeggi** [SeleniumHQ/selenium#5611]
OS:  
MacOS 10.12.6 Sierra
Selenium Version:  
3.11
Browser:  
Chrome
Browser Version:  
65.0.3325.162

## Actual Behavior -
I'm getting a randomly WebDriverError with the next stack trace
```
WebDriverError: java.net.SocketException: Connection reset by peer (connect failed)
           at Object.checkLegacyResponse (/Users/.../node_modules/selenium-webdriver/lib/error.js:546:15)
           at parseHttpResponse (/Users/.../node_modules/selenium-webdriver/lib/http.js:509:13)
           at doSend.then.response (/Users/.../node_modules/selenium-webdriver/lib/http.js:441:30)
           at <anonymous>
           at process._tickCallback (internal/process/next_tick.js:188:7)Error
           at ElementArrayFinder.applyAction_ (/Users/.../node_modules/protractor/built/element.js:459:27)
           at ElementArrayFinder.(anonymous function).args [as getAttribute] (/Users/.../node_modules/protractor/built/element.js:91:29)
           at ElementFinder.(anonymous function).args [as getAttribute] (/Users/.../webroot/node_modules/protractor/built/element.js:831:22)
           at HomePage.getFontNameFromCardCarousel (/Users/.../tests/qeguitests/e2e/pages/HomePage.js:91:148)
           at World.When (/Users/.../tests/qeguitests/e2e/features/steps_definitions/homepage_steps.js:99:33)
   - And I move to the "right" the carousel # tests/qeguitests/e2e/features/steps_definitions/homepage_steps.js:54
```
I'm getting this error randomy in different actions. It never happend in the same point twice

**Comment by workfrolov** [comment]
Have same problem with macOS 10.13.2 (17C205) and Version 64.0.3282.186 (Official Build) (64-bit)
Selenium version 3.11.0

**Comment by inzerion** [comment]
Have same problem with macOS 10.13.2 (17C205) and Version 64.0.3282.186 (Official Build) (64-bit)
Selenium version 3.11.0

**Comment by RobinFSK** [comment]
The same problem:
E/launcher - java.net.SocketException: Connection reset by peer (connect failed)
E/launcher - WebDriverError: java.net.SocketException: Connection reset by peer (connect failed)

macOS 10.13.3 (17D102)
chromedriver_2.37
selenium-server-standalone-3.11.0.jar
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by basickarl** [comment]
```
     Error: java.net.SocketException: Connection reset by peer (connect failed)
      at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
      at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
      at Request.self.callback (node_modules/webdriverio/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/webdriverio/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/webdriverio/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
Related to perhaps: https://github.com/webdriverio/webdriverio/issues/2262

**Comment by charlieargue** [comment]
Seeing the same error, posted about it here:
https://github.com/angular/protractor/issues/4733#issuecomment-394940484

Thanks for any help!

**Comment by janjad** [comment]
I have exactly the same problem on Mac 10.12.6 Sierra
Selenium version 3.12.0
Chromedriver version 2.40
Chrome 67.0

But I've found a workaround at least as it seems...
I've forced `webdriver-manager` to use selenium server version 2.53.1 and it seems that tests no longer fail on this error...

Would be great if this problem could be fixed for 3.x version too...

**Comment by abdullahawara** [comment]
### Work around for testing on Chrome:
Don't use selenium-standalone, but use http://webdriver.io/guide/services/chromedriver.html instead.

It worked for me on Mac.
```
    "devDependencies": {
        "chromedriver": "^2.40.0",
        "wdio-chromedriver-service": "^0.1.3",
        "wdio-mocha-framework": "0.5.12",
        "webdriverio": "4.13.1"
    }
```

**Comment by diemol** [comment]
Looks like this issue is mixing bits from different parts and projects, and it went stale.

It is not clear what the issue is, and after over two years it either got solved or is not relevant anymore. We are doing an issue clean up, so I will close this issue.
However, if the issue still exists, feel free to open a new one with all the information required in the template.
