### ISSUE TITLE
In 3.11, java.lang.NoSuchMethodError: com.google.gson.GsonBuilder.setLenient

### ISSUE THREAD

**Issue by bkelley13** [SeleniumHQ/selenium#5613]
When I try to create a RemoteWebDriver in 3.11, I see this error below.
This worked fine up through 3.10.  I've reverted to 3.10 for now.

I tried adding in the gson jar from google, but I still see same error.
Anyone else see this? I'm running one selenium server as hub, and then running
a node against it with webdriver for ff or chrome, same issue.

com.google.gson.GsonBuilder.setLenient()Lcom/google/gson/GsonBuilder;

java.lang.NoSuchMethodError: com.google.gson.GsonBuilder.setLenient()Lcom/google/gson/GsonBuilder;
at org.openqa.selenium.json.Json.<clinit>(Json.java:47)
at org.openqa.selenium.logging.profiler.HttpProfilerLogEntry.constructMessage(HttpProfilerLogEntry.java:37)
at org.openqa.selenium.logging.profiler.HttpProfilerLogEntry.<init>(HttpProfilerLogEntry.java:29)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:135)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
at oracle.ojet.automation.test.selenium.WebDriverManager._buildRemoteWebDriver(WebDriverManager.java:573)

**Comment by schmidtkp** [comment]
@bkelley13 You definitely need Gson. I have grid running with 3.11.0 no problem. I have the following Gson dependency:
```
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>2.8.2</version>
            </dependency> 
```

**Comment by barancev** [comment]
Please upgrade your dependency on Gson to the latest version.

**Comment by simplyviks** [comment]
Hi all, 

i added the gson dependecy 2.8.5 still see this issue?
any help is appreciated.

[2018-06-14 15:39:51.969] ERROR [MainThread] RemoteWebDriverCache:61 - Could not create a new instance of remote web driver
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.gson.GsonBuilder.setLenient()Lcom/google/gson/GsonBuilder;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	

regards,
Vikash

**Comment by snowymike** [comment]
i found i had to list the gson dependency in a very particular way in my pom.  see https://github.com/SeleniumHQ/selenium/issues/5009

**Comment by simplyviks** [comment]
Yes ,indeed I had to do the same ,strange why should I worry about the transitive dependency.

Also in particular I had to specify selenium -support dependency in one of the pom.

Overall make sure you have gson and selenium-support defined explicitly in pom.
