### ISSUE TITLE
Cannot run IE test on a specific node in Grid.

### ISSUE THREAD

**Issue by quldude** [SeleniumHQ/selenium#5614]
## Meta -
OS:  
Windows 2012R2
Selenium Version:  
webdriver 3.11.0.0
IE driver 3.9.0.0
Browser:  
Internet Explorer
Browser Version:  
IE 11 64-bit

## Expected Behavior -
Should be able to run on a particular node when "applicationName" capability is specified and IE is selected as browser to run on.
## Actual Behavior -
Getting the following error in my test:
```
Exception: OpenQA.Selenium.WebDriverException: Unexpected error. 
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
```

Getting the following error on grid hub console:
```
Caused by: 
java.lang.IllegalArgumentException: Illegal key values seen in w3c capabilities: [applicationName]
	at org.openqa.selenium.remote.NewSessionPayload.lambda$validate$6(NewSessionPayload.java:209)
	at java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)...
```

## Steps to reproduce -
Here is a C# code:
```
DesiredCapabilities capabilities = SetInternetExplorerOptions().ToCapabilities() as DesiredCapabilities;
capabilities.SetCapability(CapabilityType.BrowserName, "internet explorer");
capabilities.SetCapability(CapabilityType.Platform, new Platform(PlatformType.Windows));
capabilities.SetCapability("applicationName", "<machine ip>");

IWebDriver _WebDriver = new RemoteWebDriver(new Uri("<GRID_URL>"), capabilities, TimeSpan.FromSeconds(30));
((RemoteWebDriver)_WebDriver).FileDetector = new LocalFileDetector();

return _WebDriver;
 ```

**Comment by jimevans** [comment]
The [W3C WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html) is much stricter about what is allowed to be specified in a new session command's capabilities. There is no recognized capability for `applicationName`, and since the IE driver implements the specification, this is (correctly) rejected by both grid and the driver. If you have a need to use this capability in some custom processing somewhere, you'll need to change it to be an [extension capability](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-extension-capability).
