### ISSUE TITLE
Selenium 3.9 firefox won't launch via Webdriver 

### ISSUE THREAD

**Issue by SudeeptMohan** [SeleniumHQ/selenium#5622]
Browser Version:  

## Expected Behavior -
The browser firefox mozilla should launch

## Actual Behavior -
The browser doesn't launch and following error is thrown:
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:22.379Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:   0x47d2a4 - <no info>
   1:   0x45d174 - <no info>
   2:   0x427701 - <no info>
   3:   0x42ac5a - <no info>
   4:   0x45ff5e - <no info>
   5:   0x45581f - <no info>
   6:   0x4437a6 - <no info>
   7:   0x443aa6 - <no info>
   8:   0x6de879 - <no info>
   9:   0x4439e9 - <no info>
  10:   0x44385b - <no info>
  11:   0x4575c8 - <no info>
  12:   0x6da071 - <no info>
  13: 0x775a9564 - BaseThreadInitThunk
  14: 0x7779293c - EtwProcessPrivateLoggerRequest
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at browserAutomation.main(browserAutomation.java:45)

**Comment by SudeeptMohan** [comment]
I am using an old version of firefox - 48 with selenium 3.9 ... Could someone confirm if this is the reason for the problem?

**Comment by Jaysheel** [comment]
Yes, Selenium3 supports Firefox Qunatum.
It's preferred that you use latest version of Firefox i.e. 59 currently.

**Comment by barancev** [comment]
Please upgrade geckodriver to version 0.20 [1], it has improved error reporting, and retest the issue.

[1] https://github.com/mozilla/geckodriver/releases

**Comment by SudeeptMohan** [comment]
Firefox 59 wont let us use selenium IDE, is it planned to discard this tool and use webdriver only in future?

Retested the issue for fire fox version 48 with an upgraded gecko driver .20.0-win32, the problem of Unable to find a matching set of capabilities exists.Here is the complete log
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:22.379Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at browserAutomation.main(browserAutomation.java:45)

**Comment by barancev** [comment]
Then, please provide a [concise reproducible test case](http://sscce.org/).

**Comment by SudeeptMohan** [comment]
public void firefox() {
		
		WebDriver driver2 = 	new FirefoxDriver();
		driver2.manage().window().maximize();
		driver2.get("https://www.duckduckgo.com/");
		//search for a string in duckduckgo
		WebDriverWait wait5 = new WebDriverWait(driver2,30);
		WebElement textBox1 = wait5.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[id=search_form_input_homepage]")));
		textBox1.clear();
		textBox1.sendKeys("Buy a new PC  India");
		WebDriverWait wait6 = new WebDriverWait(driver2,30);
		WebElement btn4=wait6.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@id='search_button_homepage']")));
		btn4.click();
		driver2.quit();	
	}

**Comment by barancev** [comment]
So you call default FirefoxDriver constructor, you don't pass any capabilities explicitly, but it fails. Weird...

OK, le'ts try to collect more info. Please change constructor call to enable debug logging:
```
FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(FirefoxDriverLogLevel.DEBUG);
WebDriver driver2 = new FirefoxDriver(options);
```
and attach here the generated log.

**Comment by SudeeptMohan** [comment]
Mar 21, 2018 6:13:27 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
1521636214442	geckodriver	INFO	geckodriver 0.20.0 (0ac3698a74a7b1a742682b8e704f1f418df827ed 2018-03-13)
1521636214461	geckodriver	INFO	Listening on 127.0.0.1:27449
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:22.379Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at googleFirefox.<init>(googleFirefox.java:13)
	at browserAutomation.main(browserAutomation.java:42

**Comment by cgoldberg** [comment]
@SudeeptMohan 

> Retested the issue for fire fox version 48 with an upgraded gecko driver .20.0-win32,
>  the problem of Unable to find a matching set of capabilities exists.

are you still trying with Firefox 48?  That's not going to work with geckodriver .20

**Comment by SudeeptMohan** [comment]
i'm using firefox 48 as selenium IDE is working with older version of firefox

**Comment by cgoldberg** [comment]
> i'm using firefox 48 

it's not compatible with geckodriver .20

**Comment by rakeshnambiar** [comment]
I am getting the error `Driver info: driver.version: unknown`

`Firefox version` - `65.0.1`
`Geckodriver` - `geckodriver-v0.24.0`
