### ISSUE TITLE
Selenium Java program not sending search text to search box in Google

### ISSUE THREAD

**Issue by SudeeptMohan** [SeleniumHQ/selenium#5623]
Browser Version:  
65

## Expected Behavior -
The search string should be passed by java program to google search text, chrome browser
## Actual Behavior -

Code used :
System.out.println("performing search in google");
	if (textBox.isEnabled())
			System.out.println("search box enabled");
		//send search-text and opening search result
		textBox.click();
		System.out.println("clicked");
		textBox.clear();
		System.out.println("cleared");
		textBox.sendKeys("Linux fast pc");
		System.out.println("sent search string in google");

Error Observed:
The search string is not entered in the search field.Infact it seems the click (first task of inputting in the program) is not working.

Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:22.379Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.33.506120 (e3e53437346286..., userDataDir: C:\Users\admin\AppData\Loca...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.162, webStorageEnabled: true}
Session ID: 2dd7e11d7fc40b7faabf475b1e145ee8
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.clear(RemoteWebElement.java:118)
	at browserAutomation.main(browserAutomation.java:94)

**Comment by matmar-91** [comment]
Try to update your chromedriver first. Here you can download latest one.
https://sites.google.com/a/chromium.org/chromedriver/downloads

As mentioned on this site chromedriver 2.33 which you are using supports chrome v60-v62.

**Comment by SudeeptMohan** [comment]
works like magic, chrome driver driver upgrade does the trick, thank you
Issue verified, closing
