### ISSUE TITLE
Unable to set ImplicitWait in IE

### ISSUE THREAD

**Issue by romovs** [SeleniumHQ/selenium#5635]
## Meta
OS:  Windows 10
Selenium Version:  Selenium Server Standalone 3.11.0, IEDriverServer 3.9.0 (32-bit)
Browser:  Internet Explorer 11

## Expected Behavior
Should be able to set ImplicitWait.
This is working fine in v3.4 and earlier version of Selenium Hub and IEDriverServer.

## Actual Behavior
Following exception is thrown:
```
OpenQA.Selenium.WebDriverException: Invalid timeout type specified: ms
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'
System info: host: 'DESKTOP-S0LVI9F', ip: '10.0.2.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteTimeouts.ExecuteSetTimeout(String timeoutType, TimeSpan timeToWait)
   at OpenQA.Selenium.Remote.RemoteTimeouts.set_ImplicitWait(TimeSpan value)
```

## Steps to reproduce

```cmd
java -Dwebdriver.ie.driver.logfile=iedriver.log -Dwebdriver.ie.driver.loglevel=TRACE -Dwebdriver.chrome.driver=chromedriver.exe -Dwebdriver.ie.driver=IEDriverServer.exe -Dwebdriver.gecko.driver=geckodriver.exe -jar selenium-server-standalone-3.11.0.jar -port 4444 -timeout 320 -browserTimeout 320
```

```C#
DesiredCapabilities caps = new DesiredCapabilities();
caps.SetCapability("browserName", "internet explorer");
var driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), caps, TimeSpan.FromMinutes(2));
driver.Manage().Window.Size = new Size(1600, 900);
driver.Navigate().GoToUrl("https://ynet.co.il");
driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(2000);
```

**Comment by barancev** [comment]
Can you reproduce the issue with IEDriverServer version 3.11?

**Comment by romovs** [comment]
Does not happen with v3.11. Thanks.
I wasn't aware that v3.11 was out since the [Selenium Downloads](https://www.seleniumhq.org/download/) page still lists IEDriver v3.9 as the latest version.
