### ISSUE TITLE
Cannot launch Standalone programmatically

### ISSUE THREAD

**Issue by josmunpav** [SeleniumHQ/selenium#5648]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.11 (cloned repository from last week)
Browser:  
None

Hi, I am trying to launch a Selenium Server Standalone instance programmatically. This is the code I am using:

```

        StandaloneConfiguration configuration = new StandaloneConfiguration();        
        configuration.port = 5000;
        configuration.debug = false;        
        server = new SeleniumServer(configuration);        
        
        log.info("Launching Server on port " + configuration.port);
        if (server.boot())
            log.info("Server Launched OK");
        else
            log.info("Server could not be launched :(");

```

I get an exception launched by Jetty log system that I can't get rid of:

```
Testcase: testBrowser(LaunchSeleniumGridTest):	Caused an ERROR
org.slf4j.helpers.MessageFormatter.arrayFormat(Ljava/lang/String;[Ljava/lang/Object;)Lorg/slf4j/helpers/FormattingTuple;
java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.arrayFormat(Ljava/lang/String;[Ljava/lang/Object;)Lorg/slf4j/helpers/FormattingTuple;
	at org.seleniumhq.jetty9.util.log.JettyAwareLogger.log(JettyAwareLogger.java:619)
	at org.seleniumhq.jetty9.util.log.JettyAwareLogger.info(JettyAwareLogger.java:314)
	at org.seleniumhq.jetty9.util.log.Slf4jLog.info(Slf4jLog.java:74)
	at org.seleniumhq.jetty9.util.log.Log.initialized(Log.java:192)
	at org.seleniumhq.jetty9.util.log.Log.getLogger(Log.java:310)
	at org.seleniumhq.jetty9.util.log.Log.getLogger(Log.java:300)
	at org.seleniumhq.jetty9.util.component.AbstractLifeCycle.<clinit>(AbstractLifeCycle.java:35)
	at org.openqa.selenium.remote.server.SeleniumServer.boot(SeleniumServer.java:129)
	at LaunchSeleniumGridTest.testBrowser(LaunchSeleniumGridTest.java:86)
```

I am compiling the source code and it works if I go to a console and launch it by the standard **java -jar selenium.jar -port 5000**

In fact, I can even launch it from code if I use this code:

```
        String [] args = {"-port", "5000"};
        GridLauncherV3 launcher = new GridLauncherV3(args);
        launcher.launch();

```

Not sure what's going on but I need to be able to launch and stop standalone instances within a program.

By the way, I am using **Java 1.8.0_131** on **Windows 10**

Thanks!

**Comment by josmunpav** [comment]
Sorry gusy it was a problem with some other libraries I am using that seem to interfere. 

Closing this issue.

**Comment by darran-kelinske-fivestars** [comment]
How did you fix the issue with the other libraries?
