### ISSUE TITLE
IEDriverServer.exe crashes immediately when trying to run a test

### ISSUE THREAD

**Issue by cnsgithub** [SeleniumHQ/selenium#5662]
## Meta -
OS:  
Windows 8.1 x64
Selenium Version:  
3.11.0 / 3.9.0
Browser:  
Internet Explorer 11
Browser Version:  
11.0.9600.18763
IEDriverServer.exe Version:
3.9.0.0 x64

## Expected Behavior -
Driver should open and remote control Internet Explorer.

## Actual Behavior -
IEDriverServer.exe crashes immediately when running arbitrary tests.

WinDbg output:
```
Microsoft (R) Windows Debugger Version 10.0.16299.91 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff7`60030000 00007ff7`60336000   <path>\IEDriverServer.exe
ModLoad: 00007ffb`2f780000 00007ffb`2f92d000   C:\Windows\SYSTEM32\ntdll.dll
ModLoad: 00007ffb`2f640000 00007ffb`2f77e000   C:\Windows\system32\KERNEL32.DLL
ModLoad: 00007ffb`2cad0000 00007ffb`2cbe5000   C:\Windows\system32\KERNELBASE.dll
ModLoad: 00007ffb`2a790000 00007ffb`2a79a000   C:\Windows\SYSTEM32\VERSION.dll
ModLoad: 00007ffb`2f590000 00007ffb`2f63a000   C:\Windows\system32\msvcrt.dll
ModLoad: 00007ffa`edc70000 00007ffa`edf35000   C:\Users\<user>\AppData\Local\Temp\IEDFD39.tmp
ModLoad: 00007ffb`2ea00000 00007ffb`2eb40000   C:\Windows\system32\RPCRT4.dll
ModLoad: 00007ffb`2e9f0000 00007ffb`2e9f7000   C:\Windows\system32\PSAPI.DLL
ModLoad: 00007ffb`28380000 00007ffb`283ea000   C:\Windows\SYSTEM32\OLEACC.dll
ModLoad: 00007ffb`24a00000 00007ffb`24d21000   C:\Windows\SYSTEM32\WININET.dll
ModLoad: 00007ffb`250f0000 00007ffb`25275000   C:\Windows\SYSTEM32\urlmon.dll
ModLoad: 00007ffb`2f0d0000 00007ffb`2f247000   C:\Windows\system32\USER32.dll
ModLoad: 00007ffb`2ef80000 00007ffb`2f0cb000   C:\Windows\system32\GDI32.dll
ModLoad: 00007ffb`2e760000 00007ffb`2e80a000   C:\Windows\system32\ADVAPI32.dll
ModLoad: 00007ffb`2ebc0000 00007ffb`2ed54000   C:\Windows\system32\ole32.dll
ModLoad: 00007ffb`2e690000 00007ffb`2e756000   C:\Windows\system32\OLEAUT32.dll
ModLoad: 00007ffb`2f470000 00007ffb`2f4c4000   C:\Windows\system32\SHLWAPI.dll
ModLoad: 00007ffb`286c0000 00007ffb`28871000   C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.9600.18696_none_9333287b4748e6ab\gdiplus.dll
ModLoad: 00007ffb`2e630000 00007ffb`2e68a000   C:\Windows\system32\WS2_32.dll
ModLoad: 00007ffb`2cdd0000 00007ffb`2cdfe000   C:\Windows\system32\SspiCli.dll
ModLoad: 00007ffb`2f250000 00007ffb`2f462000   C:\Windows\system32\combase.dll
ModLoad: 00007ffb`24e20000 00007ffb`250ea000   C:\Windows\SYSTEM32\iertutil.dll
ModLoad: 00007ffb`2bec0000 00007ffb`2bee1000   C:\Windows\SYSTEM32\USERENV.dll
ModLoad: 00007ffb`2f530000 00007ffb`2f589000   C:\Windows\SYSTEM32\sechost.dll
ModLoad: 00007ffb`2f4d0000 00007ffb`2f4d9000   C:\Windows\system32\NSI.dll
ModLoad: 00007ffb`2c8a0000 00007ffb`2c8b5000   C:\Windows\SYSTEM32\profapi.dll
ModLoad: 00007ffb`2f4e0000 00007ffb`2f516000   C:\Windows\system32\IMM32.DLL
ModLoad: 00007ffb`2ee20000 00007ffb`2ef72000   C:\Windows\system32\MSCTF.dll
ModLoad: 00007ffb`2c130000 00007ffb`2c189000   C:\Windows\system32\mswsock.dll
ModLoad: 00007ffb`2b700000 00007ffb`2b70b000   C:\Windows\SYSTEM32\kernel.appcore.dll
ModLoad: 00007ffb`2c7e0000 00007ffb`2c7eb000   C:\Windows\SYSTEM32\CRYPTBASE.dll
ModLoad: 00007ffb`2c770000 00007ffb`2c7d3000   C:\Windows\SYSTEM32\bcryptPrimitives.dll
ModLoad: 00007ffb`2b530000 00007ffb`2b659000   C:\Windows\system32\uxtheme.dll
ModLoad: 00007ffb`25f40000 00007ffb`261f4000   C:\Program Files (x86)\Stardock\Start8\Start8_64.dll
ModLoad: 00007ffb`26df0000 00007ffb`26f6f000   C:\Windows\SYSTEM32\PROPSYS.dll
ModLoad: 00007ffb`2aed0000 00007ffb`2aef1000   C:\Windows\system32\dwmapi.dll
ModLoad: 00007ffb`2a970000 00007ffb`2abeb000   C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.18006_none_623f33d3ecbe86e8\comctl32.dll
ModLoad: 00007ffb`1eb30000 00007ffb`1eb3f000   C:\Windows\SYSTEM32\atlthunk.dll
(42e4.2260): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
*** WARNING: Unable to verify checksum for <path>\IEDriverServer.exe
*** ERROR: Module load completed but symbols could not be loaded for <path>\IEDriverServer.exe
IEDriverServer+0x186f8:
00007ff7`600486f8 cd29            int     29h
```

Call stack:
![image](https://user-images.githubusercontent.com/13161711/37756630-7ef8c592-2daa-11e8-8a92-725d25263bf2.png)

Java stacktrace:
```
Started InternetExplorerDriver server (64-bit)
3.9.0.0
Listening on port 48376
Only local connections are allowed

org.openqa.selenium.WebDriverException: java.net.SocketTimeoutException: Read timed out
Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:56:06.3Z'
System info: host: '<host>', ip: '<ip>', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '9.0.4'
Driver info: driver.version: InternetExplorerDriver

	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:223)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:215)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:192)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:164)
	at SeleniumTest.setup(SeleniumTest.java:21)
```

## Steps to reproduce -
Just run this JUnit test:
```java
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.ie.InternetExplorerOptions;

import java.util.concurrent.TimeUnit;

public class SeleniumTest {

    private WebDriver driver;

    @Before
    public void setup() {
        System.setProperty("webdriver.ie.driver", "<path>/IEDriverServer.exe");
        driver = new InternetExplorerDriver(new InternetExplorerOptions());
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    }

    @After
    public void teardown() {
        driver.close();
    }

    @Test
    public void test() {
        // test goes here
    }

}
```

**Comment by cnsgithub** [comment]
Btw, I followed these instructions: https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver

And I also tested selenium-client-combined-3.9.0 with the very same results.

**Comment by jimevans** [comment]
This sounds an awful lot like #5519, which was fixed in 3.11.1. What happens if you use that version of the IE driver? As always, the latest IE driver can be found at [the official release site](http://selenium-release.storage.googleapis.com/index.html).

**Comment by cnsgithub** [comment]
Upgrading the driver to 3.11.1 indeed brings the browser up and makes the test work. (When I tried 3.11.0 last week it didn't. Sorry, that I hadn't realized there is a even newer version.) Thanks for your answer.

However, after a specific JUnit test had failed, the driver crashed again and the browser stayed open. Should I open a separate issue for that?

**Comment by jimevans** [comment]
Yes, let's open a new issue. Please be sure to include WebDriver code that reproduces the issue (including a page or URL against which to test), and a TRACE-level log from `IEDriverServer.exe`.

**Comment by cnsgithub** [comment]
@jimevans Here we go: https://github.com/SeleniumHQ/selenium/issues/5664
