### ISSUE TITLE
Remote WebDriver UnreachableBrowserException: Could not start a new session

### ISSUE THREAD

**Issue by louis57** [SeleniumHQ/selenium#5679]
I got this exception for all browsers. For example, I create a remote webdriver on chrome like this:

    caps = DesiredCapabilities.chrome();
    ChromeOptions options = new ChromeOptions();
    options.addArguments("disable-infobars");
    caps.setCapability(ChromeOptions.CAPABILITY, options);
    webDriver = new RemoteWebDriver(new URL("http://myIP:5555/wd/hub"), caps);
And I got UnreachableBrowserException as follow (firefox and IE get the same exception):
    
```
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:104)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:54)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
```
But I check my selenium hub at `http://myIP:4444/grid/console`, everything is fine, the node is stil registered. I then check my node at `http://myIP:5555/wd/hub/static/resource/hub.html`, I still can click "Create Session" to create a session for all browsers.

I just got this exception today, it still worked few days ago. I am using Selenium 3.11.0, IntelliJ 2017.3, all drivers and browsers are latest versions. 

EDIT: These are the scripts I create my grid (on the same machine)
Hub: `java -jar C:\Selenium\selenium-server-standalone-3.11.0.jar -role hub`
Node: `java  -jar C:\Selenium\selenium-server-standalone-3.11.0.jar -role node -hub http://myIP:4444/grid/register -port 5555`

I googled here, but I can't find a solution for this while my gird is still running. Any help much appreciated.

**Comment by lmtierney** [comment]
Not saying this is the problem at all, just a quick observation... It looks like you're pointing your RemoteWebDriver either at a node or port `5555` of the hub. Since your hub is running on `4444` RemoteWebDriver should be pointed there

**Comment by louis57** [comment]
@lmtierney Hi, I think it should not be that problem, becasue I explicitly registered my node on port `5555`. I edited my question. And on Selenium Grid, the node is shown as `http://myIP:5555/wd/hub`

**Comment by lmtierney** [comment]
@louis57 sure, the node would be on `5555` by default, I'm talking about this line:

```
webDriver = new RemoteWebDriver(new URL("http://myIP:5555/wd/hub"), caps);
```

You never want to talk to a node directly, you want to talk to the hub.

**Comment by louis57** [comment]
I was able to fix this issue as follow:

1. I read on [Selenium Release Notes](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG) that with the current implementation of Selenium while invoking RemoteWebDriver supports the ChromeOptions, so change my code to `webDriver = new RemoteWebDriver(new URL("http://myIP:5555/wd/hub"), options);` instead of `DesiredCapabilities`. and it works.
3. There was a firewall issue on my VirtualBox where I set up my hub. After I fixed the firewall issue, I can connect to my node.

Thanks.

**Comment by ramesh531** [comment]
@louis57 Louis which selenium version you used . I'm also getting the same issue while launching the browser on my node machine. 

My Hub is a Ubuntu machine and my node is a windows 10 machine. Node is registered with the hub successfully , but when I'm running the suite from jenkins i'm getting the error.

Interestingly when I run the same suite xml from eclipse it's working fine with out any issues.

Running TestSuite http://192.168.217.76:4466/wd/hub 
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies). log4j:WARN Please initialize the log4j system properly. log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info. 
Tests run: 10, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 121.545 sec <<< FAILURE! - in TestSuite beforeClass(com.cloudleaf.webautomation.CloudLeafCIGrid) Time elapsed: 121.21 sec <<< FAILURE! org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Build info: version: '3.4.0', revision: 'unknown', time: 'unknown' System info: host: 'ip-172-31-37-249', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1074-aws', java.version: '1.8.0_191' Driver info: driver.version: RemoteWebDriver at com.cloudleaf.webautomation.CloudLeafCIGrid.beforeClass(CloudLeafCIGrid.java:90) Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to 192.168.217.76:4466 [/192.168.217.76] failed: connect timed out at com.cloudleaf.webautomation.CloudLeafCIGrid.beforeClass(CloudLeafCIGrid.java:90) Caused by: java.net.SocketTimeoutException: connect timed out at com.cloudleaf.webautomation.CloudLeafCIGrid.beforeClass(CloudLeafCIGrid.java:90) Results : Failed tests: CloudLeafCIGrid.beforeClass:90 » UnreachableBrowser Could not start a new sess... Tests run: 7, Failures: 1, Errors: 0, Skipped: 6
