### ISSUE TITLE
Unable to parse URL: http://localhost:?????/session

### ISSUE THREAD

**Issue by Tejas0435** [SeleniumHQ/selenium#5692]
## Meta -
OS:  <Windows8.1>
Selenium Version:  <3.11.0>
Browser:   Internet Explorer

Browser Version:  45.0.2453.0

Issue observed:

Started InternetExplorerDriver server (64-bit)
3.9.0.0
Listening on port 13528
Only local connections are allowed
Exception in thread "main" org.openqa.selenium.WebDriverException: java.io.IOException: Unable to parse URL: http://localhost:?????/session
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'RAJESH-SNEHA', ip: '192.168.0.105', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_161'
Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:223)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:215)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:152)
	at Gmail.Login.main(Login.java:21)
Caused by: java.io.IOException: Unable to parse URL: http://localhost:?????/session
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:67)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 6 more

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Rosewathe** [comment]
I also facing same issue, if you have a solution
 please let me know
