### ISSUE TITLE
Server terminated early with status 0

### ISSUE THREAD

**Issue by amedvedjev** [SeleniumHQ/selenium#5701]
## Meta -
OS:  
  Windows 10
Selenium Version:  
     selenium standalone versions available: 3.11.0 [last]
     chromedriver versions available: 2.35, 2.37 [last]
Browser: 
  Chrome
Browser Version:  
  Version 65.0.3325.181

## Expected Behavior -
[15:57:54][Step 5/6] [chrome #01-16] [15:57:18] I/local - Starting selenium standalone server...
[15:57:54][Step 5/6] [chrome #01-16] [15:57:21] I/local - Selenium standalone server started at http://169.254.182.34:10936/wd/hub

## Actual Behavior -
[15:58:01][Step 5/6] [chrome #01-26] [15:57:59] I/local - Starting selenium standalone server...
[15:58:01][Step 5/6] [chrome #01-26] [15:58:01] I/runnerCli - Server terminated early with status 0
[15:58:01][Step 5/6] [15:58:01] E/launcher - Runner process exited unexpectedly with error code: 1
## Steps to reproduce -
When i execute jasmine tests in parallel - sometimes is see that server failed to start. 

Thanks for any help/workaround. Is any way exists try to restart failed server?

**Comment by barancev** [comment]
Please enable debug log in selenium server (`-debug` option) and attach debug log of a failure.

**Comment by amedvedjev** [comment]
@barancev need little help. how i can do this with protractor?

**Comment by amedvedjev** [comment]
I got error in manual mode (not sure if the same)
```
[13:09:08] E/launcher - Error: Error: Server terminated early with status 0
    at earlyTermination.catch.e (C:\Users\alme01\Documents\Sources\xxxxxx\node_modules\selenium-webdriver\remote\index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by barancev** [comment]
Can you start selenium server independently of protractor?

**Comment by amedvedjev** [comment]
When i start selenium server as hub on some machine issue does not reproduce. Reproducing only when protractor starting selenium server with each test start. Reproducing 1 to 100. But it is annoying to see that one-two tests skipped due to this error.

**Comment by barancev** [comment]
I think you have to report this issue to protractor. They can at least add more logging -- what options were used to run selenium server and where to look for detailed selenium server log. We can accept a report if you are able to reproduce the issue with "vanilla" server.
