### ISSUE TITLE
Facing "Connection refused (Connection refused)" Error while launching SafariDriver with selenium-java

### ISSUE THREAD

**Issue by ssoundhar** [SeleniumHQ/selenium#5706]
## Meta -
OS:  
MAC-OS
Selenium Version:  
3.9.1
Browser:  
SafariDriver

## Actual Behavior -

Password:Password:Password:Exception in thread "main" org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:4856
Build info: version: '3.10.0', revision: '176b4a9', time: '2018-03-02T19:11:12.151Z'
System info: host: 'soundhar.local', ip: '192.168.3.57', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_131'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:78)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:60)
	at com.gmail.test.Accesssafa.main(Accesssafa.java:16)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:4856
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 6 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
	... 28 more

**Comment by ssoundhar** [comment]
Can someone help me plz..!?

**Comment by testphreak** [comment]
Did you try with Selenium v3.11 with the latest Safari and SafariDriver? Providing a reproducible test case will help others understand the issue.

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by ssoundhar** [comment]
I have just trying to launch the safari with a URL.

Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'
System info: host: 'soundhar.local', ip: '192......', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_131'
Driver info: driver.version: SafariDriver 2.48

**Comment by cgoldberg** [comment]
> I have just trying to launch the safari with a URL.

a "reproducible" test case would include sample code that you run to reproduce the issue.

**Comment by ssoundhar** [comment]
Hi cgoldberg,

Thank you for helping me. I am a beginner in selenium, I just start learning.
Here the code I used,
package com.gmail.test;

package com.gmail.test;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.safari.SafariDriver;


public class Gtestcase
{

	public static void main(String[] args) throws InterruptedException 
	{
	    
		System.setProperty("webdriver.chrome.driver", "/Users/mbf-user/Downloads/Softwares/chromedriver");
		
	         WebDriver driver = new SafariDriver();
			
		driver.get("http://35.00.xx.xx:9xxx/login");
		driver.manage().window().maximize();
		driver.findElement(By.name("email")).sendKeys("xxxx@xx.com");
		driver.findElement(By.name("password")).sendKeys("xxxxxxx");
		driver.findElement(By.className("button")).click();
	    System.out.println("Launched");
	}
}

-The same thing I have used to launch chrome, It works fine only.


Thanks,
Soundhar.S

**Comment by testphreak** [comment]
Where/how are you setting the `SafariDriver`?

**Comment by p0deje** [comment]
Please read https://webkit.org/blog/6900/webdriver-support-in-safari-10/ first and make sure you enabled SafariDriver.

**Comment by ssoundhar** [comment]
Thank you.! p0deje

**Comment by barancev** [comment]
@ssoundhar Can we close this issue?

**Comment by ssoundhar** [comment]
@barancev  Still it's not resolved, advise me for any other good way.

-Note : it asks me password while launching the safari driver, it says 
" password:password:password: "

Refer the screen below : 

![screen shot 2018-04-04 at 11 10 10 am](https://user-images.githubusercontent.com/33656403/38290468-ef5e9868-37f8-11e8-9140-0792cc59aab0.png)

**Comment by barancev** [comment]
Run `/usr/bin/safaridriver` once manually and complete the authentication prompt.
