### ISSUE TITLE
Connection reset by peer on teardown

### ISSUE THREAD

**Issue by billyvg** [SeleniumHQ/selenium#5730]
## Meta -
OS: Linux (Travis CI)

Selenium Version: 3.8.0

Browser: Chrome 
Browser Version: v61-v66+

## Expected Behavior -
Should teardown successfully

## Actual Behavior -
Intermittent connection reset issues on teardown

## Steps to reproduce -

Here are travis logs for a few builds that fail on teardown on differing tests:

https://travis-ci.org/getsentry/sentry/jobs/361312007
https://travis-ci.org/getsentry/sentry/jobs/360086412

```
_____________ ERROR at teardown of AccountSettingsTest.test_simple _____________
Traceback (most recent call last):
  File "/home/travis/build/getsentry/sentry/src/sentry/utils/pytest/selenium.py", line 267, in fin
    driver.quit()
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 129, in quit
    self.service.stop()
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 149, in stop
    self.send_remote_shutdown_command()
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 125, in send_remote_shutdown_command
    url_request.urlopen("%s/shutdown" % self.service_url)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/opt/python/2.7.13/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/raven/breadcrumbs.py", line 352, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/opt/python/2.7.13/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/opt/python/2.7.13/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/opt/python/2.7.13/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/opt/python/2.7.13/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
----------------------------- Captured stdout call -----------------------------
19:20:43 [INFO] sentry.testutils: selenium.initialize-cookies
19:20:43 [INFO] sentry.testutils: selenium.set-cookie.sentrysid (value=u'.eJxrYKotZNQIZSkuTckvZIrgYWBgyAsy9gkqLQ4LMvUxL2QOFYpPLC3JiC8tTi2KT0pMzk7NSylkCVUqTs0rKarUKy3JzCnWA6nQc81NzMxxBLKcoKpYQ3mR9GamFLJ5s5TqAQA20iZL:1f350V:pTnZzxAJ9RrcexugV2h_dZnyjYw')
----------------------------------- selenium -----------------------------------
WARNING: Failed to gather URL: [Errno 111] Connection refused
WARNING: Failed to gather screenshot: [Errno 111] Connection refused
WARNING: Failed to gather HTML: [Errno 111] Connection refused
WARNING: Failed to gather log types: [Errno 111] Connection refused
```

**Comment by lmtierney** [comment]
So looking at the code, you're using your own `driver`, including using a package called `raven` (from the stacktrace). Can you reproduce this intermittent behavior using just selenium? I've never had this error occur.

**Comment by lmtierney** [comment]
And may I ask why you're calling `close()` and then `quit()` ? https://github.com/getsentry/sentry/blob/master/src/sentry/utils/pytest/selenium.py#L297

**Comment by billyvg** [comment]
That is curious, and seems like it could be the cause of the problems. I will investigate and get back to you, thank you!

**Comment by billyvg** [comment]
Looks like it was indeed the `close()` followed by the `quit()` that was causing this. Interesting that this wasn't a problem until we upgraded to chromedriver 2.34. Thanks again!

**Comment by lmtierney** [comment]
Glad you got it figured out :+1:
