### ISSUE TITLE
IEdriver initialize failed.

### ISSUE THREAD

**Issue by kevin94chen** [SeleniumHQ/selenium#5748]
## Meta -
OS:  Windows 10

Browser:  Internet Explorer

Browser Version: IE11  

## Expected Behavior -
I tried initialize my iedriver but failed, i was setting my config as [doc says](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration)

Plz help me find out the problem!

(I also tested other driver like Chromedriver run my code, it's can work.)

## Actual Behavior -

`from selenium import webdriver`
`driver = webdriver.Ie(log_level= 'DEBUG', log_file = r'D:\Google Drive\Project\autologinVPN\logfile.txt')`

Traceback (most recent call last):
  File "D:/Google Drive/Project/autologinVPN/Main.py", line 5, in <module>
    driver = webdriver.Ie(log_level= 'DEBUG', log_file = r'D:\Google Drive\Project\autologinVPN\logfile.txt')
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 87, in __init__
    desired_capabilities=capabilities)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 528, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Program Files\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host遠端主機已強制關閉一個現存的連線。

Here is DEBUG logfile:
I 2018-04-10 13:29:17:539 server.cc(86) Starting WebDriver server on port: '50847' on host: ''
I 2018-04-10 13:29:17:539 IEServer.cpp(33) Driver version: 3.9.0.0 (64-bit)
D 2018-04-10 13:29:17:539 server.cc(148) Civetweb ACL is -0.0.0.0/0,+127.0.0.1
D 2018-04-10 13:29:20:540 server.cc(281) Command: POST /session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {}}, "desiredCapabilities": {}}
D 2018-04-10 13:29:20:540 IESession.cpp(53) Mutex acquired for session initalization
D 2018-04-10 13:29:20:544 IESession.cpp(109) Releasing session initialization mutex
D 2018-04-10 13:29:20:544 command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"capabilities": {"firstMatch": [{}], "alwaysMatch": {}}, "desiredCapabilities": {}} }
D 2018-04-10 13:29:20:544 CommandHandlers\NewSessionCommandHandler.cpp(46) Found W3C capabilities structure
D 2018-04-10 13:29:20:544 CommandHandlers\NewSessionCommandHandler.cpp(208) Found alwaysMatch in capabilities
D 2018-04-10 13:29:20:544 CommandHandlers\NewSessionCommandHandler.cpp(572) Validating capabilities object
D 2018-04-10 13:29:20:544 CommandHandlers\NewSessionCommandHandler.cpp(572) Validating capabilities object

**Comment by diemol** [comment]
Apologies for the lack of response, this issue went stale probably because the information provided is not enough to identify if it is really a bug or a problem in the local configuration. 

We are doing an issue cleanup, so I will go ahead and close this issue. If it is still actual, please open a new one with all the required information on the template.
