### ISSUE TITLE
SQLException while running Testng test from command  prompt

### ISSUE THREAD

**Issue by narasimha678** [SeleniumHQ/selenium#575]
1.I have created one testNG test in eclips and in which i am using JDBC connection to connect to Excel as DB.
2.This process is working fine when i am running the test from eclips as testNG test using testng xml file.
3.But when i run the same test from command prompt , it is giving below error.
Please let me know why the test is failing from command prompt.

Error:
java.sql.SQLException: [Microsoft][ODBC Driver Manager] Data source name not fou
nd and no default driver specified
        at sun.jdbc.odbc.JdbcOdbc.createSQLException(Unknown Source)
        at sun.jdbc.odbc.JdbcOdbc.standardError(Unknown Source)
        at sun.jdbc.odbc.JdbcOdbc.SQLDriverConnect(Unknown Source)
        at sun.jdbc.odbc.JdbcOdbcConnection.initialize(Unknown Source)
        at sun.jdbc.odbc.JdbcOdbcDriver.connect(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at com.Framework.OEMAuto.Generics.GC10_ExcelDBC.GMExcelDB(GC10_ExcelDBC.
java:39)
        at com.Framework.OEMAuto.Methods.AddTargetPageMeth.TMSelectMenu(AddTarge
tPageMeth.java:25)
        at com.Framework.OEMAuto.Test.TC2_OEMAuto_AddTarget.GMSearchBook(TC2_OEM
Auto_AddTarget.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocat
ionHelper.java:85)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWork
er.java:124)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
        at org.testng.TestRunner.privateRun(TestRunner.java:767)
        at org.testng.TestRunner.run(TestRunner.java:617)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
        at org.testng.SuiteRunner.run(SuiteRunner.java:254)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
        at org.testng.TestNG.run(TestNG.java:1057)
        at org.testng.TestNG.privateMain(TestNG.java:1364)
        at org.testng.TestNG.main(TestNG.java:1333)

**Comment by AutomatedTester** [comment]
WebDriver does not have a SQL component so the issue is not webdriver related. 

Also for issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
