### ISSUE TITLE
Unable to connect to the remote server 'driver.Manage().Timeouts()'

### ISSUE THREAD

**Issue by mh884** [SeleniumHQ/selenium#5765]
## Meta -
OS:  Windows 10
Selenium Version:  2.37
Browser:  chrome
i got this message after waiting command line 
driver.Manage().Timeouts().ImplicitWait = (TimeSpan.FromSeconds(10));

Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:60837
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

**Comment by Sathiyanarayanns** [comment]
driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
Plz use this above line coding because i think u mentioned initial case caps for Manage().Timeouts().ImplicitlyWait

**Comment by fonzi** [comment]
I recently have been seeing this as well. However, I am starting the webdriver with default values. I'm wondering if this is a real bug? Or just a misconfiguration since it's been open for quite a while now?

**Comment by diemol** [comment]
Is this issue still valid? If so, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by fonzi** [comment]
@diemol This has no longer been an issue for myself. I updated the chrome version to latest and matched it with the WebDriver.

**Comment by diemol** [comment]
Thank you for replying!
