### ISSUE TITLE
using iewebdriver in Selenium for Python:ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by mmoskovits** [SeleniumHQ/selenium#5785]
I am learning Selenium and am at the point where I want to test a simple script with the Selenium Iewebdriver. 

This same script executed successfulIy with the chromedriver. I am running IE11 on a Windows 64 bit Windows 10 PC. 

I have looked up the error(s) below on various sites and have found numerous suggestions concerning changing Proxy settings, browser settings, etc. 

None of the suggestion were very clear. 

I did follow all the recommendations in https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver but am still having these issues. 

Any suggestions are greatly appreciated!

================================================================
from selenium import webdriver

iepath="C:\\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\selenium\webdriver\IEDriverServer_x64_3.11.1\IEDriverServer.exe"
driver1=webdriver.Ie(iepath)
driver1.get("http://google.com")
print (driver1.title)
================================================================
Traceback (most recent call last):

  File "C:\Users\Marc.Marc-PC\eclipse-workspace\Basic\com\IEbrowser.py", line 15, in <module>
    driver1=webdriver.Ie(iepath)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 87, in __init__
    desired_capabilities=capabilities)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 528, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Marc.Marc-PC\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by Congee** [comment]
This is an actual issue. No public solution exists.

https://groups.google.com/forum/#!searchin/selenium-users/connection$20error$20forcibly$20closed|sort:date/selenium-users/7GqjfklcAkw/kgla7mu5BwAJ

https://stackoverflow.com/questions/45342383/python-selenium-connectionreseterror-winerror-10054-an-existing-connection-wa

**Comment by ThomIves** [comment]
@mmoskovits , I was having the same challenges. I came along 16 months after you, but I did get somewhere. Please go to my StackOverflow answer [HERE](https://stackoverflow.com/questions/45342383/python-selenium-connectionreseterror-winerror-10054-an-existing-connection-wa/57418752#57418752), and see if that question and the answers including mine help you. I hope they do to some measure.
