### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: chrome failed to start

### ISSUE THREAD

**Issue by r8w9a5k** [SeleniumHQ/selenium#5786]
Meta -
OS:
Win10

Selenium Version:
3.11.0 

Browser:
Chrome

Browser Version:  Chrome 65

## Expected Behavior
Run selenium and webdriver

## Actual Behavior
selenium.common.exceptions.WebDriverException: Message: unknown error: chrome failed to start

## Steps to reproduce
I have two identical Dell computers both runs win 10 64 bit, python 3.6.5, selenium 3.11.0, chromedriver 2.3.7. First computer runs perfectly but the second one has error:
_selenium.common.exceptions.WebDriverException: Message: unknown error: chrome failed to start_

Full error:
```
Traceback (most recent call last):
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\.pyProjects\vcasdgas\exdasfgsal.py", line 11, in <module>
    browser = webdriver.Chrome()
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\kristof\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: chrome failed to start
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.16299 x86_64)
```

**Comment by lmtierney** [comment]
> I have two identical Dell computers both runs win 10 64 bit, python 3.6.5, selenium 3.11.0, chromedriver 2.3.7. First computer runs perfectly but the second one has error

Then it is an environment issue and not a selenium issue
