### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: session not created exception from disconnected: unable to connect to renderer

### ISSUE THREAD

**Issue by ankedia** [SeleniumHQ/selenium#5789]
I'm running into this issue when running with 10 concurrent threads. 2 threads encounter this issue while other 8 threads don't encounter the issue.

[2018-04-17 16:00:05,707 UTC] [ScenarioRunner-1] [pool-1-thread-96] [ERROR] - (vUser 5) org.openqa.selenium.SessionNotCreatedException: session not created exception
 from disconnected: unable to connect to renderer
 (Session info: chrome=65.0.3325.181)
 (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.1.12-112.14.13.el7uek.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
 Command duration or timeout: 1.75 seconds
 Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
 System info: host: 'burbe27.us.oracle.com', ip: '10.149.32.22', os.name: 'Linux', os.arch: 'amd64', os.version: '4.1.12-112.14.13.el7uek.x86_64', java.version: '1.8.0_102'
 Driver info: driver.version: ChromeDriver
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
 at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
 at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
 at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
 at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
 at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
 at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
 at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
 at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
 at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
 at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
 at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
 at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
 at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
 at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:132)
 at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:181)
 at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:168)
 at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:157)
 at com.oracle.enterprisetest.tools.lg.core.ScenarioRunner.createScenarioConext(ScenarioRunner.java:343)
 at com.oracle.enterprisetest.tools.lg.core.ScenarioRunner.doRun(ScenarioRunner.java:150)
 at com.oracle.enterprisetest.tools.lg.core.ScenarioRunner.run(ScenarioRunner.java:99)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

**Comment by barancev** [comment]
Please report this issue to chromedriver: https://sites.google.com/a/chromium.org/chromedriver/help
