### ISSUE TITLE
Error forwarding the new session Empty pool of VM for setup Capabilities when upgrading from selenium-server v3.9.1 to v3.10.0

### ISSUE THREAD

**Issue by goodbomb** [SeleniumHQ/selenium#5802]
## Meta -
OS:  
Windows 10

Selenium Version:  
3.10.0, 3.11.0

Browser:  
Chrome

Browser Version:  
Version 66.0.3359.117

## Expected Behavior -
Chrome launches and executes the test run without unexpected exceptions, like in version 3.9.1.

## Actual Behavior -
Receiving the following exception when trying to launch a chrome browser during an automation test run:

```
Caused by: org.openqa.grid.common.exception.GridException: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, javascriptEnabled: true, platformName: windows, version: }
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:118)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
```

## Steps to reproduce -
Not sure how to specifically reproduce this issue here, since our test framework has a lot of inter-connected parts. What would be great to know is if there were some specific changes in v3.10.0 over 3.9.1 that could cause this problem.

Also, what specifically causes this exception?

Thanks!

**Comment by barancev** [comment]
Create a simplified grid configuration (single node) that allows to reproduce this issue, show the command you use to start hub and node and complete hub log.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario.

**Comment by Amrkamel1** [comment]
@barancev im facing same issue, im trying to lunch appium server with my java code with loading node configuration file argument as shown below but it doesnt work and throws this error message :
 
>22:06:17.748 INFO [RequestHandler.process] - Error forwarding the new session Empty pool of VM for setup Capabilities {appActivi

this is my **baseSetup class**

`public class BaseSetup   {

    protected static AndroidDriver<MobileElement> driver = null;
    protected AppiumDriverLocalService service;
    public WebDriverWait wait;
    private ThreadLocalDriver threadLocalDriver = new ThreadLocalDriver();


    @Parameters({"deviceName","platformVersion","udid","URL_","Sport","deviceId","sysPort","bootStrap","wdaPort","path"})
    @BeforeMethod(alwaysRun = true)
    public void setUp (String deviceName, String platformVersion, String udid, String URL_, String Sport, String deviceId, String sysPort, String bootStrap, String wdaPort, String path) throws MalformedURLException {
        System.out.println("Driver Is Initiated");

        DesiredCapabilities dc = new DesiredCapabilities();

        // mobile setup
        dc.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
        dc.setCapability("appium:deviceId", deviceId);
//        dc.setCapability("uiautomator2ServerInstallTimeout", "6000");

//      dc.setCapability(MobileCapabilityType.UDID,udid_);
        dc.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        dc.setCapability(MobileCapabilityType.PLATFORM_VERSION, platformVersion);
        dc.setCapability(AndroidMobileCapabilityType.SYSTEM_PORT, sysPort);
//        dc.setCapability(AndroidMobileCapabilityType.KEY_PASSWORD,"cvcv");
//        dc.setCapability("appium:unlockKey", "@0122882435abA");
        dc.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");


        //application setup
        dc.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "vcvcv");
        dc.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "cvcv");
        dc.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS,"true");
        dc.setCapability(MobileCapabilityType.CLEAR_SYSTEM_FILES, true);

//        driver configuration
    int port = Integer.parseInt(Sport);

     service = AppiumDriverLocalService
            .buildService(new AppiumServiceBuilder()
                    .usingDriverExecutable(new File("/usr/local/bin/node"))
                    .withAppiumJS(new File("/Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.js"))
                    .withArgument(Arg.ADDRESS,URL_)
                    .withArgument(Arg.NODECONFIG,path)
                    .withArgument(Arg.BootstrapPort,bootStrap)
                    .withArgument(Arg.SESSIONOVERRIDE)
                    .withArgument(Arg.CALLBACKPORT,Sport)
                    .withArgument(Arg.WDALOCALPORT,wdaPort)

                    .usingPort(port));

                service.start();

        threadLocalDriver.setTLDriver(new AndroidDriver<MobileElement>(new URL("http://"+URL_+":4444/wd/hub"),dc));
        driver = threadLocalDriver.getTLDriver();
        wait = new WebDriverWait(driver, 10);

    }

//    @AfterMethod
//    public void tearDown(){
//        driver.quit();
//        service.stop();
//        System.out.println("Driver quit");
//    }

    @AfterMethod
    public synchronized void teardown() {
        if (driver != null) {
            driver.quit();
            service.stop();
//        }
    }
    }

}
`
this is my **testng xml file**

`?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Default Suite" thread-count="5" parallel="tests" verbose="2">
<test name="Note8">
    <parameter name="deviceName" value="SM_N950F"/>
    <parameter name="udid" value="988a1641434e36333130"/>
    <parameter name="deviceId" value="192.168.1.4:5555"/>
    <parameter name="platformVersion" value="9"/>
    <parameter name="URL_" value="127.0.0.1"/>
    <parameter name="Sport" value="5000"/>
    <parameter name="bootStrap" value="4725"/>
    <parameter name="sysPort" value="8230"/>
    <parameter name="wdaPort" value="8230"/>
    <parameter name="path" value="/Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/selenium/note8.json"/>

    <classes>
        <class name="Tests.LandingPageTest"/>
    </classes>
</test> 

    <test name="Note5">
        <parameter name="deviceName" value="SM_N9208"/>
        <parameter name="udid" value="0715f75124ea0934"/>
        <parameter name="deviceId" value="192.168.1.9:5556"/>
        <parameter name="platformVersion" value="7.0"/>
        <parameter name="URL_" value="127.0.0.1"/>
        <parameter name="Sport" value="5001"/>
        <parameter name="bootStrap" value="4726"/>
        <parameter name="sysPort" value="8240"/>
        <parameter name="wdaPort" value="8240"/>
        <parameter name="path" value="/Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/selenium/note5.json"/>

        <classes>
            <class name="Tests.LandingPageTest"/>
        </classes>
    </test> 


</suite> 
`

**this is the console long :**
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: Error forwarding the new session Empty pool of VM for setup Capabilities {appActivity: gfhg, appPackage: hjgh, appium:deviceId: 192.168.1.9:5556, autoGrantPermissions: true, automationName: uiautomator2, clearSystemFiles: true, deviceName: SM_N9208, platformName: android, platformVersion: 7.0, systemPort: 8240}
Command duration or timeout: 484 milliseconds

**command used for selenium grid is** 
java -jar selenium-server-standalone-3.141.59.jar -role hub
