### ISSUE TITLE
Getting error : Uncaught WebDriverError: connection refused in docker only

### ISSUE THREAD

**Issue by bbest123** [SeleniumHQ/selenium#5808]
Hi,

I am trying to run node based selenium test case on my docker machine (on firefox gecko driver) but I am getting the below error. Can someone let me know what would be the issue?

**Version info:**
selenium-webdriver: 3.0.1
firefox : 55.0.3
geckodriver : 0.18.0

**Note:** The same test case runs fine on my local laptop and the issue is only when running on docker.

```
var profile = new firefox.Profile();
	    profile.setPreference("network.proxy.type", 1); // Manual proxy config
	    profile.setPreference("network.proxy.http", "test.proxy.com");
	    profile.setPreference("network.proxy.http_port", 8080);
	    profile.setPreference("network.proxy.ssl", "test.proxy.com");
	    profile.setPreference("network.proxy.ssl_port", 8080);
         
        var binary = new firefox.Binary(firefox.Channel);
         binary.addArguments("-headless");
         driver = new webdriver.Builder()
            .forBrowser(DriverName)
            .setFirefoxOptions(new firefox.Options().setBinary(binary).setProfile(profile))
            .build();

 driver.get(input).then(function () {
  });
```

**Error:**
```
  1) search api testing:
     Uncaught WebDriverError: connection refused
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:514:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:519:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
  From: Task: WebDriver.createSession()
      at Function.createSession (node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (node_modules/selenium-webdriver/firefox/index.js:521:41)
      at createDriver (node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (node_modules/selenium-webdriver/index.js:645:16)
      at getWebDriver (SearchAPI.js:71:14)
      at Object.<anonymous> (SearchAPI.js:77:14)
      at require (internal/module.js:11:18)
      at Array.forEach (<anonymous>)
      at startup (bootstrap_node.js:193:16)
      at bootstrap_node.js:617:3
  From: Task: WebDriver.navigate().to(http://abc.vci.com:3000/search?app-id=test&q=iphone)
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at Navigation.to (node_modules/selenium-webdriver/lib/webdriver.js:1133:25)
      at thenableWebDriverProxy.get (node_modules/selenium-webdriver/lib/webdriver.js:988:28)
      at Context.<anonymous> (SearchAPI.js:85:20)
      at runTest (node_modules/selenium-webdriver/testing/index.js:159:14)
      at node_modules/selenium-webdriver/testing/index.js:184:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1077:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:183:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
```

**Comment by frantallukas10** [comment]
I have same problem

**Comment by frantallukas10** [comment]
please who help us with this issue? I have same problem

**Comment by diemol** [comment]
If this works on your localhost and not inside a docker container, it is very much likely a network configuration issue when starting the docker container. Without any more context, it is really hard to know if something else is going on.

In any case, this leads to figuring out how to start the container properly, and you could send this question to: 
  * The [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * Or post it to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * Or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well
