### ISSUE TITLE
ExecuteScript and Actions don't deal with WrappedElements appropriately (from EventFiringWebDriver)

### ISSUE THREAD

**Issue by cwood-panopto** [SeleniumHQ/selenium#5810]
## Meta -
OS:  
All
Selenium Version:  
3.11.2
Browser:  
All (using EventFiringWebDriver) (used Chrome)

Browser Version:  
Any (used 66.0.3359.117 (64-bit))

## Expected Behavior -
Successfully perform actions or scripts using EventFiringWebDriver on WrappedElements.

## Actual Behavior -
Error message: System.ArgumentException : Argument is of an illegal typeOpenQA.Selenium.Support.Events.EventFiringWebDriver+EventFiringWebElement Parameter name: arg
Stack trace: 
at OpenQA.Selenium.Remote.RemoteWebDriver.ConvertObjectToJavaScriptObject(Object arg) at OpenQA.Selenium.Remote.RemoteWebDriver.ConvertArgumentsToJavaScriptObjects(Object[] args) at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args) at OpenQA.Selenium.Support.Events.EventFiringWebDriver.ExecuteScript(String script, Object[] args)

Error message: System.Reflection.TargetException : Object does not match target type.
Stack trace: 
at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target) at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at OpenQA.Selenium.Support.PageObjects.WebDriverObjectProxy.InvokeMethod(IMethodCallMessage msg, Object representedValue) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at OpenQA.Selenium.ILocatable.get_Coordinates() at OpenQA.Selenium.Interactions.MoveMouseAction.Perform() at OpenQA.Selenium.Interactions.CompositeAction.Perform()

## Steps to reproduce -
In both cases driver was EventFiringWebDriver and targetElement was [FindsBy(How = How.ClassName, Using = "some_class")]

public static void RunSomeScript(this IWebDriver driver, IWebElement targetElement)
{
    IJavaScriptExecutor js = (IJavaScriptExecutor)driver;
    js.ExecuteScript("arguments[0].scrollIntoView(true);", targetElement);
}

public void DoSomeAction(this IWebDriver driver, IWebElement targetElement)
{
    Actions action = new Actions(driver);
    action.MoveToElement(targetElement).Perform();
}

**Comment by cwood-panopto** [comment]
https://github.com/SeleniumHQ/selenium/pull/5811

**Comment by tomalec** [comment]
Have you found a workaround that could be used in the meantime before this PR get's merged and released?

**Comment by jimevans** [comment]
Merged in 54b37dc.

**Comment by cwood-panopto** [comment]
For those looking for a workaround until this releases, you can cast any element you pass to the ExecuteScript or Actions calls as IWrapsElement, get the WrappedElement, and pass that to the calls.
`action.MoveToElement(((IWrapsElement)element).WrappedElement).Build().Perform()`

**Comment by cwood-panopto** [comment]
You can cast any element you pass to the ExecuteScript or Actions calls as
IWrapsElement, get the WrappedElement, and pass that to the calls.
action.MoveToElement(((IWrapsElement)element).WrappedElement).Build().Perform()

On Mon, Apr 23, 2018 at 4:54 AM, Tomek Wytrębowicz <notifications@github.com
