### ISSUE TITLE
is_displayed method Issue

### ISSUE THREAD

**Issue by underscrew** [SeleniumHQ/selenium#5822]
## Meta -
OS:  Windows 10
Selenium Version:   3.11.0
Browser: Firefox 59.0.2 (64-bit)
geckodriver 0.20.1

## Expected Behavior -

```
element=driver.find_element_by_id("loginID")
boolean = element.is_displayed()
```

## Actual Behavior -

```
element=driver.find_element_by_id("loginID")
boolean = element.is_displayed()
```
TypeError: 'NoneType' object has no attribute '__getitem__'

## Steps to reproduce -
Use remote webdriver with my setup.

**Comment by lmtierney** [comment]
I cannot reproduce this.

Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by underscrew** [comment]
@lmtierney I'm sorry, forgot to say I am using RemoteWebDriver

**Comment by underscrew** [comment]
Ok, this is exactly the code i'm using here:

>

```import os
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver

def create_driver_session(session_id, executor_url):
    # Save the original function, so we can revert our patch
    org_command_execute = RemoteWebDriver.execute
    def new_command_execute(self, command, params=None):
        if command == "newSession":
            # Mock the response
            return {'success': 0, 'value': None, 'sessionId': session_id}
        else:
            return org_command_execute(self, command, params)
    # Patch the function before creating the driver object
    RemoteWebDriver.execute = new_command_execute
    new_driver = webdriver.Remote(command_executor=executor_url, desired_capabilities={})
    new_driver.session_id = session_id
    # Replace the patched function with original function
    RemoteWebDriver.execute = org_command_execute
    return new_driver

def writeDriver(driver):
    # Stores the driver sesssion
    driver.delete_all_cookies()
    session_url = driver.command_executor._url  
    session_id = driver.session_id
    with open('webDriver.log','wb') as f:
        f.write(session_url +','+ session_id)

def loadDriver():
    # Loads the driver session stored
    try:
        with open('webDriver.log','r') as f:
            a = f.read()
            session_url = a.split(',')[0]
            session_id = a.split(',')[1]
            driver = create_driver_session(session_id,session_url)
    except:
        driver = None
    return driver

def setUpDriver():
    global driver
    driver  = loadDriver()
    fp = webdriver.FirefoxProfile()
    options = Options()
    driver = webdriver.Firefox(firefox_profile=fp,firefox_options=options)
    writeDriver(driver)

setUpDriver()
driver = loadDriver()
driver.get('http:\\www.google.com')
element = driver.find_element_by_id('hplogo')
element.is_displayed()


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 485, in is_displayed
    if self._w3c and self.parent.capabilities['browserName'] == 'safari':
TypeError: 'NoneType' object has no attribute '__getitem__'```

**Comment by lmtierney** [comment]
Yeah, you definitely needed to include that you are modifying how a new session is created with your remote webdriver. Since you are modifying how the library works locally, we can't help you. I can give you a hint that you need to also reserve the returned capabilities from your original session and not just the session_id.

In the future, issues are reserved for issues with the selenium library itself.

**Comment by underscrew** [comment]
Adding `desired_capabilities = {'acceptInsecureCerts': True, 'browserName': 'firefox', 'marionette': True}` solved the problem.
Thanks a lot and sorry for the trouble.
