### ISSUE TITLE
set_page_load_timeout() issue

### ISSUE THREAD

**Issue by SergeyRademes** [SeleniumHQ/selenium#5888]
## Meta -
OS:  Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux

Selenium Version:  3.12.0

Browser:  Chrome

Browser Version:  66.0.3359.139 (64-bit)

Code: Python
## Expected Behavior -
Im using set_page_load_timeout () and TimeoutException to stop page load.
I expected after processing the timeout exception i can continue to work with webdriver

## Actual Behavior -

However, after processing the exclusion timeout all attempts at interaction with the driver end with a timout exception. I can not find items on the page, nor send a request to refresh the page. But web page is fully loaded.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/sf_C_DRIVE/presence.py", line 28, in <module>
    driver.find_element_by_tag_name("h1")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 523, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 957, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.9.0-6-amd64 x86_64)
```
## Steps to reproduce -
```
driver.set_page_load_timeout(5)
try:
   driver.get(url)
except TimeoutException:
   driver.find_element_by_tag_name("h1")
```

**Comment by lmtierney** [comment]
I have recreated this and it is an issue with chrome/chromedriver

Please log Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
