### ISSUE TITLE
A input element where type = 'checkbox' is not clickable 

### ISSUE THREAD

**Issue by sumanth1308** [SeleniumHQ/selenium#592]
Xpath:
//div[@class='ngSelectionCell ng-scope']/input[@id='browse_data']

HTML:
```
<div ng-cell="" class="">
<div class="ngSelectionCell ng-scope" ng-hide="false">
<input tabindex="-1" id="browse_data" ng-model="row.entity.selected" class="ng-selection-checkbox ng-valid ng-dirty ng-valid-parse ng-touched xh-highlight" type="checkbox">
<label for="browse_data" class="">
</label>
</div>
</div>
```

Code used with Exception raised :
```
>>> from selenium import webdriver
>>> driver = webdriver.Firefox()
>>> element = driver.find_element_by_xpath("//div[@class='ngSelectionCell ng-scope']/input[@id='browse_data']")
>>> element
<selenium.webdriver.remote.webelement.WebElement object at 0x0000000002DDC9B0>
>>> element.click
<bound method WebElement.click of <selenium.webdriver.remote.webelement.WebElement object at 0x0000000002DDC9B0>>
>>> element.click()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python26\lib\site-packages\selenium\webdriver\remote\webelement.py", line 65, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python26\lib\site-packages\selenium\webdriver\remote\webelement.py", line 402, in _execute
    return self._parent.execute(command, params)
  File "C:\Python26\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 175, in execute
    self.error_handler.check_response(response)
  File "C:\Python26\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: Element is not currently visible and so may not be interacted with
Stacktrace:
    at fxdriver.preconditions.visible (file:///c:/users/snk/appdata/local/temp/tmp7g9t5w/extensions/fxdriver@googlecode.com/components/command-process
or.js:9587)
    at DelayedCommand.prototype.checkPreconditions_ (file:///c:/users/snk/appdata/local/temp/tmp7g9t5w/extensions/fxdriver@googlecode.com/components/c
ommand-processor.js:12257)
    at DelayedCommand.prototype.executeInternal_/h (file:///c:/users/snk/appdata/local/temp/tmp7g9t5w/extensions/fxdriver@googlecode.com/components/co
mmand-processor.js:12274)
    at DelayedCommand.prototype.executeInternal_ (file:///c:/users/snk/appdata/local/temp/tmp7g9t5w/extensions/fxdriver@googlecode.com/components/comm
and-processor.js:12279)
    at DelayedCommand.prototype.execute/< (file:///c:/users/snk/appdata/local/temp/tmp7g9t5w/extensions/fxdriver@googlecode.com/components/command-pro
cessor.js:12221)```

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by klogan12** [comment]
I am facing similar issue , can someone please help?
