### ISSUE TITLE
Ruby bindings: @driver.manage.window.full_screen fails when using xvfb

### ISSUE THREAD

**Issue by jessp01** [SeleniumHQ/selenium#5927]
## Meta -
OS:  Linux, Ubuntu 16.04
Selenium Version:  
selenium-webdriver [3.12.0] installed from RubyGems, using Geckodriver v0.20.1, downloaded from https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
Ruby version: 2.3 - 2.3.1-2~16.04.9 [deb from the official repo]
Browser:  
Firefox, 60.0.1+build2-0ubun [deb from the official repo]

## Expected Behavior -
For the below test code to run successfully.

## Steps to reproduce -
Consider this code snippet:
```ruby
#!/usr/bin/ruby2.3
require "json"
require "selenium-webdriver"
gem "test-unit"
require "test/unit"

class Vconn1 < Test::Unit::TestCase

  def setup
    @profile = Selenium::WebDriver::Firefox::Profile.new
    @caps = Selenium::WebDriver::Remote::Capabilities.firefox(:firefox_profile => @profile)

    @base_url = "https://google.com"
    @driver = Selenium::WebDriver.for :firefox, desired_capabilities:@caps
    # when uncommenting this and commenting @driver.manage.window.full_screen, it works
    #@driver.manage.window.maximize
    @driver.manage.window.full_screen


    @accept_next_alert = true
    @driver.manage.timeouts.implicit_wait = 30
    @verification_errors = []
  end
  
  def teardown
    @driver.quit
    assert_equal [], @verification_errors
  end
  
  def test_vconn1
    @driver.get(@base_url )
    @driver.find_element(:id, "lst-ib").send_keys "Selenium xvfb firefox full screen problem"
    @driver.find_element(:name, "btnK").click
    #sleep(120)
  end
  
  def element_present?(how, what)
    @driver.find_element(how, what)
    true
  rescue Selenium::WebDriver::Error::NoSuchElementError
    false
  end
  
  def alert_present?()
    @driver.switch_to.alert
    true
  rescue Selenium::WebDriver::Error::NoAlertPresentError
    false
  end
  
  def verify(&blk)
    yield
  rescue Test::Unit::AssertionFailedError => ex
    @verification_errors << ex
  end
  
  def close_alert_and_get_its_text(how, what)
    alert = @driver.switch_to().alert()
    alert_text = alert.text
    if (@accept_next_alert) then
      alert.accept()
    else
      alert.dismiss()
    end
    alert_text
  ensure
    @accept_next_alert = true
  end
end
```

This works well outside of `xvfb-run` context. When calling it like so:
```sh
$ xvfb-run -s ":99 -auth /tmp/xvfb.auth -ac -screen 0 1920x1080x24" /path/to/above/code/snippet   &
```
it fails with the below BT.

## Actual Behavior -
```
Error: test_vconn1(Vconn1): Net::ReadTimeout: Net::ReadTimeout
/usr/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
/usr/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
/usr/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
/usr/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
/usr/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
/usr/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
/usr/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
/usr/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
/usr/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/usr/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
/usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/var/lib/gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
/var/lib/gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
/var/lib/gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
/var/lib/gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
/var/lib/gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
/var/lib/gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/w3c/bridge.rb:192:in `full_screen_window'
/var/lib/gems/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/window.rb:157:in `full_screen'
/tmp/sel_gecko_test.rb:22:in `setup'
```

When commenting out:
```ruby
@driver.manage.window.full_screen
```
and replacing it with:
```ruby
@driver.manage.window.maximize
```
it works correctly in xvbf context as well so the issue is only with `@driver.manage.window.full_screen`

Thanks in advance,

**Comment by lmtierney** [comment]
All selenium does is send a POST with data to geckodriver. This would be a geckodriver/firefox issue. Please log an issue there https://github.com/mozilla/geckodriver/issues

**Comment by jessp01** [comment]
Thanks, @lmtierney. Opened https://github.com/mozilla/geckodriver/issues/1281.
