### ISSUE TITLE
Option to ignore StaleElementReferenceErrors

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SeleniumHQ/selenium#5938]
## Meta
OS:  Windows 10
Selenium Version:  selenium-webdriver@4.0.0-alpha.1
Browser:  Firefox (GeckoDriver)
Browser Version: 59

Consider a test that:

1. Loads an often-changing page
2. Grabs an element from the page
3. Gets the text of that element

I don't care that the element is becoming stale (being removed from the DOM). I just want to check what its text _was_ at one point.

## Expected Behavior

Running without errors.

## Actual Behavior

```
StaleElementReferenceError: The element reference of <button id="useful"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:542:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:468:26)
```

## Steps to reproduce -

1. Run a page that constantly creates and removes elements: https://codepen.io/joshuakgoldberg/pen/pVmdOa

2. Try to grab an element on the page and its text content with `selenium-webdriver`:

```javascript
const element = await browser.findElement(By.id("useful"));

const text = await element.getText(); // throws an error most of the time
```

**Comment by JoshuaKGoldberg** [comment]
Did some digging. `selenium-webdriver` by design can't overcome these errors. Will look elsewhere. 😊

Explanation: WebDriver has us communicating with the page via a protocol that specifies elements by an ID. If the element is removed, the ID goes away.
