### ISSUE TITLE
iframe - Can't access dead object

### ISSUE THREAD

**Issue by erobinson** [SeleniumHQ/selenium#594]
When a page is open with an iframe inside of an iframe
 - page root (grandparent) -> iframe (parent) -> iframe (grand child)
When you click a button that closes the grandchild
Then you get an error saying "can't access dead object" 

The issue may exist with only 2 layers (parent / child) as opposed to 3 layers (grandparent / parent / grandchild)

It seems that the driver is trying to maintain a reference to the button that was clicked. However, the button no longer exists and thus the webdriver implodes.

org.openqa.selenium.WebDriverException: [JavaScript Error: "can't access dead object" {file: "file:///C:/Users/EROBIN~1/AppData/Local/Temp/anonymous7258014280690691374webdriver-profile/extensions/fxdriver@googlecode.com/components/synthetic-mouse.js" line: 8083}]'[JavaScript Error: "can't access dead object" {file: "file:///C:/Users/EROBIN~1/AppData/Local/Temp/anonymous7258014280690691374webdriver-profile/extensions/fxdriver@googlecode.com/components/synthetic-mouse.js" line: 8083}]' when calling method: [wdIMouse::click]
Command duration or timeout: 4.80 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'EdwardXPS', ip: '10.0.1.32', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_31'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 36ce4e5d-980b-48bd-8ede-76e151710404

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
	at gov.irs.gdi.ui.ui.UIActions.click(UIActions.java:344)
	at gov.irs.gdi.ui.pages.blops.BlopsConsoleCreate.submitTicket(BlopsConsoleCreate.java:122)
	at gov.irs.gdi.ui.pages.blops.BlopsConsoleCreate.createODWTicket(BlopsConsoleCreate.java:92)
	at gov.irs.gdi.ui.blops.reg.create.BlopsRegCreateSteps.i_submit_the_ODW_Ticket_even_if_the_system_detects_that_a_similar_ODW_ticket_has_already_been_submitted(BlopsRegCreateSteps.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cucumber.runtime.Utils$1.call(Utils.java:34)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:30)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:35)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:298)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:48)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:346)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Caused by: org.openqa.selenium.WebDriverException: [JavaScript Error: "can't access dead object" {file: "file:///C:/Users/EROBIN~1/AppData/Local/Temp/anonymous7258014280690691374webdriver-profile/extensions/fxdriver@googlecode.com/components/synthetic-mouse.js" line: 8083}]'[JavaScript Error: "can't access dead object" {file: "file:///C:/Users/EROBIN~1/AppData/Local/Temp/anonymous7258014280690691374webdriver-profile/extensions/fxdriver@googlecode.com/components/synthetic-mouse.js" line: 8083}]' when calling method: [wdIMouse::click]
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'EdwardXPS', ip: '10.0.1.32', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_31'
Driver info: driver.version: unknown

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Xing-He** [comment]
I just ran into the same problem.  

> `SwitchTo` `frame A`and then do some operations , after that the web jump to another url, so the frame just been destroyed. when i want to something with `driver.xxx`, it show errors that `Can't access dead object`

i  solved  this error with `driver.switchTo()` to get `target locator` and `targetLocator.defaultContent()` to switch focus to the topmost frame 

- [switchto](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_ThenableWebDriver.html#switchTo)
- [target locator](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_TargetLocator.html#defaultContent)
