### ISSUE TITLE
Getting connection refused error while executing Selenium + Firefox test case using SSH (OpenSSH) on Windows 

### ISSUE THREAD

**Issue by navinchandrac** [SeleniumHQ/selenium#5958]
## System

Software installed:
•	Operating System : Windows 10 (64-bit)
•	Selenium (3.7.1) with java-client 6.0.0-Beta2
•	GeckoDriver (0.20.1 – 64bit)
•	Firefox 58.0b9 (64-bit)
•	Apache-Maven-3.3.9
•	TestNG (6.11)
•	OpenSSH (Windows)
•	Putty with Plink (for Command line execution for SSH)

## Testcase

Steps to reproduce:
1.	Create maven project  (e.g Name: AutomationTestProject)
2.	Add sample selenium test case (as mentioned below)
        @Test(groups = { "SSH" }, description = "1101: google3")
	public void google4SSHTesting() throws InterruptedException, IOException {

		System.setProperty("webdriver.gecko.driver", "D:\\AutomationTestProject\\setupfiles\\Fusion\\geckodriver.exe");
		System.setProperty(FirefoxDriver.SystemProperty.DRIVER_USE_MARIONETTE, "true");

		LoggingPreferences loggingPrefs = new LoggingPreferences();
		loggingPrefs.enable(LogType.BROWSER, Level.ALL);
		loggingPrefs.enable(LogType.CLIENT, Level.ALL);
		loggingPrefs.enable(LogType.DRIVER, Level.ALL);
		loggingPrefs.enable(LogType.PERFORMANCE, Level.ALL);
		loggingPrefs.enable(LogType.PROFILER, Level.ALL);
		loggingPrefs.enable(LogType.SERVER, Level.ALL);
		DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
		desiredCapabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		desiredCapabilities.setCapability(CapabilityType.LOGGING_PREFS, loggingPrefs);

		FirefoxOptions options = new FirefoxOptions();
		options.setAcceptInsecureCerts(true);
		options.setLogLevel(FirefoxDriverLogLevel.TRACE);
		options.merge(desiredCapabilities);

		WebDriver driver = new FirefoxDriver(options);
		driver.get("http://www.google.com");
		Thread.sleep(5000);
		driver.quit();
	}
3.	Create TestNG file for above test case
4.	Create POM file for test case execution triggering
5.	Clean and build the project.

Execution Test Cases Using SSH (Command line):
1.	Open command prompt on Windows machine.
2.	Navigate to putty folder for plink command execution (as mentioned below).

        **plink -ssh -X uesr123@172.27.30.52 -pw testpwd@123 "cmd /c cd /d 'D:\AutomationTestProject' '&&' mvn exec:java"**

3.	Above command will establish the SSH connection on Windows machine and triggering POM file execution.
Note: SSH execution will be done in background (it will start GeckoDrive and Firefox Browser in background, for verification you can check it Task Manager).

## Stacktrace

D:\PuTTY>plink -ssh -X usersa@172.25.30.52 -pw testpassword@123 "cmd /c cd /d 'D:\AutomationTestProject' '&&' mvn exec:java"
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.package.automation:MavenTestProject:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-compiler-plugin @ line 160, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MavenTestProject 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ MavenTestProject >>>
[INFO]
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ MavenTestProject <<<
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ MavenTestProject ---
POM location - D:\AutomationTestProject\pom.xml
Starting Setup..
Current machine IP - 172.25.30.52
Base directory path for others - D:\AutomationTestProject\TE_Testing_Windows_Web_FF_25052018114548
Execution INI file folder - D:\AutomationTestProject\TE_Testing_Windows_Web_FF_25052018114548\Configuration
In loadIniFile - D:\AutomationTestProject\TE_Testing_Windows_Web_FF_25052018114548\Configuration
Directory is created!
File saved!
********* Process with IP *********
********* End Process with IP *********
Done Setup..
Started with POM operation...
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.package.automation:MavenTestProject:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-compiler-plugin @ line 160, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MavenTestProject 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ MavenTestProject ---
[INFO] Deleting D:\AutomationTestProject\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MavenTestProject ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ MavenTestProject ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 2 source files to D:\AutomationTestProject\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ MavenTestProject ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ MavenTestProject ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 48 source files to D:\AutomationTestProject\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ MavenTestProject ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
Base directory path for others - D:\AutomationTestProject\TE_Testing_Windows_Web_FF_25052018114548
Execution INI file folder - D:\AutomationTestProject\TE_Testing_Windows_Web_FF_25052018114548\Configuration
Report Constructor: Report Path: D:\AutomationTestProject\TE_Testing_Windows_Web_FF_25052018114548 Report File Name: TE_Testing_Windows_Web_FF_25052018114548
In loadIniFile - D:\AutomationTestProject\TE_Testing_Windows_Web_FF_25052018114548\Configuration
External Configuration INI file Path - D:\AutomationTestProject
***Test Case created for WebDemoTests.google4SSH with test id 1
In loadIniFile - D:\AutomationTestProject\TE_Testing_Windows_Web_FF_25052018114548\Configuration
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/lntestsa/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/lntestsa/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
1527660431284   geckodriver     INFO    geckodriver 0.20.1 (685f18325cea0a282c736e65972f95aa6db7ca48 2018-04-03)
1527660431291   geckodriver     INFO    Listening on 127.0.0.1:10575
1527660431933   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\lntestsa\\rust_mozprofile.X0AglP7JYgoP"
1527660432975   Marionette      INFO    Enabled via --marionette
org.openqa.selenium.WebDriverException: connection refused
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'COEMOBILE-W10', ip: '169.254.224.173', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_77'
Driver info: driver.version: SelUIBaseDriver
remote stacktrace:
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
        at com.cybage.webframework.SelUIBaseDriver.uiDriverSetup(SelUIBaseDriver.java:160)
        at com.frameworkbase.DriverBase.getUIDriver(DriverBase.java:160)
        at com.web.tests.WebDemoTests.googlesetupnew(WebDemoTests.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:744)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
        at org.testng.SuiteRunner.run(SuiteRunner.java:289)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
        at org.testng.TestNG.runSuites(TestNG.java:1144)
        at org.testng.TestNG.run(TestNG.java:1115)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
In Framework Exception connection refused
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'COEMOBILE-W10', ip: '169.254.224.173', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_77'
Driver info: driver.version: SelUIBaseDriver
remote stacktrace:
***Test Case created for Configuration Failures for Test -'Test Firefox' with test id 1
Configuration failed -WebDemoTests.googlesetupnew : Framework Exception connection refused
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'COEMOBILE-W10', ip: '169.254.224.173', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_77'
Driver info: driver.version: SelUIBaseDriver
remote stacktrace:
In End Suite for:Web_Windows - 1
In End Report
End Suite : Web_Windows
In End Report
Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 63.621 sec <<< FAILURE! - in TestSuite
googlesetupnew(com.web.tests.WebDemoTests)  Time elapsed: 63.118 sec  <<< FAILURE!
com.cybage.frameworkutility.exception.FrameworkException:
Framework Exception connection refused
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'COEMOBILE-W10', ip: '169.254.224.173', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_77'
Driver info: driver.version: SelUIBaseDriver
remote stacktrace:
        at com.web.tests.WebDemoTests.googlesetupnew(WebDemoTests.java:32)

Results :

Failed tests:
  WebDemoTests.googlesetupnew:32->DriverBase.getUIDriver:160 ╗ Framework Framewo...

Tests run: 2, Failures: 1, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:09 min
[INFO] Finished at: 2018-05-30T11:38:14+05:30
[INFO] Final Memory: 59M/443M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project MavenTestProject: There are test failures.
[ERROR]
[ERROR] Please refer to D:\AutomationTestProject\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Result - org.apache.maven.shared.invoker.DefaultInvocationResult@1fe1cb47
Exception occured in main method. Exception details - Build failed.
64 bit machine.................
Down the environment successfully...
Test execution Completed sucessfully
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:13 min
[INFO] Finished at: 2018-05-30T11:38:14+05:30
[INFO] Final Memory: 28M/352M
[INFO] ------------------------------------------------------------------------

**Comment by barancev** [comment]
SSH session does not have access to the desktop. Firefox browser can't work without "interactive session", it's a GUI application.
