### ISSUE TITLE
Protractor coniiguration not working

### ISSUE THREAD

**Issue by donseenugmail** [SeleniumHQ/selenium#5964]
I get the below error message and it is after executing the commands
1) webdriver-manager update, 
2) webdriver-manager start and 
3) protractor conf.js.

```
(node:4155) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.[14:50:37] I/launcher - Running 1 instances of WebDriver[14:50:37] I/hosted - Using the selenium server at http://localhost:4444/wd/hub[14:51:38] E/launcher - unknown error: DevToolsActivePort file doesn't exist(Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.4.0-127-generic x86_64) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 60.11 secondsBuild info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'System info: host: 'shaik', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-127-generic', java.version: '1.8.0_171'Driver info: driver.version: unknown[14:51:38] E/launcher - WebDriverError: unknown error: DevToolsActivePort file doesn't exist(Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.4.0-127-generic x86_64) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 60.11 secondsBuild info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'System info: host: 'shaik', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-127-generic', java.version: '1.8.0_171'Driver info: driver.version: unknownat Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)at doSend.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)atat process._tickCallback (internal/process/next_tick.js:160:7)From: Task: WebDriver.createSession()at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:761:15)at createDriver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:626:16)at Hosted.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:195:43)at q.then.then (/usr/local/lib/node_modules/protractor/built/runner.js:339:29)at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)[14:51:38] E/launcher - Process exited with error code 199
```

**Comment by barancev** [comment]
Please report this issue to Protractor team.

**Comment by obsessiveprogrammer** [comment]
@donseenugmail , I'm struggling with the same thing.  Did you report this in protractor or find a solution?

**Comment by glins97** [comment]
Same here.

**Comment by timnederhoff** [comment]
same here. @donseenugmail did you run in Docker? Already found a solution? or reported at protractor? Otherwise I file one myself.
ps. @barancev seems a webdriver issue to me, right?

**Comment by rtm** [comment]
I don't understand why this would be considered to be a protractor bug. The error is clearly coming from Selenium/launcher.

**Comment by lmtierney** [comment]
@rtm I don't see it _clearly_ coming from Selenium. We'd be glad to troubleshoot if you provide a reproducible scenario using *just* selenium and not `protractor` OR `webdriver-manager` since neither of them are maintained by the selenium team

**Comment by tony2tones** [comment]
I was having the very same problem, the solution i found was to downgrade your ChromeDriver. I downgraded mine to version 2.37

You can use this command
webdriver-manager update --versions.chrome 2.37
