### ISSUE TITLE
getting  error while run normal web page on eclipse its some driver issue

### ISSUE THREAD

**Issue by Mayank1208** [SeleniumHQ/selenium#5967]
OS:  

Selenium Version:  

Browser:  
<!-- Chrome

Code
package Test;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class LoadDvWeb {
	
	public static void main(String[] args) {
		
		System.setProperty("webdriver.chromedriver.driver",
				"D://Chrome//chromedriver.exe");
		
		driver.get("http://192.168.1.21/");
	}

}

error

Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	driver cannot be resolved

	at Test.LoadDvWeb.main(LoadDvWeb.java:13)

how can i solve this????

**Comment by Mayank1208** [comment]
OS:  

Selenium Version:  

Browser:  
<!-- Chrome

Code
package Test;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class LoadDvWeb {
	
	public static void main(String[] args) {
		
		System.setProperty("webdriver.chromedriver.driver",
				"D://Chrome//chromedriver.exe");
		
		driver.get("http://192.168.1.21/");
	}

}

error

Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	driver cannot be resolved

	at Test.LoadDvWeb.main(LoadDvWeb.java:13)

how can i solve this????
