### ISSUE TITLE
Returns: Failed: Uploading directories is not supported when sendkeys to input

### ISSUE THREAD

**Issue by darrenlau86** [SeleniumHQ/selenium#5988]
Versions:
[16:04:39] I/status - selenium standalone version available: 3.12.0 [last]
[16:04:39] I/status - chromedriver versions available: 2.38, 2.39 [last]
[16:04:39] I/status - geckodriver version available: v0.20.1 [last]
[16:05:02] I/version - webdriver-manager 12.0.6

Code: 
ApplicationDetailsPage.prototype.fillAppDetail = function (apiName, realm) {
  apiName = apiName || 'InitialTestAPI';
  realm = realm || 'test';
  browser.wait(EC.visibilityOf(this.requestRealmName), timeOut);
  this.selectApi(apiName);
  this.requestRealmName.sendKeys(realm);
  this.requestTestRealm.click();
  this.requestSubmitBtn.click();};

Issue:
Issue happens in line:   this.requestRealmName.sendKeys(realm); 
when call fillAppDetail method, and don't pass realm value. It will use default value "test" and return following 

error:
F    ✗ request production access with created api
      - Failed: Uploading directories is not supported: test
          at TypeError (native)
          at /Users/c5253649/Projects/openapi/apiportal/node_modules/selenium-webdriver/remote/index.js:344:13
          at promise.ControlFlow.runInFrame_ (/Users/c5253649/Projects/openapi/apiportal/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
          at wrappedCtr.notify (/Users/c5253649/Projects/openapi/apiportal/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
          at promise.Promise.notify_ (/Users/c5253649/Projects/openapi/apiportal/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
          at Array.forEach (native)
          at promise.Promise.notifyAll_ (/Users/c5253649/Projects/openapi/apiportal/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
          at goog.async.run.processWorkQueue (/Users/c5253649/Projects/openapi/apiportal/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
      From: Task: WebElement.sendKeys()
          at WebElement.sendKeys (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:2185:43)
          at actionFn (/usr/local/lib/node_modules/protractor/built/element.js:89:44)
          at Array.map (native)
          at actionResults.getWebElements.then (/usr/local/lib/node_modules/protractor/built/element.js:461:65)
          at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
          at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27)
          at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
          at process._tickCallback (internal/process/next_tick.js:103:7)Error
          at ElementArrayFinder.applyAction_ (/usr/local/lib/node_modules/protractor/built/element.js:459:27)
          at ElementArrayFinder.(anonymous function) [as sendKeys] (/usr/local/lib/node_modules/protractor/built/element.js:91:29)
          at ElementFinder.(anonymous function) [as sendKeys] (/usr/local/lib/node_modules/protractor/built/element.js:831:22)
          at Service.ApplicationDetailsPage.sendString (/Users/c5253649/Projects/openapi/apiportal/e2e/test-framework/pages/application-details-page.js:43:9)
          at Service.ApplicationDetailsPage.fillAppDetail (/Users/c5253649/Projects/openapi/apiportal/e2e/test-framework/pages/application-details-page.js:37:8)
          at UserContext.<anonymous> (/Users/c5253649/Projects/openapi/apiportal/e2e/test/superuser/admin-verify-mapping-of-api-to-ariba-product.js:119:28)
          at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:108:15
          at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1077:7)
          at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2505:12)
          at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
      From: Task: Run it("request production access with created api") in control flow
          at UserContext.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
      From asynchronous test: 
      Error
          at Suite.<anonymous> (/Users/c5253649/Projects/openapi/apiportal/e2e/test/superuser/admin-verify-mapping-of-api-to-ariba-product.js:114:3)
          at Object.<anonymous> (/Users/c5253649/Projects/openapi/apiportal/e2e/test/superuser/admin-verify-mapping-of-api-to-ariba-product.js:27:1)
          at Module._compile (module.js:570:32)
          at Object.Module._extensions..js (module.js:579:10)
          at Module.load (module.js:487:32)
          at tryModuleLoad (module.js:446:12)

**Comment by darrenlau86** [comment]
Anyone can helpl look into this?

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
