### ISSUE TITLE
bug: getText from table does return empty text

### ISSUE THREAD

**Issue by mseele** [SeleniumHQ/selenium#5994]
## Meta -
OS:  Windows 10

Selenium Version:  3.12.0

Browser:  Firefox, Chrome

Browser Version:  Firefox 60.0.1 (64-Bit) / Chrome 67.0.3396.62 (64-Bit)

## Expected Behavior -

Gets all texts from all rows from the first column

## Actual Behavior -

Does not get a text from the column where the scroll bar lies above

## Steps to reproduce -

Run the Snippet provided by

[snippet.zip](https://github.com/SeleniumHQ/selenium/files/2072436/snippet.zip)

and see the result:

```
arrays first differed at element [14]; expected:<[15]> but was:<[]>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:283)
	at org.junit.Assert.assertArrayEquals(Assert.java:298)
	at Snippet.verifyBug(Snippet.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: org.junit.ComparisonFailure: expected:<[15]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 27 more
```

**Comment by lmtierney** [comment]
getText is designed to get visible text. If it is hidden by another element (in this case, the container for the table), then it will return an empty string. You need to scroll the table in order to get the text or use javascript to get `textContent`

**Comment by mseele** [comment]
@lmtierney did you test the snippet? 
All elements completely hidden will return the valid text...then this is a bug.

**Comment by mseele** [comment]
btw, if i read the javadoc, it should work as expected:

java.lang.String getText()
Get the visible (i.e. not hidden by CSS) innerText of this element, including sub-elements, without any leading or trailing whitespace.
Returns:
The innerText of this element.

definitly a bug. or your javadoc is wrong?

**Comment by lmtierney** [comment]
No, I did not test the exact snippet since I don't have the means to (not a Java guy). I only tested that row. You're right, it is only that row that is not working, but it does if you scroll it. If you check the `isDisplayed` on the row itself or any `td` within that row, it will return `False`. The browsers don't think it's displayed. Since the text and displayedness is determined by the browser drivers, you'll have to create an issue with the chromium (chromedriver) and/or Firefox (geckodriver) teams

**Comment by mseele** [comment]
Thanks for your answer, i will open issues there.

**Comment by lmtierney** [comment]
After playing around for a bit, it has to do with the table container. Removing the `overflow: hidden` from a couple of the parent `div`s ended up making it work.

**Comment by mseele** [comment]
hm...i'm using a "normal" gwt data grid (http://samples.gwtproject.org/samples/Showcase/Showcase.html#!CwDataGrid) there. 
Of course stripped down to make the snippet much more simple.

Thanks for taking your time.
