### ISSUE TITLE
Java Selenium 3.12.0 - okhttp3 does not work properly time to time

### ISSUE THREAD

**Issue by kovalev007** [SeleniumHQ/selenium#6025]
Lang: Java
Selenium Version:  3.12.0
Browser:  Chrome and Firefox

Browser Version:  
latest versions
Chrome 67..... 64bit
Firefox 60.0.2 64 bit

Driver:
chromedriver 2.40 win32
geckodriver-v0.20.1-win64.zip

After update selenium from 3.11.0 to 3.12.0
I started getting errors time to time from following code
webDriver.getWindowHandle();
http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.html#getWindowHandle--

Can this problem occured with update okhttp from 3.9.1 to 3.10.0 in following commit
https://github.com/SeleniumHQ/selenium/commit/e6a056f6c32c541c30d8bdd062195be221e0cf13
or
https://github.com/SeleniumHQ/selenium/commit/fe48fc4cbf2edd0d4ea2eaee03061ac9ce95c304

Example code:
[code.txt](https://github.com/SeleniumHQ/selenium/files/2105121/code.txt)

Stacktrace:
at com.onevizion.guitest.AbstractSelenium.openBrowserAndLogin(AbstractSelenium.java:855)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
at org.testng.TestRunner.privateRun(TestRunner.java:771)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
at org.testng.SuiteRunner.run(SuiteRunner.java:259)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
at org.testng.TestNG.run(TestNG.java:1032)
at com.onevizion.guitest.TestNgRunOne.main(TestNgRunOne.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
at java.lang.Thread.run(Thread.java:745)
Caused by: 
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:564)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:463)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.remote.Augmenter$CompoundHandler.invoke(Augmenter.java:194)
at org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$8V9VhAFo.getWindowHandle(Unknown Source)
at com.onevizion.guitest.AbstractSelenium.openBrowserAndLogin(AbstractSelenium.java:845)
... 28 more
Caused by: java.io.IOException: unexpected end of stream on Connection{127.0.0.1:5555, proxy=DIRECT hostAddress=/127.0.0.1:5555 cipherSuite=none protocol=http/1.1}
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
... 37 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
... 55 more

**Comment by barancev** [comment]
Do you use local or remote driver? If it's remote -- do you use a standalone server? a grid? a dockerized environment?

**Comment by kovalev007** [comment]
remote driver. see java code in previously attachment - code.txt
server = java -jar selenium-server-standalone-3.12.0.jar -role hub .....
node = java -jar selenium-server-standalone-3.12.0.jar -role node .....

additional info: error disappeared when I revert node to 3.11.0 and java dependency for java code to 3.11.0

**Comment by barancev** [comment]
Can you reproduce the issue with default http factory provided by Selenium? I see you've created an alternative factory in your sample.

**Comment by AutomatedTester** [comment]
@kovalev007 Does this happen when you have an implicit wait or any long running task that takes more than 5 seconds?

**Comment by AutomatedTester** [comment]
Wondering if this is related to https://github.com/mozilla/geckodriver/issues/1304

**Comment by adamjson** [comment]
This issue is present for us in 3.11 as well.  The fix suggested in this ticket works for us:

https://github.com/zalando/zalenium/issues/593#issuecomment-395306693

Start with -Dwebdriver.http.factory=apache as a VM argument.

**Comment by adamjson** [comment]
I think this ticket should be reopened, also please see my comment on this commit https://github.com/grigaman/selenium/commit/759fa37aabb37072af59b075d48e6728eae8b5f8
