### ISSUE TITLE
can't create remote driver to use with selenium grid 

### ISSUE THREAD

**Issue by gaurav517** [SeleniumHQ/selenium#6027]
OS:
selenium grid: Linux
client where test runs: OSX

Selenium Version:  
selenium grid: 3.12.0
python binding version: 3.12.0

I am not able to create a remote web driver using python. 
```
>>> from selenium import webdriver
>>> driver =  webdriver.Remote(command_executor='http://myhub-url/wd/hub')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 

```
Is there anything I am doing wrong? Please let me know if you need any information.

**Comment by lmtierney** [comment]
You can't create a Remote Webdriver without giving capabilities. How does it know which browser to start?

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by gaurav517** [comment]
I had tried that as well (as per http://selenium-python.readthedocs.io/getting-started.html) but the result was same:

```
Python 2.7.15 (default, Jun  9 2018, 00:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
>>> driver = webdriver.Remote(command_executor='http://myhub-url/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 

>>> 
```
Expected result: Remote driver should be created.
Actual result: WebDriverException is thrown with no message.

I am using python version 2.7.15

**Comment by gaurav517** [comment]
Using IP instead of host name, getting slightly different trace:

```
>>> driver = webdriver.Remote(command_executor='http://xx.xx.xx.xx/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: None

```

**Comment by cgoldberg** [comment]
you are missing the port number on your host/ip.
please send questions to the selenium user group.

**Comment by gaurav517** [comment]
Found the reason. Reason was that host name was being automatically resolved to an IP address that happens to be ip address of loadbalancer as my selenium hub is behind load balancer. As resolve_ip is set to True by default and there is no way to change that while creating remote driver, it was resolving to wrong IP and was giving error. 

More in this forum comments:

https://groups.google.com/forum/#!topic/selenium-users/4UzL46FaLPk


Solution for me is:

1. Find a version of python binding that is compatible with my old grid.

OR

2. Use new version of python binding with new grid: Override webdriver class and set resolve_ip to False while creating RemoteConnection object.

This also calls for an enhancement ticket to be able to set resolve_ip flag while creating Remote webdriver.

**Comment by gaurav517** [comment]
So after version `3.3.2`, the request format is not compatible with an old grid (not sure about grid version though) I was using.

So for now I will use python binding version 3.3.2 with old grid. Will create an enhancement ticket to have the ability to set `resolve_ip` while creating remote driver. or make it false by default as then it would be up to user to use ip address or host name.

Is this the right place to create enhancement ticket?
