### ISSUE TITLE
org.openqa.selenium.WebDriverException: Unable to parse remote response with chrome headless

### ISSUE THREAD

**Issue by Xinshiyou** [SeleniumHQ/selenium#6028]
## Meta -
OS:  
Centos6.9 Final

Selenium Version:  
3.12.0

Browser:  
Google Chrome

Browser Version:  
Google Chrome 67.0.3396.87 

Errors:
`Exception in thread "Timer-0" org.openqa.selenium.WebDriverException: Unable to parse remote response: 
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'host.localdomain', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-696.30.1.el6.x86_64', java.version: '1.8.0_171'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:111)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at com.saic.simclick.Main.getDocumentJS(Main.java:152)
	at com.saic.simclick.Main$TimerTaskCls.parserPages(Main.java:68)
	at com.saic.simclick.Main$TimerTaskCls.run(Main.java:50)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
`

**Comment by grittima** [comment]
Good

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
