### ISSUE TITLE
Selenium does not run via cron -> unknown error

### ISSUE THREAD

**Issue by Centurion80** [SeleniumHQ/selenium#6036]
## Meta -
OS:  
Ubuntu 18.04 LTS
Selenium Version:  
3.11.0
Browser:  
Chrome

I am not sure if this is an issue with selenium or cromedriver. A somewhat similar reported issue was closed by the thread starter without further comments. The issue only arises when running the script as a cronjob, and not when running the script from the IDE or terminal.

-->

Browser Version:  
67.0.3396.87 (Official Build) (64-bit)

## Expected Behavior -
Expected the script to start a new Chrome session, open a web-page and start parsing it.

## Actual Behavior -
The script produces the following error:

`Traceback (most recent call last):
  File "/home/dpa/PycharmProjects/ParseRealEscort/Parser.py", line 117, in <module>
    parser = Parse_Realescort(r"http://www.realescort.eu/ads/category/girls/3/oslo")
  File "/home/dpa/PycharmProjects/ParseRealEscort/Parser.py", line 15, in __init__
    self.driver = webdriver.Chrome(self.path)
  File "/home/dpa/anaconda3/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/dpa/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/dpa/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/dpa/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/home/dpa/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.15.0-22-generic x86_64)`

## Steps to reproduce -
I added the following to the sudo crontab:
`PATH=/usr/bin:/bin:/home/dpa/anaconda3/bin/

39 18 * * * python /home/dpa/PycharmProjects/Parser/Parser.py >> /tmp/mycommand.log 2>&1
`

**Comment by barancev** [comment]
This is a chromedriver issue, please report it to https://bugs.chromium.org/p/chromedriver/issues/list
