### ISSUE TITLE
Java 1.7 Remote WebDriver using IE11

### ISSUE THREAD

**Issue by sushmithaguntupalli** [SeleniumHQ/selenium#6079]
OS:
Windows 7
Selenium Version:
2.52.0
Browser:
IE 11

Trying to execute my code via Remote WebDriver + IE 11.
Grid Configuration:

Hub Running in Linux machine: java -jar selenium-server-standalone-2.52.0.jar -role hub

Node Running in Windows Machine: java -Dwebdriver.ie.driver=IEDriverServer.exe -jar selenium-server-standalone-2.52.0.jar -role node -hub http://localhost:4444/grid/register -port 4446 -browser "browserName=internet explorer,version=11,platform=WINDOWS"

Code:
                        DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
			capabilities.setBrowserName("internet explorer");
			capabilities.setPlatform(Platform.WINDOWS);
			driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);

Error Console:
org.openqa.selenium.WebDriverException: session null does not exist (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_79'
Session ID: null
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=ANY, sessionId=a17c0016-0e3a-4818-a959-bafa7c6acf36, capabilities={timeouts={pageLoad=300000, implicit=0, script=30000}, browserVersion=11, platformName=windows, browserName=internet explorer, proxy={}, se:ieOptions={ignoreProtectedModeSettings=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, requireWindowFocus=false, ie.ensureCleanSession=false, initialBrowserUrl=http://localhost:12321/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.fileUploadDialogTimeout=3000, ie.browserCommandLineSwitches=}, unhandledPromptBehavior=dismiss, setWindowRect=true, pageLoadStrategy=normal, acceptInsecureCerts=false}}]
Command duration or timeout: 197 milliseconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'  os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_79'
Session ID: 994ddd11-9d3f-447d-8bd3-e5e1e37f71dd
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{platform=ANY, cssSelectorsEnabled=true, javascriptEnabled=true, sessionId=a17c0016-0e3a-4818-a959-bafa7c6acf36, capabilities={timeouts={pageLoad=300000, implicit=0, script=30000}, browserVersion=11, platformName=windows, browserName=internet explorer, proxy={}, se:ieOptions={elementScrollBehavior=0, ignoreProtectedModeSettings=true, enablePersistentHover=true, ignoreZoomSetting=false, ie.ensureCleanSession=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:12321/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.fileUploadDialogTimeout=3000, ie.browserCommandLineSwitches=}, setWindowRect=true, unhandledPromptBehavior=dismiss, acceptInsecureCerts=false, pageLoadStrategy=normal}, webdriver.remote.sessionid=994ddd11-9d3f-447d-8bd3-e5e1e37f71dd, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
	at com.wvo.automation.core.TestBase.getUrl(TestBase.java:170)
	at com.wvo.automation.core.TestBase.init(TestBase.java:72)
	at com.wvo.salepoint.scripts.NewContract.setUp(NewContract.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.remote.ScreenshotException: Screen shot has been taken
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43' os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_79'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:138)
	... 29 more
Caused by: org.openqa.selenium.WebDriverException: session null does not exist (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_79'
Session ID: null
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=ANY, sessionId=a17c0016-0e3a-4818-a959-bafa7c6acf36, capabilities={timeouts={pageLoad=300000, implicit=0, script=30000}, browserVersion=11, platformName=windows, browserName=internet explorer, proxy={}, se:ieOptions={ignoreProtectedModeSettings=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, requireWindowFocus=false, ie.ensureCleanSession=false, initialBrowserUrl=http://localhost:12321/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.fileUploadDialogTimeout=3000, ie.browserCommandLineSwitches=}, unhandledPromptBehavior=dismiss, setWindowRect=true, pageLoadStrategy=normal, acceptInsecureCerts=false}}]
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43' os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_79'
Driver info: driver.version: EventFiringWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
	at com.sun.proxy.$Proxy1.get(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:163)
	at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:40)
	at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by barancev** [comment]
If you want to use Selenium Server 2.52.0 you'd better stick to the same version of IEDriverServer. We never run cross-version tests and there is no guarrantee that IEDriverServer 3.4 can work with Server 2.52

Or, better, migrate to Java 8 and Server 3.x as soon as possible. Selenium 2.x series is not supported anymore.
