### ISSUE TITLE
Unable to launch Safari Technology preview from Selenium in Java

### ISSUE THREAD

**Issue by zaheerakhter** [SeleniumHQ/selenium#6102]
OS:  High Sierra
Selenium Version:  3.12
Browser:  Safari Technology Preview 59?

SafariOptions options = new SafariOptions();
		 options.setUseTechnologyPreview(true);
		WebDriver driver = new SafariDriver(options);
		driver.get("http://www.google.com");

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not create a session: A browser with name 'safari' version '(null)' could not be found on the system.
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:14.902Z'
System info: host: 'administrators-MacBook-Pro-4.local', ip: 'fe80:0:0:0:1809:1dd4:6ca6:235b%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_171'
Driver info: driver.version: SafariDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:78)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:60)
	at com.qa.test.BrowserTest.main(BrowserTest.java:31)

**Comment by barancev** [comment]
And where is the code?

**Comment by zaheerakhter** [comment]
Removed comment and updated message

**Comment by barancev** [comment]
This error message was returned by safaridriver, it could not find the browser executable. Please check again that your TP environment is not corrupted, and if it does not help report an issue to Apple.

**Comment by gsnedders** [comment]
Safari TP has a different browser name now; see https://github.com/SeleniumHQ/selenium/commit/0efc0be17cd616bb61ab7af4266dbf4b7d5665b9.
