### ISSUE TITLE
The browser appears to have exited before we could connect.

### ISSUE THREAD

**Issue by alirezastack** [SeleniumHQ/selenium#6194]
## Meta:
OS: Debian GNU/Linux 9
Selenium Version:  3.13.0
Browser:  Firefox

## Browser Version:  
60.1.0 (linux 64bit)

## Expected Behavior:
Run Firefox from Selenium

## Actual Behavior:

```
Traceback (most recent call last):
  File "selen.py", line 8, in <module>
    driver = webdriver.Firefox(firefox_binary=binary, capabilities=capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 187, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 73, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 104, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

## Steps to reproduce -
Install latest version of below packages:
Selenium: 3.13.0
Firefox: 60.1.0-esr
geckodriver: 0.21.0
debian: 9

The python code:

```
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('/root/firefox/firefox-bin')
driver = webdriver.Firefox(firefox_binary=binary)

driver.get('http://seleniumhq.org/')

print driver.title

driver.quit()
```

Returns error below:

`selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 255`

And the code below:

```
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

capabilities = webdriver.DesiredCapabilities().FIREFOX
capabilities["marionette"] = False

binary = FirefoxBinary('/root/firefox/firefox-bin')
driver = webdriver.Firefox(firefox_binary=binary, capabilities=capabilities)

driver.get('http://seleniumhq.org/')

print driver.title

driver.quit()
```

Returns error below:

```
Traceback (most recent call last):
  File "selen.py", line 8, in <module>
    driver = webdriver.Firefox(firefox_binary=binary, capabilities=capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 187, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 73, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 104, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```
I even ran this code with `headless` option, it didn't work either and gave the above error.

What is the issue? how should I solve this problem? Is this because of version mismatch between packages?

**Comment by lmtierney** [comment]
Your first code is setting the firefox binary the legacy way. You need to use the correct moz:firefoxOptions to set it with geckodriver. The easiest way to do this would be to use Firefox Options class:

```
from selenium import webdriver
from selenium.webdriver import FirefoxOptions
options = FirefoxOptions()
options.binary = '/root/firefox/firefox-bin'
driver = webdriver.Firefox(options=options)

driver.get('http://seleniumhq.org/')

print driver.title

driver.quit()
```

Your second code is attempting to use Legacy firefox driver `capabilities["marionette"] = False`. This driver is not compatible with Firefox `60.1.0-esr`

**Comment by lmtierney** [comment]
Actually your first code should still work, but I cannot reproduce this. How are you attempting to set headless with the first code?

**Comment by alirezastack** [comment]
By setting `options` as you have mentioned I get the below error:

```
root@automated-testing:~# python selen.py
Traceback (most recent call last):
  File "selen.py", line 9, in <module>
    driver = webdriver.Firefox(options=options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 255
```

I set the `headless` with the code below:
```
from selenium.webdriver.firefox.options import Options

options = Options()
options.add_argument("--headless")
options.add_argument("--window-size=1920,1080")

binary = FirefoxBinary('/root/firefox/firefox-bin')
driver = webdriver.Firefox(firefox_binary=binary, options=options)
```

**Comment by lmtierney** [comment]
I've tried your code with the same versions of selenium, Firefox, and geckodriver and cannot reproduce on Ubuntu 18.04. I'll have to ask you to create an issue over with the geckodriver team at https://github.com/mozilla/geckodriver as this would be an issue with geckodriver or Firefox.
