### ISSUE TITLE
Selenium-Java-Actions, error

### ISSUE THREAD

**Issue by SudeeptMohan** [SeleniumHQ/selenium#6218]
## Meta -
OS:  
 Windows 10
Selenium Version:  3.12
Mozilla Version : 61.0.1

Browser Version:  

## Expected Behavior -
An error-free selenium run.

## Actual Behavior -

1532862635424	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: rect is undefined","stacktrace":"element.getInViewCentrePoint@chrome://marionette/content/element.js:1162:5\ngetElementCenter@chrome://marionette/content/action.js:1441:14\ndispatchPointerMove/<@chrome://marionette/content/action.js:1327:18\ndispatchPointerMove@chrome://marionette/content/action.js:1323:10\ntoEvents/<@chrome://marionette/content/action.js:1110:16\naction.dispatchTickActions@chrome://marionette/content/action.js:1020:23\naction.dispatch/chainEvents<@chrome://marionette/content/action.js:989:13\naction.dispatch@chrome://marionette/content/action.js:987:22\nperformActions@chrome://marionette/content/listener.js:786:9\ndispatch/</req<@chrome://marionette/content/listener.js:491:14\ndispatch/<@chrome://marionette/content/listener.js:484:15\n"}}
Exception in thread "main" org.openqa.selenium.WebDriverException: TypeError: rect is undefined
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:03.216Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 61.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 500, moz:profile: C:\Users\admin\AppData\Loca..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: d2b3ad2d-d608-43f4-8809-28877ea543a9
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:609)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:638)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:594)
	at PhpTravelsPackage.phpTravels.main(phpTravels.java:30)

## Steps to reproduce -
package PhpTravelsPackage;

//import java.awt.List;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.By.ByClassName;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.WebElement;

public class phpTravels  {
	public static void main (String args[]) {
		
		System.setProperty("webdriver.gecko.driver","C:\\\\Marionette\\geckodriver.exe");
		FirefoxOptions options = new FirefoxOptions();
		options.setLogLevel(FirefoxDriverLogLevel.DEBUG);
		WebDriver driver = new FirefoxDriver(options);
		driver.get ("https://www.phptravels.net/");
		
		WebElement link = null;
		int linksCount = 0 ;
		
		Actions actions = new Actions(driver);
		actions.moveToElement(driver.findElement(By.id("li_myaccount"))).perform();
		
		
		
				
	}

}

**Comment by netzulo** [comment]
hey @SudeeptMohan , ty for this complete example, i can't get your "error" at python lang, ill keep here my complete example to comparasions.

- Im using my own python wrapper for selenium to test your **element action**, ignore another code that's not selenium :)

``` python
from qacode.core.bots.bot_base import BotBase
from qacode.core.webs.controls.control_base import ControlBase
SETTINGS = {
    "bot": {
        "log_output_file": "./",
        "log_name": "selenium-issue6218",
        "log_level": "DEBUG",
        "mode": "remote",
        "browser": "chrome",
        "options": {"headless": False},
        "url_hub": "http://localhost:11000/wd/hub",
        "drivers_path": "../qadrivers",
        "drivers_names": []
    }
}

try:
    bot = BotBase(**SETTINGS)
    chains = bot.curr_driver_actions
    bot.navigation.get_url("https://www.phptravels.net/")
    ctl_config = {"selector": "#li_myaccount", "on_instance_search": True, "on_instance_load": True}
    ctl = ControlBase(bot, **ctl_config)
    # TEST
    import pdb; pdb.set_trace() # TODO, remove DEBUG lane
    chains.move_to_element(ctl.element).perform()
    # END
    print(ctl)
except Exception as err:
    print("ERROR: {}".format(err))
finally:
    bot.close()

```

And execution with PDB

``` python
(qacode) D:\4.developmentWorkSpaces\1.GITHUB\delete_me>python delete_me.py
2018-07-29 14:17:51,924 - selenium-issue6218 - DEBUG - Starting browser with mode : REMOTE ...
2018-07-29 14:17:55,969 - selenium-issue6218 - INFO - Started browser with mode : REMOTE OK
2018-07-29 14:17:58,699 - selenium-issue6218 - DEBUG - control | load_settings_keys: loading keys...
2018-07-29 14:17:58,699 - selenium-issue6218 - DEBUG - control | load_settings_keys: loaded keys
2018-07-29 14:17:58,699 - selenium-issue6218 - DEBUG - control | _load_search: searching element...
2018-07-29 14:17:58,727 - selenium-issue6218 - DEBUG - control | _load_search: element found!
2018-07-29 14:17:58,727 - selenium-issue6218 - DEBUG - control | _load_properties: loading properties...
2018-07-29 14:17:58,727 - selenium-issue6218 - DEBUG - control | get_tag: searching for tag
2018-07-29 14:17:58,741 - selenium-issue6218 - DEBUG - control | get_tag: found same tag='li'
2018-07-29 14:17:58,742 - selenium-issue6218 - DEBUG - control | get_text: obtaining text...
2018-07-29 14:17:58,840 - selenium-issue6218 - DEBUG - control | get_attr_value: obtaining value for attr_name='id'2018-07-29 14:17:58,856 - selenium-issue6218 - DEBUG - control | get_attr_value: obtainedattr_name='id', value='li_myaccount'2018-07-29 14:17:58,857 - selenium-issue6218 - DEBUG - control | get_attr_value: obtaining value for attr_name='class'2018-07-29 14:17:58,873 - selenium-issue6218 - DEBUG - control | get_attr_value: obtainedattr_name='class', value=''
2018-07-29 14:17:58,873 - selenium-issue6218 - DEBUG - control | _load_properties: loaded properties> d:\4.developmentworkspaces\1.github\delete_me\delete_me.py(25)<module>()
-> chains.move_to_element(ctl.element).perform()(Pdb) c
ControlBase: name=UNNAMED, bot.browser=chrome, bot.mode=remote
settings={'selector': '#li_myaccount', 'name': 'UNNAMED', 'locator': 'css selector', 'on_instance_search': True, 'on_instance_load': True, 'auto_reload': True, 'instance': 'ControlBase'}
tag=li, is_displayed=False, is_enabled=True, is_selected=False
2018-07-29 14:18:11,765 - selenium-issue6218 - DEBUG - Closing browser...
2018-07-29 14:18:11,809 - selenium-issue6218 - INFO - Closed browser
```

### so... no errors found for python language with same example.

**Comment by SudeeptMohan** [comment]
WebDriverWait wait = new WebDriverWait(driver,30);WebElement myAccount = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//div[@id='collapse']/descendant::ul[3]/li[@id='li_myaccount']/a")));
myAccount.click();

**Comment by netzulo** [comment]
Just a note for you @SudeeptMohan , personal mind too :)

``CSS_SELECTOR`` > ``XPATH`` 

i say this because im using ``css selector`` by default here : https://github.com/netzulo/qacode/search?q=css+selector&unscoped_q=css+selector

Take a look : https://github.com/netzulo/qacode/blob/129dfec1f6e8d7292aeb1ad24a4417bbf1ce88e9/qacode/core/bots/modules/nav_base.py#L119-L148


### TIP: To use ``CSS_SELECTOR`` with selenium it's equals to use in JS console ``document.querySelectorAll('your css selector')`` , the main point some years ago from JQuery main ``$()`` object to search elements at DOM tree
