### ISSUE TITLE
Unknown error reported from getText() call

### ISSUE THREAD

**Issue by JeffML** [SeleniumHQ/selenium#625]
I'm iterating through all elements on a page (via Geb) and seeing an unknown error cropping up intermittently. Code is as follows:

```groovy
def els = $('body').allElements()
else.each {
    def lines = it.getText().split('\n')
    ...
}
```
org.openqa.selenium.WebDriverException: unknown error: Error: An invalid exception was thrown.
  (Session info: chrome=42.0.2311.90)
  (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.7.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 517 milliseconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'Data-source---LDAPv3-mavserve-edmonds-mavericklabel-com--is-not-valid--s-Computer.local', ip: '192.168.6.124', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, chrome={userDataDir=/var/folders/6z/rs03pjds26b88g0z9b6pvlf000010c/T/.org.chromium.Chromium.lUrKCn}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=42.0.2311.90, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 2846aaf588875e8be3f156a727fc5586
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:152)
	at org.openqa.selenium.WebElement$getText$1.call(Unknown Source)
	at tests.AllPagesTests$_test_for_bad_merges_and_lorem_ipsums_closure5.doCall(AllPagesTests.groovy:93)
	at tests.AllPagesTests.test for bad merges and lorem ipsums(AllPagesTests.groovy:92)
	at tests.ExceptionWrapperRule$1.evaluate(ExceptionWrapperRule.groovy:71)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)

**Comment by lukeis** [comment]
this seems like an error in chromedriver, please check your chromedriver log and submit bugs for chromedriver to their issue tracker:

https://code.google.com/p/chromedriver/issues/list
