### ISSUE TITLE
Gecko and Chrome dont work on Selenium python

### ISSUE THREAD

**Issue by AjaxFB** [SeleniumHQ/selenium#6253]
from selenium import webdriver
browser = webdriver.Chrome()
browser = webdriver.Firefox()
**chrome (https://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip)
>>> browser = webdriver.Chrome()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.9.248304,platform=Linux 4.15.0-29-generic x86_64)

**Gecko(geckodriver-v0.21.0-linux64.tar.gz)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by lmtierney** [comment]
> (Driver info: chromedriver=2.9.248304,platform=Linux 4.15.0-29-generic x86_64)

You're using a _very_ old version of chromedriver, from early 2014. Please update to the latest `2.41`.

As for geckodriver, please provide all the information from the Issue Template including Firefox version. I have no issues using the latest geckodriver and Firefox. I suspect you're using geckodriver with ESR Firefox which are not compatible. Please see the compatibility chart here: https://github.com/mozilla/geckodriver/wiki/Geckodriver-Releases

**Comment by AjaxFB** [comment]
> You're using a very old version of chromedriver, from early 2014. Please update to the latest 2.41.
Error:

>>> browser = webdriver.Chrome()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-29-generic x86_64)

I'm checking the gecko...

**Comment by lmtierney** [comment]
OS? What versions of browsers are installed? Is there a display?

**Comment by AjaxFB** [comment]
> As for geckodriver, please provide all the information from the Issue Template including Firefox version. I have no issues using the latest geckodriver and Firefox. I suspect you're using geckodriver with ESR Firefox which are not compatible. Please see the compatibility chart here: https://github.com/mozilla/geckodriver/wiki/Geckodriver-Releases

firefox 61.0.1 (64-bit)
gecko (v0.21.0)
selenium (3.14.0)

> OS? What versions of browsers are installed? Is there a display?

Chrome Version 68.0.3440.84 (Official Build) (64-bit)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by lmtierney** [comment]
And what kind of display are you using? Are you trying to run this headless?

**Comment by AjaxFB** [comment]
I try run my version on Windows(working 100%) to Linux(Ubuntu), but i cant open a browser on Linux, i test acessing web browser by python line commands. 

Why this commands dont work if i can start isolated gecko and chrome on shell and work?

```
root@usuario-VirtualBox:~# geckodriver 
1533564656090	geckodriver	INFO	geckodriver 0.21.0
1533564656096	geckodriver	INFO	Listening on 127.0.0.1:4444

root@usuario-VirtualBox:~# chromedriver 
Starting ChromeDriver 2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706) on port 9515
Only local connections are allowed.
```

```
from selenium import webdriver
browser = webdriver.Firefox()

from selenium import webdriver
browser = webdriver.Chrome()
```

**Comment by lmtierney** [comment]
Try running the browsers from command line
```
> google-chrome
> firefox
```

**Comment by AjaxFB** [comment]
```
root@usuario-VirtualBox:/tmp# firefox
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/usuario which is owned by usuario.)

usuario@usuario-VirtualBox:~$ sudo -i
root@usuario-VirtualBox:~# firefox
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by usuario.)
```

Work on usuario, chrome and firefox.
`usuario@usuario-VirtualBox:~$ firefox`

But, only firefox give me a problem, need permissions to geckodriver.log
Problem solved.
thanks, arigato gozaimasu!!! 👍 :)
@lmtierney
