### ISSUE TITLE
Exception when trying to get element's property with v3.14.0. Same code works with v3.13.0

### ISSUE THREAD

**Issue by nisb** [SeleniumHQ/selenium#6263]
## Meta -
OS:  macOS 10.13.6

Selenium Version:  3.14.0 (Python bindings)

Browser:  AppiumForMac
Browser Version:  1.1.0

## Expected Behavior -
Output a dictionary with element's width and height. With Selenium 3.13.0, the sample script prints some size:
Main window size:  {'height': 633, 'width': 745}

## Actual Behavior -
Selenium 3.14.0 throws an exception with an empty message. The output:

Traceback (most recent call last):
  File "/Volumes/data/test_env/test_selenium.py", line 21, in <module>
    size = main_wnd.size
  File "/Volumes/data/env_selenium_3.14.0/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 518, in size
    size = self._execute(Command.GET_ELEMENT_SIZE)['value']
  File "/Volumes/data/env_selenium_3.14.0/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/Volumes/data/env_selenium_3.14.0/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/Volumes/data/env_selenium_3.14.0/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 

The same issue happens with Python 2.7.15

## Steps to reproduce -
1. Create a virtual environment (using virtualenv v16.0.0) with this command:
virtualenv -p python3 _path_to_a_folder_
2. Activate the created environment:
source _path_to_a_folder_/bin/activate
3. Install Selenium (version 3.14.0 is the default for now):
pip install selenium
4. Run AppiumForMac. It can be downloaded from here (section Beta 3):
https://github.com/appium/appium-for-mac/releases
5. Make sure that TextEdit.app is not running.
6. Run script test_selenium.py
[test_selenium.py.zip](https://github.com/SeleniumHQ/selenium/files/2273407/test_selenium.py.zip)

**Comment by lmtierney** [comment]
The change to `urllib3` may have introduced some issues when not using `keep_alive`.
Please instantiate your driver with `keep_alive=True` and see if it works.

**Comment by nisb** [comment]
After setting `keep_alive=True`, the sample script works as expected. Thank you.
