### ISSUE TITLE
how to fix/control the issue "org.openqa.selenium.UnhandledAlertException"

### ISSUE THREAD

**Issue by fireson-gor** [SeleniumHQ/selenium#6277]
Hi,

Could you please help for this, it will some times happen such issue when i selenium the website page.

## System

* Version:  0.21.0-win64
* Platform:  Linux 3.10.0-862.3.2.el7.x86_64
* Firefox:  61.0.1
* Selenium:  selenium-server-standalone-3.13.0

## TestcaseException in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
**Caused by: org.openqa.selenium.UnhandledAlertException: :** 
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'hkl2005830******', ip: '130.17******', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.3.2.el7.x86_64', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 61.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 5344, moz:profile: C:\Users\43897129\AppData\L..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 6.3, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, webdriver.remote.sessionid: 9f3e151c-2a5b-4022-a6d7-cd8...} Session ID: 9f3e151c-2a5b-4022-a6d7-cd8c54b6dc7d
*** Element info: {Using=id, value=ctl00_lblDisplay}
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:371)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:417)
    at org.openqa.selenium.By$ById.findElement(By.java:218)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
    at com.selm_hkex$1.apply(selm_hkex.java:128)
    at com.selm_hkex$1.apply(selm_hkex.java:1)
    at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
    at com.selm_hkex.main(selm_hkex.java:126)
    ... 5 more

**Comment by ruby186** [comment]
首先，selenium/webdriver，会告诉你， **这个是一个question，不是一个issue** ，或者懒得和你解释，直接Closed。有耐心点会像你解释，去stackoverflow等看看。  

你这个问题，开源社区帮不了你，原因是：  
1. 缺少可重现的testcase code。
2. 日志被你截的乱七八糟的。
3. 使用了server jar，没有说清client version。  

无聊帮你猜几个原因：  
- 你的page流程，真的有一个window.alert，你没有捕获（这个就是你缺少样例代码带来的困惑）
- 你的switch to alert，写的顺序有问题，对网页执行的时序，代码的执行时序，不匹配，没起效果
- 火狐配置的问题，浏览器配置，或者用webdriver CapabilityType都可以试一试
- linux firefox和驱动的问题；可以换到win上试试（偶尔有遇到，以前2.x较常见，比如StaleElementRefEx）
- 真有BUG：） 那估计也就是错过的人吧……

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
