### ISSUE TITLE
In case of network error between client and hub lot of browsers can be created in nodes (over set limit)

### ISSUE THREAD

**Issue by ilavloki** [SeleniumHQ/selenium#628]
We have next issue:
one hub and one node with configuration to launch only one chrome at time:
  "capabilities":
      [
        {
          "browserName": "chrome",
          "maxInstances": 1,
          "seleniumProtocol": "WebDriver"
        }
      ]
Then we launch several tests in parallel (as result we see one executed tests and multiple in queue)
In case if network error occurs between clients and hub (or in case if client was aborted/killed) - request remains in queue until it find available slot.

Once slot is found: new request for new session is forwarded to this slot and new browser is created.
However when response have to be sent to client - IOException occurs:
12:44:34.419 WARN [17] com.google.common.io.Closeables - IOException thrown while closing Closeable.
org.seleniumhq.jetty7.io.EofException
	at org.seleniumhq.jetty7.http.HttpGenerator.flushBuffer(HttpGenerator.java:939)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection.flushResponse(AbstractHttpConnection.java:612)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection$Output.close(AbstractHttpConnection.java:1001)
	at com.google.common.io.Closeables.close(Closeables.java:79)
	at org.openqa.selenium.io.IOUtils.closeQuietly(IOUtils.java:45)
	at org.openqa.grid.internal.TestSession.writeRawBody(TestSession.java:440)
	at org.openqa.grid.internal.TestSession.forward(TestSession.java:266)
	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:88)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:111)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.seleniumhq.jetty7.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.seleniumhq.jetty7.servlet.ServletHandler.doHandle(ServletHandler.java:479)
	at org.seleniumhq.jetty7.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.seleniumhq.jetty7.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.seleniumhq.jetty7.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.seleniumhq.jetty7.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.seleniumhq.jetty7.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.seleniumhq.jetty7.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.seleniumhq.jetty7.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.seleniumhq.jetty7.server.Server.handle(Server.java:349)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
	at org.seleniumhq.jetty7.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:47)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
	at org.seleniumhq.jetty7.http.HttpParser.parseNext(HttpParser.java:857)
	at org.seleniumhq.jetty7.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.seleniumhq.jetty7.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:66)
	at org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:254)
	at org.seleniumhq.jetty7.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at org.seleniumhq.jetty7.io.ByteArrayBuffer.writeTo(ByteArrayBuffer.java:354)
	at org.seleniumhq.jetty7.io.bio.StreamEndPoint.flush(StreamEndPoint.java:159)
	at org.seleniumhq.jetty7.http.HttpGenerator.flushBuffer(HttpGenerator.java:875)
	... 33 more

And nothing is sent, hub still think that slot is empty (however browser is not closed).
Hub sent next new session request to same slot: so we have 2 browsers launched at same node with max 1.

In our case number of requests in queue can be quite big (let say 100) and it easily lead to fact that some nodes became not functioning - cause we have 30+ browsers launched on same host. 

To fix this issue we suggest to add exception handling in TestSession class in method forward
// START            Added exception handling across writeRawBody
                        try {
                            writeRawBody(response, bytes);
                        } catch(IOException io) {
                            if (request.getRequestType() == RequestType.START_SESSION) {
// DELETE incorrect SESSION
                                sendDeleteSessionRequest();
                            }
                            throw io;
                        }
// END            Added exception handling

**Comment by samhe** [comment]
+1

**Comment by mvorisek** [comment]
writeRawBody is failing with same problem also for other RequestType types. sendDeleteSessionRequest() should be send before every registry terminate triggered by an error, as the terminate method removes only the hub session, but not the session on node.

I just implemented it, after testing it for a week, I will commit the solution.

**Comment by youRooooock** [comment]
+1

**Comment by ncolton** [comment]
This … may explain a great deal of what we're seeing where I work.

**Comment by vbyjsue** [comment]
+1

**Comment by KabanaSoft** [comment]
+1

**Comment by emaks** [comment]
+1

**Comment by varaprasad-pakalapati** [comment]
+1
