### ISSUE TITLE
Screenshot failure with python's http requests (working with java)

### ISSUE THREAD

**Issue by ZircZag** [SeleniumHQ/selenium#6299]
## Meta -
OS:  WINDOWS-7
Selenium Version:  3.12.0
Browser:  All

## Expected Behavior -

Requesting a screenshot of google's homepage with a GET http request.

## Actual Behavior -

504 GATEWAY TIMEOUT (after a 10sec wait)

All other commands look to work.

## Steps to reproduce -
```python
from selenium import webdriver
from selenium.webdriver.remote.remote_connection import RemoteConnection

selenium_grid_url = "http://gravitee-selenium.com/wd/hub"
# Create a desired capabilities object as a starting point.
capabilities = capabilities = {'browserName': 'chrome', 'version': 'latest'}
executor = RemoteConnection(selenium_grid_url, resolve_ip=False)
driver = webdriver.Remote(desired_capabilities=capabilities,
                          command_executor=executor)
driver.get("https://google.fr")
print(driver.save_screenshot("./toto.png"));
#print(driver.current_url)
```
This code is supposed to do a screenshot of Google's homepage through a Gravitee.io gateway.
The same process works when we do it with java or when we use directly the URL "http://gravitee-selenium.com/wd/hub/$SESSION_ID/screenshot" in a browser (either firefox or chrome).
We seriously have no idea of what's happening. If somebody has any clue, it would be really helpful.
Thanks !

**Comment by lmtierney** [comment]
If you're using a proxy via environment variable, you may be running into https://github.com/SeleniumHQ/selenium/issues/6264

**Comment by ZircZag** [comment]
I had the same problem and so I already use the 3.13 version...
I don't think that it is a proxy problem because I can reach the grid with every other http request. The only one that fail is the one that aim to get a screenshot.

**Comment by lmtierney** [comment]
What's the full stack trace?

**Comment by ZircZag** [comment]
You can see below the full stack trace.

```python

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    print(driver.save_screenshot("./shot.png"));
  File "C:\Utilisateurs\A696855\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1043, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "C:\Utilisateurs\A696855\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1020, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Utilisateurs\A696855\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1052, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Utilisateurs\A696855\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1062, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Utilisateurs\A696855\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Utilisateurs\A696855\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message:
```

**Comment by lmtierney** [comment]
Well that doesn't provide much. It could be user permissions. I don't suppose you can turn up the logging level for chromedriver and get logs from it?

**Comment by diemol** [comment]
Closing as we didn't get an answer from the OP.
