### ISSUE TITLE
Failed to use driver.add_cookie: selenium.common.exceptions.InvalidArgumentException: Message: Missing 'name' parameter

### ISSUE THREAD

**Issue by ualvesdias** [SeleniumHQ/selenium#6309]
## Meta -
OS:  Windows 10 and Kali 2018.2
Selenium Version:  
3.14
Browser:  
Firefox 61.0.2 x64 and Chrome

## Expected Behavior -
It was supposed to load the cookies into the request

## Actual Behavior -
```
Traceback (most recent call last):
  File ".\facemembers.py", line 13, in <module>
    browser.add_cookie(cookies_dict)
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 882, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Avell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Missing 'name' parameter
```

Code:
```
from selenium import webdriver
page = 'https://web.facebook.com/groups/XXXXXXXXXXXXXXX/members/'
cookies_dict = {'fr':'33LKFQhckx8mGrMUlE.AWXpnaLnjFGNeVTnjRHuQWhKVNw.BbDdVC.q0.AAA.0.0.BbdxgP.AWWkiPIU', 's':'hd3W7oQewTUO0Fpmr3Si3lo', 'w':'920x793', 'datr':'hd3W_nuEw45z4hYE8u3x_xM', 'c_use':'00020831689959', 'x':'3%3AZ4Yd9BOPffF3vA%3A2%3A1534531599%3A2894%3A5516', 'p':'', 'ac':'534531610492%2F3', 'presenc':'DvF3EtimeF1534531612EuserFA21B20831689959A2EstateFDt3F_5b_5dG534531612574CEchFDp_5f1B20831689959F10CC'}
#cookies_dict = dict(fr='0LKFQhckx8mGrMUlE.AWXpnaLnjFGNeVTnjRHuQWhKVNw.BbDdVC.q0.AAA.0.0.BbdxgP.AWWkiPIU', s='hd3W7oQewTUO0Fpmr3Si3lo', w='920x793', datr='hd3W_nuEw45z4hYE8u3x_xM', c_use='00020831689959', x='3%3AZ4Yd9PO0BOPffF3vA%3A2%3A1534531599%3A2894%3A5516', p='', ac='534531610492%2F3', presenc='DvF3EtimeFdfdgf1534531612EuserFA21B20831689959A2EstateFDt3F_5b_5dG534531612574CEchFDp_5f1B208316899fghghf59F10CC')

browser = webdriver.Firefox()
browser.get(page)
browser.add_cookie(cookies_dict)
```

Note: The cookie values are different than tha actual values for safety porpouses.
Note2: I tried to add the cookies with the two different formats ({'':''} and dict()), but same behavior.

**Comment by lmtierney** [comment]
The cookie dict you're using doesn't have required values such as `name` or `value` please see the w3c spec and the python API documentation:

https://www.w3.org/TR/webdriver/#add-cookie
https://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html?highlight=add_cookie#selenium.webdriver.remote.webdriver.WebDriver.add_cookie

**Comment by ualvesdias** [comment]
Sorry, but the variable cookie_dict in my code is in the correct format, isn't it? 

cookie_dict = {'name1':'value1', 'name2':'value2'}
crowser.add_cookie(cookie_dict)

Isn't this correct?

**Comment by lmtierney** [comment]
No, `name` and `value` are the keys you need to use, and you need to add them one at a time.

In your case,

```
for key, value in cookies_dict.items():
    browser.add_cookie({'name': key, 'value': value})

**Comment by ualvesdias** [comment]
THANK YOU!!!!!
