### ISSUE TITLE
IEDriverServer.exe process does not end after installing Microsoft Update (KB4339093).

### ISSUE THREAD

**Issue by richman555** [SeleniumHQ/selenium#6314]
## Meta -
OS:   Windows 7
Selenium Version:  3.4.0
Browser:  IE 11.0.70 (KB4339093)
IEDriverServer.exe  Version: 2.53.0

## Expected Behavior -

When executing a junit test case using Selenium I expect the driver.quit(); method to kill the IEDriverServer.exe process.

## Actual Behavior -

When executing a junit test case using Selenium the driver.quit(); method does not kill the IEDriverServer.exe process.  Any subsequent execution of the test is impacted as the driver does not quit properly.

Also the following warning is available to stdoutput -

`[THREAD ID=Forwarding quit on session b23d415b-e07c-44fe-bed9-234f1e0f5d3b to remote] 2018-08-21 15:37:41,393 DEBUG  o.a.h.i.c.PoolingHttpClientConnectionManager Connection released: [id: 2][route: {}
->http://localhost:33432][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
[THREAD ID=Forwarding quit on session b23d415b-e07c-44fe-bed9-234f1e0f5d3b to remote] 2018-08-21 15:37:41,395 DEBUG  o.a.h.i.c.PoolingHttpClientConnectionManager Closing connections idle longer than 0
 SECONDS
Aug 21, 2018 3:37:57 PM org.openqa.selenium.os.ProcessUtils killWinProcess
WARNING: Process refused to die after 10 seconds, and couldn't taskkill it
org.openqa.selenium.os.ProcessUtils$ProcessStillAliveException: Timeout waiting for process to die
        at org.openqa.selenium.os.ProcessUtils.waitForProcessDeath(ProcessUtils.java:67)
        at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:129)
        at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
        at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:246)
        at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$200(UnixProcess.java:200)
        at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:126)
        at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
        at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:221)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:94)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
        at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:533)
        at com.uhc.aarp.quality.ui.example.RichsTest.sampleTest(RichsTest.java:14)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.InterruptedException
        at java.lang.ProcessImpl.waitFor(ProcessImpl.java:451)
        at org.openqa.selenium.os.ProcessUtils$ProcessWaiter.run(ProcessUtils.java:154)
        at java.lang.Thread.run(Thread.java:745)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 44.305 sec <<< FAILURE!
sampleTest(com.uhc.aarp.quality.ui.example.RichsTest)  Time elapsed: 44.225 sec  <<< ERROR!
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
`

## Steps to reproduce -
Using the Selenium with the versions mentioned above and using Windows 7.  Also make sure to install the following Microsoft Update (KB4339093).

Create and execute a junit test case using Selenium using the sample code below (issue happens with any code with driver.quit(); ) -

`     @Test
    public void sampleTest(){
        System.setProperty("webdriver.ie.driver", "C:\\dev\\IEDriverServer.exe");
        WebDriver driver=new InternetExplorerDriver();
        driver.navigate().to("www.google.com");
         driver.quit();
    }`

Execute the test case several times.  After just a few executions, you will notice that IEDriverServer.exe process is not killed nor can you manually kill it in task manager.   Also attempting to kill it via the windows taskkill command does not work.

**Comment by jimevans** [comment]
@richman555 And what happens when you use a recent IEDriverServer.exe with a recent (>= 3.5) Selenium?

**Comment by richman555** [comment]
@jimevans we have a recent upgrade project using following versions and have the same issue  -

Fluentlenium 3.6.1
Selenium 3.12.0
IEDriverServer 3.13.0.0

Since we use Fluentlenium in our project 3.6.1 (their latest release) which uses Selenium 3.12 only.

I can try to use a later IEDriverServer.exe with this configuration if its advisable and see if it helps.

This issue seems to have started once our Windows 7 machines took a MS update (KB4339093).  Machines which do not have this Windows update work fine.

Thanks!

**Comment by richman555** [comment]
@jimevans I have tested using the following -

Fluentlenium 3.6.1
Selenium 3.12.0
IEDriverServer 3.14.0.0

And I experience the same issue.  After a few runs of the test Selenium can no longer stop the IEDriverServer.exe process.  The only difference is that my Maven build is successful, though all of the processes are not killed.   I also cannot kill the processes via the Task Manager.

`Aug 22, 2018 1:29:37 PM org.openqa.selenium.os.OsProcess destroy
INFO: Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
        at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
        at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:181)
        at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:135)
        at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
        at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:222)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:95)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
        at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:443)
        at com.uhc.aarp.quality.ui.example.RichsTest.sampleTest(RichsTest.java:22)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Aug 22, 2018 1:29:37 PM org.openqa.selenium.os.OsProcess destroy
SEVERE: Unable to kill process java.lang.ProcessImpl@1191845
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.982 sec
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Oracle"

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:12 min
[INFO] Finished at: 2018-08-22T13:29:37-04:00
[INFO] Final Memory: 40M/144M
[INFO] ------------------------------------------------------------------------`

Tomorrow I can create a new project and attempt to use only the newest Selenium jars.  If you have any thoughts for me to try please let me know.  Thanks!

**Comment by richman555** [comment]
Just an update to this issue as I have had been having separate problems in updating to 3.14 jars.   

I have tried to trying to update to the Selenium 3.14 jars however it seems the following capability  is no longer working -

`capabilities.setCapability("ignoreProtectedModeSettings", true);`

And as a result I receive the following error -

```
Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value
(enabled or disabled) for all zones.(..)
```

I have been trying to get permissions from our network administrators to change it (they have this setting locked down across the company) .   It appears any version starting with 3.13 has this issue or requirement.

Using the 3.12 jar versions the issue still occurs.

Thanks for your help!

**Comment by richman555** [comment]
I also have added IEDriverServer logging and have attached the log when it fails.  The IEDriverServer process does not shut down and I see some references to IECommandExecutor::OnDestroy which are not in the logs when it executes successfully.  Hopefully this is helpful!

[selenium16-59-52-087.zip](https://github.com/SeleniumHQ/selenium/files/2350249/selenium16-59-52-087.zip)

**Comment by tictac-freshmint** [comment]
I think it has nothing to do with the Selenium version. I tried it also with 3.13 and 3.12, same issue. But with these versions it worked a few weeks ago, meaning there were no zombie processes created.
I uninstalled that Microsoft update which is mentioned in this topics title, but it did not help. Maybe Windows does not really uninstall it. It affects also other browsers, see https://github.com/SeleniumHQ/selenium/issues/6317. Maybe someone knows how to debug that Windows OS crap?

**Comment by devin5885** [comment]
> Just an update to this issue as I have had been having separate problems in updating to 3.14 jars.
> 
> I have tried to trying to update to the Selenium 3.14 jars however it seems the following capability is no longer working -
> 
> `capabilities.setCapability("ignoreProtectedModeSettings", true);`
> 
> And as a result I receive the following error -
> 
> ```
> Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value
> (enabled or disabled) for all zones.(..)
> ```
> I have been trying to get permissions from our network administrators to change it (they have this setting locked down across the company) . It appears any version starting with 3.13 has this issue or requirement.
> 
> Using the 3.12 jar versions the issue still occurs.
> 
> Thanks for your help!

For anyone who is having problems setting 'ignoreProtectedModeSettings' (or any other IE setting), you need to do the following:

 `capabilities.setCapability("se:ieOptions", {"ignoreProtectedModeSettings":true});`

because capabilities specified the other way no longer work.

**Comment by omkarnathsingh** [comment]
IE 11 is EOL, this can be closed.

**Comment by omkarnathsingh** [comment]
IE 11 is EOL, this can be closed.

**Comment by diemol** [comment]
Is this still happening after trying with the most recent versions of Selenium?

**Comment by diemol** [comment]
Closing this as we did not get more information, please feel free to open a new issue if the problem still persists after trying with the most recent versions.
