### ISSUE TITLE
Setting Desired Capability using SafariOptions.setUseTechnologyPreview(true) stop working in selenium 3.14 

### ISSUE THREAD

**Issue by aglo65** [SeleniumHQ/selenium#6315]
## Meta -
OS: macOS Sierra 10.12.6
Selenium Version: v3.14 (Java client)
Browser: Safari Technology Preview
Browser Version: Release 43 (Safari 11.1, WebKit 12605.1.12)

## Expected Behavior -
I've been running my tests that required clicking on canvas with the following configuration till the test env got updated to Selenium 3.14
DesiredCapabilities capability = new DesiredCapabilities();

			if (browser.equalsIgnoreCase("safari")) {
				capability.setCapability("browserstack.safari.driver", "2.48");
				capability.setCapability("browserstack.safari.enablePopups", true);
				SafariOptions sOptions = new SafariOptions();
				sOptions.setUseTechnologyPreview(true);
				SafariOptions.fromCapabilities(capability);   <-- new settings (fixed the error but click not working
				//capability.setCapability(SafariOptions.CAPABILITY, sOptions);   <-- deprecated throws the following error(see below under Actual behavior )
## Actual Behavior -
click() function not failing but doesn't perform a click. And I believe this is due to the latest changes related to depreciation of CAPABILITY key (see excerpt below). The configuration I've used to with CAPABILITY is failing with the error noted below.  I've  modified the settings by commented out  `capability.setCapability(SafariOptions.CAPABILITY, sOptions);` and added a new line i.e. `SafariOptions.fromCapabilities(capability); `  it fix the error and launching the browser but not working properly( i.e. setUseTechnologyPreview(true) seems not set. 
Please help me with a new configuration for setting DesiredCapabilities capability = new DesiredCapabilities();

```
>>>>>ERROR<<<<
21 Aug 2018 14:32:58  INFO logger - Staring Suite  -> PXP_SNC_2videos_Test
org.openqa.selenium.WebDriverException: OS/Browser combination invalid: {"os"=>"OS X", "os_version"=>"High Sierra", "project"=>"TremorVideoDSP_AdFormat_Automation", "safari.options"=>{"technologyPreview"=>true}, "browserstack.safari.enablePopups"=>true, "build"=>"7.0.18", "webdriver.remote.sessionid"=>"test1324", "browserVersion"=>"11.1", "name"=>"Safari11_MAC_PXP_SNC_2videos_Test", "browserName"=>"Safari Technology Preview", "browserstack.safari.driver"=>"2.48", "browserstack.debug"=>true, "acceptSslCert"=>false, "language"=>"selenium/3.14.0 (java mac)", "browser"=>"Safari Technology Preview", "browserstack.appiumLogs"=>false, "browser_version"=>"11.1"} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 739 milliseconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'OBUSLOVICH-MBP2.local', ip: 'fe80:0:0:0:423:e05b:1c5c:b64c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'
Driver info: driver.version: RemoteWebDriver
21 Aug 2018 14:32:59  INFO logger - Launching SAFARI 11.1 on OS X
```

```
>>>>>DEPRECATED<<<<
  /**
   * Key used to store SafariOptions in a {@link Capabilities} object.
   * @deprecated No replacement. Use the methods on this class
   */
  @Deprecated
  public static final String CAPABILITY = "safari.options";
```

**Comment by diemol** [comment]
Hi @aglo65,

Could you please provide a way to replicate the issue without using BrowserStack? What I can see from the error you post is this: "org.openqa.selenium.WebDriverException: OS/Browser combination invalid:", which comes from BrowserStack.

So please check if this also happens when you use a well configured setup for Safari Technology Preview without depending on BrowserStack.

**Comment by aglo65** [comment]
Hi @diemol ,
Thanks for your feedback!
Yes. The problem (i.e. click on canvas not working) is still reproducible when running locally. Here is my local env set up:
```

package seleniumTest;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.safari.SafariDriver;
import org.openqa.selenium.safari.SafariOptions;
import org.testng.annotations.Test;

import pagefactory.BaseMethods;
import utility.generic.CoordinateUtils;


public class safariTest extends BaseMethods{

	@Test
	public void launchBrowser() {
		SafariOptions options = new SafariOptions().setUseTechnologyPreview(true);
	    System.out.println(options);
	    WebDriver driver = new SafariDriver(options);
	    String URL = "https://html5.tremorvideodsp.com/v7.0.17/index.html?#/desktop/default/jwplayer/basic?playerOptions%5Bautostart%5D=true&playerOptions%5Baspectratio%5D=16%3A9&playerOptions%5Badvertising%5D%5Bclient%5D=vast&playerOptions%5Badvertising%5D%5Badmessage%5D=Ad%20%E2%80%94%20xxs%20left&playerOptions%5Badvertising%5D%5Bautoplayadsmuted%5D=true&playerOptions%5Badvertising%5D%5Btag%5D=https%3A%2F%2Fs.tremorvideodsp.com%2Fm%2F2017%2F09%2FSkZvFXP9Z%2Fvast3.xml&playerOptions%5Bfile%5D=https%3A%2F%2Fwww.apple.com%2Fmedia%2Fus%2Fwatch%2F2015%2Fa718f271_b19c_47d8_928d_d108fc5d702a%2Ftour%2Fdesign%2Fwatch-design-cc-us-20140909_1280x720h.mp4&playerOptions%5Bid%5D=tesgreenayted3&adTagUri=https%3A%2F%2Fpterodactylus.tremorvideodsp.com%2Fws%2Frml%2Freplacer%3FvastUri%3Dhttps%253A%252F%252Fs.tremorvideodsp.com%252Fm%252F2018%252F08%252FEKJF7GwmH%252Fvast3.xml%26addTVEvents%3Dtrue%26sessionId%3Df87ca66d668ab0761d99f811b0dfddd84c2de635_tc_AFD3712_TimerIncreasesWhenLongformVideoBegins_1533359435209"; 	 
		
 	   //launch the safari browser and open the application url
 	    driver.get(URL);
 	    
 	    //maximize the browser window
      	driver.manage().window().maximize();
      	
      	driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        
      	//switchToCanvas();
		
        CoordinateUtils.clickAtBottomLeftIcon(driver, getCanvas());
		  
	     
     	// close the web browser
         driver.close();

}     	

} 
```
And this is a log capture for the NPE error I'm getting
```

[RemoteTestNG] detected TestNG version 6.14.3
Capabilities {browserName: Safari Technology Preview}
Aug 22, 2018 3:49:05 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
22 Aug 2018 15:49:24  INFO logger - Clicking on Mybug
Aug 22, 2018 3:49:24 PM org.openqa.selenium.interactions.Actions moveToElement
INFO: When using the W3C Action commands, offsets are from the center of element
FAILED: launchBrowser
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.openqa.selenium.interactions.PointerInput$Origin.fromElement(PointerInput.java:222)
	at org.openqa.selenium.interactions.Actions.moveInTicks(Actions.java:417)
	at org.openqa.selenium.interactions.Actions.moveToElement(Actions.java:411)
	at utility.generic.CoordinateUtils.clickAtBottomLeftIcon(CoordinateUtils.java:160)
	at seleniumTest.safariTest.launchBrowser(safariTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

Please take another look and let me know if you see anything that might cause this failure.
Thanks!

**Comment by aglo65** [comment]
Any thoughts/idea, yet?

**Comment by kool79** [comment]
Your original issue is not reproduced in your last example. STP was successfully launched and you have NPE inside clickAtBottomLeftIcon(). 
  @barancev, current issue can be closed.

**Comment by aglo65** [comment]
Thanks for your feedback @kool79 ! 
Yes, you are right, Browserstack has removed the support for the technology preview (STP) for the Safari browsers. I'm working with Browserstack support on the solution for passing Safari.Options via capabilities. So, @barancev  please go ahead and close this ticket.
