### ISSUE TITLE
Cannot override default capabilities using webdriver.Firefox

### ISSUE THREAD

**Issue by ricklupton** [SeleniumHQ/selenium#6337]
## Meta -
OS:  Linux

Selenium Version:  3.14.0

Browser: Firefox

Browser Version: 59.0.2

## Expected Behavior -

The `acceptInsecureCerts` capability can be turned off by passing `capabilities` to `selenium.webdriver.Firefox`.

## Actual Behavior -

`acceptInsecureCerts` is always `True`.

## Steps to reproduce -

This seems like the obvious way to change the desired capability, but it doesn't change the default value -- the request fails:

```python
from selenium import webdriver

caps = webdriver.DesiredCapabilities.FIREFOX.copy()
caps['acceptInsecureCerts'] = False

session = webdriver.Firefox(capabilities=caps)
session.get("https://self-signed.badssl.com/")
print(session.current_url)
```

Result (not what I expect -- it shouldn't accept the certificate):
```shell
$ python ~/tmp/selenium_fails.py 
https://self-signed.badssl.com/
```

By changing the global default capabilities dict, you can change the setting, but I don't think this is what I'm meant to do:
```python
from selenium import webdriver

webdriver.DesiredCapabilities.FIREFOX['acceptInsecureCerts'] = False

session = webdriver.Firefox()
session.get("https://self-signed.badssl.com/")
print(session.current_url)
```

Result (what I wanted):
```shell
$ python ~/tmp/selenium_works.py 
Traceback (most recent call last):
  File "/home/rick/tmp/selenium_works.py", line 6, in <module>
    session.get("https://self-signed.badssl.com/")
  File "/home/rick/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/home/rick/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/rick/anaconda3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InsecureCertificateException: Message: 
```

## Possible diagnosis

Options uses the global DesiredCapabilities dictionary [here](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/options.py#L153).

This then overwrites the user-supplied capabilities argument [here](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/webdriver.py#L159)

**Comment by lmtierney** [comment]
This was broken in our move to allow `Remote` webdrivers to be created via `Options` only. I'll push an update that will allow setting this on the Options class as that is the way we will be preferring Options over Capabilities in the future
