### ISSUE TITLE
Test testScrollingAccountsForScrollbarWidths fails consistently

### ISSUE THREAD

**Issue by clarmso** [SeleniumHQ/selenium#6352]
## Meta
OS:  Mac OSX High Sierra Version 10.13.6

Selenium Version:  Master branch as of August 30, 2018.  No changes have been made locally.

Browser: Chrome

Browser Version: 68.0.3440.106 (Official Build) (64-bit)

## Expected Behavior
All tests pass.

## Actual Behavior
`testScrollingAccountsForScrollbarWidths` fails consistently.  See output below.

## Steps to reproduce
1. Fork SeleniumHQ/Selenium.
2. Ensure Python 2.7.15 is installed. `python` is in the `$PATH` and points to Python 2.7.15.
3. Ensure chromedriver is in the `$PATH`. (I downloaded version 2.41.)
4. Run `git clone https://github.com/<me>/selenium.git`.
5. Run `git remote add upstream git://github.com/seleniumhq/selenium.git`
6. `pip install requests` (For some reason my Python installation does not have `requests`.)
7. Run `git fetch upstream`
8. Run `git rebase upstream/master`
9. Run `./go clean test`
10. 

## Output
```
22:38:27.315  testScrollingAccountsForScrollbarWidths : FAILED
22:38:27.325  ERROR in testScrollingAccountsForScrollbarWidths
Call to fail()
Expected a test failure in 'testScrollingAccountsForScrollbarWidths' but the test passed.
Error: Call to fail()
Expected a test failure in 'testScrollingAccountsForScrollbarWidths' but the test passed.
    at Object.goog.testing.asserts.raiseException (http://localhost:21904/third_party/closure/goog/testing/asserts.js:1283:11)
    at fail (http://localhost:21904/third_party/closure/goog/testing/asserts.js:151:24)
    at goog.testing.ExpectedFailures.run (http://localhost:21904/third_party/closure/goog/testing/expectedfailures.js:214:5)
    at testScrollingAccountsForScrollbarWidths (http://localhost:21904/javascript/atoms/test/scrolling_test.html:230:24)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:899:21)
    at goog.testing.TestCase.safeRunTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:839:8)
    at goog.testing.TestCase.finishTestInvocation_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:999:10)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeTearDown_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:864:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeRunTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:839:8)
    at goog.testing.TestCase.finishTestInvocation_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:999:10)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeTearDown_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:864:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeRunTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:839:8)
    at goog.testing.TestCase.finishTestInvocation_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:999:10)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeTearDown_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:864:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeRunTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:839:8)
    at goog.testing.TestCase.finishTestInvocation_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:999:10)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeTearDown_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:864:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeRunTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:839:8)
    at goog.testing.TestCase.finishTestInvocation_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:999:10)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeTearDown_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:864:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeRunTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:839:8)
    at goog.testing.TestCase.finishTestInvocation_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:999:10)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeTearDown_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:864:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.safeRunTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:849:8)
    at goog.testing.TestCase.invokeTestFunction_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:927:19)
    at goog.testing.TestCase.runNextTest_ (http://localhost:21904/third_party/closure/goog/testing/testcase.js:839:8)
```

```
====DEBUG LOGS====

[2018-08-30 22:38:26.452][info ][tid:11][org.openqa.selenium.javascript.ClosureTestStatement] Running: http://localhost:21904/javascript/atoms/test/scrolling_test.html
[2018-08-30 22:38:26.453][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: maximizeCurrentWindow [cb4244cba250b9cdd769467f6c9c26f0, maximizeCurrentWindow {}]
[2018-08-30 22:38:26.456][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, maximizeCurrentWindow {}]
[2018-08-30 22:38:26.456][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=if (window && window.top) window.top.G_testRunner = null, args=[]}]
[2018-08-30 22:38:26.464][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=if (window && window.top) window.top.G_testRunner = null, args=[]}]
[2018-08-30 22:38:26.464][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: get [cb4244cba250b9cdd769467f6c9c26f0, get {url=http://localhost:21904/javascript/atoms/test/scrolling_test.html}]
[2018-08-30 22:38:26.478][info ][tid:34][org.seleniumhq.jetty9.server.ResourceService] content=ResourceHttpContent@475c01e2{r=file:///Users/clare/Documents/workspace/selenium/javascript/atoms/test/scrolling_test.html,ct=text/html,c=false}
[2018-08-30 22:38:26.702][info ][tid:39][org.seleniumhq.jetty9.server.ResourceService] content=ResourceHttpContent@c05d0e5{r=file:///Users/clare/Documents/workspace/selenium/javascript/atoms/test/testdata/scrolling_iframe.html,ct=text/html,c=false}
[2018-08-30 22:38:26.765][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, get {url=http://localhost:21904/javascript/atoms/test/scrolling_test.html}]
[2018-08-30 22:38:26.765][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:26.775][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:26.878][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:26.886][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:26.986][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:27.001][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:27.103][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:27.113][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:27.213][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:27.226][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:27.329][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:27.446][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isFinished();, args=[]}]
[2018-08-30 22:38:27.446][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isSuccess();, args=[]}]
[2018-08-30 22:38:27.454][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return !!tr && tr.isSuccess();, args=[]}]
[2018-08-30 22:38:27.454][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executing: executeScript [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return tr.getReport(true);, args=[]}]
[2018-08-30 22:38:27.466][info ][tid:11][org.openqa.selenium.remote.RemoteWebDriver] Executed: [cb4244cba250b9cdd769467f6c9c26f0, executeScript {script=var tr = window.top.G_testRunner;return tr.getReport(true);, args=[]}]
```

**Comment by okyrylenko** [comment]
has this been resolved? If no, is there any workaround?

**Comment by titusfortner** [comment]
Looks like the atoms tests have been consistently passing the past month at least. I can reopen if there's an issue I'm missing. Thanks.
