### ISSUE TITLE
Screenshot failure : java.net.SocketTimeoutException: Read timed out.  This is occasional

### ISSUE THREAD

**Issue by yimymo** [SeleniumHQ/selenium#6360]
## Meta -
OS:   Windows 7 

Selenium Version:  3.6

Browser:   Chrome68  chromedriver2.41

## Actual Behavior -
Screenshot failure : java.net.SocketTimeoutException: Read timed out.  This is occasional.

java.net.SocketTimeoutException: Read timed out
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info:  os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver org.openqa.selenium.WebDriverException: java.net.SocketTimeoutException: Read timed out
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info:  os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92) ~[selenium-remote-driver-3.6.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586) ~[selenium-remote-driver-3.6.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:643) ~[selenium-remote-driver-3.6.0.jar:?]

**Comment by barancev** [comment]
3.6 is out of date, please upgrade, the latest version is 3.14
