### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by JackWangAndRose** [SeleniumHQ/selenium#6408]
## Meta -
OS:  windows

Selenium Version:  

  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-java</artifactId>
  <version>3.14.0</version>

Browser Version:  

chrome 68
## Steps to reproduce -

java.net.SocketTimeoutException: Read timed out
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'I-7DE168F1', ip: '172.31.200.29', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver org.openqa.selenium.WebDriverException: java.net.SocketTimeoutException: Read timed out
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'I-7DE168F1', ip: '172.31.200.29', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92) ~[selenium-remote-driver-3.14.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548) ~[selenium-remote-driver-3.14.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:485) ~[selenium-remote-driver-3.14.0.jar:?]
	at com.itesttech.arya.agent.task.RunStep.getNavigationStart(RunStep.java:258) ~[Arya-agent-1.0.1042-SNAPSHOT.jar:?]
	at com.itesttech.arya.agent.task.RunStep.waitPageLoaded(RunStep.java:195) [Arya-agent-1.0.1042-SNAPSHOT.jar:?]
	at com.itesttech.arya.agent.task.RunStep.run(RunStep.java:142) [Arya-agent-1.0.1042-SNAPSHOT.jar:?]
	at com.itesttech.arya.agent.task.RunCase.runListStep(RunCase.java:345) [Arya-agent-1.0.1042-SNAPSHOT.jar:?]
	at com.itesttech.arya.agent.task.RunCase.runCase(RunCase.java:159) [Arya-agent-1.0.1042-SNAPSHOT.jar:?]
	at com.itesttech.arya.agent.task.RunCase.call(RunCase.java:91) [Arya-agent-1.0.1042-SNAPSHOT.jar:?]
	at com.itesttech.arya.agent.task.RunCase.call(RunCase.java:29) [Arya-agent-1.0.1042-SNAPSHOT.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_151]
	at java.net.SocketInputStream.socketRead(Unknown Source) ~[?:1.8.0_151]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_151]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_151]
	at okio.Okio$2.read(Okio.java:140) ~[okio-1.14.1.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.14.1.jar:?]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355) ~[okio-1.14.1.jar:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227) ~[okio-1.14.1.jar:?]
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.10.0.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.10.0.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.10.0.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.10.0.jar:?]
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105) ~[selenium-remote-driver-3.14.0.jar:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155) ~[selenium-remote-driver-3.14.0.jar:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[selenium-remote-driver-3.14.0.jar:?]
	... 11 more

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by JackWangAndRose** [comment]
This problem has been bothering me for a long time, and I don't know if it's because of multithreading, and now it's back.
Now it's stuck here：
	beforeURL = openBrowser.driver.getCurrentUrl();
last is  here:
String command = "return performance.timing.loadEventEnd;";
		JavascriptExecutor js = (JavascriptExecutor) driver;
		if(js == null ){
			return -1;
		}
		Object obj = js.executeScript(command);

**Comment by diemol** [comment]
@JackWangAndRose this issue is the same you reported through #6387, but in none of those you have shared a clear way to reproduce it, step by step, providing code snippets. Without that, we cannot help and we will need to close the issue as there is no way to proceed.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
