### ISSUE TITLE
WebDriver Error on Windows: logging.js not found 

### ISSUE THREAD

**Issue by kibbled** [SeleniumHQ/selenium#642]
Same steps work on OS X but not on Windows, both are running the latest version of Node.js.  Tested this on a a brand new directory even:

mkdir deleteme
cd deleteme
npm install selenium-webdriver
node

(in node)
> require('selenium-webdriver');

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\Users\Administrator\deleteme\webdriver\logging.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.Context.closure.goog.retrieveAndExecModule_ (C:\Users\Administrator\deleteme\node_modules\selenium-webdriver\_base.js:129:23)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (C:\Users\Administrator\delete
me\node_modules\selenium-webdriver\_base.js:101:12)
    at Object.goog.importScript_ (C:\Users\Administrator\deleteme\node_modules\selenium-webdriver\li
b\goog\base.js:873:9)
    at Object.goog.importModule_ (C:\Users\Administrator\deleteme\node_modules\selenium-webdriver\li
b\goog\base.js:894:14)
    at Object.goog.writeScripts_ (C:\Users\Administrator\deleteme\node_modules\selenium-webdriver\li
b\goog\base.js:1251:16)

**Comment by jamesshore** [comment]
:+1:

**Comment by abbey0007** [comment]
:+1: 

Seeing same issue

**Comment by repko-artem** [comment]
Have the same issue on Windows 7. On Ubuntu it's ok.

**Comment by darraghgrace** [comment]
Having the same issue on Windows

**Comment by raultorres88** [comment]
Seeing the same issue as well.

**Comment by jleyba** [comment]
Interesting. I get an entirely different error from `require("selenium-webdriver")` in my Win7 VM.

Will try to figure out what's going on today.

**Comment by doberkofler** [comment]
Same here with selenium-webdriver 2.46.0:

```
D:\MyDev\ljs_app\trunk\periscope\build>node
> require('selenium-webdriver');

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'D:\MyDev\ljs_app\trunk\periscope\build\webdriver\logging.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.Context.closure.goog.retrieveAndExecModule_ (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\selenium-webdriver\_base.js:129:23)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\selenium-webdriver\_base.js:101:12)
    at Object.goog.importScript_ (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\selenium-webdriver\lib\goog\base.js:873:9)
    at Object.goog.importModule_ (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\selenium-webdriver\lib\goog\base.js:894:14)
    at Object.goog.writeScripts_ (D:\MyDev\ljs_app\trunk\periscope\build\node_modules\selenium-webdriver\lib\goog\base.js:1251:16)
```

**Comment by sfhardman** [comment]
Me too.  For what it's worth the following seems to resolve the issue:
Edit _base.js
Add between line 100 and 101: opt_srcText = opt_srcText.replace(/\\/g,'/');

Looks like closure normalizePath_ does not know what to do with Windows seperators

**Comment by jleyba** [comment]
`selenium-webdriver@2.46.1` pushed to npm

**Comment by doberkofler** [comment]
@jleyba Thank you. The issue has been resolved.
