### ISSUE TITLE
Python bindings: BadStatusLineErrors when using selenium grid and keepalive connections

### ISSUE THREAD

**Issue by twiggy** [SeleniumHQ/selenium#6433]
If you start up a remote webdriver pointed at a selenium grid with Hub and nodes with keep_alive = True you can end up with errors on quit. This seems to be only happen on remote grids. If use selenium grid

```
Traceback (most recent call last):
  File "test_it.py", line 23, in <module>
    tmp.quit()
  File "/home/user/selenium_env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 689, in quit
    self.execute(Command.QUIT)
  File "/home/user/selenium_env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/user/selenium_env/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/user/selenium_env/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 490, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

This typically happens when you have a long wait between the last request and the quit. Pretty rare, but it can happen if you are verifying things outside of the test. This code will re-create the issue, provided you have a selenium gird with nodes setup. It doesn't seem to happen with a local standalone server. which makes me think it might be something timing out between the grid and nodes, but the default times i've seen in all those settings seem very high, and not something we have overriden.

```
from selenium import webdriver
from time import sleep

host = "1.2.3.4"
port = "4444"
url = "http://{0}:{1}/wd/hub".format(host, port)

caps = { "browserName": "chrome",
    "version": "",
    "platform": "ANY",
    "javascriptEnabled": True,
    "chrome.switches" : '--headless',
    "chrome.binary" : '/opt/google/chrome/chrome',
    "chromeOptions" : {
        "binary" : '/opt/google/chrome/chrome',
        "args" : ['--headless', '--no-sandbox','--window-size=1600,1200']
        }
}

tmp = webdriver.Remote(command_executor=url, desired_capabilities=caps, keep_alive=True)
tmp.get('https://www.google.com')
sleep(50)
tmp.quit()
```
If you change keep_alive=False this will pass.

**Comment by twiggy** [comment]
```
tmp = webdriver.Remote(command_executor=url, desired_capabilities=caps, keep_alive=True)
tmp.get('https://www.google.com')
sleep(50)
thing = tmp.find_element_by_css_selector('body')
thing.click()
#tmp.quit()
```

after i posted this i wondered if it was only on quit, or something like a click or find.

the above fails as well. so i think it any command. 

i'm going to hook up a debugger and see if i can't get further in there and see what status line i'm getting etc.

**Comment by twiggy** [comment]
chromedriver on my grid node is ChromeDriver 2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881)

**Comment by twiggy** [comment]
okay so after some debugging and reading/refreshing on keep-alive connections I think ultimately the socket is being terminated from the selenium grid. This could be a linux timeout or a whole lot of others thing.

IMHO I don't think we can throw the server under the bus here. A keep alive connection is not a guarantee of connection.

In remote_connection.py there is this snippet.

```
if self.keep_alive:
            if body and method != 'POST' and method != 'PUT':
                body = None
            try:
                self._conn.request(method, parsed_url.path, body, headers)
                resp = self._conn.getresponse()
            except (httplib.HTTPException, socket.error):
                self._conn.close()
                raise

            statuscode = resp.status
```

the code is blowing up on self._conn.getresponse(), but in reality getresponse() is being called on a dead connection.

while in my debugger if I call self._conn.connect() before the .getresponse() call ( when its dead ) it fixes the issue. I don't have time at the moment to figure out how to tell the connection/socket is dead.

something like 
```
if self.keep_alive:
            if body and method != 'POST' and method != 'PUT':
                body = None
            try:
                if self._conn.isdead():
                     self._conn.connect()
                self._conn.request(method, parsed_url.path, body, headers)
                resp = self._conn.getresponse()
            except (httplib.HTTPException, socket.error):
                self._conn.close()
                raise
```

should solve the problem, not sure what self._conn.isdead() should be.

**Comment by twiggy** [comment]
Sigh, the underlying code has been refactored, so not much use to this one. :)

**Comment by twiggy** [comment]
thanks @AutomatedTester for fixing this!
