### ISSUE TITLE
Can not access localhost:4444/grid/register

### ISSUE THREAD

**Issue by BryanN0919** [SeleniumHQ/selenium#6446]
## Meta -
OS:  Windows 10

Selenium Version:  3.14.0

Browser:  N/A

Browser Version:  

## Expected Behavior -
Should be able to access the /grid/register page.
## Actual Behavior -
I get the below error when going to /grid/register.  Same error shows in the cmd window I used to start the hub.

HTTP ERROR 500
Problem accessing /grid/register/. Reason:

    Server Error
Caused by:
org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'CFSQA752319LT1', ip: '165.150.2.177', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:289)
	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:219)
	at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:142)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:123)
	at org.openqa.selenium.json.Json.toType(Json.java:60)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:83)
	at org.openqa.grid.web.servlet.RegistrationServlet.doGet(RegistrationServlet.java:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Unknown Source)

## Steps to reproduce -

Performed: java -jar selenium-server-standalone-3.1.0.jar -role hub   After that completed I tried to access http://165.150.2.136:4444/grid/register/   (Also tried the current version 3.14.0)

**Comment by barancev** [comment]
What do you mean by "trying to access"?

**Comment by praveen4463** [comment]
@BryanN0919 the endpoint you're trying to access is used to register a 'node' with an instance of RegistrationRequest. This endpoint has nothing to return in response of a GET (which is what you're trying).
after a hub is up, all you'd have to do is register a node but thats done by executing a similar command with the role of 'node'.
after the hub is up, you can just view the grid on a browser by visiting '/status'.

**Comment by yahyakara** [comment]
@BryanN0919 did you find the solution ?

**Comment by suveerprithipal** [comment]
Yes, as mentioned above, we dont access that URL directly. 

1)  You should go to http://<hub-url>/grid/console via your browser instead.
2) Your nodes will register against your hub using the http://<hub-url>/grid/register/
3) In your tests, when you register a RemoteWebDriver, you will need to use http://<hub-url>/wd/hub/

Feel free to give me a shout if you would like a more detailed session to get your grid up and running.

**Comment by diemol** [comment]
Thanks @suveerprithipal for a complete answer. 

Closing as this is not really a bug.
