### ISSUE TITLE
Can not start session because of invalid character in USER_AGENT string

### ISSUE THREAD

**Issue by bozdemir84** [SeleniumHQ/selenium#6492]
## Meta -
OS:  Windows 10 (Locale TR)
Selenium Version:  3.14.0
Browser:  N/A
Browser Version:  N/A
Driver info: driver.version: FirefoxDriver
os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'

## Expected Behavior -
Start Firefox window and Open the URL

## Actual Behavior -
Gets exception and Can not start 

Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:05:20.749Z'
System info: host: 'SAMSUNG-PC', ip: '192.168.1.220', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at com.bozdemir.download.bistbulten.Test.main(Test.java:30)
Caused by: java.lang.IllegalArgumentException: Unexpected char 0x131 at 23 in User-Agent value: selenium/3.14.0 (java wındows)
	at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:352)
	at okhttp3.Headers$Builder.add(Headers.java:290)
	at okhttp3.Request$Builder.addHeader(Request.java:196)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:85)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	... 5 more

## Steps to reproduce -
```
    	WebDriver driver = new FirefoxDriver();
	 // And now use this to visit Google
        driver.get("http://www.google.com");
```

on a Turkish windows 10 machine generates exception.

**Comment by bozdemir84** [comment]
When you look at caused by, it is seen that the user agent value "selenium/3.14.0 (java wındows)" contains a Turkish character 'ı' which is the cause of problem. 
The reason underlies in org.openqa.selenium.remote.http.HttpClient.java class. It is generating a user-agent using `toLowerCase` method without a Locale. This maps string 'WINDOWS' to 'windows' in Turkish locale.  When Locale.US is added it works as expected.
 ```
  String USER_AGENT = String.format(
      "selenium/%s (java %s)",
      new BuildInfo().getReleaseLabel(),
      (Platform.getCurrent().family() == null ?
          Platform.getCurrent().toString().toLowerCase(Locale.US) :
          Platform.getCurrent().family().toString().toLowerCase(Locale.US)));
```
I committed the my changes and created a pull request already. #6491

**Comment by barancev** [comment]
Pull-request #6491 had been merged long ago, so the issue must be fixed.
