### ISSUE TITLE
Unable to run Chrome driver in parallel from multiple processes 

### ISSUE THREAD

**Issue by skudriashev** [SeleniumHQ/selenium#6544]
## Meta -
OS:  
```
$ uname -a
Linux 4e9428835181 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 GNU/Linux
```

Selenium Version: 
```
$ pip freeze
selenium==3.14.1
```

Browser: 
```
Google Chrome
```

Browser Version:  
```
$ google-chrome --version
Google Chrome 64.0.3282.119 
```

Chromedriver:
```
$ chromedriver --version
ChromeDriver 2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881)
```

## Expected Behavior -
Be able to run Chrome in parallel (multiprocessing).

## Actual Behavior -
Not able to run Chrome in parallel (multiprocessing).

## Steps to reproduce -
1. Get docker image:
```
$ docker pull joyzoursky/python-chromedriver:3.6-selenium
```

2. Run container:
```
$ docker run -it joyzoursky/python-chromedriver:3.6-selenium bash
```

3. Install ipython:
```
$ pip install ipython
```

4. Run ipython:
```
$ ipython
```

5. Create code snippet:
```
def test():  
    from selenium.webdriver import Chrome  
    from selenium.webdriver import ChromeOptions  
    
    options = ChromeOptions()  
    options.add_argument('--headless')  
    options.add_argument('--disable-extensions')  
    options.add_argument('--disable-gpu')  
    options.add_argument("--no-sandbox")  
    options.add_argument("--window-size=1920,1080")  
    
    browser = Chrome(options=options)  
    browser.get('http://github.com')  
    try:  
        print(browser.title)  
    finally: 
        browser.quit()
```

6. Test run (ok):
```
In [13]: test()                                                                                                                                               
The world’s leading software development platform · GitHub
```

7. Now run in parallel (error):
```
In [5]: import multiprocessing                                                                                                                                
In [6]: for _ in range(3): 
   ...:     multiprocessing.Process(target=test).start()                                                                                                      

In [7]: Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()                                                                                                                                                
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-f6ac560486e0>", line 15, in test
    print(browser.title)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 332, in title
    resp = self.execute(Command.GET_TITLE)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.9.93-linuxkit-aufs x86_64)

Process Process-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-f6ac560486e0>", line 13, in test
    browser.get('http://github.com')
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 323, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.9.93-linuxkit-aufs x86_64)

The world’s leading software development platform · GitHub
```

8. If I comment ` # options.add_argument("--window-size=1920,1080")` option it works again:
```
In [8]: for _ in range(3): 
   ...:     multiprocessing.Process(target=test).start()                                                                                                      

In [9]: The world’s leading software development platform · GitHub
The world’s leading software development platform · GitHub
The world’s leading software development platform · GitHub
```

It looks like changing window size somehow affects further work with driver.

**NOTE:** It is not related to the docker image itself. You can have any other Linux image with installed chrome/chromedriver/selenium.

**Comment by cgoldberg** [comment]
I think the window resizing issue has been fixed in more recent versions of chromedriver.  please try using the latest chrome/chromedriver release.

However, I don't think your code will work anyway.  Launching a second instance of chromedriver on the default port will fail ...  you must specify a unique port for each chromedriver instance. 

To see what I mean, just open 2 terminals and run `chromedriver` in each.  They will both attempt to bind to port 9515, so the second one you run will fail.

**Comment by skudriashev** [comment]
> I think the window resizing issue has been fixed in more recent versions of chromedriver. please try using the latest chrome/chromedriver release.

When I try to use the latest chromedriver I get the following error:
```
# chromedriver 
Starting ChromeDriver 2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d) on port 9515
Only local connections are allowed.
[1539792586.930][SEVERE]: bind() returned an error, errno=0: Cannot assign requested address (99)
```

> However, I don't think your code will work anyway. Launching a second instance of chromedriver on the default port will fail ... you must specify a unique port for each chromedriver instance.

AFAIK selenium take care of that and launches each instance in separate port. And if you look at my examples it actually works :)

**Comment by skudriashev** [comment]
Ok, I managed to make it work by updating chrome and chromedriver to the latest versions:
```
$ google-chrome --version
Google Chrome 70.0.3538.67 
$ chromedriver --version
ChromeDriver 2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d)
```

Python code:
```
def test():   
    from selenium.webdriver import Chrome   
    from selenium.webdriver import ChromeOptions   
   
    options = ChromeOptions()   
    options.add_argument('--headless')   
    options.add_argument('--disable-extensions')   
    options.add_argument('--disable-gpu')   
    options.add_argument("--no-sandbox")   
    options.add_argument("--window-size=1920,1080")   
    options.add_argument('--disable-dev-shm-usage') 

    browser = Chrome(options=options)   
    browser.get('http://github.com')   
    try:   
        print(browser.title)   
    finally:  
        browser.quit()    

for i in range(10): 
    multiprocessing.Process(target=test).start()                                                                                                                             

Google
Google
Google
Google
Google
Google
Google
Google
Google
Google
```

I hope this will help somebody :)
