### ISSUE TITLE
Unable to browser.manage().window().maximize with Chrome under macOS High Sierra

### ISSUE THREAD

**Issue by cwbuege** [SeleniumHQ/selenium#6554]
OS:
macOS High Sierra 10.13.6

Selenium Version:
3.14.0

Browser:
Chrome 70.0.3538.67 (Official Build)

Expected Behavior - 
When test starts, maximize the browser window.

Actual Behavior - 
Chrome never maximizes nor changes size beyond the 'default' window size that the application shows when initially installed.  Even after launching Chrome manually and resizing the window to be larger (which is remembered during subsequent restarts), the Chrome window is still the smaller size at start.

When the test fails, here is the output:
    Failed: unknown error: failed to change window state to maximized, current state is normal
      (Session info: chrome=70.0.3538.67)
      (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.13.6 x86_64)

  Stack:
    WebDriverError: unknown error: failed to change window state to maximized, current state is normal
      (Session info: chrome=70.0.3538.67)
      (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.13.6 x86_64)
        at Object.checkLegacyResponse (/pathToMyCode/node_modules/selenium-webdriver/lib/error.js:546:15)
        at parseHttpResponse (/pathToMyCode/node_modules/selenium-webdriver/lib/http.js:509:13)
        at doSend.then.response (/pathToMyCode/node_modules/selenium-webdriver/lib/http.js:441:30)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    From: Task: WebDriver.manage().window().maximize()
        at thenableWebDriverProxy.schedule (/pathToMyCode/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
        at Window.maximize (/pathToMyCode/node_modules/selenium-webdriver/lib/webdriver.js:1686:25)
        at UserContext.<anonymous> (/pathToMyCode/specs/smoke_test_spec.js:194:35)
        at /pathToMyCode/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/pathToMyCode/node_modules/selenium-webdriver/lib/promise.js:1077:7)
        at ControlFlow.promise (/pathToMyCode/node_modules/selenium-webdriver/lib/promise.js:2505:12)
        at schedulerExecute (/pathToMyCode/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/pathToMyCode/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/pathToMyCode/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/pathToMyCode/node_modules/selenium-webdriver/lib/promise.js:2974:25)
    From: Task: Run beforeAll in control flow
        at UserContext.<anonymous> (/pathToMyCode/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/pathToMyCode/specs/smoke_test_spec.js:193:5)
        at Object.<anonymous> (/pathToMyCode/specs/smoke_test_spec.js:186:1)
        at Module._compile (module.js:573:30)
        at Object.Module._extensions..js (module.js:584:10)
        at Module.load (module.js:507:32)
        at tryModuleLoad (module.js:470:12)

Attempted Workarounds - 
I tried adding '--start-fullscreen' to the chromeOptions/args parameter but when Chrome launches it goes full screen for a second and then resizes itself back to the smaller window.  The only resize that is going on (which isn't occurring) is in the beforeAll function and it is just this:
browser.manage().window().maximize();

I have confirmed that the maximize does work fine on Chrome 70 under CentOS 7 and Windows 10 so the problem does appear to be OS X specific.

Obviously I wonder if this is the type of thing that may be related to 70 having just come out over the last couple of days but not being 100% sure of that fact, I figured I'd go ahead and report it anyway just in case its an indicator of a bigger problem.

**Comment by lmtierney** [comment]
Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
