### ISSUE TITLE
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element:

### ISSUE THREAD

**Issue by upadhyayapooja11** [SeleniumHQ/selenium#656]
Hi ,
I am getting following error :+1:, though i have used explicit wait for 60 seconds. 
org.openqa.selenium.TimeoutException: Timed out after 30 seconds waiting for visibility of element located by By.xpath: //label[text()='Contact Information Source']/../..//img[@title='Add']
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-27 00:00:10'
System info: host: 'SeleniumSF01', ip: '10.80.33.181', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.7.0_25'
Session ID: 86d580cd-1a71-4c59-ab31-5e20232a1253
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=38.0.5}]
                at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:79)
                at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
                at servicecloudpages.ServiceCloudAccountsEdit.clickOnContactInfoAdd(ServiceCloudAccountsEdit.java:245)
                at tests.Aon.Accounts.US702CreateChildAccount.testVerifyParentAccountforCSRAfterSharing(US702CreateChildAccount.java:270)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
                at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
                at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
                at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
                at org.junit.rules.RunRules.evaluate(RunRules.java:20)
                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
                at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
                at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
                at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
                at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
                at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
                at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//label[text()='Contact Information Source']/../..//img[@title='Add']"}
Command duration or timeout: 34 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-27 00:00:10'
System info: host: 'SeleniumSF01', ip: '10.80.33.181', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.7.0_25'
*** Element info: {Using=xpath, value=//label[text()='Contact Information Source']/../..//img[@title='Add']}
Session ID: 86d580cd-1a71-4c59-ab31-5e20232a1253
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=38.0.5}]
                at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
                at java.lang.reflect.Constructor.newInstance(Unknown Source)
                at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
                at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
                at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
                at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
                at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
                at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
                at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:730)
                at org.openqa.selenium.support.ui.ExpectedConditions.access$0(ExpectedConditions.java:728)
                at org.openqa.selenium.support.ui.ExpectedConditions$4.apply(ExpectedConditions.java:130)
                at org.openqa.selenium.support.ui.ExpectedConditions$4.apply(ExpectedConditions.java:1)
                at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
                ... 30 more
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//label[text()='Contact Information Source']/../..//img[@title='Add']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-27 00:00:10'
System info: host: 'SeleniumSF01', ip: '10.80.33.181', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.7.0_25'
Driver info: driver.version: unknown
                at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///C:/Users/AH0104~1/AppData/Local/Temp/2/anonymous7432666803640582619webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10271)
                at <anonymous class>.FirefoxDriver.prototype.findElement(file:///C:/Users/AH0104~1/AppData/Local/Temp/2/anonymous7432666803640582619webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10280)
                at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/AH0104~1/AppData/Local/Temp/2/anonymous7432666803640582619webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12274)
                at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///C:/Users/AH0104~1/AppData/Local/Temp/2/anonymous7432666803640582619webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12279)
                at <anonymous class>.DelayedCommand.prototype.execute/<(file:///C:/Users/AH0104~1/AppData/Local/Temp/2/anonymous7432666803640582619webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12221)

**Comment by ddavison** [comment]
can we see some code in question?  where are you setting the timeout?

**Comment by upadhyayapooja11** [comment]
![image](https://cloud.githubusercontent.com/assets/12858858/8153538/01338bf8-134d-11e5-970b-497f9a2d23ad.png)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by upadhyayapooja11** [comment]
I am getting the unable to locate element error which i have mentioned first while running the above piece of code
