### ISSUE TITLE
Impossible to create Appium Native Driver in selenium-webdriver of version 4.0.0-alpha1 (nodejs)

### ISSUE THREAD

**Issue by astappiev** [SeleniumHQ/selenium#6568]
## Meta -
OS: Windows 10
Selenium Version: 4.0.0-alpha1 (nodejs)
Browser: Appium Native (Andoid 7 Emulator)

## Expected Behavior -
Create an AndroidDriver

## Actual Behavior -
```js
(node:10872) UnhandledPromiseRejectionWarning: TypeError: Target browser must be a string, but is <undefined>; did you forget to call forBrowser()?
    at Builder.build (node_modules\selenium-webdriver\index.js:574:13)
    at AndroidNativeExample.js:23:6
```

## Steps to reproduce -
```js
const capabilities = new Capabilities();
capabilities.set('platformName', 'Android');
capabilities.set('deviceName', 'Android Emulator');
capabilities.set('platformVersion', '7.0');
capabilities.set('app', 'http://saucelabs.com/example_files/ContactManager.apk');
capabilities.set('clearSystemFiles', true);
capabilities.set('noReset', true);

const driver = await new Builder()
    .withCapabilities(capabilities)
    .usingServer('http://127.0.0.1:4723/wd/hub')
    .build();
```

## How to fix -
`build` method of `Builder` class uses next code
```js
if (typeof browser !== 'string') {
      throw TypeError(
          `Target browser must be a string, but is <${typeof browser}>;` +
          ' did you forget to call forBrowser()?');
    }
```
I propose to replace it with
```js
if (typeof browser !== 'string' && !capabilities.get('app')) {
      throw TypeError(
          `Target browser must be a string, but is <${typeof browser}>;` +
          ' did you forget to call forBrowser()?');
    }
```

**Comment by manoj9788** [comment]
Thanks @astappiev 
@jleyba ping!
