### ISSUE TITLE
Error in initialising WebDriver via selenium-firefox-driver

### ISSUE THREAD

**Issue by NiksVij** [SeleniumHQ/selenium#6585]
## Meta -
OS:  
macOs HighSierra
Selenium Version:  
3.4.0,
 IDE, Intellij
Browser:  
Firefox
Language: Java

## Expected Behavior -
Exception-less initialization of web driver
## Actual Behavior -
Receiving exception in initialization. Below is the stack trace , which is giving : Exception in thread "main" org.openqa.selenium.InvalidArgumentException: unknown field `page load`, expected one of `implicit`, `pageLoad`, `script` at line 1 column 12 

`
Oct 26, 2018 9:35:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: unknown field `page load`, expected one of `implicit`, `pageLoad`, `script` at line 1 column 12
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN-R1JBAO1CNPS', ip: '10.100.52.188', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\Administrator\AppData\Local\Temp\rust_mozprofile.sTRSBvwTLBSx, rotatable=false, moz:geckodriverVersion=0.23.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=true, browserVersion=63.0, platformVersion=6.1, moz:processID=1748.0, browserName=firefox, javascriptEnabled=true, platformName=windows, setWindowRect=true, moz:webdriverClick=true}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXb1578513
Command duration or timeout: 562 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.pageLoadTimeout(RemoteWebDriver.java:880)
	at selenium.ScreenshotService.createWebDriver(ScreenshotService.java:63)
	at selenium.ScreenshotService.main(ScreenshotService.java:71)
Caused by: org.openqa.selenium.InvalidArgumentException: unknown field `page load`, expected one of `implicit`, `pageLoad`, `script` at line 1 column 12
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN-R1JBAO1CNPS', ip: '10.100.52.188', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\Administrator\AppData\Local\Temp\rust_mozprofile.sTRSBvwTLBSx, rotatable=false, moz:geckodriverVersion=0.23.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=true, browserVersion=63.0, platformVersion=6.1, moz:processID=1748.0, browserName=firefox, javascriptEnabled=true, platformName=windows, setWindowRect=true, moz:webdriverClick=true}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXb1578513
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'hyd-vijayn-m.ds.ad.adp.com', ip: 'fe80:0:0:0:d:cdb6:676b:4f63%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_144'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.pageLoadTimeout(RemoteWebDriver.java:880)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringTimeouts.pageLoadTimeout(EventFiringWebDriver.java:570)
	at org.openqa.selenium.remote.server.handler.ConfigureTimeout.call(ConfigureTimeout.java:50)
	at org.openqa.selenium.remote.server.handler.ConfigureTimeout.call(ConfigureTimeout.java:27)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`
## Steps to reproduce -
add maven dependency : 
`<dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-firefox-driver</artifactId>
        <version>3.4.0</version>
</dependency>`

use this code snippet in a java class say ScreenshotService.java
`

    private WebDriver createWebDriver(String sauceLabsUsername, String sauceLabsKey, String sauceLabsUrl) throws MalformedURLException {
        String finalUrl = "http://" + sauceLabsUsername + ":" + sauceLabsKey + "@" + sauceLabsUrl;

        URL remoteAddress =  new URL(finalUrl);

        DesiredCapabilities desiredCapabilities = DesiredCapabilities.firefox();
        desiredCapabilities.setCapability("recordVideo", false); // Prevent SauceLabs from creating unnecessary video.
        desiredCapabilities.setCapability("recordScreenshots", false); // Prevent SauceLabs from creating unnecessary screenshots.
        desiredCapabilities.setCapability("screenResolution", "1920x1080");
        WebDriver driver = new RemoteWebDriver(remoteAddress, desiredCapabilities);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.manage().timeouts().pageLoadTimeout(30, TimeUnit.SECONDS);

        return driver;
    }

    public static void main(String... args){
        ScreenshotService screenshotService = new ScreenshotService();
        try {
            screenshotService.createWebDriver(SAUCE_LABS_USERNAME, SAUCE_LABS_KEY, SAUCE_LABS_URL);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
    }

`
You can insert proper values for these variables : SAUCE_LABS_USERNAME, SAUCE_LABS_KEY, SAUCE_LABS_URL
Please let me know if you need anything else and keep me posted

**Comment by barancev** [comment]
Version 3.4.0 is out of date, please upgrade, latest version is 3.14 at the moment.

**Comment by NiksVij** [comment]
tried it with 3.14 too, same result. Please re-open the issue . Thanks

> Version 3.4.0 is out of date, please upgrade, latest version is 3.14 at the moment.

**Comment by NiksVij** [comment]
> Please provide the error log for version 3.14

`Oct 26, 2018 11:07:18 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: unknown field `page load`, expected one of `implicit`, `pageLoad`, `script` at line 1 column 12
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN-R1JBAO1CNPS', ip: '172.20.42.146', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\Administrator\AppData\Local\Temp\rust_mozprofile.iIdyLJyB7QSf, rotatable=false, moz:geckodriverVersion=0.23.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=true, browserVersion=63.0, platformVersion=6.1, moz:processID=1608.0, browserName=firefox, javascriptEnabled=true, platformName=windows, setWindowRect=true, moz:webdriverClick=true}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX66bca022
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.pageLoadTimeout(RemoteWebDriver.java:788)
	at selenium.ScreenshotService.createWebDriver(ScreenshotService.java:63)
	at selenium.ScreenshotService.main(ScreenshotService.java:71)
Caused by: org.openqa.selenium.InvalidArgumentException: unknown field `page load`, expected one of `implicit`, `pageLoad`, `script` at line 1 column 12
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN-R1JBAO1CNPS', ip: '172.20.42.146', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\Administrator\AppData\Local\Temp\rust_mozprofile.iIdyLJyB7QSf, rotatable=false, moz:geckodriverVersion=0.23.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=true, browserVersion=63.0, platformVersion=6.1, moz:processID=1608.0, browserName=firefox, javascriptEnabled=true, platformName=windows, setWindowRect=true, moz:webdriverClick=true}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX66bca022
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'hyd-vijayn-m.ds.ad.adp.com', ip: 'fe80:0:0:0:d:cdb6:676b:4f63%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_144'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.pageLoadTimeout(RemoteWebDriver.java:880)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringTimeouts.pageLoadTimeout(EventFiringWebDriver.java:570)
	at org.openqa.selenium.remote.server.handler.ConfigureTimeout.call(ConfigureTimeout.java:50)
	at org.openqa.selenium.remote.server.handler.ConfigureTimeout.call(ConfigureTimeout.java:27)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

**Comment by barancev** [comment]
This is the log from version 3.4.0 (the log contains version number). Please upgrade both the client ans the server.

**Comment by NiksVij** [comment]
I  have updated the version in pom to 3.14 only ( although its giving 3.40 in logs) , where else do I need to change the version ?

**Comment by barancev** [comment]
Ah, I see, you're using SauceLabs cloud. And they seem to be running Selenium Server v.3.4.0 by default.

Geckodriver is a W3C conformant driver, but the server provides false information: "Detected dialect: OSS". The most probable reason is outdated Selenium Server. Please read the SauceLabs documentation or ask SauceLabs support how to use a server version that is W3C conformant.

**Comment by NiksVij** [comment]
I am not sure that is the problem here . If I comment the line   `//driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);`
It is working completely fine . Even ran the class along with this code plugged in , it captured screenshots and everything else worked fine.
Moreover if you see the Exception it is mentioning: 'unknown field page load, expected one of implicit, pageLoad, script at line 1 column 12'. There is a space between page and load , whereas it seems to expecting it without space like pageLoad . I guess, this is something which should be looked at.

**Comment by barancev** [comment]
According to the W3C specification, the property name should be 'pageLoad', that's what geckodriver expects to get in the payload, because it's a W3C conformant driver.

But the server illegally reports it's OSS conformant (uses legacy protocol), and the client sends legacy 'page load' property name that can't be handled by the driver.
