### ISSUE TITLE
chromedriver 2.43  and  chrome 69 but from disconnected: unable to connect to renderer

### ISSUE THREAD

**Issue by wangxitao2273** [SeleniumHQ/selenium#6589]
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 "/Users/bjhl/PycharmProjects/GUI Test/testcase/testMainCase.py"
/Users/bjhl/PycharmProjects/GUI Test/testcase/testMainCase.py:21: DeprecationWarning: use options instead of chrome_options
  self.driver = webdriver.Chrome(chrome_options=option);
Traceback (most recent call last):
  File "/Users/bjhl/PycharmProjects/GUI Test/testcase/testMainCase.py", line 53, in <module>
    test.setUp();
  File "/Users/bjhl/PycharmProjects/GUI Test/testcase/testMainCase.py", line 21, in setUp
    self.driver = webdriver.Chrome(chrome_options=option);
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=69.0.3497.81)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.13.2 x86_64)

**Comment by wangxitao2273** [comment]
Upgrading to Chrome browser 70 is not acceptable either.

**Comment by cgoldberg** [comment]
please fill out the issue template when filing new issues.
