### ISSUE TITLE
WebDriverException: Message: newSession on Firefox 63.0

### ISSUE THREAD

**Issue by PaziewskiCezary** [SeleniumHQ/selenium#6590]
### OS:  
Ubuntu 16.04.5 LTS

### Selenium Version:  
3.14.1

### Browser:  
Firefox

### Browser Version:  
Mozilla Firefox 63.0

### Browser Add-ons:
uBlock Origin
To Google Translate
Hoxx VPN Proxy
Easy Youtube Video Downloader Express
Facebook Container
HTTPS Everywhere
Greasemonkey
Enhancer for YouTube™
DuckDuckGo Privacy Essentials
Web Developer
1-Click Downloader (Video or Photo)
Violentmonkey
English (GB) Language Pack
WebRTC Leak Shield
User-Agent Switcher and Manager
Search by Image - Reverse Image Search
No Coin
Cookie Editor
Dark Theme for Google™
Bloody Vikings!
Neat URL
Country Flags & IP Whois
Tomato Clock
View Page Archive & Cache
Swift Selection Search
Downloads sidebar
Open in Reader View
Download Notifications
WebRTC Protect
English (South African) Language Pack
Two Factor Authenticator
File Icon for GitHub, GitLab and Bitbucket
English (CA) Language Pack
Breached

### Geckodriver Version:
0.16.1

### Python Version:
Python 3.5.2

## Expected Behavior:

Should work like on older version.

## Actual Behavior:
Browser opens and  error occurs. 

#### Traceback:
```python
Traceback (most recent call last):
  File "selenium_fix.py", line 2, in <module>
    driver = webdriver.Firefox()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: newSession

```

#### geckodriver.log:
```
1540670869060	geckodriver	INFO	Listening on 127.0.0.1:37515
1540670883143	geckodriver::marionette	INFO	Starting browser /usr/lib/firefox/firefox.sh with args ["-marionette"]
1540670885498	Marionette	DEBUG	Received observer notification profile-after-change
1540670885970	Marionette	DEBUG	Received observer notification command-line-startup
1540670885970	Marionette	DEBUG	Received observer notification nsPref:changed
1540670885970	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)

(firefox:24638): Gtk-WARNING **: Theme parsing error: <data>:1:34: Expected ')' in color definition

(firefox:24638): Gtk-WARNING **: Theme parsing error: <data>:1:77: Expected ')' in color definition
1540670886872	Marionette	DEBUG	Received observer notification toplevel-window-ready
1540670893145	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1540670893146	Marionette	DEBUG	Waiting for delayed startup...
1540670893362	Marionette	DEBUG	Setting recommended pref app.normandy.api_url to 
1540670893362	Marionette	DEBUG	Setting recommended pref app.update.disabledForTesting to true
1540670893363	Marionette	DEBUG	Setting recommended pref security.turn_off_all_security_so_that_viruses_can_take_over_this_computer to true
1540670893364	Marionette	DEBUG	Setting recommended pref browser.safebrowsing.passwords.enabled to false
1540670893365	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1540670893366	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1540670893369	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1540670893369	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1540670893369	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1540670893436	Marionette	INFO	Listening on port 43927
1540670893436	Marionette	DEBUG	Remote service is active
1540670893453	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:53854
1540670893516	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1540670893518	Marionette	TRACE	0 <- [1,1,{"error":"unknown command","message":"newSession","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178: ... et@chrome://marionette/content/server.js:245:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"},null]
```

## Steps to reproduce:

```python
from selenium import webdriver
driver = webdriver.Firefox()
driver.get('https://github.com/')
```

**Comment by lmtierney** [comment]
Upgrade to the latest versions of geckodriver/selenium. See https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html?highlight=geckodriver for more info

**Comment by neurascenic** [comment]
selenium.common.exceptions.WebDriverException: Message: newSession
Seems to have reared it's head again.
FF: 67.0.4 (64-bit) OSX 10.14.5
geckodriver-v0.24.0-macos.tar.gz
selenium 3.141.0

Same steps to produce as above.  Chrome and Safari work.
Will try Canary
Thanks!

**Comment by neurascenic** [comment]
Behaves the same with current Beta.

Thanks!
