### ISSUE TITLE
FirefoxProfile not found

### ISSUE THREAD

**Issue by liangrengongzuoshi** [SeleniumHQ/selenium#6603]
## Thanks -
OS:  hub,node=Win7

Selenium Version:  3.8.1

Browser:  Firefox

Browser Version:  59

Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session resource /org/openqa/selenium/firefox/webdriver_prefs.json relative to org.openqa.selenium.firefox.FirefoxProfile not found.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'dx-crawler36.dx', ip: '10.11.0.224', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-358.el6.x86_64', java.version: '1.8.0_73'
Driver info: driver.version: unknown

org.openqa.selenium.WebDriverException: Error forwarding the new session resource /org/openqa/selenium/firefox/webdriver_prefs.json relative to org.openqa.selenium.firefox.FirefoxProfile not found.
Command duration or timeout: 15 milliseconds
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$0(JsonWireProtocolResponse.java:53)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$2(JsonWireProtocolResponse.java:91)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$0(ProtocolHandshake.java:123)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
        at com.rong360.crawler.mobile.webdriver.CrawlerRemoteWebDriver.<init>(CrawlerRemoteWebDriver.java:13)
        at com.rong360.crawler.mobile.webdriver.DriverBuilder.createNewFirefoxDriver(DriverBuilder.java:85)
        at com.rong360.crawler.mobile.service.impl.chinamobile.AnhuiMobileLoginServiceImpl.login(AnhuiMobileLoginServiceImpl.java:56)
        at com.rong360.crawler.mobile.service.impl.chinamobile.AnhuiMobileLoginServiceImpl$$FastClassBySpringCGLIB$$10b0a5e1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
        at com.rong360.crawler.mobile.annotation.LoginRequestInterceptor.around(LoginRequestInterceptor.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by barancev** [comment]
Why do you have no version information in the log?
`Build info: version: 'unknown', revision: 'unknown', time: 'unknown'`
Do you use a custom build of Selenium?

**Comment by barancev** [comment]
Closing the issue as there is no information provided that would allow to reproduce it.
