### ISSUE TITLE
ActionChains.move_to does not work with EventFiringWebElement

### ISSUE THREAD

**Issue by gklinich** [SeleniumHQ/selenium#6604]
## Meta -
Bindings: Python
OS:  Linux
Selenium Version:  3.14
Browser:  Firefox, but should be any w3c enabled browser
Browser Version:  63.0  (geckodriver 0.23)

## Expected Behavior -
ActionChains.move_to should work with EventFiringWebElements just as WebElement do, since EFWEs are just wrappers around WEs

## Actual Behavior -
Exception thrown

## Steps to reproduce -
Using a browser that is w3c capable 

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from selenium.webdriver import Firefox
from selenium.webdriver.support.events import AbstractEventListener, EventFiringWebDriver
from selenium.webdriver import ActionChains

class MyListener(AbstractEventListener):
    def before_navigate_to(self, url, driver):
        print("Before navigate to %s" % url)
    def after_navigate_to(self, url, driver):
        print("After navigate to %s" % url)

driver = Firefox()
ef_driver = EventFiringWebDriver(driver, MyListener())
ef_driver.get("http://www.google.com")
ef_elem = ef_driver.find_element_by_name("btnK")
ActionChains(driver).move_to_element(ef_elem).perform()

```
Output:
```
Before navigate to http://www.google.com
After navigate to http://www.google.com
Traceback (most recent call last):
  File "efwe_example.py", line 22, in <module>
    ActionChains(driver).move_to_element(ef_elem).perform()
  File "/home/gk3/.local/share/virtualenvs/selenium-Ey5F69Tg/lib/python2.7/site-packages/selenium/webdriver/common/action_chains.py", line 273, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
  File "/home/gk3/.local/share/virtualenvs/selenium-Ey5F69Tg/lib/python2.7/site-packages/selenium/webdriver/common/actions/pointer_actions.py", line 42, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement


```

**Comment by Herst** [comment]
Maybe have the `EventFiringWebElement` override `__instancecheck__` to pretend to be a `WebElement` as a simple fix/workaround?

**Comment by Herst** [comment]
Although this seems to be the only place where this check so maybe just add `EventFiringWebElement` to it. But on another note, what is `EventFiringWebDriver` when it does fire events for `ActionChains` stuff?
