### ISSUE TITLE
AbstractMethodError: HtmlUnitWebElement.getCoordinates()

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#6612]
## Meta -
OS:  MacOS
Selenium Version:  3.141.0
Browser: HtmlUnit
Browser Version: 2.33
HtmlUnitDriver Version: 2.33.0

## Steps to reproduce -

```java
HtmlUnitDriver driver = new HtmlUnitDriver(...);
WebElement element = driver.findElement(...);
new Actions(driver).doubleClick(element).perform();
```

## Result:
I am getting technical error:

```java
java.lang.AbstractMethodError: org.openqa.selenium.htmlunit.HtmlUnitWebElement.getCoordinates()Lorg/openqa/selenium/interactions/Coordinates;
	at org.openqa.selenium.interactions.internal.MouseAction.getActionLocation(MouseAction.java:69)
	at org.openqa.selenium.interactions.internal.MouseAction.moveToLocation(MouseAction.java:76)
	at org.openqa.selenium.interactions.DoubleClickAction.perform(DoubleClickAction.java:42)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:34)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:642)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:595)
```

**Comment by cgoldberg** [comment]
What's the expected result?
Your repro steps attempt to find elements and create Actions, but you never navigated to a page.

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/htmlunit-driver #74](https://github.com/SeleniumHQ/htmlunit-driver/issues/74) via [**ZenHub**](https://www.zenhub.com/)

**Comment by asolntsev** [comment]
Upgrade to htmlunitdriver 2.33.1 solved the issue.
