### ISSUE TITLE
Segfault on Jenkins using Chrome

### ISSUE THREAD

**Issue by Ardena** [SeleniumHQ/selenium#6638]
Kinda looks like it's not even getting to the Chrome driver in the stack trace, so I figured I'd at least ask.  This doesn't occur too often, but catching it and dealing with it is difficult.

## Meta -
OS: 
Jenkins ver. 1.651
Selenium Version:  
selenium-webdriver-3.14.0
Browser:  
Chrome

Browser Version:  
Latest, I think.

## Expected Behavior -
selenium-webdriver should start

## Actual Behavior -
Segfault

## Steps to reproduce -
Unsure

## Stack info -
[2018-10-26 21:48:15][test_selenium] Setting up DISPLAY=:23
[2018-10-26 21:48:15][test_selenium] using CHROME driver
[2018-10-26 21:48:15][test_selenium] Thread: provisioning local chrome driver
[2018-10-26 21:48:15][test_selenium] -- Control frame information -----------------------------------------------
[2018-10-26 21:48:15][test_selenium] c:0024 p:---- s:0127 e:000126 CFUNC  :require
[2018-10-26 21:48:15][test_selenium] c:0023 p:0012 s:0122 e:000121 BLOCK  /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependenci
[2018-10-26 21:48:15][test_selenium] c:0022 p:0057 s:0119 e:000118 METHOD /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependenci
[2018-10-26 21:48:15][test_selenium] c:0021 p:0017 s:0113 e:000112 METHOD /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependenci
[2018-10-26 21:48:15][test_selenium] c:0020 p:0026 s:0107 e:000106 TOP    /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/ [FINISH]
[2018-10-26 21:48:15][test_selenium] c:0019 p:---- s:0104 e:000103 CFUNC  :require
[2018-10-26 21:48:15][test_selenium] c:0018 p:0012 s:0099 e:000098 BLOCK  /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependenci
[2018-10-26 21:48:15][test_selenium] c:0017 p:0057 s:0096 e:000095 METHOD /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependenci
[2018-10-26 21:48:15][test_selenium] c:0016 p:0017 s:0090 e:000089 METHOD /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependenci [FINISH]
[2018-10-26 21:48:15][test_selenium] c:0015 p:0009 s:0084 e:000083 BLOCK  /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/ [FINISH]
[2018-10-26 21:48:15][test_selenium] c:0014 p:---- s:0081 e:000080 CFUNC  :delete
[2018-10-26 21:48:15][test_selenium] c:0013 p:0012 s:0076 e:000075 METHOD /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/
[2018-10-26 21:48:15][test_selenium] c:0012 p:0018 s:0065 e:000062 METHOD /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/ [FINISH]
[2018-10-26 21:48:15][test_selenium] c:0011 p:---- s:0054 e:000053 CFUNC  :new
[2018-10-26 21:48:15][test_selenium] c:0010 p:0120 s:0049 e:000048 METHOD /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/
[2018-10-26 21:48:15][test_selenium] c:0009 p:0020 s:0043 e:000042 METHOD /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver.
[2018-10-26 21:48:15][test_selenium] c:0008 p:0100 s:0038 e:000037 METHOD /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:334
[2018-10-26 21:48:15][test_selenium] c:0007 p:0029 s:0033 e:000032 METHOD /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:305
[2018-10-26 21:48:15][test_selenium] c:0006 p:0074 s:0029 e:000028 BLOCK  /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:194
[2018-10-26 21:48:15][test_selenium] c:0005 p:0033 s:0026 e:000025 METHOD /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:310
[2018-10-26 21:48:15][test_selenium] c:0004 p:0013 s:0015 e:000014 METHOD /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:189
[2018-10-26 21:48:15][test_selenium] c:0003 p:0082 s:0011 e:000010 METHOD /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:150
[2018-10-26 21:48:15][test_selenium] c:0002 p:0008 s:0006 e:000005 BLOCK  /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:103 [FINISH]
[2018-10-26 21:48:15][test_selenium] c:0001 p:---- s:0003 e:000002 (none) [FINISH]
[2018-10-26 21:48:15][test_selenium] 
[2018-10-26 21:48:15][test_selenium] -- Ruby level backtrace information ----------------------------------------
[2018-10-26 21:48:15][test_selenium] /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:103:in `block in run'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:150:in `start_driver'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:189:in `create_driver'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:310:in `with_retries'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:194:in `block in create_driver'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:305:in `chrome_driver'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas/spec/selenium/test_setup/selenium_driver_setup.rb:334:in `ruby_chrome_driver'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver.rb:86:in `for'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/chrome/driver.rb:35:in `initialize'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/chrome/driver.rb:67:in `create_capabilities'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/chrome/driver.rb:67:in `delete'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/chrome/driver.rb:67:in `block in create_capabilities'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote.rb:21:in `<top (required)>'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
[2018-10-26 21:48:15][test_selenium] 
[2018-10-26 21:48:15][test_selenium] -- Machine register context ------------------------------------------------
[2018-10-26 21:48:15][test_selenium]  RIP: 0x00007f7cd59a382d RBP: 0x0000000015b5c198 RSP: 0x00007f7cc3080c40
[2018-10-26 21:48:15][test_selenium]  RAX: 0x00000000fffffffd RBX: 0x0000000000008211 RCX: 0x0000000000000053
[2018-10-26 21:48:15][test_selenium]  RDX: 0x0000000000000000 RDI: 0x0000000002959772 RSI: 0x00007f7cd5aeb34b
[2018-10-26 21:48:15][test_selenium]   R8: 0x0000000000000000  R9: 0x0000000000000000 R10: 0x00007f7cd59f1cc0
[2018-10-26 21:48:15][test_selenium]  R11: 0x0000000000000009 R12: 0x0000000000004552 R13: 0x0000000000000009
[2018-10-26 21:48:15][test_selenium]  R14: 0x000000000000000b R15: 0x00007f7cd5aeb34b EFL: 0x0000000000010206
[2018-10-26 21:48:15][test_selenium] 
[2018-10-26 21:48:15][test_selenium] -- C level backtrace information -------------------------------------------
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_vm_bugreport+0x528) [0x7f7cd5f52748] vm_dump.c:684
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_bug_context+0xd0) [0x7f7cd5dd6420] error.c:506
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(sigsegv+0x3e) [0x7f7cd5ec617e] signal.c:907
[2018-10-26 21:48:15][test_selenium] /lib/x86_64-linux-gnu/libc.so.6 [0x7f7cd599ecb0]
[2018-10-26 21:48:15][test_selenium] /lib/x86_64-linux-gnu/libc.so.6(getenv+0xad) [0x7f7cd59a382d]
[2018-10-26 21:48:15][test_selenium] /lib/x86_64-linux-gnu/libc.so.6 [0x7f7cd5a869d6]
[2018-10-26 21:48:15][test_selenium] /lib/x86_64-linux-gnu/libc.so.6(__res_maybe_init+0x125) [0x7f7cd5a88065]
[2018-10-26 21:48:15][test_selenium] /lib/x86_64-linux-gnu/libc.so.6 [0x7f7cd5a37ef4]
[2018-10-26 21:48:15][test_selenium] /lib/x86_64-linux-gnu/libc.so.6(getaddrinfo+0xfd) [0x7f7cd5a3b96d]
[2018-10-26 21:48:15][test_selenium] /usr/lib/x86_64-linux-gnu/libpq.so.5 [0x7f7cc813a433]
[2018-10-26 21:48:15][test_selenium] /usr/lib/x86_64-linux-gnu/libpq.so.5(PQconnectStart+0x44) [0x7f7cc813d124]
[2018-10-26 21:48:15][test_selenium] /usr/lib/x86_64-linux-gnu/libpq.so.5(PQconnectdb+0xe) [0x7f7cc813d14e]
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/pg-1.0.0/lib/pg_ext.so(gvl_PQconnectdb_skeleton+0xc) [0x7f7cc837b9cc] gvl_wrappers.c:13
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_thread_call_without_gvl+0x42) [0x7f7cd5f03f92] thread.c:1319
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/pg-1.0.0/lib/pg_ext.so(gvl_PQconnectdb+0x29) [0x7f7cc837be29] gvl_wrappers.c:14
[2018-10-26 21:48:15][test_selenium] /mnt/canvas_cache/dependencies/ruby-2.4.1-rails51-full-bundle/ruby/2.4.0/gems/pg-1.0.0/lib/pg_ext.so(pgconn_init+0x57) [0x7f7cc8384757] pg_connection.c:272
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call0_body.constprop.139+0x1ca) [0x7f7cd5f4744a] vm_eval.c:132
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_call0+0x1b8) [0x7f7cd5f48238] vm_eval.c:62
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_class_new_instance+0x21) [0x7f7cd5e48a71] object.c:1896
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_cfunc+0xf1) [0x7f7cd5f34f41] vm_insnhelper.c:1752
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2179) [0x7f7cd5f3efe9] insns.def:1066
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_iseq_block_from_c+0x3a9) [0x7f7cd5f43f09] vm.c:969
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_yield_values+0x233) [0x7f7cd5f44fb3] vm.c:1032
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_yield_with_cfunc.isra.114.constprop.155+0x9b) [0x7f7cd5f38e1b] vm_insnhelper.c:2460
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_yield+0x385) [0x7f7cd5f4b165] vm.c:1037
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_ary_each+0x3d) [0x7f7cd5d6299d] array.c:1824
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call0_body.constprop.139+0x1ca) [0x7f7cd5f4744a] vm_eval.c:132
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_call0+0x1b8) [0x7f7cd5f48238] vm_eval.c:62
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_iterate0+0xd3) [0x7f7cd5f35373] vm_eval.c:1173
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_block_call+0x2b) [0x7f7cd5f368bb] vm_eval.c:1236
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(enum_each_with_index+0x44) [0x7f7cd5dc91d4] enum.c:2215
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_cfunc+0xf1) [0x7f7cd5f34f41] vm_insnhelper.c:1752
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2e00) [0x7f7cd5f3fc70] insns.def:967
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_call0+0x1b8) [0x7f7cd5f48238] vm_eval.c:62
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_class_new_instance+0x21) [0x7f7cd5e48a71] object.c:1896
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_cfunc+0xf1) [0x7f7cd5f34f41] vm_insnhelper.c:1752
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2179) [0x7f7cd5f3efe9] insns.def:1066
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_vm_call+0x30) [0x7f7cd5f477c0] vm_eval.c:62
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_cfunc+0xf1) [0x7f7cd5f34f41] vm_insnhelper.c:1752
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2e00) [0x7f7cd5f3fc70] insns.def:967
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_iseq_block_from_c+0x3a9) [0x7f7cd5f43f09] vm.c:969
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_block_from_c_unsplattable+0xeb) [0x7f7cd5f440ab] vm.c:1101
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_invoke_proc+0xbb) [0x7f7cd5f4420b] vm.c:1126
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_opt_call+0x9c) [0x7f7cd5f4556c] vm_insnhelper.c:1979
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_method+0xe3) [0x7f7cd5f45b33] vm_insnhelper.c:2292
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2179) [0x7f7cd5f3efe9] insns.def:1066
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_iseq_block_from_c+0x3a9) [0x7f7cd5f43f09] vm.c:969
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_block_from_c_unsplattable+0xeb) [0x7f7cd5f440ab] vm.c:1101
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_invoke_proc+0xbb) [0x7f7cd5f4420b] vm.c:1126
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_opt_call+0x9c) [0x7f7cd5f4556c] vm_insnhelper.c:1979
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_method+0xe3) [0x7f7cd5f45b33] vm_insnhelper.c:2292
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2179) [0x7f7cd5f3efe9] insns.def:1066
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(rb_call0+0x1b8) [0x7f7cd5f48238] vm_eval.c:62
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(send_internal+0xce) [0x7f7cd5f486de] vm_eval.c:952
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_cfunc+0xf1) [0x7f7cd5f34f41] vm_insnhelper.c:1752
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_method+0xe3) [0x7f7cd5f45b33] vm_insnhelper.c:2292
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2e00) [0x7f7cd5f3fc70] insns.def:967
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_iseq_block_from_c+0x3a9) [0x7f7cd5f43f09] vm.c:969
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_block_from_c_unsplattable+0xeb) [0x7f7cd5f440ab] vm.c:1101
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_invoke_proc+0xbb) [0x7f7cd5f4420b] vm.c:1126
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_opt_call+0x9c) [0x7f7cd5f4556c] vm_insnhelper.c:1979
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_method+0xe3) [0x7f7cd5f45b33] vm_insnhelper.c:2292
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2179) [0x7f7cd5f3efe9] insns.def:1066
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_iseq_block_from_c+0x3a9) [0x7f7cd5f43f09] vm.c:969
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_block_from_c_unsplattable+0xeb) [0x7f7cd5f440ab] vm.c:1101
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_invoke_proc+0xbb) [0x7f7cd5f4420b] vm.c:1126
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_opt_call+0x9c) [0x7f7cd5f4556c] vm_insnhelper.c:1979
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_method+0xe3) [0x7f7cd5f45b33] vm_insnhelper.c:2292
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2179) [0x7f7cd5f3efe9] insns.def:1066
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_iseq_block_from_c+0x3a9) [0x7f7cd5f43f09] vm.c:969
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_block_from_c_unsplattable+0xeb) [0x7f7cd5f440ab] vm.c:1101
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_invoke_proc+0xbb) [0x7f7cd5f4420b] vm.c:1126
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_call_opt_call+0x9c) [0x7f7cd5f4556c] vm_insnhelper.c:1979
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec_core+0x2179) [0x7f7cd5f3efe9] insns.def:1066
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_exec+0x87) [0x7f7cd5f43377] vm.c:1727
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_iseq_block_from_c+0x3a9) [0x7f7cd5f43f09] vm.c:969
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(invoke_block_from_c_unsplattable+0xeb) [0x7f7cd5f440ab] vm.c:1101
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(vm_invoke_proc+0xbb) [0x7f7cd5f4420b] vm.c:1126
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(thread_start_func_2+0x76e) [0x7f7cd5f00d0e] thread.c:577
[2018-10-26 21:48:15][test_selenium] /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/../lib/libruby.so.2.4(thread_start_func_1+0xd0) [0x7f7cd5f011f0] thread_pthread.c:887
[2018-10-26 21:48:15][test_selenium] /lib/x86_64-linux-gnu/libpthread.so.0(start_thread+0xc4) [0x7f7cd5752184]
[2018-10-26 21:48:15][test_selenium] /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f7cd5a6603d]

**Comment by p0deje** [comment]
This is Ruby segfaulting, possibly related to https://bugs.ruby-lang.org/issues/13586 (at least some portion of stacktrace and Ruby versions match).
