### ISSUE TITLE
'POST /session/<sessionid>/moveto' was not found [Safari 12]

### ISSUE THREAD

**Issue by pittgoose** [SeleniumHQ/selenium#6658]
OS: macOS Mojave
Selenium Version: selenium-webdriver@3.6.0 (nodeJS)
Browser: Safari
Browser Version: 12

Using protractor 5.4.1 I sent the following command to Safari to move the mouse and perform some clicks on the page:

```
browser.driver.actions()
            .mouseMove(protractorElement.getWebElement(), {x: 200, y: 0})
            .perform();
```

When running this against Safari 11 (on macOS High Sierra) the command works because the Safari driver for Safari 11 uses [JSON Wire Protocol](https://developer.apple.com/documentation/webkit/macos_webdriver_commands_for_safari_11_1_and_earlier). 

When running this same command against Safari 12 (on macOS Mojave) the command fails with the following error message because Safari driver for Safari 12 uses [W3C endpoints](https://developer.apple.com/documentation/webkit/macos_webdriver_commands_for_safari_12_and_later)

```
UnknownCommandError: The command 'POST /session/<sessionid>/moveto' was not found.
    at Object.throwDecodedError ([...]\node_modules\selenium-webdriver\lib\error.js:514:15)
    at parseHttpResponse ([...]\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response ([...]\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: mouseMove
    at thenableWebDriverProxy.schedule ([...]\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at actions.map.action ([...]\node_modules\selenium-webdriver\lib\actions.js:124:23)
    at Array.map (<anonymous>)
    at [...]\node_modules\selenium-webdriver\lib\actions.js:123:29
    at TaskQueue.execute_ ([...]\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ ([...]\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun ([...]\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at [...]\node_modules\selenium-webdriver\lib\promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: ActionSequence.perform
    at ActionSequence.perform ([...]\node_modules\selenium-webdriver\lib\actions.js:122:33)
   [...] // <- line in my code where the perform() is called.
```

**Comment by lmtierney** [comment]
You've explained the issue well, but it's not an issue with Selenium. Protractor needs to account for this.

**Comment by lmtierney** [comment]
The alpha version of selenium supports this command.

**Comment by pittgoose** [comment]
When is the full 4.0.0 version going to be released? I imagine that Protractor will only implement it when it's out of Alpha.
