### ISSUE TITLE
UnixUtils exception when quitting from Selenium RC

### ISSUE THREAD

**Issue by BenjaminXiao** [SeleniumHQ/selenium#666]
Currently I am using the Python Selenium 2.46 bindings to connect to Selenium RC 2.46. I consistently get the below error when quitting. Things were working fine in 2.45.

```
Traceback (most recent call last):
  File "../../webexrpc/endpoints.py", line 233, in teardown
    self.driver.quit()
  File "/home/xiaorzha/.local/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 477, in quit
    self.execute(Command.QUIT)
  File "/home/xiaorzha/.local/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 195, in execute
    self.error_handler.check_response(response)
  File "/home/xiaorzha/.local/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 170, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: UnixUtils may not be used on Windows
Screenshot: available via screen
Stacktrace:
    at org.openqa.selenium.os.ProcessUtils.getProcessId (ProcessUtils.java:189)
    at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.getPID (UnixProcess.java:221)
    at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$3 (UnixProcess.java:220)
    at org.openqa.selenium.os.UnixProcess.destroy (UnixProcess.java:131)
    at org.openqa.selenium.os.CommandLine.destroy (CommandLine.java:153)
    at org.openqa.selenium.firefox.FirefoxBinary.quit (FirefoxBinary.java:259)
    at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit (NewProfileExtensionConnection.java:202)
    at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit (FirefoxDriver.java:376)
    at org.openqa.selenium.firefox.FirefoxDriver.stopClient (FirefoxDriver.java:322)
    at org.openqa.selenium.remote.RemoteWebDriver.quit (RemoteWebDriver.java:477)
    at sun.reflect.GeneratedMethodAccessor61.invoke (None:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (None:-1)
    at java.lang.reflect.Method.invoke (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke (EventFiringWebDriver.java:102)
    at com.sun.proxy.$Proxy1.quit (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver.quit (EventFiringWebDriver.java:199)
    at org.openqa.selenium.remote.server.handler.DeleteSession.call (DeleteSession.java:50)
    at org.openqa.selenium.remote.server.handler.DeleteSession.call (DeleteSession.java:1)
    at java.util.concurrent.FutureTask.run (None:-1)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
    at java.lang.Thread.run (None:-1)
```

**Comment by lukeis** [comment]
I'm unable to reproduce.

On a Win 7 machine, running the standalone server plainly:

    java -jar selenium-server-standalone-2.46.0.jar

and then running the following example script:

    from selenium import webdriver
    driver = webdriver.Remote("http://<host of win7 machine>:4444/wd/hub", webdriver.DesiredCapabilities.FIREFOX)
    driver.get('https://github.com/SeleniumHQ/selenium')
    driver.quit()

works as expected with no exception in driver.quit().


Please elaborate the OS version you are running, how you are starting your selenium server and an example script that reproduces the problem (if different than the one I provided). We'll reopen the issue when that is provided, otherwise it is currently not reproducible.

**Comment by sohammukherjee** [comment]
After moving to selenium 2.47 from 2.45 this exception gets thrown from driver.quit().
Its not always recurring, but it does happen.

org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.47.0', revision: '0e4837e94b1fad0db93e88cd972ed3e235a22892', time: '2015-07-29 15:58:41'
System info: host: 'DIN51001221', ip: '10.102.43.145', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:589)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:464)
	at com.capgemini.ip.mavuno.executor.Test.tearDown(Test.java:116)
	at com.capgemini.ip.mavuno.executor.Test.executeTest(Test.java:127)
	at com.capgemini.ip.mavuno.executor.ScreenShot.run(ScreenShot.java:292)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.IllegalStateException: UnixUtils may not be used on Windows
	at org.openqa.selenium.os.ProcessUtils.getProcessId(ProcessUtils.java:189)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.getPID(UnixProcess.java:222)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$300(UnixProcess.java:201)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:131)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:190)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:568)
	... 6 more

**Comment by Toilal** [comment]
Issue still exists with 2.53.1. I'm using MarionetteDriver on Windows, and have the same stacktrace when WebDriver is closing.

Problem is that code execution reach for some reason [UnixProcess.java#L131-L132](https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/java/client/src/org/openqa/selenium/os/UnixProcess.java#L131-L132). Then the log method calls ```watchdog.getPID()``` which is not supported on Windows and throws an IllegalStateException.

Please re-open the issue.

**Comment by lukeis** [comment]
@toilal if you have a reproducible test case that you can provide and show your stacktrace, please log a new issue. This one is too old and wasn't reproduced

**Comment by Toilal** [comment]
I'm sorry, in fact I wanted to reply on this one : #2667 which is only 7 days old.

**Comment by Toilal** [comment]
I just created this issue => #2701, with a JUnit test reproducing the issue.
