### ISSUE TITLE
c# ChromeWebDriver

### ISSUE THREAD

**Issue by hejhj** [SeleniumHQ/selenium#6669]
## Meta -
OS:  
Windows 10
Selenium Version:  
 <package id="Selenium.Support" version="3.141.0" targetFramework="net461" />
  <package id="Selenium.WebDriver" version="3.141.0" targetFramework="net461" />
  <package id="Selenium.WebDriver.ChromeDriver" version="2.43.0" targetFramework="net461" />

Browser:  
Chrome

Browser Version:  
Chrome Version 70.0.3538.102 

## Expected Behavior -
return "https://www.google.co.nz"
Tried with IE driver, it's slightly better, gives me null instead of exception.

## Actual Behavior -
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.HttpCommandExecutor.HttpRequestInfo..ctor(Uri serverUri, Command commandToExecute, CommandInfo commandInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.GetProperty(String propertyName)
...

## Steps to reproduce -
var driver = new ChromeDriver();
driver.Navigate().GoToUrl("https://www.google.co.nz");	
driver.FindElement(By.Name("q")).GetProperty("baseURI");

**Comment by hejhj** [comment]
I know the root cause now, will fix it.

**Comment by simonjduff** [comment]
A NullReferenceException can't be "expected behaviour" surely.
Could you not raise a custom exception `LegacyDriverUnsupportedOperationException` or something?
NullReferenceExceptions just look like bugs.

**Comment by jimevans** [comment]
@simonjduff No, I would expect `NotImplementedException` to be thrown. Indeed, in the project tests for this very scenario (calling `GetProperty` on an implementation not compliant with the W3C specification), that’s exactly what happens. The results for `ElementPropertyTest` at http://webdriver-herald.herokuapp.com show this quite clearly for the Chrome-using-OSS-protocol-dialect case. The provided stack trace indicates it’s being thrown by the `HttpRequestInfo` constructor, which has appropriate null pointer guards in it, so I’m unable to reproduce it.

The “expected behavior” comment was directed more toward the attempt to “fix” the issue with a pull request. Since the protocol is well-defined, and the end point doesn’t exist in the references protocol dialect, blindly adding it for that dialect is inappropriate. I apologize for the ambiguity in my comment.

Finally, since ChromeDriver will default to the W3C protocol dialect starting with Chrome 75, and since work has begun to remove all use of the legacy OSS dialect of the protocol in the Selenium 4 version of the .NET bindings, taking other action on this issue seems ill-advises.

**Comment by simonjduff** [comment]
Does the above apply to Firefox as well, as I received the same error from the firefox driver?

**Comment by jimevans** [comment]
It shouldn’t throw on calling the method, and again, I refer you to the WebDriver Herald site to see that such tests exist and do pass for modern Firefox versions using geckodriver. If the property does not exist, however, a return value of `null` _is_ expected, and is the documented behavior of the method.

**Comment by simonjduff** [comment]
Thanks @jimevans I'll try to recreate and investigate further. It may be that a wrapping library is not handling null properly, though I did get the same exception trace I believe, NullReferenceException at `OpenQA.Selenium.Remote.HttpCommandExecutor.HttpRequestInfo..ctor`.
I'll raise a separate issue if required after investigation specific to firefox. Thanks, signing off.
