### ISSUE TITLE
SocketTimeoutException instead of 

### ISSUE THREAD

**Issue by sighil** [SeleniumHQ/selenium#6719]
## 🐛 Bug Report

I am using Selenium with TestNG on a UI application developed in angular. When selenium polls for an element NOT present in the UI, the execution hangs for 3 hours and finally java.net.SocketTimeoutException is thrown. 

We had seen this on earlier versions of Selenium as well (3.4). The main problem this issue causes us is the 3 hour wait. The screenshot taken after failure would be of the login page as the UI session times out in 2 hours and redirects. (We cannot change the 2 hour session timeout because this is an important testing criteria). So we are left clueless to the actual state of the UI (whether the browser has frozen etc.).

## Expected behavior

We expect org.openqa.selenium.NoSuchElementException and the 3 hour wait not to happen.

## Environment

OS: Windows 7
Browser: Chrome
Browser version: 70.0.3538.110 (Official Build) (64-bit)
Browser Driver version: Chrome driver 2.36.540470
Language Bindings version: Java 1.8.0_31

## Stacktrace

2018-11-30T00:30:47,336 [INFO ] ###Sensitive content hidden### :         is navigation successful (###Sensitive content hidden###)?
Nov 30, 2018 3:30:51 AM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.xpath: //div[@class='titlebar']//div[text()='###Sensitive content hidden###'])
org.openqa.selenium.WebDriverException: java.net.SocketTimeoutException: Read timed out
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: '###Sensitive content hidden###', ip: '###Sensitive content hidden###', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_31'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:349)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:428)
	at org.openqa.selenium.By$ByXPath.findElements(By.java:348)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:310)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:183)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:180)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)
	at ###Sensitive content hidden###
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at ###Sensitive content hidden###
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:150)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)

**Comment by sighil** [comment]
In selenium 3.4 we had handled this by overriding the socket timeout from 3 hours to 10 mins in the HttpClient using reflection.

    static void setSocketTimeout(int socketTimeoutInSeconds) {
        try {
            final Field field = Class.forName(HttpClientFactory.class.getName()).getDeclaredField("TIMEOUT_THREE_HOURS");
            field.setAccessible(true);
            Field modifiersField = Field.class.getDeclaredField("modifiers");
            modifiersField.setAccessible(true);
            modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);
            field.set(null, (int) TimeUnit.SECONDS.toMillis(socketTimeoutInSeconds));
       } catch (Exception e) {
    }

Selenium 3.14 uses OKHttpClient and a factory to initialize the variables for timeout and the above code is no longer feasible. 

public static class Factory implements HttpClient.Factory {
    private final ConnectionPool pool = new ConnectionPool();
    private final long connectionTimeout;
    private final long readTimeout;

    public Factory() {
        this(Duration.ofMinutes(2), Duration.ofHours(3));
    }

    public Factory(Duration connectionTimeout, Duration readTimeout) {
        Objects.requireNonNull(connectionTimeout, "Connection timeout cannot be null");
        Objects.requireNonNull(readTimeout, "Read timeout cannot be null");

        this.connectionTimeout = connectionTimeout.toMillis();
        this.readTimeout = readTimeout.toMillis();
    }

Is there a way to set the same in Selenium 3.14?

**Comment by sighil** [comment]
Currently in Selenium 3.14, I will use the environment variable to set the default http client as apache.

interface Factory {
   static Factory createDefault() {
       String defaultFactory = System.getProperty("webdriver.http.factory", "okhttp");
       switch (defaultFactory) {
       case "apache":
             return new ApacheHttpClient.Factory();

        case "okhttp":
        default:
            return new OkHttpClient.Factory();
        }
  }

But please consider an option to provide customization for the read timeout value so that at least the execution does not hang for 3 hours.

**Comment by diemol** [comment]
Hi @sighil,

You can check this [code](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/BaseGridRegistry.java#L62), so you will see how to use it.

Nevertheless, the proper way to set that timeout is by using the `browserTimeout` parameter, which was broken for a while but it is working properly in the latest release (3.141.59).

Moreover, this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.

**Comment by kurtfusion** [comment]
I agree with sighil with regards to this still being an issue. org.openqa.selenium.remote.internal.OkHttpClient.Factory sets a readTimeout to 3 hours. 

help me understand why this is set to 3 hours, that's a long time to wait.

The readTimeout is pulled from org.openqa.selenium.remote.http.HttpClient.Builder 
Line 94 -> protected Duration readTimeout = Duration.ofHours(3);

My workaround was to copy the whole OkHttpClient class and just override the readTimeout setting to something more reasonable like 5 minutes. 


(NOTE: I modified the OKHttpClient.java to OkHttpClientFix.java and changed the duration.) 

---- my hack ---- 
HttpCommandExecutor executor = new HttpCommandExecutor(new HashMap<String, CommandInfo>(),new URL(hub),new OkHttpClientFix.Factory());
driver = new RemoteWebDriver(executor, options);

**Comment by diemol** [comment]
This is the line where it is shown that the values are set properly
https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/java/server/src/org/openqa/grid/internal/BaseGridRegistry.java#L62
