### ISSUE TITLE
selenium-server node run with -browser , get error: unknown error: DevToolsActivePort file doesn't exist.   Must install Xvfb

### ISSUE THREAD

**Issue by ljppttfn** [SeleniumHQ/selenium#6733]
## 💬 selenium-server node run with -browser , get error: unknown error: DevToolsActivePort file doesn't exist.   
After install Xvfb, it works ok.
Why?

#### Way1:
By this way, it works ok:
```
java -jar selenium-server-standalone-3.141.59.jar -role node -hub http://127.0.0.1:5555/grid/register -maxSession 15
```
------------------
#### Way2:
But if i add `-browser `, then it works fail :
```
java -jar selenium-server-standalone-3.141.59.jar -role node -hub http://127.0.0.1:5555/grid/register -maxSession 15 -browser browserName=chrome,maxInstances=10,platform=LINUX
```
get error:
```
org.openqa.selenium.WebDriverException: 
unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 3.10.0-514.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 178 milliseconds

```

After install `Xvfb`,  Way2 works ok.

Test Code:
```
        DesiredCapabilities capability = DesiredCapabilities.chrome();
        capability.setBrowserName("chrome");
        capability.setPlatform(Platform.LINUX);

        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--headless", "--no-sandbox", "--disable-gpu", "--window-size=1290,1080","--disable-dev-shm-usage");
        chromeOptions.addArguments("--disable-extensions");
        capability.setCapability("chromeOptions", chromeOptions);
```

**Comment by ljppttfn** [comment]
when role no `-browser`, the code can use  both ```capability.setCapability("chromeOptions", chromeOptions);``` and  ```capability.setCapability("goog:chromeOptions", chromeOptions);```.

if role add `-browser`, the code must use:```capability.setCapability("goog:chromeOptions", chromeOptions);```;


But if use ```capability.setCapability("goog:chromeOptions", chromeOptions);```,
it will get error:
```
14:59:25.939 INFO [ActiveSessions$1.onStop] - Removing session abc6a27cd43268b5edb82c98ab0928ca (org.openqa.selenium.chrome.ChromeDriverService)
14:59:32.958 INFO [OsProcess.destroy] - Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
        at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
        at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:180)
        at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:136)
        at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
        at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:232)
        at org.openqa.selenium.grid.session.remote.ServicedSession.stop(ServicedSession.java:85)
        at org.openqa.selenium.remote.server.ActiveSessions.lambda$new$1(ActiveSessions.java:56)
        at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1811)
        at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3463)
        at com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3439)
        at com.google.common.cache.LocalCache$Segment.remove(LocalCache.java:3073)
        at com.google.common.cache.LocalCache.remove(LocalCache.java:4234)
        at com.google.common.cache.LocalCache$LocalManualCache.invalidate(LocalCache.java:4898)
        at org.openqa.selenium.remote.server.ActiveSessions.invalidate(ActiveSessions.java:103)
        at org.openqa.selenium.remote.server.WebDriverServlet.handle(WebDriverServlet.java:264)
        at org.openqa.selenium.remote.server.WebDriverServlet.doDelete(WebDriverServlet.java:133)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
        at org.openqa.selenium.remote.server.WebDriverServlet.service(WebDriverServlet.java:114)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
14:59:32.959 ERROR [OsProcess.destroy] - Unable to kill process java.lang.UNIXProcess@3d713a08
```

**Comment by ljppttfn** [comment]
> Unable to drain process streams. Ignoring but the exception being swallowed follows
When use `capability.setCapability("goog:chromeOptions", chromeOptions);`:

`driver.quit()`  will get  error.
`driver.close()`  works ok.

**Comment by ljppttfn** [comment]
it works ok now, but i don't remember what i do!

**Comment by diemol** [comment]
Hi @ljppttfn,

Xvfb is needed if you don't have a screen where the browser is running. E.g. http://elementalselenium.com/tips/38-headless

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
