### ISSUE TITLE
Windows Server 2012 R2- IE 11(Version - 11.0.9600.19180)- Error -org.openqa.selenium.NoSuchWindowException: Unable to get browser

### ISSUE THREAD

**Issue by santoshchk** [SeleniumHQ/selenium#6743]
OS: Windows Server 2012 R2 (64 bit)
Selenium Version: 3.13.0 /3.14.0/3.141.59
Browser: Internet explorer via IEDriverServer 32bit (Version 3.13.0 / 3.14.0)
Browser Version: IE 11 (Version - 11.0.9600.19180)
Note : All IE Protected zones set correctly and added website under trusted websites.

Snippet Java code:(Steps to Reproduce)
public static void main(String[] args) throws InterruptedException {
		String driverPath = "D:\iedriver.exe";
		System.setProperty("webdriver.ie.driver", driverPath);
		DesiredCapabilities  capabilities = DesiredCapabilities.internetExplorer();
		InternetExplorerOptions io = new InternetExplorerOptions();
		io.merge(capabilities);
		InternetExplorerDriver driver = new InternetExplorerDriver(io);
		driver.get("https://AUTTest.com");
		Thread.sleep(9000);
		String title = driver.getTitle();
		System.out.println(title);
		driver.quit();;
	}

Error :
started InternetExplorerDriver server (32-bit)
3.13.0.0
Listening on port 44853
Only local connections are allowed
Dec 11, 2018 4:10:55 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.NoSuchWindowException: Unable to get browser
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'xyzzzz', ip: '1.xx.xx.12', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_172'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:44853/, nativeEvents: true, requireWindowFocus: false}, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: d0371b01-d702-4abf-8396-13ef490f61d5
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.getTitle(RemoteWebDriver.java:280)
	at Test.main(Test.java:25)

Expected : IE browser should load and perform the expected actions.
Actual : Error -org.openqa.selenium.NoSuchWindowException: Unable to get browser

**Comment by diemol** [comment]
Is this issue still happening with the latest version of Selenium?

**Comment by diemol** [comment]
Closing this as we did not get more information, please feel free to open a new issue if the problem still persists after trying with the most recent versions.
