### ISSUE TITLE
No modal dialog is currently open (Selenium::WebDriver::Error::NoSuchAlertError)

### ISSUE THREAD

**Issue by alaxalves** [SeleniumHQ/selenium#6751]
Guys, I'm currently working on a Rails 4.2 -> Rails 5.1 upgrade and I use Firefox 60.3 as my selenium browser. But lately I've experiencing an unusual type of error. Here it goes:

```
No modal dialog is currently open (Selenium::WebDriver::Error::NoSuchAlertError)
WebDriverError@chrome://marionette/content/error.js:178:5
NoSuchAlertError@chrome://marionette/content/error.js:423:5
GeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3197:11
GeckoDriver.prototype.getTextFromDialog@chrome://marionette/content/driver.js:3160:3
despatch@chrome://marionette/content/server.js:293:20
execute@chrome://marionette/content/server.js:267:11
onPacket/<@chrome://marionette/content/server.js:242:15
onPacket@chrome://marionette/content/server.js:241:8
_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9
./features/step_definitions/web_steps.rb:147:in `rescue in block (2 levels) in <top (required)>'
./features/step_definitions/web_steps.rb:144:in `block (2 levels) in <top (required)>'
./features/step_definitions/web_steps.rb:20:in `with_scope'
./features/step_definitions/web_steps.rb:143:in `/^(?:|I )should see "([^"]*)"(?: within "([^"]*)")?$/'
features/delete_profile.feature:123:in `Then I should see "Are you sure you want to deactivate this profile?"'
```
Apparently this says the error is related to an unfound Modal in Chrome. But I'm not using Chrome at all. What could it be?

For more complete jobs my selenium jobs can be found at: 
https://gitlab.com/alaxalves/noosfero/-/jobs

**Comment by alaxalves** [comment]
Apparently, this problem was caused by my Firefox version, I was using 60.3 but for some reason even latest geckodriver 0.23 can't "see" alerts on this version, even though it gets displayed. I had to downgrade to version 57.

**Comment by alaxalves** [comment]
I closing this for now. :smile:
