### ISSUE TITLE
PhantomJS cannot register as a node in 3.141

### ISSUE THREAD

**Issue by querymetrics** [SeleniumHQ/selenium#6771]
## 💥 Regression Report

We're hitting this issue with PhantomJS 1.9.8, but the latest GhostDriver w/ PhantomJS2 may have the same issue connecting since it uses the `wd` role as well:
https://github.com/detro/ghostdriver/blob/7cf96db846e336a1a6dd9da891399902985dd57e/src/hub_register.js#L71

I know PhantomJS (especially the version we use: `1.9.8`) is old an unsupported but it worked great up to 3.14.0. We rely on PhantomJS to regression test our libraries against old browsers that don't have modern web APIs.

Would it be possible to relax the checks added in https://github.com/SeleniumHQ/selenium/commit/6ec1d7659df8f1835d68168df3a182cddc9d8329 to allow the connection from PhantomJS using the `wd` role name?

```
org.openqa.grid.common.exception.GridConfigurationException: Error with the JSON of the config : Unable to load node configuration from org.openqa.selenium.json.JsonInput@56bab22f because it contains configuration for 'wd' role
	at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.loadFromJSON(GridNodeConfiguration.java:386)
	at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.loadFromJSON(GridNodeConfiguration.java:357)
	at org.openqa.grid.web.servlet.RegistrationServlet.mapV2Configuration(RegistrationServlet.java:135)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:94)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: 
java.lang.RuntimeException: Unable to load node configuration from org.openqa.selenium.json.JsonInput@56bab22f because it contains configuration for 'wd' role
	at org.openqa.grid.internal.utils.configuration.json.NodeJsonConfiguration.loadFromJson(NodeJsonConfiguration.java:41)
	at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.loadFromJSON(GridNodeConfiguration.java:362)
	at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.loadFromJSON(GridNodeConfiguration.java:357)
	at org.openqa.grid.web.servlet.RegistrationServlet.mapV2Configuration(RegistrationServlet.java:135)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:94)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

## Last working Selenium version

Worked up to version: 3.14.0

Stopped working in version: 3.141.0

## To Reproduce

Create a docker container for PhantomJS:
* download https://raw.githubusercontent.com/querymetrics/docker-phantomjs/master/Dockerfile
* `docker build --build-arg PHANTOM_JS_VERSION=1.9.8-linux-x86_64 -t phantomjs198_image .`
* `docker run -it -p 8910:8910 -p 9000:9000 phantomjs198_image /usr/local/bin/phantomjs --webdriver=127.0.0.1:8910 --webdriver-selenium-grid-hub=http://[IP OF YOUR SELENIUM HUB]:4444`

PhantomJS will fail to connect.

## Expected behavior

Expect PhantomJS to be able to register as a node. 

## Environment

OS: OSX
Browser: PhantomJS
Browser version: 1.9.8
Browser Driver version: GhostDriver 
Selenium Grid version (if applicable): 3.141.0

**Comment by p0deje** [comment]
Tagging @barancev as the author of the breaking changes.

**Comment by sbabcoc** [comment]
Sorry for the late arrival. I'm able to use PhantomJS 2.1.1 with PhantomJSDriver 1.4.4 attached as a node to Selenium Grid 3.141.59. I'm setting up the Grid through my Selenium Foundation library, but this is just launching the Grid with the standard JAR's. I don't use the stand-alone JAR, as this brings in a whole bundle of baked-in dependencies that cause conflicts.

**Comment by diemol** [comment]
Closing this as the previous comments summarize things.
In addition, ghostdriver won't be supported in Selenium Grid 4
