### ISSUE TITLE
WebElement.location throwing error Safari

### ISSUE THREAD

**Issue by Spleeding1** [SeleniumHQ/selenium#6783]
## 🐛 Bug Report

Trying to compare elements.location['y'] in Safari throws error. If you need more information, please let me know.

## To Reproduce

Python 3.7, Django 2.1

```
from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from django.test import TestCase
from selenium import webdriver
from selenium.common.exceptions import WebDriverException
from selenium.webdriver.remote.webelement import WebElement


class FunctionalTestTest(StaticLiveServerTestCase):
    
    def setUp(self):
        self.browser = webdriver.Safari()
    
    
    def tearDown(self):
        self.browser.quit()
    
    
    def test_test_app(self):
        self.browser.get(self.live_server_url + '/_test')
        
        hello_div = self.browser.find_element_by_id(
            'hello_div'
        )
        
        goodbye_div = self.browser.find_element_by_id(
            'goodbye_div'
        )
        
        self.assertLess(
            hello_div.location['y'],
            goodbye_div.location['y']
        )
```
```
from django.shortcuts import render


def test_page(request):
    return render(request, '_test_app/test_page.html')
```

```
<!DOCTYPE html>
  <body>
    <div id="hello_div">Hello!</div>
    <div id="goodbye_div">Goodbye!</div>
  </body>
</html>
```

Detailed steps to reproduce the behavior:

## Expected behavior

I am trying to compare locations of WebElements. I have used Firefox until it stopped working recently. Switched to Safari, now I get this issue. Also, the Safari browser does not quit after the test ends. The window closes, but the app remains open.

## Test script or set of commands reproducing this issue

python3 manage.py test _test_app.tests

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E
======================================================================
ERROR: test_test_app (_test_app.tests.FunctionalTestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/------/Software/------/_test_app/tests.py", line 30, in test_test_app
    hello_div.location['y'],
  File "/Users/------/Software/------/------_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 536, in location
    "y": round(old_loc['y'])}
KeyError: 'y'

----------------------------------------------------------------------
Ran 1 test in 9.700s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

## Environment

OS:  macOS Mojave 10.14.2
Browser:  Safari
Browser version:  Version 12.0.2 (14606.3.4)
Browser Driver version:  Apple's Driver
Language Bindings version:  Python 3.141.0
Selenium Grid version (if applicable):

**Comment by KroArtem** [comment]
This sounds very similar to issue https://github.com/SeleniumHQ/selenium/issues/6637

**Comment by KroArtem** [comment]
Btw, I do have the same problem with App not closing.
>Also, the Safari browser does not quit after the test ends. The window closes, but the app remains open.

@burg , is it possible for you to check this out?

**Comment by burg** [comment]
> Btw, I do have the same problem with App not closing.
> 
> > Also, the Safari browser does not quit after the test ends. The window closes, but the app remains open.
> 
> @burg , is it possible for you to check this out?

This is a known issue; safaridriver has always done this. I'd like to fix it sometime. For now you can kill -9 safaridriver and Safari.app if it's causing you problems, such as a later session failing to be created with an already-paired Safari.

**Comment by KroArtem** [comment]
>This is a known issue; safaridriver has always done this. I'd like to fix it sometime

Ok, thanks for explanation! It doesn't influence on our flow so it doesn't cause me any problems :)

**Comment by Spleeding1** [comment]
I just got a response back from Apple on this issue.

> Engineering has determined that your bug report (46919864) is a duplicate of 45451114 and 
> will be closed.

Not that this affects what you already know, I just thought I'd let you know.

**Comment by burg** [comment]
This issue is fixed in recent Safari Technology Preview builds.
