### ISSUE TITLE
org.jruby.exceptions.RaiseException: (ArgumentError) unknown encoding name - UTF8

### ISSUE THREAD

**Issue by otkeri** [SeleniumHQ/selenium#6816]
## 🐛 Bug Report

At build time, jruby throws an error.
```
C:\selenium\selenium-3.10.0>go build --trace
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Parsing cpp/build.desc
Parsing cpp/iedriverserver/build.desc
Parsing dotnet/docs/build.desc
Parsing dotnet/test/remote/build.desc
Parsing dotnet/test/support/build.desc
Parsing dotnet/test/webdriverbackedselenium/build.desc
Parsing ide/build.desc
Parsing ide/main/build.desc
Parsing ide/plugins/csharp-format/build.desc
Parsing ide/plugins/groovy-format/build.desc
Parsing ide/plugins/java-format/build.desc
Parsing ide/plugins/perl-format/build.desc
Parsing ide/plugins/php-format/build.desc
Parsing ide/plugins/python-format/build.desc
Parsing ide/plugins/ruby-format/build.desc
Parsing javascript/build.desc
Parsing javascript/android-atoms/build.desc
Parsing javascript/atoms/build.desc
Parsing javascript/atoms/fragments/build.desc
Parsing javascript/chrome-driver/build.desc
Parsing javascript/firefox-driver/build.desc
Parsing javascript/ie-driver/build.desc
Parsing javascript/jsunit/build.desc
Parsing javascript/node/build.desc
Parsing javascript/remote/build.desc
Parsing javascript/safari-driver/build.desc
Parsing javascript/selenium-atoms/build.desc
Parsing javascript/selenium-core/build.desc
Parsing javascript/watir-atoms/build.desc
Parsing javascript/webdriver/build.desc
Parsing javascript/webdriver/atoms/build.desc
Parsing javascript/webdriver/atoms/fragments/build.desc
Parsing javascript/webdriver/atoms/fragments/inject/build.desc
Parsing javascript/webdriver/atoms/inject/build.desc
Parsing py/build.desc
Parsing rb/build.desc
org.jruby.exceptions.RaiseException: (ArgumentError) unknown encoding name - UTF8
        at org.jruby.RubyFile.expand_path(org/jruby/RubyFile.java:816)
        at RUBY.define_build_task(C:/selenium/selenium-3.10.0/rake-tasks/crazy_fun/mappings/ruby.rb:160)
        at RUBY.handle(C:/selenium/selenium-3.10.0/rake-tasks/crazy_fun/mappings/ruby.rb:153)
        at RUBY.block in create_tasks(C:/selenium/selenium-3.10.0/rake-tasks/crazy_fun.rb:71)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
        at RUBY.block in create_tasks(C:/selenium/selenium-3.10.0/rake-tasks/crazy_fun.rb:70)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
        at RUBY.block in create_tasks(C:/selenium/selenium-3.10.0/rake-tasks/crazy_fun.rb:64)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
        at RUBY.create_tasks(C:/selenium/selenium-3.10.0/rake-tasks/crazy_fun.rb:61)
        at RUBY.<main>(C:/selenium/selenium-3.10.0/rakefile:100)
        at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:973)
        at RUBY.(root)(uri:classloader:/gems/rake-10.5.0/lib/rake/rake_module.rb:1)
        at RUBY.load_rakefile(uri:classloader:/gems/rake-10.5.0/lib/rake/rake_module.rb:28)
        at RUBY.block in raw_load_rakefile(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:689)
        at RUBY.load_rakefile(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:94)
        at RUBY.standard_exception_handling(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:176)
        at RUBY.block in load_rakefile(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:93)
        at RUBY.run(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:77)
        at RUBY.standard_exception_handling(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:176)
        at RUBY.<main>(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:75)
        at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:973)
        at RUBY.<main>(uri:classloader:/gems/rake-10.5.0/bin/rake:33)
Parsing third_party/closure/build.desc
Parsing third_party/firebug/build.desc
Parsing third_party/jruby/build.desc
Parsing third_party/js/sizzle/build.desc
Parsing third_party/js/wgxpath/build.desc
** Invoke build (first_time)
** Invoke all (first_time)
** Invoke selenium-java (first_time)
** Invoke //java/client/src/org/openqa/selenium:selenium (first_time)
** Execute //java/client/src/org/openqa/selenium:selenium
org.jruby.exceptions.RaiseException: (ArgumentError) unknown encoding name - UTF8
        at org.jruby.RubyFile.expand_path(org/jruby/RubyFile.java:816)
        at RUBY.download(C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:16)
        at RUBY.buck_cmd(C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:57)
        at RUBY.block in (root)(C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:260)
        at RUBY.block in execute(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:240)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
        at RUBY.execute(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:235)
        at RUBY.block in invoke_with_call_chain(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:179)
        at RUBY.mon_synchronize(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214)
        at RUBY.invoke_with_call_chain(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172)
        at RUBY.block in invoke_prerequisites(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
        at RUBY.invoke_prerequisites(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199)
        at RUBY.block in invoke_with_call_chain(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178)
        at RUBY.mon_synchronize(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214)
        at RUBY.invoke_with_call_chain(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172)
        at RUBY.block in invoke_prerequisites(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
        at RUBY.invoke_prerequisites(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199)
        at RUBY.block in invoke_with_call_chain(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178)
        at RUBY.mon_synchronize(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214)
        at RUBY.invoke_with_call_chain(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172)
        at RUBY.block in invoke_prerequisites(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
        at RUBY.invoke_prerequisites(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199)
        at RUBY.block in invoke_with_call_chain(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178)
        at RUBY.mon_synchronize(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214)
        at RUBY.invoke_with_call_chain(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172)
        at RUBY.invoke(uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:165)
        at RUBY.invoke_task(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:150)
        at RUBY.block in top_level(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1735)
        at RUBY.block in top_level(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106)
        at RUBY.run_with_threads(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:115)
        at RUBY.top_level(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:100)
        at RUBY.block in run(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:78)
        at RUBY.standard_exception_handling(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:176)
        at RUBY.run(uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:75)
        at RUBY.<main>(uri:classloader:/gems/rake-10.5.0/bin/rake:33)
        at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:973)
        at RUBY.<main>(uri:classloader:/META-INF/jruby.home/bin/rake:1)
python C:/selenium/selenium-3.10.0/buck-out/crazy-fun/0c687e0a193b409b8b59b08b8db36b4177b28eaa/buck.pex kill
python C:/selenium/selenium-3.10.0/buck-out/crazy-fun/0c687e0a193b409b8b59b08b8db36b4177b28eaa/buck.pex build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium
PARSING BUCK FILES... 3.2s (100%)
CREATING ACTION GRAPH: FINISHED IN 0.3s
Build failed: No system compiler found. Did you install the JRE instead of the JDK?
    When running <javac_jar>.
    When building rule //java/client/src/org/openqa/selenium:beta.
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES
BUILDING: FINISHED IN 3.6s (100%) 7/36 JOBS, 2 UPDATED, 5.6% CACHE MISS
BUILD FAILED
Exception `RuntimeError' at C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:85 - python C:/selenium/selenium-3.10.0/buck-out/crazy-fun/0c687e0a193b409b8b59b08b8db36b4177b28eaa/buck.pex build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
Exception `#<Class:#<RuntimeError:0x5e3db14>>' at C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:85 - python C:/selenium/selenium-3.10.0/buck-out/crazy-fun/0c687e0a193b409b8b59b08b8db36b4177b28eaa/buck.pex build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
Exception `#<Class:#<RuntimeError:0x5e3db14>>' at C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:85 - python C:/selenium/selenium-3.10.0/buck-out/crazy-fun/0c687e0a193b409b8b59b08b8db36b4177b28eaa/buck.pex build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
Exception `#<Class:#<RuntimeError:0x5e3db14>>' at C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:85 - python C:/selenium/selenium-3.10.0/buck-out/crazy-fun/0c687e0a193b409b8b59b08b8db36b4177b28eaa/buck.pex build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
Exception `#<Class:#<RuntimeError:0x5e3db14>>' at C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:85 - python C:/selenium/selenium-3.10.0/buck-out/crazy-fun/0c687e0a193b409b8b59b08b8db36b4177b28eaa/buck.pex build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
go aborted!
python C:/selenium/selenium-3.10.0/buck-out/crazy-fun/0c687e0a193b409b8b59b08b8db36b4177b28eaa/buck.pex build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:85:in `block in buck_cmd'
org/jruby/RubyIO.java:4902:in `popen3'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jruby/open3_windows.rb:74:in `popen3'
C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:69:in `buck_cmd'
C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:260:in `block in (root)'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
uri:classloader:/gems/rake-10.5.0/bin/rake:33:in `<main>'
org/jruby/RubyKernel.java:973:in `load'
uri:classloader:/META-INF/jruby.home/bin/rake:1:in `<main>'
ArgumentError: unknown encoding name - UTF8
org/jruby/RubyFile.java:816:in `expand_path'
C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:16:in `download'
C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:57:in `buck_cmd'
C:/selenium/selenium-3.10.0/rake-tasks/buck.rb:260:in `block in (root)'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
uri:classloader:/gems/rake-10.5.0/bin/rake:33:in `<main>'
org/jruby/RubyKernel.java:973:in `load'
uri:classloader:/META-INF/jruby.home/bin/rake:1:in `<main>'
Tasks: TOP => build => all => selenium-java => //java/client/src/org/openqa/selenium:selenium
```

## To Reproduce
>go build

## Expected behavior
jruby says that the above issue has been resolved in the latest version.
https://github.com/jruby/jruby/issues/4546

## Environment

OS:  Windows 10 
Selenium Grid version (if applicable):  3.10.0

**Comment by cgoldberg** [comment]
> jruby says that the above issue has been resolved in the latest version.

the issue you linked doesn't say it was fixed

**Comment by barancev** [comment]
Is this issue still actual for master HEAD? Or version 3.10 is affected but not the latest one?

Also there is a message
`Build failed: No system compiler found. Did you install the JRE instead of the JDK?`
Make sure you've installed Java SDK and configured PATH properly.

**Comment by diemol** [comment]
Closing as we didn't get an answer from the OP.
