### ISSUE TITLE
File download in a new tab causes chrome to close #6833

### ISSUE THREAD

**Issue by Shebeok** [SeleniumHQ/selenium#6849]
Can you please Reopen issue#6833. It happens even in 3.141.59. Sample code to reproduce the issue is provided below
Meta -
OS:
Windows 7 enterprise
Selenium Version:
Selenium.WebDriver v3.141.59
Selenium.WebDriver.ChromeDriver 2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a)
Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Expected Behavior -
Attempting to download a file using a ChromeDriver. The website being "driven" opens a new tab on button click, which then triggers a download of a file. Then the browser remains open to continue further steps. This works as expected in firefox. This works when I use ChromeDriver driver=new ChromeDriver(capabilities);. The browser closes when I assign ChromeDriver instance to WebDriver.

Actual Behavior -
Once file download is completed the new tab closes then the browser also closes which causes the next steps/tests to fail with chrome not reachable exception.
Caused by: org.openqa.selenium.WebDriverException: chrome not reachable

Edited to add the code with a public page to reproduce the issue. The code fails when it tries to find link 2 with chrome not reachable.

Code to reproduce:

                System.setProperty("webdriver.chrome.driver", "webdrivers/chromedriver.exe");
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setJavascriptEnabled(true);
		capabilities.setCapability("takesScreenshot", true);
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		capabilities.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
		final ChromeOptions chromeOptions = new ChromeOptions();
		HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
		chromePrefs.put("profile.default_content_settings.popups", 0);
		chromePrefs.put("download.prompt_for_download", false);
		chromePrefs.put("download.directory_upgrade", true);
		chromePrefs.put("download.default_directory", "Downloads");
		chromePrefs.put("plugins.always_open_pdf_externally", true);
		chromeOptions.setExperimentalOption("prefs", chromePrefs);
		capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

		
		WebDriver driver=new ChromeDriver(capabilities);			
	
		driver.get("https://angular.io/guide/quickstart");
		By link1 = By.xpath("//a[@href='generated/zips/cli-quickstart/cli-quickstart.zip']");
		Thread.sleep(5000);
		WebElement element = driver.findElement(link1);
		System.out.println("1");
		element.click();
		System.out.println("2");
		Thread.sleep(5000);
		System.out.println("3");
		By link2 = By.xpath("//a[@href='guide/file-structure']");
		System.out.println("4");
		WebElement element2 = driver.findElement(link2);
		System.out.println("5");
		element2.click();
		System.out.println("6");

**Comment by diemol** [comment]
Hi @Shebeok,

I just tried your code, and it works, I also uploaded it to GitHub, check it [here](https://github.com/diemol/docker-selenium-issues/blob/master/selenium-issue-6849/src/test/java/FileDownload.java).

What I see is that the website opens a new tab, downloads the file and then the tab is closed. After that the test fails because the line 
```
        By link2 = By.xpath("//a[@href='guide/file-structure']");
        System.out.println("4");
        WebElement element2 = driver.findElement(link2);
```
are not finding the element.

If you still have this issue, please provide a link to a GitHub project where the behaviour is reproducible.

**Comment by Shebeok** [comment]
Thanks for taking time to look into the issue. It happens when 'chromeOptions.addArguments("--disable-extensions");' is added when the driver is being created. Extremely Sorry I had missed it out when I copy pasted the sample code.


`import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import java.util.HashMap;

public class FileDownload {

    @Test
    public void fileDownloadTest() throws InterruptedException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setJavascriptEnabled(true);
        capabilities.setCapability("takesScreenshot", true);
        capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
        capabilities.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
        final ChromeOptions chromeOptions = new ChromeOptions();
        HashMap<String, Object> chromePrefs = new HashMap<>();
        chromePrefs.put("profile.default_content_settings.popups", 0);
        chromePrefs.put("download.prompt_for_download", false);
        chromePrefs.put("download.directory_upgrade", true);
        chromePrefs.put("download.default_directory", "Downloads");
        chromePrefs.put("plugins.always_open_pdf_externally", true);
        chromeOptions.setExperimentalOption("prefs", chromePrefs);
        chromeOptions.addArguments("--disable-extensions");
        capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
        WebDriver driver = new ChromeDriver(capabilities);
        driver.get("https://angular.io/guide/quickstart");
        By link1 = By.xpath("//a[@href='generated/zips/cli-quickstart/cli-quickstart.zip']");
        Thread.sleep(5000);
        WebElement element = driver.findElement(link1);
        System.out.println("1");
        element.click();
        System.out.println("2");
        Thread.sleep(5000);
        System.out.println("3");
        By link2 = By.xpath("//a[@href='guide/file-structure']");
        System.out.println("4");
        WebElement element2 = driver.findElement(link2);
        System.out.println("5");
        element2.click();
        System.out.println("6");
        driver.quit();
    }

    @Test
    public void fileDownloadTestWithoutDeprecatedChromeDriver() throws InterruptedException {
        WebDriver driver = null;
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setCapability(CapabilityType.SUPPORTS_JAVASCRIPT, true);
        chromeOptions.setCapability("takesScreenshot", true);
        chromeOptions.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
        chromeOptions.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
        HashMap<String, Object> chromePrefs = new HashMap<>();
        chromePrefs.put("profile.default_content_settings.popups", 0);
        chromePrefs.put("download.prompt_for_download", false);
        chromePrefs.put("download.directory_upgrade", true);
        chromePrefs.put("download.default_directory", "Downloads");
        chromePrefs.put("plugins.always_open_pdf_externally", true);
        chromeOptions.setExperimentalOption("prefs", chromePrefs);
        chromeOptions.addArguments("--disable-extensions");
        try {
            driver = new ChromeDriver(chromeOptions);
            driver.get("https://angular.io/guide/quickstart");
            By link1 = By.xpath("//a[@href='generated/zips/cli-quickstart/cli-quickstart.zip']");
            Thread.sleep(5000);
            WebElement element = driver.findElement(link1);
            System.out.println("1");
            element.click();
            System.out.println("2");
            Thread.sleep(5000);
            System.out.println("3");
            By link2 = By.xpath("//a[@href='guide/file-structure']");
            System.out.println("4");
            WebElement element2 = driver.findElement(link2);
            System.out.println("5");
            element2.click();
            System.out.println("6");
        } finally {
            if (driver != null) {
                driver.quit();
            }
        }

    }

}`

**Comment by Shebeok** [comment]
This is the exception I am getting once the download completes and the browser closes
org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'NJ09VDI2230', ip: '10.203.160.17', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.43.600210 (68dcf5eebde371..., userDataDir: C:\Users\CHITHR~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:55724}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 71.0.3578.98, webStorageEnabled: true}
Session ID: e8a80a9f192ec9e9be8d733d3128c47e
*** Element info: {Using=xpath, value=//a[@href='guide/file-structure']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at env.MainClass.fileDownloadTestWithoutDeprecatedChromeDriver(MainClass.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
