### ISSUE TITLE
`selenium.common.exceptions.SessionNotCreatedException` issue

### ISSUE THREAD

**Issue by chenrui333** [SeleniumHQ/selenium#6854]
## 🐛 Bug Report

selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer

## To Reproduce

```
from selenium import webdriver
browser = webdriver.Chrome()
browser.get('http://seleniumhq.org/')
```

$ python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    browser = webdriver.Chrome()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.13.6 x86_64)

## Expected behavior

Should open the browser

## Test script or set of commands reproducing this issue

Could not see the browser open.

## Environment

OS: OSX
Browser: Chrome
Browser version: 71.0.3578.98
Browser Driver version: ChromeDriver 2.45
Language Bindings version: python 2
Selenium Grid version (if applicable):selenium==3.14.1

**Comment by cgoldberg** [comment]
> unable to connect to renderer

can you check your `/etc/hosts` and verify you have an entry with `127.0.0.1` for `localhost`?

**Comment by chenrui333** [comment]
@cgoldberg I will check on this tomorrow, thanks for providing the direction.

**Comment by chenrui333** [comment]
@cgoldberg yeah, it works, thanks a lot!

**Comment by cgoldberg** [comment]
great! 🥇
