### ISSUE TITLE
finding element from "http://www.ewteacher.com" raise WebDriverException: session deleted because of page crash/invalid session id/no such session

### ISSUE THREAD

**Issue by lilin3** [SeleniumHQ/selenium#6855]
## 🐛 Bug Report

```
browser=webdriver.Chrome()
browser.get("http://www.ewteacher.com") #OK
print("titile="+browser.title) #OK
body=browser.find_element_by_tag_name("body")#raise WebDriverException: Message: unknown error: session deleted because of page crash/invalid session id/no such session
```
I have tested at 4 ubuntu machines，remote and local, headless and no headless, latest version and previous version.
The fourth line code above will raise exception every time.
It is 100% reproducible.
**I have tested over 10000 sites, only this site will raise such exception.** 
Yes I did only open only one chrome session at one time and it raise exception. 
Codes work fine when I use firefox.
I don't use Docker.
Maybe it is chromedriver's problem, But I think friends here are more professional.

## To Reproduce
see codes below

## Expected behavior

```
Traceback (most recent call last):
  File "manage.py", line 186, in <module>
    manager.run()
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 182, in test8
    test.testewteacher()
  File "/home/yonghu/wode/myproject/regpark/app/main/test.py", line 51, in testewteacher
    body=browser.find_element_by_tag_name("body")
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 530, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.4.0-117-generic x86_64)

```

## Test script or set of commands reproducing this issue

```
options=ChromeOptions()
options.add_argument("--disable-dev-shm-usage") #this flag can't solve the problem too.
browser = webdriver.Remote(command_executor=my_specifice_executor, desired_capabilities=DesiredCapabilities.CHROME, options=options)
#browser=webdriver.Chrome(options=ChromeOptions())
browser.get("http://www.ewteacher.com")#OK
print("titile="+browser.title)#OK
body=browser.find_element_by_tag_name("body")#raise webdriverexception
print(body.text)

```
## Environment

OS: ubuntu 16.04
Browser: chrome
Browser version: 71.0.3578.98
Browser Driver version: chromedriver=2.45.615279
Language Bindings version: Java 1.8.0_191
Selenium Grid version (if applicable):

**Comment by lilin3** [comment]
The problem in here is related to  overriding the 'shift' method of JavaScript Array library in http://www.ewteacher.com/js/prototype.js file.

shift: function() {
    var result = this[0];
    for (var i = 0; i < this.length - 1; i++)
      this[i] = this[i + 1];
    this.length==16;  ==> !! this causes the out of memory crash
    return result;
  },

ChromeDriver doesn't support override methods of standard JavaScript libraries.

No solution.
