### ISSUE TITLE
Selenium 3.14.0 - "element not clickable at point.." when trying to interact with elements further up the page (scrolling required)

### ISSUE THREAD

**Issue by chickenZ42** [SeleniumHQ/selenium#6857]
## 🐛 Bug Report

The following issue appears in both Firefox and Chrome on different OS (linux, win) and different browser/browserdriver versions: 

When locating and interacting with elements further down a page, WebDriver auto-scrolls to the element's location.
However, if current location is down the page but next element to be located and interacted with would require scrolling up, test crashes saying "... is not clickable at point (x,y). Other element would receive the click (...)"
The element is enabled/displayed and not covered/overlayed by other elements/animations etc, only thing required is to scroll up.

Fun fact, a millisecond before crashing, it actually does scroll up but still fails with said exception message (I can tell because I've both monitored and created test reports with screenshots to see what actually causes the tests to fail).
I've also implemented WebDriverEventListener and added waits to every method (I know, it isn't pretty) just to see if it made any difference - it didn't.

The only thing where Firefox and Chrome differ:
WebDriverEventListener.beforeClickOn() - when adding a check if WebElement.isDisplayed() - if not, scroll to element by executing javascript :
((JavascriptExecutor)driver).executeScript("arguments[0].scrollIntoView();", element);

Firefox behavior:
- element: not displayed, executes javascript and successfully scrolls up the page

Chrome behavior:
- element: displayed, ignores script
- also ignores script if you tell it to do it each time beforeClickOn or changeValueOf etc (tried tons of variations here)

Note: getting coordinate of WebElement and using javascript window.scrollTo(x,y) is ignored by Chrome as well.

While I know I could enforce clicks with javascript, in my eyes that's not the point of testing "real" interactions on a website, for this way I won't know if real users were actually able to click on/write in said element.
I also only discovered this issue by accident when testing with testcontainers framework (resolution in containers used seems to be lower, hence more scrolling is required).

## To Reproduce

Detailed steps to reproduce the behavior:

Go to URL of your choice, locate WebElement further down on the page (WebDriver scrolls down then interacts with WebEelement).
Locate WebElement further up the page (WebElement is not in viewport of current location, so scrolling up would be required) and try to click on it.
Instead of doing so, browser closes and test crashes with a stacktrace like this:

org.openqa.selenium.WebDriverException: unknown error: Element <select ng-model="$parent.invModel" id="testID" name="testID" inv-backend-error="" ng-disabled="invDisabled" ng-change="invChange()" ng-readonly="invReadonly" ng-options="option.key as option.value for option in invOptions" ng-required="invRequired" class="ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required" required="required">...</select> is not clickable at point (163, 16). Other element would receive the click: <div class="large-12 columns">...</div>
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-957.1.3.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'digip-build03.inverso.local', ip: '192.168.2.62', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.1.3.el7.x86_64', java.version: '10.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.42.591071 (0b695ff80972cc..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:42320}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 71.0.3578.98, webStorageEnabled: true, webdriver.remote.sessionid: d500b85187db807617a20879a94...}
Session ID: d500b85187db807617a20879a94c1dc1
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.lambda$new$0(EventFiringWebDriver.java:403)
	at com.sun.proxy.$Proxy9.click(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.click(EventFiringWebDriver.java:416)
(...)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

## Expected behavior

WebDriver locating element, scrolling up to it, then interacting with it like it would if WebElement were located down the page.

## Test script or set of commands reproducing this issue

I can't provide the actual code due to compliancy policies, but the issue can be reproduced on any site long enough where scrolling up/down a page is required.

## Environment

OS: Windows 8.1, Linux CentOS7, testcontainers: 1.10.2 (unknown OS)
Browser: Chrome, Firefox
Browser version: several versions
Browser Driver version: several versions
Selenium Grid version (if applicable): 3.14.0

**Comment by stupidnetizen** [comment]
Hi
I ran below mentioned test case using both Chrome and Marionette and it is passing, without any issue.
`test/selenium/webdriver/common/click_scrolling_tests.py::testShouldBeAbleToClickOnAnElementHiddenByYOverflow` 

Moreover, I performed the steps to reproduce after making some modifications in the html as shown below

```html
<body>
  <div style="width:100%; height: 500px; overflow: hidden; overflow-y: auto;">
    
    <a id="link21" href="#clicked">Click me later!</a>
    <div style="height: 5000px; width: 5000px;">Placeholder</div>
    <div>
      <a id="link2" href="#clicked">Click me first!</a>
    </div>
  </div>
</body>
```

I hope that the issue that you have mentioned is occasional.
Let me know whether the steps cover the tests that you are trying to perform. 
I can send a pull request by adding the steps in the existing test case.

**Comment by chickenZ42** [comment]
Hello,
Thank you for the quick response!
I can't seem to get python module to work atm, working on that one

As for my issue, I'm using Java (jdk1.8.0_172) where the problem persists.
I've also tried using Actions class:

```
Actions actions = new Actions(webDriver);
actions.moveToElement(element).click().perform();
```

This seems to work for most (but not all) of out tests, since the mouse click event clicks exactly on the position of the element, which on some pages is obscured by header menus.
i.e. it clicks on the menu overlaying the actualy element, thus making tests fail by unintentionally getting redirected to some other page

I'm really at a loss why nothing I've tried so far seems to work for me since I'd expect WebDriver to just auto-scroll to the element when using FindBy method

I'll post an update whether the python test you used actually works for me once I managed to fix my IDE issues

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by chickenZ42** [comment]
Sorry it took me a while to respond, didn't have the time to try this week.
In the meantime I found following workaround that at least so far didn't cause any issues - before performing element.click() I'm using 

`((JavascriptExecutor)webDriver).executeScript("arguments[0].scrollIntoView(false);", element);`

 - scrolling to the bottom of the element seems to do the trick for us, since it doesn't work at all with 'true'

Due to limitations at work I'm not able to run python tests at the moment, so I'll be closing this ticket for now - thank you for your efforts!
