### ISSUE TITLE
driver.title is WebElement object instead of string

### ISSUE THREAD

**Issue by lilin3** [SeleniumHQ/selenium#6866]
## Expected behavior

```
Traceback (most recent call last):
  File "manage.py", line 229, in <module>
    manager.run()
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/yonghu/wode/myproject/regpark/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 219, in test9
    test.testjtjyol()
  File "/home/yonghu/wode/myproject/regpark/app/main/test.py", line 51, in testjtjyol
    print("titile="+browser.title)
TypeError: <flask_script.commands.Command object at 0x7f731a4ab780>: Can't convert 'WebElement' object to str implicitly
```

## Test script or set of commands reproducing this issue

```
    browser=webdriver.Chrome(options=ChromeOptions(),desired_capabilities=DesiredCapabilities.CHROME)
    browser.get("http://www.jtjyol.com")
    print("titile="+browser.title)
```

## Environment

OS: ubuntu 16.04
Chrome=66.0.3359.139 + chromedriver=2.38.552522
Chrome=71.0.3578.98 + chromedriver=2.45.615279 tested too
Language Bindings version:
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
It's a chromedriver issue, I've reported it there: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2747, please follow the referenced report.

**Comment by barancev** [comment]
Please read the comment https://bugs.chromium.org/p/chromedriver/issues/detail?id=2747#c1 for the verdict.

**Comment by lilin3** [comment]
OK Thanks
