### ISSUE TITLE
Chrome version exception after update windows package

### ISSUE THREAD

**Issue by rickywu** [SeleniumHQ/selenium#6874]
## To Reproduce

```
E:\Archive\Tool\NetAuth>python e:\Archive\Tool\NetAuth\auth.py
[0123/085057.182:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:2775/devtools/browser/356fb785-1b82-4465-93da-1eeb6d20e745
Traceback (most recent call last):
  File "e:\Archive\Tool\NetAuth\auth.py", line 17, in <module>
    browser = webdriver.Chrome('./chromedriver', chrome_options=chrome_options)
  File "D:\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "D:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17763 x86_64)

E:\Archive\Tool\NetAuth>wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value

Version=71.0.3578.98
```

## Environment

OS: <-- Windows 10 -->
Browser: <-- Chrome  -->
Browser version: <-- 71.0.3578.98 -->
Browser Driver version: <-- ChromeDriver 2.45.615291 -->
Language Bindings version: <-- Python 3.6.4 --> 

After uninstall these update then fix this problem but not sure which one caused
KB4480056 (probably)
KB4480116

**Comment by barancev** [comment]
Please report this issue to https://bugs.chromium.org/p/chromedriver/issues/list, it's a chromedriver internal error.
