### ISSUE TITLE
Using SeleniumSessionId is not working with firefox

### ISSUE THREAD

**Issue by tfaron** [SeleniumHQ/selenium#6880]
seleniumSessionId is not working for firefox [62.0.3 (64-bit)
"protractor": "~5.4.1"
"webdriver-manager": "^12.0.6",

Chromedriver_2.45
geckodriver-v0.23.0

my conf,js file has the following information in it and I have tried with marionette equal to true and false.

`exports.config = {
  framework: 'jasmine',

  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
  seleniumSessionId: 'be0739d9-f1dc-4088-b0df-d2f62de011af',

  capabilities: { browserName: 'firefox', marionette: true },`

The following error is thrown during execution:
`C:\svt-web-client\projects\client-ng\node_modules\.bin>protractor C:\svt-web-client\projects\client-ng\protractor.e2e.atf.conf.js --grep "C763889_OMNI_33968_2"
[13:05:16] I/launcher - Running 1 instances of WebDriver
[13:05:16] I/attachSession - Using the selenium server at http://127.0.0.1:4444/wd/hub
[13:05:16] I/attachSession - Using session id - be0739d9-f1dc-4088-b0df-d2f62de011af
[13:05:16] E/launcher - GET /session/be0739d9-f1dc-4088-b0df-d2f62de011af did not match a known command
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'WIN-73R0N5SIS5K', ip: '10.0.111.195', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_191'
Driver info: driver.version: unknown
[13:05:16] E/launcher - UnsupportedOperationError: GET /session/be0739d9-f1dc-4088-b0df-d2f62de011af did not match a known command
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'WIN-73R0N5SIS5K', ip: '10.0.111.195', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_191'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\svt-web-client\projects\client-ng\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\svt-web-client\projects\client-ng\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\svt-web-client\projects\client-ng\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.attachToSession()
    at Function.attachToSession (C:\svt-web-client\projects\client-ng\node_modules\selenium-webdriver\lib\webdriver.js:695:24)
    at AttachSession.getNewDriver (C:\svt-web-client\projects\client-ng\node_modules\protractor\built\driverProviders\attachSession.js:37:58)
    at Runner.createBrowser (C:\svt-web-client\projects\client-ng\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\svt-web-client\projects\client-ng\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:834:54)
    at C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:137:13)
    at flush (C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:125:13)
[13:05:16] E/launcher - Process exited with error code 199`

When using the webDriver it looks like /sessions returns the firefox session but attempting to get the single firefox session is where failing occurs

**Comment by cgoldberg** [comment]
> " but attempting to get the single firefox session is where failing occurs"

Can you please provide selenium code that reproduces your issue?
(Selenium projects does not produce jasmine, protractor, or webdriver-manager... and it is unclear how you are calling it all)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
