### ISSUE TITLE
selenium-webdriver 2.46.2: Window not found. The browser window may have been closed.

### ISSUE THREAD

**Issue by JAndritsch** [SeleniumHQ/selenium#689]
I have a capybara scenario that invokes some Javascript to interact with a complicated widget. This scenario passed with Firefox 38.0.5 and using webdriver version 2.45.0, but is now failing on 2.46.2 with the following stack trace:

```
      Window not found. The browser window may have been closed. (Selenium::WebDriver::Error::NoSuchWindowError)
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/command-processor.js:12350:in `nsCommandProcessor.prototype.execute'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/driver-component.js:9089:in `Dispatcher.executeAs/<'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/driver-component.js:9236:in `Resource.prototype.handle'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/driver-component.js:9183:in `Dispatcher.prototype.dispatch'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/driver-component.js:12136:in `WebDriverServer/<.handle'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/httpd.js:2054:in `createHandlerFunc/<'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/httpd.js:2387:in `ServerHandler.prototype.handleResponse'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/httpd.js:1223:in `Connection.prototype.process'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/httpd.js:1677:in `RequestReader.prototype._handleResponse'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/httpd.js:1525:in `RequestReader.prototype._processBody'
      [remote server] file:///var/folders/vf/11lzw25j51x9t9r7g13p_0lc0000gp/T/webdriver-profile20150619-2868-1rttmuf/extensions/fxdriver@googlecode.com/components/httpd.js:1393:in `RequestReader.prototype.onInputStreamReady'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:635:in `execute'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:388:in `deleteAllCookies'
      ...gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/common/options.rb:86:in `delete_all_cookies'
      ...gems/capybara-2.4.1/lib/capybara/selenium/driver.rb:95:in `reset!'
      ...gems/capybara-2.4.1/lib/capybara/session.rb:103:in `reset!'
      ...gems/capybara-2.4.1/lib/capybara.rb:257:in `block in reset_sessions!'
      ...gems/capybara-2.4.1/lib/capybara.rb:257:in `each'
      ...gems/capybara-2.4.1/lib/capybara.rb:257:in `reset_sessions!'
      ...gems/capybara-2.4.1/lib/capybara/cucumber.rb:8:in `After'
```

**Comment by lukeis** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/)

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lukeis** [comment]
when a test case is provided, we can reopen the issue
