### ISSUE TITLE
selenium with chrome --headless mode receive a timeout error

### ISSUE THREAD

**Issue by GrayGraySmall** [SeleniumHQ/selenium#6901]
## the error report:
```
Traceback (most recent call last):
  File "E:/timeoutTest.py", line 46, in <module>
    test()
  File "E:/timeoutTest.py", line 31, in test
    driver.get("https://baidu.com")
  File "d:\Users\dzlx\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "d:\Users\dzlx\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\Users\dzlx\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)
```

## my code : 
```

import time

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

def test():
    _chrome_options = Options()
    _chrome_options.add_argument("--headless")

    driver = webdriver.Chrome(r"E:\\timeoutTest\\Customized\\config\\chromedriver", chrome_options=_chrome_options)
    # driver = webdriver.Chrome(r"E:\\timeoutTest\\Customized\\config\\chromedriver")
    # cls.driver = webdriver.Chrome(executable_path=cls._chrome_driver_path)

    driver.set_window_size(1200, 812)
    driver.set_page_load_timeout(60)
    driver.set_script_timeout(20)
    # 隐式等待
    driver.implicitly_wait(5)

    driver.get("https://baidu.com")
    time.sleep(5)
    driver.find_element_by_id("kw").send_keys("htmlunit")
    time.sleep(5)
    driver.find_element_by_id("su").click()
    time.sleep(5)
    now_time = time.strftime("%Y%m%d.%H.%M.%S")
    driver.get_screenshot_as_file(now_time + '.png')
    print('screenshot:' + now_time + '.png')

    print(driver.current_url)
    print(driver.page_source)


if __name__ == '__main__':
    test()
```
the code can‘t run in the --headless mode.

-----------
# update：
After adding sleep time and update the chrome driver to 71.0.3578.137, and I change the request url to another，I received anther error like
this : 
```
Traceback (most recent call last):
  File "E:/timeoutTest/Customized/testTemp.py", line 35, in <module>
    test()
  File "E:/timeoutTest/Customized/testTemp.py", line 23, in test
    driver.find_element(By.XPATH, "//*[@data-view-name=\"index\"]/div/div[2]/div/div[3]/div[1]/div[1]/ul/li["
  File "d:\Users\dzlx\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "d:\Users\dzlx\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\Users\dzlx\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@data-view-name="index"]/div/div[2]/div/div[3]/div[1]/div[1]/ul/li[1]/div[1]/p"}
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=71.0.3578.137 (86ee722808adfe9e3c92e6e8ea746ade08423c7e),platform=Windows NT 6.1.7601 SP1 x86_64)
```
## and my code like this ：
```
import time

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

def test():
    _chrome_options = Options()
    _chrome_options.add_argument("--headless")

    driver = webdriver.Chrome(r"chromedriver", chrome_options=_chrome_options)
    # driver = webdriver.Chrome(r"E:\\timeoutTest\\Customized\\config\\chromedriver")
    # cls.driver = webdriver.Chrome(executable_path=cls._chrome_driver_path)

    driver.set_window_size(1200, 600)
    driver.set_page_load_timeout(100)
    driver.set_script_timeout(40)
    # 隐式等待
    driver.implicitly_wait(10)

    driver.get("https://m.ctrip.com/webapp/dingzhi/index")
    time.sleep(10)
    driver.find_element(By.XPATH, "//*[@data-view-name=\"index\"]/div/div[2]/div/div[3]/div[1]/div[1]/ul/li["
                                        "1]/div[1]/p").click()
    time.sleep(10)
    now_time = time.strftime("%Y%m%d.%H.%M.%S")
    driver.get_screenshot_as_file(now_time + '.png')
    print('screenshot:' + now_time + '.png')
    time.sleep(5)
    print(driver.current_url)
    print(driver.page_source)
    driver.quit()

if __name__ == '__main__':
    test()
```

the main reqestion is that, when I doesn't use the --headless mode, I can receive a page  screenshot like this: 
![image](https://user-images.githubusercontent.com/15920812/52026703-c9315200-2543-11e9-8d20-0c3dc1c7b9fb.png)

but when I use --headless argument, the page seems can't load and throw NoSuchElementException, the screenshot like this:
![image](https://user-images.githubusercontent.com/15920812/52026797-17465580-2544-11e9-84d7-a2c5c28a6b77.png)
this is a blank image.

and the question is no error in another seem config computer.

**Comment by cgoldberg** [comment]
> (Session info: headless chrome=71.0.3578.98)
>   (Driver info: chromedriver=2.41.578737 

Chromedriver 2.41 is not compatible with Chrome 71.. please upgrade.
also, please fill out al info requested in the issue template (selenium version, etc)

**Comment by GrayGraySmall** [comment]
> > (Session info: headless chrome=71.0.3578.98)
> > (Driver info: chromedriver=2.41.578737
> 
> Chromedriver 2.41 is not compatible with Chrome 71.. please upgrade.
> also, please fill out al info requested in the issue template (selenium version, etc)

thanks receive your reply, After I update the chromedriver version and add timesleep, I received another error, the error has updated in the question. thanks!

**Comment by barancev** [comment]
NoSuchElementException is a legit exception, Selenium throws it when it can't find an element on the current page.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
