### ISSUE TITLE
'java.lang.Long cannot be cast to java.lang.Integer' when using socksVersion

### ISSUE THREAD

**Issue by dsmontoya** [SeleniumHQ/selenium#6917]
## 🐛 Bug Report

When I send the socksVersion field to the server, I get the following error:

`java.lang.Long cannot be cast to java.lang.Integer`

The data payload is the following:

```json
{
   "capabilities":{
      "alwaysMatch":{
         "browserName":"chrome",
         "goog:chromeOptions":{

         },
         "proxy":{
            "proxyType":"manual",
            "socksProxy":"172.18.0.2",
            "socksVersion":5
         }
      }
   },
   "desiredCapabilities":{
      "browserName":"chrome",
      "chromeOptions":{

      },
      "goog:chromeOptions":{

      },
      "proxy":{
         "proxyType":"manual",
         "socksProxy":"172.18.0.2",
         "socksVersion":5
      }
   }
}
```

I'm using my own fork of the golang package https://github.com/tebeka/selenium

## To Reproduce

1. Download my issues repo and go to this issue dir.
```shell
git clone git@github.com:dsmontoya/issues.git
cd issues/selenium/socks-version
```
2. Run the selenium containers
```shell
docker-compose up
```
3. Source the env vars
```shell
source .env
```
4. Run the socks-version file or build it by yourself
```shell
./socks-version
```

## Expected behavior

It should open a new chrome window configured with a socks5 proxy.

## Test script or set of commands reproducing this issue
All the source code is provided in https://github.com/dsmontoya/issues/tree/master/selenium/socks-version

### Docker images:
* selenium/node-chrome:3.141.59
* selenium/hub:3.141.59

**Comment by cgoldberg** [comment]
can you provide the entire stacktrace?

**Comment by occupant23** [comment]
We discovered the same issue yesterday and a debugging session lead that the reason for this seem to be somewhere around the JSON conversion in the `org.openqa.selenium.remote.ProtocolHandshake.class` 
Somewhere in this beautiful commented region: 
```Java
    // Ignore the content type. It may not have been set. Strictly speaking we're not following the
    // W3C spec properly. Oh well.
    Map<?, ?> blob;
    try {
      blob = new Json().toType(response.getContentString(), Map.class);
    } catch (JsonException e) {
      throw new WebDriverException(
          "Unable to parse remote response: " + response.getContentString(), e);
    }
```

Stacktrace:
```
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'xxx, ip: 'xxx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_45'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at com.xceptance.neodymium.module.statement.browser.multibrowser.BrowserRunnerHelper.createWebdriver(BrowserRunnerHelper.java:266)
	at com.xceptance.neodymium.module.statement.browser.BrowserStatement.setUpTest(BrowserStatement.java:148)
	at com.xceptance.neodymium.module.statement.browser.BrowserStatement.evaluate(BrowserStatement.java:104)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.xceptance.neodymium.NeodymiumRunner.runChild(NeodymiumRunner.java:300)
	at com.xceptance.neodymium.NeodymiumRunner.runChild(NeodymiumRunner.java:70)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at org.openqa.selenium.Proxy.<init>(Proxy.java:94)
	at org.openqa.selenium.remote.ProtocolHandshake$Result.lambda$static$0(ProtocolHandshake.java:151)
	at org.openqa.selenium.remote.ProtocolHandshake$Result$$Lambda$217/1413730361.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake$Result.<init>(ProtocolHandshake.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$successHandler$1(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.JsonWireProtocolResponse$$Lambda$216/176683244.apply(Unknown Source)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.HandshakeResponse$$Lambda$212/816798571.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$213/1097897234.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	... 26 more
```

**Comment by dsmontoya** [comment]
Thanks for the stacktrace @occupant23.

**Comment by jbaldassari** [comment]
Any chance that this fix might get back ported to 3.x, or do we have to wait for 4.0?
