### ISSUE TITLE
"unknown error: call function result missing 'value'" when return a jQuery object in an execute_script

### ISSUE THREAD

**Issue by cwardata** [SeleniumHQ/selenium#6932]
## 🐛 Bug Report

I get this error when executing javascript that uses jQuery and returns a jQuery object.

Interesting thing is ignoring the error is fine.

## Expected behavior

Just works, removes the header or just ignores if there is no header.

## Test script or set of commands reproducing this issue

```
require 'selenium-webdriver'
require 'capybara/dsl'

class C
  extend Capybara::DSL
end

Capybara.current_driver = :selenium_chrome
Capybara.default_max_wait_time = 5

C.visit("https://getbootstrap.com/")
C.execute_script("$('#header').remove()")
```

## Environment

OS: macOS
Browser: Chrome
Browser version: 72.0.3626.96 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e)
Language Bindings version: Ruby 3.141.0 (selenium-wedriver)

**Comment by cwardata** [comment]
Backtrace:

```
d@d ~/s/cwdata> pbpaste | ruby -e "puts ARGF.read.gsub('/Users/d', '*')"
Traceback (most recent call last):
	13: from scripts/chrome2.rb:20:in `<main>'
	12: from */.rvm/gems/ruby-2.5.0/gems/capybara-3.13.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
	11: from */.rvm/gems/ruby-2.5.0/gems/capybara-3.13.2/lib/capybara/session.rb:577:in `execute_script'
	10: from */.rvm/gems/ruby-2.5.0/gems/capybara-3.13.2/lib/capybara/selenium/driver.rb:82:in `execute_script'
	 9: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/driver.rb:211:in `execute_script'
	 8: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/oss/bridge.rb:267:in `execute_script'
	 7: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/oss/bridge.rb:584:in `execute'
	 6: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
	 5: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	 4: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	 3: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
	 2: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
	 1: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
*/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': unknown error: call function result missing 'value' (Selenium::WebDriver::Error::UnknownError)
  (Session info: chrome=72.0.3626.96)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),plat
```

**Comment by p0deje** [comment]
Do you see this error in Firefox or only in Chrome?

**Comment by cwardata** [comment]
@p0deje only Chrome (tried the same script on Firefox with `driver = :selenium`)

**Comment by p0deje** [comment]
@cwardata Then it looks like ChromeDriver issue. 
Please post the issue to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
