### ISSUE TITLE
2.46.0 BrowserVersion NPE

### ISSUE THREAD

**Issue by Igor-ua** [SeleniumHQ/selenium#700]
I'm sorry if I'm wrong or posting it in the wrong place.
I've tried the latest maven's version 2.46.0. By the way - 2.45.0 is working fine with the same code.
I've got NPE when I've tried both of BrowserVersion's constructors.

```java
HtmlUnitDriver driver = new HtmlUnitDriver(new BrowserVersion("a", "b", "c", 10f, null));
or
HtmlUnitDriver driver = new HtmlUnitDriver(new BrowserVersion("a", "b", "c", 10f));
```
```java
июн 22, 2015 4:45:25 PM com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine run
SEVERE: Exception while initializing JavaScript for the page
java.lang.NullPointerException
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.hasFeature(HtmlUnitContextFactory.java:339)
	at net.sourceforge.htmlunit.corejs.javascript.Context.hasFeature(Context.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.getProperty(ScriptableObject.java:2378)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.init(JavaScriptEngine.java:302)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.access$000(JavaScriptEngine.java:104)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$1.run(JavaScriptEngine.java:171)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:628)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.initialize(JavaScriptEngine.java:182)
	at com.gargoylesoftware.htmlunit.WebClient.initialize(WebClient.java:1003)
	at com.gargoylesoftware.htmlunit.WebWindowImpl.setEnclosedPage(WebWindowImpl.java:133)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:216)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:194)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:471)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:345)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:410)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:512)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:490)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.<init>(HtmlUnitDriver.java:195)
	at selenium.Main.main(Main.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Exception in thread "main" org.openqa.selenium.WebDriverException: com.gargoylesoftware.htmlunit.ScriptException
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'PC', ip: 'my_ip', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25'
Driver info: driver.version: HtmlUnitDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:525)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:490)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.<init>(HtmlUnitDriver.java:195)
	at selenium.Main.main(Main.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.gargoylesoftware.htmlunit.ScriptException
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$1.run(JavaScriptEngine.java:175)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:628)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.initialize(JavaScriptEngine.java:182)
	at com.gargoylesoftware.htmlunit.WebClient.initialize(WebClient.java:1003)
	at com.gargoylesoftware.htmlunit.WebWindowImpl.setEnclosedPage(WebWindowImpl.java:133)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:216)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:194)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:471)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:345)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:410)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:512)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.hasFeature(HtmlUnitContextFactory.java:339)
	at net.sourceforge.htmlunit.corejs.javascript.Context.hasFeature(Context.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.getProperty(ScriptableObject.java:2378)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.init(JavaScriptEngine.java:302)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.access$000(JavaScriptEngine.java:104)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$1.run(JavaScriptEngine.java:171)
	... 21 more

Process finished with exit code 1
```

**Comment by barancev** [comment]
One can't simply pass anything as a browser version.

Try to call HtmlUnit directly:
```WebClient webClient = new WebClient(new BrowserVersion("a", "b", "c", 10f));
webClient.getPage(webClient.getOptions().getHomePage());```
and watch the same NullPointerException deep inside HtmlUnit.

Of course we can wrap this exception into WebDriverException, but I think it is worthless.

Why 2.45 works? Because we upgraded HtmlUnit to the latest available version in 2.46 :)

If you think this is a real bug please raise an issue on the HtmlUnit bug tracker.
