### ISSUE TITLE
Problem with grid in standalone with firefox

### ISSUE THREAD

**Issue by Anyazinovyeva** [SeleniumHQ/selenium#7004]
### Please note that this issue tracker is not a help form and this issue will be closed.

Start tests in selenium-standalone with error

Environment:
OS- linux 
selenium-java.version - 3.141.5
geckodriver - 0.23.0
firefox - 65.0.1

Get error when up standalone by command with grid:

Error: POST /session/2db823d0-93f7-4d66-a105-6d31b01476f8/moveto did not match a known command (POST /session/2db823d0-93f7-4d66-a105-6d31b01476f8/moveto did not match a known command)
    at new RuntimeError (/portal/portal/node_modules/hermione/node_modules/@gemini-testing/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/portal/portal/node_modules/hermione/node_modules/@gemini-testing/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/portal/portal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/portal/portal/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/portal/portal/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

And get succes result when start with comand where dont use grid.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
