### ISSUE TITLE
Error forwarding the new session Error forwarding the request org.seleniumhq.jetty9.io.EofException

### ISSUE THREAD

**Issue by OlegYanushkevich** [SeleniumHQ/selenium#7025]
## 🐛 Bug Report

When running tests in parallel under the Internet Explorer after some time I have a queue at the hub, and the number of queue items is much more than the running tests. The node accumulates a browser with a start page of about: blank. After session timeout hub kills hung sessions and starting new sessions from queue and the situation repeats until the nodes fall off by OutOfMemoryException.

### nodeconfig.json
_{
  "capabilities":
      [
        {
          "browserName": "firefox",
          "maxInstances": 10,
          "seleniumProtocol": "WebDriver"
        },
        {
          "browserName": "chrome",
          "maxInstances": 10,
          "seleniumProtocol": "WebDriver"
        },
        {
          "browserName": "internet explorer",
          "maxInstances": 5,
          "seleniumProtocol": "WebDriver"
        }
      ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 20,
  "port": 5563,
  "host": "[protected]",
  "register": true,
  "hub": "[protected]",
  "nodeStatusCheckTimeout": 5000,
  "registerCycle": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": true,
  "log" : "lognode.txt",
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}_

##hubconfig.json
_{
  "port": 4441,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {},
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "cleanUpCycle": 5000,
  "role": "hub",
  "debug": true,
  "log": "loghub.txt",
  "browserTimeout": 0,
  "timeout": 1800
}_

## Expected behavior

Grid Hub correctly works with sessions queue and node successfully finishes all sessions.

## Actual behavior

A large number of errors on the grid hub something like that:

```
06:55:38.426 INFO [RequestHandler.process] - Error forwarding the new session Error forwarding the request org.seleniumhq.jetty9.io.EofException
org.openqa.grid.internal.exception.NewSessionException: Error forwarding the request org.seleniumhq.jetty9.io.EofException
	at
org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:94)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.grid.common.exception.ClientGoneException: org.seleniumhq.jetty9.io.EofException
	at org.openqa.grid.internal.TestSession.writeRawBody(TestSession.java:492)
	at org.openqa.grid.internal.TestSession.forward(TestSession.java:286)
	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:91)
	... 34 more
Caused by: org.seleniumhq.jetty9.io.EofException
	at org.seleniumhq.jetty9.io.ChannelEndPoint.flush(ChannelEndPoint.java:292)
	at org.seleniumhq.jetty9.io.WriteFlusher.flush(WriteFlusher.java:429)
	at org.seleniumhq.jetty9.io.WriteFlusher.write(WriteFlusher.java:322)
	at org.seleniumhq.jetty9.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
	at org.seleniumhq.jetty9.server.HttpConnection$SendCallback.process(HttpConnection.java:788)
	at org.seleniumhq.jetty9.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.seleniumhq.jetty9.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.seleniumhq.jetty9.server.HttpConnection.send(HttpConnection.java:528)
	at org.seleniumhq.jetty9.server.HttpChannel.sendResponse(HttpChannel.java:778)
	at org.seleniumhq.jetty9.server.HttpChannel.write(HttpChannel.java:834)
	at org.seleniumhq.jetty9.server.HttpOutput.write(HttpOutput.java:234)
	at org.seleniumhq.jetty9.server.HttpOutput.write(HttpOutput.java:218)
	at org.seleniumhq.jetty9.server.HttpOutput.write(HttpOutput.java:535)
	at java.io.OutputStream.write(Unknown Source)
	at org.openqa.grid.internal.TestSession.writeRawBody(TestSession.java:490)
	... 36 more
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source)
	at sun.nio.ch.IOUtil.write(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
	at org.seleniumhq.jetty9.io.ChannelEndPoint.flush(ChannelEndPoint.java:272)
	... 50 more
```

and started blank IE browser on node with command:

```
06:55:38.426 DEBUG [RemoteWebDriver.log] - Executing: newSession [null, newSession {desiredCapabilities=Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: false, ie.browserCommandLineSwitches: , ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: false, initialBrowserUrl: about:blank, nativeEvents: false, requireWindowFocus: false}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}}]

06:55:38.426 DEBUG [RemoteWebDriver.log] - Executed: [null, newSession {desiredCapabilities=Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: false, ie.browserCommandLineSwitches: , ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: false, initialBrowserUrl: about:blank, nativeEvents: false, requireWindowFocus: false}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}}]

06:55:38.426 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session d9219771-ef2e-4ef8-a163-cb9e948aed09 (org.openqa.selenium.ie.InternetExplorerDriverService)
```

## Test script or set of commands reproducing this issue

1) Start grid hub;
2) Start node.
3) Running tests that using IEDriverServer through Grid Hub.

## Environment

OS: Windows 10
Browser: IE 11
Browser version: 11.321.14393.0
Browser Driver version: 3.141.0
Language Bindings version: java 1.8.0_201.
Selenium Grid version:  3.141.0

**Comment by diemol** [comment]
Hi @OlegYanushkevich,

It is known that running tests with Internet Explorer in parallel is not straightforward and most of the time it does not work. The recommendation is to have more than one node with Internet Explorer and run only one concurrent session per node. Please see more details in the links below:

https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3111
https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#multiple-instances-of-internetexplorerdriver
https://stackoverflow.com/questions/32725310/run-multiple-iedriver-instances-on-the-same-machine
