### ISSUE TITLE
Selenium Web Driver not working with java.net.useSystemProxies

### ISSUE THREAD

**Issue by HardiPatel1501** [SeleniumHQ/selenium#7031]
OS: Windows 
Browser: Chrome
Browser version: 73.0.3683.75
Browser Driver version: Chromdriver2.46
Selenium version (if applicable): 3.141

I try with below java code at that time getting time out error all time 
I am working with proxy environment 
it's seems that doesn't working with  System.setProperty("java.net.useSystemProxies", "true");

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class ChromeDriver1 {

	public static void main(String[] args) {
	System.setProperty("java.net.useSystemProxies", "true");
		
		System.setProperty("webdriver.chrome.driver", "driver Path\\chromedriver.exe");
		ChromeOptions options = new ChromeOptions();
		DesiredCapabilities capabilities = new DesiredCapabilities ();
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
                options.merge(capabilities);
		WebDriver driver= new ChromeDriver(options);

		driver.get("http://www.google.com");

		driver.manage().window().maximize();
		driver.quit();
		 
		}
}

Error:-
Starting ChromeDriver 2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1) on port 19131
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'CIPL-6PC77', ip: '192.168.100.55', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_73'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at ChromeDriver1.main(ChromeDriver1.java:27)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:19131/status] to be available after 20107 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187)
	... 9 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 10 more

**Comment by virenv** [comment]
@HardiPatel1501 : Do you have a default proxy setup on your machine?

**Comment by HardiPatel1501** [comment]
Yes i have setup proxy on my machine.

**Comment by virenv** [comment]
@HardiPatel1501 : Using your proxy are you able to hit http://localhost:19131/sessions after starting the webdriver?

**Comment by diemol** [comment]
Hi @HardiPatel1501,

We have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? When possible, please provide the information requested in the original template. Until then, we cannot continue.

In addition, the ChromeDriver version is not the adequate for the version of Chrome you report above:
```
Browser version: 73.0.3683.75
Browser Driver version: Chromdriver2.46
```
See http://chromedriver.chromium.org/downloads

Please update, and if the issue still persists, feel free to reopen and provide all the information requested in the template.
