### ISSUE TITLE
UnsupportedCommandException: mouseMoveTo  on Selenium 3.6.0 FF 55.0

### ISSUE THREAD

**Issue by saleethmohd** [SeleniumHQ/selenium#7039]
## 🐛 Bug Report

UnsupportedCommandException: mouseMoveTo  on Selenium 3.6.0 FF 55.0

I have tried with all combinations of Selenium version and FF Version

-Dsauce.selenium.version=3.6.0 -Dbrowser.version=55.0
-Dsauce.selenium.version=3.6.0 -Dbrowser.version=60.0
-Dsauce.selenium.version=3.5.3 -Dbrowser.version=55.0
-Dsauce.selenium.version=3.6.0 -Dbrowser.version=65.0 
-Dsauce.selenium.version=3.7.0 -Dbrowser.version=65.0
-Dsauce.selenium.version=3.8.0 -Dbrowser.version=65.0

I am getting same error for all the above combinations.
I tired with gecko version 0.18 and 0.23

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

SendKeys should work with Action

## Test script or set of commands reproducing this issue

        Actions builder = new Actions(pages.getCurrentPage().getDriver());
        WebElement element = pages.getCurrentPage().getElementByName(elementName);
        builder.sendKeys(element, text).perform();

org.openqa.selenium.UnsupportedCommandException: mouseMoveTo Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z' System info: host: 'WIN-SB3ER6JQ6ME', ip: '172.20.49.113', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_91' Driver info: driver.version: unknown Command duration or timeout: 0 milliseconds

org.openqa.selenium.UnsupportedCommandException: mouseMoveTo
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'WIN-SB3ER6JQ6ME', ip: '172.20.49.113', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_91'
Driver info: driver.version: unknown
Command duration or timeout: 0 milliseconds
	(reflection-construct)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.jbehave.web.selenium.RemoteWebDriverProvider$ScreenshootingRemoteWebDriver.execute(RemoteWebDriverProvider.java:134)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteMouse.mouseMove(RemoteMouse.java:89)
	at org.openqa.selenium.remote.RemoteMouse.moveIfNeeded(RemoteMouse.java:52)
	at org.openqa.selenium.remote.RemoteMouse.click(RemoteMouse.java:57)
	at org.openqa.selenium.interactions.internal.KeysRelatedAction.focusOnElement(KeysRelatedAction.java:49)
	at org.openqa.selenium.interactions.SendKeysAction.perform(SendKeysAction.java:51)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:36)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:641)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:594)

## Environment

OS:  Windows 10 
Browser: Firefox 
Browser version: 55.0
Browser Driver version: GeckoDriver 0.18
Language Bindings version: Java 1.8.0_91

**Comment by AutomatedTester** [comment]
you will need to upgrade.
