### ISSUE TITLE
./go build results in ClassNotFoundException: com.facebook.buck.cli.bootstrapper.filesystem.BuckFileSystemProvider

### ISSUE THREAD

**Issue by stoically** [SeleniumHQ/selenium#7053]
## 🐛 Bug Report

Trying to `./go build` results in an early `ClassNotFoundException: com.facebook.buck.cli.bootstrapper.filesystem.BuckFileSystemProvider` error using Java 8 and Java 10 on Ubuntu 18.04. Tested with latest master and tag selenium-3.141.59.

<details>
  <summary>Full trace for Java 8</summary>

```shell
$ ./go build --trace
Parsing cpp/build.desc
Parsing cpp/iedriverserver/build.desc
Parsing javascript/build.desc
Parsing javascript/atoms/build.desc
Parsing javascript/atoms/fragments/build.desc
Parsing javascript/chrome-driver/build.desc
Parsing javascript/watir-atoms/build.desc
Parsing javascript/android-atoms/build.desc
Parsing javascript/selenium-atoms/build.desc
Parsing javascript/ie-driver/build.desc
Parsing javascript/jsunit/build.desc
Parsing javascript/firefox-driver/build.desc
Parsing javascript/selenium-core/build.desc
Parsing javascript/node/build.desc
Parsing javascript/safari-driver/build.desc
Parsing javascript/remote/build.desc
Parsing javascript/webdriver/build.desc
Parsing javascript/webdriver/atoms/build.desc
Parsing javascript/webdriver/atoms/inject/build.desc
Parsing javascript/webdriver/atoms/fragments/build.desc
Parsing javascript/webdriver/atoms/fragments/inject/build.desc
Parsing py/build.desc
Parsing rb/build.desc
Parsing third_party/closure/build.desc
Parsing third_party/jruby/build.desc
Parsing third_party/firebug/build.desc
Parsing third_party/js/wgxpath/build.desc
Parsing third_party/js/sizzle/build.desc
** Invoke build (first_time)
** Invoke all (first_time)
** Invoke selenium-java (first_time)
** Invoke //java/client/src/org/openqa/selenium:selenium (first_time)
** Execute //java/client/src/org/openqa/selenium:selenium
./buckw kill
Downloading Buck. This may take some time
[==================================================]
./buckw build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium
Not using buckd because watchman isn't installed.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.Error: java.lang.ClassNotFoundException: com.facebook.buck.cli.bootstrapper.filesystem.BuckFileSystemProvider
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:141)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.access$100(FileSystems.java:102)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:111)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:109)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:109)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:103)
	at java.base/java.nio.file.FileSystems.getDefault(FileSystems.java:190)
	at java.base/java.io.File.toPath(File.java:2290)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1220)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:341)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:815)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.access$900(URLClassPath.java:701)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:760)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:753)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:752)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:727)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:495)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:478)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:477)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:446)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:312)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:697)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:650)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:547)
Caused by: java.lang.ClassNotFoundException: com.facebook.buck.cli.bootstrapper.filesystem.BuckFileSystemProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:131)
	... 36 more
Exception `RuntimeError' at /home/user/src/selenium/rake-tasks/buck.rb:52 - ./buckw build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
Exception `#<Class:#<RuntimeError:0x712e787e>>' at /home/user/src/selenium/rake-tasks/buck.rb:52 - ./buckw build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
Exception `#<Class:#<RuntimeError:0x712e787e>>' at /home/user/src/selenium/rake-tasks/buck.rb:52 - ./buckw build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
Exception `#<Class:#<RuntimeError:0x712e787e>>' at /home/user/src/selenium/rake-tasks/buck.rb:52 - ./buckw build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
Exception `#<Class:#<RuntimeError:0x712e787e>>' at /home/user/src/selenium/rake-tasks/buck.rb:52 - ./buckw build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
go aborted!
./buckw build --stamp-build=detect --deep //java/client/src/org/openqa/selenium:selenium failed with exit code: 1
/home/user/src/selenium/rake-tasks/buck.rb:52:in `block in buck_cmd'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/open3.rb:212:in `popen_run'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/open3.rb:102:in `popen3'
/home/user/src/selenium/rake-tasks/buck.rb:36:in `buck_cmd'
/home/user/src/selenium/rake-tasks/buck.rb:227:in `block in (root)'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
uri:classloader:/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
uri:classloader:/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
uri:classloader:/gems/rake-10.5.0/bin/rake:33:in `<main>'
org/jruby/RubyKernel.java:973:in `load'
uri:classloader:/META-INF/jruby.home/bin/rake:1:in `<main>'
Tasks: TOP => build => all => selenium-java => //java/client/src/org/openqa/selenium:selenium
```
</details>

## To Reproduce

`git clone https://github.com/SeleniumHQ/selenium.git`
`./go build`

## Expected behavior

Build completes without errors.

## Environment

OS: Ubuntu 18.04.2 LTS, Linux 4.15.0-46-generic x86_64
Python: 2.7.15rc1 (2.7.15~rc1-1)

Java 8:
- openjdk version "1.8.0_191"
- OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
- OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

Java 10:
- openjdk version "10.0.2" 2018-07-17
- OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
- OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

## Notes

If this is actually a problem with buck, I would appreciate pointers on how to narrow the issue down, so I can report it to them. Thanks!

**Comment by rapidroamer** [comment]
I see that the users of JDK11 have reported the same issue. Are you sure your java home and path are pointing to correct JdK. 

https://github.com/facebook/buck/issues/2037

**Comment by stoically** [comment]
You're right. buck seems to only run properly with Java 8 (which is also noted in their [prerequisites](https://buckbuild.com/setup/getting_started.html)) and I've only changed the path to Java 8 in the `go` file. Setting `export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64` did the trick. Thanks!
