### ISSUE TITLE
Unable to set window size in FireFox

### ISSUE THREAD

**Issue by GARMBoshouwers** [SeleniumHQ/selenium#7062]
## 🐛 Unable to set window size in FireFox

When trying to set the Window size in using intern with geckodriver on FireFox, an UnknownCommand error is generated.

## To Reproduce

Detailed steps to reproduce the behavior:

An HTML document is not needed.
Used Intern test case:

```
/* jshint browser: false, node: true, esnext: true */

const intern = require('intern').default;
const { registerSuite } = intern.getInterface('object');

registerSuite('test', {
	tests: {
		'test': function() {
			return this.remote
				.setWindowSize(400, 800)
			;
		},
	}
});
```

## Expected behavior

FireFox should open, resize to 400x800 and close again.

## Test script or set of commands reproducing this issue

Run this script using Intern 4.4.2

This returns the following error in Intern.

```
    UnknownCommand: [GET http://localhost:4444/wd/hub/session/6954a593-10a4-4052-9406-b671e625ccf8/window/rect] GET /session/6954a593-10a4-4052-9406-b671e625ccf8/window/rect
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'MVGUITESTER', ip: '192.168.129.174', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
    Driver info: driver.version: unknown
      at Server.get @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Server.ts:353:16
      at runRequest @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:132:10
      at common_1.Task.cancelled @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:164:42
      at new e @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\@theintern\common\index.js:16:5076
      at InitializedProxiedSession.Session._delegateToServer @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:110:11
      at InitializedProxiedSession.Session.serverGet @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:170:16
      at InitializedProxiedSession.Session.getWindowRect @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:811:16
      at getWindowPosition_1 @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:918:13
      at InitializedProxiedSession.Session.getWindowPosition @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:923:15
      at setWindowSize_1 @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Session.ts:708:13
      at Command._callSessionMethod @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Command.ts:733:11
      at Command.setWindowSize @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\src\Command.ts:1030:34
      at Test.test @ tests\functional\test.js:26:6
      @ ..\..\..\packages\tools\intern-4.4.2-mv0\src\lib\Test.ts:263:51
      @ ..\..\..\packages\tools\intern-4.4.2-mv0\node_modules\@theintern\common\index.js:16:7182
      @ anonymous
      at process._tickCallback @ internal\process\next_tick.js:160:7
```
This returns the following selenium log

[selenium_out.txt](https://github.com/SeleniumHQ/selenium/files/3013186/selenium_out.txt)

This was originally reported with geckodriver as [#1528](https://github.com/mozilla/geckodriver/issues/1528)

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 66.0
Browser Driver version: GeckoDriver 0.24.0
Language Bindings version: Node 9.3.0, JAVA 1.8.0_201 
Selenium Grid version (if applicable): 3.141.59 
Intern 4.4.2

**Comment by barancev** [comment]
Please report this issue to Intern project, or provide a reproduction scenario in vanilla Selenium to reopen the issue.
