### ISSUE TITLE
html runner -htmlSuite "*browser"  

### ISSUE THREAD

**Issue by TWIMMENSE** [SeleniumHQ/selenium#7113]
OS:Win10 1703
browser:IE 11  version:11.1387.15063.0

What can i set browser  
i want use IE
but it error
java -Dwebdriver.gecko.driver=C:\Circulationindustry\IEDriverServer.exe -jar C:\Circulationindustry\selenium-html-runner-3.141.59.jar -htmlSuite "*iexplore" "web address"  "C:\Circulation industry\A8\Suite1.html" "C:\Circulationindustry\A8"

error:
Test of browser failed: *iexplore
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html
        at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
        at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:134)
        at org.openqa.selenium.ie.InternetExplorerDriverService.access$000(InternetExplorerDriverService.java:35)
        at org.openqa.selenium.ie.InternetExplorerDriverService$Builder.findDefaultExecutable(InternetExplorerDriverService.java:175)
        at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
        at org.openqa.selenium.ie.InternetExplorerDriver.setupService(InternetExplorerDriver.java:281)
        at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:211)
        at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:150)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.createDriver(HTMLLauncher.java:303)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:106)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:253)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:281)

**Comment by jimevans** [comment]
You’ve set the property `webdriver.gecko.driver` instead of `webdriver.ie.driver`.

**Comment by TWIMMENSE** [comment]
i  fixed it
java -Dwebdriver.ie.driver=C:\Circulationindustry\IEDriverServer.exe -jar C:\Circulationindustry\selenium-html-runner-3.141.59.jar -htmlSuite "*iexplore" "web address"  "C:\Circulation industry\A8\Suite1.html" "C:\Circulationindustry\A8"

but  i have other error
 Test of browser failed: *iexplore
java.net.MalformedURLException: unknown protocol: c
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:186)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:107)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:253)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:281)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by TWIMMENSE** [comment]
i did  but nobody answer me
https://groups.google.com/d/msg/selenium-users/MZsqE6OAoec/XUJbJNk-CgAJ

**Comment by barancev** [comment]
Please be patient. Selenium is not a commercial project, support is provided by the community.

**Comment by TWIMMENSE** [comment]
document about html runner  is too few
i try to see the code  but i dont know why this error happen
[code](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/server/htmlrunner/HTMLLauncher.java) on 281~319

**Comment by TWIMMENSE** [comment]
I find  where error,
my path have a space
