### ISSUE TITLE
SessionNotCreatedError: Unable to create session error while launching Edge browser using Protractor

### ISSUE THREAD

**Issue by GalmaJ** [SeleniumHQ/selenium#7126]
I am unable to launch edge browser session using Protractor. 

**Below are the configuration details:**

OS : Windows 10
Version : 1809
Os build : 17763.437
Selenium version : 3.141.59
Protractor version : 5.4.2

**### Error log**

Unable to create session from {
  "desiredCapabilities": {
    "browserName": "MicrosoftEdge"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "MicrosoftEdge"
      }
    ]
  }
}
Build info: version: '3.141.59'
Driver info: driver.version: unknown
[15:32:48] E/launcher - SessionNotCreatedError: Unable to create session from {
  "desiredCapabilities": {
    "browserName": "MicrosoftEdge"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "MicrosoftEdge"
      }
    ]
  }
}
Build info: version: '3.141.59'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (user\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (user\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (user\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (user\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at createDriver (user\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (user\node_modules\selenium-webdriver\index.js:635:14)
    at Hosted.getNewDriver (user\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (user\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (user\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (user\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (user\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (user\node_modules\q\q.js:796:13)
    at user\node_modules\q\q.js:556:49
[15:32:48] E/launcher - Process exited with error code 199
 

I tried adding MicrosoftWebDriver.exe file to C:\Windows\System32 folder but still got the same error.

Does anyone have work around or solution for this issue?

**Comment by diemol** [comment]
Hi @GalmaJ,

Could you please report the issue to Protractor? https://github.com/angular/protractor. Or if you are able to reproduce it with the official Selenium bindings, feel free to open a new issue **filling out the whole template** please.
