### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException Unable to find a matching set of capabilities though provided

### ISSUE THREAD

**Issue by angeetong** [SeleniumHQ/selenium#7128]
I looked at other similiar postings about this, but there wasn't a solution that solved my issue.
Hoping by posting here I can get some guidance. Thanks for reviewing this issue.

I'm running 2 firefox windows tests, 2 firefox mac tests, 2 chrome windows tests,  and 2 chrome mac tests in parallel on both a windows node and a mac node on selenium grid at the same time with a mac hub. All tests passes except the 2 firefox mac tests. Sometimes 2 firefox mac tests will pass, but the 2 firefox windows tests would fail. Never will both 2 firefox mac tests and 2 firefox windows tests will pass at the same time. I am using the latest firefox driver, latest firefox browser version, latest selenium webdriver, and latest java 8 jdk. 

        org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'WINDOWSMACHINE', ip: 'xxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_212'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 3.38 seconds
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at base.TestBase.Setup(TestBase.java:136)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'WINDOWSMACHINE', ip: 'xxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_212'
Driver info: driver.version: unknown
remote stacktrace: 
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'A-MacBook-Pro.local', ip: '2606:6000:fccc:1e00:0:0:0:6%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_212'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.grid.session.remote.RemoteSession$Factory.performHandshake(RemoteSession.java:147)
	at org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply(ServicedSession.java:161)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:180)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:183)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:66)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Collections$2.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:69)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.DistinctOps$1$2.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Unknown Source)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames

    if(browser.contains("winfirefox"))
	{
					
			System.setProperty("webdriver.gecko.driver", 
                    ReadProperties.globalProp.getProperty("pcgeckodriver"));
			FirefoxOptions firefoxOptions = new FirefoxOptions();
			firefoxOptions.setCapability("platform", "WINDOWS");
			firefoxOptions.setCapability("browser", "firefox");
			firefoxOptions.setCapability("newCommandTimeout", 5000);
			firefoxOptions.setCapability(FirefoxDriver.MARIONETTE, true);

			whichNodeURL=winNodeURL;	
					
			try
			{
				driverThread.set(new RemoteWebDriver(new URL(whichNodeURL), firefoxOptions));
			} catch (MalformedURLException e) {
				e.printStackTrace();
			 }
					
			}
	else if(browser.contains("macfirefox"))
	{
			System.setProperty("webdriver.gecko.driver", 
                    ReadProperties.globalProp.getProperty("macgeckodriver"));
			FirefoxOptions macfirefoxOptions = new FirefoxOptions();
			macfirefoxOptions.setCapability("platform", "MAC");
			macfirefoxOptions.setCapability("browser", "firefox");
			macfirefoxOptions.setCapability("newCommandTimeout", 5000);
			macfirefoxOptions.setCapability(FirefoxDriver.MARIONETTE, true);
					
			whichNodeURL=macNodeURL;
					
			try
			{
				driverThread.set(new RemoteWebDriver(new URL(whichNodeURL), macfirefoxOptions));
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
					
			}

       <suite name="XOME Suite" parallel="tests" verbose="1" thread-count="2">

       <test name = "Mac Firefox Tests" preserve-order="true" group-by-instances="true">
       <parameter name="browser" value="macfirefox">
		<classes>
        	<class name="webTests.FilterMoreResultsByKeyword" />
        	<class name="webTests.FilterMoreResultsByYear" />
		</classes>
	</parameter>
	</test>
	<test name = "Win Firefox Tests" preserve-order="true" group-by-instances="true">
        <parameter name="browser" value="winfirefox">
		<classes>
        	<class name="webTests.FilterMoreResultsByKeyword" />
        	<class name="webTests.FilterMoreResultsByYear" />
		</classes>
	</parameter>
	</test>
	<test name = "Win Chrome Tests" preserve-order="true" group-by-instances="true">
         <parameter name="browser" value="winchrome">
		<classes>
        	<class name="webTests.FilterMoreResultsByKeyword" />
        	<class name="webTests.FilterMoreResultsByYear" />
		</classes>
	</parameter>
	</test>
	<test name = "Mac Chrome Tests" preserve-order="true" group-by-instances="true">
        <parameter name="browser" value="macchrome">
		<classes>
        	<class name="webTests.FilterMoreResultsByKeyword" />
                 <class name="webTests.FilterMoreResultsByYear" />
		</classes>
	</parameter>
	</test>
        </suite>
            
                  ` {
                         "capabilities":
                           [
                    {
                           "browserName": "firefox",
                           "marionette": true,
                           "maxInstances": 2,
                          "browser-version": "66.0.3",
                          "platform": "MAC",
                         "seleniumProtocol": "WebDriver"
                    },
                   {
                         "browserName": "chrome",
                         "maxInstances": 2,
                        "browser-version": "73.0.3683",
                        "platform": "MAC",
                        "seleniumProtocol": "WebDriver"
                   },
                   {
                         "browserName": "safari",
                          "technologyPreview": false,
                          "platform": "MAC",
                          "maxInstances": 1,
                         "seleniumProtocol": "WebDriver"
                        }
                     ],
                  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
                  "maxSession": 2,
                  "port": 5555,
                  "register": true,
                  "registerCycle": 5000,
                  "hub": "http://xxxxxxx:4444",
                 "nodeStatusCheckTimeout": 5000,
                 "nodePolling": 5000,
                 "role": "node",
                 "cleanUpCycle": 5000,
                 "timeout": 5000,
                 "unregisterIfStillDownAfter": 60000,
                "downPollingLimit": 2,
                "debug": false,
                "servlets" : [],
               "withoutServlets": [],
               "custom": {}
                }`
                   
  
      

           `

**Comment by angeetong** [comment]
By adding the binary path of Firefox browser and also adding the path of all the browser drivers to the path variable in environment variables in windows this error is no longer seen. Closing issue. 
firefoxOptions.setBinary("C:\\Program Files\\Mozilla Firefox\\firefox.exe");					macfirefoxOptions.setBinary("/Applications/Firefox.app/Contents/MacOS/firefox-bin");
