### ISSUE TITLE
Selenium WebDriver issue in Eclipse IDE 

### ISSUE THREAD

**Issue by Jeffrey93** [SeleniumHQ/selenium#7153]
Hello,

I'm trying to perform a test using BDD for Iseries and until last Friday everything was working fine but, currently, it's impossible to run any test on eclipse.

Every time I try to execute a Runner I have got this message:

### Trace:

java.lang.NoClassDefFoundError: org/openqa/selenium/internal/WrapsElement
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getDeclaredMethods(Unknown Source)
	at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:766)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:683)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:182)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:661)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:617)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:603)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:932)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:852)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:291)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:222)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:938)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at net.thucydides.core.guice.Injectors.getInjector(Injectors.java:27)
	at net.serenitybdd.core.di.WebDriverInjectors.getInjector(WebDriverInjectors.java:10)
	at net.thucydides.core.webdriver.WebDriverFactory.<init>(WebDriverFactory.java:63)
	at net.thucydides.core.webdriver.WebDriverFactory.<init>(WebDriverFactory.java:57)
	at net.thucydides.core.webdriver.WebdriverProxyFactory.<init>(WebdriverProxyFactory.java:31)
	at net.thucydides.core.webdriver.WebdriverProxyFactory.getFactory(WebdriverProxyFactory.java:37)
	at net.thucydides.core.steps.BaseStepListener.<init>(BaseStepListener.java:235)
	at net.thucydides.core.steps.BaseStepListener.<init>(BaseStepListener.java:231)
	at net.thucydides.core.steps.Listeners$BaseStepListenerBuilder.withOutputDirectory(Listeners.java:37)
	at net.serenitybdd.core.SerenityListeners.<init>(SerenityListeners.java:30)
	at cucumber.runtime.formatter.SerenityReporter.initialiseThucydidesListenersFor(SerenityReporter.java:120)
	at cucumber.runtime.formatter.SerenityReporter.lambda$handleTestSourceRead$8(SerenityReporter.java:168)
	at java.util.Optional.ifPresent(Unknown Source)
	at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:165)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$0(SerenityReporter.java:124)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:132)
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:315)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:81)
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:525)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.WrapsElement
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 83 more

### Dependencies: 

dependencies {
	///////////////////////////////////////////////////////////////////////////
	/////////LOCAL DEPENDENCIES////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////
	compile name: 'sqljdbc4'
	compile name: 'ojdbc6'
   	compile name:  'sikulixapi'
   	//Librerias POI manipular Excel
   	compile name:  'librerias poi/commons-collections4-4.1'
   	compile name:  'librerias poi/jxl'
   	compile name:  'librerias poi/poi-3.16'
   	compile name:  'librerias poi/poi-ooxml-3.16'
   	compile name:  'librerias poi/poi-ooxml-schemas-3.16'
   	compile name:  'librerias poi/xmlbeans-2.6.0'
   
   	///////////////////////////////////////////////////////////////////////////
	/////////REMOTE DEPENDENCIES///////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////
	compile group: 'commons-collections', name: 'commons-collections', version: '3.2'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.1'
    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.141.59'
    compile group: 'org.seleniumhq.selenium', name: 'selenium-api', version: '3.141.59'
    compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version: '3.141.59'
    compile group: 'org.apache.axis', name: 'axis', version: '1.4'
    compile group: 'com.sixdimensions.commons.osgi.wrapper', name: 'jaxrpc-api', version: '1.1'
    compile group: 'com.github.detro.ghostdriver', name: 'phantomjsdriver', version: '1.0.1'
	compile group: 'org.apache.poi', name: 'poi', version: '3.15'
	compile group: 'org.apache.poi', name: 'poi-ooxml', version: '3.15'
	compile group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1'
	compile group: 'commons-discovery', name: 'commons-discovery', version: '0.5'
	compile group: 'javax.activation', name: 'activation', version: '1.1'
	compile group: 'javax.mail', name: 'mail', version: '1.4'
	compile group: 'com.jcraft', name: 'jsch', version: '0.1.54'
	compile group: 'net.serenity-bdd', name: 'serenity-core', version: '2.0.48'
    compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '2.0.48'
    compile group: 'net.serenity-bdd', name: 'serenity-cucumber', version: '1.9.37'
   // compile group: 'org.jvnet.com4j', name: 'com4j', version: '2.1'
    // https://mvnrepository.com/artifact/com.googlecode.javacv/javacv
	compile group: 'com.googlecode.javacv', name: 'javacv', version: '0.1' 
	testCompile group: 'org.assertj', name: 'assertj-core', version: '3.8.0'
  	testCompile group: 'org.hamcrest', name: 'hamcrest-all', version: '1.3'  
    testCompile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.25'
    testCompile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
    testCompile('junit:junit:4.12')
     compile group: 'net.sf.jt400', name: 'jt400', version: '6.6'
       //Java Mail
   compile group: 'javax.mail', name: 'mail', version: '1.5.0-b01'
   compile group: 'javax.activation', name: 'activation', version: '1.1.1'
   compile group: 'org.apache.poi', name: 'poi', version: '3.15'
   compile group: 'org.apache.poi', name: 'poi-ooxml', version: '3.15' 
   compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.25'
   compile 'com.opencsv:opencsv:4.3.2'
	   //Lib Drools

   compile group: 'org.drools', name: 'drools-core', version: '7.14.0.Final'
   compile group: 'org.jvnet.com4j', name: 'com4j', version: '2.1'
   
   
  
   
   	   

}

OS: <Windows 10>
Selenium version: <3.141.59>

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
