### ISSUE TITLE
autoreload  of cryptography.hazmat.bindings on profile created with profile manager

### ISSUE THREAD

**Issue by jramirezpr** [SeleniumHQ/selenium#7154]
When i run this code:
```
fp =webdriver.FirefoxProfile(r'C:\Users\Guest\AppData\Roaming\Mozilla\Firefox\Profiles\3mzqjk97.profileDouble')

driver = webdriver.Firefox(fp)
driver.get(url)
```

I get this message:
```
[autoreload of cryptography.hazmat.bindings.openssl.binding failed: Traceback (most recent call last):
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\site-packages\IPython\extensions\autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\site-packages\IPython\extensions\autoreload.py", line 378, in superreload
    module = reload(module)
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 188, in <module>
    _verify_package_version(cryptography.__version__)
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 175, in _verify_package_version
    so_package_version = ffi.string(lib.CRYPTOGRAPHY_PACKAGE_VERSION)
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'CRYPTOGRAPHY_PACKAGE_VERSION'
]
[autoreload of cryptography.hazmat.backends.openssl.backend failed: Traceback (most recent call last):
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\site-packages\IPython\extensions\autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\site-packages\IPython\extensions\autoreload.py", line 378, in superreload
    module = reload(module)
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 2419, in <module>
    backend = Backend()
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 119, in __init__
    self.activate_osrandom_engine()
  File "C:\Users\Guest\Anaconda3newFolder\envs\googleadsEnv\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 160, in activate_osrandom_engine
    if self._lib.Cryptography_HAS_ENGINE:
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_ENGINE'
]
```
The website has a user/password entry, but this message appears before the driver loads, and then it doesn't use my stored values for these entries.

**Comment by cgoldberg** [comment]
please don't ignore the template when filing new issues.
