### ISSUE TITLE
[Ruby] Unable to init chromedriver in 4.0.0.alpha1 version

### ISSUE THREAD

**Issue by prashanth-sams** [SeleniumHQ/selenium#7161]
## Steps To Reproduce
```
comparison of Integer with :warn failed (ArgumentError)
```
![](https://i.imgur.com/JhGgyYb.png)

## Test script
```
@driver = Selenium::WebDriver.for :chrome
```
or
```
caps = Selenium::WebDriver::Remote::Capabilities.chrome("chromeOptions" => {"args" => [ "disable-infobars" ]})
@driver = Selenium::WebDriver.for :chrome, desired_capabilities: caps
```

## Environment

OS: 
Browser: Chrome
Browser version: Version 73.0.3683.86 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 2.45.615355 
Language Bindings version: selenium-webdriver 4.0.0.alpha1

**Comment by lmtierney** [comment]
What happens if you use a `w3c`-compliant key for `chromeOptions`? Chromedriver expects `goog:chromeOptions` instead of `chromeOptions` for `w3c`

**Comment by lmtierney** [comment]
Also, you need to update your ChromeDriver. `2.45` is not compatible with Chrome `73`. You should upgrade to ChromeDriver `73` per their recommendation http://chromedriver.chromium.org/downloads

**Comment by prashanth-sams** [comment]
@lmtierney I upgraded my chromedriver to 75 and using Google Chrome version 73; still the same issue

![image](https://user-images.githubusercontent.com/2948696/57065530-c547d400-6cda-11e9-881a-ed7b1d35b19d.png)

**Comment by prashanth-sams** [comment]
> What happens if you use a `w3c`-compliant key for `chromeOptions`? Chromedriver expects `goog:chromeOptions` instead of `chromeOptions` for `w3c`

Let me try this; but, I read the article saying this is for the older browser versions

**Comment by p0deje** [comment]
What Ruby version do you use?

**Comment by prashanth-sams** [comment]
@p0deje 
**Ruby version:** ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]

```
comparison of Integer with :warn failed (ArgumentError)
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/logger-1.2.7.1/lib/logger.rb:326:in `<'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/logger-1.2.7.1/lib/logger.rb:326:in `add'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/logger-1.2.7.1/lib/logger.rb:360:in `debug'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/service.rb:125:in `build_process'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/service.rb:151:in `start_process'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/service.rb:92:in `block in start'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/service.rb:90:in `start'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/driver.rb:301:in `service_url'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/chrome/driver.rb:39:in `initialize'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/driver.rb:46:in `new'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/driver.rb:46:in `for'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver.rb:86:in `for'
 /Users/prashanthrajjapa/Documents/pf-quality/pf-website/features/support/driver_config.rb:112:in `launch_driver_chrome'
 /Users/prashanthrajjapa/Documents/pf-quality/pf-website/features/support/hooks.rb:100:in `block in <top (required)>'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in `instance_exec'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in `block in cucumber_instance_exec_in'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:54:in `cucumber_run_with_backtrace_filtering'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:27:in `cucumber_instance_exec_in'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/hook.rb:21:in `invoke'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/runtime/before_hooks.rb:23:in `block (2 levels) in before_hooks'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/action.rb:24:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/step.rb:32:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:104:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:51:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:27:in `test_step'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/step.rb:17:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:28:in `block (3 levels) in describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:27:in `each'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:27:in `block (2 levels) in describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/around_hook.rb:17:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:104:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:51:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:34:in `around_hook'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:120:in `block (2 levels) in compose_around_hooks'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:121:in `compose_around_hooks'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:26:in `block in describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:19:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:57:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/retry.rb:18:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/quit.rb:12:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/broadcast_test_run_started_event.rb:21:in `block in done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `map'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/filters/locations_filter.rb:20:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/compiler.rb:24:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/parser.rb:39:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:32:in `parse'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:21:in `compile'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:75:in `run!'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/cli/main.rb:34:in `execute!'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/bin/cucumber:9:in `<top (required)>'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/bin/cucumber:23:in `load'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/bin/cucumber:23:in `<main>'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
```
```
Traceback (most recent call last):
	2: from /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/platform.rb:150:in `block in exit_hook'
	1: from /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/service.rb:101:in `stop
```

**Comment by prashanth-sams** [comment]
@p0deje it's the same after updating the chromedriver to 73 and Google chrome to 73

**Comment by p0deje** [comment]
I find it strange in your stacktrace a presence of `logger` gem, which is a part of Ruby stdlib for a long time. Can you try removing `logger` gem from your gems and see if it helps?

**Comment by prashanth-sams** [comment]
@p0deje it's this `no sessionId in returned payload (Selenium::WebDriver::Error::WebDriverError)`

```
no sessionId in returned payload (Selenium::WebDriver::Error::WebDriverError)
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/remote/bridge.rb:70:in `create_session'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/chrome/driver.rb:46:in `initialize'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/driver.rb:46:in `new'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver/common/driver.rb:46:in `for'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-4.0.0.alpha1/lib/selenium/webdriver.rb:86:in `for'
 /Users/prashanthrajjapa/Documents/pf-quality/pf-website/features/support/driver_config.rb:112:in `launch_driver_chrome'
 /Users/prashanthrajjapa/Documents/pf-quality/pf-website/features/support/hooks.rb:100:in `block in <top (required)>'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in `instance_exec'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in `block in cucumber_instance_exec_in'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:54:in `cucumber_run_with_backtrace_filtering'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:27:in `cucumber_instance_exec_in'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/glue/hook.rb:21:in `invoke'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/runtime/before_hooks.rb:23:in `block (2 levels) in before_hooks'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/action.rb:24:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/step.rb:32:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:104:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:51:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:27:in `test_step'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/step.rb:17:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:28:in `block (3 levels) in describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:27:in `each'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:27:in `block (2 levels) in describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/around_hook.rb:17:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:104:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:51:in `execute'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:34:in `around_hook'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:120:in `block (2 levels) in compose_around_hooks'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:121:in `compose_around_hooks'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:26:in `block in describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:19:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:57:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/retry.rb:18:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/quit.rb:12:in `test_case'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/broadcast_test_run_started_event.rb:21:in `block in done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `map'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/filters/locations_filter.rb:20:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/compiler.rb:24:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/parser.rb:39:in `done'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:32:in `parse'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:21:in `compile'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:75:in `run!'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/cli/main.rb:34:in `execute!'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/bin/cucumber:9:in `<top (required)>'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/bin/cucumber:23:in `load'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/bin/cucumber:23:in `<main>'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by lmtierney** [comment]
That part isn't unusual, https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/chrome/driver.rb#L44

**Comment by lmtierney** [comment]
Can you turn the selenium logger on `:debug` so we can see the actual traffic?

    Selenium::WebDriver.logger.level = :debug

**Comment by lmtierney** [comment]
My guess is that it's complaining about your mismatched chrome and chromedriver. For chrome 73 you should be using chromedriver 73 not 75

**Comment by prashanth-sams** [comment]
@lmtierney currently, I switched to this combination; I got the above errors after that
```
If you are using Chrome version 73, please download ChromeDriver 73.0.3683.68
```

**Comment by lmtierney** [comment]
@prashanth-sams sorry I missed that part of the thread. It'd be most helpful if we get the actual error message back from chromedriver though

**Comment by lmtierney** [comment]
Ok I finally got my env setup using 74 and 74 and am seeing the same as @prashanth-sams with chromedriver giving me this:

```
2019-05-02 07:25:33 INFO Selenium -> POST session
2019-05-02 07:25:33 INFO Selenium    >>> http://127.0.0.1:9516/session | {"capabilities":{"firstMatch":[{"browserName":"chrome"}]}}
2019-05-02 07:25:33 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.0.0.alpha2 (ruby macosx)", "Content-Length"=>"58"}
2019-05-02 07:25:33 INFO Selenium <- {"sessionId":"ab511aab88b5beb8f86671aa40bdc9f6","status":33,"value":{"message":"session not created: Missing or invalid capabilities\n  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.14.4 x86_64)"}}
```

We'll have to look into this

**Comment by lmtierney** [comment]
Or, a more preferred way:

    opts = Selenium::WebDriver::Chrome::Options.new(options: {w3c: true})
    driver = Selenium::WebDriver.for(:chrome, options: opts)

**Comment by prashanth-sams** [comment]
@lmtierney this works for me; I see @p0deje comment's on this, `It will be a default one in Chrome 75+`. Thank you!

**Comment by prashanth-sams** [comment]
we can use some explicit warning message for the users to force them to use chrome-options if the browser version is below 75

**Comment by lmtierney** [comment]
The intention is for the stable release of `4.0.0` to come after Chrome `75` is the stable release.

Closing as issue is resolved.

**Comment by prashanth-sams** [comment]
@lmtierney @p0deje Is there a workaround that we could use `logger` library? or it is not allowed to use it along with the selenium4?

**Comment by prashanth-sams** [comment]
```
 comparison of Integer with :warn failed (ArgumentError)
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/logger-1.2.7.1/lib/logger.rb:326:in `<'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/logger-1.2.7.1/lib/logger.rb:326:in `add'
 /Users/prashanthrajjapa/.rvm/gems/ruby-2.5.1/gems/logger-1.2.7.1/lib/logger.rb:360:in `debug'
```

**Comment by titusfortner** [comment]
I do think we should rescue the session not created error and return a better error for this. People will still want to run tests with chrome < 75. Another option is to always turn on w3c true.

**Comment by p0deje** [comment]
> @lmtierney @p0deje Is there a workaround that we could use logger library? or it is not allowed to use it along with the selenium4?

Is there any reason for you to use `logger` gem? You can just use stdlib logger: https://ruby-doc.org/stdlib-2.4.0/libdoc/logger/rdoc/Logger.html
