### ISSUE TITLE
Path too long exception

### ISSUE THREAD

**Issue by mshot** [SeleniumHQ/selenium#7181]
## 🐛 Bug Report

Starting **FirefoxDriver** with **FirefoxProfile** leads to **Exception**: 

> The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

Catch: this is behavior for Windows User "Administrator", with shorter user name like "xxxxx" there is no such exception observed.

This behavior most likely depends on profile used - there are some addons installed (+-15) - 
IMHO issue is that method _OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)_  **doesn't expect long paths** - If LOCAL TEMP folder + anonymous.GUID.webdriver-profile folder from selenium + folder structure inside firefox profile are beyond the limit then Exception emerge. 

_(In another project i use ZetaLongPaths to deal with such behavior, also .net 4.6.2+ seems to support long paths)_

**Stack Trace**
 ```
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.DirectoryInfo.Create()
   at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
   at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
   at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
   at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
   at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
   at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
   at OpenQA.Selenium.Internal.FileUtilities.CopyDirectory(String sourceDirectory, String destinationDirectory)
   at OpenQA.Selenium.Firefox.FirefoxProfile.WriteToDisk()
   at OpenQA.Selenium.Firefox.FirefoxProfile.ToBase64String()
   at OpenQA.Selenium.Firefox.FirefoxOptions.GenerateFirefoxOptionsDictionary()
   at OpenQA.Selenium.Firefox.FirefoxOptions.ToCapabilities()
   at OpenQA.Selenium.Firefox.FirefoxDriver.ConvertOptionsToCapabilities(FirefoxOptions options)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
 ```
## To Reproduce
with long enough user name + TEMP PATH + FF profile (in my case Ghostery addon have long inner folder path)
```
FirefoxProfile _FirefoxProfile = new FirefoxProfile(SeleniumFirefoxProfileDirectory); //"C:\\Temp\\FirefoxProfiles\\p2"
FirefoxDriverService driverService = FirefoxDriverService.CreateDefaultService();
FirefoxOptions options = new FirefoxOptions();
options.Profile = _FirefoxProfile;

IWebDriver driver = new FirefoxDriver(driverService,options,TimeSpan.FromMinutes(3));
```

Detailed steps to reproduce the behavior:

## Expected behavior

I would expect browser started with custom profile. 

## Test script or set of commands reproducing this issue

---

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 66.0.4
Browser Driver version: GeckoDriver 0.24
Language Bindings version: C# 4.0.0 alpha 
Selenium Grid version (if applicable):

**Comment by pss904** [comment]
I don't believe this is a Selenium issue so much as a Windows issue. Windows has a max path length of 260 characters, which is now editable. Perhaps check https://mspoweruser.com/ntfs-260-character-windows-10/

**Comment by mshot** [comment]
> I don't believe this is a Selenium issue so much as a Windows issue. Windows has a max path length of 260 characters, which is now editable. Perhaps check https://mspoweruser.com/ntfs-260-character-windows-10/

but selenium is using long temporally path's - 

original profile is stored at 
`c:\Users\Administrator\AppData\Roaming\Mozilla\Firefox\Profiles\p0\`
*_in my case we distribute them to_
`C:\Temp\FirefoxProfiles\p0`
geckodriver have them in 
`c:\Users\Administrator\AppData\Local\Temp\rust_mozprofile.gdyYxzkP3zoi`
but selenium temp folder is longest from them
`c:\Users\Administrator\AppData\Local\Temp\anonymous.0f8fad5b-d9cb-469f-a165-70867728950e.webdriver-profile`

that makes **36 character difference** which is exceeding the limit IMHO
is it possible to skip copy to temporal folder (example - copy only from `C:\Temp\FirefoxProfiles\p0` to `c:\Users\Administrator\AppData\Local\Temp\rust_mozprofile.gdyYxzkP3zoi`) ?

**Comment by mshot** [comment]
is there any issue with direct copy?

**Comment by diemol** [comment]
@mshot could you update the status of this with the most recent release? If this is still happening, can you please provide a GitHub repo we can clone and reproduce this on Windows 10 or 11?

**Comment by titusfortner** [comment]
Mozilla is encouraging people to move away from using Firefox Profiles with Selenium entirely, and use the prefs and args as supported by geckodriver. Also, you can add the extension via methods after you've started the driver, which was the root cause of this error. The auto-generated UUID is the right way to create unique folder names.
