### ISSUE TITLE
Sporadic (InvalidSelectorException) type error thrown: TypeError: Failed to execute 'createNSResolver' on 'Document': parameter 1 is not of type 'Node'

### ISSUE THREAD

**Issue by irileydev** [SeleniumHQ/selenium#719]
Environment
===========
Selenium Standalone Server: 2.46.0
Selenium Client (Java): 2.46.0
Browsers: Firefox 38.0.5, Chrome 43.0.2357.130 m (high probability of occurring), IE 11

Issue
=======
When trying to execute xpath locators (specifically those using the contains() method), we are seeing a sporadic InvalidSelectorException ...
TypeError: Failed to execute 'createNSResolver' on 'Document': parameter 1 is not of type 'Node' being thrown at the very onset of the test -- I'd say 1 out of every 5 runs. A quick restart of the test, and the exception magically goes away.

The stack trace is as follows:
org.openqa.selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression //label[contains(text(), 'SOP Hub')] because of the following error:
TypeError: Failed to execute 'createNSResolver' on 'Document': parameter 1 is not of type 'Node'.
  (Session info: chrome=43.0.2357.130)
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.26 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'NY12LP517735', ip: '165.181.224.155', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\ISAAC~1.RIL\AppData\Local\Temp\scoped_dir9056_16605}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=43.0.2357.130, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: bf09f86741c93e3efb5f7bb68567bf77
*** Element info: {Using=xpath, value=//label[contains(text(), 'SOP Hub')]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:455)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at com.automatedTesting.pageObjects.BasePage.highlightWidget(BasePage.java:535)
	at com.automatedTesting.pageObjects.BasePage.assertWidgetText(BasePage.java:202)
	at com.automatedTesting.pageObjects.ViewSOPListPage.waitForViewListSOP_PageToLoad(ViewSOPListPage.java:330)
	at com.automatedTesting.testcases.regressionTestSuite.AdvancedSearchTest_TC248393.getToAdvancedSrchPage(AdvancedSearchTest_TC248393.java:32)
	at com.automatedTesting.testcases.regressionTestSuite.AdvancedSearchTest_TC248393.assertWidgetsPresence(AdvancedSearchTest_TC248393.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by lukeis** [comment]
please provide a reproducible test case for us, also if that exception is only happening in Chrome, then please log a bug (with reproducible test case) in the [chromedriver project](https://code.google.com/p/chromedriver/)

we can reopen the issue when we have a way to reproduce this.

**Comment by abioneperhobby** [comment]
i have the same sporadic problem after moving on chrome

> InvalidSelectorException: Message: invalid selector: Unable to locate an element with the xpath expression //*[contains(., 'results for "player"')] because of the following error:
> TypeError: Failed to execute 'createNSResolver' on 'Document': parameter 1 is not of type 'Node'.
> 

i'm not able too as @irileydev to give a way to reproduce, otherwise it will not be sporadic.

i'm on

Session info: chrome=51.0.2704.106)
(Driver info: chromedriver=2.9.248304,platform=Linux 3.16.0-38-generic x86_64
selenium (2.53.6)

**Comment by abioneperhobby** [comment]
solved upgrading to ChromeDriver 2.25.426924
