### ISSUE TITLE
[Firefox] OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL timed out

### ISSUE THREAD

**Issue by meanthadar-p** [SeleniumHQ/selenium#7218]
I tried to execute my code by using remote driver and environment is 
> Selenium version 3.141
> Firefox 66.0.5
> Gecko driver 0.24

**Initialize Firefox Driver:**
```
FirefoxProfile firefoxProfile = new FirefoxProfile("C:\Profiles\Firefox_TravelOPB");
JavaScriptError.AddExtension(firefoxProfile);
firefoxProfile.SetPreference("general.useragent.override", GetUserAgent());
firefoxProfile.Clean();
firefoxProfile.DeleteAfterUse = true;

FirefoxOptions firefoxOption = new FirefoxOptions();
firefoxOption.Profile = firefoxProfile;
firefoxOption.Proxy =  GetProxy();

driver = new RemoteWebDriver(new Uri("http://127.0.0.1:4444/wd/hub"), firefoxOption);
```

**GetProxy function is below:**

```
private Proxy GetProxy()
{
 string proxyText = Settings.Instance.GetBrowserProxy();
 Proxy proxy = new Proxy
{
   HttpProxy = proxyText,
   SslProxy = proxyText,
   FtpProxy = proxyText,
   SocksProxy = proxyText
};

string noproxyText = Settings.Instance.GetBrowserNoProxy();
string browserName = Settings.Instance.GetBrowser().ToLower();
proxy.NoProxy = "localhost, 127.0.0.1" + (string.IsNullOrWhiteSpace(noproxyText) ? string.Empty : ", " + noproxyText);
return proxy;
}
```

**But I found error message as a following:**

```
OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4444/wd/hub/session timed out after 60 seconds.
  ----> System.Net.WebException : The operation has timed out
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary 2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
```

**_Could you please suggest any solution to fix it?_**

**Comment by meanthadar-p** [comment]
Now, I found solution to fix it

Because I use "SetEnvironmentVariable" to call geckodriver.exe in localhost's folder but its version isn't update, it's 0.11.1 not 0.24.0 

It's look like joke but I can't run another process because this issue since last two week lol.

if anyone got this problem, I wish my exp will help you.
