### ISSUE TITLE
FirefoxDriver throws exception "access to the path 'chrome.manifest' is denied" when install custom plugins

### ISSUE THREAD

**Issue by oleksiizozulenko** [SeleniumHQ/selenium#722]
When I want to install my custom plugin into firefox
Then FirefoxDriver throws exception: Access to the path 'chrome.manifest' is denied.
System.UnauthorizedAccessException was caught
  HResult=-2147024891
  Message=Access to the path 'chrome.manifest' is denied.
  Source=mscorlib
  StackTrace:
       at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
       at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
       at OpenQA.Selenium.Firefox.FirefoxExtension.Install(String profileDir)
       at OpenQA.Selenium.Firefox.FirefoxProfile.InstallExtensions()
       at OpenQA.Selenium.Firefox.FirefoxProfile.WriteToDisk()
       at OpenQA.Selenium.Firefox.FirefoxDriverServer.Start()
       at OpenQA.Selenium.Firefox.FirefoxDriverCommandExecutor.Execute(Command commandToExecute)
       at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
       at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
       at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile, ICapabilities capabilities, TimeSpan commandTimeout)
       at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxBinary binary, FirefoxProfile profile, TimeSpan commandTimeout)

Environenment: 
Selenium: 2.46
Firefox: 31ESR

Where error can not reproduce: 
Selenium 2.45
Firefox 31ESR

 Possible solution in method FirefoxExtension.Install replace all calls Directory.Delete to FileUtilities.DeleteDirectory

**Comment by jimevans** [comment]
Changed in 4680a96
