### ISSUE TITLE
SELENIUM 3.141.59 with FF 67.0.1 and GECKO driver 0.24

### ISSUE THREAD

**Issue by atchuth23** [SeleniumHQ/selenium#7274]
## 🐛 Bug Report

Runnin selenium as Windows service via nssm and the remotewebdriver is intiated and the connection is refused.

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

I want the remote session in the nssm to open a valida firefox session and execute the test.

## Test script or set of commands reproducing this issue

	    public static void main(String[] args) throws MalformedURLException, InterruptedException {
	    	System.setProperty("webdriver.gecko.driver","C:\\Users\\Administrator\\Downloads\\geckodriver-v0.24.0-win64\\geckodriver.exe");
	    	WebDriver driver = new FirefoxDriver();
	    	
	    	FirefoxOptions firefoxOptions = new FirefoxOptions();
	    	firefoxOptions.setAcceptInsecureCerts(true);
	    	firefoxOptions.setLogLevel(FirefoxDriverLogLevel.TRACE);
	    	FirefoxDriver firefoxDriver = new FirefoxDriver(firefoxOptions);
		    
	    	 driver = new RemoteWebDriver(new URL("http://localhost:5566"), firefoxOptions);
	    	    driver.navigate().to("http://www.yahoo.com");
	    		    	driver.get("https://www.google.com");
	    	driver.close();
	    	driver.quit();
	    }
        

## Environment

OS: <-- Windows 10 Windows 7 Windows server2012 -->
Browser: <- Firefox -->
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by atchuth23** [comment]
1560100055200	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\rust_mozprofile.uEtkDBmlu5jv"
1560100057976	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1560100057979	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1560100057979	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1560100063267	Marionette	INFO	Listening on port 62126
1560100063355	Marionette	WARN	TLS certificate errors will be ignored for this session
Jun 09, 2019 10:37:43 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1560100064216	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\rust_mozprofile.nqSRh5yCk198"
1560100064240	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:62153
1560100065565	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1560100065566	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1560100065566	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1560100065731	Marionette	TRACE	Received observer notification profile-after-change
1560100065852	Marionette	TRACE	Received observer notification toplevel-window-ready
1560100065925	Marionette	TRACE	Received observer notification command-line-startup
1560100065925	Marionette	TRACE	Received observer notification nsPref:changed
1560100065926	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1560100066283	Marionette	TRACE	Received observer notification toplevel-window-ready
1560100069300	Marionette	TRACE	Received observer notification marionette-startup-requested
1560100069300	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1560100069304	Marionette	TRACE	All scripts recorded.
1560100069304	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1560100069305	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1560100069305	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1560100069305	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1560100069306	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1560100069306	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1560100069306	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1560100069307	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1560100069307	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1560100069307	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1560100069307	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1560100069308	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1560100069308	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1560100069308	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1560100069308	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1560100069308	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1560100069309	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1560100069309	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1560100069309	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1560100069310	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1560100069310	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1560100069310	Marionette	DEBUG	Setting recommended pref security.certerrors.mitm.priming.enabled to false
1560100069310	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1560100069310	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1560100069310	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1560100069310	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1560100069310	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1560100069360	Marionette	INFO	Listening on port 62153
1560100069360	Marionette	DEBUG	Remote service is active
1560100069486	geckodriver::marionette	DEBUG	Connection established on 127.0.0.1:62153. Waiting for Marionette handshake
1560100069506	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:62169
1560100069517	geckodriver::marionette	DEBUG	Connected to Marionette
1560100069527	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1560100069527	Marionette	WARN	TLS certificate errors will be ignored for this session
1560100069572	Marionette	TRACE	[6442450945] Frame script loaded
1560100069611	Marionette	TRACE	[6442450945] Frame script registered
1560100069614	Marionette	DEBUG	0 <- [1,1,null,{"sessionId":"5108c3d1-80a4-4472-ae34-7dde01fad653","capabilities":{"browserName":"firefox","browserVersion":"67.0. ... ozprofile.nqSRh5yCk198","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1560100069611	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"5108c3d1-80a4-4472-ae34-7dde01fad653","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"67.0.1","moz:accessibilityChecks":false,"moz:buildID":"20190529130856","moz:geckodriverVersion":"0.24.0","moz:headless":false,"moz:processID":7244,"moz:profile":"C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\rust_mozprofile.nqSRh5yCk198","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"6.2","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
Jun 09, 2019 10:37:49 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.WebDriverException: Unable to parse remote response: <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
  <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
  <script type="text/javascript">
    var json = Object.freeze('{"consoleLink": "\u002fwd\u002fhub","type": "Standalone","class": "org.openqa.grid.web.servlet.DisplayHelpHandler$DisplayHelpServletConfig","version": "3.141.59"}');
  </script>
</head>
<body>

<div id="content">
  <div id="help-heading">
    <h1><span id="logo"></span></h1>
    <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2>
  </div>

  <div id="content-body">
    <p>
      Whoops! The URL specified routes to this help page.
    </p>
    <p>
      For more information about Selenium <span class="se-type"></span> please see the
      <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>.
      <span id="console-item">
        Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>.
      </span>
    </p>
    <p>
      Happy Testing!
    </p>
  </div>

  <div>
    <footer id="help-footer">
      Selenium is made possible through the efforts of our open source community, contributions from
      these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our
      <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>.
   </footer>
  </div>
 </div>

</body>
</html>
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:139)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:576)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:210)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at Myclass.main(Myclass.java:57)
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'JWEB-WIN12-VM1', ip: '10.213.52.52', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_211'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:126)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$19(JsonTypeCoercer.java:140)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
	at org.openqa.selenium.json.Json.toType(Json.java:69)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:113)
	... 7 more

**Comment by atchuth23** [comment]
actual fail log with the url having wd/hub in it



*****
1560102297714	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\rust_mozprofile.adhtB6IegViw"
1560102298662	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1560102298664	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1560102298664	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1560102303082	Marionette	INFO	Listening on port 54603
1560102303465	Marionette	WARN	TLS certificate errors will be ignored for this session
Jun 09, 2019 11:15:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1560102304294	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\rust_mozprofile.kD4T0zabKjz9"
1560102304306	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:54629
1560102305743	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1560102305744	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1560102305763	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1560102306034	Marionette	TRACE	Received observer notification profile-after-change
1560102306169	Marionette	TRACE	Received observer notification toplevel-window-ready
1560102306437	Marionette	TRACE	Received observer notification command-line-startup
1560102306438	Marionette	TRACE	Received observer notification nsPref:changed
1560102306438	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1560102307596	Marionette	TRACE	Received observer notification toplevel-window-ready
1560102310725	Marionette	TRACE	Received observer notification marionette-startup-requested
1560102310725	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1560102310730	Marionette	TRACE	All scripts recorded.
1560102310730	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1560102310730	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1560102310730	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1560102310730	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1560102310731	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1560102310731	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1560102310731	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1560102310731	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1560102310732	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1560102310732	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1560102310732	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1560102310732	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1560102310732	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1560102310732	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1560102310732	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1560102310732	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1560102310733	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1560102310733	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1560102310733	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1560102310733	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1560102310733	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1560102310733	Marionette	DEBUG	Setting recommended pref security.certerrors.mitm.priming.enabled to false
1560102310733	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1560102310733	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1560102310733	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1560102310734	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1560102310734	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1560102310779	Marionette	INFO	Listening on port 54629
1560102310780	Marionette	DEBUG	Remote service is active
1560102311152	geckodriver::marionette	DEBUG	Connection established on 127.0.0.1:54629. Waiting for Marionette handshake
1560102311169	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:54645
1560102311167	geckodriver::marionette	DEBUG	Connected to Marionette
1560102311171	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1560102311172	Marionette	WARN	TLS certificate errors will be ignored for this session
1560102311202	Marionette	TRACE	[6442450945] Frame script loaded
1560102311245	Marionette	TRACE	[6442450945] Frame script registered
1560102311258	Marionette	DEBUG	0 <- [1,1,null,{"sessionId":"0cf53343-300a-46bd-9f1d-d93758455890","capabilities":{"browserName":"firefox","browserVersion":"67.0. ... ozprofile.kD4T0zabKjz9","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1560102311261	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"0cf53343-300a-46bd-9f1d-d93758455890","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"67.0.1","moz:accessibilityChecks":false,"moz:buildID":"20190529130856","moz:geckodriverVersion":"0.24.0","moz:headless":false,"moz:processID":2684,"moz:profile":"C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\rust_mozprofile.kD4T0zabKjz9","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"6.2","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
Jun 09, 2019 11:15:11 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.WebDriverException: newSession
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'JWEB-WIN12-VM1', ip: '10.213.52.52', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_211'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4bb74f - <no info>
   1:           0x4bbea9 - <no info>
   2:           0x43ce8d - <no info>
   3:           0x44ce14 - <no info>
   4:           0x44944a - <no info>
   5:           0x4203e1 - <no info>
   6:           0x407dc7 - <no info>
   7:           0x6d95b9 - <no info>
   8:           0x4173a7 - <no info>
   9:           0x6d38b3 - <no info>
  10:     0x7ffe7d8813d2 - BaseThreadInitThunk
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'JWEB-WIN12-VM1', ip: '10.213.52.52', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_211'
Driver info: driver.version: RemoteWebDriver
remote stacktrace: org.openqa.selenium.WebDriverException: newSession
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'JWEB-WIN12-VM1', ip: '10.213.52.52', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_211'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4bb74f - <no info>
   1:           0x4bbea9 - <no info>
   2:           0x43ce8d - <no info>
   3:           0x44ce14 - <no info>
   4:           0x44944a - <no info>
   5:           0x4203e1 - <no info>
   6:           0x407dc7 - <no info>
   7:           0x6d95b9 - <no info>
   8:           0x4173a7 - <no info>
   9:           0x6d38b3 - <no info>
  10:     0x7ffe7d8813d2 - BaseThreadInitThunk
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.grid.session.remote.RemoteSession$Factory.performHandshake(RemoteSession.java:147)
	at org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply(ServicedSession.java:161)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:180)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:183)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:66)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Collections$2.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:69)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.DistinctOps$1$2.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Unknown Source)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$1(ProtocolHandshake.java:127)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:129)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:139)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:576)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:210)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at Myclass.main(Myclass.java:57)

**Comment by atchuth23** [comment]
java -Dwebdriver.gecko.driver=C:\lasele\geckodriver.exe -jar selenium-server-standalone-3.141.59.jar -port 5566

**Comment by Julioevm** [comment]
I'm also having problems with the latest selenium-server-standalone and firefox 67 + geckodriver 0.24
But Im running it on ubuntu 18.04

**Comment by barancev** [comment]
@atchuth23 You've shown three samples of FirefoxDriver initialization in a single code fragment. Which one is not working as expected? What log corresponds to the "broken" case?

**Comment by atchuth23** [comment]
@brancev The last log is the actual log. The actual case is i have a linux server were we execute the robot file. And we use the remote url of the windows machine were the selenium standalone jar is run.

Now the problem is i am not able to launch the firefox .

**Comment by AutomatedTester** [comment]
This looks like because you are running it as a service and it's not accessing a desktop enviroment things are just crashing. Selenium is not supported as a service.
