### ISSUE TITLE
Portprober.js must respect excludedportrange on windows

### ISSUE THREAD

**Issue by krausest** [SeleniumHQ/selenium#7284]
On my windows 10 machine with docker installed the logic implemented in findWindowsPortRange() in portprober.js often chooses a port that is actually excluded. This causes the following error:

```
Error: listen EACCES: permission denied 0.0.0.0:49719
    at Server.setupListenHandle [as _listen2] (net.js:1241:19)
    at listenInCluster (net.js:1306:12)
    at Server.listen (net.js:1394:7)
    at Promise (C:\Users\Stefa\Source\Javascript\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\net\portprober.js:159:12)
    at new Promise (<anonymous>)
    at isFree (C:\Users\Stefa\Source\Javascript\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\net\portprober.js:150:10)
    at Object.findFreePort (C:\Users\Stefa\Source\Javascript\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\net\portprober.js:176:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 49719 }
```

Portprober.js just checks for the dynamic port range:
```netsh int ipv4 show dynamicport tcp

Protokoll tcp Dynamischer Portbereich
---------------------------------
Startport      : 49152
Anzahl von Ports : 16384
```

But hyperv has some reserved ports that can be listed with the following command:

`netsh interface ipv4 show excludedportrange protocol=tcp`. This prints on my machine:
```
Startport      Endport
----------    --------
      5357        5357
      5426        5426
     49711       49810
     49811       49910
     50000       50059     *
     50060       50159
     50160       50259
     50260       50359
     50590       50689
```
Port 49719 falls within the third range.

## Environment

OS: Windows 10 with hyperv
Browser: Chrome
Browser version: 75.0
Browser Driver version: chromedriver 75.0.0
Language Bindings version: Javascript selenium-webdriver 4.0.0-alpha.1

**Comment by diemol** [comment]
The current [implementation](https://github.com/SeleniumHQ/selenium/blob/5543c5879374ec4649a02ac88284a9cad94d6779/javascript/node/selenium-webdriver/net/portprober.js) does not use ranges anymore. Therefore, this issue should be fixed by that.
