### ISSUE TITLE
geckodriver: JavascriptException: ReferenceError: a is not defined 

### ISSUE THREAD

**Issue by Snowfish1994** [SeleniumHQ/selenium#7319]
I'm using selenium-java  to test some script into firefox.
Env
    selenium version:3.141.59
    gecko version:0.24.0
    firefox version:67.0.3
    JDK:1.8
    System : Win10 1809

here is the code :

    System.setProperty(GeckoDriverService.GECKO_DRIVER_EXE_PROPERTY,"D:\\ProgramFiles\\Selenium\\geckodriver.exe");
    RemoteWebDriver driver = new FirefoxDriver();
    driver.navigateTo("https://www.baidu.com");
    driver.executeScript("var a = 2;", "");
    driver.executeScript("console.log(a*arguments[0])", 5);

I expect this code to return the correct result : show '10' in firefox console ,
but selenium throw a JavascriptException: ReferenceError: a is not defined

I know firefox has a Marionette module after google this problem.

I do some changes like this:

    FirefoxOptions options = new FirefoxOptions();
    options.setLegacy(true);
    driver = new FirefoxDriver(options);

Then , I get a org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.

What can I do to solve this "executeScript" problem?

Here are twice logs :
1、within setLegacy:

    1561342023188	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\**\\AppData\\Local\\Temp\\rust_mozprofile.NbGMaZlnbLo0"
    JavaScript error: efl1ymfbwxv.cfg, line 2: ReferenceError: Components is not defined
    1561342023796	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
    1561342023797	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
    1561342023797	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
    1561342027312	Marionette	INFO	Listening on port 6610
    1561342027520	Marionette	WARN	TLS certificate errors will be ignored for this session
    Jun 24, 2019 10:07:07 AM org.openqa.selenium.remote.ProtocolHandshake createSession
    INFO: Detected dialect: W3C
    Key:acceptInsecureCerts	Value:true
    Key:browserName	Value:firefox
    Key:browserVersion	Value:67.0.3
    Key:javascriptEnabled	Value:true
    Key:moz:accessibilityChecks	Value:false
    Key:moz:buildID	Value:20190618025334
    Key:moz:geckodriverVersion	Value:0.24.0
    Key:moz:headless	Value:false
    Key:moz:processID	Value:4216
    Key:moz:profile	Value:C:\Users\**\AppData\Local\Temp\rust_mozprofile.NbGMaZlnbLo0
    Key:moz:shutdownTimeout	Value:60000
    Key:moz:useNonSpecCompliantPointerOrigin	Value:false
    Key:moz:webdriverClick	Value:true
    Key:pageLoadStrategy	Value:normal
    Key:platform	Value:WINDOWS
    Key:platformName	Value:WINDOWS
    Key:platformVersion	Value:10.0
    Key:rotatable	Value:false
    Key:setWindowRect	Value:true
    Key:strictFileInteractability	Value:false
    Key:timeouts	Value:{implicit=0, pageLoad=300000, script=30000}
    Key:unhandledPromptBehavior	Value:dismiss and notify
    org.openqa.selenium.JavascriptException: ReferenceError: a is not defined
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
    System info: host: 'DESKTOP-I03FV10', ip: '10.2.20.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
    Driver info: org.openqa.selenium.firefox.FirefoxDriver
    Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 67.0.3, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20190618025334, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 4216, moz:profile: C:\Users\**\AppData..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
    Session ID: 1c7d0780-6eb9-42f7-83c3-69d33b233c3c
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
        at com.jiuqi.rpa.web.test.FireFoxInjectScriptTest.main(FireFoxInjectScriptTest.java:19)

2、after setLegacy(true):

    org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
    System info: host: 'DESKTOP-I03FV10', ip: '10.2.20.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
    Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:247)
        at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:159)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
        at com.jiqui.rpa.lib.browser.WebBrowserLibary.open(WebBrowserLibary.java:81)
        at com.jiuqi.rpa.web.test.FireFoxInjectScriptTest.main(FireFoxInjectScriptTest.java:12)
    Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:42482/hub/status] to be available after 45005 ms
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
        at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:245)
        ... 8 more
    Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
        ... 9 more

**Comment by jimevans** [comment]
With WebDriver, JavaScript executes in the context of an anonymous function, so using `var a` scopes the variable to that function and is removed from scope (and thus no longer exists when the function returns). Either explicitly scope the variable `a` to something persistent outside the function lifespan (like `window.a = 2` or `document.a = 2`) or remove the `var` keyword from your first script (e.g., `driver.executeScript("a = 2");`, which is implicitly setting it on the global window object in the browser).

As for `setLegacy`, that won’t work for any version of Firefox greater than 47.

**Comment by Snowfish1994** [comment]
Many Thanks!
The problem about scope doesn't arise on IE/Chrome , perhaps it is more strict on Firefox?
I'll fix it few minutes later.
Thx.
