### ISSUE TITLE
Session ID is null. Using WebDriver after calling quit()? issue while tring to close browser and start it again 

### ISSUE THREAD

**Issue by TofailHiary** [SeleniumHQ/selenium#7326]
Hello guys 
i got this issue while trying to close webdriver and open it again to close browser and open it again for each scenario in new browser session , i used cucumber hooks @before and @after as following :

`
	private static WebDriver localDriver = null;

	public static WebDriver getDriver(String browser) {
		if (localDriver == null) {
			setWebDriver(createInstance(browser));
		}
		return localDriver;
	}

	public static WebDriver getInstance() {
		if (localDriver != null) {
			return localDriver;
		}
		return null;

	}

@Before

public static WebDriver createInstance(String browserName) {
		WebDriver driver;
		

		switch (browserName.toUpperCase()) {
		case "FIREFOX":
			System.setProperty("webdriver.gecko.driver",
					"drivers/windows/fireFox/geckodriver.exe");
			driver = new FirefoxDriver();
			driver.manage().window().maximize();
			//driver.manage().deleteAllCookies();
			break;
		case "IE":
			System.setProperty("webdriver.ie.driver",
					"drivers/windows/IE/IEDriverServer.exe");
			driver = new InternetExplorerDriver();
			driver.manage().window().maximize();
			//driver.manage().deleteAllCookies();
			break;
		case "CHROME":
			System.setProperty("webdriver.chrome.driver",
					"drivers/windows/chrome/chromedriver.exe");
			driver = new ChromeDriver();
			driver.manage().window().maximize();
		
			//driver.manage().deleteAllCookies();
			break;
		case "EDGE":
			System.setProperty("webdriver.edge.driver",
					"drivers/windows/edge/MicrosoftWebDriver.exe");
			driver = new EdgeDriver();
			driver.manage().window().maximize();
			//driver.manage().deleteAllCookies();
			break;
		default:
			System.setProperty("webdriver.chrome.driver",
					"drivers/windows/chrome/chromedriver.exe");
			driver = new ChromeDriver();
			
			break;
		}
` 
and this after 

`@After 
public static void closeDriver() throws InterruptedException {
		if (localDriver != null) {
			localDriver.manage().deleteAllCookies();
			localDriver.quit();
			localDriver = null;
			Thread.sleep(5000);}
}

`

could you please help me to solve this issue 
note that my env is 
Junit 4 + cucumber + selenium 3.14

Error log : 

Feature: Check when user login to the system
Running Feature child (scenario)...
Begin scenario run...
Scenario login to the system has been started
1561402330360	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\Tofail\\AppData\\Local\\Temp\\rust_mozprofile.3crKL1plyPdx"
1561402330744	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1561402330744	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1561402330744	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1561402332275	Marionette	INFO	Listening on port 51410
1561402332503	Marionette	WARN	TLS certificate errors will be ignored for this session
Jun 24, 2019 9:52:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
FirefoxDriver: firefox on WINDOWS (8d04c0b9-65ae-4baf-8feb-04fe43040d42)has been opened
[GFX1-]: [D2D1.1] 4CreateBitmap failure Size(20444,100) Code: 0x80070057 format 0
JavaScript warning:  unreachable code after return statement
JavaScript warning: line 7241: unreachable code after return statement
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: http://%(server)s/dummy/blocklist//buckets/monitor/collections/changes/records?_expected=%221561148779474%22 is not a valid URL..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:203:13

1561402378981	Marionette	INFO	Stopped listening on port 51410
[Child 16508, Chrome_Chi[Parent 16676, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341

###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

[GPU 17488, Chrome_ChildThread] WARNING: pip
###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

Scenario completed...0
Running Feature child (scenario)...
Begin scenario run...
Scenario Invalid login to the system has been started
1561402385501	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\Tofail\\AppData\\Local\\Temp\\rust_mozprofile.AKFRHBAxS4KU"
1561402385885	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1561402385886	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1561402385886	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1561402387530	Marionette	INFO	Listening on port 51489
[Parent 25064, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 2580, Chrome_ChildThread] WARNING: pipe err1561402387693	Marionette	WARN	TLS certificate errors will be ignored for this session
Jun 24, 2019 9:53:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
FirefoxDriver: firefox on WINDOWS (b10728ed-94e6-40be-8149-5c8fc799886d)has been opened

  Scenario: login to the system               # src/test/resources/General/Login/test.feature:3
    Given I want to open home page            # Stepdefs.openHomepage()
    And I want to login username and password # Stepdefs.loginto()
    Then Check if the user on Home page       # Stepdefs.checkhomePage()
1561402393069	Marionette	INFO	Stopped listening on port 51489
[Parent 25064, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Parent 25064, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 27416, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 27416, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win[Parent 25064, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 3964, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 3964, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.c[GPU 25936, Chrome_C
###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

Initiating retry...
Current class is: com.github.mkolisnyk.cucumber.runner.ExtendedExecutionUnitRunner
Scenario completed...1
Running Feature child (scenario)...
Begin scenario run...
Scenario check forget password has been started
1561402399458	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\Tofail\\AppData\\Local\\Temp\\rust_mozprofile.zJPL3j9ROrzj"
1561402399845	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1561402399846	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1561402399846	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1561402401350	Marionette	INFO	Listening on port 51523
1561402401618	Marionette	WARN	TLS certificate errors will be ignored for this session
Jun 24, 2019 9:53:21 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
FirefoxDriver: firefox on WINDOWS (ed0c9229-42b2-45b1-b818-41c922f8a320)has been opened

  Scenario: Invalid login to the system # src/test/resources/General/Login/test.feature:8
    Given I want to open home page      # Stepdefs.openHomepage()
    Then I want to login invalid        # Stepdefs.invalid_login()
      org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
      Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
      System info: host: 'DESKTOP-85HPMJD', ip: '192.168.45.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
      Driver info: driver.version: RemoteWebDriver
      	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
      	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
      	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
      	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:420)
      	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
      	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
      	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
      	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
      	at com.sun.proxy.$Proxy19.click(Unknown Source)
      	at pageObjectsFactory.pageObjects.login.LoginPage.invalid_login(LoginPage.java:123)
      	at io.cucumber.skeleton.Stepdefs.invalid_login(Stepdefs.java:219)
      	at ✽.Then I want to login invalid(src/test/resources/General/Login/test.feature:10)

1561402406212	Marionette	INFO	Stopped listening on port 51523
[Parent 20628, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Parent 20628, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 19000, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 19000, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_[Parent 20628, Gecko_IOThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341

###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

[GPU 25400, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1560988636/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

Initiating retry...
Current class is: com.github.mkolisnyk.cucumber.runner.ExtendedExecutionUnitRunner
Scenario completed...1

  Scenario: check forget password                 # src/test/resources/General/Login/test.feature:12
    Given I want to open home page                # Stepdefs.openHomepage()
    Then Check if the password reset successfully # Stepdefs.forgetPassword()
      org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
      Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
      System info: host: 'DESKTOP-85HPMJD', ip: '192.168.45.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
      Driver info: driver.version: RemoteWebDriver
      	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
      	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
      	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
      	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:420)
      	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
      	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
      	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
      	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
      	at com.sun.proxy.$Proxy19.sendKeys(Unknown Source)
      	at pageObjectsFactory.pageObjects.login.LoginPage.forgetPasword(LoginPage.java:145)
      	at io.cucumber.skeleton.Stepdefs.forgetPassword(Stepdefs.java:224)
      	at ✽.Then Check if the password reset successfully(src/test/resources/General/Login/test.feature:14)

Failed scenarios:
src/test/resources/General/Login/test.feature:8 # Scenario: Invalid login to the system
src/test/resources/General/Login/test.feature:12 # Scenario: check forget password

3 Scenarios (2 failed, 1 passed)
7 Steps (2 failed, 5 passed)
1m22.968s

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-85HPMJD', ip: '192.168.45.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:420)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy19.click(Unknown Source)
	at pageObjectsFactory.pageObjects.login.LoginPage.invalid_login(LoginPage.java:123)
	at io.cucumber.skeleton.Stepdefs.invalid_login(Stepdefs.java:219)
	at ✽.Then I want to login invalid(src/test/resources/General/Login/test.feature:10)

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-85HPMJD', ip: '192.168.45.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:420)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy19.sendKeys(Unknown Source)
	at pageObjectsFactory.pageObjects.login.LoginPage.forgetPasword(LoginPage.java:145)
	at io.cucumber.skeleton.Stepdefs.forgetPassword(Stepdefs.java:224)
	at ✽.Then Check if the password reset successfully(src/test/resources/General/Login/test.feature:14)

Thanks in advance

**Comment by cgoldberg** [comment]
This is the tracker for Selenium issues.  Please post general questions to the [**selenium-users**](https://groups.google.com/forum/#!forum/selenium-users) mailing list.
