### ISSUE TITLE
net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: sendKeysToActiveElement while doing Ctrl+click

### ISSUE THREAD

**Issue by mahesht36** [SeleniumHQ/selenium#7333]
Hi Team,

I am using webdrivermanager, version: '3.4.0' with chrome driver 75.0.3770.90 with chrome browser 75.0.3770.100.getting below error.
it was working fine earlier with chrome browser 74.

 net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: sendKeysToActiveElement
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'VI-LLPB0312V4', ip: '172.20.51.204', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_201'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteKeyboard.pressKey(RemoteKeyboard.java:46)
	at org.openqa.selenium.interactions.KeyDownAction.perform(KeyDownAction.java:47)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:36)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:641)
	at com.johnlewis.weeklyCashBalancing.pageobjects.LogoffPage.menuCRTLClick(LogoffPage.java:85)
	at com.johnlewis.weeklyCashBalancing.pageobjects.LogoffPage$$EnhancerByCGLIB$$3d9aae92.CGLIB$menuCRTLClick$0(<generated>)
	at com.johnlewis.weeklyCashBalancing.pageobjects.LogoffPage$$EnhancerByCGLIB$$3d9aae92$$FastClassByCGLIB$$5ddc1c52.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.BaseMethodRunner.invokeMethod(BaseMethodRunner.java:10)
	at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:20)
	at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:361)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:132)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:68)
	at com.johnlewis.weeklyCashBalancing.pageobjects.LogoffPage$$EnhancerByCGLIB$$3d9aae92.menuCRTLClick(<generated>)
	at com.johnlewis.weeklyCashBalancing.steps.LogoffPageSteps.menuCTRLClick(LogoffPageSteps.java:18)
	at com.johnlewis.weeklyCashBalancing.steps.LogoffPageSteps$$EnhancerByCGLIB$$3e085ab9.CGLIB$menuCTRLClick$1(<generated>)
	at com.johnlewis.weeklyCashBalancing.steps.LogoffPageSteps$$EnhancerByCGLIB$$3e085ab9$$FastClassByCGLIB$$86031464.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.BaseMethodRunner.invokeMethod(BaseMethodRunner.java:10)
	at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:20)
	at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:361)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:132)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:68)
	at com.johnlewis.weeklyCashBalancing.steps.LogoffPageSteps$$EnhancerByCGLIB$$3e085ab9.menuCTRLClick(<generated>)
	at com.johnlewis.weeklyCashBalancing.stepdefs.WCBStepDefination.userCLTRAndClickToOpenTheMenuInMultipleTab(WCBStepDefination.java:53)
	at ?.user press CLTR and click on to open the menu in multiple tab and Verify tital of page "Enter Daily WCB Totals,Enter Other Tenders,View and Submit Weekly Totals,Maintain Registers and Sections,View Audit Trail,Submit Progress Tracker"(src/test/resources/features/LogoffWCB.feature:9)

**Comment by AutomatedTester** [comment]
Unforunately this bug has no reproduceable steps for us. Please create a reduced test case 
or  send a question to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
