### ISSUE TITLE
org.openqa.selenium.InvalidArgumentException: invalid argument from invalid argument: 'origin' must be either a string or a dictionary

### ISSUE THREAD

**Issue by tedrigofrach** [SeleniumHQ/selenium#7372]
I am not sure if it is related, but since in Chrome was automatically updated in our company from version 74.x to 75.x I get this error when running the Selenium tests in a on-premises Selenium Grid:

```
org.openqa.selenium.InvalidArgumentException: invalid argument
from invalid argument: 'origin' must be either a string or a dictionary
  (Session info: chrome=75.0.3770.100)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:618)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.proxy.$Proxy28.perform(Unknown Source)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:639)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:595)
```

It happens for instance when doing a double click or right click with the methods of org.openqa.selenium.interactions.Actions of Selenium.

I use the Chromedriver version 75.0.3770.90 because I have not found a Chromedriver which version matches exactly to our Chrome version.

When I use Chromedriver version 74.0.3729.6 then everything is okay when I run the tests against Chrome version 75.0.3770.100.

This error message originates from Chromedriver. But I am not sure why it is thrown and how to prevent it other than using an older Chromedriver version? Maybe it is a bug in Chromedriver? Or in Selenium?

Since I find no information about this issue on the internet I assume that it is not a general problem but occurs only in very rare conditions. You can try to reproduce it with Selenium version 3.141.59, Chrome 75.0.3770.100 and Chromedriver 75.0.3770.90 on Windows 10 by doing a double click on a WebElement.

**Comment by diemol** [comment]
@tedrigofrach Chrome and ChromeDriver 75 are running in W3C mode by default, and if your Selenium client is sending commands that are not supported in W3C mode, it is very likely that you will get an error.

It is easier if you send this question to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by KroArtem** [comment]
I know this issue is closed but will be happy if any solution will be found and written here. :) Still didn't manage to investigate this issue (have the same one). There are no appropriate questions in selenium user group and on stackoverflow.
