### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process #94

### ISSUE THREAD

**Issue by juancrescente** [SeleniumHQ/selenium#7444]
This is the code:

```
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options
import time
import sys
class HB:
    def __init__(self):
        print("loading browser")
        opts = Options()
        opts.headless = True
        self.browser = Firefox(options=opts)
```
    
These are the versions of everything:
```

pip3 freeze
selenium==3.141.0
firefox -v
Mozilla Firefox 68.0.1
/geckodriver --version
geckodriver 0.24.0 ( 2019-01-28)
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
Full error:

```

Traceback (most recent call last):
  File "/home/juan/telegram_homebanking/venv/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/juan/telegram_homebanking/venv/lib/python3.5/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 29, in echo
    hb = HB()
  File "/home/juan/telegram_homebanking/hb.py", line 11, in __init__
    self.browser = Firefox(options=opts)
  File "/home/juan/telegram_homebanking/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/juan/telegram_homebanking/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/juan/telegram_homebanking/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/juan/telegram_homebanking/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/juan/telegram_homebanking/venv/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

```

**Comment by Dude-X** [comment]
I would like to see your above code ran without being in an application.
The traceback seems to indicate that some other application telegram is running.

**Comment by AutomatedTester** [comment]
Closing as this has been open for a while and I don't think there is anything we can do. Looks like the driver/browser crashed
