### ISSUE TITLE
Chrome InitSession ERROR invalid argument: 'firstMatch' must contain at least one entry

### ISSUE THREAD

**Issue by meenalmenghani** [SeleniumHQ/selenium#7469]
Unable to create chrome session with Chrome v76 and selenium v3.5.3, getting **ERROR invalid argument: 'firstMatch' must contain at least one entryERROR invalid argument: 'firstMatch' must contain at least one entry**
The 'firstMatch' is empty.

We are getting error with below code:

  ```
    DesiredCapabilities caps = new DesiredCapabilities();
        caps.setPlatform(Platform.ANY);
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized");
        caps.setCapability(ChromeOptions.CAPABILITY, options);
       driver = new ChromeDriver(caps);
```

Error:

```
Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 7818
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: invalid argument: 'firstMatch' must contain at least one entry
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'xxxxx', ip: 'xxxxx', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_192'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00C87C93+1473683]
	Ordinal0 [0x00C0ADB1+961969]
	Ordinal0 [0x00B942E3+475875]
	Ordinal0 [0x00B48A06+166406]
	Ordinal0 [0x00B48DFA+167418]
	Ordinal0 [0x00B48D1D+167197]
	Ordinal0 [0x00B4742B+160811]
	Ordinal0 [0x00B30AE6+68326]
	Ordinal0 [0x00B31BF0+72688]
	Ordinal0 [0x00B31B89+72585]
	Ordinal0 [0x00C24B77+1067895]
	GetHandleVerifier [0x00D26875+506677]
	GetHandleVerifier [0x00D26610+506064]
	GetHandleVerifier [0x00D2D1B8+533624]
	GetHandleVerifier [0x00D2704A+508682]
	Ordinal0 [0x00C1C266+1032806]
	Ordinal0 [0x00C1C0DF+1032415]
	Ordinal0 [0x00C26A8B+1075851]
	Ordinal0 [0x00C26BF3+1076211]
	Ordinal0 [0x00C25BA5+1072037]
	BaseThreadInitThunk [0x755562C4+36]
	RtlSubscribeWnfStateChangeNotification [0x77DE1F69+1081]
	RtlSubscribeWnfStateChangeNotification [0x77DE1F34+1028]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:178)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:146)
```

ChromeDriver logs-

```
[1565052738.114][INFO]: Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864})
[1565052738.114][INFO]: Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1565052739.230][INFO]: [204043e3bc8e2cb05f8db44dcf269a1c] COMMAND InitSession {
   "capabilities": {
      "alwaysMatch": {

      },
      "desiredCapabilities": {
         "chromeOptions": {
            "args": [ "--start-maximized" ],
            "extensions": [  ]
         },
         "platform": "ANY"
      },
      "firstMatch": [  ],
      "requiredCapabilities": {

      }
   },
   "desiredCapabilities": {
      "chromeOptions": {
         "args": [ "--start-maximized" ],
         "extensions": [  ]
      },
      "platform": "ANY"
   },
   "requiredCapabilities": {

   }
}
[1565052739.241][INFO]: [204043e3bc8e2cb05f8db44dcf269a1c] RESPONSE InitSession ERROR invalid argument: 'firstMatch' must contain at least one entry
[1565052739.241][DEBUG]: Log type 'driver' lost 1 entries on destruction
```

## Environment

OS: Windows
Browser: Chrome
Browser version: v 76.0.3809.87
Browser Driver version: ChromeDriver v76.0.3809.68
Language Bindings version: Java v3.5.3

Could you please look into it.

**Comment by diemol** [comment]
Hi @meenalmenghani
Please update to a recent version of Selenium WebDriver, latest is 3.141.59, you are using 3.5.3
