### ISSUE TITLE
Error: Failed to import atoms module ./atoms/get-attribute.js.

### ISSUE THREAD

**Issue by zhoumh1988** [SeleniumHQ/selenium#7488]
## 🐛 Bug Report

```ssh
┏ Electron -------------------

  Error: Failed to import atoms module ./atoms/get-attribute.js. If running in dev mode, you need to run `bazel build //javascript/node/selenium-webdriver/lib/atoms:get-attribute.js` from the projectroot: Error: Cannot find module './atoms/get-attribute.js'
      at requireAtom (webpack-internal:///./node_modules/selenium-webdriver/lib/http.js:56:13)
      at eval (webpack-internal:///./node_modules/selenium-webdriver/lib/http.js:35:22)
      at Object../node_modules/selenium-webdriver/lib/http.js (/Users/root/Documents/projects/argus/desktop/dist/main/main.js:1893:1)
      at __webpack_require__ (/Users/root/Documents/projects/argus/desktop/dist/main/main.js:704:30)
      at fn (/Users/root/Documents/projects/argus/desktop/dist/main/main.js:78:20)
      at eval (webpack-internal:///./node_modules/selenium-webdriver/http/index.js:29:17)
      at Object../node_modules/selenium-webdriver/http/index.js (/Users/root/Documents/projects/argus/desktop/dist/main/main.js:1774:1)
      at __webpack_require__ (/Users/root/Documents/projects/argus/desktop/dist/main/main.js:704:30)
      at fn (/Users/root/Documents/projects/argus/desktop/dist/main/main.js:78:20)
      at eval (webpack-internal:///./node_modules/selenium-webdriver/chrome.js:133:14)

┗ ----------------------------
```

### package.json
```json
{
  ...
  "main": "./dist/main/main.js",
  "scripts": {
    "start": "npm run start:renderer && npm run start:main",
    "start:main": "electron-webpack dev",
    "start:renderer": "cross-env APP_ROOT=src/renderer BROWSER=none umi dev"
  },
  "devDependencies": {
    "cross-env": "^5.1.1",
    "electron": "^6.0.0",
    "electron-builder": "^21.2.0",
    "electron-debug": "^3.0.1",
    "electron-webpack": "^2.7.4",
    "html-webpack-plugin": "^3.2.0",
    "husky": "^0.14.3",
    "less-loader": "^4.1.0",
    "less-vars-to-js": "^1.3.0",
    "moment-locales-webpack-plugin": "^1.0.7",
    "prettier": "1.17.0",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "umi": "^2.8.16",
    "umi-plugin-dll": "^1.5.2",
    "umi-plugin-dva": "^1.7.7",
    "umi-plugin-react": "^1.9.14",
    "umi-plugin-routes": "^1.4.6",
    "webpack": "~4.35.3",
    "webpack-cli": "^3.3.2",
    "webpack-merge": "^4.2.1",
    "webpack-node-externals": "^1.7.2"
  },
  "dependencies": {
    "chromedriver": "^76.0.0",
    "selenium-webdriver": "^4.0.0-alpha.4",
    "source-map-support": "^0.5.12"
  },
  "electronWebpack": {
    "main": {
      "sourceDirectory": "src/main"
    },
    "renderer": {
      "sourceDirectory": null
    }
  }
}
```

### main.js
```javascript
const webdriver = require('selenium-webdriver')
const chrome = require('selenium-webdriver/chrome');
const chromePath = require('chromedriver').path;

const Options = chrome.Options;
const service = new chrome.ServiceBuilder(chromePath).build();
chrome.setDefaultService(service);

ipcMain.on('backchannel', async (event, arg) => {
    const driver = new webdriver.Builder()
        .forBrowser('chrome')
        .withCapabilities(webdriver.Capabilities.chrome())
        .setChromeOptions(new Options().excludeSwitches(["ignore-certificate-errors", chromePath]))
        .build()
    try {
        await driver.get('https://www.baidu.com');
        await driver.sleep(3000);
    } catch (error) {
        event.reply('backchannel-reply', error);
        console.log(error)
    } finally {
        await driver.quit();
    }
})
```

### start main
```ssh
node run start:main
or
yarn start:main
```

Detailed steps to reproduce the behavior:

## Expected behavior
open chromedriver dialog and visit baidu‘s homepage.

## Environment

OS: macOS Mojave 10.14.6
Node: v11.6.0
Npm: 6.10.2
selenium-webdriver: ^4.0.0-alpha.4
chromedriver: ^76.0.0
electron: ^6.0.0
electron-webpack: ^2.7.4

## Attempt
1. bazel
```ssh
$ bazel build //javascript/node/selenium-webdriver/lib/atoms:get-attribute.js

ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
```

2. rebuild project but not fixed.
3. I try to use simple electron's project, it works success.but not normal when use electron-webpack.

**Comment by zhoumh1988** [comment]
在项目根目录添加electron-webpack.json文件，并且删除package.json里的electronWebpack配置。

```json
{
    "main": {
        "sourceDirectory": "src/main",
        "webpackConfig": "build/webpack.main.config.js"
    },
    "renderer": {
        "sourceDirectory": null
    }
}
```

build/webpack.main.config.js
```javascript
const nodeExternals = require('webpack-node-externals');
module.exports = {
    ...
    target: 'node',
    externals: [nodeExternals()],
    ...
}
```
