### ISSUE TITLE
We are Unable to perform maximize browser for edge browser in ruby

### ISSUE THREAD

**Issue by evnraja32** [SeleniumHQ/selenium#7500]
## Environment
OS: Windows 10
Ruby Version: 2.5.5
Selenium-webdriver : 3.142.3
Edge Broser Version:
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Edge Driver Version : 10.0.17763.652 (On Demand Driver)

## Steps to reproduce:
```
require 'selenium-webdriver'

Selenium
@browser = Selenium::WebDriver.for :edge
@browser.get "https://www.google.com/"
begin
   @browser.manage.window.maximize
rescue => e
   puts e.message
   puts e.backtrace
ensure
   @browser.close
end
```

## Expected outcome:
Browser should be maximized

## Actual outcome:
``unexpected response, code=500, content-type="text/plain"

Unknown error

C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:98:in 'create_response'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/default.rb:114:in 'request'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:64:in 'call'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/bridge.rb:167:in 'execute'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in 'execute'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/edge/bridge.rb:70:in 'maximize_window'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/window.rb:143:in 'maximize'
C:/Users/ELLURV/Documents/NetBeansProjects/FutureTestFrameworks/lib/no_code_ui_automation/script.rb:17:in '<main>'
``

**Comment by evnraja32** [comment]
## Debug logs

`2019-08-19 18:47:38 DEBUG Selenium Executing Process ["C:/Windows/System32/MicrosoftWebDriver.exe", "--port=17556"]
[18:47:38.360] - Listening on http://127.0.0.1:17556/ 

[18:47:38.361] - Listening on http://[::1]:17556/ 

2019-08-19 18:47:38 INFO Selenium -> POST session
2019-08-19 18:47:38 INFO Selenium    >>> http://127.0.0.1:17556/session | {"desiredCapabilities":{"browserName":"MicrosoftEdge","version":"","platform":"WINDOWS","javascriptEnabled":false,"cssSelectorsEnabled":false,"takesScreenshot":false,"nativeEvents":false,"rotatable":false},"capabilities":{"firstMatch":[{"browserName":"MicrosoftEdge"}]}}
2019-08-19 18:47:38 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/3.142.3 (ruby windows)", "Content-Length"=>"270"}
2019-08-19 18:47:39 INFO Selenium <- {"value":{"sessionId":"C92D8C29-720F-49E7-BC23-8E3F4A5FCD3E","capabilities":{"acceptInsecureCerts":false,"browserName":"MicrosoftEdge","browserVersion":"44.17763.1.0","pageLoadStrategy":"normal","platformName":"windows","setWindowRect":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"proxy":{}}}}
2019-08-19 18:47:39 INFO Selenium Detected W3C dialect.
2019-08-19 18:47:39 INFO Selenium Forcing W3C dialect.
2019-08-19 18:47:39 INFO Selenium -> POST session/C92D8C29-720F-49E7-BC23-8E3F4A5FCD3E/url
2019-08-19 18:47:39 INFO Selenium    >>> http://127.0.0.1:17556/session/C92D8C29-720F-49E7-BC23-8E3F4A5FCD3E/url | {"url":"https://www.google.com/"}
2019-08-19 18:47:39 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/3.142.3 (ruby windows)", "Content-Length"=>"33"}
2019-08-19 18:47:40 INFO Selenium <- {"value":null}
2019-08-19 18:47:40 INFO Selenium -> POST session/C92D8C29-720F-49E7-BC23-8E3F4A5FCD3E/window/current/maximize
The following JSON wire protocol command endpoint is not allowed when server is running in W3C mode.
POST /session/C92D8C29-720F-49E7-BC23-8E3F4A5FCD3E/window/current/maximize
{}
2019-08-19 18:47:40 INFO Selenium <- Unknown error
unexpected response, code=500, content-type="text/plain"
Unknown error
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:98:in `create_response'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/edge/bridge.rb:70:in `maximize_window'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/window.rb:143:in `maximize'
C:/Users/ELLURV/Documents/NetBeansProjects/FutureTestFrameworks/lib/no_code_ui_automation/script.rb:39:in `<main>'
2019-08-19 18:47:50 INFO Selenium -> DELETE session/C92D8C29-720F-49E7-BC23-8E3F4A5FCD3E/window
2019-08-19 18:47:50 INFO Selenium <- {"value":[]}
The following JSON wire protocol command endpoint is not allowed when server is running in W3C mode.
GET /shutdown

`

**Comment by p0deje** [comment]
My apologies for not replying to the issue quickly. I'm seeing in logs:

```
The following JSON wire protocol command endpoint is not allowed when server is running in W3C mode.
```

Does it mean that Edge driver is running in W3C mode?  Does it work when you run the driver with `--jwp`?

**Comment by evnraja32** [comment]
> My apologies for not replying to the issue quickly - there was a lot going on during the last few months.
> 
> Now, I'm seeing in logs:
> 
> ```
> The following JSON wire protocol command endpoint is not allowed when server is running in W3C mode.
> ```
> 
> Does it mean that Edge driver is running in W3C mode? Does it work when you run the driver with `--jwp`?

Sorry, for replying late. Now I was using Selenium alpha3 and alpha4 and I could no issues the maximize method works as expected.
