### ISSUE TITLE
Interface mobile.NetworkConnection invisible from class loader

### ISSUE THREAD

**Issue by JadouC7** [SeleniumHQ/selenium#7502]
Good morning,
When I try to instantiate the class EventFiringWebDriver I get the following error :

java.lang.IllegalArgumentException: interface org.openqa.selenium.mobile.NetworkConnection is not visible from class loader
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Unknown Source)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Unknown Source)
	at java.lang.reflect.WeakCache$Factory.get(Unknown Source)
	at java.lang.reflect.WeakCache.get(Unknown Source)
	at java.lang.reflect.Proxy.getProxyClass0(Unknown Source)
	at java.lang.reflect.Proxy.newProxyInstance(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.<init>(EventFiringWebDriver.java:96)
...

I am using the following version : 3.14.0
I don't understand why I get this error, besides my code worked a few days ago. Here is the piece of code, I get the error on the last line : 

ChromeOptions copt = new ChromeOptions();
copt.setCapability("goog:loggingPrefs", logpref);
WebDriver driver = new ChromeDriver(copt);
EventFiringWebDriver eventFiring = new EventFiringWebDriver(driver);

What I find the most curious is that I am using ChromeDriver and it is not on a mobile, why would this interface mobile.NetworkConnection be called ?
Thanks in advance for your help.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
