### ISSUE TITLE
WebDriverProxy EPROTO wrong version number

### ISSUE THREAD

**Issue by theredfish** [SeleniumHQ/selenium#7509]
## 🐛 Bug Report

If the selenium server uses the https protocol and the webDriverProxy uses the http protocol, an EPROTO error is thrown. 

```bash
➜  selenium-webdriver git:(master) ✗ node script.js
(node:863) UnhandledPromiseRejectionWarning: Error: EPROTO write EPROTO 140076306990912:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at ClientRequest.<anonymous> (/selenium-webdriver/node_modules/selenium-webdriver/http/index.js:258:15)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at TLSSocket.Socket._destroy (net.js:613:3)
    at TLSSocket.destroy (internal/streams/destroy.js:37:8)
(node:863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:863) UnhandledPromiseRejectionWarning: Error: EPROTO write EPROTO 140076306990912:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at ClientRequest.<anonymous> (/selenium-webdriver/node_modules/selenium-webdriver/http/index.js:258:15)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at TLSSocket.Socket._destroy (net.js:613:3)
    at TLSSocket.destroy (internal/streams/destroy.js:37:8)
(node:863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

## To Reproduce
Gist : https://gist.github.com/theredfish/23c1cfebde99ec1d9827184b1fe47495

```
# start nginx
docker-compose up -d
# then run the script
npm install --save selenium-webdriver
node script.js
```
This test case reproduce the error. Now if you want a passing test case replace `https://a-real-selenium-grid/wd/hub` by `http://a-fake-selenium-grid/wd/hub`. Note the **http** protocol : it works because it's the same protocol.

## Expected behavior
HTTPS requests (e.g selenium commands) can go through a HTTP proxy.

## Environment

OS: ANY
Browser: ANY
Browser version: ANY
Browser Driver version: ANY
Language Bindings version: Javascript / Node v10.16.2
Selenium Grid version (if applicable): ANY

## Related issues
- https://github.com/axios/axios/issues/925

I can provide a pull request - But I will need some help to know where to make the changes.

**Comment by theredfish** [comment]
Hello, PR is coming. It will be available today or tomorrow.

**Comment by theredfish** [comment]
Hello @barancev ,
FYI I close the issue since the PR has been merged. Feel free to reopen it.
