### ISSUE TITLE
Question: I am not able to pass through this Initial Page for IE. "This is the initial start page for the WebDriver server" executes, navigates to app (google.com) and stucks here. 

### ISSUE THREAD

**Issue by keerthib01** [SeleniumHQ/selenium#7522]
I  am not able to pass through this Initial Page for IE. "This is the initial start page for the WebDriver server" executes, navigates to app (google.com) and stucks here. 

Configuration -

Java - 1.8.0_211
Browser - IE 11
Machine - Windows10 - (64 - Bit)
IE Driver - Tried both 64-bit and 32 bit

IE Configuration -
IE 64 bit
Security Zones settings (Protected Mode Enables for all zones)
Zoom - 100%

Can you provide urgent help ? Thanks in Advance.

My Code:

System.setProperty("webdriver.ie.driver", "C:\\Selenium\\IEDriverServer.exe");
WebDriver driver = new InternetExplorerDriver();
driver.get("https://www.google.com/");
driver.findElement(By.name("btnK")).click();

OUTPUT:

Started InternetExplorerDriver server (64-bit)
3.14.0.0
Listening on port 22703
Only local connections are allowed
Aug 28, 2019 1:44:54 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.NoSuchWindowException: Currently focused window has been closed.
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'IN5CD5425F65', ip: '192.168.31.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:22703/, nativeEvents: true, requireWindowFocus: false}, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 29fa2164-69f3-4c18-9170-d80285b10fa6
*** Element info: {Using=name, value=btnK}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:400)
	at org.openqa.selenium.By$ByName.findElement(By.java:284)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
	at DGPortal.sample3.main(sample3.java:21)

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
