### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: failed to write automation extension zip

### ISSUE THREAD

**Issue by bangbangexe** [SeleniumHQ/selenium#7561]
Starting ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}) on port 29734
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: failed to write automation extension zip
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'JWS-L-1115', ip: '192.168.1.115', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '12.0.2'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00CFEB13+1501971]
	Ordinal0 [0x00C7F6D1+980689]
	Ordinal0 [0x00C0765F+489055]
	Ordinal0 [0x00B9E0E6+57574]
	Ordinal0 [0x00B9B933+47411]
	Ordinal0 [0x00BB9800+169984]
	Ordinal0 [0x00BB942D+169005]
	Ordinal0 [0x00BB78EB+162027]
	Ordinal0 [0x00BA0AC7+68295]
	Ordinal0 [0x00BA1B40+72512]
	Ordinal0 [0x00BA1AD9+72409]
	Ordinal0 [0x00C98F37+1085239]
	GetHandleVerifier [0x00D9D7ED+503293]
	GetHandleVerifier [0x00D9D580+502672]
	GetHandleVerifier [0x00DA46AC+531644]
	GetHandleVerifier [0x00D9DFFA+505354]
	Ordinal0 [0x00C90606+1050118]
	Ordinal0 [0x00C9047F+1049727]
	Ordinal0 [0x00C9AF9B+1093531]
	Ordinal0 [0x00C9B103+1093891]
	Ordinal0 [0x00C9A095+1089685]
	BaseThreadInitThunk [0x75B10179+25]
	RtlGetAppContainerNamedObjectPath [0x77CC662D+237]
	RtlGetAppContainerNamedObjectPath [0x77CC65FD+189]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at testModules.TestChrome.main(TestChrome.java:19)

**Comment by barancev** [comment]
Please provide an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by theFrogman** [comment]
Hi @barancev ,

I tried to execute a script using chrome-driver, but it throws an error as: [https://pastebin.com/raw/7cTRcSAk](url)

I've updated Selenium libraries, chrome browser and chrome driver too. Still facing the same issue.

Specs:
- Selenium Version: selenium-java-3.141.59
- Chrome Browser version: 76.0.3809.132
- ChromeDriver version: 76.0.3809.126

As mentioned in [Version selection - Chromedriver](https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection): 

> Each version of ChromeDriver supports Chrome with matching major, minor, and build version numbers. For example, ChromeDriver 73.0.3683.20 supports all Chrome versions that start with 73.0.3683.


Awaiting reply.

Thanks.

**Comment by bangbangexe** [comment]
> Hi @barancev ,
> 
> I tried to execute a script using chrome-driver, but it throws an error as: https://pastebin.com/raw/7cTRcSAk
> 
> I've updated Selenium libraries, chrome browser and chrome driver too. Still facing the same issue.
> 
> Specs:
> 
> * Selenium Version: selenium-java-3.141.59
> * Chrome Browser version: 76.0.3809.132
> * ChromeDriver version: 76.0.3809.126
> 
> As mentioned in [Version selection - Chromedriver](https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection):
> 
> > Each version of ChromeDriver supports Chrome with matching major, minor, and build version numbers. For example, ChromeDriver 73.0.3683.20 supports all Chrome versions that start with 73.0.3683.
> 
> Awaiting reply.
> 
> Thanks.
