### ISSUE TITLE
Error when running Firefox tests on Windows

### ISSUE THREAD

**Issue by kfrajtak** [SeleniumHQ/selenium#7573]
## 🐛 Bug Report

Hi,
can you help me with following issue? [Manager](https://github.com/bonigarcia/webdrivermanager/) correctly gets the driver and then it fails when JVM cannot find class org/openqa/selenium/os/WindowsUtils. I tried to Google this class, but was not able to find out what Maven dependency am I missing. 

```
2019-09-17 11:52:48 [main] DEBUG io.github.bonigarcia.wdm.Preferences - Preference found firefox69=0.25.0 (valid until 2019-09-18 11:21:47)
2019-09-17 11:52:48 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Using geckodriver 0.25.0 (since Mozilla Firefox 69 is installed in your machine)
2019-09-17 11:52:48 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager - Driver geckodriver 0.25.0 found in cache
2019-09-17 11:52:48 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.gecko.driver as C:\Users\kfrajtak\.m2\repository\webdriver\geckodriver\win64\0.25.0\geckodriver.exe

java.lang.NoClassDefFoundError: org/openqa/selenium/os/WindowsUtils
	at rg.openqa.selenium.firefox.FirefoxBinary.locateFirefoxBinariesFromPlatform(FirefoxBinary.java:403)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:109)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:165)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at io.github.bonigarcia.wdm.test.FirefoxTest.setupTest(FirefoxTest.java:52)
```
Thanks,
Karel

## To Reproduce

Clone https://github.com/bonigarcia/webdrivermanager-examples project and run any Firefox test on Windows.

## Expected behavior

I expect the FF test to finish.

## Environment

OS: Windows10
Browser: Firefox
Browser version: 69.0 (64-bit)
Browser Driver version: 71.0.0.7191 (file version taken from geckodriver.exe properties dialog)
Language Bindings version: Java 3.141.59
More env. details in log (see above)

**Comment by diemol** [comment]
Please report this issue to https://github.com/bonigarcia/webdrivermanager-examples or https://github.com/bonigarcia/webdrivermanager/, it could be that there was a bug there. I can see that the repo was updated a few hours ago.

If this is a Selenium bug, please provide a reproducible case using only this project please.

**Comment by kfrajtak** [comment]
Thanks for reply.
