### ISSUE TITLE
"Error communicating with the remote browser" quitting Chrome

### ISSUE THREAD

**Issue by eelgheez** [SeleniumHQ/selenium#758]
When using the latest selenium-server-2.46.0.jar, chromedriver 2.16 and the latest snapshot of chromium on a Linux Selenium node, I saw one in a series of Java tests fail at the end with a WebDriverException in RemoteWebDriver#quit(),

https://code.google.com/p/chromedriver/issues/detail?id=1144

From reading RemoteWebDriver.java I figured the exception got caught, logged and re-thrown as UnreachableBrowserException.  I understand I could work the issue around by ignoring the exception in my test class method that overrides FluentLenium's FluentTest#quit().  Alternatively, I wonder if it makes sense to ignore the exception directly in RemoteWebDriver#quit(), similarly to #434.

**Comment by eelgheez** [comment]
I could not get to test my trivial change with a trivial test I added to RemoteWebDriverInitialization.java as the preceding tests fail.  (I could get the javascript ones succeed by using a bigger virtual display, 
```
$ xvfb-run -s "-screen 0 1920x1080x8" ./go clean test
[..]
Testing: //java/client/test/org/openqa/selenium/firefox:test_synthesized
go aborted!
org.apache.tools.ant.BuildException: Test org.openqa.selenium.firefox.SynthesizedFirefoxDriverTests failed

$ cat build/test_logs/TEST-test_synthesized-org.openqa.selenium.firefox.SynthesizedFirefoxDriverTests.txt
[..]
Testcase: requiredNativeEventCapabilityShouldHavePriority took 3.146 sec
    FAILED
Native events capability should be set enabled
junit.framework.AssertionFailedError: Native events capability should be set enabled
    at org.openqa.selenium.firefox.FirefoxCapabilitiesTest.requiredNativeEventCapabilityShouldHavePriority(FirefoxCapabilitiesTest.java:149)
    at org.openqa.selenium.testing.SeleniumTestRunner$2.evaluate(SeleniumTestRunner.java:110)
    at org.openqa.selenium.testing.SeleniumTestRunner.runChild(SeleniumTestRunner.java:83)

Testcase: testDisableJavascriptCapability took 2.857 sec
Testcase: testDisableHandlesAlertsCapability took 2.926 sec
Testcase: enableNativeEventCapability took 3.043 sec
    FAILED
Capability nativeEvents should be set to true
junit.framework.AssertionFailedError: Capability nativeEvents should be set to true
    at org.openqa.selenium.firefox.FirefoxCapabilitiesTest.configureCapability(FirefoxCapabilitiesTest.java:130)
    at org.openqa.selenium.firefox.FirefoxCapabilitiesTest.enableNativeEventCapability(FirefoxCapabilitiesTest.java:111)
    at org.openqa.selenium.testing.SeleniumTestRunner$2.evaluate(SeleniumTestRunner.java:110)
    at org.openqa.selenium.testing.SeleniumTestRunner.runChild(SeleniumTestRunner.java:83)

Testcase: disableNativeEventCapability took 3.22 sec
[..]
```
I guess I can try installing headers and libraries needed to build libimehandler64.so and others.  Besides, I see a compiler error,
```
Compiling: //cpp:imehandler64 as build/cpp/amd64/libimehandler64.so
cpp/imehandler/linux/src/ibushandler.cpp: In member function ‘virtual std::string IBusHandler::GetActiveEngine() const’:
cpp/imehandler/linux/src/ibushandler.cpp:70:37: error: ‘IBusEngineDesc’ has no member named ‘name’
     engine_name = std::string(desc->name);
                                     ^
cpp/imehandler/linux/src/ibushandler.cpp: In member function ‘IBusInputContext* IBusHandler::GetCurrentInputContext() const’:
cpp/imehandler/linux/src/ibushandler.cpp:88:3: error: ‘IBusConnection’ was not declared in this scope
   IBusConnection* conn = ibus_bus_get_connection(bus_);
   ^
```

**Comment by eelgheez** [comment]
OK, I tested it by invoking a sub-target "test_remote" mentioned in Rakefile.
```
xvfb-run -n 1 -s "-screen 0 1920x1080x24" bash -c "fluxbox & ./go test_remote"
```
I observed the affected test succeed after few adjustments,
```
Testing: //java/client/test/org/openqa/selenium/remote:client-tests
Compiling: //java/client/test/org/openqa/selenium/remote:remote-driver-tests as build/java/client/test/org/openqa/selenium/remote/remote-driver-tests.jar
```

The remaining tests appear to have succeeded, according to the latest file in build/test_logs.  An unrelated error message apparently came from the virtual X server,
```
Testing: //java/client/test/org/openqa/selenium/remote:remote-driver-tests
Failed to read: session.screen0.titlebar.left
Setting default value
Failed to read: session.screen0.titlebar.right
Setting default value
Compiling: //java/server/test/org/openqa/selenium/remote/server:lib as build/java/server/test/org/openqa/selenium/remote/server/lib.jar
Testing: //java/server/test/org/openqa/selenium/remote/server:small-tests
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 2246319 requests (2246313 known processed) with 0 events remaining.
```

**Comment by barancev** [comment]
We're not going to hide exceptions that occur on the driver side. If this is a driver issue it should be fixed in the driver. If it is a configuration issue the client code should handle the exception. Selenium is just a man-in-the-middle.
