### ISSUE TITLE
Actions of selenium Select fail with chrome driver 76

### ISSUE THREAD

**Issue by BathiyaL** [SeleniumHQ/selenium#7587]
## 💥 Regression Report

With chromedriver upgrade with 76.0.3809.100 I faced below issue when performing selectByVisibleText andselectByValue actions.

**NOTE:** During further analysis we observed this is not happening with all Select elements, but with Select elements which have **_prototype.js_**.
`<script src="https://ajax.googleapis.com/ajax/libs/prototype/1.6.1/prototype.js" type="text/javascript"></script`

**Exception**

```
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: script returns unexpected result
  (Session info: chrome=76.0.3809.100)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LKCONBLADDUWA02', ip: '192.168.8.101', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.100, chrome: {chromedriverVersion: 76.0.3809.68 (420c9498db8ce..., userDataDir: C:\Users\BLADDU~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:59594}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: c8321802c66a038a42aafd120f3f6ba2
*** Element info: {Using=xpath, value=.//option[normalize-space(.) = "Mercedes SLK"]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.findElements(RemoteWebElement.java:204)
	at org.openqa.selenium.remote.RemoteWebElement.findElementsByXPath(RemoteWebElement.java:265)
	at org.openqa.selenium.By$ByXPath.findElements(By.java:348)
	at org.openqa.selenium.remote.RemoteWebElement.findElements(RemoteWebElement.java:177)
	at org.openqa.selenium.support.ui.Select.selectByVisibleText(Select.java:113)
	at com.sae.selenium.mytest.SelectBoxIssueWithPrototypeJS.main(SelectBoxIssueWithPrototypeJS.java:29)
```

**Last working chromedriver version**

Worked up to version: chrome 74

Stopped working in version: 76.0.3809.100 

**Steps to Reproduce**
Detailed steps to reproduce the behavior:

```
driver.get("http://www.softwareautomationengineer.com/demo-site/rca/prototypejs-demopage.html");
	
		Select comboBox = new Select(driver.findElement(By.id("dropdown")));
		comboBox.selectByVisibleText("Mercedes SLK");
```

**Environment**
OS: Windows 10
Browser: Chrome
Browser version: 76
Chrome Driver version: 76.0.3809.100
Language Bindings version: Java

**Comment by barancev** [comment]
Can you reproduce this issue with Chrome 77? It works for me.

**Comment by BathiyaL** [comment]
Hi 
Seems this issue with the chormedirver 76.0.3809.100, this issue is in 76.0.3809.100.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3139#c3
Thanks
