### ISSUE TITLE
WebElement call takeScreenshot show UnsupportedOperationError

### ISSUE THREAD

**Issue by wenJanus** [SeleniumHQ/selenium#7618]
## To Reproduce

Detailed steps to reproduce the behavior:

//Test code:
const cards =
      await this.browser.findElementsByXpath('//div[@class="elLayouts-ContentRegion elLayouts-ContentRegion-card"]');
    expect(cards.length).equals(3);
    await takeScreenshot(cards[0], '111');

//Function code:
async function takeScreenshot(el: WebElement, name: string): Promise<any> {
  await el.takeScreenshot().then(async (png: any) => {
    await saveImage(name, png);
  });
}

//Error:
UnsupportedOperationError: GET /session/483ce73f-9647-4d0e-bc98-8a8d1663af98/element/863fba10-dc17-4571-8e2c-3b391305363f/screenshot
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: '476f8e4ac3c5', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-64-generic', java.version: '1.8.0_151'
Driver info: driver.version: unknown
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /project/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  From: Task: WebElement.takeScreenshot(false)
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.takeScreenshot (node_modules/selenium-webdriver/lib/webdriver.js:2379:17)
      at Object.takeScreenshot (src/seleniumlib/utils.ts:44:12)
      at LocalBackupToolsPage.checkModuleUx (src/pages/ssm/seaBackupToolsPage.ts:68:11)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Context.<anonymous> (src/testcase/ssm/ssm-backupTools.ts:35:12)

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
root@guitest:/project# uname -a
Linux guitest 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 GNU/Linux

Browser: 
selenium-standalone-firefox-debug
bin  firefox-57.0  geckodriver-0.19.1  selenium

Browser version: 
Browser Driver version: 
geckodriver-0.19.1

Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
You're using outdated software that does not support this operation. Please upgrade the browser, the driver and the client binding to the latest version.
