### ISSUE TITLE
selenium-4.0.0-alpha-3 has build error in Ubuntu 18.04

### ISSUE THREAD

**Issue by RonKalian** [SeleniumHQ/selenium#7647]
## 🐛 Bug Report

selenium-4.0.0-alpha-3 fails to build (using README instructions) on Ubuntu 18.04

## To Reproduce

Detailed steps to reproduce the behavior:

1. download selenium-4.0.0-alpha-3.tar.gz from https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.0.0-alpha-3
2. extract it from tar.gz, follow instructions in README to install Bazel, etc.
3. my JDK version is:  
`openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)`
4. `export $JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/`
5. run `bazel build java/...` (tried with and without `sudo`)

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 0c7c1394-489a-4ef3-8192-b2c5415e23e7
INFO: Analyzed 561 targets (294 packages loaded, 6663 targets configured).
INFO: Found 561 targets...
ERROR: /home/rk/.cache/bazel/_bazel_root/6bda101da7da8a5fadeb10e93885527f/external/bazel_tools/tools/jdk/BUILD:318:1: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) java failed: error executing command external/remotejdk11_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1862)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1851)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
	at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
	at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
	at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
	at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Caused by: java.nio.file.NoSuchFileException: external/local_jdk
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.isSameFile(UnixFileSystemProvider.java:333)
	at java.base/java.nio.file.Files.isSameFile(Files.java:1530)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1860)
	... 14 more
INFO: Elapsed time: 41.413s, Critical Path: 1.23s
INFO: 4 processes: 4 remote cache hit.
FAILED: Build did NOT complete successfully

## Environment

OS: Ubuntu 18.04 

$ uname -a
Linux <computer-name> 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by RonKalian** [comment]
... and a suggestion - it would be really helpful if you could provide .jar files for Selenium 4 Alpha releases

**Comment by barancev** [comment]
There is a distribution package that contains all jar files including all dependedcies (find there a zip file):
http://selenium-release.storage.googleapis.com/index.html?path=4.0-alpha/

**Comment by RonKalian** [comment]
thank you @barancev I used `selenium-server-4.0.0-alpha-3.jar` instead of building it

**Comment by barancev** [comment]
Can we close the issue then?
