### ISSUE TITLE
Unable to Close  the current  firefox browser (version 39.0)  window using drive.close() Method binding with selenium  API version 2.46

### ISSUE THREAD

**Issue by msrsharmaqa** [SeleniumHQ/selenium#768]
Hi,
When i try to close the  current open browser window using Firefox version 39.0  binded with java 1.6 version and  web driver API version V2.46 the current window not getting closed but when i try  to execute the quit command after  close the command then it is closing the browser window with the following error

**Jul 12, 2015 2:17:38 PM org.openqa.selenium.os.UnixProcess$SeleniumWatchDog destroyHarder
INFO: Command failed to close cleanly. Destroying forcefully (v2). org.openqa.selenium.os.UnixProcess$SeleniumWatchDog@716de067
Jul 12, 2015 2:17:38 PM org.openqa.selenium.os.ProcessUtils killWinProcess
WARNING: Process refused to die after 10 seconds, and couldn't taskkill it
java.lang.NullPointerException: Unable to find executable for: taskkill
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
	at org.openqa.selenium.os.UnixProcess.<init>(UnixProcess.java:62)
	at org.openqa.selenium.os.CommandLine.<init>(CommandLine.java:38)**

driver.close()--Not closing the current open browser window
driver.quit-- close the window with the above error

Attached screen shot is for reference

Hope you will look in to the issue and  comes out with solution

**(PS: driver.close() is working fine in chrome browser)**

Thanks in Advance!!

![fig1](https://cloud.githubusercontent.com/assets/13297497/8637162/e55f40ec-28a1-11e5-9998-66e41cbf00c4.png)

**Comment by barancev** [comment]
"Unable to find executable for: taskkill" means that the directory c:\windows\system32 is not present in the PATH environment variable. Please tune your environment.

**Comment by msrsharmaqa** [comment]
Hi,
 I have set  c:\windows\system32 environment variable but still i am getting the same error.Attached image for refernce

Error:

**Jul 13, 2015 6:41:32 PM org.openqa.selenium.os.UnixProcess$SeleniumWatchDog destroyHarder
INFO: Command failed to close cleanly. Destroying forcefully (v2). org.openqa.selenium.os.UnixProcess$SeleniumWatchDog@2a313170
Jul 13, 2015 6:41:32 PM org.openqa.selenium.os.ProcessUtils killWinProcess
WARNING: Process refused to die after 10 seconds, and couldn't taskkill it
java.lang.NullPointerException: Unable to find executable for: taskkill
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
	at org.openqa.selenium.os.UnixProcess.<init>(UnixProcess.java:62)
	at org.openqa.selenium.os.CommandLine.<init>(CommandLine.java:38)
	at org.openqa.selenium.os.WindowsUtils.killPID(WindowsUtils.java:172)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:138)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:248)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$2(UnixProcess.java:245)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:124)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
	at org.openqa.selenium.firefox.FirefoxBinary.quit(FirefoxBinary.java:259)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit(NewProfileExtensionConnection.java:202)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit(FirefoxDriver.java:376)
	at org.openqa.selenium.firefox.FirefoxDriver.stopClient(FirefoxDriver.java:322)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:477)
	at webDriver.LoginAndLogout.main(LoginAndLogout.java:27)
Exception in thread "main" java.lang.RuntimeException: Process refused to die after 10 seconds, and couldn't taskkill it: Unable to find executable for: taskkill
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:142)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:248)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$2(UnixProcess.java:245)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:124)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
	at org.openqa.selenium.firefox.FirefoxBinary.quit(FirefoxBinary.java:259)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit(NewProfileExtensionConnection.java:202)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit(FirefoxDriver.java:376)
	at org.openqa.selenium.firefox.FirefoxDriver.stopClient(FirefoxDriver.java:322)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:477)
	at webDriver.LoginAndLogout.main(LoginAndLogout.java:27)
Caused by: java.lang.NullPointerException: Unable to find executable for: taskkill
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
	at org.openqa.selenium.os.UnixProcess.<init>(UnixProcess.java:62)
	at org.openqa.selenium.os.CommandLine.<init>(CommandLine.java:38)
	at org.openqa.selenium.os.WindowsUtils.killPID(WindowsUtils.java:172)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:138)
	... 11 more**
![fig3](https://cloud.githubusercontent.com/assets/13297497/8650220/dc03b27e-298e-11e5-8ce2-046391a33417.JPG)
![fig4](https://cloud.githubusercontent.com/assets/13297497/8650223/e14bb89e-298e-11e5-9318-588268f2f32a.jpg)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by msrsharmaqa** [comment]
Hi,
In the above i have copy pasted the  error which i have  got and also  i attached the screen shot which shows the  i have set the environment variable  after that also we are getting the error

**Comment by barancev** [comment]
Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
The community members will help you to tune the environment properly.

**Comment by msrsharmaqa** [comment]
Ok. Do you mean path which i have  set is not correct ?
