### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException: POST /session/f2f6467d30e8890b9adde945446c2bda/element//click

### ISSUE THREAD

**Issue by ingen2** [SeleniumHQ/selenium#7683]
Hi 
When I use **standalone-chrome-debug** ,  UnsupportedCommandException occurred in my code 
But if I use **standalone-chrome** (no debug version) , my code ran successfully with out any error 

stack trace: 
`org.openqa.selenium.UnsupportedCommandException: POST /session/f2f6467d30e8890b9adde945446c2bda/element//click
       Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '829a5f2ca5ba', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-8-amd64', java.version: '1.8.0_222'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.decode(AbstractHttpCommandCodec.java:261)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.decode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.grid.session.remote.ProtocolConverter.handle(ProtocolConverter.java:74)
	at org.openqa.selenium.grid.session.remote.RemoteSession.execute(RemoteSession.java:129)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

--------------------

I using docker to run chrome driver debug:
`docker run -d -p 9510:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug`

Or(when no error ):
`docker run -d -p 9510:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome`

**Comment by barancev** [comment]
It seems to be a bug in a binding (a client library). What binding do you use?

**Comment by AutomatedTester** [comment]
Closing as requested info was not given
