### ISSUE TITLE
Headless and Extenstion

### ISSUE THREAD

**Issue by GodStar88** [SeleniumHQ/selenium#7701]
Hello, I am using Extention on chrome driver.
It doesn't work when i use headless mode/

OpenQA.Selenium.WebDriverException: unknown error: failed to wait for extension background page to load: chrome-extension://lkmofgnohbedopheiphabfhfjgkhfcgf/_generated_background_page.html
from unknown error: page could not be found: chrome-extension://lkmofgnohbedopheiphabfhfjgkhfcgf/_generated_background_page.html
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)

How can i fix that? please help me, thanks

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
