### ISSUE TITLE
Setting safari:automaticInspection raises a GridException

### ISSUE THREAD

**Issue by neben** [SeleniumHQ/selenium#7790]
## 🐛 Bug Report

Setting `safari:automaticInspection` or `safari:automaticProfiling` raises a `GridException`. Also, I'm unsure if setting these capabilities has any effect on current Safari versions and if they should be removed.

## To Reproduce

Using Karma with Selenium Grid and the following config fails:
```
[...]
      SafariCIGrid: {
        base: 'WebDriver',
        browserName: 'safari',
        config: webdriverConfig,
        technologyPreview: true,
        "safari:automaticInspection": true
      },
[...]
```
This is the error message on the hub:
```
17:46:37.329 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {base: WebDriver, browserName: safari, javascriptEnabled: true, safari:automaticProfiling: true, tags: [], technologyPreview: true, testName: Karma test, version: }
17:46:37.330 INFO [RequestHandler.process] - Error forwarding the new session cannot find : Capabilities {base: WebDriver, browserName: safari, javascriptEnabled: true, safari:automaticProfiling: true, tags: [], technologyPreview: true, testName: Karma test, version: }
org.openqa.grid.common.exception.CapabilityNotPresentOnTheGridException: cannot find : Capabilities {base: WebDriver, browserName: safari, javascriptEnabled: true, safari:automaticProfiling: true, tags: [], technologyPreview: true, testName: Karma test, version: }
	at org.openqa.grid.internal.ProxySet.verifyAbilityToHandleDesiredCapabilities(ProxySet.java:153)
	at org.openqa.grid.internal.DefaultGridRegistry.addNewSessionRequest(DefaultGridRegistry.java:217)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:111)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
2019-11-14 17:46:37.379:WARN:osjs.HttpChannel:qtp811587677-15: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: 
```
## Expected behavior

The session should be created, which it is, if the offending parameter is removed.

## Test script or set of commands reproducing this issue
For example, `karma start --browsers SafariCIGrid`

## Environment

OS: macOS 10.15.1
Browser: Safari
Browser version: Version 13.0.3 (15608.3.10.1.4) and Technology Preview Release 95 (Safari 13.1, WebKit 15609.1.7)
Browser Driver version: Built-in SafariDriver
Language Bindings version: Karma
Selenium Grid version (if applicable): 3.141.59

**Comment by liviulupei** [comment]
This is one of the reasons why I migrated my tests to [Endtest](https://endtest.io).

**Comment by jimevans** [comment]
@liviulupei You’ve now made the same unhelpful spam-like reply in multiple issues. Please don’t do it again. If you’re a strong advocate for tools other than Selenium, that’s fine, but it doesn’t have a place in this issue tracker.

**Comment by diemol** [comment]
This might have been an issue with Grid 3, but I just [tested](https://github.com/diemol/selenium-issues/tree/master/selenium/issue-7790) this with Grid 4 and no errors were shown. Please try with Grid 4 and if you bump into this issue again, create a new issue with all the template fields filled out.
