### ISSUE TITLE
webDriver.WebElement ".isDisplayed" is not a function

### ISSUE THREAD

**Issue by Donsky-Osano** [SeleniumHQ/selenium#7816]
## 🐛 Bug Report

Running selenium-webdriver JavaScript's driver with the following code and getting this error:
### Code
```
"use strict"
require("chromedriver");
const {Builder, By, Key, until} = require("selenium-webdriver");

(async function () {
    const driver = await new Builder().forBrowser("chrome").build();
    try {
        await driver.get("http://domain.tld:8080");
        await driver.findElement(By.css("div.buttons > button.accept")).sendKeys(Key.ENTER);
        const firstResult = await driver.wait(until.elementIsVisible(By.className("widget")), 10000);
        console.log(firstResult);
    } catch ( error ){
      console.error( error )
    } finally {
        driver.quit();
    }
})();
```
### Stack trace:
```
TypeError: element.isDisplayed is not a function
    at /Users/donsky/Projects/Testing/node_modules/selenium-webdriver/lib/until.js:303:20
    at Promise (/Users/donsky/Projects/Testing/node_modules/selenium-webdriver/lib/webdriver.js:825:19)
    at new Promise (<anonymous>)
    at evaluateCondition (/Users/donsky/Projects/Testing/node_modules/selenium-webdriver/lib/webdriver.js:823:14)
    at pollCondition (/Users/donsky/Projects/Testing/node_modules/selenium-webdriver/lib/webdriver.js:835:9)
    at Promise (/Users/donsky/Projects/Testing/node_modules/selenium-webdriver/lib/webdriver.js:849:7)
    at new Promise (<anonymous>)
    at Driver.wait (/Users/donsky/Projects/Testing/node_modules/selenium-webdriver/lib/webdriver.js:832:18)
    at example (/Users/donsky/Projects/Testing/server.js:14:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## To Reproduce

run the code snippet with the packages listed at the top of the snippet, it will produce the above error & stack track 

## Expected behavior

The element with css selector `.widget` should be set as the 'firstResult' variable

## Test script or set of commands reproducing this issue

`npm i chromedriver selenium-webdriver && node script.js`

## Environment

OS: OSX 10.15.1
Browser Driver version: ChromeDriver:Latest
NodeVersion: 10.16.3

**Comment by pawelusfr** [comment]
@Donsky-Osano  `until.elementIsVisible` takes `WebElement` but you are passing a `By`. You need to do `findElement` first and pass that to `elementIsVisible`

**Comment by AutomatedTester** [comment]
As the previous comment says, the wrong item was passed in
