### ISSUE TITLE
"unable to send message to renderer" using Selenium, Java, chrome

### ISSUE THREAD

**Issue by dougm123** [SeleniumHQ/selenium#7823]
I am attempting to get Selenium working on a Windows 10 PC.  I'm running locally.  All attempts to run the script lead to **"Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created from disconnected: unable to send message to renderer"**

I was hoping that someone might have some fresh troubleshooting ideas for me.  I've already torn this down and rebuilt the set up a few times to end up with the same result.  (I've also tried a bunch of other things, but I don't want to confuse the example provided.)

**The set up steps followed:** https://www.guru99.com/installing-selenium-webdriver.html

**Expected:** The script running is expected to launch chrome, navigate to yahoo and close.  

**What happens:** Chrome launches, "data:," appears in the URL text box, and chrome closes with the error mentioned above.  So, it didn't navigate to yahoo and an unexpected error was received.

**Java seems fine from command line.**
C:\Users\dougm>java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

**Chromedriver seems fine from command line.**
C:\Users\dougm>chromedriver
Starting ChromeDriver 78.0.3904.105 *** on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

**The chrome driver is the latest for the version of chrome I have.**
From selenium site.
"ChromeDriver 78.0.3904.105
Supports Chrome version 78
Includes the following change over version 78.0.3904.70:
Fixed incorrect calculation of element coordinates
For more details, please see the release notes."

**The versions for the example in use are:**
Starting ChromeDriver 78.0.3904.105 ...
(Session info: chrome=78.0.3904.108)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'WINDOWS-1H1GR1Q', ip: '10.0.0.207', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.1'
Driver info: driver.version: ChromeDriver

**The full error (script at end):**
Starting ChromeDriver 78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877}) on port 30991
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created
from disconnected: unable to send message to renderer
  (Session info: chrome=78.0.3904.108)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'WINDOWS-1H1GR1Q', ip: '10.0.0.207', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.1'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00C4A923+1550627]
	Ordinal0 [0x00BCA731+1025841]
	Ordinal0 [0x00B4C715+509717]
	Ordinal0 [0x00B43E80+474752]
	Ordinal0 [0x00B44135+475445]
	Ordinal0 [0x00B43BE5+474085]
	Ordinal0 [0x00B49DBE+499134]
	Ordinal0 [0x00B43B98+474008]
	Ordinal0 [0x00B4454B+476491]
	Ordinal0 [0x00B4401A+475162]
	Ordinal0 [0x00B44135+475445]
	Ordinal0 [0x00B43BE5+474085]
	Ordinal0 [0x00B4863D+493117]
	Ordinal0 [0x00B43B98+474008]
	Ordinal0 [0x00B4454B+476491]
	Ordinal0 [0x00B4401A+475162]
	Ordinal0 [0x00B44135+475445]
	Ordinal0 [0x00B43BE5+474085]
	Ordinal0 [0x00B47CF7+490743]
	Ordinal0 [0x00B43B98+474008]
	Ordinal0 [0x00B4454B+476491]
	Ordinal0 [0x00B4401A+475162]
	Ordinal0 [0x00B44135+475445]
	Ordinal0 [0x00B43BE5+474085]
	Ordinal0 [0x00B407DC+460764]
	Ordinal0 [0x00B43B98+474008]
	Ordinal0 [0x00B43A74+473716]
	Ordinal0 [0x00B4D360+512864]
	Ordinal0 [0x00AFB649+177737]
	Ordinal0 [0x00AFA8ED+174317]
	Ordinal0 [0x00AF8CDB+167131]
	Ordinal0 [0x00AE144A+70730]
	Ordinal0 [0x00AE24D0+74960]
	Ordinal0 [0x00AE2469+74857]
	Ordinal0 [0x00BE42F7+1131255]
	GetHandleVerifier [0x00CE711D+523789]
	GetHandleVerifier [0x00CE6EB0+523168]
	GetHandleVerifier [0x00CEE207+552695]
	GetHandleVerifier [0x00CE791A+525834]
	Ordinal0 [0x00BDB82C+1095724]
	Ordinal0 [0x00BE636B+1139563]
	Ordinal0 [0x00BE64D3+1139923]
	Ordinal0 [0x00BE5455+1135701]
	BaseThreadInitThunk [0x77000419+25]
	RtlGetAppContainerNamedObjectPath [0x77BA662D+237]
	RtlGetAppContainerNamedObjectPath [0x77BA65FD+189]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at newSelenium.MyClass.main(MyClass.java:13)

**Script:**
package newSelenium;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class MyClass {

	 public static String driverPath = "C:\\Users\\dougm\\Selenium\\";
	 public static WebDriver driver;
	 
		public static void main(String []args) {
			System.out.println("launching chrome browser");
			System.setProperty("webdriver.chrome.driver", driverPath+"chromedriver.exe");
			driver = new ChromeDriver();
			driver.navigate().to("http://yahoo.com");
			driver.close();
		}
	
}

**Comment by barancev** [comment]
Please report this issue to chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list
