### ISSUE TITLE
Selenium hangs indefinitely on html5 video page

### ISSUE THREAD

**Issue by SwissCheese5** [SeleniumHQ/selenium#7831]
## 🐛 Bug Report

When selenium redirects to a page with nothing but a direct video file (html video tag, opening an html5 video player), selenium stops execution on the button click line that triggered the redirect.

![image](https://user-images.githubusercontent.com/7407478/69911236-35f5d100-1421-11ea-92b0-27c4e0e7a359.png)
I can't share this link because the video expires in a few hours, however any html5 video link will work, such as this one: https://media.w3.org/2010/05/sintel/trailer.mp4

I have tested this with two different kinds of direct html5 video content page provider servers. One has Partial Content enabled and the other doesn't. This doesn't matter but it was a personal finding. The result does not change.

## To Reproduce

I tried setting the time-out for both page load and script load, and those DID throw time-out exceptions which is what I wanted, however, I cannot retrieve the direct url anymore, calling driver.getDirectUrl() throws a timeout exception. So after timing out, there is no way to access the page information.

```java
driver.manage().timeouts().setScriptTimeout(5, TimeUnit.SECONDS);
driver.manage().timeouts().pageLoadTimeout(5, TimeUnit.SECONDS);
```

I tried something a little hacky to try getting around it as follows:

```java
		try {
			Thread thread = new Thread(() -> {
				driver.findElement(By.id("surfbtn")).click();
			});
			thread.run();
			Thread.sleep(5000);
		} catch (Exception e) {
			e.printStackTrace();
		}
		final String url = driver.getCurrentUrl();
```
What this does it is click the button on a separate thread and get the direct url while the driver is working anyways. This failed so I ran out of ideas.

## Expected behavior

I expected after the page finished loading that execution continued. It does not, it hangs on the .click() method indefinitely. I also expected getDirectURL to return the url instead of throw a timeout exception.

## Test script or set of commands reproducing this issue

There is no solid test script I can provide. It is, however, very simple to reproduce.
Simply acquire a direct html5 video page like the following:
```
https://media.w3.org/2010/05/sintel/trailer.mp4
```
and use driver.get() on it

```java
		WebDriver driver = new ChromeDriver();

		driver.get("https://media.w3.org/2010/05/sintel/trailer.mp4");
```
ANYTHING after driver.get will NOT run. Even after the page loads completely and the video finishes playing.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: Version 78.0.3904.108 (Official Build) (64-bit)
Language Bindings version: Java 8 (update 101)
Selenium version: 4.0.0-alpha-3

**Comment by diemol** [comment]
Hi @SwissCheese5,

I wrote a small [script](https://github.com/diemol/selenium-issues/blob/master/selenium/issue-7831/src/test/java/VideoReproduction.java) to reproduce the issue based on your instructions but I did not bump into the problem you describe. 

Could you please provide a script we can use to reproduce the issue?

**Comment by liviulupei** [comment]
I tried it with [Endtest](https://endtest.io) and it works just fine.

**Comment by SwissCheese5** [comment]
@diemol I ran your script (copy paste), it hangs on the video page:

![image](https://user-images.githubusercontent.com/7407478/70374293-71007480-18f9-11ea-80d3-27d7f383c49b.png)

The log (nothing significant): 
```
Starting ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90) on port 36863
Only local connections are allowed.
[1575719712.543][WARNING]: Timed out connecting to Chrome, retrying...
Dec 07, 2019 1:55:14 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
```


Could be a conflict with guava? I couldn't run selenium without overriding the guava dependency

Here's my gradle script:

```
plugins {
	id 'org.springframework.boot' version '2.2.1.RELEASE'
	id 'io.spring.dependency-management' version '1.0.8.RELEASE'
	id 'java'
}

group = '<...>'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }

}

dependencies {
// https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
	compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.0.0-alpha-3'

// https://mvnrepository.com/artifact/com.google.guava/guava
	compile group: 'com.google.guava', name: 'guava', version: '28.1-jre'


	compile group: 'commons-io', name: 'commons-io', version: '2.6'
	compile 'com.google.firebase:firebase-admin:6.11.0'
	compile 'com.google.cloud:google-cloud-storage:1.101.0'
	compile group: 'net.bramp.ffmpeg', name: 'ffmpeg', version: '0.6.2'
	compile group: 'net.lingala.zip4j', name: 'zip4j', version: '2.2.4'
	implementation 'com.github.sapher:youtubedl-java:-SNAPSHOT'
	implementation 'org.springframework.boot:spring-boot-starter'
	compile("org.springframework.boot:spring-boot-starter-web")
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
}

test {
	useJUnitPlatform()
}
```

**Comment by diemol** [comment]
I am not sure if is an issue with Guava, but I can see that you are running an old ChromeDriver version to control Chrome 78.
Here is the log I see when I run the script:
```
Starting ChromeDriver 78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877}) on port 30022
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1575721434.428][WARNING]: FromSockAddr failed on netmask
Dec 07, 2019 1:23:56 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
https://media.w3.org/2010/05/sintel/trailer.mp4
https://www.google.com/?gws_rd=ssl
Quitting
```

Perhaps try using the latest ChromeDriver.

**Comment by SwissCheese5** [comment]
@diemol 
It crashes on the latest chrome driver

```
Starting ChromeDriver 79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}) on port 30338
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 79
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-FPD7KCB', ip: '192.168.1.106', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x004CA113+1548563]
	Ordinal0 [0x0044DDA1+1039777]
	Ordinal0 [0x003CE485+517253]
	Ordinal0 [0x0035FD34+64820]
	Ordinal0 [0x0035C61E+50718]
	Ordinal0 [0x0037B797+178071]
	Ordinal0 [0x0037B59D+177565]
	Ordinal0 [0x003795FB+169467]
	Ordinal0 [0x0036160A+71178]
	Ordinal0 [0x00362690+75408]
	Ordinal0 [0x00362629+75305]
	Ordinal0 [0x004671B7+1143223]
	GetHandleVerifier [0x00562B46+507814]
	GetHandleVerifier [0x00562864+507076]
	GetHandleVerifier [0x00569F47+537511]
	GetHandleVerifier [0x00563402+510050]
	Ordinal0 [0x0045F29C+1110684]
	Ordinal0 [0x0046938B+1151883]
	Ordinal0 [0x004694F3+1152243]
	Ordinal0 [0x004683F5+1147893]
	BaseThreadInitThunk [0x75B36359+25]
	RtlGetAppContainerNamedObjectPath [0x77DA7B74+228]
	RtlGetAppContainerNamedObjectPath [0x77DA7B44+180]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
```

**Comment by diemol** [comment]
@SwissCheese5 have you read the exception?
`Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 79`

If you are using Chrome 78, then ChromeDriver 78.x is needed.

**Comment by SwissCheese5** [comment]
That fixed it. Thank you.
