### ISSUE TITLE
addCookie not working in IE8 and IE 9

### ISSUE THREAD

**Issue by arpit-dhandhania** [SeleniumHQ/selenium#802]
Hi I am using selenium 2.45 and IEDriverServer 2.45 but the addcookie method is throwing following error 

IE8:
org.openqa.selenium.UnhandledAlertException: Modal dialog present: 
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'VLR2-7200013012', ip: '172.26.32.96', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=8, platform=WINDOWS, proxy={proxyType=direct}, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:36046/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: a7fd5c24-c489-49db-afac-018675bbbb97
Command duration or timeout: 1.52 seconds
Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.18-164.el5', java.version: '1.7.0_65'
Session ID: af1bed24-2b17-4e1c-87f1-c25bba4a14c7
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, enablePersistentHover=true, ignoreZoomSetting=false, ie.ensureCleanSession=false, enableElementCacheCleanup=true, browserName=internet explorer, unexpectedAlertBehaviour=dismiss, webdriver.remote.sessionid=af1bed24-2b17-4e1c-87f1-c25bba4a14c7, version=8, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:36046/, handlesAlerts=true, ie.forceCreateProcessApi=false, proxy={proxyType=direct}, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:187)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:151)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.addCookie(RemoteWebDriver.java:627)
	at TryBrowser2.main(TryBrowser2.java:50)

IE9: 

Caused by: org.openqa.selenium.WebDriverException: Unable to add cookie to page (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 63 milliseconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'BLR2-7200013154', ip: '172.26.34.41', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=9, platform=WINDOWS, proxy={proxyType=direct}, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:23186/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: c78a07e6-011c-485f-ae1a-4301a1f18b9d
Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.18-164.el5', java.version: '1.7.0_65'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.addCookie(RemoteWebDriver.java:681)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringOptions.addCookie(EventFiringWebDriver.java:503)
	at org.openqa.selenium.remote.server.handler.AddCookie.call(AddCookie.java:42)
	at org.openqa.selenium.remote.server.handler.AddCookie.call(AddCookie.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I have tried several versions of selenium along with IEDriver starting from 2.39 to 2.46. I am facing the same issue with IE 8 and 9 

Note: IE10 and 11 works fine.

**Comment by arpit-dhandhania** [comment]
The code which I used to try and set the cookie is:

DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
			Proxy tmpProxy = new Proxy();
			tmpProxy.setProxyType(org.openqa.selenium.Proxy.ProxyType.DIRECT);
			capabilities.setCapability(CapabilityType.PROXY, tmpProxy);
			
			driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);
			driver.manage().timeouts().pageLoadTimeout(25, TimeUnit.SECONDS);
			try{
			driver.get("https://xyz.com");
			}catch(Exception e){
				e.printStackTrace();
			}
			try{
			
		    driver.manage().addCookie(new Cookie("experiment", "cookie:value"));//, ".xyz.com","/",null));

**Comment by jimevans** [comment]
There is not enough information here to go on. Tests that set cookies are running in [our CI environment](http://ci.seleniumhq.org:8080/), and are running successfully on [all 5 supported versions of IE](http://ci.seleniumhq.org:8080/view/IE%20Tests/). You'll need to provide more information, including an actual page that this issue reproduces on.

I note that in your test code, you're navigating to a site using https. If this site is using an invalid or self-signed certificate, IE will display an interstitial page before proceeding to the page in question, and a cookie most emphatically _can not_ be set on that interstitial page.
