### ISSUE TITLE
[selenium 4.0.0-alpha-4] Firefox cannot be open by initiating geckodriver.exe on CLI

### ISSUE THREAD

**Issue by mitul494** [SeleniumHQ/selenium#8078]
## 🐛 Bug Report
Firefox cannot be open by initiating geckodriver.exe thorough selenium 4.0.0-alpha-4 while executing executable JAR on CLI (DOS on Windows)

## To Reproduce
Initiate geckodriver formalities and then make instance of Firefox, followed by any operation. Here, same code is working on programming editor i.e. IntelliJ, but when we make it with executable jar (using Maven shade plugin), it could not be working with selenium 4.0.0-alpha-4. (thought it was working with selenium 3.141.59)

##Resulted Log:
```
org.openqa.selenium.WebDriverException: Build info: version: 'unknown', revision: 'unknown'
System info: host: 'MITUL-DESKTOP', ip: '192.168.1.31', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: driver.version: FirefoxDriver
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:184)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:156)
        at com.malbek.automation.infrastructure.utils.DriverFactory.setDriver(DriverFactory.java:104)
        at com.malbek.automation.framework.utils.BaseTest.SetUp(BaseTest.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
        at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
        at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
        at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
        at org.testng.TestRunner.beforeRun(TestRunner.java:609)
        at org.testng.TestRunner.run(TestRunner.java:580)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
        at org.testng.SuiteRunner.run(SuiteRunner.java:286)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
        at org.testng.TestNG.runSuites(TestNG.java:1039)
        at org.testng.TestNG.run(TestNG.java:1007)
```
## Environment
OS: Windows 10
Browser: Firefox
Browser version: 73.0.1 (64-bit)
Browser Driver version: 0.26.0
Language Bindings version: Java
Selenium Grid version (if applicable): NO

**Comment by barancev** [comment]
Please provide a sample maven project to reproduce the issue.

**Comment by AutomatedTester** [comment]
Closing as requested info was not given
