### ISSUE TITLE
disconnected: received Inspector.detached event

### ISSUE THREAD

**Issue by Andy2010a** [SeleniumHQ/selenium#8100]
## 🐛 Bug Report

Getting the error ,since i upgraded my PC to Windows [Version 10.0.18362.476]

## To Reproduce
Run in 
OS---Windows NT 10.0.18362 x86_64
Chrome----80.0.3987.132
Chrome driver----80.0.3987.106
java.version: '11.0.5'
selenium 3.141.59

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

```
O```
S that its executing on : windows 10
Browser that its executing on : chrome
Starting ChromeDriver 80.0.3987.106** (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}) on port 37369
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1583968399.984][WARNING]: Timed out connecting to Chrome, retrying...
Mar. 12, 2020 10:13:22 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[1583968403.036][SEVERE]: Timed out receiving message from renderer: 0.100
[1583968403.137][SEVERE]: Timed out receiving message from renderer: 0.100
[1583968403.276][SEVERE]: Timed out receiving message from renderer: 0.100
[1583968403.544][SEVERE]: Timed out receiving message from renderer: 0.100

org.openqa.selenium.WebDriverException: disconnected: received Inspector.detached event
  (Session info: chrome=80.0.3987.132)
  (Driver info: chromedriver=80.0.3987.106(f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=**Windows NT 10.0.18362 x86_64**) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'HP5CD9322W8K', ip: '10.58.81.51', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 80.0.3987.106 (f68069574609..., userDataDir: C:\Users\1077863\AppData\Lo...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:63139}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 80.0.3987.132, webStorageEnabled: true}
Session ID: 0dd30b7e78f808ab1ae06f048678ee8b
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at pages.homePage.NavigateTo(homePage.java:108)`
```

The script
```
System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "/drivers/chrome/chromedriver.exe");

                    ChromeOptions options = new ChromeOptions();
                    //options.setBinary(System.getProperty("user.dir") + "/drivers/chrome/chromedriver.exe");
                   options.addArguments("--start-maximized");
                    addChromeGeoLocationPreferences(options);
                    
                    if (configfile.readProperty("docker").toLowerCase().equals("true")) {
                        driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444/wd/hub"), options);
                        setRemoteChromeGeoLocation(driver);
                    } else {
                        driver = new ChromeDriver(options);
                        setLocalChromeGeoLocation(driver);
                    }
```

## Environment
OS---Windows NT 10.0.18362 x86_64
Chrome----80.0.3987.132
Chrome driver----80.0.3987.106
java.version: '11.0.5'
selenium 3.141.59

**Comment by barancev** [comment]
Please report this issue to chromedriver project: https://bugs.chromium.org/p/chromedriver/issues/list

Or you can first try driver version 82, there were many complains on version 80.
