### ISSUE TITLE
Are you sure it's a good idea to use `CompletableFuture` in `FluentWait` [4.0.0-alpha5]?

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#8133]
## 💬 Questions and Help

I noticed that starting from 4.0.0, class `FluentWait` uses `CompletableFuture`. It means that all WebDriver calls will be executed in a separate thread.

It might cause problems because people often use `ThreadLocal`s for holding webdriver instance (or screenshots, or logs, or whatever else). 

For example, some [Selenide tests are failing](https://github.com/selenide/selenide/pull/1099) with 4.0.0-alpha5. It's not a problem for us, we can solve this problem in Selenide. But probably other users might experience the same problem too.

**Comment by barancev** [comment]
Good point. Do you have a better idea how to prevent blocking selenium on external calls that exceed timeout?

**Comment by barancev** [comment]
Do you have a short reproduction case of a selenide failure caused by this change?

**Comment by asolntsev** [comment]
@barancev Sure. For example, [this test](https://github.com/selenide/selenide/blob/upgrade-to-selenium4-alpha5/statics/src/test/java/integration/ScreenshotInIframeTest.java) fails. 

Actually it's enough to run this line:
```java
    SelenideElement iframe = $("#iframe_page");
    switchTo().frame(iframe);
```

to get an error:
```java
java.lang.IllegalStateException: No webdriver is bound to current thread: 34. You need to call open(url) first.

	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getWebDriver(WebDriverThreadLocalContainer.java:104)
	at com.codeborne.selenide.WebDriverRunner.getWebDriver(WebDriverRunner.java:73)
	at com.codeborne.selenide.impl.StaticDriver.getWebDriver(StaticDriver.java:37)
	at com.codeborne.selenide.impl.ElementFinder.getSearchContext(ElementFinder.java:86)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:74)
	at com.codeborne.selenide.commands.GetWrappedElement.execute(GetWrappedElement.java:11)
	at com.codeborne.selenide.commands.GetWrappedElement.execute(GetWrappedElement.java:8)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:148)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:99)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
	at com.sun.proxy.$Proxy16.getWrappedElement(Unknown Source)
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.frame(RemoteWebDriver.java:974)
	at org.openqa.selenium.support.ui.ExpectedConditions$19.apply(ExpectedConditions.java:553)
	at org.openqa.selenium.support.ui.ExpectedConditions$19.apply(ExpectedConditions.java:549)
	at org.openqa.selenium.support.ui.FluentWait.lambda$checkConditionInLoop$2(FluentWait.java:233)
	at 
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by barancev** [comment]
We've reverted back to the old behavior, see 08a90a024d18551c03e80ad382798b36f321afd0
