### ISSUE TITLE
Selenium server node failed to start new session for edge CHROMIUM

### ISSUE THREAD

**Issue by orifn1** [SeleniumHQ/selenium#8205]
## 🐛 Bug Report

**Unable to create new service: EdgeDriverService**
Selenium server node failed to start new session for Edge **Chromium**

## To Reproduce

Test is started
Test failed with message:
```
Unable to create new service: EdgeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'qh-automationV3', ip: '10.0.0.5', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: unknown (SessionNotCreated)
Stack Trace:
System.InvalidOperationException: Unable to create new service: EdgeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
```

## Expected behavior

New session starts for edge chromium browser.

## Test script or set of commands reproducing this issue

Run selenium-standalone-server.jar as hub:
```bash
java -jar selenium-server-standalone-3.141.59.jar -role hub -hubConfig DefaultHub.json -debug
```

DefaultHub.json contens:
```json
{
"port": 4444,
"newSessionWaitTimeout":-1,
"servlets":[],
"withoutServlets": [],
"capabilityMatcher":"org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
"throwOnCapabilityNotPresent":true,
"cleanUpCycle":5000,
"role": "hub",
"debug": false,
"browserTimeout":240,
"timeout":360,
"maxSession":20
}
```
Run selenium-standalone-server.jar as node:
```bash
java -jar selenium-server-standalone-3.141.59.jar -role node -nodeConfig DefaultNodeWebDriver.json
```

DefaultNodeWebDriver.json contents:
```json
{
"capabilities":
[
{
"browserName": "firefox",
"maxInstances": 5,
"seleniumProtocol": "WebDriver"
},
{
"browserName": "chrome",
"maxInstances": 20,
"seleniumProtocol": "WebDriver"
},
{
"browserName": "MicrosoftEdge"
"maxInstances": 20,
"seleniumProtocol": "WebDriver",
"webdriver.edge.driver": "C:/SeleniumGrid/msedgedriver.exe"
},
{
"platform": "WINDOWS",
"browserName": "internet explorer",
"maxInstances": 2,
"seleniumProtocol": "WebDriver"
}
],
"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
"maxSession": 20,
"port": 3334,
"register": true,
"registerCycle": 7000,
"nodePolling": 8000,
"unregisterIfStillDownAfter": 60000,
"downPollingLimit": 3,
"debug": false,
"role": "node",
"hub": "http://localhost:4444",
"servlets" : [],
"withoutServlets": [],
"custom": {}
}
```
I can not find tutorial to setup selenium grid for use with Edge Chromium so I am not sure in this setting:
```
"webdriver.edge.driver": "C:/SeleniumGrid/msedgedriver.exe"
```

## Environment

OS:  Windows 10
Browser: Edge Chromium
Browser version: 81.0.416.53 (Official build) (64-bit)
Browser Driver version: 81.0.416.53
Language Bindings version: C#  4.6.2
Selenium Grid version (if applicable): 3.141.59

**Comment by ryanrain2016** [comment]
Same problem met. Renaming the webdriver file to 'MicrosoftWebDriver.exe' and putting it in system path solve my problem.

**Comment by kgyorgy82** [comment]
Hi, I get the following error message with msedgedriver.exe. I tried to uninstall legacy MicrosoftWebDriver.exe, it didn't help. Putting it under system folder mentioned above doesn't work for me.

org.openqa.selenium.WebDriverException: Unable to parse remote response: Unknown error
Command duration or timeout: 2.16 seconds

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at com.codeborne.selenide.webdriver.RemoteDriverFactory.create(RemoteDriverFactory.java:19)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:70)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:54)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:45)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:126)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:120)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:89)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:47)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:180)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:65)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:28)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:76)
	at com.codeborne.selenide.Selenide.open(Selenide.java:48)
	at hu.icellmobilsoft.sqa.afw.DriverFactory.initDriver(DriverFactory.java:96)
	at hu.icellmobilsoft.sqa.icon.frontend.customer.pageobject.CustomerBase.navigateToSite(CustomerBase.java:40)
	at hu.icellmobilsoft.sqa.icon.frontend.customer.pageobject.CustomerBase.getStartScreen(CustomerBase.java:53)
	at hu.icellmobilsoft.sqa.icon.frontend.customer.pageobject.CustomerBase.getStartScreen(CustomerBase.java:64)
	at hu.icellmobilsoft.sqa.icon.frontend.customer.models.User.loginToHomeScreen(User.java:329)
	at hu.icellmobilsoft.sqa.icon.frontend.customer.models.User.goToCustomerScreen(User.java:67)
	at hu.icellmobilsoft.sqa.icon.frontend.customer.models.User.switchToInformationDetailsScreenThenValidate(User.java:312)
	at hu.icellmobilsoft.sqa.icon.frontend.customer.tests.ValidationTests.verifyInformationQuestionsAndAnswersPage(ValidationTests.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: org.openqa.selenium.WebDriverException: Unable to parse remote response: Unknown error
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-JLIA7J5', ip: '10.10.82.134', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.5'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.grid.session.remote.RemoteSession$Factory.performHandshake(RemoteSession.java:147)
	at org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply(ServicedSession.java:161)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:180)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:183)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:66)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:69)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:397)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:720)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)

**Comment by AutomatedTester** [comment]
Unfortunately this bug  has multiple issues but for the original and last comment follow https://www.selenium.dev/documentation/en/grid/grid_3/setting_up_your_own_grid/#configuration-of-node-with-json

**Comment by orifn1** [comment]
> Unfortunately this bug has multiple issues but for the original and last comment follow https://www.selenium.dev/documentation/en/grid/grid_3/setting_up_your_own_grid/#configuration-of-node-with-json

Link which you gave do not have any answer or similar examples(issues)
![image](https://user-images.githubusercontent.com/6146067/87000562-10eaed00-c1be-11ea-9273-26a099862ee6.png)

**Comment by AutomatedTester** [comment]
The documentation explains how to add JVM properties to the JSON. Feel free to add documentation so we have an exhaustive list.

**Comment by orifn1** [comment]
I have tried different options, but they did not work, so I opened bug, But you close it and suggest me to add description

**Comment by diemol** [comment]
@orifn1 because this is not a bug, is a request for help, which the community is happy to do. Why don't you join the Slack channel and ask questions there? All the information to join can be found at https://www.selenium.dev/support/
