### ISSUE TITLE
Incorrect error is thrown when platform does not match any capabilites [Selenium 4.0.5]

### ISSUE THREAD

**Issue by mburns02** [SeleniumHQ/selenium#8264]
## 🐛 Bug Report

_driver.version: unknown_ is incorrectly thrown when the platform supplied does not match any node.

selenium/hub:4.0.0-alpha-5-20200409 and node-chrome:4.0.0-alpha-5-20200409
## To Reproduce

Steps
Run the above commands on Mac
Attempt a connection supplying 'windows' as the platform.

## Expected behavior

More meaningful error message is shown

## Test script or set of commands reproducing this issue

Attempt a connection supplying 'windows' as the platform.

## Environment

OS: OSX
Browser: Chrome
Browser version: Latest
Browser Driver version: 4.0.5 Alpha
Language Bindings version: Java 1.8
Selenium Grid version (if applicable): selenium/hub:4.0.0-alpha-5-20200409 and node-chrome:4.0.0-alpha-5-20200409

**Comment by AutomatedTester** [comment]
I have tried to recreate this issue and I feel the error given is correct.
Error on Server
```
13:42:46.834 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: Unable to create session for <CreateSessionRequest with Capabilities {browserName: chrome, platformName: windows}>
Build info: version: '4.0.0-alpha-7', revision: 'Unknown'
System info: host: 'Davids-MacBook-Pro.local', ip: 'fd20:a680:1de7:a600:395c:6e2e:6de3:1100%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.5', java.version: '13.0.2'
Driver info: driver.version: unknown
org.openqa.selenium.SessionNotCreatedException: Unable to create session for <CreateSessionRequest with Capabilities {browserName: chrome, platformName: windows}>
Build info: version: '4.0.0-alpha-7', revision: 'Unknown'
System info: host: 'Davids-MacBook-Pro.local', ip: 'fd20:a680:1de7:a600:395c:6e2e:6de3:1100%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.5', java.version: '13.0.2'
Driver info: driver.version: unknown
	at org.openqa.selenium.grid.distributor.model.Slot.lambda$onReserve$1(Slot.java:86)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at org.openqa.selenium.grid.distributor.model.Slot.lambda$onReserve$2(Slot.java:85)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:208)
	at org.openqa.selenium.grid.distributor.Distributor.lambda$new$0(Distributor.java:89)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:183)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.distributor.Distributor.execute(Distributor.java:126)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:85)
	at org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)
	at org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.server.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:30)
	at org.openqa.selenium.grid.server.WrapExceptions.lambda$apply$0(WrapExceptions.java:36)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

and Error on Client is (I am on OSX and tried to create a session on windows with no nodes there)
```
>>> c = webdriver.Remote("http://127.0.0.1:4444", desired_capabilities={"browserName"="chrome", "platformName"="windows"})
  File "<stdin>", line 1
    c = webdriver.Remote("http://127.0.0.1:4444", desired_capabilities={"browserName"="chrome", "platformName"="windows"})
                                                                                     ^
SyntaxError: invalid syntax
>>> c = webdriver.Remote("http://127.0.0.1:4444", desired_capabilities={"browserName":"chrome", "platformName":"windows"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidburns/.pyenv/versions/3.8.3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/davidburns/.pyenv/versions/3.8.3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/davidburns/.pyenv/versions/3.8.3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/davidburns/.pyenv/versions/3.8.3/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to create session for <CreateSessionRequest with Capabilities {browserName: chrome, platformName: windows}>
Build info: version: '4.0.0-alpha-7', revision: 'Unknown'
System info: host: 'Davids-MacBook-Pro.local', ip: 'fd20:a680:1de7:a600:395c:6e2e:6de3:1100%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.5', java.version: '13.0.2'
Driver info: driver.version: unknown
```
