### ISSUE TITLE
java.lang.ClassCastException appears when Firefox Driver trying to switch to default content if some alert is open

### ISSUE THREAD

**Issue by Ulyana-Yeryksonava** [SeleniumHQ/selenium#829]
Environment:
Windows 7 64bit, Firefox Driver 2.46
If there is an alert on the page and I am trying to switch to the default content using this methods:
switchTo().defaultContent(), 
Firefox Driver throws the following exception: 
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.openqa.selenium.remote.ErrorHandler$FrameInfoToStackFrame.apply(ErrorHandler.java:297)
	at org.openqa.selenium.remote.ErrorHandler$FrameInfoToStackFrame.apply(ErrorHandler.java:290)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.addAll(Iterators.java:361)
	at com.google.common.collect.Lists.newArrayList(Lists.java:160)
	at com.google.common.collect.Iterables.toCollection(Iterables.java:337)
	at com.google.common.collect.Iterables.toArray(Iterables.java:315)
	at org.openqa.selenium.remote.ErrorHandler.rebuildServerError(ErrorHandler.java:270)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:118)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.defaultContent(RemoteWebDriver.java:912)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringTargetLocator.defaultContent(EventFiringWebDriver.java:594)

**Comment by lukeis** [comment]
defaultContent is related to frames... you need to dismiss or accept the alert first.

**Comment by lukeis** [comment]
re-read :)

**Comment by valfirst** [comment]
Some meaningful exception is expected: e.g.
```
org.openqa.selenium.UnhandledAlertException: unexpected alert open
```

**Comment by lukeis** [comment]
@valfirst can you provide a reproducible test case please?

The following worked successfully for me.

    driver.get(pages.alertsPage);
    driver.findElement(By.id("alert")).click();
    wait.until(alertIsPresent());

    EventFiringWebDriver eventFiringWebDriver = new EventFiringWebDriver(driver);
    try {
      eventFiringWebDriver.switchTo().defaultContent();
      throw new RuntimeException("should have raised an exception");
    } catch (UnhandledAlertException uae) {
      // pass... success!
      System.out.println(uae.toString());
    }

**Comment by lukeis** [comment]
or @Ulyana-Yeryksonava :)

**Comment by Ulyana-Yeryksonava** [comment]
The following throws java.lang.ClassCastException:
driver.get(pages.alertsPage);
            driver.switchTo().frame(driver.findElement(frameLocator));
            WebElement buttonOnFrame = driver.findElement(buttonOnFrameLocator);
            buttonOnFrame.click();
            wait.until(alertIsPresent());
            driver.switchTo().defaultContent();

**Comment by lukeis** [comment]
from the selenium suite... I did basically the same thing and it passes this test:

    driver.get(pages.alertsPage);
    driver.switchTo().frame(driver.findElement(By.cssSelector("iframe[name='iframeWithAlert']")));
    driver.findElement(By.id("alertInFrame")).click();
    wait.until(alertIsPresent());
    try {
      driver.switchTo().defaultContent();
      throw new RuntimeException("should have raised an exception");
    } catch (UnhandledAlertException uae) {
      // pass... success!
      System.out.println(uae.toString());
    }

With the output showing:
"org.openqa.selenium.UnhandledAlertException: Unexpected modal dialog (text: framed cheese): framed cheese"


closing as not reproducible until you can show a complete test case that it doesn't work with.
