### ISSUE TITLE
Getting org.openqa.selenium.WebDriverException: Build info without any message

### ISSUE THREAD

**Issue by gouru312** [SeleniumHQ/selenium#8319]
## 🐛 Bug Report

Sometimes the autotests are failed with exception like below:

```
org.openqa.selenium.WebDriverException: Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'http://someSite.com', ip: '', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.3.2.el7.x86_64', java.version: '1.8.0_231'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 73.0.3683.68 (47787ec04b6e3..., userDataDir: /tmp/.com.google.Chrome.xzrdjQ}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:45068}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: {}, rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 73.0.3683.75, webStorageEnabled: true}
Session ID: c69fdd3d30156f06b8ca7f470fcd6951e080ea59f684db9e9efeba7472019667
	at sun.reflect.GeneratedConstructorAccessor493.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:577)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at org.openqa.selenium.remote.RemoteWebElement.getTagName(RemoteWebElement.java:122)
```

From this exception we cannot understand what happened.

Often this issue is happened during execution of the 'GetElementTagName' command:

```
2020-05-15T03:22:12.827Z,"filebeat-4xpn4","[1589512932.827][INFO]: [e080ea59f684db9e9efeba7472019667] COMMAND GetElementTagName {\\n   ""id"": ""0.19545048040709112-13""\\n}"		
2020-05-15T03:22:12.827Z,"filebeat-4xpn4","[1589512932.827][INFO]: Waiting for pending navigations..."		
2020-05-15T03:22:12.829Z,"filebeat-4xpn4","[1589512932.829][INFO]: Done waiting for pending navigations. Status: ok"		
2020-05-15T03:22:12.832Z,"filebeat-4xpn4","[1589512932.833][INFO]: Waiting for pending navigations..."		
2020-05-15T03:22:12.842Z,"filebeat-4xpn4","[1589512932.842][INFO]: Done waiting for pending navigations. Status: ok"		
2020-05-15T03:22:12.842Z,"filebeat-4xpn4","[1589512932.843][INFO]: [e080ea59f684db9e9efeba7472019667] RESPONSE GetElementTagName ""td"""
```

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

The exception contains any more information about issue. E.g. org.openqa.selenium.WebDriverException: unknown error: cannot focus element

## Test script or set of commands reproducing this issue

We cannot reproduce this issue self. This exception happens on the different cases sometimes. No simple case to reproduce.

## Environment

OS: Linux
Browser: Chrome
Browser version: 73, 78
Browser Driver version: ChromeDriver 73.0.3683.68
Language Bindings version: 3.12
Selenium Grid version (if applicable): 3.12

**Comment by diemol** [comment]
@gouru312 
After having a look at the provided looks it is impossible to know what the exact problem is, seems that it could be related to an element not found or an issue where the page under test is at the unexpected state.

An additional thing seen from the logs is that the Selenium and ChromeDriver versions used are quite old, upgrading might help to solve the problem.

In any case, we cannot really debug the issue or provide helpful information without a reproduction scenario that helps us to understand better what is going on. Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site). Otherwise it is very likely that this issue will stale and eventually will be closed.

**Comment by diemol** [comment]
Closing as we did not get any more information.
