### ISSUE TITLE
The parameters "--publish-events" and "--subscribe-events" are not supported for 'hub' in selenium-4 alpha 6.

### ISSUE THREAD

**Issue by leiwang008** [SeleniumHQ/selenium#8414]
## 🐛 Bug Report
In previous alpha version, 'hub' command support parameter "--publish-events" and "--subscribe-events", but in version alpha 6, they are not supported anymore. How can we change the publish-port and subscribe-port if the default ports 4442, 4443 are already in use?

## To Reproduce
java -jar selenium-server-4.0.0-alpha-6.jar hub --help

Detailed steps to reproduce the behavior:

## Expected behavior

    Expect it can support these parameters as before
    --publish-events
      Connection string for publishing events to the event bus
    --subscribe-events
      Connection string for subscribing to events from the event bus

## Test script or set of commands reproducing this issue
1. I started a hub on port 6666 so that the default publish-port and subscribe-port will be occupied
java -jar selenium-server-4.0.0-alpha-6.jar hub --port 6666
2. Then I started another hub on port 4444
java -jar selenium-server-4.0.0-alpha-6.jar hub

the output is as below:
16:25:27.979 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
16:25:27.980 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
16:25:27.995 INFO [EventBusOptions.createBus] - Creating event bus: org.openqa.selenium.events.zeromq.ZeroMqEventBus
16:25:28.191 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.27.20.204:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.27.20.204:4443]
Exception in thread "main" java.lang.IllegalArgumentException: Unable to find event bus class: org.openqa.selenium.events.zeromq.ZeroMqEventBus
        at org.openqa.selenium.grid.server.EventBusOptions.createBus(EventBusOptions.java:74)
        at org.openqa.selenium.grid.server.EventBusOptions.getEventBus(EventBusOptions.java:44)
        at org.openqa.selenium.grid.commands.Hub.execute(Hub.java:98)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$2(TemplateGridCommand.java:97)
        at org.openqa.selenium.grid.Main.launch(Main.java:154)
        at org.openqa.selenium.grid.Main.go(Main.java:88)
        at org.openqa.selenium.grid.Main.main(Main.java:54)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.grid.server.EventBusOptions.createBus(EventBusOptions.java:69)
        ... 6 more
Caused by: org.zeromq.ZMQException: Errno 48 : Address already in use
        at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3546)
        at org.zeromq.ZMQ$Socket.bind(ZMQ.java:3000)
        at org.openqa.selenium.events.zeromq.BoundZmqEventBus.<init>(BoundZmqEventBus.java:55)
        at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:37)
        at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:53)
        ... 11 more

**Comment by hnestorova** [comment]
Hi @leiwang008 , @barancev , @titusfortner could you provide an example of how to specify these parameters because i cannot make them work . Here is the begining of the command:

start C:/"Program Files"/Java/jdk1.8.0_45/bin/java -jar selenium-server-alpha6.jar hub --port 4451

and what should be added to specify the "--publish-events" and "--subscribe-events" ? Thank you in advance!

**Comment by hnestorova** [comment]
@barancev , @titusfortner or maybe the fix is not in the alpha6 jar as I can see it is from May?
