### ISSUE TITLE
How to use Chrome profile other than default?

### ISSUE THREAD

**Issue by stefek99** [SeleniumHQ/selenium#854]
### Documentation:
https://sites.google.com/a/chromium.org/chromedriver/capabilities
>  you can use the user-data-dir Chrome command-line switch to tell Chrome which profile to use:

    ChromeOptions options = new ChromeOptions();
    options.addArguments("user-data-dir=/path/to/your/custom/profile");

---

I'm using - https://code.google.com/p/selenium/wiki/WebDriverJs 2.46.1 - and the following code:

```
var webdriver = require('selenium-webdriver');
var chrome = require('selenium-webdriver/chrome');
var o = new chrome.Options();
o.addArguments("user-data-dir=c:/Users/a-miste/AppData/Local/Google/Chrome/User Data/");
var driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).setChromeOptions(o).build(); 

driver.get('http://www.facebook.com');

driver.wait(function() {
 return driver.getTitle().then(function(title) {
   console.log("title: " + title);
   return true;
 });
}, 5000);
```

It was partially created thanks to this StackOverflow question: http://stackoverflow.com/questions/25779027/load-default-chrome-profile-with-webdriverjs-selenium

As I navigate to ```chrome://version/``` the profile path is correct:
> C:\Users\a-miste\AppData\Local\Google\Chrome\User Data\Default

However the whole thing crashes and I do not navigate to Facebook (I stay on the homepage)
```
C:\Michal\Code\Selenium\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
UnknownError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Windows NT 6.3 x86
_64)
    at new bot.Error (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\lib\atoms\error.js:108:18)
    at Object.bot.response.checkResponse (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\lib\atoms\res
ponse.js:109:9)
    at C:\Michal\Code\Selenium\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:160:24
    at promise.ControlFlow.runInFrame_ (C:/Michal/Code/Selenium/node_modules/selenium-webdriver/lib/goog/../web
driver/promise.js:1857:20)
    at goog.defineClass.notify (C:/Michal/Code/Selenium/node_modules/selenium-webdriver/lib/goog/../webdriver/p
romise.js:2448:25)
    at promise.Promise.notify_ (C:/Michal/Code/Selenium/node_modules/selenium-webdriver/lib/goog/../webdriver/p
romise.js:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (C:/Michal/Code/Selenium/node_modules/selenium-webdriver/lib/goog/../webdrive
r/promise.js:553:15)
    at goog.async.run.processWorkQueue (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\lib\goog\async\
run.js:125:21)
    at runMicrotasksCallback (node.js:337:7)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\li
b\webdriver\webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\lib\
webdriver\webdriver.js:131:30)
    at new Driver (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\chrome.js:783:36)
    at Builder.build (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\builder.js:454:14)
    at Object.<anonymous> (C:\Michal\Code\Selenium\3-stack.js:5:108)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
From: Task: WebDriver.navigate().to(http://www.facebook.com)
    at webdriver.WebDriver.schedule (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\lib\webdriver\webd
river.js:362:15)
    at webdriver.WebDriver.Navigation.to (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\lib\webdriver
\webdriver.js:1099:23)
    at webdriver.WebDriver.get (C:\Michal\Code\Selenium\node_modules\selenium-webdriver\lib\webdriver\webdriver
.js:793:26)
    at Object.<anonymous> (C:\Michal\Code\Selenium\3-stack.js:8:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

---

### Using different (non-default) profile

As I change the profile setting line to:
```"user-data-dir=c:/Users/a-miste/AppData/Local/Google/Chrome/User Data/Profile 1"```

The ```chrome://version``` shows the profile path as ```c:\Users\a-miste\AppData\Local\Google\Chrome\User Data\Profile 1\Default``` (note the **Default** appended by default)

---

### Copying profile to a new location

If I try using different (non-default) profile **Default** is appended. To circumvent that I copied **Profile 1** to the following directory structure:

![directory structure](https://cloud.githubusercontent.com/assets/249703/8988373/b693c252-36dd-11e5-9075-27b33ed79a0c.PNG)

And now it works just fine...

---

So the questions are:
* how to use Default profile without crashing?
* how to use other profiles without necessity of copying them?

**Comment by lukeis** [comment]
for chromedriver issues, please log bugs with the chromedriver project:

https://code.google.com/p/chromedriver/issues/list

**Comment by stefek99** [comment]
@lukeis - can you please point me at right direction?

https://code.google.com/p/chromedriver/issues/list - is shutting down...

![image](https://cloud.githubusercontent.com/assets/249703/8996973/7337e182-3714-11e5-873a-1757da8614dc.png)

**Comment by lukeis** [comment]
So far that's correct. I haven't heard yet where the chromedriver team may be moving their issue tracker to

**Comment by vilmysj** [comment]
I start getting same error when updated Node from v0.10.29 to v0.12.7.

`c:\Users\v.juras\Dev\html-toolkit-ui\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);`

It is the same with chrome or firefox.

**Comment by vanloc0301** [comment]
When run a specifies profile, I using:

    ChromeOptions options = new ChromeOptions();
    options.addArguments("user-data-dir=/path/to/your/custom/profile");

The code only applies to one profile.

Have any method to get all user and I want to open each URL will start with each profile of Chrome.

**Comment by vanloc0301** [comment]
When run a specifies profile, I using:

    ChromeOptions options = new ChromeOptions();
    options.addArguments("user-data-dir=/path/to/your/custom/profile");

The code only applies to one profile.

Have any method to get all user and I want to open each URL will start with each profile of Chrome.

**Comment by glenpierce** [comment]
When I create a test class with multiple tests in it, the first test passes, but thereafter, driver = new ChromeDriver(options); never returns with a new ChromeDriver so all subsequent tests fail. This only seems to happen when I'm setting my options to include a specific Profile. Any idea what might cause this?

**Comment by hontrang** [comment]
Hi,
I have a task to research profile in selenium, so please tell me what is advantages of custom profile compare with default profile
Best regards

**Comment by cgoldberg** [comment]
Please submit chrome and chromedriver issues to the Chromium project.  see: http://chromedriver.chromium.org/help
