### ISSUE TITLE
Once per few hundred tests operation timeout on initializing Chrome driver on Microsoft's agent

### ISSUE THREAD

**Issue by Duke4848** [SeleniumHQ/selenium#8554]
## 🐛 Bug Report

Once per few hundred times while running on VS2019 Microsoft managed agent I do get timeout on browser startup.

## To Reproduce

Create ChromeDriver before each test:

```
driverPath = Environment.GetEnvironmentVariable("ChromeWebDriver") ?? Environment.CurrentDirectory; 
driver = new ChromeDriver(driverPath);
```
run tests with MS VS2019 agent
Detailed steps to reproduce the behavior:

## Expected behavior

Browser always opens.

##Actual behaviour
Once per few hundred test runs:

OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:3656/session timed out after 60 seconds.
----> System.Net.WebException : The operation has timed out.
TearDown : BoDi.ObjectContainerException : Interface cannot be resolved: OpenQA.Selenium.IWebDriver
Stack trace
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)

## Environment

MS VS2019 Agent
OS: Windows 10
Browser: Chrome
Browser version: 84
Browser Driver version: 84.0.4147.3001
Language Bindings version: .NET Core 2.1

**Comment by diemol** [comment]
@Duke4848 it is really hard to say what the issue is with such little information provided. So many things could be the cause, available resources, etc...

Whenever you can, please open a new issue with all the requested information in it. With that, we can happily have a look.
