### ISSUE TITLE
Unable to create node in Selenium-grid with apple-tvOS (tvOS) & you.i tvOS (yitvOS) capabilities 

### ISSUE THREAD

**Issue by prathapJonnadula** [SeleniumHQ/selenium#8569]
## 🐛 Bug Report

While Trying to Crete node in Selenium grid with Apple tv & you.i tv capabilities throwing error org.openqa.selenium.platform

java.lang.IllegalArgumentException: No enum constant org.openqa.selenium.Platform.YItvOS
java.lang.IllegalArgumentException: No enum constant org.openqa.selenium.Platform.tvOS
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.openqa.selenium.Platform.valueOf(Platform.java:30)
	at org.openqa.grid.web.servlet.console.DefaultProxyHtmlRenderer.getPlatform(DefaultProxyHtmlRenderer.java:215)
	at org.openqa.grid.web.servlet.console.DefaultProxyHtmlRenderer.getPlatform(DefaultProxyHtmlRenderer.java:194)
	at org.openqa.grid.web.servlet.console.DefaultProxyHtmlRenderer.renderSummary(DefaultProxyHtmlRenderer.java:54)
	at org.openqa.grid.web.servlet.console.ConsoleServlet.process(ConsoleServlet.java:125)
	at org.openqa.grid.web.servlet.console.ConsoleServlet.doGet(ConsoleServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-07-23 14:01:20.232:WARN:osjs.HttpChannel:qtp1262773598-31: /grid/consolejava.lang.IllegalArgumentException: No enum constant org.openqa.selenium.Platform.tvOS
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.openqa.selenium.Platform.valueOf(Platform.java:30)
	at org.openqa.grid.web.servlet.console.DefaultProxyHtmlRenderer.getPlatform(DefaultProxyHtmlRenderer.java:215)
	at org.openqa.grid.web.servlet.console.DefaultProxyHtmlRenderer.getPlatform(DefaultProxyHtmlRenderer.java:194)
	at org.openqa.grid.web.servlet.console.DefaultProxyHtmlRenderer.renderSummary(DefaultProxyHtmlRenderer.java:54)
	at org.openqa.grid.web.servlet.console.ConsoleServlet.process(ConsoleServlet.java:125)
	at org.openqa.grid.web.servlet.console.ConsoleServlet.doGet(ConsoleServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-07-23 14:01:20.232:WARN:osjs.HttpChannel:qtp1262773598-31: /grid/console

## To Reproduce

Detailed steps to reproduce the behavior:
use below capabilites

 capabilities :
{
    "capabilities":
        [
            {
                "platformName":"YItvOS" (OR) "tvOS",
		"deviceName":"AppleTV-4k",
                "appium:automationName": "YouiEngine" or "XCUITest",
                "appium:udid": "udid"
            }
        ],
    "configuration":
    {
      "cleanUpCycle":2000,
      "timeout":30000,
      "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
      "maxSession": 1,
      "register": true,
      "registerCycle": 5000,
      "hubPort": 8080,
      "hubHost": "hostip",
      "hubProtocol": "http",
      "role":"node",
      "debug":true
    }
  }

run below  command :

    appium --nodeconfig=/path/nodeconfig-tvOS.json -p port -a host
## Expected behavior
Grid should support YItvOS and tvOS other platforms

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  OSX
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):  3.141.59

**Comment by diemol** [comment]
This should be done when Grid 4 is integrated with Appium, for which we have this placeholder #9127.
