### ISSUE TITLE
Selenium is no longer gracefully interacting with windows when an alert is open on Chrome 85

### ISSUE THREAD

**Issue by agrobbin** [SeleniumHQ/selenium#8638]
## 🐛 Bug Report

Starting with Chrome 85, Selenium's Chrome webdriver is no longer raising `Selenium::WebDriver::Error::UnexpectedAlertOpenError` when an alert dialog is opened (in my case via `beforeunload`, but likely not specific to this scenario).

## To Reproduce

I've included what is hopefully a fully reproducible test case below!

## Expected behavior

This should exit cleanly, with Capybara `rescue`ing `Selenium::WebDriver::Error::UnexpectedAlertOpenError`, closing the dialog, and moving on. However, starting in Chrome 85, Selenium is now raising an `EOFError` exception:

```
Traceback (most recent call last):
	18: from capybara_chrome_85_alert.rb:40:in `<main>'
	17: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.32.1/lib/capybara/session.rb:130:in `reset!'
	16: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.32.1/lib/capybara/selenium/driver_specializations/chrome_driver.rb:49:in `reset!'
	15: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/navigation.rb:32:in `to'
	14: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:59:in `get'
	13: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
	12: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	11: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	10: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:82:in `request'
	 9: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:129:in `response_for'
	 8: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	 7: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
	 6: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
	 5: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
	 4: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
	 3: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
	 2: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
	 1: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (EOFError)
```

## Test script or set of commands reproducing this issue

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'capybara'
  gem 'puma'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'byebug'
end

require 'selenium-webdriver'
require 'capybara/dsl'

html = <<~HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello World</title>
    <meta charset="utf-8">

    <script type="text/javascript">
      window.addEventListener('beforeunload', (event) => {
        event.preventDefault();
        event.returnValue = '';
      });
    </script>
  </head>
  <body>
    <h1><a href="#">Hello World</a></h1>
  </body>
</html>
HTML

app = proc { |env| [200, { "Content-Type" => "text/html" }, [html] ] }

session = Capybara::Session.new(:selenium_chrome, app)
session.visit '/'
session.click_on 'Hello World' # interact with the page, to get Chrome to fire `beforeunload`
session.reset!
```

## Environment

OS: macOS 10.15.6
Browser: Chrome 
Browser version: 85.0.4183.76
Browser Driver version: ChromeDriver 85.0.4183.38
Language Bindings version: Ruby 2.7.1, Capybara 3.33.0

**Comment by titusfortner** [comment]
First, this is the best example of a fully reproducible test case I've seen in a long while (at least for a ruby dev); thank you for putting in the time to create it.

I looked at what your code does on 84 and it checks out. If it stopped working on 85, then it's going to be a chromedriver issue and the hot potato gets passed along to: https://bugs.chromium.org/p/chromedriver/issues/list

Also, depending on what you are trying to do with the alert, maybe changing the default behavior for it makes sense: https://w3c.github.io/webdriver/#dfn-known-prompt-handling-approaches-table

**Comment by agrobbin** [comment]
My pleasure @titusfortner, and thanks for the quick response here!

I'll shepherd this along to ChromeDriver and see what they say. 🤞🏻

**Comment by agrobbin** [comment]
I've opened [ChromeDriver issue 3578](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3578) to track this issue!

**Comment by radar** [comment]
@agrobbin I just came across a similar issue in my codebase too. Thank you very much for logging it here!
