### ISSUE TITLE
I am facing this issue while running the script need help how to fix this issue!!!!

### ISSUE THREAD

**Issue by arslan8625** [SeleniumHQ/selenium#8646]
## 🐛 Bug Report
Aug 25, 2020 2:03:36 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
launch activity
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'css selector' is not supported for this session
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-NS33GG1', ip: '192.168.5.241', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.mm.parentalcontrol, deviceScreenSize=720x1600, networkConnectionEnabled=true, statBarHeight=68.0, warnings={}, viewportRect={top=68.0, left=0.0, width=720.0, height=1380.0}, databaseEnabled=false, deviceName=RF8N62GTVSJ, platform=LINUX, deviceUDID=RF8N62GTVSJ, appActivity=com.mm.parentalcontrol.ui.activities.SplashScreen, desired={appPackage=com.mm.parentalcontrol, appActivity=com.mm.parentalcontrol.ui.activities.SplashScreen, platformVersion=10, platformName=Android, udid=RF8N62GTVSJ, deviceName=Galaxy A21s}, platformVersion=10, pixelRatio=1.75, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceScreenDensity=280.0, deviceModel=SM-A217F, platformName=Android, udid=RF8N62GTVSJ, deviceApiLevel=29.0, deviceManufacturer=samsung}]
Session ID: 6fc890a7-12c9-469f-9d25-6f7e19511c7a
*** Element info: {Using=id, value=com.mm.parentalcontrol:id/englishLL}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:52)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:410)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:453)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementById(AndroidDriver.java:1)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:402)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at Config.main(Config.java:34)

Process finished with exit code 0
Did you find something wrong with the site or the documentation? Please describe
your finding in a clear and concise way. 

## To Reproduce

How can we reproduce the issue you found? Please tell us how we can do that. 
Don't forget to add:

* Absolute link where the issue was found
* Screenshot (if needed) 
* The environment you had when the issue was found (see below)

Tell us the detailed steps to reproduce it:

## Expected behavior

What do you expected to happen? How should have it worked?

## Environment

* OS: 
* Browser: 
* Browser version:

**Comment by arslan8625** [comment]
i am facing this issue while running the project in maven is any possible solution.?

**Comment by arslan8625** [comment]
public class Config {
   // static Config config;
    static String BASE="com.mm.parentalcontrol";
    static String BASE_ID="com.mm.parentalcontrol:id/";


    private static AndroidDriver<MobileElement> driver;

    public static void main(String[] args) throws MalformedURLException, InterruptedException {
        try {

            DesiredCapabilities cap = new DesiredCapabilities();
            cap.setCapability("deviceName", "Galaxy A21s");
            cap.setCapability("udid", "RF8N62GTVSJ");
            cap.setCapability("platformName", "android");
            cap.setCapability("platformVersion", "10");
            cap.setCapability("appPackage",BASE );
            cap.setCapability("appActivity", "com.mm.parentalcontrol.ui.activities.SplashScreen");

            //cap.setCapability("appActivity",".SplashActivity");
            URL url=new URL("http://127.0.0.1:4723/wd/hub");
            AndroidDriver<WebElement> driver=new AndroidDriver<WebElement>(url,cap);
            System.out.println("launch activity");
            Thread.sleep(5000);
            driver.findElementById("englishLL").click();
           // driver.findElement(By.id(BASE_ID +"englishLL")).click();
            Thread.sleep(2000);
            driver.findElement(By.id(BASE_ID+ "btnDone")).click();
            Thread.sleep(2000);
            driver.findElement(By.id(BASE_ID+ "btnStart")).click();
            Thread.sleep(2000);

        }catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by diemol** [comment]
@arslan8625 with the provided info, we cannot understand what the issue is. If you need help debugging, you can join the community Slack channel, but since this is an Appium test, I recommend to join their support channels as well.
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well

Appium 
https://discuss.appium.io/c/support
https://gitter.im/appium/appium

**Comment by arslan8625** [comment]
thanks @diemol
