### ISSUE TITLE
ChromeDriver becomes "zombie" process right after Chrome fails to start

### ISSUE THREAD

**Issue by iaroslavn** [SeleniumHQ/selenium#8706]
## 🐛 Bug Report

When creating a new ChromeDriver if initialization fails due to browser crash the chromedriver process continues to run.
This may cause many chromedriver processes to be spawned during the application lifetime which can cause a serious performance degradation.

## To Reproduce
As the exact reasons behind the Chrome crash are unknown it makes it hard to come up with the exact steps on how to reproduce the issue. This issue was observed from time to time in Production with OS resources being the only thing that varies.
The error stack trace observed at the time this happened:
```
Caused by: org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '4.0.0-alpha-6', revision: '5f43a29cfc'
System info: host: 'rendered-html-collection-service-6758545d9-xt668', ip: '100.107.126.149', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1057-aws', java.version: '11.0.5'
Driver info: driver.version: ManagedWebDriver
remote stacktrace: #0 0x559d05286a39 <unknown>

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$1(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:582)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:136)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:75)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:163)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:150)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
```
Please refer to the unit test below to get more details on how to reproduce the issue.

## Expected behavior

There should be the only chromedriver process in the process list while the application is running.

## Test script or set of commands reproducing this issue
Inside org.openqa.selenium.remote.service.DriverCommandExecutor#execute move a call to `super.execute` into a separate method so it can be mocked:
```java
  @VisibleForTesting
  Response invokeExecute(Command command) throws IOException {
    return super.execute(command);
  }
```

The below junit test should fail at `verify(service).stop()` as it is not invoked at the moment:
```java
  @Test
  public void shouldStopDriverServerOnExceptionForTheNewSessionCommand() throws IOException {
    Command command = new Command(null, DriverCommand.NEW_SESSION(new ImmutableCapabilities()));
    DriverService service = mock(DriverService.class);
    when(service.getUrl()).thenReturn(new URL("http://a.base.url:3000"));
    when(service.isRunning()).thenReturn(false, true);

    DriverCommandExecutor executor = spy(new DriverCommandExecutor(service));
    doThrow(WebDriverException.class).when(executor).invokeExecute(any(Command.class));
    assertThatExceptionOfType(WebDriverException.class)
      .isThrownBy(() -> executor.execute(command));

    verify(service).start();
    verify(service).stop();
  }
```

## Environment

OS: Debian GNU/Linux 10 (buster), Linux, 4.40-1057-aws, (Run in Docker container)
Browser: Chrome
Browser version: 85.0.4183.87
Browser Driver version: 85.0.4183.87
Language Bindings version: Java, OpenJDK Runtime Environment 18.9 (build 11.0.5+10)

**Comment by iaroslavn** [comment]
Whenever Chrome crashes on the start the chromedriver process stays because this code decides not to send the QUIT command since the sessionId remains `null`:
https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-alpha-6/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L473

and sending that `QUIT` command would have stopped the chromedriver process:
https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-alpha-6/java/client/src/org/openqa/selenium/remote/service/DriverCommandExecutor.java#L94

**Comment by link89** [comment]
We have the same issue when starting chrome with the wrong `binary` option.
