### ISSUE TITLE
The work log of the geckodriver is not displayed

### ISSUE THREAD

**Issue by Dmilut** [SeleniumHQ/selenium#8731]
## 🐛 Bug Report
I am trying to open a page in a browser but only a new window with a blank page opens. To investigate the problem, I want to look at the error log, but the geckodriver operation log is not displayed anywhere. I only get the log from selenium.

## To Reproduce
Detailed steps to reproduce the behavior:
1. Run main method in the Test class by any IDE
2. Wait about 1 min
3. Observe

## Expected behavior
A detailed log of geckodriver is displayed in the console according to the set level TRACE.

## Actual result
A detailed log of geckodriver is not displayed in the console according to the set level TRACE.

## Test script or set of commands reproducing this issue
```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;

public class Test {

    public static void main(String[] args) {

        System.setProperty("webdriver.gecko.driver", "src/main/resources/geckodriver");
        FirefoxOptions options = new FirefoxOptions();
        options.setCapability("marionette", false);
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);

        WebDriver driver = new FirefoxDriver(options);

        driver.get("http://google.com");
        driver.quit();
    }
}
```
## Console output

```
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'arch', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.8.9-arch2-1', java.version: '14.0.2'
Driver info: driver.version: FirefoxDriver
at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:247)
at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:159)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:131)
at org.openqa.selenium.firefox.FirefoxDriver.(FirefoxDriver.java:147)
at Test.main(Test.java:15)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:18496/hub/status] to be available after 45002 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:245)
... 7 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
... 8 more
```

## Environment
OS: Arch Linux 5.8.9-arch2-1
Browser: Firefox
Browser version: 80.0.1 (64-bit)
Browser Driver version: Geckodriver: 0.27.0
Language Bindings version: Java: openjdk-14.0.2
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment]
Adding `options.setCapability("marionette", false);` triggers the use of the legacy driver, which is not compatible with the version of Firefox you'd like to use.
If you remove that line, it should work.
There is more detail in this SO [post](https://stackoverflow.com/questions/43272919/difference-between-webdriver-firefox-marionette-webdriver-gecko-driver/43920453).

**Comment by Dmilut** [comment]
> Adding `options.setCapability("marionette", false);` triggers the use of the legacy driver, which is not compatible with the version of Firefox you'd like to use.
> If you remove that line, it should work.
> There is more detail in this SO [post](https://stackoverflow.com/questions/43272919/difference-between-webdriver-firefox-marionette-webdriver-gecko-driver/43920453).
### This should, but doesn't work:
```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;

public class Test {

    public static void main(String[] args) {

        System.setProperty("webdriver.gecko.driver", "src/main/resources/geckodriver");
        FirefoxOptions options = new FirefoxOptions();
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);

        WebDriver driver = new FirefoxDriver(options);

        driver.get("http://google.com");
        driver.quit();
    }
}
```
### Stacktrace
```
1601328831822	geckodriver	INFO	Listening on 127.0.0.1:24390
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'arch', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.8.10-arch1-1', java.version: '14.0.2'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at Test.main(Test.java:14)
```

**Comment by diemol** [comment]
@Dmilut because this line
```
options.setCapability("marionette", false);
```
is still present, please remove it. 
Is there are reason why you need it there?

**Comment by Dmilut** [comment]
> @Dmilut because this line
> 
> ```
> options.setCapability("marionette", false);
> ```
> 
> is still present, please remove it.
> Is there are reason why you need it there?

I removed it, it was a copy-paste bug :) Please see stacktrace

**Comment by diemol** [comment]
@Dmilut 
Now the error is different:
```
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
```
Please make sure Firefox is available and GeckoDriver can open it.

**Comment by Dmilut** [comment]
@diemol 
> @Dmilut
> Now the error is different:
> 
> ```
> Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
> ```
> 
> Please make sure Firefox is available and GeckoDriver can open it.

Yes they are, because as you can see in the stacktrace - we have geckodriver log in first row. Also, if I used this code
`options.setCapability("marionette", false); `
than Selenium open new blank page in Firefox.

**Comment by Dmilut** [comment]
@diemol Please tell me if you need any more information 
Thank you for your time!
