### ISSUE TITLE
Relative locators doesnt work in alpha 6 - throws IllegalArgumentException , but works fine till alpha5 java bindings

### ISSUE THREAD

**Issue by ShamaUgale** [SeleniumHQ/selenium#8738]
## To Reproduce
Here is the code --> https://gist.github.com/ShamaUgale/0a30751f285a5e479467882492e2bcc6 

The above code works fine and the prints the id of an element located with "4.0.0-alpha-5" selenium java bindings.
Whereas it throws the below exception for 4.0.0-alpha-6

Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 29952
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1601072744.821][WARNING]: FromSockAddr failed on netmask
ChromeDriver was started successfully.
Sep 26, 2020 3:55:46 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" java.lang.IllegalArgumentException: Argument is of an illegal type: org.openqa.selenium.By$ByTagName
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:85)
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:79)
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:79)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:514)
	at org.openqa.selenium.support.locators.RelativeLocator$RelativeBy.findElements(RelativeLocator.java:176)
	at org.openqa.selenium.By.findElement(By.java:132)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:325)
	at RelativeLocatorsExample.main(RelativeLocatorsExample.java:14)

## Expected behavior
Should be able to get the id of the element located on line 18.

## Test script or set of commands reproducing this issue
Here is the code --> https://gist.github.com/ShamaUgale/0a30751f285a5e479467882492e2bcc6 

## Environment
OS:  'Mac OS X', os.version: '10.13.6', 
Browser: Chrome 
Browser version:  85
Browser Driver version: ChromeDriver 85.0.4183.87
Language Bindings version: 4.0.0-alpha-6

**Comment by anandbagmar** [comment]
@ShamaUgale - As reported, I was able to reproduce this issue in 4.0.0-alpha6, but not in 4.0.0-alpha5. 

That said, this issue is already fixed in the latest code - so should work as expected in the next release.

**Comment by shs96c** [comment]
Thank you for pointing this out. Thank you, each of you, for the report and the comment! Marking as closed :)
