### ISSUE TITLE
SessionNotCreatedException: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Dmilut** [SeleniumHQ/selenium#8744]
## 🐛 Bug Report
I tried to open google.com using selenium + geckodriver but got the exception.

## To Reproduce
Detailed steps to reproduce the behavior:
1. Run main method in the Test class by any IDE
2. Observe

## Expected behavior
A new Firefox browser window will open and the google.com page will be shown.

## Actual result
A new Firefox browser window will not open and the google.com page will not be shown.

## Test script or set of commands reproducing this issue
```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;

public class Test {

	public static void main(String[] args) {

		System.setProperty("webdriver.gecko.driver", "src/main/resources/geckodriver");
		FirefoxOptions options = new FirefoxOptions();
		options.setLogLevel(FirefoxDriverLogLevel.TRACE);

		WebDriver driver = new FirefoxDriver(options);

		driver.get("http://google.com");
		driver.quit();
	}
}
```
## Console output

```
1601395316102	geckodriver	INFO	Listening on 127.0.0.1:15504
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'arch', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.8.12-arch1-1', java.version: '14.0.2'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at Test.main(Test.java:14)

Process finished with exit code 1
```

## Environment
OS: Arch Linux 5.8.12-arch1-1
Browser: Firefox
Browser version: 81.0 (64-bit)
Browser Driver version: Geckodriver: 0.27.0
Language Bindings version: Java: openjdk-14.0.2
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment]
@Dmilut the issue template and the log shows that you are using Grid 3.141.59, however, the script to reproduce the error is not using `RemoteWebDriver`. Could you please provide a script that reproduces the error?

**Comment by Dmilut** [comment]
I'm afraid this is a misunderstanding. I don't use Grid, I only use Selenium WebDriver. I do all this according to the documentation, which you can see [here](https://www.selenium.dev/documentation/en/selenium_installation/installing_selenium_libraries/).
Is there any other way I can help solve this problem?
Thank you!

**Comment by Dmilut** [comment]
> @Dmilut the issue template and the log shows that you are using Grid 3.141.59, however, the script to reproduce the error is not using `RemoteWebDriver`. Could you please provide a script that reproduces the error?

I'm afraid this is a misunderstanding. I don't use Grid, I only use Selenium WebDriver. I do all this according to the documentation, which you can see [here](https://www.selenium.dev/documentation/en/).
Is there any other way I can help solve this problem?
Thank you!

**Comment by tpo** [comment]
Similar here.

* Debian buster
* Mozilla Firefox 78.4.0esr
* python3-selenium 3.14.1+dfsg1-1
* geckodriver 0.27

```
$ cat foo2.py 
#!/usr/bin/python3
from selenium import webdriver
browser = webdriver.Firefox()

$ ./foo2.py 
Traceback (most recent call last):
  File "./foo2.py", line 3, in <module>
    browser = webdriver.Firefox()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

what to do?

**Comment by fritzr** [comment]
I see this as well after a fresh install of geckodriver 0.27 and pip install of Selenium (3.141.0) using Python 3.7.6 on CentOS 7.

Some quick digging reveals this issue is well known. Presumably your `/usr/bin/firefox` is actually a shell stub, and not an executable, which causes issues in geckodriver.

See #8604 or mozilla/geckodriver#1488 for the workaround in this case, which is to provide the keyword argument `firefox_binary="path/to/real/firefox"` to the `selenium.webdriver.Firefox` constructor. For me this is `/usr/lib64/firefox/firefox`, which I found by running Firefox normally and then using `pgrep` / `ps` to find the actual program which was run:

```bash
$ pgrep firefox | xargs ps -ww -opid,user,args
  PID USER    COMMAND
18266 me      /usr/lib64/firefox/firefox
```

So I can instead use:

```python
from selenium import webdriver
browser = webdriver.Firefox(firefox_binary="/usr/lib64/firefox/firefox")
```

**Comment by tpo** [comment]
Thanks a lot for that info @fritzr - I wish I had know before!

**Comment by AutomatedTester** [comment]
This is done by Geckodriver. Please raise an [issue](https://github.com/mozilla/geckodriver/blob/master/CONTRIBUTING.md#issue-reports) with them
