### ISSUE TITLE
ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: Failed to create Chrome process.

### ISSUE THREAD

**Issue by akshatvolvocars** [SeleniumHQ/selenium#8748]
## 💬 Questions & Help

Dear Experts, I am caught up in a peculiar situation.
Every time I am trying to run my simple Selenium Webdriver case, it throws the below error-

`ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: Failed to create Chrome process.`
`[0-0]  Error:  Failed to create session.
unknown error: Failed to create Chrome process.`
`
[0-0] 2020-09-30T13:32:08.653Z ERROR webdriver: unknown error: unknown error: Failed to create Chrome process.
`

Here is the entire error stack for your reference - 
```
C:\dev1\testnodeproj>npx wdio wdio.conf.js
Execution of 2 spec files started at 2020-09-30T13:32:06.090Z
2020-09-30T13:32:06.127Z INFO @wdio/cli:launcher: Run onPrepare hook
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2020-09-30T13:32:06.862Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-09-30T13:32:06.863Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-09-30T13:32:06.866Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
2020-09-30T13:32:06.875Z INFO @wdio/local-runner: Start worker 0-1 with arg: wdio.conf.js
[0-1] 2020-09-30T13:32:07.931Z INFO @wdio/local-runner: Run worker command: run
[0-1] 2020-09-30T13:32:07.949Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] 2020-09-30T13:32:07.972Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-09-30T13:32:07.993Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-1] RUNNING in chrome - C:\dev1\testnodeproj\test\specs\example.e2e.js
[0-0] RUNNING in chrome - C:\dev1\testnodeproj\test\specs\basic.js
[0-1] 2020-09-30T13:32:08.284Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-1] 2020-09-30T13:32:08.286Z INFO webdriver: [POST] http://localhost:9515/session
[0-1] 2020-09-30T13:32:08.286Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-0] 2020-09-30T13:32:08.308Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-09-30T13:32:08.312Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2020-09-30T13:32:08.312Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-1] 2020-09-30T13:32:08.409Z WARN webdriver: Request failed with status 500 due to unknown error: Failed to create Chrome process.
[0-1] 2020-09-30T13:32:08.409Z INFO webdriver: Retrying 1/3
2020-09-30T13:32:08.409Z INFO webdriver: [POST] http://localhost:9515/session
2020-09-30T13:32:08.409Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-0] 2020-09-30T13:32:08.415Z WARN webdriver: Request failed with status 500 due to unknown error: Failed to create Chrome process.
[0-0] 2020-09-30T13:32:08.415Z INFO webdriver: Retrying 1/3
2020-09-30T13:32:08.416Z INFO webdriver: [POST] http://localhost:9515/session
2020-09-30T13:32:08.416Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-1] 2020-09-30T13:32:08.494Z WARN webdriver: Request failed with status 500 due to unknown error: Failed to create Chrome process.
[0-1] 2020-09-30T13:32:08.494Z INFO webdriver: Retrying 2/3
2020-09-30T13:32:08.494Z INFO webdriver: [POST] http://localhost:9515/session
2020-09-30T13:32:08.494Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-0] 2020-09-30T13:32:08.505Z WARN webdriver: Request failed with status 500 due to unknown error: Failed to create Chrome process.
[0-0] 2020-09-30T13:32:08.505Z INFO webdriver: Retrying 2/3
2020-09-30T13:32:08.505Z INFO webdriver: [POST] http://localhost:9515/session
2020-09-30T13:32:08.505Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-0] 2020-09-30T13:32:08.569Z WARN webdriver: Request failed with status 500 due to unknown error: Failed to create Chrome process.
[0-0] 2020-09-30T13:32:08.569Z INFO webdriver: Retrying 3/3
2020-09-30T13:32:08.569Z INFO webdriver: [POST] http://localhost:9515/session
2020-09-30T13:32:08.569Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-1] 2020-09-30T13:32:08.578Z WARN webdriver: Request failed with status 500 due to unknown error: Failed to create Chrome process.
[0-1] 2020-09-30T13:32:08.578Z INFO webdriver: Retrying 3/3
2020-09-30T13:32:08.578Z INFO webdriver: [POST] http://localhost:9515/session
2020-09-30T13:32:08.578Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-0] 2020-09-30T13:32:08.653Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: Failed to create Chrome process.
[0-0]  Error:  Failed to create session.
unknown error: Failed to create Chrome process.
[0-0] 2020-09-30T13:32:08.653Z ERROR webdriver: unknown error: unknown error: Failed to create Chrome process.
    at getErrorFromResponseBody (C:\dev1\testnodeproj\node_modules\webdriver\build\utils.js:121:10)
    at WebDriverRequest._request (C:\dev1\testnodeproj\node_modules\webdriver\build\request.js:149:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startWebDriverSession (C:\dev1\testnodeproj\node_modules\webdriver\build\utils.js:41:16)
    at async Function.newSession (C:\dev1\testnodeproj\node_modules\webdriver\build\index.js:44:23)
    at async remote (C:\dev1\testnodeproj\node_modules\webdriverio\build\index.js:75:20)
    at async Runner._startSession (C:\dev1\testnodeproj\node_modules\@wdio\runner\build\index.js:204:50)
    at async Runner._initSession (C:\dev1\testnodeproj\node_modules\@wdio\runner\build\index.js:173:21)
    at async Runner.run (C:\dev1\testnodeproj\node_modules\@wdio\runner\build\index.js:91:15)
2020-09-30T13:32:08.654Z ERROR @wdio/runner: Error: Failed to create session.
unknown error: Failed to create Chrome process.
    at startWebDriverSession (C:\dev1\testnodeproj\node_modules\webdriver\build\utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-1] 2020-09-30T13:32:08.659Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: Failed to create Chrome process.
2020-09-30T13:32:08.659Z ERROR webdriver: unknown error: unknown error: Failed to create Chrome process.
    at getErrorFromResponseBody (C:\dev1\testnodeproj\node_modules\webdriver\build\utils.js:121:10)
    at WebDriverRequest._request (C:\dev1\testnodeproj\node_modules\webdriver\build\request.js:149:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startWebDriverSession (C:\dev1\testnodeproj\node_modules\webdriver\build\utils.js:41:16)
    at async Function.newSession (C:\dev1\testnodeproj\node_modules\webdriver\build\index.js:44:23)
    at async remote (C:\dev1\testnodeproj\node_modules\webdriverio\build\index.js:75:20)
    at async Runner._startSession (C:\dev1\testnodeproj\node_modules\@wdio\runner\build\index.js:204:50)
    at async Runner._initSession (C:\dev1\testnodeproj\node_modules\@wdio\runner\build\index.js:173:21)
    at async Runner.run (C:\dev1\testnodeproj\node_modules\@wdio\runner\build\index.js:91:15)
2020-09-30T13:32:08.660Z ERROR @wdio/runner: Error: Failed to create session.
unknown error: Failed to create Chrome process.
    at startWebDriverSession (C:\dev1\testnodeproj\node_modules\webdriver\build\utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-1]  Error:  Failed to create session.
unknown error: Failed to create Chrome process.
[0-0] FAILED in chrome - C:\dev1\testnodeproj\test\specs\basic.js
[0-1] FAILED in chrome - C:\dev1\testnodeproj\test\specs\example.e2e.js
2020-09-30T13:32:08.776Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:00:02

2020-09-30T13:32:08.779Z INFO @wdio/local-runner: Shutting down spawned worker
2020-09-30T13:32:09.032Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-09-30T13:32:09.033Z INFO @wdio/local-runner: shutting down
```

My browser & tests were working fine a few weeks back. 

But after updating my browser to the latest chrome version, I started getting the above error. I then decided to try a rather simple setup to isolate the issue and tried the below link to set up a small project to run a quick UI test-
`https://webdriver.io/docs/gettingstarted.html`
and faced the exact same error.

I have the latest chrome version installed. and I have not changed any permission explicitly. 

Yet, if you see that I can cross-check anything in my system, like permission, firewall etc...please suggest.
It will be a great help.

Thanks in advance
Akshat

**Comment by c0rv4x** [comment]
@akshatvolvocars 

Hey, we had similar issue in docker and here are some Chrome options, which helped us.

```
--no-sandbox
--headless
--disable-dev-shm-usage
```
