### ISSUE TITLE
Actions not working when PageFactory initElements using FieldDecorator with EventFiringWebDriver with eventListener 

### ISSUE THREAD

**Issue by sleod** [SeleniumHQ/selenium#8759]
## To Reproduce
A very easy case: start google home page and click on logo picture.
//
public class SeleniumTest {
    protected WebDriver driver;

    @FindBy(id = "hplogo")
    private WebElement logo;

    public SeleniumTest() {
        System.setProperty("webdriver.chrome.driver", "D:/chromedriver_810.exe");
        driver = new ChromeDriver();
        EventFiringWebDriver eventHandler = new EventFiringWebDriver(driver);
        driver = eventHandler.register(new WebDriverEventCapture());
        PageFactory.initElements(new DefaultFieldDecorator(new DefaultElementLocatorFactory(driver)), this);
    }

    public void checkFields() {
        driver.get("https://www.google.com");
        new Actions(driver).moveToElement(logo).click(logo).build().perform();
    }

    public static void main(String[] args) {
        new SeleniumTest().checkFields();
    }
}

//
--> Regardless what in the listener, the Programm fails after run immediately by Action Perform.
Starting ChromeDriver 81.0.4044.138 (8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}) on port 26480
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Okt 02, 2020 6:07:10 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
*******************
Exception in thread "main" java.lang.ClassCastException: com.sun.proxy.$Proxy6 cannot be cast to org.openqa.selenium.interactions.internal.Locatable
	at org.openqa.selenium.interactions.Actions.moveToElement(Actions.java:388)
	at testFramework.SeleniumTest.checkFields(SeleniumTest.java:30)
	at testFramework.SeleniumTest.main(SeleniumTest.java:34)

Process finished with exit code 1
******************

## Environment

OS:  Windows 10 64bit
Browser: Chrome
Browser version:  81.0.4044.113
Browser Driver version: ChromeDriver  81.0.4044.138
Language Bindings version: Java 3.141.59

**Comment by sleod** [comment]
seems be fixed with chrome driver with version 85
