### ISSUE TITLE
python: webdriver.Remote doesn't work with FirefoxOption.proxy

### ISSUE THREAD

**Issue by cupen** [SeleniumHQ/selenium#8765]
## 🐛 Bug Report
webdriver.Remote doesn't work with FirefoxOption.proxy

## To Reproduce
```python
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common import proxy

def create_remote(url='http://127.0.0.1:4444/wd/hub'):
    caps = DesiredCapabilities.FIREFOX.copy()

    opts = webdriver.FirefoxOptions()
    opts.headless = True
    opts.proxy = proxy.Proxy({
        "proxyType": proxy.ProxyType.MANUAL,
        "httpProxy": "127.0.0.1:1080",
        "socksProxy": "127.0.0.1:1080",
    })
    d = webdriver.Remote(
        command_executor=url,
        desired_capabilities=caps,
        options=opts,
    )
    return d
```
```python
create_remote()
```

```
Traceback (most recent call last):
  ......
  File "./driver.py", line 19, in create_remote
    options=opts,
  File "./.venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "./.venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "./.venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "./.venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to create session for <CreateSessionRequest with Capabilities {acceptInsecureCerts: true, browserName: firefox, marionette: true, moz:firefoxOptions: {args: [-headless], proxy: {httpProxy: 127.0.0.1:1080, proxyType: MANUAL, socksProxy: 127.0.0.1:1080}}}>
Build info: version: '4.0.0-alpha-7', revision: '117b9d61c9'
System info: host: 'bec157dbaf54', ip: '172.18.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.104-microsoft-standard', java.version: '1.8.0_265'
Driver info: driver.version: unknown
```

## Expected behavior

Make it works?

## Test script or set of commands reproducing this issue
* create_remote.py
```python
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common import proxy

def create_remote(url='http://127.0.0.1:4444/wd/hub'):
    caps = DesiredCapabilities.FIREFOX.copy()

    opts = webdriver.FirefoxOptions()
    opts.headless = True
    opts.proxy = proxy.Proxy({
        "proxyType": proxy.ProxyType.MANUAL,
        "httpProxy": "127.0.0.1:1080",
        "socksProxy": "127.0.0.1:1080",
    })
    d = webdriver.Remote(
        command_executor=url,
        desired_capabilities=caps,
        options=opts,
    )
    return d

create_remote()
```
* docker-compose.yml
```yaml
version: "3.4"
services:
  firefox:
    container_name:  firefox
    image: selenium/standalone-firefox:80.0-geckodriver-0.27-20200921
    restart: always
    ports:
      - 127.0.0.1:4444:4444
```

## Environment

Docker image:  selenium/standalone-firefox:80.0-geckodriver-0.27-20200921
OS:  Windows/docker
Browser:  Firefox
Browser version: 80.0
Browser Driver version: FirefoxDriver ??, GeckoDriver geckodriver
Language Bindings version: python-3.141.0

**Comment by diemol** [comment]
To discard it was something with the Grid, I tried this, using selenium 3.141.0, Firefox 81, GeckoDriver 0.27.0:
```python
from selenium import webdriver
from selenium.webdriver.common import proxy

firefox_options = webdriver.FirefoxOptions()
firefox_options.headless = True
firefox_options.log.level = "trace"
firefox_options.proxy = proxy.Proxy({
    "proxyType": proxy.ProxyType.MANUAL,
    "httpProxy": "127.0.0.1:1080",
    "socksProxy": "127.0.0.1:1080",
})
driver = webdriver.Firefox(options=firefox_options)
driver.get("http://www.google.com")
driver.quit() 
```

The message from GeckoDriver is: `Invalid moz:firefoxOptions field proxy`

Is there something wrong how the proxy is being set? @AutomatedTester, @whimboo

**Comment by whimboo** [comment]
Proxies are specified via [capabilities](https://w3c.github.io/webdriver/#proxy) and not `moz:firefoxOptions`. If that's still not working provide a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) for geckodriver.

**Comment by AutomatedTester** [comment]
I could not reproduce this situation but have improved the testing in this area with 401e9807cd. Feel free to raise a new bug if you have better steps to reproduce for us.
