### ISSUE TITLE
Selenium 4.0.0a6.post2 - Cant launch firefox (profile problem)

### ISSUE THREAD

**Issue by chenry35** [SeleniumHQ/selenium#8842]
## 🐛 Bug Report

Hello, 

I'm trying to use firefox with the SeleniumLib version 5.0.0b1 and Selenium 4.0.0a6.post2, but i have this error : FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\qtjw6357\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver_prefs.json

This file just doesnt exist. 
Im not using any profile

If i use selenium 3.14.1 its working perfectly.

Here the full log 👍 

DEBUG :
Traceback (most recent call last):
  File "c:\users\qtjw6357\appdata\local\programs\python\python38-32\lib\site-packages\SeleniumLibrary\__init__.py", line 490, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "c:\users\qtjw6357\appdata\local\programs\python\python38-32\lib\site-packages\robotlibcore.py", line 103, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "c:\users\qtjw6357\appdata\local\programs\python\python38-32\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 292, in open_browser
    return self._make_new_browser(
  File "c:\users\qtjw6357\appdata\local\programs\python\python38-32\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 323, in _make_new_browser
    driver = self._make_driver(
  File "c:\users\qtjw6357\appdata\local\programs\python\python38-32\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 715, in _make_driver
    driver = self._webdriver_creator.create_driver(
  File "c:\users\qtjw6357\appdata\local\programs\python\python38-32\lib\site-packages\SeleniumLibrary\keywords\webdrivertools\webdrivertools.py", line 83, in create_driver
    return creation_method(
  File "c:\users\qtjw6357\appdata\local\programs\python\python38-32\lib\site-packages\SeleniumLibrary\keywords\webdrivertools\webdrivertools.py", line 187, in create_firefox
    profile = self._get_ff_profile(ff_profile_dir)
  File "c:\users\qtjw6357\appdata\local\programs\python\python38-32\lib\site-packages\SeleniumLibrary\keywords\webdrivertools\webdrivertools.py", line 211, in _get_ff_profile
    return webdriver.FirefoxProfile()
  File "c:\users\qtjw6357\appdata\local\programs\python\python38-32\lib\site-packages\selenium\webdriver\firefox\firefox_profile.py", line 58, in __init__
    with open(os.path.join(os.path.dirname(__file__),
-->

## To Reproduce

Launch firefox via selenium 4.0.0a6.post2

Detailed steps to reproduce the behavior:

## Expected behavior

Launching Firefox.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows10
Browser: Firefox
Browser version: 72.0.2
Browser Driver version: 0.27.0
Selenium Grid version (if applicable): 4.0.0a6.post2

**Comment by AutomatedTester** [comment]
This has been fixed in the past, can't seem the exact commit.

SeleniumLibrary should try move over to passing over preferences via the `Options` object and if you need extensions use the specific API for it.
