### ISSUE TITLE
Java 1.8 compatibility issue in FirefoxProfile.java

### ISSUE THREAD

**Issue by BorisOsipov** [SeleniumHQ/selenium#8860]
## 💥 Regression Report

`java.lang.NoSuchMethodError: java.io.FileWriter.<init>(Ljava/io/File;Ljava/nio/charset/Charset;)` on jdk-1.8.0_231 due usage `public FileWriter(File file, Charset charset)` costructor that `@since 11` - avaliable only on jdk 11. See https://github.com/SeleniumHQ/selenium/blame/trunk/java/client/src/org/openqa/selenium/firefox/FirefoxProfile.java#L251

Will selenium 4 support jdk 1.8? I didn't find any info.

## Last working Selenium version
Worked up to version:
`selenium-firefox-driver:4.0.0-alpha-6`

Stopped working in version:
`selenium-firefox-driver:4.0.0-alpha-7`

## Stacktrace

```
java.io.FileWriter.<init>(Ljava/io/File;Ljava/nio/charset/Charset;)V
java.lang.NoSuchMethodError: java.io.FileWriter.<init>(Ljava/io/File;Ljava/nio/charset/Charset;)V
	at org.openqa.selenium.firefox.FirefoxProfile.updateUserPrefs(FirefoxProfile.java:251)
	at org.openqa.selenium.firefox.FirefoxProfile.layoutOnDisk(FirefoxProfile.java:376)
	at org.openqa.selenium.firefox.FirefoxProfile.toJson(FirefoxProfile.java:326)
	at org.openqa.selenium.firefox.FirefoxOptions.asMap(FirefoxOptions.java:296)
	at org.openqa.selenium.MutableCapabilities.merge(MutableCapabilities.java:83)
	at org.openqa.selenium.remote.DesiredCapabilities.merge(DesiredCapabilities.java:107)
```

## Environment
Language Bindings version: selenium-firefox-driver:4.0.0-alpha-7

**Comment by BorisOsipov** [comment]
Also selenium-grid:4.0.0-alpha-7

```
java.util.Optional.isEmpty()Z
java.lang.NoSuchMethodError: java.util.Optional.isEmpty()Z
	at org.openqa.selenium.grid.docker.DockerOptions.isEnabled(DockerOptions.java:98)
	at org.openqa.selenium.grid.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:113)
	at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:69)
	at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:195)
	at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
	at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:206)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$2(TemplateGridCommand.java:98)
	at org.openqa.selenium.grid.Main.launch(Main.java:154)
	at org.openqa.selenium.grid.Main.go(Main.java:88)
	at org.openqa.selenium.grid.Main.main(Main.java:54)
```

`Optional.isEmpty()` is 11 api

**Comment by diemol** [comment]
Thank you for reporting this, it was an honest mistake where some Java 11 bits went through.

We want to support Java 11 or higher in the future, but we have not made any decision yet on when and how to do that. So far, we will still support Java 8.
We will probably spend some time figuring out the Java versions support after Selenium 4 is released.
