### ISSUE TITLE
Python selenium 4.0.0.a7 and Python 3.6

### ISSUE THREAD

**Issue by nijel** [SeleniumHQ/selenium#8863]
## 🐛 Bug Report

`pip install selenium==4.0.0.a7` works on Python 3.6 even though it should not as it requires Python 3.7.

The setup.py [correctly specifies this limitation](https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-alpha-7/py/setup.py#L35), but the metadata seems to be missing on PyPI and in the package. Something probably went wrong when creating the release.

Compare https://pypi.org/project/selenium/4.0.0.a7/ and https://pypi.org/project/selenium/4.0.0a6.post2/

## To Reproduce

Detailed steps to reproduce the behavior:

```
virtualenv .venv-3.6  --python python3.6
.venv-3.6/bin/activate
pip install selenium==4.0.0.a7
```

## Expected behavior

The installation should fail:

```
ERROR: Package 'selenium' requires a different Python: 3.6.12 not in '~=3.7'
```

## Test script or set of commands reproducing this issue

See reproducer.

## Environment

OS: any
Browser: none
Browser version: none
Browser Driver version: N/A
Language Bindings version: Python 3.6.12
Selenium Grid version (if applicable): N/A

**Comment by nijel** [comment]
Just to give more insight (when people would be searching for the exception), the selenium import then fails with

```python-traceback
ImportError: Failed to import test module: weblate.trans.tests.test_selenium
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
   File "/home/runner/work/weblate/weblate/weblate/trans/tests/test_selenium.py", line 35, in <module>
    from selenium import webdriver
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/selenium/webdriver/__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 28, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 23, in <module>
    from contextlib import (contextmanager, asynccontextmanager)
ImportError: cannot import name 'asynccontextmanager'
```

**Comment by AutomatedTester** [comment]
I assumed the `setup.py` file would be used implicitly by bazel which appears to not be the case. I have raised https://github.com/bazelbuild/rules_python/issues/378 and will get it fixed there and patch our bazel to get it sorted
