### ISSUE TITLE
@FindBys stopped working not interacting with the respective element after i update the selenium version

### ISSUE THREAD

**Issue by Satyabrata4957** [SeleniumHQ/selenium#8900]
## 💥 Regression Report

I was using selenium 3.8.0 till yesterday and it was working perfectly fine but when I tried to enable the framework of the latest firefox I got to know with Gecko driver we need to have selenium more than 3.11 so I added the dependency of 3.141.59 after that everything messed up. The browser is opening but @Findbys elements are not readable.

I have also tried with the 3.8.0 by removing the maven classpath but it is not working at all

## Last working Selenium version

3.8.0

Stopped working in version:

3.141.59

Detailed steps to reproduce the behavior:

## Expected behavior

Test:-
/* HomePage - verify with popularity in part list page */
    @Test(dataProvider = "getPartsForPopularityCheck")
    public void verifyPopularityInPartResultPage(String partNumber) 
    {
    	int count=-1;
    	Iterator itr=productPopularityParts.iterator();
    	
    		searchQuery=partNumber.substring(0, (partNumber.length()-3));
    		System.out.println("Search query is:-"+searchQuery);
    		homePage.searchForProductPopularity(searchQuery);
			Util.waitForPageToBeLoad();
			while(itr.hasNext())
	    	{
	            String element = (String) itr.next();
	            if(element.contains(searchQuery))
	            {
	            	count++;
	            	if(element.equals(partNumber))
	            	{
	            		break;
	            	}
	            }
	         }
			Assert.assertTrue(srchResultsPage.validateThePartForProductPopularity(partNumber,count), "The Search by Suggestion is not navigating to SearchResults.");	
    }

Page:-
/*verify the product Popularity*/
		 public boolean validateThePartForProductPopularity(String partNo,int count) 
		 { 
			 clickOnListView();
			 changeSortByPopularity();
			 String part = parts.get(count).getText();
			 String []partNum = part.split(" ");
			 return (partNo.equals(partNum[0]));
		 }
Element:-
/* list of parts in partlist*/
	 @FindBys(@FindBy(xpath = "//div[@class='inner-container']//h2[@class='name ng-binding']"))
	 List<WebElement> parts;
It is unable to return any list for parts before it was working fine.

![image](https://user-images.githubusercontent.com/36322878/100038785-42411e00-2e2a-11eb-9c5e-78166f03de3e.png)

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 87.0.4280.66
Browser Driver version: Chome driver manager
Language Bindings version:  
Selenium Grid version (if applicable):  

**Error On the console** 

[RemoteTestNG] detected TestNG version 6.14.3
The Test has been Initiated.
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 87.0.4280.20 (since Google Chrome 87 is installed in your machine)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\satya\.m2\repository\webdriver\chromedriver\win32\87.0.4280.20\chromedriver.exe
ChromeDriver was started successfully.
Nov 24, 2020 7:25:10 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
/*--------------------------------------------------------------------------------------*/
Test 1 of 3
2020-11-24 07:25:15:145 : The launchUrlTest has been Started.
Launching the Application in UAT Environment, On Chrome browser.
2020-11-24 07:25:15:147 : The launchUrlTest is Passed.
/*--------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------*/
Test 2 of 3
2020-11-24 07:25:27:389 : The verifyPopularityInPartResultPage has been Started.
Search query is:-TSS
2020-11-24 07:26:13:335 : The verifyPopularityInPartResultPage is Failed.
/*--------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------*/
Test 3 of 3
2020-11-24 07:26:26:977 : The verifyPopularityInPartResultPage has been Started.
Search query is:-LAB
2020-11-24 07:26:53:427 : The verifyPopularityInPartResultPage is Failed.
/*--------------------------------------------------------------------------------------*/
Nov 24, 2020 7:27:53 AM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '500' -> incorrect JSON status mapping for 'timeout' (408 expected)
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=87.0.4280.66)
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'DESKTOP-9Q0MPR9', ip: '192.168.43.200', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_271'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.66, chrome: {chromedriverVersion: 87.0.4280.20 (c99e81631faa0..., userDataDir: C:\Users\satya\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:50558}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: none, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 6d4606fa0bcbada465d01955d3a18eb4
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:291)
	at com.cxCommerce.base.TestBase.captureScreenshot(TestBase.java:270)
	at com.cxCommerce.base.TestBase.getResults(TestBase.java:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by Satyabrata4957** [comment]
Can someone please help me ASAP I have a demo Today on this.
