### ISSUE TITLE
detect-drivers and drivers options are not working correctly

### ISSUE THREAD

**Issue by link89** [SeleniumHQ/selenium#8928]
## 🐛 Bug Report

`detect-drivers` and `drivers` options are not working correctly

## To Reproduce

I hope to only run chrome on a specific node (though it has other browsers installed for some reason.

If I set 
```toml
[node]
detect-drivers = "false"
drivers = ["chrome"]
```
then no browser will be added.

If I set 
```toml
[node]
detect-drivers = "true"
drivers = ["chrome"]
```

Then I will find that all browsers will be added, and chrome will be added twice.
```
16:59:25.523 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 2 times
16:59:25.524 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 2 times
16:59:25.525 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge"} 2 times
16:59:25.525 INFO [NodeOptions.report] - Adding Safari for {"browserName": "safari"} 1 times
16:59:25.526 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 2 times
```

Is there any combination that can just let me only have chrome enabled? 

## Expected behavior

Only chrome is added to grid.

## Environment

Mac OS
the latest build on the trunk (2020/12/01).

**Comment by dylanlive** [comment]
I've had similar experiences around this. I replicate your issue with:
`java -jar selenium-server-4.0.0-alpha-7.jar node --detect-drivers true -I "chrome"`

I'm surprised you got to work:
```
[node]
detect-drivers = "false"
drivers = ["chrome"]
```

When I run:
`java -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -jar selenium-server-4.0.0-alpha-7.jar node --detect-drivers false -I "chrome"`

The node reports:
```
09:28:08.962 INFO [NodeServer$1.start] - Starting registration process for node id 2914f38d-5f7f-4f2b-bd7c-ef2f280d01b7
09:28:08.965 INFO [NodeServer.execute] - Started Selenium node 4.0.0-alpha-7 (revision Unknown): http://192.168.86.24:5555
```

but it never actually registers itself to the hub. No warning/error log is being posted either.

My chromedriver path should be correct:
```
$ which chromedriver
/usr/local/bin/chromedriver
```

**Comment by link89** [comment]
While waiting for a fix on selenium, I just provide a lightweight solution to address the issue: https://github.com/link89/selenium-federation

**Comment by diemol** [comment]
This was just fixed in `trunk` and should be part of the next release.

To give a bit more context:
This configuration:
```toml
[node]
detect-drivers = "false"
drivers = ["chrome"]
```
Is not really valid because the Node needs to detect the drivers so it can filter and only add the specified by `drivers` (if detected, of course). But it is true that there was no clear message indicating that. After the commit linked above, you should get an exception that will look like this:

```
22:43:49.829 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
22:43:49.855 WARN [NodeOptions.addSpecificDrivers] - Specific drivers cannot be added if 'detect-drivers' is set to false
Exception in thread "main" org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:77)
	at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:195)
	at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
	at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:206)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$2(TemplateGridCommand.java:101)
	at org.openqa.selenium.grid.Main.launch(Main.java:154)
	at org.openqa.selenium.grid.Main.go(Main.java:88)
	at org.openqa.selenium.grid.Main.main(Main.java:54)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:30)
	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
	... 8 more
Caused by: org.openqa.selenium.grid.config.ConfigException: Specific drivers cannot be added if 'detect-drivers' is set to false
	at org.openqa.selenium.grid.node.config.NodeOptions.addSpecificDrivers(NodeOptions.java:180)
	at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:93)
	at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:66)
	... 16 more
22:43:49.857 INFO [LocalNewSessionQueue.callExecutorShutdown] - Shutting down session queue executor service
```

On the other hand, a configuration like this:
```toml
[node]
detect-drivers = "true"
drivers = ["chrome"]
```
Was actually duplicating the specified driver(s), the commit linked above fixes that. Now, only the drivers specified there will be added.

**Comment by pujagani** [comment]
Thank you @diemol for fixing it :)
