### ISSUE TITLE
WebElement freshness check incorrectly throws NoSuchElementException rather than StaleElementReferenceException  on Firefox 83

### ISSUE THREAD

**Issue by jtnord** [SeleniumHQ/selenium#8929]
## 🐛 Bug Report

`WebElement` is documented that all interactions will force a freshness check and throw a `StaleElementReferenceException`  if the `WebElement` is no longer attached to the DOM.`
some more commentart.

However when running with Firefox 83 a `NoSuchElementException` is thrown contrary to docs, and the illogical state that you already have the `WebElement`.  `NoSuchElementException` is also only documented to be thrown when using `findElementBy` methods

see discussion at https://github.com/jenkinsci/acceptance-test-harness/pull/625/files#r533578302 for more information

>I checked my docker images and it was working previously with Firefox 80, and got broken in Firefox 83.
> Looking at the Firefox 82 changelog, I can find this of interest
>> Element.setPointerCapture() throws the NotFoundError exception if the pointer id is invalid, as per the specification (bug 1662124). Previously it wrongly threw an InvalidPointerId exception.
>
> Which AFAIU could translate into StaleElementReferenceException vs. NoSuchElementException on selenium side.

## To Reproduce

Detailed steps to reproduce the behavior:

e.g.
```
WebElement we = ...;
we.click(); //  (to cause a page load)
while (true)  {
  try { we.isEnabled(); Thread.sleep(500L) }
  catch (StaleElementException e) {
   break; // the page is no longer displayed
}
``

## Expected behavior

the code waits in a loop until the element is no longer in the DOM.

## Actual Behaviour

exception like:

```
org.openqa.selenium.NoSuchElementException: 
 Web element reference not seen before: 1ec17ca6-ad5d-469a-ab36-c961982fc12a
 For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
 System info: host: 'host', ip: '1.2.3.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-14-amd64', java.version: '1.8.0_275'
 Driver info: org.openqa.selenium.firefox.FirefoxDriver
 Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 83.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20201112153044, moz:geckodriverVersion: 0.28.0, moz:headless: false, moz:processID: 2132, moz:profile: /tmp/rust_mozprofileuBQERw, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.9.0-14-amd64, proxy: Proxy(manual, http=host, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
 Session ID: f9c3668c-306b-4710-ae8c-749f30cf0768
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
 	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
 	at org.openqa.selenium.remote.RemoteWebElement.isEnabled(RemoteWebElement.java:156)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.lambda$new$0(EventFiringWebDriver.java:404)
 	at com.sun.proxy.$Proxy37.isEnabled(Unknown Source)
 	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.isEnabled(EventFiringWebDriver.java:457)```

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Linux
Browser: Firefox
Browser version: 83
Browser Driver version: 
Language Bindings version: 3.141.59
Selenium Grid version (if applicable): N/A

**Comment by AutomatedTester** [comment]
Thanks for the issue. Unfortunately, it is Geckodriver that is giving that error and we just pass it on. Please raise an issue on HTTPs://github.com/mozilla/geckodriver
