### ISSUE TITLE
Very high and non configurable default timeouts in HttpClient.Builder

### ISSUE THREAD

**Issue by pmouawad** [SeleniumHQ/selenium#8931]
## 🐛 Bug Report

We have an issue with IE11 and version 3.141.59 of selenium.
I think the issue has already been reported as:

- https://github.com/SeleniumHQ/selenium/issues/8488

But my report is not about this issue, but about the non configurable defaults set here:

https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/java/client/src/org/openqa/selenium/remote/http/HttpClient.java#L94

## To Reproduce

The hanging happens randomly after around 17 to 20 executions of same test.

Calling Serenity PageObject.get() with a URL hangs suddenly for hours. 
Making a thread dump shows following thread stack:

`"Forwarding newSession on session null to remote" #1 prio=5 os_prio=0 cpu=4875.00ms elapsed=5219.50s tid=0x000002ddfa9cf000 nid=0x4da4 runnable  [0x000000f8f70fc000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(java.base@11.0.2/Native Method)
    at java.net.SocketInputStream.socketRead(java.base@11.0.2/SocketInputStream.java:115)
    at java.net.SocketInputStream.read(java.base@11.0.2/SocketInputStream.java:168)
    at java.net.SocketInputStream.read(java.base@11.0.2/SocketInputStream.java:140)
    at okio.Okio$2.read(Okio.java:140)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
    at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
    at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
    at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.lambda$createClient$1(OkHttpClient.java:152)
    at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1$$Lambda$319/0x00000001003fe840.intercept(Unknown Source)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
    at okhttp3.RealCall.execute(RealCall.java:81)
    at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
    at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:221)
    at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:213)
    at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:190)
    at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:162)
    at net.serenitybdd.core.webdriver.driverproviders.InternetExplorerDriverProvider.lambda$newInstance$0(InternetExplorerDriverProvider.java:75)
    at net.serenitybdd.core.webdriver.driverproviders.InternetExplorerDriverProvider$$Lambda$304/0x00000001003cb840.newDriver(Unknown Source)
    at net.serenitybdd.core.webdriver.driverproviders.ProvideNewDriver.withConfiguration(ProvideNewDriver.java:40)
    at net.serenitybdd.core.webdriver.driverproviders.InternetExplorerDriverProvider.newInstance(InternetExplorerDriverProvider.java:71)
    at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:170)
    at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:151)
    - locked <0x00000000d17777b0> (a net.thucydides.core.webdriver.WebDriverFactory)
    at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
    at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:132)
    at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
    at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:172)
...`

Detailed steps to reproduce the behavior:

As explained in other bug, I don't have the reproduction scenario as it seems to be fully random.

Some notes still:

1) we have configured page load timeouts to 30 s calling:

`driver.manage().timeouts().pageLoadTimeout(30,` TimeUnit.SECONDS); `

But I don't think they apply to the issue here which seems to init of session with IExplore.

2) We have also set browserAttachTimeout to 10 seconds

## Expected behavior

I would expect the default timeouts to be configurable through properties and set to much lower defaults.
But maybe I missed something.

## Test script or set of commands reproducing this issue

NA

## Environment

OS:  Windows 10
Browser: IE 11
Browser version: 11.3986.14393.0
Browser Driver version: 
Language Bindings version: Java 11.0.2
Selenium Grid version (if applicable): NA
Serenity: 2.3.5 (https://github.com/serenity-bdd/serenity-core/releases/tag/v2.3.5)

**Comment by pujagani** [comment]
Regarding the point about very high defaults, that has been fixed as a part of https://github.com/SeleniumHQ/selenium/commit/ee446672339b8d2edfa98af2d1749082ccf35a65#diff-39f0711bcaef443153ffa800f0d669e587215a4e2b969e443ab31ff194c66040 for the next version or current trunk.

**Comment by barancev** [comment]
We've reduced the default timeout in version 4, but this change is not going to be backported to version 3.

**Comment by pmouawad** [comment]
Hello @barancev , @pujagani , 
Thanks for feedback.
What about adding configurable properties for them ? 

Thanks

**Comment by diemol** [comment]
If you are referring to the Grid, that's in my todo list for the next week.
