### ISSUE TITLE
AsyncHttpClient-1-4] WARN org.asynchttpclient.netty.handler.WebSocketHandler - onError

### ISSUE THREAD

**Issue by amiluslu** [SeleniumHQ/selenium#8935]
## 🐛 Bug Report

OS: MAC
ChromeDriver: 87.0.4280.88
Selenium alpha -7, selenium 4 alpha 6 
log4j2: 2.14.0
maven: 3.7.0
testng 7.3.0

dependencies:
selenium, maven, log4j2

When Tests run and it passes after method driver.quit it shows error in below
However this error sometimes shows up sometimes not  :

[AsyncHttpClient-1-4] WARN org.asynchttpclient.netty.handler.WebSocketHandler - onError
java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134)
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:830)
Dec 04, 2020 2:11:45 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection reset
java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134)
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:830)

## To Reproduce

To reproduce run your tests in your local machine simple test you will face this problem

I'm using mac and local test run. It passes and aftermethod it gives error.

Detailed steps to reproduce the behavior:

WebDriver driver = new ChromeDriver();
@BeforeTest
public void setUp(){
driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
driver.get("https://signin.ebay.com/");
}
@test
public void findElementbyXpath(){
driver.findElement(By.xpath(".//*[@id='gh-p-1']/a")).click();
}
@AfterMethod
public void afterMethod(){
driver.quit();
}

## Expected behavior

it quits driver successfully.

## Test script or set of commands reproducing this issue

classic 2 step test open browser navigate google.com close it 

## Environment

OS:  MAC
Browser:  Chrome 
Browser version: 87.0.4280.88
Browser Driver version: ChromeDriver 87.0.4280.88  
Language Bindings version:  Java 8,11 
Selenium Grid version (if applicable): Selenium 4 alpha 7 , selenium 4 alpha 6  
TestNG 7.3.0

**Comment by SalmonMode** [comment]
Can you provide the error and a minimal script to reproduce it, along with the other information requested in the ticket template?

**Comment by amiluslu** [comment]
WebDriver driver = new ChromeDriver(); 
    @BeforeTest
    public void setUp(){
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.get("https://signin.ebay.com/");
    }
    @Test
    public void findElementbyXpath(){
        driver.findElement(By.xpath(".//*[@id='gh-p-1']/a")).click();
    }
    @AfterMethod
    public void afterMethod(){
        driver.quit();
    }

**Comment by diemol** [comment]
I created a simple project with your script and I could not reproduce the issue, it could be a problem with the dependencies you are adding, which is out of the scope of this project.

Here is the link to the project I created https://github.com/diemol/selenium-issues/tree/master/selenium/issue-8823, and here is the log of my local execution:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 87.0.4280.20 (c99e81631faa0b2a448e658c0dbd8311fb04ddbd-refs/branch-heads/4280@{#355}) on port 47542
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1607206716.776][WARNING]: FromSockAddr failed on netmask
ChromeDriver was started successfully.
Dec 05, 2020 11:18:38 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Dec 05, 2020 11:18:38 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 87, so returning the closest version found: 86
Dec 05, 2020 11:18:38 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 87 of 86
Exception in thread "main" org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":".//*[@id='gh-p-1']/a"}
  (Session info: chrome=87.0.4280.88)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'SL-1256', ip: 'xx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_202-ea'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.88, chrome: {chromedriverVersion: 87.0.4280.20 (c99e81631faa0..., userDataDir: /var/folders/6n/_9hsq46s1gj...}, goog:chromeOptions: {debuggerAddress: localhost:65434}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 049b03b7b75d2038ea4f1e193d6c1d26
*** Element info: {Using=xpath, value=.//*[@id='gh-p-1']/a}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:196)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:129)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:123)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:501)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:332)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:379)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:312)
	at Issue8935.main(Issue8935.java:15)

Process finished with exit code 1
```

If you believe this is a Selenium issue, could you please provide a way to reproduce it, only using Selenium and no other 3rd party dependencies?

**Comment by amiluslu** [comment]
okay you are getting a no such element exception. When your test failed, it is okay. Your test has to be passed. When your test will passed , you will get this error.

**Comment by diemol** [comment]
Ok, I changed the locator to an element that exists:
```java
driver.findElement(By.xpath("//*[@id='create-account-link']")).click();
```
So now it is found and it still passes, log here:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 87.0.4280.20 (c99e81631faa0b2a448e658c0dbd8311fb04ddbd-refs/branch-heads/4280@{#355}) on port 2858
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1607207938.196][WARNING]: FromSockAddr failed on netmask
ChromeDriver was started successfully.
Dec 05, 2020 11:38:59 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Dec 05, 2020 11:39:00 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 87, so returning the closest version found: 86
Dec 05, 2020 11:39:00 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 87 of 86

Process finished with exit code 0
```

If you believe this is a Selenium issue, could you please provide a way to reproduce it, only using Selenium and no other 3rd party dependencies?

**Comment by amiluslu** [comment]
your test is done and finished it passed. This error occurs when you run your test 2 times or more.

**Comment by diemol** [comment]
> your test is done and finished it passed. This error occurs when you run your test 2 times or more.

This was not specified anywhere in the original report 😞 
In any case, I went and executed the script 10 times in a row, it still passes. So, please 🙏 provide a way to reproduce the issue, otherwise, we cannot help here.

**Comment by amiluslu** [comment]
This solution was related with chrome and chromedriver and cache of computer. Reinstalling of os solve the problem.

**Comment by bischoffdev** [comment]
I have the exact same issue when parallelizing tests. In a sequence, I never get this error but whenever I have two parallel Chrome webdrivers running, this happens. I am working on a minimal prototype. This works fine in Selenium 4 Alpha 3 but started failing from Alpha 4 on.
