### ISSUE TITLE
ConcurrentModificationException in GridModel when starting 4 tests concurrently

### ISSUE THREAD

**Issue by ham1** [SeleniumHQ/selenium#8942]
## 🐛 Bug Report

We sometimes see a `ConcurrentModificationException` in `GridModel.findNode(GridModel.java:248)` when running a grid in docker and starting 4 tests (requests for a Chrome) at the same time.

We run the grid like so:

```
SELENIUM_DOCKER_VER="4.0.0-alpha-7-prerelease-20201009"
SELENIUM_HUB_IMAGE="selenium/hub:${SELENIUM_DOCKER_VER}"
SELENIUM_NODE_IMAGE="selenium/node-chrome:${SELENIUM_DOCKER_VER}"
SELENIUM_GRID=selenium-hub
THREAD_COUNT=$(($(nproc) / 2)) # gives 4 on our 8 core machines

docker run \
  --rm \
  --network "${K3D_NETWORK}" \
  --add-host "${CUBE_URL}:${K3D_IP}" \
  --name ${SELENIUM_GRID} \
  -p 4442-4444:4442-4444 \
  ${SELENIUM_HUB_IMAGE} >"logs/selenium-hub.log" &

for i in $(seq 1 $THREAD_COUNT); do
  docker run \
    --rm \
    --network "${K3D_NETWORK}" \
    --link ${K3D_NETWORK}-serverlb \
    --link ${SELENIUM_GRID} \
    --add-host "${APP_URL}:${K3D_IP}" \
    -v /dev/shm:/dev/shm \
    --name "chrome-node-$i" \
    -e SE_EVENT_BUS_HOST=${SELENIUM_GRID} \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -e START_XVFB=false \
    -e HUB_HOST=${SELENIUM_GRID} \
    -e SCREEN_WIDTH=1200 \
    -e SCREEN_HEIGHT=900 \
    ${SELENIUM_NODE_IMAGE} >"logs/chrome-node-$i.log" &
done
```

The hub log file looks like:

```
2020-12-07 14:39:17,562 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2020-12-07 14:39:17,563 INFO supervisord started with pid 7
2020-12-07 14:39:18,565 INFO spawned: 'selenium-grid-hub' with pid 10
Starting Selenium Grid Hub...
2020-12-07 14:39:18,569 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
14:39:19.701 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
14:39:19.707 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
14:39:19.925 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.23.0.9:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.23.0.9:4443]
14:39:20.057 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.23.0.9:4442 and tcp://172.23.0.9:4443
14:39:20.101 INFO [UnboundZmqEventBus.<init>] - Sockets created
14:39:20.102 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
14:39:20.302 INFO [BoundZmqEventBus.<init>] - Event bus ready
14:39:21.012 INFO [Hub.execute] - Started Selenium hub 4.0.0-alpha-7 (revision bd15e4e88a): http://172.23.0.9:4444
14:39:21.624 INFO [LocalDistributor.add] - Added node f96a88b9-5860-4065-aff9-0f0d921478d2 at http://172.23.0.5:5555.
14:39:21.894 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "d9d0ba0b00f69b2b4f7c529fd9302c19","spanId": "5ab44c98ba8f7956","spanKind": "INTERNAL","eventTime": 1607351961891059782,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}

14:39:21.940 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "9cf105a71f9b0121cd068ac1285f9b10","spanId": "f0c6f3c66cf4ca9d","spanKind": "INTERNAL","eventTime": 1607351961939019355,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}

14:39:21.943 INFO [LocalDistributor.add] - Added node a9edf3d1-2906-4da5-98bb-4105fd3a385b at http://172.23.0.8:5555.
14:39:22.060 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "cd9daec5599b407ddb7b91ab24befa1b","spanId": "c17797cab9ade213","spanKind": "INTERNAL","eventTime": 1607351962059097338,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}

14:39:22.063 INFO [GridModel.setAvailability] - Switching node f96a88b9-5860-4065-aff9-0f0d921478d2 (uri: http://172.23.0.5:5555) from DOWN to UP
14:39:22.072 INFO [LocalDistributor.add] - Added node d8102fbe-6ad0-47b0-ac81-3011f541c0b4 at http://172.23.0.10:5555.
14:39:22.080 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "67146d757cb8891a8092f132a8116a91","spanId": "b215903d9837a2a5","spanKind": "INTERNAL","eventTime": 1607351962078728848,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}

14:39:22.205 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "0b111cbc4b1e1b30be7a0f0662abbd84","spanId": "44b7d05915aab4cb","spanKind": "INTERNAL","eventTime": 1607351962204414010,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}

14:39:22.208 INFO [GridModel.setAvailability] - Switching node a9edf3d1-2906-4da5-98bb-4105fd3a385b (uri: http://172.23.0.8:5555) from DOWN to UP
14:39:22.216 INFO [LocalDistributor.add] - Added node 176ef2c8-2d68-42b7-aaf1-f579d965923e at http://172.23.0.7:5555.
14:39:22.223 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "094e10b64e418228c4d75d5f930c0b29","spanId": "5703ea0aa6f1a012","spanKind": "INTERNAL","eventTime": 1607351962221740074,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}

14:39:22.364 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "f823cda7401c2d5d9cb4a270d3b4e911","spanId": "f59242f7a1593f28","spanKind": "INTERNAL","eventTime": 1607351962363780010,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}

14:39:22.367 INFO [GridModel.setAvailability] - Switching node d8102fbe-6ad0-47b0-ac81-3011f541c0b4 (uri: http://172.23.0.10:5555) from DOWN to UP
14:39:22.376 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "51df1a37ea0c2b734a806e502478cc5c","spanId": "b21cd0f3759e1432","spanKind": "INTERNAL","eventTime": 1607351962375822176,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}

14:39:22.379 INFO [GridModel.setAvailability] - Switching node 176ef2c8-2d68-42b7-aaf1-f579d965923e (uri: http://172.23.0.7:5555) from DOWN to UP
14:39:31.326 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "a9b98bde5886cf7e86800450d4a269f2","spanId": "831cdfbbb2ecfe93","spanKind": "INTERNAL","eventTime": 1607351971324647717,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fse\u002fgrid\u002fnode\u002fsession","http.method": "POST"}}

14:39:31.326 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "81d9d681ea366c3a89d98ea5bafa1118","spanId": "aaade92532456c77","spanKind": "INTERNAL","eventTime": 1607351971325812459,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fse\u002fgrid\u002fnode\u002fsession","http.method": "POST"}}

14:39:31.329 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "176c381a1f2fb02990d586446ba7f4b3","spanId": "155ec2416ff2003d","spanKind": "INTERNAL","eventTime": 1607351971326237128,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fse\u002fgrid\u002fnode\u002fsession","http.method": "POST"}}

14:39:31.333 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "79d7c73cb7b62e4b59a34f5e34a7021c","spanId": "0501177448163d1f","spanKind": "INTERNAL","eventTime": 1607351971332721570,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fse\u002fgrid\u002fnode\u002fsession","http.method": "POST"}}

14:39:31.336 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: null
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at org.openqa.selenium.grid.distributor.local.GridModel.findNode(GridModel.java:248)
	at org.openqa.selenium.grid.distributor.local.GridModel.setSession(GridModel.java:319)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.lambda$reserve$5(LocalDistributor.java:308)
	at org.openqa.selenium.grid.distributor.Distributor.newSession(Distributor.java:228)
	at org.openqa.selenium.grid.distributor.Distributor.lambda$new$0(Distributor.java:143)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:183)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.distributor.Distributor.execute(Distributor.java:293)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:85)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:261)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.server.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:30)
	at org.openqa.selenium.grid.server.WrapExceptions.lambda$apply$0(WrapExceptions.java:36)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
14:39:31.336 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "79d7c73cb7b62e4b59a34f5e34a7021c","spanId": "f95888debe3bdc97","spanKind": "INTERNAL","eventTime": 1607351971335449973,"eventName": "Added session into local session map","attributes": {"logger": "org.openqa.selenium.grid.sessionmap.local.LocalSessionMap","session.id": "1d834bab67b836ec2af01f10365aa33b"}}

```

## Environment

OS: Ubuntu 16.04
Browser: Chrome
Browser version: Grid
Browser Driver version: Grid
Language Bindings version: Java 4.0.0-alpha-7
Selenium Grid version (if applicable): 4.0.0-alpha-7-prerelease-20201009

**Comment by diemol** [comment]
@ham1, could you please use the most recent tag for the Docker images?
> https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-1-prerelease-20201208

Since alpha 7, a session queue was introduced and the code where the exception is happening has changed considerably. 

Please let us know if the issue is still happening after using the tag linked above, and if so, we'll be happy to have a look again.

**Comment by ham1** [comment]
Thanks for the reply. I did try the latest however found it to be far less stable, but couldn't find an obvious cause/stack trace. I.e. this issue happens about 1 every 1000 test runs whereas with the latest it failed every 50.

I will try again after Christmas and see what I can find.

This issue can probably be closed if the mechanism has changed.

**Comment by diemol** [comment]
When you say the "latest", do you mean the tag I linked above?

**Comment by ham1** [comment]
Yes, sorry I should have been more specific. I tried it on the same day I raised the issue, 9th Dec.

Running the same way as above. Is there a better/different way to run the latest version?

**Comment by diemol** [comment]
No, the script you provided should also work well with the latest tag. Just to get a bit more context before I try to reproduce this tomorrow, you start the containers in a VM, and then you run lots of Chrome tests, right?

**Comment by ham1** [comment]
Correct, we also run our app using k3d on the same VM, tests are written in Java and we run 4 concurrent tests on this 8 CPU 16GB RAM VM.

**Comment by chrisgleissner** [comment]
We are using a Selenium 4 hub with 6 connected Selenium 4 headless Chrome nodes, all setup on Ubuntu 18.04.5 and the latest official Docker images for hub and nodes (version 4.0.0-beta-1-prerelease-20201208 for the hub). 

Each attempt to concurrently execute tests via the Selenium Java 4.0.0-alpha-7 client on Amazon Corretto Java 11 against this grid instantly fails with an exception that appears to originate from the Selenium client. The exception occurs as soon as the test starts, presumably whilst attempting to establish a connection with the hub without having debugged it in detail. I don't have the stack trace at the moment. This is not a sporadic failure; it happens every single time.

The very same tests work fine against a Selenium 3 grid, all other environmental setup identical. The tests are executed from concurrently started Java 11 Docker containers, each connecting to the Selenium 3/4 hubs with the same URL. So there is a clear regression in terms of parallel test execution and we are therefore forced to stay on Selenium 3 for the time being. 

Sequential test execution works fine against both Selenium 3 and 4. This error only occurs for Selenium 4 and when attempting concurrent tests. 

Just adding this here to provide additional context. It may not be the same issue as reported by ham1, but it is also related to concurrent access.

**Comment by diemol** [comment]
@chrisgleissner, I think your issue is different. Please feel free to create a new issue with enough details for us to work on it.

**Comment by diemol** [comment]
@ham1, we have spent a couple of days trying to reproduce the issue and we have not bumped into it. We created a small Grid with one hub and 4 nodes, then we threw 100 tests to it, and they were handled properly.

Most likely the improvements done by @pujagani between the creation of this issue and the most recent pre-release (`4.0.0-beta-1-prerelease-20210201`), solved it.

If you'd like to, please try with the version mentioned above and let us know how it went.

**Comment by ham1** [comment]
I'm currently trying Java bindings 4.0.0-beta-1 and the grid docker image `4.0.0-beta-1-20210215`.

I fairly frequently get some different errors - I've not seen this `ConcurrentModificationException` much since raising this bug, so we can close this and I'll raise another about the latest errors we are seeing.

@diemol thank you so much for your help and time investigating!
