### ISSUE TITLE
Firefox not launching with Selenium Java Binding. On Exception Stack trace: org.openqa.selenium.WebDriverException: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by mindy14** [SeleniumHQ/selenium#8981]
## 🐛 Bug Report
Firefox browser does not launch in non headless mode when connected to a linux machine over remote connection. However the test executes properly when the browser is running in headless mode.

I am also not able to enable geckodriver logs from my java code. I have tried https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html but this doesn't work, I get the error "The method setLogLevel(Level) in the type FirefoxOptions is not applicable for the arguments (FirefoxDriverLogLevel)"

I have even tried making a wrapper in script file to launch geckodriver with the log level flag, that also didn't produce any logs. 

Also, I am not running as a root user and I am able to launch the firefox browser directly through terminal without any errors. 

Any help regarding this would be appreciated. Even any guidance of how to log geckodriver logs would be great so that I can proceed with troubleshooting myself. 

I have checked all compatibility versions of the geckodriver, selenium and FF browser, everything seems fine.

TIA.

## To Reproduce

Connect to a linux machine with GUI over a remote connection, try to run your test using selenium in non headless mode, you will get the following error:

org.openqa.selenium.WebDriverException: invalid argument: can't kill an exited process
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'apm-cent7-qa', ip: '192.168.141.19', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1127.13.1.el7.x86_64', java.version: '1.8.0_202'
Driver info: driver.version: RealBrowserDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)

## Expected behavior

Firefox browser window must launch when triggered in a linux machine over a remote session. 

## Environment

OS: Ubuntu 16
Browser: Firefox
Browser version: Firefox Developer Edition v81
Browser Driver version: Geckodriver 27 
Language Bindings version: Java 1.8.0_231
Selenium jar version: Selenium 3.141

**Comment by diemol** [comment]
@mindy14 what virtual display is configured for the browser to run?
Are you using [XVFB](https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml) or something similar?

**Comment by mindy14** [comment]
> @mindy14 what virtual display is configured for the browser to run?
> Are you using [XVFB](https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml) or something similar?

@diemol I'm using XFCE and connecting to it using xRDP

**Comment by diemol** [comment]
I've never used XFCE before, but just to show you how we do it in the Docker images (which are based on Ubuntu):

- We install [XVFB](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile#L13), so the browsers have a virtual display to use when not running in headless mode.
- We install [Fluxbox](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile#L52) as a window manager.
- And this is [how we start it](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile#L52).

When that setup is not present, you bump into the error posted above. I hope this guide you ideas on how to troubleshoot this.

Having said that, it is clearly a setup issue rather than a Selenium Grid/WebDriver issue. If you'd like more help with this setup, feel free to jump to our Slack/IRC channels where the community can give you a hand. You can see the links for the channels here: https://www.selenium.dev/support/

**Comment by mindy14** [comment]
@diemol 
The issue also happens when connected to CentOS remotely.

**Comment by diemol** [comment]
I understand, but setting up the machine is out of the scope of WebDriver and Grid. 

We can give you some hints and help at the Slack/IRC channel, we do not have the capacity to have the issue tracker as a help forum.
