### ISSUE TITLE
WebDriver.add_listener docstring example does not work in Python

### ISSUE THREAD

**Issue by jorenham** [SeleniumHQ/selenium#9010]
## 🐛 Bug Report

In the docstring of [`WebDriver.add_listener`](https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-alpha-7/py/selenium/webdriver/remote/webdriver.py#L1503), the example usage does not work. The module `selenium.webdriver.common.devtools` is imported but does not exist. **This breaks all code related to cdp events in Python.**

## To Reproduce

The full example:

```python
import asyncio

from selenium import webdriver
from selenium.webdriver.common.bidi.console import Console


async def main(*args, **kwargs):
    options = webdriver.ChromeOptions()
    for flag in args + tuple(f'{k}={v}' for k, v in kwargs.items()):
        options.add_argument(f'--{flag}')

    driver = webdriver.Chrome(options=options)
    driver.get('https://www.selenium.dev/')

    try:
        # The `Console.log` in the docstring example is incorrect as well
        async with driver.add_listener(Console.ALL) as messages:
            driver.execute_script("console.log('I like cheese')")

        assert messages["message"] == "I love cheese"

    finally:
        try:
            driver.quit()
        except Exception:
            pass


asyncio.run(main('headless'))
```

This results in:

```python-traceback
Traceback (most recent call last):
  File "/code/cdp_event_fail.py", line 29, in <module>
    asyncio.run(main('headless'))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/code/cdp_event_fail.py", line 17, in main
    async with driver.add_listener(Console.ALL) as messages:
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/code/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1522, in add_listener
    async with self._get_bidi_connection():
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/code/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1555, in _get_bidi_connection
    cdp.import_devtools(version)
  File "/code/venv/lib/python3.9/site-packages/selenium/webdriver/common/bidi/cdp.py", line 55, in import_devtools
    devtools = importlib.import_module("selenium.webdriver.common.devtools.v{}".format(version))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'selenium.webdriver.common.devtools'
```

## Expected behavior

No exceptions and assertion success.

## Environment

Irrelevant, but for the sake of completeness:

OS: Ubuntu 20.04
Browser: Chrome 
Browser version: 87
Browser Driver version: 87
Language Bindings version: Python 3.9

**Comment by AutomatedTester** [comment]
You're absolutely right and this has been fixed in trunk Fixed in a42009105200f9afc21d41fc1b825e148d33a402
