### ISSUE TITLE
Selenium Prerelease Beta causes WebDriver exception

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#9079]
## 🐛 Bug Report

As per https://github.com/SeleniumHQ/selenium/issues/8974#issuecomment-762957299 I tried running my tests with the newest selenium jars. However, with both new jars i started getting an exception when the test is about to open a menu in our application

## Exception

```
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {error=script timeout, message=Returned value cannot be converted to WebElement: {message=invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=87.0.4280.141)
  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 6.1.7601 SP1 x86_64)}
Build info: version: '4.0.0-beta-1', revision: '02d5e641d5'
System info: host: 'PRIVATE', ip: 'PRIVATE', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '11.0.2'
Driver info: driver.version: RemoteWebDriver, stacktrace=org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {message=invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=87.0.4280.141)
  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 6.1.7601 SP1 x86_64)}
Build info: version: '4.0.0-beta-1', revision: '02d5e641d5'
System info: host: 'PRIVATE', ip: 'PRIVATE', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '11.0.2'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:354)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:497)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:328)
	at org.openqa.selenium.grid.node.CustomLocatorHandler.execute(CustomLocatorHandler.java:202)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.node.Node.execute(Node.java:220)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.web.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:29)
	at org.openqa.selenium.grid.web.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.grid.web.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
}
Build info: version: '4.0.0-beta-1', revision: '02d5e641d5'
System info: host: 'PRIVATE', ip: '172.18.68.193', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:354)
	at org.openqa.selenium.By$ById.findElement(By.java:210)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:328)
	at PRIVATE$1.apply(PRIVATE.java:320)
	at PRIVATE$1.apply(PRIVATE.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:210)
	at PRIVATE.findElement(PRIVATE.java:318)
	at PRIVATE.openMenuByIdPath(PRIVATE.java:339)
	at PRIVATE.openSpecificMenu(PRIVATE.java:311)
	at PRIVATE.openList(PRIVATE.java:209)
	at PRIVATE.openListByType(PRIVATE.java:870)
	at PRIVATE.openObjectTypeList(PRIVATE.java:890)
	at PRIVATE(PRIVATE.java:403)
	at PRIVATE(PRIVATE.java:420)
	at PRIVATE(PRIVATE.java:136)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
## Test script or set of commands reproducing this issue

start C:/"Program Files"/Java/jdk-11.0.2/bin/java -jar selenium-server-beta.jar hub --port 4452 --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456

Node
start C:/"Program Files"/Java/jdk-11.0.2/bin/java -jar selenium-server-beta.jar node --detect-drivers true -I "chrome" -I "edge" -I "internet explorer" --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --max-sessions 1

## Environment
OS: Windows 7
Browser: IE, Chrome
Browser version: IE 11.0.9600.19356
IE Browser Driver version: 3.150.1
Browser version: Chrome 87.0.4280.141
Chrome Browser Driver version: 87.0.4280.88
Selenium Grid version : Grid 4 (4.0.0-alpha-7)

**Comment by hnestorova** [comment]
![1](https://user-images.githubusercontent.com/30794708/105344646-e4437380-5beb-11eb-9553-0383d0616cee.PNG)
![2](https://user-images.githubusercontent.com/30794708/105344647-e574a080-5beb-11eb-858d-4a067f0345df.PNG)

**Comment by diemol** [comment]
Do you have a test script to reproduce the issue?

**Comment by hnestorova** [comment]
Well, the code on our side is private so i cannot provide it but it is working as expected with alpha 7

**Comment by diemol** [comment]
We need any code that helps to reproduce the issue, it does not need to be the one you use privately. It seems the selector is showing some problems.

**Comment by barancev** [comment]
1) We'd like to see what locator was used
2) Can you reproduce the issue without grid?

**Comment by hnestorova** [comment]
Hi 
Luckily, today i tried to reproduce the issue with the latest beta version and it was not reproducible so I think we can close

**Comment by diemol** [comment]
Thank you for letting us know, @hnestorova!
