### ISSUE TITLE
[selenium4] [chromedriver] Startup timeout

### ISSUE THREAD

**Issue by sininit** [SeleniumHQ/selenium#9123]
## Description

When I use selenium4 to launch multiple Chrome browsers at the same time, the following error may appear
```
Exception in thread "Thread-9" org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'PC-20200910MRCL', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_212'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:210)
	at top.fols.winapp.zdfsp.CommandMain$3.run(CommandMain.java:459)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.InterruptedException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:204)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:95)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:227)
	at org.openqa.selenium.remote.service.DriverService.lambda$start$0(DriverService.java:193)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
	at java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:88)
	... 8 more
```
At first I thought it was a problem with my code, but I returned to selenium3 and started chrome without these errors.

## To Reproduce

```
//Normal start
//Creating ChromeDriver directly without using ChromeDriverService is the same result
for (int i = 0; i< 10; i++) {
	ChromeDriverService service = new ChromeDriverService.Builder()
			.usingDriverExecutable(new File("C:\\documents\\360Sync\\JAVA\\Yzs\\ZiDongFaShiPin\\res\\webdriver\\chrome\\App\\chromedriver.exe"))
			.usingAnyFreePort()
			.build();
	service.start();
	System.out.println(service.getUrl());
	WebDriver webDriver = new ChromeDriver(service);
	webDriver.get("http://www.baidu.com");
}
```

```
//timeout
//Creating ChromeDriver directly without using ChromeDriverService is the same result
for (int i = 0; i< 10; i++) {
   new Thread(){
	   @Override
	   public void run() {
		   ChromeDriverService service = new ChromeDriverService.Builder()
				   .usingDriverExecutable(new File("C:\\documents\\360Sync\\JAVA\\Yzs\\ZiDongFaShiPin\\res\\webdriver\\chrome\\App\\chromedriver.exe"))
				   .usingAnyFreePort()
				   .build(); 
		   try {
			   service.start();
		   } catch (IOException e) {
			   e.printStackTrace();
		   }
		   System.out.println(service.getUrl());
		   WebDriver webDriver = new ChromeDriver(service);
		   webDriver.get("http://www.baidu.com");
	   }
   }.start();
}
```

## Expected behavior
Like selenium3, i can start multiple chrome browsers at the same time without timeout

## Environment
```
OS: Windows 10 AND Windows7
Browser: Chrome?
Browser version: 86.0.4240.75
Browser Driver version: ChromeDriver 86.0.4240.22
Language Bindings version: Java 1.8.0_212
```
Selenium Grid version (if applicable): selenium4 alpha-7

**Comment by pujagani** [comment]
Thank you for providing the details for the bug. I was able to reproduce the error. After attempts on fixing the code and ruling out the problem areas, I suspect the issue is happening due to the system running out of resources.
When running the given examples with a minor tweak for creating 35 instances of ChromeDriver using Selenium version 3.141.0, results in the following time-out error: 

```
Feb 03, 2021 3:47:27 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Feb 03, 2021 3:47:50 PM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "/Users/Puja/Downloads/chromedriver" (in directory "."): error=23, Too many open files in system)
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:09:30'
System info: host: 'dockerpuja', ip: '2405:201:c:1019:bd76:b88e:1ac8:fb6f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '11.0.7'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:193)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:179)
	at com.company.ChromeDriverStartupIssue.main(ChromeDriverStartupIssue.java:22)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:9197/status] to be available after 20015 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:188)
	... 2 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 3 more
```

The behaviour is not consistent, in case it was able to create sessions for all the drivers, it was unable to load the requested url. When I started killing the browsers one by one (resources freed up), it was then able to fetch the requested url.

With 4.0.0-Alpha-7, `timeoutexception` happens with fewer instances, internally more threads might be used. 

To rule out Java bindings related issue, I ran the same example using C# bindings for Selenium 3.141.0 and 4.0.0-Alpha-7. Same timeout error was seen. 

To rule out ChromeDriver specific error, I tried running the example using the FirefoxDriver in Java and C# for  Selenium 3.141.0 and 4.0.0-Alpha-7.  Again, for 3.141.0 FirefoxDriver requires more instances (50 or more for my machine) to lead to the `timeoutexception` in Java but 15 instances for C#. 

Calling `driver.quit()` is recommended to free up resources but even then it might not help to create a stable environment to run tests parallelly since browsers do take up system resources. 
Since in all the cases, initial sessions are created then things begin to slow down/halt, it indicates that machine cannot handle the load and might not respond as expected thus leading to timeouts.

To create a stable environment I would recommend using Selenium Grid for parallel testing, it has a mechanism to set up the environment based on the processors on the machine thus avoiding overloading and not impacting tests.
Please refer https://www.selenium.dev/documentation/en/grid/ to learn and setup Grid :)

**Comment by sininit** [comment]
I only started five Chrome on my computer and then
Start five Chrome immediately, it will timeoutException
But if you wait for a longer time before starting, this will not happen
If it is selenium3, there is no such situation

 
CPU platform is Intel 9400+8G
The same result on E3-1230V2+16GB. Unfortunately, I don’t know how to use Selenium Grid.

If you can, you can consider debugging on my device
.

**Comment by sininit** [comment]
My contact information is 
telegram: t.me/selenium_alpha7

**Comment by pujagani** [comment]
Please refer to https://www.selenium.dev/documentation/en/grid/grid_4/ to get started with the Grid. It is very simple to get started with the Grid actually. The test code does not change much. It leverages the RemoteWebDriver. 

Step 1 : 
Download the latest  jar from https://github.com/SeleniumHQ/docker-selenium/tree/beta-jars

Step 2: 
Run 
` java -jar selenium-server-4.0.0-prerelease-beta-1-1f4909f59c.jar standalone --relax-checks true`

Step 3: 
Run tests against it : 
Adding a modified test script below: 

```
for (int i = 0; i< 10; i++) {
   new Thread() {
	   @Override
	   public void run() {
                   ImmutableCapabilities capabilities = new ImmutableCapabilities("browserName", "chrome");
		    WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), capabilities);
		   webDriver.get("http://www.baidu.com");
	   }
   }.start();
}

```

**Comment by JohnA2** [comment]
I have the same problem with 4.0.0-alpha-7 and Java. One system can't run more than 6 sessions in parallel and another can't even handle more than 2 in parallel. It happens with multiple browsers (I tried Firefox, Chrome and IE). Reverting to Selenium 3.14 resolves the problem. The system that could only run 2 tests in parallel without errors with 4.0 can run 30 with 3.14!

I didn't check if this issue also affects Grid, but in any case, I disagree that always using Grid is a good solution. It's much better to run locally at least when writing and testing the the code initially.

**Comment by sininit** [comment]
Yes, I think Grid may not fully reflect the problem
