### ISSUE TITLE
SOCKS5 authentication not working

### ISSUE THREAD

**Issue by xtianus** [SeleniumHQ/selenium#9176]
## 🐛 Bug Report

I'm connecting to the target server via a SOCKS5 proxy that requires username/password authentication.
I'm doing this with a patched version of  Selenium hub+node ``3.141.59`` that fixes the "Long vs Integer" bug with a merge from branch ``3.14.0-issue-6917-patch`` https://github.com/mablhq/selenium/commit/801be37639e0050d976dc2972fc236da334f175a.
Still my connection is refused by the proxy.
I can see from the Chrome logs ``chrome://net-export/`` that the proxy ip and port are correct, but I don't see any auth information so I can't tell if it's a Selenium or a Chrome problem.

Hub log:

```
21:32:28.586 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, goog:chromeOptions: {args: [user-data-dir=C:\srv\vlbdev..., --no-sandbox, user-agent=Mozilla/5.0 (Mac...], extensions: []}, proxy: {proxyType: manual, socksPassword: xxxxxx, socksProxy: 193.xxx.xxx.xxx:9183, socksUsername: xxxxxx, socksVersion: 5}}
```

Node log:

```
21:32:28.641 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "goog:chromeOptions": {
    "args": [
      "user-data-dir=C:\\srv\\vlbdev\\somewhere",
      "--no-sandbox",
      "user-agent=Mozilla\u002f5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit\u002f537.36 (KHTML, like Gecko) Chrome\u002f80.0.3987.163 Safari\u002f537.36"
    ],
    "extensions": [
    ]
  },
  "proxy": {
    "proxyType": "manual",
    "socksPassword": "xxxxxxx",
    "socksProxy": "193.xxx.xxx.xxx:9183",
    "socksUsername": "xxxxxxx",
    "socksVersion": 5
  }
}
```

Error received on the client:

```
org.openqa.selenium.WebDriverException:` unknown error: net::ERR_SOCKS_CONNECTION_FAILED

Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.150, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: C:\srv\vlbdev\xxx...}, goog:chromeOptions: {debuggerAddress: localhost:54429}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(manual, socks=193.xxx..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: a315c24a74530f2d1b3ca73663f...}
Session ID: a315c24a74530f2d1b3ca73663f7cd1d
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
```

## To Reproduce

Get a patched version of 3.141.59 (mine is here https://drive.google.com/drive/folders/1Z_7_ibx1eLJLrtiBERNrXelWaH-wW6y0?usp=sharing)
Start hub and node with

    java -jar selenium-server-standalone-3.141.59-issue-6917-patch.jar -role hub -timeout 300 -browserTimeout 60 -cleanUpCycle 10000 -newSessionWaitTimeout 20000

    java -Dwebdriver.chrome.driver="C:\somewhere\chromedriver.exe" -jar selenium-server-standalone-3.141.59-issue-6917-patch.jar -role node -hub http://localhost:4444/grid/register -browser browserName=chrome,maxInstances=5 -maxSession 5 -registerCycle 10000

Start your java client using the patched "api" jar and set a proxy on the connection:

```
Proxy proxy = new Proxy();
proxy.setSocksVersion(5);
proxy.setSocksProxy(proxyHost + ":" + proxyPort);
proxy.setSocksUsername(proxyUser);
proxy.setSocksPassword(proxyPassword);
MutableCapabilities capability = new ChromeOptions();
capability.setCapability(CapabilityType.PROXY, proxy);
WebDriver driver = new RemoteWebDriver(remoteAddress, capability);
... use driver to fetch a page
```

## Expected behavior

The target server should be reached.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 88.0.4324.150
Browser Driver version: chromedriver-88.0.4324.96
Language Bindings version: Java 3.141.59 patched 
Selenium Grid version (if applicable): 3.141.59 patched

**Comment by xtianus** [comment]
Oh well, Chrome doesn't support SOCKS authentication apparently: https://bugs.chromium.org/p/chromium/issues/detail?id=256785
