### ISSUE TITLE
Selenium "execute" does not work with FirefoxDriver when "security.csp.enable" is set to "true" 

### ISSUE THREAD

**Issue by vladikoff** [SeleniumHQ/selenium#918]
The "execute" command discussed in this bug is in the spec here: http://www.w3.org/TR/webdriver/#dfn-execute-script

### STR

1. Run Selenium tests with a custom Firefox profile
1. Set `security.csp.enable` to `true` in that custom profile
1. Have a test that POSTS to `/session/{session id}/execute` with JavaScript it wants to execute

### Expected
`.execute` should run the script when CSP is enabled

### Actual

```
11:47:22.634 INFO - Executing: [execute script: return (function () {
        try {
          localStorage.clear();
          sessionStorage.clear();
        } catch(e) {
          console.log('Failed to clearBrowserState');
          // if cookies are disabled, this will blow up some browsers.
        }
        return true;
      }).apply(this, arguments);, []])
11:47:33.524 WARN - Exception thrown
org.openqa.selenium.WebDriverException: waiting for evaluate.js load failed
Command duration or timeout: 10.54 seconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'Vlads-MacBook-Pro.local', ip: '10.242.29.24', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=39.0, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 0b4fa311-5bf5-9345-9816-ca62042bc001
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:504)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
	at com.sun.proxy.$Proxy1.executeScript(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.executeScript(EventFiringWebDriver.java:214)
	at org.openqa.selenium.remote.server.handler.ExecuteScript.call(ExecuteScript.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Other info

This bug was on the old issue tracker but does not exist in this issue tracker.
Tested this in 2.47.1. Currently the FirefoxDriver disables CSP security by default

**Comment by barancev** [comment]
Unfortunately, FirefoxDriver can't work with CSP enabled.
You'll have to wait till MarionetteDriver hits the ground running.
