### ISSUE TITLE
IE Driver Server does not read protected mode correctly

### ISSUE THREAD

**Issue by longgraham** [SeleniumHQ/selenium#919]
After upgrading to IE 11 the IEDriverServer will no longer run correctly. I get the "Protected Mode settings are not the same for all zones." error message. However, all of my protected mode settings are enabled when I look at them from the IE11 UI. 
I tried downgrading back to IE 9, but this did not fix the problem. I have followed all of the required configuration settings from https://code.google.com/p/selenium/wiki/InternetExplorerDriver. 
Currently I am using IE 11 and the 32-bit version of the IEDriverServer. Here is the log when set to DEBUG:

I 2015-08-12 10:23:53:250 server.cc(75) Starting WebDriver server on port: '1505' on host: ''
D 2015-08-12 10:23:53:251 server.cc(113) Civetweb ACL is -0.0.0.0/0,+127.0.0.1
Started InternetExplorerDriver server (32-bit)
2.47.0.0
Listening on port 1505
Log level is set to DEBUG
D 2015-08-12 10:23:54:027 server.cc(246) Command: GET /status {}
D 2015-08-12 10:23:54:028 server.cc(320) Response: {"sessionId":"","status":0,"value":{"build":{"version":"2.47.0.0"},"os":{"arch":"x64","name":"windows","version":"6.1.7601"}}}

D 2015-08-12 10:23:54:615 server.cc(246) Command: POST /session {"desiredCapabilities":{"platform":"WINDOWS","ensureCleanSession":true,"browserName":"internet explorer","version":""}}
D 2015-08-12 10:23:54:615 IESession.cpp(52) Mutex acquired for session initalization
D 2015-08-12 10:23:54:615 IESession.cpp(97) Using legacy driver implementation per user request
D 2015-08-12 10:23:54:652 IESession.cpp(131) Releasing session initialization mutex
D 2015-08-12 10:23:54:652 command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"platform":"WINDOWS","ensureCleanSession":true,"browserName":"internet explorer","version":""}} }
D 2015-08-12 10:23:54:652 BrowserFactory.cpp(80) Ignoring Protected Mode Settings: 0
D 2015-08-12 10:23:54:652 BrowserFactory.cpp(83) Checking validity of Protected Mode settings.
D 2015-08-12 10:23:54:652 BrowserFactory.cpp(1037) Detected IE version: 11, detected Windows version: 6
D 2015-08-12 10:23:54:652 BrowserFactory.cpp(1127) Found Protected Mode setting value of 3 for zone 1
D 2015-08-12 10:23:54:652 BrowserFactory.cpp(1127) Found Protected Mode setting value of 3 for zone 2
D 2015-08-12 10:23:54:652 BrowserFactory.cpp(1127) Found Protected Mode setting value of 0 for zone 3
D 2015-08-12 10:23:54:652 BrowserFactory.cpp(86) Has Valid Protected Mode Settings: 0
W 2015-08-12 10:23:54:652 IECommandExecutor.cpp(650) Unable to launch browser, received NULL process ID
W 2015-08-12 10:23:54:652 response.cc(77) Error response has status code 6 and message 'Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.' message
W 2015-08-12 10:23:54:652 IECommandExecutor.cpp(539) Unable to get current browser
D 2015-08-12 10:23:54:662 server.cc(197) Shutdown session is not found
D 2015-08-12 10:23:54:662 server.cc(320) Response: {"sessionId":"3fc8c27e-1565-4d96-b5bf-659671218b2b","status":6,"value":{"message":"Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones."}}

And here is the exception:

FAILED CONFIGURATION: @BeforeMethod setUp
org.openqa.selenium.remote.SessionNotFoundException: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.79 seconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'XXXXXXXX', ip: 'xx.xx.xx.xx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:162)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:225)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:182)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:174)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:146)
	at testCases.InitiateFederalAgencyEnrollmentTest.setUp(InitiateFederalAgencyEnrollmentTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

I am hoping to summon Jim Evans. This seems like an issue specific to my environment, of which I have little control over. However, I am able to request changes and usually get them performed in a timely manner. Any help on how to debug this situation will be greatly appreciated. Additionally, if this is not the proper forum for this issue I apologize.

**Comment by longgraham** [comment]
To summarize: why would the IEDriverServer interpret the protected mode settings differently than IE 11 would display them in the UI?

**Comment by jimevans** [comment]
No idea why the browser would display different Protected Mode settings. The driver is simply looking in the registry for the setting values, which should be the same. The driver is looking in the following registry location:

    HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones

Under that key, there are typically 5 subkeys, cleverly named `0`, `1`, `2`, `3`, and `4`. Each subkey represents a Protected Mode zone, and in each there is a DWORD value with the name `2500`. If this value has a numeric value of `0`, Protected Mode is **_on_** for that zone; a numeric value of `3` means Protected Mode is **_off_** for that zone. As backward as that seems (`0` == "on"), it's true nevertheless. Check the registry to see what values it has on the machine in question. If those registry values are out of sync with the browser UI (and there's no group policy in place that might override that), I don't know what to tell you.

If your initial setup of the machine involved editing the registry to set Protected Mode settings, make sure you're using `HKEY_CURRENT_USER` instead of `HKEY_LOCAL_MACHINE`.

**Comment by jimevans** [comment]
Two months without the requested information from the reporter. Closing issue.
