### ISSUE TITLE
selenium4.0b1 the func driver.log.add_listener cant work

### ISSUE THREAD

**Issue by Swj-ningbo** [SeleniumHQ/selenium#9196]
## 🐛 Bug Report

selenium4.0b1 the func driver.log.add_listener cant work
```$(python)
import asyncio
from selenium import webdriver
from selenium.webdriver.common.bidi.console import Console

async def main():
    driver = webdriver.Chrome()
    driver.get('http://192.168.70.45/#/login')
    async with driver.log.add_listener(Console.ERROR) as messages:
        driver.execute_script("console.error(\"I don't cheese\")")
        driver.execute_script("console.log('I love cheese')")
    assert messages["message"] == "I don't cheese"

asyncio.run(main())
```
the raise error
```$(cmd)
DevTools listening on ws://127.0.0.1:62557/devtools/browser/615bde01-4012-4cda-a6e5-818e28dc10f8
[7004:17476:0220/165151.754:ERROR:device_event_log_impl.cc(211)] [16:51:51.755] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[7004:17476:0220/165151.755:ERROR:device_event_log_impl.cc(211)] [16:51:51.756] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[7004:17476:0220/165151.769:ERROR:device_event_log_impl.cc(211)] [16:51:51.769] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[7004:17476:0220/165151.785:ERROR:device_event_log_impl.cc(211)] [16:51:51.785] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
Traceback (most recent call last):
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\a5036\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\a5036\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\a5036\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\workspace\study\test\test1.py", line 16, in <module>
    asyncio.run(main())
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\workspace\study\test\test1.py", line 10, in main
    async with driver.log.add_listener(Console.ERROR) as messages:
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "c:\workspace\study\test\venv\lib\site-packages\selenium\webdriver\remote\log.py", line 143, in add_listener
    async with self._get_bidi_connection():
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "c:\workspace\study\test\venv\lib\site-packages\selenium\webdriver\remote\log.py", line 180, in _get_bidi_connection
    async with cdp.open_cdp(ws_url) as conn:
  File "C:\Users\a5036\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "c:\workspace\study\test\venv\lib\site-packages\selenium\webdriver\common\bidi\cdp.py", line 459, in open_cdp
    async with trio.open_nursery() as nursery:
  File "c:\workspace\study\test\venv\lib\site-packages\trio\_core\_run.py", line 796, in __aenter__
    self._scope.__enter__()
  File "c:\workspace\study\test\venv\lib\site-packages\trio\_core\_ki.py", line 159, in wrapper
    return fn(*args, **kwargs)
  File "c:\workspace\study\test\venv\lib\site-packages\trio\_core\_run.py", line 449, in __enter__
    task = _core.current_task()
  File "c:\workspace\study\test\venv\lib\site-packages\trio\_core\_run.py", line 2267, in current_task
    raise RuntimeError("must be called from async context") from None
RuntimeError: must be called from async context
```

## To Reproduce

Detailed steps to reproduce the behavior:
Stable error report after running the above code

## Expected behavior

dont raise error

## Test script or set of commands reproducing this issue

```$(python)
import asyncio
from selenium import webdriver
from selenium.webdriver.common.bidi.console import Console

async def main():
    driver = webdriver.Chrome()
    driver.get('http://192.168.70.45/#/login')
    async with driver.log.add_listener(Console.ERROR) as messages:
        driver.execute_script("console.error(\"I don't cheese\")")
        driver.execute_script("console.log('I love cheese')")
    assert messages["message"] == "I don't cheese"

asyncio.run(main())
```

## Environment

OS: Windows 10
Browser: Chrome 
Browser version: 88.0.4324.182
Browser Driver version: chromedriver.exe 88.0.4324.96
Language Bindings version: Python 3.8.2 64-bit

**Comment by AutomatedTester** [comment]
We're using `trio` instead of `asyncio`. If you import `trio-asyncio` to get `asyncio` functionality and you can use `pytest-trio` for testing.

I will improve the documentation.
