### ISSUE TITLE
Mocha fails to run tests running with selenium-webdriver version `4.0.0-beta.1`

### ISSUE THREAD

**Issue by RoniSegal** [SeleniumHQ/selenium#9221]
## 🐛 Bug Report

I have mocha tests that tests ui code using selenium,
 got the following error since the last release

/var/lib/jenkins/workspace/SL.OnPremise.Agents.JavaScript-monorepo/test/agent-tests/cases/selenium/angular-7/node_modules/selenium-webdriver/lib/webdriver.js:1363
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/lib/jenkins/workspace/SL.OnPremise.Agents.JavaScript-monorepo/test/agent-tests/cases/selenium/angular-7/node_modules/selenium-webdriver/lib/http.js:34:24)

**Comment by AutomatedTester** [comment]
Could you give us a reduced test case as our test suite is functioning

**Comment by diemol** [comment]
Closing as we did not get more information.
