### ISSUE TITLE
Unable to upload file(15MB) in remote machine and failing with JsonParser Error

### ISSUE THREAD

**Issue by vinaygadegela** [SeleniumHQ/selenium#9285]
## 🐛 Bug Report

While running in local machines, we are able to upload test files of different sizes upto 20 MB, however when running the same in browserstack (remote machine), getting exceptions

**Observed for 10 MB file**

org.openqa.selenium.WebDriverException: <html>

 <head>
<title>Error 500 Java heap space</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2><pre>Java heap space</pre>
<p>RequestURI=/wd/hub/session/63f218bdcf65131f207deca3188104671ed5f084/file</p>
<p><i><small><a href="http://jetty.mortbay.org">Powered by Jetty://</a></small></i></p>
</body>
</html> 
![8-6-mb](https://user-images.githubusercontent.com/7877445/111138469-fadfc880-85a5-11eb-837a-0b66e4f6182a.png)

Command duration or timeout: 3.51 seconds

**Observed for 15 MB file**
Caused by: com.google.gson.JsonParseException: Failed parsing JSON source: JsonReader at line 1 column 16719873 to Json

Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_271'

## To Reproduce
Navigate to https://the-internet.herokuapp.com/upload
Try to upload any file of 15 mb (attached 15 mb file)

Detailed steps to reproduce the behavior:

Try to upload any file of 15 mb in https://the-internet.herokuapp.com/upload in remote machine and observe that we are getting JsonParseException

## Test script or set of commands reproducing this issue

WebDriver driver= new RemoteWebDriver(new URL("RemoteUrl@hub-cloud.browserstack.com/wd/hub/"),
                new CapabilityHelper().addCapability("chrome", "latest", "windows", "10", ""));
 ((RemoteWebDriver) driver).setFileDetector(new LocalFileDetector());
  driver.get("https://the-internet.herokuapp.com/upload");
 driver.findElement(By.cssSelector("input[type='file']")).sendKeys("D:\\15-4-mb.pdf");
[15-4-mb.pdf](https://github.com/SeleniumHQ/selenium/files/6140477/15-4-mb.pdf)

## Environment

OS:   Windows 10 
Browser:  Chrome 
Browser version: 89
Browser Driver version: ChromeDriver 89.0.4389.23
Language Bindings version:  Java 1.8
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment]
Do you get the same error when using Grid 4? (We do not support Grid 3 anymore) Or do you only get it when using BrowserStack?

**Comment by vinaygadegela** [comment]
Got the same exception with Selenium '4.0.0-alpha-6' 

Below is the piece of code, i have used 

 DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("os", "Windows");
        caps.setCapability("os_version", "10");
        caps.setCapability("browser", "Chrome");
        caps.setCapability("browser_version", "latest");
        WebDriver driver= new RemoteWebDriver(new URL("http://url@hub-cloud.browserstack.com/wd/hub/"), caps);
        ((RemoteWebDriver) driver).setFileDetector(new LocalFileDetector());
        driver.get("https://the-internet.herokuapp.com/upload");
        driver.findElement(By.cssSelector("input[type='file']")).sendKeys("D:\\15-4-mb.pdf");
      

and observed below stack trace

INFO: Detected dialect: OSS
**Exception in thread "main" org.openqa.selenium.WebDriverException: Failed parsing JSON source: JsonReader at line 1 column 16719873 to Json (WARNING: The server did not provide any stacktrace information)**
Command duration or timeout: 0 milliseconds
Build info: version: '4.0.0-alpha-6', revision: '5f43a29cfc'
System info: host: 'PRINHYLTPDL1787', ip: '192.168.0.106', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: C:\Windows\proxy\scoped_dir...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:2506}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 89.0.4389.72, webStorageEnabled: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 2b3bfdc56c9ec75bce43f0bcf3e...}
Session ID: 2b3bfdc56c9ec75bce43f0bcf3ec352a35e55072
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:217)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:169)
	at org.openqa.selenium.remote.codec.jwp.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:41)
	at org.openqa.selenium.remote.codec.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:83)
	at org.openqa.selenium.remote.codec.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:47)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:582)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:316)
	at org.openqa.selenium.remote.RemoteWebElement.upload(RemoteWebElement.java:125)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:112)
	at SampleUpload.main(SampleUpload.java:26)

I tried only with Browserstack and didn't checked with remote nodes

**Comment by diemol** [comment]
>I tried only with Browserstack and didn't checked with remote nodes

We cannot troubleshoot issues only with BrowserStack or other cloud vendors. I'd recommend to reach out to their customer support.

If you are still having the issue when trying it with Grid 4, please let us know and we'd be happy to reopen the issue.
