### ISSUE TITLE
Webdriver opens browser with "data:" and times out

### ISSUE THREAD

**Issue by arul1981** [SeleniumHQ/selenium#9364]
## 🐛 Bug Report

I am trying to open chrome browser in my company network and navigating to http://www.google.com. From code it opens browser with "data:" and not doing anything until it timeout. But the same script works with headless. I get the same issue with edge browser as well

## To Reproduce

System.setProperty("webdriver.chrome.driver", "C:\\driver\\chromedriver.exe");
 ChromeOptions o = new ChromeOptions();
  o.setBinary("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe");
        o.setExperimentalOption("useAutomationExtension", false);
        o.addArguments("--no-sandbox");
        o.addArguments("--disable-extensions");
WebDriver driver = new ChromeDriver(o);
 driver.get("https://www.google.com");

Error:
[1617879375.127][SEVERE]: Timed out receiving message from renderer: 600.000
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created
from timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=88.0.4324.150)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.18363 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 600.96 seconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'GBMLVVCSW6604', ip: '', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)

**Comment by diemol** [comment]
Do you need any proxy configuration to reach the url?

**Comment by saurabhkankriya** [comment]
I am facing the same issue. The URL gets opened when I paste it in the browser manually but fails to get open when run through the script. It just shows data and then times out.

**Comment by diemol** [comment]
Can you please paste the full log and what versions of Selenium, Chrome and ChromeDriver are you using? Are you using the most recent versions?

**Comment by Quinee** [comment]
Update the Chromedriver . I have received the SessionNotCreated Exception when chromedriver.exe was outdated

**Comment by arul1981** [comment]
This can be closed now, the issue is resolved. After I got elevated access to my corporate web browser it is working fine. Sorry, I didnt know there was something exists like this before.

**Comment by diemol** [comment]
Thanks for letting us know.
