### ISSUE TITLE
Selenium 4 beta RemoteWebDriver cannot instantiate with Proxy

### ISSUE THREAD

**Issue by pritesh-patil** [SeleniumHQ/selenium#9445]
## 🐛 Bug Report

The exception is thrown on the RemoteWebDriver object instantiation when selenium 4 beta 1/2/3 used with proxy.  Same piece of code working with Selenium v3.141.59 with proxy.  We are using BrowserStack's remote hub url and which is already whitelisted in corporate network. Proxy is not getting honoured with selenium 4 java binding.

## To Reproduce

Need to use proxy and (public) hub url offered like BrowserStack https://hub-cloud.browserstack.com

Detailed steps to reproduce the behavior:

## Expected behavior

RemoteDriver should able to connect with BS hub with proxy.

## Test script or set of commands reproducing this issue

      <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.0.0-beta-3</version>
        </dependency>

        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>4.0.0-beta-3</version>
        </dependency>

----------
      package com.sample;
      
      import org.openqa.selenium.Capabilities;
      import org.openqa.selenium.WebDriver;
      import org.openqa.selenium.remote.DesiredCapabilities;
      import org.openqa.selenium.remote.RemoteWebDriver;
      
      import java.net.URL;
      
      public class Runner {

    public static final String AUTOMATE_USERNAME = "userName";
    public static final String AUTOMATE_ACCESS_KEY = "AccessKey";
    public static final String hub = "https://" + AUTOMATE_USERNAME + ":" + AUTOMATE_ACCESS_KEY + "@hub-cloud.browserstack.com/wd/hub";
    public static WebDriver driver = null;

    public static void main(String[] args) {
        setProxy();
        try {
            driver = new RemoteWebDriver(new URL(hub), getBSCapabilities());
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (driver != null) {
            driver.get("https://www.google.com");
            driver.quit();
        }
    }

    public  static Capabilities getBSCapabilities(){
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("os", "Windows");
        caps.setCapability("os_version", "10");
        caps.setCapability("browser", "Chrome");
        caps.setCapability("browser_version", "80");
        caps.setCapability("browserstack.localIdentifier", "xyz");
        return caps;
    }

    private static void setProxy() {
        System.getProperties().put("http.proxyHost", "host");
        System.getProperties().put("http.proxyPort", "8080");
        System.getProperties().put("http.proxyUser", "user");
        System.getProperties().put("http.proxyPass", "psw");

        System.getProperties().put("https.proxyHost", "host");
        System.getProperties().put("https.proxyPort", "8080");
        System.getProperties().put("https.proxyUser", "user");
        System.getProperties().put("https.proxyPass", "psw");
    }
}

You will get exception like 

     May 05, 2021 4:51:49 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
        INFO: Using OpenTelemetry for tracing
        org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
        Build info: version: '4.0.0-beta-1', revision: '9c03156c2b'
        System info: host: 'XXXXXXXXX', ip: 'XXXXXXXXXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
        Driver info: org.openqa.selenium.remote.RemoteWebDriver
        Command: [null, newSession {desiredCapabilities=Capabilities {browserName: Chrome, bstack:options: {buildName: BUILD_NAME, chrome: Capabilities {browserName: ..., consoleLogs: info, debug: true, local: true, localIdentifier: LocalIdentifier, maskCommands: setValues, getValues, setCo..., networkLogs: true, os: Windows, osVersion: 10, projectName: Sampe Test , sessionName: Test Session}}}]
        Capabilities {}
	        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:252)
	        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:152)
	        at com.sample.Runner.main(Runner.java:27)
        Caused by: java.io.UncheckedIOException: java.net.ConnectException: connection timed out: hub-cloud.browserstack.com/185.44.131.206:443
	        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
	        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:93)
	        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:56)
	        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:103)
	        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:153)
	        at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:39)
	        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:620)
	        ... 4 more
        Caused by: java.net.ConnectException: connection timed out: hub-cloud.browserstack.com/185.44.131.206:443
	        at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	        at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
	        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	        at java.lang.Thread.run(Thread.java:748)
        Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: hub-cloud.browserstack.com/185.44.131.206:443
	        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	        ... 9 more

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 90
Language Bindings version: Java  4.0.0-beta-1/2/3

**Comment by diemol** [comment]
This will be fixed by #9434, and be part of the `beta-4` release.
