### ISSUE TITLE
Selenium4b ignores webdriver.chrome.binary

### ISSUE THREAD

**Issue by SiKing** [SeleniumHQ/selenium#9452]
## 💥 Regression Report

In previous versions I was able to set `webdriver.chrome.binary` to point to my google-chrome-beta browser binary. In Selenium 4 beta (I checked 1 through 3), this property is ignored.

## Last working Selenium version

Worked up to version: 3.141.59

Stopped working in version: 4.0.0-beta-1 (I checked up to beta-3)

## To Reproduce

Detailed steps to reproduce the behavior:

1. Take any working test, for Selenium 4.
2. Add `webdriver.chrome.binary = /any/invalid/path`.
3. Test will still pass, and it should not.

## Expected behavior

I would like to be able to point to different versions of chrome browser, on a machine that has multiple installations - for example: stable and beta. Ideally using the same mechanism as what worked in Selenium 3.

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Linux 
Browser: Chrome 
Browser version: any, I used 91.0.4472.38 beta 
Browser Driver version: any matching, I used 91.0.4472.19 
Language Bindings version: Java 4.0.0-beta-3 
Selenium Grid version (if applicable): n/a

**Comment by diemol** [comment]
Can you please provide the commands and code used to bump into this issue? We need more than a narrative description, thank you!

**Comment by SiKing** [comment]
I am having a difficult time wrapping my head around what is going on. :-\

I created the following little test [AlternateBrowserTest.zip](https://github.com/SeleniumHQ/selenium/files/6444528/AlternateBrowserTest.zip)

```java
package tests;

import org.apache.commons.lang3.BooleanUtils;
import org.junit.After;
import org.junit.Test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AlternateBrowserTest {

    private static final Logger log = LoggerFactory.getLogger(AlternateBrowserTest.class);

    ChromeDriver driver;

    @After
    public void tearDown() throws Exception {

	if (driver != null) {
	    driver.quit();
	    driver = null;
	}
    }

    /**
     * Assumes you have chromedriver is on your PATH.
     */
    @Test
    public void test_AlternateBrowser() {

	log.info("webdriver.chrome.binary : " + System.getProperty("webdriver.chrome.binary"));
	log.info("webdriver.chrome.driver : " + System.getProperty("webdriver.chrome.driver"));

	ChromeOptions options = new ChromeOptions();
	boolean headless = BooleanUtils.toBoolean(System.getProperty("headless.mode"));
	options.setHeadless(headless);

	driver = new ChromeDriver(options);
	log.info("browser : " + ((JavascriptExecutor) driver).executeScript("return navigator.userAgent;"));
    }
}
```

If I run this with Google Chrome 90 (current stable version) + matching Chrome driver + Selenium 4-b-3, everything works fine.

If I run this with Google Chrome 91 (current Beta version) + matching Chrome driver + Selenium 4-b-3, if fails! Here are the relevant parts from my logs:

```
[INFO] Running tests.AlternateBrowserTest
14:59:50.910-0700 [main] [INFO] AlternateBrowserTest - webdriver.chrome.binary : /usr/bin/google-chrome-beta
14:59:50.917-0700 [main] [INFO] AlternateBrowserTest - webdriver.chrome.driver : /var/lib/jenkins/jobs/QA/jobs/--redacted--/workspace/selenium/bin/linux/googlechrome/64bit/chromedriver
Starting ChromeDriver 91.0.4472.19 (1bf021f248676a0b2ab3ee0561d83a59e424c23e-refs/branch-heads/4472@{#288}) on port 20234
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
May 07, 2021 3:00:01 PM org.openqa.selenium.os.OsProcess destroy
INFO: Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
	at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
	at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:180)
	at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:135)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:152)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:275)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:140)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:619)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:251)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:89)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:86)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:75)
	at tests.AlternateBrowserTest.test_AlternateBrowser(AlternateBrowserTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

May 07, 2021 3:00:01 PM org.openqa.selenium.os.OsProcess destroy
SEVERE: Unable to kill process java.lang.UNIXProcess@22f59fa
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.821 s <<< FAILURE! - in tests.AlternateBrowserTest
[ERROR] test_AlternateBrowser(tests.AlternateBrowserTest)  Time elapsed: 10.737 s  <<< ERROR!
org.openqa.selenium.SessionNotCreatedException: 
Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 90.0.4430.93 with binary path /usr/bin/google-chrome
Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
System info: host: --redacted--, ip: --redacted--, os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1127.18.2.el7.x86_64', java.version: '1.8.0_262'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {desiredCapabilities=Capabilities {browserName: chrome}}]
	at tests.AlternateBrowserTest.test_AlternateBrowser(AlternateBrowserTest.java:42)
```

Specifically these two lines:

```
14:59:50.910-0700 [main] [INFO] AlternateBrowserTest - webdriver.chrome.binary : /usr/bin/google-chrome-beta
...
Current browser version is 90.0.4430.93 with binary path /usr/bin/google-chrome
```

Why the different browsers?

**Comment by SiKing** [comment]
I discovered my problem.

I have been using the [Serenity BDD](https://github.com/serenity-bdd/serenity-core) framework for a while now. The `webdriver.chrome.binary` property is part of Serenity, and **not** Selenium.

This user error. :(

Perhaps a feature request? :D

**Comment by diemol** [comment]
@SiKing, can you share your pom? We need to know what version of JUnit you are using.

**Comment by SiKing** [comment]
I was able to confirm (above) this is user-error.

I am using JUnit 4.13.2.

I was able to work around my problem by adding:
```
// since we're not in Serenity-BDD
if (System.getProperty("webdriver.chrome.binary") != null
        && !System.getProperty("webdriver.chrome.binary").isEmpty())
    options.setBinary(System.getProperty("webdriver.chrome.binary"));
```

**Comment by diemol** [comment]
Great, thank you for confirming this.
