### ISSUE TITLE
Grid with two Amazon Windows Instances: hub throws java.net.ConnectException: connection timed out: after adding the node

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#9488]
## 🐛 Bug Report

**We have two Windows instances in Amazon and are trying to use one as a hub and node and the other as a node to connect to the first one. However, after the node gets connection, the below error is printed in the hub console:**

'11:28:23.899 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
11:28:23.899 INFO [LocalDistributor.add] - Added node 99eec165-506f-4a61-b379-3b2e72c3ab56 at http://NODE_IP:5555.
11:28:33.946 WARN [UnboundZmqEventBus.lambda$notifyListeners$10] - Caught exception from listener: org.openqa.selenium.events.EventListener@3f5ec77a
java.io.UncheckedIOException: java.net.ConnectException: connection timed out: /10.146.226.253:5555
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:79)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:103)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.grid.node.remote.RemoteNode.getStatus(RemoteNode.java:207)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.add(LocalDistributor.java:233)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.register(LocalDistributor.java:220)
        at org.openqa.selenium.events.EventListener.accept(EventListener.java:43)
        at org.openqa.selenium.events.EventListener.accept(EventListener.java:25)
        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus.lambda$notifyListeners$10(UnboundZmqEventBus.java:252)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: connection timed out: /NODE_IP:5555
        at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
        at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)'

**On the node side, in its console we see:**
'11:28:23.553 INFO [NodeServer.execute] - Started Selenium node 4.0.0-beta-3 (revision 5d108f9a67): http://NODE_IP:5555
11:28:23.819 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:28:33.820 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:28:43.829 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:28:53.830 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:29:03.855 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:29:13.859 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:29:23.959 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:29:33.988 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:29:44.003 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:29:54.005 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:30:04.009 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:30:14.020 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:30:23.565 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:30:23.565 INFO [NodeServer$1.lambda$start$1] - Sending registration event...'

## Expected behavior

Both nodes connect successfully to the hub. I use the same configuration with VMs and it has no such problem

## Test script or set of commands reproducing this issue

**Hub**
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-beta-3.jar hub --port 4452 --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --healthcheck-interval 5000

**Node (Hub instance)**
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-beta-3.jar node --detect-drivers true -I "edge" -I "chrome" -I "internet explorer" --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --max-sessions 1 --session-timeout 190

**Node (2nd instance)**
start C:/"Program Files"/Java/jdk-11.0.9+11/bin/java -jar selenium-server-4.0.0-beta-3.jar node --detect-drivers true -I "edge" -I "chrome" -I "internet explorer" --publish-events tcp://HUB_IP:4455 --subscribe-events tcp://HUB_IP:4456 --max-sessions 1 --session-timeout 190

## Environment

OS: Windows 7
Browser: Edge, Chrome
Edge Browser version: Version 90.0.818.62 (Official build) (64-bit)
Edge Browser Driver version: MSEdgeDriver 89.0.774.76
Browser version: Version 90.0.4430.212 (Official Build) (64-bit)
Chrome Browser Driver version: ChromeDriver 90.0.4430.24 
Selenium Grid version : Grid 4 ( selenium-server-4.0.0-beta-3.jar)

**Comment by diemol** [comment]
The Hub needs to have access to the Node IP, since it cannot reach the Node, it cannot accept the registration and therefore the Node will try to register again.

Please double check that the Node IP and port are reachable from the Hub.

**Comment by hnestorova** [comment]
Thank you. I tried with tracert from both machines and they seem to find each other. I will further check

**Comment by hnestorova** [comment]
Hi again

You are correct - I allowed all inbound traffic for the node and the hub from each other's IP and it works now

Thanks!
