### ISSUE TITLE
Python first/always logic in the client doesn't work with arrays as values

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#9538]
## 🐛 Bug Report

The python first/always logic in the python client doesn't successfully handle the case where capability values are arrays

## To Reproduce

```
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver import FirefoxOptions

alternative_1 = FirefoxOptions()
alternative_1.set_capability("vendor:sameList", [])

alternative_2 = FirefoxOptions()
alternative_2.set_capability("vendor:sameList", [])

WebDriver(options=[alternative_1, alternative_2])
```

## Expected behavior

Everything works as expected

## Actual behavior

```
/Users/bob/.pyenv/versions/selenium/bin/python /blah/blah/blah/selenium/try.py
Traceback (most recent call last):
  File "/blah/blah/blah/selenium/try.py", line 8, in <module>
    WebDriver(options=[alternative_1, alternative_2])
  File "/Users/bob/.pyenv/versions/selenium/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 224, in __init__
    capabilities = create_matches(options)
  File "/Users/bob/.pyenv/versions/selenium/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 133, in create_matches
    samesies.update(opts[min_index].items() & opts[i + 1].items())
TypeError: unhashable type: 'list'
```

## Test script or set of commands reproducing this issue

See above

## Environment

OS: macOS
Browser: Firefox
Browser version: n/a
Browser Driver version: n/a
Language Bindings version: pre-beta4
Selenium Grid version (if applicable): n/a

**Comment by AutomatedTester** [comment]
Looking at this it only seems to appear when the list is empty. I can recreate the issue when I do the following test

```python
def test_can_set_multiple_options_with_different_arrays():
    from selenium.webdriver.firefox.options import Options as FirefoxOptions

    expected = {
        "capabilities": {
            "alwaysMatch": {
                "browserName": "firefox",
                "pageLoadStrategy": "normal",
                "platform": "ANY",
                "version": ""
            },
            "firstMatch": [
                {
                    "vendor:sameList": []
                },
                {
                    "vendor:sameList": []
                }
            ]
        }
    }
    alternative_1 = FirefoxOptions()
    alternative_1.set_capability("vendor:sameList", [])

    alternative_2 = FirefoxOptions()
    alternative_2.set_capability("vendor:sameList", [])

    result = webdriver.create_matches([alternative_1, alternative_2])

    assert result == expected

```

However, a similar test that populates an array is passing as we can see in the test in https://github.com/SeleniumHQ/selenium/blob/trunk/py/test/unit/selenium/webdriver/remote/new_session_tests.py#L76-L100 so wonder if there is a bug in python here or at least my understanding of how the union code should work in the python standard library
