### ISSUE TITLE
ChromeDriver failing to attach to ChromiumBrowser in application after upgrade from Cefsharp 89.0.170 to 90.6.70 

### ISSUE THREAD

**Issue by Phatado** [SeleniumHQ/selenium#9562]
## 🐛 Bug Report

We have a UI automation suite that uses ChromeOptions.BinaryLocation to point at our windows application which in turn houses the chromiumbrowser that we want to connect to.  

As this starts up on a background thread and we normally get back a chromeDriver. After upgrading from Cefsharp 89.0.170 to 90.6.70 we upgraded our corresponding ChromeDriver to 90.0.4430.24 - but now we get a failure when initialising the ChromeDriver.  

ChromeOptions options = new ChromeOptions();
        options.AddArgument("--no-sandbox");
        options.AddArgument("--disable-dev-shm-usage");
        options.AddArgument("--headless");
        options.AddArgument("--verbose");
        options.AddArgument("--log-path=c:\\tmp\\ChromeBrowser.log");
        options.AddArgument("--remote-debugging-port=9222");
        options.AddArgument(@"user-data-dir=" + Path.GetTempPath());
        options.AddArgument("--profile-directory=Default");

        string anbPath = AnbRunner.AnbPath;
        anbPath = anbPath.Replace("\\", "/");
        anbPath = anbPath.Replace("\"", "");
        options.BinaryLocation = anbPath;

mWebDriver = new ChromeDriver(currentDir, options, TimeSpan.FromSeconds(600));

The application starts up but immediately shuts down and we get the following errors:Exception thrown: 'System.UnauthorizedAccessException' in ANB.UIAutomation.Framework.dll
An exception of type 'System.UnauthorizedAccessException' occurred in ANB.UIAutomation.Framework.dll but was not handled in user code
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
at interop.UIAutomationCore.IUIAutomationElement.get_CurrentName()
at ANB.ScreenObjects.MainScreen..ctor() in C:\RTC\Constable_Sandbox\Constable_AutomatedTest_Source Component\ANB.UIAutomation.Framework\ScreenObjects\ANB\MainScreen.cs:line 30
at ANB.Helpers.Tasks.get_MainScreen() in C:\RTC\Constable_Sandbox\Constable_AutomatedTest_Source Component\ANB.UIAutomation.Framework\Helpers\Tasks.cs:line 90
at ANBP.ScreenObjects.ConnectToDataSourceDialog.get_Dialog() in C:\RTC\Constable_Sandbox\Constable_AutomatedTest_Source Component\ANB.UIAutomation.Framework\ScreenObjects\ANBP\ConnectToDataSourceDialog.cs:line 19
at ANBP.Helpers.ConnectToDataSourceHelper.IsDialogPresent() in C:\RTC\Constable_Sandbox\Constable_AutomatedTest_Source Component\ANB.UIAutomation.Framework\Helpers\ANBP\ConnectToDataSourceHelper.cs:line 24
at ANBP.Helpers.AnbpRunner.Run(String arguments) in C:\RTC\Constable_Sandbox\Constable_AutomatedTest_Source Component\ANB.UIAutomation.Framework\Runners\AnbpRunner.cs:line 130
at ANB.Helpers.Tasks.RunANBP(String anbArguments) in C:\RTC\Constable_Sandbox\Constable_AutomatedTest_Source Component\ANB.UIAutomation.Framework\Helpers\Tasks.cs:line 54
at ANB.Framework.ANBPTestBase.TestSuiteSetup() in C:\RTC\Constable_Sandbox\Constable_AutomatedTest_Source Component\ANB.UIAutomation.Framework\ANBPTestBase.cs:line 43
at ANBP.Tests.AutoFailExpected.TestSuiteSetup() in C:\RTC\Constable_Sandbox\Constable_AutomatedTest_Source Component\ANB.UIAutomation.Tests\ANBP\Auto Fail Expected.cs:line 15
at ANB.Framework.ANBTestBase.RunBeforeTestSuite() in C:\RTC\Constable_Sandbox\Constable_AutomatedTest_Source Component\ANB.UIAutomation.Framework\ANBTestBase.cs:line 50

I believe the issue is that it's getting the Application briefly - but then as goes to query it with IUIAutomationElement.get_CurrentName() the app closes.

I have to admit I did not set these tests up initially and so not the expert in there, but I have tried setting up logging in the ChromeBrowser (as you can see in the chromeOptions) but it's not writing out to the log.

I can start the ChromeDriver in a cmd prompt by itself and I can start the app and run it by itself and that all works with the new CEF version 90.6.70...

**Comment by diemol** [comment]
Please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
