### ISSUE TITLE
Selenium TimeoutException

### ISSUE THREAD

**Issue by dinsaw** [SeleniumHQ/selenium#9604]
## 🐛 Bug Report

Selenium timeouts after running multiple tests.  Issue is found in selenium-4-beta2, beta-3 and beta-4 versions. ~5% of our sessions fail on these jar versions.

Exception : Error or timeout while getting Distributor status: null
```
exception.stacktrace="java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at org.openqa.selenium.grid.router.GridStatusHandler.execute(GridStatusHandler.java:85)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
	at org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:51)
	at org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:54)
	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
```

## To Reproduce

Issue is reproduced by running sessions multiple times. 

## Expected behavior

The selenium jar should be working properly even after running multiple tests.

## Test script or set of commands reproducing this issue

Sample code for reproducing issues. We have to run below test multiple times
```
require 'rubygems'
require 'selenium-webdriver'
require 'date'

url = "http://username:password@hub-cloud.browserstack.com/wd/hub"

caps = Selenium::WebDriver::Remote::Capabilities.new
caps["os"] = "Windows"
caps["os_version"] = "10"
caps["browser"] = "Firefox"
caps["browser_version"] = "latest"
caps["browserstack.local"] = "false"
caps["browserstack.selenium_version"] = "4.0.0-beta-3"
caps['build'] = "W10"

puts "Loaded caps"

driver = Selenium::WebDriver.for(:remote,
  :url => url,
  :desired_capabilities => caps)

driver.navigate.to "https://duckduckgo.com"

element = driver.find_element(:name, "q")
element.send_keys "BrowserStack"
element.submit

sleep 1

puts "After sleep"
puts "Title #{driver.title}"

sleep 1
driver.quit 

```

## Environment

OS:  All Windows versions  
Browser: Chrome
Browser version: 89
Browser Driver version: NA
Language Bindings version:  Na
Selenium Grid version (if applicable): Na

**Comment by diemol** [comment]
Can this be reproduced with Selenium Grid (without BrowserStack)? Have you reached to their customer support?

**Comment by pujagani** [comment]
Thank you for providing the details. The issue persisted when sessions are running and /status endpoint is pinged at regular intervals. This was reproducible for Beta-2 and Beta-3. However, it does not persist with the Beta-4. Beta-2, Beta-3 and Beta-4 had additional timeouts related to the Netty time instance issue. The current version in the trunk fixes the random Netty timeouts. It will be available in the next release. 
Meanwhile, the same changes are available in the recent prerelease 
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210713. Please check it out. Thank you!
