### ISSUE TITLE
Unable to take full page screenshot

### ISSUE THREAD

**Issue by abhishek140389** [SeleniumHQ/selenium#9619]
Hi Team,

i am unable to take full page screenshot , my code is below, i am using java 8.
ChromeOptions options = new ChromeOptions();
//options.addArguments("headless");
driver = new ChromeDriver(options);
driver.get("https://aib.ie");
driver.manage().window().maximize();
Screenshot screenshot=new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(driver); //getting error here while taking full page screenshot.

Maven

org.seleniumhq.selenium selenium-java 3.13.0 compile
		
		<dependency>
			<groupId>ru.yandex.qatools.ashot</groupId>
			<artifactId>ashot</artifactId>
			<version>1.5.4</version>
			<scope>compile</scope> 
		</dependency>
Error

rg.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.RuntimeException: java.lang.NullPointerException
at ru.yandex.qatools.ashot.util.InnerScript.execute(InnerScript.java:32)
at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getFullHeight(ViewportPastingDecorator.java:67)
at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:41)
at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:35)
at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:145)

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!
