### ISSUE TITLE
URL-navigation throws CommandResponseException about getting response body after headers received

### ISSUE THREAD

**Issue by BoundedChenn31** [SeleniumHQ/selenium#9655]
## 🐛 Bug Report

Unable to open any page with enabled network monitoring because of  exception:
```
Unhandled exception. Unhandled exception. OpenQA.Selenium.DevTools.CommandResponseException: Fetch.getResponseBody: Can only get response body on requests captu
red after headers received.
   at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand(String commandName, JToken params, CancellationToken cancellationToken, Nullable`1 millisecondsTimeou
t, Boolean throwExceptionIfResponseNotReceived)
   at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand[TCommand,TCommandResponse](TCommand command, CancellationToken cancellationToken, Nullable`1 millisec
ondsTimeout, Boolean throwExceptionIfResponseNotReceived)
   at OpenQA.Selenium.DevTools.V91.Fetch.FetchAdapter.GetResponseBody(GetResponseBodyCommandSettings command, CancellationToken cancellationToken, Nullable`1 mi
llisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
   at OpenQA.Selenium.DevTools.V91.V91Network.AddResponseBody(HttpResponseData responseData)
   at OpenQA.Selenium.NetworkManager.OnResponsePaused(Object sender, ResponsePausedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
OpenQA.Selenium.DevTools.CommandResponseException: Fetch.getResponseBody: Can only get response body on requests captured after headers received.
   at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand(String commandName, JToken params, CancellationToken cancellationToken, Nullable`1 millisecondsTimeou
t, Boolean throwExceptionIfResponseNotReceived)
   at OpenQA.Selenium.DevTools.DevToolsSession.SendCommand[TCommand,TCommandResponse](TCommand command, CancellationToken cancellationToken, Nullable`1 millisec
ondsTimeout, Boolean throwExceptionIfResponseNotReceived)
   at OpenQA.Selenium.DevTools.V91.Fetch.FetchAdapter.GetResponseBody(GetResponseBodyCommandSettings command, CancellationToken cancellationToken, Nullable`1 mi
llisecondsTimeout, Boolean throwExceptionIfResponseNotReceived)
   at OpenQA.Selenium.DevTools.V91.V91Network.AddResponseBody(HttpResponseData responseData)
   at OpenQA.Selenium.NetworkManager.OnResponsePaused(Object sender, ResponsePausedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

## To Reproduce
**Program.cs**
```cs
using System;
using OpenQA.Selenium.Chrome;

using var chromeDriver = new ChromeDriver();
await chromeDriver.Manage().Network.StartMonitoring();
chromeDriver.Url = "https://www.selenium.dev";
Console.ReadLine();
```
**Project file**
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Selenium.WebDriver" Version="4.0.0-beta4" />
      <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="91.0.4472.10100" />
    </ItemGroup>

</Project>
```

## Expected behavior

Be able to navigate to the page.

## Test script or set of commands reproducing this issue

Please see steps to reproduce above.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 91.0.4472.124
Browser Driver version: ChromeDriver 91.0.4472.101
Language Bindings version: dotnet 4.0.0-beta4
Selenium Grid version (if applicable): N/A

**Comment by jimevans** [comment]
Fixed in 2a03bde
