### ISSUE TITLE
windows node not registering to dockerized hub

### ISSUE THREAD

**Issue by dahud10001** [SeleniumHQ/selenium#9675]
## 🐛 Bug Report

When connecting to the Linux hub, the node just keeps resending Sending registration event. 

Host Error:

```
18:07:25.696 WARN [UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2] - Caught exception from listener: org.openqa.selenium.events.EventListener@4024f47c
org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.grid.data.NodeStatus
Build info: version: '4.0.0-rc-1', revision: '74745cf081'
System info: host: '23b731438d5f', ip: '172.50.240.3', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.24.1.el7.x86_64', java.version: '11.0.11'
Driver info: driver.version: unknown
        at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
        at org.openqa.selenium.json.Json.toType(Json.java:69)
        at org.openqa.selenium.json.Json.toType(Json.java:55)
        at org.openqa.selenium.json.Json.toType(Json.java:50)
        at org.openqa.selenium.events.Event.getData(Event.java:59)
        at org.openqa.selenium.events.EventListener.accept(EventListener.java:43)
        at org.openqa.selenium.events.EventListener.accept(EventListener.java:25)
        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.lambda$notifyListeners$2(UnboundZmqEventBus.java:273)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
        ... 14 more
Caused by: java.lang.IllegalArgumentException: Node id must be set
        at org.openqa.selenium.internal.Require.nonNull(Require.java:56)
        at org.openqa.selenium.grid.data.NodeStatus.<init>(NodeStatus.java:58)
        at org.openqa.selenium.grid.data.NodeStatus.fromJson(NodeStatus.java:123)
        ... 18 more

```

Node Startup:
``` java -jar selenium-server-4.0.0-beta-4.jar node --publish-events tcp://host.name.net:4442 --subscribe-events tcp://host.name.net:4443  --host host.name.net --port 5555 ```

Docker-compose:

```
 20   node-docker:
 21     image: selenium/node-docker:4.0
 22     volumes:
 23       - ./assets:/opt/selenium/assets
 24       - ./config.toml:/opt/bin/config.toml
 25     depends_on:
 26       - selenium-hub
 27     env_file:
 28       - proxy.env
 29     environment:
 30       - SE_EVENT_BUS_HOST=selenium-hub
 31       - SE_EVENT_BUS_PUBLISH_PORT=4442
 32       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
 33       - SE_OPTS=--session-timeout 180
 34     networks:
 35       - selenium
 36
 37   selenium-hub:
 38     image: selenium/hub:4.0
 39     container_name: selenium-hub
 40     volumes:
 41       - ./resolv.conf:/etc/resolv.conf:ro
 42     ports:
 43       - "4442:4442"
 44       - "4443:4443"
 45       - "4444:4444"
 46     networks:
 47       - selenium
 48 networks:
 49    selenium:
 50      driver: bridge
 51      ipam:
 52        driver: default
 53        config:
 54         - subnet: 172.50.240.0/24

```

Host Config:
```
  1 [node]
  2 session-timeout = 60
  3
  4 [docker]
  5 # Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
  6 # start a container with the given image.
  7 configs = [
  8     "selenium/standalone-firefox:4.0", "{\"browserName\": \"firefox\"}",
  9     "selenium/standalone-chrome:4.0", "{\"browserName\": \"chrome\"}"
 10     ]
 11
 12 # URL for connecting to the docker daemon
 13 # host.docker.internal works for macOS and Windows.
 14 # Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
 15 # To have Docker listening through tcp on macOS, install socat and run the following command
 16 # socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
 17 url = "http://host.name.net:2375"
 18 # Docker imagee used for video recording
 19 video-image = "selenium/video:ffmpeg-4.3.1-20210713"
 20
 21 # Uncomment the following section if you are running the node on a separate VM
 22 # Fill out the placeholders with appropriate values
 23 #[server]
 24 #host = <ip-from-node-machine>
 25 #port = <port-from-node-machine>
```

The host docker container is able to ping port 5555 on the node.
It can also pull the 5555/status when using wget. 

## To Reproduce

Detailed steps to reproduce the behavior:

1. Build linux containers.
2. Start windows java jar.

## Expected behavior

The Windows node should connect to the linux host.

## Test script or set of commands reproducing this issue

na

## Environment

OS: Windows Server 2016, Rhel 7.9
Browser: Chrome
Browser version: 91
Selenium Grid version (if applicable): 4.0.0-rc-1

**Comment by diemol** [comment]
Please use the same in the Windows machine the same jar binary that is used in the Docker images. 
You can find it here https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210713

**Comment by diemol** [comment]
Also, please use the complete Docker tag in the images.

**Comment by dahud10001** [comment]
thanks, once updated, it started to work
