### ISSUE TITLE
cannot clone DesiredCapabilities with org.apache.commons.lang3.SerializationUtils

### ISSUE THREAD

**Issue by gogro** [SeleniumHQ/selenium#9703]
## 🐛 Bug Report

cannot clone org.openqa.selenium.DesiredCapabilities with org.apache.commons.lang3.SerializationUtils.clone()

```
org.apache.commons.lang3.SerializationException: IOException while reading or closing cloned object data

	at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:98)
	at testing.SerializationTest.Test_serializeDesiredCapabilities(SerializationTest.java:12)
        ... more
Caused by: java.io.InvalidClassException: org.openqa.selenium.remote.DesiredCapabilities; no valid constructor
	at java.base/java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:159)
	at java.base/java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:875)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2140)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1668)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:482)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:440)
	at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:92)
	... 28 more

```

## To Reproduce

clone empty or filled DesiredCapabilities with SerializationUtils.clone()

## Expected behavior

- no org.apache.commons.lang3.SerializationException is thrown
- DesiredCapabilities are cloned successfully

## Test script or set of commands reproducing this issue

```
package testing;

import org.apache.commons.lang3.SerializationUtils; // Maven: org.apache.commons:commons-lang3:3.9
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.Assert;
import org.testng.annotations.Test;

public class SerializationTest {
    @Test
    public void Test_serializeDesiredCapabilities() {
        DesiredCapabilities dc = new DesiredCapabilities();
        dc.setCapability("k", "v"); // this line can be left out to reproduce
        DesiredCapabilities clone = SerializationUtils.clone(dc);
        Assert.assertNotNull(clone);
    }
}

```

## Environment
OS : Windows 10, build 19042.1110
Language Bindings version : Java, Maven: org.seleniumhq.selenium:selenium-api:3.141.59
JDK / JVM : Azul JVM / JDK 11.0.8
Browser : any

## Possible fix
Make constructor org.openqa.selenium.AbstractCapabilities() public.
This could be an implicit requirement of the implementations of java.io.ObjectStreamClass and java.io.ObjectOutputStream - at least for consumption of Serializable by org.apache.commons.lang3.SerializationUtils.

**Comment by diemol** [comment]
What happens when you use Selenium 4 Beta 4?

**Comment by diemol** [comment]
Closing as we did not get an answer.
