### ISSUE TITLE
Grid 4: TOML Parameter for setting log file location doesn't work

### ISSUE THREAD

**Issue by ccarmannt** [SeleniumHQ/selenium#9717]
## 🐛 Bug Report

The TOML file parameter for setting the log file location doesn't work, throwing an exception when the server is launched.

## To Reproduce

Define the following in a TOML config file:

````
[logging]
# File to write out logs
# Type: string
# Example:
log-file = \my\path\goes\here\Logs\hub.log
````

Then invoke the server like this:

````
java -jar selenium-server-4.0.0-beta-4.jar hub --config hub.toml
````

The following exception will be thrown:

````
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: io.ous.jtoml.ParseException: Newline expected after assignment at 18:14
        at io.ous.jtoml.impl.Parser.error(Parser.java:250)
        at io.ous.jtoml.impl.Parser.parse(Parser.java:51)
        at io.ous.jtoml.JToml.parse(JToml.java:35)
        at org.openqa.selenium.grid.config.TomlConfig.<init>(TomlConfig.java:45)
        at org.openqa.selenium.grid.config.TomlConfig.from(TomlConfig.java:55)
        at org.openqa.selenium.grid.config.Configs.from(Configs.java:40)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
        at java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at org.openqa.selenium.grid.config.ConfigFlags.readConfigFiles(ConfigFlags.java:72)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:105)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
````

## Expected behavior

The program should not throw and the log file parameter should work correctly.

## Environment

OS: Windows 10
Selenium Grid version (if applicable): 4.0.0-beta4

**Comment by pujagani** [comment]
Thank you for providing the details. I have attempted to reproduce the issue and the issue persists when the string is not in quotes. Adding the quotes did the trick. I am using MacOS and the working toml file is as follows:

```
[server]
port = 4449

[node]
detect-drivers = true
max-sessions = 1

[logging]
log-file = "/path/Logs/hub.log"
```

Please try it out on your end and let me know if it works. If it does not, then I can triage further. Thank you!

**Comment by ccarmannt** [comment]
I put the string in quotes as suggested and got this error:

````
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: io.ous.jtoml.ParseException: Unexpected Exception at 21:14
        at io.ous.jtoml.impl.Tokenizer.error(Tokenizer.java:157)
        at io.ous.jtoml.impl.Tokenizer.next(Tokenizer.java:128)
        at io.ous.jtoml.impl.Parser.readValue(Parser.java:139)
        at io.ous.jtoml.impl.Parser.onAssignment(Parser.java:78)
        at io.ous.jtoml.impl.Parser.parse(Parser.java:48)
        at io.ous.jtoml.JToml.parse(JToml.java:35)
        at org.openqa.selenium.grid.config.TomlConfig.<init>(TomlConfig.java:45)
        at org.openqa.selenium.grid.config.TomlConfig.from(TomlConfig.java:55)
        at org.openqa.selenium.grid.config.Configs.from(Configs.java:40)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
        at java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at org.openqa.selenium.grid.config.ConfigFlags.readConfigFiles(ConfigFlags.java:72)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:105)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
        ... 6 more
Caused by: io.ous.jtoml.ParseException: Unexpected Exception at 21:14
        at io.ous.jtoml.impl.Tokenizer.error(Tokenizer.java:157)
        at io.ous.jtoml.impl.Tokenizer.next(Tokenizer.java:128)
        at io.ous.jtoml.impl.Tokenizer.next(Tokenizer.java:121)
        ... 25 more
Caused by: io.ous.jtoml.ParseException: Reserved escaped character 'R' at 21:14
        at io.ous.jtoml.impl.Tokenizer.error(Tokenizer.java:154)
        at io.ous.jtoml.impl.Tokenizer.unescapeCharacter(Tokenizer.java:278)
        at io.ous.jtoml.impl.Tokenizer.parseBasicString(Tokenizer.java:240)
        at io.ous.jtoml.impl.Tokenizer.tryParseNext(Tokenizer.java:393)
        at io.ous.jtoml.impl.Tokenizer.next(Tokenizer.java:116)
        ... 26 more
````

I then noticed you're using the wrong file system in your example.  If I switch to forward-slashes in the path, it does work.
But it should work with a windows path string.

**Comment by pujagani** [comment]
Thank you for providing the update. As I mentioned earlier I was using MacOS and hence the respective file system. To solve the issue, I have tried running the following config on a Windows machine. I see the log file getting populated as expected.
```
[server]
port = 4449

[node]
detect-drivers = true
max-sessions = 1

[logging]
log-file = 'C:\path\to\selenium.log'
```
Selenium code base uses a Toml parser. The problem was not with the underlying code since the parser follows the Toml spec. I was able to figure out the problem thanks to https://toml.io/en/. 
I recommend trying the single quotes while passing the file path. Please let me know if that solves the problem. Thank you!

**Comment by ccarmannt** [comment]
If that toml.io link says anything about this problem, I can't find it.

But using single quotes is working.

**Comment by pujagani** [comment]
The toml link was just for pointing to documentation that might help.

**Comment by pujagani** [comment]
Added file path examples via https://github.com/SeleniumHQ/selenium/commit/fec3399b79e7c77a2999fbd45759f2b1884c62b6. Also added necessary links via https://github.com/SeleniumHQ/selenium/commit/89b6c9a67397ad8e022090e98b3b00b065d8c5f1.
