### ISSUE TITLE
Grid 4: RemoteWebDriver fails to generate new session

### ISSUE THREAD

**Issue by ccarmannt** [SeleniumHQ/selenium#9724]
## 🐛 Bug Report

When the RemoteWebDriver is instantiated, no new session is generated, apparently due to the fact that the session request sent by the class includes an "Expect" header.

If I send a curl request that omits this "Expect" header, the new session is created/queued as expected.

## To Reproduce

Send a request with this content. Curl command below.

````
POST http://server:4444/session HTTP/1.1
Accept: application/json; charset=utf-8
User-Agent: selenium/4.0.0 (.net windows)
Content-Type: application/json; charset=utf-8
Host: server:4444
Content-Length: 160
Expect: 100-continue
Connection: Keep-Alive

{"capabilities":{"firstMatch":[{"browserName":"internet explorer","platformName":"WINDOWS","se:ieOptions":{"nativeEvents":true,"enablePersistentHover":true}}]}}
````

Curl command: 

````
curl -X POST -d @in.json -H "Accept: application/json; charset=utf-8" -H "User-Agent: selenium/4.0.0 (.net windows)" -H "Content-Type: application/json; charset=utf-8" -H "Expect: 100-continue" http://server:4444/session
````

## Expected behavior

New session creation should be successful.

## Environment

OS: Windows 10
Language Bindings version: C# (dotnet) 
Selenium Grid version (if applicable): 4.0.0-beta4

**Comment by diemol** [comment]
Why do you need to add the `Expect` header? I think we are not handling it. Also, can you reproduce this using the language bindings?

Do you see erros in the server log?

**Comment by ccarmannt** [comment]
To clarify, I'm not ADDING the `Expect` header, and it's not needed.
It's being added as far as I can tell by the RemoteWebDriver without any action from our code.
This was done using the C# language binding.

I don't see errors in the log. However, this section of the log appears to show the request coming in and being dropped:

````
13:52:58.554 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /session HTTP/1.1
Accept: application/json; charset=utf-8
User-Agent: selenium/4.0.0 (.net windows)
Content-Type: application/json; charset=utf-8
Host: localhost:4444
Expect: 100-continue
Connection: Keep-Alive
content-length: 160
13:52:58.554 DEBUG [RequestConverter.channelRead0] - Start of http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /session HTTP/1.1
Accept: application/json; charset=utf-8
User-Agent: selenium/4.0.0 (.net windows)
Content-Type: application/json; charset=utf-8
Host: localhost:4444
Expect: 100-continue
Connection: Keep-Alive
content-length: 160
13:52:58.937 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 160, cap: 160/160, unwrapped: PooledUnsafeDirectByteBuf(ridx: 160, widx: 160, cap: 2048)), decoderResult: success)
13:52:58.937 DEBUG [RequestConverter.channelRead0] - Closing input pipe.
````

**Comment by diemol** [comment]
Can you please provide a C# solution so I can try to reproduce the issue?

**Comment by ccarmannt** [comment]
I will, though it seems like 1 of these 2 problems is reproducible just using the curl command.

**Comment by ccarmannt** [comment]
attached a c# console app. This produces the same problem as outlined above, with this stacktrace:

````
ERROR: The HTTP request to the remote WebDriver server for URL http://localhost:4444/session timed out after 60 seconds.
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at app9724.Program.Main(String[] args) in C:\source\webdriver9724\app9724\Program.cs:line 24
````


[app9724.zip](https://github.com/SeleniumHQ/selenium/files/6947559/app9724.zip)

**Comment by ccarmannt** [comment]
This problem is no longer occurring with the latest version of Selenium Grid, as evidenced by #10228.
