### ISSUE TITLE
Grid4-beta4:  An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. java.lang.IllegalArgumentException: invalid hex byte 'or' at index 1 of '%org/jboss/version.properties'

### ISSUE THREAD

**Issue by sushant0201** [SeleniumHQ/selenium#9747]
## 🐛 Bug Report

I have a Selenium-Hub running on Linux Host and I have some nodes running on Windows 10 VM which are registered to the Selenium-Hub. The Selenium-Hub and the nodes are running 24/7. I am running into an issue where the Selenium-Hub goes into an unresponsive mode after a while and throws the following exception in the Selenium-Hub log file:

`
22:09:34.509 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
22:09:34.528 INFO [LoggingOptions.getTracer] - Using null tracer
22:09:34.586 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://xxxxxxxxxx:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://xxxxxxxxxx:4443]
22:09:34.765 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://xxxxxxxxxx:4442 and tcp://xxxxxxxxxx:4443
22:09:34.812 INFO [UnboundZmqEventBus.<init>] - Sockets created
22:09:35.814 INFO [UnboundZmqEventBus.<init>] - Event bus ready
22:09:36.891 INFO [Hub.execute] - Started Selenium Hub 4.0.0-beta-4 (revision 29f46d02dd): http://xxxxxxxxxx:4444
22:09:37.991 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
22:09:38.411 INFO [LocalDistributor.add] - Added node 26767121-c0e2-40cb-83b9-22029bac5529 at http://xxxxxxxxxx:5555.
22:09:38.527 INFO [GridModel.setAvailability] - Switching node 26767121-c0e2-40cb-83b9-22029bac5529 (uri: http://xxxxxxxxxx:5555) from DOWN to UP
22:09:49.163 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
22:09:49.168 INFO [LocalDistributor.add] - Added node 5d893626-457c-4b2c-993b-383217c6ed90 at http://xxxxxxxxxx:5555.
22:09:49.206 INFO [GridModel.setAvailability] - Switching node 5d893626-457c-4b2c-993b-383217c6ed90 (uri: 

> http://xxxxxxxxxx:5555) from DOWN to UP

22:49:52.840 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: unterminated escape sequence at index 0 of: %.
        at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:371)
        at io.netty.handler.codec.http.QueryStringDecoder.path(QueryStringDecoder.java:189)
        at org.openqa.selenium.netty.server.RequestConverter.createRequest(RequestConverter.java:145)
        at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:82)
        at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:51)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.handleHttpRequest(WebSocketUpgradeHandler.java:105)
        at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.channelRead(WebSocketUpgradeHandler.java:75)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
`

As a short-term fix, I am currently restarting the selenium-service on the Linux host whenever I see that exception getting printed out to the log-file.

Any suggestions on how can I add a long term fix to this or why I am seeing this exception would be really helpful!

## Environment

Node running on OS: Windows 10
Selenium-Hub running on OS: Linux RHEL 8.4  
Selenium Grid version: 4.0.0-beta-4

**Comment by diemol** [comment]
Tons of fixes have been implemented after Beta 4, which you can grab in our most recent prerelease [here](https://github.com/SeleniumHQ/docker-selenium/releases/download/4.0.0-rc-1-prerelease-20210823/selenium-server-4.0.0-prerelease-rc-1-ea41b757bd.jar). That error you post looks like one that got fixed weeks ago.

We expect to do a new release in 1-2 weeks.  

If you are still experiencing issues after using the prerelease jar, please open a new issue and fill out all the template fields (without removing any of them).
