### ISSUE TITLE
Selenium Java fails to find a CDP implementation after compilation

### ISSUE THREAD

**Issue by w568w** [SeleniumHQ/selenium#9820]
## 🐛 Bug Report

Selenium works fine with Edge in the IDE environment, but becomes unable to find a CDP implementation after compilation.

Output log:
```
MSEdgeDriver was started successfully.
Detected dialect: W3C
Unable to find an exact match for CDP version 93, so returning the closest version found: a no-op implementation
Unable to find CDP implementation matching 93.
Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.0.0-rc-1` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
org.openqa.selenium.devtools.DevToolsException: You are using a no-op implementation of the CDP. The most likely reason for this is that Selenium was unable to find an implementation of the CDP protocol that matches your browser. Please be sure to include an implementation on the classpath, possibly by adding a new (maven) dependency of `org.seleniumhq.selenium:selenium-devtools-vNN:4.0.0-rc-1` where `NN` matches the major version of the browser you're using.
Build info: version: '4.0.0-rc-1', revision: 'bc5511cbda'
System info: host: 'LAPTOP-XXXXXX', ip: '192.168.XX.XX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
Driver info: DevTools Connection
        at org.openqa.selenium.devtools.noop.NoOpDomains.target(NoOpDomains.java:59)
        at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:91)
```

## To Reproduce

Detailed steps to reproduce the behavior:

1. Install the latest version of Edge stable (93.0.961.47) and add the corresponding edge driver to `PATH`.
2. Initialize Selenium with the following codes:
```java
        var driver = new EdgeDriver();
        var chromeDevTools = driver.getDevTools();
        chromeDevTools.createSession();
        chromeDevTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
```
3. Run it in the IDE environment, such as IDEA, Eclipse, etc. It works normally.
4. Build artifact JAR file and execute the jar with `java -jar NAME_OF_JAR.jar`.
5. It outputs the error above.
## Expected behavior

It should work normally and output `Found exact CDP implementation for version 93` in the console.

## Test script or set of commands reproducing this issue

pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>Example</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.0.0-rc-1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.32</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-devtools-v93</artifactId>
            <version>4.0.0-rc-1</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>
```

TestBrowser.java
```java
public class TestBrowser {
    EdgeDriver driver;
    DevTools chromeDevTools;

    public TestBrowser() {
        var options = new EdgeOptions();
        driver = new EdgeDriver(options);
        chromeDevTools = driver.getDevTools();
        chromeDevTools.createSession();
        chromeDevTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
    }
}
```
## Environment

OS: Windows 11
Browser: Edge
Browser version: 93.0.961.47
Browser Driver version:  Edge Driver 93.0.961.44
Language Bindings version: Java 4.0.0-rc-1
Selenium Grid version (if applicable):

**Comment by diemol** [comment]
This is because you have the dependencies working in your IDE, but when you generate a jar with your code those dependencies are not present. You need to either make them available via the classpath or build a [fat jar](http://tutorials.jenkov.com/maven/maven-build-fat-jar.html),
