### ISSUE TITLE
Selenium standalone (grid) hangs from time to time (4.0 beta or rc1)

### ISSUE THREAD

**Issue by StanislavKharchenko** [SeleniumHQ/selenium#9822]
## Last working Selenium version

Worked up to version: 3.141.59 (selenium standalone)
Stopped working in version: 4.0 (beta, rc1)

Steps to reproduce:
1. Start selenium standalone:
`java -Dwebdriver.chrome.driver=chromedriver.exe -Dwebdriver.edge.driver=msedgedriver.exe -jar selenium-server-4.0.0-rc-1.jar standalone --port 4444 --max-sessions 8 --override-max-sessions true --log ./server.log --session-timeout 3600`
2. Run several tests in parallel; execution status will be ok;
3. Don't stop/restart selenium standalone process;
4. In the next days try to run tests again

Expected: the behavior is the same as in step#2
Actual: some times (not always in the next day after grid starting, could be in 2-3-4 days) webdriver can't establish connection to selenium.
If I open selenium console in browser by link http://<selenium-host>:4444 
then it trying to display sessions, but can't load.

The output logs are following:

```
09:38:06.467 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "1b8f54a543ea9542950248f1deb040cb","eventTime": 1631601486466429800,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: 3686a38bf7fed013fee68a9554aaa8f6\nBuild info: version: '4.0.0-rc-1', revision: 'bc5511cbda'\nSystem info: host: 'PC-GENAT01', ip: '10.98.74.219', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_291'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 3686a38bf7fed013fee68a9554aaa8f6\nBuild info: version: '4.0.0-rc-1', revision: 'bc5511cbda'\nSystem info: host: 'PC-GENAT01', ip: '10.98.74.219', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_291'\nDriver info: driver.version: unknown\r\n\tat 
org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:129)\r\n\tat 
org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$3(HandleSession.java:136)\r\n\tat 
io.opentelemetry.context.Context.lambda$wrap$2(Context.java:219)\r\n\tat 
org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:110)\r\n\tat 
org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\r\n\tat 
org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat 
org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n\tat 
org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat 
org.openqa.selenium.grid.router.Router.execute(Router.java:91)\r\n\tat 
org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)\r\n\tat 
org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)\r\n\tat 
org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n\tat 
org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n\tat 
org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat 
org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)\r\n\tat 
org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat 
org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n\tat 
org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat 
org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n\tat 
org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat 
org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\r\n\tat 
org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n\tat 
org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n\tat 
org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n\tat 
org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n\tat 
org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\r\n\tat 
java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\r\n\tat java.util.concurrent.FutureTask.run(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat 
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "pc-genat01:4444","http.method": "GET","http.request_content_length": "0","http.scheme": "HTTP","http.target": "\u002fsession\u002f3686a38bf7fed013fee68a9554aaa8f6\u002fscreenshot","http.user_agent": "selenium\u002f4.0.0-beta.4 (js windows)","session.id": "3686a38bf7fed013fee68a9554aaa8f6"}}
```

It repeats each time when webdriver trying to connect to selenium.
Restart of selenium-stanndalone process help, but also not always and could work from 1, 2,...n attempts of restart.

## Environment

OS: Windows 10
Browser: Chrome, Edge
Browser version: 93 (reproduced also previously in 90, 91, 92)
Browser Driver version: 93 (reproduced also previously in 90, 91, 92)
Language Bindings version: Javascript
Selenium Grid version (if applicable): 4.0 rc1

**Comment by pujagani** [comment]
Thank you for providing the details. I have a few questions regarding the issue described. 
1. When the Grid hangs, does it have any nodes that are registered? Can you check by pinging /status endpoint? 
2. ```If I open selenium console in browser by link http://:4444 then it trying to display sessions, but can't load.``` Does that mean the Grid UI cannot load at all? or the only the sessions tab does not load? 
3. Does the Grid UI and sessions tab load otherwise properly when running the sessions in parallel? 
3. Does it only happen in the Standalone mode? Or have you observed it in Hub-Node or fully distributed mode as well? 
4. The stack trace shared seems like a deleted session is being requested. Are the sessions long-running? Can you please provide the client-side reproducible code snippet? 

The more details we have, the easier it is for us to debug the issue and pinpoint the problem. Appreciate your time and effort. Thank you!

**Comment by StanislavKharchenko** [comment]
@pujagani Thanks for your response!
The web UI loaded partially. It trying to load data on both tabs, smth like progress bar displayed during load data, but nothing loaded as result.
Firstly we faced with this issue after upgrade to selenium 4 beta-2 from selenium 3.141. All this time it was actual. We thought that this is known defect (since beta) and were using scheduled restart of grid. But now I see that selenium got "RC" state and issue still actual.

**Comment by diemol** [comment]
@StanislavKharchenko do you have more insights based on the other questions?

- Does the Grid UI and sessions tab load otherwise properly when running the sessions in parallel?
- Does it only happen in the Standalone mode? Or have you observed it in Hub-Node or fully distributed mode as well?
- The stack trace shared seems like a deleted session is being requested. Are the sessions long-running? Can you please provide the client-side reproducible code snippet?

It would be very helpful to see the whole Grid log, so we understand when the issue starts to happen. 

Please also notice that you are using the flag to override the max number of recommended sessions (`--override-max-sessions true`), which could be affecting the stability of the VM where the Grid is running.

**Comment by StanislavKharchenko** [comment]
@diemol 
1. Both Grid UI and sessions tab are fully loaded data during run when webdriver successfully connected to selenium; the issue with web console only after N attempts when webdriver can't connect;
2. I don't checked with hub mode, but I can say that the similar issue was if run selenium under docker too;
3. We have scenarios where test cases could run a long time, but, the sessions should be deleted after test case finished. Maybe here it could be some hangs zombie processes, which are not stopped and can't be stopped first time after selenium standalone restart. From the client side this just hangs during bulding new webdriver, so nothing specific.

I've found that webdriver can't connect to selenium and trying to restart selenium process.
After first restart - issue the same and what I have in logs:

```
09:37:34.238 INFO [LogManager$RootLogger.log] - Using the system default encoding
09:37:34.242 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
09:37:35.923 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
09:37:35.925 WARN [NodeOptions.getSessionFactories] - Overriding max recommended number of 8 concurrent sessions. Session stability and reliability might suffer!
09:37:35.925 WARN [NodeOptions.getSessionFactories] - One browser session is recommended per available processor. Safari is always limited to 1 session per host.
09:37:35.925 WARN [NodeOptions.getSessionFactories] - Overriding this value for Internet Explorer is not recommended. Issues related to parallel testing with Internet Explored won't be accepted.
09:37:35.925 WARN [NodeOptions.getSessionFactories] - Double check if enabling 'override-max-sessions' is really needed
09:37:35.976 INFO [NodeOptions.discoverDrivers] - Discovered 2 driver(s)
09:37:36.006 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge"} 8 times
09:37:36.007 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 8 times
09:37:36.228 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
09:37:36.261 INFO [LocalDistributor.add] - Added node 56b42233-6cdf-4306-9353-d8c3e4412164 at http://10.98.74.219:4444. Health check every 120s
09:37:36.262 INFO [GridModel.setAvailability] - Switching node 56b42233-6cdf-4306-9353-d8c3e4412164 (uri: http://10.98.74.219:4444) from DOWN to UP
09:37:36.893 INFO [Standalone.execute] - Started Selenium Standalone 4.0.0-rc-1 (revision bc5511cbda): http://10.98.74.219:4444
09:37:37.508 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "ca91a2b82fdf8eac7150b6909c7db864","eventTime": 1631601457499497500,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: 460edcaa7051f4f0887a882f9815f2f8\nBuild info: version: '4.0.0-rc-1', revision: 'bc5511cbda'\nSystem info: host: 'PC-GENAT01', ip: '10.98.74.219', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_291'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 460edcaa7051f4f0887a882f9815f2f8\nBuild info: version: '4.0.0-rc-1', revision: 'bc5511cbda'\nSystem info: host: 'PC-GENAT01', ip: '10.98.74.219', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_291'\nDriver info: driver.version: unknown\r\n\tat org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:129)\r\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$3(HandleSession.java:136)\r\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:219)\r\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:110)\r\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\r\n\tat org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)\r\n\tat org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)\r\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\r\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\r\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\r\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\r\n\tat java.util.concurrent.FutureTask.run(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "pc-genat01:4444","http.method": "POST","http.request_content_length": "4985","http.scheme": "HTTP","http.target": "\u002fsession\u002f460edcaa7051f4f0887a882f9815f2f8\u002fexecute\u002fasync","http.user_agent": "selenium\u002f4.0.0-beta.4 (js windows)","session.id": "460edcaa7051f4f0887a882f9815f2f8"}}
```

Below this logs repeat the similar parts several times with info like:
`09:37:37.508 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "ca91a2b82fdf8eac7150b6909c7db864","eventTime": 1631601457499497500,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: `

Maybe it is possible to turn on some detailed logs/traces?

**Comment by diemol** [comment]
This seems hard to troubleshoot from our side because the details and steps to reproduce are very ambiguos. One thing that I keep seeing in your comments is `Unable to execute request for an existing session: Unable to find session with ID:`, which means that you are trying to quey a session that already stopped. 

In the end, what we can do to help is just to give you hints on what to check (like monitor CPU and RAM, running processes to identify what is going on when the situation happens). 

If have had Grids running overnight and I have not bumped into this issue. We would be happy to troubleshoot if you give us a step by step guide how to reproduce it, including the tests needed to create the same situation you are having on your end.

**Comment by StanislavKharchenko** [comment]
I will try to set ALL level logs and check if some additional info will be there.
Unfortunately this reproduced not often but could be sporadically, 1-2 per week or even less often.

**Comment by diemol** [comment]
OK, if you find a way to reproduce the issue for us to have a look, I'll be happy to reopen the issue. Please let us know when you have more information on how to reproduce this, thanks!

**Comment by StanislavKharchenko** [comment]
Here is what I see today:
```

08:25:03.389 INFO [LocalDistributor.newSession] - Session request received by the distributor: 
 [Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [], prefs: {download: {default_directory: D:\teamcity\Lab Results Ent..., directory_upgrade: true, promt_for_download: false}, plugins.always_open_pdf_externally: true}}}, Capabilities {acceptInsecureCerts: true, browserName: chrome, count: 1, enableVNC: true, enableVideo: false, goog:chromeOptions: {args: [], prefs: {download: {default_directory: D:\teamcity\Lab Results Ent..., directory_upgrade: true, promt_for_download: false}, plugins.always_open_pdf_externally: true}}, timeZone: Europe/Kiev}]
08:25:04.452 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
08:25:04.454 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: c387700b5586410a693b76f6ca206061, Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 93.0.4577.82, chrome: {chromedriverVersion: 93.0.4577.63 (ff5c0da2ec0ad..., userDataDir: C:\Users\skha\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:53903}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://10.98.74.219:4444/sess..., se:cdpVersion: 93.0.4577.82, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
08:36:52.975 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: invalid hex byte 'uf' at index 2 of '/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/windows/win.ini'
	at io.netty.util.internal.StringUtil.decodeHexByte(StringUtil.java:256)
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:373)
	at io.netty.handler.codec.http.QueryStringDecoder.path(QueryStringDecoder.java:189)
	at org.openqa.selenium.netty.server.RequestConverter.createRequest(RequestConverter.java:145)
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:82)
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:51)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.handleHttpRequest(WebSocketUpgradeHandler.java:126)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.channelRead(WebSocketUpgradeHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
08:36:57.983 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: invalid hex byte 'uf' at index 2 of '/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/%uff0e%uff0e/winnt/win.ini'
	at io.netty.util.internal.StringUtil.decodeHexByte(StringUtil.java:256)
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:373)
	at io.netty.handler.codec.http.QueryStringDecoder.path(QueryStringDecoder.java:189)
	at org.openqa.selenium.netty.server.RequestConverter.createRequest(RequestConverter.java:145)
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:82)
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:51)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.handleHttpRequest(WebSocketUpgradeHandler.java:126)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.channelRead(WebSocketUpgradeHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
```

@diemol Maybe this can help to understand a root cause.

**Comment by diemol** [comment]
Well, it means that an event was not properly processed, but without any context or a way for us to bump into the same warning and behaviour, I cannot say more. Sorry.

**Comment by StanislavKharchenko** [comment]
@diemol I've found some regularity when such issue could occur. It seems if by some reasons webdriver session wasn't quit properly (driver.quit() wasn't called) and process exited with code 1 - then the next time selenium web console and grid will hang and new webdriver session couldn't started as well. 
I still can't find any useful info in logs. 
But, as far as I understand, if process of webdriver was killed by some unexpected reasons then selenium grid should close it by timeout as well?
