### ISSUE TITLE
[py] BiDi APIs for python That's too bad

### ISSUE THREAD

**Issue by defnngj** [SeleniumHQ/selenium#9911]
https://www.selenium.dev/documentation/webdriver/bidi_apis/

* Register Basic Auth

Python(selenium) has no `driver.register()`  --- this is bug?

* Mutation Observation

```py 
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait

driver = webdriver.Chrome()
async with driver.log.mutation_events() as event:
    pages.load("dynamic.html")
    driver.find_element(By.ID, "reveal").click()
    WebDriverWait(driver, 5)\
        .until(EC.visibility_of(driver.find_element(By.ID, "revealed")))

assert event["attribute_name"] == "style"
assert event["current_value"] == ""
assert event["old_value"] == "display:none;"

```
1. Python(selenium) has no `dirver.log`
2. How is `pages` defined? 

Who can tell me how to use it:

```py
import asyncio
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.log import Log
from selenium.webdriver.support import expected_conditions as EC


async def demo():
    driver = webdriver.Chrome()
    session = driver.bidi_connection()
    log = Log(driver, session)

    async with log.mutation_events() as event:
        driver.get("https://www.google.com")
        driver.find_element(By.ID, "reveal").click()
        WebDriverWait(driver, 5)\
            .until(EC.visibility_of(driver.find_element(By.ID, "revealed")))

    assert event["attribute_name"] == "style"
    assert event["current_value"] == ""
    assert event["old_value"] == "display:none;"

asyncio.run(demo())
```

error:

```shell
Traceback (most recent call last):
  File "D:/github/test-circle/selenium4/code/demo.py", line 25, in <module>
    asyncio.run(demo())
  File "C:\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:/github/test-circle/selenium4/code/demo.py", line 12, in demo
    log = Log(driver, session)
  File "C:\Python38\lib\site-packages\selenium\webdriver\common\log.py", line 48, in __init__
    self.session = bidi_session.session
AttributeError: '_AsyncGeneratorContextManager' object has no attribute 'session'
```

Must asyncio be used？ Why provide asyncio examples, and incomplete？

**Comment by ghost** [comment]
👋 Hi there! Thank you for creating this issue.

I am the Selenium Assistant Bot 🤖, I triage issues in this repository. If I can't do it, I label it to help maintainers identify issues that need triaging.

I am an Open Source project 🙌, post bugs or ideas [here](https://github.com/SeleniumHQ/selenium-assistant)!
