### ISSUE TITLE
[🐛 Bug]: [Ruby][4.0.0] driver.on_log_event throws exception

### ISSUE THREAD

**Issue by shashikdm** [SeleniumHQ/selenium#9935]
### What happened?

A runtime exception is thrown in ruby when using the method `driver.on_log_event`.
I am trying out the cdp examples in [documentation](https://www.selenium.dev/documentation/webdriver/bidi_apis/#listen-to-consolelog-events) in ruby. So I installed selenium-webdriver gem using `gem install selenium-webdriver`. This installed the latest stable `4.0.0`. Then I added `chromedriver` binary in my path, and ran following code snippet:
```
require 'selenium-webdriver'

def run_session
  driver = Selenium::WebDriver.for :chrome
  driver.get 'http://www.google.com'
  logs = []
  driver.on_log_event(:console) do |event|
    logs.push(event)
    puts logs.length
  end

  driver.execute_script('console.log("here")')
  driver.quit
end

run_session
```
That resulted in the following exception:
```
Traceback (most recent call last):
        5: from cdp_commands.rb:16:in `<main>'
        4: from cdp_commands.rb:7:in `run_session'
        3: from /Users/shashikantkadam/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-4.0.0/lib/selenium/webdriver/common/driver_extensions/has_log_events.rb:66:in `on_log_event'
        2: from /Users/shashikantkadam/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-4.0.0/lib/selenium/webdriver/common/driver_extensions/has_devtools.rb:33:in `devtools'
        1: from /Users/shashikantkadam/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/shashikantkadam/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- selenium/devtools (LoadError)
```

### How can we reproduce the issue?

```shell
require 'selenium-webdriver'

def run_session
  driver = Selenium::WebDriver.for :chrome
  driver.get 'http://www.google.com'
  logs = []
  driver.on_log_event(:console) do |event|
    logs.push(event)
    puts logs.length
  end

  driver.execute_script('console.log("here")')
  driver.quit
end

run_session
```

### Relevant log output

```shell
Traceback (most recent call last):
        5: from cdp_commands.rb:16:in `<main>'
        4: from cdp_commands.rb:7:in `run_session'
        3: from /Users/shashikantkadam/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-4.0.0/lib/selenium/webdriver/common/driver_extensions/has_log_events.rb:66:in `on_log_event'
        2: from /Users/shashikantkadam/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-4.0.0/lib/selenium/webdriver/common/driver_extensions/has_devtools.rb:33:in `devtools'
        1: from /Users/shashikantkadam/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/shashikantkadam/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- selenium/devtools (LoadError)
```

### Operating System

macOS Big Sur

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 94

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.61

### Are you using Selenium Grid?

No

**Comment by shashikdm** [comment]
Sorry, after looking into the code, I realized I only need to install another gem, `gem install selenium-devtools`. That fixed the issue
