### ISSUE TITLE
[🐛 Bug]: IEDriver crashed when call API FindElementByXPath

### ISSUE THREAD

**Issue by guangyuexu** [SeleniumHQ/selenium#9938]
### What happened?

Build IEDriver from trunk branch. IEDriver crashed when call API FindElementByXPath.
The test was made with IEDriver and Edge in IEMode. The crash also happens when test with IEDriver and IE. 

### How can we reproduce the issue?

```shell
using System;
using OpenQA.Selenium;
using OpenQA.Selenium.IE;

namespace Selenium_Web
{
    class Program
    {
        IWebDriver reqDriver = null;
        static void Main(string[] args)
        {
            //change the path accordingly
            var dir = @"C:\dev\selenium\build\cpp\x64\Debug"; 
            var driverexe = "IEDriverServer.exe";

            var ieService = InternetExplorerDriverService.CreateDefaultService(dir, driverexe);
            var ieOptions = new InternetExplorerOptions { IgnoreZoomLevel = true };
            ieOptions.PageLoadStrategy = PageLoadStrategy.Eager;
            ieOptions.AddAdditionalCapability("ie.edgechromium", true);  // comment this line when test with IE
            //change the path accordingly
            ieOptions.AddAdditionalCapability("ie.edgepath", "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"); // comment this line when test with IE
            
            InternetExplorerDriver reqDriver = new InternetExplorerDriver(ieService, ieOptions);
            reqDriver.Url = "https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_opener";
            
            reqDriver.FindElementByXPath("//button[text()='Run ❯']").Click();

            Console.WriteLine("Done");
            Console.ReadLine();
        }
    }
}
```

### Relevant log output

```shell
Started InternetExplorerDriver server (64-bit)
3.150.2.0
Listening on port 58616
Only local connections are allowed
Unhandled exception. OpenQA.Selenium.NoSuchElementException: Unable to find element with xpath == //button[text()='Run ?']
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at Selenium_Web.Program.Main(String[] args) in C:\dev\IEDriver test\BrowserAutomation\IEDriverSelenium\Program - Copy.cs:line 26
```

### Operating System

Windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Edge 94

### What are the browser driver(s) and version(s) where you see this issue?

IEDriver 3.150.2.0

**Comment by jimevans** [comment]
Should be fixed in 1ca3c06. Thank you for the report and contribution!
