### ISSUE TITLE
[🐛 Bug]: JSON parsing error when creating capabilities

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#9954]
### What happened?

When starting a session on Sauce Labs, if a user does not have sufficient VMs for their account, Sauce Labs will reply with a redirect message and (I believe) an empty payload. @shs96c I know you fixed something like this and I thought it was addressed in the RC, but the stack trace below is showing 4.0.0. Does a Redirect response need separate processing? It seems like it shouldn't be necessary to parse the payload at all for a redirect.

### How can we reproduce the issue?

```shell
It would be difficult to reproduce this without a Sauce account and running more in parallel than sessions available, but should be able to mock out a response in a unit test?
```

### Relevant log output

```shell
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: 
	at org.openqa.selenium.json.Json.toType(Json.java:57)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:109)
	... 28 more
Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'EC2AMAZ-DQI8KAO', ip: '10.204.197.75', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:307)
	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:229)
	at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
	at org.openqa.selenium.json.Json.toType(Json.java:71)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	... 30 more

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: 
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:112)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
```

### Operating System

n/a

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/java-client/issues/1608

Basically, what needs to be done is to enable `followRedirects` option for the default HTTP client.

**Comment by mykola-mokhnach** [comment]
cc @diemol

**Comment by diemol** [comment]
Fixed via https://github.com/SeleniumHQ/selenium/commit/9d9e4c7185cd44aafb18e707a34bcfc851fa9a31, thanks for the hint @mykola-mokhnach 

We will do a release in a couple of days.

**Comment by mykola-mokhnach** [comment]
Thanks @diemol for such a swift turnaround on that
