### ISSUE TITLE
[🐛 Bug]: I use ChromeDriver to getScreenshot, but it gets stuck after running for a while

### ISSUE THREAD

**Issue by changfeng2021** [SeleniumHQ/selenium#9962]
### What happened?

I use ChromeDriver to getScreenshot, but it gets stuck after running for a while. I need to use tasks to loop screenshots. There is no problem at the beginning, but it will get stuck later

### How can we reproduce the issue?

```shell
    public void takeScreenshot(Input input) {
        driver.get(input.processLink());

        TimeUnit.SECONDS.sleep(1);

        File file = driver.getScreenshotAs(OutputType.FILE);
        String path = StrUtil.format("{}/{}", DirectoryUtil.home(), V2raySEConst.SHARE_PNG);
        log.info("path = {}", path);
        FileUtil.copy(file, new File (path), true);
        FileUtil.del(file);
//        driver.close();
    }
```

### Relevant log output

```shell
System info: host: 'iZj6c2e1aik19scpt0a22tZ', ip: '172.31.216.142', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-86-generic', java.version: '11.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 94.0.4606.81, chrome: {chromedriverVersion: 94.0.4606.81 (5a03c5f103317..., userDataDir: /tmp/.org.chromium.Chromium...}, goog:chromeOptions: {debuggerAddress: localhost:43241}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 2b5ddc486f7b4935c74e111686d4f0b4
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187) ~[selenium-remote-driver-3.141.59.jar!/:na]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122) ~[selenium-remote-driver-3.141.59.jar!/:na]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49) ~[selenium-remote-driver-3.141.59.jar!/:na]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158) ~[selenium-remote-driver-3.141.59.jar!/:na]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[selenium-remote-driver-3.141.59.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[selenium-remote-driver-3.141.59.jar!/:na]
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277) ~[selenium-remote-driver-3.141.59.jar!/:na]
	at com.v2rayse.share.utils.HtmlUtil.takeScreenshot(HtmlUtil.java:37) ~[classes!/:na]
	at com.v2rayse.share.utils.ShareUtil.share(ShareUtil.java:19) ~[classes!/:na]
	at com.v2rayse.share.task.ShareTask.updateShareCode(ShareTask.java:31) ~[classes!/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.10.jar!/:5.3.10]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.10.jar!/:5.3.10]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.10.jar!/:5.3.10]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

### Operating System

ubuntu 20.04

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 94.0.4606.81

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.81

**Comment by changfeng2021** [comment]
When I execute close, the process does not exit
```log
  501  4214  4210   0 12:18下午 ??         0:00.04 chromedriver --port=9831
  501  4238  4210   0 12:18下午 ??         0:00.05 chromedriver --port=45854
```
