### ISSUE TITLE
[🐛 Bug]: RemoteWebDriver.builder()  Unable to establish websocket connection

### ISSUE THREAD

**Issue by gog27771** [SeleniumHQ/selenium#9976]
### What happened?

I have upgraded to Selenium 4 but i am unable to establish a connection to my website using the code 
```java
WebDriver remoteWebDriver = RemoteWebDriver.builder().oneOf(options).address(new URL(grid)).build();
```

The browser window opens but thats as far as it gets. My original code works fine `RemoteWebDriver  remoteWebDriver = new RemoteWebDriver(new URL(grid), options);` but i want to be able to use DevTools so my driver needs augmenting. I have tried using edge and chrome (latest versions) but i continue to get the same error.

Im using Java 8, Grid 4 Node and Hub and selenium-java version 4.0.0

![Browser window](https://user-images.githubusercontent.com/57394145/138453537-79d27b13-f7ec-4053-bb7f-02a0904d11c1.PNG)

The process seems to fail at this method - 

```java
public WebSocket openSocket(HttpRequest request, Listener listener) {
        Require.nonNull("Request to send", request);
        Require.nonNull("WebSocket listener", listener);
        return **(WebSocket)this.toWebSocket.apply(request, listener);**
    }
```

### How can we reproduce the issue?

```shell
ChromeOptions options =new ChromeOptions();
options.setCapability("platformName","windows");
WebDriver remoteWebDriver = RemoteWebDriver.builder().oneOf(options).address(new URL(grid)).build();
```

### Relevant log output

```shell
STACKTRACE

Oct 22, 2021 1:04:42 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found exact CDP implementation for version 95
Oct 22, 2021 1:04:54 PM org.openqa.selenium.remote.http.netty.NettyWebSocket lambda$new$0
WARNING: Connection refused: no further information: /0.0.0.0:4444
java.net.ConnectException: Connection refused: no further information: /0.0.0.0:4444
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:4444
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Oct 22, 2021 1:04:54 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection refused: no further information: /0.0.0.0:4444
java.net.ConnectException: Connection refused: no further information: /0.0.0.0:4444
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:4444
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

SESSION INFORMATION

Oct 22, 2021 1:18:41 PM org.openqa.selenium.remote.http.DumpHttpExchangeFilter lambda$apply$2
INFO: HTTP Request: (POST) /session
  Cache-Control: no-cache
  Content-Length: 431
  Content-Type: application/json; charset=utf-8

{
  "desiredCapabilities": {
    "browserName": "chrome",
    "platformName": "windows",
    "goog:chromeOptions": {
      "args": [
      ],
      "extensions": [
      ]
    }
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "args": [
          ],
          "extensions": [
          ]
        },
        "platformName": "windows"
      }
    ]
  }
}
Oct 22, 2021 1:18:41 PM org.openqa.selenium.remote.http.DumpHttpExchangeFilter lambda$apply$2
INFO: HTTP Request: (POST) /session
  User-Agent: selenium/4.0.0 (java windows)
  Cache-Control: no-cache
  Content-Length: 431
  Content-Type: application/json; charset=utf-8

{
  "desiredCapabilities": {
    "browserName": "chrome",
    "platformName": "windows",
    "goog:chromeOptions": {
      "args": [
      ],
      "extensions": [
      ]
    }
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "args": [
          ],
          "extensions": [
          ]
        },
        "platformName": "windows"
      }
    ]
  }
}
Oct 22, 2021 1:18:48 PM org.openqa.selenium.remote.http.DumpHttpExchangeFilter lambda$apply$2
INFO: HTTP Response: Status code: 200
  content-length: 1195
  Cache-Control: no-cache
  Content-Type: application/json; charset=utf-8

{
  "value": {
    "sessionId": "fce3322c6495286afaf9d3b3c375066c",
    "capabilities": {
      "acceptInsecureCerts": false,
      "browserName": "chrome",
      "browserVersion": "95.0.4638.54",
      "chrome": {
        "chromedriverVersion": "95.0.4638.17 (a9d0719444d4b035e284ed1fce73bf6ccd789df2-refs\u002fbranch-heads\u002f4638@{#178})",
        "userDataDir": "C:\\Users\\a609923\\AppData\\Local\\Temp\\5\\scoped_dir532_974048133"
      },
      "goog:chromeOptions": {
        "debuggerAddress": "localhost:52905"
      },
      "networkConnectionEnabled": false,
      "pageLoadStrategy": "normal",
      "platformName": "WINDOWS",
      "proxy": {
      },
      "se:cdp": "ws:\u002f\u002f0.0.0.0:4444\u002fsession\u002ffce3322c6495286afaf9d3b3c375066c\u002fse\u002fcdp",
      "se:cdpVersion": "95.0.4638.54",
      "setWindowRect": true,
      "strictFileInteractability": false,
      "timeouts": {
        "implicit": 0,
        "pageLoad": 300000,
        "script": 30000
      },
      "unhandledPromptBehavior": "dismiss and notify",
      "webauthn:extension:credBlob": true,
      "webauthn:extension:largeBlob": true,
      "webauthn:virtualAuthenticators": true
    }
  }
}
Oct 22, 2021 1:18:48 PM org.openqa.selenium.remote.http.DumpHttpExchangeFilter lambda$apply$2
INFO: HTTP Response: Status code: 200
  content-length: 1195
  Cache-Control: no-cache
  Content-Type: application/json; charset=utf-8

{
  "value": {
    "sessionId": "fce3322c6495286afaf9d3b3c375066c",
    "capabilities": {
      "acceptInsecureCerts": false,
      "browserName": "chrome",
      "browserVersion": "95.0.4638.54",
      "chrome": {
        "chromedriverVersion": "95.0.4638.17 (a9d0719444d4b035e284ed1fce73bf6ccd789df2-refs\u002fbranch-heads\u002f4638@{#178})",
        "userDataDir": "C:\\Users\\a609923\\AppData\\Local\\Temp\\5\\scoped_dir532_974048133"
      },
      "goog:chromeOptions": {
        "debuggerAddress": "localhost:52905"
      },
      "networkConnectionEnabled": false,
      "pageLoadStrategy": "normal",
      "platformName": "WINDOWS",
      "proxy": {
      },
      "se:cdp": "ws:\u002f\u002f0.0.0.0:4444\u002fsession\u002ffce3322c6495286afaf9d3b3c375066c\u002fse\u002fcdp",
      "se:cdpVersion": "95.0.4638.54",
      "setWindowRect": true,
      "strictFileInteractability": false,
      "timeouts": {
        "implicit": 0,
        "pageLoad": 300000,
        "script": 30000
      },
      "unhandledPromptBehavior": "dismiss and notify",
      "webauthn:extension:credBlob": true,
      "webauthn:extension:largeBlob": true,
      "webauthn:virtualAuthenticators": true
    }
  }
}
Oct 22, 2021 1:18:49 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found exact CDP implementation for version 95
```

### Operating System

Windows 10 and my Grid is hosted on a VM using Windows Server 2019

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 94 and 95

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 95

### Are you using Selenium Grid?

Grid 4.0.0 Node and Hub

**Comment by diemol** [comment]
Please add a complete reproduction script. Also, can you share the details how the Grid is started and the Grid logs when this error occurs? Are websockets open in the Node machine?

**Comment by gog27771** [comment]
Hi @diemol,
Unfortunately im not allowed to share too much code due to company rules, however my setup is pretty standard and all works fine up until this section

```java
ChromeOptions options =new ChromeOptions();
options.setCapability("platformName","windows");
WebDriver remoteWebDriver = RemoteWebDriver.builder().oneOf(options).address(new URL(grid)).build();
```

**This is how im starting my grid -** 
```bash
java -jar selenium-server-4.0.0.jar hub
```

**This is how im starting my node -** 
```bash
java -Dwebdriver.chrome.driver=C:\GOG\chromedriver\chromedriver.exe -Dwebdriver.gecko.driver=C:\GOG\chromedriver\geckodriver.exe -Dwebdriver.edge.driver=C:\GOG\chromedriver\msedgedriver.exe -jar selenium-server-4.0.0.jar node --detect-drivers true
```

**Everything works fine when i use the standard remotewebdriver -** 
```java
RemoteWebDriver remoteWebDriver = new RemoteWebDriver(new URL(grid), options);
``` 

**But not when i use**  `RemoteWebDriver.builder()`

**This is my grid url -** `http://vc2coma1615188.fmr.com:4444`.

 **The browser opens but fails to connect with following stacktrace -** 

```
WARNING: Connection refused: no further information: /0.0.0.0:4444
java.net.ConnectException: Connection refused: no further information: /0.0.0.0:4444
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:4444
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Oct 23, 2021 5:59:03 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection refused: no further information: /0.0.0.0:4444
java.net.ConnectException: Connection refused: no further information: /0.0.0.0:4444
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /0.0.0.0:4444
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

 INFO [main] (DriverFactory.java:158)- Unable to establish websocket connection to http://0.0.0.0:4444/session/1e279201dd03013a535323381b5c07ea/se/cdp
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'LB080390', ip: '10.24.99.55', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: unknown--[org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:104), org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:137), org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:127), org.openqa.selenium.devtools.Connection.<init>(Connection.java:77), org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:34), org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$0(SeleniumCdpConnection.java:56), java.util.Optional.map(Optional.java:215), org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:54), org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:47), org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:48), org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:29), org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:186), org.openqa.selenium.remote.RemoteWebDriverBuilder.build(RemoteWebDriverBuilder.java:363), support.DriverFactory.createNewDriverInstance(DriverFactory.java:73), support.DriverFactory.initialize(DriverFactory.java:47), support.DriverFactory.<init>(DriverFactory.java:38), stepdefinitions.SetUpSteps.launchBrowser(SetUpSteps.java:56), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), io.cucumber.java.Invoker.doInvoke(Invoker.java:66), io.cucumber.java.Invoker.invoke(Invoker.java:24), io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47), io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:59), io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46), io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21), io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10), io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92), io.cucumber.core.runner.TestStep.run(TestStep.java:64), io.cucumber.core.runner.TestCase.run(TestCase.java:98), io.cucumber.core.runner.Runner.runPickle(Runner.java:73), io.cucumber.core.runtime.Runtime.lambda$execute$5(Runtime.java:110), io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117), io.cucumber.core.runtime.Runtime.lambda$execute$6(Runtime.java:110), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:233), java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112), io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:86), java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193), java.util.stream.SliceOps$1$1.accept(SliceOps.java:204), java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359), java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126), java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499), java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486), java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472), java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708), java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234), java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499), io.cucumber.core.runtime.Runtime.run(Runtime.java:87), io.cucumber.core.cli.Main.run(Main.java:92), io.cucumber.core.cli.Main.main(Main.java:34)]

Step failed
java.lang.AssertionError: Unable to establish websocket connection to http://0.0.0.0:4444/session/1e279201dd03013a535323381b5c07ea/se/cdp
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'LB080390', ip: '10.24.99.55', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: unknown
	at org.junit.Assert.fail(Assert.java:89)
	at support.DriverFactory.createNewDriverInstance(DriverFactory.java:159)
	at support.DriverFactory.initialize(DriverFactory.java:47)
	at support.DriverFactory.<init>(DriverFactory.java:38)
	at stepdefinitions.SetUpSteps.launchBrowser(SetUpSteps.java:56)
```

**This is the session information from the grid -** 
```
Session1e279201dd03013a535323381b5c07eaOS LogoBrowser Logov.95.0.4638.54
Capabilities:

{
  "acceptInsecureCerts": false,
  "browserName": "chrome",
  "browserVersion": "95.0.4638.54",
  "chrome": {
    "chromedriverVersion": "95.0.4638.17 (a9d0719444d4b035e284ed1fce73bf6ccd789df2-refs/branch-heads/4638@{#178})",
    "userDataDir": "C:\\Users\\a609923\\AppData\\Local\\Temp\\6\\scoped_dir9668_700246247"
  },
  "goog:chromeOptions": {
    "debuggerAddress": "localhost:50320"
  },
  "networkConnectionEnabled": false,
  "pageLoadStrategy": "normal",
  "platformName": "WINDOWS",
  "proxy": {},
  "se:cdp": "ws://0.0.0.0:4444/session/1e279201dd03013a535323381b5c07ea/se/cdp",
  "se:cdpVersion": "95.0.4638.54",
  "setWindowRect": true,
  "strictFileInteractability": false,
  "timeouts": {
    "implicit": 0,
    "pageLoad": 300000,
    "script": 30000
  },
  "unhandledPromptBehavior": "dismiss and notify",
  "webauthn:extension:credBlob": true,
  "webauthn:extension:largeBlob": true,
  "webauthn:virtualAuthenticators": true
}
```

**Any help would be great!**

**Comment by diemol** [comment]
@gog27771, there is no need to provide the exact same script you are using internally. We need any script that can help us to reproduce the issue using a public website (you can also use http://the-internet.herokuapp.com/).

**Comment by titusfortner** [comment]
It makes sense that you can initialize RemoteWebDriver without a problem, because it doesn't automatically augment the driver like RemoteWebDriverBuilder does, and the augmentation code is obviously the cause of this error.

I'm curious about what is coming back from: https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0/java/src/org/openqa/selenium/devtools/SeleniumCdpConnection.java#L60

Maybe the `se:cdp` capability isn't returning a valid value? I think this is available when looking at capabilities returned from normal driver initialization, so might be able to look at that. Also, like @diemol asked, are you sure sockets are open and available? But even then, it shouldn't break this, because I've run the builder on machines that don't have sockets open...

**Comment by gog27771** [comment]
@titusfortner, this is what is returned from ` Object cdp = capabilities.getCapability("se:cdp");` -

`ws://0.0.0.0:4444/session/626d325b8cacc44888e3c1ab1a6e6899/se/cdp`

**Comment by gog27771** [comment]
[EHAC.zip](https://github.com/SeleniumHQ/selenium/files/7418656/EHAC.zip)

@diemol @titusfortner I have uploaded a basic script that contains the error i am getting. I have previously sent my grid info here - https://github.com/SeleniumHQ/selenium/issues/9976#issuecomment-950182167

**Comment by shs96c** [comment]
The `0.0.0.0` should be a proper IP address. That won't be helping matters.

**Comment by gog27771** [comment]
Yes but im not sure why that is the case
