### ISSUE TITLE
[🐛 Bug]: Unable to cast RemoteWebDriver with HasLogEvents

### ISSUE THREAD

**Issue by aditya-qapitol** [SeleniumHQ/selenium#9989]
### What happened?

When creating a Chrome session via the Selenium Grid 4 the `RemoteWebdriver` is unable to call `onLogEvent` function present in the `HasLogEvents`.

### How can we reproduce the issue?

```shell
ChromeOptions chromeOptions = new ChromeOptions();
WebDriver driver=RemoteWebDriver.builder().address("https://localhost:4444").addAlternative(chromeOptions).build();
Augmenter augmenter = new Augmenter();
driver = augmenter.augment(driver);

AtomicReference<DomMutationEvent> seen = new AtomicReference<>();
CountDownLatch latch = new CountDownLatch(1);
((HasLogEvents) driver).onLogEvent(domMutation(mutation -> {
                seen.set(mutation);
                latch.countDown();
                System.out.println("CALLED setMutationObserver");
}));
```
```


### Relevant log output

```shell
Starting ChromeDriver 95.0.4638.17 (a9d0719444d4b035e284ed1fce73bf6ccd789df2-refs/branch-heads/4638@{#178}) on port 54433
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
01:22:36.461 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
01:22:36.512 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: 6f22ede5087c20495851ba842a983655, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 95.0.4638.54, chrome: {chromedriverVersion: 95.0.4638.17 (a9d0719444d4b..., userDataDir: C:\Users\UDAAN\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:57981}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: {}, se:cdp: ws://localhost:62864/sessio..., se:cdpVersion: 95.0.4638.54, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Oct 27, 2021 1:22:37 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found exact CDP implementation for version 95
01:22:37.413 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://localhost:57981/devtools/browser/db16502d-4a46-4c20-85f3-0775e0afc68d
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$zfgo1jMb cannot be cast to org.openqa.selenium.logging.HasLogEvents
	at com.qapitol.sauron.tests.Sel4LocalMutationTest.setMutationObserver(Sel4LocalMutationTest.java:98)
	at com.qapitol.sauron.tests.Sel4LocalMutationTest.test(Sel4LocalMutationTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

### Operating System

Windows 10

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95.0.4638.54

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 95.0.4638.17

### Are you using Selenium Grid?

4.0.0

**Comment by AutomatedTester** [comment]
@pujagani did I see you had a fix for this?

**Comment by pujagani** [comment]
Yes, the fix is part of https://github.com/SeleniumHQ/selenium/commit/a25ad324ea3dc0a3babda00b34d177a9ae66d51f. It will be available in the next release. Then the usage will be as shown in the example in the issue comment https://github.com/SeleniumHQ/selenium/issues/9934#issuecomment-948258463.
