### ISSUE TITLE
[🐛 Bug]: Relative locator fails when the root element is an inner element

### ISSUE THREAD

**Issue by ValorHeart** [SeleniumHQ/selenium#9991]
### What happened?

When the root element used to locate the new element from is found through another element, the relative locator fails to locate the new element.
I'm using Java.

### How can we reproduce the issue?

```shell
1. Look for container element and then look for inner element inside it (element.findElement...)
2. Use relative locator locating new element next to the inner element found at the first stage.
```

### Relevant log output

```shell
Caused by: org.openqa.selenium.json.JsonException: java.lang.reflect.InvocationTargetException
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'DESKTOP-JKEB3NF', ip: '192.168.10.85', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [2dc36142c232a3e869aa224f944095c4, findElement {using=relative, value={root={xpath=//p[contains(@class, 'FieldReadModeValue')]}, filters=[{kind=below, args=[[[[[ChromeDriver: chrome on ANY (2dc36142c232a3e869aa224f944095c4)] -> xpath: //div[contains(@class, 'form-wrapper')]]] -> xpath: //div[contains(@class, 'FieldLabel')]]]}]}}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 95.0.4638.54, chrome: {chromedriverVersion: 95.0.4638.17 (a9d0719444d4b...}, goog:chromeOptions: {debuggerAddress: localhost:3434}, javascriptEnabled: true, pageLoadStrategy: normal, platform: ANY, platformName: ANY, proxy: Proxy(), se:cdp: ws://localhost:3434/devtool..., se:cdpVersion: 95.0.4638.54, setWindowRect: false, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 2dc36142c232a3e869aa224f944095c4
	at org.openqa.selenium.json.SimplePropertyDescriptor.lambda$getPropertyDescriptors$1(SimplePropertyDescriptor.java:107)
	at org.openqa.selenium.json.JsonOutput.mapObject(JsonOutput.java:392)
	at org.openqa.selenium.json.JsonOutput.lambda$new$31(JsonOutput.java:207)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:287)
	at org.openqa.selenium.json.JsonOutput.mapObject(JsonOutput.java:395)
	at org.openqa.selenium.json.JsonOutput.lambda$new$31(JsonOutput.java:207)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:287)
	at org.openqa.selenium.json.JsonOutput.lambda$new$22(JsonOutput.java:169)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.json.JsonOutput.lambda$new$23(JsonOutput.java:169)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:287)
	at org.openqa.selenium.json.JsonOutput.lambda$new$24(JsonOutput.java:182)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at org.openqa.selenium.json.JsonOutput.lambda$new$25(JsonOutput.java:177)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:287)
	at org.openqa.selenium.json.JsonOutput.lambda$new$22(JsonOutput.java:169)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.json.JsonOutput.lambda$new$23(JsonOutput.java:169)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:287)
	at org.openqa.selenium.json.JsonOutput.lambda$new$24(JsonOutput.java:182)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at org.openqa.selenium.json.JsonOutput.lambda$new$25(JsonOutput.java:177)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:287)
	at org.openqa.selenium.json.JsonOutput.lambda$new$24(JsonOutput.java:182)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at org.openqa.selenium.json.JsonOutput.lambda$new$25(JsonOutput.java:177)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:287)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:278)
	at org.openqa.selenium.json.Json.toJson(Json.java:42)
	at org.openqa.selenium.remote.codec.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:259)
	at org.openqa.selenium.remote.codec.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:127)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:172)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:383)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:375)
	at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:115)
	at com.sun.proxy.$Proxy19.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:204)
	at plainid.auto.infra.web.SeleniumBot.lambda$getElementBelow$14(SeleniumBot.java:307)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	... 35 more
	Suppressed: org.openqa.selenium.json.JsonException: Attempting to close incomplete json stream
```

### Operating System

Windows 10

### Selenium version

4.00

### What are the browser(s) and version(s) where you see this issue?

Chrome 95

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 95

**Comment by AutomatedTester** [comment]
As requested in the form, can we have steps to reproduce.

**Comment by ValorHeart** [comment]
When i've tried to create an reproduce example with simple system it worked, as i can't share the system i'm working on because it's work place system it's a problematic for me to supply the reproduce environment which it gives me an issues at.
i'll close it for now, as it works on the simple website and will re-check my work on my complex system.
thanks.
