### ISSUE TITLE
[🐛 Bug]: Webdriver doesn't accept "service" keyword, but executable_path is deprecated

### ISSUE THREAD

**Issue by jtommi** [SeleniumHQ/selenium#9992]
### What happened?

I'm trying to create a webdriver by specifying the executable path like so
```
driver = webdriver.Chrome(
                executable_path="/home/user/.local/bin/chromedriver", options=options
            )
```
This results in "DeprecationWarning: executable_path has been deprecated, please pass in a Service object"

So I tried passing in a service object:
```
chrome_service = Service(executable_path="/home/user/.local/bin/chromedriver")
driver = webdriver.Chrome(service=chrome_service, options=options)

```
This resulted in TypeError: __init__() got an unexpected keyword argument 'service'

### How can we reproduce the issue?

```shell
chrome_service = Service(executable_path="/home/user/.local/bin/chromedriver")
driver = webdriver.Chrome(service=chrome_service, options=options)

```
```


### Relevant log output

```shell
DeprecationWarning: executable_path has been deprecated, please pass in a Service object
TypeError: __init__() got an unexpected keyword argument 'service'
```

### Operating System

WSL2 Ubuntu 20.04.3 LTS (on Windows 10)

### Selenium version

Python 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 95 (didn't try others)

### Are you using Selenium Grid?

Not intentionally at least

**Comment by AutomatedTester** [comment]
I've tried to recreate this issue and can't. I don't have my chromedriver in your location but used your example

```bash
davidburns in ~/development/selenium on trunk ● λ python3
Python 3.9.4 (default, Apr  5 2021, 01:50:46) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
w>>> webdriver.__version__
'4.0.0'
>>> from selenium.webdriver.chrome.service import Service
>>> chrome_service = Service(executable_path="/home/user/.local/bin/chromedriver")
>>> from selenium.webdriver.chrome.options import Options
>>> options = Options()
>>> driver=webdriver.Chrome(service=chrome_service, options=options)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/bin/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 84, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
```

**Comment by jtommi** [comment]
I don't get it, I can't reproduce it either, using the same script (git versioned, so I know it didn't change), the same virtual environment.
Thanks for giving it a try and sorry for wasting your time

**Comment by jtommi** [comment]
PEBCAK
I called the script from Airflow where I was using one venv, and when testing directly on the machine, I was using a different venv, one had v3, the other v4.
